### ISSUE TITLE
[PRE REVIEW]: A flexible search system for high-accuracy identification of biological entities and molecules

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3717]
**Submitting author:** @maxkfranz (<a href="http://orcid.org/0000-0003-0169-0480">Max Franz</a>)
**Repository:** <a href="https://github.com/PathwayCommons/grounding-search" target ="_blank">https://github.com/PathwayCommons/grounding-search</a>
**Version:** 0.6.0
**Editor:** @galessiorob
**Reviewers:** @AlexanderPico, @rabdill
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/dfad3b1bc874b0f813f6814723a646f5/status.svg)](https://joss.theoj.org/papers/dfad3b1bc874b0f813f6814723a646f5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dfad3b1bc874b0f813f6814723a646f5"><img src="https://joss.theoj.org/papers/dfad3b1bc874b0f813f6814723a646f5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dfad3b1bc874b0f813f6814723a646f5/status.svg)](https://joss.theoj.org/papers/dfad3b1bc874b0f813f6814723a646f5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @maxkfranz. **Currently, there isn't an JOSS editor assigned** to your paper.

@maxkfranz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1810

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.03 s (62.2 files/s, 111925.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              0              0          93209
JSON                             9              0              0          13084
JavaScript                      46            651            600           7031
Markdown                         2             89              0            254
TeX                              1             12              0            119
YAML                             2              2              0             47
Dockerfile                       1              9             11             13
Bourne Shell                     1              4              1             11
-------------------------------------------------------------------------------
SUM:                            64            767            612         113768
-------------------------------------------------------------------------------


Statistical information for the repository 'e5293c12ec645182cd108def' was
gathered on 2021/09/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christian Dallago                1             1              1            0.01
Jeffrey Wong                    50          1575            454            7.83
Max Franz                       78          6134           1702           30.23
jvwong                          11          5653           5621           43.50
metincansiper                   44          3681           1089           18.40
user                             1             4              2            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christian Dallago             1          100.0         21.2                0.00
Max Franz                  4831           78.8         18.7                4.62
jvwong                     1278           22.6          5.0                7.98
metincansiper              2171           59.0         21.0               12.67
user                          1           25.0         22.6                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03717/joss.03717/10.21105.joss.03717.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03717/joss.03717/10.21105.joss.03717.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1101/2021.03.10.382333 may be a valid DOI for title: Capturing scientific knowledge in computable form
- 10.1093/nar/gkq1039 may be a valid DOI for title: Pathway Commons, a web resource for biological pathway data
- 10.1038/npre.2009.3212.1 may be a valid DOI for title: Reflect: augmented browsing for the life scientist
- 10.1093/bioinformatics/btn424 may be a valid DOI for title: The Synergizer service for translating gene, protein and other biological identifiers
- 10.1093/nar/gkg034 may be a valid DOI for title: STRING: a database of predicted functional associations between proteins
- 10.1186/gb-2008-9-s1-s4 may be a valid DOI for title: GeneMANIA: a real-time multiple association network integration algorithm for predicting gene function
- 10.1093/nar/gkm226 may be a valid DOI for title: g: Profiler—a web-based toolset for functional profiling of gene lists from large-scale experiments
- 10.1186/1471-2105-8-401 may be a valid DOI for title: The Protein Identifier Cross-Referencing (PICR) service: reconciling protein identifiers across multiple source databases
- 10.1093/nar/gkr1097 may be a valid DOI for title: Identifiers. org and MIRIAM Registry: community resources to provide persistent identification
- 10.1101/2021.03.30.437702 may be a valid DOI for title: Gene name errors: lessons not learned
- 10.1093/nar/gki031 may be a valid DOI for title: Entrez Gene: gene-centered information at NCBI

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@maxkfranz thanks for this submission. I will be looking for a handling editor for this work. In the mean time can you work on fixing those references :point_up:. You can call `@whedon generate pdf` here to update the paper and call `@whedon check references` to check those DOI's. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@galessiorob do you think you could edit this work? The editors in the domain of bioinformatics are currently handling many other submissions. Let me know if this works fits well enough with your data science background. Thanks

**Comment by maxkfranz** [comment]
The [suggested DOIs](https://github.com/openjournals/joss-reviews/issues/3717#issuecomment-917360026) look correct to me.  Thanks

@whedon check references

**Comment by galessiorob** [comment]
@Kevin-Mattheus-Moerman Happy to take this one!

@maxkfranz I'll start reaching out to [potential reviewers](https://bit.ly/joss-reviewers), but if you have any specific suggestions feel free to ping them here.

**Comment by galessiorob** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1101/2021.03.10.382333 may be a valid DOI for title: Capturing scientific knowledge in computable form
- 10.1093/nar/gkq1039 may be a valid DOI for title: Pathway Commons, a web resource for biological pathway data
- 10.1038/npre.2009.3212.1 may be a valid DOI for title: Reflect: augmented browsing for the life scientist
- 10.1093/bioinformatics/btn424 may be a valid DOI for title: The Synergizer service for translating gene, protein and other biological identifiers
- 10.1093/nar/gkg034 may be a valid DOI for title: STRING: a database of predicted functional associations between proteins
- 10.1186/gb-2008-9-s1-s4 may be a valid DOI for title: GeneMANIA: a real-time multiple association network integration algorithm for predicting gene function
- 10.1093/nar/gkm226 may be a valid DOI for title: g: Profiler—a web-based toolset for functional profiling of gene lists from large-scale experiments
- 10.1186/1471-2105-8-401 may be a valid DOI for title: The Protein Identifier Cross-Referencing (PICR) service: reconciling protein identifiers across multiple source databases
- 10.1093/nar/gkr1097 may be a valid DOI for title: Identifiers. org and MIRIAM Registry: community resources to provide persistent identification
- 10.1101/2021.03.30.437702 may be a valid DOI for title: Gene name errors: lessons not learned
- 10.1093/nar/gki031 may be a valid DOI for title: Entrez Gene: gene-centered information at NCBI

INVALID DOIs

- None
```

**Comment by galessiorob** [comment]
@maxkfranz if the suggested DOIs look good you can start adding them to the actual doc.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by maxkfranz** [comment]
> @maxkfranz if the suggested DOIs look good you can start adding them to the actual doc.

I thought this was automatic.  Assuming you mean the bib file, I'll amend that.  Thanks

> @maxkfranz I'll start reaching out to potential reviewers, but if you have any specific suggestions feel free to ping them here.

Here are some suggestions:

- John Bachman @johnbachman
- Ben Gyori https://scholar.harvard.edu/bgyori/home
- Alex Pico @AlexanderPico
- Andrew Su @andrewsu
- Scooter Morris @scootermorris

**Comment by maxkfranz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2021.03.10.382333 is OK
- 10.1093/nar/gkq1039 is OK
- 10.15252/msb.20177651 is OK
- 10.1038/npre.2009.3212.1 is OK
- 10.1093/bioinformatics/btn424 is OK
- 10.1093/nar/gkg034 is OK
- 10.1186/gb-2008-9-s1-s4 is OK
- 10.1093/nar/gkm226 is OK
- 10.1186/1471-2105-8-401 is OK
- 10.1093/nar/gkr1097 is OK
- 10.1101/2021.03.30.437702 is OK
- 10.1093/nar/gki031 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by galessiorob** [comment]
@whedon add @AlexanderPico as reviewer

**Comment by whedon** [comment]
OK, @AlexanderPico is now a reviewer

**Comment by maxkfranz** [comment]
Other potential reviewers:

- Martina Summer-Kutmon https://www.maastrichtuniversity.nl/martina.kutmon
- Avi Ma'ayan https://github.com/AviMaayan
- Guanming Wu https://ohsu.pure.elsevier.com/en/persons/guanming-wu

**Comment by galessiorob** [comment]
Thanks for the suggestions @maxkfranz, I have sent invites to all of them. I'll wait a few days for them to respond and as soon as we have at least two assigned reviewers we can start the process.

**Comment by maxkfranz** [comment]
Thanks, @galessiorob

**Comment by galessiorob** [comment]
@whedon add @rabdill as reviewer

**Comment by whedon** [comment]
OK, @rabdill is now a reviewer

**Comment by galessiorob** [comment]
🎉 Thanks for volunteering to be reviewers @AlexanderPicoand @rabdill!

I'll generate a "review issue" that will contain individual checklists to go through, feel free to get started at your earliest convenience, don't hesitate to ask if you need clarification or help - you can @mention me directly on the issue.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3756.
