### ISSUE TITLE
[REVIEW]: Go-HEP: libraries for High Energy Physics analyses in Go

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#372]
**Submitting author:** @sbinet (<a href="http://orcid.org/0000-0003-4913-6104">Sebastien Binet</a>)
**Repository:** <a href="https://github.com/go-hep/hep" target ="_blank">https://github.com/go-hep/hep</a>
**Version:** v0.4
**Editor:** @arfon
**Reviewer:** @jpivarski
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.887895" target="_blank">10.5281/zenodo.887895</a>

## Status

[![status](http://joss.theoj.org/papers/0b007c81073186f7c61f95ea26ad7971/status.svg)](http://joss.theoj.org/papers/0b007c81073186f7c61f95ea26ad7971)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0b007c81073186f7c61f95ea26ad7971"><img src="http://joss.theoj.org/papers/0b007c81073186f7c61f95ea26ad7971/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0b007c81073186f7c61f95ea26ad7971/status.svg)](http://joss.theoj.org/papers/0b007c81073186f7c61f95ea26ad7971)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/go-hep/hep" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@jpivarski, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/go-hep/hep">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4)?
- [x] **Authorship:** Has the submitting author (@sbinet) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jpivarski it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by jpivarski** [comment]
What are the deadlines for this review (rough or strict)? I need to schedule it in with other activities.

**Comment by arfon** [comment]
> What are the deadlines for this review (rough or strict)? I need to schedule it in with other activities.

Ideally in the next couple of weeks. We don't have strict deadlines.

**Comment by jpivarski** [comment]
I don't think the `LICENSE` file is sufficient. It claims copyright and states terms for redistribution, but (not being a lawyer) I don't know if that covers the full terms of an [OSI license](https://opensource.org/licenses/alphabetical). Just pick a common one (ASF2, BSD, MIT).

Still going through the other steps, from top to bottom of the checklist...

**Comment by jpivarski** [comment]
Nevermind! I see on [https://go-hep.org/](go-hep.org) that it's licensed under BSD-3, so I was about to say, "copy-paste the text of a BSD-3" license, but that's exactly what he did. It just happens to be very short.

So the license is fine.

**Comment by jpivarski** [comment]
Installation _seemed_ to go without problems. I'm not getting error messages from the import statement, so I think I can check off that box.

**Comment by jpivarski** [comment]
There are clearly automated tests because Travis finds them, but I can't find them. The `.travis.yml` is so basic they must be in the standard place for Go, but I don't know what that is. Based on the fact that I see clear and detailed Travis reports, I'm going to check this box.

**Comment by sbinet** [comment]
yes, travis knows how Go tests are run.

if you want to run them by hand:

```sh
$> cd $GOPATH/src/go-hep.org/x/hep
$> go test -v ./...
```

(yes, with the `...` ellipsis at the end: this instructs the Go toolchain to recurse and traverse all the tree under the current working directory)

**Comment by jpivarski** [comment]
There's also clear community support guidelines and good API documentation.

However, I'm not able to find any tutorials for getting started. I picked x/hep/rootio as a starting point (my primary interest) and I can't get it to work. I'll submit an issue and see what happens.

**Comment by sbinet** [comment]
Go has a nice "examples" feature that is leveraged by the documentation presentation tool, godoc.

Examples for a type inside a package are _e.g._ here:

- https://godoc.org/go-hep.org/x/hep/rootio#pkg-examples

**Comment by sbinet** [comment]
and if you want to run benchmarks:

```
$> cd rootio
$> go test -v -run=NONE -bench=. -benchmem -count=5 .
goos: linux
goarch: amd64
pkg: go-hep.org/x/hep/rootio
BenchmarkTreeScannerStruct-4              	  100000	     17515 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerStruct-4              	  100000	     17521 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerStruct-4              	  100000	     17437 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerStruct-4              	  100000	     17514 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerStruct-4              	  100000	     17562 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerStruct-4                  	  200000	      6209 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerStruct-4                  	  200000	      6253 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerStruct-4                  	  200000	      6257 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerStruct-4                  	  200000	      6257 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerStruct-4                  	  200000	      6226 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerVars-4                	  100000	     15960 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerVars-4                	  100000	     15952 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerVars-4                	  100000	     15961 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerVars-4                	  100000	     15913 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerVars-4                	  100000	     16182 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerVars-4                    	  200000	      6116 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerVars-4                    	  200000	      6138 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerVars-4                    	  200000	      6169 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerVars-4                    	  200000	      6117 ns/op	       0 B/op	       0 allocs/op
BenchmarkScannerVars-4                    	  200000	      6113 ns/op	       0 B/op	       0 allocs/op
BenchmarkTreeScannerVarsBigFileScalar-4   	     100	  22425657 ns/op	  505110 B/op	  125000 allocs/op
BenchmarkTreeScannerVarsBigFileScalar-4   	     100	  22302968 ns/op	  505110 B/op	  125000 allocs/op
BenchmarkTreeScannerVarsBigFileScalar-4   	     100	  22443355 ns/op	  505111 B/op	  125000 allocs/op
BenchmarkTreeScannerVarsBigFileScalar-4   	     100	  22367911 ns/op	  505110 B/op	  125000 allocs/op
BenchmarkTreeScannerVarsBigFileScalar-4   	     100	  22492822 ns/op	  505110 B/op	  125000 allocs/op
BenchmarkScannerVarsBigFileScalar-4       	     200	   7702788 ns/op	    2554 B/op	       0 allocs/op
BenchmarkScannerVarsBigFileScalar-4       	     200	   7749957 ns/op	    2554 B/op	       0 allocs/op
BenchmarkScannerVarsBigFileScalar-4       	     200	   7706357 ns/op	    2554 B/op	       0 allocs/op
BenchmarkScannerVarsBigFileScalar-4       	     200	   7651564 ns/op	    2554 B/op	       0 allocs/op
BenchmarkScannerVarsBigFileScalar-4       	     200	   7662549 ns/op	    2554 B/op	       0 allocs/op
BenchmarkTreeScannerVarsBigFileSlice-4    	      30	  41926597 ns/op	 5834710 B/op	  375033 allocs/op
BenchmarkTreeScannerVarsBigFileSlice-4    	      30	  40863289 ns/op	 5834708 B/op	  375033 allocs/op
BenchmarkTreeScannerVarsBigFileSlice-4    	      30	  41548413 ns/op	 5834724 B/op	  375034 allocs/op
BenchmarkTreeScannerVarsBigFileSlice-4    	      30	  41602640 ns/op	 5834708 B/op	  375033 allocs/op
BenchmarkTreeScannerVarsBigFileSlice-4    	      30	  41578124 ns/op	 5834720 B/op	  375033 allocs/op
BenchmarkScannerVarsBigFileSlice-4        	     100	  20647574 ns/op	 1287076 B/op	  157616 allocs/op
BenchmarkScannerVarsBigFileSlice-4        	     100	  20287316 ns/op	 1287075 B/op	  157616 allocs/op
BenchmarkScannerVarsBigFileSlice-4        	     100	  20401387 ns/op	 1287077 B/op	  157616 allocs/op
BenchmarkScannerVarsBigFileSlice-4        	     100	  20292135 ns/op	 1287076 B/op	  157616 allocs/op
BenchmarkScannerVarsBigFileSlice-4        	     100	  20671081 ns/op	 1287075 B/op	  157616 allocs/op
PASS
ok  	go-hep.org/x/hep/rootio	79.667s
```

`count=5` is to run each benchmark 5 times (to estimate std-err).

another tool [benchstat](https://godoc.org/rsc.io/benchstat) understands the output format of `go test -bench` and can extract meaningful statistics:

```
$> go get rsc.io/benchstat
$>  benchstat ./foo.txt 
name                            time/op
TreeScannerStruct-4             17.5µs ± 0%
ScannerStruct-4                 6.24µs ± 1%
TreeScannerVars-4               15.9µs ± 0%
ScannerVars-4                   6.13µs ± 1%
TreeScannerVarsBigFileScalar-4  22.4ms ± 0%
ScannerVarsBigFileScalar-4      7.69ms ± 1%
TreeScannerVarsBigFileSlice-4   41.5ms ± 2%
ScannerVarsBigFileSlice-4       20.5ms ± 1%

name                            alloc/op
TreeScannerStruct-4              0.00B     
ScannerStruct-4                  0.00B     
TreeScannerVars-4                0.00B     
ScannerVars-4                    0.00B     
TreeScannerVarsBigFileScalar-4   505kB ± 0%
ScannerVarsBigFileScalar-4      2.55kB ± 0%
TreeScannerVarsBigFileSlice-4   5.83MB ± 0%
ScannerVarsBigFileSlice-4       1.29MB ± 0%

name                            allocs/op
TreeScannerStruct-4               0.00     
ScannerStruct-4                   0.00     
TreeScannerVars-4                 0.00     
ScannerVars-4                     0.00     
TreeScannerVarsBigFileScalar-4    125k ± 0%
ScannerVarsBigFileScalar-4        0.00     
TreeScannerVarsBigFileSlice-4     375k ± 0%
ScannerVarsBigFileSlice-4         158k ± 0%
```

(and `benchstat` can compare 2 files and thus provide p-values between 2 sets of benchmarks)

**Comment by jpivarski** [comment]
I only needed a little orientation, so I'm going to say, "yes" to documentation. What I needed was there, I just couldn't find it. "Yes" to functionality because I could run it over one of my own data files (though I didn't do a comprehensive study, just a simple example).

And finally, "yes" to performance. Again, I haven't done a systematic study and my laptop has a weird configuration (no L3 cache in my CPU). However, I found go-hep/rootio to be only 25% slower than C++ ROOT on a normal, compressed file and _twice as fast as C++_ on an uncompressed file.

Hint, hint to the authors: include uncompressed files in your tests! Maybe you're only slow because the Go zlib is slow, and when you remove that, you expose a lower overhead in entry handling than `TTree::GetEntry`. ROOT is moving to LZ4 compression (by default), which is much faster than zlib, so this might not matter, as long as you can get LZ4 in Go.

**Comment by jpivarski** [comment]
Only a few checkboxes left: statement of need. The go-hep/hep README doesn't say why you might need such a thing. I think you can make an argument for it in one or two sentences.

Also, I don't remember where `paper.md` is. Could you point me to it again?

The ROOT team is in flux about what DOI they want to represent ROOT, now that there are options for referencing software, rather than just papers. Traditionally, the correct reference is their 1997 paper.

**Comment by sbinet** [comment]
`paper.md` is in that PR: go-hep/hep#88.
https://github.com/go-hep/hep/pull/88/files

**Comment by jpivarski** [comment]
The `paper.md` has a good statement of need. I'd say copy-paste a lot of that text into the README— it's a good introduction to the purpose of this project.

The ROOT reference you have is from 2009. It looks relevant, but I'm pretty sure they have a preference for the 1997 one, just so that they can count references.

**Comment by jpivarski** [comment]
It's a 1996 paper:

  - [https://root-forum.cern.ch/t/roots-references-in-a-paper/14638](https://root-forum.cern.ch/t/roots-references-in-a-paper/14638)
  - bottom of [https://root.cern.ch/root/Publications.html](https://root.cern.ch/root/Publications.html)

**Comment by sbinet** [comment]
PTAL.

- https://github.com/go-hep/hep/pull/88/commits/d438a0801e59aedb618a87a751d0bab111cf8e96 (ROOT paper)
- https://github.com/go-hep/hep/pull/88/commits/936377e5f7dd9586bc0e46d237893027ce20609f (add motivations to `README`)

**Comment by sbinet** [comment]
also: @jpivarski  actually reviewed (implicitly) `master` which is more or less what `v0.5` is. (I tagged it at the beginning of this week.)

assuming the review process is successful, wouldn't it make sense for me to cut a new release (`v0.6`) and update openjournals/joss-reviews#372 to point at it? (it currently refers to `v0.4`).

**Comment by jpivarski** [comment]
Nothing I checked was 0.4 specific, in fact "go get go-hep" got the latest master. (You might want to change that to the latest _release_, if possible.) I concur that the JOSS stamp should be on v0.5 or a new v0.6. There are release notes about fixes to the module I was testing in 0.5.

Also, I think I'm done with the review. It was a lot easier than I thought. I'm going to "close" this issue because I think it's done.

Congratulations! It's nice software! (And benchmark it on some uncompressed files!)

**Comment by sbinet** [comment]
> Congratulations! It's nice software! (And benchmark it on some uncompressed files!)
thanks! (and thanks for the tip: in my ACAT paper, I was actually quoting compressed and uncompressed perf numbers. I'll send a PR against [jblomer/iotools](https://github.com/jblomer/iotools) repo to get some "official" benchmark numbers.)

@jpivarski @arfon : is there anything else left to do on my side? apart from merging my `joss-paper` branch into `master` and tag `v0.6` ?

**Comment by jpivarski** [comment]
Okay, so I'm not supposed to close it. Awaiting further instruction.

**Comment by arfon** [comment]
> Okay, so I'm not supposed to close it. Awaiting further instruction.

👍 thanks for being proactive by we don't close the issues until we've accepted the paper.

**Comment by arfon** [comment]
@sbinet - it looks like Pandoc can't find a couple of the references - could you take a look?

```
pandoc-citeproc: reference ROOT not found
pandoc-citeproc: reference Go not found
```

**Comment by sbinet** [comment]
PTAL @arfon 

oops... should be ok now.

**Comment by arfon** [comment]
OK thanks. This is now looking good.

@sbinet - At this point could you merge the `joss-paper` branch into `master` and tag `v0.6`. Then please make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by sbinet** [comment]
- `joss-paper` merged into `master`: `[DONE]`
- tag `v0.6`: `[DONE]`
- DOI: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.887895.svg)](https://doi.org/10.5281/zenodo.887895)

thanks! :)

**Comment by sbinet** [comment]
(not sure @arfon does see updates here... apologies for the ping)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.887895 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.887895" target="_blank">10.5281/zenodo.887895</a> is the archive.

**Comment by arfon** [comment]
@jpivarski - many thanks for your review here ✨ 

@sbinet - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00372 ⚡️ 🚀 💥
