### ISSUE TITLE
[PRE REVIEW]: CategoricalTimeSeries.jl: A toolbox for categorical time-series analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3720]
**Submitting author:** @johncwok (<a href="http://orcid.org/0000-0001-6266-5575">Corentin  Nelias</a>)
**Repository:** <a href="https://github.com/johncwok/CategoricalTimeSeries.jl" target ="_blank">https://github.com/johncwok/CategoricalTimeSeries.jl</a>
**Version:** 1.0.0
**Editor:** @jbytecode
**Reviewers:** @bkamins, @felixcremer
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e/status.svg)](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e"><img src="https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e/status.svg)](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @johncwok. **Currently, there isn't an JOSS editor assigned** to your paper.

@johncwok if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 784

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (525.4 files/s, 136060.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              1              0              0           2671
JavaScript                       6            473           1213           2025
Julia                            8            183             17           1301
HTML                             7            272             18            950
Markdown                         8            134              0            513
CSS                              2             16             67             71
TeX                              1              8              0             65
YAML                             3             11              2             53
TOML                             1              5              0             20
XML                              1              0              0             11
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            39           1102           1317           7681
-------------------------------------------------------------------------------


Statistical information for the repository 'ba0299fa7fab93bc7c126dce' was
gathered on 2021/09/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Corentin Nelias                  1          3711              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Corentin Nelias            3711          100.0          0.0               32.69
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK

MISSING DOIs

- 10.1093/biomet/80.3.611 may be a valid DOI for title: Spectral analysis for categorical time series: Scaling and the spectral envelope
- 10.1145/369133.369172 may be a valid DOI for title: Finding motifs using random projections
- 10.1162/neco_a_00961 may be a valid DOI for title: The deterministic information bottleneck

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@johncwok thanks for this submission. I will be looking for a handling editor for this work. In the mean time can you work on fixing those references :point_up:. You can call `@whedon generate pdf` here to update the paper and call `@whedon check references` to check those DOI's. Thanks.

**Comment by johncwok** [comment]
@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: :point_left:

**Comment by johncwok** [comment]
Dear Kevin, I checked the existing DOIs and added the missing ones.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1.1.91.5339 is INVALID
- 10.1.1.6.9199 is INVALID
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@johncwok it looks like two still need some work, perhaps they need /..... FYI you can also run these commands I just ran yourself.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @jbytecode as editor

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
Dear @johncwok 

You can use the site https://whedon.theoj.org/ to compile your paper and bibtex and then you can let the whedon dump the latest version here.

Do you have any suggestions for potential reviewers?  If yes, please mention them here in this thread (without tagging them with an @ - we don't want to disturb them). In addition, this [list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
 
In case you are unable to create a suitable list of referees, I will create one for you.

Thank you in advance.

**Comment by jbytecode** [comment]
@johncwok a small tip before inviting reviewers:

In tests of your package, it is a good practice to divide tests into categories like 

```julia
@testset "integerIB"
    @test ..... 
end
```

instead of commenting like 

```julia
#testing integerIB
@test ....
```

**Comment by johncwok** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by johncwok** [comment]
@jbytecode I will have a look at potential reviewers this evening, and make test sets. Thanks for the feedback.
I have another question: one of the papers I have in the references (The information bottleneck) doesn't seem to have a DOI. Is it an issue?

**Comment by jbytecode** [comment]
it seems it is an unpublished one and I couldn't find a crossref entry either.
you can leave it as is.

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: :point_left:

**Comment by johncwok** [comment]
Looking at the list (from the bottom), I think these people might be adapted referees:
jiweiqi, metelkin, papachristoumarios

**Comment by jbytecode** [comment]
👋👋👋 Dear @jiweiqi, @metelkin, and @felixcremer   👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_CategoricalTimeSeries.jl: A toolbox for categorical time-series analysis_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3720).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jiweiqi** [comment]
Hi @jbytecode , thanks for your invitation. This package looks cool. However, I am not an expert in analyzing categorical time series (instead I am more familiar with dynamic systems with continuous variable). I would suggest someone else in this field review this paper. Thanks again and I am happy to involve in the future review processes.

**Comment by jbytecode** [comment]
Dear @jiweiqi, thank you for the quick response. Hope we will work together in later submissions. Who is your suggestion? Could you please mention the github id here without an @ symbol? 
Thank you in advance!

**Comment by johncwok** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03720/joss.03720/10.21105.joss.03720.pdf) :page_facing_up: :point_left:

**Comment by jiweiqi** [comment]
> Dear @jiweiqi, thank you for the quick response. Hope we will work together in later submissions. Who is your suggestion? Could you please mention the github id here without an @ symbol?
> Thank you in advance!

Hi, I would recommend https://github.com/bkamins

**Comment by jbytecode** [comment]
Dear @bkamins  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_CategoricalTimeSeries.jl: A toolbox for categorical time-series analysis_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3720).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by bkamins** [comment]
Hi, I can review it. I have one question and two comments.

The question is: what exactly should I review (code, documentation, the article proof)?

The comments are:
* it would be great to review the package against some release of it. Currently I do not see any releases nor tags for this package.
* the current state of the package when added to an environment does not allow latest version of DataFrames.jl to be installed. It restricts it to 0.19 release. I think it would be good to try to fix that.

Thank you!

**Comment by jbytecode** [comment]
> Hi, I can review it. I have one question and two comments.
> 
> The question is: what exactly should I review (code, documentation, the article proof)?

@bkamins, Thank you for the reply. When the review starts, there will be 20 checkboxes for each reviewer that indicate the corresponding  review item including the software, the paper, and the documentation. If you accept, I will be here to help you anytime. 

> 
> The comments are:
> 
> * it would be great to review the package against some release of it. Currently I do not see any releases nor tags for this package.
> * the current state of the package when added to an environment does not allow latest version of DataFrames.jl to be installed. It restricts it to 0.19 release. I think it would be good to try to fix that.
> 

Since these are about reviewing, you will be able to interact with the author(s) and list a reviewing report during the process. This process will start whenever we set at least two reviewers for the submission.
> Thank you!


Does this answers fit your questions?

**Comment by johncwok** [comment]
Dear bkamins,

might I ask what you mean by release? The package was added to the julia registry some 10 months ago (https://github.com/JuliaRegistries/General/tree/master/C/CategoricalTimeSeries).
I am a bit puzzled by the restrictions on the version of dataframes, since I didn't explicitly enforce any. I tried to explicitly make it work for later release, I hope this will fix it.

**Comment by bkamins** [comment]
> do these answers fit your questions?

So I wait for the second reviewer. Right?

> might I ask what you mean by release?

In https://github.com/JuliaRegistries/General/blob/master/C/CategoricalTimeSeries/Versions.toml you only have:
```
["0.1.0"]
git-tree-sha1 = "62468caf4b35c78a97dc7a5be9ea068a1f731a27"
```
while in your repo in https://github.com/johncwok/CategoricalTimeSeries.jl/blob/main/Project.toml you currently have:
```
name = "CategoricalTimeSeries"
uuid = "f5116226-a574-5b1a-a4a4-91edc520f498"

authors = ["Corentin Nelias <cwokpoubelle@laposte.net>"]
version = "1.0.0"
```
so as you can see the versions are inconsistent. And there is no tag for 0.1 release on your repository.
Normally it is recommended to make a tag and a release on GitHub for each version of the package.

> I am a bit puzzled by the restrictions on the version of dataframes

The reason is that in IntegerIB.jl in https://github.com/johncwok/IntegerIB.jl/blob/master/Project.toml you have:
```
[compat]
julia = "^1.0"
DataFrames = "^0.19"
```
which disallows latest version of DataFrames.jl.

---

In general I would recommend - as for the reviewed packages to make proper releases also for all packages that the reviewed package depends on as e.g. IntegerIB.jl does not have a proper release either.

To be clear, as is explained here https://github.com/JuliaRegistries/Registrator.jl/#note-on-git-tags-and-github-releases Julia package manager does not depend on GitHub tags, however, this is a good practice to have them and properly manage releases on GitHub (as users will normally check them when using your package). You can have a look at DataFrames.jl as an example how it looks like when this process is followed here: https://github.com/JuliaData/DataFrames.jl/releases.

The reason is that currently when you install your packages Julia installs some very old version of it (almost a year old) and not what is in `main` branch, as it currently uses the `62468caf4b35c78a97dc7a5be9ea068a1f731a27` git-tree-sha1 as a reference what should be installed (and it is dated Oct 28, 2020).

**Comment by jbytecode** [comment]
@whedon add @bkamins as reviewer

@bkamins yes, you are assigned as the first reviewer. When we set the second one, a new issue will be created. You can review the paper in there. 

Thank you!

**Comment by whedon** [comment]
OK, @bkamins is now a reviewer

**Comment by jbytecode** [comment]
👋👋👋 Dear  @papachristoumarios  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_CategoricalTimeSeries.jl: A toolbox for categorical time-series analysis_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3720).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
👋👋👋 Dear  @daviddewhurst  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_CategoricalTimeSeries.jl: A toolbox for categorical time-series analysis_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3720).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by felixcremer** [comment]
Dear @jbytecode, 

I would be willing to review this submission, but I can only start doing the review two weeks from now. 

Is it a conflict of interest, that I and the main author are both employed by the Max-Planck-Society? 
We are on different institutes and haven't met each other.

**Comment by arfon** [comment]
> Is it a conflict of interest, that I and the main author are both employed by the Max-Planck-Society?
> We are on different institutes and haven't met each other.

Thank you for disclosing this @felixcremer. We are happy to waive this possible conflict (i.e., we are happy to have you as a reviewer!).

**Comment by jbytecode** [comment]
@whedon add @felixcremer as reviewer

Thank you @felixcremer, it is not a problem to wait until you are available. This deadline is reasonable for us. Thank you for accepting our invitation.

**Comment by whedon** [comment]
OK, @felixcremer is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3733.
