### ISSUE TITLE
[PRE REVIEW]: GiNaCDE: the high-performance F-expansion and First Integral Methods with C++ library for solving Nonlinear Differential Equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3721]
**Submitting author:** @mithun218 (<a href="http://orcid.org/0000-0002-9678-4625">Mithun Bairagi</a>)
**Repository:** <a href="https://github.com/mithun218/GiNaCDE" target ="_blank">https://github.com/mithun218/GiNaCDE</a>
**Version:** v1.0.0
**Editor:** @meg-simula
**Reviewers:** @peanutfun, @carstenbauer
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665/status.svg)](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665"><img src="https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665/status.svg)](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mithun218. **Currently, there isn't an JOSS editor assigned** to your paper.

@mithun218 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 962

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (433.4 files/s, 136644.3 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
C++                                 24           2117            729           8719
TeX                                  2            144             15            925
C/C++ Header                        11            217            106            642
CMake                                3             54             64            219
Markdown                             3             47              0            167
YAML                                 1              1              4             18
Windows Resource File                1              0              0              1
-----------------------------------------------------------------------------------
SUM:                                45           2580            918          10691
-----------------------------------------------------------------------------------


Statistical information for the repository '50ef42e6afd55c37d5444ce8' was
gathered on 2021/09/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mithun218                        1         12819              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mithun218                 12819          100.0          0.0                6.56
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1155/2013/104894 is OK
- 10.1016/j.chaos.2005.10.007 is OK
- 10.1016/S0960-0779(03)00102-4 is OK
- 10.1016/S0375-9601(01)00825-8 is OK
- 10.15388/NA.17.4.14052 is OK
- 10.1016/j.cpc.2004.08.007 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/S0375-9601(02)01775-9 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.amc.2010.04.026 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1006/jsco.2001.0494 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jmaa.2010.08.050 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0010-4655(96)00104-X is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0010-4655(02)00559-3 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jsc.2003.09.004 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03721/joss.03721/10.21105.joss.03721.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03721/joss.03721/10.21105.joss.03721.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@mithun218 thanks for this submission. I will be looking for a handling editor for this work. In the mean time can you work on fixing those references :point_up:. You can call `@whedon generate pdf` here, in a comment, to update the paper and call `@whedon check references` to check those DOI's. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by mithun218** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03721/joss.03721/10.21105.joss.03721.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03721/joss.03721/10.21105.joss.03721.pdf) :page_facing_up: :point_left:

**Comment by mithun218** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S0375-9601(02)01775-9 is OK
- 10.1155/2013/104894 is OK
- 10.1016/j.chaos.2005.10.007 is OK
- 10.1016/S0960-0779(03)00102-4 is OK
- 10.1016/S0375-9601(01)00825-8 is OK
- 10.15388/NA.17.4.14052 is OK
- 10.1016/j.amc.2010.04.026 is OK
- 10.1006/jsco.2001.0494 is OK
- 10.1016/j.jmaa.2010.08.050 is OK
- 10.1016/0010-4655(96)00104-X is OK
- 10.1016/S0010-4655(02)00559-3 is OK
- 10.1016/j.jsc.2003.09.004 is OK
- 10.1016/j.cpc.2004.08.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mithun218** [comment]
@Kevin-Mattheus-Moerman I checked and corrected DOIs.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by meg-simula** [comment]
Yes, can do.

**Comment by meg-simula** [comment]
:wave: Thanks, @mithun218 for the submission. This looks very much ready for review with JOSS. 

I'll reach out to reviewers, and get back to you.  Would you have any suggestions for reviewers, for instance from[ this spreadsheet](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822)?

**Comment by mithun218** [comment]
Hi and thank you @meg-simula for accepting to be editor for our paper! 

For reviewers, I'll suggest 
solanpaa, peanutfun, jamiejquinn, balos1, dawbarton, dglmoore,cpgr

**Comment by meg-simula** [comment]
:wave: @peanutfun @balos1 @ketch would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by peanutfun** [comment]
@meg-simula yes, I would like to! ☺️

**Comment by meg-simula** [comment]
@whedon assign @peanutfun as reviewer

**Comment by whedon** [comment]
OK, @peanutfun is now a reviewer

**Comment by meg-simula** [comment]
Quick update: I'm actively searching for a second reviewer @mithun218, will let you know of further updates.

**Comment by meg-simula** [comment]
Thanks @mithun218, let's ask them here.

**Comment by meg-simula** [comment]
:wave: @justinsgray @sivaramambikasaran @crstnbr @schruste would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by carstenbauer** [comment]
@meg-simula, yes, I can take this on. 🙂

**Comment by meg-simula** [comment]
Excellent, thanks for the prompt response @carstenbauer! Then we can get this review started.

**Comment by meg-simula** [comment]
@whedon add @carstenbauer as reviewer

**Comment by whedon** [comment]
OK, @carstenbauer is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3885.

**Comment by JustinSGray** [comment]
I can review
