### ISSUE TITLE
[REVIEW]: obscura: A modular C++ tool and library for the direct detection of (sub-GeV) dark matter via nuclear and electron recoils

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3725]
**Submitting author:** @temken (<a href="http://orcid.org/0000-0002-4251-2229">Timon Emken</a>)
**Repository:** <a href="https://github.com/temken/obscura" target ="_blank">https://github.com/temken/obscura</a>
**Version:** v1.0.0
**Editor:** @lucydot
**Reviewers:** @rafaelab, @villaa
**Archive:** <a href="https://doi.org/10.5281/zenodo.5665890" target="_blank">10.5281/zenodo.5665890</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9/status.svg)](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9"><img src="https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9/status.svg)](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/temken/obscura" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rafaelab @villaa, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lucydot know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @rafaelab 
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/temken/obscura">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/temken/obscura">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@temken) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @villaa
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/temken/obscura">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/temken/obscura">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@temken) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rafaelab @villaa it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1207

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (1122.8 files/s, 161367.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             33            747            588           5969
C/C++ Header                    16            261            126            696
reStructuredText                14            486            502            513
CMake                            3             38             32            311
TeX                              1             26              0            215
Markdown                         3             60              0            131
YAML                             3             14             22             76
DOS Batch                        1              8              1             26
Python                           1             15             30             10
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            76           1659           1308           7956
-------------------------------------------------------------------------------


Statistical information for the repository '19ed62eb8367d241d93e9389' was
gathered on 2021/09/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Timon Emken                    176         16450           8061          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Timon Emken                8442           51.3          8.4                8.81
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.physrep.2004.08.031 is OK
- 10.1038/s41586-018-0542-z is OK
- 10.1103/PhysRevResearch.2.033195 is OK
- 10.1103/PhysRevD.33.3495 is OK
- DOI:10.5281/zenodo.4559874 is OK
- 10.1103/PhysRevD.85.076007 is OK
- 10.1007/JHEP05(2016)046 is OK
- 10.1140/epjc/s10052-018-6513-6 is OK
- 10.1140/epjc/s10052-017-5155-4 is OK
- 10.1103/PhysRevD.31.3059 is OK
- 10.1103/PhysRevD.101.055004 is OK
- 10.1103/PhysRevD.80.083502 is OK
- 10.1016/S0927-6505(96)00047-3 is OK
- 10.1103/PhysRevD.33.2071 is OK

MISSING DOIs

- 10.1103/physrevresearch.3.033149 may be a valid DOI for title: Crystal responses to general dark matter-electron interactions

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3725 with the following error: 
```
 [WARNING] Citeproc: citation villaa not found
Error producing PDF.
! Undefined control sequence.
\hyper@@link ->\let \Hy@reserved@a 
                                   \relax \@ifnextchar [{\hyper@link@ }{\hyp...
l.348 }

Looks like we failed to compile the PDF

```

**Comment by lucydot** [comment]
@whedon assign @rafaelab as reviewers

**Comment by whedon** [comment]
OK, @rafaelab is now a reviewer

**Comment by lucydot** [comment]
@whedon add @villaa as reviewer

**Comment by whedon** [comment]
OK, @villaa is now a reviewer

**Comment by lucydot** [comment]
@villaa @rafaelab  Thanks again for agreeing to review. Reviewer checklists have been generated for you above, feel free to get started whenever is convenient for you in the nearest few weeks. It is best to raise any issues during the review process in the software repository and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below.

I'll check back in regularly, and do not hesitate to ask if you have questions.

**Comment by rafaelab** [comment]
I finished testing the code. It was easy to install and to execute. Everything worked as expected and the additional tests I did show that the package is robust. The only thing I really missed was a folder with the cpp files corresponding to the examples shown in the docs.

The last point is that there are no guidelines for people wishing to contribute to the software, as required by JOSS.

I'm happy to recommend `obscura' for publication once these minor issues and the ones about the paper are addressed by @temken.

**Comment by temken** [comment]
Hi @rafaelab,
Thank you for reviewing the paper and code, the positive feedback, and the constructive suggestions. I will respond to each issue raised and summarize the changes I made. All changes have just been merged into the [main branch](https://github.com/temken/obscura).

## 1. Regarding the paper
 
>     * l. 18: "terrestrial atom". I'd use something else broader than just "atom". Something like "terrestrial particle".
> 
>     * l. 53: "the evaluation this expression" => missing "of"
> 
>     * l. l. 54: inputes => inputs

I implemented these changes in [paper/paper.md](https://github.com/temken/obscura/blob/master/paper/paper.md)

[[Link to the corresponding commit]](https://github.com/temken/obscura/commit/7933e93a320b9a786710c3783f313dd33c3eef00)

> As for the content, the text does not specify that DM particles that can be treated with the code. Sure, the code is flexible enough to enable the user to input their favourite model. But there are certainly some limitations. Would it work, for example, with heavier particles, for example (at least the ones that can penetrate the atmosphere and reach the detector)? To be fair, this is written in the statement of need, which I personally find a bit too late for the reader.

I added a few clarifying statements to the third paragraph of the Summary in [paper/paper.md](https://github.com/temken/obscura/blob/master/paper/paper.md).

[[Link to the corresponding commit]](https://github.com/temken/obscura/commit/9653cf1271451c51ad9df9c1fdf8fee351ab77fa)

> I'm also missing how the results obtained with `obscura` compare with other other published results. I suppose other people have already produced figures like figure 1. If this is the case, how do the curves compares with yours?

This is a very good idea. I have added a dashed line to figure 1 to indicate the official results as reported by the experimental collaborations. This was possible for most experiments with the exception of SD nuclear interactions. I also extended the figure description.

[[Link to the corresponding commit 1]](https://github.com/temken/obscura/commit/7933e93a320b9a786710c3783f313dd33c3eef00)  
[[Link to the corresponding commit 2]](https://github.com/temken/obscura/commit/e7a15aec7ffd46867a63206082cd70ec70b2e1ce)

## 2. Regarding the software

> I finished testing the code. It was easy to install and to execute. Everything worked as expected and the additional tests I did show that the package is robust. The only thing I really missed was a folder with the cpp files corresponding to the examples shown in the docs.

All examples found in the [example page](https://obscura.readthedocs.io/en/latest/07_Examples.html) of the documentation are now also found as cpp files in [obscura/examples](https://github.com/temken/obscura/tree/master/examples). I have also tested them again, and they compile and run successfully.

[[Link to the corresponding commit]](https://github.com/temken/obscura/commit/7c1a9643d6de585a42a745c90e222c790984623f)

> The last point is that there are no guidelines for people wishing to contribute to the software, as required by JOSS.

Thank you for this nice suggestion. I added the file [docs/CONTRIBUTING.md](https://github.com/temken/obscura/tree/master/docs/CONTRIBUTING.md) to clarify to everyone how they can contribute.
 
[[Link to the corresponding commit]](https://github.com/temken/obscura/commit/849cc24aed9dc92a458e4ab9c379c77152f2495c)

> I'm happy to recommend `obscura' for publication once these minor issues and the ones about the paper are addressed by @temken.

Thanks again for the valuable feedback! I hope the code/paper is now suitable for publication in JOSS.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: :point_left:

**Comment by lucydot** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.physrep.2004.08.031 is OK
- 10.1038/s41586-018-0542-z is OK
- 10.1103/PhysRevResearch.2.033195 is OK
- 10.1103/PhysRevResearch.3.033149 is OK
- 10.1103/PhysRevD.33.3495 is OK
- DOI:10.5281/zenodo.4559874 is OK
- 10.1103/PhysRevD.85.076007 is OK
- 10.1007/JHEP05(2016)046 is OK
- 10.1140/epjc/s10052-018-6513-6 is OK
- 10.1140/epjc/s10052-017-5155-4 is OK
- 10.1103/PhysRevD.31.3059 is OK
- 10.1103/PhysRevD.101.055004 is OK
- 10.1103/PhysRevD.80.083502 is OK
- 10.1016/S0927-6505(96)00047-3 is OK
- 10.1103/PhysRevD.33.2071 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lucydot** [comment]
@whedon set 10.5281/zenodo.5607961 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5607961" target="_blank">10.5281/zenodo.5607961</a> is the archive.

**Comment by lucydot** [comment]
Hi @temken I've just realised the version is 0.2.0 - I'd usually expect production/stable code to be at a version number 1.0.0+ (with 0.X.Y for beta releases). Was this an oversight per chance?

**Comment by temken** [comment]
Hi @lucydot,
I didn't really think much about it, it was just that all previous version were 0.1.x, so I thought 0.2.0 would be the next step. I can make another release with version 1.0.0 if necessary. Please let me know.

**Comment by lucydot** [comment]
Hi @temken - I'd consider releasing this as 1.0.0. It's not a deal-breaker, I'll leave the final decision up to you - it may be best to follow what is typically done in your particular domain. However in my experience 0.X.Y versions are those used for initial development  - see, for example, the guidance for semantic versioning: https://semver.org/.

**Comment by temken** [comment]
Hi @lucydot,
Thank you for the link, which was very instructive. I'll definitely be more mindful on my versioning in the future. I just released version 1.0.0 (tag (v1.0.0)[https://github.com/temken/obscura/releases/tag/v1.0.0]) replacing the previous v0.2.0, which I deleted.  Version 1.0.0 is archived under [DOI:10.5281/zenodo.5665890](https://zenodo.org/record/5665890).

I also made a very minor change to the acknowledgments of the paper (specification of a grant).

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.5665890 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5665890" target="_blank">10.5281/zenodo.5665890</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.physrep.2004.08.031 is OK
- 10.1038/s41586-018-0542-z is OK
- 10.1103/PhysRevResearch.2.033195 is OK
- 10.1103/PhysRevResearch.3.033149 is OK
- 10.1103/PhysRevD.33.3495 is OK
- DOI:10.5281/zenodo.4559874 is OK
- 10.1103/PhysRevD.85.076007 is OK
- 10.1007/JHEP05(2016)046 is OK
- 10.1140/epjc/s10052-018-6513-6 is OK
- 10.1140/epjc/s10052-017-5155-4 is OK
- 10.1103/PhysRevD.31.3059 is OK
- 10.1103/PhysRevD.101.055004 is OK
- 10.1103/PhysRevD.80.083502 is OK
- 10.1016/S0927-6505(96)00047-3 is OK
- 10.1103/PhysRevD.33.2071 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @temken, it looks like this submission is essentially at the finish line, so I'm going to step in and help wrap it up.

I found a few minor issues in the paper to fix:
- Throughout the article, can you please add commas after "e.g.", and commas before if used in the sentence (for example, at the end of the first paragraph, it should be "... backgrounds, e.g., due to cosmic rays.")
- Before equation (1), I recommend changing it to `... as derived by @Essig:2015cda`, which will make it "as derived by Essig et al. (2015)".
- In the statement of need, I would remove the "see e.g." you use in two places, and just have the example citations at the end of the sentences.

**Comment by temken** [comment]
Hi @kyleniemeyer,

Thanks a lot for looking over the paper. I implemented the changes you suggested and also ran a spell-check.

[Link to commit](https://github.com/temken/obscura/pull/35/commits/52c37bc5adaaaa6c7513b0aeaa939cc9e0232b17)

I hope it is now ready for publication. If not let me know :)
Best regards,
Timon

**Comment by kyleniemeyer** [comment]
@whedon generage pdf

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@temken Looks great! Can you now archive the repository (e.g., on Zenodo) and provide the DOI here?

**Comment by temken** [comment]
Since the last changes were only minor fixes to the paper, could we use the DOI provided before (v1.0.0)? [10.5281/zenodo.5665890](https://zenodo.org/record/5665890)

Or is it necessary to make a new release and generate a new DOI (v1.0.1)?

**Comment by kyleniemeyer** [comment]
@temken ah I missed that—if the only changes are in the paper then we can use the existing archive/version. Thanks!

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.5665890 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5665890" target="_blank">10.5281/zenodo.5665890</a> is the archive.

**Comment by lucydot** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by lucydot** [comment]
It looks to me that everything is good to go now @kyleniemeyer? I'll recommend acceptance now..
Congratulations @temken  looks like we are *almost* there!

**Comment by lucydot** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.physrep.2004.08.031 is OK
- 10.1038/s41586-018-0542-z is OK
- 10.1103/PhysRevResearch.2.033195 is OK
- 10.1103/PhysRevResearch.3.033149 is OK
- 10.1103/PhysRevD.33.3495 is OK
- DOI:10.5281/zenodo.4559874 is OK
- 10.1103/PhysRevD.85.076007 is OK
- 10.1007/JHEP05(2016)046 is OK
- 10.1140/epjc/s10052-018-6513-6 is OK
- 10.1140/epjc/s10052-017-5155-4 is OK
- 10.1103/PhysRevD.31.3059 is OK
- 10.1103/PhysRevD.101.055004 is OK
- 10.1103/PhysRevD.80.083502 is OK
- 10.1016/S0927-6505(96)00047-3 is OK
- 10.1103/PhysRevD.33.2071 is OK

MISSING DOIs

- 10.1103/physrevd.104.095015 may be a valid DOI for title: Extended Calculation of Dark Matter-Electron Scattering in Crystal Targets

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2761

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2761, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by lucydot** [comment]
@temken it looks like the pre-print from Griffin et al has just been published in PRD (10.1103/physrevd.104.095015) - please could you update the paper reference to reflect this? Thank-you

**Comment by Kevin-Mattheus-Moerman** [comment]
@temken a change was requested here :point_up: , let us know when this is ready to proceed.

**Comment by temken** [comment]
Hi @lucydot and @Kevin-Mattheus-Moerman,
I updated the reference ([link to commit](https://github.com/temken/obscura/commit/b2f28438cc06689d4099dc964aff45cb090b67be)). All should be ready now.

**Comment by lucydot** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03725/joss.03725/10.21105.joss.03725.pdf) :page_facing_up: :point_left:

**Comment by lucydot** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.physrep.2004.08.031 is OK
- 10.1038/s41586-018-0542-z is OK
- 10.1103/PhysRevResearch.2.033195 is OK
- 10.1103/PhysRevResearch.3.033149 is OK
- 10.1103/PhysRevD.33.3495 is OK
- DOI:10.5281/zenodo.4559874 is OK
- 10.1103/PhysRevD.85.076007 is OK
- 10.1007/JHEP05(2016)046 is OK
- 10.1140/epjc/s10052-018-6513-6 is OK
- 10.1140/epjc/s10052-017-5155-4 is OK
- 10.1103/PhysRevD.31.3059 is OK
- 10.1103/PhysRevD.101.055004 is OK
- 10.1103/PhysRevD.104.095015 is OK
- 10.1103/PhysRevD.80.083502 is OK
- 10.1016/S0927-6505(96)00047-3 is OK
- 10.1103/PhysRevD.33.2071 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lucydot** [comment]
Thanks @temken that looks good! 🎈

**Comment by lucydot** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.physrep.2004.08.031 is OK
- 10.1038/s41586-018-0542-z is OK
- 10.1103/PhysRevResearch.2.033195 is OK
- 10.1103/PhysRevResearch.3.033149 is OK
- 10.1103/PhysRevD.33.3495 is OK
- DOI:10.5281/zenodo.4559874 is OK
- 10.1103/PhysRevD.85.076007 is OK
- 10.1007/JHEP05(2016)046 is OK
- 10.1140/epjc/s10052-018-6513-6 is OK
- 10.1140/epjc/s10052-017-5155-4 is OK
- 10.1103/PhysRevD.31.3059 is OK
- 10.1103/PhysRevD.101.055004 is OK
- 10.1103/PhysRevD.104.095015 is OK
- 10.1103/PhysRevD.80.083502 is OK
- 10.1016/S0927-6505(96)00047-3 is OK
- 10.1103/PhysRevD.33.2071 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2776

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2776, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Hi @temken! I'll help finish publishing your paper. First, can you update the metadata in your Zenodo archive so that the title and author list exactly match your JOSS paper?

**Comment by kthyng** [comment]
Paper looks good!

**Comment by temken** [comment]
Hi @kthyng, I updated the metadata of the Zenodo archive.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1466162882207440898) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2785
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03725](https://doi.org/10.21105/joss.03725)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @temken! Many thanks to editor @lucydot and reviewers @rafaelab and @villaa for your time, hard work, and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03725/status.svg)](https://doi.org/10.21105/joss.03725)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03725">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03725/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03725/status.svg
   :target: https://doi.org/10.21105/joss.03725
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03725/status.svg)](https://doi.org/10.21105/joss.03725)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
