### ISSUE TITLE
[PRE REVIEW]: Swalbe.jl: A lattice Boltzmann solver for thin film hydrodynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3728]
**Submitting author:** @Zitzeronion (<a href="http://orcid.org/0000-0002-2371-5610">Stefan Zitz</a>)
**Repository:** https://jugit.fz-juelich.de/compflu/swalbe.jl/
**Branch with paper.md** (empty if default branch): 
**Version:** 0.1.0
**Editor:** @arfon
**Reviewers:** @mbernaschi
**Managing EiC:** Kevin M. Moerman

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/414a5b53a41e05a250a352360a7da337/status.svg)](https://joss.theoj.org/papers/414a5b53a41e05a250a352360a7da337)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/414a5b53a41e05a250a352360a7da337"><img src="https://joss.theoj.org/papers/414a5b53a41e05a250a352360a7da337/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/414a5b53a41e05a250a352360a7da337/status.svg)](https://joss.theoj.org/papers/414a5b53a41e05a250a352360a7da337)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Zitzeronion. **Currently, there isn't an JOSS editor assigned** to your paper.

@Zitzeronion if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (835.6 files/s, 127485.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           31            514            618           3396
TOML                             4            261              2           1087
Markdown                         5            117              0            594
YAML                             4              2              1            121
-------------------------------------------------------------------------------
SUM:                            44            894            621           5198
-------------------------------------------------------------------------------


Statistical information for the repository 'f4fa79f4691ddcc869ade811' was
gathered on 2021/09/14.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3728 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Zitzeronion** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Zitzeronion** [comment]
@whedon generate pdf from branch JOSS_submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03728/joss.03728/10.21105.joss.03728.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03728/joss.03728/10.21105.joss.03728.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @dpsanders as editor

**Comment by whedon** [comment]
@dpsanders has been invited to edit this submission.

**Comment by Zitzeronion** [comment]
Added some more information to the affiliations and made .bib file spell Boltzmann with a capital B.
@whedon generate pdf from branch JOSS_submission

Another potential reviewer would be datseris.george@gmail.com, I think he is one of the founders of DrWatson.jl

**Comment by Zitzeronion** [comment]
@whedon generate pdf from branch JOSS_submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03728/joss.03728/10.21105.joss.03728.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03728/joss.03728/10.21105.joss.03728.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@dpsanders can you help edit this submission?

**Comment by dpsanders** [comment]
@Kevin-Mattheus-Moerman Sorry, yes I can.

**Comment by dpsanders** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by Zitzeronion** [comment]
Hello @dpsanders, 
Thank you very much for taking over the editorial work!

I think George Datseris could be a potential reviewer, but don't know if he is too familiar with thin film problems. However I know he knows a lot about Julia and Julia packages. Other reviewers might be: mancellin, jramirezcr or ali-ramadhan (from the list above).

**Comment by Zitzeronion** [comment]
Hey just wanted to ask if there is something I can or should do?
It seems that so far no reviewer has been assinged. I don't mind waiting just wanted to check.

**Comment by jramirezcr** [comment]
> 👋 @jramirezcr and @ali-ramadhan: Would you be available and willing to review this submission for [JOSS](https://joss.theoj.org/), the Journal of Open Source Software? Reviews are focused on the software and take place via GitHub issues. Thanks!

Dear @dpsanders.

I would like to review this submission. However, I don't have much experience using Julia, and I think this is a limitation.

**Comment by Zitzeronion** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03728/joss.03728/10.21105.joss.03728.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03728/joss.03728/10.21105.joss.03728.pdf) :page_facing_up: :point_left:

**Comment by Zitzeronion** [comment]
Dear @dpsanders and @jramirezcr,

I am terribly sorry for keeping you wait for ever. I hope you two do fine in this strange times.

I tried to update the paper according to your suggestions @dpsanders , there is a simple and easy use case outside of the tutorial section of the documentation. There is a minor review of other software solutions that can be used to simulate the thin film equation.

As far as I understood @jramirezcr  did not yet had a look at the repo, correct?

**Comment by Zitzeronion** [comment]
@dpsanders is it okay to put an authors contribution section into the paper?

By the way, happy holidays and a merry Christmas if you are already on vacation

**Comment by Zitzeronion** [comment]
Dear @dpsanders,
Is it possible to have a status update on the review process?
Some time has passed, which is not a problem at all, but I would like to know if our contribution is still considered for review or not.
And if there is anything I can do to help with the process?

In the meantime, we submitted a manuscript for publication based on the software of this submission.
The preprint can be found at: https://arxiv.org/abs/2112.09770

Please let me know if there is something that I can do :)

**Comment by dpsanders** [comment]
👋 @Zitzeronion: I apologize for the long delay. Let me get back to you soon. 

Do you have suggestions for reviewers who are familiar with lattice Boltzmann, but who are not necessarily members of the Julia community? Perhaps authors of similar packages in other languages?

**Comment by Zitzeronion** [comment]
👋 @dpsanders: We came up with a few names.

However, I think all of them did not review for JOSS yet.
Some possible reviewers could be:
Mathias Krause (mathias.krause@kit.edu), Max Gaedtke (maximilian.gaedtke@kit.edu), Giorgio Amati (g.amati@cineca.it), Massimo Bernaschi (massimo.bernaschi@cnr.it) or Dominique Derome (dominique.derome@usherbrooke.ca) or Jan Carmeliet (cajan@ethz.ch).
Especially Max Gaedtke could be interested, but it could be that his KIT email is outdated.

I hope this helps, let me know if it does not, so we can work out solutions.

**Comment by Zitzeronion** [comment]
Happy Monday,

Is there any news you can share with us @dpsanders ?
Did one of the above person replied yet, or should we try to come up with more possible reviewers?

**Comment by Zitzeronion** [comment]
Dear @dpsanders sorry to bother you again, but another month has passed since your last reply.

It seems the issue of finding a referee is more severe than expected. 
Can you supply us with any update or with instructions of how we can help? 
Thanks in advance 😃

**Comment by arfon** [comment]
@editorialbot assign me as editor

**Comment by arfon** [comment]
@Zitzeronion – my apologies things have moved slowly here. @dpsanders has decided to step down from the JOSS editorial team due to his other work commitments. Thanks @dpsanders for all of your work as a JOSS editor over the past few years! ✨ 

@Zitzeronion – I'll be your editor from here on out. I see you've already suggested a few possible reviewers – I'll start contacting them to see if they'd be willing to provide a review.

**Comment by arfon** [comment]
@Datseris – would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by Datseris** [comment]
Hi @arfon , while this looks like a great package, I will unfortunately decline reviewing because I am swamped reviewing too many things already :( Sorry!

**Comment by Zitzeronion** [comment]
Hello 👋  @arfon and thank you for taking over the editorial burden. 
Thanks @dpsanders for all the work you put in 👏 . 

Please let me know if I can do something to help.

**Comment by arfon** [comment]
> Hi @arfon , while this looks like a great package, I will unfortunately decline reviewing because I am swamped reviewing too many things already :( Sorry!

No problem. Thanks anyway @Datseris. If you have any suggestions for alternative reviewers, please let me know.

Over email, @mbernaschi has kindly agreed to review this submission. Thank you @mbernaschi! In order to expedite the process, I'm going to go ahead and open the main review with @mbernaschi as the first reviewer, as and when we find a second reviewer, I'll add them directly to the main review thread there.

**Comment by arfon** [comment]
@editorialbot add @mbernaschi as reviewer

**Comment by arfon** [comment]
@editorialbot start review

**Comment by arfon** [comment]
@mbernaschi & @Zitzeronion – see you over in #4312 where the actual review will take place.
