### ISSUE TITLE
[PRE REVIEW]: SNEWPY: A Data Pipeline from Supernova Simulations to Neutrino Signals

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3729]
**Submitting author:** @JostMigenda (<a href="http://orcid.org/0000-0002-5350-8049">Jost Migenda</a>)
**Repository:** <a href="https://github.com/SNEWS2/snewpy" target ="_blank">https://github.com/SNEWS2/snewpy</a>
**Version:** v1.1b3
**Editor:** @dfm
**Reviewers:** @apizzuto, @PeterDenton
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8/status.svg)](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8"><img src="https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8/status.svg)](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @JostMigenda. **Currently, there isn't an JOSS editor assigned** to your paper.

@JostMigenda if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.02877 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1088/1367-2630/abde33 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1075

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.26 s (288.2 files/s, 58784.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          26           1272           2424           3219
Jupyter Notebook                20              0           5676           1745
Markdown                        17             57              0            291
make                             1             28              6            143
reStructuredText                 7             70             67             92
TeX                              1              6              0             84
YAML                             3             16             20             84
-------------------------------------------------------------------------------
SUM:                            75           1449           8193           5658
-------------------------------------------------------------------------------


Statistical information for the repository '5cffc9fd509bf09d78f1a9ac' was
gathered on 2021/09/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Evan O'Connor                   19          1052            364            7.04
Jost Migenda                    50          1948           1822           18.76
Segev BenZvi                   151          7697           4154           58.96
jpkneller                       22          2454             43           12.42
mcolomermolla                    6            58             52            0.55
nuberoi                          5           365             20            1.92
thomahrens                       2            68              4            0.36

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Evan O'Connor               102            9.7          9.6               15.69
Jim Kneller                   3          100.0          0.2               66.67
Jost Migenda               1639           84.1          0.9                8.72
Segev BenZvi               4341           56.4          7.9               18.84
Spencer Griswold              8          100.0          0.0                0.00
jpkneller                   738           30.1          7.6                9.35
mcolomermolla                10           17.2          0.3               20.00
nuberoi                      51           14.0         15.4               11.76
thomahrens                   23           33.8          2.2                4.35
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03729/joss.03729/10.21105.joss.03729.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03729/joss.03729/10.21105.joss.03729.pdf) :page_facing_up: :point_left:

**Comment by JostMigenda** [comment]
A few suggestions for potential reviewers: **apizzuto**, **bradkav** (who has [previously reviewed a JOSS paper I submitted](https://github.com/openjournals/joss-reviews/issues/2877)), **peterdenton** (not on the JOSS reviewer list, but [interested in neutrino codes](https://peterdenton.github.io/Code/index.html)) and **rafaelab**. (And, if we extend the search a bit, also **kostunin**, **KAClough** or people in the list of potential reviewers who include "astrophysics" in their topics.)

Note also that, later this week, we plan to submit a separate paper that’s more focussed on the underlying physics to AAS Journals and would like to make use of [the AAS/JOSS collaboration](https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing).

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @xuanxu @dfm this sounds like your :tea: (cup of tea), however you are both handling lots of submissions. I'll label this as waitlisted for now but let me know if you think you can take it on.

**Comment by Kevin-Mattheus-Moerman** [comment]
@JostMigenda thanks for this submission. As you can see from my comment, many of our editors in this domain are currently pre-ocupied with other submissions as JOSS is processing a bit of a backlog at the moment. As such I have listed this work as `waitlisted`, which means an editor will get to it once they are available. Thank you for your patience.

**Comment by dfm** [comment]
@whedon assign me as editor

I'm happy to edit! As @Kevin-Mattheus-Moerman mentioned, we're a little swamped, but I'll do a first pass of editing and start tracking down reviewers in the next week or so. Thanks in advance for your patience!

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by JostMigenda** [comment]
Thanks for volunteering—and yes, happy to wait a few days longer if it helps you stick to a sustainable workload!

One first question to the editor right away: As is common in astro/particle physics, this work was done not just by a small number of people but as part of a larger collaboration (in this case the SNEWS Collaboration). Is it possible to include the collaboration name after the author list in a JOSS paper? (E.g. like the AASTeX class, which has a [special `\collaboration{}{}` command](https://journals.aas.org/aastex-v6-3-author-guide/#title_author) for that.)

**Comment by dfm** [comment]
@JostMigenda: I'm working on finding reviewers now and I'll keep you posted on that!

> One first question to the editor right away: As is common in astro/particle physics, this work was done not just by a small number of people but as part of a larger collaboration (in this case the SNEWS Collaboration). Is it possible to include the collaboration name after the author list in a JOSS paper? (E.g. like the AASTeX class, which has a special \collaboration{}{} command for that.)

Sorry about the delay on this response, but I actually had to do a little digging. We don't currently have a special command for this and our usual recommendation for this is to just add the collaboration as an author. You'll need to include an affiliation, so perhaps choose the primary institution or just label it "no affiliation".

**Comment by dfm** [comment]
@whedon add @apizzuto as reviewer

Alex has agreed to review this submission - thank you!! I believe that Alex has identified a potential COI that should be shared here. @JostMigenda please let me know here or via email if you or the other authors have any issue with this, otherwise, I'm happy to waive it after it is disclosed.

**Comment by whedon** [comment]
OK, @apizzuto is now a reviewer

**Comment by dfm** [comment]
@whedon add @PeterDenton as reviewer

And Peter has agreed to be our second reviewer - thanks!

After we take a look at @apizzuto's potential conflict, we'll be good to get started.

@ all: please don't hesitate to ask if you have any questions, comments, or issues as we go. I'm here to help this go smoothly!

**Comment by whedon** [comment]
OK, @PeterDenton is now a reviewer

**Comment by apizzuto** [comment]
Hi all, thanks for the submission!
The [JOSS COI policy](https://github.com/openjournals/joss/blob/master/COI.md) requests that reviewers disclose potential COIs. I am a member of the IceCube Collaboration and there are at least a few folks on the author list of this paper that are also members (Segev BenZvi, Spencer Griswold, and I may have missed others). The COI policy says that for large collaborations this is often fine as long as we did not work together.
I believe that I am enough removed to review the contribution without bias, and I am happy to still review this project if the authors believe I can review this impartially and are comfortable waiving this COI, but I am happy to defer to the authors.

**Comment by JostMigenda** [comment]
I confirm that we don't think this is an issue and we're happy with waiving this COI.

**Comment by apizzuto** [comment]
Great, thanks for checking on that @JostMigenda . I'll take a look at the paper and code in the coming days, then

**Comment by danielskatz** [comment]
FYI, the waived COI has to be approved by the editor, not by the authors.  (not that I see any problem, but please wait for @dfm to decide.)

**Comment by dfm** [comment]
Thanks @danielskatz!

Yes, given the scope of this potential COI and @JostMigenda's response, I am happy to waive this case and proceed with the review. Thanks again @apizzuto for being transparent. I'll get the review started in a new thread and we'll move over there for the rest of the process. Thanks again, everyone!

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3772.
