### ISSUE TITLE
[REVIEW]: array_split: Multi-dimensional array partitioning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#373]
**Submitting author:** @Shane-J-Latham (<a href="http://orcid.org/0000-0001-8033-4665">Shane J. Latham</a>)
**Repository:** <a href="https://github.com/array-split/array_split" target ="_blank">https://github.com/array-split/array_split</a>
**Version:** 0.5.0
**Editor:** @arfon
**Reviewer:** @dvalters
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.889080" target="_blank">10.5281/zenodo.889080</a>

## Status

[![status](http://joss.theoj.org/papers/4b59c7430176ef78c80c6a1100031eb6/status.svg)](http://joss.theoj.org/papers/4b59c7430176ef78c80c6a1100031eb6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4b59c7430176ef78c80c6a1100031eb6"><img src="http://joss.theoj.org/papers/4b59c7430176ef78c80c6a1100031eb6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4b59c7430176ef78c80c6a1100031eb6/status.svg)](http://joss.theoj.org/papers/4b59c7430176ef78c80c6a1100031eb6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/array-split/array_split" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@dvalters, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/array-split/array_split">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.5.0)?
- [x] **Authorship:** Has the submitting author (@Shane-J-Latham) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @dvalters it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by dvalters** [comment]
# Review summary
@arfon @Shane-J-Latham

My review is quite short as I could find little to fault in the submission. The standard of the **array_split** software package is high. It is well documented and with a good level of testing. It provides a useful and substantial extension to the functionality of the basic NumPy array splitting functions. There are good applications for scientific parallel codes as the author suggests in the paper. The quality of the Python code is also high. 

I have very few requests before the paper can be accepted, just minor issues with some of the references:

## References
Could you check that DOIs are provided for papers that have them. The Dalcin (2011) paper has a DOI available on the [Science Direct website](http://www.sciencedirect.com/science/article/pii/S0309170811000777), but it is not included in the `.bib` file. Similarly for the reference to scikit-image (https://www.ncbi.nlm.nih.gov/pubmed/25024921), and the NumPy Array reference (http://ieeexplore.ieee.org/document/5725236/).

Once these are fixed, I can recommend it be accepted into JOSS.

## Suggestions (not required for acceptance)
The documentation is a good standard, but it would be really useful if at somepoint diagrams could be added to illustrate how the arrays are being split with the different functions (I find I often have to sketch out what I want the arrays/halos to look like when working on problems like this). The writing as it stands is clear, however, and this is only a suggestion for future work and not required for acceptance in my opinion.

**Comment by Shane-J-Latham** [comment]
Thanks for the review @dvalters, much appreciated.

Yes, I neglected to include DOIs in the 0.5.0 version, have subsequently updated
them in the `0.5.x_rc` branch, see this [paper.bib](https://github.com/array-split/array_split/blob/0.5.x_rc/docs/joss/paper.bib). I'll create a 0.5.1 version,
which includes the corrected `paper.bib`, on acceptance for the DOI.

Some diagrams in the documentation would indeed add some clarity.
More generally, the ability to visualise the calculated *split* would also
be valuable. Could plot 1D, 2D and maybe 3D *splits* using [matplotlib](https://matplotlib.org/),
and for higher dimensions plot 2D slices at specified axis positions...

**Comment by arfon** [comment]
@Shane-J-Latham - please merge [this PR](https://github.com/array-split/array_split/pull/1) fixing up some issues with the bibtex. Also, then please could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by array-split** [comment]
Thanks for the paper.bib syntax fixes @arfon. DOI is 10.5281/zenodo.889080

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.889080 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.889080" target="_blank">10.5281/zenodo.889080</a> is the archive.

**Comment by arfon** [comment]
@dvalters - many thanks for your excellent review ✨ 

@Shane-J-Latham - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00373 ⚡️ 🚀 💥
