### ISSUE TITLE
Contribution and authorship: Has the submitting author (@chrisamiller) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### ISSUE THREAD

**Issue by friedue** [openjournals/joss-reviews#3731]

**Comment by whedon** [comment]
:wave: This repository is only for review issues (`pre-review` and `review`) that have been created by our editorial infrastructure, and this issue appears not to be one of these.

As such, this issue will be closed. If you're opening an issue as part of a review, please open a new issue instead in the software repository associated with the submission that you are reviewing.

Many thanks!
