### ISSUE TITLE
[PRE REVIEW]: Greenhouse: Scrape Prevention using Pre-rendered Image streaming.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3737]
**Submitting author:** @god-s-perfect-idiot (<a href="http://orcid.org/0000-0003-2213-8820">Samar Musthafa</a>)
**Repository:** <a href="https://github.com/god-s-perfect-idiot/greenhouse" target ="_blank">https://github.com/god-s-perfect-idiot/greenhouse</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/865db8d7fa1da9f25ab1edb50100f90b/status.svg)](https://joss.theoj.org/papers/865db8d7fa1da9f25ab1edb50100f90b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/865db8d7fa1da9f25ab1edb50100f90b"><img src="https://joss.theoj.org/papers/865db8d7fa1da9f25ab1edb50100f90b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/865db8d7fa1da9f25ab1edb50100f90b/status.svg)](https://joss.theoj.org/papers/865db8d7fa1da9f25ab1edb50100f90b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @god-s-perfect-idiot. **Currently, there isn't an JOSS editor assigned** to your paper.

@god-s-perfect-idiot if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 735

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (358.8 files/s, 53336.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             2              0              0            843
Markdown                         3            168              0            694
HTML                             4             27              0            257
JavaScript                       3             18              0            105
CSS                              1              8              0             38
TeX                              1              2              0             24
YAML                             1              8             15             23
-------------------------------------------------------------------------------
SUM:                            15            231             15           1984
-------------------------------------------------------------------------------


Statistical information for the repository '64ae04f8e1d084a443fc2208' was
gathered on 2021/09/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
god-s-perfect-idiot              3           147             24          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
god-s-perfect-idiot         123           83.7          0.9                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03737/joss.03737/10.21105.joss.03737.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03737/joss.03737/10.21105.joss.03737.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@god-s-perfect-idiot – thanks for your submission to JOSS. Unfortunately, at ~100 lines of JavaScript, this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion. It's also not clear that this software meets [JOSS' definitions of research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software).

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
