### ISSUE TITLE
[REVIEW]: mcMST: A Toolbox for the Multi-Criteria Minimum Spanning Tree Problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#374]
**Submitting author:** @jakobbossek (<a href="http://orcid.org/0000-0002-4121-4668">Jakob Bossek</a>)
**Repository:** <a href="https://github.com/jakobbossek/mcMST" target ="_blank">https://github.com/jakobbossek/mcMST</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @gvegayon
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.894402" target="_blank">10.5281/zenodo.894402</a>

## Status

[![status](http://joss.theoj.org/papers/31244283ec1570d0ca4753e2a39028ab/status.svg)](http://joss.theoj.org/papers/31244283ec1570d0ca4753e2a39028ab)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/31244283ec1570d0ca4753e2a39028ab"><img src="http://joss.theoj.org/papers/31244283ec1570d0ca4753e2a39028ab/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/31244283ec1570d0ca4753e2a39028ab/status.svg)](http://joss.theoj.org/papers/31244283ec1570d0ca4753e2a39028ab)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jakobbossek/mcMST" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@gvegayon, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jakobbossek/mcMST">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@jakobbossek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @gvegayon it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @gvegayon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gvegayon

**Comment by Kevin-Mattheus-Moerman** [comment]
:rocket: @jakobbossek This is where the review process will happen. 

@gvegayon see here for the [reviewer guidelines](http://joss.theoj.org/). See here for an example [review process](https://github.com/openjournals/joss-reviews/issues/354). Feel free to comment here or create issues on the repository and link to them here. Tick the boxes at the top here if you feel the requirements are met. Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ArdiaD @lmarti @berndbischl @jakob-r @aklxao2 @luca-scr we would like to recruit multiple reviewers. If you would also like to review for us please join here by commenting on this submission and opening issues on the repository. Thanks!

**Comment by ArdiaD** [comment]
Currently under water with various projects, but would be happy to help later this year.

**Comment by berndbischl** [comment]
hi guys,

i am 
a) currently traveling
and
b) have worked together with jakob on multiple suggestions, including suoervising his master's, so i dont feel there is an arm's length distance here

will therefore decline.

(PS: I want to say how much I like everything I see what happens at JOSS)

**Comment by gvegayon** [comment]
Overall the project looks very good, although a couple of things can be done to (I think) improve it by solving the following issues that I just listed:

1.  The AppVeyor link is broken (https://github.com/jakobbossek/mcMST/issues/8)
2.  The [@]return tag in mcMSTPrim.R is bad (https://github.com/jakobbossek/mcMST/issues/9)
3.  Specify (or actually point to) the definition of the output of mcMSTEmoaZhou and friends (https://github.com/jakobbossek/mcMST/issues/10)
4.  Coding standards/misc (https://github.com/jakobbossek/mcMST/issues/11)

HIH

**Comment by jakobbossek** [comment]
Hi guys,

thanks for editing @Kevin-Mattheus-Moerman and reviewing @gvegayon 👍 
I'm on vacation right now forcing myself not to work nevertheless and read work-related mails too often 😉 

@gvegayon Thanks for the fast review process! I am happy to go through the issues you opened as soon as vacation ends.

**Comment by luca-scr** [comment]
Hello,

sorry but due to several projects going on at this moment, I won't be able to complete the review. 

Best,

Luca

> On 21 Aug 2017, at 17:18, Kevin Mattheus Moerman <notifications@github.com> wrote:
> 
> @ArdiaD @lmarti @berndbischl @jakob-r @aklxao2 @luca-scr we would like to recruit multiple reviewers. If you would also like to review for us please join here by commenting on this submission and opening issues on the repository. Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
--------------------------------------
Luca Scrucca, PhD
Associate Professor of Statistics
Department of Economics 
University of Perugia
Via A. Pascoli, 20
06123 Perugia (Italy)
Tel +39-075-5855229
Fax +39-075-5855950
E-mail luca.scrucca@unipg.it
Web page http://www.stat.unipg.it/luca
--------------------------------------

**Comment by aklxao2** [comment]
Hello, 

currently I am with several projects that consumes all my time, so I'm afraid I must decline the review. Sorry.

Best regards.
Ángel.

**Comment by jakob-r** [comment]
Hi,
together with @berndbischl I worked with @jakobbossek on multiple projects so I guess my review would be biased.

**Comment by gvegayon** [comment]
Just closed the last issue created in jakobbossek/mcMST (https://github.com/jakobbossek/mcMST/issues/11). I'm OK with what the project looks like now :+1:

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the review @gvegayon! @arfon, over to you, we are good to accept this one!

**Comment by arfon** [comment]
@jakobbossek - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by jakobbossek** [comment]
@gvegayon Thanks for the thorough review! 👍 

@arfon Just uploaded a new version to [CRAN](https://cran.r-project.org/web/packages/mcMST/index.html) and [Zenedo](https://zenodo.org/record/894402#.Wb_Q1K3qi34). The DOI is https://doi.org/10.5281/zenodo.894402

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.894402 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.894402" target="_blank">10.5281/zenodo.894402</a> is the archive.

**Comment by arfon** [comment]
@gvegayon - many thanks for your review here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@jakobbossek - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00374 ⚡️ 🚀 💥
