### ISSUE TITLE
[PRE REVIEW]: specieshindex: How scientifically popular is a species?

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3744]
**Submitting author:** @jessicatytam (<a href="http://orcid.org/0000-0003-3655-1974">Jessica Tam</a>)
**Repository:** <a href="https://github.com/jessicatytam/specieshindex" target ="_blank">https://github.com/jessicatytam/specieshindex</a>
**Version:** 0.3.1
**Editor:** @Bisaloo
**Reviewers:** @kamapu, @tom-gu, @DrMattG
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/401f3e0de4da2e338c5903d8a96a910b/status.svg)](https://joss.theoj.org/papers/401f3e0de4da2e338c5903d8a96a910b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/401f3e0de4da2e338c5903d8a96a910b"><img src="https://joss.theoj.org/papers/401f3e0de4da2e338c5903d8a96a910b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/401f3e0de4da2e338c5903d8a96a910b/status.svg)](https://joss.theoj.org/papers/401f3e0de4da2e338c5903d8a96a910b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jessicatytam. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Bisaloo.

@jessicatytam if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1478

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (466.8 files/s, 185112.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rmd                              2            271            520           2140
R                                9            175           1233           1355
TeX                              3             31              0            521
Markdown                         2            100              0            312
YAML                             1             15              1             68
-------------------------------------------------------------------------------
SUM:                            17            592           1754           4396
-------------------------------------------------------------------------------


Statistical information for the repository '9da9031ad554ed0ec6c0f5d2' was
gathered on 2021/09/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
jessicatytam                     2            19             19          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1073/pnas.0507655102 is OK
- 10.1111/tbed.12221 is OK
- 10.1111/mam.12066 is OK
- 10.1007/s11192-015-1798-9 is OK
- 10.1007/s11192-007-1859-9 is OK
- 10.1371/journal.pone.0131004 is OK
- 10.1111/mam.12038 is OK
- 10.1038/s41598-017-09084-6 is OK
- 10.1139/facets-2016-0011 is OK
- 10.1007/s11192-006-0147-4 is OK
- 10.1017/S1367943004001799 is OK
- 10.1371/journal.pone.0189577 is OK
- 10.1007/s11192-006-0146-5 is OK
- 10.1016/S0169-5347(01)02381-3 is OK
- 10.1038/s41467-018-07916-1 is OK
- 10.1111/acv.12586 is OK
- 10.1038/s41477-021-00912-2 is OK
- 10.1016/j.gecco.2018.e00423 is OK
- 10.1007/s11160-019-09556-0 is OK
- 10.1111/j.1523-1739.2006.00616.x is OK
- 10.1111/j.1523-1739.2010.01453.x is OK
- 10.1108/07378830610715473 is OK

MISSING DOIs

- 10.1093/eurheartj/ehx446 may be a valid DOI for title: Other Metrics: beyond the Impact Factor

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@Bisaloo are you up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @Bisaloo as editor

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by Bisaloo** [comment]
Hi @kthyng and @jessicatytam, yes, I can edit this submission

**Comment by Bisaloo** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Bisaloo

**Comment by Bisaloo** [comment]
@jessicatytam, while I'm looking for reviewers, could you please have a look at the missing DOI detected by whedon in [this comment](https://github.com/openjournals/joss-reviews/issues/3744#issuecomment-924010397)?

**Comment by Bisaloo** [comment]
@ahasverus, would you be interested in reviewing this paper & R package for JOSS?

**Comment by Bisaloo** [comment]
:wave: @dombennett, you signaled interest in reviewing papers for JOSS? Would you have time to review this paper & package that matches the research interests you listed.

**Comment by Bisaloo** [comment]
Hi @kamapu :wave:, I saw your post on rOpenSci slack and this package seems relevant to your interests. Would you be able to help JOSS with a review?

**Comment by kamapu** [comment]
> Hi @kamapu wave, I saw your post on rOpenSci slack and this package seems relevant to your interests. Would you be able to help JOSS with a review?

This seems to be an interesting package. I may not feel comfortable reviewing a package but if the matter of review is a manuscript, I can take the challenge :+1:

**Comment by Bisaloo** [comment]
@kamapu, thanks for your answer. You can learn more about the review process at JOSS in [our documentation](https://joss.readthedocs.io/en/latest/index.html). The section ["review criteria"](https://joss.readthedocs.io/en/latest/review_criteria.html) and ["review checklist"](https://joss.readthedocs.io/en/latest/review_checklist.html) should answer your questions.

In short, we review both [the package](https://github.com/jessicatytam/specieshindex) & [the paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03744/joss.03744/10.21105.joss.03744.pdf). I believe it is possible to bring valuable insights by trying to use the package a way any user would: try to install it, read the documentation, see if you get any errors at any point, tell us if any crucial functionality seems to be missing, etc. Some items may require a slightly more advanced knowledge of R (e.g., does the package have tests?) but seeing that you already developed a couple of packages, you might already be familiar with these concepts.

Feel free to take a couple of days to think about it if you'd like. But if you are already sure you do not wish to review this package & paper, I understand and respect your decision :+1:.

**Comment by kamapu** [comment]
> @kamapu, thanks for your answer. You can learn more about the review process at JOSS in [our documentation](https://joss.readthedocs.io/en/latest/index.html). The section ["review criteria"](https://joss.readthedocs.io/en/latest/review_criteria.html) and ["review checklist"](https://joss.readthedocs.io/en/latest/review_checklist.html) should answer your questions.
> 
> In short, we review both [the package](https://github.com/jessicatytam/specieshindex) & [the paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03744/joss.03744/10.21105.joss.03744.pdf). I believe it is possible to bring valuable insights by trying to use the package a way any user would: try to install it, read the documentation, see if you get any errors at any point, tell us if any crucial functionality seems to be missing, etc. Some items may require a slightly more advanced knowledge of R (e.g., does the package have tests?) but seeing that you already developed a couple of packages, you might already be familiar with these concepts.
> 
> Feel free to take a couple of days to think about it if you'd like. But if you are already sure you do not wish to review this package & paper, I understand and respect your decision +1.

I learned programming by doing but it may be the case of many of us, thus I may oversee some technical details but I can take the challenge of assessing this package and attached article from the perspective of an user.

**Comment by Bisaloo** [comment]
> I learned programming by doing but it may be the case of many of us, thus I may oversee some technical details but I can take the challenge of assessing this package and attached article from the perspective of an user.

Great! Thank you for your help! Let me find a second reviewer and we can get started.

**Comment by Bisaloo** [comment]
@whedon add @kamapu as reviewer

**Comment by whedon** [comment]
OK, @kamapu is now a reviewer

**Comment by Bisaloo** [comment]
Hi @tom-gu :wave:, would you have any interest in helping us to review this package and paper? I understand this is only tangentially related to the core of your research interests (which I discovered via the `bdverse`) but I believe this has the potential to pique your interest :wink:

**Comment by Bisaloo** [comment]
Hi @hope-data-science, would you be able to help us review this [R package](https://github.com/jessicatytam/specieshindex) and [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03744/joss.03744/10.21105.joss.03744.pdf) for JOSS? According to the keywords you submitted in our review volunteering form (`scientometrics`, `bibliometrics`, `ecology`), this submission is made for you :grin:

**Comment by Bisaloo** [comment]
Hi @DrMattG :wave:, would you be able to help us review this [R package](https://github.com/jessicatytam/specieshindex) and [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03744/joss.03744/10.21105.joss.03744.pdf) for JOSS? This seems *really* close to the interests you list in our review volunteering form and in your [GitHub README](https://github.com/DrMattG/DrMattG)!

**Comment by tom-gu** [comment]
> Hi @tom-gu 👋, would you have any interest in helping us to review this package and paper? I understand this is only tangentially related to the core of your research interests (which I discovered via the `bdverse`) but I believe this has the potential to pique your interest 😉

Hi @Bisaloo 😃
Yes, I can review the [R package](https://github.com/jessicatytam/specieshindex) and [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03744/joss.03744/10.21105.joss.03744.pdf) for JOSS. 
What's a reasonable timetable?

**Comment by Bisaloo** [comment]
Thanks for your answer! The review at JOSS is slightly different than others journals. In short, we have found it is usually more efficient to have a more interactive review, where reviewers can post their comments/suggestions/questions as they come as GitHub issues in the submission repository. This differs from "traditional" reviews where you send all your review comments at once. [More details are available in our documentation](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). I'll post a detailed guide when the review process officially starts.

We usually aim to have comments within 1-2 weeks (you will receive an automated reminder after 2 weeks asking you about your current progress) but there is room for some flexibility.

**Comment by DrMattG** [comment]
> Hi @DrMattG 👋, would you be able to help us review this [R package](https://github.com/jessicatytam/specieshindex) and [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03744/joss.03744/10.21105.joss.03744.pdf) for JOSS? This seems _really_ close to the interests you list in our review volunteering form and in your [GitHub README](https://github.com/DrMattG/DrMattG)!

Hi @Bisaloo I'd be happy to!

**Comment by Bisaloo** [comment]
> > Hi @DrMattG wave, would you be able to help us review this [R package](https://github.com/jessicatytam/specieshindex) and [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03744/joss.03744/10.21105.joss.03744.pdf) for JOSS? This seems _really_ close to the interests you list in our review volunteering form and in your [GitHub README](https://github.com/DrMattG/DrMattG)!
> 
> Hi @Bisaloo I'd be happy to!

Amazing! With 3 reviewers, we are ready to go! The review can now formally start :tada:.

**Comment by Bisaloo** [comment]
@whedon add @tom-gu as reviewer

**Comment by Bisaloo** [comment]
@whedon add @DrMattG as reviewer

**Comment by whedon** [comment]
OK, @DrMattG is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3776.
