### ISSUE TITLE
[PRE REVIEW]: Frites: A Python package for functional connectivity analysis and group-level statistics of neurophysiological data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3746]
**Submitting author:** @EtienneCmb (<a href="http://orcid.org/0000-0002-7362-3247">Etienne Combrisson</a>)
**Repository:** <a href="https://github.com/brainets/frites" target ="_blank">https://github.com/brainets/frites</a>
**Version:** v0.4.0
**Editor:** @meg-simula
**Reviewers:** @madvn, @travisbthomp
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/437a7362501b2ea984e1d4fed4646076/status.svg)](https://joss.theoj.org/papers/437a7362501b2ea984e1d4fed4646076)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/437a7362501b2ea984e1d4fed4646076"><img src="https://joss.theoj.org/papers/437a7362501b2ea984e1d4fed4646076/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/437a7362501b2ea984e1d4fed4646076/status.svg)](https://joss.theoj.org/papers/437a7362501b2ea984e1d4fed4646076)
```

**Author instructions**

Thanks for submitting your paper to JOSS @EtienneCmb. **Currently, there isn't an JOSS editor assigned** to your paper.

@EtienneCmb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3746 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (1198.4 files/s, 107003.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         105           2315           5540           7016
SVG                              1              0              0            710
reStructuredText                84            617            706            568
TeX                              1             25              0            221
YAML                             6             45              5            181
CSS                              1             15              3             49
HTML                             2              2              3             28
DOS Batch                        1              8              1             26
make                             2              8             11             23
-------------------------------------------------------------------------------
SUM:                           203           3035           6269           8822
-------------------------------------------------------------------------------


Statistical information for the repository '8243ec038bbb84bf6f71b8fc' was
gathered on 2021/09/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
EtienneCmb                     372         23581           8285           99.58
Ruggero Basanisi                 2             9              8            0.05
brovelli.a                      11            71             45            0.36

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
EtienneCmb                14823           62.9          9.4               19.00
Ruggero Basanisi              8           88.9          7.2               50.00
brovelli.a                   40           56.3          4.8               35.00
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by kthyng** [comment]
@meg-simula Could you edit this submission?

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by EtienneCmb** [comment]
Dear @kthyng, here's a tag free list of potential reviewers :
- saran-nns
- JanCBrammer
- sappelhoff
- madvn
- ihrke
- karnigili
- zen-juen
- SRSteinkamp
- neurofractal

**Comment by meg-simula** [comment]
@whedon assign meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by meg-simula** [comment]
Thanks for the submission and the suggested reviewers @EtienneCmb! I will follow-up from here in the next few days.

**Comment by EtienneCmb** [comment]
Dear @meg-simula, do you have news from the potential reviewers?

**Comment by meg-simula** [comment]
:wave: @EtienneCmb I've reviewed the paper and code, and this looks very much ready for review in JOSS. I'll reach out to reviewers now.

**Comment by EtienneCmb** [comment]
Excellent, thank you !

**Comment by meg-simula** [comment]
:wave: @madvn @karnigili @jacobes @zen-juen would any of you be willing to review this submission for JOSS? 

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by madvn** [comment]
Hi @meg-simula , this work from @EtienneCmb et. al. looks quite interesting. While I'd be happy to review it, I'd like to first ask you what timeline you are looking at before I commit to it.

**Comment by zen-juen** [comment]
Thanks for reaching out! However, I'll pass since the specificities of the methods in Frites seem to be out of my area of expertise!

**Comment by meg-simula** [comment]
@madvn I'm glad to hear it! A review in the course of the next month or so would be much appreciated (depending on the time to find a second reviewer...)

**Comment by madvn** [comment]
Sounds good. I can do it!

**Comment by brovelli** [comment]
Thanks @madvn for accepting to review Frites. I hope you will find it interesting. In fact, I have seen you have developed an Information theory toolbox as well, also using PID measures. We are also currently working on them, probably adding them to the next release of Frites.

**Comment by whedon** [comment]
OK, @madvn is now a reviewer
