### ISSUE TITLE
[PRE REVIEW]: bikedata

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#375]
**Submitting author:** @mpadge (<a href="http://orcid.org/0000-0003-2172-5265">Mark Padgham</a>)
**Repository:** <a href="https://github.com/ropensci/bikedata" target ="_blank">https://github.com/ropensci/bikedata</a>
**Version:** v0.0.4
**Editor:** @karthik
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @mpadge. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mpadge if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by maelle** [comment]
(not interfering with the previous comment, just for info) This submission has been accepted to rOpenSci. The review thread can be found at https://github.com/ropensci/onboarding/issues/116

**Comment by mpadge** [comment]
@arfon Fair question on something I didn't directly address in the current [`paper.md`](https://github.com/ropensci/bikedata/blob/master/paper.md). It has very direct research application through opening up - curating, one might even say - arguably the worlds largest open ongoing dataset on human mobility. Without the package, these kinds of data can only be accessed in a very ad-hoc and piecemeal fashion. Moreover, there is quite arguably no other equivalent data set on human mobility that is both open and constantly evolving and updating.

Shall I update the `paper.md` to incorporate some of those points?

**Comment by karthik** [comment]
@mpadge Yes please, the more you can articulate a direct research application, the more likely it is to get approved here at JOSS.

**Comment by mpadge** [comment]
updated `paper.md` pasted here:

> The R package `bikedata` collates and facilitates access to arguably the world's largest open ongoing dataset on human mobility. All other comparable sources of data (such public transit data, or mobile phone data) are either not publicly available, or have been released only at single distinct times for single distinct purposes. Many public hire bicycle systems in the U.S.A., along with Santander Cycles in London, U.K., issue ongoing releases of their usage data, providing a unique source of data for analysing, visualising, and understanding human movement and urban environments. Such data provide an invaluable resource for urban planners, geographers, social and health scientists and policy makers, data visualisation specialists, and data-affine users of the systems themselves.  The `bikedata` package aims to provide unified access to usage statistics from all public hire bicycle systems which provide  data. These currently including Santander Cycles in London, U.K., and from the U.S.A., citibike in New York City NY, Divvy in Chicago IL, Capital Bikeshare in Washington DC, Hubway in Boston MA, Metro in Los Angeles LA, and Indego in Philadelphia PA. Additional systems will be added on an ongoing basis. The package facilitates the three necessary steps of (1) downloading data; (2) storing data in a readily accessible form (in this case in a single SQLite3 database); (3) extracting aggregate statistics.  The two primary aggregate statistics are matrices of numbers of trips between all pairs of stations, and daily time series. Both forms of aggregation may be extracted for specific dates, times, or demographic characteristics of cyclists.


Will that suffice? Let me know if not, or if there's anything I should or could do

**Comment by karthik** [comment]
@mpadge this looks good. Can you please add this to the paper?

**Comment by mpadge** [comment]
It's already there

**Comment by mpadge** [comment]
@karthik @arfon any news on progress here?

**Comment by karthik** [comment]
@mpadge Thanks for checking in. Apologies for the delays, but we'll provide you with an update soon.

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/471. Feel free to close this issue now!
