### ISSUE TITLE
[PRE REVIEW]: qualR: An R package to download São Paulo and Rio de Janeiro air pollution data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3753]
**Submitting author:** @quishqa (<a href="http://orcid.org/0000-0002-7371-1116">Mario Eduardo Gavidia Calderón</a>)
**Repository:** <a href="https://github.com/quishqa/qualR" target ="_blank">https://github.com/quishqa/qualR</a>
**Version:** v0.9.5
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d9e96637f111ed1cc499a21985ded9c9/status.svg)](https://joss.theoj.org/papers/d9e96637f111ed1cc499a21985ded9c9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d9e96637f111ed1cc499a21985ded9c9"><img src="https://joss.theoj.org/papers/d9e96637f111ed1cc499a21985ded9c9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d9e96637f111ed1cc499a21985ded9c9/status.svg)](https://joss.theoj.org/papers/d9e96637f111ed1cc499a21985ded9c9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @quishqa. **Currently, there isn't an JOSS editor assigned** to your paper.

@quishqa if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1372

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (1593.1 files/s, 96101.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               26            157            355            635
Markdown                         3            151              0            454
TeX                              1             11              0            119
YAML                             3             21              9             57
Rmd                              1             21             30             31
-------------------------------------------------------------------------------
SUM:                            34            361            394           1296
-------------------------------------------------------------------------------


Statistical information for the repository '22a083b9ae8a7d3d6708d037' was
gathered on 2021/09/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.atmosenv.2017.03.051 is OK
- 10.1016/j.envsoft.2011.09.008 is OK
- 10.1016/j.atmosenv.2018.09.026 is OK
- 10.1016/j.scitotenv.2020.139085 is OK

MISSING DOIs

- 10.5860/choice.35-5721 may be a valid DOI for title: Atmospheric Chemistry and Physics: From Air Pollution to Climate Change

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03753/joss.03753/10.21105.joss.03753.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03753/joss.03753/10.21105.joss.03753.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @quishqa and thanks for your submission. I am going to run a "scope query" on it which pings the editorial board to check the scope of the submission. This happens when a package has less than 1000 lines of codes. Someone will get back to you in a week or two with the results, thanks for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by quishqa** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by quishqa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03753/joss.03753/10.21105.joss.03753.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03753/joss.03753/10.21105.joss.03753.pdf) :page_facing_up: :point_left:

**Comment by quishqa** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1372

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (1784.0 files/s, 107618.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               26            157            355            635
Markdown                         3            151              0            454
TeX                              1             11              0            119
YAML                             3             21              9             57
Rmd                              1             21             30             31
-------------------------------------------------------------------------------
SUM:                            34            361            394           1296
-------------------------------------------------------------------------------


Statistical information for the repository '2525cb39a4bb7f4523aec828' was
gathered on 2021/09/22.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
👋 @quishqa - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Additionally, the work seems to be a data access wrapper that is limited to one cite, with no/little analytic capability. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
