### ISSUE TITLE
[PRE REVIEW]: ExtremeLearning: A Selection of Pure-Python Extreme Learning Machine Approaches

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3754]
**Submitting author:** @kjhall01 (<a href="http://orcid.org/0000-0003-3723-0662">Kyle Hall</a>)
**Repository:** <a href="https://github.com/kjhall01/extremelearning" target ="_blank">https://github.com/kjhall01/extremelearning</a>
**Version:** v0.1.3
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c66096747539077a943ba84222ec9263/status.svg)](https://joss.theoj.org/papers/c66096747539077a943ba84222ec9263)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c66096747539077a943ba84222ec9263"><img src="https://joss.theoj.org/papers/c66096747539077a943ba84222ec9263/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c66096747539077a943ba84222ec9263/status.svg)](https://joss.theoj.org/papers/c66096747539077a943ba84222ec9263)
```

**Author instructions**

Thanks for submitting your paper to JOSS @kjhall01. **Currently, there isn't an JOSS editor assigned** to your paper.

@kjhall01 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1060

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (588.7 files/s, 29460.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17             89             18            662
Markdown                         2             62              0            260
YAML                             2              7              4             47
Bourne Shell                     1              0              0              1
DOS Batch                        1              0              0              1
-------------------------------------------------------------------------------
SUM:                            23            158             22            971
-------------------------------------------------------------------------------


Statistical information for the repository '975bfdce8dc55ca37fc3137c' was
gathered on 2021/09/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
kjhall01                         7           839             70          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
kjhall01                    769           91.7          0.0                2.34
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S0305004100030401 is OK
- 10.1109/IEMBS.2007.4353024 is OK
- 10.26024/p6mv-en77 is OK
- 10.1109/IJCNN.2004.1380068 is OK
- 10.1007/s11063-012-9253-x is OK
- 10.1109/ACCESS.2020.2971012 is OK
- 10.1155/2020/3604579 is OK
- 10.1109/ACCESS.2015.2450498 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/B978-0-12-809393-1.00006-4 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.neucom.2008.01.005 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03754/joss.03754/10.21105.joss.03754.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03754/joss.03754/10.21105.joss.03754.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @kjhall01 and thanks for your submission. I am going to run a "scope query" on it which pings the editorial board to check the scope of the submission. This happens when a package has less than 1000 lines of code. Someone will get back to you in a week or two with the results, thanks for your patience.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @kjhall01 - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.
