### ISSUE TITLE
[PRE REVIEW]: QuasinormalModes.jl: A Julia package for computing1 discrete eigenvalues of second order ODEs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3755]
**Submitting author:** @lucass-carneiro (<a href="http://orcid.org/0000-0001-6764-1812">Lucas Timotheo Sanches</a>)
**Repository:** <a href="https://github.com/lucass-carneiro/QuasinormalModes.jl/" target ="_blank">https://github.com/lucass-carneiro/QuasinormalModes.jl/</a>
**Version:** v1.0.0
**Editor:** @pdebuyl
**Reviewers:** @JamieBamber, @cescalara
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55/status.svg)](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55"><img src="https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55/status.svg)](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55)
```

**Author instructions**

Thanks for submitting your paper to JOSS @lucass-carneiro. **Currently, there isn't an JOSS editor assigned** to your paper.

@lucass-carneiro if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (566.1 files/s, 68817.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           14            364            179           1525
Markdown                         7            156              0            373
TOML                             2             92              1            363
SVG                              2              0             10            253
YAML                             3              3              0             85
-------------------------------------------------------------------------------
SUM:                            28            615            190           2599
-------------------------------------------------------------------------------


Statistical information for the repository '3d91e88a9afa4522ad18630b' was
gathered on 2021/09/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3755 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03755/joss.03755/10.21105.joss.03755.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03755/joss.03755/10.21105.joss.03755.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @lucass-carneiro and thanks for your submission. All of our relevant editors are fully loaded currently so I am adding your submission to a waitlist. Thank you for your patience.

**Comment by lucass-carneiro** [comment]
@kthyng Thanks for letting me know!

**Comment by noatamir** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @noatamir

**Comment by noatamir** [comment]
👋 @jarvist @Datseris - would either or both of you be willing to edit this JOSS submission?

**Comment by noatamir** [comment]
Hi @lucass-carneiro, I'll be your editor for this submission. 

Could you look at our [potential reviewer list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) and maybe suggest reviewers (without tagging them with an @)? You can also suggest names outside of the list, just be aware of our [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy).

**Comment by danielskatz** [comment]
@noatamir - FYI, when you start editing a submission that is on the waitlist, please remove the label when you start
(And thanks for editing this one!)

**Comment by Datseris** [comment]
Hello,
oh this is unfortunate. I would love to review this one! It is somewhat close to my expertise. Unfortunately I will have to decline, because my other obligations at the moment leave me with not enough spare time until next year :( Sorry, and good luck!

**Comment by lucass-carneiro** [comment]
Hi @noatamir. Looking at the list, I think my submission lies within the area of expertise of these reviewers: ygrange, leios, ysimillides, ziotom78, malmaud, PhilipVinc, Jgoldfar, ma-sadeghi, smsharma, fhorrobin, solanpaa, williamfgc, Christovis, cescalara

**Comment by noatamir** [comment]
👋 @ygrange @ziotom78 @leios @ysimillides - would any of your be willing to review this submission for JOSS?

**Comment by ygrange** [comment]
It's a bit outside my field (I'm more of an experimental astronomy guy) but I'd be happy to poke at it if someone with more (theoretical astronomy/physics) domain knowledge could supplement that.

**Comment by ziotom78** [comment]
Hi @noatamir, my specialization is similar to @ygrange, so I second the request to look for a theoretician. (But if you need I can co-review this.)

**Comment by noatamir** [comment]
Thank you both! 
I'm still looking for another reviewer with theoretical astronomy/physics via email, as I'm not sure everyone is reading their github notifications.. I'll keep you posted.

**Comment by lucass-carneiro** [comment]
Hey @noatamir, any news?

**Comment by lucass-carneiro** [comment]
@kthyng Hey Kristen. I'm having trouble communicating with my editor. The last time she responded was over a month ago. Is there anything you can do?

**Comment by kthyng** [comment]
@lucass-carneiro Thanks for the ping. We're seeing if we can get ahold of @noatamir to check in too.

**Comment by kthyng** [comment]
@lucass-carneiro Thank you for your patience. Indeed we cannot get ahold of @noatamir so we will recruit a new editor now.

@pdebuyl are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
Hi @kthyng I'll edit the paper

**Comment by pdebuyl** [comment]
Hi @ziotom78 would you review the article "QuasinormalModes.jl: A Julia package for computing1 discrete eigenvalues of second order ODEs" for the Journal of Open Source Software?

**Comment by ziotom78** [comment]
Hi @pdebuyl, as I wrote above, my domain is instrumental astronomy, so theoretical models of Schwartzschild black holes is a bit outside my domain. I can co-referee this paper if I am sided by somebody with a more theoretical background.

**Comment by pdebuyl** [comment]
Woops, sorry @ziotom78 I was just assigned this submission and did not scroll up to read about previous contact attempts. Indeed, the search for Julia-aware relativist is not trivial :-) I'll try to find someone else in priority.

@lucass-carneiro for information I also carry out my reviewer search by email. I'll update you here when appropriate.

**Comment by pdebuyl** [comment]
@whedon assign @JamieBamber as reviewer

**Comment by whedon** [comment]
OK, @JamieBamber is now a reviewer

**Comment by pdebuyl** [comment]
@whedon add @cescalara as reviewer

**Comment by whedon** [comment]
OK, @cescalara is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4077.
