### ISSUE TITLE
[PRE REVIEW]: AIBECS.jl: The ideal tool for exploring global marine biogeochemical cycles.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3758]
**Submitting author:** @briochemc (<a href="http://orcid.org/0000-0002-3838-5976">Benoit Pasquier</a>)
**Repository:** <a href="https://github.com/JuliaOcean/AIBECS.jl" target ="_blank">https://github.com/JuliaOcean/AIBECS.jl</a>
**Version:** v0.10.10
**Editor:** @kthyng
**Reviewers:** @dankelley 
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4/status.svg)](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4"><img src="https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4/status.svg)](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4)
```

**Author instructions**

Thanks for submitting your paper to JOSS @briochemc. **Currently, there isn't an JOSS editor assigned** to your paper.

@briochemc if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (769.8 files/s, 77469.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           45           1080            856           3503
Markdown                         7            105              0            291
YAML                             9             12              0            288
TeX                              1             35              0            254
TOML                             2              5              0             77
JSON                             1              0              0             35
-------------------------------------------------------------------------------
SUM:                            65           1237            856           4448
-------------------------------------------------------------------------------


Statistical information for the repository '0f031c0a10763faabdbf5e8d' was
gathered on 2021/09/23.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3758 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSSpaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSSpaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03758/joss.03758/10.21105.joss.03758.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03758/joss.03758/10.21105.joss.03758.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @briochemc! Please check out the [reviewer list](https://bit.ly/joss-reviewers) and think through your own network of people you know (who aren't conflicted) to let me know some suggestions for reviewers. List their github handles here without the "@" prefix so they aren't preemptively pinged.

**Comment by briochemc** [comment]
Hi @kthyng! Here are some suggestions for reviewers :
- from the reviewer list:
    - ali-ramadhan
    - dankelley
    - patrickcgray
    - callumrollo
    - DamienIrving
    - mauro3
- and from my network (GitHub handles):
    - gaelforget
    - zhenwu0728
    - gregbritten

**Comment by briochemc** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kthyng** [comment]
Hi @gregbritten! Are you interested in reviewing this submission for the Journal of Open Source Software? The reviews are done openly in github via issues in the software and a summary in a review issue. You can read more about the process [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). We are asking for reviews to be finished in 4-6 weeks, but suggest you start sooner than that since the review process tends to be iterative between the reviewer and author. Thanks for your consideration.

**Comment by dankelley** [comment]
@kthyng yes, I can look at it.  (I didn't see a whedon instruction to say that, so sorry for making an extra step for you.) Dan.

**Comment by dankelley** [comment]
Yes, I can review it.  (I've already started and will likely finish this afternoon.  It's a holiday here, and I have a break from term but only for a day.)

**Comment by whedon** [comment]
It looks like you don't have an editor and reviewer assigned yet so I can't start the review. Try one or more of these commands:

```
# Change editorial assignment
@whedon assign @username as editor

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer
```

**Comment by kthyng** [comment]
@whedon assign @dankelley  as reviewer

**Comment by kthyng** [comment]
Just to be clear, I am still looking for a second reviewer and @gregbritten if you are interested or not please let me know! I have started the review so @dankelley can get to working on their review.

**Comment by patrickcgray** [comment]
> @patrickcgray would you be able to review this JOSS submission? The reviews are done openly in github via issues in the software and a summary in a review issue. You can read more about the process [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). We are asking for reviews to be finished in 4-6 weeks, but suggest you start sooner than that since the review process tends to be iterative between the reviewer and author. Thanks for your consideration.

Hi @kthyng this package looks amazing! and I'd love to dig into it, but I'm not familiar enough with Julia and don't have the time over the coming month to do it justice. I look forward to seeing it in JOSS though!

**Comment by kthyng** [comment]
Thanks for your response @patrickcgray!

@zhenwu0728 I wanted to come back to you. Regarding the workshop you ran with @briochemc — do you feel like you could be an unbiased reviewer of the software package? If so, I think we could proceed given that we are airing the conflict of interest in the open.

**Comment by zhenwu0728** [comment]
Hi @kthyng I think I can be an unbiased reviewer for this package. I can do the review later this week and the following week.

**Comment by kthyng** [comment]
@zhenwu0728 Excellent! I need to do a bit of manual reworking now since I previously started the review so @dankelley could do his right away. I'll ping you from the review issue itself when it's all set up.
