### ISSUE TITLE
[PRE REVIEW]:  spectrapepper: A Python toolbox for advanced analysis of spectroscopic data for materials and devices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3759]
**Submitting author:** @enricgrau (<a href="http://orcid.org/0000-0002-8357-5824">Enric Grau-Luque</a>)
**Repository:** <a href="https://github.com/spectrapepper/spectrapepper" target ="_blank">https://github.com/spectrapepper/spectrapepper</a>
**Version:** 0.1.0
**Editor:** @rkurchin
**Reviewers:** @stuartcampbell, @ksunden
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0/status.svg)](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0"><img src="https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0/status.svg)](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @enricgrau. **Currently, there isn't an JOSS editor assigned** to your paper.

@enricgrau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 884

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.solmat.2015.12.036 is OK
- 10.1038/s41598-017-01381-4 is OK
- 10.1039/c9ta03625c is OK
- 10.1063/1.5061809 is OK
- 10.1002/PIP.541 is OK
- 10.1039/d1ta01299a is OK
- 10.1002/aenm.201903242 is OK
- 10.1016/j.respol.2005.12.006 is OK
- 10.1002/9781119148739.ch4 is OK
- 10.1016/j.joule.2018.05.009 is OK
- 10.1039/d0ee02838j is OK
- 10.1039/c9ta02356a is OK
- 10.1038/s41586-018-0337-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/ZENODO.4681666 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/ZENODO.4743323 is OK
- 10.1177/0003702819839098 is OK
- 10.1016/j.chemolab.2018.06.009 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/1593511 is INVALID
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.25 s (252.1 files/s, 169755.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      17           4513           4497          17139
HTML                            11           1976             33           5174
SVG                              1              0              0           2671
Python                          10            762            880           1786
XML                              1              0              2           1618
CSS                              4            191             35            757
TeX                              1             40              0            335
Markdown                         4             41              0            163
YAML                             7             18              9            163
reStructuredText                 7             89             55            147
JSON                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            64           7630           5511          29959
-------------------------------------------------------------------------------


Statistical information for the repository '8a962bb4dd5f976923fc097f' was
gathered on 2021/09/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Enric Tomas Grau Luq            60        111899          82323          100.00
unknown                          1             3              2            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Enric Tomas Grau Luq      29577           26.4          2.8               16.06
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03759/joss.03759/10.21105.joss.03759.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03759/joss.03759/10.21105.joss.03759.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@rkurchin is this a good fit for you?

**Comment by kthyng** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by rkurchin** [comment]
@whedon assign me as editor

Sure, happy to!

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by rkurchin** [comment]
@ksunden, @stuartcampbell,
Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by stuartcampbell** [comment]
Yes I am willing.

**Comment by rkurchin** [comment]
@whedon add @stuartcampbell as reviewer

Thanks Stuart! We'll get the main review issue started once we secure another reviewer.

**Comment by whedon** [comment]
OK, @stuartcampbell is now a reviewer

**Comment by ksunden** [comment]
I am also willing

**Comment by rkurchin** [comment]
@whedon add @ksunden as reviewer

Fantastic! Thanks a lot! Stay tuned for review issue and some checklists...

**Comment by whedon** [comment]
OK, @ksunden is now a reviewer

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3781.
