### ISSUE TITLE
[PRE REVIEW]: EDO.js: A comprehensive JavaScript library for interaction with musical set theory in any tuning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3760]
**Submitting author:** @MichaelSel (<a href="http://orcid.org/0000-0002-6061-0674">Michael Seltenreich</a>)
**Repository:** <a href="https://github.com/MichaelSel/edoJS" target ="_blank">https://github.com/MichaelSel/edoJS</a>
**Version:** v1.2.13
**Editor:** @bmcfee
**Reviewers:** @napulen, @albincorreya
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec/status.svg)](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec"><img src="https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec/status.svg)](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec)
```

**Author instructions**

Thanks for submitting your paper to JOSS @MichaelSel. **Currently, there isn't an JOSS editor assigned** to your paper.

@MichaelSel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 694

**Comment by whedon** [comment]
PDF failed to compile for issue #3760 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations, date, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.37 s (216.7 files/s, 206099.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            41          30009             98          22045
JavaScript                      22           2398          10706          10374
CSS                              5            181             57            859
Markdown                         2             30              0             90
JSON                             2              3              0             71
TeX                              1              8              0             66
XML                              7              0              0             56
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            81          32629          10861          33562
-------------------------------------------------------------------------------


Statistical information for the repository 'c51b7feb21f50dcae24e82e9' was
gathered on 2021/09/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael                        112         33473          12405           92.52
MichaelSel                       6          3060            649            7.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael                   22733           67.9          9.2               47.88
MichaelSel                  746           24.4         11.3               10.32
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by MichaelSel** [comment]
expectopatronum and adammichaelwood may be suitable to review the paper

**Comment by MichaelSel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3760 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations, date, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by MichaelSel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: :point_left:

**Comment by MichaelSel** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by MichaelSel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @MichaelSel and thanks for your submission. Our relevant editors are at full capacity at the moment, but one should become available shortly. I'll put your submission on the waitlist for now and thanks for your patience.

**Comment by MichaelSel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: :point_left:

**Comment by MichaelSel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/745935 is OK

MISSING DOIs

- 10.1007/978-1-4684-8917-0_17 may be a valid DOI for title: The Pitch Set as a Level of Description for Studying Musical Pitch Perception
- 10.2307/843809 may be a valid DOI for title: Coordination of interval sizes in seven-tone collections
- 10.1121/1.4777600 may be a valid DOI for title: Auditory roughness estimation of complex spectra—Roughness degrees and dissonance ratings of harmonic intervals revisited
- 10.1080/17459730701376743 may be a valid DOI for title: Coherence and sameness in well-formed and pairwise well-formed scales
- 10.2307/j.ctt1xp3t38.20 may be a valid DOI for title: The structure of atonal music

INVALID DOIs

- None
```

**Comment by MichaelSel** [comment]
Thanks Kristen!

**Comment by MichaelSel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: :point_left:

**Comment by MichaelSel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03760/joss.03760/10.21105.joss.03760.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @mikldk - I wonder if you might be able to edit this JOSS submission?  I know it's not quite on topic for you, but we don't really have an editors in the music area.

**Comment by danielskatz** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by bmcfee** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by bmcfee** [comment]
:wave: per offline conversation with @kthyng - I can edit this one.  I technically have a [COI](https://joss.theoj.org/about#ethics) due to being at the same institution as the author (NYU), but as we're in completely separate units (GSAS and Steinhardt, respectively), this shouldn't be a problem.

**Comment by danielskatz** [comment]
On behalf of JOSS, we agree that this COI can be waived due to @bmcfee really being the only editor with the right background for this, and the fact that the units are separate.

**Comment by bmcfee** [comment]
@whedon assign @napulen as reviewer

**Comment by whedon** [comment]
OK, @napulen is now a reviewer

**Comment by bmcfee** [comment]
@whedon add @albincorreya as reviewer

**Comment by whedon** [comment]
OK, @albincorreya is now a reviewer

**Comment by bmcfee** [comment]
:wave: @MichaelSel we're ready to get the review going, though one of the reviewers (@albincorreya) won't be able to start until after next week.

**Comment by bmcfee** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3784.
