### ISSUE TITLE
[PRE REVIEW]: Correlated random walk propagation of cosmic rays in magnetic turbulence

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3762]
**Submitting author:** @reichherzerp (<a href="http://orcid.org/0000-0003-4513-8241">Patrick Reichherzer</a>)
**Repository:** <a href="https://gitlab.ruhr-uni-bochum.de/reichp2y/rwpropa" target ="_blank">https://gitlab.ruhr-uni-bochum.de/reichp2y/rwpropa</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e9f493bd20e903f98a484a971c6f646a/status.svg)](https://joss.theoj.org/papers/e9f493bd20e903f98a484a971c6f646a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e9f493bd20e903f98a484a971c6f646a"><img src="https://joss.theoj.org/papers/e9f493bd20e903f98a484a971c6f646a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e9f493bd20e903f98a484a971c6f646a/status.svg)](https://joss.theoj.org/papers/e9f493bd20e903f98a484a971c6f646a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @reichherzerp. **Currently, there isn't an JOSS editor assigned** to your paper.

@reichherzerp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1681

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (411.3 files/s, 112243.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          11            536            938           1022
TeX                              1             21              0            335
Markdown                         2            115              0            267
Jupyter Notebook                 4              0           1480            198
-------------------------------------------------------------------------------
SUM:                            18            672           2418           1822
-------------------------------------------------------------------------------


Statistical information for the repository '7e45917b17f32406071af444' was
gathered on 2021/09/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Patrick Reichherzer            264          4828           1988          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Patrick Reichherzer        2496           51.7          0.8               12.54
```

**Comment by kthyng** [comment]
Hi @reichherzerp and thanks for your submission. Since it is on the border of our acceptable size, I am going to ping the editorial board to check it out in more detail to make sure it is in scope. This process will take 1-2 weeks, thanks for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03762/joss.03762/10.21105.joss.03762.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03762/joss.03762/10.21105.joss.03762.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/806/2/217 is OK
- 10.1088/1674-4527/16/10/162 is OK
- 10.3847/1538-4357/ab643b is OK
- 10.22323/1.395.0468 is OK
- 10.1098/rsif.2008.0014 is OK
- 10.1086/148912 is OK
- 10.1063/1.4928940 is OK
- 10.1063/1.4807033 is OK
- 10.1088/1475-7516/2017/06/046 is OK
- 10.1088/1475-7516/2016/05/038 is OK
- 10.1088/1475-7516/2017/02/015 is OK
- 10.1086/306470 is OK
- 10.1093/mnras/staa2533 is OK
- 10.1103/PhysRevD.65.023002 is OK
- 10.1086/307452 is OK
- 10.1016/j.physrep.2020.05.002 is OK
- 10.3847/1538-4365/ac1517 is OK
- 10.3847/2041-8213/aa6aa6 is OK

MISSING DOIs

- 10.22323/1.395.0978 may be a valid DOI for title: CRPropa 3.2: a framework for high-energy astroparticle propagation

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hello @reichherzerp, thanks for your patience. We have reviewed your submission, and have decided that your submission is out of scope at this time, due to not meeting the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. 

However, we do think that this could be reviewed by JOSS if you add tests and proper packaging, and make it a bit easier for reviewers to verify the performance claims. If you can improve on those three areas, we would welcome a resubmission.

Alternatively, we have [other suggestions](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages) for how you might receive credit for your work as is.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
