### ISSUE TITLE
[PRE REVIEW]: sbp-env: A Python Package for Sampling-based Motion Planner and Samplers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3767]
**Submitting author:** @soraxas (<a href="http://orcid.org/0000-0003-0641-5250">Tin Lai</a>)
**Repository:** <a href="https://github.com/soraxas/sbp-env" target ="_blank">https://github.com/soraxas/sbp-env</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @KanishAnand, @OlgerSiebinga
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/59cea6b194d33c2844b79084f0d940d8/status.svg)](https://joss.theoj.org/papers/59cea6b194d33c2844b79084f0d940d8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/59cea6b194d33c2844b79084f0d940d8"><img src="https://joss.theoj.org/papers/59cea6b194d33c2844b79084f0d940d8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/59cea6b194d33c2844b79084f0d940d8/status.svg)](https://joss.theoj.org/papers/59cea6b194d33c2844b79084f0d940d8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @soraxas. **Currently, there isn't an JOSS editor assigned** to your paper.

@soraxas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 776

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (398.1 files/s, 53152.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          46           1331           1651           4214
reStructuredText                12            304            375            264
TeX                              1             29              0            209
Markdown                         2             54              0            122
YAML                             2              8              8             54
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            65           1738           2042           4898
-------------------------------------------------------------------------------


Statistical information for the repository '6bc9d9ed0a1af00d0c2d6379' was
gathered on 2021/09/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Oscar Lai                      161         10302           6725           49.29
Tin Lai                         38         10692           6827           50.71

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Oscar Lai                  1392           13.5         32.5               11.85
Tin Lai                    5814           54.4          4.9               14.26
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10/gdkx6g is OK
- 10/ghpwwm is OK
- 10/ghjdnk is OK
- 10/gmv7jc is OK
- 10/d66p3t is OK
- 10/ghqdw7 is OK
- 10/ghvk26 is OK
- 10/gddhk5 is OK
- 10/gddhmf is OK
- 10/gg2n24 is OK

MISSING DOIs

- 10.1109/access.2020.3023200 may be a valid DOI for title: Cooperative Pathfinding Based on Memory-Efficient Multi-Agent RRT
- 10.1109/robot.2005.1570709 may be a valid DOI for title: Dynamic-Domain RRTs: Efficient Exploration by Controlling the Sampling Domain
- 10.1109/isatp.2001.928961 may be a valid DOI for title: Move3D: A generic platform for path planning
- 10.1109/mra.2011.2181749 may be a valid DOI for title: Moveit! [ros topics]

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03767/joss.03767/10.21105.joss.03767.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03767/joss.03767/10.21105.joss.03767.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@soraxas - thanks for this submission.  I'll be your editor.

If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

While we look for reviewers, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by soraxas** [comment]
Hi @danielskatz thanks for the info!

Based on the given list, in reverse order: `KanishAnand, seungback, OlgerSiebinga, ekorudiawan, etc.` look like suitable candidates as reviewers (with *Robotics* as domain/topics and *python* as preferred language)

**Comment by soraxas** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10/gdkx6g is OK
- 10.1109/access.2020.3023200 is OK
- 10/ghpwwm is OK
- 10/ghjdnk is OK
- 10.1109/robot.2005.1570709 is OK
- 10/gmv7jc is OK
- 10/d66p3t is OK
- 10/ghqdw7 is OK
- 10/ghvk26 is OK
- 10/gddhk5 is OK
- 10/gddhmf is OK
- 10/gg2n24 is OK
- 10.1109/isatp.2001.928961 is OK
- 10.1109/mra.2011.2181749 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by soraxas** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03767/joss.03767/10.21105.joss.03767.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03767/joss.03767/10.21105.joss.03767.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @KanishAnand, @seungback, @OlgerSiebinga - would one or two of you be willing to review this submission for JOSS?

**Comment by KanishAnand** [comment]
@danielskatz I am willing to review

**Comment by danielskatz** [comment]
Thanks @KanishAnand - I'll add you in the system, and then once we get one or two more reviewers, we'll start the review in a new issue.

**Comment by danielskatz** [comment]
@whedon assign @KanishAnand as reviewer

**Comment by whedon** [comment]
OK, @KanishAnand is now a reviewer

**Comment by OlgerSiebinga** [comment]
@danielskatz - Yes, I'm willing to review as well

**Comment by danielskatz** [comment]
Thanks @OlgerSiebinga. I'll add you as well.

I've made an email request to another group, and would like to wait for a day or so to see if they are interested too - But either way, we'll start in 48 hours or so.

**Comment by danielskatz** [comment]
@whedon add @OlgerSiebinga as reviewer

**Comment by whedon** [comment]
OK, @OlgerSiebinga is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

Ok, let's go ahead and get started!

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3782.
