### ISSUE TITLE
[PRE REVIEW]: knotR - pleasing knot projections using Bezier curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#377]
**Submitting author:** @RobinHankin (<a href="http://orcid.org/0000-0001-5982-0415">Robin Hankin</a>)
**Repository:** <a href="https://github.com/RobinHankin/knotR" target ="_blank">https://github.com/RobinHankin/knotR</a>
**Version:** 1.0-3
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @RobinHankin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@RobinHankin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by RobinHankin** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
Hi @RobinHankin, many thanks for your submission to JOSS. Unfortunately this submission does not meet two of our [submission criteria](http://joss.theoj.org/about#submission_requirements):

> - Your software should have an obvious research application
> - Minor, 'utility' packages are not acceptable
