### ISSUE TITLE
[REVIEW]: SNEWPY: A Data Pipeline from Supernova Simulations to Neutrino Signals

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3772]
**Submitting author:** @JostMigenda (<a href="http://orcid.org/0000-0002-5350-8049">Jost Migenda</a>)
**Repository:** <a href="https://github.com/SNEWS2/snewpy" target ="_blank">https://github.com/SNEWS2/snewpy</a>
**Version:** v1.1
**Editor:** @dfm
**Reviewer:** @apizzuto, @PeterDenton
**Archive:** <a href="https://doi.org/10.5281/zenodo.5719209" target="_blank">10.5281/zenodo.5719209</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8/status.svg)](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8"><img src="https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8/status.svg)](https://joss.theoj.org/papers/fa644e244a5e7f3b5f5a42a5b82874e8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SNEWS2/snewpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@apizzuto & @PeterDenton, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @apizzuto
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/SNEWS2/snewpy">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SNEWS2/snewpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@JostMigenda) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @PeterDenton
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/SNEWS2/snewpy">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SNEWS2/snewpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@JostMigenda) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @apizzuto, @PeterDenton it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.02877 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1088/1367-2630/abde33 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.48 s (157.2 files/s, 32066.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          26           1272           2424           3219
Jupyter Notebook                20              0           5676           1745
Markdown                        17             57              0            291
make                             1             28              6            143
reStructuredText                 7             70             67             92
TeX                              1              6              0             84
YAML                             3             16             20             84
-------------------------------------------------------------------------------
SUM:                            75           1449           8193           5658
-------------------------------------------------------------------------------


Statistical information for the repository 'c4394c8fe7f7a6e63f58999c' was
gathered on 2021/09/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Evan O'Connor                   19          1052            364            7.04
Jost Migenda                    50          1948           1822           18.76
Segev BenZvi                   151          7697           4154           58.96
jpkneller                       22          2454             43           12.42
mcolomermolla                    6            58             52            0.55
nuberoi                          5           365             20            1.92
thomahrens                       2            68              4            0.36

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Evan O'Connor               102            9.7          9.6               15.69
Jim Kneller                   3          100.0          0.2               66.67
Jost Migenda               1639           84.1          0.9                8.72
Segev BenZvi               4341           56.4          7.9               18.84
Spencer Griswold              8          100.0          0.0                0.00
jpkneller                   738           30.1          7.6                9.35
mcolomermolla                10           17.2          0.3               20.00
nuberoi                      51           14.0         15.4               11.76
thomahrens                   23           33.8          2.2                4.35
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03772/joss.03772/10.21105.joss.03772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03772/joss.03772/10.21105.joss.03772.pdf) :page_facing_up: :point_left:

**Comment by apizzuto** [comment]
@whedon commands

**Comment by apizzuto** [comment]
Hi @JostMigenda, thanks for the tweaks to the paper and looking into the install issue. My installation is working now and I checked off everything for the paper in my checklist. I'll work through the examples in the next few days.

**Comment by apizzuto** [comment]
I just had a look at all of the notebooks, and first and foremost, after running through them I have to say I'm really impressed with all of the notebooks and all of the examples that you provided. I had a good time running through all of the different model notebooks and seeing what SNEWPY can do. 
However, I ran into a couple of small problems with some of the notebooks, and I had a request for the organization of the notebooks. These are all outlined in the issue I just opened (https://github.com/SNEWS2/snewpy/issues/113).

I think that I'm close to finishing up my review, but just to keep everyone in the loop – I still want to (1) read through the rest of the API docs to make sure everything looks good, (2) briefly take a glance at the code to make sure all of the functionality claims are verified (although after looking at the notebooks I think it's safe to say that they are) and (3) take a glance at the testing suite

**Comment by JostMigenda** [comment]
As you say, detectors are all implemented in SNOwGLoBES, so that’s not part of SNEWPY. [SNOwGLoBES’ documentation](https://github.com/SNOwGLoBES/snowglobes/tree/master/doc) has info on how to add a detector, though.

Many thanks for the thorough check of example notebooks and tests! I’ll respond in the respective issues.

**Comment by arfon** [comment]
Just an FYI that the DOI for the related AAS publication will be `10.3847/1538-4357/ac350f`

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JostMigenda/JOSSReview. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03772/joss.03772/10.21105.joss.03772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03772/joss.03772/10.21105.joss.03772.pdf) :page_facing_up: :point_left:

**Comment by JostMigenda** [comment]
Thanks @arfon! I’ve updated the paper with the DOI.

**Comment by JostMigenda** [comment]
👋 @PeterDenton — It’s been a couple of weeks since your last activity on this issue. If you got stuck while installing or using SNEWPY, can you please let us know? I’m happy to help to ensure that we can progress with this review!

**Comment by PeterDenton** [comment]
Hi Jost, I'm a bit behind on things, but I should be able to start working
on it this week.

**Comment by JostMigenda** [comment]
For posterity, since I forgot to mention this JOSS review issue in the respective issues:
* SNEWS2/snewpy#145 and SNEWS2/snewpy#146 were opened as part of the review and are fixed already.
* SNEWS2/snewpy#147 is still open, but more of a suggestion so it shouldn’t block progress here—@PeterDenton, I hope I’m not misrepresenting you here!

It looks like both review checklists are completed now. I’ll check if Whedon is happy with the paper.

**Comment by JostMigenda** [comment]
@whedon check references
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.02877 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1088/1367-2630/abde33 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by JostMigenda** [comment]
@whedon generate pdf

(Huh; multiple commands in one post don’t work, apparently?)

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03772/joss.03772/10.21105.joss.03772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03772/joss.03772/10.21105.joss.03772.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@JostMigenda Awesome - thanks for the summary! Give me a few days to do some final checks and edits, then I'll have a couple of small tasks for you before publication. 

@PeterDenton @apizzuto: thank you both for your reviews!! I really appreciate the time and expertise that you donated to this process.

**Comment by dfm** [comment]
@JostMigenda: Thanks for your patience. I've checked in about the formatting issue with the manuscript and we're actually just going to fix that in post production, so for now, we're going to proceed with the final processing. Here are the steps that I'll need from you:

1. Take one last read through the manuscript to make sure that you're happy with it (it's harder to make changes later!), especially the author names and affiliations. I've taken a pass and it looks good to me!
2. Increment the version number of the software and report that version number back here.
3. Create an archived release of that version of the software (using Zenodo or something similar). _Please make sure that the metadata (title and author list) exactly match the paper._ Then report the DOI of the release back to this thread.

Thanks!

**Comment by JostMigenda** [comment]
@dfm I’ve tagged a new version (`v1.1`) and archived it to Zenodo ([DOI:10.5281/zenodo.5719209](https://zenodo.org/record/5719209)). The metadata that’s automatically generated by GitHub isn’t correct; I’ll contact a co-author who has permissions to edit that and will respond here as soon as that’s fixed.

**Comment by whedon** [comment]
OK. v1.1 is the version.

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.5719209 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5719209" target="_blank">10.5281/zenodo.5719209</a> is the archive.

**Comment by dfm** [comment]
@JostMigenda thanks! Just ping me once they have had a chance to update it and I'll get us wrapped up.

**Comment by JostMigenda** [comment]
@dfm We've updated the Zenodo metadata; so go ahead whenever you're ready! 😊

**Comment by dfm** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.02877 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1088/1367-2630/abde33 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2767

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2767, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by dfm** [comment]
This has now been handed off to the EiCs for the final processing, and they may have some remaining edits before publication. But, in the meantime, thanks @JostMigenda, @PeterDenton, and @apizzuto for participating in this process!!

👋 ping @arfon re formatting issues

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1464492837618204675) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2770
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03772](https://doi.org/10.21105/joss.03772)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@apizzuto, @PeterDenton – many thanks for your reviews here and to @dfm  for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@JostMigenda – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03772/status.svg)](https://doi.org/10.21105/joss.03772)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03772">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03772/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03772/status.svg
   :target: https://doi.org/10.21105/joss.03772
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03772/status.svg)](https://doi.org/10.21105/joss.03772)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
