### ISSUE TITLE
[PRE REVIEW]: The jagstargets R package: a reproducible workflow framework for Bayesian data analysis with JAGS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3774]
**Submitting author:** @wlandau (<a href="http://orcid.org/0000-0003-1878-3253">William Landau</a>)
**Repository:** <a href="https://github.com/ropensci/jagstargets" target ="_blank">https://github.com/ropensci/jagstargets</a>
**Version:** 0.0.1
**Editor:** @galessiorob
**Reviewers:** @AoifeHughes, @sachsmc, @JonasMoss, MaaniBeigy
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/759f48d9ae7bc57e318e2d0ecc00569e/status.svg)](https://joss.theoj.org/papers/759f48d9ae7bc57e318e2d0ecc00569e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/759f48d9ae7bc57e318e2d0ecc00569e"><img src="https://joss.theoj.org/papers/759f48d9ae7bc57e318e2d0ecc00569e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/759f48d9ae7bc57e318e2d0ecc00569e/status.svg)](https://joss.theoj.org/papers/759f48d9ae7bc57e318e2d0ecc00569e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @wlandau. **Currently, there isn't an JOSS editor assigned** to your paper.

@wlandau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 352

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (752.5 files/s, 80315.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               26             33            510           1872
SVG                              2              0              0            810
Rmd                              3            126            242            431
JSON                             1              0              0            370
Markdown                        10             94              0            339
YAML                             5             35              0            219
TeX                              2             13              0            136
-------------------------------------------------------------------------------
SUM:                            49            301            752           4177
-------------------------------------------------------------------------------


Statistical information for the repository 'b8c82128968f71b990a0c392' was
gathered on 2021/09/28.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02959 is OK
- 10.21105/joss.03193 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03774/joss.03774/10.21105.joss.03774.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03774/joss.03774/10.21105.joss.03774.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @galessiorob - would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by galessiorob** [comment]
👋 Hi @wlandau 

I am in the process of assigning reviewers to this submission, if you have any suggestions please let me know and feel free to @ mention them here.

Basic checks to go over before we formally start the review:

 - [ ] There’s a general description of the software
           Needs expanding
 - [ ] The software is within the scope as research software
           Potentially to be expanded to denote research application and use cases
 - [ ] OSI-approved license: GNU General Public License (GPL)

**Comment by wlandau-lilly** [comment]
Hi @galessiorob, thanks for reaching out.

> OSI-approved license: GNU General Public License (GPL)

Yes, `jagstargets` is currently under MIT. Does the software need to be switched to GPL for the JOSS manuscript to be considered?

**Comment by wlandau** [comment]
Hi @galessiorob, thanks for reaching out.

> OSI-approved license: GNU General Public License (GPL)

Yes, `jagstargets` is currently under MIT. Does the software need to be switched to GPL for the JOSS manuscript to be considered?

**Comment by galessiorob** [comment]
@wlandau MIT license is just fine 👍

I've emailed several volunteers that I think are a good match for your paper, but feel free to recommend others by mentioning them here. Thanks!

**Comment by galessiorob** [comment]
👋 @wlandau I just sent a fresh batch of invites to review this paper, once we get a second reviewer we can go ahead and start the actual review.

Thanks for the patience!

**Comment by galessiorob** [comment]
@whedon add @sachsmc as reviewer

**Comment by whedon** [comment]
OK, @sachsmc is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @JonasMoss as reviewer

**Comment by whedon** [comment]
OK, @JonasMoss is now a reviewer

**Comment by galessiorob** [comment]
@whedon add MaaniBeigy as reviewer

**Comment by whedon** [comment]
OK, MaaniBeigy is now a reviewer

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3877.
