### ISSUE TITLE
[PRE REVIEW]: Binary-parser: A declarative and efficient parser generator for binary data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3777]
**Submitting author:** @keichi (<a href="http://orcid.org/0000-0002-1607-5694">Keichi Takahashi</a>)
**Repository:** <a href="https://github.com/keichi/binary-parser" target ="_blank">https://github.com/keichi/binary-parser</a>
**Version:** v2.0.1
**Editor:** @majensen
**Reviewers:** @GaurangTandon, @Fil
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ec35c0e3ccc750a5cdab9771e5a6bf21/status.svg)](https://joss.theoj.org/papers/ec35c0e3ccc750a5cdab9771e5a6bf21)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ec35c0e3ccc750a5cdab9771e5a6bf21"><img src="https://joss.theoj.org/papers/ec35c0e3ccc750a5cdab9771e5a6bf21/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ec35c0e3ccc750a5cdab9771e5a6bf21/status.svg)](https://joss.theoj.org/papers/ec35c0e3ccc750a5cdab9771e5a6bf21)
```

**Author instructions**

Thanks for submitting your paper to JOSS @keichi. **Currently, there isn't an JOSS editor assigned** to your paper.

@keichi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (407.9 files/s, 161443.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             6              5              0           4679
JavaScript                      11            213             52           1936
TypeScript                       1            216             12           1284
Markdown                         1             94              0            519
YAML                             2             10              4             50
HTML                             1              2              0             22
Java                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                            23            540             68           8495
-------------------------------------------------------------------------------


Statistical information for the repository '9a7a1ff9fc6c4a97de4866c2' was
gathered on 2021/09/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alasdair Morrison                2            13              5            0.12
Bruce Mitchener                  1            37              2            0.26
Ericbla                          2           131              2            0.89
Fabian Wiles                     7           842           1595           16.35
HUANG Wei                        1            22              0            0.15
Joshua Gross                     2            25              5            0.20
Keichi Takahashi               100          6428           4421           72.81
Maxime Carey                     1            14              9            0.15
Mohamed Akram                    2            79             50            0.87
Pedro Pérez Furio                3           269             13            1.89
Sam Petersen                     1             3              0            0.02
Simran                           1             1              1            0.01
Trevor Manz                      3            20             22            0.28
Ulric Wilfred                    4           394             43            2.93
Yu Shimura                       1             2              8            0.07
abductedPlatypus                 4           147             92            1.60
ddaf                             4            84              4            0.59
joshuadutton                     1             7              2            0.06
matw                             1            20              1            0.14
nhjm449                          1            83              1            0.56
szaboge                          1             2              2            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bruce Mitchener               8           21.6         83.1                0.00
Ericbla                      38           29.0         44.4                0.00
Fabian Wiles                160           19.0         27.9                2.50
HUANG Wei                     7           31.8         77.4                0.00
Joshua Gross                  3           12.0         70.8                0.00
Keichi Takahashi           1622           25.2         19.3                2.28
Mohamed Akram                20           25.3         17.6                0.00
Pedro Pérez Furio           107           39.8          3.6                0.00
Ulric Wilfred               113           28.7         59.2               27.43
abductedPlatypus             88           59.9          5.7                0.00
ddaf                         16           19.0         80.7                0.00
joshuadutton                  1           14.3         49.2                0.00
nhjm449                      23           27.7         49.2                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3777 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/SPW.2014.31 is OK
- 10.1109/SPW.2015.31 is OK
- 10.1109/SPW.2014.35 is OK
- 10.1017/S0956796898003050 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03777/joss.03777/10.21105.joss.03777.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03777/joss.03777/10.21105.joss.03777.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @Bisaloo - you were suggested by the author to edit this submission. Are you able to do so?

**Comment by danielskatz** [comment]
@whedon invite @Bisaloo as editor

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by Bisaloo** [comment]
Hi @danielskatz, I don't think I'm a good fit for this submission. It's pretty far from my area of expertise, both in terms of scope and language. I'll refine my profile in the editor list accordingly.

**Comment by danielskatz** [comment]
Ok, thanks - this one is a bit tough to find the right person

**Comment by danielskatz** [comment]
👋 @noatamir - do you think you would be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @noatamir as editor

**Comment by whedon** [comment]
@noatamir has been invited to edit this submission.

**Comment by noatamir** [comment]
I'm in a similar position to @Bisaloo I'm afraid..

**Comment by kyleniemeyer** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by keichi** [comment]
Hi @majensen, thanks for editing this paper. I would like to confirm if there is anything I should do from my side?

**Comment by majensen** [comment]
@keichi my apologies, work is getting in the way of the important stuff. I am working on getting reviewers for your paper. Can you make any suggestions? Much appreciated-

**Comment by keichi** [comment]
Going through the list of reviewers, it seems GaurangTandon and Milantex are a good fit for the topic of this paper. I can suggest more if needed.

**Comment by majensen** [comment]
@GaurangTandon would you be available to review [this work](#3777) for [JOSS](https://joss.theoj.org)? We could really benefit from your expertise. Please have a look at the [reviewer information](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Thanks for your consideration! -@majensen

**Comment by majensen** [comment]
@Milantex - would you have time and interest to review [this work](#3777) for [https://joss.theoj.org](JOSS)? We would really appreciate your expertise. Please have a look at the [reviewer information](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and let me know in this thread. Thanks for your consideration! -@majensen

**Comment by GaurangTandon** [comment]
@majensen Sure, I'd be happy to do a review.

**Comment by majensen** [comment]
@whedon assign @GaurangTandon as reviewer

**Comment by whedon** [comment]
OK, @GaurangTandon is now a reviewer

**Comment by majensen** [comment]
@Fil - would you be able to review [this work](#3777) for [JOSS](https://joss.theoj.org)? Your JS expertise would be very helpful. Thanks for your consideration - -@majensen

**Comment by Fil** [comment]
Can do!

**Comment by majensen** [comment]
@whedon add @Fil as reviewer

**Comment by whedon** [comment]
OK, @Fil is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3940.

**Comment by majensen** [comment]
@GaurangTandon @Fil thanks so much for helping review @keichi 's work. The review has now begun over in issue #3940.
