### ISSUE TITLE
[PRE REVIEW]: robustHD: An R package for robust regression with high-dimensional data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3779]
**Submitting author:** @aalfons (<a href="http://orcid.org/0000-0002-2513-3788">Andreas Alfons</a>)
**Repository:** <a href="https://github.com/aalfons/robustHD/" target ="_blank">https://github.com/aalfons/robustHD/</a>
**Version:** 0.7.0
**Editor:** @mikldk
**Reviewers:** @valentint, @msalibian
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3929d5aaa6df61cea6e470253df4a258/status.svg)](https://joss.theoj.org/papers/3929d5aaa6df61cea6e470253df4a258)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3929d5aaa6df61cea6e470253df4a258"><img src="https://joss.theoj.org/papers/3929d5aaa6df61cea6e470253df4a258/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3929d5aaa6df61cea6e470253df4a258/status.svg)](https://joss.theoj.org/papers/3929d5aaa6df61cea6e470253df4a258)
```

**Author instructions**

Thanks for submitting your paper to JOSS @aalfons. **Currently, there isn't an JOSS editor assigned** to your paper.

@aalfons if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1545

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (1250.5 files/s, 184250.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               54            566           3707           3816
C++                              8            139            699           1261
Markdown                         2             66              0            253
TeX                              1             14              0            137
C/C++ Header                     8             46             60             95
C                                1              3              1             40
-------------------------------------------------------------------------------
SUM:                            74            834           4467           5602
-------------------------------------------------------------------------------


Statistical information for the repository '69652df2ac313c35c895555d' was
gathered on 2021/09/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andreas Alfons                  45          4408           2075          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andreas Alfons             2344           53.2         92.2               34.56
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1198/016214507000000950 may be a valid DOI for title: Robust Linear Model Selection Based on Least Angle Regression
- 10.1214/12-aoas575 may be a valid DOI for title: Sparse Least Trimmed Squares Regression for Analyzing High-Dimensional Large Data Sets
- 10.1016/j.csda.2015.02.007 may be a valid DOI for title: Robust Groupwise Least Angle Regression
- 10.1016/j.csda.2017.02.002 may be a valid DOI for title: Robust and Sparse Estimators for Linear Regression Models
- 10.1016/j.chemolab.2017.11.017 may be a valid DOI for title: Robust and Sparse Estimation Methods for High-Dimensional Linear and Logistic Regression
- 10.1080/00401706.2017.1305299 may be a valid DOI for title: Robust Lasso Regression Using Tukey’s Biweight Criterion
- 10.1214/19-aoas1269 may be a valid DOI for title: Robust Elastic Net Estimators for Variable Selection and Identification of Proteomic Biomarkers
- 10.21203/rs.2.15653/v3 may be a valid DOI for title: Dysbiosis, Gut Barrier Dysfunction and Inflammation in Dementia: A Pilot Study
- 10.3389/fevo.2020.583831 may be a valid DOI for title: Chironomidae Morphological Types and Functional Feeding Groups as a Habitat Complexity Vestige

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03779/joss.03779/10.21105.joss.03779.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03779/joss.03779/10.21105.joss.03779.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @aalfons - while we find an editor, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @mikldk - would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @mikldk as editor

**Comment by aalfons** [comment]
@danielskatz - My apologies, I added the DOI URL's instead of just the DOI's. I updated the bib file and I'll try again now to see if I did it correctly.

**Comment by aalfons** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1198/016214507000000950 is OK
- 10.1214/12-AOAS575 is OK
- 10.1016/j.csda.2015.02.007 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.1016/j.csda.2017.02.002 is OK
- 10.1016/j.chemolab.2017.11.017 is OK
- 10.1080/00401706.2017.1305299 is OK
- 10.1214/19-AOAS1269 is OK
- 10.1186/s12877-020-01644-2 is OK
- 10.3389/fevo.2020.583831 is OK
- 10.1158/0008-5472.can-12-1370 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by aalfons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03779/joss.03779/10.21105.joss.03779.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03779/joss.03779/10.21105.joss.03779.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@aalfons - thank you for the submission.

Do you have any suggestions for reviewers ([here](https://bit.ly/joss-reviewers) is a list of potential reviewers)?

**Comment by aalfons** [comment]
**msalibian** is an expert in the field and one of the authors of the `pense` package, which I mention in the *Related software* section. He's on the list of potential reviewers you sent.

**ineswilms** is also an expert on robust statistics and high-dimensional data. But I have to mention that I recently started a project with her. We have not collaborated earlier, and the joint project is not related to the submitted work. If this is a conflict of interest, I can suggest someone else.

**Comment by mikldk** [comment]
@aalfons Thanks for your suggestions. I would appreciate if you could suggest an alternative to ineswilms for the reasons you mention, thanks.

**Comment by aalfons** [comment]
@mikldk - sure: **valentint** is one of the authors of the `robustbase` package, which is the main package on robust statistics in R, and he has also written the package `rrcovHD` which contains functionality such as PCA and outlier detection in high dimensions.

**Comment by mikldk** [comment]
@aalfons. Thanks. A few comments before I invite the reviewers:

- [ ] Can you add your country to the paper (in addition to "Rrasmus School of Economics, Erasmus University Rotterdam")?
- [ ] Figure 1: Change `lambda` to `expression(lambda)`
- [ ] The paper is fairly long (see [here](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)); maybe move some examples to a `README.Rmd` (that is then compiled to `README.md`)?

**Comment by aalfons** [comment]
**Point 1)** Done.

**Point 2)** I deliberately used `lambda` in Figure 1 to maintain the connection with argument `lambda` of function `sparseLTS()`. However, if you prefer me to use `expression(lambda)`, I can change that.

**Point 3)** When I checked the word count in `paper.md` with RStudio before submission, I got 1017 words excluding the metadata, so I was hoping it would still be ok. I designed the two examples to show off most of the functionality of the package (regularization, stepwise variable selection along a sequence, model selection via prediction error and via information criterion, examples of plots) in a rather compact form (6 pages including references). But if you prefer, I can remove the second example (robust groupwise least angle regression) from the paper. In that case I would still put *both examples* in `README.Rmd`, to keep the set of examples (that shows off most functionality) together in one place.

@mikldk - please let me know what you think and I'll make the changes accordingly.

**Comment by mikldk** [comment]
@aalfons Thanks. Ad 2: Fine with me :+1:. Ad 3: Let's hear what the reviewers say. Anyway, I think it would be nice to have the examples in the `README`, too.

**Comment by mikldk** [comment]
@msalibian, @valentint: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by aalfons** [comment]
@mikldk - great, thanks! I'll add the examples in the `README` either way. I'll recompile the paper now to have the updated address in there.

**Comment by aalfons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03779/joss.03779/10.21105.joss.03779.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03779/joss.03779/10.21105.joss.03779.pdf) :page_facing_up: :point_left:

**Comment by msalibian** [comment]
@mikldk Yes. Sorry I forget if there's anything specific I need to do here to accept. Pls let me know.

**Comment by aalfons** [comment]
@mikldk - The two examples from the paper are now included in `README` as well.

@msalibian - Thanks for agreeing to review the paper!

**Comment by mikldk** [comment]
@msalibian, @valentint Thanks. No, not yet. I'll create a review issue and the you'll get an invite that you must accept.

**Comment by mikldk** [comment]
@whedon assign @valentint as reviewer

**Comment by whedon** [comment]
OK, @valentint is now a reviewer

**Comment by mikldk** [comment]
@whedon add @msalibian as reviewer

**Comment by whedon** [comment]
OK, @msalibian is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3786.
