### ISSUE TITLE
[PRE REVIEW]: Finch: MinHashing for Sequencing Data with Abundance Calculation and Adaptive Filtering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#378]
**Submitting author:** @bovee (<a href="http://orcid.org/0000-0002-8819-9549">Roderick Boveee</a>)
**Repository:** <a href="https://github.com/onecodex/finch-rs" target ="_blank">https://github.com/onecodex/finch-rs</a>
**Version:** v0.1.2
**Editor:** @biorelated
**Reviewer:** @HadrienG 

**Author instructions**

Thanks for submitting your paper to JOSS @bovee. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bovee if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by boydgreenfield** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@biorelated @mgymrek would either of you be willing to edit this submission for JOSS?

**Comment by bovee** [comment]
Just checking in; is there anything we can do to help this submission along?

**Comment by arfon** [comment]
@bovee - apologies for the delay here. We're struggling a little to find an editor to handle this submission.

@pjotrp - any chance you'd be willing to edit this one?

**Comment by biorelated** [comment]
@arfon happy to edit this.

**Comment by arfon** [comment]
> @arfon happy to edit this.

🎉 thanks @biorelated

**Comment by arfon** [comment]
@whedon assign @biorelated as editor

**Comment by whedon** [comment]
OK, the editor is @biorelated

**Comment by bovee** [comment]
@arfon @biorelated Thanks!

**Comment by boydgreenfield** [comment]
@biorelated Thanks for offering to be the editor! I appreciate that this falls into your (probably quite limited) spare time, but have you had a chance to take a look yet? Please don't hesitate to ping me or @bovee if we can help in any way.

**Comment by arfon** [comment]
@biorelated - how are you getting along finding a reviewer for this submission?

**Comment by biorelated** [comment]
@arfon @boydgreenfield @bovee  My sincere apologies for this delay. I have not had a reviewer for this. I am happy for another editor to take it. Meanwhile I will contact a couple more reviewers. Thanks.

**Comment by biorelated** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by biorelated** [comment]
@HadrienG @JaroslavHron Would you mind reviewing this publication us? 
Thank you.

**Comment by HadrienG** [comment]
@biorelated I'd be happy to review this.

**Comment by biorelated** [comment]
@whedon assign @HadrienG  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @HadrienG

**Comment by biorelated** [comment]
@whedon start review magic-word=banana

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by biorelated** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/505. Feel free to close this issue now!

**Comment by biorelated** [comment]
Thank you @HadrienG for agreeing to take time to review this work. Please let me know if there any issues or concerns. The review is on #505.
