### ISSUE TITLE
[REVIEW]:  spectrapepper: A Python toolbox for advanced analysis of spectroscopic data for materials and devices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3781]
**Submitting author:** @enricgrau (<a href="http://orcid.org/0000-0002-8357-5824">Enric Grau-Luque</a>)
**Repository:** <a href="https://github.com/spectrapepper/spectrapepper" target ="_blank">https://github.com/spectrapepper/spectrapepper</a>
**Version:** 0.1.3
**Editor:** @rkurchin
**Reviewer:** @stuartcampbell, @ksunden
**Archive:** <a href="https://doi.org/10.5281/zenodo.5708435" target="_blank">10.5281/zenodo.5708435</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0/status.svg)](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0"><img src="https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0/status.svg)](https://joss.theoj.org/papers/d65c85c8917de62f951050c3deaa85f0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/spectrapepper/spectrapepper" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@stuartcampbell & @ksunden, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @rkurchin know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @stuartcampbell
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/spectrapepper/spectrapepper">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/spectrapepper/spectrapepper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@enricgrau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @ksunden
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/spectrapepper/spectrapepper">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/spectrapepper/spectrapepper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@enricgrau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete? (See spectrapepper/spectrapepper#3)
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @stuartcampbell, @ksunden it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 884

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.solmat.2015.12.036 is OK
- 10.1038/s41598-017-01381-4 is OK
- 10.1039/c9ta03625c is OK
- 10.1063/1.5061809 is OK
- 10.1002/PIP.541 is OK
- 10.1039/d1ta01299a is OK
- 10.1002/aenm.201903242 is OK
- 10.1016/j.respol.2005.12.006 is OK
- 10.1002/9781119148739.ch4 is OK
- 10.1016/j.joule.2018.05.009 is OK
- 10.1039/d0ee02838j is OK
- 10.1039/c9ta02356a is OK
- 10.1038/s41586-018-0337-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/ZENODO.4681666 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/ZENODO.4743323 is OK
- 10.1177/0003702819839098 is OK
- 10.1016/j.chemolab.2018.06.009 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/1593511 is INVALID
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (301.9 files/s, 203317.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      17           4513           4497          17139
HTML                            11           1976             33           5174
SVG                              1              0              0           2671
Python                          10            762            880           1786
XML                              1              0              2           1618
CSS                              4            191             35            757
TeX                              1             40              0            335
Markdown                         4             41              0            163
YAML                             7             18              9            163
reStructuredText                 7             89             55            147
JSON                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            64           7630           5511          29959
-------------------------------------------------------------------------------


Statistical information for the repository '78a4a889db4b38b5652b2815' was
gathered on 2021/09/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Enric Tomas Grau Luq            60        111899          82323          100.00
unknown                          1             3              2            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Enric Tomas Grau Luq      29577           26.4          2.8               16.06
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: :point_left:

**Comment by rkurchin** [comment]
☝️ note to @enricgrau to fix that invalid DOI issue at some point (not urgent, but will need to be done eventually)

**Comment by enricgrau** [comment]
> ☝️ note to @enricgrau to fix that invalid DOI issue at some point (not urgent, but will need to be done eventually)

Thank you for the note @rkurchin. I've fixed the issue in the .bib file and push the changes into the repository. Any other actions I should take? Thank you again.

**Comment by rkurchin** [comment]
@whedon generate pdf

That's all! It should rerun the checks again and verify...

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references

@rkurchin - this is how to run the checks - doing that and generating the pdf are separate commands

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.solmat.2015.12.036 is OK
- 10.1038/s41598-017-01381-4 is OK
- 10.1039/c9ta03625c is OK
- 10.1063/1.5061809 is OK
- 10.1002/PIP.541 is OK
- 10.1039/d1ta01299a is OK
- 10.1002/aenm.201903242 is OK
- 10.1016/j.respol.2005.12.006 is OK
- 10.1002/9781119148739.ch4 is OK
- 10.1016/j.joule.2018.05.009 is OK
- 10.1039/d0ee02838j is OK
- 10.1039/c9ta02356a is OK
- 10.1038/s41586-018-0337-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/ZENODO.4681666 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/ZENODO.4743323 is OK
- 10.1177/0003702819839098 is OK
- 10.1016/j.chemolab.2018.06.009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rkurchin** [comment]
Haha oops, thanks @danielskatz; I would've remembered that eventually but you beat me to it ;)

Anyway, @enricgrau, DOI's look good 👍

**Comment by enricgrau** [comment]
@rkurchin I just realize there is an author missing and reuploaded the .md file with the added author missing. Let me know if this is fine or I should roll it back and dot it later on. Thank you!

**Comment by rkurchin** [comment]
@whedon generate pdf

Nope, that's fine! I'll just regenerate it here and you can double-check that it all looks good...

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: :point_left:

**Comment by enricgrau** [comment]
> Nope, that's fine! I'll just regenerate it here and you can double-check that it all looks good...

Thank you @rkurchin. The proof looks good!

**Comment by rkurchin** [comment]
👋 @stuartcampbell @ksunden reminder to get your reviews started!

**Comment by rkurchin** [comment]
👋 Hi @stuartcampbell and @ksunden, just checking in on the status of this!

**Comment by enricgrau** [comment]
@stuartcampbell Thank you for your feedback. We will look into integrating more automated testing progressively and also include some bullet points for this on the contribution guidelines with the following updates.

**Comment by ksunden** [comment]
Modulo using the preferred matplotlib citation ([PR submitted](https://github.com/spectrapepper/spectrapepper/pull/8)), I'm ready to sign off on my part.

I do encourage the authors to take a look at implementation of some of their core routines: while performance considerations are not claims made and thus not directly evaluated, there are many instances in the codebase where bare python for loops are used for common calculations such as sums/means. These could be replaced by calls to the appropriate numpy/scipy function (perhaps with an `axis` argument) which would likely be both more performant and easier to read.

Even some of the higher level statistic implemented in this package with pure python are available from scipy, which is already a dependency anyway (this includes the spearman and pearson correlation, though the scipy implementation may not be the desired API for this use case, the numeric computation is the same).

I agree with Stuart that additional testing would be nice, but the most important parts are covered.

I think the documentation would benefit from some additional narrative, as well as including the plots generated by the provided examples.

**Comment by enricgrau** [comment]
@ksunden Thank you for your valuable insights. 

Indeed, we don't make any performance claims, however, with your advice we will better look at the codebase to replace common calculations by proper numpy/scipy functions. Hopefully for a v0.2.0 we can make performance claims.

As you correctly point out, we do include some functions that are already available on other libraries. This is intentional since we believe that having one single library that encloses all this common practices of the field will make it easier for non-experienced users and also allows us to adapt the input and output format that better suite these particular workflows. The latter also reinforces the need for us to make better descriptions of the functions and examples, as you also mention. We will improve this with following versions and include guidelines for good narrratives in the future.

**Comment by rkurchin** [comment]
Thanks again everyone for the thoughtful engagement on this submission! @enricgrau, leave a comment here when you've fixed that citation and we can start finalizing! 😃

**Comment by enricgrau** [comment]
@rkurchin The citation is fixed, both `.bib` and `.md` files are now updated. Thank you!

**Comment by rkurchin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: :point_left:

**Comment by rkurchin** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.solmat.2015.12.036 is OK
- 10.1038/s41598-017-01381-4 is OK
- 10.1039/c9ta03625c is OK
- 10.1063/1.5061809 is OK
- 10.1002/PIP.541 is OK
- 10.1039/d1ta01299a is OK
- 10.1002/aenm.201903242 is OK
- 10.1016/j.respol.2005.12.006 is OK
- 10.1002/9781119148739.ch4 is OK
- 10.1016/j.joule.2018.05.009 is OK
- 10.1039/d0ee02838j is OK
- 10.1039/c9ta02356a is OK
- 10.1038/s41586-018-0337-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/ZENODO.4681666 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1177/0003702819839098 is OK
- 10.1016/j.chemolab.2018.06.009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rkurchin** [comment]
I opened https://github.com/spectrapepper/spectrapepper/pull/9 with a few editorial tweaks to the manuscript

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03781/joss.03781/10.21105.joss.03781.pdf) :page_facing_up: :point_left:

**Comment by enricgrau** [comment]
> I opened [spectrapepper/spectrapepper#9](https://github.com/spectrapepper/spectrapepper/pull/9) with a few editorial tweaks to the manuscript

@rkurchin Thank you for your suggested tweaks. We believe they do improve the way the manuscript reads and, with just a couple of exceptions, where approved and merged.

**Comment by rkurchin** [comment]
Great! The next steps are:
1. Create a new tagged release and comment here with the version number
2. Create an archive of the package (e.g. on Zenodo or figshare) with matching metadata (title, authors, etc.) to this submission and report the associated DOI here
And then we'll be ready to proceed with publication! 🎉

**Comment by rkurchin** [comment]
👆 @enricgrau, just checking in on this. We're nearly ready to publish!

**Comment by enricgrau** [comment]
@rkurchin Sorry for the delay. The archive of version `0.1.3` was created on Zenodo with DOI: 10.5281/zenodo.5708435 and matching metadata. Thank you!

**Comment by rkurchin** [comment]
@whedon set 0.1.3 as version

**Comment by whedon** [comment]
OK. 0.1.3 is the version.

**Comment by rkurchin** [comment]
@whedon set 10.5281/zenodo.5708435 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5708435" target="_blank">10.5281/zenodo.5708435</a> is the archive.

**Comment by rkurchin** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.solmat.2015.12.036 is OK
- 10.1038/s41598-017-01381-4 is OK
- 10.1039/c9ta03625c is OK
- 10.1063/1.5061809 is OK
- 10.1002/PIP.541 is OK
- 10.1039/d1ta01299a is OK
- 10.1002/aenm.201903242 is OK
- 10.1016/j.respol.2005.12.006 is OK
- 10.1002/9781119148739.ch4 is OK
- 10.1016/j.joule.2018.05.009 is OK
- 10.1039/d0ee02838j is OK
- 10.1039/c9ta02356a is OK
- 10.1038/s41586-018-0337-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/ZENODO.4681666 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1177/0003702819839098 is OK
- 10.1016/j.chemolab.2018.06.009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2756

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2756, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1461669094160314373) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2757
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03781](https://doi.org/10.21105/joss.03781)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@stuartcampbell, @ksunden – many thanks for your reviews here and to @rkurchin for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@enricgrau – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03781/status.svg)](https://doi.org/10.21105/joss.03781)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03781">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03781/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03781/status.svg
   :target: https://doi.org/10.21105/joss.03781
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03781/status.svg)](https://doi.org/10.21105/joss.03781)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
