### ISSUE TITLE
[REVIEW]: EDO.js: A comprehensive JavaScript library for interaction with musical set theory in any tuning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3784]
**Submitting author:** @MichaelSel (<a href="http://orcid.org/0000-0002-6061-0674">Michael Seltenreich</a>)
**Repository:** <a href="https://github.com/MichaelSel/edoJS" target ="_blank">https://github.com/MichaelSel/edoJS</a>
**Version:** v1.2.13
**Editor:** @bmcfee
**Reviewer:** @napulen, @albincorreya
**Archive:** <a href="https://doi.org/10.5281/zenodo.5705161" target="_blank">10.5281/zenodo.5705161</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec/status.svg)](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec"><img src="https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec/status.svg)](https://joss.theoj.org/papers/ac6a3995ef216d89f442801412c252ec)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MichaelSel/edoJS" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@napulen & @albincorreya, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @bmcfee know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @napulen
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/MichaelSel/edoJS">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MichaelSel/edoJS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@MichaelSel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @albincorreya
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/MichaelSel/edoJS">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MichaelSel/edoJS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@MichaelSel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] #3826
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @napulen, @albincorreya it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 698

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/745935 is OK

MISSING DOIs

- 10.1007/978-1-4684-8917-0_17 may be a valid DOI for title: The Pitch Set as a Level of Description for Studying Musical Pitch Perception
- 10.2307/843809 may be a valid DOI for title: Coordination of interval sizes in seven-tone collections
- 10.1121/1.4777600 may be a valid DOI for title: Auditory roughness estimation of complex spectra—Roughness degrees and dissonance ratings of harmonic intervals revisited
- 10.1080/17459730701376743 may be a valid DOI for title: Coherence and sameness in well-formed and pairwise well-formed scales
- 10.2307/j.ctt1xp3t38.20 may be a valid DOI for title: The structure of atonal music

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (346.4 files/s, 329497.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            41          30009             98          22045
JavaScript                      22           2398          10706          10374
CSS                              5            181             57            859
Markdown                         2             35              0             90
JSON                             2              3              0             71
TeX                              1              8              0             66
XML                              7              0              0             56
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            81          32634          10861          33562
-------------------------------------------------------------------------------


Statistical information for the repository 'f3291fc4aa7d2ee118ee8934' was
gathered on 2021/09/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael                        112         33473          12405           92.52
MichaelSel                       6          3060            649            7.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael                   22733           67.9          9.2               47.88
MichaelSel                  746           24.4         11.3               10.32
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
PDF failed to compile for issue #3784 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 4, column 3):
unexpected "T"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
PDF failed to compile for issue #3784 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 77, column 3):
unexpected "t"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

```

**Comment by MichaelSel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: :point_left:

**Comment by bmcfee** [comment]
Hi @MichaelSel, I want to make sure we A) don't lose the thread on this, and B) are mindful of our reviewer's time and attention.  There's no rush or pressure on this from the JOSS side. If you have a sense of when you expect to have these issues resolved, we can have whedon set a reminder to come back in X weeks.  Thanks!

**Comment by MichaelSel** [comment]
Hi @bmcfee, as far as I am aware I have responded and incorporated all of the reviewers comments already.

**Comment by napulen** [comment]
Hi @bmcfee @MichaelSel, on my end, I need to run the unit tests locally before closing the issue. I'll try to get that sorted out tonight. All other blocking items on my end are closed.

**Comment by napulen** [comment]
I was unfortunately unable to run the tests locally without some further reading/scripts. It should be an easy fix though, I left the relevant comments in the issue https://github.com/MichaelSel/edoJS/issues/8, plus an additional issue about a deprecated `npm` flag.

**Comment by MichaelSel** [comment]
I believe this is now resolved. I'll leave it up to Néstor to make the
final call.

**Comment by napulen** [comment]
Confirming that all my issues have been resolved.

**Comment by bmcfee** [comment]
Thanks @napulen !

@albincorreya where does that leave you on remaining issues?

**Comment by MichaelSel** [comment]
> Thanks, @bmcfee for your inputs! I agree with you on that. So, I am good with everything about this submission. @MichaelSel My suggestions in my previous comment can be considered optional.

@bmcfee I believe he already confirmed he is okaying everything (see above). I may have misunderstood.

**Comment by bmcfee** [comment]
@MichaelSel His review still has a few unchecked boxes - I was interpreting his prior comment as referring to some of the "stretch goal" issues, but he can clarify.

**Comment by MichaelSel** [comment]
@bmcfee No problem

**Comment by albincorreya** [comment]
@bmcfee Confirming all the issues except the automated CI pipeline has been resolved. Since the CI pipeline is not a must-have, I let @MichaelSel make the call. He will work on it during future iterations of the project. Thus not blocking this review as I understand.

**Comment by bmcfee** [comment]
@albincorreya Would you mind updating the review checklist then?  We can move on when the checklist is complete.

**Comment by albincorreya** [comment]
@bmcfee done!

**Comment by bmcfee** [comment]
Thanks @albincorreya !  It's not showing up on my side though.  Very weird.

**Comment by bmcfee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: :point_left:

**Comment by bmcfee** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/745935 is OK

MISSING DOIs

- 10.1007/978-1-4684-8917-0_17 may be a valid DOI for title: The Pitch Set as a Level of Description for Studying Musical Pitch Perception
- 10.2307/843809 may be a valid DOI for title: Coordination of interval sizes in seven-tone collections
- 10.1121/1.4777600 may be a valid DOI for title: Auditory roughness estimation of complex spectra—Roughness degrees and dissonance ratings of harmonic intervals revisited
- 10.1080/17459730701376743 may be a valid DOI for title: Coherence and sameness in well-formed and pairwise well-formed scales
- 10.2307/j.ctt1xp3t38.20 may be a valid DOI for title: The structure of atonal music

INVALID DOIs

- None
```

**Comment by bmcfee** [comment]
@MichaelSel things look generally good with the draft and the repo.  A couple of final to-dos for you:

1. Fix the missing DOI's in your references (see whedon comment above)
2. Create a new tag and release of the software incorporating changes made during the review.  (If it's already up to date, you can skip this step.)
3. Deposit the (new) release at an archive such as Zenodo or Figshare, and report back here with the DOI.  We'll use that to link the JOSS paper to the archived software version.

**Comment by MichaelSel** [comment]
@whedon <https://github.com/whedon> check references

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by MichaelSel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-4684-8917-0_17 is OK
- 10.2307/745935 is OK
- 10.2307/843809 is OK
- 10.1121/1.4777600 is OK
- 10.1093/acprof:oso/9780195178296.001.0001 is OK
- 10.1080/17459730701376743 is OK

MISSING DOIs

- 10.2307/j.ctt1xp3t38.20 may be a valid DOI for title: The structure of atonal music

INVALID DOIs

- None
```

**Comment by MichaelSel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-4684-8917-0_17 is OK
- 10.2307/745935 is OK
- 10.2307/843809 is OK
- 10.1121/1.4777600 is OK
- 10.1093/acprof:oso/9780195178296.001.0001 is OK
- 10.1080/17459730701376743 is OK

MISSING DOIs

- 10.2307/j.ctt1xp3t38.20 may be a valid DOI for title: The structure of atonal music

INVALID DOIs

- None
```

**Comment by MichaelSel** [comment]
@bmcfee, Hi Brian. 
I updated the DOIs of everything with the exception of Allan Forte's book "The Structure of Tonal Music" which doesn't seem to have a DOI listen anywhere. I did include its ISBN instead. The DOI whedon proposes is the wrong one. 

I put a release on the repository and uploaded that to Zenodo. The DOI generated for that is 10.5281/zenodo.5705161
Here is the Zenodo record: https://zenodo.org/record/5705161

Please let me know if there anything you like me to do. 

Thanks!

**Comment by bmcfee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: :point_left:

**Comment by bmcfee** [comment]
@MichaelSel thanks!

It looks like you're missing a DOI for music21, which ought to be https://doi.org/10.5281/zenodo.1416113

Everything else looks okay to me.

**Comment by bmcfee** [comment]
@whedon set 10.5281/zenodo.5705161 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5705161" target="_blank">10.5281/zenodo.5705161</a> is the archive.

**Comment by MichaelSel** [comment]
@bmcfee oopsie! You're right. Added the Music21 DOI. Sorry about that.

**Comment by bmcfee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03784/joss.03784/10.21105.joss.03784.pdf) :page_facing_up: :point_left:

**Comment by bmcfee** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-4684-8917-0_17 is OK
- 10.2307/745935 is OK
- 10.2307/843809 is OK
- 10.1121/1.4777600 is OK
- 10.1093/acprof:oso/9780195178296.001.0001 is OK
- 10.1080/17459730701376743 is OK
- 10.5281/zenodo.1416114 is OK

MISSING DOIs

- 10.2307/j.ctt1xp3t38.20 may be a valid DOI for title: The structure of atonal music

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2752

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2752, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by MichaelSel** [comment]
@bmcfee Looks good to me.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1460866742771671041) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2753
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03784](https://doi.org/10.21105/joss.03784)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@napulen, @albincorreya – many thanks for your reviews here and to @bmcfee for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@MichaelSel  – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03784/status.svg)](https://doi.org/10.21105/joss.03784)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03784">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03784/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03784/status.svg
   :target: https://doi.org/10.21105/joss.03784
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03784/status.svg)](https://doi.org/10.21105/joss.03784)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by bmcfee** [comment]
Congrats @MichaelSel and thanks again to @napulen and @albincorreya !

**Comment by napulen** [comment]
Congrats @MichaelSel !
