### ISSUE TITLE
[PRE REVIEW]: Json2Xlsx: PHP library for extraction and visualization of data in a spreadsheet

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3787]
**Submitting author:** @scheiblr (<a href="http://orcid.org/0000-0003-2067-5569">Raphael Scheible</a>)
**Repository:** <a href="https://github.com/scheiblr/Json2Xlsx" target ="_blank">https://github.com/scheiblr/Json2Xlsx</a>
**Version:** v0.5.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a1ee576da731cd8a0afea306c0542942/status.svg)](https://joss.theoj.org/papers/a1ee576da731cd8a0afea306c0542942)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a1ee576da731cd8a0afea306c0542942"><img src="https://joss.theoj.org/papers/a1ee576da731cd8a0afea306c0542942/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a1ee576da731cd8a0afea306c0542942/status.svg)](https://joss.theoj.org/papers/a1ee576da731cd8a0afea306c0542942)
```

**Author instructions**

Thanks for submitting your paper to JOSS @scheiblr. **Currently, there isn't an JOSS editor assigned** to your paper.

@scheiblr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (415.4 files/s, 62415.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             2              0              0           1119
SQL                              5             13             37            800
PHP                              6            135            172            438
Markdown                         3             21              0             67
Bourne Shell                     2              6              1             29
YAML                             1              3              2             12
-------------------------------------------------------------------------------
SUM:                            19            178            212           2465
-------------------------------------------------------------------------------


Statistical information for the repository '78529e40bbf83ae15f265717' was
gathered on 2021/10/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Raphael Scheible                 6          1364            514          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Raphael Scheible            850           62.3          0.4                4.35
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3787 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03787/joss.03787/10.21105.joss.03787.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03787/joss.03787/10.21105.joss.03787.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fimmu.2018.00543 is OK
- 10.1093/bioinformatics/btz525 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hello @scheiblr, unfortunately after review of the JOSS editorial board, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by scheiblr** [comment]
Thank you very much for looking into it and the fast reply. Just for me to know better, what is acceptable for JOSS: what exactly did not match the requirements?

**Comment by scheiblr** [comment]
Thanks for the clarification! And again, thank you very much for taking all the time!
