### ISSUE TITLE
[PRE REVIEW]: SISSO++: A C++ Implementation of the Sure Independence Screening and Sparisifying Operator Approach

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3788]
**Submitting author:** @tpurcell90 (<a href="http://orcid.org/0000-0003-4564-7206">Thomas Purcell</a>)
**Repository:** <a href="https://gitlab.com/sissopp_developers/sissopp" target ="_blank">https://gitlab.com/sissopp_developers/sissopp</a>
**Version:** v1.0.0
**Editor:** @jarvist
**Reviewers:** @ml-evs, @AstroBarker
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/72b4c8d40d9a0401039ade39a7801759/status.svg)](https://joss.theoj.org/papers/72b4c8d40d9a0401039ade39a7801759)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/72b4c8d40d9a0401039ade39a7801759"><img src="https://joss.theoj.org/papers/72b4c8d40d9a0401039ade39a7801759/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/72b4c8d40d9a0401039ade39a7801759/status.svg)](https://joss.theoj.org/papers/72b4c8d40d9a0401039ade39a7801759)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tpurcell90. **Currently, there isn't an JOSS editor assigned** to your paper.

@tpurcell90 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 756

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.43 s (1071.9 files/s, 180467.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                            149           4960           3014          29071
C/C++ Header                    81           2657          13448           7235
Python                         125           1926           1948           6285
Markdown                        13            336              0           1937
CMake                           16            244            627           1396
JSON                            21              0              0            398
reStructuredText                41            227            507            290
TeX                              1              2              0            289
YAML                             1             15              0            197
TOML                             1             11              1             51
MATLAB                           3             12             23             44
Dockerfile                       1             12              2             33
DOS Batch                        1              8              1             26
Bourne Shell                     4              1              0             24
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           459          10415          19578          47285
-------------------------------------------------------------------------------


Statistical information for the repository '8b8a8f238d6244bd8a2199a6' was
gathered on 2021/10/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Thomas                         389         80841          45434           55.43
Thomas Purcell                 328         72096          29426           44.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Thomas                    70625           87.4          5.7               25.75
Thomas Purcell                8            0.0          6.1                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/acscatal.8b04478 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1088/2515-7639/ab077b is OK
- 10.1103/PhysRevMaterials.2.083802 is OK
- 10.1557/mrc.2019.85 is OK
- 10.1016/j.cej.2019.123412 is OK
- 10.1126/sciadv.aay2631 is OK
- 10.1038/s41467-018-06682-4 is OK
- 10.1021/acsami.9b14530 is OK
- 10.1038/s41467-021-22048-9 is OK
- 10.1021/acs.accounts.1c00153 is OK
- 10.1021/acscatal.0c04170 is OK
- 10.1021/acs.jcim.9b00807 is OK
- 10.1126/sciadv.aav0693 is OK
- 10.1103/PhysRevMaterials.4.034204 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03788/joss.03788/10.21105.joss.03788.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03788/joss.03788/10.21105.joss.03788.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @jarvist - Would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @jarvist as editor

**Comment by whedon** [comment]
@jarvist has been invited to edit this submission.

**Comment by tpurcell90** [comment]
For reviewers: tbirkandan and Ohjeah are good topic fits, but don't have C++ as a listed language

**Comment by tpurcell90** [comment]
Any update on the status of the review?

**Comment by tpurcell90** [comment]
@jarvist Any word on reviewers? I can try to look at the list again to find more suggestions

**Comment by jarvist** [comment]
@whedon add @ml-evs as reviewer

Many thanks for volunteering Matthew!  :wave:

**Comment by whedon** [comment]
OK, @ml-evs is now a reviewer

**Comment by jarvist** [comment]
> @jarvist Any word on reviewers? I can try to look at the list again to find more suggestions

I've just checked through my correspondence, and unfortunately everything else so far has come back negative. With @ml-evs ' expertise, a second reviewer with  C++ rather than domain experience might work well. If you have any additional suggestions, please do mention them!

**Comment by ml-evs** [comment]
No problem @jarvist!

As a disclosure, I know @tpurcell90 through another project (a large collaboration, OPTIMADE) and we have met at previous workshops. We appear on one recent paper together (https://doi.org/10.1038/s41597-021-00974-z), but I feel comfortable and able to proceed as an unbiased reviewer, provided others agree.

**Comment by tpurcell90** [comment]
@jarvist Sorry for the late response I somehow missed this

Based on the JOSS list I would recommend AstroBarker, codeling, ccaprani, and jdreo.

@ml-evs  Thanks for offering to review!

**Comment by jarvist** [comment]
Thanks! I will review the list & contact some potential reviewers by email.

**Comment by jarvist** [comment]
@whedon add @AstroBarker as reviewer

Thank you Brandon for agreeing to review. :wave:

**Comment by whedon** [comment]
OK, @AstroBarker is now a reviewer

**Comment by jarvist** [comment]
OK, I think we are good to go everyone :smile_cat:

**Comment by jarvist** [comment]
@whedon start review

Whedon?

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3960.
