### ISSUE TITLE
[PRE REVIEW]: Pyradigm: PYthon based data structure to improve Dataset's InteGrity in Machine learning workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#379]
**Submitting author:** @raamana (<a href="http://orcid.org/0000-0003-4662-0558">Pradeep Reddy Raamana</a>)
**Repository:** <a href="https://github.com/raamana/pyradigm" target ="_blank">https://github.com/raamana/pyradigm</a>
**Version:** v0.3.0.3
**Editor:** @arokem
**Reviewer:** @ahwillia

**Author instructions**

Thanks for submitting your paper to JOSS @raamana. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@raamana if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by raamana** [comment]
Thanks @arokem for editing this. 

Two devs volunteered to review for JOSS that might fit the need here, would be @ahwillia and @stsievert. If @oesteban has time to review for another package, that'd be even better.

**Comment by stsievert** [comment]
@raamana I'd be happy to review this!

**Comment by ahwillia** [comment]
I could give a brief review as well. From a quick look over - I'd be interested in an explanation about how well this plays with pandas and other existing tools/libraries.

**Comment by arokem** [comment]
Thanks @raamana for the submission. Looks interesting! 

Thanks @ahwillia and @stsievert for agreeing to review this! 

I'd be happy if both of you could review this. I will try to assign both of you as reviewers through our bot, @whedon, but I am not sure whether that would work automatically. Either way, please consider both of you as reviewers for this, and I will wait for both of your 👍 before accepting this paper.

**Comment by arokem** [comment]
@whedon assign @ahwillia as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ahwillia

**Comment by arokem** [comment]
@whedon assigne @stsievert as reviewer

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/382. Feel free to close this issue now!

**Comment by arokem** [comment]
Alright, @stsievert, @ahwillia : please head over to #382 for the review. 

I will close this one.

**Comment by stsievert** [comment]
Looks like you have a typo in https://github.com/openjournals/joss-reviews/issues/379#issuecomment-325241673 (an extra "e" on assign)
