### ISSUE TITLE
[PRE REVIEW]: PYRUS: Plotting Copy Number Estimates in Genome-Wide Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3791]
**Submitting author:** @tycheleturner (<a href="http://orcid.org/0000-0001-8246-6477">Tychele N. Turner</a>)
**Repository:** <a href="https://github.com/TNTurnerLab/PYRUS" target ="_blank">https://github.com/TNTurnerLab/PYRUS</a>
**Version:** v.1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/99b36e9fac1028a3b9872b959e403eb8/status.svg)](https://joss.theoj.org/papers/99b36e9fac1028a3b9872b959e403eb8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/99b36e9fac1028a3b9872b959e403eb8"><img src="https://joss.theoj.org/papers/99b36e9fac1028a3b9872b959e403eb8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/99b36e9fac1028a3b9872b959e403eb8/status.svg)](https://joss.theoj.org/papers/99b36e9fac1028a3b9872b959e403eb8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tycheleturner. **Currently, there isn't an JOSS editor assigned** to your paper.

@tycheleturner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btq671 is OK
- 10.1038/nature09708 is OK
- 10.1186/s12915-018-0535-2 is OK
- 10.3390/genes11020141 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 549

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (122.3 files/s, 25494.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1             32              1            373
Markdown                         2            152              0            225
TeX                              1              3              0             48
-------------------------------------------------------------------------------
SUM:                             4            187              1            646
-------------------------------------------------------------------------------


Statistical information for the repository '95f853311c8756ce02ea3901' was
gathered on 2021/10/01.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03791/joss.03791/10.21105.joss.03791.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03791/joss.03791/10.21105.joss.03791.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @tycheleturner - I'm unsure if this software meets the JOSS [definition of research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) or is of [sufficient scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) due to the quite small code size, so I'm going to mark it for an editor discussion, which should take a week or two, then we'll get back to you.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by tycheleturner** [comment]
@danielskatz Thank you for the update. We look forward to hearing from you.

**Comment by kyleniemeyer** [comment]
Hello @tycheleturner, thanks for your patience. Unfortunately, upon review, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. In addition, the software appears to be one script rather than reusable software, without much documentation.

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by tycheleturner** [comment]
@kyleniemeyer Thank you for your consideration of PYRUS.
