### ISSUE TITLE
[REVIEW]: mctreesearch4j: A Monte Carlo Tree Search Implementation for the JVM

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3804]
**Submitting author:** @larkz (<a href="http://orcid.org/0000-0002-9375-1035">Larkin Liu</a>)
**Repository:** <a href="https://github.com/JunTaoLuo/mctreesearch4j" target ="_blank">https://github.com/JunTaoLuo/mctreesearch4j</a>
**Version:** 0.0.4
**Editor:** @adi3
**Reviewer:** @TimKam, @slim-patchy
**Archive:** <a href="https://doi.org/10.5281/zenodo.5975821" target="_blank">10.5281/zenodo.5975821</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0d2c29b74817700a3569b1167bdd89de/status.svg)](https://joss.theoj.org/papers/0d2c29b74817700a3569b1167bdd89de)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0d2c29b74817700a3569b1167bdd89de"><img src="https://joss.theoj.org/papers/0d2c29b74817700a3569b1167bdd89de/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0d2c29b74817700a3569b1167bdd89de/status.svg)](https://joss.theoj.org/papers/0d2c29b74817700a3569b1167bdd89de)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JunTaoLuo/mctreesearch4j" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@TimKam & @slim-patchy, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @adi3 know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @TimKam
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JunTaoLuo/mctreesearch4j">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JunTaoLuo/mctreesearch4j">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@larkz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @slim-patchy
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JunTaoLuo/mctreesearch4j">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JunTaoLuo/mctreesearch4j">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@larkz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by TimKam** [comment]
Apologies, I will need more time; as I've mentioned when asked to review, I am not that fast this time of the year, considering conference review duties and the teaching workload peak of my teaching context. I have this on my list, though.

**Comment by larkz** [comment]
> Apologies, I will need more time; as I've mentioned when asked to review, I am not that fast this time of the year, considering conference review duties and the teaching workload peak of my teaching context. I have this on my list, though.

@TimKam @adi3 no worries take your time

**Comment by TimKam** [comment]
I added some additional comments to the PR (with comprehensive changes) made by the authors: https://github.com/aqtech-ca/mctreesearch4j/pull/68

**Comment by larkz** [comment]
> I added some additional comments to the PR (with comprehensive changes) made by the authors: [aqtech-ca/mctreesearch4j#68](https://github.com/aqtech-ca/mctreesearch4j/pull/68)

Thanks for the notes, we will take some time to go over them and make the corrections.

**Comment by larkz** [comment]
@TimKam @adi3 @slim-patchy all of the comments regarding our paper and code have been addressed (from the authors' perspective) - please see https://github.com/aqtech-ca/mctreesearch4j/pull/68, we would kindly ask for a resolution moving forward. And feel free to let us know if further editions are required.

**Comment by adi3** [comment]
@TimKam - can you please continue with your review and mark off the items in your checklist above? Would be great if you can have your review finished in the next two weeks. Thank you!

**Comment by adi3** [comment]
@larkz the ball is in @TimKam 's court right now.

@TimKam - Hopefully your calendar is a bit freer at the beginning of the year. Would you be able to finish this review in the next couple of weeks?

**Comment by TimKam** [comment]
Apologies for getting back to this late. I thank the authors for addressing my comments. As mentioned initially, I am somewhat on the fence w.r.t. *substantial scholarly effort* because the MC tree-search is AI 'from the textbook'. Still, there is probably some value in the work and I have enjoyed trying it out a bit. I have no further feedback or change requests.

**Comment by larkz** [comment]
thanks @TimKam for you review notes. Much appreciated!

To reiterate our main goal from doing this project was
a) Provide a stable and proven implementation of MCTS for the JVM ecosystem.
b) Provide a ready software platform, where researchers can already have the tooling to experiment with new MCTS modifications. 
c) Provide key software design principles, specifically for MCTS, where under such design principles, one can also build a modular and efficient MCTS software.

From our perspective, the level of scholarly effort is rather incremental, but nevertheless the goal was to achieve a) b) and c) rather than reinvent MCTS algorithmically (of which future researchers are more than free to do using our software).

Happy holidays and many thanks again for your suggestions. @adi3 please move this forward per your discretion.

**Comment by adi3** [comment]
@TimKam - thank you for finishing the review! We greatly appreciate your effort and the diligence with which you proceeded.

@larkz - Thank you for your patience through the process. The goal of JOSS is to provide visibility to robust and efficient implementations of software that could be of help to other academics or the wider research community, even if the code itself does not push the needle in terms of inventing something new. In view of this, I will be happy to recommend your paper for publishing. Thanks again!

**Comment by adi3** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by adi3** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi:10.20944/preprints202107.0622.v1 is OK
- 10.1023/A:1013689704352 is OK
- 10.1109/TCIAIG.2012.2200894 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by adi3** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1569

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (1620.0 files/s, 105927.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Kotlin                          42            483             98           1875
Bourne Shell                     3             44             72            254
Gradle                           4             34             14            167
DOS Batch                        2             51              4            152
Markdown                         2             58              0            150
TeX                              1              7              0             68
-------------------------------------------------------------------------------
SUM:                            54            677            188           2666
-------------------------------------------------------------------------------


Statistical information for the repository '1dea7542fa3d4a1fc4395ade' was
gathered on 2022/01/10.
No commited files with the specified extensions were found.
```

**Comment by adi3** [comment]
@whedon generate pdf

**Comment by adi3** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by adi3** [comment]
@larkz - I have just one more formality required from you. Can you please issue a new tagged release of the software and archive it on Zenodo, figshare or another archiving platform of your choice? Then report the release's version number and the archive's DOI on this thread. Thank you, and congratulations!

**Comment by larkz** [comment]
hi the changes have been merged and a release has been made. We created a record on Zenodo

**Comment by larkz** [comment]
@adi3 hi the changes have been merged and a release 0.0.4 corresponding to this PR has been made. We created a record on Zenodo with DOI 10.5281/zenodo.5834890 [link](https://zenodo.org/record/5834890#.Ydy5dOrMKrw)

Please let us know if anything else!

**Comment by larkz** [comment]
hi @adi3 just a gentle reminder, did you get a chance to look over the published code on Zenodo?

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.5834890 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5834890" target="_blank">10.5281/zenodo.5834890</a> is the archive.

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi:10.20944/preprints202107.0622.v1 is OK
- 10.1023/A:1013689704352 is OK
- 10.1109/TCIAIG.2012.2200894 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
Bumping this to the EiC on rotation to bring it to their attention.

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2922

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2922, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@larkz I have read the paper and inspected the ZENODO archive. Below are some final points to work on.

- [ ] Consider explaining the acronym `JVM` in the summary (currently done in the next Statement of Need section)
- [ ] Check `...is able inherit...` in the conclusion section, this should probably read `...is able to inherit...`
- [ ] Please edit the ZENODO archive (you need to do this manually) such that the title and author fields fully match that of the paper. Currently the title does not match. You may also wish to add author ORCID information at this point, and to generally make the archive meta data complete e.g. with a description etc. but we leave this up to you. 
- [ ] It looks like I should update the version tag to `v0.0.4`. I'll process this now but please confirm if this is correct.

**Comment by larkz** [comment]
hello @Kevin-Mattheus-Moerman 
I've addressed to two grammar/wording isseus.
To confirm, yes the release version is `0.0.4` you may change accordingly.

- To ask, what should the title of the Zenodo archive be? The authors match, but I looked at other JOSS papers and it seems like the pattern is {repo-name}:{some_comment}. Please let us know.

**Comment by Kevin-Mattheus-Moerman** [comment]
@larkz the title should actually match that of the paper.

**Comment by larkz** [comment]
@Kevin-Mattheus-Moerman unfortunately, I couldn't get the file to manually upload to the Zenodo archive, I think either there is a bug, or I'm not using it correctly. It is working on the sandbox, https://sandbox.zenodo.org/record/1007518#.Yf2TE-pKirw

I am just waiting until the bug/issue with Zenodo is resolved... https://github.com/zenodo/zenodo/issues/2290..., if you happen to know how to resolve this please let me know in advance.

**Comment by larkz** [comment]
@Kevin-Mattheus-Moerman, the previous Zenodo issue seems to have resolved itself (just waited for ~1 hr), we put the article up with a new DOI https://zenodo.org/record/5975821. Please update accordingly,

I think all the action items from your side are complete, let me know if you require anything else.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.5975821 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5975821" target="_blank">10.5281/zenodo.5975821</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 0.0.4 as version

**Comment by whedon** [comment]
OK. 0.0.4 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon recommend accept

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi:10.20944/preprints202107.0622.v1 is OK
- 10.1023/A:1013689704352 is OK
- 10.1109/TCIAIG.2012.2200894 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2928

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2928, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @larkz looks like we are all set now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1489879387390545920) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2929
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03804](https://doi.org/10.21105/joss.03804)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by Kevin-Mattheus-Moerman** [comment]
Congratulations on your publication @larkz! :tada: 

Special thanks to @TimKam and @slim-patchy for their review efforts! And thank you @adi3 for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03804/status.svg)](https://doi.org/10.21105/joss.03804)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03804">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03804/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03804/status.svg
   :target: https://doi.org/10.21105/joss.03804
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03804/status.svg)](https://doi.org/10.21105/joss.03804)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
