### ISSUE TITLE
[PRE REVIEW]: Systole: A python package for cardiac signal synchrony and analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3805]
**Submitting author:** @LegrandNico (<a href="http://orcid.org/0000-0002-2651-4929">Nicolas Legrand</a>)
**Repository:** <a href="https://github.com/embodied-computation-group/systole/" target ="_blank">https://github.com/embodied-computation-group/systole/</a>
**Version:** v0.2.0
**Editor:** @osorensen
**Reviewers:** @axel-loewe
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0db9e2b393ac69b67ecd1a6d6c12ae87/status.svg)](https://joss.theoj.org/papers/0db9e2b393ac69b67ecd1a6d6c12ae87)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0db9e2b393ac69b67ecd1a6d6c12ae87"><img src="https://joss.theoj.org/papers/0db9e2b393ac69b67ecd1a6d6c12ae87/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0db9e2b393ac69b67ecd1a6d6c12ae87/status.svg)](https://joss.theoj.org/papers/0db9e2b393ac69b67ecd1a6d6c12ae87)
```

**Author instructions**

Thanks for submitting your paper to JOSS @LegrandNico. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@LegrandNico if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.29 s (304.3 files/s, 67577.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          60           1718           3091           4556
SVG                              7              1              1           3521
Jupyter Notebook                 5              0           5015            318
CSS                              1             37              9            197
reStructuredText                 7            241            294            163
HTML                             3            102              0            155
YAML                             3              7              0             59
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            88           2118           8418           9004
-------------------------------------------------------------------------------


Statistical information for the repository '337e7c61de538bb4ebdea85f' was
gathered on 2021/10/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gidon Levakov                    2             3              3            0.00
LegrandNico                     86         12434           7716            9.88
Nicolas Legrand                 98         38864          38975           38.17
Nicolas Marc Simon L           132         55338          50581           51.93
Peter                            1             3              3            0.00
micahgallen                      1            17             14            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
LegrandNico                8261           66.4          4.9                8.67
Nicolas Marc Simon L       1087            2.0         16.3               19.04
Peter                         2           66.7          2.2                0.00
galialab                      2          100.0          3.6                0.00
micahgallen                  13           76.5         20.5               38.46
```

**Comment by osorensen** [comment]
@LegrandNico, before we start the review, I also suggest you fix the following small issues iin the paper:

- Please make sure Python is spelled consistently. Currently both 'python' and 'Python' are being used.
- Lines 23-24: The sentence 'Similarly, rising interest in understanding how heart-rate variability relates to ...' is not completely. You can, e.g., rewrite to 'Similarly, there is a rising interesting in understanding ...'.

**Comment by osorensen** [comment]
@siravan @axel-loewe @agricolab @neuromusic @mih @JonathanReardon would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by osorensen** [comment]
@janfreyberg @wmvanvliet @ixjlyons would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by osorensen** [comment]
> Yep :)

Excellent, then we have two reviewers and are ready to start!
