### ISSUE TITLE
[PRE REVIEW]: The 3D Slicer RVXLiverSegmentation plug-in for interactive liver anatomy reconstruction from medical images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3807]
**Submitting author:** @antoinevacavant (<a href="http://orcid.org/0000-0001-9616-3282">Antoine Vacavant</a>)
**Repository:** <a href="https://github.com/R-Vessel-X/SlicerRVXLiverSegmentation" target ="_blank">https://github.com/R-Vessel-X/SlicerRVXLiverSegmentation</a>
**Version:** 1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @lassoan, @deepakri201
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/999c4fe176099cce249b99ddea1b5bc5/status.svg)](https://joss.theoj.org/papers/999c4fe176099cce249b99ddea1b5bc5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/999c4fe176099cce249b99ddea1b5bc5"><img src="https://joss.theoj.org/papers/999c4fe176099cce249b99ddea1b5bc5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/999c4fe176099cce249b99ddea1b5bc5/status.svg)](https://joss.theoj.org/papers/999c4fe176099cce249b99ddea1b5bc5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @antoinevacavant. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@antoinevacavant if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

:wave: @Kevin-Mattheus-Moerman – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by fedorov** [comment]
@Kevin-Mattheus-Moerman, I am assuming you will make a separate [REVIEW] issue for the assigned reviewers, right (like you did for the submission I reviewed in the past [here](https://github.com/openjournals/joss-reviews/issues/2006#issuecomment-640799592))?

I am just not sure if the process is the same as before, considering you assigned @deepakri201 19 days ago, but she has not received any instructions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@thewtex @ljod @FMalmberg would you be interested in reviewing this work for JOSS ([the Journal of Open Source Software](https://joss.theoj.org)): _"The 3D Slicer RVXLiverSegmentation plug-in for interactive liver anatomy reconstruction from medical images"_? 
The [JOSS review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses on [the software](https://github.com/R-Vessel-X/SlicerRVXLiverSegmentation) as well as [a short paper](https://github.com/openjournals/joss-papers/blob/joss.03807/joss.03807/10.21105.joss.03807.pdf). 

If you haven't reviewed for JOSS before, below is an example of our GitHub based review process, where you can see that sets of check-boxes guide the reviewers through the process: 
https://github.com/openjournals/joss-reviews/issues/2969

**Comment by Kevin-Mattheus-Moerman** [comment]
@fedorov thanks for your message. The process has not changed, and I will initiate the review now to avoid further delay. I was hoping to attract an additional reviewer but will proceed with two for now. We can also add a 3rd if needed at a later stage.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3920.

**Comment by Kevin-Mattheus-Moerman** [comment]
@thewtex @ljod @FMalmberg if you are able to review for us I can still add you over at https://github.com/openjournals/joss-reviews/issues/3920.
