### ISSUE TITLE
[PRE REVIEW]: LaboRecommender: A crazy-easy to use Python-based recommender system for laboratory tests

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3808]
**Submitting author:** @fvillena (<a href="http://orcid.org/0000-0002-8759-466X">Fabián Villena</a>)
**Repository:** <a href="https://github.com/fvillena/laborecommender" target ="_blank">https://github.com/fvillena/laborecommender</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/467086d6b13b24097fbcc62d04fa9670/status.svg)](https://joss.theoj.org/papers/467086d6b13b24097fbcc62d04fa9670)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/467086d6b13b24097fbcc62d04fa9670"><img src="https://joss.theoj.org/papers/467086d6b13b24097fbcc62d04fa9670/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/467086d6b13b24097fbcc62d04fa9670/status.svg)](https://joss.theoj.org/papers/467086d6b13b24097fbcc62d04fa9670)
```

**Author instructions**

Thanks for submitting your paper to JOSS @fvillena. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @bmcfee.

@fvillena if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (481.9 files/s, 40831.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            140            480            265
TeX                              1             20              0            145
Markdown                         2             20              0             40
Jupyter Notebook                 2              0            307             31
reStructuredText                 3             15             36             17
YAML                             1              0              0              9
-------------------------------------------------------------------------------
SUM:                            18            195            823            507
-------------------------------------------------------------------------------


Statistical information for the repository 'c9d3cb6aa7b38ed655c16949' was
gathered on 2021/10/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fabián Villena                  24           960             75          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Fabián Villena              885           92.2          0.3                9.15
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1371/journal.pone.0078962 is OK
- 10.1017/S0266462312000281 is OK
- 10.1108/K-06-2017-0196 is OK
- 10.1016/j.artmed.2019.101761 is OK
- 10.2196/12957 is OK
- 10.1007/978-3-319-29659-3 is OK

MISSING DOIs

- 10.1373/jalm.2016.021634 may be a valid DOI for title: Frequency that Laboratory Tests Influence Medical Decisions
- 10.1309/lm404l0hhutwwudd may be a valid DOI for title: Clinical Laboratory Tests: Which, Why, and What Do The Results Mean?

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hello @fvillena, thanks for your interest in JOSS. Unfortunately, because of the relatively small size of your submission (<300 source lines of code), this does not meet our requirements for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). (This is not meant to say that your work is not useful)

If you expand the software, we would consider this in the future. Otherwise, please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by whedon** [comment]
Paper rejected.
