### ISSUE TITLE
[PRE REVIEW]: AutoMapDB: automagically mapping of Postgres database schema into a Python abstraction

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3809]
**Submitting author:** @scheiblr (<a href="http://orcid.org/0000-0003-2067-5569">Raphael Scheible</a>)
**Repository:** <a href="https://gitlab.com/mds-imbi-freiburg/automapdb" target ="_blank">https://gitlab.com/mds-imbi-freiburg/automapdb</a>
**Version:** 0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4bd59b474584aa1fdead9daa92c95461/status.svg)](https://joss.theoj.org/papers/4bd59b474584aa1fdead9daa92c95461)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4bd59b474584aa1fdead9daa92c95461"><img src="https://joss.theoj.org/papers/4bd59b474584aa1fdead9daa92c95461/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4bd59b474584aa1fdead9daa92c95461/status.svg)](https://joss.theoj.org/papers/4bd59b474584aa1fdead9daa92c95461)
```

**Author instructions**

Thanks for submitting your paper to JOSS @scheiblr. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @luizirber.

@scheiblr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
Hello @scheiblr, thanks for your interest in JOSS. Because of the relatively small size of your submission in terms of lines of code, we are going to review it for scope prior to assigning editors/reviewers. We should get back to you within a week or two, thank you for your patience.

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/s12911-018-0646-2 is OK
- 10.1136/jamia.2009.000893 is OK
- 10.3414/ME17-02-0025 is OK
- 10.3414/ME17-02-0022 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
