### ISSUE TITLE
[PRE REVIEW]: Delve: Neural Network Feature Variance Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3812]
**Submitting author:** @justinshenk (<a href="http://orcid.org/0000-0002-0664-7337">Justin Shenk</a>)
**Repository:** <a href="https://github.com/delve-team/delve" target ="_blank">https://github.com/delve-team/delve</a>
**Version:** v0.1.48
**Editor:** @rkurchin
**Reviewers:** @sambitdash, @dionhaefner
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/364a58b2dc11293da55bd26af2d3f503/status.svg)](https://joss.theoj.org/papers/364a58b2dc11293da55bd26af2d3f503)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/364a58b2dc11293da55bd26af2d3f503"><img src="https://joss.theoj.org/papers/364a58b2dc11293da55bd26af2d3f503/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/364a58b2dc11293da55bd26af2d3f503/status.svg)](https://joss.theoj.org/papers/364a58b2dc11293da55bd26af2d3f503)
```

**Author instructions**

Thanks for submitting your paper to JOSS @justinshenk. **Currently, there isn't an JOSS editor assigned** to your paper.

@justinshenk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1107

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (647.7 files/s, 76176.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          19            491            579           2291
TeX                              1            109              0           1269
reStructuredText                21            296            251            361
Markdown                         2             61              0            214
YAML                             7             12              6            184
DOS Batch                        1              8              1             26
make                             1              4              7              9
Jupyter Notebook                 1              0             52              2
-------------------------------------------------------------------------------
SUM:                            53            981            896           4356
-------------------------------------------------------------------------------


Statistical information for the repository 'f066576e584af59859ff0efd' was
gathered on 2021/10/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Cypher42                        64          3500           2894           46.42
Johan Byttner                    3           203            127            2.40
Justin Shenk                   158          4420           1845           45.49
MLRichter                       18           350            205            4.03
Wolf Byttner                     5           171             26            1.43
mmarcinkiewicz                   1            12             20            0.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Johan Byttner               155           76.4         18.9                0.65
Justin Shenk               1911           43.2          8.9               11.25
MLRichter                  1178          336.6         19.2                6.71
Wolf Byttner                117           68.4         13.0                1.71
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03812/joss.03812/10.21105.joss.03812.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03812/joss.03812/10.21105.joss.03812.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/wacv.2018.00097 is OK
- 10.1007/s11263-019-01228-7 is OK
- 10.5281/zenodo.5233860 is OK

MISSING DOIs

- 10.1525/california/9780520290099.003.0002 may be a valid DOI for title: Size Matters
- 10.1109/cvpr.2016.319 may be a valid DOI for title: Learning Deep Features for Discriminative Localization

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon invite @martinfleis as editor

:wave: @martinfleis – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@martinfleis has been invited to edit this submission.

**Comment by martinfleis** [comment]
@arfon Sorry, I won't be able to take care of this one right now. I can do that in about two weeks if you won't find anyone in the meantime.

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by rkurchin** [comment]
@soroushj and @yzhao062, would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by yzhao062** [comment]
@rkurchin Thanks for the invite. I am a bit tied up ATM.

I think @DerrickXuNu (https://github.com/DerrickXuNu), @orange90 (https://github.com/orange90), and @youngfish42 (https://github.com/youngfish42) will be good reviewers for this who also build deep learning libraries. 

Hope this helps!

**Comment by rkurchin** [comment]
@tuchandra and @sambitdash, would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by sambitdash** [comment]
@rkurchin I can review.

**Comment by rkurchin** [comment]
@whedon add @sambitdash as reviewer

**Comment by whedon** [comment]
OK, @sambitdash is now a reviewer

**Comment by rkurchin** [comment]
@yxoos, would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by rkurchin** [comment]
@synthaze, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by rkurchin** [comment]
@dionhaefner, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by dionhaefner** [comment]
Sure, let's do this :)

**Comment by whedon** [comment]
OK, @dionhaefner is now a reviewer

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3992.
