### ISSUE TITLE
[REVIEW]: AIBECS.jl: The ideal tool for exploring global marine biogeochemical cycles.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3814]
**Submitting author:** @briochemc (<a href="http://orcid.org/0000-0002-3838-5976">Benoit Pasquier</a>)
**Repository:** <a href="https://github.com/JuliaOcean/AIBECS.jl" target ="_blank">https://github.com/JuliaOcean/AIBECS.jl</a>
**Version:** v0.11.2
**Editor:** @kthyng
**Reviewers:** @dankelley, @zhenwu0728
**Archive:** <a href="https://doi.org/10.5281/zenodo.5787531" target="_blank">10.5281/zenodo.5787531</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4/status.svg)](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4"><img src="https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4/status.svg)](https://joss.theoj.org/papers/df0ebed76e349224389195ebd8b7c4a4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JuliaOcean/AIBECS.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dankelley, @zhenwu0728 please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @dankelley
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JuliaOcean/AIBECS.jl">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaOcean/AIBECS.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@briochemc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @zhenwu0728
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JuliaOcean/AIBECS.jl">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaOcean/AIBECS.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@briochemc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (1386.9 files/s, 139568.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           45           1080            856           3503
Markdown                         7            105              0            291
YAML                             9             12              0            288
TeX                              1             35              0            254
TOML                             2              5              0             77
JSON                             1              0              0             35
-------------------------------------------------------------------------------
SUM:                            65           1237            856           4448
-------------------------------------------------------------------------------


Statistical information for the repository 'ceb9abfad540c058d4e7a0b6' was
gathered on 2021/10/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3814 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSSpaper

**Comment by kthyng** [comment]
Sounds great, thanks for your fast responses and review @dankelley!

**Comment by kthyng** [comment]
@whedon add @zhenwu0728 as reviewer

**Comment by whedon** [comment]
OK, @zhenwu0728 is now a reviewer

**Comment by kthyng** [comment]
@zhenwu0728 I think you should be good to go now. Let me know if you have any problems, and thanks!

**Comment by zhenwu0728** [comment]
JuliaOcean/AIBECS.jl#83

**Comment by kthyng** [comment]
Excellent! Let's hear from @briochemc to see responses to your comments.

**Comment by kthyng** [comment]
@briochemc Looks like we are waiting to hear back from you on your reviewer input.

**Comment by briochemc** [comment]
@kthyng Yes! I've been working (slowly) on the code revisions according to @zhenwu0728's code comments! (I already merged a PR with one fix for output display, and I am trying options for moving the notebooks from Jupyter to Pluto)

**Comment by briochemc** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kthyng** [comment]
@briochemc Ok perfect! Carry on.

**Comment by briochemc** [comment]
@whedon generate pdf from branch JOSSpaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSSpaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: :point_left:

**Comment by briochemc** [comment]
@whedon generate pdf from branch JOSSpaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSSpaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: :point_left:

**Comment by briochemc** [comment]
@whedon generate pdf from branch JOSSpaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSSpaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: :point_left:

**Comment by briochemc** [comment]
@whedon generate pdf from branch JOSSpaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSSpaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: :point_left:

**Comment by briochemc** [comment]
@whedon generate pdf from branch JOSSpaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSSpaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: :point_left:

**Comment by briochemc** [comment]
Dear @kthyng, 

We have revised the manuscript according to @dankelley's and @zhenwu0728 's review comments in [PR #87](https://github.com/JuliaOcean/AIBECS.jl/pull/87) (for convenience: [link to the diff of the manuscript since its first submission](https://github.com/JuliaOcean/AIBECS.jl/compare/04740b960819a74f7899ab5b26f7596fe0b009df...JOSSpaper#diff-b78ae3bcb0e076c47930040ffb0e3bd3cb6a3aaa232b98a678557bbebfe71e4d)).

We have fixed all the code issues mentioned in [Issue #83](https://github.com/JuliaOcean/AIBECS.jl/issues/83)  by @zhenwu0728 in [PR #85](https://github.com/JuliaOcean/AIBECS.jl/pull/85) and [PR #87](https://github.com/JuliaOcean/AIBECS.jl/pull/87) except for the suggestion to port the notebooks from Jupyter to Pluto. This is because of breaking changes in Pluto itself that made it incompatible with the current parameter-handling implementation of AIBECS, which relies on function-overloading macros. While we hope to eventually revisit the parameter internals and interface to rely on fewer macros and make it Pluto compatible, we believe such extensive code revisions are out of the scope of @zhenwu0728's suggestion. We, therefore, hope that our revisions in [PR #85](https://github.com/JuliaOcean/AIBECS.jl/pull/85) are sufficient. (It makes sense for [Issue #83](https://github.com/JuliaOcean/AIBECS.jl/issues/83) to remain open, however, as a reminder to make the transition from Jupyter to Pluto in the future).

Overall, we believe @dankelley's and @zhenwu0728 's comments have helped us improve the software and the manuscript. (They are now acknowledged in the manuscript.)

Below you will find our point-by-point replies to the reviewers' comments.

We hope you will find that our revisions are sufficient for publication in JOSS.

On behalf of the authors,
Best Regards,
Benoit Pasquier

## Response to reviewer 1 (@dankelley) comments

> I recommend accepting this submission. It is a welcome addition to the field, and it would be to the credit of JOSS to publicize it to a wide range of educators/researchers.

We thank @dankelley for his recommendation.

> I have made some comments below, in the major/minor format that I normally use for scientific journals. I am not sure whether this is useful for a JOSS manuscript, but I didn't see any other way to provide more detailed comments, after I finished the checklist. As can be seen, I have a few suggestions that might improve the clarity of the writing, but I leave it up to the authors to decide whether to follow them (except for the minor comment about a broken citation).

The broken citation has been fixed and the suggestions have been broadly followed (details below).

> Were this a conventional scientific paper, I would have appreciated a bit more about the class of modelling frameworks supported by this project, and about any related limitations. However, for JOSS, I think what the authors have said on this matter is wholly sufficient.

We have added "steady-state" in multiple sentences to clarify (repeatedly) that this is the class of modelling currently in the scope of AIBECS.

> As for JOSS, I do think it would be helpful to add a few sentences about why Julia is chosen for the project, because their addition might give the work a broader impact. (Basically, Julia opens up doors that are closed to other systems, and folks who have not used it might not be aware just how important this is.) However, I leave the choice up to the authors.

We have added a sentence clarifying that AIBECS owes its user-friendliness and efficiency to the Julia language.

> I am always happy to see software aimed at more than just a single project. It's even better when developers take the time to educate others about how their creations might help others in the work. I think JOSS is designed specifically for this sort of thing, and I think the authors deserved to be thanked not just for their authorship of the software, but also for considering JOSS as a way to expose the work to a wider audience.

We thank @dankelley for this comment.

> ### Major Comments
>
> The manuscript outlines in reasonable detail the need for the package, although I would have appreciated more commentary on the focus on steady-state models, which is a limitation that is certainly acceptable in many applications, although it is somewhat swept under the rug here. On the technical side, the paper might have been strengthened by discussing in more detail why Julia is well-suited to this application.

We have added "steady-state" in multiple sentences to clarify (repeatedly) that this is the current scope of AIBECS. We have also added a sentence explaining why Julia was chosen.

> As for the github site and the code, both are of high quality. I worked through the 'age' tutorial, and it is straightforward and informative -- a model of how to do this sort of thing, in my opinion.
> ### Minor comments
>
> * Overall, the citations are overly heavy, in my opinion. I prefer writing that
>       cites only papers that a reader might reasonably want to consult, to learn
>       more about a particular point raised in the text. As an example, L103
>       consists entirely of citations, and all readers are told about them is that
>       they relate to parameters relating to the carbon cycle. This seems to be
>       insufficient guidance, at least for readers like me.  I am not objecting to
>       this style, because I know it to be common in some fields.

We appreciate this comment, which is similar to a comment by @zhenwu0728. The purpose of this list of references was not to point the reader to more detailed studies of particular points. Instead, it was intended to provide links to previous relevant modelling work that could have benefited from a framework like the one provided by AIBECS. However, we agree that trimming was appropriate here, and we have thus removed most of that paragraph although we have kept references to a few high-profile publications. In our opinion, the manuscript now gets straighter to the point.

> * I suggest removing "ideal" from the title. Let readers decide that.

The title now reads "A tool (...)" instead of "The ideal tool (...)".

> * Para 1 (L2:18) I think it might be useful to add a few sentences on why Julia
>       is a good choice for this project. Otherwise, the paper might only be read by
>       folks who are already familiar with the language.

We have added "Written in [Julia](https://julialang.org/) — chosen for of its combined expressive power and efficiency" a bit later in the text, after introducing the (MATLAB) AWESOME OCIM.

> * L27: This suggestion by Box about all models being wrong was essentially
>       a discussion point, not a scientific finding or a mathematical conclusion. It
>       might help to rewrite that sentence in a form like "Box (1979) has remarked
>       that ", to make things a bit clearer.  In some existential sense,
>       perhaps _everything_ is wrong.

We have revised the text as per the suggestion.

> * L28: Readers might take the authors to mean that parameters _only_ arise when
>       assumptions are made.  This is not entirely true. Another use of parameters
>       is to use a model to make predictions for a range of cases.  While I do not
>       object to the phrasing as it is, I might suggest `L28 s/give rise/can give rise/`. (Here I am using a sort of `sed` instruction to indicate a suggested
>       edit, although the `28` refers to a line number as printed, not in the file.
>       I'll use that notation throughout this review.)

We have revised the text accordingly.

> * L31: It's not clear that minimizing model-observation misfit always improves
>       the skill of a model, if the latter is (I think, reasonably) taken to
>       indicate prediction of a yet-unobserved state.  Overfitting can yield poor
>       predictions, sometimes.  Perhaps `L32 s/which also improves/which may also improve/` might help a bit, if the authors agree that there is a slight
>       chance of confusion here.

We have revised the text to say "may improve".

> * L73: the `Taburet_etal_2019` citation is broken.

This citation has been fixed.




## Response to reviewer 2 (@zhenwu0728) comments

> I've worked through "ideal age" and "PO4-POP" examples, and they are well documented and informative. I only have a few minor comments for the package and the paper.
>
> * The examples are great, but Binder is not working properly (tried a few times to launch Binder and it crashed while running the model, possibly because of the limit of memory). I suggest the authors may use Pluto.jl and [PlutoSliderServer.jl](https://github.com/JuliaPluto/PlutoSliderServer.jl) to host examples.

It is correct that Binder does not work "well" for these tutorials. This is because one has to load AIBECS (and its dependencies) and download circulations and data on a remote machine.

Translating them to Pluto is a great idea but, unfortunately, the latest version of Pluto (v0.17.2) is *not* compatible with AIBECS.jl. The current parameter interface of AIBECS.jl (which works with earlier Pluto versions, such as v0.15.0) relies on [FieldMetadata.jl](https://github.com/rafaqz/FieldMetadata.jl) macros that extend functions that are imported from FieldMetadata.jl (e.g., `units`, `bounds`). However, in Pluto v0.17.2, imported functions now cannot be extended in separate cells (see [issue 846](https://github.com/fonsp/Pluto.jl/issues/846#issuecomment-760886664)).

In response, we have added a note at the start of each tutorial and each how-to guide mentioning that binder might be slow.

Eventually, we might entirely rewrite the parameter internals and the user interface (without macros), but we believe that such a revision is out of the scope of @zhenwu0728's suggestion.

> * A better `show()` is needed for `OCIM2.load()`, `F_and_∇ₓF`, etc. Now it's hard to get any useful information from the output.

We have fixed the output issues of `OCIM2.load()` by not returning the often-unused He-flux fields. These can still be loaded if the keyword argument `FeFluxes=true` is provided. We have also fixed the output of `F_and_∇ₓF` by revising the interface slightly. Where users previously called

```julia
F, ∇ₓF = F_and_∇ₓF(args...)
```

which returned two functions (`F` is the tendencies of the tracers and `∇ₓF` its Jacobian w.r.t the tracers),
now users should call

```julia
F = AIBECSFunction(args...)
```

which returns only `F`. The Jacobian is still accessible (by calling `F.jac(args...)`, following SciML syntax) but is not exposed to the users who generally don't need to directly use it. The output of `AIBECSFunction(args...)` is now cleaner and in line with the SciML ecosystem.

> For paper.md:
>
> * L11-15: It might be good to provide one or two examples for both simple and complicated models.

We have added the Archer et al. (2000) 2-box model example for the simple case and the MITgcm for an example of a complicated model.

> * L16: It would be good to point out that AIBECS.jl only resolves steady states.

We have added "steady-state" here (and multiple other places following @dankelley's comments).

> * L31: It is worth mentioning that minimizing model-observation mismatches may cause overfitting.

We have followed @dankelley's suggestion here and revised the text to simply say "*may* improve".

> * L73: `Taburet_etal_OcnSci_2019` citation is broken.

This citation has been fixed.

> * L102-119: I think there are too many citations, only one or two for each kind of model is enough.

This list has been cut down. (See response to the similar comment made by @dankelley above.)

**Comment by kthyng** [comment]
@zhenwu0728 can you state here if you consider your review satisfactorily addressed?

**Comment by zhenwu0728** [comment]
Hi @kthyng, I think the authors did a good job. I realized that translating the examples to Pluto requires a lot of effort and the authors can do it at their own pace. The current examples are also good enough.

**Comment by kthyng** [comment]
@zhenwu0728 Thank you!

It looks like both reviews have been completed, so we can proceed with publication.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@briochemc can you archive your software in a place like Zenodo and report back the doi here? Also please update the metadata in the archive so the author list and title exactly match your JOSS paper.
Also, please state here the software version you would like associated with your JOSS paper — you'd probably want to make a new tag/release of the software also.

**Comment by kthyng** [comment]
@briochemc The paper looks good, but:
* is reference Garcia et al a bit repetitive? 
* Kelley 2003 should have Newton capitalized
* Should julia be capitalized? (Rackaukas )
* Schlitzer - capitalize Atlantic and uncapitalize the journal
* Thacker - I think Hessian should be capitalized?
* please look through all references in detail to catch other errors

**Comment by briochemc** [comment]
- [ ] archived in Zenodo [here](XXX): doi:XXX
- [x] author list and title now exactly match the JOSS paper
- [x] software version to be associated with the JOSS paper: v0.11.2
- [x] Garcia et al reference is fixed
- [x] Kelley 2003 reference fixed (Newton capitalized)
- [x] Rackaukas reference fixed (Julia capitalized)
- [x] Schlitzer reference fixed (Atlantic capitalized and journal name uncapitalized)
- [x] Thacker reference fixed (Hessian capitalized)
- [x] please look through all references in detail to catch other errors. Fixed the following (I might have fixed some references that do not make it into the paper as well):
  - [x] Amante and Eakins (2009) entry type fixed to be a `@dataset` entry type
  - [x] Dai (2017) fixed (now a `@dataset` and redundant name in title removed)
  - [x] Lin et al (2019) fixed (now a `@software`)
  - [x] Luijendijk (2019) fixed (now a `@dataset`)
  - [x] Rackaukas and Nie (2017) fixed (on top of editor request, DifferentialEquations.jl was not capitalized properly and page number and DOI were missing)
  - [x] Schlitzer et al (2018) fixed (now a `@dataset`)

**Comment by briochemc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03814/joss.03814/10.21105.joss.03814.pdf) :page_facing_up: :point_left:

**Comment by briochemc** [comment]
@kthyng, I am done with the checklist above! Anything else I should do?

**Comment by kthyng** [comment]
@briochemc Sorry for my delay, I had the past few weeks off! Everything is looking ready to go now!

**Comment by kthyng** [comment]
@whedon set v0.11.2 as version

**Comment by whedon** [comment]
OK. v0.11.2 is the version.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.5787531 as doi

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.5787531 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5787531" target="_blank">10.5281/zenodo.5787531</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1478863043186638848) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2867
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03814](https://doi.org/10.21105/joss.03814)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @briochemc! Many thanks to reviewers @dankelley and @zhenwu0728 for your time, hard work, and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03814/status.svg)](https://doi.org/10.21105/joss.03814)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03814">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03814/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03814/status.svg
   :target: https://doi.org/10.21105/joss.03814
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03814/status.svg)](https://doi.org/10.21105/joss.03814)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
