### ISSUE TITLE
[PRE REVIEW]: CHAMP is an HPC Access and Metadata Portal

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3815]
**Submitting author:** @cc-a (<a href="http://orcid.org/0000-0003-0942-8030">Christopher Cave-Ayland</a>)
**Repository:** <a href="https://github.com/ImperialCollegeLondon/champ" target ="_blank">https://github.com/ImperialCollegeLondon/champ</a>
**Version:** v2.0.0
**Editor:** @crvernon
**Reviewers:** @thurber, @acrlakshman
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a/status.svg)](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a"><img src="https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a/status.svg)](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @cc-a. **Currently, there isn't an JOSS editor assigned** to your paper.

@cc-a if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon check repository from branch joss

**Comment by whedon** [comment]
Wordcount for `paper.md` is 777

**Comment by whedon** [comment]
OK, the editor is @crvernon

**Comment by arfon** [comment]
> @arfon - I am happy to take this on if you wish.

:zap: thanks!

**Comment by crvernon** [comment]
:wave: @thurber - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by acrlakshman** [comment]
> :wave: @acrlakshman - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Sure.

**Comment by whedon** [comment]
OK, @acrlakshman is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3824.
