### ISSUE TITLE
[PRE REVIEW]: COMPAS: A rapid binary population synthesis suite

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3816]
**Submitting author:** @ilyamandel (<a href="http://orcid.org/0000-0002-6134-8946">Ilya Mandel</a>)
**Repository:** <a href="https://github.com/TeamCOMPAS/methods_paper_markdown" target ="_blank">https://github.com/TeamCOMPAS/methods_paper_markdown</a>
**Version:** v02.21.00
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f4105bb15c85763ebb5944bf89b1469c/status.svg)](https://joss.theoj.org/papers/f4105bb15c85763ebb5944bf89b1469c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f4105bb15c85763ebb5944bf89b1469c"><img src="https://joss.theoj.org/papers/f4105bb15c85763ebb5944bf89b1469c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f4105bb15c85763ebb5944bf89b1469c/status.svg)](https://joss.theoj.org/papers/f4105bb15c85763ebb5944bf89b1469c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ilyamandel. **Currently, there isn't an JOSS editor assigned** to your paper.

@ilyamandel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1078

**Comment by arfon** [comment]
👋 @ilyamandel, many thanks for your submission to JOSS. It looks like this paper is associated with this software repository https://github.com/TeamCOMPAS/COMPAS?

If that's correct, please resubmit to JOSS, with the `paper.md` (and associated files) in the https://github.com/TeamCOMPAS/COMPAS repository, rather than a standalone one here. Note, the paper doesn't need to ever be merged into the commit history for a project, and can live in a separate branch during the review process.

**Comment by ilyamandel** [comment]
> Also, please see the errors from Whedon above. The author affiliations need quoting when there are multiple.

@arfon -- Fixed.  Though I note that I followed the instructions of creating an auto-compilation action in the repo, and that produced a PDF, with appropriate affiliations, without any issues...

**Comment by ilyamandel** [comment]
> If that's correct, please resubmit to JOSS, with the `paper.md` (and associated files) in the https://github.com/TeamCOMPAS/COMPAS repository, rather than a standalone one here. Note, the paper doesn't need to ever be merged into the commit history for a project, and can live in a separate branch during the review process.

@arfon -- I created a branch with the requested files, as suggested:
https://github.com/TeamCOMPAS/COMPAS/tree/JOSS
and resubmitted.

**Comment by ilyamandel** [comment]
Suggested editor -- dfm.
