### ISSUE TITLE
[PRE REVIEW]: singcar: Comparing single cases to small samples in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3818]
**Submitting author:** @jorittmo (<a href="http://orcid.org/0000-0001-5075-0166">Jonathan Ö. Rittmo</a>)
**Repository:** <a href="https://github.com/jorittmo/singcar" target ="_blank">https://github.com/jorittmo/singcar</a>
**Version:** v.0.1.3
**Editor:** @csoneson
**Reviewers:** @craddm, @lindemann09
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6c878f9c454c5b0f6491a018bc980f0d/status.svg)](https://joss.theoj.org/papers/6c878f9c454c5b0f6491a018bc980f0d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6c878f9c454c5b0f6491a018bc980f0d"><img src="https://joss.theoj.org/papers/6c878f9c454c5b0f6491a018bc980f0d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6c878f9c454c5b0f6491a018bc980f0d/status.svg)](https://joss.theoj.org/papers/6c878f9c454c5b0f6491a018bc980f0d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jorittmo. **Currently, there isn't an JOSS editor assigned** to your paper.

@jorittmo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1076/clin.12.4.482.7241 is OK
- 10.1037/0894-4105.19.3.318 is OK
- 10.1080/02643290701290146 is OK
- 10.1016/S0028-3932(01)00224-X is OK
- 10.1016/j.cortex.2011.02.017 is OK
- 10.1016/j.cortex.2020.11.005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
👋🏻 @lindemann09, @Metafrancois - would you be interested in reviewing this submission for JOSS? 

> singcar: Comparing single cases to small samples in R

**Comment by csoneson** [comment]
👋🏻 @lindemann09 - if you're still available, I'd be happy to take you up on your offer of reviewing this submission after you're back in office next week.

**Comment by csoneson** [comment]
👋🏻 I'm going to assign @craddm and @lindemann09 as reviewers and open the review issue, to allow @craddm to get started and with the understanding that we'll still have to confirm that @lindemann09 is still happy to review once back in the office (if not, we can always solve that over in the review issue).

**Comment by csoneson** [comment]
@whedon assign @craddm as reviewer

**Comment by whedon** [comment]
OK, @craddm is now a reviewer

**Comment by csoneson** [comment]
@whedon add @lindemann09 as reviewer

**Comment by whedon** [comment]
OK, @lindemann09 is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3887.
