### ISSUE TITLE
[PRE REVIEW]: ordPens: An R package for Selection, Smoothing and Principal Components Analysis for Ordinal Variables

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3819]
**Submitting author:** @ahoshiyar (<a href="http://orcid.org/0000-0002-5702-130X">Aisouda Hoshiyar</a>)
**Repository:** <a href="https://github.com/ahoshiyar/ordPens" target ="_blank">https://github.com/ahoshiyar/ordPens</a>
**Version:** 1.0.0
**Editor:** @osorensen
**Reviewers:** @fartist, @FranjoIM, @mingzehuang
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2418101c27f855d290a5da28bcee0ea5/status.svg)](https://joss.theoj.org/papers/2418101c27f855d290a5da28bcee0ea5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2418101c27f855d290a5da28bcee0ea5"><img src="https://joss.theoj.org/papers/2418101c27f855d290a5da28bcee0ea5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2418101c27f855d290a5da28bcee0ea5/status.svg)](https://joss.theoj.org/papers/2418101c27f855d290a5da28bcee0ea5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ahoshiyar. **Currently, there isn't an JOSS editor assigned** to your paper.

@ahoshiyar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1310

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03819/joss.03819/10.21105.joss.03819.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03819/joss.03819/10.21105.joss.03819.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
@osorensen has been invited to edit this submission.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03819/joss.03819/10.21105.joss.03819.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03819/joss.03819/10.21105.joss.03819.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@whedon add @fartist as reviewer

**Comment by osorensen** [comment]
@whedon add @FranjoIM as reviewer

**Comment by whedon** [comment]
OK, @mingzehuang is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3828.
