### ISSUE TITLE
[REVIEW]: rfasst: An R tool to estimate air pollution impacts on health and agriculture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3820]
**Submitting author:** @jonsampedro (<a href="http://orcid.org/0000-0002-2277-1530">Jon Sampedro</a>)
**Repository:** <a href="https://github.com/JGCRI/rfasst" target ="_blank">https://github.com/JGCRI/rfasst</a>
**Version:** v1.2
**Editor:** @dhhagan
**Reviewer:** @nanhung, @ibarraespinosa
**Archive:** <a href="https://doi.org/10.5281/zenodo.5838361" target="_blank">10.5281/zenodo.5838361</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d/status.svg)](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d"><img src="https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d/status.svg)](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JGCRI/rfasst" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nanhung & @ibarraespinosa, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dhhagan know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @nanhung
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JGCRI/rfasst">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JGCRI/rfasst">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jonsampedro) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @ibarraespinosa
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/JGCRI/rfasst">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JGCRI/rfasst">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jonsampedro) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nanhung, @ibarraespinosa it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1281

**Comment by nanhung** [comment]
@jonsampedro I can download the example GCAM database from Zenodo through `rpackageutils::download_unpack_zip()`, but have a problem conducting the following process. Can you figure out this issue? 

![Screenshot 2021-11-01 131017](https://user-images.githubusercontent.com/25087463/139735289-70c38f1b-9c3e-4d1d-a913-a3dca97925c0.png)

**Comment by jonsampedro** [comment]
@nanhung That error is related with the `rgcam` package (dependency), which is used to extract the relevant data from the GCAM database.  Is it your working directory (WD) equal to the "db_path"? `rgcam::localDBConn` does not work when the WD is set to be the same as the directory that holds GCAM database, so that may be the problem.

**Comment by jonsampedro** [comment]
Hello @nanhung . During the review process I have realized that there has been an update in the downstrem `rmap` software, so if you activated map=T, there were some errors. I have made some modifications and the maps can be now generated with no issues, so you may need to the pull the changes from the main branch. I could make a new release, but I thought that it would be more efficient making it after including all your comments. Sorry for the inconvenience!

**Comment by nanhung** [comment]
@jonsampedro Thanks for your solution. However, I still can not solve the issue. The error occurs even I follow the tutorial in `rgcam`. Did I miss anything?

![Screenshot 2021-11-08 140237](https://user-images.githubusercontent.com/25087463/140826041-f3b3d184-418d-4600-a2a3-60f24979bf6f.png)

**Comment by jonsampedro** [comment]
@nanhung I have replicated the tutorial example and the connection worked fine for me (see below). 
![image](https://user-images.githubusercontent.com/78936824/140843363-fe9010b6-3b71-4979-b83a-05464c1f2bae.png)

Do you meet the system and package requirements to run the package? These are listed in the DESCRIPTION file at the `rgcam` repo: https://github.com/JGCRI/rgcam/blob/master/DESCRIPTION

I have been checking the rgcam issues site (https://github.com/JGCRI/rgcam/issues), and I cannot find a similar error listed there, but I will try to solve it and get you back. Thanks!

**Comment by nanhung** [comment]
@jonsampedro Thanks! I got the problem solved by switching to Linux. There are some problems when running in Windows and even WSL (I guess it's from `rgcam` package). You might need to check if you can run the package under these OS. I will further test the example modules.

**Comment by nanhung** [comment]
I found that the default setting is assumed that the user had `output/m1` and  `output/maps/m1/maps_em` directory to store the data for the m1 module. But it could be better if you add some code in your `m1_emissions_rescale` (and other modules) to create the directory if users didn't have this directory. For example, 

```r
if (!dir.exists("output")) dir.create("output")
```

**Comment by jonsampedro** [comment]
@nanhung yes I organized the outputs on different folders due to the large amount of diverse outputs that the tool can produce. If the repository is cloned the subdirectories will be already there, but I will add the suggested code to each of the modules to ensure the function still works even though there is no subfolder on the WD. Thanks for flagging this!

**Comment by jonsampedro** [comment]
Hello, I just wanted to let you know I have pushed the following changes to the main branch:

A suggested by @nanhung  , I have edited all the functions in the package, so that they create the corresponding subdirectory if it does not exist, instead of giving an error.

Following the comments by @ibarraespinosa , I have modified the main text and it now includes:
- A code example to show how the package works.
- A new framing of the tool, comparing the package with additional models and tools that have been extensively applied in scientific literature.

Hope these changes look Ok to you, and happy to make any additional changes and clarifications.

**Comment by ibarraespinosa** [comment]
Hello @jonsampedro thank for the update and sorry for the delay. I Will continue the review on weekend

**Comment by nanhung** [comment]
Thanks @jonsampedro ! I am still working on the module 1 and checking the details. 
I suggest that you put more explanation of the output. For instance, where can find the full name of the abbreviation? Waht is the unit of the value?
You can add the description in `m1_emissions_rescale()` function.

**Comment by jonsampedro** [comment]
@nanhung I have updated the function documentation (in the four modules) including all the units and the sources for:

-  Full names of the regions and list of the countries that form each region
-  List of commodities that form each crop category

**Comment by jonsampedro** [comment]
Hello @nanhung and @ibarraespinosa , just wanted to check if there is any update with the review and if you want me to make any change or add some more information. Just let me know if you want any additional clarification. Thanks in advance!

**Comment by nanhung** [comment]
Thanks, @jonsampedro I still working on the review process. Currently, everything is good. I will let you know if I have additional questions that need to be clarified.

**Comment by ibarraespinosa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03820/joss.03820/10.21105.joss.03820.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03820/joss.03820/10.21105.joss.03820.pdf) :page_facing_up: :point_left:

**Comment by ibarraespinosa** [comment]
hello @dhhagan, I think the manuscript and software are good enough to be accepted. I have tested all the functions and the @jonsampedro  has incorporated many of my suggestions. Then I recommend acceptance of rfasst for publication at JOSS.

Merry Christmas!  🎅 🎄 🎶

**Comment by nanhung** [comment]
Hi everyone, I would also recommend accepting the manuscript and the software since there is no issue that needs to be fixed and updated. 

Happy holiday:)

**Comment by jonsampedro** [comment]
Thank you @ibarraespinosa and @nanhung for your very constructive reviews, which have significantly improved both the tool and the manuscript. 

Happy Holidays!

**Comment by dhhagan** [comment]
Hey @jonsampedro sorry for the long, holiday break. I am finishing this up now!

**Comment by dhhagan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03820/joss.03820/10.21105.joss.03820.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03820/joss.03820/10.21105.joss.03820.pdf) :page_facing_up: :point_left:

**Comment by jonsampedro** [comment]
Hello @dhhagan. Thank you, just let me know if you require anything from my side.

**Comment by dhhagan** [comment]
@jonsampedro Can you do the following for me?

- [ ] Make a tagged release and archive. 
- [ ] Report the version number and archive doi in this thread

After that is complete, I can move ahead with the acceptance process.

**Comment by jonsampedro** [comment]
Sure @dhhagan, I have created a new release (rfasst-v1.2) , which is stored in zenodo with the following details:

**Zenodo site**: https://zenodo.org/record/5838361#.Yd2ym_7MJPY
**DOI**: 10.5281/zenodo.5838361

**Comment by dhhagan** [comment]
Hey @jonsampedro can you update the archive title and author list to match the paper?

**Comment by jonsampedro** [comment]
Hello @dhhagan , I have edited the archive title and authors to match the paper. See the updated archive here: https://zenodo.org/record/5838361#.YebL0P7MKUk

Note that, for clarity, I have also edited the corresponding release in the GitHub repository (https://github.com/JGCRI/rfasst/releases/tag/rfasst-v1.2)

Hope everything is OK now, thanks!

**Comment by dhhagan** [comment]
@whedon set 10.5281/zenodo.5838361 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5838361" target="_blank">10.5281/zenodo.5838361</a> is the archive.

**Comment by whedon** [comment]
OK. v1.2 is the version.

**Comment by dhhagan** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.envint.2020.105513 is OK
- 10.1016/s2542-5196(18)30029-9 is OK
- 10.5194/gmd-12-677-2019 is OK
- 10.1002/essoar.10501661.1 is OK
- 10.1016/j.eja.2018.06.002 is OK
- 10.1073/pnas.1803222115 is OK
- 10.5194/acp-18-16173-2018 is OK
- 10.2172/1036082 is OK
- 10.1016/j.atmosenv.2008.10.033 is OK
- 10.5194/gmd-12-1443-2019 is OK
- 10.5194/gmd-14-2867-2021 is OK
- 10.1029/2001JD000807 is OK
- 10.5194/gmd-11-369-2018 is OK
- 10.5194/acp-16-3825-2016 is OK
- 10.5281/zenodo.4480334 is OK
- 10.21105/joss.00662 is OK
- 10.1016/j.envsoft.2018.02.009 is OK
- 10.1016/j.envsoft.2015.09.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2907

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2907, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by jonsampedro** [comment]
Thank you @dhhagan . Is there any additional action expected from my side? Thanks!

**Comment by dhhagan** [comment]
@jonsampedro You should be good unless the EiC has a comment.

**Comment by jonsampedro** [comment]
Perfect @dhhagan , thank you!

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1487227257135538178) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2917
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03820](https://doi.org/10.21105/joss.03820)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@nanhung, @ibarraespinosa – many thanks for your reviews here and to @dhhagan for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@jonsampedro – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03820/status.svg)](https://doi.org/10.21105/joss.03820)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03820">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03820/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03820/status.svg
   :target: https://doi.org/10.21105/joss.03820
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03820/status.svg)](https://doi.org/10.21105/joss.03820)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by jonsampedro** [comment]
Everything looks OK to me. Thanks all for your valuable comments and the support during the process!

**Comment by ibarraespinosa** [comment]
Thanks to you @jonsampedro for such nice work

**Comment by Daniel-Rud** [comment]
@jonsampedro Hi Jon, I would like to ask if you would be interested in reviewing our JOSS submission "fgwqsr: An R Package for Frequentist Grouped Weighted Quantile Sum Regression".  We offer an implementation of the weighted quantile sum regression that does not require data splitting, has inference for both group effects and weights, and improves power to detect effects in chemical mixture settings.  If interested, our mansucript has been published in Statistics in Medicine, https://onlinelibrary.wiley.com/doi/full/10.1002/sim.70078.  Thank you very much for your consideration!
