### ISSUE TITLE
[REVIEW]: cofad: An R package and shiny app for contrast analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3822]
**Submitting author:** @johannes-titz (<a href="http://orcid.org/0000-0002-1102-5719">Johannes Titz</a>)
**Repository:** <a href="https://github.com/johannes-titz/cofad" target ="_blank">https://github.com/johannes-titz/cofad</a>
**Version:** v0.2.0
**Editor:** @chartgerink
**Reviewer:** @tianxzhu, @svmiller
**Archive:** <a href="https://doi.org/10.5281/zenodo.5702779" target="_blank">10.5281/zenodo.5702779</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406/status.svg)](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406"><img src="https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406/status.svg)](https://joss.theoj.org/papers/b86ad7d9c7500604c0c66df652475406)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/johannes-titz/cofad" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tianxzhu & @svmiller, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @chartgerink know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @tianxzhu
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/johannes-titz/cofad">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/johannes-titz/cofad">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@johannes-titz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @svmiller
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/johannes-titz/cofad">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/johannes-titz/cofad">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@johannes-titz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Wordcount for `paper.md` is 555

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (469.9 files/s, 63286.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               15             91            498           1298
XML                              1              0             14            761
Markdown                         5            146              0            603
TeX                              2             12              0            116
Rmd                              2            117            173             92
Bourne Shell                     1              2              9             60
YAML                             2              1              4             21
INI                              1              4              0             10
HTML                             1              3              0              5
-------------------------------------------------------------------------------
SUM:                            30            376            698           2966
-------------------------------------------------------------------------------


Statistical information for the repository 'ca72b9ece9263960d61ab75a' was
gathered on 2021/10/13.
No commited files with the specified extensions were found.
```

**Comment by chartgerink** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03822/joss.03822/10.21105.joss.03822.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03822/joss.03822/10.21105.joss.03822.pdf) :page_facing_up: :point_left:

**Comment by chartgerink** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1207/s15328031us0301_1 is OK
- 10.1017/CBO9780511804403 is OK
- 10/gdz7q2 is OK
- 10/b5f2gc is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by chartgerink** [comment]
@johannes-titz could you please update the short DOIs to full length DOIs? Specifically these two

```
- 10/gdz7q2 is OK
- 10/b5f2gc is OK
```

**Comment by johannes-titz** [comment]
@chartgerink Thanks for the update! I changed the short DOIs to full length DOIs. Is this OK?

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1207/s15328031us0301_1 is OK
- 10.1017/CBO9780511804403 is OK
- 10.18637/jss.v069.i01 is OK
- 10.1002/bimj.200810425 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by chartgerink** [comment]
many thanks @johannes-titz!

I am only awaiting a short summary from the reviewers - after that I can move forward with the editorial process based on their assessment.

**Comment by svmiller** [comment]
I think what Titz and Burkhardt offer here merits publication in the Journal of Open Source Software. The authors advocate for greater use of a contrast analysis for testing hypotheses about means in a factorial design. The authors note that alternatives to the contrast analysis exist, though with important limitations. To better advocate its use, the authors offer a Shiny app that allows users to upload their own data to do their own contrast analyses.

I think the authors have provided an important contribution to researchers working in psychology and the social sciences (who would assuredly benefit from these methods). I was able to upload a pilot data set and calculate my own contrast analyses, so the software behaves as it should. I'm also a big proponent of rewarding those who make software to make all our lives easier. I recommend JOSS proceed with publication here.

**Comment by chartgerink** [comment]
I haven't heard back from @tianxzhu, but given the positive review from @svmiller and no negative comments from @tianxzhu - I will move forward and am happy to accept this for publication, @johannes-titz 😊 

@johannes-titz could you please deposit the software in Zenodo/FigShare and share the DOI with me? I will initiate some of whedon's checks in the meantime.

**Comment by chartgerink** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03822/joss.03822/10.21105.joss.03822.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03822/joss.03822/10.21105.joss.03822.pdf) :page_facing_up: :point_left:

**Comment by chartgerink** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1207/s15328031us0301_1 is OK
- 10.1017/CBO9780511804403 is OK
- 10.18637/jss.v069.i01 is OK
- 10.1002/bimj.200810425 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by johannes-titz** [comment]
@chartgerink Thank you very much! I just made a final commit for the release and released version 0.2.1 on github (tag v0.2.1), which is also linked at zenodo (https://zenodo.org/record/5702779) with the following doi: 10.5281/zenodo.5702779

Do you need anything else?

@svmiller Thank you for such a positive feedback! I hope the software will be as useful as your review suggests :).

@tianxzhu Thank you very much for your time and effort to review the submission!

**Comment by chartgerink** [comment]
@whedon set 10.5281/zenodo.5702779 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5702779" target="_blank">10.5281/zenodo.5702779</a> is the archive.

**Comment by chartgerink** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1207/s15328031us0301_1 is OK
- 10.1017/CBO9780511804403 is OK
- 10.18637/jss.v069.i01 is OK
- 10.1002/bimj.200810425 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2751

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2751, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by chartgerink** [comment]
@johannes-titz the editor in chief that's on rotation will do a final pass and may come back with a final bit here and there. Otherwise, we're good and thank you for your patience as we worked through this :)

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1460868656909459456) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2754
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03822](https://doi.org/10.21105/joss.03822)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@tianxzhu, @svmiller – many thanks for your reviews here and to @chartgerink for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@johannes-titz – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03822/status.svg)](https://doi.org/10.21105/joss.03822)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03822">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03822/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03822/status.svg
   :target: https://doi.org/10.21105/joss.03822
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03822/status.svg)](https://doi.org/10.21105/joss.03822)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by johannes-titz** [comment]
@arfon Thank you for being so quick with the final steps! @chartgerink Thanks for the professional editing process! @svmiller @tianxzhu Thanks again for taking the time to review this submission.
