### ISSUE TITLE
[REVIEW]: cca-zoo

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3823]
**Submitting author:** @jameschapman19 (<a href="http://orcid.org/0000-0002-9364-8118">James Chapman</a>)
**Repository:** <a href="https://github.com/jameschapman19/cca_zoo" target ="_blank">https://github.com/jameschapman19/cca_zoo</a>
**Version:** v1.10.8
**Editor:** @emdupre
**Reviewer:** @robbisg, @hugorichard, @ejolly
**Archive:** <a href="https://doi.org/10.5281/zenodo.5786616" target="_blank">10.5281/zenodo.5786616</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3f5f0727ab300be64719665f2e43b055/status.svg)](https://joss.theoj.org/papers/3f5f0727ab300be64719665f2e43b055)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3f5f0727ab300be64719665f2e43b055"><img src="https://joss.theoj.org/papers/3f5f0727ab300be64719665f2e43b055/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3f5f0727ab300be64719665f2e43b055/status.svg)](https://joss.theoj.org/papers/3f5f0727ab300be64719665f2e43b055)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jameschapman19/cca_zoo" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@robbisg & @hugorichard & @ejolly, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @emdupre know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @robbisg
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/jameschapman19/cca_zoo">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jameschapman19/cca_zoo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jameschapman19) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @hugorichard
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/jameschapman19/cca_zoo">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jameschapman19/cca_zoo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jameschapman19) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @ejolly
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/jameschapman19/cca_zoo">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jameschapman19/cca_zoo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jameschapman19) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1397

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/2333955 is OK
- 10.1016/0304-4076(76)90010-5 is OK
- 10.1162/0899766042321814 is OK
- 10.1007/s11336-011-9206-8 is OK
- 10.1093/biostatistics/kxp008 is OK
- 10.2202/1544-6115.1329 is OK
- 10.2202/1544-6115.1406 is OK
- 10.1111/biom.13043 is OK
- 10.3389/fninf.2016.00049 is OK
- 10.1007/978-1-4612-4228-4_3 is OK
- 10.1109/allerton.2015.7447071 is OK
- 10.1109/cvpr.2007.383137 is OK
- 10.1109/tnn.2007.891186 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by robbisg** [comment]
Sorry for the delay, I will review the package this week.

**Comment by hugorichard** [comment]
@emdupre, here is my review:

This is a really nice piece of software. I believe it is really useful to have all these CCA methods gathered at the same place. 

I recommend acceptance. 

As a side note, I believe the vision of mvlearn and cca-zoo coincide. It would be interesting to study how to fuse the two in my opinion.

A few comments:
- The statement of need is missing in the documentation
- I don't like to have examples as notebooks. I believe it is much better to do it like in sklearn (with .py files that generate figures along with some text that describes why the experiment is performed and why the model is useful).
- I believe the tests are not rigorous enough. In many tests, nothing is actually checked (there is no assert statement). In other tests, it is only checked that the performance of some methods is lower than others. It would be more convincing to test that the method actually works: take some synthetic data that match the CCA model and show that the method can learn projection so that the correlation of the projected data is above 0.9.
- I get an ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' 
after running pip install cca-zoo. It is fixed if I force the version of scikit-learn to be 0.24 so something needs to be fixed there.
- The tests are extremely long to run... much longer than sklearn although the library is not as huge. This should definitely be fixed.
- Some tests are failing on my end when I run `py.test test_models.py` with the error ValueError: Unknown projection '3d'

**Comment by robbisg** [comment]
Hi everyone,

@emdupre I will not open an issue in the `cca-zoo` repo since I think that on my side there are few requests that can be addressed in this thread. But if you prefer, I can open the issue! ;)

### Review
I think `cca-zoo` is a very useful package that can be used to relate multivariate datasets. Personally, I used very basic implementations of these technique and I am very happy for the possibility of using more advance technique included in this tool!

#### Paper
The paper is well written and presents an extensive comparison of other similar packages and the implementation philosophy.
These edits should be included, in my point of view:
- Although you are presenting a software tool, I believe that a brief mathematical formulation of the problem, as presented in the tutorial notebook, can help a partially-expert reader to understand the application of the tool
- As before, a very simple example of the application of these technique can help a non-expert reader to understand the package.

### Software
The software uses the `scikit-learn` standard and this is very useful for the users, moreover CI and tests are valuable efforts to make the package more robust.
I hadn't any test or import errors, and by inspecting github CI, it seems that everything is ok, also using different python versions.

- I agree with @hugorichard, that examples can be "prettified" as in `scikit-learn` or `mvlearn` and is quite easy using `sphinx-gallery`.
- I think that you can also add in the documentation the mathematical formulation of these algorithms.

I think that the tool is in a very good shape, I recommend acceptance.

Thanks @jameschapman19 and @emdupre, and sorry for the delay.

**Comment by jameschapman19** [comment]
I was wary of replying as I don't know the process but it feels appropriate for me to say thanks both. All of these comments I agree with and will action them.

- examples in .py files (another benefit I have realized of this is that they can be tested cleanly on commit)
- smaller dimensionality tests should speed things up and improve the nature of the tests (and also make hard tests on results less unwieldy i.e. I can put correct array results in the script if they aren't high dimensional). I notice this is essentially how the scikit-learn ones work. I also agree that a quick-and-easy approach is just to check correlations are reasonably high (and perhaps that regularization makes them lower). I took this approach a little with the deep tests (i.e. DCCA higher correlation than linear CCA).
- maths in the docs is a great idea.

**Comment by emdupre** [comment]
Thanks both @hugorichard and @robbisg for your reviews, and @jameschapman19 for your thoughtful response !

Please do feel free to continue discussions in thread, though as specific issues on `cca-zoo` arise from this review process it will be helpful to cross-link them here !

**Comment by emdupre** [comment]
:wave: hi @ejolly ! I just wanted to check-in on this review.

Please let me know if you're encountering any technical difficulties that I can help with, or if you have a timeline for when you expect to be able to complete this !

**Comment by ejolly** [comment]
hey @emdupre sorry for the delay. I'm hoping to have this done by the end of this week or the start of next at the latest!

**Comment by ejolly** [comment]
Hey @emdupre @jameschapman19 here's my review:

## Review

- Super cool package and it's nice to see to all these algorithms (including their deep learning variants) in one place!
- I found the manuscript clear and adhering to JOSS requirements
- The API reference is also great and nicely documented
- Recommend acceptance

## Suggested Changes
- I do agree with the other reviewers that it would be nice to move some of the math + high-level explanations from the tutorial notebooks into a dedicated page in the documentation site. This would help non-experts get acquainted with the methods and more clearly see how they could use `cca-zoo` for their own problems
- I'd also recommend using `sphinx-gallery` to combine your tutorials with your documentation. You might consider adding another step in your CI pipeline to build and deploy your documentation after your test suite finishes. This has a few advantages:
   - It ensures that your live docs automatically stay updated with any new commits
   - It executes the code in the tutorial notebooks which serve as a secondary layer of testing that your test-suite might not cover
 
### Minor suggested changes

 - Not strictly necessary but it might be nice to have a `pip install cca-zoo[all]` option 
 - Since the intended audience seem to be folks who are familiar with scikit-learn, you might consider adopting the American-English spelling of "center" as oppose to "centre" for any method and function argument as they do in their API and documentation for consistency and user-experience. 
 

## Test and Issues
- I had no issues running the full testing suite in a fresh environment on macOS with Python 3.8.12
- There were a few issues with one of the tutorial notebooks which I noted [here](https://github.com/jameschapman19/cca_zoo/issues/77)

**Comment by emdupre** [comment]
Thanks @ejolly for your review ! 

It looks like https://github.com/jameschapman19/cca_zoo/issues/74, https://github.com/jameschapman19/cca_zoo/issues/75, https://github.com/jameschapman19/cca_zoo/issues/76, and https://github.com/jameschapman19/cca_zoo/issues/77 were all created in response to reviewer feedback, so I'll monitor those issues to see how the revisions are going. 

@hugorichard @robbisg @ejolly if there are any additional issues you noted that you consider to _not_ be covered by those issues, please let us know here !

**Comment by jameschapman19** [comment]
@emdupre closed that final issue. Thanks for all of the suggestions I hope that they have all been addressed in some way.

**Comment by emdupre** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03823/joss.03823/10.21105.joss.03823.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03823/joss.03823/10.21105.joss.03823.pdf) :page_facing_up: :point_left:

**Comment by emdupre** [comment]
Thank you, @jameschapman19 ! 

@hugorichard and @robbisg I want to check with you explicitly since you have a few unchecked items on your reviewer checklist : do the provided revisions (as discussed in the cross-linked issues) address your previous concerns ? Of course, @ejolly, please also let us know if there's anything that you don't consider resolved !

**Comment by ejolly** [comment]
Looks good to me!

**Comment by robbisg** [comment]
Looks good to me too! :+1:

**Comment by hugorichard** [comment]
Looks good to me too!

**Comment by emdupre** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/2333955 is OK
- 10.1016/0304-4076(76)90010-5 is OK
- 10.1162/0899766042321814 is OK
- 10.1007/s11336-011-9206-8 is OK
- 10.1093/biostatistics/kxp008 is OK
- 10.2202/1544-6115.1329 is OK
- 10.2202/1544-6115.1406 is OK
- 10.1111/biom.13043 is OK
- 10.3389/fninf.2016.00049 is OK
- 10.1007/978-1-4612-4228-4_3 is OK
- 10.1109/allerton.2015.7447071 is OK
- 10.1109/cvpr.2007.383137 is OK
- 10.1109/tnn.2007.891186 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by emdupre** [comment]
Thank you @ejolly @hugorichard @robbisg for your thoughtful reviews and @jameschapman19 for your impressive work on `cca-zoo` !

At this point, @jameschapman19, could you please:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. I see that you released version `v1.10.6` 5 days ago and have made no changes to `main` since; please let me know if you'd like to use that as the  JOSS-associated release.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata (e.g., the JOSS paper and software archive have the same title and author listing)
- [ ] List the DOI of the archived version here.

I can then move forward with accepting the submission :rocket:

**Comment by jameschapman19** [comment]
Thanks all.

- I've made a tiny fix so please go with v1.10.7
- It is archived in Zenodo.
- Hao-Ting and I are listed as authors on both the JOSS paper and software archive.
- The DOI is 10.5281/zenodo.5781712 and can be viewed at https://zenodo.org/record/5781712

**Comment by emdupre** [comment]
@whedon set v1.10.7 as version

**Comment by whedon** [comment]
OK. v1.10.7 is the version.

**Comment by emdupre** [comment]
Thank you, @jameschapman19 !

Could you also please update the Zenodo archive title so it matches the title of the JOSS paper ? Specifically, "cca-zoo : a python package for implementing models from the canonical correlation analysis family".

**Comment by jameschapman19** [comment]
Ah I see - done.

**Comment by emdupre** [comment]
@whedon set 10.5281/zenodo.5781712 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5781712" target="_blank">10.5281/zenodo.5781712</a> is the archive.

**Comment by emdupre** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/2333955 is OK
- 10.1016/0304-4076(76)90010-5 is OK
- 10.1162/0899766042321814 is OK
- 10.1007/s11336-011-9206-8 is OK
- 10.1093/biostatistics/kxp008 is OK
- 10.2202/1544-6115.1329 is OK
- 10.2202/1544-6115.1406 is OK
- 10.1111/biom.13043 is OK
- 10.3389/fninf.2016.00049 is OK
- 10.1007/978-1-4612-4228-4_3 is OK
- 10.1109/allerton.2015.7447071 is OK
- 10.1109/cvpr.2007.383137 is OK
- 10.1109/tnn.2007.891186 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2827

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2827, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @jameschapman19, I'm just doing some final checks before accepting.

Can you capitalize "python" in the paper's title? There are some uses throughout the paper where it should be capitalized as well.

Also, the Bach and Jordan reference needs a few more details. This is a technical report, published by University of California Berkeley Department of Statistics, Tech. Rep. 688. You can also add the URL https://statistics.berkeley.edu/sites/default/files/tech-reports/688.pdf.

Lastly, please confirm that there are no DOIs available for the Wenwen et al. and Wong et al. references.

**Comment by emdupre** [comment]
Thank you for catching those points, @kyleniemeyer !

> Can you capitalize "python" in the paper's title? There are some uses throughout the paper where it should be capitalized as well.

@jameschapman19, when you're making those changes please update it in the zenodo archive as well, just so those two documents match !

**Comment by jameschapman19** [comment]
Thanks @kyleniemeyer - I was able to track down a doi for Wenwen et al. too

@emdupre I made a related change to the references in the docstrings themselves so best to also change to 1.10.8 (but don't worry if it's too much trouble).

**Comment by emdupre** [comment]
> @emdupre I made a related change to the references in the docstrings themselves so best to also change to 1.10.8 (but don't worry if it's too much trouble).

Thank you, @jameschapman19 ! To confirm, did you also create a corresponding archive for the new release ? Can you list the DOI here if so ?

**Comment by jameschapman19** [comment]
New DOI: 10.5281/zenodo.5786616

Just realised there is also the DOI which resolves to the most recent: 10.5281/zenodo.4382739

I don't know what is more appropriate for JOSS but I'm happy with either.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.5786616 as archive

We prefer the DOI that points to the specific version

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5786616" target="_blank">10.5281/zenodo.5786616</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03823/joss.03823/10.21105.joss.03823.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03823/joss.03823/10.21105.joss.03823.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@jameschapman19 sorry, the Wenwen et al. reference still needs one final change—the DOI field should not have the extra `doi=` in it, just do `doi={10.1049/cje.2017.08.004}`

**Comment by jameschapman19** [comment]
🤦 fixed

**Comment by emdupre** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03823/joss.03823/10.21105.joss.03823.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03823/joss.03823/10.21105.joss.03823.pdf) :page_facing_up: :point_left:

**Comment by emdupre** [comment]
@whedon set v1.10.8 as version

**Comment by whedon** [comment]
OK. v1.10.8 is the version.

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1472284790967709698) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2836
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03823](https://doi.org/10.21105/joss.03823)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @jameschapman19 on your article's publication in JOSS!

Many thanks to @robbisg, @hugorichard, and @ejolly for reviewing this submission, and @emdupre for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03823/status.svg)](https://doi.org/10.21105/joss.03823)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03823">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03823/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03823/status.svg
   :target: https://doi.org/10.21105/joss.03823
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03823/status.svg)](https://doi.org/10.21105/joss.03823)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
