### ISSUE TITLE
[REVIEW]: CHAMP is an HPC Access and Metadata Portal

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3824]
**Submitting author:** @cc-a (<a href="http://orcid.org/0000-0003-0942-8030">Christopher Cave-Ayland</a>)
**Repository:** <a href="https://github.com/ImperialCollegeLondon/champ" target ="_blank">https://github.com/ImperialCollegeLondon/champ</a>
**Version:** v2.1.0
**Editor:** @crvernon
**Reviewer:** @thurber, @acrlakshman
**Archive:** <a href="https://doi.org/10.5281/zenodo.6026417" target="_blank">10.5281/zenodo.6026417</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a/status.svg)](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a"><img src="https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a/status.svg)](https://joss.theoj.org/papers/5439f73b03eff8700a4b573813ed369a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ImperialCollegeLondon/champ" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@thurber & @acrlakshman, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @crvernon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @thurber
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/ImperialCollegeLondon/champ">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ImperialCollegeLondon/champ">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cc-a) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @acrlakshman
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/ImperialCollegeLondon/champ">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ImperialCollegeLondon/champ">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cc-a) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03824/joss.03824/10.21105.joss.03824.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03824/joss.03824/10.21105.joss.03824.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
:mega: Mid-week rally!  Looks like @cc-a @thurber and @acrlakshman are all participating on this [issue](https://github.com/ImperialCollegeLondon/champ/issues/70) and all is rolling along well.  Let's keep pushing to get this in great shape for publication!

👏 Keep up the good work!

**Comment by crvernon** [comment]
:mega: Mid-week rally!  

@thurber and @acrlakshman please provide a short update in this issue thread concerning the status of your reviews.  Thanks! 

@cc-a are there any blockers on your side of things?  I would like to keep our momentum up so we may keep pushing to get this in great shape for publication!

**Comment by acrlakshman** [comment]
> mega Mid-week rally!
> 
> @thurber and @acrlakshman please provide a short update in this issue thread concerning the status of your reviews. Thanks!
> 
> @cc-a are there any blockers on your side of things? I would like to keep our momentum up so we may keep pushing to get this in great shape for publication!

I am on a different schedule last week, i shall provide my final update over the weekend.

**Comment by cc-a** [comment]
No blockers on my front. I think I have a proof of principle for running tests in a containerised demo cluster. Needs a tidy up though.

**Comment by crvernon** [comment]
@thurber and @acrlakshman please provide a short update in this issue thread concerning the status of your reviews. Thanks!

**Comment by thurber** [comment]
hi @crvernon, there are a few issues still outstanding in ImperialCollegeLondon/champ#70, the blocking one being a way to test the champ interface against a mock cluster. I believe @cc-a was close to implementing a solution.

**Comment by crvernon** [comment]
Thanks @thurber !  

@cc-a could you provide an update as to how things are going on your end?

**Comment by crvernon** [comment]
:mega: Mid-week rally!  

:wave: @acrlakshman please provide a short update in this issue thread concerning the status of your reviews. 

:wave: @cc-a please provide an update here on the status of your responses to the reviewers thus far.

Thanks!

**Comment by acrlakshman** [comment]
Hi @crvernon , I need to finish going through the code, on the side I am also waiting for my comments to be addressed as noted in https://github.com/ImperialCollegeLondon/champ/issues/70.

**Comment by cc-a** [comment]
I've managed to sort the tricky bit with the containerised cluster for testing and will address the more minor comments in short order..

**Comment by thurber** [comment]
@crvernon - with @cc-a's latest updates that provide an end-to-end testing environment, I am satisfied with my review. Nice work!

**Comment by crvernon** [comment]
:mega: Mid-week rally!

It would be good to get this one wrapped up soon @cc-a so we can free up our reviewers.  How are things looking on your side of things for finishing up the remaining issues?  It looks like @acrlakshman has several more items to check off and @thurber has approved all.

@acrlakshman could you also provide an update to where things stand on your side of things?

Thanks!

**Comment by acrlakshman** [comment]
> 

@crvernon, my comments were addressed. I shall submit my final review before this weekend.

**Comment by crvernon** [comment]
Thank you @acrlakshman !

**Comment by crvernon** [comment]
Also @acrlakshman please don't forget to check off any remaining boxes that have been addressed in your reviewer checklist.  Thanks!

**Comment by acrlakshman** [comment]
> Also @acrlakshman please don't forget to check off any remaining boxes that have been addressed in your reviewer checklist. Thanks!

@crvernon , sure I will clear all pending items.

**Comment by acrlakshman** [comment]
Things look good with the current shape, but all changes are in `joss-review`, may I know if things will be merged into `develop` branch?

**Comment by cc-a** [comment]
@acrlakshman Sure, if there are no further comments.

**Comment by crvernon** [comment]
@acrlakshman - if you have finished your current review and are satisfied with the outcome, please check off your final box for `Substantial scholarly effort` and I'll move to conducting my portion of this process.  Thanks!

**Comment by acrlakshman** [comment]
> @acrlakshman Sure, if there are no further comments.

no further comments from my side to get that branch merged.

**Comment by acrlakshman** [comment]
> @acrlakshman - if you have finished your current review and are satisfied with the outcome, please check off your final box for `Substantial scholarly effort` and I'll move to conducting my portion of this process. Thanks!

Done.

**Comment by crvernon** [comment]
@cc-a - I want to make sure I am working on what will be the branch that is targeted for release / publication.  Your default branch is `develop` which is fine.  Are you planning on bringing the `joss` branch into `develop`?  

Also, you have quite a few dependabot PRs open do you mind evaluating merging these and ensuring they don't break your code?  This may help prevent potential security issues for users.

**Comment by cc-a** [comment]
Thanks @crvernon. All dependabot PR's have been resolved and the `joss-review` branch implementing feedback has been merged into develop.

Is it an expectation that the paper.md should be part of the mainline development branch? If not I would prefer to keep it in its own separate branch.

**Comment by crvernon** [comment]
@whedon generate pdf from branch develop

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch develop. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3824 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by crvernon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03824/joss.03824/10.21105.joss.03824.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03824/joss.03824/10.21105.joss.03824.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/ci500302p is OK
- 10.21105/joss.00622 is OK
- 10.14454/FXWS-0523 is OK
- 10.1186/s13321-017-0190-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by crvernon** [comment]
@cc-a - the following are some comments concerning the paper specifically:

- [ ] HPC and FAIR are used as an acronym before it has been described.  For example:  "CHAMP (CHAMP is an HPC Access and Metadata Portal)..."  This could be something like "CHAMP is a high performance computing (HPC) and metadata portal which provides an easy to use workflow for FAIR (Findability, Accessibility, Interoperability, and Reusability) scientific guiding principles data generation and publication."
- [ ] Figures are not referred to in text.  See this previous JOSS publication for how to use figure referencing:  https://joss.theoj.org/papers/10.21105/joss.03221 . Please let me know if you have questions about this.
- [ ] On line 22.  `e.g.` should always be followed by a comma
- [ ] On line 40.  Open OnDemand is given an acronym here (e.g., OOD) but it has been used earlier in text.
- [ ] Need citation for NGINX
- [ ] Need acronym breakout for UIDs
- [ ] "CHAMP is written in Python (>3.7)..." should read "CHAMP is written for use in Python (>3.7)..."  and is this supposed to be >3.7 and not >=3.7?
- [ ] YAML needs acronym breakout
- [ ] Sentence "This allows flexibility to e.g. use a job..." should read "For example, this allows flexibility to use a job..."
- [ ]  API needs acronym breakout
- [ ] OAuth2 needs citation
- [ ] Sentence "...data repositories where desired, in the case of Imperial..." should read "...data repositories where desired, as in the case of Imperial..."
- [ ] Period needed after `Dr` in "Dr Matthew Harvey"

Thanks!

**Comment by crvernon** [comment]
> Thanks @crvernon. All dependabot PR's have been resolved and the `joss-review` branch implementing feedback has been merged into develop.
> 
> Is it an expectation that the paper.md should be part of the mainline development branch? If not I would prefer to keep it in its own separate branch.

Yes, it is fine to have the paper in a separate branch.

**Comment by cc-a** [comment]
@crvernon Thanks for the paper feedback. This has now been incorporated to the `joss` branch.

**Comment by crvernon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03824/joss.03824/10.21105.joss.03824.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03824/joss.03824/10.21105.joss.03824.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/ci500302p is OK
- 10.21105/joss.00622 is OK
- 10.14454/FXWS-0523 is OK
- 10.1186/s13321-017-0190-6 is OK
- 10.17487/RFC6749 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by crvernon** [comment]
@cc-a - we are almost there!  Next is just setting up the archive for your new release. 

- We want to make sure the archival has the correct metadata that JOSS requires.  This includes a title that matches the paper title and a correct author list.  

So here is what we have left to do:
- [ ] Conduct a GitHub release of the current reviewed version of the software you now have on the branch in which you want to be the target for the published (reviewed) code and archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) to ensure it has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here

I can then move forward with accepting the submission.

**Comment by cc-a** [comment]
Thanks for the reminder. I've archived a new release at https://doi.org/10.5281/zenodo.6026417

**Comment by crvernon** [comment]
@editorialbot set v2.1.0 as version

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.6026417" target="_blank">10.5281/zenodo.6026417</a> is the archive.

**Comment by crvernon** [comment]
@whedon set v2.1.0 as version

**Comment by whedon** [comment]
OK. v2.1.0 is the version.

**Comment by crvernon** [comment]
🎉  @cc-a thanks for putting together a really nice software product! Thanks to @thurber and @acrlakshman for a constructive and timely review!

I am recommending that your submission be accepted. An EIC will review this shortly and confirm final publication if all goes well.

**Comment by crvernon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
PDF failed to compile for issue #3824 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by crvernon** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/ci500302p is OK
- 10.21105/joss.00622 is OK
- 10.14454/FXWS-0523 is OK
- 10.1186/s13321-017-0190-6 is OK
- 10.17487/RFC6749 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2936

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2936, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by kthyng** [comment]
Hi @cc-a! Looks ready to go!!

**Comment by kthyng** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1491612941925466113) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2937
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03824](https://doi.org/10.21105/joss.03824)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations on your new publication @cc-a!! Many thanks to editor @crvernon and reviewers @thurber and @acrlakshman for your time, hard work, and expertise!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03824/status.svg)](https://doi.org/10.21105/joss.03824)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03824">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03824/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03824/status.svg
   :target: https://doi.org/10.21105/joss.03824
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03824/status.svg)](https://doi.org/10.21105/joss.03824)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
