### ISSUE TITLE
[PRE REVIEW]: Sepia, a taxonomy oriented read classifier in Rust

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3825]
**Submitting author:** @hcdenbakker (<a href="http://orcid.org/0000-0002-4086-1580">Henk den Bakker</a>)
**Repository:** <a href="https://github.com/hcdenbakker/sepia" target ="_blank">https://github.com/hcdenbakker/sepia</a>
**Version:** v0.0.2
**Editor:** @will-rowe
**Reviewers:** @Ebedthan, @telatin
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/711e7a5f1810c1211a515ea0c0beab9f/status.svg)](https://joss.theoj.org/papers/711e7a5f1810c1211a515ea0c0beab9f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/711e7a5f1810c1211a515ea0c0beab9f"><img src="https://joss.theoj.org/papers/711e7a5f1810c1211a515ea0c0beab9f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/711e7a5f1810c1211a515ea0c0beab9f/status.svg)](https://joss.theoj.org/papers/711e7a5f1810c1211a515ea0c0beab9f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @hcdenbakker. **Currently, there isn't an JOSS editor assigned** to your paper.

@hcdenbakker if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by will-rowe** [comment]
Hi there. Sorry for the delay. This sounds great.

**Comment by will-rowe** [comment]
Thanks Luiz. Hi @Ebedthan - it would be great if you could review?

**Comment by whedon** [comment]
OK, @Ebedthan is now a reviewer

**Comment by will-rowe** [comment]
@lskatz - would you be willing to review this?

**Comment by will-rowe** [comment]
Oops, sorry. Long day!

**Comment by telatin** [comment]
>  I'll see if any alternatives are available.

Hello everyone, I'm happy to review this if needed!

**Comment by will-rowe** [comment]
Hi @telatin - thank you very much and yes please!

**Comment by will-rowe** [comment]
@whdeon add @telatin as reviewer
