### ISSUE TITLE
[REVIEW]: disksurf: Extracting the 3D Structure of Protoplanetary Disks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3827]
**Submitting author:** @richteague (<a href="http://orcid.org/0000-0003-1534-5186">Richard Teague</a>)
**Repository:** <a href="https://github.com/richteague/disksurf" target ="_blank">https://github.com/richteague/disksurf</a>
**Version:** v0.1.7
**Editor:** @christinahedges
**Reviewer:** @emptymalei, @cpinte
**Archive:** <a href="https://doi.org/10.5281/zenodo.5670586" target="_blank">10.5281/zenodo.5670586</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/436317ccf31e271043309092032ccf08/status.svg)](https://joss.theoj.org/papers/436317ccf31e271043309092032ccf08)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/436317ccf31e271043309092032ccf08"><img src="https://joss.theoj.org/papers/436317ccf31e271043309092032ccf08/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/436317ccf31e271043309092032ccf08/status.svg)](https://joss.theoj.org/papers/436317ccf31e271043309092032ccf08)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/richteague/disksurf" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@emptymalei & @cpinte, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @christinahedges know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @emptymalei
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/richteague/disksurf">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/richteague/disksurf">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@richteague) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @cpinte
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/richteague/disksurf">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/richteague/disksurf">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@richteague) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201629098 is OK
- 10.21105/joss.01632 is OK
- 10.1086/670067 is OK
- 10.1038/s41586-019-1642-0 is OK
- 10.3847/1538-4357/abf92e is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.4599319 is OK
- 10.1051/0004-6361/201731377 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (202.0 files/s, 43357.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            318            822           1143
TeX                              1             11              0            177
Markdown                         3             22              0             65
Jupyter Notebook                 1              0            485             55
reStructuredText                 2             19             15             33
DOS Batch                        1              8              1             26
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            15            382           1329           1508
-------------------------------------------------------------------------------


Statistical information for the repository '19f2eaae75f8267d394caeb7' was
gathered on 2021/10/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jane Huang                       1             4              2            0.05
Richard Teague                  54          6994           4983           97.65
richteague                       3           276              6            2.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Richard Teague             2283           32.6          1.5                9.77
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03827/joss.03827/10.21105.joss.03827.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03827/joss.03827/10.21105.joss.03827.pdf) :page_facing_up: :point_left:

**Comment by christinahedges** [comment]
@richteague, @emptymalei , @cpinte – This is the review thread for the paper. Please don't hesitate to message me here if you have questions.

Please read the "Reviewer instructions & questions" in the first comment above to get started. If you get lost, you can also see the reviewer guidelines.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. If you are concerned about a requirement, please discuss it here on this thread 🧵 . Feel free to post about questions/concerns as they come up as you go through your review.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention #3827 so that a link is created to this thread (and I can keep an eye on what is happening).

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule. When you're finished with your checklist, leave a comment and @ me to let everyone know your review is complete.

**Comment by cpinte** [comment]
Thanks !

**Comment by emptymalei** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03827/joss.03827/10.21105.joss.03827.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03827/joss.03827/10.21105.joss.03827.pdf) :page_facing_up: :point_left:

**Comment by emptymalei** [comment]
Hmm, I found a strange thing about the markdown to pdf generator. 

![CleanShot 2021-11-01 at 20 11 44@2x](https://user-images.githubusercontent.com/663798/139727777-25159df9-d72a-4f25-b854-c1bdabb5282a.png)

The order of `'` and `,` is different from the original markdown file:

https://github.com/richteague/disksurf/blob/8b1fdf1c1780eefa6c6d008ca4a6739a5a1f45df/paper/paper.md?plain=1#L40

**Comment by richteague** [comment]
Apologies for missing that code, @cpinte! Do you have a Zenodo reference that I could use to reference it, or would a link to the GitHub repository be OK?

@kthyng - Do you have a preference from an editorial point of view?

**Comment by danielskatz** [comment]
It is odd that it's being generated differently than specified, though in this case, correct grammar would be 

> 'scattering surface,' the emission surface equivalent for small, submicron grains, was described

both the first comma inside the quote, and the second comma added.

**Comment by kthyng** [comment]
I didn't know that would happen in the pdf compilation! My understanding for the order of quotes vs. commas in a sentence is geographically dependent with different accepted rules in the U.S. vs the U.K. for example.

**Comment by cpinte** [comment]
@richteague thanks, a link to github would be great.

**Comment by christinahedges** [comment]
@cpinte and @emptymalei it seems like both of your review checklists are complete. Thank you for your speedy work! If you have any further comments for the authors please do post them, otherwise let me know on the thread if you're happy with the submission and would like to complete your review and recommend acceptance.

**Comment by emptymalei** [comment]
Hi @christinahedges , from my side, I'm happy with the submission and would like to recommend accepting the current manuscript.

**Comment by cpinte** [comment]
Hi @christinahedges, 
I am also happy to recommend the paper for publication.

**Comment by emptymalei** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03827/joss.03827/10.21105.joss.03827.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03827/joss.03827/10.21105.joss.03827.pdf) :page_facing_up: :point_left:

**Comment by christinahedges** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201629098 is OK
- 10.21105/joss.01632 is OK
- 10.1086/670067 is OK
- 10.1038/s41586-019-1642-0 is OK
- 10.3847/1538-4357/abf92e is OK
- 10.3847/1538-4365/ac1434 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.3847/1538-4365/ac143b is OK
- 10.3847/1538-4365/ac143d is OK
- 10.5281/zenodo.4599319 is OK
- 10.1051/0004-6361/201731377 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by christinahedges** [comment]
Thank you very much reviewers! @richteague your paper submission looks good to me. If you are happy and would like to make no further changes based on the review, please make a tagged release 🏷️ of the code and archive it, and then please report the version number and archive DOI here in this thread. Please make sure this archived version has all the correct meta data (author names, title etc)!

I can then recommend to our EIC that we accept this submission. 

Thank you again to @emptymalei and @cpinte for your hard work and thorough review!

**Comment by richteague** [comment]
Thanks @christinahedges! I've made a version of the code and archived version here: 10.5281/zenodo.5670586.

Thanks also to @cpinte and @emptymalei for reviewing this submission!

**Comment by kyleniemeyer** [comment]
Hi @richteague, can you edit the metadata of the Zenodo archive so that the title and author list match the JOSS paper?

**Comment by richteague** [comment]
Hi @kyleniemeyer, I should have changed that now.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.5670586 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5670586" target="_blank">10.5281/zenodo.5670586</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201629098 is OK
- 10.21105/joss.01632 is OK
- 10.1086/670067 is OK
- 10.1038/s41586-019-1642-0 is OK
- 10.3847/1538-4357/abf92e is OK
- 10.3847/1538-4365/ac1434 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.3847/1538-4365/ac143b is OK
- 10.3847/1538-4365/ac143d is OK
- 10.5281/zenodo.4599319 is OK
- 10.1051/0004-6361/201731377 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2747

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2747, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1459266886332518404) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2748
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03827](https://doi.org/10.21105/joss.03827)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @richteague on your article's publication in JOSS!

Many thanks to @emptymalei and @cpinte for reviewing this, and @christinahedges for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03827/status.svg)](https://doi.org/10.21105/joss.03827)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03827">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03827/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03827/status.svg
   :target: https://doi.org/10.21105/joss.03827
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03827/status.svg)](https://doi.org/10.21105/joss.03827)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
