### ISSUE TITLE
[PRE REVIEW]: sknet: A Python framework for Machine Learning in Complex Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3830]
**Submitting author:** @TNanukem (<a href="http://orcid.org/0000-0001-5675-554X">Tiago Toledo Junior</a>)
**Repository:** <a href="https://github.com/TNanukem/scikit-net/" target ="_blank">https://github.com/TNanukem/scikit-net/</a>
**Version:** v0.0.1
**Editor:** @osorensen
**Reviewers:** @dvysardana, @drj11
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6a2c114ff1c64ff07bd4735638515359/status.svg)](https://joss.theoj.org/papers/6a2c114ff1c64ff07bd4735638515359)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6a2c114ff1c64ff07bd4735638515359"><img src="https://joss.theoj.org/papers/6a2c114ff1c64ff07bd4735638515359/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6a2c114ff1c64ff07bd4735638515359/status.svg)](https://joss.theoj.org/papers/6a2c114ff1c64ff07bd4735638515359)
```

**Author instructions**

Thanks for submitting your paper to JOSS @TNanukem. **Currently, there isn't an JOSS editor assigned** to your paper.

@TNanukem if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3830 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch docs/joss_paper

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03830/joss.03830/10.21105.joss.03830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03830/joss.03830/10.21105.joss.03830.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch docs/joss_paper
