### ISSUE TITLE
[PRE REVIEW]: Rasusa: Randomly subsample sequencing reads to a specified coverage

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3831]
**Submitting author:** @mbhall88 (<a href="http://orcid.org/0000-0003-3683-6208">Michael Hall</a>)
**Repository:** <a href="https://github.com/mbhall88/rasusa" target ="_blank">https://github.com/mbhall88/rasusa</a>
**Version:** 0.6.0
**Editor:** @mikldk
**Reviewers:** @k3yavi, @holtgrewe
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c7a5d695898c3126119297020490fcae/status.svg)](https://joss.theoj.org/papers/c7a5d695898c3126119297020490fcae)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c7a5d695898c3126119297020490fcae"><img src="https://joss.theoj.org/papers/c7a5d695898c3126119297020490fcae/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c7a5d695898c3126119297020490fcae/status.svg)](https://joss.theoj.org/papers/c7a5d695898c3126119297020490fcae)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mbhall88. **Currently, there isn't an JOSS editor assigned** to your paper.

@mbhall88 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by mbhall88** [comment]
Thank you for the feedback @mikldk. I address each comment/question below.

> @mbhall88 - thank you for the submission.
> 
> I'll go ahead and invite reviewers. Meanwhile I have a few comments/questions:
> 
> For the paper:
> 
>     * [ ]  Please write out your affiliation (so the reader knows what "EMBL-EBI" means)

Done.

> 
>     * [ ]  Maybe mention massive parallel sequencing? (As opposed to Sanger/single molecule sequencing.)

I am curious as to why? Rasusa is agnostic to how the data were generated.

> 
>     * [ ]  "For example, coverage of 5x indicates that each nucleotide in the original genetic material is represented five times in the read file." -- maybe make explicit that this in on average five times?

Done.

> 
> 
> For the method:
> 
>     * [ ]  Say the data is 100x (cf. above, that is an average?); we subsample to 20x using `Rasusa` - as I read it, this is now a minimum, right?

Sorry, I don't quite understand what you are asking? If we subsample to 20x then, theoretically, on average, each position has 20x. Not sure if that is what you are referring to?

> 
>     * [ ]  Is it possible to use the quality (for `FASTQ` files) or read length (e.g. prefer longer/shorter reads) in the sampling, or is the sampling performed uniformly amongst reads without considering any of such characteristics?

No. This was a deliberate design choice. As I mention in the paragraph about Filtlong, such filtering means the resulting data is not necessarily representative of the the original data source. See https://github.com/mbhall88/rasusa/issues/16#issuecomment-558168931 for an elaboration of this.

> 
>     * [ ]  Is it possible to balance the sampling to take into account the reading direction of the reads (3'->5' / 5'->3')?

No. To do this Rasusa would need to know the strand orientation, which is not represented in FASTA/Q, and it only operates on those file formats.

**Comment by mikldk** [comment]
@mbhall88, thanks.


> > For the method:
> > ```
> > * [ ]  Say the data is 100x (cf. above, that is an average?); we subsample to 20x using `Rasusa` - as I read it, this is now a minimum, right?
> > ```
> 
> Sorry, I don't quite understand what you are asking? If we subsample to 20x then, theoretically, on average, each position has 20x. Not sure if that is what you are referring to?

You answer my question here: the subsampling to 20x means that the subsample has 20x on average, not as a minimum. That's fine. Is this explictely written in the paper (if not, I would consider doing it, but it is up to you to decide)?

**Comment by mbhall88** [comment]
I've added a clarifying statement.

**Comment by mikldk** [comment]
@kblin: Would you be interested in reviewing this submission to The Journal of Open Source Software? Reviews are open and based on a checklist. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. If you have any questions or concerns please let me know.

**Comment by k3yavi** [comment]
Hi @mikldk , I am ready with my comments, may I ask ask where can I upload the checklist, as mentioned [here](https://joss.readthedocs.io/en/latest/review_checklist.html).

**Comment by mikldk** [comment]
@k3yavi That sounds great. Please hang on to the comments while we find an additional reviewer. Once that is done, I will create a review issue with a checklist that you can use (and mention additional things in that issue or by creating issues in the software's repo that are then mentioning the review issue).

@mbhall88 Unfortunately, it seems like @kblin is unable to review. Can you please suggest two additional reviewers (please do not tag them)

**Comment by mbhall88** [comment]
`holtgrewe` and `bovee`?

**Comment by mikldk** [comment]
@holtgrewe, @holtgrewe: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by holtgrewe** [comment]
@mikldk I'd be happy to review this submission.

**Comment by mikldk** [comment]
@whedon add @holtgrewe as reviewer

**Comment by whedon** [comment]
OK, @holtgrewe is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3941.
