### ISSUE TITLE
[PRE REVIEW]: Annoroad Browser: A multi-omic visualization tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3833]
**Submitting author:** @Spartanzhao (<a href="http://orcid.org/0000-0001-5293-820X">Yue Zhao</a>)
**Repository:** <a href="https://github.com/Spartanzhao/Annoroad-Browser/" target ="_blank">https://github.com/Spartanzhao/Annoroad-Browser/</a>
**Version:** v.1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9029dfa1e742250ebbb3091cb78dc19a/status.svg)](https://joss.theoj.org/papers/9029dfa1e742250ebbb3091cb78dc19a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9029dfa1e742250ebbb3091cb78dc19a"><img src="https://joss.theoj.org/papers/9029dfa1e742250ebbb3091cb78dc19a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9029dfa1e742250ebbb3091cb78dc19a/status.svg)](https://joss.theoj.org/papers/9029dfa1e742250ebbb3091cb78dc19a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Spartanzhao. **Currently, there isn't an JOSS editor assigned** to your paper.

@Spartanzhao if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what went wrong with the paper compilation? :point_up:

**Comment by Spartanzhao** [comment]
> @openjournals/dev can you see what went wrong with the paper compilation? ☝️

Hi, I had revised my github repository, How can I resubmit again?

**Comment by Spartanzhao** [comment]
> Paper compilation is failing because the metadata block is not closed.
> 
> Invalid:
> 
> ```yaml
> ---
> title: 'Annoroad Browser: A biological multi-omic visualization tool'
> tags:
>   - Python
>   - bioinformatics
>   - multi omic
>   - Hi-C
>   - visualization
> authors:
>   - name: Zhao Yue^[co-first author] 
>     orcid: 0000-0001-5293-820X
>     affiliation: 1
>   - name: Yuan Zan^[co-first author] # note this makes a footnote saying 'co-first author'
>     affiliation: 1
> affiliations:
>  - name: Zhao Yue, Senior bioinformatic engineer , Beijing Annoroad Genomics
>    index: 1
> 
> date: 18 October 2021
> bibliography: paper.bib
> 
> 
> # Summary
> Different types of high throughput sequencing such as Hi-C, ChIP-seq, ATAC-seq, Cut&Tag, transcriptome...
> ```
> 
> Correct:
> 
> ```yaml
> ---
> title: 'Annoroad Browser: A biological multi-omic visualization tool'
> tags:
>   - Python
>   - bioinformatics
>   - multi omic
>   - Hi-C
>   - visualization
> authors:
>   - name: Zhao Yue^[co-first author] 
>     orcid: 0000-0001-5293-820X
>     affiliation: 1
>   - name: Yuan Zan^[co-first author] # note this makes a footnote saying 'co-first author'
>     affiliation: 1
> affiliations:
>  - name: Zhao Yue, Senior bioinformatic engineer , Beijing Annoroad Genomics
>    index: 1
> 
> date: 18 October 2021
> bibliography: paper.bib
> ---
> 
> # Summary
> Different types of high throughput sequencing such as Hi-C, ChIP-seq, ATAC-seq, Cut&Tag, transcriptome...
> ```
> 
> Notice the second `---`

Hi， I had revised my paper.md, how can I resubmit again?
