### ISSUE TITLE
[PRE REVIEW]: PICOS: A Python interface to conic optimization solvers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3835]
**Submitting author:** @Viech (<a href="http://orcid.org/0000-0002-0190-2693">Maximilian Stahlberg</a>)
**Repository:** <a href="https://gitlab.com/picos-api/picos" target ="_blank">https://gitlab.com/picos-api/picos</a>
**Version:** v2.3
**Editor:** @melissawm
**Reviewers:** @sfuxy, @marwahaha
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/bd72442e34002c825f672716b2870c98/status.svg)](https://joss.theoj.org/papers/bd72442e34002c825f672716b2870c98)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bd72442e34002c825f672716b2870c98"><img src="https://joss.theoj.org/papers/bd72442e34002c825f672716b2870c98/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bd72442e34002c825f672716b2870c98/status.svg)](https://joss.theoj.org/papers/bd72442e34002c825f672716b2870c98)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Viech. **Currently, there isn't an JOSS editor assigned** to your paper.

@Viech if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by Viech** [comment]
Hello!

The two proposed DOIs seem correct; I added both to `paper.bib`. Note that the journal paper [here](https://dl.acm.org/doi/10.5555/2946645.3007036) has a DOI in the URL but [doi.org does not recognize it](https://dx.doi.org/10.5555/2946645.3007036), so I left it without one.

Making my co-author @gsagnol aware of this review.

@whedon check references from branch joss

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by melissawm** [comment]
Thanks for your patience, I have been out of office.

👋🏻 Hello @sfuxy, @marwahaha, @sayakpaul would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by marwahaha** [comment]
I can review sometime in December.

**Comment by sayakpaul** [comment]
Hi @melissawm. Unfortunately, I will have to pass this one out.

**Comment by sfuxy** [comment]
Hello Melissa,

Yes, I will be able to start reviewing after thanksgiving. I’m very
familiar with conic programming, SOCP/SDP but it’s my first time review
with JOSS.
If I have questions related to the review process, can I refer them to you?

Thanks,
Silvano

Il giorno martedì 9 novembre 2021, Melissa Weber Mendonça <
***@***.***> ha scritto:

**Comment by melissawm** [comment]
Of course, @sfuxy - that is perfectly fine, feel free to ping if you have any questions. If @Viech is ok with the review starting in december, I can assign @marwahaha, otherwise we can try to find another reviewer. 

Just for information, I will assign @sfuxy as reviewer but the actual review issue will only start after a second reviewer is decided on.

**Comment by melissawm** [comment]
@whedon assign @sfuxy as reviewer

**Comment by whedon** [comment]
OK, @sfuxy is now a reviewer

**Comment by Viech** [comment]
I'm fine with the review starting in December!

**Comment by melissawm** [comment]
Great, then I'll add @marwahaha as a reviewer and we can start. This will automatically close this issue, and a new one (where the actual review will happen) will be opened, and you all will be tagged on it. Thanks!

**Comment by melissawm** [comment]
@whedon add @marwahaha as reviewer

**Comment by whedon** [comment]
OK, @marwahaha is now a reviewer

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3915.
