### ISSUE TITLE
[PRE REVIEW]: MetaWards: A flexible metapopulation framework for modelling disease spread

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3840]
**Submitting author:** @chryswoods (<a href="http://orcid.org/0000-0001-6563-9903">Christopher Woods</a>)
**Repository:** <a href="https://github.com/metawards/MetaWards" target ="_blank">https://github.com/metawards/MetaWards</a>
**Version:** v1.6.1
**Editor:** @majensen
**Reviewers:** @klmedeiros, @acolum
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/417370bd5dcf72fbc9438ff8bf2f2b66/status.svg)](https://joss.theoj.org/papers/417370bd5dcf72fbc9438ff8bf2f2b66)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/417370bd5dcf72fbc9438ff8bf2f2b66"><img src="https://joss.theoj.org/papers/417370bd5dcf72fbc9438ff8bf2f2b66/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/417370bd5dcf72fbc9438ff8bf2f2b66/status.svg)](https://joss.theoj.org/papers/417370bd5dcf72fbc9438ff8bf2f2b66)
```

**Author instructions**

Thanks for submitting your paper to JOSS @chryswoods. **Currently, there isn't an JOSS editor assigned** to your paper.

@chryswoods if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by chryswoods** [comment]
Thanks for considering our submission. I've looked at the list of possible reviewers and maybe acolum, klmedeiros, barryrowlingson, stensy or ibontama? (I am looking at the intersection of epidemiology and python)

Thanks again for your time. Please let me know if there is anything I can do to help.

**Comment by majensen** [comment]
@chryswoods many apologies - I have been AWOL. I will get rolling with reviewers for your work.

**Comment by majensen** [comment]
@amoeba - would you have time/interest in reviewing [this work](#3840) for JOSS? Much appreciated as ever -

**Comment by majensen** [comment]
@acolum - Would you have time and interest in reviewing [this work](#3840) for [JOSS](https://joss.theoj.org)? Really appreciate your help in the past. Thanks -@majensen

**Comment by majensen** [comment]
@klmedeiros - Thanks for your previous reviews for [JOSS](https://joss.theoj.org). Would you have time and interest to review [this new work](#3840)? Appreciate your consideration- 
- @majensen

**Comment by klmedeiros** [comment]
@majensen I'd be happy to!

**Comment by majensen** [comment]
@klmedeiros awesome, will add you in a jiffy

**Comment by majensen** [comment]
@whedon assign @klmedeiros as reviewer

**Comment by whedon** [comment]
OK, @klmedeiros is now a reviewer

**Comment by acolum** [comment]
@majensen Thank you, and I'd be happy to as well.

**Comment by majensen** [comment]
Wonderful @acolum!

**Comment by majensen** [comment]
@whedon add @acolum as reviewer

**Comment by whedon** [comment]
OK, @acolum is now a reviewer

**Comment by majensen** [comment]
@amoeba - thanks for considering - I have got agreement from two others, so you're off the hook for this one - MAJ

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3914.

**Comment by majensen** [comment]
@chryswoods - thanks for your patience and @acolum @klmedeiros thanks for your service- we'll perform the review over at #3914
