### ISSUE TITLE
[PRE REVIEW]: Microbiome.jl and BiobakeryUtils.jl - Julia packages for working with microbial community data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3841]
**Submitting author:** @kescobo (<a href="http://orcid.org/0000-0003-3200-7533">Bonham, Kevin</a>)
**Repository:** <a href="https://github.com/EcoJulia/Microbiome.jl" target ="_blank">https://github.com/EcoJulia/Microbiome.jl</a>
**Version:** v0.8.0
**Editor:** @will-rowe
**Reviewers:** @adRn-s, @aguang
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/450fa18f47932c5fd3b837edeac91440/status.svg)](https://joss.theoj.org/papers/450fa18f47932c5fd3b837edeac91440)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/450fa18f47932c5fd3b837edeac91440"><img src="https://joss.theoj.org/papers/450fa18f47932c5fd3b837edeac91440/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/450fa18f47932c5fd3b837edeac91440/status.svg)](https://joss.theoj.org/papers/450fa18f47932c5fd3b837edeac91440)
```

**Author instructions**

Thanks for submitting your paper to JOSS @kescobo. **Currently, there isn't an JOSS editor assigned** to your paper.

@kescobo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@kescobo thanks for this submission. I will be helping to look for a handling editor. 

@kescobo Note that in the readme for Microbiome.nl you point to: `https://github.com/EcoJulia/BiobakeryUtils` which gives a 404 error since the `.jl` part is missing, the correct URL seems to be: https://github.com/EcoJulia/BiobakeryUtils.jl

**Comment by whedon** [comment]
Wordcount for `paper.md` is 963

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/nu13082833 is OK
- 10.3390/microorganisms9081608 is OK
- 10.1137/141000671 is OK
- 10.21105/joss.03349 is OK
- 10.7554/eLife.65088 is OK
- 10.5281/zenodo.5566503 is OK

MISSING DOIs

- 10.1186/s13059-017-1359-z may be a valid DOI for title: Experimental design and quantitative analysis of microbial community multiomics
- 10.5334/jors.151 may be a valid DOI for title: Differentialequations.jl–a performant and feature-rich ecosystem for solving differential equations in julia

INVALID DOIs

- 10.3389/fmicb.2021.670336 is INVALID
```

**Comment by kescobo** [comment]
Alright! Finally got the "stable" docs for BiobakeryUtils to build correctly.

@adRn-s and @aguang thanks for agreeing to review! It's up to you of course, but I suggest [starting here](https://docs.ecojulia.org/BiobakeryUtils.jl/stable/gettingstarted/#getting-started) in the docs

**Comment by adRn-s** [comment]
Great. I've followed the docs without any problem so far. At least, until the installation of biobakeryutils. But...

Is ok to report issues here? If so:

I'm unable to run the `metaphlan()` function because [this URL](https://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_latest) is 404... or maybe without SSL cert? I tried `http` (without **s**) and only saw a text in my web browser.

**Comment by adRn-s** [comment]
Great!

PS. I had some issue, but apparently it was my connectivity

**Comment by will-rowe** [comment]
Hi all. I'm having some Github difficulties with this thread for some reason. I will assign our reviewers and move this to a review issue. Thank you for agreeing to review and to @kescobo for getting the docs ready

**Comment by will-rowe** [comment]
@whedon assign @adRn-s as reviewer

**Comment by whedon** [comment]
OK, @adRn-s is now a reviewer

**Comment by will-rowe** [comment]
@whedon add @aguang as reviewer

**Comment by whedon** [comment]
OK, @aguang is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3876.
