### ISSUE TITLE
[PRE REVIEW]: PySINDy: A comprehensive Python package for robust sparse system identification

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3845]
**Submitting author:** @akaptano (<a href="http://orcid.org/0000-0002-6337-2907">Alan Kaptanoglu</a>)
**Repository:** <a href="https://github.com/dynamicslab/pysindy" target ="_blank">https://github.com/dynamicslab/pysindy</a>
**Version:** v1.2.3
**Editor:** @sbenthall
**Reviewers:** @henrykironde, tuelwer
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a54fbe1f73ab517ef7d1c1e2e84fe73b/status.svg)](https://joss.theoj.org/papers/a54fbe1f73ab517ef7d1c1e2e84fe73b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a54fbe1f73ab517ef7d1c1e2e84fe73b"><img src="https://joss.theoj.org/papers/a54fbe1f73ab517ef7d1c1e2e84fe73b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a54fbe1f73ab517ef7d1c1e2e84fe73b/status.svg)](https://joss.theoj.org/papers/a54fbe1f73ab517ef7d1c1e2e84fe73b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @akaptano. **Currently, there isn't an JOSS editor assigned** to your paper.

@akaptano if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by tbsexton** [comment]
> @tbsexton would you be available to review this submission?

Let me take a look, but at a glance I believe so! Thanks for the ping.

**Comment by sbenthall** [comment]
@henrykironde Thank you for volunteering. Normally, I would assign you as a reviewer immediately. However, in this case the author seems to have a strong preference for reviewers in their area of research, and has named several. I will keep you in mind as a backup!

**Comment by sbenthall** [comment]
@tbsexton Were you able to give it a look?

@astanziola would you be able to review this submission?

**Comment by akaptano** [comment]
@sbenthall sorry if I gave you the wrong impression -- I was simply suggesting people to try and make your job a bit easier. Even my suggestions for reviewers mostly do not overlap with my area of research, so I am quite happy if you put Henry as a reviewer.

**Comment by astanziola** [comment]
Hi! This looks like a wonderful project, but unfortunately I don't have enough time to guarantee a timely review on this, I'm sorry.

**Comment by sbenthall** [comment]
Ah, ok, thanks for that clarification @akaptano 

@henrykironde you're on deck now. Thanks for volunteering!

**Comment by sbenthall** [comment]
@whedon assign @henrykironde as reviewer

**Comment by whedon** [comment]
OK, @henrykironde is now a reviewer

**Comment by sbenthall** [comment]
@sea-bass Would you be able to review this submission?

@karnigili Would you able to review this submission?

**Comment by sbenthall** [comment]
@georgiastuart would you be able to review this submission?

**Comment by georgiastuart** [comment]
@sbenthall when do you need the review in by? I'm behind on a couple of other reviews but can do this in December (or maybe January) if that's not too late.

**Comment by akaptano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03845/joss.03845/10.21105.joss.03845.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03845/joss.03845/10.21105.joss.03845.pdf) :page_facing_up: :point_left:

**Comment by akaptano** [comment]
@whedon generate pdf from branch PDEFIND_and_IntegralSINDy

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch PDEFIND_and_IntegralSINDy. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03845/joss.03845/10.21105.joss.03845.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03845/joss.03845/10.21105.joss.03845.pdf) :page_facing_up: :point_left:

**Comment by sbenthall** [comment]
@georgiastuart There is no strict timeline for reviews. It is common for reviews to take a month or two. If you think you can get to this in December or January, I'd say your timing is entirely appropriate. May I add you as a reviewer?

**Comment by sbenthall** [comment]
@tuelwer Would you be able to review this submission?

**Comment by sbenthall** [comment]
@sayakpaul would you be able to review this submission?

**Comment by akaptano** [comment]
Merged the branch into master, everything is now included in release 1.5.1, so regenerating the pdf here:

@whedon generate pdf

**Comment by akaptano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03845/joss.03845/10.21105.joss.03845.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03845/joss.03845/10.21105.joss.03845.pdf) :page_facing_up: :point_left:

**Comment by tuelwer** [comment]
@sbenthall Yes, I can write a review for this submission! 👍

**Comment by sbenthall** [comment]
Thank you @tuelwer ! I'll sign you up.

**Comment by sbenthall** [comment]
@whedon add tuelwer as reviewer

**Comment by whedon** [comment]
OK, tuelwer is now a reviewer

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3994.
