### ISSUE TITLE
[PRE REVIEW]: Intracranial Electrode Location and Analysis in MNE-Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3847]
**Submitting author:** @alexrockhill (<a href="http://orcid.org/0000-0003-3868-7453">Alexander Rockhill</a>)
**Repository:** <a href="https://github.com/mne-tools/mne-python" target ="_blank">https://github.com/mne-tools/mne-python</a>
**Version:** 0.24.dev0
**Editor:** @prashjha
**Reviewers:** @TomDonoghue, @janfreyberg
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cc3e2851a5ade159cd1988a4b0732054/status.svg)](https://joss.theoj.org/papers/cc3e2851a5ade159cd1988a4b0732054)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cc3e2851a5ade159cd1988a4b0732054"><img src="https://joss.theoj.org/papers/cc3e2851a5ade159cd1988a4b0732054/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cc3e2851a5ade159cd1988a4b0732054/status.svg)](https://joss.theoj.org/papers/cc3e2851a5ade159cd1988a4b0732054)
```

**Author instructions**

Thanks for submitting your paper to JOSS @alexrockhill. **Currently, there isn't an JOSS editor assigned** to your paper.

@alexrockhill if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by prashjha** [comment]
Howdy, @TomDonoghue! Would you be interested in reviewing this submission?

**Comment by prashjha** [comment]
Hello, @kczimm! This submission may be of interest to you. Any chance you could review it?

**Comment by kczimm** [comment]
Hey @prashjha, I'm sorry I'm unable to review this at the moment.

**Comment by prashjha** [comment]
@kczimm no worries. Thanks for letting me know fast!! Have a good one.

**Comment by prashjha** [comment]
Hi @spinicist, would you be interested in reviewing this submission?

**Comment by TomDonoghue** [comment]
@prashjha - this looks super interesting, and within my area - I'd be happy to review it!

**Comment by prashjha** [comment]
Great, adding you now! :)

**Comment by prashjha** [comment]
@whedon assign @TomDonoghue as reviewer

**Comment by whedon** [comment]
OK, @TomDonoghue is now a reviewer

**Comment by spinicist** [comment]
Hello, I sadly don't have the time but looks like you are quorate for the review now?

**Comment by prashjha** [comment]
Hi @spinicist, we need one more. Thanks for a prompt response.

Is this a hard pass? If we don't find one more reviewer, would you be able to take this up??

**Comment by spinicist** [comment]
Apologies for misunderstanding.

I do not have time at the moment to do the review.

**Comment by prashjha** [comment]
Okay!! Have a good one.

**Comment by prashjha** [comment]
Hi Jan, @janfreyberg! Would you be interested in reviewing this submission?

**Comment by janfreyberg** [comment]
Hi, yes - happy to review this :)

**Comment by janfreyberg** [comment]
@whedon assign @janfreyberg as reviewer

**Comment by whedon** [comment]
I'm sorry @janfreyberg, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by prashjha** [comment]
@janfreyberg super thanks for agreeing to review. :)

**Comment by prashjha** [comment]
@whedon add @janfreyberg as reviewer

**Comment by whedon** [comment]
OK, @janfreyberg is now a reviewer

**Comment by prashjha** [comment]
Hi @alexrockhill, we now have two reviewers so I will start the review process.

Thanks in advance @TomDonoghue and @janfreyberg for your time.

**Comment by prashjha** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3897.
