### ISSUE TITLE
[PRE REVIEW]: hei: Calculate Healthy Eating Index (HEI) Scores

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#385]
**Submitting author:** @timfolsom (<a href="http://orcid.org/0000-0002-8647-5810">Timothy Folsom</a>)
**Repository:** <a href="https://github.com/timfolsom/hei" target ="_blank">https://github.com/timfolsom/hei</a>
**Version:** v0.1.0
**Editor:** @leeper
**Reviewer:** @maelle

**Author instructions**

Thanks for submitting your paper to JOSS @timfolsom. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@timfolsom if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @leeper - would you be willing to edit this submission for JOSS?

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon assign @maelle as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @maelle

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/417. Feel free to close this issue now!
