### ISSUE TITLE
[PRE REVIEW]: PopMedNet: A scalable and extensible open-source informatics platform designed to facilitate the implementation and operation of distributed health data networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3851]
**Submitting author:** @ddeehere (<a href="http://orcid.org/0000-0001-7021-6227">Daniel Dee</a>)
**Repository:** <a href="https://github.com/PopMedNet-Team/popmednet.git" target ="_blank">https://github.com/PopMedNet-Team/popmednet</a>
**Version:** 2021.4
**Editor:** @danielskatz
**Reviewers:** @jhancock4d, @lrasmus
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b/status.svg)](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b"><img src="https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b/status.svg)](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ddeehere. **Currently, there isn't an JOSS editor assigned** to your paper.

@ddeehere if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@ddeehere - We've just finished the scope discussion, and this has been approved to be reviewed.  I'll remove the scope query label and start working on finding an editor to start the review

**Comment by danielskatz** [comment]
👋 @csoneson - do you think you can edit this submission?  It's a little different than most submissions...

**Comment by danielskatz** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by ddeehere** [comment]
> 👋 @csoneson - do you think you can edit this submission? It's a little different than most submissions...

Yes, we can edit the submission. Can you provide some guidance on where we differ from others so that we know where we are deficient? Thank you.

**Comment by danielskatz** [comment]
👋 @ddeehere - I think you missed that fact that the invitation to edit was to @csoneson. JOSS reviews include a number of roles, including 
* an Assistant Editor-in-Chief (AEiC), currently me
* an editor, to be found by the AEiC, not currently filled
* at least two reviewers, to be found by the editor, not currently filled
* the author, you

**Comment by csoneson** [comment]
@danielskatz - sorry, I'm afraid this is really quite a bit out of my comfort zone/experience on the implementation side 😬 If it's possible to find someone with experience in web applications or database querying, I think that would be a better fit in this case.

**Comment by danielskatz** [comment]
@whedon assign me as editor

I'll take it :)

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@ddeehere - I'll be the editor.  The next step is to find at least 2 reviewers.  If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
external are fine - the list is just one resource if useful
(of course, please keep in mind the [JOSS conflict of interest guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy))

**Comment by danielskatz** [comment]
@ddeehere - any further suggestions?

**Comment by danielskatz** [comment]
👋 @martinmodrak & @borishejblum - would one of both of you be willing to review this JOSS submission?

**Comment by ddeehere** [comment]
> @ddeehere - any further suggestions?

For external reviewers, would a developer who works for the same company (but not directly involved in the PopMedNet development) be acceptable? How about a subcontractor for Harvard Pilgrim Health Care Institute (who's the primary mover of PopMedNet) be acceptable? I am thinking in terms of whether that will violate conflict of interest guidelines. Neither of them are actively involved in PopMedNet.

**Comment by danielskatz** [comment]
someone from the same company would not make sense, but someone who is a user would

**Comment by martinmodrak** [comment]
Unfortunately, this is both at the very edge of my knowledge (I did some WinForms a long time ago, but have never used ASP.NET, I also now only bare minimum on security) and quite a large project - I won't be able to set aside time to review it responsibly at the moment.

**Comment by danielskatz** [comment]
👋  @scossin & @vianneyJouhet - would one or both of you be willing to review this JOSS submission?

JOSS is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged.

JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html

Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

**Comment by danielskatz** [comment]
👋 @ddeehere - I probably need some more suggestions from you.

**Comment by danielskatz** [comment]
👋 @scossin & @vianneyJouhet - just checking with you both again re https://github.com/openjournals/joss-reviews/issues/3851#issuecomment-963542710

**Comment by ddeehere** [comment]
@danielskatz - I am checking with a few contacts to see if any could review without violating conflict of interest rule.

> 👋 @ddeehere - I probably need some more suggestions from you.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03851/joss.03851/10.21105.joss.03851.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03851/joss.03851/10.21105.joss.03851.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
I've been reaching out to a lot of people about being potential reviewers, and one has accepted - thanks @jsaw5

**Comment by danielskatz** [comment]
I'll add you in the system now, but we won't start the review until we find at least one more reviewer

**Comment by danielskatz** [comment]
@whedon assign @jsaw5 as reviewer

**Comment by whedon** [comment]
OK, @jsaw5 is now a reviewer

**Comment by danielskatz** [comment]
Unfortunately, @jsaw5 is not going to be able to review this, so I'm removing her

**Comment by danielskatz** [comment]
@whedon remove @jsaw5 as reviewer

**Comment by whedon** [comment]
OK, @jsaw5 is no longer a reviewer

**Comment by ddeehere** [comment]
@danielskatz I have reached out and waiting to hear from potential reviewers from outside JOSS volunteers.

**Comment by danielskatz** [comment]
Thanks - I'm continuing to do this as well

**Comment by danielskatz** [comment]
@ddeehere - I've had no luck finding reviewers. Unfortunately, if we cannot find reviewers, we cannot proceed.  I hope you will have more luck than I have.

**Comment by ddeehere** [comment]
> @ddeehere - I've had no luck finding reviewers. Unfortunately, if we cannot find reviewers, we cannot proceed. I hope you will have more luck than I have.

@danielskatz I found someone who's keeping it open to try to review before January. He did recommend another person, which I will reach out to see if he's available.

**Comment by ddeehere** [comment]
@danielskatz I got someone who's willing to review it. He's asking if there are examples of other reviews he can look at to give him some guidance on what he has to do. Can you point me to some reviews of other submissions? Thanks and Happy Holidays!

**Comment by danielskatz** [comment]
@ddeehere - every published paper from JOSS (https://joss.theoj.org/papers/published) has a link on the right side for Paper review.  In addition, https://joss.readthedocs.io/en/latest/reviewer_guidelines.html provides general guidelines.

**Comment by ddeehere** [comment]
@danielskatz I found a reviewer. His Github handle is: jhancock4d

Let me know if there is something he or I need to do for him to proceed. Thank you.

**Comment by danielskatz** [comment]
Thanks @ddeehere - we do also need to find one more reviewer - JOSS requires two.

**Comment by danielskatz** [comment]
👋 @jhancock4d - @ddeehere has said you are willing to review this. Please confirm, and I will assign you, but we will not actually start the review until we also find one more reviewer.

**Comment by jhancock4d** [comment]
@danielskatz Confirmed!

**Comment by danielskatz** [comment]
@whedon assign @jhancock4d as reviewer

again, we won't start the actual review until we find one more reviewer

**Comment by whedon** [comment]
OK, @jhancock4d is now a reviewer

**Comment by danielskatz** [comment]
@ddeehere (and @jhancock4d) - I've been on vacation the last two weeks and am also this week, but I'll start looking for another reviewer again on the 10th.  If you have any suggestions, please also make them here.

**Comment by danielskatz** [comment]
👋 @lrasmus - thanks very much for volunteering to review this submission.  I'll add you, and then start the review, which will open a new issue, and I'll comment again there.

**Comment by danielskatz** [comment]
@whedon add @lrasmus as reviewer

**Comment by whedon** [comment]
OK, @lrasmus is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4062.
