### ISSUE TITLE
[PRE REVIEW]: Torque-limited simple pendulum: A toolkit for getting familiar with control algorithms in underactuated robotics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3853]
**Submitting author:** @fwiebe (<a href="http://orcid.org/0000-0002-2195-9697">Felix Wiebe</a>)
**Repository:** <a href="https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum" target ="_blank">https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum</a>
**Version:** v1.0.0
**Editor:** @gkthiruvathukal
**Reviewers:** @ricopicone, @jingnanshi
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/77462b287597cd368b8da2b18424ae63/status.svg)](https://joss.theoj.org/papers/77462b287597cd368b8da2b18424ae63)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/77462b287597cd368b8da2b18424ae63"><img src="https://joss.theoj.org/papers/77462b287597cd368b8da2b18424ae63/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/77462b287597cd368b8da2b18424ae63/status.svg)](https://joss.theoj.org/papers/77462b287597cd368b8da2b18424ae63)
```

**Author instructions**

Thanks for submitting your paper to JOSS @fwiebe. **Currently, there isn't an JOSS editor assigned** to your paper.

@fwiebe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by fwiebe** [comment]
@gkthiruvathukal I would propose any of
 
@CameronDevine, @vmatos, @stevemacenski, @sea-bass

 as reviewers, The following could fit as well:

@jizecn, @jingnanshi, @seungback, @giodegas, @ekorudiawan, @destogl, @nnadeau, @trallard, @OlgerSiebinga

**Comment by nnadeau** [comment]
Sorry, not available in the short term 🙁

**Comment by CameronDevine** [comment]
This looks like an excellent submission. Unfortunately, I don't currently have time to be part of the review process. However, I believe one of my colleagues, @ricopicone, could be another potential reviewer.

**Comment by ricopicone** [comment]
I can review this, per @CameronDevine's suggestion. I don't believe I'm on the reviewer list but here's my academic profile:
[http://ricopic.one/](http://ricopic.one/)
If you would like me to review this and there are reviewer instructions please send them my way.

**Comment by gkthiruvathukal** [comment]
@ricopicone  Thanks for being willing to help! Let me figure out whether you need to be registered as a reviewer or not. Thanks for sharing your profile!

@openjournals/joss-eics   Am I able to add @ricopicone as a reviewer? Or does he need to be added to our list of people first?

**Comment by jingnanshi** [comment]
I am happy to review this project. Please let me know what are the next steps.

**Comment by kthyng** [comment]
@gkthiruvathukal and @ricopicone Anyone with access to github can review regardless of the reviewer list (pending COI concerns as appropriate of course). If you want to sign up, here is the means to do so: https://joss.theoj.org/reviewer-signup.html. Otherwise please proceed!

**Comment by trallard** [comment]
I am so sorry I do not have capacity right now

**Comment by gkthiruvathukal** [comment]
@ricopicone So happy that you are willing to help with this review. I will invite you know.

@trallard I am sorry you're so busy! I know the feeling. I will try to find a second reviewer.

**Comment by gkthiruvathukal** [comment]
@whedon assign @ricopicone as reviewer

**Comment by whedon** [comment]
OK, @ricopicone is now a reviewer

**Comment by ricopicone** [comment]
@gkthiruvathukal will whedon generate a reviewer checklist like I see [here](https://github.com/openjournals/joss-reviews/issues/3783)? I have reviewed the review criteria and checklist from the JOSS docs and can begin reviewing.

**Comment by SteveMacenski** [comment]
On vacation, can’t do this one unfortunately

**Comment by sea-bass** [comment]
I'm unable to review this one as well, as my work is keeping me quite busy at the moment.

**Comment by gkthiruvathukal** [comment]
@SeungBack Are you willing to help review this JOSS submission? I need a second reviewer before I can begin the review process. (@ricopicone, you'll see this once we get a second reviewer, to answer your question above.)

**Comment by jingnanshi** [comment]
@gkthiruvathukal Not sure whether you've seen my earlier comment, but I'm happy to review this submission.

**Comment by gkthiruvathukal** [comment]
@jingnanshi Thank you so much! I will add you and get started.

**Comment by gkthiruvathukal** [comment]
@whedon add @jingnanshi as reviewer

**Comment by whedon** [comment]
OK, @jingnanshi is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3884.

**Comment by SeungBack** [comment]
@gkthiruvathukal Thank you for the suggestion, but I am not available to review it at this moment.

**Comment by gkthiruvathukal** [comment]
@SeungBack Thanks! I was able to find two reviewers. Best!
