### ISSUE TITLE
[PRE REVIEW]: DEVSIM: A TCAD Semiconductor Device Simulator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3854]
**Submitting author:** @tcaduser (<a href="http://orcid.org/0000-0002-6783-0194">Juan E. Sanchez</a>)
**Repository:** <a href="https://github.com/devsim/devsim.git" target ="_blank">https://github.com/devsim/devsim.git</a>
**Version:** v1.6.0
**Editor:** @lucydot
**Reviewers:** @jgoldfar, @dalonsoa
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/962b5ad390d866433b5efb68b4b68168/status.svg)](https://joss.theoj.org/papers/962b5ad390d866433b5efb68b4b68168)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/962b5ad390d866433b5efb68b4b68168"><img src="https://joss.theoj.org/papers/962b5ad390d866433b5efb68b4b68168/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/962b5ad390d866433b5efb68b4b68168/status.svg)](https://joss.theoj.org/papers/962b5ad390d866433b5efb68b4b68168)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tcaduser. **Currently, there isn't an JOSS editor assigned** to your paper.

@tcaduser if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by lucydot** [comment]
Hi @tcaduser thanks for the suggestions!

Hi @Jgoldfar and @dalonsoa 👋 are you available to review this submission?

**Comment by jgoldfar** [comment]
Hi there Lucy, and thanks for thinking of me. I would be able to review
this work within the month, if that timeline works for this publication.

>

**Comment by dalonsoa** [comment]
Hi @lucydot , same here. Happy to provide a review for this during November.

**Comment by lucydot** [comment]
@whedon assign @jgoldfar as reviewer

**Comment by whedon** [comment]
OK, @jgoldfar is now a reviewer

**Comment by lucydot** [comment]
@whedon add @dalonsoa as reviewer

**Comment by whedon** [comment]
OK, @dalonsoa is now a reviewer

**Comment by lucydot** [comment]
@jgoldfar @dalonsoa thank-you for agreeing to review.  I'll ask our bot Whedon to start a review issue thread (this is the pre-review thread) - the review guidelines will be listed at the top of that new thread. 

We're asking for reviews to be complete within a 4-6 week period. As the review is usually an iterative process (rather than something you do in one sitting) it's best for reviews to start earlier in that timeline - providing the review through November will work well 👍

**Comment by lucydot** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3898.

**Comment by jgoldfar** [comment]
@whedon re-invite @jgoldfar as reviewer

**Comment by whedon** [comment]
I'm sorry @jgoldfar, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by jgoldfar** [comment]
Hi @lucydot - I think you may need to run the above command for me to be able to submit my review (found this on https://joss.readthedocs.io/en/latest/whedon.html)

**Comment by danielskatz** [comment]
@whedon re-invite @jgoldfar as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@jgoldfar please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by danielskatz** [comment]
Sorry, this actually should have been done in the review thread, not here, but I think it will still work.
