### ISSUE TITLE
[PRE REVIEW]: PyMPDATA v1: Numba-accelerated Pythonic implementation of MPDATA with examples in Python, Julia and Matlab

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3855]
**Submitting author:** @slayoo (<a href="http://orcid.org/0000-0003-2361-0082">Sylwester Arabas</a>)
**Repository:** <a href="https://github.com/atmos-cloud-sim-uj/PyMPDATA" target ="_blank">https://github.com/atmos-cloud-sim-uj/PyMPDATA</a>
**Version:** v1
**Editor:** @mjsottile
**Reviewers:** @dmikushin, @olekravchenko
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a/status.svg)](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a"><img src="https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a/status.svg)](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @slayoo. **Currently, there isn't an JOSS editor assigned** to your paper.

@slayoo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by slayoo** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03855/joss.03855/10.21105.joss.03855.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03855/joss.03855/10.21105.joss.03855.pdf) :page_facing_up: :point_left:

**Comment by slayoo** [comment]
(updated the paper.md with a figure and sample code snippets in Python, Julia and Matlab)

**Comment by mjsottile** [comment]
:wave: @slayoo Before I get started looking for reviewers I want to check to see if you have any specific people in mind that you would recommend be invited to review.  If so, please list them and I'll reach out.

**Comment by slayoo** [comment]
Hello, @mjsottile,
At the bottom of the PyMPDATA README file, we have listed several related projects (https://github.com/atmos-cloud-sim-uj/PyMPDATA#other-open-source-mpdata-implementations). Among contributors to these projects, and excluding folks we have co-authored with, there are the following Github users - perhaps potential reviewers:
- hilaryweller0 (https://github.com/AtmosFOAM/AtmosFOAM/commit/947b192f69d973ea4a7cfab077eb5c6c6fa8b0cf) 
- dmikushin (https://github.com/apc-llc/mpdata/graphs/contributors)
- anilzen, olekravchenko (https://github.com/olekravchenko/centpy/graphs/contributors)
- ThanasisMattas (https://github.com/ThanasisMattas/mattflow/graphs/contributors)
- stefanmeili (https://github.com/stefanmeili/FastFD/graphs/contributors)
- https://github.com/orgs/clawpack/people

Browsing through Github topics, some other projects can be found and filtered by language, e.g.:
- https://github.com/topics/advection-diffusion?l=Python
- https://github.com/topics/advection?l=Matlab
- https://github.com/topics/advection-diffusion?l=Julia

HTH, thank you,
Sylwester

**Comment by mjsottile** [comment]
:wave: @hilaryweller0, @dmikushin, @olekravchenko - you were suggested by the author of this submission to JOSS as potential reviewers. Would you be interested in providing a review? If you haven't reviewed for JOSS before, you can see the review criteria here : https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you are interested and I can add you as a reviewer to the submission.

**Comment by dmikushin** [comment]
Hi thanks for reaching out, I'm new to JOSS but will be happy to help!

**Comment by mjsottile** [comment]
@dmikushin Great - once we get another reviewer I can initiate the review.  Then you'll see the checklist in the review issue that gets created.  The process is pretty straightforward, and I'm happy to help or answer questions along the way.

**Comment by olekravchenko** [comment]
@mjsottile Hi, sure. I'm glad to take a part.

**Comment by mjsottile** [comment]
@whedon assign @dmikushin as reviewer

**Comment by whedon** [comment]
OK, @dmikushin is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @olekravchenko as reviewer

**Comment by whedon** [comment]
OK, @olekravchenko is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3896.
