### ISSUE TITLE
[PRE REVIEW]: Phonemizer: Text to Phones Transcription for Multiple Languages in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3856]
**Submitting author:** @mmmaat (<a href="http://orcid.org/0000-0001-7586-7133">Bernard</a>)
**Repository:** <a href="https://github.com/bootphon/phonemizer" target ="_blank">https://github.com/bootphon/phonemizer</a>
**Version:** v3.0
**Editor:** @danielskatz
**Reviewers:** @henrykironde, @chrisbrickhouse
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/08d1ffc14f233f56942f78f3742b266e/status.svg)](https://joss.theoj.org/papers/08d1ffc14f233f56942f78f3742b266e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/08d1ffc14f233f56942f78f3742b266e"><img src="https://joss.theoj.org/papers/08d1ffc14f233f56942f78f3742b266e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/08d1ffc14f233f56942f78f3742b266e/status.svg)](https://joss.theoj.org/papers/08d1ffc14f233f56942f78f3742b266e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mmmaat. **Currently, there isn't an JOSS editor assigned** to your paper.

@mmmaat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
👋 @sbenthall - a ping on this...  (and note that one reviewer has already volunteered :) )

**Comment by danielskatz** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by arfon** [comment]
I've just emailed @sbenthall directly. If we don't hear back from him in the next few days, we'll find another editor.

**Comment by sbenthall** [comment]
Hello. Sorry for the slow response on this.
I don't feel like I have the necessary expertise to be the editor on this paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
It looks like @faroit might be a good editor for this. They are however preoccupied with other submissions at the moment so I will mark this as `waitlisted` for the moment. 
@faroit if you can take this, let me know if we can assign you as editor. Thanks.

**Comment by danielskatz** [comment]
I'll edit this submission

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @henrykironde - thanks for volunteering to review - I'll add you, and once we find another reviewer, we'll start the review

**Comment by danielskatz** [comment]
@whedon assign @henrykironde as reviewer

**Comment by whedon** [comment]
OK, @henrykironde is now a reviewer

**Comment by danielskatz** [comment]
👋 @mmmaat - the next step is to find at least two reviewers. We have one already, and need at least one more. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by mmmaat** [comment]
Hi @danielskatz, thank you for editing this paper. After a brief search in the reviewers list I fount 6 potential reviewers with expertise in Python and Natural Language Processing (more are available):
* sergioburdisso (Python, NLP)
* chrisbrickhouse (Python, linguistics)
* pzelasko (Python, speech, NLP)
* kmichael08 (Python, NLP)
* proycon (Python, NLP)
* aozorahime (Python, NLP)

**Comment by danielskatz** [comment]
👋 @sergioburdisso & @chrisbrickhouse - would one or both of you be willing to review this JOSS submission?

**Comment by chrisbrickhouse** [comment]
I would be willing to review

**Comment by danielskatz** [comment]
Thanks @chrisbrickhouse - I'll add you, and we can get started.

**Comment by danielskatz** [comment]
@whedon add @chrisbrickhouse as reviewer

**Comment by whedon** [comment]
OK, @chrisbrickhouse is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3958.

**Comment by sergioburdisso** [comment]
@danielskatz Nice to meet you and sorry for the delay! I have no problem to review this submission, but be aware that this is going to be my first time :worried:

**Comment by danielskatz** [comment]
Thanks @sergioburdisso - but we've found enough reviewers and started the reviewer - maybe next time
