### ISSUE TITLE
[PRE REVIEW]: MitoHEAR

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3857]
**Submitting author:** @gabrielelubatti (<a href="http://orcid.org/0000-0001-8495-8096">Gabriele Lubatti</a>)
**Repository:** <a href="https://github.com/ScialdoneLab/MitoHEAR" target ="_blank">https://github.com/ScialdoneLab/MitoHEAR</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ca81b408a4aa5d5338a9e90cdbfd00b0/status.svg)](https://joss.theoj.org/papers/ca81b408a4aa5d5338a9e90cdbfd00b0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ca81b408a4aa5d5338a9e90cdbfd00b0"><img src="https://joss.theoj.org/papers/ca81b408a4aa5d5338a9e90cdbfd00b0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ca81b408a4aa5d5338a9e90cdbfd00b0/status.svg)](https://joss.theoj.org/papers/ca81b408a4aa5d5338a9e90cdbfd00b0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @gabrielelubatti. **Currently, there isn't an JOSS editor assigned** to your paper.

@gabrielelubatti if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
👋 @gabrielelubatti - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission has issues with the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS, combined with a need for more work to make the software more mature, such as well-organized documentation, [packaging/installation](https://joss.readthedocs.io/en/latest/review_criteria.html#installation-instructions), hard-coded paths in vignettes, etc. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work. Alternatively, we would be happy to reconsider this software after work to address the points above.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
