### ISSUE TITLE
[PRE REVIEW]: SimuPy: A python framework for modeling and simulating dynamical systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#386]
**Submitting author:** @sixpearls (<a href="http://orcid.org/0000-0001-5602-1888">Benjamin Margolis</a>)
**Repository:** <a href="https://github.com/simupy/simupy" target ="_blank">https://github.com/simupy/simupy</a>
**Version:** v1.0.0
**Editor:** @cmadan
**Reviewer:** @demotu

**Author instructions**

Thanks for submitting your paper to JOSS @sixpearls. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sixpearls if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by sixpearls** [comment]
In terms of preferred languages and subject area, @moorepants is probably the best suited reviewer. However, we're at the same institution (and we know each other); I don't know what the JOSS policy is for this situation. In general I would trust @moorepants's ability to determine if he could be fair, especially so with the open discussion format. There are also a number of other reviewers who should be able to provide good feedback in addition to @moorepants.

If possible, I would appreciate it if the reviewer would be willing to work with me to get a DOI by Sept 8th so I can reference it in a conference manuscript. That's pretty soon, so I don't expect that to be treated as a hard constraint.

Thanks!
Ben

**Comment by sixpearls** [comment]
I just wanted to check in, @arfon. Would it be appropriate to suggest other reviewers/editors? I see a number of people familiar using Python and MATLAB (this project could be compared to Simulink) for solving ODE's and doing numerical modeling.

**Comment by cMadan** [comment]
@whedon assign @cmadan as editor

**Comment by whedon** [comment]
OK, the editor is @cmadan

**Comment by cMadan** [comment]
@sixpearls, I'm happy to serve as editor for this submission :)

@moorepants, if you think you can objectively review this project (and are otherwise available), I think it's fine to have you as a reviewer here. If not, perhaps @sixpearls can suggest someone else from the list linked in the first comment here.

**Comment by moorepants** [comment]
I'd prefer if some other reviewers are asked before me. Ben is a graduate student in my department's program and it would be best if there was a bit more conflict of interest gap between us. If no one else can do it, I may have time to do the review.

**Comment by sixpearls** [comment]
Thanks, @moorepants. I understand the preference!

It looks like @lheagy, @kyleniemeyer, and @katyhuff are all python users who might be familiar with this type of simulation. Perhaps one of you might be willing to review this?

**Comment by katyhuff** [comment]
@sixpearls :  I can probably do this, but not for a few weeks -- I'm booked solid for a while. Hopefully @lheagy or @kyleniemeyer will agree!

**Comment by kyleniemeyer** [comment]
@cMadan @sixpearls I could also probably review this, but I'd like to recommend finding a reviewer that isn't a JOSS editor... our plates are already pretty full.

**Comment by moorepants** [comment]
@sixpearls FYI, I found reviewers for my recent submission by looking for similar software on github and then asking the authors of those packages to review.

**Comment by lheagy** [comment]
@sixpearls, @cMadan: I would be happy to help with the review but I am travelling for the next 4 weeks so I am going to be slower to respond and am likely not the best choice to take point on the review. If you do find someone else to take point, I am happy to be a second reviewer

**Comment by sixpearls** [comment]
@katyhuff @kyleniemeyer @lheagy thanks for your responses. Appreciate you all taking the time to respond. Thanks for the suggestion about cross-referencing the editorial board list.

From the list, it looks like @arghdos and @mosteo work in related areas and use python. Beyond that, it would start to be at least a little out of field and/or preferred programming language based on the suggested reviewer list. I'm not sure how much that matters.

@moorepants thanks for the suggestion!

@demotu @siboles @stavness @melund @jslee02 @cybanical @chrisdembia would any of you be willing to review [my submission](https://github.com/simupy/simupy) to [JOSS](http://joss.theoj.org/)? I believe you're all familiar with the journal, but the review guidelines are [here](http://joss.theoj.org/about#reviewer_guidelines).

**Comment by demotu** [comment]
Yes, I can review your submission; the simupy sounds very interesting.

@demotu <https://github.com/demotu>

-
Marcos Duarte
http://demotu.org/

**Comment by cMadan** [comment]
@demotu, great! I'll set you as the reviewer then and start the review process.

If anyone else also wants to contribute to the review, please feel free to also make comments in the review issue.

**Comment by cMadan** [comment]
@whedon set @demotu as reviewer

**Comment by cMadan** [comment]
@whedon assign @demotu as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @demotu

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/396. Feel free to close this issue now!
