### ISSUE TITLE
[PRE REVIEW]: 3D Line Radiative Transfer & Synthetic Observations with Magritte

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3863]
**Submitting author:** @FredDeCeuster (<a href="http://orcid.org/0000-0001-5887-8498">Frederik De Ceuster</a>)
**Repository:** <a href="https://github.com/Magritte-code/Magritte" target ="_blank">https://github.com/Magritte-code/Magritte</a>
**Version:** 0.0.1
**Editor:** @xuanxu
**Reviewers:** @gonsie, @CFGrote
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/010e408b39422f6691f876925e37d256/status.svg)](https://joss.theoj.org/papers/010e408b39422f6691f876925e37d256)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/010e408b39422f6691f876925e37d256"><img src="https://joss.theoj.org/papers/010e408b39422f6691f876925e37d256/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/010e408b39422f6691f876925e37d256/status.svg)](https://joss.theoj.org/papers/010e408b39422f6691f876925e37d256)
```

**Author instructions**

Thanks for submitting your paper to JOSS @FredDeCeuster. **Currently, there isn't an JOSS editor assigned** to your paper.

@FredDeCeuster if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by xuanxu** [comment]
@mdelorme, @gonsie would you be willing to review this paper? I think your knowledge of Simulation software and C++/Python makes both of you a good fit for this submission.

**Comment by gonsie** [comment]
I can review.

**Comment by xuanxu** [comment]
@whedon add @gonsie as reviewer

**Comment by whedon** [comment]
OK, @gonsie is now a reviewer

**Comment by xuanxu** [comment]
@gonsie great, thanks! I'll start the review issue once we have the second reviewer. Stay tuned!

**Comment by xuanxu** [comment]
@StanczakDominik would you be willing to review this paper? I think your knowledge of physics simulation software makes you a good fit for this submission.

**Comment by StanczakDominik** [comment]
Apologies,I'd love to and the package looks awesome from a glance, but I'm already overcommitted as it is at the moment :(

**Comment by xuanxu** [comment]
@CFGrote would you be willing to review this paper? I think your knowledge of physics and Python/C++ makes you a good fit for this submission.

**Comment by CFGrote** [comment]
yes, count me in

**Comment by xuanxu** [comment]
@CFGrote great, thanks! I'll add you as reviewer and start the review issue right away

**Comment by xuanxu** [comment]
@whedon add @CFGrote as reviewer

**Comment by whedon** [comment]
OK, @CFGrote is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3905.
