### ISSUE TITLE
[PRE REVIEW]: retworkx: A High-Performance Graph Library for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3867]
**Submitting author:** @IvanIsCoding (<a href="http://orcid.org/0000-0002-8257-2103">Ivan Carvalho</a>)
**Repository:** <a href="https://github.com/Qiskit/retworkx/" target ="_blank">https://github.com/Qiskit/retworkx/</a>
**Version:** v0.10.2
**Editor:** @drvinceknight
**Reviewers:** @szhorvat, @inakleinbottle
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d88f8b00bb1c5dba0310a8e41a651732/status.svg)](https://joss.theoj.org/papers/d88f8b00bb1c5dba0310a8e41a651732)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d88f8b00bb1c5dba0310a8e41a651732"><img src="https://joss.theoj.org/papers/d88f8b00bb1c5dba0310a8e41a651732/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d88f8b00bb1c5dba0310a8e41a651732/status.svg)](https://joss.theoj.org/papers/d88f8b00bb1c5dba0310a8e41a651732)
```

**Author instructions**

Thanks for submitting your paper to JOSS @IvanIsCoding. **Currently, there isn't an JOSS editor assigned** to your paper.

@IvanIsCoding if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by szhorvat** [comment]
I would be interested in reviewing this.

**Comment by drvinceknight** [comment]
Thank @szhorvat, I will add you as a reviewer and deem to find other reviewers with expertise in Python/Rust.

**Comment by drvinceknight** [comment]
@whedon assign @szhorvat as reviewer

**Comment by whedon** [comment]
OK, @szhorvat is now a reviewer

**Comment by drvinceknight** [comment]
@jkbren, @inakleinbottle and @felipeZ I'm pinging you to ask if you would be able to assist with reviewing this submissions to JOSS (The Journal of Open Source Software).

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: “retworkx: A High-Performance Graph Library for Python” which I believe fits within your stated interests/expertise. You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by IvanIsCoding** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03867/joss.03867/10.21105.joss.03867.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03867/joss.03867/10.21105.joss.03867.pdf) :page_facing_up: :point_left:

**Comment by inakleinbottle** [comment]
@drvinceknight I'd be happy to review that article.

**Comment by drvinceknight** [comment]
Thanks @inakleinbottle

**Comment by drvinceknight** [comment]
@whedon add @inakleinbottle as reviewer

**Comment by whedon** [comment]
OK, @inakleinbottle is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3968.

**Comment by drvinceknight** [comment]
@szhorvat and @inakleinbottle the review has started over on #3968 where there are instructions and guidance. If you have any queries at all or if there is anything I can assist with please let me know.

**Comment by szhorvat** [comment]
Thanks @drvinceknight. There seems to be an issue with compiling the PDF in #3968.
