### ISSUE TITLE
[PRE REVIEW]: Falcon-Ripple-Client: A Graphical Ripple-detection Client for Falcon

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3868]
**Submitting author:** @MaybeJustJames (<a href="http://orcid.org/0000-0002-0020-421X">James Collier</a>)
**Repository:** <a href="https://bitbucket.org/kloostermannerflab/falcon-swr-client" target ="_blank">https://bitbucket.org/kloostermannerflab/falcon-swr-client</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c62b001630f187e67163247153288d22/status.svg)](https://joss.theoj.org/papers/c62b001630f187e67163247153288d22)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c62b001630f187e67163247153288d22"><img src="https://joss.theoj.org/papers/c62b001630f187e67163247153288d22/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c62b001630f187e67163247153288d22/status.svg)](https://joss.theoj.org/papers/c62b001630f187e67163247153288d22)
```

**Author instructions**

Thanks for submitting your paper to JOSS @MaybeJustJames. **Currently, there isn't an JOSS editor assigned** to your paper.

@MaybeJustJames if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by kthyng** [comment]
Hi @MaybeJustJames and thanks for your submission! I am going to ping the editorial board to make sure it is in scope — we usually take a closer look before reviewing GUIs so I just want to be sure before starting. This will take 1-2 weeks, thanks for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by MaybeJustJames** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by MaybeJustJames** [comment]
@kthyng The labels seem wrong to me: I would remove the `Makefile` and `Shell` labels and add a `Rust` label

**Comment by kthyng** [comment]
@MaybeJustJames Looks like @arfon added the labels ✅

**Comment by danielskatz** [comment]
👋 @MaybeJustJames - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission is not [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) as defined by JOSS, as it appears to be a GUI wrapper that does not provide new functionality. This does not mean that it is not software that is useful in research, but just that JOSS does not consider it in scope for review as research software. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
