### ISSUE TITLE
[PRE REVIEW]: RECOLO: A Python package for the reconstruction of surface pressure loads from kinematic fields using the virtual fields method

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3869]
**Submitting author:** @PolymerGuy (<a href="http://orcid.org/0000-0002-9981-4041">Sindre Nordmark Olufsen</a>)
**Repository:** <a href="https://github.com/PolymerGuy/recolo" target ="_blank">https://github.com/PolymerGuy/recolo</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @nicoguaro, @corentin-dev
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9c0b1dc9e5e554516bcad0fb918f4708/status.svg)](https://joss.theoj.org/papers/9c0b1dc9e5e554516bcad0fb918f4708)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9c0b1dc9e5e554516bcad0fb918f4708"><img src="https://joss.theoj.org/papers/9c0b1dc9e5e554516bcad0fb918f4708/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9c0b1dc9e5e554516bcad0fb918f4708/status.svg)](https://joss.theoj.org/papers/9c0b1dc9e5e554516bcad0fb918f4708)
```

**Author instructions**

Thanks for submitting your paper to JOSS @PolymerGuy. **Currently, there isn't an JOSS editor assigned** to your paper.

@PolymerGuy if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by kthyng** [comment]
Hi @PolymerGuy! Please take a look at the paper errors above. Also you will need a section entitled "Statement of Need" in your paper.

**Comment by kthyng** [comment]
Hi @Kevin-Mattheus-Moerman are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by PolymerGuy** [comment]
Hi @kthyng and @Kevin-Mattheus-Moerman ! I have now added the section "Statement of need" and hopefully fixed the bug related to affiliations above. When compiling the paper I didn't get any warnings on this error but I think it's OK now.

**Comment by PolymerGuy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03869/joss.03869/10.21105.joss.03869.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03869/joss.03869/10.21105.joss.03869.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@PolymerGuy I have started to look for reviewers for this submission. If you are able to suggest reviewers at this point that would be helpful. You can mention their github handle here but leave out the `@` symbol.

**Comment by PolymerGuy** [comment]
@Kevin-Mattheus-Moerman From browsing through the list of reviewers, the following persons appear to have similar fields of research:
chennachaos
thelfer
yangbai90
kegiljarhus
iammix
corentin-dev

**Comment by Kevin-Mattheus-Moerman** [comment]
@ahojukka5 @azzeddinetiba @jeevanjyoti4 @nicoguaro @ilyasst @diehlpk @thelfer @yangbai90 @kegiljarhus @corentin-dev would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org):
 "_RECOLO: A Python package for the reconstruction of surface pressure loads from kinematic fields using the virtual fields method_". 

The [smooth review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub on a dedicated review issues (e.g. here is [an example](https://github.com/openjournals/joss-reviews/issues/3860)) and focuses on:
- [A short paper](https://github.com/openjournals/joss-papers/blob/joss.03869/joss.03869/10.21105.joss.03869.pdf)
- [The software](https://github.com/PolymerGuy/recolo)

Let me know if you have any questions. Note that given the COVID pandemic we can be quite flexible regarding time needed to review. Thanks!

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman I can edit the paper.

**Comment by thelfer** [comment]
@Kevin-Mattheus-Moerman I don't have any specific knowledge of this topic. I would prefer let someone else handle this review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, @nicoguaro is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@ahojukka5 @azzeddinetiba @jeevanjyoti4 @ilyasst @diehlpk @yangbai90 @kegiljarhus @corentin-dev would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org):
 "_RECOLO: A Python package for the reconstruction of surface pressure loads from kinematic fields using the virtual fields method_". 


The [smooth review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub on a dedicated review issues (e.g. here is [an example](https://github.com/openjournals/joss-reviews/issues/3860)) and focuses on:
- [A short paper](https://github.com/openjournals/joss-papers/blob/joss.03869/joss.03869/10.21105.joss.03869.pdf)
- [The software](https://github.com/PolymerGuy/recolo)

Let me know if you have any questions. Note that given the COVID pandemic we can be quite flexible regarding time needed to review. Thanks!

**Comment by jeevanjyoti4** [comment]
I am really sorry. But I don't think I have the expertise to properly
examine this work.

I hope to be able to contribute to the review process in the future.

Best regards,
Jeevan

-----------------------------------------------------------------------------
Dr Jeevanjyoti Chakraborty
Assistant Professor
Department of Mechanical Engineering
Indian Institute of Technology (IIT) Kharagpur
Kharagpur - 721302
West Bengal, India
http://www.facweb.iitkgp.ac.in/~jeevanjyoti/
-----------------------------------------------------------------------------

**Comment by kegiljarhus** [comment]
Dear Kevin,

Sorry for the late reply on this one. Thank you for considering me as a
reviewer, but this falls outside my field of expertise so I hope someone
else more suitable can contribute.

Regards,
Knut Erik Giljarhus

**Comment by Kevin-Mattheus-Moerman** [comment]
@jomorlier @ahojukka5 @azzeddinetiba @ilyasst @diehlpk @yangbai90 @corentin-dev would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org):
 "_RECOLO: A Python package for the reconstruction of surface pressure loads from kinematic fields using the virtual fields method_". 


The [smooth review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub on a dedicated review issues (e.g. here is [an example](https://github.com/openjournals/joss-reviews/issues/3860)) and focuses on:
- [A short paper](https://github.com/openjournals/joss-papers/blob/joss.03869/joss.03869/10.21105.joss.03869.pdf)
- [The software](https://github.com/PolymerGuy/recolo)

Let me know if you have any questions. Note that given the COVID pandemic we can be quite flexible regarding time needed to review. Thanks!

**Comment by corentin-dev** [comment]
@Kevin-Mattheus-Moerman I am willing to review this paper.
Regards,
Corentin

**Comment by whedon** [comment]
OK, @corentin-dev is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@corentin-dev thanks for agreeing to help with this review! Is it correct that this is you: https://lmrs.univ-rouen.fr/fr/persopage/corentin-lothode, it would be good to confirm (and as a suggestion to perhaps add your full name and affiliation to your GitHub profile).

**Comment by corentin-dev** [comment]
@Kevin-Mattheus-Moerman done

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3980.
