### ISSUE TITLE
[PRE REVIEW]: populR: Residential population down-scaling in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3870]
**Submitting author:** @mbatsaris (<a href="http://orcid.org/0000-0002-1805-3528">Marios Batsaris</a>)
**Repository:** <a href="https://github.com/mbatsaris/populR" target ="_blank">https://github.com/mbatsaris/populR</a>
**Version:** v0.1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/24fe46aea74f1e2e7ad8d478472e4aea/status.svg)](https://joss.theoj.org/papers/24fe46aea74f1e2e7ad8d478472e4aea)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/24fe46aea74f1e2e7ad8d478472e4aea"><img src="https://joss.theoj.org/papers/24fe46aea74f1e2e7ad8d478472e4aea/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/24fe46aea74f1e2e7ad8d478472e4aea/status.svg)](https://joss.theoj.org/papers/24fe46aea74f1e2e7ad8d478472e4aea)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mbatsaris. **Currently, there isn't an JOSS editor assigned** to your paper.

@mbatsaris if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1171

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/gec3.12465 is OK
- 10.1016/j.compenvurbsys.2005.07.005 is OK
- 10.1111/gean.12012 is OK
- 10.1111/j.1467-9671.2009.01171.x is OK
- 10.1111/j.1749-8198.2009.00220.x is OK
- 10.32614/rj-2018-009 is OK
- 10.21105/joss.01221 is OK
- 10.1016/j.ijdrr.2015.07.015 is OK
- 10.1559/152304010792194985 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (771.8 files/s, 45364.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             59              0            159
TeX                              1              2              0            100
R                                6              0            130             79
-------------------------------------------------------------------------------
SUM:                             9             61            130            338
-------------------------------------------------------------------------------


Statistical information for the repository '9f699e3cbfee2b5d98f8e25e' was
gathered on 2021/10/29.
No commited files with the specified extensions were found.
```

**Comment by kthyng** [comment]
Hi @mbatsaris and thanks for your submission. Unfortunately, it appears that your submission is not in scope in terms of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html?highlight=maintainable#substantial-scholarly-effort). In particular, though lines of code (LOC) is not a perfect representation of effort, we do have a cutoff in which we desk-reject submission with LOC under 300. With your R LOC at 79, I am desk rejecting this following that rule.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
