### ISSUE TITLE
[PRE REVIEW]: TriP: A Python package for the kinematic modeling of serial-parallel hybrid robots

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3871]
**Submitting author:** @liquidcronos (<a href="http://orcid.org/0000-0002-7825-3476">Jan Baumgärtner</a>)
**Repository:** <a href="https://github.com/TriPed-Robot/TriP" target ="_blank">https://github.com/TriPed-Robot/TriP</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @SeungBack, @bmagyar
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/03c967bcda198bac6af1ef6342507c3f/status.svg)](https://joss.theoj.org/papers/03c967bcda198bac6af1ef6342507c3f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/03c967bcda198bac6af1ef6342507c3f"><img src="https://joss.theoj.org/papers/03c967bcda198bac6af1ef6342507c3f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/03c967bcda198bac6af1ef6342507c3f/status.svg)](https://joss.theoj.org/papers/03c967bcda198bac6af1ef6342507c3f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @liquidcronos. **Currently, there isn't an JOSS editor assigned** to your paper.

@liquidcronos if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (511.6 files/s, 65275.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          15            408            532           1128
XML                              1              0              2            792
reStructuredText                 4            219            174            305
Markdown                         5             43              0             94
YAML                             3             17             18             75
make                             1              4              6             10
SVG                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                            30            691            732           2405
-------------------------------------------------------------------------------


Statistical information for the repository '80f7b7f79408c560e6df6fc2' was
gathered on 2021/10/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jan Baumgärnter                 15           343            205            1.42
Jan Baumgärtner                 97         17351           2849           52.34
Torben Miller                   80          2635          15208           46.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jan Baumgärnter            1770          516.0          1.4                7.18
Jan Baumgärtner             161            0.9          0.0               54.66
Torben Miller               137            5.2          5.5                7.30
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3871 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.mechatronics.2020.102367 is OK
- 10.1007/s12532-018-0139-4 is OK
- 10.3390/app10072567 is OK
- 10.1007/s11044-005-4196-x is OK
- 10.1109/70.88066 is OK
- 10.1115/1.4005233 is OK
- 10.1007/1-4020-4133-0_2 is OK
- 10.1109/TMECH.2006.871087 is OK

MISSING DOIs

- 10.1016/j.apm.2015.04.020 may be a valid DOI for title: Unified solving inverse dynamics of 6-DOF serial–parallel manipulators
- 10.1007/s12206-016-1036-2 may be a valid DOI for title: Kinematics and dynamics analysis of a novel serial-parallel dynamic simulator
- 10.1109/humanoids.2014.7041473 may be a valid DOI for title: Overview of the torque-controlled humanoid robot TORO
- 10.1109/mra.2011.2181749 may be a valid DOI for title: Moveit![ros topics]

INVALID DOIs

- https://doi.org/10.1016/j.mechmachtheory.2008.03.002 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.rcim.2012.09.016 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03871/joss.03871/10.21105.joss.03871.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03871/joss.03871/10.21105.joss.03871.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @liquidcronos - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.


In addition, you could work on the possibly missing DOIs that whedon suggests (and incorrect DOIs), but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references from branch paper` to check again, and the command `@whedon generate pdf from branch paper` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by liquidcronos** [comment]
Hey @danielskatz thanks for considering TriP.
Most of these DOIs seem to be from bibtex entries that aren't used in the paper, I will will these Issues right away.

**Comment by liquidcronos** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.mechatronics.2020.102367 is OK
- 10.1007/s12532-018-0139-4 is OK
- 10.1109/TMECH.2006.871087 is OK
- 10.1016/j.mechmachtheory.2008.03.002 is OK
- 10.1016/j.rcim.2012.09.016 is OK
- 10.1109/MRA.2011.2181749 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by liquidcronos** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03871/joss.03871/10.21105.joss.03871.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03871/joss.03871/10.21105.joss.03871.pdf) :page_facing_up: :point_left:

**Comment by liquidcronos** [comment]
Everything seems to check out now

**Comment by kyleniemeyer** [comment]
Hi @liquidcronos, the editorial board has reviewed your submission and found that it meets our expectations for review, so this will continue. However, we do not have an editor available in this area right now, so I'm going to place this on our waitlist until someone becomes available (hopefully soon!)

**Comment by Kevin-Mattheus-Moerman** [comment]
@liquidcronos I've checked today (I am AEiC on call this week) and all editors in the robotics domain are still fully occupied with other submissions. I'll check again in a couple of days and we will proceed to invite/assign an editor once they become available.

**Comment by liquidcronos** [comment]
Thanks for the update @Kevin-Mattheus-Moerman .
I have to say I have been really impressed so far with how open this process is!

**Comment by danielskatz** [comment]
Even though I'm not in the robotics domain, I'll go ahead and take this to edit

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @liquidcronos - the next step is to find at least two reviewers.  If you have any suggestions for potential reviewers, please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by liquidcronos** [comment]
Hey @danielskatz thanks for the update, I have looked at the list and I found a number of suitable reviewers:
sea-bass, nnadeau, CameronDevine, SeungBack and carlosjoserg

**Comment by danielskatz** [comment]
Thanks @liquidcronos - note that I've changed the title of this submission to fix a spelling error (seriell should be serial) - Can you do this in the paper.md as well?

**Comment by danielskatz** [comment]
👋 @sea-bass & @nnadeau - Would one or both of you be willing to review this JOSS submission?

**Comment by liquidcronos** [comment]
> Thanks @liquidcronos - note that I've changed the title of this submission to fix a spelling error (seriell should be serial) - Can you do this in the paper.md as well?

Yeah, that the german spelling... Thanks for letting me know, it should be fixed now.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03871/joss.03871/10.21105.joss.03871.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03871/joss.03871/10.21105.joss.03871.pdf) :page_facing_up: :point_left:

**Comment by nnadeau** [comment]
unfortunately i'm not available at the moment

**Comment by danielskatz** [comment]
👋 @CameronDevine & @SeungBack - Would one or both of you be willing to review this JOSS submission?

**Comment by SeungBack** [comment]
Thank you for the suggestions, and I will participate in reviewing this paper.

**Comment by CameronDevine** [comment]
@danielskatz Unfortunately I don't have time at the moment.

**Comment by danielskatz** [comment]
Thanks @SeungBack - I'll add you in the system, but we won't start the review until we find one more reviewer.

**Comment by danielskatz** [comment]
@whedon assign @SeungBack as reviewer

**Comment by whedon** [comment]
OK, @SeungBack is now a reviewer

**Comment by danielskatz** [comment]
👋 @sea-bass - Would you be willing to review this JOSS submission? (just checking again)

**Comment by danielskatz** [comment]
@ carlosjoserg - Would you be willing to review this JOSS submission?

**Comment by sea-bass** [comment]
> wave @sea-bass & @nnadeau - Would one or both of you be willing to review this JOSS submission?

Hi all -- unfortunately I am unable to review at the moment. Thank you for asking!

**Comment by danielskatz** [comment]
👋 @carlosjoserg - Would you be willing to review this JOSS submission?

**Comment by CameronDevine** [comment]
In case they are interested, in the past I have reviewed similar submissions with @adi3 and @trallard and have had a similar submission of my own reviewed by @bmagyar and @amjaeger17.

**Comment by danielskatz** [comment]
Thanks @CameronDevine!!

**Comment by danielskatz** [comment]
👋 @adi3 and @trallard - Would one of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋 @bmagyar and @amjaeger17 - Would one of you be willing to review this JOSS submission?

**Comment by bmagyar** [comment]
Happy to review this one!

**Comment by danielskatz** [comment]
Thanks @bmagyar - I'll add you and we'll get started!

**Comment by danielskatz** [comment]
@whedon add @bmagyar as reviewer

**Comment by whedon** [comment]
OK, @bmagyar is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3967.
