### ISSUE TITLE
[PRE REVIEW]: PPQplan: An R package for process performance qualification (PPQ) Plans in Chemistry, Manufacturing and Controls (CMC) Statistical Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3872]
**Submitting author:** @allenzhuaz (<a href="http://orcid.org/0000-0003-3830-8660">Yalin Zhu</a>)
**Repository:** <a href="https://github.com/allenzhuaz/PPQplan" target ="_blank">https://github.com/allenzhuaz/PPQplan</a>
**Version:** v1.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/18e90390f168a2a3efcbb4888e78a1a9/status.svg)](https://joss.theoj.org/papers/18e90390f168a2a3efcbb4888e78a1a9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/18e90390f168a2a3efcbb4888e78a1a9"><img src="https://joss.theoj.org/papers/18e90390f168a2a3efcbb4888e78a1a9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/18e90390f168a2a3efcbb4888e78a1a9/status.svg)](https://joss.theoj.org/papers/18e90390f168a2a3efcbb4888e78a1a9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @allenzhuaz. **Currently, there isn't an JOSS editor assigned** to your paper.

@allenzhuaz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 847

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (412.4 files/s, 129398.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      13           2431           2619           9851
HTML                            23           1126            281           3505
R                               15             29            517            458
CSS                              5            103             57            451
Markdown                         4             49              0            146
YAML                             5             14              2            130
Rmd                              3            112            212             76
XML                              1              0              0             54
TeX                              1              5              0             39
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            71           3869           3689          14721
-------------------------------------------------------------------------------


Statistical information for the repository '0c9dce2e073034bf4c1628f0' was
gathered on 2021/10/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zhu                              2         13807              0           32.77
allenzhuaz                       2         14712          13618           67.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Zhu                         189            1.4          0.0                8.47
allenzhuaz                14712          100.0         -0.0               17.71
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1201/9780429447273 may be a valid DOI for title: Interactive Web-Based Data Visualization with R, plotly, and shiny

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03872/joss.03872/10.21105.joss.03872.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03872/joss.03872/10.21105.joss.03872.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @allenzhuaz - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

It would be useful if you could add a LICENSE file with the GPL-3 license that is mentioned in the DESCRIPTION file

In addition, you could work on the possibly missing DOI that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by allenzhuaz** [comment]
> @whedon check references



> 👋 @allenzhuaz - thanks for your submission. Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. You should hear back in a week or so.
> 
> It would be useful if you could add a LICENSE file with the GPL-3 license that is mentioned in the DESCRIPTION file
> 
> In addition, you could work on the possibly missing DOI that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

Thank you, I have added LICENSE file, and update for MIT license. Also added DOI's for the reference

**Comment by allenzhuaz** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "doi" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:title=>["Statistical applications for chemistry, manufacturing and controls (CMC) in the pharmaceutical industry"], :author=>["Burdick, Richard K and LeBlond, David J and Pfahler, Lori B and Quiroz, Jorge and Sidor, Leslie and Vukovinsky, Kimberly and Zhang, Lanju"], :year=>["2017"], :publisher=>["Springer"]}]

**Comment by allenzhuaz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-319-50186-4 is OK
- 10.1007/978-0-387-98141-3 is OK
- 10.1201/9780429447273 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by allenzhuaz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03872/joss.03872/10.21105.joss.03872.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03872/joss.03872/10.21105.joss.03872.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @allenzhuaz - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
