### ISSUE TITLE
[PRE REVIEW]: ePat: extended PROVEAN annotation tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3873]
**Submitting author:** @itotaku1225 (<a href="http://orcid.org/0000-0002-6376-584X">Takumi Ito</a>)
**Repository:** <a href="https://github.com/itotaku1225/ePat" target ="_blank">https://github.com/itotaku1225/ePat</a>
**Version:** v3.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a065f4c8e718d5db95466d322c7bf912/status.svg)](https://joss.theoj.org/papers/a065f4c8e718d5db95466d322c7bf912)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a065f4c8e718d5db95466d322c7bf912"><img src="https://joss.theoj.org/papers/a065f4c8e718d5db95466d322c7bf912/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a065f4c8e718d5db95466d322c7bf912/status.svg)](https://joss.theoj.org/papers/a065f4c8e718d5db95466d322c7bf912)
```

**Author instructions**

Thanks for submitting your paper to JOSS @itotaku1225. **Currently, there isn't an JOSS editor assigned** to your paper.

@itotaku1225 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 998

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/nmeth0410-248 is OK
- 10.1371/journal.pone.0046688 is OK
- 10.1093/bioinformatics/btv195 is OK
- 10.1007/s10633-021-09826-y is OK
- 10.1038/s10038-018-0465-4 is OK
- 10.1038/nprot.2009.86 is OK
- 10.1038/srep33742 is OK
- 10.1002/mgg3.1308 is OK
- 10.1167/iovs.16-19450 is OK
- 10.1016/j.jmoldx.2020.08.007 is OK
- 10.1038/s41598-020-62119-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (301.3 files/s, 19430.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6             20             50            310
Markdown                         2             82              0            172
TeX                              1             13              0            172
Bourne Shell                     5             10              2             72
-------------------------------------------------------------------------------
SUM:                            14            125             52            726
-------------------------------------------------------------------------------


Statistical information for the repository 'a712c330c75598ae5966846c' was
gathered on 2021/11/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ito-Takumi1225                  11            27             23           11.74
itotaku1225                      1           376              0           88.26

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ito-Takumi1225               17           63.0          0.5               17.65
itotaku1225                 363           96.5          0.0               12.95
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03873/joss.03873/10.21105.joss.03873.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03873/joss.03873/10.21105.joss.03873.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @itotaku1225 - Unfortunately, this submission is too little small - it does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
