### ISSUE TITLE
[PRE REVIEW]: Annoroad Browser: A multi-omic visualization tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3874]
**Submitting author:** @Spartanzhao (<a href="http://orcid.org/0000-0001-5293-820X">Yue Zhao</a>)
**Repository:** <a href="https://github.com/Spartanzhao/Annoroad-Browser/" target ="_blank">https://github.com/Spartanzhao/Annoroad-Browser/</a>
**Version:** v.1.0.0
**Editor:** @jmschrei
**Reviewers:** @pkerpedjiev, @elliothershberg
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/aaabf5a6dec727262436a5f531b18b6b/status.svg)](https://joss.theoj.org/papers/aaabf5a6dec727262436a5f531b18b6b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aaabf5a6dec727262436a5f531b18b6b"><img src="https://joss.theoj.org/papers/aaabf5a6dec727262436a5f531b18b6b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aaabf5a6dec727262436a5f531b18b6b/status.svg)](https://joss.theoj.org/papers/aaabf5a6dec727262436a5f531b18b6b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Spartanzhao. **Currently, there isn't an JOSS editor assigned** to your paper.

@Spartanzhao if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1279

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/s13059-015-0741-y is OK
- 10.1038/nature13986 is OK
- 10.1016/j.cels.2016.07.002 is OK
- 10.1093/nar/gkz348 is OK
- 10.1093/bioinformatics/btaa692 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (133.5 files/s, 22317.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             85             75            952
Markdown                         3             66              0            113
TeX                              1              5              0             35
Bourne Shell                     2              0              0              6
-------------------------------------------------------------------------------
SUM:                             8            156             75           1106
-------------------------------------------------------------------------------


Statistical information for the repository '617aa1157642b138150b278f' was
gathered on 2021/11/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Spartanzhao                      5          2225           1113          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Spartanzhao                1112           50.0          0.0                6.83
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3874 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 1, column 14):
unexpected "c"
expecting space or ","
Looks like we failed to compile the PDF

```

**Comment by danielskatz** [comment]
👋 @Spartanzhao - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.


Also, please note that your paper does not compile, with an error in the bib file. Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). My guess is that the "/" or " " or both in the bib entry name is causing the problem - you might change this to "AB-compartment".  You probably also will need to change "WashU Browser" to "WashU-Browser" or similar, then also change the .md file where these are cited.

Please feel free to make changes to your .bib or .md file, then use the command `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Spartanzhao** [comment]
Yes, I will fix this problems as soon as possible. My work is trying to build a tool which is much better than WashU browser and pyGenomeTrack, and in some situations, replace IGV. This tool is very easy to expand, other people can easily add any new functions if they want, or customize their heat map color series. This is a very useful multi-omic visualization tool. We have many papers are going to publish based on this tool. Because all the Hi-C, epigenome analysis all require this tool's help in our research center.

**Comment by kyleniemeyer** [comment]
Hi @Spartanzhao, we are going to proceed with review of your submission.

@jmschrei can you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @jmschrei as editor

**Comment by whedon** [comment]
@jmschrei has been invited to edit this submission.

**Comment by jmschrei** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jmschrei

**Comment by jmschrei** [comment]
@Spartanzhao have you fixed the issue with your paper yet?

**Comment by Spartanzhao** [comment]
> @Spartanzhao have you fixed the issue with your paper yet?

I think that I had fixed the issue on reference. But I am not sure whether there are some other issues.

**Comment by Spartanzhao** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3874 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 1, column 14):
unexpected "c"
expecting space or ","
Looks like we failed to compile the PDF

```

**Comment by Spartanzhao** [comment]
> @Spartanzhao have you fixed the issue with your paper yet?
I just figured out how test my paper, I am fixing it as soon as possible.

**Comment by Spartanzhao** [comment]
> @Spartanzhao have you fixed the issue with your paper yet?

@jmschrei , I have fixed the problem, my github have passed the test on https://whedon.theoj.org/

**Comment by jmschrei** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03874/joss.03874/10.21105.joss.03874.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03874/joss.03874/10.21105.joss.03874.pdf) :page_facing_up: :point_left:

**Comment by jmschrei** [comment]
@whedon add @pkerpedjiev as reviewer

**Comment by whedon** [comment]
OK, @pkerpedjiev is now a reviewer

**Comment by jmschrei** [comment]
@whedon add @elliothershberg as reviewer

**Comment by whedon** [comment]
OK, @elliothershberg is now a reviewer

**Comment by jmschrei** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3916.
