### ISSUE TITLE
[PRE REVIEW]: Basix: a runtime finite element basis evaluation library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3878]
**Submitting author:** @mscroggs (<a href="http://orcid.org/0000-0002-4658-2443">Matthew Scroggs</a>)
**Repository:** <a href="https://github.com/FEniCS/basix" target ="_blank">https://github.com/FEniCS/basix</a>
**Version:** v0.3.0
**Editor:** @jedbrown
**Reviewers:** @tisaac, @wence-
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a0c3fde86db28bd8c97d0dfe92d056f1/status.svg)](https://joss.theoj.org/papers/a0c3fde86db28bd8c97d0dfe92d056f1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a0c3fde86db28bd8c97d0dfe92d056f1"><img src="https://joss.theoj.org/papers/a0c3fde86db28bd8c97d0dfe92d056f1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a0c3fde86db28bd8c97d0dfe92d056f1/status.svg)](https://joss.theoj.org/papers/a0c3fde86db28bd8c97d0dfe92d056f1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mscroggs. **Currently, there isn't an JOSS editor assigned** to your paper.

@mscroggs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/1039813.1039820 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1145/2566630 is OK
- 10.1007/BF01396415 is OK
- 10.1007/BF01389668 is OK
- 10.1007/BF01389710 is OK
- 10.1051/m2an/197307R300331 is OK
- 10.1007/BF02733251 is OK
- 10.1007/s00211-011-0394-z is OK
- 10.1007/s10208-011-9087-3 is OK
- 10.1090/S0025-5718-2013-02783-4 is OK
- 10.1007/978-3-642-23099-8_11 is OK
- 10.1145/1731022.1731030 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (769.4 files/s, 147713.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             24           1092            900          10002
Python                          41            819            898           3129
C/C++ Header                    25            656           1998           2538
SVG                              7            112              0            395
YAML                             5             48              8            395
Markdown                         8            124              0            371
CMake                            6             58             53            251
TeX                              1             19              0            183
HTML                             4              1              7             38
reStructuredText                 2             10             11             20
TOML                             1              6              0             12
CSS                              1              5              0             11
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           126           2954           3881          17355
-------------------------------------------------------------------------------


Statistical information for the repository 'aaf67bba3479b72fb6e58dde' was
gathered on 2021/11/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adeeb Arif Kor                   1           136             59            0.23
Chris Richardson               227         14302           9403           28.45
Garth N. Wells                  86         11697          11280           27.57
Igor Baratta                     8           310            814            1.35
Jack S. Hale                     3            48             26            0.09
Jørgen Schartum Dokk             1            13             18            0.04
Massimiliano Leoni               1            11              2            0.02
Matthew Scroggs                170         25026           9299           41.19
Michal Habera                    1             0              4            0.00
igorbaratta                      1             1              1            0.00
nikhilTkur                       1           878              0            1.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adeeb Arif Kor               79           58.1          8.0                7.59
Chris Richardson           1604           11.2         11.9               29.49
Garth N. Wells             4171           35.7          7.0               13.45
Igor Baratta                230           74.2          5.2               10.87
Jack S. Hale                 48          100.0          4.7                2.08
Jørgen Schartum Dokk         12           92.3          6.0               16.67
Matthew Scroggs           15025           60.0          5.3               16.34
nikhilTkur                  863           98.3          2.7                1.39
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03878/joss.03878/10.21105.joss.03878.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03878/joss.03878/10.21105.joss.03878.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@jedbrown - would you be willing to edit this?  I know you are at your limit, but it seems a good fit...

**Comment by danielskatz** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@mscroggs :wave: Thanks for your submission to JOSS. This looks like a really useful package. Some notes:

1. It looks like the C++ code makes heavy use of xtensor, which thus deserves citation.
2. The paper doesn't mention quadrature, but the choice of quadrature is significant (especially for tetrahedra) so it would be useful to state/cite supported methods.
3. The documentation site lacks C++ examples. I think it would be useful to have at least one example that has equivalent C++ and Python, considering that low-dependency C++ is one of the selling points of Basix relative to FIAT.
4. The docs have a nice breakdown of element topology and associated FE families -- I think it would be nice to include that in the paper, versus what is currently summarized in one sentence of the paper.
5. Is there any attempt or interest in preserving tensor product structure for bases that have it?

Once I hear from you on these points, I'll move forward with finding reviewers.

**Comment by mscroggs** [comment]
@jedbrown Thanks for these comments, I'll push some updates to the documentation/paper and let you know when these are done

**Comment by mscroggs** [comment]
@jedbrown We've pushed some changes to the paper:

1. We've added a citation to xtensor.
2. We've added a sentence about quadrature to the paper, and referenced the Xiao-Gimbutas quadrature rule as this is what is currently used for triangles.
3. We've added two translations of demos to C++ to the website at https://docs.fenicsproject.org/basix/main/python/demo/demo_create_and_tabulate.py.html and https://docs.fenicsproject.org/basix/main/python/demo/demo_dof_transformations.py.html
4. We've added the element and topology info to the paper.
5. We have longer term plans to work on providing details of tensor product representations, but didn't write this in the paper as this is still in the very early stages of development.

Thanks again for your comments.

**Comment by mscroggs** [comment]
possible suitable reviewers (from list): peanutfun, schruste, felipefr, FaroukM, krober10nd

Suitable reviewers (not on list): wence, ReubenHill

**Comment by mscroggs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03878/joss.03878/10.21105.joss.03878.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03878/joss.03878/10.21105.joss.03878.pdf) :page_facing_up: :point_left:

**Comment by mscroggs** [comment]
@jedbrown Hello! Is there anything else we need to do on our end to move this pre-review forward?

**Comment by jedbrown** [comment]
Thanks for your patience. We have two reviewers and can start the review.

**Comment by jedbrown** [comment]
@whedon add @tisaac as reviewer

**Comment by whedon** [comment]
OK, @tisaac is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @wence- as reviewer

**Comment by whedon** [comment]
OK, @wence- is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3982.
