### ISSUE TITLE
[PRE REVIEW]: mmrefpoints: Projecting long-term marine mammal abundance with bycatch

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3879]
**Submitting author:** @mcsiple (<a href="http://orcid.org/0000-0002-4260-9856">Margaret Siple</a>)
**Repository:** <a href="https://github.com/mcsiple/mmrefpoints" target ="_blank">https://github.com/mcsiple/mmrefpoints</a>
**Version:** v0.1.1
**Editor:** @fboehm
**Reviewers:** @ha0ye and @eirenjacobson
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466/status.svg)](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466"><img src="https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466/status.svg)](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mcsiple. **Currently, there isn't an JOSS editor assigned** to your paper.

@mcsiple if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1309

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (641.4 files/s, 111965.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             7            208             92           3429
R                               46            487           1472           3388
JSON                             2              7              0            682
Rmd                              8            445            993            606
Markdown                         5            108              0            398
TeX                              2             27              0            366
YAML                             3              2              4             29
-------------------------------------------------------------------------------
SUM:                            73           1284           2561           8898
-------------------------------------------------------------------------------


Statistical information for the repository '4dbac8429a4c7e4f6fe1ebd8' was
gathered on 2021/11/02.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.1748-7692.1998.tb00688.x is OK
- 10.1111/mms.12427 is OK
- 10.1644/11-MAMM-A-291.1 is OK
- 10.1093/icesjms/fsy049 is OK
- 10.1139/f84-058 is OK
- 10.2989/025776195784156511 is OK
- 10.1890/14-1990 is OK
- 10.1002/ece3.4772 is OK
- 10.7557/3.2747 is OK
- 10.3389/fmars.2021.735770 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03879/joss.03879/10.21105.joss.03879.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03879/joss.03879/10.21105.joss.03879.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @Bisaloo - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @Bisaloo as editor

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by fboehm** [comment]
If @Bisaloo isn't available to edit this, I'd be happy to edit it.

**Comment by danielskatz** [comment]
👋 @fboehm - given that @Bisaloo didn't ask for it, I suggested this, and you are interested, I'll just go ahead and assign it to you

**Comment by danielskatz** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by mcsiple** [comment]
Suitable reviewers for this paper/package might be:
From the list (without @ tags, organized from bottom to top of [list of people](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) provided above):
crvernon
neerajdhanraj
tbrown122387
ha0ye

An additional reviewer who would be excellent and who is not listed is: 
eirenjacobson

Thank you!

**Comment by fboehm** [comment]
@crvernon, @eirenjacobson, @neerajdhanraj, @tbrown122387, @ha0ye   - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by crvernon** [comment]
@fboehm Apologies, I am currently the editor for several other JOSS articles in-review and will not have time to be a reviewer on this one.  Looks like a good one though!   Kind regards!

**Comment by eirenjacobson** [comment]
Hi Frederick,

If you need a second reviewer, I would be happy to review

Cheers,

Eiren
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Eiren Jacobson, Ph.D.
Email: ***@***.***
Website: eirenjacobson.github.io
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by eirenjacobson** [comment]
@fboehm, if you need a second reviewer, I would be happy to review!

**Comment by fboehm** [comment]
@whedon assign @ha0ye and @eirenjacobson as reviewers

**Comment by whedon** [comment]
OK, @ha0ye and @eirenjacobson is now a reviewer

**Comment by fboehm** [comment]
@whedon begin review

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by fboehm** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3888.

**Comment by tbrown122387** [comment]
@fboehm it looks like you're all good on reviewers?

**Comment by fboehm** [comment]
> @fboehm it looks like you're all good on reviewers?

Thanks, @tbrown122387 ! Yes, we ended up finding enough reviewers. Thanks again - I hope that we can work together on a future submission.

**Comment by fboehm** [comment]
@tbrown122387 - It turns out that we need another reviewer for this submission. Would you be willing to review it for JOSS over the next 4 to 6 weeks? Thanks again!

**Comment by tbrown122387** [comment]
@fboehm yeah sure I can help out

**Comment by fboehm** [comment]
> @fboehm yeah sure I can help out

Thank you, @tbrown122387 ! I've now added you as a reviewer in the "review" issue, https://github.com/openjournals/joss-reviews/issues/3888. You should find a checklist to guide your review there.
