### ISSUE TITLE
[PRE REVIEW]: Sinaps: A Python library to simulate voltage dynamic and ionic electrodiffusion in neurons

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3880]
**Submitting author:** @cgurrr (<a href="http://orcid.org/0000-0002-1128-1069">Claire Guerrier</a>)
**Repository:** <a href="https://github.com/ngltr/sinaps" target ="_blank">https://github.com/ngltr/sinaps</a>
**Version:** 0.2
**Editor:** @meg-simula
**Reviewers:** @martejulie, @blbentley
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d47fbf887ce21cf686a56bac1b36817e/status.svg)](https://joss.theoj.org/papers/d47fbf887ce21cf686a56bac1b36817e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d47fbf887ce21cf686a56bac1b36817e"><img src="https://joss.theoj.org/papers/d47fbf887ce21cf686a56bac1b36817e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d47fbf887ce21cf686a56bac1b36817e/status.svg)](https://joss.theoj.org/papers/d47fbf887ce21cf686a56bac1b36817e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @cgurrr. **Currently, there isn't an JOSS editor assigned** to your paper.

@cgurrr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 517

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.3389/fncir.2020.00033 may be a valid DOI for title: Comprehensive Imaging of Sensory-Evoked Activity of Entire Neurons Within the Awake Developing Brain Using Ultrafast AOD-Based Random-Access Two-Photon Microscopy
- 10.1371/journal.pcbi.1006485 may be a valid DOI for title: Active dendrites regulate the spatiotemporal spread of signaling microdomains.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (476.8 files/s, 124313.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            465            586           1321
Jupyter Notebook                10              0           5690            477
Markdown                         2             19              0             54
reStructuredText                 4             33             39             44
TeX                              1              9              0             37
YAML                             1              5              4             27
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            34            543           6327           1995
-------------------------------------------------------------------------------


Statistical information for the repository '101082f254699460241a82a1' was
gathered on 2021/11/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Claire                          10           423            263            7.27
Claire Guerrier                 66          5259           3149           89.16
Nicolas                          1             1              1            0.02
Nicolas Galtier                  4           176            103            2.96
Niko                             4            45             10            0.58

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Claire                       60           14.2         19.0                5.00
Claire Guerrier            2252           42.8          4.3                9.90
Nicolas                       1          100.0          0.3                0.00
Nicolas Galtier              53           30.1         21.5               50.94
Niko                          6           13.3         25.1                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03880/joss.03880/10.21105.joss.03880.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03880/joss.03880/10.21105.joss.03880.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
Sure, right up my alley.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03880/joss.03880/10.21105.joss.03880.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03880/joss.03880/10.21105.joss.03880.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.3389/fncir.2020.00033 may be a valid DOI for title: Comprehensive Imaging of Sensory-Evoked Activity of Entire Neurons Within the Awake Developing Brain Using Ultrafast AOD-Based Random-Access Two-Photon Microscopy
- 10.1371/journal.pcbi.1006485 may be a valid DOI for title: Active dendrites regulate the spatiotemporal spread of signaling microdomains.

INVALID DOIs

- None
```

**Comment by meg-simula** [comment]
@cgurrr Thanks for this submission and my apologies for the delay in handling. 

If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by meg-simula** [comment]
:wave: @martejulie would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by martejulie** [comment]
@meg-simula Absolutely!

**Comment by meg-simula** [comment]
@whedon assign @martejulie as reviewer

**Comment by whedon** [comment]
OK, @martejulie is now a reviewer

**Comment by meg-simula** [comment]
Great @martejulie! I've assigned you as a reviewer now. At least one more reviewer is needed, so feel free to just stay put and await further information.

**Comment by cgurrr** [comment]
@meg-simula Thanks for accepting to be an editor for our submission. I apologize for the late reply.

Follow three names coming from the reviewer suggestion list, that could be a good match:
ryEllison, for his expertise in both computational neuroscience and biophysics, 
It seems that blbentley and woolfeh could also be good match.

**Comment by meg-simula** [comment]
:wave: @ryEllison @woolfeh @blbentley would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by blbentley** [comment]
Hello @meg-simula,  I would be happy to review this.

**Comment by woolfeh** [comment]
Hi @meg-simula, I would also be happy to review this submission but wouldn't be able to start for a couple of weeks. Is that OK?

**Comment by ryEllison** [comment]
Hey, @meg-simula, I would be happy to review this!

**Comment by meg-simula** [comment]
Wow @blbentley @woolfeh @ryEllison - thank you all for the positive and quick responses! We just need one more reviewer on this, and since @blbentley was first (in addition to @martejulie), I'll assign you now and get this review started.

**Comment by meg-simula** [comment]
@whedon add reviewer @blbentley

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by meg-simula** [comment]
@whedon add @blbentley as reviewer

**Comment by whedon** [comment]
OK, @blbentley is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4012.
