### ISSUE TITLE
[PRE REVIEW]: VeridicalFlow: a python package for building trustworthy data-science pipelines with PCS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3881]
**Submitting author:** @csinva (<a href="http://orcid.org/0000-0003-0318-2340">Chandan Singh</a>)
**Repository:** <a href="https://github.com/Yu-Group/veridical-flow" target ="_blank">https://github.com/Yu-Group/veridical-flow</a>
**Version:** v0.0.2
**Editor:** @jbytecode
**Reviewers:** @kmichael08, @richrobe
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0b03fae2cd00b2f21ce1a8ce4ea08118/status.svg)](https://joss.theoj.org/papers/0b03fae2cd00b2f21ce1a8ce4ea08118)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0b03fae2cd00b2f21ce1a8ce4ea08118"><img src="https://joss.theoj.org/papers/0b03fae2cd00b2f21ce1a8ce4ea08118/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0b03fae2cd00b2f21ce1a8ce4ea08118/status.svg)](https://joss.theoj.org/papers/0b03fae2cd00b2f21ce1a8ce4ea08118)
```

**Author instructions**

Thanks for submitting your paper to JOSS @csinva. **Currently, there isn't an JOSS editor assigned** to your paper.

@csinva if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (386.8 files/s, 131191.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              1              0            433           4699
HTML                             7            188              0           2613
Python                          12            184            349           1541
Jupyter Notebook                11              0           2531            977
Markdown                         5             50              0            154
TeX                              1             13              0            119
YAML                             2              5              2             27
Bourne Shell                     2              1              3             16
-------------------------------------------------------------------------------
SUM:                            41            441           3318          10146
-------------------------------------------------------------------------------


Statistical information for the repository 'ce547ac15e9ed28a5e481ff6' was
gathered on 2021/11/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Abhineet                         3           307             48            4.38
Chandan Singh                   35          1587            894           30.64
James Duncan                    23          1967           1025           36.96
Rushk014                        11          1194            958           26.58
aagarwal1996                     1            94             22            1.43

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chandan Singh               510           32.1          5.9                7.06
James Duncan               1038           52.8          2.2                8.38
Rushk014                    518           43.4          1.1                1.74
aagarwal1996                  8            8.5          8.2                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s42256-019-0048-x is OK
- 10.1073/pnas.1900654116 is OK

MISSING DOIs

- 10.21105/joss.03192 may be a valid DOI for title: imodels: a python package for fitting interpretable models
- 10.1109/mcse.2011.37 may be a valid DOI for title: The NumPy array: a structure for efficient numerical computation
- 10.1145/3336191.3372191 may be a valid DOI for title: Veridical data science

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03881/joss.03881/10.21105.joss.03881.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03881/joss.03881/10.21105.joss.03881.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @csinva - while we find an editor, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @jbytecode - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @jbytecode as editor

**Comment by whedon** [comment]
@jbytecode has been invited to edit this submission.

**Comment by jbytecode** [comment]
@danielskatz of course, thank you

**Comment by jbytecode** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s42256-019-0048-x is OK
- 10.1073/pnas.1900654116 is OK

MISSING DOIs

- 10.21105/joss.03192 may be a valid DOI for title: imodels: a python package for fitting interpretable models
- 10.1109/mcse.2011.37 may be a valid DOI for title: The NumPy array: a structure for efficient numerical computation
- 10.1145/3336191.3372191 may be a valid DOI for title: Veridical data science

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03881/joss.03881/10.21105.joss.03881.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03881/joss.03881/10.21105.joss.03881.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
Dear  @csinva

Thank you for submitting your paper to JOSS.

[ ] Please have a look at the [Reviewer List](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit) and list some suitable potential reviewers here. Please start from bottom of the list. Do not use @ character when you list them - just because we don't want to bother them. If you don't have any suggestions I will - of course - find suitable reviewers for you.

[ ] While I am sending invitations, please correct the missing DOIs that Whedon suggests above. 

[ ] You can compile and test your paper using the Whedon utility in page https://whedon.theoj.org/

Thank you in advance.

**Comment by csinva** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.03192 is OK
- 10.1109/mcse.2011.37 is OK
- 10.5281/zenodo.3509134 is OK
- 10.1145/3399579.3399867 is OK
- 10.1145/3186266 is OK
- 10.1111/0272-4332.00040 is OK
- 10.1038/137252a0 is OK
- 10.1145/3336191.3372191 is OK
- 10.1038/s42256-019-0048-x is OK
- 10.1073/pnas.1900654116 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/1953048.2078195 is INVALID
```

**Comment by csinva** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.03192 is OK
- 10.1109/mcse.2011.37 is OK
- 10.5281/zenodo.3509134 is OK
- 10.1145/3399579.3399867 is OK
- 10.1145/3186266 is OK
- 10.1111/0272-4332.00040 is OK
- 10.1038/137252a0 is OK
- 10.1145/3336191.3372191 is OK
- 10.1038/s42256-019-0048-x is OK
- 10.1073/pnas.1900654116 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csinva** [comment]
Thanks for serving as editor!

1. Here are some potential reviewers from the list: richrobe, kmichael08, dionhaefner, vimalthilak, 
2. I believe I have corrected the DOIs
3. The paper seems to compile properly

Also tagging my co-authors: @jpdunc23, @rushk014, @aagarwal1996

**Comment by jbytecode** [comment]
👋👋👋 Dear @richrobe  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_VeridicalFlow: a python package for building trustworthy data-science pipelines with PCS_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3881).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
👋👋👋 Dear @kmichael08  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_VeridicalFlow: a python package for building trustworthy data-science pipelines with PCS_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3881).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03881/joss.03881/10.21105.joss.03881.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03881/joss.03881/10.21105.joss.03881.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
@csinva since this is a scientific paper, not a documentation on GitHub, could be please remove the logo in Summary section of the paper?

**Comment by kmichael08** [comment]
Hey @jbytecode. Happy to review!

**Comment by jbytecode** [comment]
@whedon add @kmichael08 as reviewer

@kmichael08 thank you for accepting our invitation. After assigning one more reviewer, I will give the instructions.

**Comment by whedon** [comment]
OK, @kmichael08 is now a reviewer

**Comment by jbytecode** [comment]
👋👋👋 Dear @vimalthilak  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_VeridicalFlow: a python package for building trustworthy data-science pipelines with PCS_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3881).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by richrobe** [comment]
> 👋👋👋 Dear @richrobe 👋👋👋
> 
> Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?
> 
> JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_VeridicalFlow: a python package for building trustworthy data-science pipelines with PCS_". You can find more information at the top of this Github issue (#3881).
> 
> The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

Hi @jbytecode!
Sorry for the late reply, but I'd be happy to review as well!

**Comment by jbytecode** [comment]
@whedon add @richrobe as reviewer

**Comment by whedon** [comment]
OK, @richrobe is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3895.
