### ISSUE TITLE
[PRE REVIEW]: NeuralFieldEq.jl: A flexible solver to compute Neural Field Equations in several scenarios

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3886]
**Submitting author:** @tiagoseq (<a href="http://orcid.org/0000-0001-8579-3676">Tiago Sequeira</a>)
**Repository:** <a href="https://github.com/tiagoseq/NeuralFieldEq.jl" target ="_blank">https://github.com/tiagoseq/NeuralFieldEq.jl</a>
**Version:** v0.1.2
**Editor:** @jarvist
**Reviewers:** @rougier, @gdetor
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/85354f0f2b6244439e90d51fe28a9ef5/status.svg)](https://joss.theoj.org/papers/85354f0f2b6244439e90d51fe28a9ef5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/85354f0f2b6244439e90d51fe28a9ef5"><img src="https://joss.theoj.org/papers/85354f0f2b6244439e90d51fe28a9ef5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/85354f0f2b6244439e90d51fe28a9ef5/status.svg)](https://joss.theoj.org/papers/85354f0f2b6244439e90d51fe28a9ef5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tiagoseq. **Currently, there isn't an JOSS editor assigned** to your paper.

@tiagoseq if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1046

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (497.8 files/s, 231814.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              2            701             49          14825
Julia                           14            190            158            845
Markdown                         7            141              0            538
JavaScript                       5             44             78            511
HTML                             5             34              0            233
TeX                              1             13              0            120
YAML                             3              0              1            114
TOML                             2              5              0             20
JSON                             1              0              0              7
-------------------------------------------------------------------------------
SUM:                            40           1128            286          17213
-------------------------------------------------------------------------------


Statistical information for the repository 'f7f106851943d798c2b1f437' was
gathered on 2021/11/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
tiagoseq                         1           633              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
tiagoseq                    633          100.0          0.0               12.32
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/JPROC.2004.840301 is OK
- 10.1002/cne.21974 is OK
- 10.1016/S0006-3495(72)86068-5 is OK
- 10.1103/PhysRevE.82.055701 is OK
- 10.1007/978-3-642-54593-1_6 is OK
- 10.3389/fninf.2015.00025 is OK
- 10.1186/2190-8567-4-1 is OK
- 10.1137/141000671 is OK
- 10.1109/ICSTCC.2019.8885972 is OK

MISSING DOIs

- 10.1007/bf00337259 may be a valid DOI for title: Dynamics of pattern formation in lateral.inhibition type neural fields

INVALID DOIs

- https://doi.org/10.1113/jphysiol.1952.sp004764 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03886/joss.03886/10.21105.joss.03886.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03886/joss.03886/10.21105.joss.03886.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@tiagoseq - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOI that whedon suggests and the incorrect DOI, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by tiagoseq** [comment]
Hello,
Some time ago, Nicolas Rougier suggested that I should submit the solver to
JOSS and indicate him as a reviewer. Because the method implemented is
based on the novel technique presented in this paper
<https://hal.inria.fr/hal-00872132> authored by Axel Hutt and Nicolas
Rougier.

This solver handles with several types of Neural Field equations, being
user friendly, easy to use and efficient as possible. As far as I can tell,
there isn't other piece of software that brings together this features.

I will check the issues with DOI and update the .bib file.

Thank you,
Tiago

Em qua., 3 de nov. de 2021 às 13:35, Daniel S. Katz <
***@***.***> escreveu:

**Comment by kyleniemeyer** [comment]
Hi @tiagoseq, we are going to proceed with review of your submission.

@drvinceknight do you think you could edit this submission? The author has one reviewer suggestion already.

**Comment by kyleniemeyer** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by arfon** [comment]
I've just emailed Vince directly to see if he might be able to take on this submission. If we don't hear back in a few days, we'll look for an alternative editor.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon I'll proceed to invite an alternative editor

**Comment by Kevin-Mattheus-Moerman** [comment]
@jarvist it looks like this, although a neuroscientific application, might be a good editor for this. Are you able to help?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jarvist as editor

**Comment by whedon** [comment]
@jarvist has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jarvist could you help edit this work?

**Comment by jarvist** [comment]
@whedon assign @jarvist as editor

Yep, can do!

**Comment by whedon** [comment]
OK, the editor is @jarvist

**Comment by jarvist** [comment]
@tiagoseq do you have any reviewer suggestions? From looking at the fairly specialist problem domain, and the fairly specialist language (Julia), I suppose it might be easiest to find two reviewers with complementary scientific + programming language specific (+ PDE?) skills.

**Comment by tiagoseq** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1113/jphysiol.1952.sp004764 is OK
- 10.1109/JPROC.2004.840301 is OK
- 10.1002/cne.21974 is OK
- 10.1016/S0006-3495(72)86068-5 is OK
- 10.1103/PhysRevE.82.055701 is OK
- 10.1007/978-3-642-54593-1_6 is OK
- 10.3389/fninf.2015.00025 is OK
- 10.1186/2190-8567-4-1 is OK
- 10.1007/BF00337259 is OK
- 10.1137/141000671 is OK
- 10.1109/ICSTCC.2019.8885972 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by tiagoseq** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03886/joss.03886/10.21105.joss.03886.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03886/joss.03886/10.21105.joss.03886.pdf) :page_facing_up: :point_left:

**Comment by jarvist** [comment]
@whedon invite @rougier as reviewer

OK! Let's ask Nicolas directly here, as he seems to be a regular user of GitHub. 

We need at least two reviewers for JOSS. As Nicolas appears to be a domain expert, I suppose someone with PDE / Julia experience would be complementary.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by rougier** [comment]
I can review but I might be a bit late (note before end of December I would say)

**Comment by jarvist** [comment]
Great! As Tiago has already spoken with you, I presume such a timeline will be fine.

**Comment by jarvist** [comment]
@whedon assign @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by rougier** [comment]
@gdetor or @sje30 might be interested in reviewing this as well.

**Comment by gdetor** [comment]
@rougier  I could review it

**Comment by jarvist** [comment]
@whedon add @gdetor as reviewer

Great! Thank you Georgios.

**Comment by whedon** [comment]
OK, @gdetor is now a reviewer

**Comment by jarvist** [comment]
@whedon start review

Let's get this party started!

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3974.
