### ISSUE TITLE
[REVIEW]: mmrefpoints: Projecting long-term marine mammal abundance with bycatch

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3888]
**Submitting author:** @mcsiple (<a href="http://orcid.org/0000-0002-4260-9856">Margaret Siple</a>)
**Repository:** https://github.com/mcsiple/mmrefpoints
**Branch with paper.md** (empty if default branch): 
**Version:** v 1.0.1
**Editor:** @fboehm
**Reviewers:** @ha0ye, @tbrown122387
**Archive:** 10.5281/zenodo.6338110

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466/status.svg)](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466"><img src="https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466/status.svg)](https://joss.theoj.org/papers/548532c08c82cf64015d5440c495a466)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mcsiple/mmrefpoints" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ha0ye, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fboehm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @ha0ye
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mcsiple/mmrefpoints">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mcsiple/mmrefpoints">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mcsiple) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

@tbrown122387, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fboehm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @tbrown122387 
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mcsiple/mmrefpoints">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mcsiple/mmrefpoints">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mcsiple) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ha0ye and @eirenjacobson it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1309

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (745.6 files/s, 130135.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             7            208             92           3429
R                               46            487           1472           3388
JSON                             2              7              0            681
Rmd                              8            445            993            606
Markdown                         5            108              0            398
TeX                              2             27              0            366
YAML                             3              2              4             29
-------------------------------------------------------------------------------
SUM:                            73           1284           2561           8897
-------------------------------------------------------------------------------


Statistical information for the repository 'fc9602a544d20e3515f37bef' was
gathered on 2021/11/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.1748-7692.1998.tb00688.x is OK
- 10.1111/mms.12427 is OK
- 10.1644/11-MAMM-A-291.1 is OK
- 10.1093/icesjms/fsy049 is OK
- 10.1139/f84-058 is OK
- 10.2989/025776195784156511 is OK
- 10.1890/14-1990 is OK
- 10.1002/ece3.4772 is OK
- 10.7557/3.2747 is OK
- 10.3389/fmars.2021.735770 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3888 with the following error: 
```
 [WARNING] Citeproc: citation eirenjacobson not found
Error producing PDF.
! Undefined control sequence.
\hyper@@link ->\let \Hy@reserved@a 
                                   \relax \@ifnextchar [{\hyper@link@ }{\hyp...
l.386 }

Looks like we failed to compile the PDF

```

**Comment by fboehm** [comment]
@whedon re-invite  @eirenjacobson as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@ @eirenjacobson please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by fboehm** [comment]
@whedon re-invite @ha0ye as reviewer

**Comment by whedon** [comment]
@ha0ye already has access.

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03888/joss.03888/10.21105.joss.03888.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03888/joss.03888/10.21105.joss.03888.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
@ha0ye and @

**Comment by fboehm** [comment]
@eirenjacobson - Did you have a chance to accept the invitation? (in the thread above)
If the link has expired, please let me know. Thanks again!

**Comment by ha0ye** [comment]
I haven't started yet, but it's on my calendar.

**Comment by fboehm** [comment]
Hi, @eirenjacobson - sorry for my error. Can you check to see if you can check the boxes in the checklist? Just try to check one, to see if the checkmark appears, then uncheck it, assuming that you haven't actually verified that piece of information for the review. I think that there was an issue with your invitation, but the bot whedon may have resolved it. Thanks again!

**Comment by eirenjacobson** [comment]
No, I can't check the boxes :(

**Comment by fboehm** [comment]
Thanks for checking. I'll re-invite you now via the bot.

**Comment by fboehm** [comment]
@whedon re-invite @eirenjacobson as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@eirenjacobson please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by eirenjacobson** [comment]
I'm all set now, thanks!

**Comment by eirenjacobson** [comment]
Hi all, I had planned to complete this review this week but I am currently participating in strike action to improve UK higher education staff pension, pay, equality and working conditions (for more information, see https://www.ucu.org.uk/article/11896/Why-were-taking-action). I will try to complete my review when I return from strike next week.

**Comment by mcsiple** [comment]
Thank you for letting us know @eirenjacobson and power to the people!

**Comment by ha0ye** [comment]
I have completed my review, and my detailed notes are in the issue linked directly above.

**Comment by fboehm** [comment]
@whedon add @tbrown122387 as reviewer

**Comment by whedon** [comment]
OK, @tbrown122387 is now a reviewer

**Comment by fboehm** [comment]
@whedon remove @eirenjacobson as reviewer

**Comment by whedon** [comment]
OK, @eirenjacobson is no longer a reviewer

**Comment by fboehm** [comment]
@tbrown122387 and @ha0ye - how are the reviews going? Is there anything that I can do to assist you?

**Comment by fboehm** [comment]
@mcsiple - are there any questions about the issues that the reviewers have opened?

**Comment by tbrown122387** [comment]
@fboehm  everything’s all good thanks. Just waiting to hear back on this (probably final) issue.

**Comment by mcsiple** [comment]
@fboehm thank you-- I am slowly working through the revisions and I don't think I have any questions so far. Thank you @tbrown122387  and @ha0ye for both of your reviews! More soon.

**Comment by mcsiple** [comment]
Thank you all for your patience and both Hao and Taylor for your reviews. I have been working on addressing both reviewers' comments in the following issues:

1. @ha0ye 's review notes:  mcsiple/mmrefpoints#57
2. Detailed responses and commits related to functionality review from @ha0ye : mcsiple/mmrefpoints#54
3. @tbrown122387 's coverage comments: mcsiple/mmrefpoints#58 

I have been working through the testing infrastructure and should be done soon. I have now made modifications addressing everything (I think) except test coverage (should be done soon) and the version updating issue (will make a new release when I'm done writing tests; zenodo is now auto-linked to the github repo so it should automatically update authors and version # when I push changes). 

In the first version I released, I accidentally only included the first three authors; if anyone has experience changing the author list for a zenodo-linked repo, I would love your guidance. Ideally the next release (0.1.2) will have all the authors that are in CITATION.cff.

Thank you both again, and more coming soon.

**Comment by ha0ye** [comment]
> In the first version I released, I accidentally only included the first three authors; if anyone has experience changing the author list for a zenodo-linked repo, I would love your guidance. Ideally the next release (0.1.2) will have all the authors that are in CITATION.cff.

I believe you can go in to Zenodo -> Upload to manually select and then update the info on an existing deposit. Or if you're set up for auto-archiving of releases, then the newer DOI will have the updated information.

**Comment by mcsiple** [comment]
Alright! I believe I am done making revisions. A few notes:

## Author list in CITATION.cff and on Zenodo
I was able to properly update the `.zenodo.json` file so that it automatically updates the [Zenodo entry](https://zenodo.org/record/5919455#.YfYZzVjMI-Q) when I make a new release on GitHub. [Release v0.1.6](https://github.com/mcsiple/mmrefpoints/releases/tag/v.0.1.6) has all the changes incorporated. I think it is fully ready for the reviewers to look over again. 

## Test coverage
Test coverage is addressed by the commits above and in mcsiple/mmrefpoints/issues/58. The coverage is not 100%; this is partly because some of the functions that `covr::report()` finds are `golem` functions that I did not write. 

## Not sure if I need to tag whedon
Tagging @ha0ye , @tbrown122387 , and @fboehm  here to let you know I have finished revisions.

**Comment by fboehm** [comment]
@mcsiple - Thanks for your message and the updates. @ha0ye and @tbrown122387 can now review the changes.

**Comment by tbrown122387** [comment]
looks good @fboehm nice job @mcsiple

**Comment by fboehm** [comment]
Thanks for finalizing your review, @tbrown122387 !

**Comment by mcsiple** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03888/joss.03888/10.21105.joss.03888.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03888/joss.03888/10.21105.joss.03888.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
@ha0ye - have you had a chance to review the changes from @mcsiple ? Please let me know if any questions or concerns remain. Thanks again!

**Comment by mcsiple** [comment]
Need to re-make the pdf again for a colleague; sorry for all the traffic. 

@whedon generate PDF

**Comment by fboehm** [comment]
@ha0ye - Thanks for your message. Would it be reasonable for you to review things before March 1, 2022?

Thanks again!

**Comment by ha0ye** [comment]
Yup, that will work!

**Comment by ha0ye** [comment]
@fboehm No more issues to report from me.

**Comment by mcsiple** [comment]
Thanks @ha0ye -- and thank you for adding the Markdown child doc thing as its own issue. I  don't know if this is required, but the automated review thingy might be waiting until you check off boxes above. 

@fboehm Let me know if there are other things I should address, otherwise I eagerly await your decision!

**Comment by fboehm** [comment]
@mcsiple - the reviewers have recommended your submission for publication. Before we officially publish it, please make the following changes to your paper.md and bib file:

There's one small typo that needs fixing:

line 56 (of the pdf): delete "based"

Also, please cite R and shiny and include the references in your bibliography. 

We can proceed towards publication once these changes are made.

**Comment by mcsiple** [comment]
Hi @fboehm -- just fixed those two things. Thanks for your help!

**Comment by fboehm** [comment]
Thank you, @mcsiple !

**Comment by fboehm** [comment]
@editorialbot generate pdf

**Comment by fboehm** [comment]
@mcsiple - one small fix is needed in the new reference to Shiny: Please fix the bib file so that R is capitalized on line 114 of the pdf. You can accomplish this by placing braces around a capital R, like {R} within the bibtex entry. Thanks again!

**Comment by fboehm** [comment]
@editorialbot check references

**Comment by mcsiple** [comment]
Fixed! Sorry about that. I copied from `citation` in R and didn't realize I needed that extra formatting to get the caps. Should be good now.

**Comment by fboehm** [comment]
Thank you, @mcsiple.

**Comment by fboehm** [comment]
@editorialbot generate pdf

**Comment by fboehm** [comment]
@editorialbot set v1.0.0 as version

**Comment by fboehm** [comment]
@editorialbot set 10.5281/zenodo.6336011 as archive

**Comment by fboehm** [comment]
@editorialbot recommend-accept

**Comment by fboehm** [comment]
@openjournals/joss-eics - can you explain the error message that we're getting? I'm unfamiliar with it. Thanks!

**Comment by xuanxu** [comment]
The error is caused because there are two invalid issn values in the bib file: [here](https://github.com/mcsiple/mmrefpoints/blob/master/paper.bib#L69) and [here](https://github.com/mcsiple/mmrefpoints/blob/master/paper.bib#L86).

**Comment by mcsiple** [comment]
Thanks @xuanxu -- I fixed the .bib entries. Do I need to create another release?

**Comment by fboehm** [comment]
@whedon set version as v 1.0.1

**Comment by fboehm** [comment]
@editorialbot set version as v 1.0.1

**Comment by fboehm** [comment]
@editorialbot set v 1.0.1 as version

**Comment by fboehm** [comment]
set 10.5281/zenodo.6338110 as archive

**Comment by fboehm** [comment]
@editorialbot set 10.5281/zenodo.6338110 as archive

**Comment by fboehm** [comment]
@editorialbot recommend-accept

**Comment by kyleniemeyer** [comment]
Hi @mcsiple, I've made a small PR for the paper that does some minor formatting changes: https://github.com/mcsiple/mmrefpoints/pull/62

Could you merge this? I will then accept your paper.

**Comment by mcsiple** [comment]
Hi @kyleniemeyer -- done. Thank you!

**Comment by kyleniemeyer** [comment]
@editorialbot generate pdf

**Comment by kyleniemeyer** [comment]
@editorialbot accept

**Comment by mcsiple** [comment]
Upon step 0, I found that one of the authors has an extra L in his name in paper.md🤦🏻‍♀️ It's correct everywhere else and I just fixed it. What do I do next? Sorry for the inconvenience...

**Comment by kyleniemeyer** [comment]
@arfon can you correct the published paper?

**Comment by mcsiple** [comment]
Found two more copy edits in paper.md (sorry, and thank you)-- see below.

**Comment by arfon** [comment]
@editorialbot recommend-accept

**Comment by arfon** [comment]
@editorialbot recommend-accept

**Comment by arfon** [comment]
@editorialbot accept

**Comment by arfon** [comment]
@kyleniemeyer – this should be updated now. Note that the new PDF might take a few hours to show up on the JOSS site due to caching.
