### ISSUE TITLE
[PRE REVIEW]: excluder: An R package that checks for exclusion criteria in online data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3889]
**Submitting author:** @JeffreyRStevens (<a href="http://orcid.org/0000-0003-2375-1360">Jeffrey R Stevens</a>)
**Repository:** <a href="https://github.com/ropensci/excluder/" target ="_blank">https://github.com/ropensci/excluder/</a>
**Version:** v0.3.1
**Editor:** @danielskatz
**Reviewers:** @danielskatz
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/25a045841e7e91fdc25745cc458a1fd6/status.svg)](https://joss.theoj.org/papers/25a045841e7e91fdc25745cc458a1fd6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/25a045841e7e91fdc25745cc458a1fd6"><img src="https://joss.theoj.org/papers/25a045841e7e91fdc25745cc458a1fd6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/25a045841e7e91fdc25745cc458a1fd6/status.svg)](https://joss.theoj.org/papers/25a045841e7e91fdc25745cc458a1fd6)
```

**Author instructions**

Thanks for submitting your paper to JOSS @JeffreyRStevens. **Currently, there isn't an JOSS editor assigned** to your paper.

@JeffreyRStevens if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (738.5 files/s, 119196.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            30           1452            386           5253
R                               27            296           1419           2071
Markdown                         6            211              0            849
CSS                              3             99             48            428
JSON                             1              0              0            303
JavaScript                       3             64             32            256
SVG                              9              0              1            179
YAML                             5             26              2            142
Rmd                              2             86            177            101
-------------------------------------------------------------------------------
SUM:                            86           2234           2065           9582
-------------------------------------------------------------------------------


Statistical information for the repository '8f1b3b2c7f80c1a279cf0928' was
gathered on 2021/11/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeffrey Stevens                  1           352              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jeffrey R. Stevens          352          100.0         -0.0                9.09
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3889 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/13645579.2018.1563966 is OK
- 10.1177/1948550619875149 is OK
- 10.3758/s13428-021-01694-3 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03889/joss.03889/10.21105.joss.03889.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03889/joss.03889/10.21105.joss.03889.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @mikldk - would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@JeffreyRStevens - thank you for the submission.

Do you have any suggestions for reviewers ([here](https://bit.ly/joss-reviewers) is a list of potential reviewers)?

**Comment by JeffreyRStevens** [comment]
Thanks, @mikldk. The package has already been peer reviewed in rOpenSci by Joseph O'Brien (@jmobrien) and Julia Silge (@juliasilge) at https://github.com/ropensci/software-review/issues/455. Is there a fast-track review option since it has already been peer reviewed? If so, do you still need additional reviewers?
Thanks.

**Comment by danielskatz** [comment]
Yes, sorry, I was not aware of this when I asked @mikldk to edit.  I'll take this back and run this through quickly, in the next day or few hopefully.

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by JeffreyRStevens** [comment]
@danielskatz, OK--thanks. Note that the reviewers did not review the paper, just the package.

**Comment by danielskatz** [comment]
right - that's typical - I will review the paper as part of the process

**Comment by danielskatz** [comment]
@ehedon assign @danielskatz as reviewer

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, @danielskatz is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3893.
