### ISSUE TITLE
[PRE REVIEW]: Quail: A Python toolbox for analyzing and plotting free recall data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#389]
**Submitting author:** @andrewheusser (<a href="http://orcid.org/0000-0001-6353-688X">Andrew Heusser</a>)
**Repository:** <a href="https://github.com/ContextLab/quail" target ="_blank">https://github.com/ContextLab/quail</a>
**Version:** v0.1.0
**Editor:** @cMadan
**Reviewer:** @RichardLitt

**Author instructions**

Thanks for submitting your paper to JOSS @andrewheusser. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@andrewheusser if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by cMadan** [comment]
@andrewheusser, this looks like a really useful project! Do you have any suggestions for reviewers?

**Comment by andrewheusser** [comment]
@cMadan Thanks!  We are hoping it will be useful to others.  We are using it in the lab and it streamlines our analyses quite a bit.

Regarding reviewers, would it be possible for you to review it?  Given your background in psychology and memory it seems like the best fit out of the list of reviewers, but I wasn't sure if that would be possible given that you are the editor.  If not, here are 3 more that also seem like a good fit:

1. arokem
2. jkahn
3. richardlitt

**Comment by cMadan** [comment]
@andrewheusser, unfortunately, I can't serve as both editor and reviewer. I also just moved to another uni/country last week and wouldn't have time to adequately review the project myself.

@jkahn and @RichardLitt, would either of you be able to review this project?

**Comment by RichardLitt** [comment]
I won't be able to, sorry. Overloaded this next few weeks. If no one steps up by October 1st, I'd be happy to.

**Comment by cMadan** [comment]
Thanks, @RichardLitt! I'll ping you if we still haven't found someone by then.

**Comment by jdkoen** [comment]
Unfortunately, I too am unable to review and test it out at this time. Will
be out of the country for a week and am booked solid with participants the
following week.

Best,

Josh

**Comment by cMadan** [comment]
@RichardLitt, are you still available to be a reviewer for this?

**Comment by RichardLitt** [comment]
@whedon assign @RichardLitt as reviewer

**Comment by whedon** [comment]
I'm sorry @RichardLitt, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by arfon** [comment]
@whedon assign @RichardLitt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @RichardLitt

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/424. Feel free to close this issue now!
