### ISSUE TITLE
[PRE REVIEW]: Unishox: A hybrid encoder for Short Unicode Strings

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3890]
**Submitting author:** @siara-cc (<a href="http://orcid.org/0000-0001-6642-447X">Arundale Ramanathan</a>)
**Repository:** <a href="https://github.com/siara-cc/Unishox2" target ="_blank">https://github.com/siara-cc/Unishox2</a>
**Version:** 1.0.1
**Editor:** @gkthiruvathukal
**Reviewers:** @gradvohl, @linuxscout
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58/status.svg)](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58"><img src="https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58/status.svg)](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58)
```

**Author instructions**

Thanks for submitting your paper to JOSS @siara-cc. **Currently, there isn't an JOSS editor assigned** to your paper.

@siara-cc if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1844

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (251.3 files/s, 89424.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                3            215            292           2932
C++                              1             68             64            995
TeX                              3            231              4            898
C/C++ Header                     3             45             74            163
Markdown                         2             77              0            154
YAML                             1              4              0             91
CMake                            3             12              0             58
JSON                             1              0              0             16
make                             1              3              0             10
-------------------------------------------------------------------------------
SUM:                            18            655            434           5317
-------------------------------------------------------------------------------


Statistical information for the repository 'f8939c64e70f37ed4a40752c' was
gathered on 2021/11/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Arun                            44          5920           1522           61.79
Arundale Ramanathan              1             2           1036            8.62
James Z.M. Gao                  24          1248            953           18.27
Jonathan Greenblatt              3          1261             17           10.61
Luis Diaz                        1             4              2            0.05
Luis Díaz Más                    5            36             43            0.66

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Arun                       2938           49.6         10.4               10.96
James Z.M. Gao              638           51.1          0.7                1.88
Jonathan Greenblatt        1244           98.7          6.1                7.72
Luis Díaz Más                28           77.8          1.4                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/tit.2004.834752 may be a valid DOI for title: Information Theory, Inference, and Learning Algorithms
- 10.4135/9781412959384.n229 may be a valid DOI for title: A Mathematical Theory of Communication
- 10.1109/jrproc.1952.273898 may be a valid DOI for title: A method for the construction of minimum-redundancy codes
- 10.1007/978-3-319-77525-8_100098 may be a valid DOI for title: Delta Encoding

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03890/joss.03890/10.21105.joss.03890.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03890/joss.03890/10.21105.joss.03890.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - would you be able to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @gkthiruvathukal as editor

**Comment by whedon** [comment]
@gkthiruvathukal has been invited to edit this submission.

**Comment by gkthiruvathukal** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@siara-cc Please suggest 4-5 potential reviewers from the list of people so we can begin the review process. See the top of this issue thread. (Please don't use the @ symbol to mention them. I'll do that.)

**Comment by siara-cc** [comment]
@gkthiruvathukal  Thank you for taking this forward. I suggest drj11, desilinguist, sepandhaghighi, linuxscout, gradvohl, tresoldi from the list.

**Comment by siara-cc** [comment]
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

I have added DOIs where ever available

**Comment by siara-cc** [comment]
Hi @gkthiruvathukal, please see my reply above - not sure if it missed your notice.

**Comment by gkthiruvathukal** [comment]
Thanks, @siara-cc! Stay tuned.

**Comment by gkthiruvathukal** [comment]
@linuxscout and gradvohl: Are you willing to help contribute a review for this JOSS submission?

**Comment by gradvohl** [comment]
Yes. I'm in.

**Comment by linuxscout** [comment]
Ok, I will review it.

**Comment by gradvohl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03890/joss.03890/10.21105.joss.03890.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03890/joss.03890/10.21105.joss.03890.pdf) :page_facing_up: :point_left:

**Comment by gkthiruvathukal** [comment]
@whedon assign @gradvohl as reviewer

**Comment by whedon** [comment]
OK, @gradvohl is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon add @linuxscout as reviewer

**Comment by whedon** [comment]
OK, @linuxscout is now a reviewer

**Comment by gkthiruvathukal** [comment]
@linuxscout and @gradvohl, thank you for your willingness to review!

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3919.

**Comment by siara-cc** [comment]
Thank you @linuxscout @gradvohl @gkthiruvathukal
