### ISSUE TITLE
[PRE REVIEW]: Council Data Project: Software for Municipal Data Collection, Analysis, and Publication

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3891]
**Submitting author:** @JacksonMaxfield (<a href="http://orcid.org/0000-0003-2564-0373">Jackson Brown</a>)
**Repository:** <a href="https://github.com/CouncilDataProject/cookiecutter-cdp-deployment" target ="_blank">https://github.com/CouncilDataProject/cookiecutter-cdp-deployment</a>
**Version:** v3.0.0
**Editor:** @chartgerink
**Reviewers:** @hknd23, @chainsawriot
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a3ed732d18a07a70ac256501911a8122/status.svg)](https://joss.theoj.org/papers/a3ed732d18a07a70ac256501911a8122)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a3ed732d18a07a70ac256501911a8122"><img src="https://joss.theoj.org/papers/a3ed732d18a07a70ac256501911a8122/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a3ed732d18a07a70ac256501911a8122/status.svg)](https://joss.theoj.org/papers/a3ed732d18a07a70ac256501911a8122)
```

**Author instructions**

Thanks for submitting your paper to JOSS @JacksonMaxfield. **Currently, there isn't an JOSS editor assigned** to your paper.

@JacksonMaxfield if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1234

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (956.9 files/s, 63830.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            17            172             77            917
Markdown                        12            336              0            712
Python                          11            138             92            603
JSON                             6              0              0            103
TeX                              1              7              0             76
HTML                             1              2              3             73
make                             2             12              0             52
JSX                              1              3              0             24
-------------------------------------------------------------------------------
SUM:                            51            670            172           2560
-------------------------------------------------------------------------------


Statistical information for the repository '1d969924b4365059687dcb4c' was
gathered on 2021/11/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Hawk Ticehurst                   2            23            170           13.08
Isaac Na                         3             3              3            0.41
Jackson Maxfield Bro            13           932            147           73.15
JacksonMaxfield                  1           195              0           13.22
Toni Wells                       1             1              1            0.14

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Hawk Ticehurst                5           21.7          5.2                0.00
Isaac Na                      1           33.3          1.1                0.00
Jackson Maxfield Bro        826           88.6          2.5                9.93
Toni Wells                    1          100.0          7.5                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00411 is OK

MISSING DOIs

- 10.1017/s1537592709990892 may be a valid DOI for title: All Politics Is Local: The Reemergence of the Study of City Politics
- 10.5860/choice.49-1821 may be a valid DOI for title: CourtListener

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03891/joss.03891/10.21105.joss.03891.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03891/joss.03891/10.21105.joss.03891.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@JacksonMaxfield - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by nniiicc** [comment]
@danielskatz - see https://github.com/openjournals/joss/issues/990 about scope.

**Comment by danielskatz** [comment]
Thanks @nniiicc - can you clarify what software would be reviewed in this case?

**Comment by JacksonMaxfield** [comment]
Hey @danielskatz!

Thanks @nniiicc for pointing to the issue. The software which should be reviewed is:

* https://github.com/CouncilDataProject/cookiecutter-cdp-deployment (the repository which this paper is in)
* https://github.com/CouncilDataProject/cdp-backend
* https://github.com/CouncilDataProject/cdp-frontend

**Comment by danielskatz** [comment]
Thanks @JacksonMaxfield and @nniiicc - I've ended the scope query, and we'll move onto finding an editor

**Comment by danielskatz** [comment]
👋 @chartgerink - the submitters suggested you as the editor for this JOSS submission - can you edit it?

**Comment by danielskatz** [comment]
@whedon invite @chartgerink as editor

**Comment by whedon** [comment]
@chartgerink has been invited to edit this submission.

**Comment by chartgerink** [comment]
Hi @danielskatz - happy to! I will find some reviewers 😊

**Comment by danielskatz** [comment]
Thanks - you can/should assign yourself as the editor in this case, via `@whedon assign me as editor` or `@whedon assign @chartgerink as editor`

**Comment by danielskatz** [comment]
@whedon assign @chartgerink as editor

but I'll do it in this case :)

**Comment by JacksonMaxfield** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S1537592709990892 is OK
- 10.21105/joss.00411 is OK

MISSING DOIs

- 10.5860/choice.49-1821 may be a valid DOI for title: CourtListener

INVALID DOIs

- None
```

**Comment by JacksonMaxfield** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03891/joss.03891/10.21105.joss.03891.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03891/joss.03891/10.21105.joss.03891.pdf) :page_facing_up: :point_left:

**Comment by JacksonMaxfield** [comment]
DOI for "All Politics is Local" updated but CourtListener doesn't seem to have a DOI at all so leaving as is.

**Comment by chartgerink** [comment]
@whedon assign @chainsawriot as reviewer

**Comment by whedon** [comment]
OK, @chainsawriot is now a reviewer

**Comment by chartgerink** [comment]
@whedon assign @hknd23 as reviewer

**Comment by whedon** [comment]
OK, @hknd23 is now a reviewer

**Comment by chartgerink** [comment]
@whedon add @chainsawriot as reviewer

**Comment by whedon** [comment]
OK, @chainsawriot is now a reviewer

**Comment by chartgerink** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3904.
