### ISSUE TITLE
[PRE REVIEW]: PySPI: A python analysis framework for INTEGRAL/SPI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3892]
**Submitting author:** @BjoernBiltzinger (<a href="http://orcid.org/0000-0003-3381-0985">Björn Biltzinger</a>)
**Repository:** <a href="https://github.com/BjoernBiltzinger/pyspi" target ="_blank">https://github.com/BjoernBiltzinger/pyspi</a>
**Version:** v0.9.0
**Editor:** @christinahedges
**Reviewers:** @tohuvavohu, @DougBurke
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b502144fc0c1c6d71c76fc808c016c96/status.svg)](https://joss.theoj.org/papers/b502144fc0c1c6d71c76fc808c016c96)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b502144fc0c1c6d71c76fc808c016c96"><img src="https://joss.theoj.org/papers/b502144fc0c1c6d71c76fc808c016c96/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b502144fc0c1c6d71c76fc808c016c96/status.svg)](https://joss.theoj.org/papers/b502144fc0c1c6d71c76fc808c016c96)
```

**Author instructions**

Thanks for submitting your paper to JOSS @BjoernBiltzinger. **Currently, there isn't an JOSS editor assigned** to your paper.

@BjoernBiltzinger if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 753

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.34 s (295.5 files/s, 77834.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          29           1305           2035           3211
CSS                             36             31             77           2590
Markdown                         9            159              0            794
Jupyter Notebook                 7              0          14764            573
YAML                             7             68             34            375
TeX                              1              4              0             41
DOS Batch                        1              8              1             27
JavaScript                       1              1              8             26
reStructuredText                 6             35             83             22
HTML                             2              0             25             20
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           100           1615          17033           7689
-------------------------------------------------------------------------------


Statistical information for the repository '3d3d3040fde4e0c1ac016181' was
gathered on 2021/11/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Biltzinger Bjoern                2             6              6            0.02
BjoernBiltzinger                42          2354           3821            8.76
Björn Biltzinger               248         32315          24419           80.48
J. Michael Burgess              69          3909            878            6.79
grburgess                        9          2551            238            3.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Björn Biltzinger           3535           10.9          5.1               13.47
grburgess                  3051          119.6          9.9               15.90
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361:20031482 is OK

MISSING DOIs

- 10.22323/1.312.0130 may be a valid DOI for title: The Multi-Mission Maximum Likelihood framework (3ML)
- 10.22323/1.312.0130 may be a valid DOI for title: The Multi-Mission Maximum Likelihood framework (3ML)

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3892 with the following error: 
```
 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (0000-0002-0552-353) for Thomas Siegert (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
👋 @BjoernBiltzinger - note that your paper does not compile. Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). 
The problem might be the blank line (line 7) in your metadata.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @christinahedges - do you think you would be able to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @christinahedges as editor

**Comment by whedon** [comment]
@christinahedges has been invited to edit this submission.

**Comment by BjoernBiltzinger** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.5646924 is OK
- 10.5281/zenodo.5646953 is OK
- 10.1051/0004-6361:20031482 is OK

MISSING DOIs

- 10.22323/1.312.0130 may be a valid DOI for title: The Multi-Mission Maximum Likelihood framework (3ML)

INVALID DOIs

- None
```

**Comment by BjoernBiltzinger** [comment]
The suggested DOI for the "The Multi-Mission Maximum Likelihood framework (3ML)" is not the correct one. Unfortunately there is no DOI for this paper, because it was only published on arxiv.

**Comment by BjoernBiltzinger** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03892/joss.03892/10.21105.joss.03892.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03892/joss.03892/10.21105.joss.03892.pdf) :page_facing_up: :point_left:

**Comment by christinahedges** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @christinahedges

**Comment by christinahedges** [comment]
@BjoernBiltzinger thanks for your submission to JOSS! I will look into your submission, and search for relevant reviewers. If you have suggestions for people who would make good reviewers for your work (without conflicts of interest) please let me know here in the thread.

Thank you for updating the article, sorry it seems to have broken your CI!

**Comment by BjoernBiltzinger** [comment]
@christinahedges I fixed the broken CI. The problem is that the INTEGRAL data archive at ISDC is not working at the moment. They had some technical difficulties last Thursday and are still working to get everything running again. For the CI, I added the relevant data files for the tests to the package now. So if the data archive is not working, these local files are used to run the tests. 

But the problem at the moment is that most of PySPI will not run, because we rely on the data download from the ISDC data archive. I hope this problem gets fixed soon.

**Comment by christinahedges** [comment]
Hi @BjoernBiltzinger it looks like your CI is passing now so it seems like the archive is live again. I am searching for reviewers for this tool now, please do let me know if you have suggestions, otherwise, watch this space!

**Comment by BjoernBiltzinger** [comment]
Hi @christinahedges, looking at the list of available reviewers, I think four possible reviewers for our submission could be: Fipanther, dhuppenkothen, smsharma, nespinoza

**Comment by christinahedges** [comment]
Hi @BjoernBiltzinger thanks, I can look into these reviewers. Feel free to choose people who aren't on the list, who are in your field and understand your science use case well, and may be responsive to a JOSS review.

**Comment by christinahedges** [comment]
Hi @BjoernBiltzinger, just checking in, I'm still digging for reviewers for this submission. We'll find people, I'll keep you posted!

**Comment by christinahedges** [comment]
@whedon assign @tohuvavohu as reviewer

**Comment by whedon** [comment]
OK, @tohuvavohu is now a reviewer

**Comment by christinahedges** [comment]
Hi @@tohuvavohu and @BjoernBiltzinger, we have one reviewer, unfortunately there was a second reviewer but we've found a conflict of interest, and so I need some more time to find a second reviewer. Watch this space!

**Comment by christinahedges** [comment]
@whedon add @DougBurke as reviewer

**Comment by whedon** [comment]
OK, @DougBurke is now a reviewer

**Comment by christinahedges** [comment]
Hello all, thank you so much for being part of the JOSS review process. I'm now going to start the review. I understand because of the holidays, many of us won't be responsive to this review for a little while. That's totally ok!

**Comment by christinahedges** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4017.
