### ISSUE TITLE
[PRE REVIEW]: GCM-Filters: A Python Package for Diffusion-based Spatial Filtering of Gridded Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3894]
**Submitting author:** @NoraLoose (<a href="http://orcid.org/0000-0002-3684-9634">Nora Loose</a>)
**Repository:** <a href="https://github.com/ocean-eddy-cpt/gcm-filters" target ="_blank">https://github.com/ocean-eddy-cpt/gcm-filters</a>
**Version:** v0.1.3
**Editor:** @elbeejay
**Reviewers:** @callumrollo, @AleksiNummelin, @isgiddy
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/bc8ad806627f0d754347686e21f00d40/status.svg)](https://joss.theoj.org/papers/bc8ad806627f0d754347686e21f00d40)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bc8ad806627f0d754347686e21f00d40"><img src="https://joss.theoj.org/papers/bc8ad806627f0d754347686e21f00d40/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bc8ad806627f0d754347686e21f00d40/status.svg)](https://joss.theoj.org/papers/bc8ad806627f0d754347686e21f00d40)
```

**Author instructions**

Thanks for submitting your paper to JOSS @NoraLoose. **Currently, there isn't an JOSS editor assigned** to your paper.

@NoraLoose if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1131

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1029/2021MS002552 is OK
- 10.5334/jors.148 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 1721.1/117188 is OK
- 10.5281/zenodo.4968496 is OK

MISSING DOIs

- 10.25080/majora-7b98e3ed-013 may be a valid DOI for title:  Dask: Parallel Computation with Blocked algorithms and Task Scheduling 

INVALID DOIs

- https://doi.org/10.1029/2019MS001726 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (230.3 files/s, 176058.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            428            366           1502
Jupyter Notebook                 8              0          23079            879
reStructuredText                 6            219            182            259
TeX                              1             18              0            191
YAML                             7             12             15            184
Markdown                         2             35              0            114
TOML                             1              2              0             11
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            36            718          23649           3149
-------------------------------------------------------------------------------


Statistical information for the repository 'a7710009ba542e7c996313ed' was
gathered on 2021/11/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Ross                      8            89             20            1.10
Arthur                          24           483            420            9.10
Elizabeth A Yankovsk             6           132             41            1.74
Gustavo Marques                 10           632            198            8.37
Ian Grooms                      30           456            305            7.67
Julius Busecke                   6           104            209            3.16
NoraLoose                      116          3111           1557           47.06
Ryan Abernathey                 28          1461            686           21.64
Scott Bachman                    2             8              8            0.16

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew Ross                  70           78.7          0.9               14.29
Arthur                        5            1.0          7.9                0.00
Elizabeth A Yankovsk         25           18.9          1.0               16.00
Gustavo Marques             249           39.4          5.6               10.84
Ian Grooms                  201           44.1          5.7                5.97
Julius Busecke               83           79.8          9.2               39.76
NoraLoose                   936           30.1          4.6               10.36
Ryan Abernathey             727           49.8          5.9                8.12
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03894/joss.03894/10.21105.joss.03894.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03894/joss.03894/10.21105.joss.03894.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@noraloose - while we find an editor, can you work on the possibly missing DOI and the incorrect DOI that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @elbeejay - do you think you could edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @elbeejay as editor

**Comment by whedon** [comment]
@elbeejay has been invited to edit this submission.

**Comment by danielskatz** [comment]
@kthyng - just pinging you as well, since this falls into your area, but you currently don't have editing slots open

**Comment by NoraLoose** [comment]
Thanks @danielskatz for handling our submission and looking for an editor!

> while we find an editor, can you work on the possibly missing DOI and the incorrect DOI that whedon suggests

Yes, working on it!

**Comment by NoraLoose** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1029/2021MS002552 is OK
- 10.5334/jors.148 is OK
- 10.25080/Majora-7b98e3ed-013 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1029/2019MS001726 is OK
- 1721.1/117188 is OK
- 10.5281/zenodo.4968496 is OK

MISSING DOIs

- 10.25080/majora-7b98e3ed-013 may be a valid DOI for title:  Dask: Parallel Computation with Blocked algorithms and Task Scheduling 

INVALID DOIs

- None
```

**Comment by NoraLoose** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1029/2021MS002552 is OK
- 10.5334/jors.148 is OK
- 10.25080/majora-7b98e3ed-013 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1029/2019MS001726 is OK
- 1721.1/117188 is OK
- 10.5281/zenodo.4968496 is OK

MISSING DOIs

- 10.25080/majora-7b98e3ed-013 may be a valid DOI for title:  Dask: Parallel Computation with Blocked algorithms and Task Scheduling 

INVALID DOIs

- None
```

**Comment by NoraLoose** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3894 with the following error: 
```
 
```

**Comment by NoraLoose** [comment]
@whedon generate pdf

**Comment by elbeejay** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @elbeejay

**Comment by elbeejay** [comment]
@NoraLoose can you try switching the bib entry-type for `dask` to `@misc` instead of `@Manual`? That is the recommended format for citing a software repository per the JOSS docs ([link](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)), and so it might play nicer with whedon.

**Comment by NoraLoose** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3894 with the following error: 
```
 
```

**Comment by NoraLoose** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1029/2021MS002552 is OK
- 10.5334/jors.148 is OK
- 10.25080/majora-7b98e3ed-013 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1029/2019MS001726 is OK
- 1721.1/117188 is OK
- 10.5281/zenodo.4968496 is OK

MISSING DOIs

- 10.25080/majora-7b98e3ed-013 may be a valid DOI for title:  Dask: Parallel Computation with Blocked algorithms and Task Scheduling 

INVALID DOIs

- None
```

**Comment by elbeejay** [comment]
Thanks for giving it a shot; I'll see if we can get a whedon-expert to have a look.

**Comment by NoraLoose** [comment]
Thanks @elbeejay! The paper compiles just fine if I try via https://whedon.theoj.org/.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03894/joss.03894/10.21105.joss.03894.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03894/joss.03894/10.21105.joss.03894.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Looks like @whedon was running out of memory, this can sometimes happen with very large vector images (such as [this one](https://github.com/ocean-eddy-cpt/gcm-filters/blob/master/filtered_vorticity.png)). If possible, please downsize that image, and this should be fine, but also, Whedon can likely be coaxed into compiling this (as just happened) 😸

**Comment by NoraLoose** [comment]
Thanks @arfon for looking into this! I have decreased the figure size by half. Let's hope Whedon will like this paper better now!

**Comment by NoraLoose** [comment]
I have a few suggestions for potential reviewers.

From the spreadsheet:
* callumrollo
* ali-ramadhan
* edoddridge

Not on the list:
* leewujung
* AleksiNummelin
* isgiddy
* dcherian
* emiliom
* cgentemann

**Comment by elbeejay** [comment]
:wave: @callumrollo, @ali-ramadhan, @edoddridge, would you be willing to review this submission to JOSS? I believe you all have prior experience with JOSS, but for your reference, the JOSS review criteria can be found [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

The submission is "GCM-Filters: A Python Package for Diffusion-based Spatial Filtering of Gridded Data". This is a pre-review issue which is used to find reviewers. Once 2 or 3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks, although this can be extended if needed. If you are not able to review but can recommend someone else, please mention them here (in this case please mention their GitHub handle without the "@" symbol).

If you are interested, please take a look at the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) to ensure you do not have a conflict before agreeing to review this submission.

Thank you, feel free to reach out if you have any questions about the JOSS review process. Please do not feel any pressure to accept this review request if you do not have the time or do not feel comfortable reviewing this software package, we appreciate and respect our peer-reviewers' time.

**Comment by callumrollo** [comment]
Hi @elbeejay, I'd be happy to review this submission. I've not got much experience with GCMs, but can focus on the Python implementation, testing, documentation etc.

I have not formal conflict of interest and I have never worked with the lead author. However, I am a contributor to the [glidertools](https://github.com/GliderToolsCommunity/GliderTools) package along with jbusecke, who has made several contributions to GCM-filters. I do not think this would affect my review of this submitssion, but please exclude me if this breaks the JOSS conflict of interest guidelines.

**Comment by elbeejay** [comment]
> Hi @elbeejay, I'd be happy to review this submission. I've not got much experience with GCMs, but can focus on the Python implementation, testing, documentation etc.
> 
> I have not formal conflict of interest and I have never worked with the lead author. However, I am a contributor to the [glidertools](https://github.com/GliderToolsCommunity/GliderTools) package along with jbusecke, who has made several contributions to GCM-filters. I do not think this would affect my review of this submitssion, but please exclude me if this breaks the JOSS conflict of interest guidelines.

Hi @callumrollo. We'd appreciate your expertise on and review of the Pythonic elements of the submission. Thank you for being forthcoming about the potential `glidertools` COI, from your description it does not seem as if that runs afoul of the JOSS COI guidelines.

**Comment by elbeejay** [comment]
@whedon add @callumrollo as reviewer

**Comment by whedon** [comment]
OK, @callumrollo is now a reviewer

**Comment by edoddridge** [comment]
Hi @elbeejay. I'm only working part time at the moment and wouldn't be able to do this in any sort of reasonable time frame, so I will need to decline this time. Sorry.

**Comment by elbeejay** [comment]
> Hi @elbeejay. I'm only working part time at the moment and wouldn't be able to do this in any sort of reasonable time frame, so I will need to decline this time. Sorry.

No problem, thanks for letting us know!

**Comment by AleksiNummelin** [comment]
Hi @elbeejay, I'd be happy to review, I have tested the tool already so this is  a good chance to look through the code properly. I will be busy for the next 2 weeks so expect little progress, but after that I'd expect to submit the review relatively quickly.

**Comment by elbeejay** [comment]
Awesome @AleksiNummelin, sounds like you'll be able to provide perspectives as both a real user and fellow developer. Thank you for being clear about your relationship with the lead-author, I agree that it does not sound like a true COI.

**Comment by elbeejay** [comment]
@whedon add @AleksiNummelin as reviewer

**Comment by whedon** [comment]
OK, @AleksiNummelin is now a reviewer

**Comment by elbeejay** [comment]
:wave: @isgiddy, would you be willing to review this submission to JOSS? I think your experience as an ocean scientist would allow you to provide the authors with a constructive review. At JOSS we do checklist-driven reviews, the JOSS review criteria can be found [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

The submission is "GCM-Filters: A Python Package for Diffusion-based Spatial Filtering of Gridded Data". This is a pre-review issue which is used to find reviewers. Once 2 or 3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks, although this can be extended if needed.

If you are interested, please take a look at the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) to ensure you do not have a conflict before agreeing to review this submission.

Thank you, feel free to reach out if you have any questions about the JOSS review process. Please do not feel any pressure to accept this review request if you do not have the time or do not feel comfortable reviewing this software package, we appreciate and respect our peer-reviewers' time.

**Comment by NoraLoose** [comment]
Hey @elbeejay! Just another thought: in case we are still short on reviewers, here are two more suggestions:

* raphaeldussin
* Jiawei Zhuang

**Comment by elbeejay** [comment]
> Hey @elbeejay! Just another thought: in case we are still short on reviewers, here are two more suggestions:
> 
> * raphaeldussin
> * JiaweiZhuang

Thank you, yes I am hoping to find one more reviewer before we move from "pre-review" to the "review" itself.

**Comment by isgiddy** [comment]
> 
Hi @elbeejay. This looks interesting and I'd be happy to learn more about this filtering technique and wider applications via the review process.

**Comment by elbeejay** [comment]
> > 
> 
> Hi @elbeejay. This looks interesting and I'd be happy to learn more about this filtering technique and wider applications via the review process.

Awesome, thanks!

**Comment by elbeejay** [comment]
@whedon add @isgiddy as reviewer

**Comment by whedon** [comment]
OK, @isgiddy is now a reviewer

**Comment by elbeejay** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3947.
