### ISSUE TITLE
[PRE REVIEW]: cffr: Generate Citation File Format Metadata for R Packages

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3899]
**Submitting author:** @dieghernan (<a href="http://orcid.org/0000-0001-8457-4658">Diego Hernangómez</a>)
**Repository:** <a href="https://github.com/ropensci/cffr" target ="_blank">https://github.com/ropensci/cffr</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewers:** @arfon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/af5b76a70be0a5f9d1117ac37e3c3ba7/status.svg)](https://joss.theoj.org/papers/af5b76a70be0a5f9d1117ac37e3c3ba7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/af5b76a70be0a5f9d1117ac37e3c3ba7"><img src="https://joss.theoj.org/papers/af5b76a70be0a5f9d1117ac37e3c3ba7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/af5b76a70be0a5f9d1117ac37e3c3ba7/status.svg)](https://joss.theoj.org/papers/af5b76a70be0a5f9d1117ac37e3c3ba7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dieghernan. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@dieghernan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (816.5 files/s, 138978.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                        18            394              0           5077
R                               35            690            902           2240
YAML                             8             94             37            329
JSON                             1              0              0            256
Rmd                              3            426            518            236
TeX                              1              3              0             32
-------------------------------------------------------------------------------
SUM:                            66           1607           1457           8170
-------------------------------------------------------------------------------


Statistical information for the repository '277b9aef7bca4098f7f54f82' was
gathered on 2021/11/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3899 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by dieghernan** [comment]
Hi @arfon , glad you are reviewing this. I guess you are already aware, but just in case the paper is in the [joss](https://github.com/ropensci/cffr/tree/joss) branch.

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/ZENODO.5529914 is OK
- 10.5281/zenodo.5171937 is OK
- 10.5281/zenodo.4748266 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03899/joss.03899/10.21105.joss.03899.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03899/joss.03899/10.21105.joss.03899.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@dieghernan - the fact that one of the DOIs has ZENODO in it while the others have zenodo looks a bit awkward - at some point if you are making changes, you might make this consistent

**Comment by dieghernan** [comment]
No problem, just let me know the best moment and I would change it

**Comment by danielskatz** [comment]
anytime would be fine

**Comment by dieghernan** [comment]
Done

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.5529914 is OK
- 10.5281/zenodo.5171937 is OK
- 10.5281/zenodo.4748266 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03899/joss.03899/10.21105.joss.03899.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03899/joss.03899/10.21105.joss.03899.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, @arfon is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3900.
