### ISSUE TITLE
[PRE REVIEW]: ResumableFunctions: C# sharp style generators for Julia.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#390]
**Submitting author:** @benlauwens (<a href="http://orcid.org/0000-0003-0761-6265">Ben Lauwens</a>)
**Repository:** <a href="https://github.com/BenLauwens/ResumableFunctions.jl.git" target ="_blank">https://github.com/BenLauwens/ResumableFunctions.jl.git</a>
**Version:** v0.1.0
**Editor:** @danielskatz
**Reviewer:** @gasagna

**Author instructions**

Thanks for submitting your paper to JOSS @benlauwens. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@benlauwens if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @danielskatz - the submitting author suggested you as an editor.

**Comment by danielskatz** [comment]
I have no experience with c# or julia, but I can try to edit this.

@BenLauwens - please let me know if you have reviewer suggestions.

**Comment by BenLauwens** [comment]
Hi @danielskatz

I propose three reviewers:
- Dr [Davide Lasagna ](davide.lasagna@soton.ac.uk): he knows Julia and he is interested to use `ResumableFunctions` to express complex iteration patterns
- Assoc Prof [Bart Janssens](Bart.janssens@rma.ac.be): he is a colleague who has developed `QML.jl` and needs the functionalities of `ResumableFunctions` to reduce the overhead of progress bar updates in a GUI
- [Jeffrey Sarnoff](jeffrey.sarnoff@gmail.com): during JuliaCon2016 he was hosting the session in which I presented an extension of `SimJulia`. He has developed several Julia package and knows the language and its tools very well

They are all familiar with Julia and the first two have a clear use case for `ResumableFunctions` that is complementary to my use case (process description in an event driven simulator).

Kind regards

Ben

**Comment by danielskatz** [comment]
@gasagna @barche @Jeffrey-Sarnoff - would one of you be willing to review this software paper for [JOSS](http://joss.theoj.org)?

We have some [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines) to let you know what we expect of a reviewer/review.

Reviews are done through github issues - once a reviewer is assigned, I will close this issue and open a review issue, that you will go through as you review the paper and the software.  An example is https://github.com/openjournals/joss-reviews/issues/357 (this paper was just accepted.)

**Comment by barche** [comment]
Hi,

I would be willing to review, but as Ben pointed out we are at the same university, so I think @gasagna or @Jeffrey-Sarnoff should have priority if they are available.

Kind regards,

Bart

**Comment by gasagna** [comment]
Hi, 

I will be very happy to review this paper. 

Best regards, 

Davide

**Comment by danielskatz** [comment]
Thanks very much @gasagna

**Comment by danielskatz** [comment]
@whendon assign @gasagna as reviewer

**Comment by danielskatz** [comment]
@whedon assign @gasagna as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gasagna

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/400. Feel free to close this issue now!
