### ISSUE TITLE
[PRE REVIEW]: PySS3: A new interpretable and simple machine learning model for text classification

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3906]
**Submitting author:** @sergioburdisso (<a href="http://orcid.org/0000-0002-7694-6834">Sergio Gastón Burdisso</a>)
**Repository:** <a href="https://github.com/sergioburdisso/pyss3" target ="_blank">https://github.com/sergioburdisso/pyss3</a>
**Version:** v0.6.4
**Editor:** @bmcfee
**Reviewers:** @hbaniecki, @kmichael08
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/872acc280f71e2a26e249d65dd399acd/status.svg)](https://joss.theoj.org/papers/872acc280f71e2a26e249d65dd399acd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/872acc280f71e2a26e249d65dd399acd"><img src="https://joss.theoj.org/papers/872acc280f71e2a26e249d65dd399acd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/872acc280f71e2a26e249d65dd399acd/status.svg)](https://joss.theoj.org/papers/872acc280f71e2a26e249d65dd399acd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @sergioburdisso. **Currently, there isn't an JOSS editor assigned** to your paper.

@sergioburdisso if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1642

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.35 s (193.9 files/s, 91315.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              6           1361            375           7369
Python                          10           1460           2144           5469
HTML                             5            429              6           4772
reStructuredText                20           1452           1207           1017
JavaScript                      10             85            193            897
Markdown                         6            208              0            392
Jupyter Notebook                 6              0           2668            276
TeX                              1             12              0            113
YAML                             2              8              5             46
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            68           5027           6606          20386
-------------------------------------------------------------------------------


Statistical information for the repository 'cc4994dc5d00d54aa9536cbb' was
gathered on 2021/11/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Florian Angermeir                1            19             19            0.20
Sergio Burdisso                202         14552           4147           99.80

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Florian Angermeir            18           94.7         16.4               22.22
Sergio Burdisso           10258           70.5         10.0                6.19
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1371/journal.pone.0168344 may be a valid DOI for title: Rumor detection over varying time windows
- 10.1016/j.eswa.2017.07.040 may be a valid DOI for title: Early detection of deception and aggressiveness using profile-based representations
- 10.1007/978-3-319-44564-9_3 may be a valid DOI for title: A test collection for research on depression and language use
- 10.1007/978-3-319-65813-1_30 may be a valid DOI for title: eRisk 2017: CLEF Lab on Early Risk Prediction on the Internet: Experimental foundations

INVALID DOIs

- https://doi.org/10.1016/j.eswa.2019.05.023 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.patrec.2020.07.001 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03906/joss.03906/10.21105.joss.03906.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03906/joss.03906/10.21105.joss.03906.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @sergioburdisso, we will use this issue to find and assign editor and reviewers. While we are doing that, could you resolve those issues with the DOIs in your references?

@bmcfee could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @bmcfee as editor

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by bmcfee** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by bmcfee** [comment]
@whedon assign @hbaniecki as reviewer

**Comment by whedon** [comment]
OK, @hbaniecki is now a reviewer

**Comment by bmcfee** [comment]
Note: @hbaniecki has agreed to review, but won't be available for another week or so.

**Comment by sergioburdisso** [comment]
Hi guys! thank you for consider my submission :)

> Hi @sergioburdisso, we will use this issue to find and assign editor and reviewers. While we are doing that, could you resolve those issues with the DOIs in your references?
> 
Hi! yes, I've just updated the DOIs and pushed the changes to the repository. :rocket: thank you for the suggestion.


> Note: @hbaniecki has agreed to review, but won't be available for another week or so.

Ok. No problem, so we will wait until @hbaniecki is available then :+1: 

Again, thank you guys for taking the time to process and reviewing this submission! :muscle:

**Comment by bmcfee** [comment]
@whedon add @kmichael08 as reviewer

**Comment by whedon** [comment]
OK, @kmichael08 is now a reviewer

**Comment by bmcfee** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3934.

**Comment by bmcfee** [comment]
I've opened up the review issue, but it may still be a little bit before our reviewers are available to get started on it.  This way it will at least be ready to go when they are.
