### ISSUE TITLE
[PRE REVIEW]: OpenCADD-KLIFS: A Python package to fetch kinase data from the KLIFS database

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3907]
**Submitting author:** @dominiquesydow (<a href="http://orcid.org/0000-0003-4205-8705">Dominique Sydow</a>)
**Repository:** <a href="https://github.com/volkamerlab/opencadd" target ="_blank">https://github.com/volkamerlab/opencadd</a>
**Version:** v1.0.0
**Editor:** @richardjgowers
**Reviewers:** @ojeda-e, @andrewtarzia, @mcs07
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8a382e79501e885a05cf34e0a34f2498/status.svg)](https://joss.theoj.org/papers/8a382e79501e885a05cf34e0a34f2498)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8a382e79501e885a05cf34e0a34f2498"><img src="https://joss.theoj.org/papers/8a382e79501e885a05cf34e0a34f2498/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8a382e79501e885a05cf34e0a34f2498/status.svg)](https://joss.theoj.org/papers/8a382e79501e885a05cf34e0a34f2498)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dominiquesydow. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @richardjgowers.

@dominiquesydow if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3907 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
Hi @dominiquesydow, it looks like your JOSS paper is not located in the repository correctly for our system to find. I think this may be because the paper is nested? Normally the paper is located in `paper/paper.md`.

@openjournals/dev can you give more-specific guidance here?

**Comment by kyleniemeyer** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by danielskatz** [comment]
@kyleniemeyer - I don't see a paper at all, in the tree or in a branch - JOSS should find it if it's in a directory. So maybe before an editor starts, we should make sure there is a paper added?

**Comment by kyleniemeyer** [comment]
@danielskatz the paper appears to be here: https://github.com/volkamerlab/opencadd/tree/master/papers/opencadd-klifs

**Comment by kyleniemeyer** [comment]
(@danielskatz that is what I meant about it being nested, it is at `papers/opencadd-klifs/paper.md`)

**Comment by danielskatz** [comment]
I see - whedon usually finds things like this - I wonder if the directory was called joss if that would help

**Comment by dominiquesydow** [comment]
Hi @kyleniemeyer and @danielskatz, 

Thank you for opening this pre-review!

I am sorry for the holdup caused by the nested folder structure; I assumed it will work, since the [Whedon paper review service](https://whedon.theoj.org/) can locate the paper:
- Paper repository address: https://github.com/volkamerlab/opencadd 
- Custom branch (optional): master

---

> @danielskatz the paper appears to be here: https://github.com/volkamerlab/opencadd/tree/master/papers/opencadd-klifs

That is correct.

I have moved the files to an un-nested `paper` folder on the `joss-paper` branch; https://github.com/volkamerlab/opencadd/pull/121. 
I suggest I merge that PR and we try again?

> I see - whedon usually finds things like this - I wonder if the directory was called joss if that would help

Alternatively, please let me know if you prefer that I try `paper/joss` (if I understand your suggestion correctly).

---

As a general question: Are published JOSS papers linked to a specific `paper.md` location or can authors move these files after publication to e.g. subdirectories?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3907 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3907 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@dominiquesydow Hmm, I'm really not sure what is going on. I can see the paper in `paper/paper.md` in the `joss-paper` branch, which should totally work. @openjournals/dev @arfon any ideas what is going on here?

Also, you can absolutely leave the paper in a branch that is never merged, or remove the paper after publication. We archive the paper itself and the software repository does not need to contain it after acceptance.

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3907 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3907 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
@dominiquesydow – apologies for the issues here. I've found the original issue (the repository address had a space in it which was confusing Whedon).

The paper currently won't compile as there are two `paper.md` files present. (`/papers/opencadd-klifs/paper.md`, `/paper/paper.md`). Please delete one of these (either is fine).

**Comment by dominiquesydow** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03907/joss.03907/10.21105.joss.03907.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03907/joss.03907/10.21105.joss.03907.pdf) :page_facing_up: :point_left:

**Comment by dominiquesydow** [comment]
Hi @arfon, my apologies for the space in the URL. I removed the duplicated `paper.md` file - Whedon is successful now. 
Thanks for your help!

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 730

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.38 s (294.8 files/s, 112102.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          61           2177           5339           6106
Jupyter Notebook                 8              0          26158            577
Markdown                        13            130              0            381
SVG                              1              1              1            307
YAML                             8             49             26            300
reStructuredText                12            201            192            231
TeX                              1             15              0            137
diff                             3             23             51             99
Bourne Shell                     3              5              2             32
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           112           2613          31776           8207
-------------------------------------------------------------------------------


Statistical information for the repository '4e1566fa824955118133c535' was
gathered on 2021/11/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Annie Pham                       6           353             37            0.84
Dennis Köser                    16           669            250            1.98
Enes                            12           765            330            2.36
Jaime RGP                       34          4379            919           11.40
Jaime Rodríguez-Guer            29           839            876            3.69
Unknown                        398         20494          13741           73.65
anniepham7                       2            78             27            0.23
dominiquesydow                  13          2403            290            5.79
pipaj97                          3            28              6            0.07

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Annie Pham                   20            5.7         18.1               20.00
Dennis Köser                396           59.2         18.4                4.29
Enes                        135           17.6         18.5                8.89
Jaime RGP                  3321           75.8          4.6               16.83
Jaime Rodríguez-Guer        681           81.2         17.4                9.10
Julian Pipart                23          100.0          2.3               26.09
Unknown                    9007           43.9         11.3               11.89
anniepham7                   45           57.7         18.8                4.44
```

**Comment by richardjgowers** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@andrewtarzia @mcs07 @ojeda-e would any/all of you be available to review this?

**Comment by mcs07** [comment]
Yes I'd be happy to review!

**Comment by andrewtarzia** [comment]
Happy to - just confirming it is just that module of the code base?

**Comment by ojeda-e** [comment]
I'm in!

**Comment by richardjgowers** [comment]
@whedon add @ojeda-e as reviewer

**Comment by whedon** [comment]
OK, @ojeda-e is now a reviewer

**Comment by richardjgowers** [comment]
@whedon add @andrewtarzia as reviewer

**Comment by whedon** [comment]
OK, @andrewtarzia is now a reviewer

**Comment by richardjgowers** [comment]
@whedon add @mcs07 as reviewer

**Comment by whedon** [comment]
OK, @mcs07 is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3951.

**Comment by dominiquesydow** [comment]
> @dominiquesydow – apologies for the issues here. I've found the original issue (the repository address had a space in it which was confusing Whedon).
> 
> The paper currently won't compile as there are two `paper.md` files present. (`/papers/opencadd-klifs/paper.md`, `/paper/paper.md`). Please delete one of these (either is fine).

Hi @afron, my apologies for circling back to the previous Whedon issue. We may have a same problem again in the review PR:
https://github.com/openjournals/joss-reviews/issues/3951

We have now on `opencadd`'s master the following files (FYI the merged PR https://github.com/volkamerlab/opencadd/pull/121):
```
├── paper
│   ├── opencadd_klifs_toc.png
│   ├── paper.bib
│   └── paper.md
├── papers
│   └── opencadd-superposition
│       └── paper-superposer.md
```
Generating the PDF from the `master` branch does not work (see the fail in the review PR [here](https://github.com/openjournals/joss-reviews/issues/3951#issuecomment-987850134)).

We have only one `paper.md` file  - is this again the URL-space problem?

**Comment by arfon** [comment]
>  is this again the URL-space problem?

Yes, sorry. I forgot to fix this in the database so the problem appeared again in the review issue. Should be fixed now.

**Comment by dominiquesydow** [comment]
Thank you, @arfon!
