### ISSUE TITLE
[PRE REVIEW]: limHaloPT: A numerical Package for Accurate Modelling of Line Intensity Power spectrum

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3908]
**Submitting author:** @amoradinejad (<a href="http://orcid.org/0000-0001-8841-9989">Azadeh Moradinezhad Dizgah</a>)
**Repository:** <a href="https://github.com/amoradinejad/limHaloPT" target ="_blank">https://github.com/amoradinejad/limHaloPT</a>
**Version:** v1.0.0
**Editor:** @eloisabentivegna
**Reviewers:** @ziotom78, @abhimaniyar
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/dde5dbbc5317090aa593124dec601c08/status.svg)](https://joss.theoj.org/papers/dde5dbbc5317090aa593124dec601c08)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dde5dbbc5317090aa593124dec601c08"><img src="https://joss.theoj.org/papers/dde5dbbc5317090aa593124dec601c08/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dde5dbbc5317090aa593124dec601c08/status.svg)](https://joss.theoj.org/papers/dde5dbbc5317090aa593124dec601c08)
```

**Author instructions**

Thanks for submitting your paper to JOSS @amoradinejad. **Currently, there isn't an JOSS editor assigned** to your paper.

@amoradinejad if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 816

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1475-7516/2016/07/028 is OK
- 10.1088/1475-7516/2015/02/013 is OK
- 10.1088/1475-7516/2018/05/019 is OK
- 10.1016/j.ascom.2015.05.005 is OK
- 10.1088/1475-7516/2011/07/034 is OK
- 10.3847/1538-3881/aadae0 is OK
- 10.1046/j.1365-8711.2000.03715.x is OK
- 10.1016/S0370-1573(02)00276-4 is OK
- 10.1088/1475-7516/2012/07/051 is OK
- 10.1007/JHEP09(2012)082 is OK
- 10.1103/PhysRevD.96.083528 is OK

MISSING DOIs

- 10.1088/1475-7516/2021/05/067 may be a valid DOI for title: Astrophysics & Cosmology from Line Intensity Mapping vs Galaxy Surveys

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03908/joss.03908/10.21105.joss.03908.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03908/joss.03908/10.21105.joss.03908.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 816

**Comment by kyleniemeyer** [comment]
For some reason @whedon is not reporting the repository/code statistics completely, I am not sure why. Also, the paper does have a "Statement of Need" section, it is just part of a "Scientific Context and Statement of Need" section title.

@amoradinejad while we are getting started, can you resolve the reference issues pointed out above?

**Comment by kyleniemeyer** [comment]
@amoradinejad I also noticed that the README describes the software documentation as still under development. For us to proceed with the review here, we expect sufficient documentation, as described in our [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#documentation). 

I'm also not seeing anything in the software repository that looks like tests. Are there any tests or example cases built in that would enable reviewers to evaluate that the software is working correctly?

**Comment by arfon** [comment]
> For some reason @whedon is not reporting the repository/code statistics completely, I am not sure why. Also, the paper does have a "Statement of Need" section, it is just part of a "Scientific Context and Statement of Need" section title.

@kyleniemeyer – I ran `cloc` locally:

```
github.com/AlDanial/cloc v 1.86  T=6.31 s (55.5 files/s, 257664.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    41           1561           1359        1578221
HTML                           133            894            240          19280
TeX                             32           1054            323           8855
C                               14           1556           1969           4658
JavaScript                     116            159            162           2837
CSS                              4            365             51           1833
XML                              1              6              8            226
SVG                              3              1              1            129
Markdown                         3             53              0             94
make                             2              7              0             49
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                           350           5657           4117        1616200
-------------------------------------------------------------------------------
```

**Comment by amoradinejad** [comment]
I resolved the reference issue, listed below.  

MISSING DOIs

- 10.1088/1475-7516/2021/05/067 may be a valid DOI for title: Astrophysics & Cosmology from Line Intensity Mapping vs Galaxy Surveys

INVALID DOIs

Best, 
Azadeh Moradinezhad

**Comment by amoradinejad** [comment]
Hi, 

I address the two questions in-line below. 

> On 12 Nov 2021, at 19:35, Kyle Niemeyer ***@***.***> wrote:
> 
> 
> @amoradinejad <https://github.com/amoradinejad> I also noticed that the README describes the software documentation as still under development. For us to proceed with the review here, we expect sufficient documentation, as described in our review criteria <https://joss.readthedocs.io/en/latest/review_criteria.html#documentation>.
> 
> 

Documentation is complete, since only two functions were missing comments. I updated those comments. The full documentation was generated by Oxygen, and is found on the url https://amoradinejad.github.io/limHaloPT/html/index.html <https://amoradinejad.github.io/limHaloPT/html/index.html> . 


> I'm also not seeing anything in the software repository that looks like tests. Are there any tests or example cases built in that would enable reviewers to evaluate that the software is working correctly?
> 
There is no separate test file. However, the example tests for function calls for some of the main functions , which compute the line signal are given in main.c module.  



Please let me know if further information was needed. 


Best,
Azadeh Moradinezhad

**Comment by kyleniemeyer** [comment]
@amoradinejad thank you.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03908/joss.03908/10.21105.joss.03908.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03908/joss.03908/10.21105.joss.03908.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @eloisabentivegna as editor

@eloisabentivegna can you edit this submission?

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by amoradinejad** [comment]
Hi, 

Since my scientific publications are cited with my full last name, Moradinezhad Dizgah, may I ask yo have the citation label (footnote on page 1) to “Moradinezhad Dizgah et al” instead of “Dizgah et al” ?

Thank you,
Azadeh Moradinezhad

**Comment by eloisabentivegna** [comment]
> @eloisabentivegna can you edit this submission?

Sure!

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by kyleniemeyer** [comment]
> Hi, Since my scientific publications are cited with my full last name, Moradinezhad Dizgah, may I ask yo have the citation label (footnote on page 1) to “Moradinezhad Dizgah et al” instead of “Dizgah et al” ? Thank you, Azadeh Moradinezhad
> […](#)

This may be something that @arfon has to do manually when we get to the publication stage.

**Comment by arfon** [comment]
> This may be something that @arfon has to do manually when we get to the publication stage.

Yes, please mention this at the end of the review process @amoradinejad – we have to manually fix this when the paper is ready to be published.

**Comment by eloisabentivegna** [comment]
Update: I am still trying to identify reviewers for this submission. @amoradinejad, you're welcome to make suggestions!

**Comment by eloisabentivegna** [comment]
Further update: @ziotom78 has accepted to review the paper (thanks!), so long as a second reviewer with deeper expertise in line intensity mapping (or cosmological power spectrum analysis in general) addresses these aspects. @sgeorge91, @changhoonhahn, @alaingdl, can any of you help here?

**Comment by eloisabentivegna** [comment]
Welcome to 2022! @sgeorge91, @changhoonhahn, @alaingdl, could you let us know if you're available to review this submission?

**Comment by alaingdl** [comment]
I am very sorry but it is really too far from my limited range of competence or expertise. 

Do you have consider one of the authors in the citation list as a referee ?

**Comment by eloisabentivegna** [comment]
@alaingdl, thanks for the update and the suggestion.

**Comment by sgeorge91** [comment]
Hi!
Sorry about the late reply. I had a look at the article draft and realized
I'm super out of my depth here too. I can ask around a bit and see if I can
suggest someone more competent in case you don't find a second reviewer.
Warm regards,
Sandip

**Comment by alaingdl** [comment]
I ask around and I got few suggestions, colleagues working on [CII] line at 158 um. I would prefer to send the names/contact by email. (I don't know whether they have account here)

**Comment by eloisabentivegna** [comment]
Thanks, @alaingdl. I have sent you an email to get the contacts you found.

**Comment by eloisabentivegna** [comment]
Dear @amoradinejad, thanks for your message. I have been looking for a second reviewer who is fully within the domain of your submission, but have received several declinations. Please feel free to suggest reviewers!

**Comment by eloisabentivegna** [comment]
Update: I have possibly identified a second reviewer, who will confirm within a few days whether they have capacity to carry out a review shortly.

**Comment by eloisabentivegna** [comment]
I am happy to share that @abhimaniyar has agreed to review this submission. We are now ready to start. 🎉

**Comment by amoradinejad** [comment]
Great, thank you for the information. 

Best,
Azadeh Moradinezhad Dizgah

**Comment by eloisabentivegna** [comment]
@whedon assign @ziotom78 as reviewer

**Comment by whedon** [comment]
OK, @ziotom78 is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @abhimaniyar as reviewer

**Comment by whedon** [comment]
OK, @abhimaniyar is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4173.
