### ISSUE TITLE
[PRE REVIEW]: Cacatoo: building, exploring, and sharing spatially structured models of biological systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3909]
**Submitting author:** @bramvandijk88 (<a href="http://orcid.org/0000-0002-6330-6934">Bram van Dijk</a>)
**Repository:** <a href="https://github.com/bramvandijk88/cacatoo" target ="_blank">https://github.com/bramvandijk88/cacatoo</a>
**Version:** v1.0.0
**Editor:** @Bisaloo
**Reviewers:** @emilydolson, @TimKam
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/91fee0cc4c10d0d7696b78819072317a/status.svg)](https://joss.theoj.org/papers/91fee0cc4c10d0d7696b78819072317a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/91fee0cc4c10d0d7696b78819072317a"><img src="https://joss.theoj.org/papers/91fee0cc4c10d0d7696b78819072317a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/91fee0cc4c10d0d7696b78819072317a/status.svg)](https://joss.theoj.org/papers/91fee0cc4c10d0d7696b78819072317a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @bramvandijk88. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sbenthall.

@bramvandijk88 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 629

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/bioinformatics/btt772 may be a valid DOI for title: Morpheus: a user-friendly modeling environment for multiscale and multicellular systems biology
- 10.1101/2021.05.29.446280 may be a valid DOI for title: Transposable elements drive the evolution of genome streamlining
- 10.1016/j.zool.2019.02.007 may be a valid DOI for title: Resolving structure and function of metaorganisms through a holistic framework combining reductionist and integrative approaches
- 10.1098/rstb.2019.0248 may be a valid DOI for title: Toward a dynamical understanding of microbial communities
- 10.1101/053405 may be a valid DOI for title: Excess of mutational jackpot events in growing populations due to gene surfing
- 10.3389/fmicb.2015.00728 may be a valid DOI for title: The pan-genome as a shared genomic resource: mutual cheating, cooperation and the black queen hypothesis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03909/joss.03909/10.21105.joss.03909.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03909/joss.03909/10.21105.joss.03909.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=9.33 s (561.5 files/s, 71138.8 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
JavaScript                            4222          56563          79269         315324
JSON                                   377            112              0          50807
Markdown                               352          14318              2          39957
HTML                                    90          22468            318          19790
SVG                                     12              0              1          16734
TypeScript                             106            239          29152          10712
CSS                                     14            399             81           2229
XML                                      5            241             13           2074
diff                                     2             97            280           1150
YAML                                    32             18             10            489
Windows Module Definition                5             83              0            451
CoffeeScript                             7             23             11             92
make                                     5             34             17             80
Bourne Shell                             5             23              9             76
TeX                                      1              7              0             68
Bourne Again Shell                       2             11              1             43
Nix                                      1              1              0             19
ERB                                      1              1              0             18
Lisp                                     1              0              0              6
---------------------------------------------------------------------------------------
SUM:                                  5240          94638         109164         460119
---------------------------------------------------------------------------------------


Statistical information for the repository 'e71be3bef725cf1cef313253' was
gathered on 2021/11/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bram van Dijk                   24          3508           1172            0.87
bramvandijk88                  149        490957          16525           94.09
jeroenmeijer                     2            26             24            0.01
root                             4         24015           3150            5.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
bramvandijk88            472856           96.3          1.4               17.84
jeroenmeijer                  4           15.4          1.3                0.00
```

**Comment by kyleniemeyer** [comment]
Hi @bramvandijk88, as we are getting started in this pre-review issue, could you fix those missing DOIs in the references?

@Bisaloo could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @Bisaloo as editor

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by bramvandijk88** [comment]
> Hi @bramvandijk88, as we are getting started in this pre-review issue, could you fix those missing DOIs in the references?
> 
> @Bisaloo could you edit this submission?

Absolutely, I'll get on it. 

On a seperate note, it's hard to find reviewers for this I can imagine. Not a lot of javascript programmers are in your list. In any case, these usernames seemed somewhat appropriate for my submission:

emilydolson
kavir1698
jamesdamillington
TimKam

**Comment by Bisaloo** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Bisaloo

**Comment by Bisaloo** [comment]
:wave: :wave: @kyleniemeyer @bramvandijk88, yes I can edit this issue.

Before we can get properly started, I notice that whedon severely overestimates the number of code lines. Whedon uses GitHub's linguist to detect the relevant files & languages. Could you edit your `.gitattributes` with the relevant `linguist-` attributes ([examples](https://stackoverflow.com/a/43142088)) so that auto-generated files, external libraries, etc. are excluded from the line count please? 

Should the `node_modules` folder be committed anyways? The `package-lock.json` should be enough.

**Comment by bramvandijk88** [comment]
> 👋 👋 @kyleniemeyer @bramvandijk88, yes I can edit this issue.

Thanks for editing. 

> Before we can get properly started, I notice that whedon severely overestimates the number of code lines. Whedon uses GitHub's linguist to detect the relevant files & languages. Could you edit your `.gitattributes` with the relevant `linguist-` attributes ([examples](https://stackoverflow.com/a/43142088)) so that auto-generated files, external libraries, etc. are excluded from the line count please?
> 
> Should the `node_modules` folder be committed anyways? The `package-lock.json` should be enough, shouldn't it?

Yeah, good point. I didn't even notice I had added the node modules, so I'll get on it. 

> I couldn't find good documentation on how to use linguist so if this is not clear, please let me know and I'll try to submit a PR myself.

I'll let you know when I've updated it, and let's see.

**Comment by bramvandijk88** [comment]
@Bisaloo I have 

i) removed node modules from the repository and added it to .gitignore
ii) added a .gitattributes file that excludes certain files from the documentation that aren't part of the core code, or are duplicated files for the github.io page. 

Let me know if this resolves the line count issues.

**Comment by Bisaloo** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 629

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.28 s (404.9 files/s, 269703.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            67          22319            315          19029
SVG                              9              0              0          16611
JavaScript                      27           1465           3095           9487
JSON                             1              0              0           1862
CSS                              6            199             68           1230
TeX                              1              8              0             75
Markdown                         2             32              0             64
Bourne Shell                     1             17              9             54
-------------------------------------------------------------------------------
SUM:                           114          24040           3487          48412
-------------------------------------------------------------------------------


Statistical information for the repository 'f533dcfef3d7a2ba52f9e876' was
gathered on 2021/11/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bram van Dijk                   24          3508           1172            0.47
bramvandijk88                  151        490983         472651           96.80
jeroenmeijer                     2            26             24            0.01
root                             4         24015           3150            2.73

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
bramvandijk88             16756            3.4          3.3               23.10
jeroenmeijer                  4           15.4          1.6                0.00
```

**Comment by Bisaloo** [comment]
Thanks for your quick answer! I believe a couple of other changes are necessary:

- `dist/` should be `.gitignore`d since users will generate it from the contents of `src/`
- `lib/` contents are third party dependencies, right? If so, they should be marked as `linguist-vendored` in `.gitignore`

Please let me know if I misunderstand something or if you disagree.

I believe we should be good to go after this :+1:.

**Comment by Bisaloo** [comment]
Regarding reviewers, we are not limited the google spreadsheet. The list contains people who agreed to review for JOSS but if you know potential good reviewers who are not in the list, feel free to suggest them as well.

**Comment by bramvandijk88** [comment]
> Thanks for your quick answer! I believe a couple of other changes are necessary:
> 
> * `dist/` should be `.gitignore`d since users will generate it from the contents of `src/`

No, I don't actually want to do that. I'm uploading the compiled library to the repository so that users can immediately dive into the examples without having to install anything. The zero-install is one of the selling points of this package ;D

> * `lib/` contents are third party dependencies, right? If so, they should be marked as `linguist-vendored` in `.gitignore`

Yes, thanks, I've added it. 

> 
> Please let me know if I misunderstand something or if you disagree.
> 
> I believe we should be good to go after this 👍.

Alright, good. The problem with finding reviewers is that this is a really niche library (javascript is not very common, and the type of models are also quite niche), so I don't know who to suggest except my close colleagues, which is clearly a conflict of interest...

**Comment by Bisaloo** [comment]
Okay, fair enough. I had a look at the jsfiddle examples and it looks very nice.

I would still recommend you add `linguist-generated` to `dist/` so it doesn't show up in diff but it's up to you. 

I'll start looking into reviewers.

**Comment by bramvandijk88** [comment]
> I would still recommend you add `linguist-generated` to `dist/` so it doesn't show up in diff but it's up to you.

Actually, yes, I'll do that.

**Comment by Bisaloo** [comment]
:wave: :wave: @emilydolson @TimKam, based on the keywords and programming languages in listed when you volunteered to review for JOSS, you would be very good candidates to review this [javascript library](https://github.com/bramvandijk88/cacatoo) and [associated paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03909/joss.03909/10.21105.joss.03909.pdf). Would you please be available to review them?

**Comment by emilydolson** [comment]
Yes! I would be happy to!

**Comment by Bisaloo** [comment]
Awesome, thank for your quick answer :100:. Once I find the 2nd reviewer, I'll open the review thread and explain how it works. 

If you are already curious, all the information is summarized in our documentation at https://joss.readthedocs.io/en/latest/.

**Comment by Bisaloo** [comment]
@whedon add @emilydolson as reviewer

**Comment by whedon** [comment]
OK, @emilydolson is now a reviewer

**Comment by TimKam** [comment]
I still need to review another JOSS paper (2nd round), but in roughly a week, I should be available. I had a quick look and I'd look forward to reviewing this project.

**Comment by Bisaloo** [comment]
Are you sure you're okay with reviewing two papers back to back? I can look for other reviewers.

If you think it's fine, we can easily wait one week.

**Comment by TimKam** [comment]
Should be okay, as I am done with the other review by now.

**Comment by Bisaloo** [comment]
@whedon add @TimKam as reviewer

**Comment by whedon** [comment]
OK, @TimKam is now a reviewer

**Comment by Bisaloo** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3948.
