### ISSUE TITLE
[PRE REVIEW]: pyGPGO: Bayesian Optimization for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#391]
**Submitting author:** @hawk31 (<a href="http://orcid.org/0000-0002-5335-7834">Jiménez J.</a>)
**Repository:** <a href="https://github.com/hawk31/pyGPGO" target ="_blank">https://github.com/hawk31/pyGPGO</a>
**Version:** 0.3.0.dev1
**Editor:** @arfon
**Reviewer:** @dfm

**Author instructions**

Thanks for submitting your paper to JOSS @hawk31. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@hawk31 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @jakevdp - the submitting author suggested you as an editor.

**Comment by arfon** [comment]
@openjournals/joss-editors - would anyone else be willing to edit this submission?

**Comment by hawk31** [comment]
It's been more than a month since I submitted this to JOSS. Does it usually take this long?

**Comment by arfon** [comment]
> It's been more than a month since I submitted this to JOSS. Does it usually take this long?

@hawk31 - we've got a pretty big backlog of submissions right now. We'll try and get to this soon.

**Comment by labarba** [comment]
Occasionally, when an editor is flagged but they are impossibly busy, we don't get a quick reply and there is a delay. But it is not usual. If you might suggest another editor, we'll try again.

**Comment by hawk31** [comment]
Can I suggest @arokem as a new reviewer?

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@dfm - would you be willing to review this submission for JOSS?

**Comment by dfm** [comment]
Sure!

**Comment by arfon** [comment]
@whedon assign @dfm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dfm

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/431. Feel free to close this issue now!

**Comment by arfon** [comment]
Thanks @dfm - see you over in #431 for the actual review.
