### ISSUE TITLE
[PRE REVIEW]: medoutcon: Nonparametric efficient causal mediation analysis with machine learning in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3911]
**Submitting author:** @nhejazi (<a href="http://orcid.org/0000-0002-7127-2789">Nima Hejazi</a>)
**Repository:** <a href="https://github.com/nhejazi/medoutcon" target ="_blank">https://github.com/nhejazi/medoutcon</a>
**Version:** v0.1.5
**Editor:** @mikldk
**Reviewers:** @erikcs, @rrrlw
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/36b2d7b95d977fa506aed40a1dd2294a/status.svg)](https://joss.theoj.org/papers/36b2d7b95d977fa506aed40a1dd2294a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/36b2d7b95d977fa506aed40a1dd2294a"><img src="https://joss.theoj.org/papers/36b2d7b95d977fa506aed40a1dd2294a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/36b2d7b95d977fa506aed40a1dd2294a/status.svg)](https://joss.theoj.org/papers/36b2d7b95d977fa506aed40a1dd2294a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nhejazi. **Currently, there isn't an JOSS editor assigned** to your paper.

@nhejazi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1810

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (910.1 files/s, 185350.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            25           1155            319           4217
R                               11            260            790           1732
Markdown                         4            129              0            560
CSS                              3             99             48            428
TeX                              1             40              0            398
JavaScript                       3             64             32            256
Rmd                              2            109            443            144
YAML                             4             13              0             71
XML                              1              0              0             57
make                             1              9              0             20
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            56           1878           1633           7894
-------------------------------------------------------------------------------


Statistical information for the repository 'd68110cbeddd98003c0932f4' was
gathered on 2021/11/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nima Hejazi                      5           716            364          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nima Hejazi                 352           49.2          0.2                9.09
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/biomet/asaa085 is OK
- 10.1111/rssb.12362 is OK
- 10.5281/zenodo.1342293 is OK
- 10.1111/ectj.12097 is OK
- 10.1515/jci-2020-0018 is OK
- 10.1214/12-AOS990 is OK
- 10.2202/1557-4679.1361 is OK
- 10.21105/joss.00512 is OK
- 10.5281/zenodo.835602 is OK
- 10.1111/biom.13375 is OK
- 10.1111/add.15377 is OK

MISSING DOIs

- 10.1007/978-3-319-65304-4_14 may be a valid DOI for title: Stochastic Treatment Regimes
- 10.1111/j.1541-0420.2011.01685.x may be a valid DOI for title: Population intervention causal effects based on stochastic interventions
- 10.1515/jci-2016-0006 may be a valid DOI for title: Longitudinal mediation analysis with time-varying mediators and exposures, with application to survival outcomes
- 10.1097/ede.0000000000000034 may be a valid DOI for title: Effect decomposition in the presence of an exposure-induced mediator-outcome confounder
- 10.1515/em-2017-0007 may be a valid DOI for title: Robust and flexible estimation of stochastic mediation effects: a proposed method and example in a randomized trial setting
- 10.1007/978-1-4612-5769-1 may be a valid DOI for title: Contributions to a general asymptotic statistical theory
- 10.1007/978-1-4419-9782-1_27 may be a valid DOI for title: Cross-validated targeted minimum-loss-based estimation
- 10.1214/aos/1176350609 may be a valid DOI for title: Consistent estimation of the influence function of locally asymptotically linear estimators
- 10.1097/00001648-199203000-00013 may be a valid DOI for title: Identifiability and exchangeability for direct and indirect effects
- 10.1007/978-1-4419-9782-1_27 may be a valid DOI for title: Cross-validated targeted minimum-loss-based estimation
- 10.1257/aer.p20171038 may be a valid DOI for title: Double/debiased/neyman machine learning of treatment effects
- 10.1007/978-3-319-59626-6_5 may be a valid DOI for title: The method of path coefficients
- 10.4324/9780203994627 may be a valid DOI for title: The Logic of Scientific Discovery
- 10.1097/01.ede.0000208475.99429.2d may be a valid DOI for title: Estimation of direct causal effects

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03911/joss.03911/10.21105.joss.03911.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03911/joss.03911/10.21105.joss.03911.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @nhejazi, we will use this pre-review issue to get things started, by assigning an editor and finding reviewers. (Any suggestions you have for the latter would certainly be appreciated). In the meantime, could you work on resolving those DOI issues in your references?

@jmschrei could you edit this one?

**Comment by kyleniemeyer** [comment]
@whedon invite @jmschrei as editor

**Comment by whedon** [comment]
@jmschrei has been invited to edit this submission.

**Comment by jmschrei** [comment]
Hey @kyleniemeyer. I actually don't know R at all or the R ecosystem so I may not be the best editor here.

**Comment by kyleniemeyer** [comment]
@jmschrei ok, I will see if I can find someone else. But, I will say that it's usually less important for the editor to be an expert on the language (vs. the domain) and much more important that the reviewers are.

**Comment by kyleniemeyer** [comment]
@whedon invite @mikldk editor

@mikldk could you edit this one?

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon invite @mikldk as editor

@mikldk could you edit this one?

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@nhejazi - thank you for the submission.

Do you have any suggestions for reviewers ([here](https://bit.ly/joss-reviewers) is a list of potential reviewers)?

**Comment by nhejazi** [comment]
Thanks for editing this submission @mikldk. The ideal reviewer would have a working knowledge of R and some familiarity with causal inference and machine learning. Perhaps someone (or a few) among @jjharden, @csinva, @tedinburgh, @mariacuellar, and @tgerke might have time to review this?

**Comment by mikldk** [comment]
> Thanks for editing this submission @mikldk. The ideal reviewer would have a working knowledge of R and some familiarity with causal inference and machine learning. Perhaps someone (or a few) among jjharden, csinva, tedinburgh, mariacuellar, and tgerke might have time to review this?

Thanks. I edited your comment (removed the tags).

**Comment by mikldk** [comment]
@jjharden, @csinva: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by jjharden** [comment]
I am sorry, but I am at my capacity for reviews at the moment.

**Comment by mikldk** [comment]
@tedinburgh, @mariacuellar: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by tedinburgh** [comment]
It looks very interesting, but I'm also unable to do fit this review in I'm afraid. Apologies and best of luck!

**Comment by mariacuellar** [comment]
I can't do it either. Thanksgiving is a bad time for me.

But have you tried Brian Vegetabile from RAND? He would be a great
reviewer: ***@***.***

**Comment by mikldk** [comment]
@csinva, @tgerke: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@nhejazi Can you maybe suggest a few more reviewers?

**Comment by nhejazi** [comment]
perhaps a few folks among erikcs, klmedeiros, joethorley, rrrlw, carpenitoThomas, Larsvanderlaan, rachaelvp, ttriche would be willing to co-review? it'd be much appreciated if you're able to spare the time.

**Comment by bvegetabile** [comment]
Hi all, I'm sorry for the delay in response.  I'm not used to getting article reviews through Github and thought the initial request was spam.  What is the timeline for the review?  I have a lot going on through the holidays (I'm an AE for an applied stats journal and have a few manuscripts on my plate already).

**Comment by mikldk** [comment]
@erikcs, @klmedeiros, @joethorley: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
> Hi all, I'm sorry for the delay in response. I'm not used to getting article reviews through Github and thought the initial request was spam. What is the timeline for the review? I have a lot going on through the holidays (I'm an AE for an applied stats journal and have a few manuscripts on my plate already).

Thanks, I'll keep you in mind. I would prefer to finished this off before the holidays.

**Comment by mikldk** [comment]
@erikcs, @klmedeiros, @joethorley: Would you be interested in reviewing this submission to The Journal of Open Source Software? Reviews are open and based on a checklist. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. If you have any questions or concerns please let me know.

**Comment by erikcs** [comment]
I'm happy to help out with a review - I should be able to get it done by early December.

**Comment by joethorley** [comment]
@mikldk - Machine learning isn't really my thing - please feel free to send me Bayesian software tho

**Comment by mikldk** [comment]
@whedon assign @erikcs as reviewer

**Comment by whedon** [comment]
OK, @erikcs is now a reviewer

**Comment by carpenitoThomas** [comment]
@mikldk I cannot in good faith review this submission as one of the authors (Mark J. van der Laan) was my thesis advisor. Would love to be considered for future software regarding missing data, though!

**Comment by rrrlw** [comment]
@mikldk I have no expertise in the topic and, thus, would not be useful in reviewing that aspect of the submission. However, I would be willing to review the R package itself (documentation, etc.) if another reviewer who is an expert in this area would be willing to evaluate the functionality/validity.

I can start the review as early as 13-Dec-2021 (1 week from today). Let me know if this works, happy to help if it does!

**Comment by nhejazi** [comment]
Just to add a bit of background, @rrrlw and @mikldk, the statistical methodology need not be the subject of the review (though comments are welcome), since this package is an implementation that accompanied work that has already been peer reviewed and published (https://doi.org/10.1093/biomet/asaa085). The primary purpose of this submission is a review of the software.

**Comment by mikldk** [comment]
@whedon add @rrrlw as reviewer

**Comment by whedon** [comment]
OK, @rrrlw is now a reviewer

**Comment by mikldk** [comment]
@rrrlw: As @nhejazi mentions it is perfectly fine to review the package itself, so I have added you as a reviewer. Thanks.

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3979.
