### ISSUE TITLE
[PRE REVIEW]: WaveletsExt.jl: Extending the boundaries of wavelets in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3912]
**Submitting author:** @ShozenD (<a href="http://orcid.org/0000-0001-5575-641X">Shozen Dan</a>)
**Repository:** <a href="https://github.com/UCD4IDS/WaveletsExt.jl" target ="_blank">https://github.com/UCD4IDS/WaveletsExt.jl</a>
**Version:** v0.1.10
**Editor:** @bmcfee
**Reviewers:** @lostanlen, @malmaud
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/af5f6558736b9c3ec2bd3cf36b0cdf40/status.svg)](https://joss.theoj.org/papers/af5f6558736b9c3ec2bd3cf36b0cdf40)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/af5f6558736b9c3ec2bd3cf36b0cdf40"><img src="https://joss.theoj.org/papers/af5f6558736b9c3ec2bd3cf36b0cdf40/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/af5f6558736b9c3ec2bd3cf36b0cdf40/status.svg)](https://joss.theoj.org/papers/af5f6558736b9c3ec2bd3cf36b0cdf40)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ShozenD. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @bmcfee.

@ShozenD if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1310

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (925.9 files/s, 197189.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           30           1571           1338           7516
Markdown                        18            177              0            893
TeX                              1             17              0            244
YAML                             4              0              1            117
TOML                             3              4              0             49
-------------------------------------------------------------------------------
SUM:                            56           1769           1339           8819
-------------------------------------------------------------------------------


Statistical information for the repository '8eb3153f692ac3a79f4a79b4' was
gathered on 2021/11/12.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF01250288 is OK
- 10.1007/978-1-4612-2544-7_17 is OK
- 10.1109/78.258102 is OK
- 10.1109/ICASSP.1995.480422 is OK
- 10.1093/biomet/81.3.425 is OK
- 10.2307/2291512 is OK
- 10.1109/TSIPN.2016.2632039 is OK
- 10.1137/1.9781611970104 is OK
- 10.1016/B978-0-12-374370-1.50001-9 is OK
- 10.1201/9781439863619 is OK
- 10.1007/978-1-4612-2544-7_5 is OK
- 10.1016/S0031-3203(00)00116-3 is OK
- 10.1016/S0031-3203(02)00019-5 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03912/joss.03912/10.21105.joss.03912.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03912/joss.03912/10.21105.joss.03912.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @bmcfee and @faroit, would one of you be able to edit this one?

**Comment by bmcfee** [comment]
Sure, I can do this one.

**Comment by kyleniemeyer** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by bmcfee** [comment]
@whedon add @lostanlen as reviewer

**Comment by whedon** [comment]
OK, @lostanlen is now a reviewer

**Comment by bmcfee** [comment]
@whedon add @malmaud as reviewer

**Comment by whedon** [comment]
OK, @malmaud is now a reviewer

**Comment by bmcfee** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3937.
