### ISSUE TITLE
[REVIEW]: CR-Sparse: Hardware accelerated functional algorithms for sparse signal processing in Python using JAX

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3917]
**Submitting author:** @shailesh1729 (<a href="http://orcid.org/0000-0003-2217-4768">Shailesh Kumar</a>)
**Repository:** <a href="https://github.com/carnotresearch/cr-sparse" target ="_blank">https://github.com/carnotresearch/cr-sparse</a>
**Version:** v0.2.2
**Editor:** @pdebuyl
**Reviewer:** @Saran-nns, @mirca
**Archive:** <a href="https://doi.org/10.5281/zenodo.5749792" target="_blank">10.5281/zenodo.5749792</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ebd4e5ca27a5db705b1dc382b64e0bed/status.svg)](https://joss.theoj.org/papers/ebd4e5ca27a5db705b1dc382b64e0bed)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ebd4e5ca27a5db705b1dc382b64e0bed"><img src="https://joss.theoj.org/papers/ebd4e5ca27a5db705b1dc382b64e0bed/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ebd4e5ca27a5db705b1dc382b64e0bed/status.svg)](https://joss.theoj.org/papers/ebd4e5ca27a5db705b1dc382b64e0bed)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/carnotresearch/cr-sparse" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Saran-nns & @mirca, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @pdebuyl know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @Saran-nns
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/carnotresearch/cr-sparse">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/carnotresearch/cr-sparse">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shailesh1729) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] #3939
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @mirca
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/carnotresearch/cr-sparse">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/carnotresearch/cr-sparse">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shailesh1729) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Saran-nns, @mirca it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 4567

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3088525.3088527 is OK
- 10.1109/ICCV.2001.937651 is OK
- 10.1016/j.acha.2009.04.002 is OK
- 10.1109/jstsp.2010.2042411 is OK
- 10.1109/wvm.1991.212809 is OK
- 10.1023/A:1008000628999 is OK
- 10.1109/tit.2009.2016006 is OK
- 10.1109/tit.2010.2054653 is OK
- 10.1007/978-1-4419-7011-4 is OK
- 10.1109/cvprw.2009.5206547 is OK
- 10.1109/tpami.2013.57 is OK
- 10.1109/CVPR.2003.1211332 is OK
- 10.1109/iccv.2001.937679 is OK
- 10.1109/tpami.2005.92 is OK
- 10.21105/joss.01237 is OK
- 10.1016/b978-0-12-374370-1.x0001-8 is OK
- 10.1016/j.acha.2008.07.002 is OK
- 10.1109/acssc.1993.342465 is OK
- 10.1109/34.584098 is OK
- 10.1007/bf00129684 is OK
- 10.1175/1520-0477(1998)079<0061:APGTWA>2.0.CO;2 is OK
- 10.1109/TIT.2004.834793 is OK
- 10.1109/MSP.2010.939739 is OK
- 10.1109/CVPR.2016.425 is OK
- 10.1007/s11263-012-0535-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.36 s (1049.5 files/s, 132232.0 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                          295           4312           8807          16578
TeX                               2            484              1           3263
reStructuredText                 54           1291           1502           1047
Markdown                          7            200              0            894
Jupyter Notebook                  9              0           8309            616
YAML                              4              9              7            148
JavaScript                        1              6             16            117
CSS                               1              9              0             37
JSON                              2              0              0             33
DOS Batch                         1              8              1             26
make                              1              5              7             13
Bourne Again Shell                1              2              0              3
Bourne Shell                      1              1              0              2
--------------------------------------------------------------------------------
SUM:                            379           6327          18650          22777
--------------------------------------------------------------------------------


Statistical information for the repository 'e94c8f59a0f0e97d97a5b8ce' was
gathered on 2021/11/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Shailesh Kumar                 587         33404           3399          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Shailesh Kumar            30005           89.8          2.9               22.73
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment]
@Saran-nns @mirca make sure to accept the invitation to the reviewers group and to have a look at the reviewer guidelines linked to at the top of this review page.

@shailesh1729 the article is very long by JOSS standard, I recommed to shorten it already. The explanations about l0 and l1 problems and about the linear operators are best left in the software documentation.

**Comment by shailesh1729** [comment]
@pdebuyl, thanks for the input. Let me work on shortening it.

**Comment by shailesh1729** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: :point_left:

**Comment by shailesh1729** [comment]
@pdebuyl, I have revised the paper and moved the theoretical explanations to the online documentation and placed references to it in the paper draft.  It is down to 7 pages in draft. 

Kindly, let me know if I should work on shortening it further.

With regards,
Shailesh

**Comment by Saran-nns** [comment]
Hi, a quick update. I created an [issue](https://github.com/carnotresearch/cr-sparse/issues/21#issue-1059511222) with some suggestions at the repository.

**Comment by pdebuyl** [comment]
Hi @shailesh1729 thanks for the editing, this is better. The listing of features in the summary is still excessive (explicit and detailed listing of all subpackages is also for the documentation). Also, a mention such as "For details, see the onlinedocumentation" is redundant.

**Comment by shailesh1729** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: :point_left:

**Comment by Saran-nns** [comment]
@shailesh1729 Besides the length of the draft as mentioned by @pdebuyl, I am convinced with the recent draft. I closed the issue https://github.com/carnotresearch/cr-sparse/issues/21 in favor of @shailesh1729

**Comment by shailesh1729** [comment]
@Saran-nns, I have resolved carnotresearch/cr-sparse#22. Kindly check.

**Comment by mirca** [comment]
@shailesh1729 I'm happy with the current state of the library/paper apart from the issues I have opened in the repo. Please, take a look.

**Comment by shailesh1729** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: :point_left:

**Comment by shailesh1729** [comment]
@mirca, thanks a lot for your feedback. I have updated the online docs and the paper based on the issues you filed. Kindly check. Let me know if there is anything else missing.

**Comment by Saran-nns** [comment]
@pdebuyl My checklist is finished.  It is my pleasure to review this package and I am happy to accept it. Well done @shailesh1729  💯

**Comment by mirca** [comment]
@pdebuyl I have completed my review and I'm happy to recommend this package for acceptance in JOSS. Thanks @shailesh1729!

**Comment by shailesh1729** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: :point_left:

**Comment by shailesh1729** [comment]
Thank you @Saran-nns  and @mirca for your kind feedback. 

@pdebuyl I have done one more round of editing and brought down the paper to 7 pages while keeping all the changes and additions suggested by the reviewers.  Kindly, let me know if this is good enough.

**Comment by pdebuyl** [comment]
Thanks all for the very proactive work here! I'll proceed to the editorial steps during the week.

**Comment by pdebuyl** [comment]
Hi @shailesh1729 

I went through the papers and have minor comments:
- Can you archive the companion https://carnotresearch.github.io/cr-sparse-companion/intro.html on zenodo (the rendered version or rendered+source) and cite it in your article? It is supplemental data to the code so it is better if it is archived.
- For "Yang, J., & Zhang, Y. (2011)", "Kim, S.-J., Koh, K., Lustig, M., Boyd, S., & Gorinevsky, D. (2007)", the title of the article is missing.
- Please add the link to "yall user guide" (Zhang, Yang & Yin 2010) https://www.caam.rice.edu/~optimization/L1/YALL1/User_Guide/YALL1v1.0_User_Guide.pdf (or the 2009 version if it is what you used, I picked the latest from the code's webpage).
- Please add the preprint URL for Ravasi, M., & Vasconcelos, I. (2019).
- First sentence, recommended wording: "We introduceCR-Sparse, a Python library that enables efficiently solving a wide variety of6sparse representation based signal processing problems" -> "We introduce CR-Sparse, a Python library that enables to efficiently solve a wide variety of sparse representation based signal processing problems".
- Line 50: add a space after link to YALL1

If the code has not changed since release v0.2.1 https://zenodo.org/record/5635717 I'll use that as the archive, can you confirm?

The new version of the article is much better in terms of length, thanks!

**Comment by shailesh1729** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: :point_left:

**Comment by shailesh1729** [comment]
HI @pdebuyl,

Thank you for the detailed feedback. I have corrected the bibliographic and other editing issues in the new draft. 

I have created the zenodo archive for the companion site:
- code (notebooks) from main branch https://doi.org/10.5281/zenodo.5749633
- rendered Jupyter book version from the gh-pages branch https://doi.org/10.5281/zenodo.5749656

I have cited the second one in the paper. 

During the last month of review, while the code didn't change, the documentation and README were revised significantly based on the feedback received here.  Hence, I have created a new release (v0.2.2) just now capturing all the doc updates. 

The Zenodo archive link for v0.2.2 is:  https://doi.org/10.5281/zenodo.5749792
This should be used for archival purposes. 

Hope this addresses the concerns listed by you.

Thank you again for all your help in improving the quality of the software and the paper.

**Comment by pdebuyl** [comment]
Thank you for the update, all is good on my side!

Thanks @Saran-nns and @mirca for the review!

**Comment by pdebuyl** [comment]
@whedon set v0.2.2 as version

**Comment by whedon** [comment]
OK. v0.2.2 is the version.

**Comment by pdebuyl** [comment]
@whedon set 10.5281/zenodo.5749792 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5749792" target="_blank">10.5281/zenodo.5749792</a> is the archive.

**Comment by pdebuyl** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3088525.3088527 is OK
- 10.1109/ICCV.2001.937651 is OK
- 10.1137/080716542 is OK
- 10.1007/s12532-011-0029-5 is OK
- 10.1016/j.acha.2009.04.002 is OK
- 10.1109/jstsp.2010.2042411 is OK
- 10.1109/wvm.1991.212809 is OK
- 10.1016/j.crma.2008.03.014 is OK
- 10.1137/S003614450037906X is OK
- 10.1023/A:1008000628999 is OK
- 10.1109/tit.2009.2016006 is OK
- 10.1002/cpa.20042 is OK
- 10.1109/tit.2010.2054653 is OK
- 10.1109/tit.2006.871582 is OK
- 10.1007/978-1-4419-7011-4 is OK
- 10.1109/cvprw.2009.5206547 is OK
- 10.1109/tpami.2013.57 is OK
- 10.1007/978-0-8176-4948-7 is OK
- 10.1109/CVPR.2003.1211332 is OK
- 10.1109/iccv.2001.937679 is OK
- 10.1109/JSTSP.2007.910971 is OK
- 10.1109/tpami.2005.92 is OK
- 10.21105/joss.01237 is OK
- 10.1016/b978-0-12-374370-1.x0001-8 is OK
- 10.1109/ACCESS.2018.2886471 is OK
- 10.1016/j.acha.2008.07.002 is OK
- 10.1561/2400000003 is OK
- 10.1109/acssc.1993.342465 is OK
- 10.1109/34.584098 is OK
- 10.1016/j.sigpro.2020.107548 is OK
- 10.1109/JCN.2013.000083 is OK
- 10.5281/zenodo.5749656 is OK
- 10.21105/joss.02844 is OK
- 10.1007/bf00129684 is OK
- 10.1175/1520-0477(1998)079<0061:APGTWA>2.0.CO;2 is OK
- 10.1109/TIT.2004.834793 is OK
- 10.1109/MSP.2010.939739 is OK
- 10.1137/090777761 is OK
- 10.1109/CVPR.2016.425 is OK
- 10.1007/s11263-012-0535-6 is OK

MISSING DOIs

- 10.1145/355984.355989 may be a valid DOI for title: LSQR: An algorithm for sparse linear equations and sparse least squares

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2791

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2791, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Hi @shailesh1729! I'll be helping with final publishing.

Can you update the metadata on your Zenodo archive so the title and author list exactly match your JOSS paper?

**Comment by kthyng** [comment]
Paper and version look good.

**Comment by shailesh1729** [comment]
Thanks, @kthyng, 

I just updated the metadata (title and author list) on the Zenodo archive https://doi.org/10.5281/zenodo.5749792

Does this look good?  Anything else that I need to do?

**Comment by pdebuyl** [comment]
@kthyng "metadata on your Zenodo archive so the title and author list exactly match your JOSS paper" -> sorry, I forgot to check it

**Comment by pdebuyl** [comment]
and the LSQR entry from the TOMS does not have a DOI to avoid you looking for it :-)

**Comment by shailesh1729** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3088525.3088527 is OK
- 10.1109/ICCV.2001.937651 is OK
- 10.1137/080716542 is OK
- 10.1007/s12532-011-0029-5 is OK
- 10.1016/j.acha.2009.04.002 is OK
- 10.1109/jstsp.2010.2042411 is OK
- 10.1109/wvm.1991.212809 is OK
- 10.1016/j.crma.2008.03.014 is OK
- 10.1137/S003614450037906X is OK
- 10.1023/A:1008000628999 is OK
- 10.1109/tit.2009.2016006 is OK
- 10.1002/cpa.20042 is OK
- 10.1109/tit.2010.2054653 is OK
- 10.1109/tit.2006.871582 is OK
- 10.1007/978-1-4419-7011-4 is OK
- 10.1109/cvprw.2009.5206547 is OK
- 10.1109/tpami.2013.57 is OK
- 10.1007/978-0-8176-4948-7 is OK
- 10.1109/CVPR.2003.1211332 is OK
- 10.1109/iccv.2001.937679 is OK
- 10.1109/JSTSP.2007.910971 is OK
- 10.1109/tpami.2005.92 is OK
- 10.21105/joss.01237 is OK
- 10.1016/b978-0-12-374370-1.x0001-8 is OK
- 10.1109/ACCESS.2018.2886471 is OK
- 10.1016/j.acha.2008.07.002 is OK
- 10.1145/355984.355989 is OK
- 10.1561/2400000003 is OK
- 10.1109/acssc.1993.342465 is OK
- 10.1109/34.584098 is OK
- 10.1016/j.sigpro.2020.107548 is OK
- 10.1109/JCN.2013.000083 is OK
- 10.5281/zenodo.5749656 is OK
- 10.21105/joss.02844 is OK
- 10.1007/bf00129684 is OK
- 10.1175/1520-0477(1998)079<0061:APGTWA>2.0.CO;2 is OK
- 10.1109/TIT.2004.834793 is OK
- 10.1109/MSP.2010.939739 is OK
- 10.1137/090777761 is OK
- 10.1109/CVPR.2016.425 is OK
- 10.1007/s11263-012-0535-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by shailesh1729** [comment]
It was my mistake. I added the LSQR reference later and forgot to add the DOI.

**Comment by shailesh1729** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03917/joss.03917/10.21105.joss.03917.pdf) :page_facing_up: :point_left:

**Comment by shailesh1729** [comment]
All DOIs are good now in the updated draft.

**Comment by kthyng** [comment]
Great! All looks good! I missed that DOI, thanks for the follow up.

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1466486047697682432) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2792
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03917](https://doi.org/10.21105/joss.03917)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @shailesh1729! Many thanks to editor @pdebuyl and reviewers @Saran-nns and @mirca for your time, hard work, and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03917/status.svg)](https://doi.org/10.21105/joss.03917)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03917">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03917/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03917/status.svg
   :target: https://doi.org/10.21105/joss.03917
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03917/status.svg)](https://doi.org/10.21105/joss.03917)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by shailesh1729** [comment]
Thank you everyone for your guidance and support. It is a great feeling to be published on JOSS.
