### ISSUE TITLE
@linuxscout and @gradvohl: Are you willing to help contribute a review for this JOSS submission?

### ISSUE THREAD

**Issue by linuxscout** [openjournals/joss-reviews#3918]
ok, I accept

_Originally posted by @gkthiruvathukal in https://github.com/openjournals/joss-reviews/issues/3890#issuecomment-969784482_

**Comment by whedon** [comment]
:wave: This repository is only for review issues (`pre-review` and `review`) that have been created by our editorial infrastructure, and this issue appears not to be one of these.

As such, this issue will be closed. If you're opening an issue as part of a review, please open a new issue instead in the software repository associated with the submission that you are reviewing.

Many thanks!

**Comment by linuxscout** [comment]
I just made a mistake
