### ISSUE TITLE
[PRE REVIEW]: ECNet: Large scale machine learning projects for fuel property prediction

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#392]
**Submitting author:** @TJKessler (<a href="http://orcid.org/0000-0002-7363-4050">Travis Kessler</a>)
**Repository:** <a href="https://github.com/TJKessler/ECNet" target ="_blank">https://github.com/TJKessler/ECNet</a>
**Version:** v1.2.4.dev1
**Editor:** @arokem
**Reviewer:** @krother

**Author instructions**

Thanks for submitting your paper to JOSS @TJKessler. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@TJKessler if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @arokem - the submitting author suggested you as an editor.

**Comment by arokem** [comment]
Yeah - I can edit this. @TJKessler : do you have ideas for people who could review this?

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by TJKessler** [comment]
@arokem - @krother or @jkahn from the provided list of JOSS reviewers would be a good fit

**Comment by arokem** [comment]
:wave: @krother : would you be willing to review this submission for JOSS?

**Comment by krother** [comment]
yes :+1:

**Comment by arokem** [comment]
@whedon assign @krother as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @krother

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/401. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks @krother! I am closing this now - head over to https://github.com/openjournals/joss-reviews/issues/401 for the review issue, including explanations and a check list for you to go through with the criteria for the review.
