### ISSUE TITLE
[PRE REVIEW]: Python Sphere RCS: a Library to Compute Mie Series Scattering of Lossy Dielectric Spheres

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3921]
**Submitting author:** @IliyaShofman (<a href="http://orcid.org/0000-0003-1798-8337">Iliya Shofman</a>)
**Repository:** <a href="https://github.com/modelics/Python-Sphere-RCS" target ="_blank">https://github.com/modelics/Python-Sphere-RCS</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1f28373bf65e3fa6da5d873bee7c5536/status.svg)](https://joss.theoj.org/papers/1f28373bf65e3fa6da5d873bee7c5536)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1f28373bf65e3fa6da5d873bee7c5536"><img src="https://joss.theoj.org/papers/1f28373bf65e3fa6da5d873bee7c5536/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1f28373bf65e3fa6da5d873bee7c5536/status.svg)](https://joss.theoj.org/papers/1f28373bf65e3fa6da5d873bee7c5536)
```

**Author instructions**

Thanks for submitting your paper to JOSS @IliyaShofman. **Currently, there isn't an JOSS editor assigned** to your paper.

@IliyaShofman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 431

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi:10.1364/ao.53.007224 is OK
- doi.org/10.1364/AO.19.001505 is OK

MISSING DOIs

- 10.2307/1266136 may be a valid DOI for title: Handbook of Mathematical Functions With Formulas, Graphs, and Mathematical Tables.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (296.4 files/s, 53233.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            333            673            882
Markdown                         2             54              0            160
TeX                              1              5              0             48
-------------------------------------------------------------------------------
SUM:                            12            392            673           1090
-------------------------------------------------------------------------------


Statistical information for the repository 'bdb085f2d4ced169867b3050' was
gathered on 2021/11/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
IliyaShofman                     3          2174            286          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
IliyaShofman               1888           86.8          0.0                8.79
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03921/joss.03921/10.21105.joss.03921.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03921/joss.03921/10.21105.joss.03921.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@IliyaShofman thanks for your submission to JOSS – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

Also, please note, as far as I can tell, you're using a custom license here which is not allowed in JOSS. Please update your license to use a standard [OSI approved](https://opensource.org/licenses) license

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@IliyaShofman Unfortunately, after a scope review by the JOSS editorial board, it was determined that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  

At this point we will proceed to reject this submission. 

Note that this rejection does not mean the software is not useful or not functional, or that it is poorly made. It merely means that given its size it is currently out of scope for JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work. Alternatively you may also consider a re-submission if this work is substantially expanded in terms of functionality and magnitude of scholarly effort. Furthermore, for JOSS to consider a re-submission, other aspects may need improvement such as the license type (which should be an [OSI approved license](https://opensource.org/licenses)) as well as the general packaging of the software.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
