### ISSUE TITLE
[PRE REVIEW]: GXBeam: A Pure Julia Implementation of Geometrically Exact Beam Theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3924]
**Submitting author:** @taylormcd (<a href="http://orcid.org/0000-0001-7993-5703">Taylor McDonnell</a>)
**Repository:** <a href="https://github.com/byuflowlab/GXBeam.jl" target ="_blank">https://github.com/byuflowlab/GXBeam.jl</a>
**Version:** v0.3.1
**Editor:** @prashjha
**Reviewers:** @Kevin-Mattheus-Moerman, @PetrKryslUCSD
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/13cb0c41e9834510c6acf732bdfa8c05/status.svg)](https://joss.theoj.org/papers/13cb0c41e9834510c6acf732bdfa8c05)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/13cb0c41e9834510c6acf732bdfa8c05"><img src="https://joss.theoj.org/papers/13cb0c41e9834510c6acf732bdfa8c05/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/13cb0c41e9834510c6acf732bdfa8c05/status.svg)](https://joss.theoj.org/papers/13cb0c41e9834510c6acf732bdfa8c05)
```

**Author instructions**

Thanks for submitting your paper to JOSS @taylormcd. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@taylormcd if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 822

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4404703 is OK
- 10.5281/zenodo.5633646 is OK
- 10.5334/jors.151 is OK
- 10.2514/5.9781600866821.0103.0142 is OK
- 10.1002/sapm197352287 is OK
- 10.1016/j.compstruct.2012.04.007 is OK
- 10.1063/1.4985091 is OK
- 10.2514/5.9781600866821.0059.0102 is OK

MISSING DOIs

- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (245.6 files/s, 121683.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           13           1730           1069           7306
Markdown                         7            751              0           3075
SVG                              6              6              6           2656
TeX                              1             10              0            119
YAML                             4              5              0             71
TOML                             3              2              0             41
-------------------------------------------------------------------------------
SUM:                            34           2504           1075          13268
-------------------------------------------------------------------------------


Statistical information for the repository '7a647fcdc9870292be9361ef' was
gathered on 2021/11/19.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03924/joss.03924/10.21105.joss.03924.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03924/joss.03924/10.21105.joss.03924.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @prashjha as editor

:wave: @prashjha – would you be able to handle this submission for us?

**Comment by whedon** [comment]
@prashjha has been invited to edit this submission.

**Comment by prashjha** [comment]
@arfon sure...thanks!

**Comment by prashjha** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @prashjha

**Comment by Kevin-Mattheus-Moerman** [comment]
@prashjha I am interested in this work and would like to "take it for a spin". I could serve as an N+1th reviewer if you like. I say N+1th, since I am quite new to Julia, so do recommend you get some much more experienced reviewers here too. 

FYI I'd say that the reviewers and developers of Gridap (https://joss.theoj.org/papers/10.21105/joss.02520) would be great as a reviewer for this too e.g.: fverdugo

**Comment by prashjha** [comment]
@Kevin-Mattheus-Moerman thanks and I am cool with you being the reviewer....adding you now

**Comment by prashjha** [comment]
@whedon assign @Kevin-Mattheus-Moerman as reviewer

**Comment by whedon** [comment]
OK, @Kevin-Mattheus-Moerman is now a reviewer

**Comment by prashjha** [comment]
Hi @fverdugo, @Kevin-Mattheus-Moerman and I think this submission will be of interest to you. Would you be able to review this?

**Comment by prashjha** [comment]
Hi @Jgoldfar, any chance you could review this submission for JOSS?

**Comment by prashjha** [comment]
@taylormcd I am still looking for one more reviewer to get started. Meanwhile, if you have suggestions for potential reviewers, share them here!

**Comment by Kevin-Mattheus-Moerman** [comment]
@prashjha perhaps `Andlon` (https://twitter.com/andreas_longva) would be interested in reviewing

**Comment by prashjha** [comment]
Hi @Andlon, would you be interested in reviewing this submission for JOSS?

**Comment by Andlon** [comment]
Hi @prashjha: I appreciate the recommendation from @Kevin-Mattheus-Moerman, but I unfortunately don't have enough experience with Julia nor beam theory to be comfortable about this!

**Comment by taylormcd** [comment]
PetrKryslUCSD or ahojukka5 might be good options.

**Comment by prashjha** [comment]
@Andlon no worries. Thanks for letting me/us know.

**Comment by prashjha** [comment]
Hello Professor @PetrKryslUCSD, any chance you could review this submission for JOSS

**Comment by PetrKryslUCSD** [comment]
Sure, no prob.

**Comment by prashjha** [comment]
Awesome!!

**Comment by prashjha** [comment]
@whedon add @PetrKryslUCSD as reviewer

**Comment by whedon** [comment]
OK, @PetrKryslUCSD is now a reviewer

**Comment by prashjha** [comment]
Hi @taylormcd, we now have two reviewers so I will start the review process.

Thanks in advance @Kevin-Mattheus-Moerman and @PetrKryslUCSD for your time. I will see you in 'Review' issue.

**Comment by prashjha** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3997.
