### ISSUE TITLE
[PRE REVIEW]: LEGWORK: A python package for computing the evolution and detectability of stellar-origin gravitational-wave sources with space-based detectors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3925]
**Submitting author:** @TomWagg (<a href="http://orcid.org/0000-0001-6147-5761">Thomas Wagg</a>)
**Repository:** <a href="https://github.com/TeamLEGWORK/LEGWORK" target ="_blank">https://github.com/TeamLEGWORK/LEGWORK</a>
**Version:** v0.1.6
**Editor:** @arfon
**Reviewers:** @dbkeitel, @cmbiwer
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/82477c099f1c94f12e11cc398ece6f8d/status.svg)](https://joss.theoj.org/papers/82477c099f1c94f12e11cc398ece6f8d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/82477c099f1c94f12e11cc398ece6f8d"><img src="https://joss.theoj.org/papers/82477c099f1c94f12e11cc398ece6f8d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/82477c099f1c94f12e11cc398ece6f8d/status.svg)](https://joss.theoj.org/papers/82477c099f1c94f12e11cc398ece6f8d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @TomWagg. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@TomWagg if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (507.0 files/s, 136913.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18           1093           1765           2067
Jupyter Notebook                13              0           6277            917
TeX                              1             12              0            217
Markdown                         2             19              0             98
YAML                             2             10             10             68
CSS                              1             10             10             55
reStructuredText                 7             67            136             49
DOS Batch                        1              8              1             26
JavaScript                       1              2              2             18
make                             1              4              7              9
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            48           1225           8208           3530
-------------------------------------------------------------------------------


Statistical information for the repository '2dbcc748e8fe5081ff47be0c' was
gathered on 2021/11/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tom Wagg                       328          7459           4166           40.13
katiebreivik                    65          9502           7843           59.87

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Katie Breivik              2149          100.0          8.0               11.54
Tom Wagg                   2798           37.5          6.2                9.72
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
PDF failed to compile for issue #3925 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03925/joss.03925/10.21105.joss.03925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03925/joss.03925/10.21105.joss.03925.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@TomWagg – many thanks for your submission to JOSS! 

Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by TomWagg** [comment]
@arfon, gladly, very excited for the review! 😄

Here's a couple of potential reviewers that I think should work

- duncanmmacleod
- cmbiwer
- johnveitch
- db87
- dbkeitel
- sbozzolo

**Comment by TomWagg** [comment]
@whedon set v0.1.6 as version

**Comment by whedon** [comment]
I'm sorry @TomWagg, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
@whedon set v0.1.6 as version

**Comment by whedon** [comment]
OK. v0.1.6 is the version.

**Comment by arfon** [comment]
@duncanmmacleod @cmbiwer @johnveitch – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is: _LEGWORK: A python package for computing the evolution and detectability of stellar-origin gravitational-wave sources with space-based detectors_.

**Comment by johnveitch** [comment]
Hi @arfon. Thanks for the invitation to act as a reviewer for JOSS. I had a look through LegWork and it seems to be a very nicely put together package. I would be happy to review it but I've got a pretty full diary before Christmas so I don't think I'll be very swift. Perhaps if we can divide the work between myself and others it would be possible on that timescale, if that would suit you.

**Comment by cmbiwer** [comment]
I just finished reviewing another JOSS submission a couple weeks ago, so I'd let others have a chance before me. But if no one else is available, then I can be one of the reviewers.

**Comment by arfon** [comment]
:wave: @sbozzolo @dbkeitel – would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is: _LEGWORK: A python package for computing the evolution and detectability of stellar-origin gravitational-wave sources with space-based detectors_.

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod @cmbiwer @johnveitch – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
> 
> The submission under consideration is: _LEGWORK: A python package for computing the evolution and detectability of stellar-origin gravitational-wave sources with space-based detectors_.

Sorry @arfon, similar to John I don't think I'll be able to get to this quickly, but could come back to this in the new year if you haven't been able to find a reviewer before then.

**Comment by Sbozzolo** [comment]
> wave @Sbozzolo @dbkeitel – would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
> 
> The submission under consideration is: _LEGWORK: A python package for computing the evolution and detectability of stellar-origin gravitational-wave sources with space-based detectors_.

I am in the same boat as cmbiwer: I can review LEGWORK, but I finished another JOSS review two days ago and I am happy to let others go. If no one is available, you can count on me.

**Comment by dbkeitel** [comment]
This looks like a very professionally assembled package, and in principle I'd be happy to help with review. However I'm confused by the intended relation between the JOSS paper and the longer one at https://arxiv.org/abs/2111.08717 with the exact same title and very similar abstract. From https://joss.readthedocs.io/en/latest/submitting.html#co-publication-of-science-methods-and-software I see that in principle "co-publication" is fine, but here it looks like the other version also explicitly describes the package and so I'm not sure what the JOSS submission is adding. So before committing to review, maybe @TomWagg could clarify a bit and  @arfon could opine if this seems reasonable.

**Comment by TomWagg** [comment]
Hi @dbkeitel, I'm sure @arfon will have more thoughts but my understanding was that this was the point behind co-publication. Our motivation behind also submitting to JOSS is that we are able to get a review of the code itself. Only the manuscript that we submit to AAS will be reviewed and it was important to us that we ensure that not just our writing, but also our package was reviewed and that's what the JOSS submission adds. We think this will help us to improve the code and, should the review be successful, will indicate to others that the package has been written well.

But I'll of course defer to @arfon if we've misunderstand how these co-publications should work!

**Comment by dbkeitel** [comment]
Thanks for the clarifications @TomWagg and @arfon , I was not aware of the details of this initiative and from the documentations page I had interpreted the model as more "orthogonal" than this very "parallel" process. Still, thinking as a potential reader / end-user I'd personally find it very confusing to encounter two papers in different journals that overlap so much and even share the title; is that explicitly expected under the agreement with AAS or subject to discussion during review?

Also when you say "a more detailed software review", is this still the original JOSS model that focuses mostly on packaging and documentation as per the check-list, or is an actual in-depth review of the scientific and numerical validity of the code expected? (Similar to what e.g. the LVK collaboration, and probably other large collaborations, consider a "software review".) I'm afraid for the latter I wouldn't have the qualification and time.

**Comment by arfon** [comment]
> Still, thinking as a potential reader / end-user I'd personally find it very confusing to encounter two papers in different journals that overlap so much and even share the title; is that explicitly expected under the agreement with AAS or subject to discussion during review?

Yes, I can see how this could be a little confusing. Historically – for the ~25 papers that have been through this process so far – the titles have been identical/very similar between the JOSS and AAS paper in ~25% of cases (like here). 

> Also when you say "a more detailed software review", is this still the original JOSS model that focuses mostly on packaging and documentation as per the check-list.

:+1: yes, the JOSS review is the same.

Going back to the origins/purpose of this dual review process for a moment. The AAS paper is likely to be the 'canonical' reference for this software package (although this is of course up to the authors). The AAS paper includes a far more detailed description of what the purpose of the package is, detailed mathematical derivations of the algorithms implemented in the code, detailed example results etc. While the AAS review process is mostly focused on the scientific merit of this software within a specific area of science, the is little/no actual review of the software, its implementation, usability etc. and this is where JOSS steps in.

I guess what I'm saying is that the AAS and JOSS reviews are two halves of a whole review of the work. Due to us not wanting to conflate our editorial processes, when we first established this collaboration we decided it would be most straightforward to simply have two papers go through a normal review, and for them to cite each other.

**Comment by dbkeitel** [comment]
Thanks @arfon ! It probably isn't a model I'd be going for myself as an author, but I agree that this submission matches your intended model, and you can sign me up for review.

Also as a purely optional and personal suggestion to @tomwagg and co-authors: to disambiguate titles, the current one seems perfect for JOSS, but maybe you could consider changing over at ApJ to something like `Computing the evolution and detectability of stellar-origin gravitational-wave sources for space-based detectors with the python package LEGWORK`? Then it would be clear that the JOSS paper is a "software reference" while ApJ focuses more on the physics of it. But as @arfon wrote, having the same title seems perfectly fine by editorial agreement between the two journals, so I won't officially complain review-wise if you prefer to keep both the same.

**Comment by arfon** [comment]
Wonderful, thanks @dbkeitel!

**Comment by arfon** [comment]
@whedon add @dbkeitel as reviewer

**Comment by whedon** [comment]
OK, @dbkeitel is now a reviewer

**Comment by arfon** [comment]
> Also as a purely optional and personal suggestion to @TomWagg and co-authors: to disambiguate titles, the current one seems perfect for JOSS, but maybe you could consider changing over at ApJ to something like Computing the evolution and detectability of stellar-origin gravitational-wave sources for space-based detectors with the python package LEGWORK? Then it would be clear that the JOSS paper is a "software reference" while ApJ focuses more on the physics of it.

@TomWagg – this isn't required, but I do think this is a good suggestion if possible.

**Comment by arfon** [comment]
@db87 – would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is: _LEGWORK: A python package for computing the evolution and detectability of stellar-origin gravitational-wave sources with space-based detectors_.

**Comment by TomWagg** [comment]
Agreed @arfon, thanks for the feedback @dbkeitel! We've updated the title of the ApJ paper to `Computing the evolution and detectability of stellar-origin gravitational-wave sources in space-based detectors using the LEGWORK python package` (as you can see [here](https://raw.githubusercontent.com/TeamLEGWORK/LEGWORK-paper/main-pdf/ms.pdf))

I think perhaps this could be something to add to the guidance on joint JOSS/AAS submissions if there is a preference for having distinct titles between the two?

**Comment by TomWagg** [comment]
Actually, having discussed this with my co-authors, they suggested that perhaps it isn't sensible to change the title of the ApJ paper. Since, changing the title doesn't really change the _content_ of the paper, and so it could become even more confusing if two papers with extremely similar content have different titles. Whereas having the same title can make it extremely clear that the two papers are a joint submission.

But if you still feel strongly that they should have different names we shall of course follow your guidance!

**Comment by arfon** [comment]
> But if you still feel strongly that they should have different names we shall of course follow your guidance!

I do not, so let's keep things as they are.

**Comment by arfon** [comment]
@whedon add @cmbiwer as reviewer

**Comment by whedon** [comment]
OK, @cmbiwer is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3998.

**Comment by cmbiwer** [comment]
Sounds good @arfon.
