### ISSUE TITLE
[PRE REVIEW]: EllipSect: A Python tool for surface brightness analysis for GALFIT

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3926]
**Submitting author:** @canorve (<a href="http://orcid.org/0000-0002-3721-8869">Christopher Anorve</a>)
**Repository:** <a href="https://github.com/canorve/EllipSect" target ="_blank">https://github.com/canorve/EllipSect</a>
**Version:** 2.1.3
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5bd141b13bd173b060dcb757180bdf07/status.svg)](https://joss.theoj.org/papers/5bd141b13bd173b060dcb757180bdf07)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5bd141b13bd173b060dcb757180bdf07"><img src="https://joss.theoj.org/papers/5bd141b13bd173b060dcb757180bdf07/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5bd141b13bd173b060dcb757180bdf07/status.svg)](https://joss.theoj.org/papers/5bd141b13bd173b060dcb757180bdf07)
```

**Author instructions**

Thanks for submitting your paper to JOSS @canorve. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@canorve if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1527

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (477.9 files/s, 123957.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22           1945            549           3118
Markdown                         4            336              0            737
TeX                              1             23              0            296
-------------------------------------------------------------------------------
SUM:                            27           2304            549           4151
-------------------------------------------------------------------------------


Statistical information for the repository '3f2c7b1f22299cb57fcedde7' was
gathered on 2021/11/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christopher Añorve             175         22880          17322           99.85
Ulises                           1            58              4            0.15

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christopher Añorve         5588           24.4          1.8                9.68
Ulises                       24           41.4          1.1               33.33
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1086/340952 is OK
- 10.1093/mnras/226.4.747 is OK
- 10.1046/j.1365-8711.2002.05412.x is OK
- 10.1088/0004-6256/138/5/1417 is OK
- 10.1086/503539 is OK
- 10.1093/mnras/sts633 is OK
- 10.1111/j.1365-2966.2012.20619.x is OK
- 10.1111/j.1365-2966.2010.17426.x is OK
- 10.1093/mnras/stab2321 is OK
- 10.1093/mnras/stab2709 is OK
- 10.3847/1538-4357/aa7da4 is OK
- 10.1086/190669 is OK
- 10.1086/182301 is OK
- 10.1088/0004-6256/139/6/2097 is OK

MISSING DOIs

- 10.1007/978-1-4612-1694-0_16 may be a valid DOI for title: A New Look at the Statistical Model Identification
- 10.1214/aos/1176344136 may be a valid DOI for title: Estimating the Dimension of a Model

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03926/joss.03926/10.21105.joss.03926.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03926/joss.03926/10.21105.joss.03926.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@canorve – many thanks for your submission to JOSS. After a cursory review of the repository, I'm going to ask my fellow editors to conduct a scope review of this submission. This will likely take a week or so, thanks for your patience!

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @canorve and thanks for your submission. I'm sorry to say that the editorial board still feels like this is not quite in scope, despite your effort in the meantime. Specific feedback includes:
* still very close to a stand-alone script even with your changes
* needs more functionality added 
* suggestion to combine with other work to make a more capable library, maybe with your other GALFIT tools?
* the code is structured for a set task and so not easily extensible
* the argument parsing may be fragile
* a more generic utility library would be better
* a large fraction of the code is command line parsing that would be better handled by the standard library, and the rest of it is mostly plotting. (plotting is ok as part of submissions but usually shouldn't be most of the code)

Alternatively, you might consider publishing your software another way; we have some guidance on that here: https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
