### ISSUE TITLE
[PRE REVIEW]: pyscreener: A Python Wrapper for Computational Docking Software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3927]
**Submitting author:** @davidegraff (<a href="http://orcid.org/0000-0003-1250-3329">David E. Graff</a>)
**Repository:** <a href="https://github.com/coleygroup/pyscreener.git" target ="_blank">https://github.com/coleygroup/pyscreener.git</a>
**Version:** v1.1.1
**Editor:** @richardjgowers
**Reviewers:** @mikemhenry, @rvhonorato
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fdf9d3c5864cbca0f3f7ea0530d33720/status.svg)](https://joss.theoj.org/papers/fdf9d3c5864cbca0f3f7ea0530d33720)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fdf9d3c5864cbca0f3f7ea0530d33720"><img src="https://joss.theoj.org/papers/fdf9d3c5864cbca0f3f7ea0530d33720/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fdf9d3c5864cbca0f3f7ea0530d33720/status.svg)](https://joss.theoj.org/papers/fdf9d3c5864cbca0f3f7ea0530d33720)
```

**Author instructions**

Thanks for submitting your paper to JOSS @davidegraff. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @richardjgowers.

@davidegraff if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (700.7 files/s, 78147.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           48           1150           2092           3930
Markdown                          6             97              1            293
YAML                              7             23              3            127
INI                               6             13              0             45
Bourne Again Shell                1              9              9             30
Bourne Shell                      1              5              8             28
DOS Batch                         1              8              1             27
make                              1              4              6             10
--------------------------------------------------------------------------------
SUM:                             71           1309           2120           4490
--------------------------------------------------------------------------------


Statistical information for the repository '32763b25b2868fe4021ec7ce' was
gathered on 2021/11/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
david graff                    207         48964          27945          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
david graff                7172           14.6          4.1                9.55
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3927 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03927/joss.03927/10.21105.joss.03927.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03927/joss.03927/10.21105.joss.03927.pdf) :page_facing_up: :point_left:

**Comment by richardjgowers** [comment]
I can take this

**Comment by arfon** [comment]
Great, thanks!

**Comment by arfon** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@rvhonorato @rmeli @mikemhenry would any/all of you be available to help review this?

**Comment by RMeli** [comment]
@richardjgowers As much as I would like to review this submission, I am too busy in this period (up to Christmas) to ensure a timely review and therefore I'll have to pass.

**Comment by rvhonorato** [comment]
@richardjgowers yes, thanks for the invite (:

**Comment by mikemhenry** [comment]
@richardjgowers yes!

**Comment by richardjgowers** [comment]
@whedon add @mikemhenry as reviewer

**Comment by whedon** [comment]
OK, @mikemhenry is now a reviewer

**Comment by richardjgowers** [comment]
@whedon add @rvhonorato as reviewer

**Comment by whedon** [comment]
OK, @rvhonorato is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3950.
