### ISSUE TITLE
[PRE REVIEW]: Elephas: Distributed Deep Learning with Keras & Spark

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3928]
**Submitting author:** @maxpumperla (<a href="http://orcid.org/0000-0002-7801-4184">Max Pumperla</a>)
**Repository:** <a href="https://github.com/maxpumperla/elephas" target ="_blank">https://github.com/maxpumperla/elephas</a>
**Version:** 3.0.0
**Editor:** @taless474
**Reviewers:** @marksantcroos, @burch-cm
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/328ce9586713a195b27a55658885cd5b/status.svg)](https://joss.theoj.org/papers/328ce9586713a195b27a55658885cd5b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/328ce9586713a195b27a55658885cd5b"><img src="https://joss.theoj.org/papers/328ce9586713a195b27a55658885cd5b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/328ce9586713a195b27a55658885cd5b/status.svg)](https://joss.theoj.org/papers/328ce9586713a195b27a55658885cd5b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @maxpumperla. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@maxpumperla if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (1071.6 files/s, 77364.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          47            722            421           2591
Markdown                        12             89              0            254
Jupyter Notebook                 1              0            495             88
YAML                             3              4              1             70
Dockerfile                       1             14              4             55
INI                              1              3              0              7
Bourne Shell                     1              3              3              4
Groovy                           1              2              5              2
-------------------------------------------------------------------------------
SUM:                            67            837            929           3071
-------------------------------------------------------------------------------


Statistical information for the repository '57ff5016c4b3a951fea4bac3' was
gathered on 2021/11/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
10056727                         1             1              1            0.01
A-Fayez92                        1             1              1            0.01
Alberto Fumagalli                1             1              1            0.01
Ana Maria Martinez F             4             6              9            0.10
Gaurav Yeole                     1             1              1            0.01
Ivan Montero                     1             2              0            0.01
JONATHAN-DS\Jonathan             2            22             32            0.36
Jose Alvarez                     2             3              2            0.03
Liang-Chi Hsieh                  1             4              4            0.05
Max                              2             2              0            0.01
Max Pumperla                   187          6976           3035           67.14
Oscar Pan                       21           193             92            1.91
Samangooei                       5            82             45            0.85
Willem Meints                    1            11              2            0.09
Yuan Yifan                       1             4              3            0.05
danielenricocahall             101          1855           2424           28.70
ivanmontero                      1             4              1            0.03
jordan vega                      2            20              2            0.15
spencerimp                       1            62              5            0.45

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JONATHAN-DS\Jonathan          5           22.7         42.4                0.00
Jose Alvarez                  2           66.7         32.5                0.00
Liang-Chi Hsieh               3           75.0         67.8               33.33
Max Pumperla               2506           35.9         43.9                8.90
Oscar Pan                   139           72.0          5.0                4.32
Samangooei                    4            4.9         59.9                0.00
Yuan Yifan                    2           50.0         12.6                0.00
danielenricocahall         1059           57.1          6.5                5.19
jordan vega                  14           70.0         33.2                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3928 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch mp_joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch mp_joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03928/joss.03928/10.21105.joss.03928.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03928/joss.03928/10.21105.joss.03928.pdf) :page_facing_up: :point_left:

**Comment by maxpumperla** [comment]
Hi @arfon thanks for kicking off the build etc. In my submission I forgot to mention that `elephas` has been cited many times (https://scholar.google.com/scholar?hl=de&as_sdt=0%2C5&q=elephas+keras&btnG=). I hope by publishing in JOSS we can make it easier for researchers to cite it properly.

**Comment by arfon** [comment]
@whedon invite @taless474 as editor

:wave: @taless474 – would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@taless474 has been invited to edit this submission.

**Comment by taless474** [comment]
> @whedon invite @taless474 as editor
> 
> 👋 @taless474 – would you be able to edit this submission for JOSS?

Yes, I like to!

**Comment by taless474** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @taless474

**Comment by taless474** [comment]
@xirdneh, are you interested in reviewing this? 
@maxpumperla Hi, nice submission. Do you know any potential reviewers?

**Comment by taless474** [comment]
@maxpumperla would you please introduce some potential reviewers?

**Comment by maxpumperla** [comment]
hey @taless474, first of all thanks for reaching out - I'm truly sorry I missed your message the first time around.

Going through your list of reviewers, here are a few suggestions (in no particular order): sonal-raj, ahurriyetoglu, marksantcroos, FreddieV4, dghoshal-lbl

**Comment by taless474** [comment]
Thank you @maxpumperla 
@burch-cm would you be interested in reviewing this?

**Comment by taless474** [comment]
@marksantcroos,@dghoshal-lbl would you be interested in reviewing this?

**Comment by marksantcroos** [comment]
@taless474 I should be able to review this one.

**Comment by taless474** [comment]
@whedon assign @marksantcroos as reviewer

**Comment by whedon** [comment]
OK, @marksantcroos is now a reviewer

**Comment by taless474** [comment]
@FreddieV4 are you interested in reviewing this?

**Comment by taless474** [comment]
@ahurriyetoglu are you interested in reviewing this work?

**Comment by burch-cm** [comment]
> Thank you @maxpumperla 
> 
> @burch-cm would you be interested in reviewing this?

I would be interested in reviewing this if reviews are still needed.

**Comment by taless474** [comment]
@whedon add @burch-cm as reviewer

**Comment by whedon** [comment]
OK, @burch-cm is now a reviewer

**Comment by taless474** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4073.
