### ISSUE TITLE
[PRE REVIEW]: SEIQHCDRO COVID-19 Interactive Modelling Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3929]
**Submitting author:** @tuankhoin (<a href="http://orcid.org/0000-0001-8556-5876">Tuan-Khoi Nguyen</a>)
**Repository:** <a href="https://github.com/tuankhoin/SEIQHCDRO-Interactive-Model" target ="_blank">https://github.com/tuankhoin/SEIQHCDRO-Interactive-Model</a>
**Version:** v3.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/acd71734c91116717fb7f62e072aace4/status.svg)](https://joss.theoj.org/papers/acd71734c91116717fb7f62e072aace4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/acd71734c91116717fb7f62e072aace4"><img src="https://joss.theoj.org/papers/acd71734c91116717fb7f62e072aace4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/acd71734c91116717fb7f62e072aace4/status.svg)](https://joss.theoj.org/papers/acd71734c91116717fb7f62e072aace4)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tuankhoin. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jbytecode.

@tuankhoin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1420

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.lanwpc.2020.100077 is OK
- 10.1097/EDE.0000000000001257 is OK
- 10.1056/NEJMc2025203 is OK
- 10.1017/dmp.2020.357 is OK
- 10.1016/j.puhip.2021.100132 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (87.6 files/s, 42586.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2            140            570           1662
Markdown                         2            101              0            253
CSS                              1             22              0            104
TeX                              1              6              0             58
-------------------------------------------------------------------------------
SUM:                             6            269            570           2077
-------------------------------------------------------------------------------


Statistical information for the repository 'd8a007ca59a924eea1832c9b' was
gathered on 2021/11/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Hoang Anh Ngo                   24           382            233           12.08
hoanganhngo610                   2             4              4            0.16
tuankhoin                       82          3345           1122           87.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Hoang Anh Ngo               148           38.7          4.5                4.73
hoanganhngo610                4          100.0          4.5                0.00
tuankhoin                  2220           66.4          1.4                4.95
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03929/joss.03929/10.21105.joss.03929.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03929/joss.03929/10.21105.joss.03929.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@tuankhoin – thanks for your submission to JOSS. I'm querying the scope of this submission so the wider editorial team can provide their feedback.

This submission is a little different from what we usually allow in JOSS, in particular, visualisation tools are generally out of scope for us, and web applications where a significant fraction of the code contribution is UI configuration (as is the case here).

The scope query will likely take a week or so.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by hoanganhngo610** [comment]
@arfon Thank you so much for handling our application for JOSS! I'm Hoang-Anh, co-author with @tuankhoin of the model and also of this tool. I really hope I can have a few words to back up our application to the journal. 

Originally, we decided to create a Python library out of this with more flexibility, which is the ability to create a full model from scratch, define the compartments and hyperparameters, alongside all the options provided in our current tool. 

However, given the fact that the resources for CS are limited within the medical system in Vietnam, especially in remote provinces, we had to switch to a visualization tool that has everything available and as easy to use as possible, which is why we switched to the current version of the web-app. We know that this is a little bit unusual as a submission, but given the model's impact on the epidemiological community and its popularity and impact, we really hope that the editorial team can give it a chance! 

This is indeed one of the very few modeling visualization tools around the world, besides the very most famous ones like CovidSim.

Thank you so much and have a nice weekend!

**Comment by Kevin-Mattheus-Moerman** [comment]
@tuankhoin Unfortunately, after a scope review by the JOSS editorial board, it was determined that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  

At this point we will proceed to reject this submission. 

Note that this rejection does not mean the software is not useful or not functional, or that it is poorly made. It merely means that given its size it is currently out of scope for JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work. Alternatively you may also consider a re-submission if this work is substantially expanded in terms of functionality.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
