### ISSUE TITLE
[PRE REVIEW]: bittrex: A R Client for the Bittrex Crypto-Currency Exchange

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#393]
**Submitting author:** @kaneplusplus (<a href="http://orcid.org/0000-0003-1899-6662">Michael Kane</a>)
**Repository:** <a href="https://github.com/ropensci/bittrex/" target ="_blank">https://github.com/ropensci/bittrex/</a>
**Version:** v0.1.6
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @kaneplusplus. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kaneplusplus if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @kaneplusplus - thanks for your submission to JOSS. We've recently tightened up our submission criteria for JOSS (this pre-dates your submission to rOpensci). Would you be able to add some extra language to this `paper.md` to address the [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is in the paper)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by kaneplusplus** [comment]
@arfon Yes, this is not problem and I'm happy to make this clearer. I confirm this does have research applications. A few financial/economics research areas and topics include:
- Comparisons between semi-regulated markets (bittrex) to traditional, regulated markets.
- Microfinancing for start-ups using initial coin offerings.
- Quantifying the value of non-traditional products and services.
- Systemic risk of multiple crypto-currencies on the same block chain.
- Crypto-coins as a proxy for sports betting where sports betting is illegal.

I will clean this up and revise `paper.md` in the next couple of days and follow up.

**Comment by kaneplusplus** [comment]
@afron The extra language has been added. Please let me know if you need anything else.

**Comment by arfon** [comment]
> @afron The extra language has been added. Please let me know if you need anything else.

@kaneplusplus many thanks.

**Comment by arfon** [comment]
@kaneplusplus - could you link to the rOpensci onboarding thread here please?

**Comment by karthik** [comment]
@arfon https://github.com/ropensci/onboarding/issues/120

**Comment by arfon** [comment]
@whedon set @arfon as reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/402. Feel free to close this issue now!
