### ISSUE TITLE
[PRE REVIEW]: Ocetrac: A Python package to track the spatiotemporal evolution of marine heatwaves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3930]
**Submitting author:** @hscannell (<a href="http://orcid.org/0000-0002-6604-1695">Hillary Scannell</a>)
**Repository:** <a href="https://github.com/ocetrac/ocetrac" target ="_blank">https://github.com/ocetrac/ocetrac</a>
**Version:** v0.1.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/787eff04eb98d78b435d67f6ec194ea7/status.svg)](https://joss.theoj.org/papers/787eff04eb98d78b435d67f6ec194ea7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/787eff04eb98d78b435d67f6ec194ea7"><img src="https://joss.theoj.org/papers/787eff04eb98d78b435d67f6ec194ea7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/787eff04eb98d78b435d67f6ec194ea7/status.svg)](https://joss.theoj.org/papers/787eff04eb98d78b435d67f6ec194ea7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @hscannell. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@hscannell if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1579

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (651.1 files/s, 129065.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1             22              0            458
YAML                            11             17             16            454
Python                           6            168            153            358
Jupyter Notebook                 5              0           4841            346
Markdown                         6             53              0            122
reStructuredText                 6             98             64            114
TOML                             1              4              1             25
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            37            366           5082           1886
-------------------------------------------------------------------------------


Statistical information for the repository '96663667704d6a5348ba142d' was
gathered on 2021/11/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Hillary Scannell                11           170            338           18.98
Julius Busecke                   3           113             92            7.66
hscannell                       35          1395            569           73.37

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Hillary Scannell            639          375.9          1.9               18.47
Julius Busecke               40           35.4          3.3                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmarsys.2012.10.009 is OK
- 10.1016/j.pocean.2015.12.014 is OK
- 10.1038/s41558-019-0412-1 is OK
- 10.5670/oceanog.2013.27 is OK
- 10.1002/2016GL070023 is OK
- 10.1038/s41598-020-63650-z is OK
- 10.1073/pnas.1901084116 is OK
- 10.1038/s41586-018-0383-9 is OK
- 10.3389/fmars.2019.00734 is OK
- 10.1038/s41467-019-10206-z is OK
- 10.1038/s41467-018-03732-9 is OK
- 10.1038/s41598-020-75445-3 is OK
- 10.1007/s00382-019-04707-2 is OK
- 10.1038/s43017-020-0068-4 is OK
- 10.1146/annurev-marine-032720-095144 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.7717/peerj.453 is OK
- 10.5334/jors.148 is OK
- 10.1029/2020GL090661 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03930/joss.03930/10.21105.joss.03930.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03930/joss.03930/10.21105.joss.03930.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@hscannell – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@hscannell Unfortunately, after a scope review by the JOSS editorial board, it was determined that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  

At this point we will proceed to reject this submission. 

Note that this rejection does not mean the software is not useful or not function or poorly made. It merely means that given its size it is currently out of scope for JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work. Alternatively you may also consider a re-submission if this work is substantially expanded in terms of functionality and magnitude of scholarly effort.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by hscannell** [comment]
We appreciate the consideration @Kevin-Mattheus-Moerman and hope a re-submission is possible in the future. Thanks!
