### ISSUE TITLE
[PRE REVIEW]: IVY Plot: Enhancing a Dot Plot by Representing Observations as Leaflets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3931]
**Submitting author:** @tringuyen2023 (<a href="http://orcid.org/0000-0002-1253-9404">Tri Nguyen</a>)
**Repository:** <a href="https://github.com/tringuyen2023/IVYplot-Journal.git" target ="_blank">https://github.com/tringuyen2023/IVYplot-Journal.git</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/584039f22ffa6d90b55f05cb14f41f65/status.svg)](https://joss.theoj.org/papers/584039f22ffa6d90b55f05cb14f41f65)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/584039f22ffa6d90b55f05cb14f41f65"><img src="https://joss.theoj.org/papers/584039f22ffa6d90b55f05cb14f41f65/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/584039f22ffa6d90b55f05cb14f41f65/status.svg)](https://joss.theoj.org/papers/584039f22ffa6d90b55f05cb14f41f65)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tringuyen2023. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@tringuyen2023 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (467.8 files/s, 86665.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              2             88              9            390
R                                1              2              2              2
Rmd                              1             29            217              2
-------------------------------------------------------------------------------
SUM:                             4            119            228            394
-------------------------------------------------------------------------------


Statistical information for the repository '4dffcb63a69128148b8470ca' was
gathered on 2021/11/19.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #3931 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon reject

@tringuyen2023 – I'm rejecting this submission as:

- It does not appear to be prepared for JOSS (see our [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html))
- There is no software associated with the submission.
- There is no open source license.

Please read our [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) and resubmit if you believe this decision has been made in error.

**Comment by whedon** [comment]
Paper rejected.
