### ISSUE TITLE
[PRE REVIEW]: Hyperas: Simple Hyperparameter Tuning for Keras Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3933]
**Submitting author:** @maxpumperla (<a href="http://orcid.org/0000-0002-7801-4184">Max Pumperla</a>)
**Repository:** <a href="https://github.com/maxpumperla/hyperas" target ="_blank">https://github.com/maxpumperla/hyperas</a>
**Version:** 0.4.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/812e0d30558c86eb53656b7e6b0a39af/status.svg)](https://joss.theoj.org/papers/812e0d30558c86eb53656b7e6b0a39af)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/812e0d30558c86eb53656b7e6b0a39af"><img src="https://joss.theoj.org/papers/812e0d30558c86eb53656b7e6b0a39af/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/812e0d30558c86eb53656b7e6b0a39af/status.svg)](https://joss.theoj.org/papers/812e0d30558c86eb53656b7e6b0a39af)
```

**Author instructions**

Thanks for submitting your paper to JOSS @maxpumperla. **Currently, there isn't an JOSS editor assigned** to your paper.

@maxpumperla if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 583

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (666.6 files/s, 66202.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          20            321            214           1416
Markdown                         3            101              0            319
Jupyter Notebook                 2             10            304             64
TeX                              1              5              0             52
YAML                             2              1              1             36
INI                              1              4              0             32
-------------------------------------------------------------------------------
SUM:                            29            442            519           1919
-------------------------------------------------------------------------------


Statistical information for the repository 'd8524686c4a255c6becb655d' was
gathered on 2021/11/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AHoke                            2           127             10            3.62
Ambros94                         1            87              0            2.30
CyberZHG                         1           103             11            3.02
Deepali Jain                     1             3              0            0.08
Emmanuel Kahembwe                5            14             13            0.71
Jonathan Mackenzie               7           143             45            4.97
Jonathan Owen                    4            45             17            1.64
Li Shen                          1             9              0            0.24
Matthias Winkelmann              4            77             13            2.38
Max Pumperla                    56          1619            618           59.18
Michael Norris                   2             8              4            0.32
Philipp Kainz                   12           259             77            8.89
Sohan Jain                       7           102             63            4.37
haramoz                          2           147             17            4.34
maxpumperla                      6           126             21            3.89
michaele4343                     1             1              1            0.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AHoke                       112           88.2         31.4                0.89
Ambros94                     85           97.7         32.5                7.06
CyberZHG                    103          100.0         15.2                3.88
Deepali Jain                  3          100.0         28.4                0.00
Emmanuel Kahembwe             9           64.3         37.3                0.00
Jonathan Mackenzie           94           65.7         13.2                3.19
Jonathan Owen                34           75.6         30.1                0.00
Matthias Winkelmann           7            9.1         36.4                0.00
Max Pumperla               1150           71.0         36.4                2.35
Michael Norris                6           75.0         30.3                0.00
Philipp Kainz               214           82.6         30.2                7.01
Sohan Jain                    3            2.9         39.3                0.00
haramoz                     130           88.4         15.6                1.54
michaele4343                  1          100.0         18.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03933/joss.03933/10.21105.joss.03933.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03933/joss.03933/10.21105.joss.03933.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@maxpumperla thanks for this submission. I have just flagged this work for additional scope review by our editorial board. This is normal for submissions of this sizes and should take about 1-2 weeks.

**Comment by maxpumperla** [comment]
@Kevin-Mattheus-Moerman thanks for letting me know!

**Comment by kthyng** [comment]
@maxpumperla I'm sorry to say that this has been deemed to be out of scope in terms of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort), partly because the number of lines of code that are tied directly to function instead of tests and examples is relatively low (by my count, around 500). This is by no means a commentary on the usefulness of your software. We would invite a resubmission if, for example, the scope of this work were to expand. Alternatively, we have some guidance on other ways to publish your work here: https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by maxpumperla** [comment]
@kthyng yeah, you have to measure something. `lots of code == substantial` is a choice I guess I have to respect.

but you do understand that hyperas has been cited many times, right? https://scholar.google.de/scholar?hl=de&as_sdt=0%2C5&q=hyperas+keras&btnG= People try to cite it all the time, but can't do it properly just yet. This was an effort to submit a paper that has _substantial_ impact on the community.
