### ISSUE TITLE
[PRE REVIEW]: Castor: A C++ library to code “à la matlab”

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3936]
**Submitting author:** @matthieuaussal (<a href="http://orcid.org/0000-0002-2812-7578">Matthieu Aussal</a>)
**Repository:** <a href="https://gitlab.labos.polytechnique.fr/leprojetcastor/joss_paper" target ="_blank">https://gitlab.labos.polytechnique.fr/leprojetcastor/joss_paper</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9dcd5e0b7d2b73de3e34c0ce5dc29cf0/status.svg)](https://joss.theoj.org/papers/9dcd5e0b7d2b73de3e34c0ce5dc29cf0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9dcd5e0b7d2b73de3e34c0ce5dc29cf0"><img src="https://joss.theoj.org/papers/9dcd5e0b7d2b73de3e34c0ce5dc29cf0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9dcd5e0b7d2b73de3e34c0ce5dc29cf0/status.svg)](https://joss.theoj.org/papers/9dcd5e0b7d2b73de3e34c0ce5dc29cf0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @matthieuaussal. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @danielskatz.

@matthieuaussal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 2074

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (273.3 files/s, 49740.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         1             61              0            236
TeX                              1              9              0             58
-------------------------------------------------------------------------------
SUM:                             2             70              0            294
-------------------------------------------------------------------------------


Statistical information for the repository 'f85603bcaeaf46a12eaf52ec' was
gathered on 2021/11/19.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1145/2049662.2049663 may be a valid DOI for title: The University of Florida sparse matrix collection
- 10.1109/icme.2012.93 may be a valid DOI for title: Creating the Sydney York morphological and acoustic recordings of ears database
- 10.1109/38.865875 may be a valid DOI for title: Visualizing with VTK: a tutorial

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3936 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.330 ...url{matthieu.aussal@polytechnique.edu}}}}

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@matthieuaussal  – thanks for your submission to JOSS. Please resubmit with the JOSS paper within the `Castor` source code repository. Please note, the paper can be in a separate branch that doesn't get merged into the main branch.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
