### ISSUE TITLE
[PRE REVIEW]: epwshiftr: Create future EnergyPlus Weather files using CMIP6 data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3942]
**Submitting author:** @hongyuanjia (<a href="http://orcid.org/0000-0002-0075-8183">Hongyuan Jia</a>)
**Repository:** <a href="https://github.com/ideas-lab-nus/epwshiftr" target ="_blank">https://github.com/ideas-lab-nus/epwshiftr</a>
**Version:** v0.1.3
**Editor:** @KristinaRiemer
**Reviewers:** @mitmat, @bczernecki
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/794e8707a0bd5b38777d514650a0fd65/status.svg)](https://joss.theoj.org/papers/794e8707a0bd5b38777d514650a0fd65)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/794e8707a0bd5b38777d514650a0fd65"><img src="https://joss.theoj.org/papers/794e8707a0bd5b38777d514650a0fd65/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/794e8707a0bd5b38777d514650a0fd65/status.svg)](https://joss.theoj.org/papers/794e8707a0bd5b38777d514650a0fd65)
```

**Author instructions**

Thanks for submitting your paper to JOSS @hongyuanjia. **Currently, there isn't an JOSS editor assigned** to your paper.

@hongyuanjia if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 709

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (552.2 files/s, 108739.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               13            474           1065           2455
SVG                              1              1              1            743
Markdown                        10            149              0            667
YAML                             6             44              2            285
TeX                              1             12              0            168
Rmd                              1             69            106             61
-------------------------------------------------------------------------------
SUM:                            32            749           1174           4379
-------------------------------------------------------------------------------


Statistical information for the repository '0ddf90afa7d69707f51e5d17' was
gathered on 2021/11/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/buildings9070166 is OK
- 10/b4n9qc is OK
- 10.5194/gmd-9-1937-2016 is OK
- 10.5194/gmd-9-3461-2016 is OK
- 10.1016/s0378-7788(00)00114-6 is OK
- 10/b4z2gp is OK
- 10.18637/jss.v059.i10 is OK
- 10.1016/j.enbuild.2021.110757 is OK

MISSING DOIs

- 10.1016/0927-0248(95)80019-0 may be a valid DOI for title: 38th European Photovoltaic Solar Energy Conference and Exhibition

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03942/joss.03942/10.21105.joss.03942.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03942/joss.03942/10.21105.joss.03942.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @timtroendle as editor

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by timtroendle** [comment]
I am sorry but I cannot edit one more paper at this point.

**Comment by Kevin-Mattheus-Moerman** [comment]
@timtroendle okay, no worries, thanks for getting back to me.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedeon invite @KristinaRiemer as editor

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
Hi @hongyuanjia! I'm looking for reviewers for your submission now, specifically for folks who have expertise in both R and the relevant domain of your submission. Do you have any suggestions for who I could reach out to that fulfills both of those aspects?

**Comment by hongyuanjia** [comment]
Hi @KristinaRiemer.

First, thank you for accepting as the editor for my submission!

I went through [the list of JOSS reviewers](https://bit.ly/joss-reviewers) but did not find any R experts that work on this topic. I list folks that work on a similar topic but use python ([znicholls](https://github.com/znicholls)) or R experts that may be a good match for this review, based on their GitHub record. See: https://github.com/openjournals/joss-reviews/issues/3942#issuecomment-975627753

Also, I searched all available CRAN packages and found developers below who worked on similar topics and maybe a good suit for this review. But since they are not on the JOSS reviewer list, I am not sure whether they are available/willing for doing this review.

- Michael Sumner ([mdsumner](https://github.com/mdsumner)): Spatial expert and the developer of a number of famous R spatial packages.
- Michael Matiu ([mitmat](https://github.com/mitmat)):  [eurocordexr](https://cran.r-project.org/package=eurocordexr) maintainer.
- Blake Seers ([blasee](https://github.com/blasee)): [clifro](https://cran.r-project.org/package=clifro) maintainer
- Bartosz Czernecki ([bczernecki](https://github.com/bczernecki)): [climate](https://cran.r-project.org/package=climate) maitainer
- Hernando Cortina ([cortinah](https://github.com/cortinah)): [hockeystick](https://cran.r-project.org/package=hockeystick) maintainer

**Comment by KristinaRiemer** [comment]
Luckily, we are not limited to the JOSS reviewer list, that list is just a good place to start. Anyone who feels they have the right skill set (and no conflict of interest with the authors) can be a reviewer.

I've reached out to a few folks and I'll use your list too. Thanks!

**Comment by hongyuanjia** [comment]
@KristinaRiemer Any updates on the reviewing process? Thanks

**Comment by KristinaRiemer** [comment]
Hi @hongyuanjia, thanks for checking in. I've reached out to some folks with more domain expertise, but haven't had much luck. I've also contacted the possible reviewers you've suggested above and am waiting to hear back from them. I'll keep you up to date! 

Just so you know, I'm going to be on vacation December 23 to January 2, but I'll continue to work on finding reviewers and getting the review of your submission started during that time period!

**Comment by hongyuanjia** [comment]
Thanks @KristinaRiemer . Much appreciated!

**Comment by KristinaRiemer** [comment]
@whedon assign @mitmat as reviewer

**Comment by whedon** [comment]
OK, @mitmat is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon add @bczernecki as reviewer

**Comment by whedon** [comment]
OK, @bczernecki is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4030.

**Comment by KristinaRiemer** [comment]
Hi @mitmat and @bczernecki! Thank you again for agreeing to review this JOSS submission. The review itself will happen in the GitHub issue linked to above. Feel free to let me know if you have questions about this process or the submission there.
