### ISSUE TITLE
[PRE REVIEW]: Rainbow: Automated Air-Liquid Interface Cell Culture Analysis Using Deep Optical Flow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3944]
**Submitting author:** @AlphonsG (<a href="http://orcid.org/0000-0002-9607-2839">Alphons Gwatimba</a>)
**Repository:** <a href="https://github.com/AlphonsG/Rainbow-Optical-Flow-For-ALI" target ="_blank">https://github.com/AlphonsG/Rainbow-Optical-Flow-For-ALI</a>
**Version:** 0.1.0
**Editor:** @jmschrei
**Reviewers:** @tpeulen, @Assistedevolution
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f1d97af6910c2dfffc3b1e396b70541f/status.svg)](https://joss.theoj.org/papers/f1d97af6910c2dfffc3b1e396b70541f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f1d97af6910c2dfffc3b1e396b70541f"><img src="https://joss.theoj.org/papers/f1d97af6910c2dfffc3b1e396b70541f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f1d97af6910c2dfffc3b1e396b70541f/status.svg)](https://joss.theoj.org/papers/f1d97af6910c2dfffc3b1e396b70541f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AlphonsG. **Currently, there isn't an JOSS editor assigned** to your paper.

@AlphonsG if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3944 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.49 s (67.8 files/s, 39851.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1           1778              2          13273
Python                          21            366            371           1013
Jupyter Notebook                 4              0           2042            195
Markdown                         3             81              0            134
YAML                             3             18             48             84
JSON                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            33           2243           2463          14705
-------------------------------------------------------------------------------


Statistical information for the repository '462bb500a67f0353dcaa5b14' was
gathered on 2021/11/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alphons                        104          4421           1049          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alphons                    1750           39.6          0.6                7.54
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch dev

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dev. Reticulating splines etc...
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@AlphonsG I am using the correct branch there, i.e. `dev` to generate the paper from?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03944/joss.03944/10.21105.joss.03944.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03944/joss.03944/10.21105.joss.03944.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jmschrei as editor

**Comment by whedon** [comment]
@jmschrei has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jmschrei from the available editors this seems most aligned with your expertise, are you able to help edit?

**Comment by AlphonsG** [comment]
> @AlphonsG I am using the correct branch there, i.e. `dev` to generate the paper from?

Hello @Kevin-Mattheus-Moerman, nice to virtually meet you. I have merged `dev` with the main branch so please use the main branch to review the paper and software. Apologies for forgetting to merge.

**Comment by AlphonsG** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03944/joss.03944/10.21105.joss.03944.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03944/joss.03944/10.21105.joss.03944.pdf) :page_facing_up: :point_left:

**Comment by AlphonsG** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by AlphonsG** [comment]
May I also suggest Shihao Jiang as a potential reviewer (email address shihao.jiang@anu.edu.au, GitHub username zacjiang).

**Comment by jmschrei** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jmschrei

**Comment by jmschrei** [comment]
@ivergara and @tpeulen would either of you be available to review this submission?

**Comment by tpeulen** [comment]
I am available and agree to review this submission.

**Comment by jmschrei** [comment]
@whedon assign @tpeulen as reviewer

**Comment by whedon** [comment]
OK, @tpeulen is now a reviewer

**Comment by jmschrei** [comment]
@ebezzam would you be available to review this submission? Thanks!

**Comment by ebezzam** [comment]
hi @jmschrei sorry won't be available for this one!

**Comment by jmschrei** [comment]
No problem. @Subho07 would you be able to review this submission?

**Comment by Subho07** [comment]
Hi @jmschrei I am sorry I do not have expertise in this area of research

**Comment by jmschrei** [comment]
No problem. @jenzopr would you be able to review this submission?

**Comment by jmschrei** [comment]
Hi @abhishekbajpayee, would you be able to review this submission?

**Comment by jenzopr** [comment]
> No problem. @jenzopr would you be able to review this submission?

Currently no. I'm sorry :-(

**Comment by jmschrei** [comment]
Hi @Narayana-Rao, would you be able to review this submission?

**Comment by Narayana-Rao** [comment]
Hi @jmschrei, 
Thanks for considering me, but I am sorry, I am not an expert in this field.

**Comment by AlphonsG** [comment]
Hello,

May I suggest Sarada Lee (leesarada@gmail.com) and Sean Driver (sean@assistedevolution.net) who both have github accounts and experience in the field. Here is a recent publication of theirs: 

https://pubmed.ncbi.nlm.nih.gov/34413367/

**Comment by jmschrei** [comment]
Thanks @AlphonsG. I'm going to try a few more people.

@afrubin or @Scivision, would either of you be able to review this submission?

**Comment by slee5777** [comment]
> Hello,
> 
> May I suggest Sarada Lee ([leesarada@gmail.com](mailto:leesarada@gmail.com)) and Sean Driver ([sean@assistedevolution.net](mailto:sean@assistedevolution.net)) who both have github accounts and experience in the field. Here is a recent publication of theirs:
> 
> https://pubmed.ncbi.nlm.nih.gov/34413367/

Could you remove Sean and my personal email addresses?  We don't want them to make public.

**Comment by YuliyaLab** [comment]
Hello @jmschrei ,
possible to get an estimate on the turn around time on the review? One of the co-authors here. Is this not the right avenue for our software paper? Can you please consider AlphonsG's suggestion above for the reviewer to speed things up? 
Many thanks!
Yuliya

**Comment by jmschrei** [comment]
Hi @YuliyaLab. Sorry for the delay in getting reviewers. I haven't had this amount of difficulty in getting reviewers in any of the other submissions I've handled -- I think part of the challenge was the holiday break. I'm going to reach out to a few more people tomorrow and see if I can find reviewers. Generally, I don't like to ask people that are recommended by the authors because I don't know what their connections to the author are.

**Comment by YuliyaLab** [comment]
Hi @jmschrei, appreciate you searching for reviewers! We understand there could be issues with connections...
Suggested reviewers run Perth Machine Learning Group and had a paper in automated (AI-based) cell counting. 
Thanks!

**Comment by jmschrei** [comment]
I talked about this paper with the other editors and they think it's worth pursuing the names you've recommended. @zacjiang, @slee5777, @assistedevolution, would either of you be able to review this submission? Thanks, and sorry for the earlier inconvenience regarding your emails.

**Comment by Assistedevolution** [comment]
I am happy to review this.. 

Can you point me a quick overview of your Github based review process?

**Comment by jmschrei** [comment]
Great! I'll get the process started. That'll create a new issue with instructions.

**Comment by jmschrei** [comment]
@whedon add @Assistedevolution as reviewer

**Comment by whedon** [comment]
OK, @Assistedevolution is now a reviewer

**Comment by jmschrei** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4080.
