### ISSUE TITLE
[PRE REVIEW]: Castor: A C++ library to code "à la matlab"

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3945]
**Submitting author:** @matthieuaussal (<a href="http://orcid.org/0000-0002-2812-7578">Matthieu Aussal</a>)
**Repository:** <a href="https://github.com/leprojetcastor/castor" target ="_blank">https://github.com/leprojetcastor/castor</a>
**Version:** v1.0.0
**Editor:** @jbytecode
**Reviewers:** @mkitti, @junliu2050
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/758f31f8f400959b11a18cf5f7a5d04f/status.svg)](https://joss.theoj.org/papers/758f31f8f400959b11a18cf5f7a5d04f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/758f31f8f400959b11a18cf5f7a5d04f"><img src="https://joss.theoj.org/papers/758f31f8f400959b11a18cf5f7a5d04f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/758f31f8f400959b11a18cf5f7a5d04f/status.svg)](https://joss.theoj.org/papers/758f31f8f400959b11a18cf5f7a5d04f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @matthieuaussal. **Currently, there isn't an JOSS editor assigned** to your paper.

@matthieuaussal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1145/2049662.2049663 may be a valid DOI for title: The University of Florida sparse matrix collection
- 10.1109/icme.2012.93 may be a valid DOI for title: Creating the Sydney York morphological and acoustic recordings of ears database
- 10.1109/38.865875 may be a valid DOI for title: Visualizing with VTK: a tutorial

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (388.6 files/s, 202136.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     7           3977           6283          22256
C++                             12            385            365           2080
reStructuredText                46           2015           2742           1332
Markdown                         2             63              0            239
CMake                            8             40             19            149
TeX                              1              9              0             58
YAML                             2              9              8             46
Python                           1              4              1             15
CSS                              1              2              0             11
make                             1              4              7             10
-------------------------------------------------------------------------------
SUM:                            81           6508           9425          26196
-------------------------------------------------------------------------------


Statistical information for the repository 'c9d7348d11ce970a392b467e' was
gathered on 2021/11/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
@marc.bakry                      1             8              8            0.04
Antoine RIDEAU                   1             1              1            0.00
Marc                             5           140              7            0.33
Matthieu Aussal                 33          4056           1918           13.29
Series Laurent                   5         35796           2680           85.58
U-INTRA\MB264355                 1           180              0            0.40
U-INTRA\mb264355                 7           135             31            0.37

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
@marc.bakry                   6           75.0         12.7              100.00
Antoine RIDEAU                1          100.0          4.8                0.00
Marc                        105           75.0         10.2                9.52
Matthieu Aussal            2667           65.8          9.6               27.78
Series Laurent            32503           90.8          0.5               18.13
U-INTRA\mb264355             84           62.2         11.9               23.81
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3945 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.330 ...url{matthieu.aussal@polytechnique.edu}}}}

Looks like we failed to compile the PDF

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3945 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.330 ...url{matthieu.aussal@polytechnique.edu}}}}

Looks like we failed to compile the PDF

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what is wrong with the paper :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jbytecode as editor

**Comment by whedon** [comment]
@jbytecode has been invited to edit this submission.

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by matthieuaussal** [comment]
Hi, 

Can we do something to help you?

M. Aussal & L. Series

**Comment by jbytecode** [comment]
Dear @matthieuaussal - maybe you can use [https://whedon.theoj.org/](https://whedon.theoj.org/) to debug your md file and make it successfully compiled to pdf.

**Comment by xuanxu** [comment]
The PDF is not compiling due to unscaped characters. [This change](https://github.com/leprojetcastor/castor/pull/1) should fix it.

**Comment by jbytecode** [comment]
Dear @matthieuaussal, please apply the pull request that @xuanxu sent then ping me.

**Comment by matthieuaussal** [comment]
@xuanxu <https://github.com/xuanxu> merge accepted, is it ok?

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03945/joss.03945/10.21105.joss.03945.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03945/joss.03945/10.21105.joss.03945.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
👋👋👋 Dear @amadeusine  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "Castor: A C++ library to code "à la matlab". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3945).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
👋👋👋 Dear @jingnanshi  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "Castor: A C++ library to code "à la matlab". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3945).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
👋👋👋 Dear @mewilhel  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "Castor: A C++ library to code "à la matlab". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3945).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
Dear @matthieuaussal

Do you have any suggestions for potential reviewers? You can also use the list [here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822).
Please mention the GitHub users without using the @ character. 

Thank you in advance.

**Comment by matthieuaussal** [comment]
Dear Editor,

We can suggest @agramfort, wich is a colleague from INRIA. 

Otherwise, from your list, we check people both in Matlab and C++ preferred langage, with a numerical background  : 

Applied math :
@junliu2050
@rosoport
@faroukm
@pitsianis
@rosoport
 
Others (signal processing, mechanics, etc.):
@greatv
@hasantahir
@florian-rosenthal
@somefunagba
@declanol
@ononak
@WalBytes
@AdeBytes

Is it ok for you?

Best, 

Matthieu

**Comment by jbytecode** [comment]
👋👋👋 @junliu2050 @rosoport 👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "Castor: A C++ library to code "à la matlab". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3945).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by agramfort** [comment]
I feel I am too close to @matthieuaussal who is working in the same
institution as me

>

**Comment by jbytecode** [comment]
@agramfort thank you for the response. Hope to work together in other submissions in the future.

**Comment by jbytecode** [comment]
@whedon add @mkitti as reviewer

**Comment by whedon** [comment]
OK, @mkitti is now a reviewer

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03945/joss.03945/10.21105.joss.03945.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03945/joss.03945/10.21105.joss.03945.pdf) :page_facing_up: :point_left:

**Comment by mkitti** [comment]
I'm not clear if there is a rendering issue or not, but the figures appear to lack captions.

**Comment by jbytecode** [comment]
@mkitti when the review starts, you can address this issue again so the authors corrects the paper so that the figures are linked to the caption.

**Comment by junliu2050** [comment]
Hi, thanks for inviting me. I guess I can try to provide some feedback
based on my background in scientific computing.
Will the review process be anonymous or not? I think I like the idea of
JOSS, but never had any experience with it yet.

**Comment by jbytecode** [comment]
@whedon add @junliu2050 as reviewer

Dear @junliu2050,

The reviewing process will be open and registered. Reviewers use their github usernames as their identity and they are also registered in the paper.

thank you for accepting our invitation.

**Comment by whedon** [comment]
OK, @junliu2050 is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3965.

**Comment by matthieuaussal** [comment]
@mkitti we forget to define captions, sorry for that. It’s now done!

**Comment by jbytecode** [comment]
@matthieuaussal this is the pre-review issue, all issues belong to the paper review is discussed and reported in the review issue.

**Comment by matthieuaussal** [comment]
So we do not make any changes until the review report has been sent? (it’s my first submission in joss)

**Comment by jbytecode** [comment]
@matthieuaussal please use https://github.com/openjournals/joss-reviews/issues/3965, this issue was closed after we assigned reviewers.

**Comment by rosoport** [comment]
Hi, should be possible I would like to assist in reviewing the paper.
Kind Regards
Rodrigo Portugal

**Comment by jbytecode** [comment]
@rosoport thank you for your response, however, we have already assigned two reviewers to this submission. Hope we work together in the future.

**Comment by junliu2050** [comment]
Hi, after carefully reading through the paper, I feel I may not be very
suitable for reviewing such a library since I do not use or develop a
similar package by myself.
Hence you may assign Rodrigo Portugal as 2nd reviewer. Overall it is an
interesting package, but the examples and comparison with similar packages
can be improved.

**Comment by jbytecode** [comment]
@rosoport - this is an update, I invited you again as the 2nd reviewer. Please accept if you still want to review this submission. Here is the review link: https://github.com/openjournals/joss-reviews/issues/3965 . thank you.
