### ISSUE TITLE
[PRE REVIEW]: METASnake: A Snakemake Workflow to facilitate automated processing of metagenomic data through the metaWRAP pipeline

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3946]
**Submitting author:** @jkrapohl (<a href="http://orcid.org/0000-0003-0364-6387">John Krapohl</a>)
**Repository:** <a href="https://github.com/jkrapohl/METASnake" target ="_blank">https://github.com/jkrapohl/METASnake</a>
**Version:** 1.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/07798c77d300fcf8e057db98702ca7fa/status.svg)](https://joss.theoj.org/papers/07798c77d300fcf8e057db98702ca7fa)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/07798c77d300fcf8e057db98702ca7fa"><img src="https://joss.theoj.org/papers/07798c77d300fcf8e057db98702ca7fa/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/07798c77d300fcf8e057db98702ca7fa/status.svg)](https://joss.theoj.org/papers/07798c77d300fcf8e057db98702ca7fa)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jkrapohl. **Currently, there isn't an JOSS editor assigned** to your paper.

@jkrapohl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 455

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.12688/f1000research.29032.2 is OK
- 10.1186/s40168-018-0541-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (457.3 files/s, 33000.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Bourne Shell                     2             50             56            141
Markdown                         2             34              0             67
TeX                              1              1              0             22
YAML                             1             12             36             14
-------------------------------------------------------------------------------
SUM:                             6             97             92            244
-------------------------------------------------------------------------------


Statistical information for the repository '9e2265a2afa72c654195b535' was
gathered on 2021/11/23.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03946/joss.03946/10.21105.joss.03946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03946/joss.03946/10.21105.joss.03946.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@jkrapohl thanks for this submission. Unfortunately this work is not substantial enough, in terms of code content, and therefore does not match our [substantial scholarly effort criteria](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). I will therefore proceed to reject this submission at this point. 

Note that rejection does not mean the software is not useful, not functional, or not well prepared. Rejection here merely means this work is not in scope  as it stands for JOSS. Also, we would welcome potential future submissions or re-submissions, that are more substantial.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
