### ISSUE TITLE
[PRE REVIEW]: dumux-sediment: A fully implicit framework for bedload transport simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3949]
**Submitting author:** @MartinBAW (<a href="http://orcid.org/0000-0002-2303-0662">Martin Utz</a>)
**Repository:** <a href="https://git.iws.uni-stuttgart.de/dumux-appl/dumux-sediment" target ="_blank">https://git.iws.uni-stuttgart.de/dumux-appl/dumux-sediment</a>
**Version:** 1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2cbb2aad2b05de541d70582626708944/status.svg)](https://joss.theoj.org/papers/2cbb2aad2b05de541d70582626708944)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2cbb2aad2b05de541d70582626708944"><img src="https://joss.theoj.org/papers/2cbb2aad2b05de541d70582626708944/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2cbb2aad2b05de541d70582626708944/status.svg)](https://joss.theoj.org/papers/2cbb2aad2b05de541d70582626708944)
```

**Author instructions**

Thanks for submitting your paper to JOSS @MartinBAW. **Currently, there isn't an JOSS editor assigned** to your paper.

@MartinBAW if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1196

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s00607-008-0004-9 is OK
- 10.1016/j.advwatres.2011.05.002 is OK
- 10.5169/seals-83975 is OK
- 10.1016/j.camwa.2020.02.012 is OK

MISSING DOIs

- 10.1007/978-3-662-48342-8 may be a valid DOI for title: Press/Siever Allgemeine Geologie

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (649.6 files/s, 203948.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              3              0              0           9300
C/C++ Header                    17            209            917            941
Markdown                         3            153              0            715
Python                           2             39             40            130
CMake                           14             24             19            113
C++                              1             35             47            100
TeX                              1             17              1             73
-------------------------------------------------------------------------------
SUM:                            41            477           1024          11372
-------------------------------------------------------------------------------


Statistical information for the repository '3ca71342764acb26713c7ab0' was
gathered on 2021/11/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bernd Flemisch                   1             2              2            0.01
Leopold Stadler                  8            69             44            0.28
Martin Utz                     243         21300          18863           99.40
leopold.stadler                  6            60             64            0.31

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Leopold Stadler              32           46.4          6.5               62.50
Martin Utz                 2426           11.4         14.7               40.48
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03949/joss.03949/10.21105.joss.03949.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03949/joss.03949/10.21105.joss.03949.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@MartinBAW thanks for this submission. I have just flagged this submission for a scope review by our editorial board. This means that we shall determine if this in in scope in terms of the size and functionality this submissions offers (see also our criteria around ["substantial scholarly effort"](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)). This is standard for submissions of this size and should take about 2 weeks to complete. Thanks for your patience.

**Comment by danielskatz** [comment]
@MartinBAW - We've decided that JOSS will not review this submission because the technical contribution appears to be an HLL Riemann solver and a couple other closures that plug into the framework. The "library" part is about 600 LOC, plus another 400 for an example driver. It doesn't really have unit tests and could use better documentation. We're also unsure about why domain-specific QoI, boundaries, etc. are missing, though maybe that's somehow generic with DUNE/DuMux. If more work/functionality is put into this in the future, please feel free to resubmit it, and mention this issue (`https://github.com/openjournals/joss-reviews/issues/3949`) at that time.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
