### ISSUE TITLE
[PRE REVIEW]: Xbim.Essentials: a library for interoperable building information applications

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#395]
**Submitting author:** @CBenghi (<a href="http://orcid.org/0000-0003-3252-5461">Claudio Benghi</a>)
**Repository:** <a href="https://github.com/xBimTeam/XbimEssentials" target ="_blank">https://github.com/xBimTeam/XbimEssentials</a>
**Version:** 4.0
**Editor:** @arfon
**Reviewer:** @Haacked

**Author instructions**

Thanks for submitting your paper to JOSS @CBenghi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@CBenghi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by CBenghi** [comment]
Hello @arfon, 
thanks for your comment, I had concerns about this aspect as well, but reading again in your guidelines the parts that apply are highlighted as follows:

"JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, **engineering**); supports the functioning of research instruments or the execution of research experiments; **extracts knowledge from large data sets**; offers a mathematical library, or similar."

The libriary offers the ability to extract information from construction projects, and it's been used in the past to enable research projects on carbon assessment and several other aspects of construction management and construction engineering. It has also served in the areas of information science (I know at least of three publications in [Advanced Engineering Informatics](https://www.journals.elsevier.com/advanced-engineering-informatics) that have used it for their work, but in absence of a formal publication the usage has (sadly) not been acknowledged. 

Unfortunately construction engineering publications have sometimes lower standards than other branches on this front, but my hope was that through Joss some of this might improve.

I have provided in the paper a list of government sponsored research projects, that this library supports, how can I complement this info to match the requirements?

Thanks,
Claudio

**Comment by CBenghi** [comment]
I've read the requirements again and spotted omissions, I'm going to amend the paper and inform you when an update is available for consideration.

**Comment by arfon** [comment]
> I've read the requirements again and spotted omissions, I'm going to amend the paper and inform you when an update is available for consideration.

Excellent, many thanks!

**Comment by CBenghi** [comment]
Hello @arfon,
I've revised the structure of the paper to explicit the areas of research that could benefit from the software and clarify the features.
I've also re-framed the rest of the paper to prioritise the abstract capabilities rather than API implementation.

I hope you'll find the changes sufficient to progress to review.

Best,
Claudio

**Comment by arfon** [comment]
> I hope you'll find the changes convincing to progress to review.

Many thanks for these updates @CBenghi. Before we can move to review we'll need to have one of the @openjournals/joss-editors to volunteer to edit this submission.

In the meantime, if you have any suggestions for potential reviewers please mention them here.

**Comment by CBenghi** [comment]
Thanks for your note, @arfon.

Having had a look at the list of editors I am uncertain about ideal reviewer.

I haven't spotted anybody with a connected research background or anyone with a c# or .net repository on their github page.

If you can find any volunteer I'd be happy to guide them meticulously through any technical hurdles.

I'm confident that the project is set up to production standards. As long as they have access to Visual studio, building and testing the solution, as well as installing the binaries as a dependency for setting up custom analysis scenarios, should take only a few moments. 

For any future needs, of course, I'd be happy to volunteer for the review of engineering related submissions or .Net implementations.

**Comment by CBenghi** [comment]
Hello @arfon,

I've looked again at the list of editors and (looking at all individual github pages) you seem to be short on .Net Platform reviewers. 
I might be wrong, but I expect a resurgence of .Net now that the new cross platform core 2.0 is out.

If I manage to find a volunteers with an established .Net background (e.g. .net foundation or otherwise active in the open-source net ecosystem) would you accept their review?

Should they have academic research background?
Thanks,
Claudio

**Comment by arfon** [comment]
> I've looked again at the list of editors and (looking at all individual github pages) you seem to be short on .Net Platform reviewers.

Yes, that's definitely true! Feel free to suggest some potential reviewers and we'll see what we can do.

**Comment by CBenghi** [comment]
@arfon,
I've tried with no luck to get a suitable reviewer, but I'm not finding it easy.

I'll propose a different path. 
I can take you (or your preferred editor) through the hurdles of the .Net technology for the review of Xbim.Essentials and thereafter I'll take care of any other .Net reviews that might be submitted.

All it takes is a Windows machine, and a little time. Visual Studio is free and installs relatively fast in the latest version. All other dependencies needed are downloaded automatically once you have the code downloaded from Github.

I'm quite keen on this, I'd be happy to support the review with custom videos or any questions you might have along the way.

Would this be possible?

**Comment by arfon** [comment]
> All it takes is a Windows machine, and a little time. Visual Studio is free and installs relatively fast in the latest version. All other dependencies needed are downloaded automatically once you have the code downloaded from Github.

I wouldn't be able to do this sorry. Would any of the @openjournals/joss-editors be able to do this?

**Comment by Haacked** [comment]
Hey @arfon! It's been a long time. I've been asked to review this project as a subject matter expert in .NET and I was happy to see your involvement.

I'm happy to help review this. Just let me know next steps.

**Comment by arfon** [comment]
Hey Phil! Nice to see you here :-)

It would be great to have you review this submission for us. Hopefully the process should be relatively smooth and straightforward. Also, it all happens right here on GitHub. I'll issue a few commands to our robot @whedon and we should be in good shape to get started.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @Haacked as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Haacked

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/473. Feel free to close this issue now!

**Comment by arfon** [comment]
@Haacked when you get a chance, please head over to #473 where the actual review of this submission should take place.
