### ISSUE TITLE
[PRE REVIEW]: ASGarD: Adaptive Sparse Grid Discretization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3953]
**Submitting author:** @quantumsteve (<a href="http://orcid.org/0000-0002-2018-7904">Steven Hahn</a>)
**Repository:** https://github.com/project-asgard/asgard
**Branch with paper.md** (empty if default branch): 
**Version:** v0.4.0
**Editor:** @arfon
**Reviewers:** @joglekara, @drobnyjt, @cticenhour
**Managing EiC:** Kevin M. Moerman

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/dbc8b3d352b73a460d8cc57f1de1debf/status.svg)](https://joss.theoj.org/papers/dbc8b3d352b73a460d8cc57f1de1debf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dbc8b3d352b73a460d8cc57f1de1debf"><img src="https://joss.theoj.org/papers/dbc8b3d352b73a460d8cc57f1de1debf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dbc8b3d352b73a460d8cc57f1de1debf/status.svg)](https://joss.theoj.org/papers/dbc8b3d352b73a460d8cc57f1de1debf)
```

**Author instructions**

Thanks for submitting your paper to JOSS @quantumsteve. **Currently, there isn't an JOSS editor assigned** to your paper.

@quantumsteve if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3953 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.74 s (156.4 files/s, 78157.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    42           4443           2605          24659
C++                             54           3234           1517          18830
CMake                            7            179            275           1034
Markdown                         6             66              0            189
MATLAB                           2             41             21            177
YAML                             3              7             11            174
Bourne Shell                     1              2              0              7
-------------------------------------------------------------------------------
SUM:                           115           7972           4429          45070
-------------------------------------------------------------------------------


Statistical information for the repository '7c9f1dea305737e4e344c902' was
gathered on 2021/11/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Benjamin T. McDaniel           469         45166          23951           32.44
Cole Kendrick                   26          1765            842            1.22
David Green                     69          8865           4531            6.29
Graham Lopez                   108         31364          14058           21.32
Harry Hughes                    16          3421           2410            2.74
Hugo Brunie                      5           884            781            0.78
Mark Cianciosa                   3            98            117            0.10
McDaniel, Benjamin T             5          2236             33            1.07
Steven Hahn                     22          1710            263            0.93
T McDaniel                       3           218            312            0.25
Tim Younkin                      7           215            155            0.17
Timothy Younkin                  7          1127            735            0.87
Tyler                            2            76             62            0.06
Tyler McDaniel                 392         20000          22180           19.80
adam-mcdaniel                   11          1449             59            0.71
elwasif                         26          1301            171            0.69
none                            19         14265           8220           10.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Benjamin T. McDaniel       5458           12.1         31.6               10.17
Cole Kendrick               957           54.2          7.1                7.21
David Green                2618           29.5         27.2               19.60
Graham Lopez              14180           45.2         11.4               10.47
Harry Hughes                514           15.0         24.2                4.09
Hugo Brunie                 842           95.2          8.5                0.59
Mark Cianciosa               98          100.0          1.2               22.45
McDaniel, Benjamin T       1400           62.6         34.3                4.36
Steven Hahn                1523           89.1          1.0                2.82
Tim Younkin                  90           41.9         27.3               51.11
Timothy Younkin              49            4.3         27.9                0.00
Tyler McDaniel            16188           80.9         18.8                6.02
adam-mcdaniel                29            2.0         27.5                3.45
elwasif                     366           28.1         24.8                9.02
none                      10976           76.9         18.6                2.73
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3953 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Hao Lau (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@quantumsteve please remove the invalid (all zero) orcid id's from the paper. Instead leave out the orcid specification for these if they do not have an orcid id, see also below and: 
https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography


```yaml
authors:
  - name: Adrian M. Price-Whelan^[co-first author] # note this makes a footnote saying 'co-first author'
    orcid: 0000-0003-0872-7098
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Author Without ORCID^[co-first author] # note this makes a footnote saying 'co-first author'
    affiliation: 2
```

After fixing the paper you can update the pdf draft here by calling `@whedon generate pdf from branch paper`

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jarvist as editor

**Comment by whedon** [comment]
@jarvist has been invited to edit this submission.

**Comment by quantumsteve** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03953/joss.03953/10.21105.joss.03953.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03953/joss.03953/10.21105.joss.03953.pdf) :page_facing_up: :point_left:

**Comment by jarvist** [comment]
@whedon assign @jarvist as editor

OK, happy to edit this.

**Comment by whedon** [comment]
OK, the editor is @jarvist

**Comment by jarvist** [comment]
@quantumsteve  - do you have any reviewer suggestions?

**Comment by quantumsteve** [comment]
We suggest Nick Murphy (namurphy), Sterling Smith (smithsp),  Archis Joglekar (joglekara), Rogerio Jorge (rogeriojorge) or Carsten Fortmann-Grote (CFGrote).

**Comment by joglekara** [comment]
@jarvist, happy to take it on

**Comment by jarvist** [comment]
@whedon add @joglekara as reviewer

Wonderful! Welcome aboard.

**Comment by whedon** [comment]
OK, @joglekara is now a reviewer

**Comment by jarvist** [comment]
Still looking for reviewers! Apologies for the delay.

**Comment by quantumsteve** [comment]
May we suggest two more reviewers? Casey Icenhour (cticenhour), John Drobny (drobnyjt)

**Comment by joglekara** [comment]
@quantumsteve sorry for the wait here... 

@jarvist @Kevin-Mattheus-Moerman , is there anything I can do to help get the review process started? Perhaps, we can just proceed with 1 reviewer?

**Comment by arfon** [comment]
Just a heads up that I've pinged @jarvist over email to give us an update.

**Comment by arfon** [comment]
@editorialbot assign me as reviewer

**Comment by arfon** [comment]
@editorialbot assign me as editor

**Comment by arfon** [comment]
@quantumsteve @joglekara – apologies for the delay here. I'll take this submission on to help @jarvist out here.

**Comment by arfon** [comment]
:wave: @cticenhour & @drobnyjt - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is _ASGarD: Adaptive Sparse Grid Discretization_

**Comment by drobnyjt** [comment]
Hi @arfon - I'm attending the Exascale Computing Project's annual meeting, so would not be able to start in earnest until next week. If that's okay, I'd be happy to.

**Comment by cticenhour** [comment]
Hi @arfon! I also would be available, but I do need to disclose that the first author on this work (David L Green) is a member of my PhD committee (*not* my dissertation advisor, however). We have not collaborated on this particular work. If this is a CoI, please let me know.

**Comment by arfon** [comment]
@editorialbot add @drobnyjt as reviewer

**Comment by arfon** [comment]
@editorialbot add @cticenhour as reviewer

> Hi @arfon! I also would be available, but I do need to disclose that the first author on this work (David L Green) is a member of my PhD committee (not my dissertation advisor, however). We have not collaborated on this particular work. If this is a CoI, please let me know.

Thank you for flagging this @cticenhour. I'm happy to waive this possible conflict.

**Comment by arfon** [comment]
@editorialbot start review

**Comment by arfon** [comment]
@joglekara, @drobnyjt, @cticenhour – see you over in #4378 where the actual review will take place!
