### ISSUE TITLE
[PRE REVIEW]: ViMMS 2.0: A framework to develop, test and optimise 2 fragmentation strategies in LC-MS metabolomics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3954]
**Submitting author:** @joewandy (<a href="http://orcid.org/0000-0002-3068-4664">Joe Wandy</a>)
**Repository:** <a href="https://github.com/glasgowcompbio/vimms/" target ="_blank">https://github.com/glasgowcompbio/vimms/</a>
**Version:** v2.0
**Editor:** @csoneson
**Reviewers:** @jspaezp, @MKoesters
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6cc8d7f2a392a694798c8dd5781dcccd/status.svg)](https://joss.theoj.org/papers/6cc8d7f2a392a694798c8dd5781dcccd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6cc8d7f2a392a694798c8dd5781dcccd"><img src="https://joss.theoj.org/papers/6cc8d7f2a392a694798c8dd5781dcccd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6cc8d7f2a392a694798c8dd5781dcccd/status.svg)](https://joss.theoj.org/papers/6cc8d7f2a392a694798c8dd5781dcccd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @joewandy. **Currently, there isn't an JOSS editor assigned** to your paper.

@joewandy if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1985

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.35 s (463.4 files/s, 210259.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             13              0              0          18864
Python                          76           2816           2633          12746
Jupyter Notebook                38              0          28555           4541
R                                4            159            115           1257
Markdown                        21            149              0            517
TeX                              1              9              0            104
YAML                             5             11             14            101
DOS Batch                        1              3              1              5
Bourne Shell                     1              1              0              2
-------------------------------------------------------------------------------
SUM:                           160           3148          31318          38137
-------------------------------------------------------------------------------


Statistical information for the repository 'b22b3c5f38bc33893c9d147c' was
gathered on 2021/11/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Joe Wandy                       97          7111           6004           28.60
Kei kuan To                      9            93             76            0.37
Rónán Daly                     5          9800            266           21.95
Simon Rogers                   171          5691            992           14.57
VinnyDavies                    172          4500           2328           14.89
dependabot[bot]                  2             2              2            0.01
joewandy                        59          3901           3882           16.97
unknown                         15           975            230            2.63

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Joe Wandy                  6868           96.6          8.5               13.96
Kei kuan To                  11           11.8         15.3                9.09
Rónán Daly               5550           56.6          0.0               14.61
Simon Rogers               2964           52.1         14.1                5.67
VinnyDavies                2174           48.3          8.4                4.65
unknown                     628           64.4          9.5                0.80
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03954/joss.03954/10.21105.joss.03954.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03954/joss.03954/10.21105.joss.03954.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1186/1471-2105-15-s7-s9 may be a valid DOI for title: Proteomics, lipidomics, metabolomics: a mass spectrometry tutorial from a computer scientist’s point of view
- 10.1101/744227 may be a valid DOI for title: In silico optimization of mass spectrometry fragmentation strategies in metabolomics
- 10.1021/acs.analchem.0c03895.s001 may be a valid DOI for title: Rapid Development of Improved Data-Dependent Acquisition Strategies
- 10.1093/bioinformatics/btu729 may be a valid DOI for title: JAMSS: proteomics mass spectrometry simulation in Java
- 10.1021/pr400727e may be a valid DOI for title: Mspire-Simulator: LC-MS shotgun proteomic simulator for creating realistic gold standard data
- 10.1093/bioinformatics/btv745 may be a valid DOI for title: MSAcquisitionSimulator: data-dependent acquisition simulator for LC-MS shotgun proteomics
- 10.3390/genes12030396 may be a valid DOI for title: SMITER—A Python Library for the Simulation of LC-MS/MS Experiments
- 10.1186/s12859-015-0540-1 may be a valid DOI for title: OpenMS-Simulator: an open-source software for theoretical tandem mass spectrum prediction

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@joewandy could you check those missing DOI's :point_up:  you can call `@whedon generate pdf` here to update the paper or call `@whedon check references` to check those DOI's again. Thanks.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋🏻  @joewandy - I will handle your submission and start by looking for suitable reviewers. If you have suggestions, please let me know here (without tagging them with `@`).

**Comment by joewandy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/nbt.4101 is OK
- 10.1186/1471-2105-15-s7-s9 is OK
- 10.1101/744227 is OK
- 10.1021/acs.analchem.0c03895 is OK
- 10.1093/bioinformatics/btu729 is OK
- 10.1021/pr400727e is OK
- 10.1093/bioinformatics/btv745 is OK
- 10.3390/genes12030396 is OK
- 10.1186/s12859-015-0540-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by joewandy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03954/joss.03954/10.21105.joss.03954.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03954/joss.03954/10.21105.joss.03954.pdf) :page_facing_up: :point_left:

**Comment by joewandy** [comment]
> @joewandy could you check those missing DOI's ☝️ you can call `@whedon generate pdf` here to update the paper or call `@whedon check references` to check those DOI's again. Thanks.

Thanks for letting me know. I've fixed those missing DOIs and regenerated the paper.

**Comment by joewandy** [comment]
> 👋🏻 @joewandy - I will handle your submission and start by looking for suitable reviewers. If you have suggestions, please let me know here (without tagging them with `@`).

Hello i'd like to suggest the following people as reviewers as I'm aware they have worked on similar things in the past:

MKoesters -- worked on [SMITER](https://www.mdpi.com/2073-4425/12/3/396)
lfnothias -- worked on [MS2Planner](https://academic.oup.com/bioinformatics/article/37/Supplement_1/i231/6319686)
florian-huber -- did a lot of work on deep learning and mass spec data

**Comment by csoneson** [comment]
👋🏻   @MKoesters, @florian-huber, @jorainer - would two of you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? 

> ViMMS 2.0: A framework to develop, test and optimise 2 fragmentation strategies in LC-MS metabolomics

You can find more information about JOSS and the review process [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) - of course, happy to answer any questions as well.

**Comment by jorainer** [comment]
Sorry for my late reply - super busy at present. Thus I'll also not have time to review at present - besides, I'm not a python developer, so I can't provide usefull feedback on the actual implementation.

**Comment by florian-huber** [comment]
I could review the manuscript!

One disclaimer though: I did collaborate with one of the authors (Simon Rogers), including a publication that was finished >1 year ago. The collaboration was on a very different project and I was not involved in any way in the project presented here. So, I believe that I can make an impartial assessment of the work, but that's up to you to decide @csoneson .

**Comment by csoneson** [comment]
Thank you @florian-huber!  Unfortunately, I think this is still a bit too recent for our CoI policy ("recent (past four years) collaborators in funded research or work that is published"). I hope we can get back to you for another submission in the future!

**Comment by csoneson** [comment]
👋🏻 @hechth, @jspaezp - would you be interested in reviewing this submission for JOSS? 

> ViMMS 2.0: A framework to develop, test and optimise 2 fragmentation strategies in LC-MS metabolomics

**Comment by jspaezp** [comment]
@csoneson would be glad to.

**Comment by hechth** [comment]
@csoneson Hi, when would you need me to confirm this? I'd like to first investigate the repository a bit to get a grasp on the complexity and time effort for a proper review :)

**Comment by csoneson** [comment]
@hechth - it would be great if you could come back to me before the end of the week so that, if needed, I can look for another reviewer without too much delay. If you would like some more information about reviewing for JOSS, including the review criteria and checklist, see [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) - of course, I'm happy to answer any questions as well. Thanks!

**Comment by csoneson** [comment]
> @csoneson would be glad to.

Thank you @jspaezp! I will assign you as a reviewer now, and once we have also a second one I will open the actual review issue where you will then find your review checklist etc.

**Comment by csoneson** [comment]
@whedon assign @jspaezp as reviewer

**Comment by whedon** [comment]
OK, @jspaezp is now a reviewer

**Comment by MKoesters** [comment]
@csoneson I'd also be willing to do the review

**Comment by csoneson** [comment]
Brilliant, thanks @MKoesters!

**Comment by csoneson** [comment]
@whedon add @MKoesters as reviewer

**Comment by whedon** [comment]
OK, @MKoesters is now a reviewer

**Comment by csoneson** [comment]
👋🏻 @hechth - did you have a chance to check whether you would like to review this submission? Thanks.

**Comment by hechth** [comment]
@csoneson hi, sorry for not giving you an update. I thought with @MKoesters accepting there are the 2 required reviewers and since he was suggested initially by the author as a reviewer I thought it would be self explanatory that they are doing the review :)

I'm also currently pretty busy and the software is pretty complex so I'd rather leave it to them :)

Thank you very much for your consideration and let me know if anything changes or is unclear.

**Comment by csoneson** [comment]
Alright! We do sometimes have more than two reviewers, so I wanted to give everyone the opportunity. Hopefully we can come back to you for another review in the future.

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3990.
