### ISSUE TITLE
[PRE REVIEW]: Dune-MMesh: The Dune Grid Module for Moving Interfaces

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3955]
**Submitting author:** @samuel.burbulla (<a href="http://orcid.org/0000-0002-2566-9777">Samuel Burbulla</a>)
**Repository:** <a href="https://github.com/samuelburbulla/dune-mmesh/" target ="_blank">https://github.com/samuelburbulla/dune-mmesh/</a>
**Version:** 1.3
**Editor:** @diehlpk
**Reviewers:** @krober10nd,  @vijaysm
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0/status.svg)](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0"><img src="https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0/status.svg)](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @samuel.burbulla. **Currently, there isn't an JOSS editor assigned** to your paper.

@samuel.burbulla if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3955 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.63 s (1162.9 files/s, 302050.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   601          24036          17975         120957
C++                             25            487            242           1865
Python                          21            551            563           1024
make                             2            110             72            959
Markdown                         3            132              0            597
GLSL                            12             83            111            446
Jupyter Notebook                 6              0           1283            423
reStructuredText                34            208          16214            282
CMake                           19             57             17            241
YAML                             3             15              4            103
DOS Batch                        1              8              1             26
TOML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                           728          25687          36482         126926
-------------------------------------------------------------------------------


Statistical information for the repository 'da4f1bbfdb26898f59b3fd68' was
gathered on 2021/11/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Maximilian Hörl                  3           599            143            0.38
Samuel                          18           665            216            0.45
Samuel Burbulla                286        179458          12786           98.77
Timo Koch                        4            12             15            0.01
dedner                          16           586            161            0.38

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Maximilian Hörl             374           62.4         21.2               18.45
Samuel Burbulla          167150           93.1          5.8               11.71
Timo Koch                     5           41.7          5.6                0.00
dedner                      171           29.2         17.2                2.34
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch feature/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03955/joss.03955/10.21105.joss.03955.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03955/joss.03955/10.21105.joss.03955.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@samuel.burbulla did I use the correct branch to build the paper :point_up: ?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
Alternatively @diehlpk you could handle this paper if you are interested. However since you are handling quite a few already I invited @hugoledoux first here.

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman I can do it, since one paper is close to be accepted. Just waiting for the author's last edit. 

However, if the other editor wants to take it, it is fine.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @diehlpk. I decided to assign you since you responded first and it is good to get as many papers of the AEiC desk and out for review as possible. Thanks again!

**Comment by hugoledoux** [comment]
I'm too slow 🤷🏼‍♂️

**Comment by diehlpk** [comment]
@samuel.burbulla would you mind recommending some reviewers?

**Comment by diehlpk** [comment]
Hey @vijaysm @KParas @krober10nd @cedricchevalier19 would you be interested in reviewing this paper?

**Comment by krober10nd** [comment]
I'd be interested in reviewing.

**Comment by diehlpk** [comment]
@whedon assign @krober10nd as reviewer

**Comment by whedon** [comment]
OK, @krober10nd is now a reviewer

**Comment by diehlpk** [comment]
> I'd be interested in reviewing.

Thanks, I invited you.

**Comment by vijaysm** [comment]
Hi @diehlpk, sure I should be able to review it in December, before the holidays.

**Comment by diehlpk** [comment]
@whedon add  @vijaysm as reviewer

**Comment by whedon** [comment]
OK,  @vijaysm is now a reviewer

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3959.
