### ISSUE TITLE
[REVIEW]: SimuPy: A python framework for modeling and simulating dynamical systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#396]
**Submitting author:** @sixpearls (<a href="http://orcid.org/0000-0001-5602-1888">Benjamin Margolis</a>)
**Repository:** <a href="https://github.com/simupy/simupy" target ="_blank">https://github.com/simupy/simupy</a>
**Version:** v1.0.0
**Editor:** @cmadan
**Reviewer:** @demotu
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.896706" target="_blank">10.5281/zenodo.896706</a>

## Status

[![status](http://joss.theoj.org/papers/e3f363198781fe8ff62db595f123f39e/status.svg)](http://joss.theoj.org/papers/e3f363198781fe8ff62db595f123f39e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e3f363198781fe8ff62db595f123f39e"><img src="http://joss.theoj.org/papers/e3f363198781fe8ff62db595f123f39e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e3f363198781fe8ff62db595f123f39e/status.svg)](http://joss.theoj.org/papers/e3f363198781fe8ff62db595f123f39e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/simupy/simupy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@demotu, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cmadan know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/simupy/simupy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@sixpearls) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @demotu it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@demotu, it would be great if you could work through the reviewer checklist in the first comment and see if the submission addresses each point sufficiently. If not, please post issues in the submission's repo or here, as makes sense and hopefully @sixpearls can respond accordingly.

**Comment by demotu** [comment]
The submission addresses all JOSS points sufficiently.
I installed simupy and ran the examples. Everything works fine. 
The link for the API doc at the README.rst doesn't work.
Could you provide working links for the documentation and docstrings?

**Comment by sixpearls** [comment]
Hi @demotu, thanks for your feedback, I'm glad you like the software! 

The link to the API docs on the README is intentionally broken because the README is imported into a page of the [real docs](https://simupy.readthedocs.io/en/latest/index.html) and I wanted to keep the documentation DRY (Do not Repeat Yourself). Github does render a link to the documentation on readthedocs as a badge correctly at the top of the file. 

Do you think this is sufficient?

**Comment by demotu** [comment]
Using Sympy as example, it has a link to its homepage at the very first
line and a specific session about documentation and usage with a clear link
to the docs. Particularly about documentation, I wouldn't mind redundancy.

-
Marcos Duarte
http://demotu.org/

**Comment by sixpearls** [comment]
Thanks, I agree working links to the documentation everywhere is helpful.

I figured out how to do it in a way I'm happy with. Now, the github README will point to the latest docs on readthedocs, the pypi description will point to the most recent X.Y.Z build of the docs on readthedocs, and a built version of the docs will have a local link.

Does this address all your concerns?

**Comment by demotu** [comment]
Yes, I AM satisfied with this change.

Em 13 de set de 2017 01:21, "Ben Margolis" <notifications@github.com>
escreveu:

Thanks, I agree working links to the documentation everywhere is helpful.

I figured out how to do it in a way I'm happy with. Now, the github README
will point to the latest docs on readthedocs, the pypi description will
point to the most recent X.Y.Z build of the docs on readthedocs, and a
built version of the docs will have a local link.

Does this address all your concerns?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/396#issuecomment-329054820>,
or mute the thread

**Comment by cMadan** [comment]
@sixpearls, I looked the repo over and everything looks great! You did an excellent job of preparing a useful readme, paper.md, and examples.

@demotu, is there a reason you haven't checked the performance checkbox in the list in the first comment here?

**Comment by demotu** [comment]
I just checked the performance checkbox.

-
Marcos Duarte
http://demotu.org/

On Wed, Sep 13, 2017 at 7:59 AM, Christopher Madan <notifications@github.com

**Comment by sixpearls** [comment]
Thanks for your review and feedback, @demotu.

@cMadan, what are the next steps to get this published? And I'm glad you liked the documentation and paper!

**Comment by cMadan** [comment]
Next I need the DOI for an archived version of the project, submitted to Zenodo or figshare. After you provide that, we're all set!

**Comment by sixpearls** [comment]
Should the archive of the project include the paper documents? Or just the software package, such as released to PyPi?

Thanks,
Ben

**Comment by sixpearls** [comment]
This DOI is for the files associated with the software package as distributed by PyPi with the paper subfolder from the repository included additionally. Please let me know if this needs any corrections.

http://doi.org/10.5281/zenodo.896706

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.896706 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.896706" target="_blank">10.5281/zenodo.896706</a> is the archive.

**Comment by cMadan** [comment]
@sixpearls, you did it perfectly. Now we just need @arfon to do the honors of officially accepting the paper :). Great work! 🎉

**Comment by arfon** [comment]
@demotu many thanks for your review here and to @cMadan for editing this submission ✨ 

@sixpearls - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00396 ⚡️ 🚀 💥

**Comment by sixpearls** [comment]
Thanks so much!
