### ISSUE TITLE
[PRE REVIEW]: Kamodo: A functional api for space weather models and data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3963]
**Submitting author:** @asherp (<a href="http://orcid.org/0000-0002-5718-1303">Asher Pembroke</a>)
**Repository:** <a href="https://github.com/EnsembleGovServices/kamodo-core" target ="_blank">https://github.com/EnsembleGovServices/kamodo-core</a>
**Version:** 21.10.0
**Editor:** @dfm
**Reviewers:** @dstansby, @samaloney
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308/status.svg)](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308"><img src="https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308/status.svg)](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308)
```

**Author instructions**

Thanks for submitting your paper to JOSS @asherp. **Currently, there isn't an JOSS editor assigned** to your paper.

@asherp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1439

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.5281/zenodo.2537188 is OK
- 10.5281/zenodo.1199703 is OK
- 10.1029/2018JA025297 is OK
- 10.5281/zenodo.4313063 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1016/j.jastp.2004.07.030 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1029/2010JA016023 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.94 s (43.8 files/s, 8266.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          15           1310            637           4648
Markdown                         7           1030              0           1527
Jupyter Notebook                11              0           4411            550
SVG                             33              1              1            417
YAML                            10             31             25            332
TeX                              1             24              1            293
CSS                              1             47             77            291
HTML                             3             48              1            165
JavaScript                       1             43              6             83
Dockerfile                       1              8             17             13
Bourne Shell                     1              2              0              3
TOML                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            85           2544           5176           8324
-------------------------------------------------------------------------------


Statistical information for the repository '2008ef017506489454123f78' was
gathered on 2021/11/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Asher Pembroke                 130          6721           8902           27.18
Darren De Zeeuw                 44         17018           4203           36.92
Lutz Rastaetter                 16          4664            125            8.33
Michael Hirsch, Ph.D             1             1             31            0.06
asherp                          44          4463            599            8.81
iamjavaexpert                    5           820            259            1.88
rebeccaringuette                19          7152           2521           16.83

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Asher Pembroke             5926           88.2         13.8                8.08
Michael Hirsch, Ph.D          1          100.0         25.6                0.00
iamjavaexpert               798           97.3         11.6                0.75
rebeccaringuette              2            0.0          2.2               50.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03963/joss.03963/10.21105.joss.03963.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03963/joss.03963/10.21105.joss.03963.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@dfm What do you think about editing this submission?

**Comment by kthyng** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

I'm happy to edit. Give me a couple of days for a few initial checks and then I'll start recruiting reviewers. This can be a little slow these days, but I'll keep this thread posted on the progress. @asherp: don't hesitate to ping me if you have questions as the review progresses!

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@asherp: A quick update to say that I'm still working on recruiting reviewers and I'll keep this thread updated as I find them!

**Comment by asherp** [comment]
> @asherp: A quick update to say that I'm still working on recruiting reviewers and I'll keep this thread updated as I find them!

Can I suggest @mbobra ?

**Comment by dfm** [comment]
I don't think mbobra is available at the moment (unless she wants to volunteer here :D), but thanks for the suggestion. That being said, _please don't tag people in this thread_ because things will get noisy over here and we don't want to inundate them with notifications. Thanks!

**Comment by dfm** [comment]
@whedon add @dstansby as reviewer

Thanks for agreeing to review, David! I'm still working on finding a second reviewer and, as soon as I do, we'll get this show on the road.

**Comment by whedon** [comment]
OK, @dstansby is now a reviewer

**Comment by mbobra** [comment]
Ah I'm so sorry for the late response, @dfm! I'm happy to take over editing duties from you if you wish (you can re-assign me as editor). I am familiar with heliophysics and space weather forecasting so it might be a better fit with @asherp 's work.

**Comment by dfm** [comment]
@mbobra: Thanks and no worries at all! We've just lined up our second reviewer so I'll get the review started. I'm happy for you to take over or to continue editing myself. No stress either way!

**Comment by dfm** [comment]
@whedon add @samaloney as reviewer

Thanks Shane for agreeing to review!

I'm going to get the main review issue thread started and we'll move over there for the rest of the process. Please let me know if you have any questions as we go. Thanks all for agreeing to be involved!

**Comment by whedon** [comment]
OK, @samaloney is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4053.

**Comment by mbobra** [comment]
@dfm Since you did all the hard work to find the reviewers, you should get the credit for editing this submission. I'm happy to help and will keep an eye on #4053.

**Comment by dfm** [comment]
Sounds good - thanks @mbobra!
