### ISSUE TITLE
[PRE REVIEW]: PiSCAT: A Python Package for Interferometric Scattering Microscopy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3964]
**Submitting author:** @po60nani (<a href="http://orcid.org/0000-0002-0724-3158">Houman Mirzaalian Dastjerdi</a>)
**Repository:** <a href="https://github.com/SandoghdarLab/PiSCAT" target ="_blank">https://github.com/SandoghdarLab/PiSCAT</a>
**Version:** 0.1.20
**Editor:** @emdupre
**Reviewers:** @ziatdinovmax, @aquilesC
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/81fb6452cdd3d3f792d50a4e8763940c/status.svg)](https://joss.theoj.org/papers/81fb6452cdd3d3f792d50a4e8763940c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/81fb6452cdd3d3f792d50a4e8763940c"><img src="https://joss.theoj.org/papers/81fb6452cdd3d3f792d50a4e8763940c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/81fb6452cdd3d3f792d50a4e8763940c/status.svg)](https://joss.theoj.org/papers/81fb6452cdd3d3f792d50a4e8763940c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @po60nani. **Currently, there isn't an JOSS editor assigned** to your paper.

@po60nani if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.29 s (426.2 files/s, 91555.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         101           4144           2737          12282
Markdown                         7            330              0            964
Jupyter Notebook                 5              0           5035            432
reStructuredText                 6            159            130            123
DOS Batch                        1              9              1             27
CSS                              1              2              0             11
make                             1              4              7             10
YAML                             1              4              6              7
-------------------------------------------------------------------------------
SUM:                           123           4652           7916          13856
-------------------------------------------------------------------------------


Statistical information for the repository '8044d47c03604b0a6c934938' was
gathered on 2021/11/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Houman Mirzaalian Da            75         19750           1045           96.55
Matthias Baer                    1           215            137            1.63
Reza Gholami M                   2             5              5            0.05
rgholam                          1           380              0            1.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Houman Mirzaalian Da      18564           94.0          0.9                3.17
Matthias Baer               215          100.0          6.6                5.58
rgholam                     384          101.1          1.8                4.17
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3964 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSS-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03964/joss.03964/10.21105.joss.03964.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03964/joss.03964/10.21105.joss.03964.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@emdupre would this be an ok fit for you from the imaging direction?

**Comment by kthyng** [comment]
@whedon invite @emdupre as editor

**Comment by whedon** [comment]
@emdupre has been invited to edit this submission.

**Comment by emdupre** [comment]
Sorry for my slow response ! I'll admit that the scientific content is quite far from my expertise, but I can edit if you think I'm the best available fit :)

**Comment by danielskatz** [comment]
Given your willingness, I will go ahead and assign you - feel free to reach out to other JOSS editors for suggestions, if needed.   Thanks!!

**Comment by danielskatz** [comment]
@whedon assign @emdupre as editor

**Comment by whedon** [comment]
OK, the editor is @emdupre

**Comment by emdupre** [comment]
Great, thanks @danielskatz @kthyng !

:wave: Hi @po60nani, and thank you for your submission to JOSS !

If you have any suggestions for potential reviewers, please let me know by listing their names or GitHub handles (without the @, so they don't receive a notification) here. You can suggest reviewers from any relevant project, though we often recommend starting with [this list of people](https://bit.ly/joss-reviewers) as they have already agreed to review for JOSS (please start at the bottom of the list).

**Comment by po60nani** [comment]
Hi,

Thank you for your consideration. Based on the list you sent me, I've identified the following individuals as the greatest match for our package domain.

1. jonatanalvelid
2. xaviercm94
3. pr4deepr
4. vigji
5. ziatdinovmax
6. caldarolamartin
7. uellue
8. AoifeHughes

Sincerely,
Houman Mirzaalian

**Comment by emdupre** [comment]
Hello @caldarolamartin @ziatdinovmax @jonatanalvelid  @emmanuelle  :wave:

Would you be willing to review _PiSCAT: A Python Package for Interferometric Scattering Microscopy_ for [JOSS (the Journal of Open Source Software)](https://joss.theoj.org) ?

The review takes place on GitHub and focuses on [the software](https://github.com/SandoghdarLab/PiSCAT) and this short paper: https://github.com/openjournals/joss-papers/blob/joss.03964/joss.03964/10.21105.joss.03964.pdf

If you're available to review this work, please let me know and I'll add you as a reviewer. Once I have sufficient reviewers I'll open a dedicated review issue.

Thank you !

**Comment by ziatdinovmax** [comment]
@emdupre Sure - will be to help help with a review

**Comment by caldarolamartin** [comment]
Hi Elizabeth,

Thanks for considering me for the review, but since I am on leave I am
afraid I can not review the paper at this time. If you still need another
reviewer I suggest Aquiles Carattino, his background is similar to mine.

Thanks for understanding, I hope I can review next time.

Best,
Martin


-------------------------

Martín Caldarola

**Comment by jonatanalvelid** [comment]
Hi Elizabeth,
Thank you for considering me, but I am unfortunately not available to review currently.
I hope I will be considered again and will happily review then, and thanks for your understanding. 

Best,
Jonatan

**Comment by emdupre** [comment]
Thank you @ziatdinovmax @caldarolamartin and @jonatanalvelid for your responses ! 

I appreciate your willingness to review, @ziatdinovmax. I'll work on identifying at least one additional reviewer before starting the process.

Of course, I will absolutely keep you both in mind for future reviews, @caldarolamartin and @jonatanalvelid :slightly_smiling_face: 

Thank you all again !

**Comment by emdupre** [comment]
Hello @aquilesC :wave: 

Would you be willing to review _PiSCAT: A Python Package for Interferometric Scattering Microscopy_ for [JOSS (the Journal of Open Source Software)](https://joss.theoj.org/)?

The review takes place on GitHub and focuses on [the software](https://github.com/SandoghdarLab/PiSCAT) and this short paper: https://github.com/openjournals/joss-papers/blob/joss.03964/joss.03964/10.21105.joss.03964.pdf

If you're available to review this work, please let me know and I'll add you as a reviewer. Once I have sufficient reviewers I'll open a dedicated review issue.

Thank you !

**Comment by aquilesC** [comment]
Hello @emdupre ! 
I can do it during the first or second week of January. If that timeline fits , feel free to add me as reviewer.

**Comment by emdupre** [comment]
Thank you, @aquilesC ! 

Yes, that timeline is very reasonable (both since JOSS is still in [reduced service mode](https://blog.joss.theoj.org/2020/05/reopening-joss) and since we're quickly approaching the holiday season !). I'll go ahead and add you as a reviewer now :rocket:

**Comment by emdupre** [comment]
@whedon add @ziatdinovmax as reviewer

**Comment by whedon** [comment]
OK, @ziatdinovmax is now a reviewer

**Comment by emdupre** [comment]
@whedon add @aquilesC as reviewer

**Comment by whedon** [comment]
OK, @aquilesC is now a reviewer

**Comment by emdupre** [comment]
Hi again everyone,

Since both @aquilesC and @ziatdinovmax have agreed to review, I'm going to go ahead and open a dedicated review issue to get this process started :rocket: 

. @caldarolamartin @jonatanalvelid @emmanuelle, thank you again for your consideration :sunflower:

**Comment by emdupre** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4024.
