### ISSUE TITLE
[PRE REVIEW]: physical_validation: A Python package to assess the physical validity of molecular simulation results

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3969]
**Submitting author:** @ptmerz (<a href="http://orcid.org/0000-0002-7045-8725">Pascal T. Merz</a>)
**Repository:** <a href="https://github.com/shirtsgroup/physical_validation" target ="_blank">https://github.com/shirtsgroup/physical_validation</a>
**Version:** v1.0
**Editor:** @rkurchin
**Reviewers:** @tonigi, @geraldjwang and @zadehsey
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c9a1f78736ec33a06350982c439bf21a/status.svg)](https://joss.theoj.org/papers/c9a1f78736ec33a06350982c439bf21a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c9a1f78736ec33a06350982c439bf21a"><img src="https://joss.theoj.org/papers/c9a1f78736ec33a06350982c439bf21a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c9a1f78736ec33a06350982c439bf21a/status.svg)](https://joss.theoj.org/papers/c9a1f78736ec33a06350982c439bf21a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ptmerz. **Currently, there isn't an JOSS editor assigned** to your paper.

@ptmerz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3969 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=5.09 s (21.4 files/s, 25793.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          69           1628           4534         102794
reStructuredText                 6            182            127            619
XML                              1              1              0            536
Jupyter Notebook                 5              0          20146            408
YAML                            23             32             15            163
Markdown                         3             18              0             64
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           109           1873          24829         104621
-------------------------------------------------------------------------------


Statistical information for the repository 'ff4fa33adc8adadd5114ad17' was
gathered on 2021/12/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chris Walker                     1            84              0            0.05
MKiesel                          1             5              0            0.00
Matt Thompson                    1            58            391            0.27
Matthew W. Thompson              2             1             95            0.06
Michael Shirts                   4           125             97            0.14
Pascal Merz                    265        126619          24639           91.98
Pascal T. Merz                   1             5              5            0.01
SimonBoothroyd                   4          4755           1473            3.79
Theodore Fobe                    1             8              8            0.01
Wei-Tse Hsu                      2            13             11            0.01
mrshirts                        41          4744           1303            3.68

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chris Walker                 84          100.0          0.1               11.90
MKiesel                       4           80.0          6.6                0.00
Matt Thompson                57           98.3          6.9               98.25
Michael Shirts               16           12.8         57.8               12.50
Pascal Merz              104703           82.7          6.4                1.31
SimonBoothroyd             4058           85.3         18.6                9.59
Theodore Fobe                 8          100.0         17.2                0.00
Wei-Tse Hsu                  12           92.3          6.4                0.00
mrshirts                     14            0.3        111.8               14.29
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03969/joss.03969/10.21105.joss.03969.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03969/joss.03969/10.21105.joss.03969.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by rkurchin** [comment]
@whedon assign @rkurchin as editor

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by rkurchin** [comment]
👋  @KEIPERTK and @tonigi, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by tonigi** [comment]
Yes, I'm available. (y)

**Comment by rkurchin** [comment]
@whedon dd @tonigi as reviewer

**Comment by rkurchin** [comment]
@whedon add @tonigi as reviewer

**Comment by whedon** [comment]
OK, @tonigi is now a reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by rkurchin** [comment]
@whedon add @geraldjwang and @zadehsey as reviewers

(I have separately discussed this with them, @zadehsey is @geraldjwang's student and they will complete one review checklist together)

**Comment by whedon** [comment]
OK, @geraldjwang and @zadehsey is now a reviewer

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3981.
