### ISSUE TITLE
[PRE REVIEW]: UKCensusAPI: python and R interfaces to the nomisweb UK census data API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#397]
**Submitting author:** @virgesmith (<a href="http://orcid.org/0000-0002-9951-6642">Andrew Smith</a>)
**Repository:** <a href="https://github.com/virgesmith/UKCensusAPI" target ="_blank">https://github.com/virgesmith/UKCensusAPI</a>
**Version:** 0.1
**Editor:** @leeper
**Reviewer:** @jrnold

**Author instructions**

Thanks for submitting your paper to JOSS @virgesmith. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@virgesmith if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @openjournals/ropensci - would this submission be a good candidate for rOpenSci?

**Comment by virgesmith** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by leeper** [comment]
This looks like a good candidate for rOpenSci. If it doesn't go that route, I can be editor.

**Comment by karthik** [comment]
@leeper Checking with the rest of the editors on this now.

**Comment by karthik** [comment]
@leeper This is a pass from ropensci, so please continue with a JOSS review.

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon assign @jrnold as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jrnold

**Comment by leeper** [comment]
've confirmed that this submission has:

- [X]  An OSI approved license (GPL)
- [X] A description of the software and its research applications
- [X] Is in scope for this journal

**Comment by leeper** [comment]
@whedon start review --magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/408. Feel free to close this issue now!
