### ISSUE TITLE
[PRE REVIEW]: rmap: An R package to plot and compare tabular data on customizable maps across scenarios and time

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3972]
**Submitting author:** @zarrarkhan (<a href="http://orcid.org/0000-0002-8147-8553">Zarrar Khan</a>)
**Repository:** <a href="https://github.com/JGCRI/rmap" target ="_blank">https://github.com/JGCRI/rmap</a>
**Version:** v1.0.0
**Editor:** @hugoledoux
**Reviewers:** @CamilleMorlighem, @maczokni
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4cdf462f70681bc335ddebf5868b249c/status.svg)](https://joss.theoj.org/papers/4cdf462f70681bc335ddebf5868b249c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4cdf462f70681bc335ddebf5868b249c"><img src="https://joss.theoj.org/papers/4cdf462f70681bc335ddebf5868b249c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4cdf462f70681bc335ddebf5868b249c/status.svg)](https://joss.theoj.org/papers/4cdf462f70681bc335ddebf5868b249c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @zarrarkhan. **Currently, there isn't an JOSS editor assigned** to your paper.

@zarrarkhan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1074

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (205.9 files/s, 91494.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               19           1404           2413           7675
Rmd                              1            367            512            781
TeX                              1             18              0            189
Markdown                         5             57              0            177
YAML                             5             32              0            153
-------------------------------------------------------------------------------
SUM:                            31           1878           2925           8975
-------------------------------------------------------------------------------


Statistical information for the repository 'de3c5d203fd14f0a3d552a14' was
gathered on 2021/12/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Khan                             2           442            442          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10113-021-01775-1 is OK
- 10.1088/1748-9326/ac046c is OK
- 10.21105/joss.00054 is OK
- 10.32614/RJ-2011-006 is OK
- 10.1007/b106573 is OK
- 10.5194/gmd-12-677-2019 is OK
- 10.5334/jors.292 is OK

MISSING DOIs

- 10.18637/jss.v084.i06 may be a valid DOI for title: tmap: Thematic Maps in R
- 10.32614/rj-2018-009 may be a valid DOI for title: Simple features for R: standardized support for spatial vector data.

INVALID DOIs

- 0.1029/2020EF001970 is INVALID
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03972/joss.03972/10.21105.joss.03972.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03972/joss.03972/10.21105.joss.03972.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @zarrarkhan and thanks for your submission. I am pinging the editorial board for input to make sure this submission is in scope for the journal. Usually we do this for plotting-focused packages to make sure the breadth of the package is large enough. This process will take 1-2 weeks. Thanks for your patience.

**Comment by zarrarkhan** [comment]
> @zarrarkhan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Here are suggested reviewers from the list. These reviewers are from the bottom of the list and indicate both R as their preferred language and spatial analysis in their domains: 

- fernandomayer
- hknd23
- nickbearman
- ateucher
- tsamsonov
- yongzesong
- ssujit
- jpiburn
- wcjochem
- adithirgis
- kauedesousa
- GISerDaishaoqing
- mikerspencer
- jayrobwilliams
- mikejohnson51
- garretrc
- becarioprecario
- adibender

**Comment by Kevin-Mattheus-Moerman** [comment]
@zarrarkhan it would be helpful if you could clearly illustrate how this work has a **direct scientific research application** (beyond visualization), so how it directly influences scientific research. This should make it clear why researchers would feel the need to cite this work. Simple utility tools or visualization tools tend not to be cited since they might not have an effect on the scientific findings. If you could help clarify where this software sits in the spectrum ranging from pure research software to pure visualization, that would be helpful. Are the comparisons only visual or also quantitative?

**Comment by zarrarkhan** [comment]
@Kevin-Mattheus-Moerman. Thanks for the question. `rmap's` absolute and percentage difference mapping capabilities while using relatively simple algorithms are not trivial (especially for gridded time series) and definitely have a significant **direct scientific research application** in that they help researches identify changes between scenarios as well as trends across time. All the papers already using `rmap's` capabilities would have cited this paper had it already been published. Additionally as the package is becoming more popular at our institute and partner universities several authors have asked me for how to cite the software. I am hesitant to provide them with a zenodo doi for the software release and would rather provide the final JOSS citation if accepted. The following examples from actual publications highlight the quantitative applications vs pure visualization:

- Khan, Z., Iyer, G., Patel, P., Kim, S., Hejazi, M., Burleyson, C. and Wise, M., 2021. Impacts of long-term temperature change and variability on electricity investments. Nature communications, 12(1), pp.1-12. https://doi.org/10.1038/s41467-021-21785-1
    * Fig 1. `rmap` Pure visualization
    * Fig 4. `rmap` Quantitative spatial analysis of spatial distribution of installed capacity and capital investments across the US in 2100.

- Wild, T.B., Khan, Z., Zhao, M., Suriano, M., Bereslawski, J.L., Roberts, P., Casado, J., Gaviño‐Novillo, M., Clarke, L., Hejazi, M. and Miralles‐Wilhelm, F., 2021. The Implications of Global Change for the Co‐Evolution of Argentina's Integrated Energy‐Water‐Land Systems. Earth's Future, 9(8), p.e2020EF001970. https://doi.org/10.1029/2020EF001970
    * Fig 2. `rmap` Pure visualization
    * Fig 4. `rmap` Quantitative spatial analysis of spatial differences between reference case and multiple Global Climate Model (GCMs) as well as Representative Concentration Pathways (RCPs) to explore implications of climate projections on runoff.
    * Figs 7,8,9: `rmap` Quantitative spatial analysis of the implications of climate change vs policy on landuse and agricultural production. Key to highlighting the implications of these scenarios which would not be possible by comparing pure absolute values across the maps.
    * Fig 10. `rmap` Pure visualization of absolute values to show final conclusion.

- Khan, Z., Wild, T.B., Iyer, G.C., Hejazi, M. and Vernon, C.R., 2021. The future evolution of energy-water-agriculture interconnectivity across the US. Environmental Research Letters. https://doi.org/10.1088/1748-9326/ac046c
    * Fig 5. `rmap` Quantitative spatial analysis of changes in the intersectoral interconnectivity indices across the US from the reference case. In this particular example it was essential to use `rmap's` % difference functionality because we are comparing across distinct parameters (Magnitude Index vs Spread Index) which could not be comparable as absolute values.

- Upcoming research article on implications of socioeconomics and climate change on global water withdrawals which was presented at EGU. The paper is in prep and will be submitted to Nature Scientific Data in the next few months. Preliminary results can be seen at the EGU site: https://presentations.copernicus.org/EGU21/EGU21-903_presentation.pdf 
    * Fig. `rmap` Quantitative spatial analysis (global gridded) of the implications of socioeconomics and climate change scenarios by 2100 from the reference scenario (SSP2 no climate in 2015) for global water withdrawals. 

In all these papers the difference maps are used to derive the key conclusions of each paper. So I believe `rmap` offers a valuable quantitative capability to make conclusions about the spatial implications of different scenarios and time periods.

**Comment by kyleniemeyer** [comment]
Hi @zarrarkhan, we are going to proceed with review of your submission; one or two editors suggested there was room for improvement that could come via the review process.

**Comment by kyleniemeyer** [comment]
@whedon invite @hugoledoux as editor

Hi @hugoledoux, can you edit this one?

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by zarrarkhan** [comment]
> Hi @zarrarkhan, we are going to proceed with review of your submission; one or two editors suggested there was room for improvement that could come via the review process.

@kyleniemeyer @hugoledoux Thanks for the update. We look forward to the editor and reviewer comments to improve our paper/package.

**Comment by hugoledoux** [comment]
@jhollist @Maczokni @mikejohnson51 @jayrobwilliams @GISerDaishaoqing

According to your keywords, you all seem very suitable for this. If you have time and are interested, let me know here please.

**Comment by hugoledoux** [comment]
@whedon assign @CamilleMorlighem as reviewer

**Comment by whedon** [comment]
OK, @CamilleMorlighem is now a reviewer

**Comment by maczokni** [comment]
> @jhollist @maczokni @mikejohnson51 @jayrobwilliams @GISerDaiShaoqing
> 
> According to your keywords, you all seem very suitable for this. If you have time and are interested, let me know here please.

Sure, happy to!

**Comment by hugoledoux** [comment]
@whedon add @maczokni as reviewer

**Comment by whedon** [comment]
OK, @maczokni is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4015.

**Comment by hugoledoux** [comment]
I've got 2 reviewers so I'll start the review now, but if one of you wants to the 3rd one let me know I'll add you, first-come-first-served.

@jhollist @mikejohnson51 @jayrobwilliams @GISerDaiShaoqing

**Comment by jhollist** [comment]
I have to pass on this one, @hugoledoux.  But thanks for the invite and happy holidays, all!
