### ISSUE TITLE
[PRE REVIEW]: ADaPT-ML: A Data Programming Template for Machine Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3975]
**Submitting author:** @nulberry (<a href="http://orcid.org/0000-0001-8512-1810">Andrea Whittaker</a>)
**Repository:** <a href="https://github.com/U-Alberta/ADaPT-ML" target ="_blank">https://github.com/U-Alberta/ADaPT-ML</a>
**Version:** v1.0.0
**Editor:** @jmschrei
**Reviewers:** @aaronpeikert, @wincowgerDEV
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e846e08311cee3886d33101209166f4c/status.svg)](https://joss.theoj.org/papers/e846e08311cee3886d33101209166f4c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e846e08311cee3886d33101209166f4c"><img src="https://joss.theoj.org/papers/e846e08311cee3886d33101209166f4c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e846e08311cee3886d33101209166f4c/status.svg)](https://joss.theoj.org/papers/e846e08311cee3886d33101209166f4c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nulberry. **Currently, there isn't an JOSS editor assigned** to your paper.

@nulberry if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 612

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s00778-019-00552-1 is OK
- 10.1145/3399579.3399867 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (314.2 files/s, 24069.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          23            311            347           1627
Markdown                         4            137              0            476
YAML                             8             48             10            347
Bourne Shell                     5             21              1             94
TeX                              1              5              0             74
Dockerfile                       3             15              4             69
XML                              1              0              0             12
JSON                             2              0              0              2
-------------------------------------------------------------------------------
SUM:                            47            537            362           2701
-------------------------------------------------------------------------------


Statistical information for the repository 'd9ae149d38be116e6387b351' was
gathered on 2021/12/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrea Whittaker               175          6151           3860          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrea Whittaker           2291           37.2          3.1                5.85
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03975/joss.03975/10.21105.joss.03975.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03975/joss.03975/10.21105.joss.03975.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @jmschrei! Would this be a good fit for you?

**Comment by kthyng** [comment]
@whedon invite @jmschrei as editor

**Comment by whedon** [comment]
@jmschrei has been invited to edit this submission.

**Comment by jmschrei** [comment]
I can do this but I am away from my computer for the weekend

**Comment by danielskatz** [comment]
Thanks!

**Comment by danielskatz** [comment]
@whedon assign @jmschrei as editor

**Comment by whedon** [comment]
OK, the editor is @jmschrei

**Comment by jmschrei** [comment]
@aaronpeikert are you able to review this submission? The GitHub is mostly in Python but the tool seems to not involve programming that much.

@julianpistorius are you able to review this submission?

**Comment by aaronpeikert** [comment]
Looks like a great project. Judging from the first glimpse, I am comfortable enough with Python to review it.

**Comment by jmschrei** [comment]
@whedon invite @aaronpeikert as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by jmschrei** [comment]
@whedon add @aaronpeikert as reviewer

**Comment by whedon** [comment]
OK, @aaronpeikert is now a reviewer

**Comment by jmschrei** [comment]
Hi @tupi, would you be able to serve as a reviewer for this submission?

**Comment by jmschrei** [comment]
Hi @wincowgerDEV, would you b able to serve as a reviewer for this submission?

**Comment by wincowgerDEV** [comment]
I am able to serve as a reviewer for this submission, thanks for the invitation.

**Comment by jmschrei** [comment]
@whedon add @wincowgerDEV as reviewer

**Comment by whedon** [comment]
OK, @wincowgerDEV is now a reviewer

**Comment by jmschrei** [comment]
Great! Let's start.

**Comment by jmschrei** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4038.
