### ISSUE TITLE
[PRE REVIEW]: RWNN: Fast and simple non-linear modelling using random weight neural networks in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3977]
**Submitting author:** @svilsen (<a href="http://orcid.org/0000-0002-9718-8147">Søren Vilsen</a>)
**Repository:** <a href="https://github.com/svilsen/RWNN" target ="_blank">https://github.com/svilsen/RWNN</a>
**Version:** 0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/825c2e78822900a581bc07f428a874d2/status.svg)](https://joss.theoj.org/papers/825c2e78822900a581bc07f428a874d2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/825c2e78822900a581bc07f428a874d2"><img src="https://joss.theoj.org/papers/825c2e78822900a581bc07f428a874d2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/825c2e78822900a581bc07f428a874d2/status.svg)](https://joss.theoj.org/papers/825c2e78822900a581bc07f428a874d2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @svilsen. **Currently, there isn't an JOSS editor assigned** to your paper.

@svilsen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (658.4 files/s, 67222.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               27            484            702           1594
C++                              3             48             13            254
Markdown                         1             19              0             51
-------------------------------------------------------------------------------
SUM:                            31            551            715           1899
-------------------------------------------------------------------------------


Statistical information for the repository 'd3c1f2aae892b8cf98f32c37' was
gathered on 2021/12/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Søren Vilsen                     7           263             32           52.40
svilsen                          8           100             67           29.66
unknown                          2            76             25           17.94

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
svilsen                     241          241.0          5.4                5.39
unknown                      74           97.4          1.7                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3977 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3977 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kthyng** [comment]
@svilsen I am going to ping the editorial board to make sure this submission is in scope. This process will take 1-2 weeks; thanks for your patience!

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by pdebuyl** [comment]
@svilsen can you add the orcid to the paper?

**Comment by svilsen** [comment]
> @svilsen can you add the orcid to the paper?

Has been added to the paper.md file in the JOSS branch.

**Comment by pdebuyl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3977 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by pdebuyl** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03977/joss.03977/10.21105.joss.03977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03977/joss.03977/10.21105.joss.03977.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment]
Thank you, this solved the pdf generation issue.

**Comment by kyleniemeyer** [comment]
Hello @svilsen, unfortunately the editorial board's consensus was that this submission is not suitable for review at this time. Editors suggested that while work is good, the scope is fairly small and not likely to be used by others in its current state.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
