### ISSUE TITLE
[PRE REVIEW]: patRoon 2.0: Improved non-target analysis workflows including automated transformation product screening

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3978]
**Submitting author:** @rickhelmus (<a href="http://orcid.org/0000-0001-9401-3133">Rick Helmus</a>)
**Repository:** <a href="https://github.com/rickhelmus/patRoon" target ="_blank">https://github.com/rickhelmus/patRoon</a>
**Version:** 2.0.0
**Editor:** @KristinaRiemer
**Reviewers:** @wesleyburr, @hechth
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d0c9c8c937bbf8f9e00e12d1a9f95715/status.svg)](https://joss.theoj.org/papers/d0c9c8c937bbf8f9e00e12d1a9f95715)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d0c9c8c937bbf8f9e00e12d1a9f95715"><img src="https://joss.theoj.org/papers/d0c9c8c937bbf8f9e00e12d1a9f95715/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d0c9c8c937bbf8f9e00e12d1a9f95715/status.svg)](https://joss.theoj.org/papers/d0c9c8c937bbf8f9e00e12d1a9f95715)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rickhelmus. **Currently, there isn't an JOSS editor assigned** to your paper.

@rickhelmus if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3978 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.33 s (398.5 files/s, 188254.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             94              0              1         105126
HTML                           113           6754            879          49403
R                              179           5968           7967          25637
JavaScript                      30           3241           3334          13870
C++                             29           3394           1066          12257
Rmd                             20           1350           2031           1835
C/C++ Header                    31            664            753           1787
CSS                             17            172            118           1527
Markdown                         3            196              0            872
TeX                              2             30              0            388
YAML                             8             24              8            358
XML                              1              0              0            186
Dockerfile                       2             12              2             38
Julia                            1             12              1             30
PowerShell                       1              0              0              9
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                           532          21817          16160         213324
-------------------------------------------------------------------------------


Statistical information for the repository 'd9b61dca2a3eb311a03aaf2c' was
gathered on 2021/12/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
CircleCI updater                16         42712          39448           59.85
Rick                             1             6              8            0.01
Rick Helmus                     54         25859           4974           22.46
rhelmus                         18         24154            103           17.67
rickhelmus                       2             6             11            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
CircleCI updater          27904           65.3         12.7               37.24
Rick Helmus               20289           78.5         29.2                9.18
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch paper20

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper20. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03978/joss.03978/10.21105.joss.03978.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03978/joss.03978/10.21105.joss.03978.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @rickhelmus and thanks for your submission! I see your paper for version 1.0 — can you describe what the review process for that paper entailed? Was there a software review? I know that you are seeking to publish on the basis of improvements between the two versions, but it would still be helpful to know what review went into v1.0. Thanks!

**Comment by rickhelmus** [comment]
Dear @kthyng,

Thanks for the swift response!

The previous paper provided a detailed overview of the functionality, implementation, infrastructure, benchmarks and a brief usage overview of patRoon 1.0. While most reviewers primarily focused on the contents of the manuscript, the website, inclusion of unit tests and software installation were also covered (for instance, providing Docker images with patRoon resulted from feedback of a reviewer). However, based on my impressions, I expect that JOSS reviews put more weight on the code quality, documentation, infrastructure and other software related issues.

Hope that helps and I am happy to give more details if needed!

**Comment by rickhelmus** [comment]
> @rickhelmus if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Regarding any potential reviewers, I came up with the following suggestions:

- jorainer
- lgatto*
- sgibb
- Zhiqiang-PANG
- jsychong
- wesleyburr*
- hechth*
- joewandy*

My selection was mainly based on experience with mass spectrometry and general experience in software development. People noted with a * have previous JOSS contributions.

Thanks,
Rick

**Comment by schymane** [comment]
> Hi @rickhelmus and thanks for your submission! I see your paper for version 1.0 — can you describe what the review process for that paper entailed? Was there a software review? I know that you are seeking to publish on the basis of improvements between the two versions, but it would still be helpful to know what review went into v1.0. Thanks!

Thanks @kthyng - in addition to @rickhelmus 's response, I'm adding in the link to the article plus JCheminf requirements for software articles, FYI: 

https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-00477-w

https://jcheminf.biomedcentral.com/submission-guidelines/preparing-your-manuscript/software

**Comment by danielskatz** [comment]
Thanks @rickhelmus and @schymane - I'm going to ask the JOSS editors to take a look at this to decide if we will review it - you should hear back in a week or two.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hi @rickhelmus, we are going to proceed with reviewing this submission; the next step is to find an editor to handle that process.

**Comment by kyleniemeyer** [comment]
@whedon invite @KristinaRiemer as editor

Hi @KristinaRiemer, can you edit this one?

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@kyleniemeyer I can edit this submission.

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
Thank you for providing the list of possible reviewers who have both software development and domain experience, @rickhelmus! 

@lgatto @wesleyburr @hechth would any of you be able and willing to review this JOSS submission of an R package for mass spectrometry analysis? You can view the software at the repo linked in the first comment.

**Comment by wesleyburr** [comment]
@KristinaRiemer: sure, so long as you're ok if I don't touch it until Jan 4+, when I return to work.

**Comment by KristinaRiemer** [comment]
@wesleyburr yup! That's totally fine. Thank you for agreeing to review!

**Comment by KristinaRiemer** [comment]
@whedon assign @wesleyburr as reviewer

**Comment by whedon** [comment]
OK, @wesleyburr is now a reviewer

**Comment by hechth** [comment]
Hi, yeah, I can do the review :)

**Comment by KristinaRiemer** [comment]
Hi @hechth, thank you so much for being able to do this review!

**Comment by KristinaRiemer** [comment]
@whedon add @hechth as reviewer

**Comment by whedon** [comment]
OK, @hechth is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4029.

**Comment by KristinaRiemer** [comment]
Okay, @wesleyburr & @hechth, the review will happen in the GitHub issue linked to in the previous message from whedon. Instructions and your checklists for the review are located there in the top comment. Let me know over there if you have questions for me or the author!

**Comment by lgatto** [comment]
Apologies for the late reply, but I won't be able to review the software/paper.

**Comment by KristinaRiemer** [comment]
@lgatto thanks for getting back about this! Luckily, we were able to find reviewers. Thanks!
