### ISSUE TITLE
[PRE REVIEW]: astroplan: an astropy affiliated package for observation planning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#398]
**Submitting author:** @bmorris3 (<a href="http://orcid.org/0000-0003-2528-3409">Brett Morris</a>)
**Repository:** <a href="https://github.com/astropy/astroplan" target ="_blank">https://github.com/astropy/astroplan</a>
**Version:** v0.3
**Editor:** @jakevdp
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @bmorris3. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bmorris3 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @jakevdp - the submitting author suggested you as an editor for this submission.

**Comment by bmorris3** [comment]
Hi @arfon and @jakevdp – may I temporarily retract this submission, while the authors and I are considering journal options?

**Comment by arfon** [comment]
@bmorris3 - sure thing. I'll mark this as paused.

**Comment by arfon** [comment]
> Hi @arfon and @jakevdp – may I temporarily retract this submission, while the authors and I are considering journal options?

@bmorris3 - did you decide what you want to do here?

**Comment by bmorris3** [comment]
@arfon After some discussion with the co-authors we've decided to submit elsewhere. But my next JOSS submission shouldn't be too far behind. Thanks again!

**Comment by arfon** [comment]
No problem :-)
