### ISSUE TITLE
[PRE REVIEW]: SpatialGEV: Fast Bayesian inference for spatial extreme value models in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3983]
**Submitting author:** @meixichen (<a href="http://orcid.org/0000-0003-1012-5352">Meixi Chen</a>)
**Repository:** <a href="https://github.com/meixichen/SpatialGEV" target ="_blank">https://github.com/meixichen/SpatialGEV</a>
**Version:** 0.0.0.9000
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c473e3a205bc4da8d8e4eec071190b8c/status.svg)](https://joss.theoj.org/papers/c473e3a205bc4da8d8e4eec071190b8c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c473e3a205bc4da8d8e4eec071190b8c"><img src="https://joss.theoj.org/papers/c473e3a205bc4da8d8e4eec071190b8c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c473e3a205bc4da8d8e4eec071190b8c/status.svg)](https://joss.theoj.org/papers/c473e3a205bc4da8d8e4eec071190b8c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @meixichen. **Currently, there isn't an JOSS editor assigned** to your paper.

@meixichen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1586

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (501.5 files/s, 26994.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               16             44            176            499
C/C++ Header                     3             34             47            157
Markdown                         2             36              0            135
TeX                              1             24              0            111
C++                              2              4              2             23
-------------------------------------------------------------------------------
SUM:                            24            142            225            925
-------------------------------------------------------------------------------


Statistical information for the repository '2c853898d4c3a67030ce677b' was
gathered on 2021/12/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
meixichen                        5           771            581           91.54
mlysy                            1           101             24            8.46

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
meixichen                   193           25.0          2.8               14.51
mlysy                        74           73.3         12.2               28.38
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03983/joss.03983/10.21105.joss.03983.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03983/joss.03983/10.21105.joss.03983.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/s0167-4730(98)00015-0 may be a valid DOI for title: Extreme Value Modelling of Hurricane Wind Speeds
- 10.1198/016214506000000780 may be a valid DOI for title: Bayesian Spatial Modeling of Extreme Precipitation Return Levels
- 10.1007/s10687-009-0098-2 may be a valid DOI for title: A Comparison Study of Extreme Precipitation from Six Different Regional Climate Models via Spatial Hierarchical Modeling
- 10.1002/env.2301 may be a valid DOI for title: Bayesian Hierarchical Modeling of Extreme Hourly Precipitation in Norway
- 10.1016/j.jhydrol.2015.09.023 may be a valid DOI for title: A Spatial Model to Examine Rainfall Extremes in Colorado’s Front Range
- 10.1201/b10905-6 may be a valid DOI for title: MCMC Using Hamiltonian Dynamics
- 10.1007/s13253-009-0010-1 may be a valid DOI for title: Continuous Spatial Process Models for Spatial Extreme Values
- 10.18637/jss.v070.i05 may be a valid DOI for title: TMB: Automatic Differentiation and Laplace Approximation

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @meixichen - I'm a little confused by your submission comment "The computational methods used this package and an application of it are described in a different paper (https://arxiv.org/abs/2110.07051), which has been submitted to another peer-reviewed journal."

Also, there's no open source license in the repo, which is required for JOSS review - see https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss

Next, the code is quite small, so because of that and the possible overlap with the other paper, I'm going to ask the JOSS editors to review this to see if we consider it in-scope to review.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hello @meixichen, unfortunately this submission does not meeting the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criteria for review by JOSS, so we will not be reviewing it.

Please consider our recommendations for [other venues for publishing/archiving software](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages).

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by meixichen** [comment]
Thank you both for letting me know and flagging the issues. I appreciated your time.
