### ISSUE TITLE
[PRE REVIEW]: DCISolver.jl: A Julia Solver for Nonlinear Optimization using Dynamic Control of Infeasibility

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3984]
**Submitting author:** @tmigot (<a href="http://orcid.org/0000-0001-7729-2513">Tangi Migot</a>)
**Repository:** <a href="https://github.com/JuliaSmoothOptimizers/DCISolver.jl" target ="_blank">https://github.com/JuliaSmoothOptimizers/DCISolver.jl</a>
**Version:** v0.2.4
**Editor:** @jbytecode
**Reviewers:** @odow, @jbcaillau
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/771e48a0ee4949b0e8b145bdbcc71ae2/status.svg)](https://joss.theoj.org/papers/771e48a0ee4949b0e8b145bdbcc71ae2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/771e48a0ee4949b0e8b145bdbcc71ae2"><img src="https://joss.theoj.org/papers/771e48a0ee4949b0e8b145bdbcc71ae2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/771e48a0ee4949b0e8b145bdbcc71ae2/status.svg)](https://joss.theoj.org/papers/771e48a0ee4949b0e8b145bdbcc71ae2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tmigot. **Currently, there isn't an JOSS editor assigned** to your paper.

@tmigot if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (593.1 files/s, 55795.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           20            261            198           2071
Markdown                         6            152              0            627
YAML                             6              3              3            153
TOML                             4              5              0             76
Bourne Shell                     1              4              0             12
TeX                              1              0              0             10
-------------------------------------------------------------------------------
SUM:                            38            425            201           2949
-------------------------------------------------------------------------------


Statistical information for the repository '88d3a76cbbae1f73a89c69eb' was
gathered on 2021/12/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3984 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03984/joss.03984/10.21105.joss.03984.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03984/joss.03984/10.21105.joss.03984.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/070679557 is OK
- 10.1007/s10589-014-9687-3 is OK
- 10.1007/s10107-004-0559-y is OK
- 10.21105/joss.00615 is OK
- 10.5281/zenodo.3969045 is OK
- 10.1287/ijoc.2021.1067 is OK
- 10.5281/zenodo.3948381 is OK
- 10.5281/zenodo.1188851 is OK
- 10.5281/zenodo.2558627 is OK
- 10.5281/zenodo.822073 is OK
- 10.5281/zenodo.3900668 is OK
- 10.5281/zenodo.2658672 is OK
- 10.1145/992200.992202 is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.1147/rd.471.0057 is OK
- 10.1145/962437.962438 is OK
- 10.1145/1236463.1236467 is OK
- 10.3390/pr6080106 is OK
- 10.13140/rg.2.1.2846.6803 is OK
- 10.1007/978-1-4419-6935-4_15 is OK
- 10.1007/978-1-4614-3226-5 is OK
- 10.1007/s00158-011-0666-3 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1137/141000671 is OK
- 10.1287/ijoc.2014.0623 is OK
- 10.5281/zenodo.3994983 is OK
- 10.5281/zenodo.2629034 is OK
- 10.1007/0-387-30065-1_4 is OK
- 10.1137/15M1020575 is OK
- 10.1287/mnsc.36.5.519 is OK
- 10.5281/zenodo.2655082 is OK
- 10.5281/zenodo.5056629 is OK

MISSING DOIs

- 10.47749/t/unicamp.2013.918998 may be a valid DOI for title: Controle dinâmico de infactibilidade para programação não linear

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @melissawm - you were suggested as the editor, and though I know you are at your requested limit, I wanted to see if you are willing to take this as well. If not, we will wait list until an editor in this area is available.

**Comment by danielskatz** [comment]
@whedon invite @melissawm as editor

**Comment by whedon** [comment]
@melissawm has been invited to edit this submission.

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/070679557 is OK
- 10.1007/s10589-014-9687-3 is OK
- 10.1007/s10107-004-0559-y is OK
- 10.21105/joss.00615 is OK
- 10.5281/zenodo.3969045 is OK
- 10.1287/ijoc.2021.1067 is OK
- 10.5281/zenodo.3948381 is OK
- 10.5281/zenodo.1188851 is OK
- 10.5281/zenodo.2558627 is OK
- 10.5281/zenodo.822073 is OK
- 10.5281/zenodo.3900668 is OK
- 10.5281/zenodo.2658672 is OK
- 10.1145/992200.992202 is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.1147/rd.471.0057 is OK
- 10.1145/962437.962438 is OK
- 10.1145/1236463.1236467 is OK
- 10.3390/pr6080106 is OK
- 10.13140/rg.2.1.2846.6803 is OK
- 10.1007/978-1-4419-6935-4_15 is OK
- 10.1007/978-1-4614-3226-5 is OK
- 10.1007/s00158-011-0666-3 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1137/141000671 is OK
- 10.1287/ijoc.2014.0623 is OK
- 10.5281/zenodo.3994983 is OK
- 10.5281/zenodo.2629034 is OK
- 10.1007/0-387-30065-1_4 is OK
- 10.1137/15M1020575 is OK
- 10.1287/mnsc.36.5.519 is OK
- 10.5281/zenodo.2655082 is OK
- 10.5281/zenodo.5056629 is OK
- 10.47749/T/UNICAMP.2013.918998 is OK
- 10.1007/s101070100263 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by tmigot** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03984/joss.03984/10.21105.joss.03984.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03984/joss.03984/10.21105.joss.03984.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
Given a potential conflict with @melissawm, I withdraw my request that she edit.

**Comment by danielskatz** [comment]
👋 @jbytecode - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @jbytecode as editor

**Comment by whedon** [comment]
@jbytecode has been invited to edit this submission.

**Comment by jbytecode** [comment]
@whedon assign me as editor

thank you @danielskatz

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
Dear @tmigot 

Do you have any suggestions for potential reviewers? You can also use the list [here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822).
Please mention the GitHub users without using the @ character (just because we don't want to bother them with unnecessary notifications). 

Thank you in advance.

**Comment by jbytecode** [comment]
@whedon check references from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/070679557 is OK
- 10.1007/s10589-014-9687-3 is OK
- 10.1007/s10107-004-0559-y is OK
- 10.21105/joss.00615 is OK
- 10.5281/zenodo.3969045 is OK
- 10.1287/ijoc.2021.1067 is OK
- 10.5281/zenodo.3948381 is OK
- 10.5281/zenodo.1188851 is OK
- 10.5281/zenodo.2558627 is OK
- 10.5281/zenodo.822073 is OK
- 10.5281/zenodo.3900668 is OK
- 10.5281/zenodo.2658672 is OK
- 10.1145/992200.992202 is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.1147/rd.471.0057 is OK
- 10.1145/962437.962438 is OK
- 10.1145/1236463.1236467 is OK
- 10.3390/pr6080106 is OK
- 10.13140/rg.2.1.2846.6803 is OK
- 10.1007/978-1-4419-6935-4_15 is OK
- 10.1007/978-1-4614-3226-5 is OK
- 10.1007/s00158-011-0666-3 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1137/141000671 is OK
- 10.1287/ijoc.2014.0623 is OK
- 10.5281/zenodo.3994983 is OK
- 10.5281/zenodo.2629034 is OK
- 10.1007/0-387-30065-1_4 is OK
- 10.1137/15M1020575 is OK
- 10.1287/mnsc.36.5.519 is OK
- 10.5281/zenodo.2655082 is OK
- 10.5281/zenodo.5056629 is OK
- 10.47749/T/UNICAMP.2013.918998 is OK
- 10.1007/s101070100263 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03984/joss.03984/10.21105.joss.03984.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03984/joss.03984/10.21105.joss.03984.pdf) :page_facing_up: :point_left:

**Comment by tmigot** [comment]
> Dear @tmigot
> 
> Do you have any suggestions for potential reviewers? You can also use the list [here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822). Please mention the GitHub users without using the @ character (just because we don't want to bother them with unnecessary notifications).
> 
> Thank you in advance.

Dear @jbytecode ,

Checking interests in Julia programming and optimization, the following potential reviewers might be interested : matbesancon, aivodji, odow, degleris1, jbcaillau, justinsgray, mewilhel

**Comment by jbytecode** [comment]
@tmigot - thank you so much for the list, indeed, it is very helpful.

**Comment by jbytecode** [comment]
👋👋👋 Dear @matbesancon  and  @aivodji  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "**DCISolver.jl: A Julia Solver for Nonlinear Optimization using Dynamic Control of Infeasibility**". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3984).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
👋👋👋 Dear @odow  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "**DCISolver.jl: A Julia Solver for Nonlinear Optimization using Dynamic Control of Infeasibility**". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3984).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by odow** [comment]
Yes I can do it.

**Comment by jbytecode** [comment]
@whedon add @odow as reviewer

@odow - Thank you so much for accepting our invitation. When we set the second reviewer, the process will start and I will inform you.

**Comment by whedon** [comment]
OK, @odow is now a reviewer

**Comment by jbytecode** [comment]
👋👋👋 Dear @jbcaillau  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "**DCISolver.jl: A Julia Solver for Nonlinear Optimization using Dynamic Control of Infeasibility**". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3984).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
Dear @jbcaillau, thank you for the quick reply.

Now, I am setting you as the second reviewer and then the review will start in an other GitHub issue.

Thank you.

**Comment by jbytecode** [comment]
@whedon add @jbcaillau as reviewer

**Comment by whedon** [comment]
OK, @jbcaillau is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3991.
