### ISSUE TITLE
[PRE REVIEW]: SurfinPy 2.0:  A Phase Diagram Generator for Surfaces and Bulk Phases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3985]
**Submitting author:** @jstse (<a href="http://orcid.org/0000-0002-1320-557X">Joshua Tse</a>)
**Repository:** <a href="https://github.com/symmy596/SurfinPy" target ="_blank">https://github.com/symmy596/SurfinPy</a>
**Version:** v2.0
**Editor:** @lucydot
**Reviewers:** @awvwgk
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3e3e853bf4eb3ea9e754228343ad6c8b/status.svg)](https://joss.theoj.org/papers/3e3e853bf4eb3ea9e754228343ad6c8b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3e3e853bf4eb3ea9e754228343ad6c8b"><img src="https://joss.theoj.org/papers/3e3e853bf4eb3ea9e754228343ad6c8b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3e3e853bf4eb3ea9e754228343ad6c8b/status.svg)](https://joss.theoj.org/papers/3e3e853bf4eb3ea9e754228343ad6c8b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jstse. **Currently, there isn't an JOSS editor assigned** to your paper.

@jstse if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01210 is OK
- 10.1021/acs.jpcc.0c07437 is OK
- 10.1039/D0CP00021C is OK
- 10.1021/acs.jpcc.9b09046 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 686

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.23 s (84.7 files/s, 262148.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22            365           1079           1318
YAML                            11              6             12           1039
Jupyter Notebook                28              0         315114            804
reStructuredText                25            509            691            391
Markdown                         8            109              0            276
TeX                              6             31              0            247
DOS Batch                        1              8              1             27
CSS                              1              3              0             12
make                             1              4              6             10
Bourne Shell                     1              1              0              5
-------------------------------------------------------------------------------
SUM:                           104           1036         316903           4129
-------------------------------------------------------------------------------


Statistical information for the repository '8bae86b70a53b7981ff97217' was
gathered on 2021/12/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Symington                  19          2431           1307            9.86
Benjamin Morgan                  6            45             20            0.17
jstse                           10           107             94            0.53
symmy596                        70         17803          16119           89.44

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Symington             2665          109.6         20.7                6.90
jstse                        97           90.7          3.7               10.31
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03985/joss.03985/10.21105.joss.03985.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03985/joss.03985/10.21105.joss.03985.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@jstse - your paper does not have any references, which is very unusual. Is there no previous work that you are basing this work on, such as papers, books, software, etc.?  Please see https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography for an example of how to do this.

**Comment by danielskatz** [comment]
@whedon invite @lucydot as editor

**Comment by whedon** [comment]
@lucydot has been invited to edit this submission.

**Comment by jstse** [comment]
@whedon generate pdf

**Comment by jstse** [comment]
Reference should now be fixed

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03985/joss.03985/10.21105.joss.03985.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03985/joss.03985/10.21105.joss.03985.pdf) :page_facing_up: :point_left:

**Comment by jstse** [comment]
Possible reviewers:
- dandavies99
- mkhorton

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01210 is OK
- 10.1021/acs.jpcc.0c07437 is OK
- 10.1039/D0CP00021C is OK
- 10.1021/acs.jpcc.9b09046 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
Also a note from the submission for @lucydot (or the editor, if someone else)
> surfinpy v2 is not considered for publication elsewhere, and adds to surfinpy v1 ([JOSS, DOI 10.21105/joss.01210](https://doi.org/10.21105/joss.01210)). v2 is a substantial addition to v1, which was limited to surface phase diagrams. v2 allows solid state chemists and physicists to build phase diagrams for bulk phases using data from DFT calculations including entropic terms from vibrational frequencies, and where available experimental corrections. v2's publication in JOSS will precede research papers from the Huddersfield and Bath research groups on a wide range of materials, including the MgO-CO2-H2O system, the doping of SrTiO3, and hydrogen defects in UO2.

**Comment by lucydot** [comment]
Hi @danielskatz @jstse - very happy to be editor for this

**Comment by lucydot** [comment]
@whedon assign @lucydot as editor

**Comment by whedon** [comment]
OK, the editor is @lucydot

**Comment by lucydot** [comment]
Hi @jstse I'll be your editor for this submission 👋

@dandavies99 are you available to review this submission? Note you may need to check conflict of interest - the JOSS CoI policy is [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy)

@mkhorton are you available to review again for JOSS?

**Comment by dandavies99** [comment]
Hi @lucydot, I'm happy to review this and don't declare any conflicts of interest. For full transparency, I worked in the same department as the authors at the University of Bath until 2018, and have never collaborated with any of the authors in funded research or work that is published.

If you're happy on that basis then feel free to assign me.

**Comment by mkhorton** [comment]
I'm full on peer reviews right now, but if you haven't found another reviewer by Jan I'd be happy to review.

**Comment by lucydot** [comment]
Thanks @dandavies99 - I'll assign you now.

And thanks @mkhorton I can see you are a very active reviewer for JOSS  ✨  - so can particularly understand why you may not be available to review for us now. I'll ping a few other people to see if they can help and take it from there.

**Comment by lucydot** [comment]
@whedon assign @dandavies99 as reviewer

**Comment by whedon** [comment]
OK, @dandavies99 is now a reviewer

**Comment by lucydot** [comment]
@awvwgk, @amandadumi or @jeffhammond are you available to review this submission? It appears that each of you have the Python and domain knowledge needed.

**Comment by awvwgk** [comment]
Sure, I am available to review this one.

**Comment by lucydot** [comment]
@awvwgk excellent! I'll assign you now.

**Comment by lucydot** [comment]
@whedon assign @awvwgk as reviewer

**Comment by whedon** [comment]
OK, @awvwgk is now a reviewer

**Comment by lucydot** [comment]
@awvwgk @dandavies99 @jstse it looks like we are ready to start the review! ✨ 

I'll now ask our bot Whedon to start a review issue thread (this is the pre-review thread).

Please email me or (preferred) ping me in the new review thread with any questions you have about the process. There are review guidelines and a checklist at the top of the new thread (the link will appear below), and there is further reviewer documentation [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

We're normally asking for reviews to be complete within a 4-6 week period however I think given that many of us will be taking a break over Christmas (myself included) and so a 1-2 week delay might be expected and is reasonable. As the review is usually an iterative process it's best for reviews to start earlier in that timeline. You don't need to write a full review in one sitting - rather it's a back-and-forth conversation between reviewers, author, editor and our bot Whedon.

**Comment by lucydot** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4014.
