### ISSUE TITLE
[PRE REVIEW]: TransBigData: A Python package for transportation spatio-temporal big data processing, analysis and visualization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3986]
**Submitting author:** @ni1o1 (<a href="http://orcid.org/0000-0003-2513-2969">Qing Yu</a>)
**Repository:** <a href="https://github.com/ni1o1/transbigdata" target ="_blank">https://github.com/ni1o1/transbigdata</a>
**Version:** v0.2.7
**Editor:** @martinfleis
**Reviewers:** @jGaboardi, @anitagraser
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d1055fe3105dfa2dcff4cb6c7688a79b/status.svg)](https://joss.theoj.org/papers/d1055fe3105dfa2dcff4cb6c7688a79b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d1055fe3105dfa2dcff4cb6c7688a79b"><img src="https://joss.theoj.org/papers/d1055fe3105dfa2dcff4cb6c7688a79b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d1055fe3105dfa2dcff4cb6c7688a79b/status.svg)](https://joss.theoj.org/papers/d1055fe3105dfa2dcff4cb6c7688a79b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ni1o1. **Currently, there isn't an JOSS editor assigned** to your paper.

@ni1o1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 623

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03986/joss.03986/10.21105.joss.03986.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03986/joss.03986/10.21105.joss.03986.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jclepro.2020.119974 is OK
- 10.1016/j.jclepro.2020.122471 is OK
- 10.1016/j.trc.2020.102672 is OK
- 10.1016/j.apenergy.2020.115038 is OK
- 10.1016/j.jclepro.2020.125567 is OK

MISSING DOIs

- 10.1177/03611981211036684 may be a valid DOI for title: Taxi Global Positioning System Data in Urban Road Network: A Methodology to Identify Key Road Clusters Based on Travel Speed–Traffic Volume Correlation
- 10.1016/j.ijtst.2021.01.002 may be a valid DOI for title: Partitioning urban road network based on travel speed correlation

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @martinfleis - you've been suggested as the editor - are you able to do this?

A first step would be to do some minor proofreading of the paper and the references, including missing DOIs

**Comment by danielskatz** [comment]
@whedon invite @martinfleis as editor

**Comment by whedon** [comment]
@martinfleis has been invited to edit this submission.

**Comment by martinfleis** [comment]
@whedon assign me as editor

@danielskatz yes, I am able to edit this paper.

**Comment by martinfleis** [comment]
👋 Hi @ni1o1,

if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Can you please check the suggestions on references listed in https://github.com/openjournals/joss-reviews/issues/3986#issuecomment-989993592 and add missing DOIs (if available)?

Also, could you try to format the list starting on a line 35 of the manuscript as an actual markdown list? The syntax should look like this:

```md
- First item
- Second item
- Third item
- Fourth item
```

**Comment by ni1o1** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jclepro.2020.119974 is OK
- 10.1016/j.jclepro.2020.122471 is OK
- 10.1016/j.trc.2020.102672 is OK
- 10.1016/j.apenergy.2020.115038 is OK
- 10.1016/j.jclepro.2020.125567 is OK
- 10.1177/03611981211036684 is OK
- 10.1016/j.ijtst.2021.01.002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ni1o1** [comment]
@whedon  generate pdf

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by ni1o1** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by ni1o1** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03986/joss.03986/10.21105.joss.03986.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03986/joss.03986/10.21105.joss.03986.pdf) :page_facing_up: :point_left:

**Comment by ni1o1** [comment]
> 👋 Hi @ni1o1,
> 
> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 
> Can you please check the suggestions on references listed in [#3986 (comment)](https://github.com/openjournals/joss-reviews/issues/3986#issuecomment-989993592) and add missing DOIs (if available)?
> 
> Also, could you try to format the list starting on a line 35 of the manuscript as an actual markdown list? The syntax should look like this:
> 
> ```lisp
> - First item
> - Second item
> - Third item
> - Fourth item
> ```

Dear @martinfleis ,
Checking interests in Python programming and transportation data science, the following potential reviewers might be interested :
RafalKucharskiPK/,katmratliff,EricaEgg,nsaunier,fil,GalenStocking,dvysardana,kellieotto,ethanwhite,earino,sgrieve

**Comment by ni1o1** [comment]
The missing DOIs issue and the markdown list issue are also fixed, thank you for editting our paper. @martinfleis

**Comment by martinfleis** [comment]
@ni1o1 Thanks! Check https://github.com/ni1o1/transbigdata/pull/3 that should fix the formatting issue.

**Comment by martinfleis** [comment]
👋👋👋 Dear @davidbailey, @jGaboardi, and @anitagraser, 

Would you be willing to assist in reviewing this submission for JOSS (Journal of Open Source Software)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "TransBigData: A Python package for transportation spatio-temporal big data processing, analysis and visualization". You can find more information at the top of this Github issue (#3986).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

Thank you!

**Comment by jGaboardi** [comment]
@martinfleis I can do it.

**Comment by martinfleis** [comment]
@whedon assign @jGaboardi as reviewer

**Comment by whedon** [comment]
OK, @jGaboardi is now a reviewer

**Comment by anitagraser** [comment]
@martinfleis yes, count me in.

**Comment by martinfleis** [comment]
@whedon add @anitagraser as reviewer

**Comment by whedon** [comment]
OK, @anitagraser is now a reviewer

**Comment by anitagraser** [comment]
I haven't had chance to look at the code yet. Concerning the paper, I think there is one point in the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) that is currently not addressed: 

> A description of how this software compares to other commonly-used packages in this research area.

**Comment by jGaboardi** [comment]
Has the paper already been moved from 'pre-review' to 'review'? Are we meant to have started reviewing already?

**Comment by martinfleis** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4021.
