### ISSUE TITLE
[PRE REVIEW]: Calcs: A Python package for calculating stellar chromospheric activity parameters of Ca II H&K lines with LAMOST LRS spectra

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3987]
**Submitting author:** @yoxilyze (<a href="http://orcid.org/0000-0001-5299-9715">张伟涛</a>)
**Repository:** <a href="https://github.com/sadatalib/calcs" target ="_blank">https://github.com/sadatalib/calcs</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/460cec55f9b22ad75ce113d53115b5d6/status.svg)](https://joss.theoj.org/papers/460cec55f9b22ad75ce113d53115b5d6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/460cec55f9b22ad75ce113d53115b5d6"><img src="https://joss.theoj.org/papers/460cec55f9b22ad75ce113d53115b5d6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/460cec55f9b22ad75ce113d53115b5d6/status.svg)](https://joss.theoj.org/papers/460cec55f9b22ad75ce113d53115b5d6)
```

**Author instructions**

Thanks for submitting your paper to JOSS @yoxilyze. **Currently, there isn't an JOSS editor assigned** to your paper.

@yoxilyze if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1007

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (360.5 files/s, 36543.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5             61             79            304
Markdown                         2             74              0            172
TeX                              1              8              0            113
-------------------------------------------------------------------------------
SUM:                             8            143             79            589
-------------------------------------------------------------------------------


Statistical information for the repository '089f9e4b5f8cbc32571482f3' was
gathered on 2021/12/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
hehan-dev                        7            76             59           18.65
yxilyze                         16           508             81           81.35

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
hehan-dev                    68           89.5          0.0               10.29
yxilyze                     376           74.0          0.1                3.99
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1674-4527/12/9/003 is OK
- 10.1088/1674-4527/12/7/002 is OK
- 10.1086/156618 is OK
- 10.1086/130324 is OK
- 10.1051/0004-6361/201219868 is OK
- 10.1088/1674-4527/15/8/013 is OK
- 10.1038/ncomms11058 is OK
- 10.3847/2515-5172/abd93b is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03987/joss.03987/10.21105.joss.03987.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03987/joss.03987/10.21105.joss.03987.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @yoxilyze - This paper does not meeting the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criteria for review by JOSS, so we will not be reviewing it.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
