### ISSUE TITLE
[PRE REVIEW]: text2sdg: An open-source solution to monitoring sustainable development goals from text

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3988]
**Submitting author:** @psychobas (<a href="http://orcid.org/0000-0002-3999-1388">Dominik S. Meier</a>)
**Repository:** <a href="https://github.com/dwulff/text2sdg" target ="_blank">https://github.com/dwulff/text2sdg</a>
**Version:** 0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4dd2b396e39ac2c3bbc750a12431412c/status.svg)](https://joss.theoj.org/papers/4dd2b396e39ac2c3bbc750a12431412c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4dd2b396e39ac2c3bbc750a12431412c"><img src="https://joss.theoj.org/papers/4dd2b396e39ac2c3bbc750a12431412c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4dd2b396e39ac2c3bbc750a12431412c/status.svg)](https://joss.theoj.org/papers/4dd2b396e39ac2c3bbc750a12431412c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @psychobas. **Currently, there isn't an JOSS editor assigned** to your paper.

@psychobas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #3988 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03988/joss.03988/10.21105.joss.03988.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03988/joss.03988/10.21105.joss.03988.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.6084/m9.figshare.11106113.v1 is OK
- 10.17632/87txkw7khs.1 is OK
- 10.5281/zenodo.3817445 is OK
- 10.5281/zenodo.3567769 is OK

MISSING DOIs

- 10.18356/9789210056083 may be a valid DOI for title: The Sustainable Development Goals Report 2021

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@psychobas - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOI that whedon suggests, but note that this be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references from branch joss` to check again, and the command `@whedon generate pdf from branch joss` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by psychobas** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.6084/m9.figshare.11106113.v1 is OK
- 10.17632/87txkw7khs.1 is OK
- 10.5281/zenodo.3817445 is OK
- 10.5281/zenodo.3567769 is OK
- 10.18356/9789210056083 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by psychobas** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03988/joss.03988/10.21105.joss.03988.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03988/joss.03988/10.21105.joss.03988.pdf) :page_facing_up: :point_left:

**Comment by psychobas** [comment]
@danielskatz thanks for the fast processing! I added the missing DOI and recompiled the PDF.

**Comment by kyleniemeyer** [comment]
Hello @psychobas, unfortunately this submission does not meeting the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criteria for review by JOSS, so we will not be reviewing it.

Please consider our recommendations for [other venues for publishing/archiving software](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages).

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
