### ISSUE TITLE
[PRE REVIEW]: Web interface for reflectivity fitting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#399]
**Submitting author:** @mdoucet (<a href="http://orcid.org/0000-0002-5560-6478">Mathieu Doucet</a>)
**Repository:** <a href="https://github.com/neutrons/web_reflectivity" target ="_blank">https://github.com/neutrons/web_reflectivity</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSS @mdoucet. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mdoucet if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by mdoucet** [comment]
Looking at the list of potential reviewers, @tacaswell would be a good reviewer for this work.

**Comment by mdoucet** [comment]
Other potential reviewers may be @jochym and @bjmorgan.

**Comment by mdoucet** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by mdoucet** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current JOSS editors:

```
@arfon
@pjotrp
@arokem
@karthik
@brainstorm
@kyleniemeyer
@katyhuff
@acabunoc
@jakevdp
@tracykteal
@mgymrek
@danielskatz
@leeper
@labarba
@lheagy
@cMadan
@Kevin-Mattheus-Moerman
@biorelated
```

**Comment by mdoucet** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
I'm sorry @mdoucet, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@jochym, @bjmorgan, would either of you be willing to review this submission for JOSS?

**Comment by mdoucet** [comment]
Another possible reviewer could be @betatim.

**Comment by arfon** [comment]
> Another possible reviewer could be @betatim.

@betatim - any chance you could help us with this submission?

**Comment by mdoucet** [comment]
Another possible reviewer could be @khinsen.

**Comment by mdoucet** [comment]
Another possible reviewer could be @nicoguaro.

**Comment by nicoguaro** [comment]
@arfon, @mdoucet, I think I can review this one. But at this point of year it will probably take longer.

**Comment by arfon** [comment]
@nicoguaro - fantastic, many thanks!

**Comment by arfon** [comment]
@whedon assign @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nicoguaro

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/469. Feel free to close this issue now!

**Comment by arfon** [comment]
@nicoguaro @mdoucet - see you over in #469 for the actual paper review.
