### ISSUE TITLE
[PRE REVIEW]: SimpleFOC: A Field Oriented Control (FOC) Library for Controlling Brushless Direct Current (BLDC) and Stepper Motors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3999]
**Submitting author:** @askuric (<a href="http://orcid.org/0000-0002-3323-4482">Antun Skuric</a>)
**Repository:** https://github.com/simplefoc/Arduino-FOC/
**Branch with paper.md** (empty if default branch): 
**Version:** v2.2
**Editor:** @gkthiruvathukal
**Reviewers:** @sea-bass, @ixjlyons
**Managing EiC:** Kyle Niemeyer

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4382445f249e064e9f0a7f6c1bb06b1d/status.svg)](https://joss.theoj.org/papers/4382445f249e064e9f0a7f6c1bb06b1d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4382445f249e064e9f0a7f6c1bb06b1d"><img src="https://joss.theoj.org/papers/4382445f249e064e9f0a7f6c1bb06b1d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4382445f249e064e9f0a7f6c1bb06b1d/status.svg)](https://joss.theoj.org/papers/4382445f249e064e9f0a7f6c1bb06b1d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @askuric. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @adi3.

@askuric if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3999 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (1026.8 files/s, 121956.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             48           1316           2133           5679
Arduino Sketch                  64           1141           2048           2543
C/C++ Header                    35            432           1223           1044
Markdown                         3             79              0            231
YAML                             1             12              1             52
-------------------------------------------------------------------------------
SUM:                           151           2980           5405           9549
-------------------------------------------------------------------------------


Statistical information for the repository '49467072c8e83df4b385089a' was
gathered on 2021/12/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ATILIUS-REGULUS                  1             6              0            0.02
Antun Skuric                     4             7              7            0.04
David                            4             6              3            0.02
Jordan Cormack                   1           124              0            0.33
Owen Williams                   25          1216            485            4.57
Richard Unger                   30          3412           1626           13.52
SKURIC Antun                     1             2              3            0.01
Sergey Royz                      1           144              0            0.39
Sroka, Kamil                     1           180            186            0.98
Stefan Dessens                   6           538             50            1.58
Tim Meehan                       3            32             33            0.17
askuric                        162         17319           8835           70.20
candyriver                       1           130              0            0.35
maxime                          13          1902            997            7.78
qazxswedcvfrtgbnhyuj             1             1              1            0.01
tschundler                       1             6              3            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ATILIUS-REGULUS               1           16.7         10.1                0.00
Antun Skuric                  4           57.1          4.7                0.00
David                         5           83.3          8.5                0.00
Jordan Cormack               77           62.1          6.5               25.97
Owen Williams               504           41.4         12.4               27.98
Richard Unger              1922           56.3          5.7               19.98
SKURIC Antun                  2          100.0          0.4                0.00
Sroka, Kamil                136           75.6          4.1                8.09
Stefan Dessens              535           99.4          5.1               26.17
Tim Meehan                    5           15.6         12.8               40.00
askuric                    8204           47.4          8.4               31.61
maxime                      432           22.7          4.7               21.76
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03999/joss.03999/10.21105.joss.03999.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03999/joss.03999/10.21105.joss.03999.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check references from branch joss_paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss_paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/codit49905.2020.9263910 may be a valid DOI for title: Model-Based Design Streamlines for STM32 Motor Control Embedded Software System
- 10.1109/eiconrus.2018.8317164 may be a valid DOI for title: PMSM vector control techniques—A survey
- 10.51257/o-42509210 may be a valid DOI for title: Mécatronique
- 10.1049/iet-pel.2018.5231 may be a valid DOI for title: Hybrid field oriented and direct torque control for sensorless BLDC motors used in aerial drones
- 10.1109/icrera.2018.8566749 may be a valid DOI for title: High performance foc for induction motors with low cost atsam3x8e microcontroller
- 10.21105/joss.00456 may be a valid DOI for title: ros_control: A generic and simple control framework for ROS
- 10.1109/iprecon49514.2020.9315210 may be a valid DOI for title: Performance Analysis of Vector controlled PMSM Drive modulated with Sinusoidal PWM and Space Vector PWM
- 10.1109/iecon.2016.7793092 may be a valid DOI for title: SoC FPGA-based field oriented control of BLDC motor using low resolution Hall sensor
- 10.1109/ieit53149.2021.9587419 may be a valid DOI for title: Wireless Enabled Brushless DC Motor Controller for Robotic Application
- 10.1109/iros.2012.6386252 may be a valid DOI for title: Actuator design for high force proprioceptive control in fast legged locomotion

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @askuric, while we are getting started with assigning an editor and finding reviewers, could you take a look at the missing DOIs for references in your paper and begin adding those?

**Comment by kyleniemeyer** [comment]
@whedon invite @gkthiruvathukal as editor

Hi @gkthiruvathukal, could you edit this submission?

**Comment by whedon** [comment]
@gkthiruvathukal has been invited to edit this submission.

**Comment by askuric** [comment]
Hello @kellyrowland, 
Thanks for setting up the pre-review, I am very happy to be starting this process. 
I've updated the references to include the DOIs and ISBNs where applicable. 

Regarding the reviewers, I've passed through the list and I'd maybe suggest some experts in the control systems domain:
- sea-bass
- destogl
- ixjlyons
- CameronDevine

**Comment by gkthiruvathukal** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer Yes, I will edit this submission. Thanks to @askuric for suggesting some prospective reviewers.
I will try to get this moving before the holidays but am going to be having some much-needed downtime (soon).

**Comment by gkthiruvathukal** [comment]
@askuric Thank you for your patience. I was out of the office until 4th January. Then I became department chair at my university and have been transitioning into this role. I'm finally able to resume work on my JOSS workload.

@sea-bass and @destogl, Are you willing to contribute a review for this JOSS submission?

**Comment by askuric** [comment]
Congratulations on your new position @gkthiruvathukal and thanks again for accepting the editor role for our paper.
I am very happy to hear that the process is starting, I am looking forward to hear your feedback on our project!

**Comment by gkthiruvathukal** [comment]
Thank you, @askuric. Hopefully, we can get review started soon!  I need two reviewers to proceed. We should be under way in a few days (based on recent submissions I am editing).

**Comment by sea-bass** [comment]
I am happy to review for this submission.

**Comment by gkthiruvathukal** [comment]
@whedon assign @sea-bass  as reviewer

**Comment by whedon** [comment]
OK, @sea-bass  is now a reviewer

**Comment by gkthiruvathukal** [comment]
@ixjlyons, are you willing to contribute a review for this JOSS submission?

**Comment by ixjlyons** [comment]
Sure, I can review. Sorry for the delay.

**Comment by gkthiruvathukal** [comment]
@whedon add @ixjlyons as reviewer

**Comment by gkthiruvathukal** [comment]
@editorialbot add @ixjlyons as reviewer

**Comment by gkthiruvathukal** [comment]
@editorialbot start review
