### ISSUE TITLE
[PRE REVIEW]: liionpack: A Python package for simulating packs of batteries with PyBaMM

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4000]
**Submitting author:** @TomTranter (<a href="http://orcid.org/0000-0003-4721-5941">Thomas Tranter</a>)
**Repository:** <a href="https://github.com/pybamm-team/liionpack" target ="_blank">https://github.com/pybamm-team/liionpack</a>
**Version:** v1.0.0
**Editor:** @timtroendle
**Reviewers:** @EricaEgg, @mefuller
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1187d2a3788a6751cd4cce3dc016b7f3/status.svg)](https://joss.theoj.org/papers/1187d2a3788a6751cd4cce3dc016b7f3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1187d2a3788a6751cd4cce3dc016b7f3"><img src="https://joss.theoj.org/papers/1187d2a3788a6751cd4cce3dc016b7f3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1187d2a3788a6751cd4cce3dc016b7f3/status.svg)](https://joss.theoj.org/papers/1187d2a3788a6751cd4cce3dc016b7f3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @TomTranter. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jgostick.

@TomTranter if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1440

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (783.7 files/s, 107722.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          36            562            838           2776
Markdown                         7            216              0            487
Jupyter Notebook                 9              0           2998            464
YAML                             9             41             25            354
JSON                             1             22              0            138
TeX                              1              9              0             89
JavaScript                       1              1              2             25
INI                              1              2              0             19
CSS                              1              0              0              4
-------------------------------------------------------------------------------
SUM:                            66            853           3863           4356
-------------------------------------------------------------------------------


Statistical information for the repository 'ab16f18676d13f9b6ba7c7ed' was
gathered on 2021/12/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ferran Brosa Planell             5           135             92            0.69
Gavin Wiggins                   28           959            744            5.18
Priyanshu Agarwal                4            79             25            0.32
Robert Timms                     4           189            173            1.10
Saransh                         12           324            396            2.19
Tom Tranter                    200         16418          12703           88.50
TomTranter                       1            16              9            0.08
Valentin Sulzer                 11           315            159            1.44
ksnvikrant                       1            38              0            0.12
tomtranter                       1            93             38            0.40

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ferran Brosa Planell         10            7.4          1.2               20.00
Gavin Wiggins               219           22.8          1.1               23.74
Priyanshu Agarwal            51           64.6          0.7               13.73
Robert Timms                 47           24.9          1.5               48.94
Saransh                     168           51.9          0.8               10.12
Tom Tranter                3487           21.2          0.7                7.92
Valentin Sulzer             222           70.5          2.0               28.83
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/s12532-018-0139-4 may be a valid DOI for title: CasADi: a software framework for nonlinear optimization and optimal control
- 10.1149/osf.io/67ckj may be a valid DOI for title: Python battery mathematical modelling (PyBaMM)
- 10.1016/0010-4485(76)90063-4 may be a valid DOI for title: The modified nodal approach to network analysis
- 10.1149/1945-7111/aba44b may be a valid DOI for title: Probing heterogeneity in li-ion batteries with coupled multiscale models of electrochemistry and thermal transport using tomographic domains
- 10.1149/1945-7111/ab9050 may be a valid DOI for title: Development of experimental techniques for parameterization of multi-scale lithium-ion battery models
- 10.1149/1945-7111/abbce4 may be a valid DOI for title: A suite of reduced-order models of a single-layer lithium-ion pouch cell

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04000/joss.04000/10.21105.joss.04000.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04000/joss.04000/10.21105.joss.04000.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @jgostick as editor

Hi @jgostick, could you edit this submission?

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @TomTranter, while we are getting started assigning an editor and finding reviewers, could you take a look at the missing DOI messages above and see about adding those to the paper?

**Comment by jgostick** [comment]
@tomtranter was my postdoc for 2 years from 2018-2019 and we have a slew of papers togehter.  If this is not a conflict of interest, the I'm OK to do it.  Just checking with you first.

**Comment by TomTranter** [comment]
@kyleniemeyer sure I'll set up a review branch and make them there.

**Comment by TomTranter** [comment]
I searched your reviewer database for people comfortable reviewing batteries and these names came up: mefuller, yangbai90, EricaEgg

**Comment by jgostick** [comment]
Hi @kyleniemeyer , I forgot to mention you in my query above.  Am in eligible to edit this one?

**Comment by kyleniemeyer** [comment]
Thanks @jgostick, I think we would prefer to avoid the conflict of interest here, and wait until someone else becomes available to edit.

@TomTranter Thanks for the reviewer suggestions! Your submission will be on our waitlist, until someone else becomes available to edit soon.

**Comment by TomTranter** [comment]
@kyleniemeyer I don't really see that there will be a conflict. I haven't worked with @jgostick for 3 years and I know that he would be more than fair. How long do you expect that I have to wait?

**Comment by kthyng** [comment]
Hi @TomTranter — sorry but while I can't quite remember the rule of thumb for how long a conflict between postdoc advisor/postdoc is, it is at least 5 years and this is not a gray area. I see at least 4 other editors that may be appropriate for this submission but they are all currently full. Hopefully it won't be too long to get some availability! Thanks for your patience.

**Comment by danielskatz** [comment]
fwiw, JOSS COI guidelines are in https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy

**Comment by danielskatz** [comment]
👋 @@timtroendle - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @timtroendle as editor

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by timtroendle** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by timtroendle** [comment]
Happy to serve as the editor here.

Hello @TomTranter, I'll be looking for reviewers. If you have any questions in the process, let me know.

**Comment by TomTranter** [comment]
Hi @timtroendle, thanks for picking this up. I mentioned above the following may be suitable given their battery background mefuller, yangbai90, EricaEgg

**Comment by timtroendle** [comment]
:wave: @mefuller, @yangbai90 & @EricaEgg, would any of you be willing to review this submission for JOSS?

**Comment by mefuller** [comment]
I'd be happy to review

**Comment by EricaEgg** [comment]
I am also happy to review.

**Comment by timtroendle** [comment]
Thanks @EricaEgg and @mefuller, that's great to hear. Let's start the review right away. @yangbai90, should you be interested in joining the review at a later stage, just let me know.

**Comment by timtroendle** [comment]
@whedon add @EricaEgg as reviewer

**Comment by whedon** [comment]
OK, @EricaEgg is now a reviewer

**Comment by timtroendle** [comment]
@whedon add @mefuller as reviewer

**Comment by whedon** [comment]
OK, @mefuller is now a reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4051.

**Comment by timtroendle** [comment]
Great. I've added you as a reviewer.
