### ISSUE TITLE
[PRE REVIEW]: Octopus-sensing: A python library for human behavior studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4001]
**Submitting author:** @nastaran62 (<a href="http://orcid.org/0000-0002-6082-9772">Nastaran Saffaryazdi</a>)
**Repository:** <a href="https://github.com/octopus-sensing/octopus-sensing" target ="_blank">https://github.com/octopus-sensing/octopus-sensing</a>
**Version:** v3.1.0
**Editor:** @ajstewartlang
**Reviewers:** @ixjlyons, @peircej
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/771f1e646589e0981d21be4e002fd28f/status.svg)](https://joss.theoj.org/papers/771f1e646589e0981d21be4e002fd28f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/771f1e646589e0981d21be4e002fd28f"><img src="https://joss.theoj.org/papers/771f1e646589e0981d21be4e002fd28f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/771f1e646589e0981d21be4e002fd28f/status.svg)](https://joss.theoj.org/papers/771f1e646589e0981d21be4e002fd28f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nastaran62. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @oliviaguest.

@nastaran62 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 821

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (970.2 files/s, 106004.2 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           57           1078           2222           2979
XML                               3              0              0           1538
reStructuredText                 16            313            191            661
TeX                               1             20              0            155
Markdown                          2             29              0             90
Bourne Shell                      1             10              5             68
YAML                              2             17              5             68
TOML                              1              5              5             40
MATLAB                            1              3              0             31
DOS Batch                         1              8              1             26
make                              1              7             13             20
Bourne Again Shell                1              0              0              5
INI                               1              0              0              2
--------------------------------------------------------------------------------
SUM:                             88           1490           2442           5683
--------------------------------------------------------------------------------


Statistical information for the repository '0440c69a766d1cb0abb544cc' was
gathered on 2021/12/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aidin Gharibnavaz               28          1901            306           12.12
Nastaran                        76          8435           5145           74.56
Nastaran Saffaryazdi             7          1951            474           13.31
nastaran62                       1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aidin Gharibnavaz          1412           74.3          7.4               20.54
Nastaran                   4840           57.4          4.7               10.89
Nastaran Saffaryazdi         41            2.1         22.5               12.20
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04001/joss.04001/10.21105.joss.04001.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04001/joss.04001/10.21105.joss.04001.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.biopsycho.2010.03.010 may be a valid DOI for title: Autonomic nervous system activity in emotion: A review
- 10.3390/brainsci10020085 may be a valid DOI for title: Multimodal Affective State Assessment Using fNIRS+ EEG and Spontaneous Facial Expression
- 10.1016/j.imu.2020.100372 may be a valid DOI for title: Development of a Real-Time Emotion Recognition System Using Facial Expressions and EEG based on machine learning and deep neural network methods
- 10.5334/pb-46-1-2-99 may be a valid DOI for title: Psychopathy and physiological detection of concealed information: A review
- 10.1016/j.ijhcs.2018.10.003 may be a valid DOI for title: Observers’ physiological measures in response to videos can be used to detect genuine smiles
- 10.1109/access.2020.3007109 may be a valid DOI for title: Affective Robot Story-Telling Human-Robot Interaction: Exploratory Real-Time Emotion Estimation Analysis Using Facial Expressions and Physiological Signals
- 10.1109/t-affc.2011.15 may be a valid DOI for title: Deap: A database for emotion analysis; using physiological signals
- 10.1016/j.entcs.2019.04.009 may be a valid DOI for title: Emotion recognition from physiological signal analysis: A review
- 10.1007/s10111-020-00641-0 may be a valid DOI for title: Towards measuring cognitive load through multimodal physiological data
- 10.3390/s20030592 may be a valid DOI for title: Human emotion recognition: Review of sensors and methods

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @nastaran62, thanks for your interest in JOSS. Unfortunately, we do not have any editors from this area available at the moment, so this submission will be on our waitlist until someone becomes available to edit.

In the meantime, could you please take a look at the missing DOIs in your article and resolve those? Also, any reviewer suggestions you could make would be helpful. Thanks!

**Comment by nastaran62** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.biopsycho.2010.03.010 is OK
- 10.1037/pspi0000337 is OK
- 10.3390/brainsci10020085 is OK
- 10.1016/j.imu.2020.100372 is OK
- 10.5334/pb-46-1-2-99 is OK
- 10.1016/j.ijhcs.2018.10.003 is OK
- 10.1186/s40561-018-0080-z is OK
- 10.1109/ACCESS.2020.3007109 is OK
- 10.1109/TCYB.2020.2974688 is OK
- 10.3390/s18072074 is OK
- 10.1109/T-AFFC.2011.15 is OK
- 10.1016/j.entcs.2019.04.009 is OK
- 10.1007/s10111-020-00641-0 is OK
- 10.1111/jcal.12590 is OK
- 10.3390/s20030592 is OK
- 10.1109/COMST.2017.2731979 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by nastaran62** [comment]
Hi @kyleniemeyer , Thanks for your comments. I fixed the missing DOIs.

We are suggesting the following reviewers:
@Tam-Pham
@TomDonoghue
@peircej
@ixjlyons

Thank you very much

**Comment by ixjlyons** [comment]
I can review

**Comment by kthyng** [comment]
@ajstewartlang Are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @ajstewartlang as editor

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon assign @ixjlyons as reviewer

**Comment by whedon** [comment]
OK, @ixjlyons is now a reviewer

**Comment by ajstewartlang** [comment]
> I can review

Thanks @ixjlyons - much appreciated! Once I've added a second reviewer I'll start the review process.

**Comment by peircej** [comment]
@ajstewartlang I can review this one too :-)

**Comment by ajstewartlang** [comment]
@whedon add @peircej as reviewer

**Comment by whedon** [comment]
OK, @peircej is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4045.
