### ISSUE TITLE
[PRE REVIEW]: ReMove: A Configuration Tool for Robot-Assisted Experiments in Rehabilitation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4003]
**Submitting author:** @Rehablab (<a href="http://orcid.org/0000-0001-8781-301X">Qiang Xu</a>)
**Repository:** <a href="https://github.com/Rehablab/ReMove" target ="_blank">https://github.com/Rehablab/ReMove</a>
**Version:** v1.0.0
**Editor:** @adi3
**Reviewers:** @AustinTSchaffer, @sneakers-the-rat
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ba84509d8d520542b62ce321509ba604/status.svg)](https://joss.theoj.org/papers/ba84509d8d520542b62ce321509ba604)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ba84509d8d520542b62ce321509ba604"><img src="https://joss.theoj.org/papers/ba84509d8d520542b62ce321509ba604/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ba84509d8d520542b62ce321509ba604/status.svg)](https://joss.theoj.org/papers/ba84509d8d520542b62ce321509ba604)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Rehablab. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @prashjha.

@Rehablab if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1012

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (301.7 files/s, 150655.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              7            421              0          17141
C#                              26            111            148           1939
JSON                             3              0              0            432
Markdown                         2             46              0            101
Unity-Prefab                     1              0              0             77
TeX                              1              3              0             30
YAML                             1              1              4             19
-------------------------------------------------------------------------------
SUM:                            41            582            152          19739
-------------------------------------------------------------------------------


Statistical information for the repository 'db678bb452291ffe19f31b5f' was
gathered on 2021/12/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4003 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.2340/16501977-0936 may be a valid DOI for title: Long-term benefits of progressive resistance training in chronic stroke: a 4-year follow-up
- 10.2340/16501977-0129 may be a valid DOI for title: Progressive resistance training after stroke: effects on muscle strength, muscle tone, gait performance and perceived participation
- 10.1310/tsr1906-471 may be a valid DOI for title: Resistance training for gait speed and total distance walked during the chronic stage of stroke: a meta-analysis

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hello @Rehablab, the JOSS editorial board is going to review your submission to see if it meets our requirements; we will get back to you within a week or two on this.

**Comment by danielskatz** [comment]
@rehablab - I suspect this doesn't compile because of one or more of three things:

* the blank orcid line should be remove - if there is no orcid, this line isn't needed

* `    - name: Chuanxin M. Niu^[corresponding author&#58;&nbsp;minos.niu&#64;gmail.com]`

which you could try changing to just to
`    - name: Chuanxin M. Niu^[corresponding author]`

* or the blank line between the affiliations and the date, which you could remove.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right (or you've made changes in the .md file) to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
Also, looking at your paper, you have put the references in manually rather than tagging them so they are built - see the example paper: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by Rehablab** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.2340/16501977-0936 may be a valid DOI for title: Long-term benefits of progressive resistance training in chronic stroke: a 4-year follow-up
- 10.2340/16501977-0129 may be a valid DOI for title: Progressive resistance training after stroke: effects on muscle strength, muscle tone, gait performance and perceived participation
- 10.1310/tsr1906-471 may be a valid DOI for title: Resistance training for gait speed and total distance walked during the chronic stage of stroke: a meta-analysis

INVALID DOIs

- None
```

**Comment by Rehablab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04003/joss.04003/10.21105.joss.04003.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04003/joss.04003/10.21105.joss.04003.pdf) :page_facing_up: :point_left:

**Comment by adi3** [comment]
@whedon assign @adi3 as editor

**Comment by whedon** [comment]
OK, the editor is @adi3

**Comment by adi3** [comment]
@Rehablab - I'll be the editor for this review. To get things going, could you please suggest 5-6 reviewers from this list that you consider appropriate to vet this paper? While selecting, you should confirm that the domain expertise of the reviewer matches the subject matter of your paper and software.

Thank you!

**Comment by Rehablab** [comment]
Thanks @adi3 .
For reviewers, could I please suggest the following from the list:
- federeghe
- sneakers-the-rat
- vmatos
- AustinTSchaffer
- destogl
- ekorudiawan

**Comment by adi3** [comment]
@federeghe @sneakers-the-rat @vmatos @AustinTSchaffer @destogl @ekorudiawan - Would any of you be interested in reviewing this paper on robotics? We would greatly appreciate your help!

**Comment by AustinTSchaffer** [comment]
@adi3 I'd love to!

**Comment by sneakers-the-rat** [comment]
@adi3 would be happy to :)

**Comment by adi3** [comment]
@whedon add @AustinTSchaffer as reviewer

**Comment by whedon** [comment]
OK, @AustinTSchaffer is now a reviewer

**Comment by adi3** [comment]
@whedon add @sneakers-the-rat as reviewer

**Comment by whedon** [comment]
OK, @sneakers-the-rat is now a reviewer

**Comment by adi3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4071.
