### ISSUE TITLE
[PRE REVIEW]: Data Integrity Fingerprint (DIF) - A reference implementation in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4004]
**Submitting author:** @lindemann09 (<a href="http://orcid.org/0000-0003-3789-5373">Oliver Lindemann</a>)
**Repository:** <a href="https://github.com/expyriment/dataintegrityfingerprint-python" target ="_blank">https://github.com/expyriment/dataintegrityfingerprint-python</a>
**Version:** v0.7.5
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fb4a5f73906854ef853d49dd0a0fe9be/status.svg)](https://joss.theoj.org/papers/fb4a5f73906854ef853d49dd0a0fe9be)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fb4a5f73906854ef853d49dd0a0fe9be"><img src="https://joss.theoj.org/papers/fb4a5f73906854ef853d49dd0a0fe9be/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fb4a5f73906854ef853d49dd0a0fe9be/status.svg)](https://joss.theoj.org/papers/fb4a5f73906854ef853d49dd0a0fe9be)
```

**Author instructions**

Thanks for submitting your paper to JOSS @lindemann09. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @ajstewartlang.

@lindemann09 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1037

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (469.8 files/s, 57935.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            204            173            857
Markdown                         2            120              0            329
TeX                              1             25              0            157
YAML                             3              5              4             79
make                             1              5              0             15
-------------------------------------------------------------------------------
SUM:                            16            359            177           1437
-------------------------------------------------------------------------------


Statistical information for the repository 'aa24dd7620cd6b92a0c16cfb' was
gathered on 2021/12/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Florian Krause                  17           340            121           14.96
Oliver Lindemann                22          1439            615           66.67
fladd                            6           376            190           18.37

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Florian Krause              262           77.1         21.5                5.34
Oliver Lindemann            665           46.2         10.9                4.51
fladd                       307           81.6          4.4                5.21
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.18 is OK
- 10.22541/au.159422974.49069472 is OK
- 10.1515/libri-2020-0018 is OK
- 10.1038/s41597-020-0486-7 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04004/joss.04004/10.21105.joss.04004.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04004/joss.04004/10.21105.joss.04004.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hello @lindemann09, thanks for your interest in JOSS. The editorial board is going to review your submission to see if it meets our requirements for [scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) (related to software package size) and [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software). We will get back to you within a week or two at most.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
