### ISSUE TITLE
[PRE REVIEW]: PsiRESP: calculating RESP charges with Psi4

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4005]
**Submitting author:** @lilyminium (<a href="http://orcid.org/0000-0002-6095-6704">Lily Wang</a>)
**Repository:** <a href="https://github.com/lilyminium/psiresp" target ="_blank">https://github.com/lilyminium/psiresp</a>
**Version:** v0.3.1
**Editor:** @pdebuyl
**Reviewers:** @ptmerz
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0/status.svg)](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0"><img src="https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0/status.svg)](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @lilyminium. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pdebuyl.

@lilyminium if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1317

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (771.7 files/s, 161516.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          46           1301           1582           4610
TeX                              3             49              0            813
XML                              1              0              0            586
YAML                             9             58             51            510
reStructuredText                38            277            275            450
Markdown                        12            137              0            394
Jupyter Notebook                 3              0          13492            146
TOML                             1              3              0             44
Bourne Shell                     3              5              8             41
DOS Batch                        1              8              1             27
make                             1              7              8             20
CSS                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                           119           1845          15417           7644
-------------------------------------------------------------------------------


Statistical information for the repository 'a89f4b6c81344534ad5e2508' was
gathered on 2021/12/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lily Wang                       31         24698          17245          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lily Wang                  7453           30.2          1.8                9.78
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/jcc.21787 is OK
- 10.25080/Majora-629e541a-00e is OK
- 10.1021/ct200196m is OK
- 10.1002/jcc.540161106 is OK
- 10.1021/ja00074a030 is OK
- 10.1021/j100142a004 is OK
- 10.1039/c0cp00111b is OK
- 10.1093/nar/gkm887 is OK
- 10.1038/s42004-020-0291-4 is OK
- 10.1002/qua.26035 is OK
- 10.1002/jcc.540050204 is OK
- 10.1063/1.1740588 is OK
- 10.1021/jp0667442 is OK
- 10.1021/ja00049a045 is OK
- 10.1063/5.0059356 is OK
- 10.5281/zenodo.5601736 is OK
- 10.1063/5.0005188 is OK
- 10.5281/zenodo.4107869 is OK
- 10.1063/1.1747632 is OK
- 10.1007/BF00549096 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1002/(SICI)1096-987X(20000130)21:2<132::AID-JCC5>3.0.CO;2-P is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/jcc.540141013 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/wcms.1491 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/jcc.540110311 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1107/S0021889883010985 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/wcms.93 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04005/joss.04005/10.21105.joss.04005.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04005/joss.04005/10.21105.joss.04005.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @pdebuyl as editor

Hi @pdebuyl, could you edit this submission?

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @lilyminium, while we are getting started assigning an editor and finding reviewers, could you please take a look at those DOI issues raised above and resolve them in your paper?

**Comment by lilyminium** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04005/joss.04005/10.21105.joss.04005.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04005/joss.04005/10.21105.joss.04005.pdf) :page_facing_up: :point_left:

**Comment by lilyminium** [comment]
Thanks @kyleniemeyer -- I've fixed those now.

For reviewers, could I please suggest the following from the list:

* hannahbrucemacdonald
* mkhorton
* ptmerz
* blakeaw
* chryswoods

**Comment by kthyng** [comment]
@pdebuyl Adding a ping here now that it is the new year — would you like to edit this submission? Thanks!

**Comment by kthyng** [comment]
@pdebuyl Awesome! I'll assign you to it now with the understanding you'll start next week. Thanks!

**Comment by kthyng** [comment]
@whedon assign @pdebuyl as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by lilyminium** [comment]
@pdebuyl I just made a new release of psiresp 0.3 -- would it be possible to change the version to that instead? It contains minor improvements:  making some dependencies optional and renaming some ambiguously-named variables.

**Comment by lilyminium** [comment]
Hi there, just checking in on the progress of this submission.

**Comment by pdebuyl** [comment]
Hi @lilyminium sorry about this. I was getting another submission started and will look for reviewers quickly.

**Comment by pdebuyl** [comment]
@hannahbrucemacdonald @ptmerz would you review the article "PsiRESP: calculating RESP charges with Psi4" for the Journal of Open Source Software?

**Comment by ptmerz** [comment]
@pdebuyl Yes, I'd be happy to review!

**Comment by pdebuyl** [comment]
Thank you very much @ptmerz The review will only start once a second reviewer is onboard.

**Comment by pdebuyl** [comment]
@whedon assign @ptmerz as reviewer

**Comment by whedon** [comment]
OK, @ptmerz is now a reviewer

**Comment by pdebuyl** [comment]
@whedon set v0.3 as version

**Comment by whedon** [comment]
OK. v0.3 is the version.

**Comment by pdebuyl** [comment]
@whedon set v0.3.1 as version

**Comment by whedon** [comment]
OK. v0.3.1 is the version.

**Comment by hannahbrucemacdonald** [comment]
Hey - the paper looks interesting, happy to review!

**Comment by pdebuyl** [comment]
Thank you very much @hannahbrucemacdonald !

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4100.
