### ISSUE TITLE
[PRE REVIEW]: anndata: Annotated data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4006]
**Submitting author:** @falexwolf (<a href="http://orcid.org/0000-0002-8760-7838">F. Alexander Wolf</a>)
**Repository:** https://github.com/theislab/anndata
**Branch with paper.md** (empty if default branch): 
**Version:** v0.8.0
**Editor:** @luizirber
**Reviewers:** @nlhepler, @rcannood
**Managing EiC:** Kyle Niemeyer

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8b1f66b60f7af653cc09ff32fee77d83/status.svg)](https://joss.theoj.org/papers/8b1f66b60f7af653cc09ff32fee77d83)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8b1f66b60f7af653cc09ff32fee77d83"><img src="https://joss.theoj.org/papers/8b1f66b60f7af653cc09ff32fee77d83/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8b1f66b60f7af653cc09ff32fee77d83/status.svg)](https://joss.theoj.org/papers/8b1f66b60f7af653cc09ff32fee77d83)
```

**Author instructions**

Thanks for submitting your paper to JOSS @falexwolf. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @luizirber.

@falexwolf if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4006 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (338.4 files/s, 66561.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          56           2517           2160           9421
reStructuredText                14            252            203            511
YAML                             5             19              2            128
TOML                             1              8              3            105
make                             1              5              6             14
Jupyter Notebook                 1              0            171             12
SVG                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                            79           2801           2545          10192
-------------------------------------------------------------------------------


Statistical information for the repository 'c726abe4832b1d137cffbca9' was
gathered on 2021/12/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Wolf                        5            96             52            0.28
Chris Rands                      2           120              2            0.23
Daniel Burkhardt                 1             4              0            0.01
Fabian Rost                      1            27              0            0.05
Francesco G. Brundu              1             8              0            0.01
Gokcen Eraslan                   7            21             13            0.06
Gregor Sturm                     1             4              0            0.01
Gökcen Eraslan                   1             9              0            0.02
Gökçen Eraslan                   4            42              9            0.10
Isaac Virshup                  251         12084           5583           32.97
Jeffrey Regier                   1             1              1            0.00
Joshua Gould                     2             7              1            0.01
Justin Kiggins                   1            48             10            0.11
Koncopd                         42          1207            756            3.66
Matt Weiden                      4            92             57            0.28
Michal Klein                     5            25              9            0.06
Miles Smith                      1            11              7            0.03
Olga Botvinnik                   1            59             32            0.17
Philipp A                      169          7065           8837           29.68
Robrecht Cannoodt               12            85             46            0.24
Roman Hillje                     1            64              9            0.14
Ryan Williams                    3             5             22            0.05
Sergei R                         2            24              2            0.05
Sergei Rybakov                  10          1337             15            2.52
Stefan Peidli                    1             1              1            0.00
Tom White                        6           227              6            0.43
Volker Bergen                    7           167             68            0.44
bkmartinjr                       1            39              0            0.07
dawe                             3            38              2            0.07
falexwolf                      206         10798           4171           27.94
huidongchen                      2            15             12            0.05
ilia-kats                        2            78             17            0.18
michalk8                         1            35              2            0.07

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chris Rands                  23           19.2         24.0                4.35
Daniel Burkhardt              4          100.0          2.4                0.00
Fabian Rost                  12           44.4         32.1                0.00
Francesco G. Brundu           3           37.5         38.3               33.33
Gokcen Eraslan               11           52.4         12.8                9.09
Gökçen Eraslan               22           52.4         33.1                0.00
Isaac Virshup              7660           63.4         21.9                5.68
Joshua Gould                  1           14.3         25.4                0.00
Justin Kiggins               18           37.5         28.0                0.00
Koncopd                    1368          113.3          6.8                5.48
Matt Weiden                  85           92.4         20.9                3.53
Michal Klein                 17           68.0         21.2                0.00
Miles Smith                   3           27.3         27.3                0.00
Olga Botvinnik               27           45.8         22.8               14.81
Philipp A                  3267           46.2         26.7                7.53
Robrecht Cannoodt            21           24.7         12.7                0.00
Roman Hillje                 64          100.0          5.9               12.50
Tom White                    30           13.2         40.9               10.00
Volker Bergen                49           29.3         19.2                2.04
bkmartinjr                   19           48.7         37.6                0.00
dawe                         11           28.9         47.7               27.27
falexwolf                  1266           11.7         42.8               12.24
huidongchen                   4           26.7         37.4                0.00
ilia-kats                    78          100.0          2.7                2.56
michalk8                     35          100.0          1.7                2.86
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4006 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: tags (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kyleniemeyer** [comment]
Hi @falexwolf, could you add the `tags` field in the paper YAML header? I wasn't aware that was strictly required, but the error message seems to be pointing to that. Also, I'm not sure if the special characters you have used in the affiliations wil work, but we can find out!

**Comment by falexwolf** [comment]
Hi @kyleniemeyer, added the `tags` field! Apologies we missed that. It rendered in the preview.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04006/joss.04006/10.21105.joss.04006.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04006/joss.04006/10.21105.joss.04006.pdf) :page_facing_up: :point_left:

**Comment by luizirber** [comment]
Confirming I can edit this one

**Comment by kyleniemeyer** [comment]
@whedon assign @luizirber as editor

Thanks @luizirber!

**Comment by whedon** [comment]
OK, the editor is @luizirber

**Comment by falexwolf** [comment]
Thank you so much, @luizirber and @kyleniemeyer!

For reviewers, these are some people who have familiarity with the project: 
* https://github.com/ambrosejcarr
* https://github.com/rcannood
* https://github.com/stavrospapadopoulos
* https://github.com/tomwhite
* https://github.com/joshua-gould
* https://github.com/adamgayoso

People who would be incredible to have their input from!
* https://github.com/hadley
* https://github.com/jakevdp

Happy to think more!

**Comment by arfon** [comment]
@falexwolf – please don't use the affiliation block like this. You can see how to include footnotes associated with authors in the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).

```
 - name: "Co-creator."
   index: †
 - name: "Present address: Cellarity, Cambridge, MA."
   index: ‡
```

**Comment by falexwolf** [comment]
A very Happy New Year! Apologies for the late response, I was on extended holidays.

Understood, @arfon! I'll update accordingly!

**Comment by falexwolf** [comment]
FYI: The footnote issue is fixed.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #4006 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
It looks like this paper includes an ORCID (0000-0003-0872-7098) that is probably not correct.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04006/joss.04006/10.21105.joss.04006.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04006/joss.04006/10.21105.joss.04006.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @luizirber, just a gentle ping to assign reviewers on this submission. Thanks!

**Comment by luizirber** [comment]
@whedon assign @nlhepler as reviewer

**Comment by whedon** [comment]
OK, @nlhepler is now a reviewer

**Comment by arfon** [comment]
@luizirber – looks like we're still looking for a second reviewer here?

**Comment by falexwolf** [comment]
Hi @luizirber! Has there been any progress with the review process? Can we do anything to help?

**Comment by luizirber** [comment]
@falexwolf Sorry for the delay, I sent a couple more emails to potential reviewers, more updates soon

**Comment by falexwolf** [comment]
Thank you, Luiz!

**Comment by Athene-ai** [comment]
@falexwolf  I would like to review this paper

**Comment by falexwolf** [comment]
Thank you, @Athene-ai!

**Comment by Athene-ai** [comment]
@luizirber I can not wait to be added as a second review for this paper

**Comment by luizirber** [comment]
@editorialbot add @Athene-ai as reviewer

**Comment by Athene-ai** [comment]
@editorialbot  add @Athene-ai  as reviewer

**Comment by Athene-ai** [comment]
> 👋 @Athene-ai - reviewers can only be added by editors, not by themselves

Oh so sorry 😅😅😅

**Comment by luizirber** [comment]
@editorialbot add @rcannood as reviewer

**Comment by luizirber** [comment]
Thanks @rcannood for accepting the invite to review!

**Comment by luizirber** [comment]
@editorialbot start review

**Comment by falexwolf** [comment]
Thank you for reviewing the paper, @rcannood and @nlhepler!
