### ISSUE TITLE
[PRE REVIEW]: DASF: A data analytics software framework for distributed environments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4009]
**Submitting author:** @d-eggert (<a href="http://orcid.org/0000-0003-0251-4390">Daniel Eggert</a>)
**Repository:** <a href="https://git.geomar.de/digital-earth/dasf/dasf-messaging-python" target ="_blank">https://git.geomar.de/digital-earth/dasf/dasf-messaging-python</a>
**Version:** v0.2.0
**Editor:** @martinfleis
**Reviewers:** @uellue, @sk1p, @cjwu
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e8022c832c1bb6e879b89508a83fa75e/status.svg)](https://joss.theoj.org/papers/e8022c832c1bb6e879b89508a83fa75e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e8022c832c1bb6e879b89508a83fa75e"><img src="https://joss.theoj.org/papers/e8022c832c1bb6e879b89508a83fa75e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e8022c832c1bb6e879b89508a83fa75e/status.svg)](https://joss.theoj.org/papers/e8022c832c1bb6e879b89508a83fa75e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @d-eggert. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @martinfleis.

@d-eggert if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (668.6 files/s, 107777.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          33           1350           1801           4000
Jinja Template                   3             19              0            118
JSON                             6              0              0             89
Markdown                         1             28              0             75
YAML                             2              5              4             57
INI                              1              3              0             17
TOML                             1              1              0              9
-------------------------------------------------------------------------------
SUM:                            47           1406           1805           4365
-------------------------------------------------------------------------------


Statistical information for the repository '16a00984eabd907c1f54b96c' was
gathered on 2021/12/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Eggert                   34          1369            299           11.07
Daniela Rabe                     2            27              9            0.24
Peter Morstein                   5            53             20            0.48
Philipp S. Sommer               44          6048           2999           60.04
Philipp Sommer                  12          3611            631           28.15
Stefan Lüdtke                    1             3              0            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel Eggert               672           49.1          8.8               16.22
Daniela Rabe                 19           70.4         22.8               31.58
Peter Morstein               17           32.1         14.1                0.00
Philipp S. Sommer          5232           86.5         12.8               12.02
Philipp Sommer             1211           33.5          0.8                3.72
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4009 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04009/joss.04009/10.21105.joss.04009.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04009/joss.04009/10.21105.joss.04009.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check references from branch joss-submission

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-submission
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @martinfleis as editor

Hi @martinfleis, could you edit this? Please note that this submission actually comprises four software packages, found at https://git.geomar.de/digital-earth/dasf/

**Comment by whedon** [comment]
@martinfleis has been invited to edit this submission.

**Comment by martinfleis** [comment]
@kyleniemeyer Yes, but considering the time of the year, I won't be able to start until January.

**Comment by kyleniemeyer** [comment]
@martinfleis of course, not a problem

**Comment by martinfleis** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @martinfleis

**Comment by d-eggert** [comment]
Hi, I got the software DOIs from my institute:

One, as an umbrella for the entire framework: https://doi.org/10.5880/GFZ.1.4.2021.004
and three for the individual parts/repositories:
https://doi.org/10.5880/GFZ.1.4.2021.005, https://doi.org/10.5880/GFZ.1.4.2021.006, https://doi.org/10.5880/GFZ.1.4.2021.007

What is your preferred way of referencing them in the paper?

**Comment by martinfleis** [comment]
@d-eggert We will use the umbrella DOI as an archived version attached to the paper once the review is over. I would suggest using those for individual parts as a reference instead of the links to Gitlab.

**Comment by d-eggert** [comment]
Thanks for your feedback, @martinfleis. I expected it to be possible as soon as I set the visibility to 'public', which is obviously not the case. :man_shrugging:

@cfgmr is it possible to enable issue creation for anonymous users at the geomar gitlab instance or shall/can we create accounts for the reviewers?

**Comment by d-eggert** [comment]
@martinfleis, I fixed the typo, thanks.

@whedon generate pdf from branch joss-submission

**Comment by martinfleis** [comment]
Thanks!

> shall/can we create accounts for the reviewers?

It is not a question of reviewers as much as normal users of your software. Manual creation of accounts for selected people doesn't qualify, I am afraid.

**Comment by martinfleis** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04009/joss.04009/10.21105.joss.04009.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04009/joss.04009/10.21105.joss.04009.pdf) :page_facing_up: :point_left:

**Comment by d-eggert** [comment]
> It is not a question of reviewers as much as normal users of your software. Manual creation of accounts for selected people doesn't qualify, I am afraid.

Ok, so it's somewhat trickier than anticipated. Let's see what the Geomar Git administrator can offer.

**Comment by d-eggert** [comment]
Hi @martinfleis , 

I wrote @cfgmr an additional eMail to see when he returns to office. I got an out-of-office reply, but with an old date :man_shrugging:  
So, I don't expect to hear from him before next week.

> It is not a question of reviewers as much as normal users of your software. Manual creation of accounts for selected people doesn't qualify, I am afraid.

I know there is the possibility in Gitlab to create issues via a repository-specific email address. It's not as convenient as a registered user, but would `Permit individuals to create issues/file tickets against your repository.` Would that qualify? At least in case the Geomar Git administrators can't offer a better solution.

**Comment by martinfleis** [comment]
I am not sure about that as it doesn't allow discussion in the issue, right? I can use the email to file a ticket but not to respond to your reply. When this happened before (see #2831 for example), people usually created a mirror of the repository on some open platform.

**Comment by cfgmr** [comment]
Hi @d-eggert  and @martinfleis,

sorry for the late reply, I was indeed on holiday till today. Including my colleague @dirks in here for faster responses in the future 😉 

Surprisingy, Gitlab actually does not allow anonymous creation of issues (see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/60132). Reading Issues however works without login. This is general behavior and not limited to our instance. This means that any user wanting to create an issue would need to be authenticated, i.e. needs a login.

While Gitlab does support account creation via OmniAuth, we currently do not plan on opening our GitLab instance to OAuth providers beyond the HelmholzAAI.

Gitlab  recommends [Service Desk](https://docs.gitlab.com/ee/user/project/service_desk.html) as solution for this use case. This allows creation of issues anonymously via a project-specific email. @martinfleis for the anonymous user, discussion is possible and works exclusively over email. Project members however can reply to the issus as usual; Comments and replies to the issue are relayed via email to the OP, and OP can reply by mail to the issue.

@martinfleis does this meet your requirements? 

@d-eggert service desk is enabled in our instance and ready to use (adaptation of email templates might be required). It can be enabled on  a repository basis, not on groups but if you would like to have one address for the whole group we could create a specific repo for that. Let me know if you would like to go forward with this and we can talk about the details.

As @martinfleis proposed, the alternative to service desk would be to mirror the repos somewhere with OmniAuth support.

**Comment by martinfleis** [comment]
Thanks for the explanation @cfgmr!

The Service Desk solution should be enough, assuming it will be properly documented. Keep in mind, that you need to enable it for all 4 repositories (or create one to collect reports as you suggest, but I'd say it is better to keep Service Desk-based reports in the same place as standard issues).

**Comment by d-eggert** [comment]
Thanks for the insight @cfgmr !

I will then enable (and document) the Service Desk solution for the repos. I also find it more sustainable than the mirror alternative.

**Comment by dirks** [comment]
@d-eggert maybe have a look at the [the upstream documentation](https://docs.gitlab.com/ee/user/project/service_desk.html#configuring-service-desk) for some best practices. Let us know if you need any help with the implementation.

**Comment by d-eggert** [comment]
Thanks @dirks for the doc link. 

@martinfleis, I enabled the service desk feature for all four repos and added a 'service desk' section to the readme of each repository. I did not setup custom email templates, as I don't expect too much traffic via this channel yet.

I tested the feature here:
https://git.geomar.de/digital-earth/dasf/dasf-messaging-python/-/issues/40

appears to work as intended.

**Comment by martinfleis** [comment]
@d-eggert Thanks for setting it up! If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by d-eggert** [comment]
Wow, pretty comprehensive list :sweat_smile: 

people with a potentially fitting skill set and domain knowledge: **kislerdm**, **cjwu**, **xirdneh**, **uellue** and **diegomoreiracarvalho**

**Comment by martinfleis** [comment]
👋👋👋 Dear @cjwu, and @uellue,

Would you be willing to assist in reviewing this submission for JOSS (Journal of Open Source Software)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "TDASF: A data analytics software framework for distributed environments". You can find more information at the top of this Github issue (#4009).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

Thank you!

**Comment by uellue** [comment]
@martinfleis @d-eggert sure! I had a quick look already. Looks very interesting, I just had a hard time to understand what exactly that is, how one uses it and with which other software it could be comparable. I'd be happy to help improve that, in particular with targeted questions. :-)

Since it seems to be related to web applications, my colleague @sk1p could also help with the review if that is welcome.

**Comment by martinfleis** [comment]
@whedon assign @uellue as reviewer

Thanks @uellue!

@sk1p would you be willing to take the reviewer's role as well?

**Comment by whedon** [comment]
OK, @uellue is now a reviewer

**Comment by sk1p** [comment]
> would you be willing to take the reviewer's role as well?

Sure!

**Comment by martinfleis** [comment]
@whedon add @sk1p as reviewer

@sk1p Thank you!

I'll wait until Monday to give another reviewer a time to respond and formally start the review next week.

**Comment by whedon** [comment]
OK, @sk1p is now a reviewer

**Comment by cjwu** [comment]
Hi @Martin,
I am happy to review this article.
Thanks.
CJ

**Comment by cjwu** [comment]
Hi @martinfleis 
I am happy to review this article.
Thanks.
CJ

**Comment by martinfleis** [comment]
@whedon add @cjwu as reviewer

**Comment by whedon** [comment]
OK, @cjwu is now a reviewer

**Comment by martinfleis** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4052.
