### ISSUE TITLE
[REVIEW]: ECNet: Large scale machine learning projects for fuel property prediction

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#401]
**Submitting author:** @TJKessler (<a href="http://orcid.org/0000-0002-7363-4050">Travis Kessler</a>)
**Repository:** <a href="https://github.com/TJKessler/ECNet" target ="_blank">https://github.com/TJKessler/ECNet</a>
**Version:** v1.2.4.dev1
**Editor:** @arokem
**Reviewer:** @krother
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.910866" target="_blank">10.5281/zenodo.910866</a>

## Status

[![status](http://joss.theoj.org/papers/f556afbc97e18e1c1294d98e0f7ff99f/status.svg)](http://joss.theoj.org/papers/f556afbc97e18e1c1294d98e0f7ff99f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f556afbc97e18e1c1294d98e0f7ff99f"><img src="http://joss.theoj.org/papers/f556afbc97e18e1c1294d98e0f7ff99f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f556afbc97e18e1c1294d98e0f7ff99f/status.svg)](http://joss.theoj.org/papers/f556afbc97e18e1c1294d98e0f7ff99f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/TJKessler/ECNet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@krother, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/TJKessler/ECNet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2.4.dev1)?
- [x] **Authorship:** Has the submitting author (@TJKessler) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @krother it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by krother** [comment]
Thanks for the quick and precise repsonse. All issues resolved. Good job!

**Comment by krother** [comment]
@arokem I suggest to publish this article.

**Comment by TJKessler** [comment]
@krother - thank you for taking the time to review ECNet!

**Comment by arokem** [comment]
Thank you both for the quick turnaround here. @TJKessler : Your next step is to make an archive from the current version (e.g., using Zenodo) and to post the DOI of the archive here.

**Comment by TJKessler** [comment]
@arokem - here is the archive DOI: 10.5281/zenodo.893638

**Comment by arfon** [comment]
@TJKessler - Could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by TJKessler** [comment]
@arfon - all references in paper.md are now included in paper.bib.

**Comment by arfon** [comment]
Thanks @TJKessler - this is nearly right but not quite there. Please _remove_ the content below the `#References` section in your `paper.md` (https://github.com/TJKessler/ECNet/blob/master/paper/paper.md#references) and _cite_ the entries in your `paper.bib` as described [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html). That way, the citations are compiled into the `References` section when the PDF is created by Pandoc.

**Comment by TJKessler** [comment]
@arfon - I think I got it this time, let me know if it is still off.

**Comment by arfon** [comment]
> @arfon - I think I got it this time, let me know if it is still off.

Nearly! Please merge https://github.com/TJKessler/ECNet/pull/7. Then, could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by TJKessler** [comment]
@arfon - ECNet#7 has been merged, here is the updated DOI: 10.5281/zenodo.910866

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.910866 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.910866" target="_blank">10.5281/zenodo.910866</a> is the archive.

**Comment by arfon** [comment]
@krother - many thanks for your review here and to @arokem for editing this submission ✨ 

@TJKessler - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00401 ⚡️ 🚀 :boom:
