### ISSUE TITLE
[PRE REVIEW]: CGC: a scalable Python package for co- and tri-clustering of geo-data cubes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4011]
**Submitting author:** @fnattino (<a href="http://orcid.org/0000-0003-3286-0139">Francesco Nattino</a>)
**Repository:** <a href="https://github.com/phenology/cgc" target ="_blank">https://github.com/phenology/cgc</a>
**Version:** v0.6.1
**Editor:** @hugoledoux
**Reviewers:** @Subho07, @Narayana-Rao
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2994234d6e691cbdb4e180bc38e17b2a/status.svg)](https://joss.theoj.org/papers/2994234d6e691cbdb4e180bc38e17b2a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2994234d6e691cbdb4e180bc38e17b2a"><img src="https://joss.theoj.org/papers/2994234d6e691cbdb4e180bc38e17b2a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2994234d6e691cbdb4e180bc38e17b2a/status.svg)](https://joss.theoj.org/papers/2994234d6e691cbdb4e180bc38e17b2a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @fnattino. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @martinfleis.

@fnattino if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (506.1 files/s, 56893.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          28            502            785           2574
reStructuredText                10            237            179            363
Jupyter Notebook                 2              0            386             76
YAML                             3              6              0             63
JSON                             1              0              0             44
DOS Batch                        1              8              1             27
make                             1              4              6             10
CSS                              1              2              3              8
-------------------------------------------------------------------------------
SUM:                            47            759           1360           3165
-------------------------------------------------------------------------------


Statistical information for the repository '6ea8f36e5c988e4cb2fe7816' was
gathered on 2021/12/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
EIzquierdo                       1           157              0            1.39
Francesco Nattino              137          5081           2173           64.35
Meiert Grootes                  28           224             72            2.63
Meiert Willem Groote             7             5             10            0.13
Ou Ku                            7            16             20            0.32
Serkan Girgin                   10            48             53            0.90
rogerkuou                       62          1852           1561           30.28

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Francesco Nattino          3065           60.3          7.4                9.59
Meiert Grootes               19            8.5         15.5               10.53
Meiert Willem Groote          1           20.0         15.2              100.00
Ou Ku                        16          100.0          7.7                0.00
Serkan Girgin                 2            4.2         15.6                0.00
rogerkuou                   758           40.9          4.9                8.44
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4011 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04011/joss.04011/10.21105.joss.04011.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04011/joss.04011/10.21105.joss.04011.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check references from branch joss_paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss_paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/VAST.2009.5332584 is OK
- 10.1145/502512.502550 is OK
- 10.1145/956750.956764 is OK
- 10.1080/00045608.2014.958389 is OK
- 10.1080/13658816.2013.788249 is OK
- 10.1080/01621459.1972.10481214 is OK
- 10.5334/jors.148 is OK
- 10.25080/Majora-4af1f417-011 is OK
- 10.18637/jss.v088.i07 is OK
- 10.1016/0377-0427(87)90125-7 is OK
- 10.1109/ACCESS.2018.2801263 is OK
- 10.1080/13658816.2014.994520 is OK
- 10.1002/2015JG003308 is OK
- 10.1080/24694452.2017.1325725 is OK
- 10.1016/j.cageo.2020.104420 is OK

MISSING DOIs

- 10.1145/1014052.1014111 may be a valid DOI for title: A Generalized Maximum Entropy Approach to Bregman Co-clustering and Matrix Approximation

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @hugoledoux as editor

Hi @hugoledoux, could you edit this submission?

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@pwernette @kmarkert @arthur-e @Subho07

You seem to fit well the profile for this review, if you're interested let me know!

**Comment by Subho07** [comment]
@hugoledoux Thanks. I can review this manuscript

**Comment by hugoledoux** [comment]
@whedon assign @Subho07 as reviewer

**Comment by whedon** [comment]
OK, @Subho07 is now a reviewer

**Comment by hugoledoux** [comment]
@visr or @Huite : would you be interested in doing this review?

**Comment by hugoledoux** [comment]
@whedon add @Narayana-Rao as reviewer

**Comment by whedon** [comment]
OK, @Narayana-Rao is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4032.
