### ISSUE TITLE
[PRE REVIEW]: OfflineMOT: A Python Package for multiple objects detection and tracking from bird view stationary drone videos

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4018]
**Submitting author:** @engyasin (<a href="http://orcid.org/0000-0002-5282-7259">Yasin Yousif</a>)
**Repository:** <a href="https://github.com/engyasin/Offline_MOT" target ="_blank">https://github.com/engyasin/Offline_MOT</a>
**Version:** v1.0.0
**Editor:** @hugoledoux
**Reviewers:** @Shiming94, @lucaferranti 
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/94ab6a9e87d3423efc025216e897fcc3/status.svg)](https://joss.theoj.org/papers/94ab6a9e87d3423efc025216e897fcc3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/94ab6a9e87d3423efc025216e897fcc3"><img src="https://joss.theoj.org/papers/94ab6a9e87d3423efc025216e897fcc3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/94ab6a9e87d3423efc025216e897fcc3/status.svg)](https://joss.theoj.org/papers/94ab6a9e87d3423efc025216e897fcc3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @engyasin. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @gkthiruvathukal.

@engyasin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1251

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (256.3 files/s, 47781.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          24            800           1172           2217
Jupyter Notebook                 8              0           1994            286
Markdown                         3            108              0            177
TeX                              1             11              0            109
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            37            920           3170           2807
-------------------------------------------------------------------------------


Statistical information for the repository '830558d311cd6bcd364e07a8' was
gathered on 2021/12/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Yasin Yousif                    20         10098           5909          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Yasin Yousif               4189           41.5          0.7               11.36
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04018/joss.04018/10.21105.joss.04018.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04018/joss.04018/10.21105.joss.04018.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- 10.1109/iccv.2019.00103 may be a valid DOI for title: Tracking without bells and whistles
- 10.1109/icip.2017.8296962 may be a valid DOI for title: Simple online and realtime tracking with a deep association metric
- 10.1109/ivs.2019.8814092 may be a valid DOI for title: Top-view trajectories: A pedestrian dataset of vehicle-crowd interaction from controlled experiments and crowded campus

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@engyasin – many thanks for your submission to JOSS. While I look for a possible editor, if you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon invite @jni as editor

:wave: @jni – would you be able to handle this submission for us?

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by engyasin** [comment]
@arfon  Thanks for the instructions

**Comment by engyasin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04018/joss.04018/10.21105.joss.04018.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04018/joss.04018/10.21105.joss.04018.pdf) :page_facing_up: :point_left:

**Comment by engyasin** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/iccv.2019.00103 is OK
- 10.1109/icip.2017.8296962 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/ivs.2019.8814092 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@hugoledoux are you interested in editing this submssion?

**Comment by kthyng** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@abhishekbajpayee @abuccts @jizecn @nsaunier 

I think you are suitable for this reviewer, if you are interested let me know here please!

**Comment by hugoledoux** [comment]
@Scivision @thomakra @xzyaoi

I think you are suitable for this reviewer, if you are interested let me know here please!

**Comment by thomakra** [comment]
I'm sorry, but I do not have the capacity at this time.

-Thomas-

**Comment by xzyaoi** [comment]
@hugoledoux  I am sorry, I don't think I am qualified and suitable for reviewing this paper.
Hope you will get a better reviewer.

Best regards

**Comment by hugoledoux** [comment]
@whedon assign @Shiming94 as reviewer

**Comment by whedon** [comment]
OK, @Shiming94 is now a reviewer

**Comment by hugoledoux** [comment]
@tpurcell90 @lucaferranti @ekorudiawan

I think you are suitable for this reviewer, if you are interested let me know here please!

**Comment by lucaferranti** [comment]
@hugoledoux yes I can review this

**Comment by hugoledoux** [comment]
@whedon add @lucaferranti  as reviewer

**Comment by whedon** [comment]
OK, @lucaferranti  is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4099.
