### ISSUE TITLE
[PRE REVIEW]: nsink: An R package for flow path nitrogen removal estimation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4019]
**Submitting author:** @jhollist (<a href="http://orcid.org/0000-0002-9254-9740">Jeffrey W Hollister</a>)
**Repository:** <a href="https://github.com/USEPA/nsink" target ="_blank">https://github.com/USEPA/nsink</a>
**Version:** v1.1.0
**Editor:** @crvernon
**Reviewers:** @jmp75, @ldecicco-USGS
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3af12dd8d27ca1605958d4fd021deaa8/status.svg)](https://joss.theoj.org/papers/3af12dd8d27ca1605958d4fd021deaa8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3af12dd8d27ca1605958d4fd021deaa8"><img src="https://joss.theoj.org/papers/3af12dd8d27ca1605958d4fd021deaa8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3af12dd8d27ca1605958d4fd021deaa8/status.svg)](https://joss.theoj.org/papers/3af12dd8d27ca1605958d4fd021deaa8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jhollist. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@jhollist if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 979

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (894.9 files/s, 117033.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               24            257            914           2179
Markdown                         5            100              0            335
TeX                              2             37              0            314
XML                              1              0              0            192
YAML                             3             25              2            121
Rmd                              2             70            239             54
-------------------------------------------------------------------------------
SUM:                            37            489           1155           3195
-------------------------------------------------------------------------------


Statistical information for the repository 'f84a60edc45b4ec5a97848ae' was
gathered on 2021/12/21.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04019/joss.04019/10.21105.joss.04019.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04019/joss.04019/10.21105.joss.04019.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ecoleng.2010.02.006 is OK
- 10.32614/RJ-2018-009 is OK
- 10.18637/jss.v014.i06 is OK
- 10.1016/j.cageo.2004.03.012 is OK
- 10.32614/RJ-2016-014 is OK
- 10.1007/978-1-4614-7618-4 is OK
- 10.32614/RJ-2016-061 is OK

MISSING DOIs

- 10.3133/ofr20191096 may be a valid DOI for title: User’s guide for the National Hydrography Dataset plus (NHDPlus) High Resolution.
- 10.3390/rs11242971 may be a valid DOI for title: Overall methodology design for the United States national land cover database 2016 products

INVALID DOIs

- 10.1641/0006-3568(2002)052[0129:BSIPGO]2.0.CO;2 is INVALID
- 10.32614/RJ-2021-048 is INVALID
```

**Comment by arfon** [comment]
:wave: @jhollist – many thanks for your submission to JOSS! While I look for an editor to handle your submission if you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon invite @Bisaloo as editor

:wave: @Bisaloo – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by jhollist** [comment]
@arfon Thanks for the Whedon tips.  I have looked at those suggested DOIs and will run the checks shortly.

**Comment by jhollist** [comment]
@whedon generate pdf

**Comment by jhollist** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04019/joss.04019/10.21105.joss.04019.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04019/joss.04019/10.21105.joss.04019.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ecoleng.2010.02.006 is OK
- 10.32614/RJ-2018-009 is OK
- 10.18637/jss.v014.i06 is OK
- 10.1016/j.cageo.2004.03.012 is OK
- 10.32614/RJ-2016-014 is OK
- 10.1007/978-1-4614-7618-4 is OK
- 10.32614/RJ-2016-061 is OK
- 10.3133/ofr20191096 is OK
- 10.3390/rs11242971 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1641/0006-3568(2002)052[0129:BSIPGO]2.0.CO;2 is INVALID
- 10.32614/RJ-2021-048 is INVALID
```

**Comment by jhollist** [comment]
@arfon those two invalid DOIs are correct as far as I can tell.  The resolve with https://doi.org/ so I will leave them as is.

**Comment by Bisaloo** [comment]
> @whedon invite @Bisaloo as editor
> 
> wave @Bisaloo – would you be willing to edit this submission for JOSS?

Hi, I'm currently on leave with a limited internet access until January 20. I think it's better if you are able to find another editor for this submission.

**Comment by kthyng** [comment]
Hi @crvernon are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @crvernon as editor

**Comment by whedon** [comment]
@crvernon has been invited to edit this submission.

**Comment by crvernon** [comment]
@kthyng happy to help! 

@whedon assign @crvernon as editor

**Comment by danielskatz** [comment]
@whedon assign @crvernon as editor

whedon commands have to be at the start of a comment :)

**Comment by crvernon** [comment]
@kthyng it looks like my self assignment via whedon did not take.  Can you try on your end?  Thanks!

**Comment by whedon** [comment]
OK, the editor is @crvernon

**Comment by crvernon** [comment]
> @whedon assign @crvernon as editor
> 
> whedon commands have to be at the start of a comment :)

Thanks @danielskatz !

**Comment by crvernon** [comment]
:wave: @jhollist - I'll be your topic editor for this submission.

The first step in this pre-review is to find at least 2 reviewers. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this [list of people](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by jhollist** [comment]
Hi @crvernon.  Appreciate you taking this on.  

A few possibilities I can think of: dblodget-usgs, ldecicco-usgs, dylanbeaudette

From the list: alessandroamaranto, jmp75, arbennett, mikejohnson51, wincowgerDEV all look like possibilities.

And one other, but might have COI as I have worked with them, but not on this project:  fawda123

Hope this helps!

**Comment by crvernon** [comment]
:wave:   @jmp75 - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by crvernon** [comment]
:wave:   @ldecicco-USGS - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by jmp75** [comment]
@crvernon I can review this submission.

**Comment by crvernon** [comment]
@whedon assign @jmp75 as reviewer

**Comment by whedon** [comment]
OK, @jmp75 is now a reviewer

**Comment by ldecicco-USGS** [comment]
Sure, I'll review as well.

**Comment by crvernon** [comment]
@whedon add @ldecicco-USGS as reviewer

**Comment by whedon** [comment]
OK, @ldecicco-USGS is now a reviewer

**Comment by crvernon** [comment]
:wave: Alright @jhollist @jmp75 @ldecicco-USGS  - I am going to close this Pre-Review and kick off the full review which you should receive a notification for.  Thanks!

**Comment by crvernon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4039.
