### ISSUE TITLE
[PRE REVIEW]: SenAOReFoc: A Closed-Loop Sensorbased Adaptive Optics and Remote Focusing Control Software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4023]
**Submitting author:** @jiahecui (<a href="http://orcid.org/0000-0003-2122-5754">Jiahe Cui</a>)
**Repository:** <a href="https://github.com/jiahecui/SenAOReFoc" target ="_blank">https://github.com/jiahecui/SenAOReFoc</a>
**Version:** v1.0.0
**Editor:** @diehlpk
**Reviewers:** @abhilash12iec002 
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c0c5c8e06b379c4ac5374b261241068d/status.svg)](https://joss.theoj.org/papers/c0c5c8e06b379c4ac5374b261241068d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c0c5c8e06b379c4ac5374b261241068d"><img src="https://joss.theoj.org/papers/c0c5c8e06b379c4ac5374b261241068d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c0c5c8e06b379c4ac5374b261241068d/status.svg)](https://joss.theoj.org/papers/c0c5c8e06b379c4ac5374b261241068d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jiahecui. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@jiahecui if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1615

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/lsa.2014.46 is OK
- 10.1038/nn.4358 is OK
- 10.1364/OE.401117 is OK
- 10.1364/OE.27.031316 is OK
- 10.1364/OE.25.004368 is OK
- 10.1364/OE.26.001655 is OK
- 10.1364/OE.23.026208 is OK
- 10.5281/zenodo.3885508 is OK
- 10.1364/OE.442025 is OK
- 10.1364/BOE.8.004369 is OK
- 10.1364/AOPT.2005.AThB4 is OK
- 10.1111/j.1365-2966.2004.08524.x is OK
- 10.1364/OL.26.000746 is OK
- 10.1097/OPX.0b013e3181ff9a8b is OK
- 10.1098/rsta.2007.0013 is OK
- 10.1038/nmeth.4218 is OK
- 10.3928/1081-597X-20010901-13 is OK

MISSING DOIs

- 10.1364/boda.2021.dth2a.2 may be a valid DOI for title: Remote-Focussing for Volumetric Imaging in a Contactless and Label-Free Neurosurgical Microscope
- 10.1117/12.2054470 may be a valid DOI for title: Object-oriented Matlab adaptive optics toolbox
- 10.1146/annurev.aa.31.090193.000305 may be a valid DOI for title: Adaptive optics for astronomy: principles, performance, and applications

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.24 s (210.3 files/s, 81868.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          43           3134           4702           8803
Qt                               2              0              0           1474
Markdown                         2            165              0            763
TeX                              1             21              0            241
YAML                             1             12              0             82
JSON                             1              0              0             70
-------------------------------------------------------------------------------
SUM:                            50           3332           4702          11433
-------------------------------------------------------------------------------


Statistical information for the repository 'cf2651fd48f43136d981d7e9' was
gathered on 2021/12/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jiahe Cui                      203       1380249        1369584           99.68
jiahecui                        55          7430           1470            0.32

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jiahe Cui                 16639            1.2          9.7               10.30
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04023/joss.04023/10.21105.joss.04023.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04023/joss.04023/10.21105.joss.04023.pdf) :page_facing_up: :point_left:

**Comment by jiahecui** [comment]
> Suggestion for potential reviewers: caldarolamartin, jonatanalvelid

**Comment by arfon** [comment]
:wave: @jiahecui – many thanks for your submission to JOSS. While I look for an editor to handle your submission if you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon invite @jni as editor

:wave: @jni – would you be able to edit this submission for JOSS? Many thanks!

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by jiahecui** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04023/joss.04023/10.21105.joss.04023.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04023/joss.04023/10.21105.joss.04023.pdf) :page_facing_up: :point_left:

**Comment by jiahecui** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/lsa.2014.46 is OK
- 10.1038/nn.4358 is OK
- 10.1364/OE.401117 is OK
- 10.1364/OE.27.031316 is OK
- 10.1364/OE.25.004368 is OK
- 10.1364/OE.26.001655 is OK
- 10.1364/OE.23.026208 is OK
- 10.5281/zenodo.3885508 is OK
- 10.1364/boda.2021.dth2a.2 is OK
- 10.1364/OE.442025 is OK
- 10.1364/BOE.8.004369 is OK
- 10.1364/AOPT.2005.AThB4 is OK
- 10.1111/j.1365-2966.2004.08524.x is OK
- 10.1117/12.2054470 is OK
- 10.1364/OL.26.000746 is OK
- 10.1146/annurev.aa.31.090193.000305 is OK
- 10.1097/OPX.0b013e3181ff9a8b is OK
- 10.1098/rsta.2007.0013 is OK
- 10.1038/nmeth.4218 is OK
- 10.3928/1081-597X-20010901-13 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
@jiahecui would be great if you could recommend some reviewers?

**Comment by jiahecui** [comment]
> Hello and thank you for agreeing to be editor! Suggestion for potential reviewers: caldarolamartin, jonatanalvelid.

**Comment by diehlpk** [comment]
Hi @caldarolamartin and @jonatanalvelid would you be interested in reviewing this paper?

**Comment by diehlpk** [comment]
Hi @dvanic or @sfuxy or @jodemaey or @abhilash12iec002 would you be interested in reviewing this paper?

**Comment by dvanic** [comment]
@diehlpk: sorry, it's too far outside my area of expertise 😓

**Comment by jonatanalvelid** [comment]
Hi @diehlpk, thank you for considering me, but I am unfortunately not available to review currently.
I hope I will be considered again in the future and will happily review then, and thanks for your understanding.

Best,
Jonatan

**Comment by abhilash12iec002** [comment]
Yes, I can review the said paper.



Best,

Abhilash Singh
PhD Scholar, 1810302
Fluvial Geomorphology and Remote Sensing Lab,
Department of EES, AB-2, Lab-10,
Indian Institute of Science Education and Research Bhopal
mobile: +91-9990674147
***@***.***
www.abhilashsingh.net
***@***.***>

**Comment by jodemaey** [comment]
Hi,

Same as @dvanic comment for me, it is way outside of my area of expertise.

Sorry,

Jonathan

**Comment by diehlpk** [comment]
@whedon assign @abhilash12iec002  as reviewer

**Comment by whedon** [comment]
OK, @abhilash12iec002  is now a reviewer

**Comment by diehlpk** [comment]
@jiahecui would be great if you could recommend more reviewers?

**Comment by abhilash12iec002** [comment]
@jiahecui Please find my comments below;
I have read the complete article, “SenAOReFoc: A Closed-Loop Sensorbased Adaptive Optics and Remote Focusing Control Software” with full consideration. The title is short and sufficient. The summary part is nicely written in a very concise way. In the statement of need section, there exists a scope of improvement. For example; “The functionality of the software has also been tested on different operating systems (Windows/macOS/Linux) for sake of generality.” For this line, a concluding remark on the performance on each platform must be added. Also, the lines from 71 to 73 must be explained in detail. I think these two points are very crucial points and a good set of motivation for this software. I am very much satisfied with the Example usage section. Apart from reading the article, I have spent a good chunk of time using the SenAOReFoc package in the due course of this review. I am satisfied with the functionality of this software. 

Overall, the submitted manuscript is well written, and ably demonstrates the community requirement for this open-source tool. I recommend publication after incorporating the suggestions discussed above.

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4075.

**Comment by diehlpk** [comment]
@abhilash12iec002 That was quick. I started the review in #4075, and please check the checkboxes there.

**Comment by jiahecui** [comment]
> 

@diehlpk Sure no problem, I suggest JackTyson, caldarolamartin, alvesjnr, aquilesC. Thank you very much!

**Comment by jiahecui** [comment]
> @jiahecui Please find my comments below; I have read the complete article, “SenAOReFoc: A Closed-Loop Sensorbased Adaptive Optics and Remote Focusing Control Software” with full consideration. The title is short and sufficient. The summary part is nicely written in a very concise way. In the statement of need section, there exists a scope of improvement. For example; “The functionality of the software has also been tested on different operating systems (Windows/macOS/Linux) for sake of generality.” For this line, a concluding remark on the performance on each platform must be added. Also, the lines from 71 to 73 must be explained in detail. I think these two points are very crucial points and a good set of motivation for this software. I am very much satisfied with the Example usage section. Apart from reading the article, I have spent a good chunk of time using the SenAOReFoc package in the due course of this review. I am satisfied with the functionality of this software.
> 
> Overall, the submitted manuscript is well written, and ably demonstrates the community requirement for this open-source tool. I recommend publication after incorporating the suggestions discussed above.

@abhilash12iec002 Thank you very much for the thorough review and detailed comments. Your time is greatly appreciated! We will make the revisions as soon as possible!

**Comment by abhilash12iec002** [comment]
@jiahecui Thanks and Good luck!

**Comment by diehlpk** [comment]
Hi  @JackTyson, @caldarolamartin, @alvesjnr, @aquilesC would you be interested in reviewing this paper?

**Comment by aquilesC** [comment]
Thanks for the invite! I am wrapping up another review here on JOSS and with zero bandwidth to take up another one.

**Comment by JackTyson** [comment]
Hi @diehlpk, yes, this area sits within my expertise and I would be happy to review.

**Comment by diehlpk** [comment]
@whedon add @JackTyson as reviewer

**Comment by whedon** [comment]
OK, @JackTyson is now a reviewer

**Comment by alvesjnr** [comment]
Hi,

I would be happy to review.

**Comment by diehlpk** [comment]
@whedon add  @alvesjnr as reviewer

**Comment by whedon** [comment]
OK,  @alvesjnr is now a reviewer
