### ISSUE TITLE
[PRE REVIEW]: SimuPy Flight Vehicle Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4026]
**Submitting author:** @ixjlyons (<a href="http://orcid.org/0000-0002-9143-8459">Kenneth Lyons</a>)
**Repository:** https://github.com/nasa/simupy-flight
**Branch with paper.md** (empty if default branch): 
**Version:** 0.0.1
**Editor:** @prashjha
**Reviewers:** @athulpg007, @aliaksei135
**Managing EiC:** Arfon Smith

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d9c33e4d58c9c4722139138c4d9a67be/status.svg)](https://joss.theoj.org/papers/d9c33e4d58c9c4722139138c4d9a67be)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d9c33e4d58c9c4722139138c4d9a67be"><img src="https://joss.theoj.org/papers/d9c33e4d58c9c4722139138c4d9a67be/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d9c33e4d58c9c4722139138c4d9a67be/status.svg)](https://joss.theoj.org/papers/d9c33e4d58c9c4722139138c4d9a67be)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ixjlyons. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dpsanders.

@ixjlyons if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 378

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (354.2 files/s, 122761.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             15            801            445           8751
HTML                             2            167              0           3404
Python                          34            691            218           3007
Jupyter Notebook                 1              0           1216            443
TeX                              1             18              0            126
reStructuredText                 2             32             18             44
Markdown                         1              4              0             23
-------------------------------------------------------------------------------
SUM:                            56           1713           1897          15798
-------------------------------------------------------------------------------


Statistical information for the repository 'b43de56b30069440b4042c08' was
gathered on 2021/12/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ben Margolis                    45          5091           1591           85.84
Kenneth Lyons                    3           270            343            7.88
ben                              1           489              0            6.28

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ben Margolis               3160           62.1          6.8                1.80
Kenneth Lyons               267           98.9          1.8                1.50
ben                         489          100.0          1.9                6.34
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04026/joss.04026/10.21105.joss.04026.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04026/joss.04026/10.21105.joss.04026.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00396 is OK
- 10.2514/6.2002-4482 is OK
- 10.7717/peerj-cs.103 is OK
- 10.2514/6.2019-2901 is OK
- 10.5281/zenodo.3940699 is OK
- 10.21105/joss.01745 is OK

MISSING DOIs

- 10.2514/6.2020-1012 may be a valid DOI for title: Pterodactyl: Development and comparison of control architectures for a mechanically deployed entry vehicle
- 10.1007/s40295-019-00191-2 may be a valid DOI for title: Nonlinear model predictive control of reentry vehicles based on Takagi-Sugeno fuzzy models
- 10.2514/6.2021-0762 may be a valid DOI for title: Pterodactyl: System Analysis of an Asymmetric and Symmetric Deployable Entry Vehicle for Precision Targeting Using Flaps
- 10.2514/6.2021-0764.vid may be a valid DOI for title: Pterodactyl: Guidance and Control of a Symmetric Deployable Entry Vehicle using an Aerodynamic Control System

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@ixjlyons – many thanks for your submission to JOSS. While we look for an editor to handle this submission, if you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@ixjlyons – I also see that your software is licensed under the NOSA agreement. Could you please update the PDF license to be a plain text file named `LICENSE` in your repository (with the [NOSA agreement language](https://opensource.org/licenses/NASA-1.3)).

**Comment by sixpearls** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04026/joss.04026/10.21105.joss.04026.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04026/joss.04026/10.21105.joss.04026.pdf) :page_facing_up: :point_left:

**Comment by sixpearls** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00396 is OK
- 10.2514/6.2002-4482 is OK
- 10.7717/peerj-cs.103 is OK
- 10.2514/6.2019-2901 is OK
- 10.2514/6.2020-1012 is OK
- 10.1007/s40295-019-00191-2 is OK
- 10.2514/6.2021-0762 is OK
- 10.5281/zenodo.3940699 is OK
- 10.21105/joss.01745 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.2514/6.2021-0764. is INVALID
```

**Comment by sixpearls** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04026/joss.04026/10.21105.joss.04026.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04026/joss.04026/10.21105.joss.04026.pdf) :page_facing_up: :point_left:

**Comment by sixpearls** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00396 is OK
- 10.2514/6.2002-4482 is OK
- 10.7717/peerj-cs.103 is OK
- 10.2514/6.2019-2901 is OK
- 10.2514/6.2020-1012 is OK
- 10.1007/s40295-019-00191-2 is OK
- 10.2514/6.2021-0762 is OK
- 10.2514/6.2021-0764 is OK
- 10.5281/zenodo.3940699 is OK
- 10.21105/joss.01745 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@prashjha are you interested in editing this submission?

**Comment by whedon** [comment]
@prashjha has been invited to edit this submission.

**Comment by prashjha** [comment]
@kthyng thank you. I will be glad to be editor of this submission.

**Comment by prashjha** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @prashjha

**Comment by prashjha** [comment]
Hi, @ixjlyons, it is a pleasure to handle your submission as the editor. Could you please suggest a couple of potential reviewers from this [reviewers list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822). Let me know if you have trouble finding the names.

**Comment by prashjha** [comment]
@ixjlyons, while you and I are looking for potential reviewers, I have a few remarks for the draft of the paper:

As per the example JOSS paper [here](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography), you are missing 'Statement of Need'. For a software article, I would also like to see some details about the model and application using your code. You may also need to add the 'Acknowledgments' section if any. I would recommend keeping the article within 3 page limit (excluding references).

**Comment by prashjha** [comment]
Hi @ixjlyons, could you please respond to my comments above? Thanks!

**Comment by ixjlyons** [comment]
Hi @prashjha, apologies for the delay.

We are working on updates to the paper per your suggestions.

In the meantime, here are some reviewers that look like they might be interested in reviewing this submission:

- aliaksei135
- athulpg007
- cknoll
- crbinz
- Juanlu001
- helgee
- ngoiz

(I haven't @'d them in case you want to downselect first)

Also, I saw a few others in the list that might be appropriate in case the above don't work out.

**Comment by prashjha** [comment]
Hi @aliaksei135, would you be interested in reviewing this submission for JOSS?

**Comment by prashjha** [comment]
Howdy @athulpg007, any chance you could review this JOSS submission?

**Comment by athulpg007** [comment]
I am happy to review this submission.

**Comment by aliaksei135** [comment]
Likewise happy to review.

**Comment by ixjlyons** [comment]
@whedon generate pdf

**Comment by ixjlyons** [comment]
@editorialbot generate pdf

**Comment by ixjlyons** [comment]
@prashjha we've made some updates to the paper including adding a statement of need section.

**Comment by ixjlyons** [comment]
@prashjha

**Comment by prashjha** [comment]
Dear @athulpg007 and @aliaksei135, there was some delay in starting the review. I am hoping you both are still good to review this submission. I will kickstart the review today.

**Comment by prashjha** [comment]
@ixjlyons thanks...looks good in a quick glance.

**Comment by prashjha** [comment]
@editorialbot check references

**Comment by prashjha** [comment]
@editorialbot start review

**Comment by prashjha** [comment]
@editorialbot add @athulpg007 as reviewer

**Comment by prashjha** [comment]
@editorialbot add @aliaksei135 as reviewer

**Comment by prashjha** [comment]
@editorialbot start review
