### ISSUE TITLE
[PRE REVIEW]: NLFFF: A Python package for a 3D non-linear force-free magnetic field extrapolation in cartesian coordinate system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4027]
**Submitting author:** @liusnaoc (<a href="http://orcid.org/0000-0002-1396-7603">Suo Liu</a>)
**Repository:** <a href="https://github.com/liusnaoc/NLFFF_opti.git" target ="_blank">https://github.com/liusnaoc/NLFFF_opti.git</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ad3e392f6d468ae0149f71dc150e21fd/status.svg)](https://joss.theoj.org/papers/ad3e392f6d468ae0149f71dc150e21fd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ad3e392f6d468ae0149f71dc150e21fd"><img src="https://joss.theoj.org/papers/ad3e392f6d468ae0149f71dc150e21fd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ad3e392f6d468ae0149f71dc150e21fd/status.svg)](https://joss.theoj.org/papers/ad3e392f6d468ae0149f71dc150e21fd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @liusnaoc. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@liusnaoc if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 856

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s11207-020-01622-2 is OK
- 10.1086/309355 is OK
- 10.1007/s11207-020-01622-2 is OK
- 10.1086/155111 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (327.1 files/s, 47050.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             62             51            473
Markdown                         2             53              0            142
TeX                              1              0              0             63
IDL                              1              3              6             10
-------------------------------------------------------------------------------
SUM:                             6            118             57            688
-------------------------------------------------------------------------------


Statistical information for the repository 'd46b514312e8febcae233f2a' was
gathered on 2021/12/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Liu Suo                          1           586              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Liu Suo                     586          100.0          0.0                4.95
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04027/joss.04027/10.21105.joss.04027.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04027/joss.04027/10.21105.joss.04027.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@liusnaoc – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by liusnaoc** [comment]
@arfon  I integrate some complex algorithms into one program, which may be relatively small, but it needs a lot of programming and related testing work.

**Comment by arfon** [comment]
@liusnaoc – thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
