### ISSUE TITLE
[PRE REVIEW]: ImagingReso: A Tool for Neutron Resonance Imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#403]
**Submitting author:** @zhangy6x (<a href="http://orcid.org/0000-0002-0083-1408">Yuxuan Zhang</a>)
**Repository:** <a href="https://github.com/ornlneutronimaging/ImagingReso" target ="_blank">https://github.com/ornlneutronimaging/ImagingReso</a>
**Version:** v1.5.8
**Editor:** @arokem
**Reviewer:** @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSS @zhangy6x. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zhangy6x if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
👋 @katyhuff : do you know anyone who could review this? Looks like it might be in your ball park (??)

**Comment by arokem** [comment]
@zhangy6x : alternatively, do you have any suggestions for reviewers?

**Comment by zhangy6x** [comment]
@arokem I think @betatim and @nicoguaro could be potential reviewers for this work. Thanks.

**Comment by nicoguaro** [comment]
I think that I can review this.

**Comment by arokem** [comment]
@whedon assign @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nicoguaro

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/407. Feel free to close this issue now!

**Comment by arokem** [comment]
@nicoguaro : thanks for reviewing! Head over to #407 for the review. I will close this one.
