### ISSUE TITLE
[REVIEW]: mixR: An R package for Finite Mixture Modeling for Both Raw and Binned Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4031]
**Submitting author:** @GaryBAYLOR (<a href="http://orcid.org/0000-0003-0519-9605">Youjiao Yu</a>)
**Repository:** <a href="https://github.com/GaryBAYLOR/mixR.git" target ="_blank">https://github.com/GaryBAYLOR/mixR.git</a>
**Version:** v0.2.1
**Editor:** @fboehm
**Reviewer:** @welch16, @soodoku
**Archive:** <a href="https://doi.org/10.5281/zenodo.5842096" target="_blank">10.5281/zenodo.5842096</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f330cc88d1d8dc43fb6ba8f426beff21/status.svg)](https://joss.theoj.org/papers/f330cc88d1d8dc43fb6ba8f426beff21)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f330cc88d1d8dc43fb6ba8f426beff21"><img src="https://joss.theoj.org/papers/f330cc88d1d8dc43fb6ba8f426beff21/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f330cc88d1d8dc43fb6ba8f426beff21/status.svg)](https://joss.theoj.org/papers/f330cc88d1d8dc43fb6ba8f426beff21)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/GaryBAYLOR/mixR.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@welch16 & @soodoku, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fboehm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @welch16
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/GaryBAYLOR/mixR.git">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/GaryBAYLOR/mixR.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@GaryBAYLOR) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @soodoku
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/GaryBAYLOR/mixR.git">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/GaryBAYLOR/mixR.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@GaryBAYLOR) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @welch16, @soodoku it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1120

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1977.tb01600.x is OK
- 10.1111/j.2517-6161.1996.tb02104.x is OK
- 10.2307/2347790 is OK
- 10.1080/03610926.2018.1494838 is OK
- 10.18637/jss.v032.i06 is OK
- 10.32614/rj-2016-021 is OK
- 10.18637/jss.v011.i08 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1002/wics.147 is OK
- 10.1007/s10661-020-8223-4 is OK
- 10.1016/j.watres.2019.115369 is OK
- 10.1080/10549811.2020.1841009 is OK
- 10.1101/2020.10.21.348573 is OK
- 10.1016/j.jvolgeores.2021.107257 is OK
- 10.1016/j.physa.2021.126764 is OK
- 10.1093/forsci/fxab051 is OK
- 10.1142/12366 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (883.6 files/s, 91109.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               51            412            981           2064
C++                              2            184            271           1602
TeX                              2             29              0            241
Markdown                         4             60              0            163
Rmd                              1             51            126             69
YAML                             1              4              7             26
-------------------------------------------------------------------------------
SUM:                            61            740           1385           4165
-------------------------------------------------------------------------------


Statistical information for the repository '1ca6dfe2deee2a80c2576670' was
gathered on 2022/01/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Xiaozhen Han                     1            40              0            1.91
Youjiao (Gary) Yu                1          2035             18           98.09

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Xiaozhen Han                 22           55.0          0.0                9.09
Youjiao (Gary) Yu          2035          100.0          0.0               14.59
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04031/joss.04031/10.21105.joss.04031.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04031/joss.04031/10.21105.joss.04031.pdf) :page_facing_up: :point_left:

**Comment by welch16** [comment]
Hey @fboehm, this is my first time reviewing for JOSS, so I was wondering if I can comment on the package vignette and such?

**Comment by soodoku** [comment]
@fboehm ---all clear from my end. @GaryBAYLOR made all the recommended changes.

**Comment by fboehm** [comment]
@soodoku and @welch16 - Thanks so much for your work on the reviews! Yes, @welch16 - please do comment on the vignettes and other features of the package as needed. Please feel free to post comments in this thread and to open issues in the package repository as you work through the package. Please don't hesitate to ask me any questions that arise. Thanks again!

**Comment by fboehm** [comment]
@welch16 - for any issues that you open in the package repository, please post a comment here in this thread with a link to the issue. Thanks again!

**Comment by welch16** [comment]
I create an issue here: https://github.com/GaryBAYLOR/mixR/issues/32. But except that, I think everything looks good

**Comment by GaryBAYLOR** [comment]
Hi @fboehm,
Here are links to all issues raised by @soodoku.
Contributor Guidelines: https://github.com/GaryBAYLOR/mixR/issues/17
statement of need within readme: https://github.com/GaryBAYLOR/mixR/issues/18
model object: https://github.com/GaryBAYLOR/mixR/issues/20
has bic been consistently implemented? https://github.com/GaryBAYLOR/mixR/issues/21
documenting 'ev': https://github.com/GaryBAYLOR/mixR/issues/22
more helpful error would be useful: https://github.com/GaryBAYLOR/mixR/issues/23
missing error message? https://github.com/GaryBAYLOR/mixR/issues/25
more unit tests: https://github.com/GaryBAYLOR/mixR/issues/26

Thanks!

**Comment by welch16** [comment]
@fboehm: all clear from my end too

**Comment by fboehm** [comment]
Thanks, @welch16 and @soodoku for your constructive reviews. Thanks, @GaryBAYLOR - there are a few remaining steps before publication. Let me proofread the manuscript in the next two days. I'll then provide instructions for the remaining steps - namely, making an archive and a new release... but don't do those steps until I get back to you after the proofreading. Thanks again!

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04031/joss.04031/10.21105.joss.04031.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04031/joss.04031/10.21105.joss.04031.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
@GaryBAYLOR - here are a few minor edits needed for paper.md:

1. Line 29 (of the pdf): ggplot should be ggplot2. Also, be sure to typeset ggplot2 as you did the other package names. 
2. Line 48 (of the pdf): "binning is it" should be "binning is that it"
3. line 94 (of the pdf): "better than it with" should be "better than that with"
4. Figure 2 (top left and top right) : Do you want to change the axis tick labels to be only on the integers? Since you're considering only integer values? Right now, they have 0.5 increments.

**Comment by fboehm** [comment]
@GaryBAYLOR - The references section of the pdf needs a few edits:

1. In Eddelbuettel, et al., capitalize R and C (in C++). 
2. in Benaglia, et al., capitalize R.
3. Korne, et al. has the wrong doi: use https://dx.doi.org/10.1128/mSphere.00218-21. The currently listed doi directs to the preprint.
4. Leisch (2004) needs a capital R. Also, the "m" in FlexMix needs to be capitalized.
5. Scrucca, et al. needs a lower case "m" in "mclust", even though it is the first letter of the title.
6. Sylvestre, et al. needs capital "E." and lower-case "coli".
7. Yang, et al. needs a capital "T" in "Tennessee". 
8. Yang (2021) needs a capital "R".

**Comment by fboehm** [comment]
All other doi's direct to the correct articles.

**Comment by GaryBAYLOR** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04031/joss.04031/10.21105.joss.04031.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04031/joss.04031/10.21105.joss.04031.pdf) :page_facing_up: :point_left:

**Comment by GaryBAYLOR** [comment]
Hi @fboehm, thanks for your proofreading and detailed comments. I fixed all issues about the text, plots and the references. 
* For the plots (the first two in Figure 2), I updated the paper as well as the R function plot.selectEM() in the package to only plot integer values on x axis. 
* For issues in the references, I just realize that JOSS compiler automatically changes the first letter of the first word in the paper title to uppercase, and all other letters to lowercase (if not followed by .). So I manually forced letters to be uppercase or lowercase by using {A} or {a}.

Please let me know if you still have other comments. And again, I appreciate your help in improving the quality of the paper.

**Comment by fboehm** [comment]
Thanks so much, @GaryBAYLOR ! 

Please create an archive, with a service like zenodo, and a new git release of your package. Please be sure that the title and authors for the archive match exactly those of the paper.md. Once you've done those two tasks, please report here the version number for the release and the doi for the archive. Let me know if you have any questions about this. Thanks again!

**Comment by GaryBAYLOR** [comment]
Hi @fboehm,
I have created a new release of mixR on Github with version number v0.2.1 (see [here](https://github.com/GaryBAYLOR/mixR/tree/v0.2.1))
I have created an archive on Zenodo with DOI: 10.5281/zenodo.5842096 (see [here](https://zenodo.org/record/5842096#.Yd8x3xPMKFi)).

Can you help check if both the git release and zenodo archive are in correct format required by JOSS? Thanks!
Youjiao

**Comment by fboehm** [comment]
@whedon set version as v0.2.1

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by fboehm** [comment]
@whedon commands

**Comment by whedon** [comment]
OK. v0.2.1 is the version.

**Comment by fboehm** [comment]
@whedon set 10.5281/zenodo.5842096 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5842096" target="_blank">10.5281/zenodo.5842096</a> is the archive.

**Comment by fboehm** [comment]
Hi, @GaryBAYLOR - the release and the archive look good. Thanks!

**Comment by fboehm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1977.tb01600.x is OK
- 10.1111/j.2517-6161.1996.tb02104.x is OK
- 10.2307/2347790 is OK
- 10.1080/03610926.2018.1494838 is OK
- 10.18637/jss.v032.i06 is OK
- 10.32614/rj-2016-021 is OK
- 10.18637/jss.v011.i08 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1002/wics.147 is OK
- 10.1007/s10661-020-8223-4 is OK
- 10.1016/j.watres.2019.115369 is OK
- 10.1080/10549811.2020.1841009 is OK
- 10.1128/mSphere.00218-21 is OK
- 10.1016/j.jvolgeores.2021.107257 is OK
- 10.1016/j.physa.2021.126764 is OK
- 10.1093/forsci/fxab051 is OK
- 10.1142/12366 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by fboehm** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1977.tb01600.x is OK
- 10.1111/j.2517-6161.1996.tb02104.x is OK
- 10.2307/2347790 is OK
- 10.1080/03610926.2018.1494838 is OK
- 10.18637/jss.v032.i06 is OK
- 10.32614/rj-2016-021 is OK
- 10.18637/jss.v011.i08 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1002/wics.147 is OK
- 10.1007/s10661-020-8223-4 is OK
- 10.1016/j.watres.2019.115369 is OK
- 10.1080/10549811.2020.1841009 is OK
- 10.1128/mSphere.00218-21 is OK
- 10.1016/j.jvolgeores.2021.107257 is OK
- 10.1016/j.physa.2021.126764 is OK
- 10.1093/forsci/fxab051 is OK
- 10.1142/12366 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2880

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2880, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon recommend-accept

Thanks all - this looks good

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1977.tb01600.x is OK
- 10.1111/j.2517-6161.1996.tb02104.x is OK
- 10.2307/2347790 is OK
- 10.1080/03610926.2018.1494838 is OK
- 10.18637/jss.v032.i06 is OK
- 10.32614/rj-2016-021 is OK
- 10.18637/jss.v011.i08 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1002/wics.147 is OK
- 10.1007/s10661-020-8223-4 is OK
- 10.1016/j.watres.2019.115369 is OK
- 10.1080/10549811.2020.1841009 is OK
- 10.1128/mSphere.00218-21 is OK
- 10.1016/j.jvolgeores.2021.107257 is OK
- 10.1016/j.physa.2021.126764 is OK
- 10.1093/forsci/fxab051 is OK
- 10.1142/12366 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2881

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2881, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1481679080986714112) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2882
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.04031](https://doi.org/10.21105/joss.04031)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @GaryBAYLOR (Youjiao Yu)!!

And thanks to @welch16 and @soodoku for reviewing, and @fboehm for editing!
We couldn't do this without you!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.04031/status.svg)](https://doi.org/10.21105/joss.04031)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.04031">
  <img src="https://joss.theoj.org/papers/10.21105/joss.04031/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.04031/status.svg
   :target: https://doi.org/10.21105/joss.04031
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.04031/status.svg)](https://doi.org/10.21105/joss.04031)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
