### ISSUE TITLE
[PRE REVIEW]: APCtools: Descriptive and Model-based Age-Period-Cohort Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4034]
**Submitting author:** @bauer-alex (<a href="http://orcid.org/0000-0003-3495-5131">Alexander Bauer</a>)
**Repository:** <a href="https://github.com/bauer-alex/APCtools" target ="_blank">https://github.com/bauer-alex/APCtools</a>
**Version:** 1.0.0
**Editor:** @Nikoleta-v3
**Reviewers:** @strengejacke , @fernandomayer
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/521ba03bdc6e6f19fd7b66d2e1ef3759/status.svg)](https://joss.theoj.org/papers/521ba03bdc6e6f19fd7b66d2e1ef3759)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/521ba03bdc6e6f19fd7b66d2e1ef3759"><img src="https://joss.theoj.org/papers/521ba03bdc6e6f19fd7b66d2e1ef3759/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/521ba03bdc6e6f19fd7b66d2e1ef3759/status.svg)](https://joss.theoj.org/papers/521ba03bdc6e6f19fd7b66d2e1ef3759)
```

**Author instructions**

Thanks for submitting your paper to JOSS @bauer-alex. **Currently, there isn't an JOSS editor assigned** to your paper.

@bauer-alex if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 989

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/sim.2764 is OK
- 10.1093/biostatistics/kxi028 is OK
- 10.1097/EDE.0000000000001236 is OK
- 10.1093/biomet/asn026 is OK
- 10.1158/1055-9965.EPI-14-0300 is OK
- 10.18637/jss.v021.i08 is OK
- 10.1177/1354816620987198 is OK
- 10.1201/9781315370279 is OK
- 10.1201/b13902 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (340.3 files/s, 47430.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               25            650           1199           1927
SVG                              2              1              1            697
YAML                             7             50             13            214
Markdown                         3             45              0            189
TeX                              1             11              0             98
Rmd                              2            107            277             96
-------------------------------------------------------------------------------
SUM:                            40            864           1490           3221
-------------------------------------------------------------------------------


Statistical information for the repository '83ed6a38456e94af19c09dc3' was
gathered on 2022/01/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04034/joss.04034/10.21105.joss.04034.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04034/joss.04034/10.21105.joss.04034.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04034/joss.04034/10.21105.joss.04034.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04034/joss.04034/10.21105.joss.04034.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @Bisaloo! Are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @Bisaloo as editor

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by kthyng** [comment]
@bauer-alex: please add an open source license and make sure one section in your paper is entitled "Statement of Need".

**Comment by kthyng** [comment]
Hi @Nikoleta-v3! Are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @Nikoleta-v3 as editor

**Comment by whedon** [comment]
@Nikoleta-v3 has been invited to edit this submission.

**Comment by Nikoleta-v3** [comment]
👋🏻 @kthyng! Happy new year. I'm happy to edit this submission

**Comment by Nikoleta-v3** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Nikoleta-v3

**Comment by bauer-alex** [comment]
Thanks @kthyng and @Nikoleta-v3 for your efforts!

Regarding the missing points raised by Kristen:

> @bauer-alex: please add an open source license and make sure one section in your paper is entitled "Statement of Need".

I now added both the open source license and the _Statement of Need_ section.

**Comment by Nikoleta-v3** [comment]
Thank you @bauer-alex! Could you take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers 😄

**Comment by bauer-alex** [comment]
Then I would suggest @noamross (Noam Ross) and @strengejacke (Daniel Lüdecke).

Let me know if you need more suggestions.

**Comment by Nikoleta-v3** [comment]
Can you recommend 2 more reviewers? Thank you!

**Comment by bauer-alex** [comment]
Sure, here you go: @cmaimone (Christina Maimone) and @rrrlw (Raoul Wadhwa)

**Comment by rrrlw** [comment]
Unfortunately, I am unable to review this submission. Best of luck!

**Comment by cmaimone** [comment]
No, I just accepted another review yesterday.

**Comment by strengejacke** [comment]
Happy new year everyone! I'm happy to review this submission!

**Comment by Nikoleta-v3** [comment]
Thank you everyone for your replies, and happy new year!

**Comment by Nikoleta-v3** [comment]
@whedon assign @strengejacke  as reviewer

**Comment by whedon** [comment]
OK, @strengejacke  is now a reviewer

**Comment by Nikoleta-v3** [comment]
👋 @allaway & @fernandomayer &  @franjoim & @allenzhuaz would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "APCtools: Descriptive and Model-based Age-Period-Cohort Analysis". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by allaway** [comment]
@Nikoleta-v3 I am not an expert (or even really familiar with) Age-Period-Cohort analysis, but would be happy read up on it a bit and review.

**Comment by fernandomayer** [comment]
Yes, I would be happy to make this review.

**Comment by Nikoleta-v3** [comment]
@whedon add @fernandomayer as reviewer

**Comment by whedon** [comment]
OK, @fernandomayer is now a reviewer

**Comment by Nikoleta-v3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4056.

**Comment by Nikoleta-v3** [comment]
👋🏻  @allaway! I hope you are well 😄  

A while back I asked if you could review this submission and you very kindly agreed.

Back then a few more people stepped up and I assigned different reviewers. Unfortunately, one of them is not available any more.

The review is currently taking place here:  https://github.com/openjournals/joss-reviews/issues/4056. As you can see one reviewer has already gone over the submission. I was wondering if you could help with the second review?

Thank you in advance!

**Comment by allaway** [comment]
Hi @Nikoleta-v3, I am not able to review at the moment, but a colleague of mine (@jaybee84) is registered as a reviewer with JOSS and expressed interest in reviewing this article, in case you are open to considering her!

**Comment by Nikoleta-v3** [comment]
That's amazing -- thank you @allaway for the suggestion! I will assign @jaybee84 as a reviewer. Thank you both very much for your time!
