### ISSUE TITLE
[PRE REVIEW]: svFSI: A Multiphysics Package for Integrated Cardiac Modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4035]
**Submitting author:** @CZHU20 (<a href="http://orcid.org/0000-0002-1099-8893">Chi Zhu</a>)
**Repository:** <a href="https://github.com/SimVascular/svFSI" target ="_blank">https://github.com/SimVascular/svFSI</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @chennachaos, @JaroslavHron,  @axel-loewe
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cf1aa78cd6e9d4cbf818053aef61bc83/status.svg)](https://joss.theoj.org/papers/cf1aa78cd6e9d4cbf818053aef61bc83)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cf1aa78cd6e9d4cbf818053aef61bc83"><img src="https://joss.theoj.org/papers/cf1aa78cd6e9d4cbf818053aef61bc83/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cf1aa78cd6e9d4cbf818053aef61bc83/status.svg)](https://joss.theoj.org/papers/cf1aa78cd6e9d4cbf818053aef61bc83)
```

**Author instructions**

Thanks for submitting your paper to JOSS @CZHU20. **Currently, there isn't an JOSS editor assigned** to your paper.

@CZHU20 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jcp.2015.11.022 is OK
- 10.1161/CIRCRESAHA.110.223610 is OK
- 10.1007/s10439-016-1762-8 is OK
- 10.1115/1.4005694 is OK
- 10.1016/j.jelectrocard.2003.09.017 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.1371/journal.pcbi.1005828 is OK
- 10.1371/journal.pcbi.1009331 is OK
- 10.1016/j.jbiomech.2018.03.034 is OK
- 10.1002/cnm.3351 is OK
- 10.1615/Int.J.UncertaintyQuantification.2020033068 is OK
- 10.1007/s10237-020-01294-8 is OK
- 10.1115/1.4048032 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1210

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.85 s (214.3 files/s, 93933.8 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
Fortran 77                              79           6159           7485          37515
C                                      121           8078           7418          32300
C++                                      5           3117           6762          27459
C/C++ Header                            50           2780           4050          12528
Fortran 90                               5           1081            353           6067
make                                    46            419            585           2621
CMake                                   35            436            928           2118
Bourne Shell                            35            255            260            680
Markdown                                 5            237              0            680
CSS                                      1             92             47            217
TeX                                      1             16              0            160
Tcl/Tk                                   3             50            110            150
Bourne Again Shell                       7             66             90            142
Windows Module Definition                1              1              6             53
WiX source                               1             10              0             23
HTML                                     1              0              0             12
---------------------------------------------------------------------------------------
SUM:                                   396          22797          28094         122725
---------------------------------------------------------------------------------------


Statistical information for the repository '19f6d329e7ea08cda6dad05e' was
gathered on 2022/01/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chi                              1             6              2            0.00
Vijay Vedula                     7           257            205            0.27
alexkaiser                       1             0          50067           29.37
osmsc                            1        119931              0           70.35

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chi Zhu                       4          100.0          0.6                0.00
Vijay Vedula                256           99.6          8.3               18.75
osmsc                     69660           58.1          0.0               19.87
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04035/joss.04035/10.21105.joss.04035.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04035/joss.04035/10.21105.joss.04035.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @Kevin-Mattheus-Moerman would you like to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@chennachaos @JaroslavHron @albansouche @meg-simula @soudah @loumalouomega @philbucher @sbryngelson @RiccardoRossi would you be interested in reviewing this work _"svFSI: A Multiphysics Package for Integrated Cardiac Modeling"_ for [JOSS, the journal of open source software](https://joss.theoj.org)?  

JOSS reviews and publishes open source software. The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on a very short paper (see here: [:page_with_curl:](https://github.com/openjournals/joss-papers/blob/joss.04035/joss.04035/10.21105.joss.04035.pdf)) and the software itself (see here: [:floppy_disk:](https://github.com/SimVascular/svFSI) ). 

This here is a pre-review issue where we assign reviewers. Once we have sufficient reviewers we will open a dedicated review issue. Here is an example of such an issue for a previous submission: https://github.com/openjournals/joss-reviews/issues/2089

Let me know if you have questions. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@CZHU20 thanks for this submission. As you can see I have started to invite potential reviewers. My apologies for the delay in getting this process started. 
If at this point you can suggest reviewers please do so. You can mention them here but leave the `@` symbol for now. Thanks.

**Comment by sbryngelson** [comment]
I’m not qualified to review this.

On Jan 31, 2022, at 17:14, Kevin Mattheus Moerman ***@***.******@***.***>> wrote:



@chennachaos<https://github.com/chennachaos> @JaroslavHron<https://github.com/JaroslavHron> @albansouche<https://github.com/albansouche> @meg-simula<https://github.com/meg-simula> @soudah<https://github.com/soudah> @loumalouomega<https://github.com/loumalouomega> @philbucher<https://github.com/philbucher> @sbryngelson<https://github.com/sbryngelson> @RiccardoRossi<https://github.com/RiccardoRossi> would you be interested in reviewing this work "svFSI: A Multiphysics Package for Integrated Cardiac Modeling" for JOSS, the journal of open source software<https://joss.theoj.org/>?

JOSS reviews and publishes open source software. The review process<https://joss.readthedocs.io/en/latest/reviewer_guidelines.html> takes place on GitHub and focuses on a very short paper (see here: 📃<https://github.com/openjournals/joss-papers/blob/joss.04035/joss.04035/10.21105.joss.04035.pdf>) and the software itself (see here: 💾<https://github.com/SimVascular/svFSI> ).

This here is a pre-review issue where we assign reviewers. Once we have sufficient reviewers we will open a dedicated review issue. Here is an example of such an issue for a previous submission: #2089<https://github.com/openjournals/joss-reviews/issues/2089>

Let me know if you have questions. Thanks!

**Comment by CZHU20** [comment]
@Kevin-Mattheus-Moerman Thank you for the help! 
I would recommend Dr. Boyce Griffith (boyceg), Dr. Roman Poya (romeric) and Dr. Steve Maas (SteveMaas1978) as potential reviewers.

**Comment by JaroslavHron** [comment]
Hi, I will be happy to review this work.

**Comment by chennachaos** [comment]
Hi @Kevin-Mattheus-Moerman!
I will be happy to review this. Count me in. Thanks!

**Comment by loumalouomega** [comment]
Greetings, for an FSI framework maybe Dr. @rubenzorrilla is better suited than me (he is active in the project which I assume you were looking for when elaborating the list)

So, no from my side, but now I know JOSS, thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @chennachaos as reviewer

**Comment by whedon** [comment]
OK, @chennachaos is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @JaroslavHron as reviewer

**Comment by whedon** [comment]
OK, @JaroslavHron is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
I reached out to @axel-loewe via Twitter, and he agreed to help with this review, so I'll add him now and we'll start the review process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add  @axel-loewe as reviewer

**Comment by whedon** [comment]
OK,  @axel-loewe is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4118.

**Comment by Kevin-Mattheus-Moerman** [comment]
If any of the potential reviewers pinged above are still interested to join let me know. I can add you later if needed.

**Comment by philbucher** [comment]
thx for the offer but I currently don't have the time to review

**Comment by rubenzorrilla** [comment]
Many thanks for the offer but I don't have time right now to do a proper review. In any case thanks to this I am now aware of JOSS.
