### ISSUE TITLE
[PRE REVIEW]: False arrhythmia alarm reduction in the intensive care unit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#404]
**Submitting author:** @liandrea4 (<a href="http://orcid.org/0000-0001-8419-5527">Andrea Li</a>)
**Repository:** <a href="https://github.com/MIT-LCP/false-alarm-reduction" target ="_blank">https://github.com/MIT-LCP/false-alarm-reduction</a>
**Version:** v1.0.1
**Editor:** @arfon
**Reviewer:** @stsievert

**Author instructions**

Thanks for submitting your paper to JOSS @liandrea4. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@liandrea4 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@acabunoc
@arfon
@arokem
@biorelated
@brainstorm
@cMadan
@danielskatz
@jakevdp
@karthik
@katyhuff
@kyleniemeyer
@labarba
@leeper
@lheagy
@mgymrek
@pjotrp
@tracykteal
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@stsievert @effigies @oesteban would one of you be willing to review this submission for JOSS?

**Comment by danielskatz** [comment]
ping ... that this seems stuck

**Comment by stsievert** [comment]
I can review this, but probably not right away.

**Comment by arfon** [comment]
> I can review this, but probably not right away.

Great, thanks @stsievert. No huge rush but I'll go ahead and start the main review issue.

**Comment by arfon** [comment]
@whedon assign @stsievert as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stsievert

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/481. Feel free to close this issue now!

**Comment by arfon** [comment]
@stsievert - see you over in #481 for the actual review.
