### ISSUE TITLE
[PRE REVIEW]: HOST: A Python package for Higher-Order-STatitics seismic pickers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4043]
**Submitting author:** @mbagagli (<a href="http://orcid.org/0000-0001-9409-8667">Matteo Bagagli</a>)
**Repository:** <a href="https://github.com/mbagagli/host-picker" target ="_blank">https://github.com/mbagagli/host-picker</a>
**Version:** 2.4.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/507599c646b1444625b5ee52be9cc7a9/status.svg)](https://joss.theoj.org/papers/507599c646b1444625b5ee52be9cc7a9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/507599c646b1444625b5ee52be9cc7a9"><img src="https://joss.theoj.org/papers/507599c646b1444625b5ee52be9cc7a9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/507599c646b1444625b5ee52be9cc7a9/status.svg)](https://joss.theoj.org/papers/507599c646b1444625b5ee52be9cc7a9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mbagagli. **Currently, there isn't an JOSS editor assigned** to your paper.

@mbagagli if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1484

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1785/0120120347 is OK
- 10.1088/1749-4699/8/1/014003 is OK
- 10.1111/j.1365-246X.2010.04570.x is OK
- 10.2312/GFZ.NMSOP-2_CH16 is OK
- 10.4294/zisin1948.38.3_365 is OK
- 10.1109/TGRS.2002.800438 is OK
- 10.1093/gji/ggy423 is OK

MISSING DOIs

- 10.1785/bssa07206b0225 may be a valid DOI for title: Automatic Phase Pickers: Their Present Use and Future Prospects
- 10.1785/bssa0770041437 may be a valid DOI for title: An Automatic Phase Picker for Local and Teleseismic Events
- 10.1016/s0031-9201(99)00007-2 may be a valid DOI for title: Robust Automatic P-phase Picking: An on-Line Implementation in the Analysis of Broadband Seismogram Recordings

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (86.6 files/s, 21441.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            261            502           1072
Markdown                         4            192              0            777
Jupyter Notebook                 5              0           1246            199
TeX                              1             11              0            159
C                                1             53             61            146
YAML                             1              0              2             21
-------------------------------------------------------------------------------
SUM:                            19            517           1811           2374
-------------------------------------------------------------------------------


Statistical information for the repository '98e1840bb9776fba07dffd9e' was
gathered on 2022/01/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
matteo                          24          3482           1387          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
matteo                     2095           60.2         11.8               14.84
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04043/joss.04043/10.21105.joss.04043.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04043/joss.04043/10.21105.joss.04043.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@mbagagli - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @mbagagli - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  The package seems to compute empirical third and fourth moments from datasets, which is a very simple thing to do. Further, we believe the C++ code can probably be replaced with a few lines of vectorized numpy code.

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
