### ISSUE TITLE
[PRE REVIEW]: MitoHEAR: an R package for the estimation and downstream statistical analysis of the mtDNA heteroplasmy calculated from single-cell datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4046]
**Submitting author:** @gabrielelubatti (<a href="http://orcid.org/0000-0001-8495-8096">Gabriele Lubatti</a>)
**Repository:** <a href="https://github.com/ScialdoneLab/MitoHEAR" target ="_blank">https://github.com/ScialdoneLab/MitoHEAR</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c09644764704a44604502c2aa911e004/status.svg)](https://joss.theoj.org/papers/c09644764704a44604502c2aa911e004)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c09644764704a44604502c2aa911e004"><img src="https://joss.theoj.org/papers/c09644764704a44604502c2aa911e004/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c09644764704a44604502c2aa911e004/status.svg)](https://joss.theoj.org/papers/c09644764704a44604502c2aa911e004)
```

**Author instructions**

Thanks for submitting your paper to JOSS @gabrielelubatti. **Currently, there isn't an JOSS editor assigned** to your paper.

@gabrielelubatti if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (152.8 files/s, 1375.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         1              6              0              3
-------------------------------------------------------------------------------


Statistical information for the repository '51dd164e04eac847ef2cb74f' was
gathered on 2022/01/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #4046 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 641

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (553.9 files/s, 198443.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                8            747             13           1741
Rmd                             10           1726           1518           1389
Markdown                         2             60              0            236
TeX                              1             10              0             83
-------------------------------------------------------------------------------
SUM:                            21           2543           1531           3449
-------------------------------------------------------------------------------


Statistical information for the repository '75699784801fbbd9543ce1aa' was
gathered on 2022/01/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch master

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch master. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04046/joss.04046/10.21105.joss.04046.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04046/joss.04046/10.21105.joss.04046.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @gabrielelubatti - thanks for your resubmission.  I think one issue is still packaging, with good R practices described in https://r-pkgs.org/index.html. Another is that I still see hardcoded paths in vignettes, such as line 38 in https://github.com/ScialdoneLab/MitoHEAR/blob/master/vignettes/Ludwig_et_al_example_notebook.Rmd: 
```path_to_bam_fig_2="/nas_storage/gabriele.lubatti/heteroplasmy/published_dataset/all_bam_files/"```

**Comment by gabrielelubatti** [comment]
Hello. Regarding the point (Another is that I still see hardcoded paths in vignettes, such as line 38 in [ https://github.com/ScialdoneLab/MitoHEAR/blob/master/vignettes/Ludwig_et_al_example_notebook.Rmd | https://github.com/ScialdoneLab/MitoHEAR/blob/master/vignettes/Ludwig_et_al_example_notebook.Rmd ] : 
path_to_bam_fig_2="/nas_storage/gabriele.lubatti/heteroplasmy/published_dataset/all_bam_files/"), 
this path_to_bam_fig_2 is just an example of input and running it will not affect the execution of the vignettes, because as I write immediately after in the vignette " We don't execute the function *get_raw_counts_allele* here and we directly load his output.".

**Comment by danielskatz** [comment]
ok, that's fine - I'm just scanning the repo, not actually running the notebook (or even viewing it with the right format)

**Comment by danielskatz** [comment]
👋 @gabrielelubatti - I'm going to ask JOSS editors to look at this submission before we decide to review it, based on the packaging issue.  We should be able to decide in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by arfon** [comment]
@gabrielelubatti – many thanks for your submission to JOSS. After a review by our editorial team, this submission has been considered not eligible for review in JOSS.

In particular:

- The packaging of this software looks incomplete. The DESCRIPTION file of the R package still has the text from the template, and the installation instructions look unnecessarily complicated.
- All the R scripts appear duplicated (in the R/ and vignettes/ directories).
- There is commented out code in lots of places, the style is inconsistent and does not follow best practices for readability.

While some modifications are expected as part of a JOSS review, this submission simply doesn't meet a reasonable level of quality to be reasonably sent out for review at JOSS.

We would encourage you to consult resources such as http://adv-r.had.co.nz/Style.html and https://docs.fedoraproject.org/en-US/packaging-guidelines/R/ to improve the presentation of your software and its usability for future users.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
