### ISSUE TITLE
[PRE REVIEW]: visxhclust: An R Shiny package for visual exploration of hierarchical clustering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4047]
**Submitting author:** @rhenkin (<a href="http://orcid.org/0000-0002-5511-5230">Rafael Henkin</a>)
**Repository:** <a href="https://github.com/rhenkin/visxhclust" target ="_blank">https://github.com/rhenkin/visxhclust</a>
**Version:** 1.0.0
**Editor:** @osorensen
**Reviewers:** @jonjoncardoso, @wiljnich
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/bba2b08ac88581cfd5cf446686183536/status.svg)](https://joss.theoj.org/papers/bba2b08ac88581cfd5cf446686183536)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bba2b08ac88581cfd5cf446686183536"><img src="https://joss.theoj.org/papers/bba2b08ac88581cfd5cf446686183536/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bba2b08ac88581cfd5cf446686183536/status.svg)](https://joss.theoj.org/papers/bba2b08ac88581cfd5cf446686183536)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rhenkin. **Currently, there isn't an JOSS editor assigned** to your paper.

@rhenkin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4047 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (1072.5 files/s, 137142.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            42           1950            523           5693
R                               27            183            611           1769
Markdown                        14            160              0            611
CSS                              5             99             60            432
JavaScript                       5             68             39            290
Rmd                              4             62            116             60
YAML                             2              8              2             39
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           100           2530           1352           8905
-------------------------------------------------------------------------------


Statistical information for the repository '34e4d4334e770a6728620ce0' was
gathered on 2022/01/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Rafael Henkin                    4           538              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Rafael Henkin               538          100.0          0.8               11.52
```

**Comment by danielskatz** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv428 is OK
- 10.1007/978-3-540-70956-5_7 is OK
- 10.1111/1467-9868.00293 is OK
- 10.1093/nar/gkv468 is OK

MISSING DOIs

- 10.1093/bioinformatics/btw313 may be a valid DOI for title: Complex heatmaps reveal patterns and correlations in multidimensional genomic data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04047/joss.04047/10.21105.joss.04047.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04047/joss.04047/10.21105.joss.04047.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@rhenkin - thanks for your submission.  I'll look for an editor next.

In addition, you could work on the possibly missing DOI that whedon suggests, but note that this may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references from branch paper` to check again, and the command `@whedon generate pdf from branch paper` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @osorensen - are you able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @osorensen as editor

**Comment by whedon** [comment]
@osorensen has been invited to edit this submission.

**Comment by rhenkin** [comment]
> @rhenkin - thanks for your submission. I'll look for an editor next.
> 
> In addition, you could work on the possibly missing DOI that whedon suggests, but note that this may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references from branch paper` to check again, and the command `@whedon generate pdf from branch paper` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

Thanks, I will look into that one

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04047/joss.04047/10.21105.joss.04047.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04047/joss.04047/10.21105.joss.04047.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@jonjoncardoso @gagolews; would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by gagolews** [comment]
Apologies, I cannot handle a review for you this time; I have a dozen or so reviews pending ++ editorial work.
Cheers, Marek

**Comment by osorensen** [comment]
That's ok @gagolews. Thanks for your quick response

**Comment by jonjoncardoso** [comment]
> @jonjoncardoso @gagolews; would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Hi @osorensen , I'm happy to carry a review of this submission

**Comment by osorensen** [comment]
@whedon add @jonjoncardoso as reviewer

**Comment by whedon** [comment]
OK, @jonjoncardoso is now a reviewer

**Comment by adithirgis** [comment]
Thanks for reaching out! I'm afraid I won't have time in the upcoming months. Sorry. Thanks!

**Comment by osorensen** [comment]
Ok, @adithirgis, thanks for responding quickly!

**Comment by osorensen** [comment]
@wiljnich; would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by wiljnich** [comment]
@osorensen Yes, I am able and willing to review this submission.

**Comment by osorensen** [comment]
@whedon add @wiljnich as reviewer

**Comment by whedon** [comment]
OK, @wiljnich is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4074.
