### ISSUE TITLE
[PRE REVIEW]: VPsearch: fast exact sequence similarity search for genomic sequences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4048]
**Submitting author:** @jvkersch (<a href="http://orcid.org/0000-0002-5813-5659">Joris Vankerschaver</a>)
**Repository:** https://github.com/enthought/vpsearch
**Branch with paper.md** (empty if default branch): 
**Version:** 0.2.0
**Editor:** @lpantano
**Reviewers:** @tamarahadz, @sdhutchins
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6fa23d3972137c1395e59a53466fbe50/status.svg)](https://joss.theoj.org/papers/6fa23d3972137c1395e59a53466fbe50)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6fa23d3972137c1395e59a53466fbe50"><img src="https://joss.theoj.org/papers/6fa23d3972137c1395e59a53466fbe50/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6fa23d3972137c1395e59a53466fbe50/status.svg)](https://joss.theoj.org/papers/6fa23d3972137c1395e59a53466fbe50)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jvkersch. **Currently, there isn't an JOSS editor assigned** to your paper.

@jvkersch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 957

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S0022-2836(05)80360-2 is OK
- 10.1016/0020-0190(91)90074-R is OK
- 10.1128/AEM.00062-07 is OK
- 10.1128/AEM.01043-13 is OK
- 10.1093/nar/gks1219 is OK
- 10.1038/nmeth.3869 is OK
- 10.1186/s12859-016-0930-z is OK
- 10.1002/0471250953.bi0309s53 is OK
- 10.1146/annurev-biodatasci-072018-021156 is OK
- 10.1109/MCSE.2010.118 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1145/313559.313789 is INVALID
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (609.3 files/s, 73570.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Cython                           2            124             78            628
JSON                             2              0              0            300
Markdown                         2             55              0            283
Python                           5             99             80            277
TeX                              1             10              0            156
YAML                             3             12              0             75
C/C++ Header                     1             16              9             53
Dockerfile                       1              4              0             11
Bourne Shell                     1              4              5              8
TOML                             1              0              0              7
-------------------------------------------------------------------------------
SUM:                            19            324            172           1798
-------------------------------------------------------------------------------


Statistical information for the repository '815e7125c936ba8cf4160cc8' was
gathered on 2022/01/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Joris Vankerschaver             20           368             71           61.66
KERNS11                          1             7              3            1.40
Peter Zahemszky                  5           149             14           22.89
Robert Kern                      2            99              1           14.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Joris Vankerschaver         323           87.8         12.8                6.81
Peter Zahemszky             132           88.6          0.0               15.15
Robert Kern                  79           79.8          0.0                5.06
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04048/joss.04048/10.21105.joss.04048.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04048/joss.04048/10.21105.joss.04048.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@jvkersch - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOI that whedon suggests, but note that this may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by jvkersch** [comment]
@danielskatz Thank you for your message. I hope that the tool passes muster, even if it is at the lower end of LOC. It is a full fledged replacement for industry-standard tools after all. 

Regarding the DOI, I found the paper in the [ACM digital library](https://dl.acm.org/doi/10.5555/313559.313789) with another DOI ... which is also invalid. I've contacted the ACM digital library, let's see what they suggest.

**Comment by arfon** [comment]
@whedon invite @lpantano as editor

:wave: @lpantano – would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by lpantano** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@whedon assign @tamarahadz as reviewer

**Comment by whedon** [comment]
OK, @tamarahadz is now a reviewer

**Comment by lpantano** [comment]
Hi @brentp, would you be interested on reviewing this tool? or know somebody who could help with this? Thanks!

**Comment by brentp** [comment]
It's a bit outside my area. Maybe @rob-p or @BenLangmead would have a better idea?

**Comment by jvkersch** [comment]
@lpantano Thanks for the continued effort in dealing with the paper, I really appreciate it. Please let me know if there's anything I can do to facilitate the reviewing process.

Regarding the incorrect DOI that was pointed out above: I actually contacted both ACM and SIAM and while both were really responsive, there's not much they can do at the moment. Apparently it's not clear who has the responsibility for that volume of proceedings, and it doesn't look likely this will be fixed. I would propose just removing the offending DOI.

**Comment by lpantano** [comment]
Hi @jvkersch, still trying to look for another reviewer. Could you go over the possible reviewers file and see if anyone there could fit for this tool? Thanks

**Comment by lpantano** [comment]
Hi @sdhutchins, would you like to review this tool? thanks!

**Comment by sdhutchins** [comment]
Hey, @lpantano! I'm open to reviewing it.

**Comment by lpantano** [comment]
@editorialbot add @sdhutchins as reviewer

**Comment by lpantano** [comment]
Thank you so much! I am starting the review now!

**Comment by lpantano** [comment]
@editorialbot start review
