### ISSUE TITLE
[PRE REVIEW]: Hyper2D: a finite-volume solver for hyperbolic PDEs and hypersonic flows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4049]
**Submitting author:** @sbocce (<a href="http://orcid.org/0000-0003-2276-9606">Stefano Boccelli</a>)
**Repository:** <a href="https://github.com/sbocce/hyper2D/" target ="_blank">https://github.com/sbocce/hyper2D/</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1cbe2d133f3707dae6ecd1755d176737/status.svg)](https://joss.theoj.org/papers/1cbe2d133f3707dae6ecd1755d176737)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1cbe2d133f3707dae6ecd1755d176737"><img src="https://joss.theoj.org/papers/1cbe2d133f3707dae6ecd1755d176737/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1cbe2d133f3707dae6ecd1755d176737/status.svg)](https://joss.theoj.org/papers/1cbe2d133f3707dae6ecd1755d176737)
```

**Author instructions**

Thanks for submitting your paper to JOSS @sbocce. **Currently, there isn't an JOSS editor assigned** to your paper.

@sbocce if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 828

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (404.3 files/s, 42316.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                           5            203            254            391
make                             5             76             43            112
Markdown                         1             28              0            103
TeX                              1              6              0             40
-------------------------------------------------------------------------------
SUM:                            12            313            297            646
-------------------------------------------------------------------------------


Statistical information for the repository '58522c33394097adf96f126a' was
gathered on 2022/01/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1063/5.0006258 may be a valid DOI for title: Collisionless ion modeling in Hall thrusters: Analytical axial velocity distribution function and heat flux closures

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04049/joss.04049/10.21105.joss.04049.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04049/joss.04049/10.21105.joss.04049.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@sbocce - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOI that whedon suggests, but note that this may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by sbocce** [comment]
@danielskatz thank you for your message and for considering my submission. I have the impression that whedon may have picked only one single directory for counting the code statistics. It reports 646 lines of code, but the full software is much larger. Maybe it does not recognize the directory structure. Let me know if you need me to modify anything.

I'll be fixing the DOI in the meanwhile. Thank you again

**Comment by danielskatz** [comment]
It appears our check may not be recognizing/counting lines in .f03 files.  @arfon, any thoughts here?

**Comment by sbocce** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/5.0006258 is OK
- 10.1111/j.1365-2966.2005.09546.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sbocce** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04049/joss.04049/10.21105.joss.04049.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04049/joss.04049/10.21105.joss.04049.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
Given the problem with our LOC counting (missing .f03 files), I'm going to take this back out of scope review and look for an editor

**Comment by danielskatz** [comment]
👋 @jedbrown - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by jedbrown** [comment]
We could switch from `cloc` to `tokei`. It does lots of things well, but misclassifies the Matlab source.
```console
$ tokei
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 FORTRAN Modern         62        10104         6403          480         3221
 Makefile               12          549          266          102          181
 Markdown                1          131            0          103           28
 Objective-C             6          898          682            0          216
 Plain Text              1            9            0            7            2
===============================================================================
 Total                  82        11691         7351          692         3648
===============================================================================
```

**Comment by danielskatz** [comment]
Thanks @jedbrown - ok, let's go back to the scope query, but this time for subject, not for effort

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by sbocce** [comment]
@jedbrown thanks a lot for your message. I'll reply by points

- Documentation: I thought the wiki was sufficient, since the code is pretty simple. Should I improve this further? Also, are tests a strict requirement? 

- Statement of need -> thanks, I'll fix that.

- I can confirm that we never submitted to SoftwareX. Initially, I was targeting SoftwareX, and just wrote this in the README, for the time being. Then I found that SoftwareX charges 600 USD (which I'm not giving to Elsevier), I looked for an alternative and found JOSS. Apparently, I forgot to update the README.

- LeVeque -> thanks, I'll fix that

Regarding the scope, JOSE is perfectly fine for me. Let me know what you think is best. In case, should I withdraw the submission and create a new one?

**Comment by danielskatz** [comment]
If you think JOSE is better, then yes, withdraw here and submit there.  I can take care of the withdrawal here if you confirm this is your intent

**Comment by sbocce** [comment]
@danielskatz Thanks. I'll double check the scope and requirements of JOSE and will confirm you ASAP

**Comment by sbocce** [comment]
@danielskatz OK, I can confirm that JOSE is better for my needs, and I will resubmit there. If you could withdraw the paper for me, that would surely help. Thank you again for your time!

**Comment by danielskatz** [comment]
Great, thanks - good luck in JOSE

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
