### ISSUE TITLE
[PRE REVIEW]: ENASearch: A Python library for interacting with ENA's API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#405]
**Submitting author:** @bebatut (<a href="http://orcid.org/0000-0001-9852-1987">Bérénice Batut</a>)
**Repository:** <a href="https://github.com/bebatut/enasearch" target ="_blank">https://github.com/bebatut/enasearch</a>
**Version:** 0.1.1
**Editor:** @brainstorm
**Reviewer:** @vals

**Author instructions**

Thanks for submitting your paper to JOSS @bebatut. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bebatut if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@brainstorm - would you be willing to edit this submission for JOSS?

**Comment by brainstorm** [comment]
Sure, happy to @arfon!

**Comment by arfon** [comment]
Great. Thanks!

**Comment by arfon** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by brainstorm** [comment]
@vals, would you like to be a reviewer for this ENA package?: https://github.com/bebatut/enasearch

**Comment by vals** [comment]
Hey @brainstorm!

Hm maybe.. Do you have some general reviewer instructions as well as deadlines somewhere?

**Comment by brainstorm** [comment]
@vals The reviews are really straightforward and fast. The ones I've done myself took between 10 and 20 minutes since JOSS is a highly automated github journal.

The checklist you'll be presented with when I assign you as a reviewer is very easy to go through as you review the software:

http://joss.theoj.org/about#reviewer_guidelines

No deadlines, just proceed at your own pace, but don't take too long, please. Are you in for it? ;)

**Comment by vals** [comment]
Sure, sounds all right.

**Comment by brainstorm** [comment]
@whedon assign @vals as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vals

**Comment by brainstorm** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/418. Feel free to close this issue now!
