### ISSUE TITLE
[PRE REVIEW]: Vectorized capsid rendering in the browser with capsid.js

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4054]
**Submitting author:** @dnanto (<a href="http://orcid.org/0000-0002-6123-2441">Daniel Negrón</a>)
**Repository:** <a href="https://github.com/dnanto/capsid" target ="_blank">https://github.com/dnanto/capsid</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4f7f40fb20dae76c955bdbf750da2d7a/status.svg)](https://joss.theoj.org/papers/4f7f40fb20dae76c955bdbf750da2d7a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4f7f40fb20dae76c955bdbf750da2d7a"><img src="https://joss.theoj.org/papers/4f7f40fb20dae76c955bdbf750da2d7a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4f7f40fb20dae76c955bdbf750da2d7a/status.svg)](https://joss.theoj.org/papers/4f7f40fb20dae76c955bdbf750da2d7a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dnanto. **Currently, there isn't an JOSS editor assigned** to your paper.

@dnanto if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 901

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gkq901 is OK
- 10.1128/JVI.75.24.11943-11947.2001 is OK
- 10.1093/nar/gkn840 is OK
- 10.1101/sqb.1962.027.001.005 is OK
- 10.1038/s41467-019-12367-3 is OK
- 10.1016/j.bpj.2010.02.051 is OK
- 10.1016/0042-6822(65)90319-3 is OK
- 10.1371/journal.pone.0261269 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (252.4 files/s, 104392.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             2              0              0           6929
JavaScript                       4             88            247           1089
HTML                             2             82              0            517
XML                              1              0              2            441
Markdown                         4             74              0            179
TeX                              1              1              0            140
CSS                              1             12              0             67
YAML                             2              1              8             44
SVG                              7              0              0              7
-------------------------------------------------------------------------------
SUM:                            24            258            257           9413
-------------------------------------------------------------------------------


Statistical information for the repository '410b878a69dbf62a96925ae5' was
gathered on 2022/01/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
dnanto                          63          3528           2104          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
dnanto                     1424           40.4          5.8               17.42
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04054/joss.04054/10.21105.joss.04054.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04054/joss.04054/10.21105.joss.04054.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@dnanto - thanks for your submission. I'm going to ask JOSS editors to review it to see if it is [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) as defined by JOSS. This does not mean that it is not software that is useful in research, but just that JOSS might not consider it in scope for review as research software.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
👋 @dnanto Unfortunately, after discussion among the JOSS editors, we have decided that this submission does not meet the [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) criterion for review by JOSS, since the software package focuses exclusively on visualization. (Again, this is not a statement that your software is not useful!)

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by dnanto** [comment]
Thanks for taking the time to review the paper!
