### ISSUE TITLE
[PRE REVIEW]: title: 'terrainr: An R package for creating immersive virtual environments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4055]
**Submitting author:** @mikemahoney218 (<a href="http://orcid.org/0000-0003-2402-304X">Michael Mahoney</a>)
**Repository:** <a href="https://github.com/ropensci/terrainr" target ="_blank">https://github.com/ropensci/terrainr</a>
**Version:** v0.5.1
**Editor:** @danielskatz
**Reviewers:** @danielskatz
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e6ae4bea1e15438600e3ba709a75c11b/status.svg)](https://joss.theoj.org/papers/e6ae4bea1e15438600e3ba709a75c11b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e6ae4bea1e15438600e3ba709a75c11b"><img src="https://joss.theoj.org/papers/e6ae4bea1e15438600e3ba709a75c11b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e6ae4bea1e15438600e3ba709a75c11b/status.svg)](https://joss.theoj.org/papers/e6ae4bea1e15438600e3ba709a75c11b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mikemahoney218. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikemahoney218 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (908.1 files/s, 92799.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               36            320            843           2574
Markdown                         7             88              0            507
YAML                            10             64              1            474
JSON                             1              0              0            292
Rmd                              3            134            332            163
C#                               1             19              1            115
-------------------------------------------------------------------------------
SUM:                            58            625           1177           4125
-------------------------------------------------------------------------------


Statistical information for the repository '2bdfd4730f316c890d88d95e' was
gathered on 2022/01/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mike Mahoney                     4           406            406          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4055 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by mikemahoney218** [comment]
Apologies for the paper not rendering -- the paper lives in https://github.com/ropensci/terrainr/tree/paper which I could specify in the pre-submission rendering service, but I couldn't figure out how to provide the branch to the actual submission workflow.

**Comment by danielskatz** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by danielskatz** [comment]
@whedon generated pdf from branch paper

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/13658816.2010.510800 is OK
- 10.1002/0471448354.ch1 is OK
- 10.14778/2824032.2824122 is OK
- 10.1137/1.9781611972757.24 is OK
- 10.1890/120103 is OK
- 10.1175/BAMS-D-15-00324.1 is OK
- 10.1177/1478077119849659 is OK
- 10.32614/RJ-2018-009 is OK
- 10.1080/1523908X.2020.1798751 is OK
- 10.1080/09654313.2012.722943 is OK
- 10.1016/j.landurbplan.2019.103635 is OK
- 10.1080/1523908032000121193 is OK
- 10.1016/S0169-2046(02)00245-1 is OK
- 10.1109/GEOINFORMATICS.2010.5567608 is OK
- 10.32614/RJ-2016-061 is OK
- 10.5194/isprs-archives-XLII-4-397-2018 is OK
- 10.1080/17538947.2018.1501106 is OK
- 10.1016/j.futures.2010.04.006 is OK
- 10.1007/s10980-012-9716-5 is OK
- 10.1016/j.compenvurbsys.2004.05.004 is OK
- 10.1080/02513625.2006.10556960 is OK
- 10.1007/BF03545339 is OK

MISSING DOIs

- 10.5040/9781350983816 may be a valid DOI for title: Unity
- 10.1038/sdata.2018.40 may be a valid DOI for title: A suite of global, cross-scale topographic variables for environmental and biodiversity modeling
- 10.21236/ad0289565 may be a valid DOI for title: Augmenting human intellect: A conceptual framework
- 10.1007/s42489-019-00003-5 may be a valid DOI for title: The Sound of Being There: Audiovisual Cartography with Immersive Virtual Environments
- 10.1016/j.jeem.2008.08.002 may be a valid DOI for title: Virtual experiments and environmental policy
- 10.1007/s42489-020-00069-6 may be a valid DOI for title: Creating Immersive Virtual Environments Based on Open Geospatial Data and Game Engines
- 10.1016/j.jeem.2008.08.002 may be a valid DOI for title: Virtual experiments and environmental policy

INVALID DOIs

- https://doi.org/10.1016/S0169-2046(01)00123-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/B978-008044531-1/50422-X is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0169-2046(01)00137-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0169-2046(01)00132-3 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.compenvurbsys.2005.07.002 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.envsci.2005.08.002 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.compenvurbsys.2004.05.002 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.gloenvcha.2009.04.002 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cities.2019.102559 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04055/joss.04055/10.21105.joss.04055.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04055/joss.04055/10.21105.joss.04055.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @mikemahoney218 - if you can remove the entries in the .bib file that aren't used, that will simply our checks. Whedon checks everything in that file, whether it is used in the paper or not, unfortunately.

**Comment by danielskatz** [comment]
You can use the commands I gave to check this. note that whedon commands must be the first thing in a comment

**Comment by danielskatz** [comment]
👋 @kbarnhart - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by mikemahoney218** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/17538947.2018.1501106 is OK

MISSING DOIs

- 10.5040/9781350983816 may be a valid DOI for title: Unity
- 10.1007/s42489-020-00069-6 may be a valid DOI for title: Creating Immersive Virtual Environments Based on Open Geospatial Data and Game Engines

INVALID DOIs

- None
```

**Comment by mikemahoney218** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s42489-020-00069-6 is OK
- 10.1080/17538947.2018.1501106 is OK

MISSING DOIs

- 10.5040/9781350983816 may be a valid DOI for title: Unity

INVALID DOIs

- None
```

**Comment by mikemahoney218** [comment]
I believe that should address the reference check! Let me know if I missed anything.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04055/joss.04055/10.21105.joss.04055.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04055/joss.04055/10.21105.joss.04055.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by danielskatz** [comment]
Sorry, I missed the rOpenSci part - given that, you don't need to do anything, I will take care of it.

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
Link to rOpenSci review: https://github.com/ropensci/software-review/issues/416

**Comment by kbarnhart** [comment]
Sounds good @danielskatz, thanks!

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, @danielskatz is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4060.
