### ISSUE TITLE
[PRE REVIEW]: SEEDPOD Ground Risk: A Python application and library for Uncrewed Aerial Systems ground risk analysis and risk-aware path finding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4058]
**Submitting author:** @aliaksei135 (<a href="http://orcid.org/0000-0003-0023-0300">Aliaksei Pilko</a>)
**Repository:** <a href="https://github.com/aliaksei135/seedpod_ground_risk/" target ="_blank">https://github.com/aliaksei135/seedpod_ground_risk/</a>
**Version:** v0.15.0
**Editor:** @danielskatz
**Reviewers:** @kylebeggs, @AustinTSchaffer
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b26d16f767693e3905b645aae9b72834/status.svg)](https://joss.theoj.org/papers/b26d16f767693e3905b645aae9b72834)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b26d16f767693e3905b645aae9b72834"><img src="https://joss.theoj.org/papers/b26d16f767693e3905b645aae9b72834/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b26d16f767693e3905b645aae9b72834/status.svg)](https://joss.theoj.org/papers/b26d16f767693e3905b645aae9b72834)
```

**Author instructions**

Thanks for submitting your paper to JOSS @aliaksei135. **Currently, there isn't an JOSS editor assigned** to your paper.

@aliaksei135 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/DASC.2017.8102039 is OK
- 10.1109/ICUAS48674.2020.9213990 is OK
- 10.2514/6.2017-3273 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 713

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.51 s (184.8 files/s, 18239.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          70           1240            725           5032
JSON                             5              0              0           1344
Qt                               3              0              0            465
Markdown                         4             66              0            177
YAML                             3             11             12             81
XML                              6              0              0             44
QML                              1              9              0             34
TeX                              1              2              0             31
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            94           1328            737           7214
-------------------------------------------------------------------------------


Statistical information for the repository '9b2ba87a17b2c54baafe1cfa' was
gathered on 2022/01/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aliaksei Pilko                 391         12386           5139           92.94
Zach Tait                        8           794            411            6.39
Zach10a                          5            92             35            0.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aliaksei Pilko             6154           49.7          8.3                7.57
Zach Tait                   843          106.2          3.3                3.44
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04058/joss.04058/10.21105.joss.04058.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04058/joss.04058/10.21105.joss.04058.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @aliaksei135 - I'll be the editor for your submission.  The next step is to find at least 2 reviewers. If you have any suggestions for potential reviewers, please mention them here in this thread (without tagging them with an @). Note that [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
Also, is this software Windows only?

**Comment by aliaksei135** [comment]
Hi, thanks!

The software has an installer that is Windows only, however the wheels build for Linux and Windows. We have CI tests for both platforms.

I'll have a look through the list and find reviewers

**Comment by aliaksei135** [comment]
Looking through some of the list, the following seem suitable:

- dionhaefner - 1 active
- helgee - 0 active
- Garethwpeters - 0 active
- nickbearman - 0 active
- kylebeggs - 0 active
- AustinTSchaffer - 1 active

Hopefully at least 2 will be available and willing.

**Comment by danielskatz** [comment]
👋 @helgee & @Garethwpeters - Would one or both of you be willing to review this JOSS submission?

**Comment by nickbearman** [comment]
@danielskatz I can't look at the Python library (I need to remove that from my profile) so you still want me to see if I can review this paper? Thanks.

**Comment by danielskatz** [comment]
@nickbearman - please take a look and see what you think.

**Comment by kylebeggs** [comment]
@danielskatz  I'd be willing.

**Comment by danielskatz** [comment]
@kylebeggs - thanks very much - I'll assign you now, but we won't start the review until we find a second reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @kylebeggs as reviewer

**Comment by danielskatz** [comment]
👋 @dionhaefner & @AustinTSchaffer - It looks like you are currently reviewing JOSS submissions, but in case one of you is able to take on one more, please let me know if you can review this one.

**Comment by dionhaefner** [comment]
Sorry, my pipeline is full at the moment.

**Comment by AustinTSchaffer** [comment]
I have 2 others, but seeing that this one is Python, I'd love to.

**Comment by danielskatz** [comment]
Thanks very much @AustinTSchaffer - I'll add you and we'll get started

**Comment by danielskatz** [comment]
@whedon add @AustinTSchaffer as reviewer

**Comment by whedon** [comment]
OK, @AustinTSchaffer is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4079.
