### ISSUE TITLE
[PRE REVIEW]: BSBT: A package for analysing spatial comparative judgement data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4059]
**Submitting author:** @rowlandseymour (<a href="http://orcid.org/0000-0002-8739-3921">Rowland Seymour</a>)
**Repository:** <a href="https://github.com/rowlandseymour/BSBT" target ="_blank">https://github.com/rowlandseymour/BSBT</a>
**Version:** v1.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f0b6e939cb15f50201c615e82d8d3a35/status.svg)](https://joss.theoj.org/papers/f0b6e939cb15f50201c615e82d8d3a35)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f0b6e939cb15f50201c615e82d8d3a35"><img src="https://joss.theoj.org/papers/f0b6e939cb15f50201c615e82d8d3a35/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f0b6e939cb15f50201c615e82d8d3a35/status.svg)](https://joss.theoj.org/papers/f0b6e939cb15f50201c615e82d8d3a35)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rowlandseymour. **Currently, there isn't an JOSS editor assigned** to your paper.

@rowlandseymour if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4059 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/BigData.2018.8622268 is OK
- 10.18637/jss.v048.i09 is OK
- 10.2307/2334029 is OK
- 10.18637/jss.v048.i09 is OK
- 10.1111/j.1467-9876.2012.01046.x is OK
- 10.1073/pnas.1813720116 is OK
- 10.1080/10618600.2012.638220 is OK
- 10.1111/rssc.12532 is OK
- 10.3758/s13428-021-01714-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04059/joss.04059/10.21105.joss.04059.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04059/joss.04059/10.21105.joss.04059.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @rowlandseymour - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by kyleniemeyer** [comment]
👋 @rowlandseymour I'm sorry to say that after discussion among the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS, due to its small size.

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
