### ISSUE TITLE
[PRE REVIEW]: MatDL: A Lightweight Deep Learning Library in MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#406]
**Submitting author:** @haythamfayek (<a href="http://orcid.org/0000-0002-1840-7605">Haytham Fayek</a>)
**Repository:** <a href="https://github.com/haythamfayek/MatDL" target ="_blank">https://github.com/haythamfayek/MatDL</a>
**Version:** v0.7.0
**Editor:** @cmadan
**Reviewer:** @nirum

**Author instructions**

Thanks for submitting your paper to JOSS @haythamfayek. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@haythamfayek if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@whedon assign @cmadan as editor

**Comment by whedon** [comment]
OK, the editor is @cmadan

**Comment by cMadan** [comment]
@haythamfayek, this looks like a great submission! Do you have any suggestions for reviewers?

**Comment by haythamfayek** [comment]
Thanks @cMadan! From the list of [reviewers](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv), how about @Kevin-Mattheus-Moerman, @nirum, or @sealhuang?

**Comment by sealhuang** [comment]
@haythamfayek Thank you for mentioning me. I am not very familiar with the deep learning, so if that's not a problem I can do the review. And if someone with more DL experience would like to handle this review, I think it may be more helpful for this software.

**Comment by nirum** [comment]
This looks interesting! I'm happy to review it

**Comment by haythamfayek** [comment]
Thanks @nirum & @sealhuang!

**Comment by cMadan** [comment]
@sealhuang, no problem. I'm sure a future submission will be more suited to your background.

@nirum, thanks for volunteering! I'll assign you as the reviewer and go ahead and start the review process.

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon assign @nirum as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nirum

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/413. Feel free to close this issue now!
