### ISSUE TITLE
[PRE REVIEW]: PyPVRPM: Photovoltaic Reliability and Performance Model in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4063]
**Submitting author:** @brandons209 (<a href="http://orcid.org/0000-0001-8278-7158">Brandon Silva</a>)
**Repository:** <a href="https://github.com/FSEC-Photovoltaics/pvrpm-lcoe" target ="_blank">https://github.com/FSEC-Photovoltaics/pvrpm-lcoe</a>
**Version:** v1.6.0
**Editor:** @jgostick
**Reviewers:** @SarthakJariwala
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/359bb7f809f245df315e45d3e7bb9213/status.svg)](https://joss.theoj.org/papers/359bb7f809f245df315e45d3e7bb9213)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/359bb7f809f245df315e45d3e7bb9213"><img src="https://joss.theoj.org/papers/359bb7f809f245df315e45d3e7bb9213/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/359bb7f809f245df315e45d3e7bb9213/status.svg)](https://joss.theoj.org/papers/359bb7f809f245df315e45d3e7bb9213)
```

**Author instructions**

Thanks for submitting your paper to JOSS @brandons209. **Currently, there isn't an JOSS editor assigned** to your paper.

@brandons209 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "," (COMMA) [#<BibTeX::Bibliography data=[5]>, "@", #<BibTeX::Entry >, {:title=>["Validation of PV-RPM Code in the System Advisor Model."], :author=>["Geoffrey Klise and Olga Lavrova and Janine Freeman"], :abstractnote=>["This paper describes efforts made by Sandia National Laboratories (SNL) and the National Renewable Energy Laboratory (NREL) to validate the SNL developed PV Reliability Performance Model (PV - RPM) algorithm as implemented in the NREL System Advisor Model (SAM). The PV - RPM model is a library of functions that estimates component failure and repair in a photovoltaic system over a desired simulation period. The failure and repair distributions in this paper are probabilistic representations of component failure and repair based on data collected by SNL for a PV power plant operating in Arizona. The validation effort focuses on whether the failure and repair dist ributions used in the SAM implementation result in estimated failures that match the expected failures developed in the proof - of - concept implementation. Results indicate that the SAM implementation of PV - RPM provides the same results as the proof - of - concep t implementation, indicating the algorithms were reproduced successfully."], :doi=>["10.2172/1367461"], :url=>["https://www.osti.gov/biblio/1367461"], :journal=>[""]}, ",", "number", "="]

**Comment by whedon** [comment]
Wordcount for `paper.md` is 728

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.19 s (443.9 files/s, 190796.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2405           2473           9211
HTML                            24           3699             72           8933
SVG                              1              0              0           2671
Python                          16            746            840           2645
CSS                              4            191             35            757
YAML                             6            113            116            683
JSON                             5              0              0            496
reStructuredText                11            179            312            180
TeX                              1              8              0             83
Markdown                         2             16              0             42
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            86           7369           3856          25736
-------------------------------------------------------------------------------


Statistical information for the repository 'b9a1cfc611b678191da3dd81' was
gathered on 2022/01/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brandon                         25          2729           1089           17.80
Brandon Silva                    9         15281            152           71.95
brandons209                     15          1876            324           10.26

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brandon Silva             18320          119.9          2.9               16.18
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04063/joss.04063/10.21105.joss.04063.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04063/joss.04063/10.21105.joss.04063.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @brandons209 - I've suggested a bunch of changes in  https://github.com/FSEC-Photovoltaics/pvrpm-lcoe/pull/26 to fix the bib errors

**Comment by danielskatz** [comment]
👋 @jgostick - are you able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by brandons209** [comment]
> wave @brandons209 - I've suggested a bunch of changes in [FSEC-Photovoltaics/pvrpm-lcoe#26](https://github.com/FSEC-Photovoltaics/pvrpm-lcoe/pull/26) to fix the bib errors

Thank you! The paper compiled fine so I didn't realize there were errors. I'll merge the changes.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2172/1367461 is OK
- 10.1109/PVSC.2018.8547454 is OK
- 10.1109/PVSC.2017.8366397 is OK
- 10.2172/1761998 is OK

MISSING DOIs

- 10.1109/pvsc.2018.8547454 may be a valid DOI for title: Evaluating Energy Impacts and Costs from PV Component Failures
- 10.2172/1088066 may be a valid DOI for title: The Comparison of Three Photovoltaic System Designs Using the Photovoltaic Reliability and Performance Model (PVRPM)

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
While things get started, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by brandons209** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2172/1088066 is OK
- 10.2172/1367461 is OK
- 10.1109/PVSC.2018.8547454 is OK
- 10.1109/PVSC.2017.8366397 is OK
- 10.2172/1761998 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by brandons209** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04063/joss.04063/10.21105.joss.04063.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04063/joss.04063/10.21105.joss.04063.pdf) :page_facing_up: :point_left:

**Comment by jgostick** [comment]
@sevberg, I tried to email you but your juelich address listed in our reviewer database is bouncing back.  I'm hoping you receive this github ping.  You expertise would seem very well suited to review this package.  Could you let me know if you are still willing and able to do this?  Thanks!

**Comment by jgostick** [comment]
@whedon add @SarthakJariwala as reviewer

**Comment by whedon** [comment]
OK, @SarthakJariwala is now a reviewer

**Comment by jgostick** [comment]
I'm going to start the reivew despite having only one reviewer for now.  I will add the second later.

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4093.

**Comment by jgostick** [comment]
Hi @brandons209 can suggest a few names how may be able to review this?  My search so far have yielded a pretty small and interconnected group of people.

**Comment by brandons209** [comment]
> Hi @brandons209 can suggest a few names how may be able to review this? My search so far have yielded a pretty small and interconnected group of people.

Hello! I am not sure what you are asking. Are you asking me to recommend some people outside of JOSS to help review this? I can recommend some people from NREL if that's the case.

**Comment by jgostick** [comment]
Not to worry, I found someone.
