### ISSUE TITLE
[PRE REVIEW]: LoopScheduler: A customizable and extensible framework for game loop architecture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4064]
**Submitting author:** @pragma-once (<a href="http://orcid.org/0000-0002-4951-0250">Masiha Majidzadeh</a>)
**Repository:** <a href="https://github.com/LoopScheduler/LoopScheduler" target ="_blank">https://github.com/LoopScheduler/LoopScheduler</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f7a0ec9d18c1e33e59e8bbdcfceb1a76/status.svg)](https://joss.theoj.org/papers/f7a0ec9d18c1e33e59e8bbdcfceb1a76)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f7a0ec9d18c1e33e59e8bbdcfceb1a76"><img src="https://joss.theoj.org/papers/f7a0ec9d18c1e33e59e8bbdcfceb1a76/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f7a0ec9d18c1e33e59e8bbdcfceb1a76/status.svg)](https://joss.theoj.org/papers/f7a0ec9d18c1e33e59e8bbdcfceb1a76)
```

**Author instructions**

Thanks for submitting your paper to JOSS @pragma-once. **Currently, there isn't an JOSS editor assigned** to your paper.

@pragma-once if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 987

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (169.5 files/s, 20467.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             18            219            194           2253
SVG                              1              1              1            573
C/C++ Header                    11             61            421            356
Markdown                         2             74              0            246
Python                           2             26             15             81
TeX                              1              3              0             35
CMake                            3             10              0             19
-------------------------------------------------------------------------------
SUM:                            38            394            631           3563
-------------------------------------------------------------------------------


Statistical information for the repository '9cae04f719d9389ae5003f2f' was
gathered on 2022/01/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Majidzadeh                     121          4955           1329          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Majidzadeh                 3626           73.2          2.7               41.20
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1145/1394021.1394035 may be a valid DOI for title: A game loop architecture for the gpu used as a math coprocessor in real-time applications
- 10.1145/1658866.1658869 may be a valid DOI for title: An adaptative game loop architecture with automatic distribution of tasks between cpu and gpu

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @pragma-once - thanks for your submission.  Can you say a few words about how this is [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) as defined by JOSS?  What kinds of researchers would cite this submission in their own papers?  This isn't clear to me in your statement of need.

**Comment by pragma-once** [comment]
Hello, thank you. I couldn't relate the research software defined by JOSS to the game related software. There has been research on game loops, and they have solved the performance issues but they are specific about the game components. This work however focuses on a general purpose approach to game loops, because not all games or game engines are designed the same way. It could be cited by researchers who work on the game development topic, like game engines.

**Comment by danielskatz** [comment]
Thanks @pragma-once - given your statements, I'm going to ask the JOSS editors to decide if this fits JOSS's scope for review.  You should get a decision in a week or two.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@pragma-once - thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission is out of scope for JOSS as we don't believe it meets our definition of [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software).

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
