### ISSUE TITLE
[PRE REVIEW]: violinplotter: R package for comparing means with violin plots

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4065]
**Submitting author:** @jeffersonfparil (<a href="http://orcid.org/0000-0002-5693-4123">Jefferson Paril</a>)
**Repository:** <a href="https://github.com/jeffersonfparil/violinplotter.git" target ="_blank">https://github.com/jeffersonfparil/violinplotter.git</a>
**Version:** v3.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8edab420766a995a6f0ee34a8c8796fb/status.svg)](https://joss.theoj.org/papers/8edab420766a995a6f0ee34a8c8796fb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8edab420766a995a6f0ee34a8c8796fb"><img src="https://joss.theoj.org/papers/8edab420766a995a6f0ee34a8c8796fb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8edab420766a995a6f0ee34a8c8796fb/status.svg)](https://joss.theoj.org/papers/8edab420766a995a6f0ee34a8c8796fb)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jeffersonfparil. **Currently, there isn't an JOSS editor assigned** to your paper.

@jeffersonfparil if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (830.4 files/s, 56690.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               10             10            389            465
Markdown                         4             26              0             96
YAML                             1              4              7             27
-------------------------------------------------------------------------------
SUM:                            15             40            396            588
-------------------------------------------------------------------------------


Statistical information for the repository '7f2b2566ae8964e128de0cdb' was
gathered on 2022/01/14.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #4065 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch JOSS-manuscript

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS-manuscript
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch JOSS-manuscript

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-0-387-32833-1_226 is OK
- 10.1007/978-1-4419-9863-7_1212 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04065/joss.04065/10.21105.joss.04065.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04065/joss.04065/10.21105.joss.04065.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @jeffersonfparil - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
👋 @jeffersonfparil - I'm sorry to say that after discussion among the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
