### ISSUE TITLE
[PRE REVIEW]: KST48: a Powerful Program for the Location of Minimum Energy Crossing Points (MECPs)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4066]
**Submitting author:** @RimoAccelerator (<a href="http://orcid.org/0000-0002-0628-8864">Yumiao Ma</a>)
**Repository:** <a href="https://github.com/RimoAccelerator/KST48/" target ="_blank">https://github.com/RimoAccelerator/KST48/</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fd6bcf61c3c6de0ac0f4b35fa08e3aaa/status.svg)](https://joss.theoj.org/papers/fd6bcf61c3c6de0ac0f4b35fa08e3aaa)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fd6bcf61c3c6de0ac0f4b35fa08e3aaa"><img src="https://joss.theoj.org/papers/fd6bcf61c3c6de0ac0f4b35fa08e3aaa/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fd6bcf61c3c6de0ac0f4b35fa08e3aaa/status.svg)](https://joss.theoj.org/papers/fd6bcf61c3c6de0ac0f4b35fa08e3aaa)
```

**Author instructions**

Thanks for submitting your paper to JOSS @RimoAccelerator. **Currently, there isn't an JOSS editor assigned** to your paper.

@RimoAccelerator if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 867

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (105.5 files/s, 29781.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1             58             53            792
Markdown                         2             39              0            124
TeX                              1              0              0             63
-------------------------------------------------------------------------------
SUM:                             4             97             53            979
-------------------------------------------------------------------------------


Statistical information for the repository '302b87b4e59573ee1a24e104' was
gathered on 2022/01/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
RimoAccelerator                  6          1226            323          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
RimoAccelerator             903           73.7          0.0                5.87
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4293421 is OK

MISSING DOIs

- 10.1016/0009-2614(94)00433-1 may be a valid DOI for title: A direct method for the location of the lowest energy point on a potential surface crossing
- 10.1007/s002140050309 may be a valid DOI for title: The singlet and triplet states of phenyl cation. A hybrid approach for locating minimum energy crossing points between non-interacting potential energy surfaces
- 10.1039/b108658h may be a valid DOI for title: Methods for optimizing large molecules. Part III. An improved algorithm for geometry optimization using direct inversion in the iterative subspace (GDIIS)
- 10.1093/imamat/6.1.76 may be a valid DOI for title: The convergence of a class of double-rank minimization algorithms 1. general considerations

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@RimoAccelerator - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
👋 @RimoAccelerator I'm sorry to say that after discussion among the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS, due to its relatively small size.

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
