### ISSUE TITLE
[PRE REVIEW]: pymdp: A Python library for active inference in discrete state spaces

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4067]
**Submitting author:** @conorheins (<a href="http://orcid.org/0000-0002-5884-7728">Conor Heins</a>)
**Repository:** <a href="https://github.com/infer-actively/pymdp" target ="_blank">https://github.com/infer-actively/pymdp</a>
**Version:** v0.0.4
**Editor:** @emdupre
**Reviewers:** @seankmartin, @patrickmineault
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a6362c8d3e0c953d8ce832664a32f66b/status.svg)](https://joss.theoj.org/papers/a6362c8d3e0c953d8ce832664a32f66b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a6362c8d3e0c953d8ce832664a32f66b"><img src="https://joss.theoj.org/papers/a6362c8d3e0c953d8ce832664a32f66b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a6362c8d3e0c953d8ce832664a32f66b/status.svg)](https://joss.theoj.org/papers/a6362c8d3e0c953d8ce832664a32f66b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @conorheins. **Currently, there isn't an JOSS editor assigned** to your paper.

@conorheins if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (484.3 files/s, 174779.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          30           1995           1963           4615
Jupyter Notebook                11              0           9723           1496
MATLAB                           9            558            790           1406
Markdown                         2             94              0            234
YAML                             2             10             10             42
reStructuredText                 8             29             40             36
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            64           2698          12534           7864
-------------------------------------------------------------------------------


Statistical information for the repository '7cedfe214e7c8c9994a0c05b' was
gathered on 2022/01/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexander Kiefer                 2             5              3            0.01
Beren                            4           193             54            0.32
Brennan Klein                    1             1              1            0.00
Conor Heins                     87          8074           2193           13.16
alec-tschantz                   55          8626           6334           19.18
arun                             3            88             73            0.21
conorheins                     237         26192          26172           67.13

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexander Kiefer              5          100.0          6.5                0.00
Beren                        13            6.7         20.0               15.38
alec-tschantz              1245           14.4         18.4               12.21
arun                         13           14.8         11.6                0.00
conorheins                 7297           27.9          7.3                9.09
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4067 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch paper_branch

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper_branch
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper_branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper_branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1371/journal.pone.0006421 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1162/neco_a_01354 is OK
- 10.1080/17588928.2015.1020053 is OK
- 10.1038/s41598-018-38246-3 is OK
- 10.1561/2200000001 is OK
- 10.1167/jov.20.4.12 is OK
- 10.1038/ncomms14218 is OK
- 10.3390/e22050552 is OK
- 10.1162/neco.1992.4.3.415 is OK
- 10.1016/j.neuroimage.2004.07.041 is OK
- 10.1080/01621459.2017.1285773 is OK
- 10.1126/science.1238406 is OK
- 10.1007/s00422-012-0512-8 is OK
- 10.1016/j.tics.2011.11.018 is OK
- 10.1162/neco_a_01357 is OK
- 10.1109/IJCNN48605.2020.9207382 is OK
- 10.1016/0166-2236(83)90190-X is OK
- 10.1523/JNEUROSCI.11-03-00641.1991 is OK
- 10.1162/NECO_a_00912 is OK
- 10.3390/e21030257 is OK
- 10.3389/frobt.2019.00020 is OK
- 10.1007/s00422-018-0785-7 is OK
- 10.1371/journal.pcbi.1007805 is OK
- 10.1109/ICASSP40776.2020.9054364 is OK
- 10.1016/B978-0-12-372560-8.X5000-1 is OK
- 10.1038/nrn2787 is OK
- 10.1016/j.jmp.2020.102447 is OK
- 10.1016/S0004-3702(98)00023-X is OK
- 10.1162/neco_a_01351 is OK
- 10.1093/cercor/bhu159 is OK
- 10.1016/j.drugalcdep.2020.108208 is OK
- 10.1503/jpn.200032 is OK
- 10.31234/osf.io/b4jm6 is OK
- 10.1016/j.neuroimage.2008.02.054 is OK
- 10.1016/j.jmp.2020.102348 is OK
- 10.1007/978-3-030-64919-7_1 is OK
- 10.1016/j.neubiorev.2016.06.022 is OK
- 10.1162/neco.1995.7.5.889 is OK
- 10.1037/13536-000 is OK
- 10.1016/j.neunet.2021.05.010 is OK
- 10.1109/LRA.2021.3090015 is OK
- 10.1016/B978-0-323-88506-5.50066-8 is OK
- 10.1007/s00422-019-00805-w is OK
- 10.3390/e23020198 is OK
- 10.1080/10407413.2021.1965480 is OK
- 10.1098/rsif.2013.0475 is OK
- 10.7554/eLife.41703 is OK
- 10.1162/neco_a_00999 is OK

MISSING DOIs

- 10.1162/neco_a_01427 may be a valid DOI for title: Chance-Constrained Active Inference
- 10.1017/s0140525x19001353 may be a valid DOI for title: Generative models as parsimonious descriptions of sensorimotor loops
- 10.7551/mitpress/7111.003.0009 may be a valid DOI for title: Perceptions as hypotheses
- 10.31234/osf.io/2rzu5 may be a valid DOI for title: Active inference, selective attention, and the cocktail party problem
- 10.1016/j.schres.2021.07.032 may be a valid DOI for title: Everything is connected: Inference and attractors in delusions
- 10.31234/osf.io/bsuh8 may be a valid DOI for title: Long-term stability of computational parameters during approach-avoidance conflict in a transdiagnostic psychiatric patient sample

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04067/joss.04067/10.21105.joss.04067.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04067/joss.04067/10.21105.joss.04067.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @emdupre - are you able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @emdupre as editor

**Comment by whedon** [comment]
@emdupre has been invited to edit this submission.

**Comment by emdupre** [comment]
Yes, happy to take this ! Thanks @danielskatz

**Comment by emdupre** [comment]
@whedon assign @emdupre as editor

**Comment by whedon** [comment]
OK, the editor is @emdupre

**Comment by emdupre** [comment]
:wave: Hi @conorheins, and thank you for your submission to JOSS !

If you have any suggestions for potential reviewers, please let me know by listing their names or GitHub handles (without the @, so they don't receive a notification) here.

**Comment by conorheins** [comment]
Hi @emdupre, thanks for agreeing to review our submission!

I leave some the github handles of some suggested reviewers below (some from the list, some not):

From the list:
woolfeh
seankmartin
olgadoronina
franziskaaah
bramvandijk88
richrobe

not on the list:
ucbtns
kaiu85
semihakbayrak
ivan-bocharov
micahgallen

**Comment by emdupre** [comment]
:wave: Hi @seankmartin, @richrobe, @semihakbayrak, @patrickmineault !

Would you be willing to review _pymdp: A Python library for active inference in discrete state spaces_ for [JOSS (the Journal of Open Source Software)](https://joss.theoj.org/)?

You can learn more about reviewing for JOSS -- including our conflict of interest policy -- [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

The review takes place on GitHub and focuses on [the software](https://github.com/infer-actively/pymdp) and this short paper:
https://github.com/openjournals/joss-papers/blob/joss.04067/joss.04067/10.21105.joss.04067.pdf

If you're available to review this work, please let me know and I'll add you as a reviewer. Once I have sufficient reviewers I'll open a dedicated review issue.

Thank you !

**Comment by richrobe** [comment]
Hi @emdupre, sorry, I can't do a review right now :/ Hopefully next time!

Best,
Robert

**Comment by seankmartin** [comment]
Hi @emdupre 

Sure, I'm good to review pymdp!

**Comment by semihakbayrak** [comment]
Hi @emdupre! Unfortunately I am not available. Bests!

**Comment by patrickmineault** [comment]
@emdupre I can do it

**Comment by emdupre** [comment]
Hi everyone, thanks for your quick responses !

I'll go ahead and add @seankmartin and @patrickmineault as reviewers for this submission and start the review process :rocket:

**Comment by emdupre** [comment]
@whedon add @seankmartin as reviewer

**Comment by whedon** [comment]
OK, @seankmartin is now a reviewer

**Comment by emdupre** [comment]
@whedon add @patrickmineault as reviewer

**Comment by whedon** [comment]
OK, @patrickmineault is now a reviewer

**Comment by emdupre** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4098.
