### ISSUE TITLE
[REVIEW]: UKCensusAPI: python and R interfaces to the nomisweb UK census data API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#408]
**Submitting author:** @virgesmith (<a href="http://orcid.org/0000-0002-9951-6642">Andrew Smith</a>)
**Repository:** <a href="https://github.com/virgesmith/UKCensusAPI" target ="_blank">https://github.com/virgesmith/UKCensusAPI</a>
**Version:** 0.1
**Editor:** @leeper
**Reviewer:** @jrnold
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1048388" target="_blank">10.5281/zenodo.1048388</a>

## Status

[![status](http://joss.theoj.org/papers/40041a0ebb1364286d5eb144d333bb6a/status.svg)](http://joss.theoj.org/papers/40041a0ebb1364286d5eb144d333bb6a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/40041a0ebb1364286d5eb144d333bb6a"><img src="http://joss.theoj.org/papers/40041a0ebb1364286d5eb144d333bb6a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/40041a0ebb1364286d5eb144d333bb6a/status.svg)](http://joss.theoj.org/papers/40041a0ebb1364286d5eb144d333bb6a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/virgesmith/UKCensusAPI" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@jrnold, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/virgesmith/UKCensusAPI">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1)?
- [x] **Authorship:** Has the submitting author (@virgesmith) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jrnold it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by leeper** [comment]
@virgesmith I see there are still a few open review issues. How are things progressing?

**Comment by virgesmith** [comment]
@leeper: I've addressed issues raised so far by @jrnold. Two are still open: #15 (split into 2 packages), because in my opinion this isn't a good idea (I've explained my position), and #14 (release tag) as I wanted to leave this until all other issues were resolved. I'm really waiting for @jrnold to respond on these (and any further issues he wants to raise)

**Comment by virgesmith** [comment]
@leeper, @jrnold I'm keen to progress this but its all gone rather quiet...

**Comment by leeper** [comment]
@virgesmith I've just taken another look at this. I would like to see some small revisions before accepting this. Namely, it would be good for all of the R documentation pages to include small examples of code usage. It's fine to include all of these in `\dontrun{}` brackets. Similarly, can the main package [documentation page](https://github.com/virgesmith/UKCensusAPI/blob/master/R/UKCensusAPI.R) include some of the general introductory content from the README? READMEs are not easily accessible from within R so having this within-package documentation is pretty important from a usability perspective.

Also please do generate a github release (per https://github.com/virgesmith/UKCensusAPI/issues/14) and initiate a Zenodo (or other) archive to obtain a DOI for that release.

**Comment by virgesmith** [comment]
@leeper have done the documentation changes and the release as requested.

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1048388 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1048388" target="_blank">10.5281/zenodo.1048388</a> is the archive.

**Comment by leeper** [comment]
@virgesmith Looks good to me. Thanks for the submission!

@arfon Over to you.

**Comment by leeper** [comment]
@arfon Just a bump. This one is all set.

**Comment by arfon** [comment]
@jrnold - many thanks for your review here and to @leeper for editing this submission ✨ 

@virgesmith - your paper is now accepted into JOSS and your paper DOI is https://doi.org/10.21105/joss.00408 ⚡️ 🚀 💥

**Comment by arfon** [comment]
@virgesmith - also, please merge these changes that I had to make to complete your submission: https://github.com/virgesmith/UKCensusAPI/pull/20
