### ISSUE TITLE
[PRE REVIEW]: UltaNet Implementing a antithesis neural network for Human Activity Recognition with Keras

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4081]
**Submitting author:** @engrhamzaaliimran (<a href="http://orcid.org/0000-0001-7365-3326">Hamza Ali Imran</a>)
**Repository:** <a href="https://github.com/engrhamzaaliimran/UltaNet" target ="_blank">https://github.com/engrhamzaaliimran/UltaNet</a>
**Version:** 1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f75b8c93abfa288ee37ed2234651bdff/status.svg)](https://joss.theoj.org/papers/f75b8c93abfa288ee37ed2234651bdff)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f75b8c93abfa288ee37ed2234651bdff"><img src="https://joss.theoj.org/papers/f75b8c93abfa288ee37ed2234651bdff/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f75b8c93abfa288ee37ed2234651bdff/status.svg)](https://joss.theoj.org/papers/f75b8c93abfa288ee37ed2234651bdff)
```

**Author instructions**

Thanks for submitting your paper to JOSS @engrhamzaaliimran. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lucydot.

@engrhamzaaliimran if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (161.9 files/s, 123623.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 1              0            506           1014
Markdown                         1              2              0              5
-------------------------------------------------------------------------------
SUM:                             2              2            506           1019
-------------------------------------------------------------------------------


Statistical information for the repository '23fcd84d16912ce302e7fc02' was
gathered on 2022/01/21.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4081 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
Hello @engrhamzaaliimran, unfortunately your submission does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html), because it is a Jupyter Notebook and not a software package. This analysis looks useful and important for supporting your research article, but this is not a fully featured research code like what JOSS reviews.

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
