### ISSUE TITLE
[PRE REVIEW]: ALUES: An R package for Agricultural Land Use Evaluation System

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4082]
**Submitting author:** @alstat (<a href="http://orcid.org/0000-0003-3784-8593">Al-Ahmadgaid Asaad</a>)
**Repository:** https://github.com/alstat/ALUES
**Branch with paper.md** (empty if default branch): 
**Version:** v0.2.1
**Editor:** @fabian-s
**Reviewers:** @corybrunson, @kuesterc9
**Managing EiC:** Kyle Niemeyer

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/11269cd0052a7e141aeec0393399d2a9/status.svg)](https://joss.theoj.org/papers/11269cd0052a7e141aeec0393399d2a9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/11269cd0052a7e141aeec0393399d2a9"><img src="https://joss.theoj.org/papers/11269cd0052a7e141aeec0393399d2a9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/11269cd0052a7e141aeec0393399d2a9/status.svg)](https://joss.theoj.org/papers/11269cd0052a7e141aeec0393399d2a9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @alstat. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@alstat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.41 s (1331.7 files/s, 176404.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           265          13118           3543          42362
R                              242            261           5922           3347
C++                              6             26             55            693
CSS                              3             99             48            428
JavaScript                       4             64             34            266
Rmd                              8             61            405            223
Markdown                         5             43              0            211
YAML                             4             23              2            161
TeX                              1             11              0             93
SVG                              2              0              1             29
-------------------------------------------------------------------------------
SUM:                           540          13706          10010          47813
-------------------------------------------------------------------------------


Statistical information for the repository 'd6cf8757ee7f1ca362a2032a' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Al-Ahmadgaid Asaad               4          1173             39           35.07
alstat                          13          1256            988           64.93

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Al-Ahmadgaid Asaad          539           46.0          0.0                8.53
alstat                      863           68.7          1.6               10.08
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.envsoft.2003.10.006 is OK
- 10.1016/j.compag.2013.02.003 is OK
- 10.1080/10618600.1996.10474713 is OK
- 10.1016/S0198-9715(01)00031-X is OK
- 10.1016/S0019-9958(65)90241-X is OK
- 10.1111/j.1475-2743.1991.tb00881.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04082/joss.04082/10.21105.joss.04082.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04082/joss.04082/10.21105.joss.04082.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @KristinaRiemer as editor

👋  Hi @KristinaRiemer, could you edit this one?

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by fabian-s** [comment]
hey @kyleniemeyer,  if @KristinaRiemer is busy at the moment I could take this on as well
;)

**Comment by danielskatz** [comment]
@whedon assign @fabian-s as editor

great, thanks @fabian-s!

**Comment by whedon** [comment]
OK, the editor is @fabian-s

**Comment by KristinaRiemer** [comment]
Thank you @fabian-s! Yes, a little slammed at the moment.

**Comment by fabian-s** [comment]
:wave: @nuest, :wave: @benmarwick,  :wave: @dlebauer

would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by nuest** [comment]
Hi! I'm on parental leave, but feel free to ping me again in April if you're still a review short then.

**Comment by fabian-s** [comment]
:wave: @jhollist @corybrunson @cole-brokamp

would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by corybrunson** [comment]
@fabian-s i would be glad to! I have deadlines this week but can conduct my review next week (March 14–18).

**Comment by fabian-s** [comment]
@editorialbot add @corybrunson as reviewer

**Comment by fabian-s** [comment]
@editorialbot add @kuesterc9 as reviewer

**Comment by fabian-s** [comment]
@editorialbot start review
