### ISSUE TITLE
[PRE REVIEW]: Video event segmentation tool (VEST) for qualitative coding of video clips

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4083]
**Submitting author:** @jcheong0428 (<a href="http://orcid.org/0000-0002-9255-1648">Jin Hyun Cheong</a>)
**Repository:** <a href="https://github.com/jcheong0428/vest" target ="_blank">https://github.com/jcheong0428/vest</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f785d00d5314ee113d1ca4856570a218/status.svg)](https://joss.theoj.org/papers/f785d00d5314ee113d1ca4856570a218)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f785d00d5314ee113d1ca4856570a218"><img src="https://joss.theoj.org/papers/f785d00d5314ee113d1ca4856570a218/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f785d00d5314ee113d1ca4856570a218/status.svg)](https://joss.theoj.org/papers/f785d00d5314ee113d1ca4856570a218)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jcheong0428. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @ajstewartlang.

@jcheong0428 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 518

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (57.6 files/s, 128634.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       3            420            516          15894
HTML                             1            101              4            743
TeX                              1              8              0             78
Markdown                         2             24              0             68
PHP                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                             8            553            520          16784
-------------------------------------------------------------------------------


Statistical information for the repository 'ab1e10fe6cd70ac7e1e57781' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
jcheong0428                      1         16830              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
jcheong0428               16830          100.0          0.0                3.07
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1201/b13125-4 may be a valid DOI for title: Free-ranging macaque mothers exaggerate tool-using behavior when observed by offspring
- 10.1038/s41592-021-01106-6 may be a valid DOI for title: Geometric deep learning enables 3D kinematic profiling across species and environments
- 10.1038/s41592-021-01110-w may be a valid DOI for title: The DANNCE of the rats: a new toolkit for 3D tracking of animal behavior
- 10.1037/0022-3514.76.6.893 may be a valid DOI for title: The chameleon effect: the perception–behavior link and social interaction.
- 10.31234/osf.io/bd9wn may be a valid DOI for title: Synchronized affect in shared experiences strengthens social connection

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04083/joss.04083/10.21105.joss.04083.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04083/joss.04083/10.21105.joss.04083.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
👋 @jcheong0428 Thanks for your interest in JOSS. Since your submission does not quite appear to be a typical, distributable research software package, the editorial board is going to review your submission to ensure it meets our [requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) to be reviewed. This should take at most a week or two.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@jcheong0428 – thanks for your submission to JOSS. Unfortunately after review, the JOSS editorial team has decided this submission is not in scope for JOSS.

The primary challenge we see here is that software cannot reasonably be reviewed by others by virtue of the fact that all of the source code is contained in one large JavaScript file.

For this project to be considered for review in JOSS we would need to see the software decomposed into a more modular codebase (i.e., classes, modules), attention to packaging of the software (e.g., [npm](https://www.npmjs.com)), and tests/documentation. 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
