### ISSUE TITLE
[PRE REVIEW]: SGMCMCJax: a lightweight JAX library for stochastic gradient Markov chain Monte Carlo algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4084]
**Submitting author:** @jeremiecoullon (<a href="http://orcid.org/0000-0002-7032-3425">Jeremie Coullon</a>)
**Repository:** <a href="https://github.com/jeremiecoullon/SGMCMCJax" target ="_blank">https://github.com/jeremiecoullon/SGMCMCJax</a>
**Version:** 0.2.9
**Editor:** @dfm
**Reviewers:** @canyon289, @ColCarroll
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6e5913beea589991b0091ada7daaf676/status.svg)](https://joss.theoj.org/papers/6e5913beea589991b0091ada7daaf676)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6e5913beea589991b0091ada7daaf676"><img src="https://joss.theoj.org/papers/6e5913beea589991b0091ada7daaf676/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6e5913beea589991b0091ada7daaf676/status.svg)](https://joss.theoj.org/papers/6e5913beea589991b0091ada7daaf676)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jeremiecoullon. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@jeremiecoullon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 704

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (472.1 files/s, 51058.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22            319            139           1151
Jupyter Notebook                 7              0           1769            334
reStructuredText                 6            226             92            266
TeX                              1              6              0            115
Markdown                         2             47              0            108
DOS Batch                        1              8              1             26
INI                              2              6              0             13
make                             2              5              7             13
-------------------------------------------------------------------------------
SUM:                            43            617           2008           2026
-------------------------------------------------------------------------------


Statistical information for the repository '2979e4158294689da1530474' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeremie Coullon                 66          3010           1471           97.39
Kevin Murphy                     3            95             25            2.61

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jeremie Coullon            1520           50.5          1.2                6.45
Kevin Murphy                 89           93.7          0.1                8.99
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- 10.18637/jss.v091.i03 may be a valid DOI for title: sgmcmc: An R package for stochastic gradient Markov chain Monte Carlo

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04084/joss.04084/10.21105.joss.04084.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04084/joss.04084/10.21105.joss.04084.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @jeremiecoullon, while we are getting started, could you take a look at that potentially missing DOI? I also noticed some formatting issues with your references, if you could take a look at those too.

For reference, the available citation commands are:
- `@author:2001`  ->  "Author et al. (2001)"
- `[@author:2001]` -> "(Author et al., 2001)"
- `[@author1:2001; @author2:2001]` -> "(Author1 et al., 2001; Author2 et al., 2002)"

**Comment by kyleniemeyer** [comment]
@whedon invite @dfm as editor

👋 @dfm could you edit this one?

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

Sure thing! @jeremiecoullon give me a few days to do a first editorial pass and then I'll start recruiting reviewers. Let me know if you have any questions as the process progresses.

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by jeremiecoullon** [comment]
@kyleniemeyer : thanks for these tips! 
- I fixed the reference formatting issue (Baker et al, 2019, Abadi et al 2015). Is this what you meant?
- I added the missing DOI for Baker et al (2019)

Let me know if there are any other issues I can help with

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04084/joss.04084/10.21105.joss.04084.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04084/joss.04084/10.21105.joss.04084.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@jeremiecoullon yep, looks good!

@dfm Thanks!

**Comment by dfm** [comment]
@whedon add @canyon289 as reviewer

Thanks for agreeing to review, Ravin!

**Comment by whedon** [comment]
OK, @canyon289 is now a reviewer

**Comment by dfm** [comment]
@whedon add @ColCarroll as reviewer

Thanks also to Colin!

**Comment by whedon** [comment]
OK, @ColCarroll is now a reviewer

**Comment by canyon289** [comment]
Hello all, thrilled to be a reviewer and learn more about your work!

**Comment by dfm** [comment]
@whedon start review

@ColCarroll, @canyon289, @jeremiecoullon — The bot will now get the main review thread started in a new issue so I'll see you all over there!

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4113.
