### ISSUE TITLE
[PRE REVIEW]: GridapDistributed: a massively parallel finite element toolbox in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4085]
**Submitting author:** @amartinhuertas (<a href="http://orcid.org/0000-0001-5751-4561">Dr. Alberto F. Martin</a>)
**Repository:** <a href="https://github.com/gridap/GridapDistributed.jl/" target ="_blank">https://github.com/gridap/GridapDistributed.jl/</a>
**Version:** v0.2.4
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @PetrKryslUCSD, @Leticia-maria, @jedbrown
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3bd4bf42932beb69c49ebd4f88db45c2/status.svg)](https://joss.theoj.org/papers/3bd4bf42932beb69c49ebd4f88db45c2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3bd4bf42932beb69c49ebd4f88db45c2"><img src="https://joss.theoj.org/papers/3bd4bf42932beb69c49ebd4f88db45c2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3bd4bf42932beb69c49ebd4f88db45c2/status.svg)](https://joss.theoj.org/papers/3bd4bf42932beb69c49ebd4f88db45c2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @amartinhuertas. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@amartinhuertas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (580.6 files/s, 53180.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           30            555            154           2572
TOML                             4             28              1            109
Markdown                         3             44              0            100
YAML                             2              0              1             93
Bourne Shell                     1              1              3              3
-------------------------------------------------------------------------------
SUM:                            40            628            159           2877
-------------------------------------------------------------------------------


Statistical information for the repository 'af68adb7bce61eef1e13bb4e' was
gathered on 2022/01/21.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4085 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04085/joss.04085/10.21105.joss.04085.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04085/joss.04085/10.21105.joss.04085.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check references from branch joss_paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss_paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.21105/JOSS.02520 is OK
- 10.1137/20M1328786 is OK
- 10.1007/978-3-030-23957-2 is OK
- 10.5194/GMD-6-2099-2013 is OK
- 10.1137/100791634 is OK
- 10.1006/JCPH.1996.0047 is OK
- 10.3402/TELLUSA.V56I5.14436 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

👋 @Kevin-Mattheus-Moerman I hesitate slightly to ask you to edit this, since you've already got a solid workload, but it looks *right* in your wheelhouse...

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by amartinhuertas** [comment]
> @amartinhuertas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). 

@kyleniemeyer, suggestions for reviewers:
 * PetrKryslUCSD
 * KristofferC
 * ranocha

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@jedbrown @PetrKryslUCSD,  @Leticia-maria, @TeroFrondelius, @KristofferC, @rouson, @tjhei, @chrisrichardson, @Kevin-Mattheus-Moerman, @vijaysm, @likask would you be interesting in reviewing this software: "GridapDistributed: a massively parallel finite element toolbox in Julia" for [JOSS](https://joss.theoj.org)? 

Short paper: https://github.com/openjournals/joss-papers/blob/joss.04085/joss.04085/10.21105.joss.04085.pdf
Software: https://github.com/gridap/GridapDistributed.jl/

**Comment by Leticia-maria** [comment]
> @jedbrown @PetrKryslUCSD,  @Leticia-maria, @TeroFrondelius, @KristofferC, @rouson, @tjhei, @chrisrichardson, @vijaysm, @likask would you be interesting in reviewing this software: "GridapDistributed: a massively parallel finite element toolbox in Julia" for [JOSS](https://joss.theoj.org)? 
> 
> Short paper: https://github.com/openjournals/joss-papers/blob/joss.04085/joss.04085/10.21105.joss.04085.pdf
> Software: https://github.com/gridap/GridapDistributed.jl/

Thank you for calling me. I will review and we can keep in contact😊

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Leticia-maria as reviewer

**Comment by whedon** [comment]
OK, @Leticia-maria is now a reviewer

**Comment by vijaysm** [comment]
I'm unfortunately swamped with many things at the moment and so won't be able to finish my review without delays. It's definitely an interesting project and I'll keep my eye out on this page to follow the review comments. If you still need someone in a few weeks, I definitely will be able to review it. Thanks @Kevin-Mattheus-Moerman

**Comment by jedbrown** [comment]
I'm also interested in the project, but can't accept new reviewing until my kids can return to childcare and I can finish my already-overdue reviews. You're welcome to ping if you still need a reviewer in a few weeks.

**Comment by likask** [comment]
It looks like a very interesting project. However, I have to decline the review. I have a teaching-intensive period, and could not fully commit to this work.  @Kevin-Mattheus-Moerman

**Comment by PetrKryslUCSD** [comment]
Sure, happy to do it. @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @PetrKryslUCSD as reviewer

**Comment by whedon** [comment]
OK, @PetrKryslUCSD is now a reviewer

**Comment by rouson** [comment]
@Kevin-Mattheus-Moerman I'm interested in the subject matter, but my lack of prior experience with Julia would preclude providing a timely review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @Leticia-maria as reviewer

**Comment by whedon** [comment]
OK, @Leticia-maria is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@Leticia-maria apologies I accidentally replaced you above with Petr, so had to add you again.

**Comment by Leticia-maria** [comment]
> @Leticia-maria apologies I accidentally replaced you above with Petr, so had to add you again.

No problem @Kevin-Mattheus-Moerman. What's my deadline to review?

**Comment by Kevin-Mattheus-Moerman** [comment]
@Leticia-maria we used to aim for about 2-3 weeks but we can be (and have to be) quite flexible as we've seen (and experienced personally) that most people are struggling to keep up with things during the pandemic. So if you could aim for ~3 weeks great, but if you need more time just let me know. Note we have not formally started the review yet since this is the pre-review issue. You may start already if you wish but you can also wait until we've opened the review issue.

**Comment by Kevin-Mattheus-Moerman** [comment]
> I'm also interested in the project, but can't accept new reviewing until my kids can return to childcare and I can finish my already-overdue reviews. You're welcome to ping if you still need a reviewer in a few weeks.

@jedbrown I was wondering if you'd be okay being assigned as a reviewer at this point. Note though you can take your time. We can give you all the time you need (terms and conditions apply :wink: ) but I think we could use your help.

**Comment by jedbrown** [comment]
Okay, go ahead and assign me.

**Comment by whedon** [comment]
OK, @jedbrown is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4157.
