### ISSUE TITLE
[PRE REVIEW]: HDMIA: An Architect for High Demand Medical Image 2 Analysis using Deep Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4087]
**Submitting author:** @magedhelmy1 (<a href="http://orcid.org/0000-0003-1504-8536">Maged Helmy</a>)
**Repository:** <a href="https://github.com/magedhelmy1/capillarydetection" target ="_blank">https://github.com/magedhelmy1/capillarydetection</a>
**Version:** 0.1
**Editor:** @Bisaloo
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5508f9f11abc53f889b6547dc68dd6ef/status.svg)](https://joss.theoj.org/papers/5508f9f11abc53f889b6547dc68dd6ef)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5508f9f11abc53f889b6547dc68dd6ef"><img src="https://joss.theoj.org/papers/5508f9f11abc53f889b6547dc68dd6ef/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5508f9f11abc53f889b6547dc68dd6ef/status.svg)](https://joss.theoj.org/papers/5508f9f11abc53f889b6547dc68dd6ef)
```

**Author instructions**

Thanks for submitting your paper to JOSS @magedhelmy1. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Bisaloo.

@magedhelmy1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/s00134-018-5070-7 may be a valid DOI for title: Second consensus on the assessment of sublingual microcirculation in critically ill patients: results from a task force of the European Society of Intensive Care Medicine
- 10.1109/ms.2021.3089730 may be a valid DOI for title: Database of the Year: Postgres

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04087/joss.04087/10.21105.joss.04087.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04087/joss.04087/10.21105.joss.04087.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hello @magedhelmy1, thanks for your interest in JOSS. 

I noticed that you described your submission as an "original research study". JOSS does not actually review or publish original research, but instead research software packages: https://joss.readthedocs.io/en/latest/submitting.html

Original research should be submitted to a domain journal for review; we would review software that was developed in support of or related to that research. Can you clarify how your submission meets that requirement?

**Comment by magedhelmy1** [comment]
Hi @kyleniemeyer , thanks for your comment.

Indeed, this is not an original research study to be published here. But this is a research software package intended to address a research challenge: quantifying blood capillaries in patients. This software research package aims to support the functioning of research instruments (blood vessel quantification) and the execution of research experiments (quantifying the capillaries in the skin). My apologies if that was not clear.

Another small typo is in the title "HDMIA: An Architect for High Demand Medical Image 2 Analysis using Deep Learning", the number "2" should not exist there. Again, please accept my apologies for that.

**Comment by magedhelmy1** [comment]
Hi @kyleniemeyer , I hope you had a good weekend.

In addition to the previous answer, I include a detailed answer below to each point in the link [shared](https://joss.readthedocs.io/en/latest/submitting.html).

### Submission requirements

- [X] The software must be open source as per the OSI definition.
- [X] The software must have an obvious research application.
> The research application of the proposed research software is the ability to quantify capillary density in a microcirculation image in under 2 seconds.
> Capillaries are the smallest vessels in the body responsible for delivering oxygen and nutrients to surrounding cells. Various life-threatening diseases alter the density of healthy capillaries within the capillaries. In previous studies, capillary density was manually assessed by trained specialists. However, manual analysis of a standard 20-second microvascular video requires 2 minutes on average and necessitates extensive training. Thus, manual analysis of capillary density has been reported to hinder the application of microvascular microscopy in a clinical environment. This paper presents research software to quantify the capillaries to address this problem.

- [X] You must be a major contributor to the software you are submitting, and have a GitHub account to participate in the review process.

> I, the main author, have  99.96% contribution to the code as per the commits.


- [X] Your paper must not focus on new research results accomplished with the software.

> No new research has been accomplished in this paper. The proposed research software quantifies the capillaries to enable doctors and clinical researchers to develop their medical hypotheses with regard to specific diseases and capillary density alternation.

- [X] Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

### In addition, the software associated with your submission must:

- [X] Be stored in a repository that can be cloned without registration.
- [X] Be stored in a repository that is browsable online without registration.
- [X] Have an issue tracker that is readable without registration.
- [X] Permit individuals to create issues/file tickets against your repository.


### What we mean by research software

- [X] JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar

> This paper solves a problem in medicine, specifically the automated quantification of capillaries in Microcirculation images.


### Substantial scholarly effort

- [X] JOSS publishes articles about software that represent a substantial scholarly effort on the part of the authors. Your software should be a significant contribution to the available open-source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).
With the availability of this software, we contribute on two folds.

> First,  we enable some new research challenges to be addressed by allowing the complete automation of quantifying the capillary density in Microcirculation images. 
> On the second fold, the proposed software makes addressing research challenges significantly better by enabling doctors, researchers, and clinical personnel to develop their hypotheses with regards to the significance of capillary density changes in patients with specific diseases.
More concretely, it allows them to assess if various diseases indeed alter the capillary density and by how much.

- [X] As a rule of thumb, JOSS’ minimum allowable contribution should represent not less than three months of work for an individual.

> Almost daily commits for the past 120 days (with the exclusion of Christmas and new year, weekends and public holidays)

- [X] Age of software (is this a well-established software project) / length of commit history.
- [X] Number of commits.
> 660 commits

- [X] Number of authors.

> Me plus two professors in computer science and one associate professor in mathematics since we spent 1-year surveying state of the art and preparing the proposed architecture in this research package.

- [X] Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.
> According to the experimental software report 18978
- [ ] Whether the software has already been cited in academic papers.

> A different set of authors has informed me they are working on 2 separate papers that will use the proposed research software. The first paper will compare the alteration of capillary density between recovering COVID19 patients and dying COVID19 patients. The second paper will compare the capillary density between pigs with a mechanical heart and pigs with a normal heart.
> Another set of authors has informed me that they will explore the option of using the proposed software to compare the capillary density in healthy subjects and patients with diabetes and if capillary density can be used to predict amputation of a diabetic patient.

Both papers are still in writing with the authors.

- [ ] Whether the software is sufficiently useful that it is likely to be cited by your peer group.

> Our proposed software is currently used by a company that provides microcirculation analysis software.
> Furthermore, the authors mentioned in the previous point have cited our software and those citations will be public if their papers have been accepted for publication. We are optimistic that more will cite and use our proposed research package since it automates a manual process with comparable accuracy to the manual researcher.

- [X] In addition, JOSS requires that software should be feature-complete (i.e., no half-baked solutions), packaged appropriately according to common community standards for the programming language being used (e.g., Python, R), and designed for maintainable extension (not one-off modifications of existing tools). “Minor utility” packages, including “thin” API clients, and single-function packages are not acceptable.

> As part of the repo, we deployed our system here http://www.analysecapillary.space/ so it can be used out of the box.


### Co-publication of science, methods, and software

- [X] Sometimes authors prepare a JOSS publication alongside a contribution describing a science application, details of algorithm development, and/or methods assessment. In this circumstance, JOSS considers submissions for which the implementation of the software itself reflects a substantial scientific effort. This may be represented by the design of the software, the implementation of the algorithms, creation of tutorials, or any other aspect of the software. We ask that authors indicate whether related publications (published, in review, or nearing submission) exist as part of submitting to JOSS.

> As indicated in the README, the details of the algorithm can be found here [CapillaryNet: An Automated System to Quantify Skin Capillary Density and Red Blood Cell Velocity from Handheld Vital Microscopy](https://arxiv.org/abs/2104.11574). The paper is currently under review with the Artificial Intelligence in Medicine journal. However, the CapillaryNet paper covers more algorithms than just capillary quantification. The submitted research software to JOSS focuses on capillary quantification and its deployment. 


### Your paper should include:

- [X] A list of the authors of the software and their affiliations, using the correct format (see the example below).
- [X] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- [X] A Statement of Need section that clearly illustrates the research purpose of the software.
- [X] A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
- [X] Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
- [X] Acknowledgement of any financial support.

**Comment by arfon** [comment]
@whedon invite @Bisaloo as editor

:wave: @Bisaloo – would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@Bisaloo has been invited to edit this submission.

**Comment by Bisaloo** [comment]
:wave: :wave: @arfon @magedhelmy1, yes, I can edit this submission

**Comment by Bisaloo** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Bisaloo

**Comment by Bisaloo** [comment]
Hi @magedhelmy1 :wave:, I'll be your topic editor for this submission.

The first step in this pre-review is to find at least 2 reviewers. If you have any suggestions for potential reviewers, please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by magedhelmy1** [comment]
Hi @arfon, Thanks for assigning a reviewer to this.
Hi @Bisaloo, glad you are on board to be the topic editor for this submission.

I went through the Google sheet and can suggest several names.
Any 2 who are available of the following as you see fit.

sgk98
arn1291
gxlarson
AnthonyOfSeattle
Ykarpate
nnadeau
dirmeier
vyasr
lucaferranti
rabdill
tuelwer
robbisg
erik-whiting

**Comment by Bisaloo** [comment]
I'm going to already request some changes, as to facilitate the life of potential reviewers and already clarify certain points about this submission. Could you please:

- [ ] Have a look at the problematic DOIs identified by Whedon: https://github.com/openjournals/joss-reviews/issues/4087#issuecomment-1018837483
- [ ] Add a caption to all figures in the paper
- [ ] Remove obsolete files / breadcrumbs in the repository. As an example, I suspect the `ter temp` file should not be here. There might be others, I recommend you double check the entire repo for such files.
- [ ] Replace the `LICENSE` by the actual text of the CC BY-NC 4.0 license, so it can be auto-detected by GitHub and by other tools
- [ ] Add an actual contributing guide. The `contributing.md` file is currently empty. This contributing guide should detail, among other things, how to report an issue (what kind of information should be provided), explain which files should/can be changed by contributors vs files that are auto-generated (you should then also explain how they are auto-generated), how to test your changes (possibly by running automated tests if you have any), and provide at least an example file.
- [ ] Since your repository doesn't contain a simple software pacage, add a section in the README to present the repository structure and what each folder contains.

**Comment by magedhelmy1** [comment]
Hi @Bisaloo, thank you for being proactive and listing the improvements! I appreciate it.
I have incorporated all but one. Below are my comments on each point you stated and the corresponding change location.
I am only stuck at one point, which is the second point. Please clarify it, and I will improve right away.


- [x] Have a look at the problematic DOIs identified by Whedon: https://github.com/openjournals/joss-reviews/issues/4087#issuecomment-1018837483


> I have updated the references and added DOIs where applicable.
> The changes are reflected in [paper.bib](https://github.com/magedhelmy1/capillarydetection/blob/master/paper.bib)
> I am unsure how to re-run Whedon to see the report generated and fix the consequential issues.

- [] Add a caption to all figures in the paper

> I am unsure how to solve this remark.
> All figures seem to have captions. Can you please clarify in another way?
> Figure 1: The System Context View figure.
> Figure 2: The System Container View figure.
> Figure 3: The System Component View figure.


- [x] Remove obsolete files / breadcrumbs in the repository. As an example, I suspect the `ter temp` file should not be here. There might be others, I recommend you double check the entire repo for such files.


> I have now removed `ter temp`, `jq.exe`, `ray` and other similar files and folders that are obolsete.


- [x] Replace the `LICENSE` by the actual text of the CC BY-NC 4.0 license, so it can be auto-detected by GitHub and by other tools

> I have added this, and the changes are reflected in [license.md](https://github.com/magedhelmy1/capillarydetection/blob/master/LICENSE.md)


- [x] Update of remove `SECURITY.md` since it doesn't seem that you updated the boilerplate text, and it doesn't mean anything in the context of your repository.


> I have now removed that file, `SECURITY.md` .


- [x] Add an actual contributing guide. The `contributing.md` file is currently empty. This contributing guide should detail, among other things, how to report an issue (what kind of information should be provided), explain which files should/can be changed by contributors vs files that are auto-generated (you should then also explain how they are auto-generated), how to test your changes (possibly by running automated tests if you have any), and provide at least an example file.

> I have updated this and the changes are reflected in [README.MD](https://github.com/magedhelmy1/capillarydetection#contributing) and [contributing.md](https://github.com/magedhelmy1/capillarydetection/blob/master/contributing.md)


- [x] Since your repository doesn't contain a simple software package, add a section in the README to present the repository structure and what each folder contains.

> I have now added that section, and the changes are reflected in [project structure](https://github.com/magedhelmy1/capillarydetection#project-structure)

**Comment by Bisaloo** [comment]
For the caption, I meant a more informative & more descriptive caption. At the moment, as a reader, I don't really understand what I'm looking at and what information I should get from these figures.

**Comment by Bisaloo** [comment]
Hi @tuelwer :wave:, I see that you volunteered to review for JOSS and this submission seems to fit perfectly your expertise, both in terms and topics and programming language.

 Would you be available to review this submission?

Please note that this is a somewhat complex submission with several layers. If you want to review only one of these layers (e.g., the python backend but not the react frontend), this is perfectly fine :slightly_smiling_face:

**Comment by magedhelmy1** [comment]
Thank you @Bisaloo for taking the time to clarify.
I have now extended the captions of the figures to include your feedback.
Please let me know if I can improve it further or if you have other questions.

**Comment by Bisaloo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04087/joss.04087/10.21105.joss.04087.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04087/joss.04087/10.21105.joss.04087.pdf) :page_facing_up: :point_left:

**Comment by tuelwer** [comment]
This is very interesting work! 

@Bisaloo unfortunately, I am currently busy and cannot review this submission in reasonable time. Please, feel free to contact me again in a couple of weeks if you have not found a reviewer by then!

**Comment by magedhelmy1** [comment]
@tuelwer thank you! and thanks for responding fast.

**Comment by Bisaloo** [comment]
Thanks for your quick answer @tuelwer, I'll ping you again in a couple of weeks if necessary :slightly_smiling_face:

**Comment by magedhelmy1** [comment]
Hey @Bisaloo , happy to suggest other names if needed besides the 13 above.

**Comment by Bisaloo** [comment]
Hi @fepegar :wave:, I see you volunteered to review submissions for JOSS. [This submission](https://github.com/magedhelmy1/capillarydetection), with [the associated pape](https://github.com/openjournals/joss-papers/blob/joss.04087/joss.04087/10.21105.joss.04087.pdf?rgh-link-date=2022-02-04T14%3A15%3A41Z)r, seems to fit quite well with your expertise. Would you be able to review it?

**Comment by Bisaloo** [comment]
Hi @michaelberks :wave:, I see you volunteered to review submissions for JOSS. [This submission](https://github.com/magedhelmy1/capillarydetection), with [the associated paper](https://github.com/openjournals/joss-papers/blob/joss.04087/joss.04087/10.21105.joss.04087.pdf?rgh-link-date=2022-02-04T14%3A15%3A41Z), seems to fit quite well with your expertise. Would you be able to review it?

Please note that this is a somewhat complex submission with several layers. If you want to review only one of these layers (e.g., the python backend but not the react frontend), this is perfectly fine :slightly_smiling_face:

**Comment by fepegar** [comment]
> Hi @fepegar 👋, I see you volunteered to review submissions for JOSS. [This submission](https://github.com/magedhelmy1/capillarydetection), with [the associated pape](https://github.com/openjournals/joss-papers/blob/joss.04087/joss.04087/10.21105.joss.04087.pdf?rgh-link-date=2022-02-04T14%3A15%3A41Zr), seems to fit quite well with your expertise. Would you be able to review it?

Please note that this is a somewhat complex submission with several layers. If you want to review only one of these layers (e.g., the python backend but not the react frontend), this is perfectly fine 🙂

Hi, @Bisaloo. Thanks for pinging me. Unfortunately, this topic is not really close to my areas of knowledge. Good luck finding someone!

**Comment by Bisaloo** [comment]
Hi @robbisg :wave:, the author has identified you as a potential good reviewer for this submission.

Would you be available to review this [piece of software](https://github.com/magedhelmy1/capillarydetection) and [associated paper](https://github.com/openjournals/joss-papers/blob/joss.04087/joss.04087/10.21105.joss.04087.pdf?rgh-link-date=2022-02-08T23%3A03%3A33Z) for JOSS?

**Comment by magedhelmy1** [comment]
Kind remainder to Bisaloo comments to check if you are available to review the paper submitted to JOSS :)  

@michaelberks 
@robbisg

**Comment by robbisg** [comment]
Sorry for the delay! Yes I'm available!

**Comment by Bisaloo** [comment]
Thanks for your answer @robbisg! :pray: Please see my comment below.

@magedhelmy1, while I was looking for reviewers, some comments have been raised about whether this submission is really in scope for JOSS. In particular:

- it seems to be more a clinical/medical tool than a research tool when our policy states: "The software must have an **obvious** research application."
- it is not clear to me how a trained ML model without the training data fits in our scope

Please let me some time to gather the opinions of other editors, and I'll get back to you as soon as possible. Thanks

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
> While useful for many areas of research, pre-trained machine learning models and notebooks are not in-scope for JOSS.

https://joss.readthedocs.io/en/latest/submitting.html

**Comment by robbisg** [comment]
Hi @Bisaloo ,

at a first sight it seemed to me that this software is a platform for uploading images and applying pre-trained methods for the identification of some diseases. 
Despite it can be useful for some research activity since it detects capillarity density from images, speeding up this process for clinical applications, it seems that is a bit out of the scope of JOSS, as far as I understood and as pointed out by @danielskatz .

**Comment by magedhelmy1** [comment]
Hi @danielskatz , thanks for the hyperlink and highlight.
This paper is not a pre-trained machine learning model.
The focus of this paper is not the algorithm but rather the "Architecture for High Demand Medical Image Analysis..." built as a platform powered by deep learning models. The algorithm is added for sake of completion and usability of the proposed architecture.

In Figure 3 in the paper, you will see where the "pre-trained" model is in relation to the whole system. It barely occupies 5% of the total system workflow. In fact, it occupies around 2 lines of code in the whole project.

The pre-trained algorithm is submitted as a separate paper for publication in another journal including the data used for training it. This paper focuses on the deployment of this model by coupling several systems together. This way my aim is to meet the following requirement from JOSS `The software must have an obvious research application.` is  @robbisg comment which is `it detects capillarity density from images, speeding up this process for clinical applications,` or else this is an architecture was no obvious research use.

@robbisg
There are several JOSS papers that provide software platforms that do improve existing research activities as you highlighted yourself, for example:

https://joss.theoj.org/papers/10.21105/joss.00040

You can find a few more here if you search https://joss.theoj.org/papers/published

With regards to the JOSS requirements, I have a detailed list earlier https://github.com/openjournals/joss-reviews/issues/4087#issuecomment-1020590129 , I'd appreciate it if you highlight there which part is a bit out of the scope of JOSS and I am happy to address.

**Comment by danielskatz** [comment]
Thanks @magedhelmy1 - the editors are/will examine this and make a decision, and your comments will be helpful in that process

**Comment by magedhelmy1** [comment]
Thank you @danielskatz for keeping me posted. I appreciate it. 

Since the comments might be helpful, I will take this opportunity to also address @Bisaloo comments.

`it seems to be more a clinical/medical tool than a research tool when our policy states: "The software must have an obvious research application."`

This is a clinical tool, yes, but that does not mean it is not a research tool also.
In fact, I did go the extra step and built the clinical tool on top of the architecture to demonstrate the usefulness of the proposed architecture as a research tool. In this case, analyze capillary density in under 2 seconds. This should also satisfy the sentence in that same document later which states
 
`Whether or not the software is sufficiently useful that it is likely to be cited by your peer group.`
 
This is a general-use tool that can be adapted to many similar types of research because it provides a general architecture for pushing images through a deep learning model to provide results in real-time.

Thus, I would argue there are 2 interlinked obvious research applications and they are
 
1) Researchers who are interested in Microcirculation analyses can simply build on this architecture to analyze many different kinds of  Microcirculation images.
Some expansions on this package are:
- Calculate from the video instead of images
- Calculate the velocity of blood within the capillary
- Calculate blood hematocrit
 
I will not state them all here, but if you have the time, please feel free to check table 9 in [Second consensus on the assessment of sublingual microcirculation in critically ill patients: results from a task force of the European Society of Intensive Care Medicine](https://link.springer.com/article/10.1007/s00134-018-5070-7) where researchers will need such tools if they will to use microcirculation analysis in bedside inside hospitals.

2) As the title captures, this is an architect on how to analyze medical images using deep learning. So if one would strip away the "tool" part from the code, that is the microcirculation images and deep learning code. You can use this architecture to analyze any image in high demand using any deep learning model. In the performance testing, I show that you are able to get up to 3000 Response per Second which is the equivalent of 10.8million RPS per hour. Thus, the "High Demand" part is in the title.

`it is not clear to me how a trained ML model without the training data fits in our scope`

As highlighted in the earlier comment that this paper is not about the trained ML Model thus I did not provide the data. A paper with the model+data by the same authors is under consideration in another journal (AIIM).
I am happy to modify the paper to reflect the above statements since it seems I did not do that adequately.

Happy to address any further comments or clarify myself further.

**Comment by magedhelmy1** [comment]
hey @danielskatz, I hope all is well. Any news?

**Comment by danielskatz** [comment]
👋 @magedhelmy1 - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission has issues in both the JOSS [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) and [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criteria.

This does not mean that it is not software that is useful in research, but just that JOSS does not consider it in scope for review as a substantial contribution of research software.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

Our specific comments are that the submission seems mostly targeted to clinicians, as clearly framed in the paper. This is also highlighted by the fact that there is no way to analyse a folder of images in bulk, or even to export the results of the analysis in a data frame. Currently, the user has to copy the results manually to aggregate them. Additionally, it is not clear what this submission is really about. One major part seems to be a pre-trained ML model, which would make it outside of JOSS scope (+ this part is currently under consideration for publication in another journal according to the author). You defended your submission by saying that the pre-trained ML model is just here to illustrate their submission but that the actual object of interest here is the "architecture", i.e., the fact that you built a react frontend to this ML model and a system to handle the communication between the frontend and the backend. But if we ignore the ML model, we don't think this qualifies as a substantial scholarly effort, as illustrated by the very low number of lines of code.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
