### ISSUE TITLE
[PRE REVIEW]: Imagedata: A Python library to handle medical image data in NumPy array subclass Series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4088]
**Submitting author:** @erling6232 (<a href="http://orcid.org/0000-0001-8268-1206">Erling Andersen</a>)
**Repository:** <a href="https://github.com/erling6232/imagedata" target ="_blank">https://github.com/erling6232/imagedata</a>
**Version:** 1.4.0
**Editor:** @galessiorob
**Reviewers:** @glatard, @mwegrzyn, @joaorodrigues
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6a1bc6ea5a200a7a9204cfafcd6e49b8/status.svg)](https://joss.theoj.org/papers/6a1bc6ea5a200a7a9204cfafcd6e49b8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6a1bc6ea5a200a7a9204cfafcd6e49b8"><img src="https://joss.theoj.org/papers/6a1bc6ea5a200a7a9204cfafcd6e49b8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6a1bc6ea5a200a7a9204cfafcd6e49b8/status.svg)](https://joss.theoj.org/papers/6a1bc6ea5a200a7a9204cfafcd6e49b8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @erling6232. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@erling6232 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1653

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.5543955 is OK
- 10.3389/fninf.2014.00013 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1385/ni:5:1:11 is OK
- 10.5281/zenodo.4295521 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.1016/j.neuroimage.2004.07.051 may be a valid DOI for title: Advances in functional and structural MR image analysis and implementation as FSL

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (526.6 files/s, 103232.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          52           2041           4001           9881
reStructuredText                24            514            527            780
Markdown                         1             67              0            238
TeX                              2             12              0            188
XML                              7              0              0             77
YAML                             3             13             19             70
JSON                             1              0              0             67
INI                              1              5              0             33
make                             2             12              7             30
DOS Batch                        1              8              1             26
TOML                             1              0              0              7
-------------------------------------------------------------------------------
SUM:                            95           2672           4555          11397
-------------------------------------------------------------------------------


Statistical information for the repository '2c00397f7b7b0ea0ca9d8f59' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andersen                         1             1              1            0.00
Erling Andersen                427         30795          14733          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andersen                      1          100.0          5.1              100.00
Erling Andersen           15922           51.7         23.3               16.78
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04088/joss.04088/10.21105.joss.04088.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04088/joss.04088/10.21105.joss.04088.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @galessiorob as editor

👋 Hi @galessiorob, could you edit this one?

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by erling6232** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #4088 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 131, column 3):
unexpected "j"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

```

**Comment by erling6232** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04088/joss.04088/10.21105.joss.04088.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04088/joss.04088/10.21105.joss.04088.pdf) :page_facing_up: :point_left:

**Comment by erling6232** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04088/joss.04088/10.21105.joss.04088.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04088/joss.04088/10.21105.joss.04088.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@galessiorob would you be able to help edit this work?

**Comment by galessiorob** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by galessiorob** [comment]
👋 Hi @erling6232

I am in the process of assigning reviewers to this submission; if you have any suggestions, please let me know and feel free to @ mention them here.

**Comment by whedon** [comment]
OK, @glatard is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @mwegrzyn as reviewer

**Comment by galessiorob** [comment]
@whedon add @joaorodrigues as reviewer

**Comment by whedon** [comment]
OK, @joaorodrigues is now a reviewer

**Comment by galessiorob** [comment]
🎉 Thanks for volunteering to be reviewers @glatard @mwergrzyn and @joarodrigues!

I'll generate a "review issue" that will contain individual checklists to go through, feel free to get started at your earliest convenience, don't hesitate to ask if you need clarification or help - you can @mention me directly on the issue.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4133.

**Comment by JoaoRodrigues** [comment]
Thanks @galessiorob, quick question just to set expectations. What's the expected deadline for this review?

**Comment by galessiorob** [comment]
@JoaoRodrigues we try to keep reviews within 3 to 8 weeks, but this may vary depending on the complexity of the paper. Does this timeline work for you?

**Comment by JoaoRodrigues** [comment]
It does, thanks!
