### ISSUE TITLE
[PRE REVIEW]: GEMMI: A library for structural biology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4089]
**Submitting author:** @wojdyr (<a href="http://orcid.org/0000-0003-3980-4092">Marcin Wojdyr</a>)
**Repository:** https://github.com/project-gemmi/gemmi/
**Branch with paper.md** (empty if default branch): 
**Version:** v0.5.1
**Editor:** @kellyrowland
**Reviewers:** @jamesrhester, @dominiquesydow
**Managing EiC:** Kyle Niemeyer

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/46628eee7a937a0dfed5033a29c9b15a/status.svg)](https://joss.theoj.org/papers/46628eee7a937a0dfed5033a29c9b15a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/46628eee7a937a0dfed5033a29c9b15a"><img src="https://joss.theoj.org/papers/46628eee7a937a0dfed5033a29c9b15a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/46628eee7a937a0dfed5033a29c9b15a/status.svg)](https://joss.theoj.org/papers/46628eee7a937a0dfed5033a29c9b15a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @wojdyr. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @majensen.

@wojdyr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4089 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.36 s (1213.9 files/s, 281495.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   264           7129           6835          50780
C++                             86           1083            486          13235
reStructuredText                10           3123           3734           4770
Python                          50            501            491           3699
C                                8            429            768           3235
JSON                             3              0              0            884
YAML                             7             66             27            423
CMake                            1             73             38            324
Bourne Shell                     6             35             65            242
Markdown                         2             24              0             68
make                             2             19              7             52
Fortran 90                       2              3              4             42
CSS                              1              3              3             13
JavaScript                       1              1              0             12
-------------------------------------------------------------------------------
SUM:                           443          12489          12458          77779
-------------------------------------------------------------------------------


Statistical information for the repository 'bdb3c33c87722c8a07bad91d' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
CV-GPhL                          1             8              8            0.01
ClAuS Flensburg                  4            36              9            0.02
Dmitriy Marin                    2             9              9            0.01
FX Coudert                       1             1              1            0.00
Jack Greisman                    2            52             19            0.04
Keitaro Yamashita               16           398            108            0.26
Marcin Wojdyr                 2415        138848          50969           99.30
Markus Gerstel                   1             1              1            0.00
Sergei Izmailov                  5           132             60            0.10
keitaroyam                      45           432             49            0.25

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
CV-GPhL                       8          100.0         32.9                0.00
ClAuS Flensburg              36          100.0          1.8                0.00
Dmitriy Marin                 2           22.2         39.9                0.00
Jack Greisman                35           67.3         11.2                0.00
Keitaro Yamashita            23            5.8         13.6                0.00
Marcin Wojdyr             88055           63.4         34.6               10.91
Markus Gerstel                1          100.0         14.1                0.00
Sergei Izmailov              44           33.3         19.4                4.55
keitaroyam                  480          111.1          5.8                0.83
```

**Comment by kyleniemeyer** [comment]
@whedon invite @will-rowe as editor

👋 Hi @will-rowe, could you edit this one?

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by wojdyr** [comment]
@whedon generate pdf from branch paper

Regarding reviewer suggestion: the joss_reviewers list has a few people with "structural biology" topic:
joaorodrigues shriyaamittal joaomcteixeira rvhonorato nicksisco1932

If you'd like someone from outside this list, you could try people from here:
https://phenix-online.org/people
They won't have any conflicts of interest as we never collaborated.

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @will-rowe as editor

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @will-rowe, would you be able to help edit this work?

**Comment by majensen** [comment]
(Thanks for the suggestion @wojdyr  - I'm afraid I'm maxed out at this time)

**Comment by Kevin-Mattheus-Moerman** [comment]
@wojdyr I have just `waitlisted` this submission since none of the editors in domains relevant to this submission (e.g. chemistry, bioinformatics) are currently available. We will assign an editor once one becomes available.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @kellyrowland as editor

@kellyrowland do you think you could edit this submission?

**Comment by whedon** [comment]
@kellyrowland has been invited to edit this submission.

**Comment by kellyrowland** [comment]
Hi @Kevin-Mattheus-Moerman 👋 I can take this on.

**Comment by kellyrowland** [comment]
Hi @nicksisco1932 @jamesrhester 👋 

Would you be interested in and available to review this JOSS submission?

**Comment by jamesrhester** [comment]
Yes, happy to review this. I have contributed to a previous project of the author but I don't think this rises to the level of conflict of interest as it is not ongoing and not recent.

**Comment by kellyrowland** [comment]
@whedon add @jamesrhester as reviewer

**Comment by whedon** [comment]
OK, @jamesrhester is now a reviewer

**Comment by jamesrhester** [comment]
Hmm, no [REVIEW] issue has been created yet. Is that right?

**Comment by kellyrowland** [comment]
That's right, generally editors wait until at least two reviewers are
confirmed to create the review issue.

Having said that, if you'd like to get started on the review, I think I
could start that issue and seek a second reviewer in parallel.

**Comment by jamesrhester** [comment]
Just wanted to make sure I hadn't missed anything. Realistically I can't get started on the review until end of next week, so if there's no second reviewer before then perhaps that would be the moment to start the issue.

**Comment by kellyrowland** [comment]
Hi @dominiquesydow @betteridiot 👋 would either of you be interested in and available to review this JOSS submission?

**Comment by dominiquesydow** [comment]
Yes, I'd be happy to review!

**Comment by kellyrowland** [comment]
Great, thank you!

**Comment by kellyrowland** [comment]
@editorialbot add @dominiquesydow as reviewer

**Comment by kellyrowland** [comment]
@editorialbot start review
