### ISSUE TITLE
[PRE REVIEW]: CytobankAPIstats: Computes Signaling and Population Statistics for Cytometry Data on Cytobank using 'CytobankAPI'

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#409]
**Submitting author:** @athrom (<a href="http://orcid.org/0000-0001-6689-7904">Allison Throm</a>)
**Repository:** <a href="https://github.com/athrom/CytobankAPIstats" target ="_blank">https://github.com/athrom/CytobankAPIstats</a>
**Version:** v1.0
**Editor:** @biorelated
**Reviewer:** @nelkibs

**Author instructions**

Thanks for submitting your paper to JOSS @athrom. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@athrom if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @biorelated it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @biorelated - the submitting author suggested you as the editor

**Comment by biorelated** [comment]
@nelkibs Would you be happy to review this work for the JOSS journal? I am happy to assist you with the review process. Thanks!

**Comment by nelkibs** [comment]
Hi George,

Been off radar since last week. Technological problem. Just seen this. Si
we talk about it on Monday?

Nelson

**Comment by biorelated** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by biorelated** [comment]
@whedon assign @nelkibs as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nelkibs

**Comment by biorelated** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by biorelated** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/445. Feel free to close this issue now!
