### ISSUE TITLE
[PRE REVIEW]: yadg: yet another datagram

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4090]
**Submitting author:** @PeterKraus (<a href="http://orcid.org/0000-0002-4359-5003">Peter Kraus</a>)
**Repository:** <a href="https://github.com/dgbowl/yadg" target ="_blank">https://github.com/dgbowl/yadg</a>
**Version:** v4.0.0
**Editor:** @galessiorob
**Reviewers:** @aozorahime, @1mikegrn
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3/status.svg)](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3"><img src="https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3/status.svg)](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @PeterKraus. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jgostick.

@PeterKraus if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1191

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=5.53 s (24.4 files/s, 110112.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            34              0              0         596261
Python                          67           1203           2254           6812
reStructuredText                21            243            360            584
SVG                              2              2              2            349
YAML                             7              9             20            224
TeX                              1             21              0            205
Markdown                         2             23              0             70
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                           135           1501           2636         604511
-------------------------------------------------------------------------------


Statistical information for the repository 'c5e9dc91e7563a2a4d9be693' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kraus                            1            74             73            0.48
Kraus, Peter                    16          3924           1935           19.14
Nicolas Vetsch                   1           544              0            1.78
Peter Kraus                     27          3375           1261           15.14
Vetsch, Nicolas                  2          1940            169            6.89
krpe                            88          6880           4842           38.29
vetschn                         44          2983           2617           18.29

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kraus, Peter               6595          168.1          2.1                2.79
Nicolas Vetsch              544          100.0          0.0                6.25
Peter Kraus                 336           10.0          4.7               12.50
Vetsch, Nicolas            2789          143.8          0.5                6.38
vetschn                       5            0.2          2.3                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.33774/chemrxiv-2021-mh17g is OK
- 10.1002/cctc.202001132 is OK
- 10.1186/1471-2105-13-115 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1007/s11244-020-01380-2 is OK
- 10.1038/sdata.2016.18 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04090/joss.04090/10.21105.joss.04090.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04090/joss.04090/10.21105.joss.04090.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @PeterKraus, normally we would find an editor at this stage, who would then identify and assign reviewers for your submission—unfortunately none of the editors with relevant expertise are available right now, so we have to put your submission on our waitlist for the time being.

In the meantime, it would be a great help if you could suggest any reviewers, to help speed up the process once we do assign an editor. Thanks!

**Comment by PeterKraus** [comment]
Hi @kyleniemeyer, no worries, I understand the delays. I had a look at the reviewer list, and here are some suggestions, as requested starting at the bottom of the list:

- synthaze (general python tools)
- 1mikegrn (material science & chemistry & cheminformatics)
- varlottaang (data science & data ethics)
- bobturneruk (data engineering & good software engineering practices)
- alberto-battistel (impedance spectroscopy, electrochemistry, data analysis)
- lscalfi (electrochemistry, physical chemistry)
- mdmurbach (electrochemistry)

Cheers!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
:wave: @galessiorob do you think you can take this one on?

**Comment by galessiorob** [comment]
@whedon add @galessiorob as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by galessiorob** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by galessiorob** [comment]
👋 Hi @PeterKraus

I'm in the process of finding editors for this paper. If you have any suggestions feel free to add their handles in a comment, and I can send them invites. Looking forward to working on this paper!

**Comment by PeterKraus** [comment]
Hi @gallesiorob, pleasure to have you as an editor. I've listed a few names of folks who seem to have the right interest & coding preferences from the lower parts of the "signed-up reviewers" sheet [here](https://github.com/openjournals/joss-reviews/issues/4090#issuecomment-1019274321) - not sure if you want me to actually tag them or what's the process?

**Comment by galessiorob** [comment]
Awesome, thanks so much @PeterKraus! I can reach out to them and once we have two or three volunteers I'll open a review issue with a checklist for them to use as a guide.

**Comment by galessiorob** [comment]
@whedon add @aozorahime as reviewer

**Comment by whedon** [comment]
OK, @aozorahime is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @1mikegrn as reviewer

**Comment by whedon** [comment]
OK, @1mikegrn is now a reviewer

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4166.
