### ISSUE TITLE
[PRE REVIEW]: py_SBeLT: A Python software for stochastic sediment transport under rarefied conditions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4091]
**Submitting author:** @szwiep (<a href="http://orcid.org/0000-0002-0812-9509">Sarah Zwiep</a>)
**Repository:** https://github.com/szwiep/py_SBeLT
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.1
**Editor:** @kbarnhart
**Reviewers:** @pfeiffea, @tdoane
**Managing EiC:** Kyle Niemeyer

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d7b9cc16b87e8875ec7115a22e1413fe/status.svg)](https://joss.theoj.org/papers/d7b9cc16b87e8875ec7115a22e1413fe)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d7b9cc16b87e8875ec7115a22e1413fe"><img src="https://joss.theoj.org/papers/d7b9cc16b87e8875ec7115a22e1413fe/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d7b9cc16b87e8875ec7115a22e1413fe/status.svg)](https://joss.theoj.org/papers/d7b9cc16b87e8875ec7115a22e1413fe)
```

**Author instructions**

Thanks for submitting your paper to JOSS @szwiep. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@szwiep if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1104

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (275.7 files/s, 48309.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            467            455           1398
Markdown                         6            109              0            337
TeX                              1             15              0            178
YAML                             5             21             65            109
-------------------------------------------------------------------------------
SUM:                            18            612            520           2022
-------------------------------------------------------------------------------


Statistical information for the repository '2afd8eaf15168ebac979a698' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Greg Baker                       1             6              5            0.14
Sarah Zwiep                     30          2773           1245           50.11
szwiep                          69          2392           1597           49.75

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Greg Baker                    6          100.0         -0.0                0.00
szwiep                     2314           96.7          2.9               10.59
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevE.74.011302 is OK
- 10.1017/S0022112007008774 is OK
- 10.1029/2009JF001260 is OK
- 10.1080/00221686.2019.1702594 is OK
- 10.1002/2015JF003552 is OK
- 10.1029/2012JF002352 is OK
- 10.1002/2016JF003833 is OK
- 10.5194/esurf-9-629-2021 is OK
- 10.5194/esurf-6-1089-2018 is OK
- 10.1029/2012JF002353 is OK
- 10.1029/2019WR025116 is OK

MISSING DOIs

- 10.1061/9780784408148.ch03 may be a valid DOI for title: Transport of gravel and sediment mixtures

INVALID DOIs

- http://dx.doi.org/10.14288/1.0349138 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/2014RG000474 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4091 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kyleniemeyer** [comment]
Hi @szwiep, I think the empty `orcid:` field under your name is causing the paper build issue. Can you either add your ORCID, or remove the field?

**Comment by kyleniemeyer** [comment]
@whedon invite @kbarnhart as editor

👋 Hi @kbarnhart, could you edit this one? Note that the paper has a build issue at the moment, but that should be resolved quickly.

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by szwiep** [comment]
Hi @kyleniemeyer, I added my ORCID to the field. Thanks for letting me know.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #4091 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:204:in `block in parse_authors': Author (Shawn M. Chartrand^[co-first author]) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kyleniemeyer** [comment]
@szwiep ah, I'm sorry, it was actually the affiliation field for your coauthor that was causing the problem. (Or perhaps both things.)

Could you change `affiliation: 1, 2` to `affiliation: "1, 2"` (with the quotation marks)?

**Comment by szwiep** [comment]
@kyleniemeyer done! Field has been updated.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #4091 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:204:in `block in parse_authors': Author (Shawn M. Chartrand^[co-first author]) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kyleniemeyer** [comment]
@szwiep this just won't quite resolve! I notice one issue but miss the others, apparently...

The sub-fields under your coauthor's name should not have dashes, since that is used to mark new entries in the `authors` list. So, can you replace the second author block with
```yaml
  - name: Shawn M. Chartrand^[co-first author] 
    orcid: 0000-0002-9309-1137
    affiliation: "1, 2"
```

**Comment by szwiep** [comment]
@kyleniemeyer Thanks for helping sort this out. I'll update the dashes. One potential problem: would the second affiliation need an `index: 2` sub-field? Right now it doesn't.

**Comment by kyleniemeyer** [comment]
@szwiep no, combining two affiliations within quotes like that is the correct approach. (See the example paper: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

**Comment by szwiep** [comment]
@kyleniemeyer sorry, I meant in the affiliations section. Looks like we we're missing the index:

```{markdown}
  - name: Department of Earth Sciences, Simon Fraser University
   index: 2
```
Just committed those (dashes and index) changes.

**Comment by kbarnhart** [comment]
@kyleniemeyer I can handle this. I'll go ahead and assign myself. 

@szwiep I'll be able to start handling this actively in the middle of next week. At that point I'll do a standard pre-review check of the submission, depending on the results of that I may provide some feedback, and then will start to look for reviewers. Please let me know if you have questions at any point either here or at krbarnhart@usgs.gov

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04091/joss.04091/10.21105.joss.04091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04091/joss.04091/10.21105.joss.04091.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@szwiep it built! 

@kbarnhart thanks!

**Comment by smchartrand** [comment]
@kyleniemeyer @kbarnhart thanks for your support getting the pdf build issues resolved! Much appreciated.

**Comment by smchartrand** [comment]
Just a note that I have addressed the doi issues raised above by @whedon during the pdf build process.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04091/joss.04091/10.21105.joss.04091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04091/joss.04091/10.21105.joss.04091.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevE.74.011302 is OK
- 10.1017/S0022112007008774 is OK
- 10.1029/2009JF001260 is OK
- 10.1080/00221686.2019.1702594 is OK
- 10.14288/1.0349138 is OK
- 10.1002/2015JF003552 is OK
- 10.1029/2012JF002352 is OK
- 10.1002/2016JF003833 is OK
- 10.5194/esurf-9-629-2021 is OK
- 10.5194/esurf-6-1089-2018 is OK
- 10.1061/9780784408148.ch03 is OK
- 10.1029/2012JF002353 is OK
- 10.1002/2014RG000474 is OK
- 10.1029/2019WR025116 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by smchartrand** [comment]
@kbarnhart - I am following up on the above request for suggested reviewers. After looking through the JOSS reviewer list, here are some suggestions (I searched for keyword "geomorphology" and started at the bottom of the list and made it halfway):

1. marda-science and dbuscombe-usgs
2. ldominguezruben
3. katmratliff
4. pwernette
5. chrisleaman
6. kellykochanski

**Comment by kbarnhart** [comment]
@szwiep @smchartrand Thanks for this submission, I think it is a great contribution and I look forward to seeing it through the JOSS review process. I've gone through my standard pre-review evaluation of this submission and I have identified some issues that I think would be beneficial to address before I find reviewers and start review. Most of these comments are directly related to the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) and [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html). These are issues that would come up very quickly during review and so I find that it is best to address them before review starts. 

* **Documentation**
   * **Missing API documentation.** I see most functions are well documented, but I couldn't find API documentation linked from the readme. Based on the readme, I know that the main intent is for the model to be run by specifying a .yaml file, but the extensibility of the submission relies on the core functions themselves. Thus, I’d expect the API level documentation to be exposed.
    * **Examples.** Other than the readme, I didn't find any examples. Examples don't need to be extensive, but some more info to help a user understand how to use the software. An example would also provide the possibility to show an example .yaml input file.
    * **Theory:** Somewhere in the documentation I'd recommend a bit more theory background connecting the software options to the theory of rarified sediment transport (e.g., why a lognormal distribution, how do you handle when particles land on one another).
    * **More details regarding the output file.** Some more information about the output file would benefit a user. For example: how are the final metrics calculated (including the subregion definition), what is stored in `np.array(f["iteration_i"]["model"])`? Particle ages, locations, depths, etc?
    * **Needs additional installation architecture/instructions** A user might want to have their project directories separate from this package (e.g., alternative file structures than what is shown in the readme, including not needing to duplicate the python code provided here). How might a user handle this? I suspect that it would be best solved by more formally packaging the contribution so that py_SBeLT could be installed and then run.py and plot_maker.py could be run from the command line using a [console_script](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/?highlight=console_scripts#console-scripts).
* **Tests:** I see that the submission has tests, but it is not clear how a user would run them. 
* **Address reference formatting**. For example, disambiguation (D.J. vs David Jon Furbish) and missing citekeys, (e.g., lines 12).
 
I'm going to mark this submission as paused to give you whatever time you need to address the above comments. Please consider me a resource in addressing these comments and let me know if you have any questions. You can reach me either here or at krbarnhart@usgs.gov

**Comment by smchartrand** [comment]
Thanks very much @kbarnhart. Really appreciate this feedback and the proactiveness. @szwiep and I plan to get these addressed in the middle of February and submitted shortly thereafter. Hope this helps for your own schedule juggling and planning.

**Comment by kbarnhart** [comment]
@smchartrand glad to hear. I look forward to seeing the revisions to the submission.

**Comment by smchartrand** [comment]
Quick question @kbarnhart. Your above comment regarding **Theory** - is it best to add the additional text in the readme or the JOSS paper? Thanks.

**Comment by kbarnhart** [comment]
I'd recommend adding it to the ReadMe or another page in the documentation (JOSS in flexible in how the documentation is structured). That way the theory is more easily discoverable relative to the code.

**Comment by smchartrand** [comment]
Hi @kbarnhart. Just wanted to give you an update. Sarah and I are still working on your suggestions and hope to have things ready soon. Hope you are well and thanks for your patience.

**Comment by kbarnhart** [comment]
@smchartrand thanks for the update and no problem at all. If you have any questions for me as you work on the suggestions, please let me know.

**Comment by szwiep** [comment]
@kbarnhart thank you very much for your initial feedback and recommendations for the model, and thank you for your patience while we implemented them! The recommendations have all been addressed so I believe we're ready to resume the submission.

**Comment by kbarnhart** [comment]
@szwiep thanks for that update. I should be able to look more closely at this near the end of this week or early next week.

**Comment by smchartrand** [comment]
Thanks @kbarnhart. We look forward to hearing back from you.

**Comment by kbarnhart** [comment]
@szwiep and @smchartrand thanks for these updates, they are great. 

I have a couple of very minor comments and I've proposed changes that I think would be beneficial in a pull request. Most of the recommendations are to provide more links to other files in the Readme and to structure the documentation a bit. Feel free to modify any of my recommendations, they are just suggestions. The only thing I didn't include was actual text describing how a user might test an installation. Forgive me if that was somewhere I didn't notice. 

I will now start looking for reviewers.

**Comment by kbarnhart** [comment]
@editorialbot set v1.0.1 as version

**Comment by kbarnhart** [comment]
:wave: @pfeiffea @tdoane would you be willing to review the submission "py_SBeLT: A Python software for stochastic sediment transport under rarefied conditions" for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. I think your backgrounds in sediment transport would make you valuable reviewers of this contribution. 

If you are interested and able, please read our [conflict of interest](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) before agreeing. 

We would ask for reviews within 4–6 weeks, but that generally means starting the process sooner since it tends to be iterative between the reviewers and author(s). You can read more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Thanks for your consideration and let me know if you have any questions (here or at krbarnhart@usgs.gov)

**Comment by pfeiffea** [comment]
Hi @kbarnhart. I'd be happy to. I should be able to complete a first review by ~April 21st.

**Comment by tdoane** [comment]
HI @kbarnhart! I'm happy to review as well. The timeline works for me. Thanks!

**Comment by kbarnhart** [comment]
@editorialbot add @pfeiffea to reviewers

**Comment by kbarnhart** [comment]
@editorialbot add @tdoane to reviewers

**Comment by kbarnhart** [comment]
@editorialbot start review
