### ISSUE TITLE
[PRE REVIEW]: davos: The Python package smuggler

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4092]
**Submitting author:** @paxtonfitzpatrick (<a href="http://orcid.org/0000-0003-0205-3088">Paxton Fitzpatrick</a>)
**Repository:** <a href="https://github.com/ContextLab/davos" target ="_blank">https://github.com/ContextLab/davos</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c4abf0c1f6b107a79a3ef4fcf0a1b83c/status.svg)](https://joss.theoj.org/papers/c4abf0c1f6b107a79a3ef4fcf0a1b83c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c4abf0c1f6b107a79a3ef4fcf0a1b83c"><img src="https://joss.theoj.org/papers/c4abf0c1f6b107a79a3ef4fcf0a1b83c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c4abf0c1f6b107a79a3ef4fcf0a1b83c/status.svg)](https://joss.theoj.org/papers/c4abf0c1f6b107a79a3ef4fcf0a1b83c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @paxtonfitzpatrick. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @galessiorob.

@paxtonfitzpatrick if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1478

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (434.5 files/s, 136248.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 9              0           3652           3313
Python                          29            703           2080           3168
Markdown                         2            136              1            763
YAML                             4             49             30            325
TeX                              1             12              0            108
TOML                             1             10              6             67
-------------------------------------------------------------------------------
SUM:                            46            910           5769           7744
-------------------------------------------------------------------------------


Statistical information for the repository '71765c343c46c0941f2a633d' was
gathered on 2022/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
jeremymanning                    1            14              0            0.08
paxtonfitzpatrick              304         11356           5964           99.92

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
paxtonfitzpatrick          5402           47.6          6.8               12.25
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.5281/zenodo.5182775 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.3389/fninf.2015.00011 is OK
- 10.1109/MCSE.2007.53 is OK
- 10.25080/MAJORA-4AF1F417-011 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.21105/joss.03021 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04092/joss.04092/10.21105.joss.04092.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04092/joss.04092/10.21105.joss.04092.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by paxtonfitzpatrick** [comment]
Thanks @kyleniemeyer! While the README is written to appeal to a general audience and serve as documentation, the paper (particularly the Statement of Need) better explains its intended use as research software.

**Comment by kyleniemeyer** [comment]
@paxtonfitzpatrick got it, thanks. We'll make sure to consider that!

**Comment by arfon** [comment]
@paxtonfitzpatrick – many thanks for your submission to JOSS. After review by the JOSS editorial team, this submission has been deemed to be out of scope for JOSS. While we recognise that this is useful software that has some relevance to research, we don't believe it meets [our definition of research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software).

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
