### ISSUE TITLE
[PRE REVIEW]: UncertainSCI: A Python Package for Noninvasive Parametric Uncertainty Quantification of Simulation Pipelines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4094]
**Submitting author:** @jessdtate (<a href="http://orcid.org/0000-0002-2934-1453">Jess Tate</a>)
**Repository:** https://github.com/SCIInstitute/UncertainSCI
**Branch with paper.md** (empty if default branch): 
**Version:** v0.2.0b
**Editor:** @kellyrowland
**Reviewers:** @shahmoradi, @RichardClayton
**Managing EiC:** Arfon Smith

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/660d2fe53fbf67dd2714e9546251bd33/status.svg)](https://joss.theoj.org/papers/660d2fe53fbf67dd2714e9546251bd33)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/660d2fe53fbf67dd2714e9546251bd33"><img src="https://joss.theoj.org/papers/660d2fe53fbf67dd2714e9546251bd33/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/660d2fe53fbf67dd2714e9546251bd33/status.svg)](https://joss.theoj.org/papers/660d2fe53fbf67dd2714e9546251bd33)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jessdtate. **Currently, there isn't an JOSS editor assigned** to your paper.

@jessdtate if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1182

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (477.1 files/s, 63833.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          51           2538           2187           5215
Markdown                        13            310              0            643
TeX                              2             21              0            215
reStructuredText                11            113            151             87
Ruby                             1             20              6             83
YAML                             2              7              8             50
DOS Batch                        1              8              1             26
CSS                              1              7              0             23
JavaScript                       2              4              0             17
make                             1              4              7              9
Bourne Shell                     2              1              0              7
HTML                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                            88           3033           2360           6380
-------------------------------------------------------------------------------


Statistical information for the repository '8c7c197928885b2f5817d821' was
gathered on 2022/01/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Akil Narayan                    87         12377           5631           48.27
Daniel White                    16           211            190            1.07
Nidhi P                          1             0              5            0.01
Nidhi Patel                      3            79             22            0.27
ZEXINLIU                         1             1              1            0.01
Zexin Liu                       51         10433           7888           49.11
jab0707                          2           187             26            0.57
jessdtate                       18           184             67            0.67
nids2001                         1             3              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Akil Narayan               7179           58.0         11.3               11.99
Daniel White                153           72.5         15.7                7.19
Nidhi Patel                  27           34.2         15.7                3.70
ZEXINLIU                      1          100.0         20.6                0.00
Zexin Liu                  2040           19.6         16.2               12.70
jab0707                     161           86.1          7.8               30.43
jessdtate                   147           79.9          6.2                6.12
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.22489/CinC.2020.275 is OK
- 10.1016/j.brs.2021.10.226 is OK
- 10.1137/17M1140960 is OK
- 10.5802/smai-jcm.24 is OK
- 10.1553/etna_vol50s71 is OK

MISSING DOIs

- 10.1109/iembs.2005.1615736 may be a valid DOI for title: The Influence of Stochastic Organ Conductivity in 2D ECG Forward Modeling: A Stochastic Finite Element Study
- 10.23919/cinc53138.2021.9662950 may be a valid DOI for title: The Role of Myocardial Fiber Direction in Epicardial Activation Patterns via Uncertainty Quantification 
- 10.23919/cinc53138.2021.9662837 may be a valid DOI for title: Uncertainty Quantification in Simulations of Myocardial Ischemia

INVALID DOIs

- https://doi.org/10.1002/cnm.3395 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/978-3-030-78710-3_49 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04094/joss.04094/10.21105.joss.04094.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04094/joss.04094/10.21105.joss.04094.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @jni as editor

:wave: @jni – would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jni do you think you can help edit this one?

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by kthyng** [comment]
Hi @kellyrowland! Is this is your wheelhouse at all?

**Comment by kthyng** [comment]
@whedon invite @kellyrowland as editor

**Comment by whedon** [comment]
@kellyrowland has been invited to edit this submission.

**Comment by kellyrowland** [comment]
Hi @kthyng - this is admittedly a bit out of my core areas of expertise but I think I could take it on.

**Comment by kthyng** [comment]
@kellyrowland You can choose — don't feel like you have to!

**Comment by kellyrowland** [comment]
🙂 I'll pick it up; part of the benefits of being a JOSS editor is learning new things.

**Comment by kthyng** [comment]
@whedon assign @kellyrowland as editor

**Comment by whedon** [comment]
OK, the editor is @kellyrowland

**Comment by kellyrowland** [comment]
Hi @NMontanaBrown @dsurujon 👋 

Would you be interested in and available to review this JOSS submission?

**Comment by kellyrowland** [comment]
Hi @shahmoradi @tleonardi 👋 would you be interested in and available to review this JOSS submission?

**Comment by NMontanaBrown** [comment]
> Hi @NMontanaBrown @dsurujon 👋
> 
> Would you be interested in and available to review this JOSS submission?

Hi, thanks for the invite. This is slightly out of my scope so my review likely be the most useful. Apologies for the slow reply!

**Comment by kellyrowland** [comment]
No worries, thanks!

**Comment by tleonardi** [comment]
Hi, apologies for the slow reply. Same thing for me, this is outside my field of expertise and I would be able to do a proper job!

**Comment by kellyrowland** [comment]
Hi @jessdtate - would you be able to recommend any folks who might be able to review this paper?

**Comment by dsurujon** [comment]
> Hi @NMontanaBrown @dsurujon 👋
> 
> Would you be interested in and available to review this JOSS submission?

Hi, sorry for the delayed response. This seems outside my area of expertise as well. I'm not super familiar with the application. Maybe @bmomeni might be able to help?

**Comment by bmomeni** [comment]
> > Hi @NMontanaBrown @dsurujon 👋
> > Would you be interested in and available to review this JOSS submission?
> 
> Hi, sorry for the delayed response. This seems outside my area of expertise as well. I'm not super familiar with the application. Maybe @bmomeni might be able to help?

Sorry, it's outside of my expertise too.

**Comment by kellyrowland** [comment]
No worries, thanks for the responses all.

**Comment by jessdtate** [comment]
@kellyrowland do we need more than what I sent via email?  I can try to find a few more.

**Comment by kellyrowland** [comment]
@editorialbot add @RichardClayton as reviewer
