### ISSUE TITLE
[PRE REVIEW]: Fast k-medoids Clustering in Rust and Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4096]
**Submitting author:** @kno10 (<a href="http://orcid.org/0000-0001-9143-4880">Erich Schubert</a>)
**Repository:** <a href="https://github.com/kno10/python-kmedoids.git" target ="_blank">https://github.com/kno10/python-kmedoids.git</a>
**Version:** 0.2.0
**Editor:** @mikldk
**Reviewers:** @timClicks, @TahiriNadia
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4d6eb4cebdad66a96ebf153f986376f3/status.svg)](https://joss.theoj.org/papers/4d6eb4cebdad66a96ebf153f986376f3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4d6eb4cebdad66a96ebf153f986376f3"><img src="https://joss.theoj.org/papers/4d6eb4cebdad66a96ebf153f986376f3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4d6eb4cebdad66a96ebf153f986376f3/status.svg)](https://joss.theoj.org/papers/4d6eb4cebdad66a96ebf153f986376f3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @kno10. **Currently, there isn't an JOSS editor assigned** to your paper.

@kno10 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4096 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch JOSS-draft

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-draft. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04096/joss.04096/10.21105.joss.04096.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04096/joss.04096/10.21105.joss.04096.pdf) :page_facing_up: :point_left:

**Comment by kno10** [comment]
> @kno10 – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

Thank you @arfon!
The majority of the code lives in the Rust sister repository (we maybe should have put the paper draft there - the python part really is just a wrapper, but will likely have many more users) - maybe you can run whedon statistics on that repository instead:
https://github.com/kno10/rust-kmedoids
and of course much of the scholarly effort previously went into the Java version - the Rust version was a pretty direct port of this (except for the new parallelization by @lale1009).

**Comment by arfon** [comment]
Got it. Thanks @kno10. FYI JOSS editors, this is the `cloc` output for the [https://github.com/kno10/rust-kmedoids](https://github.com/kno10/rust-kmedoids) repo.

```
      19 text files.
      19 unique files.                              
       3 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.02 s (793.9 files/s, 105865.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rust                            14             72            472           1543
Markdown                         2             40              0             94
TOML                             1              7              1             38
-------------------------------------------------------------------------------
SUM:                            17            119            473           1675
-------------------------------------------------------------------------------
```

**Comment by arfon** [comment]
@whedon invite @mikldk as editor

:wave: @mikldk – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@kno10 - thank you for the submission.

Do you have any suggestions for reviewers ([here](https://bit.ly/joss-reviewers) is a list of potential reviewers) - please do not tag (`@`) anyone yet?

**Comment by lale1009** [comment]
Thanks @mikldk for organizing the review process.

We (@kno10) would suggest the following reviewers based on their primary topics and preferred programming languages. The list is sorted by fitting with our topic:
- timClicks (focus on Rust as a programming language, author of "Rust in Action")
- TahiriNadia (consensus kmedoids tree clustering)
- lmcinnes (hdbscan python package)
- gagolews (benchmark suite for clustering)
- rth (scikit-learn, pyo3, rust)
- amarkos (Joint Dimension Reduction and Clustering)
- matbesancon (Julia, but also optimization in Rust)
- bovee (bioinformatics, rust+python)
- jonjoncardoso (graph clustering, python)
- HadrienG (machine learning in bioinformatics)
- lutzhamel (self-organizing-maps)

**Comment by mikldk** [comment]
@timClicks, @TahiriNadia: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@lmcinnes, @gagolews: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by TahiriNadia** [comment]
> @timClicks, @TahiriNadia: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. If you have any questions or concerns please let me know.

Yes, I will!

**Comment by timClicks** [comment]
I'm happy to review the paper @mikldk

**Comment by mikldk** [comment]
@whedon add @timClicks as reviewer

**Comment by whedon** [comment]
OK, @timClicks is now a reviewer

**Comment by mikldk** [comment]
@whedon add @TahiriNadia as reviewer

**Comment by whedon** [comment]
OK, @TahiriNadia is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4183.

**Comment by gagolews** [comment]
Dear Mikkel, apologies for not getting back to you any sooner - I was on holidays in the Aussie bush, where the internet connection was virtually non-existent.

**Comment by mikldk** [comment]
> Dear Mikkel, apologies for not getting back to you any sooner - I was on holidays in the Aussie bush, where the internet connection was virtually non-existent.

@gagolews No worries (but I may ask you another time). Hope you enjoyed the holiday.
