### ISSUE TITLE
[PRE REVIEW]: pyemgpipeline: A Python package for electromyography processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4097]
**Submitting author:** @tlwu (<a href="http://orcid.org/0000-0002-1823-6818">Tsung-Lin Wu</a>)
**Repository:** <a href="https://github.com/aalhossary/pyemgpipeline" target ="_blank">https://github.com/aalhossary/pyemgpipeline</a>
**Version:** v0.1.0
**Editor:** @osorensen
**Reviewers:** @tuliofalmeida
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c95cc7e641fc919b3ba3a040189f90d8/status.svg)](https://joss.theoj.org/papers/c95cc7e641fc919b3ba3a040189f90d8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c95cc7e641fc919b3ba3a040189f90d8"><img src="https://joss.theoj.org/papers/c95cc7e641fc919b3ba3a040189f90d8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c95cc7e641fc919b3ba3a040189f90d8/status.svg)](https://joss.theoj.org/papers/c95cc7e641fc919b3ba3a040189f90d8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tlwu. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @prashjha.

@tlwu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 700

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jelekin.2016.10.001 is OK
- 10.1016/j.jelekin.2005.07.003 is OK
- 10.1016/S1050-6411(18)30348-1 is OK
- 10.21105/joss.01870 is OK

MISSING DOIs

- 10.1201/9781420036985.ax2 may be a valid DOI for title: Standards for reporting EMG data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.20 s (414.4 files/s, 145400.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      13           2405           2470           9219
HTML                            13            435             39           5304
SVG                              1              0              0           2671
Python                          36            550            962           1586
CSS                              4            191             35            758
Jupyter Notebook                 3              0           1783            170
reStructuredText                 8             81            122            100
Markdown                         2             34              0             92
TeX                              1              5              0             54
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            83           3713           5419          19989
-------------------------------------------------------------------------------


Statistical information for the repository 'd9bc99becc6bbdbcd911752f' was
gathered on 2022/01/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Amr ALHOSSARY                    1           182              0            0.24
tlwu                            31         46050          28946           99.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Amr ALHOSSARY                 4            2.2          0.0                0.00
tlwu                      17282           37.5          1.1               15.72
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04097/joss.04097/10.21105.joss.04097.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04097/joss.04097/10.21105.joss.04097.pdf) :page_facing_up: :point_left:

**Comment by tlwu** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by tlwu** [comment]
> @tlwu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 

Based on the preferred programming languages and domains/topic areas in the [list](https://bit.ly/joss-reviewers), potential reviewers are as follows:
(row id in the list) username or email

(1804) (email) gcarreno@iee.org
(951) GerJuli
(741) abhishektha
(489) ixjlyons
(482) melund
(63) trallard
(44) moorepants

**Comment by arfon** [comment]
@whedon invite @osorensen as editor

:wave: @osorensen – I realize this submission is not really in your area but would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@osorensen has been invited to edit this submission.

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
:wave: @melund & @abhishektha, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by melund** [comment]
@osorensen Sorry I am too busy at the moment to take this on. Hope you can find someone else.

**Comment by osorensen** [comment]
That's fine @melund, thanks for your quick response!

**Comment by osorensen** [comment]
@moorepants would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by abhishektha** [comment]
@osorensen Unfortunately I will have to pass as well as I'm quite busy the next two months! Thanks for asking!

**Comment by osorensen** [comment]
Ok, thanks for responding quickly, @abhishektha

**Comment by osorensen** [comment]
@tuliofalmeida would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by tuliofalmeida** [comment]
Hi,

I appreciate the invitation. It will be a pleasure to review this paper.

Best,

Túlio

**Comment by osorensen** [comment]
@whedon add @tuliofalmeida as reviewer

**Comment by whedon** [comment]
OK, @tuliofalmeida is now a reviewer

**Comment by osorensen** [comment]
@alcantarar would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by alcantarar** [comment]
Sorry, I'm unavailable to review this submission.

**Comment by osorensen** [comment]
Ok @alcantarar, thanks for your quick reply!

**Comment by osorensen** [comment]
@guxiaob would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4156.
