### ISSUE TITLE
[PRE REVIEW]: bomrang: Fetch Australian Government Bureau of Meteorology Data in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#410]
**Submitting author:** @adamhsparks (<a href="http://orcid.org/0000-0002-0061-8359">Adam H. Sparks</a>)
**Repository:** <a href="https://github.com/ropensci/bomrang" target ="_blank">https://github.com/ropensci/bomrang</a>
**Version:** 0.0.7
**Editor:** @karthik
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @adamhsparks. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@adamhsparks if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@adamhsparks - could you link to the rOpensci onboarding thread here please?

**Comment by adamhsparks** [comment]
https://github.com/ropensci/onboarding/issues/121

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/411. Feel free to close this issue now!
