### ISSUE TITLE
[PRE REVIEW]: DeepSynth: Scaling Neural Program Synthesis with Distribution-based Search

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4102]
**Submitting author:** @Theomat (<a href="http://orcid.org/0000-0002-5043-3221">Théo Matricon</a>)
**Repository:** <a href="https://github.com/nathanael-fijalkow/DeepSynth" target ="_blank">https://github.com/nathanael-fijalkow/DeepSynth</a>
**Version:** v1.0
**Editor:** @terrytangyuan
**Reviewers:** @njuaplusplus, @Kraks
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b5281edb0bde03b86149a7baf94db2f0/status.svg)](https://joss.theoj.org/papers/b5281edb0bde03b86149a7baf94db2f0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b5281edb0bde03b86149a7baf94db2f0"><img src="https://joss.theoj.org/papers/b5281edb0bde03b86149a7baf94db2f0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b5281edb0bde03b86149a7baf94db2f0/status.svg)](https://joss.theoj.org/papers/b5281edb0bde03b86149a7baf94db2f0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Theomat. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Bisaloo.

@Theomat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4102 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (336.5 files/s, 54004.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          49           1226           1144           5435
Markdown                         1             50              0            170
-------------------------------------------------------------------------------
SUM:                            50           1276           1144           5605
-------------------------------------------------------------------------------


Statistical information for the repository '313c0312657f832fda8317e8' was
gathered on 2022/01/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Guillaume Lagarde                8           871            242            5.05
Nathanael Fijalkow              37          7691           3627           51.35
Theomat                        179          5698           3279           40.72
ellisk42@gmail.com               5           540             95            2.88

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Guillaume Lagarde            64            7.3          5.8                0.00
Nathanael Fijalkow         4073           53.0          2.7               10.83
Theomat                    3660           64.2          3.4               10.44
ellisk42@gmail.com            8            1.5          4.0               37.50
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04102/joss.04102/10.21105.joss.04102.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04102/joss.04102/10.21105.joss.04102.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Noting from the author submission information that there is a related paper (accepted into AAAI22) that describes the methodology https://arxiv.org/abs/2110.12485

**Comment by arfon** [comment]
@whedon invite @terrytangyuan as editor

:wave: @terrytangyuan – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@terrytangyuan has been invited to edit this submission.

**Comment by terrytangyuan** [comment]
Yes

**Comment by danielskatz** [comment]
@whedon assign @terrytangyuan as editor

@terrytangyuan - note that you can do this yourself as well

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
👋🏻 Hi @smattr @ritwikagarwal @bzz @reSHARMA, would you be interested in reviewing this submission? Feel free to recommend anyone else that might be interested as well.

**Comment by terrytangyuan** [comment]
@whedon assign @njuaplusplus as reviewer

**Comment by danielskatz** [comment]
2

**Comment by terrytangyuan** [comment]
@njuaplusplus Thanks! 

@Kraks Would you be willing to review for this submission?

**Comment by Kraks** [comment]
@njuaplusplus @terrytangyuan Thanks for inviting me! Yes, I'm happy to review this submission.

**Comment by terrytangyuan** [comment]
@whedon add @Kraks as reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4151.

**Comment by terrytangyuan** [comment]
Thank you! @njuaplusplus and @Kraks. See you at https://github.com/openjournals/joss-reviews/issues/4151.

**Comment by bzz** [comment]
I'm sorry for the delay - I have started looking into reviewing the paper but got distracted and was not familiar with the workflow.

Is it too late and I shall stop, or would it be possible to join at #4151 ?
Thanks!

**Comment by terrytangyuan** [comment]
> I'm sorry for the delay - I have started looking into reviewing the paper but got distracted and was not familiar with the workflow.
> 
> Is it too late and I shall stop, or would it be possible to join at #4151 ? Thanks!

@bzz Yes you can still join! I just added you as reviewer as well.
