### ISSUE TITLE
[PRE REVIEW]: FlexWing-ROM: A matlab framework for data-driven reduced-order modeling of flexible wings

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4106]
**Submitting author:** @urban-fasel (<a href="http://orcid.org/0000-0002-3716-686X">Urban Fasel</a>)
**Repository:** https://github.com/urban-fasel/FlexWingROM
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @oriolcg, @omtazi
**Managing EiC:** Arfon Smith

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/70cc0af28cda2015132999136ce38eee/status.svg)](https://joss.theoj.org/papers/70cc0af28cda2015132999136ce38eee)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/70cc0af28cda2015132999136ce38eee"><img src="https://joss.theoj.org/papers/70cc0af28cda2015132999136ce38eee/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/70cc0af28cda2015132999136ce38eee/status.svg)](https://joss.theoj.org/papers/70cc0af28cda2015132999136ce38eee)
```

**Author instructions**

Thanks for submitting your paper to JOSS @urban-fasel. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@urban-fasel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1430

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.37 s (243.0 files/s, 61693.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                         520           7153          15352         106601
HTML                            37           1792           3627           9769
Markdown                         7            130              0            445
XSLT                             1             64             25            311
TeX                              1             30              0            277
GLSL                             2             15              7            155
XML                              5             12             28            118
CSS                              1             14              0             57
YAML                             1              0              0             11
-------------------------------------------------------------------------------
SUM:                           575           9210          19039         117744
-------------------------------------------------------------------------------


Statistical information for the repository 'd2ff388ae72b4622554afdaf' was
gathered on 2022/01/28.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S0962492902000077 is OK
- 10.1146/annurev.fluid.37.061903.175743 is OK
- 10.1016/j.jcp.2017.02.027 is OK
- 10.2514/3.55530 is OK
- 10.1117/12.776137 is OK
- 10.1016/j.paerosci.2012.06.001 is OK
- 10.1017/jfm.2013.163 is OK
- 10.2514/1.J055193 is OK

MISSING DOIs

- 10.1088/1361-665x/aa7c87 may be a valid DOI for title: Aerostructural optimization of a morphing wing for airborne wind energy applications
- 10.2514/1.j059621 may be a valid DOI for title: Concurrent Design and Flight Mission Optimization of Morphing Airborne Wind Energy Wings
- 10.1098/rspa.2020.0079 may be a valid DOI for title: Data-driven nonlinear aeroelastic models of morphing wings for control
- 10.1002/rnc.3586 may be a valid DOI for title: A method to construct reduced-order parameter-varying models
- 10.1016/j.ast.2021.106821 may be a valid DOI for title: The balanced mode decomposition algorithm for data-driven LPV low-order models of aeroservoelastic systems
- 10.1145/800186.810616 may be a valid DOI for title: A two-dimensional interpolation function for irregularly-spaced data
- 10.2514/1.j052715 may be a valid DOI for title: Aero-structural optimization of three-dimensional adaptive wings with embedded smart actuators
- 10.2514/1.j058019 may be a valid DOI for title: Reduced-order dynamic model of a morphing airborne wind energy aircraft
- 10.1242/jeb.204.12.2073 may be a valid DOI for title: Shape, flapping and flexion: wing and fin design for forward flight
- 10.1038/35089071 may be a valid DOI for title: Spanwise flow and the attachment of the leading-edge vortex on insect wings
- 10.1126/science.1142281 may be a valid DOI for title: Bat flight generates complex aerodynamic tracks
- 10.2514/1.36694 may be a valid DOI for title: Aeromechanics of membrane wings with implications for animal flight

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04106/joss.04106/10.21105.joss.04106.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04106/joss.04106/10.21105.joss.04106.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman @prashjha – I know you both have pretty full (editorial) plates right now. Are there any other JOSS editors you think could be a good fit here?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon If this remains waitlisted for too long feel free to assign it to me, I can take it if needed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@urban-fasel thanks for this submission. I am currently looking for reviewers. If you can suggest any reviewers that would be helpful too. You can mention their github handle (without the @ symbol) here. 

Could you clarify if this submission is compatible with Octave? Or does it require special MATLAB functions/toolboxes that are note part of Octave. I ask this as some reviewers can only review Octave rather than MATLAB submissions. Thanks.

**Comment by urban-fasel** [comment]
Hi @Kevin-Mattheus-Moerman, thanks for being the editor of our submission!
Some potential reviewers from the joss_reviewers list: vaishnavtv, wahls, mbudisic, balaje
and some additional potential reviewers: nairaditya, ben-herrmann, dylaneij, rschmehl, marconij
The submission is not compatible with Octave as it uses some functions that are not implemented in Octave yet.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @urban-fasel I'll have a look at those potential reviewers

**Comment by Kevin-Mattheus-Moerman** [comment]
@weymouth I was wondering if this submission on flexible wings featuring FSI is of interest to you and if you could review it for [JOSS](https://joss.theoj.org/). It does require MATLAB though. If you are not available/able, perhaps you could suggest a colleague? Thanks. 

Short paper: https://github.com/openjournals/joss-papers/blob/joss.04106/joss.04106/10.21105.joss.04106.pdf
Software: https://github.com/urban-fasel/FlexWingROM

**Comment by weymouth** [comment]
I don't use/have MATLAB. Looks interesting though.

**Comment by oriolcg** [comment]
HI @Kevin-Mattheus-Moerman , I'll be happy to review it, but I'll need some guidance on the process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @oriolcg as reviewer

**Comment by whedon** [comment]
OK, @oriolcg is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@oriolcg this is a prereview issue where we assign reviewers. Once we have at least two reviewers I'll trigger a review issue. In the review issue you'll have a checklist to go through which will guide you through the review process. Here is an example of a finished review issue: 
https://github.com/openjournals/joss-reviews/issues/3053

The process should be fairly smooth and self-explanatory, but if you want to learn more you can read all about it here too: 
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Let me know if you have any questions. Thanks for your help!

**Comment by Kevin-Mattheus-Moerman** [comment]
@chennachaos I feel like I'm close to "over inviting" you to review for JOSS, but do let me know if this work is your cup of tea, and would, despite the reliance on MATLAB, be interesting to review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@Nicola-Fonzi @dciliberti @Philipp-Conen @JaroslavHron @albansouche would you be interested in reviewing this submission for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/). The work is entitled: _A matlab framework for data-driven reduced-order modeling of flexible wings_. 

Note this submission is not Octave compatible so reviewing it does require a MATLAB installation. 

JOSS reviews take place on GitHub and focus on the review and evaluation of [the software](https://github.com/urban-fasel/FlexWingROM) as well as a [very short paper](https://github.com/openjournals/joss-papers/blob/joss.04106/joss.04106/10.21105.joss.04106.pdf). 

This is a pre-review issue where we find and assign reviewers. If you are interested I'll add you as a reviewer and once we have sufficient reviewers I'll trigger a dedicated review issue (see this example of a finished review issue: https://github.com/openjournals/joss-reviews/issues/2089). 

Thanks.

**Comment by Nicola-Fonzi** [comment]
Hi @Kevin-Mattheus-Moerman and thank you for being the reviewer of the paper! I am one of the authors so I guess I have to decline your invitation to review, but feel free to contact me in the future for other works

**Comment by Kevin-Mattheus-Moerman** [comment]
@Nicola-Fonzi my sincere apologies. I see you are on the paper, sorry I did not see your name as a contributor for the software (https://github.com/urban-fasel/FlexWingROM/graphs/contributors) so accidentally invited you.

**Comment by Nicola-Fonzi** [comment]
No worries, and thank you again for being the editor

**Comment by dciliberti** [comment]
Good evening,sorry I am not available. Best regards,Danilo Ciliberti Da: Kevin Mattheus MoermanInviato: martedì 22 febbraio 2022 14:49A: openjournals/joss-reviewsCc: Danilo Ciliberti; MentionOggetto: Re: [openjournals/joss-reviews] [PRE REVIEW]: FlexWing-ROM: A matlab framework for data-driven reduced-order modeling of flexible wings (Issue ***@***.*** @dciliberti @Philipp-Conen @JaroslavHron @albansouche would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS). The work is entitled: A matlab framework for data-driven reduced-order modeling of flexible wings.Note this submission is not Octave compatible so reviewing it does require a MATLAB installation.JOSS reviews take place on GitHub and focus on the review and evaluation of the software as well as a very short paper.This is a pre-review issue where we find and assign reviewers. If you are interested I'll add you as a reviewer and once we have sufficient reviewers I'll trigger a dedicated review issue (see this example of a finished review issue: #2089).Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by JaroslavHron** [comment]
Hi  @Kevin-Mattheus-Moerman - I am sorry but right now I am busy with other review duties.

**Comment by Kevin-Mattheus-Moerman** [comment]
@chennachaos :+1: no worries. Yeah you already deserve a medal for your other review efforts. Thanks for getting back to me.

**Comment by Kevin-Mattheus-Moerman** [comment]
@frederickgosselin thanks for your comment [on Twitter](https://twitter.com/FrdrckGssln/status/1497182840705929218?s=20&t=BZpuicZiW56P7QIdE4hMvw) it would be great to assign yourself or your student as reviewer. Let me know how to proceed.

**Comment by omtazi** [comment]
Hello @Kevin-Mattheus-Moerman, I am a student of @frederickgosselin and I would be happy to review this work.

**Comment by frederickgosselin** [comment]
Hi @Kevin-Mattheus-Moerman, Omar Tazi-Labzour @omtazi is a graduate student working with me at Polytechnique Montreal. I'll give him a hand with the review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot add @omtazi as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot start review
