### ISSUE TITLE
[PRE REVIEW]: swift-emulator: A Python package for emulation of simulated scaling relations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4107]
**Submitting author:** @Moyoxkit (<a href="http://orcid.org/0000-0003-0862-8639">Roi Kugel</a>)
**Repository:** https://github.com/SWIFTSIM/emulator
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @dfm
**Reviewers:** @JDonaldM, @kstoreyf
**Managing EiC:** Arfon Smith

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/61d082196ef861cc0b612486c1fa6d40/status.svg)](https://joss.theoj.org/papers/61d082196ef861cc0b612486c1fa6d40)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/61d082196ef861cc0b612486c1fa6d40"><img src="https://joss.theoj.org/papers/61d082196ef861cc0b612486c1fa6d40/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/61d082196ef861cc0b612486c1fa6d40/status.svg)](https://joss.theoj.org/papers/61d082196ef861cc0b612486c1fa6d40)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Moyoxkit. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@Moyoxkit if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1247

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (766.9 files/s, 103894.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          52           1821           2043           4069
reStructuredText                 9            241            369            445
Markdown                         4             90              0            381
TeX                              1             10              0            154
YAML                             2              4              6             45
DOS Batch                        1              8              1             26
Bourne Shell                     2              5              1             15
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            72           2183           2427           5144
-------------------------------------------------------------------------------


Statistical information for the repository 'dfb0ed94f64c16d6f235ff2f' was
gathered on 2022/01/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JBorrow                          5            72             45            0.88
Josh Borrow                    125          7331           1648           67.29
Moyoxkit                        40          3660            443           30.75
Roi Kugel                        4           115             29            1.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Josh Borrow                6181           84.3          8.6                6.28
Moyoxkit                   1717           46.9          9.9                6.00
Roi Kugel                    35           30.4         12.0               11.43
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TPAMI.2015.2448083 is OK
- 10.21105/joss.02430 is OK
- 10.1093/mnras/stu1536 is OK
- 10.1093/mnras/stv725 is OK
- 10.1093/mnras/stx2656 is OK
- 10.1093/mnras/stw2792 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04107/joss.04107/10.21105.joss.04107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04107/joss.04107/10.21105.joss.04107.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @dfm as editor

:wave: @dfm – this looks like it should be up your street. Would you be willing to edit this for us?

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

Sure - I'm happy to edit.

@Moyoxkit — give me a few days for an initial review and then I'll start recruiting reviewers. I'll keep you posted on the progress here, but let me know if you have any questions as the review progresses.

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@whedon add @JDonaldM as reviewer

Thanks Jamie for agreeing to review! Once we have a second reviewer lined up, we'll get the review rolling.

**Comment by dfm** [comment]
@Moyoxkit, @JDonaldM — I'm very sorry about the delay here. I'm still working on finding a second reviewer, but hope to be able to get the review started ASAP. Thanks for your patience!

**Comment by dfm** [comment]
@Moyoxkit: in the meantime, [as the bot requested above](https://github.com/openjournals/joss-reviews/issues/4107#issuecomment-1024745904), can you add a "Statement of need" section to the paper?

**Comment by Moyoxkit** [comment]
Should be added/changed now. @whedon generate pdf

**Comment by dfm** [comment]
@editorialbot add @kstoreyf as reviewer

Thanks Kate for agreeing to review, and thanks all for your patience! I'll get the main review started now in a new issue.
