### ISSUE TITLE
[PRE REVIEW]: CrysalGrowthTracker: A Python package for calculating the face advancment rates of crystals from videos taken using synchrotron radiation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4108]
**Submitting author:** @jonathanHuwP (<a href="http://orcid.org/0000-0001-5283-8065">Jonathan Pickering</a>)
**Repository:** https://github.com/jonathanHuwP/CrystalGrowthTracker
**Branch with paper.md** (empty if default branch): joss-submission
**Version:** v0.9
**Editor:** @lucydot
**Reviewers:** @CFGrote, @KedoKudo
**Managing EiC:** Arfon Smith

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/41293dd8310d7374a9bf87a1569912fb/status.svg)](https://joss.theoj.org/papers/41293dd8310d7374a9bf87a1569912fb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/41293dd8310d7374a9bf87a1569912fb"><img src="https://joss.theoj.org/papers/41293dd8310d7374a9bf87a1569912fb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/41293dd8310d7374a9bf87a1569912fb/status.svg)](https://joss.theoj.org/papers/41293dd8310d7374a9bf87a1569912fb)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jonathanHuwP. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Bisaloo.

@jonathanHuwP if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (444.4 files/s, 96091.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          54           1967           4581           5247
Qt                              13              0              0           2952
Markdown                         1             72              0             88
YAML                             1              0              0             12
-------------------------------------------------------------------------------
SUM:                            69           2039           4581           8299
-------------------------------------------------------------------------------


Statistical information for the repository '5e692f98668ec4334210b455' was
gathered on 2022/01/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Joanna Leng                     48          3930           1763            6.92
Jonathan Pickering             676         39134          37408           93.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Joanna Leng                 127            3.2         14.6                0.00
Jonathan Pickering        11668           29.8          6.4               18.43
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4108 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
PDF failed to compile for issue #4108 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Joanna Leng, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by arfon** [comment]
@jonathanHuwP – thanks for your submission to JOSS. The author affiliation strings need to be comma-separated (while being quoted, e.g.:

```
authors:
  - name: Joanna Leng^[co-first author]
    orcid: 0000-0001-9790-162X
    affiliation: "1,3"
  - name: Jonathan H. Pickering^[co-first author]
    affiliation: "2,3"
    orcid: 0000-0001-5283-8065
  - name: Sven L. M. Schroeder
    affiliation: "4,5,6,7"
  - name: Gunjen Das
    affiliation: "4,5,6,7"
```

Could you fix up your paper and ask @whedon to recompile with `@whedon generate pdf from branch joss-submission`

**Comment by arfon** [comment]
Also, adding the `waitlist` label here as we don't currently have capacity with the right editors to handle this submission right now. @jonathanHuwP I would expect a 2-3 week delay before an editor is assigned.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jonathanHuwP have you implemented the fix indicated :point_up: ?

**Comment by kthyng** [comment]
@lucydot Now that you've wrapped up another submission.... ready for this one?? :)

**Comment by kthyng** [comment]
@whedon invite @lucydot as editor

**Comment by whedon** [comment]
@lucydot has been invited to edit this submission.

**Comment by lucydot** [comment]
@kthyng I'm happy to edit this submission 💎

**Comment by lucydot** [comment]
@whedon assign @lucydot as editor

**Comment by whedon** [comment]
OK, the editor is @lucydot

**Comment by lucydot** [comment]
@whedon generate pdf from branch joss-submission

**Comment by lucydot** [comment]
> @jonathanHuwP – thanks for your submission to JOSS. The author affiliation strings need to be comma-separated (while being quoted, e.g.:
> 
> ```
> authors:
>   - name: Joanna Leng^[co-first author]
>     orcid: 0000-0001-9790-162X
>     affiliation: "1,3"
>   - name: Jonathan H. Pickering^[co-first author]
>     affiliation: "2,3"
>     orcid: 0000-0001-5283-8065
>   - name: Sven L. M. Schroeder
>     affiliation: "4,5,6,7"
>   - name: Gunjen Das
>     affiliation: "4,5,6,7"
> ```
> 
> Could you fix up your paper and ask @whedon to recompile with `@whedon generate pdf from branch joss-submission`

@jonathanHuwP it looks like there are still problems with the formatting of your submission. Please could you have a go at fixing as suggested in the quote block above?

**Comment by jonathanHuwP** [comment]
Hello,

Sorry for the delayed response.

I have picked out a set of possible reviewers, see the attached spreadsheet.

Thanks,
Jonathan
________________________________

**Comment by lucydot** [comment]
@jonathanHuwP I can't see anything attached (I'm not sure it is possible to attach something to a Github issue thread). Have you acted on the earlier message re: the formatting of your submission? Please visit the issue thread (if viewing through email) to see the full discussion.

**Comment by jonathanHuwP** [comment]
Hello Lucy,

I have found the original mail and corrected the author affiliation.

Regards,
Jonathan
________________________________

**Comment by lucydot** [comment]
@editorialbot set joss-submission as branch

**Comment by lucydot** [comment]
@jonathanHuwP I cannot see your list of proposed reviewers?...please post them directly in the thread (without the @ sign)

**Comment by lucydot** [comment]
@mikapfl @marcocamma @kedokudo @maurov are any of you available to review this submission? I can see you all have expertise in X-ray spectroscopy.

@jonathanHuwP can you confirm that yourself of one of the other authors will be available to participate in the review process over the next month-6 week period?

**Comment by mikapfl** [comment]
This software is not dealing with X-ray spectroscopy as far as I can see. At least the README talks about X-ray shadowgraphs, i.e. real-space images. My expertise is in X-ray scattering, i.e. reciprocal space images, with side knowledge about spectroscopy, i.e. frequency space images. I don't know enough about real-space images to review a software dealing with it meaningfully.

**Comment by maurov** [comment]
@lucydot thanks for the invitation to review this software, but as pointed out by @mikapfl, it is not dealing with X-ray spectroscopy, so I am not able to review it neither.

**Comment by KedoKudo** [comment]
@lucydot thanks for the invitation.  I have some experience with x-ray radiography and I think I should be able to review this package later this week.

**Comment by lucydot** [comment]
@CFGrote @stuartcampbell are either of you available to review this submission for JOSS? The one-line project description reads "This project extracts data on the growth rates of individual faces from x-ray video shadowgraphs of growing crystals." - it may be in or around your area of expertise?

**Comment by CFGrote** [comment]
I can review this submission but only after April 17 due to vacation and family requirements.

**Comment by lucydot** [comment]
Hi @CFGrote that timescale is fine from an editorial standpoint.

@KedoKudo are still able to do the review? If so, I'll start the process rolling now and @CFGrote can join once they are able.

**Comment by KedoKudo** [comment]
> Hi @CFGrote that timescale is fine from an editorial standpoint.
> 
> @KedoKudo are still able to do the review? If so, I'll start the process rolling now and @CFGrote can join once they are able.

yes, I can review this submission.

**Comment by lucydot** [comment]
@editorialbot add @CFGrote as reviewer

**Comment by lucydot** [comment]
@editorialbot add @KedoKudo as reviewer

**Comment by lucydot** [comment]
@editorialbot start review
