### ISSUE TITLE
[PRE REVIEW]: Cabana: A Performance Portable Library for Particle-Based Simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4109]
**Submitting author:** @streeve (<a href="http://orcid.org/0000-0002-4250-9476">Samuel Reeve</a>)
**Repository:** <a href="https://github.com/ECP-copa/Cabana" target ="_blank">https://github.com/ECP-copa/Cabana</a>
**Version:** 0.5
**Editor:** @diehlpk
**Reviewers:** @atmyers, @XzzX
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/70570727c0f968bbbc6d4fa49edf66b7/status.svg)](https://joss.theoj.org/papers/70570727c0f968bbbc6d4fa49edf66b7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/70570727c0f968bbbc6d4fa49edf66b7"><img src="https://joss.theoj.org/papers/70570727c0f968bbbc6d4fa49edf66b7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/70570727c0f968bbbc6d4fa49edf66b7/status.svg)](https://joss.theoj.org/papers/70570727c0f968bbbc6d4fa49edf66b7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @streeve. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @diehlpk.

@streeve if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (1075.6 files/s, 317555.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   101           6142           9893          30025
C++                             37            993           2269           3442
CMake                           36            164            446            747
YAML                             8             31              6            711
Dockerfile                       2             15              7            175
Markdown                         3             34              0            109
-------------------------------------------------------------------------------
SUM:                           187           7379          12621          35209
-------------------------------------------------------------------------------


Statistical information for the repository 'dc986b03be36a424c0239e07' was
gathered on 2022/01/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aaron Scheinberg                 3          1170            656            0.66
Alan Ayala                       1           176            122            0.11
Andrey Prokopenko                1            10              4            0.01
Christoph Junghans              15          6030           6895            4.68
Damien L-G                      85          1113           1245            0.85
Eric Medwedeff                   2            13              0            0.00
G. Chen                         26          2897           1431            1.57
GitHub Action                    2            24             15            0.01
Guangye Chen                     5            86             23            0.04
Rene Halver                     34          2244           1498            1.36
Robert Bird                     31           548            560            0.40
Robert Francis Bird              2           575             12            0.21
Sam                              3            28             62            0.03
Sam Reeve                      186         13552          36826           18.25
Shane Fogerty                    3           308            125            0.16
Shane Patrick Fogert            63          4352           1643            2.17
Stephan Schulz                  22          1092            183            0.46
Stuart Slattery                380        124446          57227           65.83
YuxingQiu                       47          5602           1954            2.74
ascheinb                         3             6              6            0.00
dalg24                           5            22             26            0.02
sfogerty                         7            15            679            0.25
uy7                              4           319            159            0.17

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alan Ayala                    3            1.7         17.1                0.00
Andrey Prokopenko            10          100.0         15.8                0.00
Christoph Junghans         3720           61.7         27.5                1.13
Damien L-G                  706           63.4         18.8                7.22
Eric Medwedeff               13          100.0         12.2               15.38
GitHub Action                10           41.7         12.2                0.00
Guangye Chen                 15           17.4         30.6               13.33
Robert Bird                 488           89.1         33.5               30.12
Sam                          19           67.9         34.2               26.32
Sam Reeve                  9930           73.3         12.3               38.61
Shane Patrick Fogert        353            8.1          7.9               12.46
Stephan Schulz              913           83.6          1.7               17.42
Stuart Slattery            3069            2.5         10.7                9.94
YuxingQiu                  3442           61.4         12.6               19.76
uy7                       30073         9427.3         28.7               25.30
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4109 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by streeve** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04109/joss.04109/10.21105.joss.04109.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04109/joss.04109/10.21105.joss.04109.pdf) :page_facing_up: :point_left:

**Comment by streeve** [comment]
We'd like to suggest XzzX and atmyers as reviewers

**Comment by arfon** [comment]
@whedon invite @diehlpk as editor

:wave: @diehlpk – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@diehlpk has been invited to edit this submission.

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
Hi @arfon I am happy to edit the paper. However, I have to declare that one of the authors and I have contributed code to the same repository a few years ago.

**Comment by diehlpk** [comment]
Hi @XzzX and @atmyers would you be interested in reviewing this paper?

**Comment by atmyers** [comment]
@diehlpk Yes, I'd be able to review.

**Comment by XzzX** [comment]
@diehlpk Yes, I would also review the paper.
Please note, I am a user of this software for about half a year and filed a few issues, but I am by no means a developer.

**Comment by diehlpk** [comment]
@whedon assign @atmyers as reviewer

**Comment by whedon** [comment]
OK, @XzzX is now a reviewer

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4115.
