### ISSUE TITLE
[PRE REVIEW]: GBOML: Graph-Based Optimization Modeling Language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4110]
**Submitting author:** @MiftariB (<a href="http://orcid.org/0000-0001-5334-0234">Bardhyl Miftari</a>)
**Repository:** <a href="https://gitlab.uliege.be/smart_grids/public/gboml" target ="_blank">https://gitlab.uliege.be/smart_grids/public/gboml</a>
**Version:** v0.1.0
**Editor:** @fraukewiese
**Reviewers:** @odow, @leonardgoeke
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/29a98e5ccf2778eb41c8b725a809e51b/status.svg)](https://joss.theoj.org/papers/29a98e5ccf2778eb41c8b725a809e51b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/29a98e5ccf2778eb41c8b725a809e51b"><img src="https://joss.theoj.org/papers/29a98e5ccf2778eb41c8b725a809e51b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/29a98e5ccf2778eb41c8b725a809e51b/status.svg)](https://joss.theoj.org/papers/29a98e5ccf2778eb41c8b725a809e51b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @MiftariB. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sjpfenninger.

@MiftariB if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1119

**Comment by whedon** [comment]
PDF failed to compile for issue #4110 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: tags (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (672.4 files/s, 113595.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          42           2574           1795           6915
JSON                             8              0              0           1735
reStructuredText                29            537            640            424
TeX                              1             18              0            176
Markdown                         4             39              0             79
YAML                             2              8              2             36
DOS Batch                        1              8              1             26
make                             1              4              7              9
TOML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            89           3188           2445           9403
-------------------------------------------------------------------------------


Statistical information for the repository '5014cfd42cb889b309bc9fb1' was
gathered on 2022/01/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AdrienBolland                    1            21             22            0.12
Bardh                          140         17830          10443           80.85
Christophe Druet                 1             1              0            0.00
Hatim Djelassi                  20           690            471            3.32
Mathias Berger                   5          1449             23            4.21
MiftariB                        18          3163            855           11.49

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bardh                     10853           60.9          4.8                6.62
Hatim Djelassi              103           14.9         11.1                0.00
Mathias Berger               82            5.7          0.5               46.34
MiftariB                    246            7.8          4.7                5.28
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1137/15M1020575 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/s12532-011-0026-8 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/s12532-012-0036-1 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1287/mnsc.36.5.519 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/s12532-009-0008-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/978-1-4613-0215-5_8 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.5334/jors.188 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.23919/PSCC.2018.8442948 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.21105/joss.00825 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.esr.2018.01.003 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.enpol.2011.06.033 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.3389/fenrg.2021.671279 is INVALID because of 'https://doi.org/' prefix
```

**Comment by MiftariB** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04110/joss.04110/10.21105.joss.04110.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04110/joss.04110/10.21105.joss.04110.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @fraukewiese as editor

:wave: @fraukewiese – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@fraukewiese has been invited to edit this submission.

**Comment by arfon** [comment]
@MiftariB - could you please remove the `https://doi.org/` prefixes from your BibTeX file? For example, `https://doi.org/10.3389/fenrg.2021.671279` should be `fenrg.2021.671279`

**Comment by MiftariB** [comment]
Might be a mistake on my end but I think I already removed the prefixes yesterday after I asked whedon to regenerate the pdf (I also forgot to put tags which is fixed now) as you can see here : https://gitlab.uliege.be/smart_grids/public/gboml/-/blob/master/paper/references.bib. 

Sorry for the inconvenience, 

Regards, 

MIFTARI B

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/15M1020575 is OK
- 10.1007/s12532-011-0026-8 is OK
- 10.1007/s12532-012-0036-1 is OK
- 10.1287/mnsc.36.5.519 is OK
- 10.1007/s12532-009-0008-2 is OK
- 10.1007/978-1-4613-0215-5_8 is OK
- 10.5334/jors.188 is OK
- 10.23919/PSCC.2018.8442948 is OK
- 10.21105/joss.00825 is OK
- 10.1016/j.esr.2018.01.003 is OK
- 10.1016/j.enpol.2011.06.033 is OK
- 10.3389/fenrg.2021.671279 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@MiftariB - yes, looks good, thanks

**Comment by fraukewiese** [comment]
Yes I can edit this paper.

@whedon assign me as editor

**Comment by fraukewiese** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fraukewiese

**Comment by fraukewiese** [comment]
@simnh, @nworbmot, @abhishek0208
– would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: [https://joss.readthedocs.io/en/latest/reviewer_guidelines.html](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

The submission under review here is [GBOML: Graph-Based Optimization Modeling Language](https://gitlab.uliege.be/smart_grids/public/gboml)

**Comment by MiftariB** [comment]
Dear @fraukewiese, 

Can i also suggest @odow and @matbesancon as potential reviewers ? 

Regards, 

Miftari B

**Comment by odow** [comment]
I can do it (I'm one of the JuMP developers).

**Comment by fraukewiese** [comment]
@odow : Thank you very much! I will assign you as reviewer. We will start the review as soon as a second reviewer will agree to review.

**Comment by fraukewiese** [comment]
@whedon add @odow as reviewer

**Comment by whedon** [comment]
OK, @odow is now a reviewer

**Comment by fraukewiese** [comment]
@simnh, @nworbmot, @abhishek0208 @matbesancon 
We already found one reviewer, but we need two, so it would be great if one of you could additionally review this submission.

**Comment by abhishek0208** [comment]
Hi @fraukewiese, sorry but I'm going to have to decline. Thanks for the invitation to review.

**Comment by MiftariB** [comment]
Dear @fraukewiese,

In case none of the reviewers respond, we went through the list of JOSS reviewers and think that brynpickering, timtroendle, fneum and sevberg could be potential reviewers for the submission.

Regards, 

Miftari B

**Comment by matbesancon** [comment]
Dear @fraukewiese, thank you for reaching out, I sadly won't be able to review this paper

**Comment by fraukewiese** [comment]
@matbesancon : Thanks for the reply!

**Comment by fraukewiese** [comment]
@MiftariB : Thanks for the suggestions. I try to reach out to the two requested reviewers who have not yet replied by Mail. If I get negative answers, I will come back to your suggestions.

**Comment by fraukewiese** [comment]
simnh and nworbmot declined via Mail.

**Comment by leonardgoeke** [comment]
I can do it.

**Comment by fraukewiese** [comment]
Great. Thanks @leonardgoeke

**Comment by fraukewiese** [comment]
@whedon add @leonardgoeke as reviewer

**Comment by whedon** [comment]
OK, @leonardgoeke is now a reviewer

**Comment by fraukewiese** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4158.

**Comment by fraukewiese** [comment]
@leonardgoeke @odow – thanks a lot for agreeing to review here! See you over in https://github.com/openjournals/joss-reviews/issues/4158 where the actual review will take place.
