### ISSUE TITLE
[PRE REVIEW]: SwiftVISA: Controlling Instrumentation with a Swift-based Implementation of the VISA Communication Protocol #4068

### ISSUE THREAD

**Issue by OHildreth** [openjournals/joss-reviews#4111]
STOP STOP STOP STOP STOP
STOP STOP STOP STOP STOP
👇 ================================== 👇

Issues in this repository are automatically generated by the journal submission system. DO NOT FILE ISSUES HERE.

If you have a question about JOSS then please open an issue on the main JOSS repository: https://github.com/openjournals/joss

☝ ================================== ☝

THANKS FOR NOT OPENING AN ISSUE HERE

Hi,
 Sorry for missing on the comments.  This is my first time using this type of review process.

I was hoping to get more information about why this article didn't meet the "Substantial scholarly effort" criteria.  I think the issue might be how we divided up the work between multiple packages that built upon one another but allowed users to select either a pure Swift implementation (SwiftVISASwift) or ones that relied upon the pre-compiled VISA framework to varying degrees.  This split was necessary because different operating systems have different requirements.  

I think I linked to SwiftVISASwift instead of the top-level SwiftVISA Organization (https://github.com/SwiftVISA).  Our project included over 7,000 lines of code within the SwiftVISA organization spread across 9 different repositories so that the code could be shared between the different implementations.  This made the SwiftVISASwift implementation look much smaller than it actually is.

I can see about moving the paper.md to the organization's page if that would help.

Thanks for your help,

 Owen Hildreth

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4111 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by OHildreth** [comment]
https://github.com/SwiftVISA/SwiftVISASwift/tree/paper

The paper is in the SwiftVISASwift repository in the "paper" tree.

**Comment by danielskatz** [comment]
If you have a question about JOSS then please open an issue on the main JOSS repository: https://github.com/openjournals/joss
