### ISSUE TITLE
[PRE REVIEW]: NGSTrefftz: Add-on to NGSolve for Trefftz methods

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4112]
**Submitting author:** @PaulSt (<a href="http://orcid.org/0000-0001-5073-3366">Paul Stocker</a>)
**Repository:** <a href="https://github.com/PaulSt/NGSTrefftz" target ="_blank">https://github.com/PaulSt/NGSTrefftz</a>
**Version:** v0.0.0
**Editor:** @Nikoleta-v3
**Reviewers:** @mscroggs, @thelfer 
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c2f4e85b118c22b81aa27d7799265409/status.svg)](https://joss.theoj.org/papers/c2f4e85b118c22b81aa27d7799265409)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c2f4e85b118c22b81aa27d7799265409"><img src="https://joss.theoj.org/papers/c2f4e85b118c22b81aa27d7799265409/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c2f4e85b118c22b81aa27d7799265409/status.svg)](https://joss.theoj.org/papers/c2f4e85b118c22b81aa27d7799265409)
```

**Author instructions**

Thanks for submitting your paper to JOSS @PaulSt. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @meg-simula.

@PaulSt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 545

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (667.7 files/s, 140590.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             11            498            311           3260
C/C++ Header                     9            254             98           1158
Jupyter Notebook                11              0           1810            731
Python                           7            137            334            585
TeX                              1             14              0            117
YAML                             1              8              2            106
Markdown                         2             19              0             81
CMake                            1             10              5             54
Dockerfile                       2             15             15             40
JSON                             1              0              0             23
-------------------------------------------------------------------------------
SUM:                            46            955           2575           6155
-------------------------------------------------------------------------------


Statistical information for the repository 'cbbae1bb7d6d33ddf4cfe316' was
gathered on 2022/01/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Paul                           666         43191          36793           96.72
Paul Stocker                     5             9            442            0.55
PaulSt                          33          1392            871            2.74

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Paul                        644            1.5         39.1                7.14
Paul Stocker               5991        66566.7         12.3               10.95
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.camwa.2020.01.006 is OK
- 10.1007/s00211-017-0910-x is OK
- 10.1007/978-3-319-41640-3_8 is OK

MISSING DOIs

- 10.1115/1.1995716 may be a valid DOI for title: Trefftz finite element method and its applications
- 10.1016/0965-9978(95)00067-4 may be a valid DOI for title: Trefftz method: an overview 

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04112/joss.04112/10.21105.joss.04112.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04112/joss.04112/10.21105.joss.04112.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @Nikoleta-v3 as editor

:wave: @Nikoleta-v3 – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@Nikoleta-v3 has been invited to edit this submission.

**Comment by Nikoleta-v3** [comment]
👋 @arfon - I am happy to edit this submission but my C++ is a bit rusty 😅 is this okay?

**Comment by Kevin-Mattheus-Moerman** [comment]
@Nikoleta-v3 It is okay if your C++ is rusty. As long as you can judge the overall quality of the work well, are able to find suitable reviewers, and can interpret reviewer comments on quality and issues with the software. I'll go ahead and assign you but let me know if there are any issues.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Nikoleta-v3 as editor

**Comment by whedon** [comment]
OK, the editor is @Nikoleta-v3

**Comment by Nikoleta-v3** [comment]
Great, thank you @Kevin-Mattheus-Moerman !

**Comment by Nikoleta-v3** [comment]
Hey 👋🏻 @PaulSt thank you again for your submission with JOSS, could you please:

- 1️⃣  take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers 
- 2️⃣  check and fix the missing DOIs: https://github.com/openjournals/joss-reviews/issues/4112#issuecomment-1025166198

**Comment by PaulSt** [comment]
Hi :wave: @Nikoleta-v3 and thank you for reviewing my submission. 
- I would suggest mscroggs and Balaje as reviewers
- the DOIs should be fixed now

**Comment by PaulSt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04112/joss.04112/10.21105.joss.04112.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04112/joss.04112/10.21105.joss.04112.pdf) :page_facing_up: :point_left:

**Comment by Nikoleta-v3** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.camwa.2020.01.006 is OK
- 10.1007/s00211-017-0910-x is OK
- 10.1115/1.1995716 is OK
- 10.1016/0965-9978(95)00067-4 is OK
- 10.1007/978-3-319-41640-3_8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Nikoleta-v3** [comment]
Perfect, thank you @PaulSt! Could you please suggest two more reviewers? 😄

**Comment by Nikoleta-v3** [comment]
👋 @mscroggs &  @Balaje & @felipefr & @sigvaldm would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "NGSTrefftz: Add-on to NGSolve for Trefftz methods ". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by mscroggs** [comment]
:wave: I'd be happy to review this

**Comment by Nikoleta-v3** [comment]
@whedon assign @mscroggs as reviewer

**Comment by whedon** [comment]
OK, @mscroggs is now a reviewer

**Comment by Nikoleta-v3** [comment]
Thank you 🙏🏻

**Comment by sigvaldm** [comment]
Would love to, but I'm really busy for at least the entire February, so if there's someone else that can do it sooner then that would be better for the author.

**Comment by Nikoleta-v3** [comment]
👋 @thelfer & @capitalaslash & @yangbai90 would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "NGSTrefftz: Add-on to NGSolve for Trefftz methods ". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by thelfer** [comment]
@Nikoleta-v3 Don't know Trefftz methods, but the method seems worth investigating. And it will be the occasion to learn a bit more about `NGSolve`, which I don't know either. If you don't expect the review for tomorrow,  I would be quite interested to review the paper. I could do that in the coming month.

**Comment by Nikoleta-v3** [comment]
Hey @thelfer! That’s absolutely fine on my end 😄  I will assign you as a reviewer now – thank you for your time!

**Comment by Nikoleta-v3** [comment]
@whedon add @thelfer  as reviewer

**Comment by whedon** [comment]
OK, @thelfer  is now a reviewer

**Comment by Nikoleta-v3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4135.
