### ISSUE TITLE
[PRE REVIEW]: E2EDNA 2.0: Python Pipeline for Simulating DNA Aptamers with Ligands

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4116]
**Submitting author:** @taoliu032 (<a href="http://orcid.org/0000-0002-1082-5570">Tao Liu</a>)
**Repository:** <a href="https://github.com/siminegroup/E2EDNA2" target ="_blank">https://github.com/siminegroup/E2EDNA2</a>
**Version:** v1.0
**Editor:** @csoneson
**Reviewers:** @JoaoRodrigues, @rvhonorato
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/313422a651f2ff1ad183e898f4f5f5a3/status.svg)](https://joss.theoj.org/papers/313422a651f2ff1ad183e898f4f5f5a3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/313422a651f2ff1ad183e898f4f5f5a3"><img src="https://joss.theoj.org/papers/313422a651f2ff1ad183e898f4f5f5a3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/313422a651f2ff1ad183e898f4f5f5a3/status.svg)](https://joss.theoj.org/papers/313422a651f2ff1ad183e898f4f5f5a3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @taoliu032. **Currently, there isn't an JOSS editor assigned** to your paper.

@taoliu032 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4116 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.24 s (238.0 files/s, 67327.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              9              0              0           7642
Python                          36           1410           1607           4910
Markdown                         8             70              0            182
YAML                             1              1              0            172
Bourne Shell                     3             26             15             90
-------------------------------------------------------------------------------
SUM:                            57           1507           1622          12996
-------------------------------------------------------------------------------


Statistical information for the repository 'f841f8a3fe7a1563639de96d' was
gathered on 2022/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ISDementyev                     95           486            303            2.60
InfluenceFunctional             30         16125           9003           82.90
Tao Liu                         70          2448           1945           14.49
siminegroup                      1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ISDementyev                 129           26.5          5.5                4.65
InfluenceFunctional        6252           38.8          3.8                9.77
Tao Liu                    1546           63.2          2.2               22.45
```

**Comment by taoliu032** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04116/joss.04116/10.21105.joss.04116.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04116/joss.04116/10.21105.joss.04116.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @will-rowe as editor

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@taoliu032 I have just `waitlisted` this submission since none of the editors in the bioinformatics domain are currently available. We will assign an editor once one becomes available.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @csoneson as editor

@csoneson do you think you'd be able to help edit this submission?

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by taoliu032** [comment]
@Kevin-Mattheus-Moerman Thank you very much! I was just wondering today if I should follow up :)

**Comment by csoneson** [comment]
👋🏻 @taoliu032 - I had a quick look at the submission, and I was wondering if you could perhaps quickly clarify a couple of things before we move on: 

* The relation to E2EDNA ([repo](https://github.com/InfluenceFunctional/E2EDNA), [paper](https://pubs.acs.org/doi/10.1021/acs.jcim.1c00696)) - admittedly this is not really my field of expertise, but it wasn't totally clear to me. The paper mentions that E2EDNA 2.0 is more user-friendly and easier to install, but it wasn't obvious if there are other significant additions/advantages/differences, and whether you would recommend E2EDNA users to switch to E2EDNA 2.0, or if they are to some extent complementary and you plan to maintain both going forward (the paper denotes them as predecessor/successor, but I couldn't see e.g. a note in the E2EDNA repo pointing people to E2EDNA 2.0). 
* I see only instructions for installation on macOS, and a file `macos_installation.sh` in the repo - do you expect it to work also for other operating systems, or is there an inherent restriction to macOS? I suspect the provided environment yml file will not be portable. 

Thanks!

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
@taoliu032 Thanks! I'll start by looking for a couple of suitable reviewers for this submission - if you have any suggestions (e.g. from the list in the first comment above), feel free to mention them here.

**Comment by csoneson** [comment]
👋🏻 @ayush9pandey, @ayaanhossain - would you be interested in reviewing this submission for JOSS? 

> E2EDNA 2.0: Python Pipeline for Simulating DNA Aptamers with Ligands

**Comment by ayush9pandey** [comment]
I don't think I have the right expertise to be a reviewer for this submission, so I'll pass.

**Comment by taoliu032** [comment]
@csoneson thank you so much! 
After going through the list looking for reviewers in computational chemistry/molecular dynamics simulation particularly, here are two suggestions: **JoaoRodrigues** and **rvhonorato** - both are GitHub handles. However, I do not know about either of them and there are so many experts under the same categories. Therefore, feel free to select any reviewers as you see fit :) Have a wonderful week!

**Comment by csoneson** [comment]
@ayush9pandey - no problem, thanks for responding!

**Comment by csoneson** [comment]
👋🏻 @JoaoRodrigues, @rvhonorato - would you be interested in reviewing this submission for JOSS? 

> E2EDNA 2.0: Python Pipeline for Simulating DNA Aptamers with Ligands

**Comment by rvhonorato** [comment]
Thanks for the invite @csoneson and for the suggestion @taoliu032. 

Yes I'd like to review this one!

**Comment by csoneson** [comment]
Brilliant, thanks @rvhonorato! Once we have one more reviewer we'll start the actual review issue where you'll have your checklist etc.

**Comment by taoliu032** [comment]
@csoneson May I ask to slightly modify the code? One of the toggles was not perfectly set up but it does not affect the backbone or main features of the code at all. I literally just need to edit one line and delete a few.

This is my first ever submission to JOSS (very exciting experience!), so I am not sure if I could make changes to the code at the moment or if I should wait till the official review starts to bring up this request. I wonder if you could point out what action would be deemed to be most appropriate?

My apologies for any inconvenience! Thank you very much!

**Comment by csoneson** [comment]
@taoliu032 - yes, feel free to go ahead and make this change. Once the review has started, it may be good to refrain from making major changes at the very same time that the reviewers are going through the code, just because it may become very confusing which version should be checked :)

**Comment by taoliu032** [comment]
@csoneson Thank you for clarification! I have just made the change to the JOSS branch. Yes exactly, I do not intend to confuse any reviewers therefore the JOSS branch will become off limits once the review starts 🙂

**Comment by csoneson** [comment]
Pinging @JoaoRodrigues and @ayaanhossain - would one of you be interested in reviewing this submission for JOSS?

> E2EDNA 2.0: Python Pipeline for Simulating DNA Aptamers with Ligands

**Comment by csoneson** [comment]
@whedon assign @JoaoRodrigues as reviewer

**Comment by whedon** [comment]
OK, @JoaoRodrigues is now a reviewer

**Comment by csoneson** [comment]
@whedon add @rvhonorato as reviewer

**Comment by whedon** [comment]
OK, @rvhonorato is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4182.
