### ISSUE TITLE
[REVIEW]: geneXplainR: An R interface for the geneXplain platform

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#412]
**Submitting author:** @pstegma (<a href="http://orcid.org/0000-0002-1881-8746">Philip Stegmaier</a>)
**Repository:** <a href="https://github.com/genexplain/geneXplainR" target ="_blank">https://github.com/genexplain/geneXplainR</a>
**Version:** 0.4
**Editor:** @mgymrek
**Reviewer:** @selbouhaddani
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1013318" target="_blank">10.5281/zenodo.1013318</a>

## Status

[![status](http://joss.theoj.org/papers/f9e01bf1a9649a3ab078215c81bb6f12/status.svg)](http://joss.theoj.org/papers/f9e01bf1a9649a3ab078215c81bb6f12)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f9e01bf1a9649a3ab078215c81bb6f12"><img src="http://joss.theoj.org/papers/f9e01bf1a9649a3ab078215c81bb6f12/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f9e01bf1a9649a3ab078215c81bb6f12/status.svg)](http://joss.theoj.org/papers/f9e01bf1a9649a3ab078215c81bb6f12)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/genexplain/geneXplainR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@selbouhaddani, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/genexplain/geneXplainR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.4)?
- [x] **Authorship:** Has the submitting author (@pstegma) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @selbouhaddani it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by selbouhaddani** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by selbouhaddani** [comment]
# General

The submission describes an R package "*geneXplainR*" that provides an interface to connect to an external platform "geneXplain". By using the R package queries can be submitted and results can be retrieved from the platform. This can be done without leaving the R environment.

Overall I think this is a submission suited for the JOSS. The R package enables access to bioinformatics tools and workflows used by bioinformatics experts and researchers from R, from which additional R functionalities can be used to further process the results. Although the platform is closed source, the R package is open source and there is an option to freely register to get an account.

# Comments

## Usage

- There is a small typo in the README.md: `gx.login("http://genexample.com/bioumlweb","user","password"),` 
Please remove the last comma.
- The first argument of the function `gx.login` in the README.md is `"http://genexample.com/bioumlweb"` which does not work (I got an error: `Could not resolve host: genexample.com`). Perhaps an alternative is to just use `"https://platform.genexplain.com"` as this is the default value. In addition I couldn't find any other web addresses in the documentation that could also be inserted as argument, it is a good idea to give examples e.g. in the help file of `gx.login`.
- In section **Example** in the README.md in the *examples* branch a code chunk is shown in which a functional classification analysis of a gene set is discussed. Currently this chunk only works if the user already has uploaded some dataset in the correct format. 
It's not strictly necessary, but I think availability of a toy dataset would be very appreciated by the user, so that this code runs without having to construct and upload datasets. This would help understanding the code and the functionalities. 

## Paper.md

In my opinion the paper.md file is well written and well structured. Some minor comments are:

- In "*Methods integrated into the system integrates include*", the word "*integrates*" should be removed.
- Unfortunately it is not clear where to report issues or seek support. Should the user use the Github Issue system, or go to the genexplain website? Please add a statement to clarify this.
- The citations in the `paper.bib` file do not include doi's, while they are available (e.g. the article corresponding to *@upstreamAnalysis* has doi 10.3390/microarrays4020270). If I interpret the last checkmark correctly, the available doi's should be added.

Please let me know if anything was unclear.

**Comment by pstegma** [comment]
Thank you for the comments. I am working on the suggested improvements.

**Comment by pstegma** [comment]
First of all, many thanks again to the reviewer for spending time with the review and for his very helpful comments which we are certain help to improve the quality of the software. We think we were able to implement all of the requested points. Please find below our detailed response.

# Replies to reviewer comments

## Usage

The comma typo as well as the misspelled URL were corrected. More examples 
and instructions how to call the `gx.login` function were added to the README.md as well as to the geneXplain.R source file. 
The following sentences were added to the Usage section of the README.md:

```Markdown
If you just wish to try out the functionality of geneXplainR, you can sign into the demo account on our
public server *platform.genexplain.com* by simply calling *gx.login()*, without parameters. To access another server that
provides a demo workspace, you can call *gx.login* with the server URL as only argument.
```

The following executable examples were added to the roxygen of `gx.login` in R/geneXplain.R:

```R
 #'
 #' @examples
 #'
 #' # Sign into demo account on public server
 #' gx.login()
 #' gx.logout()
 #' # Sign into demo account specifying server URL
 #' gx.login("https://platform.genexplain.com")
 #' gx.logout()
 #'
```

The Example section in the README.md of the *examples* branch was updated
and now contains the following executable R code which entirely relies on
existing example data and demo workspace:

```R
## Login to demo account
gx.login()

## Example data sets can be found under 'data/Examples'. Here we use a set of upregulated genes.
my_data <- paste0("data/Examples/TNF-stimulation of HUVECs GSE2639, ",
                  "Affymetrix HG-U133A microarray/Data/DEGs with limma/",
                  "Normalized (RMA) DEGs with limma/Condition_1 vs. Condition_2/",
                  "Up-regulated genes Ensembl")

## This will be the path to the result table. It will be put into the 'Demo project' provided
##  in this workspace.
my_result <- paste0("data/Projects/Demo project/Data/",
                    "my_demo_result_",
                    Sys.Date(),"_",
                    floor(runif(1, 1, 10^12)))

## This invokes the functional classification analysis according
## to the Gene Ontology.
gx.analysis("Functional classification",
             list(sourcePath = my_data,
             species = "Human (Homo sapiens)",
             bioHub = "Full gene ontology classification",
             outputTable = my_result));
                
## This command loads the result table into an R data frame.
data <- gx.get(my_result)
```

## Paper.md

Support sections describing where to report issues were added to the README.md of the master branch as well as to the paper.

The dois and doi URLs were added to citations in paper.bib.

**Comment by selbouhaddani** [comment]
Thank you for addressing all the remarks. I went through the package again and verified that all JOSS requirements are met. 
@mgymrek I'm satisfied with the current submission.

**Comment by mgymrek** [comment]
Thanks @selbouhaddani for the review. I have looked through the comments and response and everything looks good. 
@arfon I think we are ready to accept this submission.

**Comment by arfon** [comment]
@pstegma - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by pstegma** [comment]
@arfon - This is the DOI 10.5281/zenodo.1013318 .

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1013318 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1013318" target="_blank">10.5281/zenodo.1013318</a> is the archive.

**Comment by arfon** [comment]
@selbouhaddani - many thanks for your review and to @mgymrek for editing this submission ✨ 

@pstegma - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00412 ⚡️ 🚀 💥

**Comment by pstegma** [comment]
@selbouhaddani  @mgymrek  @arfon  Great news, we are very glad about the paper being accepted. Many thanks to everyone!
