### ISSUE TITLE
[REVIEW]: QDistRnd: A GAP package for computing the distance of quantum error-correcting codes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4120]
**Submitting author:** @LeonidPryadko (<a href="http://orcid.org/0000-0002-4990-0259">Leonid P. Pryadko</a>)
**Repository:** https://github.com/QEC-pages/QDistRnd/
**Branch with paper.md** (empty if default branch): 
**Version:** 0.8.5
**Editor:** @danielskatz
**Reviewers:** @oscarhiggott, @pan-pavel
**Archive:** 10.5281/zenodo.6374733

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3f7bbe8765963b577608064456e69405/status.svg)](https://joss.theoj.org/papers/3f7bbe8765963b577608064456e69405)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3f7bbe8765963b577608064456e69405"><img src="https://joss.theoj.org/papers/3f7bbe8765963b577608064456e69405/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3f7bbe8765963b577608064456e69405/status.svg)](https://joss.theoj.org/papers/3f7bbe8765963b577608064456e69405)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/QEC-pages/QDistRnd/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@oscarhiggott & @pan-pavel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @oscarhiggott
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/QEC-pages/QDistRnd/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/QEC-pages/QDistRnd/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@LeonidPryadko) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @pan-pavel
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/QEC-pages/QDistRnd/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/QEC-pages/QDistRnd/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@LeonidPryadko) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @oscarhiggott, @pan-pavel it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1143

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (301.0 files/s, 61771.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
ANTLR Grammar                    7            142              0           1209
TeX                              2             43              0            992
Markdown                         2             28              0            182
YAML                             2              6              9             57
-------------------------------------------------------------------------------
SUM:                            13            219              9           2440
-------------------------------------------------------------------------------


Statistical information for the repository '2e71ddffd5114c1a811dd9db' was
gathered on 2022/02/01.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ISIT.2009.5205648 is OK
- 10.1103/PhysRevLett.122.230501 is OK
- 10.1103/PhysRevA.102.062402 is OK
- 10.1103/PhysRevA.88.012311 is OK
- 10.1063/1.4891487 is OK
- 10.22331/q-2021-11-22-585 is OK
- 10.1109/TIT.2015.2422294 is OK
- 10.1006/jsco.1996.0125 is OK
- 10.1103/PhysRevA.87.020304 is OK
- 10.18154/RWTH-2018-01100 is OK
- 10.1109/ICC.2004.1312605 is OK
- 10.1109/ISIT.2008.4595332 is OK
- 10.1109/TIT.2017.2690381 is OK
- 10.1109/18.21270 is OK
- 10.1109/18.57202 is OK

MISSING DOIs

- 10.1016/j.swevo.2020.100797 may be a valid DOI for title: Genetic algorithms with permutation-based representation for computing the distance of linear codes
- 10.1109/tit.2021.3119384 may be a valid DOI for title: Quantum LDPC Codes with Almost Linear Minimum Distance

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04120/joss.04120/10.21105.joss.04120.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04120/joss.04120/10.21105.joss.04120.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@oscarhiggott and @pan-pavel - Thanks for agreeing to review this submission.
This is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

Please read the first couple of comments in this issue carefully, so that you can accept the invitation from JOSS and be able to check items, and so that you don't get overwhelmed with notifications from other activities in JOSS.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#4120` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 3-4 weeks. Please let me know if either of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@danielskatz) if you have any questions/concerns.

**Comment by danielskatz** [comment]
@pan-pavel - I saw you tried to open a couple of issues using the GitHub Convert to issue functionality when working through this checklist. Instead, please open any new issues associated with your review in the [software repository associated with the submission](https://github.com/QEC-pages/QDistRnd/) and mention `openjournals/joss-reviews#4120` so that a link is created to this thread (and I can keep an eye on what is happening)

**Comment by danielskatz** [comment]
I've done this for you in these cases, as you can see above

**Comment by pan-pavel** [comment]
> I've done this for you in these cases, as you can see above
> 
Thanks a lot, Daniel!

**Comment by danielskatz** [comment]
👋 @oscarhiggott and @pan-pavel - this is just a quick check-in here a week into the process.

@oscarhiggott, it looks like you haven't yet accepted [the GitHub invitation](https://github.com/openjournals/joss-reviews/invitations) to the review process. Please do when you have a minute, as described in the first two comments in this issue.

@pan-pavel - thanks for starting your review, checking-off items, and adding issues where you've found problems.

@LeonidPryadko - thanks for responding to some of the issues so far.

**Comment by oscarhiggott** [comment]
Hi @danielskatz, I just accepted the GitHub invitation but I still can't seem to edit the checklist for some reason, do you know why that is? Thanks!

**Comment by danielskatz** [comment]
I'm not sure. One possibility is that you have multiple github accounts.  Another is that something just went wrong, so we can try again

**Comment by danielskatz** [comment]
@whedon re-invite @oscarhiggott as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@oscarhiggott please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by oscarhiggott** [comment]
Great, thanks @danielskatz, all working now

**Comment by LeonidPryadko** [comment]
Two problems have been corrected and the corresponding issues closed on the GitHub page for the program.

**Comment by danielskatz** [comment]
👋 @oscarhiggott, @pan-pavel - I just wanted to check with you both again and see how your reviews are coming, and if there's anything blocking you that either I or @LeonidPryadko can help with

**Comment by oscarhiggott** [comment]
Hi @danielskatz I hope to complete the review soon, nothing blocking me at the moment thanks

**Comment by danielskatz** [comment]
@oscarhiggott - it looks like @LeonidPryadko has addressed 2 of your open issues, though not  https://github.com/QEC-pages/QDistRnd/issues/16 for some reason (or maybe this was addressed too, just not commented upon in the issue?)

**Comment by danielskatz** [comment]
👋 @pan-pavel - How is your review coming?

**Comment by pan-pavel** [comment]
> 👋 @pan-pavel - How is your review coming?

Hello Daniel, 

It is almost complete. I hope to finish the review in a week.

Pavel

**Comment by danielskatz** [comment]
@oscarhiggott - I see you've check all your boxes now. Does this indicate you are satisfied for this to proceed to publication?

**Comment by oscarhiggott** [comment]
Hi @danielskatz - yes I am happy for it to proceed to publication

**Comment by danielskatz** [comment]
👋 @pan-pavel - Can you let us know if you are ok with this now proceeding to publication?

**Comment by pan-pavel** [comment]
Hello Daniel,

Sorry for the late response! Yes, I think we can now proceed to publication. 

Best Regards,
Pavel

**Comment by danielskatz** [comment]
@editorialbot check references

**Comment by danielskatz** [comment]
@LeonidPryadko - I've suggested some minor changes to the paper in https://github.com/QEC-pages/QDistRnd/pull/20 - If you can merge this, we can move forward to acceptance and publication.  Let me know if you disagree with any of these changes.

**Comment by LeonidPryadko** [comment]
The changes look fine.  I am about to merge them, and will make a couple of
additional small edits to the manuscript in the next half an hour or so.

Leonid

**Comment by danielskatz** [comment]
When you are done, please:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by LeonidPryadko** [comment]
I am done with any changes to the paper.md file.

Regarding the items you requested, do you have a more detailed set of
instructions, please?
I do not really understand what "tagged release" means, nor where exactly
the version needs to be listed, or where to get the DOI from.

Thanks,

Leonid

**Comment by danielskatz** [comment]
A tagged release is really a snapshot of the repository at a given time, with a label (typically a version number) - see https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

And what JOSS needs is for that snapshot to be deposited in an archive that will preserve it and gives it a DOI, which is most easily done via Zenodo for GitHub repositories, following the instructions in https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content (though note that you can also use other archival services if you wish)

To summarize, the simplest path is to
1. Follow https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content to create a link/hook from your GitHub repository to Zenodo
2. See https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content for how to create a release on GitHub, which will then trigger an archive being stored on Zenodo
3. Go into Zenodo and update the metadata for that archive to make sure the title and authors match those of the paper (rather than those of the repository). See the section labeled "How can I edit the metadata of a published record?" in https://help.zenodo.org for how to do this.

**Comment by danielskatz** [comment]
@LeonidPryadko - did my comment/explanation help?

**Comment by LeonidPryadko** [comment]
I created a release on Zenodo
https://zenodo.org/record/6374559

I also tried to follow the instructions on the release page and created a
.zenodo.json file in the repository.
However, after re-releasing the package, the Zenodo release failed, with a
cryptic message.
Any suggestions?
Specifically, is there a way to verify the validity of the `.zenodo.json`
file without generating a release?

Thanks,

Leonid

**Comment by danielskatz** [comment]
At this point, I suggest we use https://zenodo.org/record/6374733#.YjnAPC-B1_4 (https://doi.org/10.5281/zenodo.6374733), and you just updated the metadata in this deposit so that the title matches the title of the paper.  See the section labeled "How can I edit the metadata of a published record?" in https://help.zenodo.org/ for how to do this.

**Comment by danielskatz** [comment]
@editorialbot set 0.8.5 as version

**Comment by danielskatz** [comment]
@editorialbot set 10.5281/zenodo.6374733 as archive

**Comment by LeonidPryadko** [comment]
I just corrected the title and edited the description a bit in the last
version released,
https://doi.org/10.5281/zenodo.6374733

Please let me know if any other actions are needed.

Thank you,

Leonid

**Comment by danielskatz** [comment]
Thanks - that looks good

**Comment by danielskatz** [comment]
@editorialbot recommend-accept

**Comment by danielskatz** [comment]
@xuanxu - can you help me understand this ☝️ error?

**Comment by xuanxu** [comment]
@danielskatz it seems there's a reference in the .bib file missing the author

**Comment by danielskatz** [comment]
ok, thanks - I'll look into it.

But why don't we catch this in generate pdf?  there shouldn't be any new error in recommend-accept, I don't think

**Comment by danielskatz** [comment]
@LeonidPryadko - I think that if you can merge https://github.com/QEC-pages/QDistRnd/pull/21, it will let us progress

**Comment by xuanxu** [comment]
@editorialbot generate pdf

**Comment by danielskatz** [comment]
thanks @xuanxu - it's good to see the same error here. My next request :) would be a slightly more specific error message

**Comment by xuanxu** [comment]
Yeah :) we're working on it!

**Comment by LeonidPryadko** [comment]
I just merged it.  Please let me know if I should also generate a new
release.

Leonid

**Comment by danielskatz** [comment]
We don't need a new release - We want the correct software to be preserved, and the final paper, but are less concerned with the paper source.

**Comment by danielskatz** [comment]
@editorialbot recommend-accept

**Comment by danielskatz** [comment]
@editorialbot accept

**Comment by LeonidPryadko** [comment]
Ok, this is a corrected version
https://zenodo.org/record/6374733
with all version numbers up to date.

Thanks for the help!
Anything else I need to do?

Best,

Leonid
