### ISSUE TITLE
References to arXiv

### ISSUE THREAD

**Issue by pan-pavel** [openjournals/joss-reviews#4121]
In the references, the links to some of the papers are not up-to-date. 
For example, the following references are already published:

1) Breuckmann, Nikolas P., & Eberhardt, J. N. (2020). Balanced product quantum codes. ...
2) Panteleev, P., & Kalachev, G. (2020). Quantum LDPC codes with almost linear minimum
distance ...
3) Hastings, M. B., Haah, J., & O’Donnell, R. (2020). Fiber bundle codes: Breaking the ...

It is better to check all the cited arXiv references and replace them with the links to the published versions.

**Comment by whedon** [comment]
:wave: This repository is only for review issues (`pre-review` and `review`) that have been created by our editorial infrastructure, and this issue appears not to be one of these.

As such, this issue will be closed. If you're opening an issue as part of a review, please open a new issue instead in the software repository associated with the submission that you are reviewing.

Many thanks!
