### ISSUE TITLE
[PRE REVIEW]: PyAMG: Algebraic Multigrid Solvers in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4125]
**Submitting author:** @lukeolson (<a href="http://orcid.org/0000-0002-5283-6104">Luke Olson</a>)
**Repository:** <a href="https://github.com/pyamg/pyamg/" target ="_blank">https://github.com/pyamg/pyamg/</a>
**Version:** v4.2.2
**Editor:** @jedbrown
**Reviewers:** @mayrmt
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3c0d9c1133ea69038b47fda5ec6769ab/status.svg)](https://joss.theoj.org/papers/3c0d9c1133ea69038b47fda5ec6769ab)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3c0d9c1133ea69038b47fda5ec6769ab"><img src="https://joss.theoj.org/papers/3c0d9c1133ea69038b47fda5ec6769ab/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3c0d9c1133ea69038b47fda5ec6769ab/status.svg)](https://joss.theoj.org/papers/3c0d9c1133ea69038b47fda5ec6769ab)
```

**Author instructions**

Thanks for submitting your paper to JOSS @lukeolson. **Currently, there isn't an JOSS editor assigned** to your paper.

@lukeolson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4125 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.27 s (472.3 files/s, 146625.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          92           4732           8962          14640
C++                              8            423              8           3553
C/C++ Header                     8            601           2568           3110
CSS                              1            125             21            517
Markdown                         8             73              0            269
YAML                             5             39              0            262
Bourne Shell                     2              1              0             26
reStructuredText                 2             29             31             20
TOML                             1              1              0             12
make                             1              4              6             10
TeX                              1              0              0              7
-------------------------------------------------------------------------------
SUM:                           129           6028          11596          22426
-------------------------------------------------------------------------------


Statistical information for the repository '5e61014456ad07e20b867fed' was
gathered on 2022/02/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ben Southworth                   7           770            433            0.77
Christian Zielinski              1             7              4            0.01
Guillaume Lemaitre               1            68             63            0.08
Isuru Fernando                   1             2              2            0.00
Jacob Schroder                 188         35814          10495           29.55
Luke Olson                     672         31913          34797           42.56
Marek Wojciechowski              1             3              3            0.00
Martin Fergie                    4            46             40            0.05
Matthew West                     1           377             82            0.29
Nathan Bell                    237         19585           8741           18.07
Nico Schlömer                   10            59            184            0.16
Oliver Krzysik                   1            14              7            0.01
Schroder                        22          1024            914            1.24
Scott MacLachlan                 2           121              5            0.08
Southworth                      16           440            286            0.46
Tristan Konolige                 1           136             37            0.11
Wolfgang Noichl                  1             2              1            0.00
ben-s-southworth                 1             9              3            0.01
ekmolloy                         2             2              2            0.00
lukeolson                      124          7313           2934            6.54

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ben Southworth              476           61.8         66.5               17.44
Christian Zielinski           6           85.7         77.9               50.00
Guillaume Lemaitre           52           76.5         24.3                1.92
Isuru Fernando                2          100.0         37.7                0.00
Jacob Schroder            11716           32.7        138.6               20.16
Martin Fergie                31           67.4         86.2                0.00
Matthew West                304           80.6         21.9               44.41
Nathan Bell                5644           28.8        138.1               19.53
Nico Schlömer                25           42.4         18.4                0.00
Schroder                    582           56.8        101.2               18.21
Scott MacLachlan             23           19.0         22.5               34.78
Southworth                   80           18.2         67.3                5.00
Tristan Konolige            114           83.8         68.9               10.53
Wolfgang Noichl               2          100.0          4.0                0.00
ben-s-southworth            226         2511.1         37.7               25.22
ekmolloy                      1           50.0         83.4                0.00
lukeolson                 19313          264.1         56.0                7.97
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04125/joss.04125/10.21105.joss.04125.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04125/joss.04125/10.21105.joss.04125.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "," (COMMA) [#<BibTeX::Bibliography data=[8]>, "@", #<BibTeX::Entry >, {:title=>["An Introduction to Algebraic Multigrid"], :author=>["Falgout, R D"], :doi=>[""], :url=>["https://www.osti.gov/biblio/897960"], :journal=>["Computing in Science and Engineering, vol. 8, no. 6, November 1, 2006, pp. 24-33"]}, ",", "number", "="]

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what happened here with the reference check?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by danielskatz** [comment]
@Kevin-Mattheus-Moerman & @lukeolson - the error says the last bib entry is the problem. I suggest changing it to 
```
@article{amgintro,
  title   = {An Introduction to Algebraic Multigrid},
  author  = {Falgout, R. D.},
  url     = {https://www.osti.gov/biblio/897960},
  journal = {Computing in Science \& Engineering},
  doi = {10.1109/MCSE.2006.105},
  volume = 8,
  number = 6,
  pages = {24-33},
  place   = {United States},
  year    = 2006,
  month   = oct,
}
```

**Comment by lukeolson** [comment]
> @Kevin-Mattheus-Moerman & @lukeolson - the error says the last bib entry is the problem. I suggest changing it to
> 
> ```
> @article{amgintro,
>   title   = {An Introduction to Algebraic Multigrid},
>   author  = {Falgout, R. D.},
>   url     = {https://www.osti.gov/biblio/897960},
>   journal = {Computing in Science \& Engineering},
>   doi = {10.1109/MCSE.2006.105},
>   volume = 8,
>   number = 6,
>   pages = {24-33},
>   place   = {United States},
>   year    = 2006,
>   month   = oct,
> }
> ```

Thanks @danielskatz .  I made this change.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/1.9781611971057 is OK
- 10.1007/BF02238511 is OK
- 10.1137/050626272 is OK
- 10.1137/16M1082706 is OK
- 10.1137/1.9780898719505 is OK
- 10.1109/MCSE.2006.105 is OK

MISSING DOIs

- 10.1007/978-3-540-70529-1_338 may be a valid DOI for title: Multigrid Methods: Geometric

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@lukeolson can you check that missing DOI?

**Comment by lukeolson** [comment]
> @lukeolson can you check that missing DOI?

done.  added two additional DOI

**Comment by danielskatz** [comment]
@lukeolson - you can use the command `@whedon check references` to check again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by lukeolson** [comment]
@danielskatz gotcha (I wasn't sure if I was allowed to interact with whedon)

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/1.9781611971057 is OK
- 10.1007/BF02238511 is OK
- 10.1137/050626272 is OK
- 10.1137/16M1082706 is OK
- 10.1007/978-3-540-70529-1_337 is OK
- 10.1007/978-3-540-70529-1_338 is OK
- 10.1137/1.9780898719505 is OK
- 10.1109/MCSE.2006.105 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lukeolson** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04125/joss.04125/10.21105.joss.04125.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04125/joss.04125/10.21105.joss.04125.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
> @danielskatz gotcha (I wasn't sure if I was allowed to interact with whedon)

Yes, and encouraged, to make the journal as scalable as possible.  Whedon has some controls, so different roles can do different things, but these commands related to the paper are open to authors.

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
Welcome, @lukeolson! :wave: I'll get started finding reviewers.

**Comment by jedbrown** [comment]
@mayrmt :wave: Would you by chance be not-conflicted (with Luke or Jacob) and available to review this submission?

**Comment by mayrmt** [comment]
@jedbrown I don't have a conflict of interest and I'm happy to review this submission. Can you please provide more details on the review process for JOSS?

**Comment by jedbrown** [comment]
Certainly. The review will be coordinated through a GitHub issue, with possible issues filed directly to upstream. Your review covers the (short) paper, but also the project documentation, and we expect reviewers to experiment with running the software. https://joss.readthedocs.io/en/latest/review_criteria.html

@whedon add @mayrmt as reviewer

**Comment by whedon** [comment]
OK, @mayrmt is now a reviewer

**Comment by lukeolson** [comment]
@jedbrown @mayrmt scipy 1.8 was released yesterday, causing an import issue with pyamg.  I rolled out a new release today `4.2.1` -> `4.2.2`.  Just a heads-up in case the [version needs to change here](https://joss.readthedocs.io/en/latest/whedon.html?highlight=version#changing-the-software-version).

**Comment by jedbrown** [comment]
@whedon set v4.2.2 as version

**Comment by jedbrown** [comment]
Thanks, Luke. It's common that there are updates during review and we'll set the version when it's time to archive for acceptance.

**Comment by mayrmt** [comment]
@jedbrown I have started to look into the proposed code etc. Should I kick-off the official review process via `[at]whedon start review` or are there any other steps that have to happen before that?

**Comment by jedbrown** [comment]
Sure, I'll start it now and add another reviewer when I get replies.

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4142.
