### ISSUE TITLE
[PRE REVIEW]: SimplyAgree: An R package and jamovi Module for Simplifying Agreement and Reliability Analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4126]
**Submitting author:** @arcaldwell49 (<a href="http://orcid.org/0000-0002-4541-6283">Aaron R. Caldwell</a>)
**Repository:** <a href="https://github.com/arcaldwell49/SimplyAgree" target ="_blank">https://github.com/arcaldwell49/SimplyAgree</a>
**Version:** v0.0.2
**Editor:** @fboehm
**Reviewers:** @slwu89, @itismeghasyam
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/576840a8539ab55e78ef32a233570bfd/status.svg)](https://joss.theoj.org/papers/576840a8539ab55e78ef32a233570bfd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/576840a8539ab55e78ef32a233570bfd"><img src="https://joss.theoj.org/papers/576840a8539ab55e78ef32a233570bfd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/576840a8539ab55e78ef32a233570bfd/status.svg)](https://joss.theoj.org/papers/576840a8539ab55e78ef32a233570bfd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @arcaldwell49. **Currently, there isn't an JOSS editor assigned** to your paper.

@arcaldwell49 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/19466315.2019.1677495 is OK
- 10.1016/s0140-6736(86)90837-8 is OK
- 10.1177/096228029900800204 is OK
- 10.2307/2532051 is OK
- 10.1177/0962280211402548 is OK
- 10.1002/sim.2778 is OK
- 10.1080/10543400802527890 is OK
- 10.1016/j.cmpb.2012.09.002 is OK
- 10.1515/ijb-2015-0039 is OK

MISSING DOIs

- 10.1519/15184.1 may be a valid DOI for title: Quantifying Test-Retest Reliability Using the Intraclass Correlation Coefficient and the SEM

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.77 s (582.2 files/s, 137135.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           162           4584            728          55787
R                              116           1745           1999           6351
CSS                             10           1103             68           6151
Markdown                        34           2727              0           5048
Rmd                             78           4381           7879           3781
XML                              4              8              3            751
YAML                            15             69             11            714
TeX                              4             68              9            643
JavaScript                      12            102             53            601
C/C++ Header                     1             20              0             60
SVG                             11              0              1             58
Bourne Shell                     1              5              0             13
-------------------------------------------------------------------------------
SUM:                           448          14812          10751          79958
-------------------------------------------------------------------------------


Statistical information for the repository 'ba2c7fe6e184fbd077ad1250' was
gathered on 2022/02/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aaron Caldwell                  10          1343            144           79.48
arcaldwell49                     2            24            360           20.52

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
arcaldwell49                863         3595.8          0.3                6.72
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arcaldwell49** [comment]
My sincerest apologies, I am pushing the license file to GitHub now. Also,
just as a note, one article failed the DOI check. I am unsure what the
issue is here but this is the DOI listed on the publication and on PubMed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arcaldwell49 The DOI is missing for this one, please can you add it? 

```bib
@article{weir2005,
  url = {https://pubmed.ncbi.nlm.nih.gov/15705040/},
  year = {2005},
  volume = {19},
  number = {1},
  pages = {231},
  author = {Joseph P. Weir},
  title = {Quantifying Test-Retest Reliability Using the Intraclass Correlation Coefficient and the {SEM}},
  journal = {The Journal of Strength and Conditioning Research}
}
```

I think adding `doi = {10.1519/15184.1}` would do it.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fboehm you have been suggested as editor for this work. Do you think it is a fit for you? The paper doesn't compile yet but the raw form is here: https://raw.githubusercontent.com/arcaldwell49/SimplyAgree/master/paper/paper.md

**Comment by Kevin-Mattheus-Moerman** [comment]
@arcaldwell49 I see. I checked just now too, so it looks like there is no DOI. In that case we'll ignore this warning message and you can leave the bib file as is.

**Comment by fboehm** [comment]
Yes, @Kevin-Mattheus-Moerman, I'm happy to edit this submission.

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@itismeghasyam, @slwu89, @ramiromagno - Would you be willing to review this submission to JOSS? We conduct our checklist-driven reviews in Github issues. Thank you for considering this!

**Comment by itismeghasyam** [comment]
@fboehm I would be happy to review this submission. This is my first time reviewing for JOSS, how/where do I get started?

**Comment by slwu89** [comment]
@fboehm yes I agree to review this JOSS submission, thanks.

**Comment by fboehm** [comment]
@whedon assign @slwu89 as reviewer

**Comment by whedon** [comment]
OK, @slwu89 is now a reviewer

**Comment by fboehm** [comment]
@whedon add @itismeghasyam as reviewer

**Comment by whedon** [comment]
OK, @itismeghasyam is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4148.

**Comment by fboehm** [comment]
@itismeghasyam and @slwu89 - Thank you for agreeing to review this submission. We've placed the review checklist over in the "review issue", #4148. There, you'll find a checklist for each of you. You'll want to evaluate whether the submission meets each of the criteria in the checklist. If it doesn't satisfy one of the items, please describe why it doesn't in the comment thread. You can also open issues in the package repository - just be sure to link to them in the review issue. Please ask me questions if you don't know how to proceed. Thanks again!

**Comment by arcaldwell49** [comment]
All, I just want to give a small update. A user of the package noticed an error under certain conditions for agree_nest and agree_reps. I have put in a small patch (v0.0,3) to fix the issue. I am merging a branch with the main branch now and will submit to CRAN soon.

**Comment by slwu89** [comment]
Hi @fboehm thank you for the update, and @arcaldwell49 for that information.
