### ISSUE TITLE
[PRE REVIEW]: tesliper: a theoretical spectroscopist's little helper

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4127]
**Submitting author:** @mishioo (<a href="http://orcid.org/0000-0001-7884-8982">Michał M. Więcław</a>)
**Repository:** <a href="https://github.com/mishioo/tesliper" target ="_blank">https://github.com/mishioo/tesliper</a>
**Version:** 0.9.0
**Editor:** @rkurchin
**Reviewers:** @alejandrogallo, @arepstein
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3dedbebd87078d759ac2c40afaf47138/status.svg)](https://joss.theoj.org/papers/3dedbebd87078d759ac2c40afaf47138)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3dedbebd87078d759ac2c40afaf47138"><img src="https://joss.theoj.org/papers/3dedbebd87078d759ac2c40afaf47138/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3dedbebd87078d759ac2c40afaf47138/status.svg)](https://joss.theoj.org/papers/3dedbebd87078d759ac2c40afaf47138)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mishioo. **Currently, there isn't an JOSS editor assigned** to your paper.

@mishioo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4127 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (438.8 files/s, 109270.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          82           3135           4856          12979
reStructuredText                12            724            786           1384
Markdown                         1             44              0            199
YAML                             2              8              0             39
-------------------------------------------------------------------------------
SUM:                            97           3911           5642          14601
-------------------------------------------------------------------------------


Statistical information for the repository '87f5f109770b64ab2d292ec7' was
gathered on 2022/02/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
M. M. Więcław                   98          3826           4561            9.02
Michal M. Wieclaw               12           277            229            0.54
Michał M. Więcław              774         53120          31004           90.44

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michał M. Więcław         20970           39.5         12.1                4.77
```

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/chir.22691 is OK
- 10.1002/chir.22138 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04127/joss.04127/10.21105.joss.04127.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04127/joss.04127/10.21105.joss.04127.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@jarvist this looks like your cup of tea :tea: would you be able to help edit this submission?  You have a lot on your plate it seems so I'll waitlist this for now but let me know if you could take it.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mishioo I have waitlisted this submission for now since all editors in this domain are currently handling many other submissions. We'll continue once an editor becomes available.

**Comment by mishioo** [comment]
Understood, thanks for the update. Can't wait for the review to start, I'm very excited about this submission!

**Comment by danielskatz** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by alejandrogallo** [comment]
👋 @rkurchin I am willing

**Comment by rkurchin** [comment]
@whedon add @alejandrogallo as reviewer

**Comment by rkurchin** [comment]
Sounds great, thanks for the suggestion!

@arepstein, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by rkurchin** [comment]
@whedon add @arepstein as reviewer

**Comment by whedon** [comment]
OK, @arepstein is now a reviewer

**Comment by rkurchin** [comment]
Thanks so much for the suggestion, @arosen93, and apologies for any inadvertent email spam I just caused – I replied inviting @arepstein off of my email before realizing he'd already replied agreeing to do it! 🤩 (comment subsequently deleted)

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4164.
