### ISSUE TITLE
[REVIEW]: MatDL: A Lightweight Deep Learning Library in MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#413]
**Submitting author:** @haythamfayek (<a href="http://orcid.org/0000-0002-1840-7605">Haytham Fayek</a>)
**Repository:** <a href="https://github.com/haythamfayek/MatDL" target ="_blank">https://github.com/haythamfayek/MatDL</a>
**Version:** v0.8.0
**Editor:** @cmadan
**Reviewer:** @nirum
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1042860" target="_blank">10.5281/zenodo.1042860</a>

## Status

[![status](http://joss.theoj.org/papers/fa33e01459843ac8a5b781b1bd0c3250/status.svg)](http://joss.theoj.org/papers/fa33e01459843ac8a5b781b1bd0c3250)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fa33e01459843ac8a5b781b1bd0c3250"><img src="http://joss.theoj.org/papers/fa33e01459843ac8a5b781b1bd0c3250/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fa33e01459843ac8a5b781b1bd0c3250/status.svg)](http://joss.theoj.org/papers/fa33e01459843ac8a5b781b1bd0c3250)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/haythamfayek/MatDL" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@nirum, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cmadan know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/haythamfayek/MatDL">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.7.0)?
- [x] **Authorship:** Has the submitting author (@haythamfayek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @nirum it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@nirum, let me know if you have any questions about the review process :)

**Comment by nirum** [comment]
Will do! I'm working on the review, will likely need a few more days :)

**Comment by cMadan** [comment]
@nirum, no worries, thanks for the update!

**Comment by haythamfayek** [comment]
Ping @cMadan @nirum :)

**Comment by nirum** [comment]
Apologies I’ve been swamped with other work—but I am planning on getting to this by the end of the week!

**Comment by nirum** [comment]
Hi @cMadan,

I have installed and verified @haythamfayek's code. It looks very good! There are a couple of minor issues I made over on his main repo. One those are addressed, then this has my approval!

Thanks for being so patient--sorry about the delay!
Niru

**Comment by nirum** [comment]
p.s. here's my CNN training on MNIST 😃 

<img width="1074" alt="screen shot 2017-10-31 at 11 27 54 pm" src="https://user-images.githubusercontent.com/904854/32262691-3734cd90-be93-11e7-8a47-0e48ad05d109.png">

**Comment by nirum** [comment]
One other comment--there aren't tests that can be run--but there is gradient checking code, and a number of pre-specified architectures. I would encourage @haythamfayek to include some tests for his code (perhaps there are some ideas to be harvested from [this post](https://medium.com/@keeper6928/how-to-unit-test-machine-learning-code-57cf6fd81765)), but I don't think that this is a blocking issue.

**Comment by cMadan** [comment]
Thanks for the thorough review, @nirum!

**Comment by haythamfayek** [comment]
Thanks @nirum for your time and feedback. I addressed both issues you raised: haythamfayek/MatDL#1 and haythamfayek/MatDL#2.

**Comment by nirum** [comment]
Looks great! This has my approval. @cMadan, can you advise on the next steps?

**Comment by cMadan** [comment]
@haythamfayek, I just need you to archive the current code on a service like Zenodo or figshare (and provide me with the DOI) and we'll be all set!

**Comment by haythamfayek** [comment]
Hi @cMadan 

Here is the DOI from Zenodo: 
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1042860.svg)](https://doi.org/10.5281/zenodo.1042860)

There is now a version mismatch from the above. The submitted version is 0.7 vs the archived version is 0.8. How can I amend that?

**Comment by nirum** [comment]
I updated this issue with the new version. In case you reference the version in the paper.md file, edit it there too--I think that's all you have to do.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1042860 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1042860" target="_blank">10.5281/zenodo.1042860</a> is the archive.

**Comment by arfon** [comment]
@nirum - many thanks for your review and to @cMadan for editing this submission ✨ 

@haythamfayek - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00413 ⚡️ 🚀 💥

**Comment by arfon** [comment]
> @arfon - the last line in the pdf has a link that overflows into the margin and out of the pdf. Is there anything that can be done about it?

Huh, yeah, something weird going on in the [LaTeX template](https://github.com/openjournals/whedon/blob/master/resources/latex.template) we use to produce the PDF. A couple of thoughts:

- The word 'GitHub' in that sentence already links to the GitHub repository in the PDF so perhaps we don't need the URL called out separately too.
- JOSS papers by default link to the software repository already (see the left-hand column) so this entire sentence could be considered redundant?

**Comment by haythamfayek** [comment]
@arfon - I am happy to remove the link from `paper.md` (Will that auto recompile?) but the links will continue to overflow in other documents as well. We can add the `breaklinks` option to the hyperref package to allow multi-line links. Would you like me to submit a pull request?

**Comment by arfon** [comment]
> Would you like me to submit a pull request?

Yes please do. I'll recompile the paper once you've made the change to the LaTeX template.
