### ISSUE TITLE
[PRE REVIEW]: tidytags: Importing and Analyzing Twitter Data Collected with Twitter Archiving Google Sheets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4130]
**Submitting author:** @bretsw (<a href="http://orcid.org/0000-0002-6984-416X">K. Bret Staudt Willet</a>)
**Repository:** <a href="https://github.com/ropensci/tidytags" target ="_blank">https://github.com/ropensci/tidytags</a>
**Version:** v0.2.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fc4f003ad3891b8ba8e3fc8f8ae2c6e0/status.svg)](https://joss.theoj.org/papers/fc4f003ad3891b8ba8e3fc8f8ae2c6e0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fc4f003ad3891b8ba8e3fc8f8ae2c6e0"><img src="https://joss.theoj.org/papers/fc4f003ad3891b8ba8e3fc8f8ae2c6e0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fc4f003ad3891b8ba8e3fc8f8ae2c6e0/status.svg)](https://joss.theoj.org/papers/fc4f003ad3891b8ba8e3fc8f8ae2c6e0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @bretsw. **Currently, there isn't an JOSS editor assigned** to your paper.

@bretsw if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1148

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/s11528-018-0313-6 may be a valid DOI for title: Tweet, and we shall find: Using digital methods to locate participants in educational hashtags
- 10.1016/j.compedu.2020.103809 may be a valid DOI for title: Identifying multiple learning spaces within a single teacher-focused Twitter hashtag
- 10.1080/15391523.2019.1611507 may be a valid DOI for title: Revisiting how and why educators use Twitter: Tweet types and purposes in# Edchat
- 10.1111/bjet.12788 may be a valid DOI for title: Academics’ social media use over time is associated with individual, relational, cultural and political factors
- 10.1016/j.compedu.2018.08.010 may be a valid DOI for title: Exploring the relationship between online discourse and commitment in Twitter professional learning communities

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=6.75 s (7.4 files/s, 157125.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            16             37           3182        1053650
R                               22            133            390            818
Markdown                         5            182              0            533
JSON                             1              0              0            383
TeX                              1              5              0             62
Rmd                              5            291            790             38
-------------------------------------------------------------------------------
SUM:                            50            648           4362        1055484
-------------------------------------------------------------------------------


Statistical information for the repository '9fbbcf25d5151dabe8e77ac7' was
gathered on 2022/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bret Staudt Willet              11          5219           5246           99.74
Joshua Rosenberg                 1            27              0            0.26

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04130/joss.04130/10.21105.joss.04130.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04130/joss.04130/10.21105.joss.04130.pdf) :page_facing_up: :point_left:

**Comment by bretsw** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by bretsw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #4130 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (3a53af365551df09848a75c9/paper.md): did not find expected key while parsing a block mapping at line 4 column 5 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by bretsw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04130/joss.04130/10.21105.joss.04130.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04130/joss.04130/10.21105.joss.04130.pdf) :page_facing_up: :point_left:

**Comment by bretsw** [comment]
I have updated the paper's citations and reference list, and the PDF proof looks good to me at this point.

**Comment by Kevin-Mattheus-Moerman** [comment]
@bretsw thanks for this submission. I have just flagged this work for additional scope review by our editorial board. This is common for software of this size (e.g. <1000 lines of code), and relates to our [substantial scholarly effort criteria](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). Furthermore we will assess if this is in scope in terms of whether or not it qualifies as research software. 
This scope review should be completed within about 2 weeks.

**Comment by bretsw** [comment]
@Kevin-Mattheus-Moerman, thank you for taking a look and letting me know about the process. I'm hoping that the long history of commits and successful acceptance by rOpenSci will bode well. In any event, thank you for your consideration!

**Comment by sara-02** [comment]
Not an R person but I am interested in reviewing this. @Kevin-Mattheus-Moerman @bretsw

**Comment by danielskatz** [comment]
👋 @bretsw -  I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for publication by JOSS. This is not a decision about the software quality, where we trust the rOpenSci review process that it went through, but of the scope according to the JOSS submission criteria.

As noted on the [rOpenSci Guide for Authors](https://devguide.ropensci.org/authors-guide.html)

> if your package is deemed in scope by JOSS editors, only the accompanying short paper would be reviewed, (not the software that will have been extended reviewed by rOpenSci by that time). Not all rOpenSci packages will meet the criteria for JOSS.

If the software is expanded in the future, we would be pleased to consider that version for possible publication.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by bretsw** [comment]
Hi, @danielskatz, thank you for getting back to us and letting us know the result of the conversation amongst JOSS editors.

Honestly, I was surprised by this outcome. The primary reason has to do with what rOpenSci communicated about the process (described [in this blog post](https://ropensci.org/blog/2017/11/29/review-collaboration-mee/)):

> Since late 2015, rOpenSci has partnered with the [Journal of Open Source software (JOSS)](https://joss.theoj.org/), an open access journal that publishes brief articles on research software. Packages accepted to rOpenSci can be submitted for fast-track publication at JOSS, in which JOSS editors may evaluate based on rOpenSci’s reviews alone. As rOpenSci’s review criteria is significantly more stringent and designed to be compatible with JOSS, these packages are generally accepted without additional review.

Beyond the rOpenSci-JOSS partnership, @jrosen48 and I view tidytags as fitting quite well within [JOSS's vision](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort): 

> Your software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).

This last part, "addressing research challenges significantly better (e.g., faster, easier, simpler)", is precisely why we developed tidytags. Our aim is to make the kinds of social media research we do accessible to a broader range of social science researchers.

With this context for my surprise, would you be willing to share any insights regarding your decision?

Thank you in advance for any additional explanation you are able to offer.

**Comment by danielskatz** [comment]
I don't really have more to add, but I can try to restate the decision we made.  We (JOSS) have no issue with the quality of your software, or its utility, or its research application - our decision here is based purely on that we don't think it meets our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion, which we enforce to support the reputation of the journal, so that ideally, an author who publishes a paper in JOSS is seen as having done equivalent work to what would be needed to publish a paper in another scholarly journal.  It's extremely rare that JOSS will accept anything that's under 1000 LOC.  If your software was more substantial (e.g., larger) and met our substantial scholarly effort criterion, we would accept it without any additional peer review.

Again, the [rOpenSci Guide for Authors](https://devguide.ropensci.org/authors-guide.html) includes some text that says that this is possible:

> if your package is deemed in scope by JOSS editors, only the accompanying short paper would be reviewed, (not the software that will have been extended reviewed by rOpenSci by that time). Not all rOpenSci packages will meet the criteria for JOSS.

I hope this helps.

**Comment by bretsw** [comment]
@danielskatz, thank you for your follow up response and providing more explanation. I appreciate it.
