### ISSUE TITLE
[PRE REVIEW]: LangToGroup: A Haskell package for group presentation construction from formal language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4132]
**Submitting author:** @MaxVortman (<a href="http://orcid.org/0000-0003-0730-494X">Maksym Shamrai</a>)
**Repository:** <a href="https://github.com/YaccConstructor/LangToGroup" target ="_blank">https://github.com/YaccConstructor/LangToGroup</a>
**Version:** v1.0.0
**Editor:** @Nikoleta-v3
**Reviewers:** @ocramz, @JoyMitra 
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/bb303d08530e9df999cec36df86b2f75/status.svg)](https://joss.theoj.org/papers/bb303d08530e9df999cec36df86b2f75)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bb303d08530e9df999cec36df86b2f75"><img src="https://joss.theoj.org/papers/bb303d08530e9df999cec36df86b2f75/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bb303d08530e9df999cec36df86b2f75/status.svg)](https://joss.theoj.org/papers/bb303d08530e9df999cec36df86b2f75)
```

**Author instructions**

Thanks for submitting your paper to JOSS @MaxVortman. **Currently, there isn't an JOSS editor assigned** to your paper.

@MaxVortman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 746

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (894.1 files/s, 98571.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Haskell                        102           1629            627           9424
Markdown                         3             75              0            223
YAML                             5             31             73            141
TeX                              1              0              0            119
Bourne Shell                     1              0              0              5
-------------------------------------------------------------------------------
SUM:                           112           1735            700           9912
-------------------------------------------------------------------------------


Statistical information for the repository 'f341c469d7697473df98b515' was
gathered on 2022/02/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3210259.3210264 is OK
- 10.1186/1471-2105-8-S6-S8 is OK

MISSING DOIs

- 10.1080/00437956.1961.11659755 may be a valid DOI for title: Some methodological remarks on generative grammar
- 10.2307/3597195 may be a valid DOI for title: Isoperimetric and Isodiametric Functions of Groups

INVALID DOIs

- https://doi.org/10.1016/j.ic.2004.03.006 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04132/joss.04132/10.21105.joss.04132.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04132/joss.04132/10.21105.joss.04132.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@MaxVortman can you check those potentially missing/invalid DOI's :point_up: you can update the paper here by calling: `@whedon generate pdf`. And you can also check the references by calling `@whedon check references`.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @Nikoleta-v3 as editor

:wave: @Nikoleta-v3 are you able to handle this submission? Thanks

**Comment by whedon** [comment]
@Nikoleta-v3 has been invited to edit this submission.

**Comment by Nikoleta-v3** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Nikoleta-v3

**Comment by Nikoleta-v3** [comment]
Thank you @MaxVortman! Could you:

- 1️⃣ check for potentially missing/invalid DOI's https://github.com/openjournals/joss-reviews/issues/4132#issuecomment-1030581850
- 2️⃣ take a look through https://bit.ly/joss-reviewers and suggest at least four potential reviewers 😄

**Comment by Nikoleta-v3** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3210259.3210264 is OK
- 10.1186/1471-2105-8-S6-S8 is OK

MISSING DOIs

- 10.1080/00437956.1961.11659755 may be a valid DOI for title: Some methodological remarks on generative grammar
- 10.2307/3597195 may be a valid DOI for title: Isoperimetric and Isodiametric Functions of Groups

INVALID DOIs

- https://doi.org/10.1016/j.ic.2004.03.006 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Nikoleta-v3** [comment]
Thank you for the suggestions @MaxVortman 👍🏻 

Regarding the DOI. My apologies for the unclear message what I meant was can you fix the potential missing/invalid DOIs of your references ⬆️

**Comment by MaxVortman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00437956.1961.11659755 is OK
- 10.1515/9783110218329 is OK
- 10.1145/3210259.3210264 is OK
- 10.1186/1471-2105-8-S6-S8 is OK
- 10.1177/0038038588022001007 is OK
- 10.25596/jalc-2001-519 is OK
- 10.1016/j.ic.2004.03.006 is OK
- 10.2307/3597195 is OK
- 10.1007/978-1-4612-4176-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by MaxVortman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04132/joss.04132/10.21105.joss.04132.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04132/joss.04132/10.21105.joss.04132.pdf) :page_facing_up: :point_left:

**Comment by MaxVortman** [comment]
@Nikoleta-v3, done 🤟

**Comment by Nikoleta-v3** [comment]
👋 @ritwikagarwal & @JoyMitra & @adk9 & @ocramz would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "LangToGroup: A Haskell package for group presentation construction from formal language". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by Nikoleta-v3** [comment]
Thank you @ocramz 😄 🙏🏻 

@whedon assign @ocramz as reviewer

**Comment by Nikoleta-v3** [comment]
@whedon assign @ocramz as reviewer

**Comment by JoyMitra** [comment]
Hi,

I will be happy to help.

Best,
Joy Mitra

**Comment by Nikoleta-v3** [comment]
Thank you so much!

**Comment by Nikoleta-v3** [comment]
@whedon add @JoyMitra  as reviewer

**Comment by whedon** [comment]
OK, @JoyMitra  is now a reviewer

**Comment by Nikoleta-v3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4184.
