### ISSUE TITLE
[PRE REVIEW]: CAMML: an R package for multi-label cell typing of single cell RNA-sequencing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4137]
**Submitting author:** @schiebout (<a href="http://orcid.org/0000-0002-4830-8237">Courtney Schiebout</a>)
**Repository:** <a href="https://github.com/schiebout/CAMML" target ="_blank">https://github.com/schiebout/CAMML</a>
**Version:** v.0.1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e62a69bed3c7e8a3f436d02d2d5ef221/status.svg)](https://joss.theoj.org/papers/e62a69bed3c7e8a3f436d02d2d5ef221)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e62a69bed3c7e8a3f436d02d2d5ef221"><img src="https://joss.theoj.org/papers/e62a69bed3c7e8a3f436d02d2d5ef221/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e62a69bed3c7e8a3f436d02d2d5ef221/status.svg)](https://joss.theoj.org/papers/e62a69bed3c7e8a3f436d02d2d5ef221)
```

**Author instructions**

Thanks for submitting your paper to JOSS @schiebout. **Currently, there isn't an JOSS editor assigned** to your paper.

@schiebout if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1157

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (290.1 files/s, 33649.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                4             89            136            326
TeX                              1             14              0            195
Markdown                         2             17              0             35
-------------------------------------------------------------------------------
SUM:                             7            120            136            556
-------------------------------------------------------------------------------


Statistical information for the repository 'd678ce06c8c71f34f85266d9' was
gathered on 2022/02/07.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btp616 is OK
- 10.1093/nar/gkaa582 is OK
- 10.1038/nmeth.4380 is OK
- 10.1093/bioinformatics/btr260 is OK
- 10.1038/nbt.3192 is OK
- 10.1038/nprot.2017.149 is OK
- 10.1038/s41467-020-18158-5 is OK
- 10.1016/j.molcel.2015.04.005 is OK
- 10.1126/science.aaa1934 is OK
- 10.1186/s13059-019-1874-1 is OK
- 10.1016/j.cell.2021.04.048 is OK

MISSING DOIs

- 10.1142/9789811250477_0019 may be a valid DOI for title: CAMML: Multi-Label Immune Cell-Typing and Stemness Analysis for Single-Cell RNA-sequencing

INVALID DOIs

- https://doi.org/10.1016/j.cell.2019.03.005 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04137/joss.04137/10.21105.joss.04137.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04137/joss.04137/10.21105.joss.04137.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@schiebout I have just flagged this submission for additional scope review by the editorial board. In particular we need to review if this work complies with our criteria around ["substantial scholarly effort"](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). The additional scope review will take approximately 2 weeks to complete.

**Comment by kthyng** [comment]
@schiebout Sorry to follow up so quickly with bad news, but actually when the LOC are around 300 as in this submission, we do have a policy of desk rejection. This is not a commentary on how useful the code is, by any means. If the package were to expand a lot in functionality we would be happy to reconsider in the future. Thank you.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
