### ISSUE TITLE
[PRE REVIEW]: CVtreeMLE: Efficient Estimation of Mixed Exposures using Data Adaptive Decision Trees and Cross-Validated Targeted Maximum Likelihood Estimation in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4138]
**Submitting author:** @blind-contours (<a href="http://orcid.org/0000-0002-5515-6307">David McCoy</a>)
**Repository:** <a href="https://github.com/blind-contours/CVtreeMLE" target ="_blank">https://github.com/blind-contours/CVtreeMLE</a>
**Version:** v1.0.0
**Editor:** @osorensen
**Reviewers:** @GaryBAYLOR, @cpalmer718
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0/status.svg)](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0"><img src="https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0/status.svg)](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @blind-contours. **Currently, there isn't an JOSS editor assigned** to your paper.

@blind-contours if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1243

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (650.2 files/s, 110050.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               39            832           1214           2592
HTML                             1             35              2           1020
Markdown                         3            125              0            872
TeX                              2             55              0            631
Rmd                              2            241            425            180
YAML                             2             12              0             57
-------------------------------------------------------------------------------
SUM:                            49           1300           1641           5352
-------------------------------------------------------------------------------


Statistical information for the repository '016336473fc33527e993cb7e' was
gathered on 2022/02/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1515/ijb-2015-0013 is OK
- 10.2202/1557-4679.1217 is OK
- 10.1111/j.1541-0420.2011.01685.x is OK
- 10.1002/sim.5907 is OK
- 10.1007/978-3-319-65304-4_14 is OK
- 10.1007/978-1-4419-9782-1 is OK
- 10.1007/978-3-319-65304-4 is OK
- 10.2202/1557-4679.1356 is OK
- 10.1111/rssb.12362 is OK
- 10.1111/biom.13375 is OK
- 10.21105/joss.02526 is OK
- 10.5281/zenodo.1342293 is OK
- 10.5281/zenodo.3558313 is OK
- 10.5281/zenodo.3698329 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04138/joss.04138/10.21105.joss.04138.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04138/joss.04138/10.21105.joss.04138.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@blind-contours thanks for this submission. Normally we aim to assign a handling editor at this point. However unfortunately all our editors in the domains relevant to this submission (biostatistics) are currently preoccupied with other submissions. Hence I have just flagged this submission as `waitlisted`. We will assign an editor once one becomes available.

**Comment by kthyng** [comment]
@KristinaRiemer Would this be an ok fit for you?

**Comment by kthyng** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@kthyng this is pretty far outside my statistical background, so I think for that reason alone it might be better to find a more suitable editor. I'm also a little swamped right now and have been meaning to modify my editorial load accordingly.

**Comment by kthyng** [comment]
@KristinaRiemer Ok got it, thanks!

**Comment by kthyng** [comment]
@osorensen would this be a good fit for you?

**Comment by kthyng** [comment]
@whedon invite @osorensen as editor

**Comment by whedon** [comment]
@osorensen has been invited to edit this submission.

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@blind-contours, I am the associate editor for this submission now, and will try to find reviewers. In the meantime, could you please correct the following in the submitted manuscript:

- Line 63: rewrite "represenation" to "representation".
- Lines 77-78: I assume "general additive models" should be "generalized additive models"?

**Comment by osorensen** [comment]
:wave: @GaryBAYLOR @cpalmer718 @Metafrancois, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by GaryBAYLOR** [comment]
@osorensen Thanks for reaching out. I will be glad to review it!

**Comment by osorensen** [comment]
@whedon add @GaryBAYLOR as reviewer

**Comment by whedon** [comment]
OK, @GaryBAYLOR is now a reviewer

**Comment by blind-contours** [comment]
> @blind-contours, I am the associate editor for this submission now, and will try to find reviewers. In the meantime, could you please correct the following in the submitted manuscript:
> 
> * Line 63: rewrite "represenation" to "representation".
> * Lines 77-78: I assume "general additive models" should be "generalized additive models"?

@osorensen thanks for spotting these - I have made the corrections.

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04138/joss.04138/10.21105.joss.04138.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04138/joss.04138/10.21105.joss.04138.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@msalibian would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by cpalmer718** [comment]
@osorensen my apologies for the delay, it has been a challenging week. If there is still need, I would be happy to review this package. I completely understand if that is no longer needed.

**Comment by osorensen** [comment]
Thanks @cpalmer718, it would be much appreciated

**Comment by whedon** [comment]
OK, @cpalmer718 is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4181.

**Comment by osorensen** [comment]
Thanks a lot for responding @msalibian. Luckily we already have two reviewers, so I think it will be fine. But thanks for recommending your PhD student. I'll keep her in mind next time.
