### ISSUE TITLE
[PRE REVIEW]: HSF as a Future-Proof Solution to Hippocampal Subfields Segmentation in MRI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4139]
**Submitting author:** @clementpoiret (<a href="http://orcid.org/0000-0002-1571-2161">Clément POIRET</a>)
**Repository:** https://github.com/clementpoiret/HSF
**Branch with paper.md** (empty if default branch): 
**Version:** 1.0.1
**Editor:** Pending
**Reviewers:** Pending
**Managing EiC:** Kevin M. Moerman

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3b18a66b8881771e614534d3584ce8ea/status.svg)](https://joss.theoj.org/papers/3b18a66b8881771e614534d3584ce8ea)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3b18a66b8881771e614534d3584ce8ea"><img src="https://joss.theoj.org/papers/3b18a66b8881771e614534d3584ce8ea/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3b18a66b8881771e614534d3584ce8ea/status.svg)](https://joss.theoj.org/papers/3b18a66b8881771e614534d3584ce8ea)
```

**Author instructions**

Thanks for submitting your paper to JOSS @clementpoiret. **Currently, there isn't an JOSS editor assigned** to your paper.

@clementpoiret if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1372

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.33 s (170.2 files/s, 11702.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                        20            411              0           1043
Python                          10            217            256            549
TeX                              1             21              0            291
YAML                            16             39             28            277
SVG                              5             26              4            203
reStructuredText                 1             81             24            158
CSS                              1             17              0            144
TOML                             1              6              0             40
JavaScript                       1              1              0             15
-------------------------------------------------------------------------------
SUM:                            56            819            312           2720
-------------------------------------------------------------------------------


Statistical information for the repository 'c5fec712f04e6b6b5d965ea0' was
gathered on 2022/02/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Clément POIRET                  51          1275            399          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Clément POIRET             1038           81.4          0.6                8.77
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41380-018-0036-2 is OK
- 10.1002/hbm.22627 is OK
- 10.1016/j.neuroimage.2015.04.042 is OK
- 10.1016/j.neuroimage.2017.09.049 is OK
- 10.1016/j.ijrobp.2019.06.2177 is OK
- 10.3389/fninf.2019.00030 is OK
- 10.1016/S1053-8119(09)70884-5 is OK
- 10.1038/s41597-020-0557-9 is OK
- 10.1038/s41398-021-01628-9 is OK
- 10.1186/s13195-020-00642-1 is OK
- 10.1038/sdata.2015.59 is OK
- 10.1212/WNL.0000000000011413 is OK
- 10.1016/j.neuroimage.2010.06.040 is OK
- 10.1016/j.nicl.2017.05.022 is OK
- 10.1002/hipo.23385 is OK
- 10.1038/nn.4284 is OK
- 10.3174/ajnr.A4659 is OK
- 10.1016/j.neuroimage.2013.02.003 is OK
- 10.1016/j.dib.2020.106043 is OK
- 10.1016/j.neucom.2019.01.103 is OK
- 10.1007/978-3-642-33603-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04139/joss.04139/10.21105.joss.04139.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04139/joss.04139/10.21105.joss.04139.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@clementpoiret thanks for this submission. I have just flagged this submission for additional scope assessment by our editorial board. This is common for submissions of this size (see also our requirements around [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)). This scope review should be completed within 2 weeks.

**Comment by clementpoiret** [comment]
@Kevin-Mattheus-Moerman thanks for taking the time to process our paper. In the meantime, I remain at your disposal for any additional information request.

**Comment by arfon** [comment]
@clementpoiret – thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@editorialbot reject
