### ISSUE TITLE
[PRE REVIEW]: Augmentor: An Image Augmentation Library for Machine Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#414]
**Submitting author:** @mdbloice (<a href="http://orcid.org/0000-0002-2468-4086">Marcus Bloice</a>)
**Repository:** <a href="https://github.com/mdbloice/Augmentor" target ="_blank">https://github.com/mdbloice/Augmentor</a>
**Version:** v0.1.5
**Editor:** @arfon
**Reviewer:** @sealhuang

**Author instructions**

Thanks for submitting your paper to JOSS @mdbloice. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mdbloice if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @jakevdp - the submitting author suggested you as an editor

**Comment by arfon** [comment]
@sealhuang - would you be willing to review this submission for JOSS?

**Comment by sealhuang** [comment]
OK! I'd like to review this work @arfon 
And I think I need a few more days to get familiar with the review procedure and finalize the review :)

**Comment by arfon** [comment]
@whedon assign @sealhuang as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sealhuang

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start-review magic-word=bananas

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/432. Feel free to close this issue now!

**Comment by arfon** [comment]
@sealhuang - please head over to https://github.com/openjournals/joss-reviews/issues/432 for the actual review issue.
