### ISSUE TITLE
[REVIEW]: pypbomb: A Python package with tools for the design of detonation tubes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4143]
**Submitting author:** @cartemic (<a href="http://orcid.org/0000-0002-5559-936X">Mick Carter</a>)
**Repository:** https://github.com/cartemic/pypbomb/
**Branch with paper.md** (empty if default branch): 
**Version:** v1.1.0
**Editor:** @kyleniemeyer
**Reviewers:** @mefuller, @wenkailiang
**Archive:** 10.5281/zenodo.6558618

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/288143539a2e4f5ab1b83cbee4e17052/status.svg)](https://joss.theoj.org/papers/288143539a2e4f5ab1b83cbee4e17052)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/288143539a2e4f5ab1b83cbee4e17052"><img src="https://joss.theoj.org/papers/288143539a2e4f5ab1b83cbee4e17052/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/288143539a2e4f5ab1b83cbee4e17052/status.svg)](https://joss.theoj.org/papers/288143539a2e4f5ab1b83cbee4e17052)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cartemic/pypbomb/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mefuller & @wenkailiang, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kyleniemeyer know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @mefuller
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/cartemic/pypbomb/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cartemic/pypbomb/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cartemic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @wenkailiang
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/cartemic/pypbomb/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cartemic/pypbomb/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cartemic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1318

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (582.9 files/s, 120913.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            664           1211           3345
Jupyter Notebook                 1              0            787            364
TeX                              1             24              0            197
YAML                             3             12             21             90
reStructuredText                11             60             68             70
Markdown                         3             23              0             59
DOS Batch                        1              8              1             26
make                             1              4              7              9
CSS                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            34            795           2095           4163
-------------------------------------------------------------------------------


Statistical information for the repository '255f002e6ef9ee6edd230313' was
gathered on 2022/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Carter                          35          3513           1531           11.38
Mick Carter                    140         21285          17979           88.62

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mick Carter                5220           24.5         11.5                7.95
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04143/joss.04143/10.21105.joss.04143.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04143/joss.04143/10.21105.joss.04143.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1115/1.3089497 is OK
- 10.1016/j.pecs.2007.11.002 is OK
- 10.5281/zenodo.1174508 is OK
- 10.2514/1.43659 is OK
- 10.1017/S0022112007005046 is OK
- 10.1007/s00348-017-2420-0 is OK
- 10.2514/6.2015-1350 is OK
- 10.1016/j.combustflame.2010.04.011 is OK
- 10.1016/j.proci.2010.07.071 is OK
- 10.2514/6.2016-1198 is OK
- 10.1016/j.combustflame.2014.11.026 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
👋 @wenkailiang @mefuller @cartemic

**Comment by cartemic** [comment]
Thanks @wenkailiang and @mefuller for agreeing to review, and @kyleniemeyer for agreeing to edit!

**Comment by kyleniemeyer** [comment]
Hi @mefuller and @wenkailiang, I just wanted to check in on the status of your reviews. Do you think you will be able to complete them soon?

**Comment by mefuller** [comment]
I completely forgot about this.
I will aim to look at it and hopefully get it done over the weekend

**Comment by mefuller** [comment]
I completely forgot about this.
I will aim to look at it and hopefully get it done over the weekend

**Comment by kyleniemeyer** [comment]
Hi @mefuller, did you have a chance to work on your review?

@wenkailiang can you give an update on your progress? Thanks

**Comment by mefuller** [comment]
@kyleniemeyer you wrote as I am working on it (which is still no excuse for my tardiness)

**Comment by kyleniemeyer** [comment]
@mefuller thanks!

**Comment by mefuller** [comment]
I have requested some updates to the documentation/clarifications so that I can better test and examine the software, but this looks to be a very good submission

**Comment by kyleniemeyer** [comment]
@mefuller great, thank you! Is your reviewer checklist at the top up to date? (Feel free to leave anything unchecked for now as you wait for those issues to be resolved.)

**Comment by kyleniemeyer** [comment]
@cartemic Can you address @mefuller's comments (left as issues https://github.com/cartemic/pypbomb/issues/7 and https://github.com/cartemic/pypbomb/issues/8) and let me know here when those are resolved?

**Comment by cartemic** [comment]
@kyleniemeyer Sure thing! I'll have a look and get started on those issues tonight after work. Thanks @mefuller!

**Comment by wenkailiang** [comment]
@kyleniemeyer Sorry about the late response. I will update my comments here asap.

**Comment by wenkailiang** [comment]
@kyleniemeyer @cartemic This is a nice contribution to the community. The package could be very useful for the design of detonation tube. Just a few comments:

- The method used in the DDT estimation is not very clear to me (it might be due to my lack of knowledge in this area). Some equations from the Ciccarelli and Dorofeev work might be added to the manuscript.

- Is it possible to include the non-ideal effects in the calculations? For example,  https://github.com/Cantera/cantera/blob/master/interfaces/cython/cantera/examples/reactors/NonIdealShockTube.py

**Comment by wenkailiang** [comment]
@kyleniemeyer Also, I haved updated the checklist. Thanks.

**Comment by kyleniemeyer** [comment]
@wenkailiang thank you! I noticed a number of unchecked boxes still, that your comments just now do not address. Do you have concerns in those areas too?

**Comment by wenkailiang** [comment]
@kyleniemeyer These are just items I'm not very sure about, so I just left them unchecked, not meaning I have concerns in these. Thanks.

**Comment by cartemic** [comment]
@wenkailiang thanks for your comments! I've opened an issue to include equations for DDT run-up estimation in the paper (cartemic/pypbomb#10).

Non-ideal effects are not currently within the scope of pypbomb as presented here, however they could be included in a future version by exposing the option for phase specification to the user in more places (e.g. the `sd` module). Currently phase specification within pypbomb is only used in DDT run-up calculations, and the inclusion there is due to the use of viscosity in the run-up equation used for blockage ratios less than 30%.

**Comment by wenkailiang** [comment]
@cartemic Thank you for the responses!

**Comment by cartemic** [comment]
@kyleniemeyer [#10](https://github.com/cartemic/pypbomb/issues/10) is resolved.

**Comment by cartemic** [comment]
@kyleniemeyer [#7](https://github.com/cartemic/pypbomb/issues/7) is resolved.

**Comment by mefuller** [comment]
@kyleniemeyer @cartemic I am satisfied with the recent changes and have no further major concerns

**Comment by cartemic** [comment]
@mefuller @wenkailiang thank you for your time and input!

**Comment by kyleniemeyer** [comment]
@editorialbot generate pdf

**Comment by kyleniemeyer** [comment]
Hi @cartemic, we are nearly ready to accept! Just a few small items:

1. Can you add commas after the uses of "e.g." in the paper? In other words, "e.g.,".

2. Could you add a bit more detail to the README? Since that is the effectively the landing page for people, I think it should have a bit more basic info about the project, simple installation instructions (not for developers, just pip/conda users), and perhaps a very simple example usage.

Once you have done these things, please archive the software repository on Zenodo or Figshare and let me know the DOI here.

**Comment by cartemic** [comment]
@kyleniemeyer DOI is [10.5281/zenodo.6558618](https://zenodo.org/record/6558618)

**Comment by kyleniemeyer** [comment]
@editorialbot generate pdf

**Comment by cartemic** [comment]
@kyleniemeyer sorry I didn't catch that last night. Metadata has been updated.

**Comment by kyleniemeyer** [comment]
@editorialbot set archive as 10.5281/zenodo.6558618

**Comment by kyleniemeyer** [comment]
@editorialbot set 10.5281/zenodo.6558618 as archive

**Comment by kyleniemeyer** [comment]
@editorialbot recommend-accept

**Comment by kyleniemeyer** [comment]
@editorialbot accept

**Comment by kyleniemeyer** [comment]
Congratulations @cartemic on your paper's publication in JOSS! 

Many thanks to @mefuller and @wenkailiang for reviewing this submission.

**Comment by cartemic** [comment]
Awesome! Thanks @kyleniemeyer @wenkailiang @mefuller :)

**Comment by JohannesBuchner** [comment]
I found this because I am subscribed to the JOSS news feed. To an unfamiliar person such as myself, this software seems to be applicable to improving construction of pipe bombs and to estimate the impact of attacks on infrastructure.  I am a bit puzzled why neither the review proces nor the paper includes a discussion of ethical concerns of a public release of this software? For example, an argument why this is not a concern to the authors? Maybe I am misunderstanding something. From looking at the research group's profile, they seem to be involved in military applications ("projectile impact").
