### ISSUE TITLE
[PRE REVIEW]: TrackerControl: Transparency and Choice around App Tracking

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4144]
**Submitting author:** @kasnder (<a href="http://orcid.org/0000-0002-7412-8731">Konrad Kollnig</a>)
**Repository:** https://github.com/TrackerControl/tracker-control-android
**Branch with paper.md** (empty if default branch): 
**Version:** 
**Editor:** @sbenthall
**Reviewers:** @gradvohl, @gcdeshpande
**Managing EiC:** Kristen Thyng

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/dbc6b091eb510b47b80b59ada8afd9d1/status.svg)](https://joss.theoj.org/papers/dbc6b091eb510b47b80b59ada8afd9d1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dbc6b091eb510b47b80b59ada8afd9d1"><img src="https://joss.theoj.org/papers/dbc6b091eb510b47b80b59ada8afd9d1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dbc6b091eb510b47b80b59ada8afd9d1/status.svg)](https://joss.theoj.org/papers/dbc6b091eb510b47b80b59ada8afd9d1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @kasnder. **Currently, there isn't an JOSS editor assigned** to your paper.

@kasnder if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.54 s (358.0 files/s, 69198.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                            111            531            211          13262
Java                            51           2228           1486          12248
C                               11            787            480           3893
SVG                              4              0              2           1056
C/C++ Header                     2            145             34            427
Markdown                         3             69              0            188
Bourne Shell                     1             23             36            126
Gradle                           3             26             16            125
DOS Batch                        1             21              2             66
HTML                             1              7              3             43
ProGuard                         1              9             26             28
YAML                             2              4              0             25
Sass                             1              7              0             24
CMake                            1              5              0             19
JSON                             2              0              0              2
-------------------------------------------------------------------------------
SUM:                           195           3862           2296          31532
-------------------------------------------------------------------------------


Statistical information for the repository '91431e37728c7123bb2d3a69' was
gathered on 2022/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Atrate                           1             4              4            0.02
Konrad Kollnig                 252         30648           8911           99.87
TacoTheDank                      1            19             24            0.11

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Atrate                        4          100.0         21.6                0.00
Konrad Kollnig            21705           70.8         21.9                9.43
TacoTheDank                  19          100.0         13.6                5.26
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4144 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04144/joss.04144/10.21105.joss.04144.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04144/joss.04144/10.21105.joss.04144.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@sbenthall would this be a good fit for you?

**Comment by sbenthall** [comment]
Yes, thank you, I'll edit this.

**Comment by danielskatz** [comment]
@whedon assign @sbenthall as editor

**Comment by whedon** [comment]
OK, the editor is @sbenthall

**Comment by gradvohl** [comment]
Hello @sbenthall,

Yes 👍🏼, I am able to review it. However, since I am on vacation until March, 3, I can start just by that date.

Best.

**Comment by sbenthall** [comment]
Thank you, @gradvohl 
 I'll add you as a reviewer

**Comment by sbenthall** [comment]
@editorialbot add @gradvohl as reviewer

**Comment by sbenthall** [comment]
@gradvohl Thanks for your question. I am in the process of searching for a second reviewer. When I have one confirmed, I will begin the review process, which will create a new issue with a checklist for reviewers.

If you would like to do your review ahead of time, I suggest you use this checklist:

https://joss.readthedocs.io/en/latest/review_checklist.html

... and record your review responses in a way that makes it easy to transfer them into the new form when that issue is made.

**Comment by gcdeshpande** [comment]
Hi @sbenthall, happy to review.

**Comment by sbenthall** [comment]
Thank you @gcdeshpande ! We'll begin the formal review process shortly.

**Comment by sbenthall** [comment]
@editorialbot add @gcdeshpande as reviewer

**Comment by sbenthall** [comment]
@editorialbot start review
