### ISSUE TITLE
[PRE REVIEW]: cspp: A Tool for the Correlates of State Policy Project Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4145]
**Submitting author:** @caleblucas (<a href="http://orcid.org/0000-0003-0049-4680">Caleb Lucas</a>)
**Repository:** <a href="https://github.com/correlatesstatepolicy/cspp/" target ="_blank">https://github.com/correlatesstatepolicy/cspp/</a>
**Version:** 0.3.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0e8aa4056f750446e307a9a21d534d4e/status.svg)](https://joss.theoj.org/papers/0e8aa4056f750446e307a9a21d534d4e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0e8aa4056f750446e307a9a21d534d4e"><img src="https://joss.theoj.org/papers/0e8aa4056f750446e307a9a21d534d4e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0e8aa4056f750446e307a9a21d534d4e/status.svg)](https://joss.theoj.org/papers/0e8aa4056f750446e307a9a21d534d4e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @caleblucas. **Currently, there isn't an JOSS editor assigned** to your paper.

@caleblucas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 659

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01686 is OK
- 10.1017/spq.2021.17 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (1023.6 files/s, 141157.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         4            138              0            677
R                               13            227            519            611
Rmd                              2            198            325            185
TeX                              1              1              0             13
YAML                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            21            564            844           1488
-------------------------------------------------------------------------------


Statistical information for the repository 'd0ba861113e00932fee1db87' was
gathered on 2022/02/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4145 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by caleblucas** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by caleblucas** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 663

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (737.4 files/s, 117047.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         5            248              0           1163
R                               13            227            519            611
Rmd                              2            198            325            185
TeX                              1              1              0             13
YAML                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            22            674            844           1974
-------------------------------------------------------------------------------


Statistical information for the repository '9e6b596c2cf162a6d3e47d43' was
gathered on 2022/02/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04145/joss.04145/10.21105.joss.04145.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04145/joss.04145/10.21105.joss.04145.pdf) :page_facing_up: :point_left:

**Comment by caleblucas** [comment]
> Failed to discover a valid open source license.

We licensed it under GNU General Public License v3.0 (8b2f2d82b31edc09331fbbb3789bfe705fa6aac2), but not sure which @whedon command validates that.

**Comment by caleblucas** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by caleblucas** [comment]
We can recommend @andrewheiss, @josiahparry, and @pmohanty as potential reviewers. Thank you.

**Comment by andrewheiss** [comment]
I'd be happy to review!

**Comment by kthyng** [comment]
Hi @caleblucas and thanks for your submission! Looks like it is off to a great start here but first I need to run a "scope query" check to make sure the submission is in scope for JOSS. I need to do this when the LOC < 1000. This will take 1-2 weeks; thanks for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by caleblucas** [comment]
@kthyng Sounds great, thanks very much! I appreciate it.

**Comment by danielskatz** [comment]
👋 @caleblucas - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
