### ISSUE TITLE
[PRE REVIEW]: hessQuik: Fast Hessian computation of composite functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4146]
**Submitting author:** @elizabethnewman (<a href="http://orcid.org/0000-0002-6309-7706">Elizabeth Newman</a>)
**Repository:** <a href="https://github.com/elizabethnewman/hessQuik" target ="_blank">https://github.com/elizabethnewman/hessQuik</a>
**Version:** v0.0.1
**Editor:** @jbytecode
**Reviewers:** @GregaVrbancic, @yhtang
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/126dc76c56d70524ac58b47a9bee7460/status.svg)](https://joss.theoj.org/papers/126dc76c56d70524ac58b47a9bee7460)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/126dc76c56d70524ac58b47a9bee7460"><img src="https://joss.theoj.org/papers/126dc76c56d70524ac58b47a9bee7460/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/126dc76c56d70524ac58b47a9bee7460/status.svg)](https://joss.theoj.org/papers/126dc76c56d70524ac58b47a9bee7460)
```

**Author instructions**

Thanks for submitting your paper to JOSS @elizabethnewman. **Currently, there isn't an JOSS editor assigned** to your paper.

@elizabethnewman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 2045

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (768.6 files/s, 70540.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          37            717            243           1811
Jupyter Notebook                 3              0            388            775
Markdown                         9            106              3            316
TeX                              1             29              0            201
-------------------------------------------------------------------------------
SUM:                            50            852            634           3103
-------------------------------------------------------------------------------


Statistical information for the repository '608527bc1f18afe7cf6c50c9' was
gathered on 2022/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
elizabethnewman                128          6362           3591          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
elizabethnewman            2771           43.6          1.4                6.35
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CVPR.2016.90 is OK
- 10.1109/EuroSP.2016.36 is OK
- 10.1007/978-1-4842-4470-8_7 is OK
- 10.1137/1.9781611973808 is OK
- 10.1073/pnas.1922204117 is OK
- 10.1137/07070111X is OK
- 10.1007/s40304-017-0103-z is OK
- 10.1088/1361-6420/aa9a90 is OK
- 10.1073/pnas.1916634117 is OK

MISSING DOIs

- 10.1002/gamm.202100008 may be a valid DOI for title: An Introduction to Deep Generative Modeling
- 10.1109/cvpr.2016.90 may be a valid DOI for title: Deep residual learning for image recognition
- 10.1016/j.jcp.2018.10.045 may be a valid DOI for title: Physics-informed neural networks: A deep learning framework for solving forward and inverse problems involving nonlinear partial differential equations

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04146/joss.04146/10.21105.joss.04146.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04146/joss.04146/10.21105.joss.04146.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @jbytecode! Is this a reasonable fit for you?

**Comment by kthyng** [comment]
@whedon invite @jbytecode as editor

**Comment by sara-02** [comment]
@jbytecode I am interested in reviewing this.

**Comment by jbytecode** [comment]
@whedon assign me as editor

of course @kthyng, thank you.

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by elizabethnewman** [comment]
Dear @jbytecode,

Thank you for your fast response!  Here is a list of potential reviewers:

- jamiehadd
- jdmoorman
- GregaVrbancic
- yhtang

Please let me know if you need any additional information.

**Comment by jbytecode** [comment]
👋👋👋 Dear @jamiehadd  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "**hessQuik: Fast Hessian computation of composite functions**". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/4146).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
👋👋👋 Dear @jdmoorman  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "**hessQuik: Fast Hessian computation of composite functions**". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/4146).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
👋👋👋 Dear @GregaVrbancic  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "**hessQuik: Fast Hessian computation of composite functions**". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/4146).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by GregaVrbancic** [comment]
@jbytecode sure, I can review this submission.

**Comment by jbytecode** [comment]
@whedon add @GregaVrbancic as reviewer

Dear @GregaVrbancic thank you for the quick response. I am assigning you as the first reviewer. 

The reviewing process will start after I set a second reviewer. Please keep in touch.

**Comment by whedon** [comment]
OK, @GregaVrbancic is now a reviewer

**Comment by jbytecode** [comment]
👋👋👋 Dear @yhtang  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "**hessQuik: Fast Hessian computation of composite functions**". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/4146).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
@whedon add @yhtang as reviewer

Dear @yhtang, 

Thank you for accepting our invitation. We have now two reviewers so I can start the reviewing. 
Whenever the editorial bot starts the review, a new Github issue will be created. 
I will present the required instructions there.

**Comment by whedon** [comment]
OK, @yhtang is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4171.
