### ISSUE TITLE
[PRE REVIEW]: GEMA: An open-source Python library for self-organizing-maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4147]
**Submitting author:** @albertoceiec (<a href="http://orcid.org/0000-0003-4951-8102">Alberto Nogales</a>)
**Repository:** <a href="https://github.com/ufvceiec/GEMA" target ="_blank">https://github.com/ufvceiec/GEMA</a>
**Version:** v0.4.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0223e8606b2e2ed8e31eddc67508d77a/status.svg)](https://joss.theoj.org/papers/0223e8606b2e2ed8e31eddc67508d77a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0223e8606b2e2ed8e31eddc67508d77a"><img src="https://joss.theoj.org/papers/0223e8606b2e2ed8e31eddc67508d77a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0223e8606b2e2ed8e31eddc67508d77a/status.svg)](https://joss.theoj.org/papers/0223e8606b2e2ed8e31eddc67508d77a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @albertoceiec. **Currently, there isn't an JOSS editor assigned** to your paper.

@albertoceiec if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1116

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (248.3 files/s, 347950.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            122            187            424
Jupyter Notebook                 1              0          12794            265
TeX                              1             14              0            116
Markdown                         2             26              0             64
-------------------------------------------------------------------------------
SUM:                            10            162          12981            869
-------------------------------------------------------------------------------


Statistical information for the repository '60361975f898c3728540ac5f' was
gathered on 2022/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Antonio                         13          1503           1608           77.79
Antonio Pérez                    3            81             25            2.65
Gonzalo-MAC                      1           782              0           19.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Antonio                     733           48.8          7.4               13.51
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04147/joss.04147/10.21105.joss.04147.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04147/joss.04147/10.21105.joss.04147.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/0004-3702(91)90084-w may be a valid DOI for title: Probabilistic Reasoning in Intelligent Systems:  Networks of Plausible Inference
- 10.1109/comst.2018.2880039 may be a valid DOI for title: An overview on application of machine learning techniques in optical networks
- 10.1007/bf00337288 may be a valid DOI for title: Self-organized formation of topologically correct feature maps
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D graphics environment
- 10.18637/jss.v078.i09 may be a valid DOI for title: Somoclu: An efficient parallel library for self-organizing maps
- 10.1007/s12021-008-9041-y may be a valid DOI for title: PyMVPA: A python toolbox for multivariate pattern analysis of fMRI data
- 10.1007/978-3-030-19642-4_8 may be a valid DOI for title: Competencies in Higher Education: A Feature Analysis with Self-Organizing Maps

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @albertoceiec and thanks for your submission! I am going to run a "scope query" meaning that the greater editorial board will be asked to check if this is in scope for JOSS. The main question is the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This process will take 1-2 weeks. Thanks for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @albertoceiec - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

In addition, one editor commented 
> 7 similar libraries are mentioned in the paper, and the benefits of GEMA are "metrics" and interactive visualizations. Given the small size of the package, I don't know that this is sufficient, especially when the new metrics are unclear (searching "metrics" or "topology" in the repo does not offer any real insight here). I think either more features not present in the other SOM libraries is needed, or a more clear reasoning as to why the community needs another SOM library.

**Comment by danielskatz** [comment]
@whedon reject
