### ISSUE TITLE
[REVIEW]: HylleraasMD: Massively parallel hybrid particle-field molecular dynamics in python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4149]
**Submitting author:** @mortele (<a href="http://orcid.org/0000-0003-4244-4876">Morten Ledum</a>)
**Repository:** https://github.com/Cascella-Group-UiO/HyMD
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.9
**Editor:** @rkurchin
**Reviewers:** @blakeaw, @yhtang, @abb58
**Archive:** 10.5281/zenodo.7839898

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5ea61fe1ad1657834b9efb30c66bc64d/status.svg)](https://joss.theoj.org/papers/5ea61fe1ad1657834b9efb30c66bc64d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5ea61fe1ad1657834b9efb30c66bc64d"><img src="https://joss.theoj.org/papers/5ea61fe1ad1657834b9efb30c66bc64d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5ea61fe1ad1657834b9efb30c66bc64d/status.svg)](https://joss.theoj.org/papers/5ea61fe1ad1657834b9efb30c66bc64d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Cascella-Group-UiO/HyMD" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@blakeaw & @yhtang, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @rkurchin know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @blakeaw
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/Cascella-Group-UiO/HyMD">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Cascella-Group-UiO/HyMD">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mortele) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] #5308
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by yhtang** [comment]
I found another article on ChemRxiv titled [HylleraasMD: A Domain Decomposition-Based Hybrid Particle-Field Software for Multi-Scale Simulations of Soft Matter](https://doi.org/10.26434/chemrxiv-2021-796ql) from the same group of authors.

It seems that both papers focus on the HylleraasMD software and the ChenRxiv one is more elaborated. Is it meant for a more traditional platform?

Could the authors (@mortele) please clarify this, especially if the ChemRxiv version is still under review somewhere?

**Comment by yhtang** [comment]
@mortele Thanks for the clarification! That's very helpful.

**Comment by yhtang** [comment]
I noticed that the automated test coverage is around 50%. Should this be considered something that needs improvement? @rkurchin @blakeaw

**Comment by yhtang** [comment]
I am now stuck at the functionality and performance check due to a difficulty in installing `h5py` in Fedora as already documented in https://github.com/Cascella-Group-UiO/HyMD/issues/157. I will resume as soon as a workaround has been found.

**Comment by rkurchin** [comment]
I would agree with @blakeaw's perspective – JOSS doesn't include specific coverage requirements for this reason. That being said, @yhtang, if you see lack of coverage in areas crucial to functionality, that could certainly be an argument for suggesting additional tests!

**Comment by blakeaw** [comment]
Ran into a problem/errors when running automated tests: https://github.com/Cascella-Group-UiO/HyMD/issues/160

**Comment by mortele** [comment]
Hi @yhtang and @blakeaw. I apologize for the slow response from our end on the issues opened so far. With the slight delay after being waitlisted in the JOSS system, this review ended up coinciding with the last 10 days of my PhD contract. As such I am incredibly busy and need to have my focus mostly elsewhere for a little while. I will try to offload the review-response work as much as possible on the other members of my team, but unfortunately, I need to ask for some patience from you guys as the response time will probably still be long. 

I apologize again for the inconvenience and hope you understand.

**Comment by yhtang** [comment]
@mortele Totally understand. Good luck on your defense!

**Comment by rkurchin** [comment]
Absolutely – take your time, and congratulations on finishing up!

**Comment by blakeaw** [comment]
No problem, @mortele.  Good luck!

**Comment by mortele** [comment]
Hi @rkurchin, sorry again for the delay, I am just getting back into things. I will be starting work on resolving the review issues in the next couple of days.

**Comment by rkurchin** [comment]
Hi all, checking in on this! Happy for any general updates, but here are some questions related to specific issues:
* @blakeaw, were you able to resolve the issues with testing from https://github.com/Cascella-Group-UiO/HyMD/issues/160 ?
* @mortele (and/or @Lun4m and @samiransen23), what's the status of the community guidelines as discussed at https://github.com/Cascella-Group-UiO/HyMD/issues/159 ?
* It seems like both reviewers also filed some issues related to ease of installation of the package, e.g. https://github.com/Cascella-Group-UiO/HyMD/issues/157 and https://github.com/Cascella-Group-UiO/HyMD/issues/161, so would also be good to get updates on those...

**Comment by mortele** [comment]
Hi again @rkurchin. The docs have been updated to reflect new and improved build directives for the package. Hopefully that should be sufficient to address the last point. Regarding the finalization of the community contributor guidelines, I will have an update within a day or two. As for the first point—the mysterious `test_force` failures reported by @blakeaw, I am  so far stumped. But hopefully I will be able to work out what is going on with a little more information about the specific environment used.

**Comment by blakeaw** [comment]
Hi @rkurchin. I went ahead closed https://github.com/Cascella-Group-UiO/HyMD/issues/161 as it has been addressed. I'll work with @mortele to see if we can figure what is going on with https://github.com/Cascella-Group-UiO/HyMD/issues/160.

**Comment by arfon** [comment]
@blakeaw, @yhtang, @rkurchin, @mortele – I'm afraid we're going to need to pause this review to resolve an administrative issue amongst our editorial team.

@blakeaw, @yhtang – please hold off doing any further work on your review until you've heard back from us.

**Comment by mortele** [comment]
Hi @arfon, thank you for letting us know.

**Comment by arfon** [comment]
:wave: @blakeaw, @yhtang – apologies for the very long delay here. We're ready to restart this review but before we do so, I wanted to check if you're still able to provide a review here?

**Comment by blakeaw** [comment]
Hi @arfon, sure. I can continue my review.

**Comment by arfon** [comment]
> Hi @arfon, sure. I can continue my review.

Great stuff. Thank you!

**Comment by arfon** [comment]
Friendly bump here @yhtang – apologies again for the delay – would you be able to resume this review?

**Comment by rkurchin** [comment]
👋 @abb58, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by abb58** [comment]
> 👋 @abb58, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Sure, please send the relevant invite to review. thanks!

**Comment by rkurchin** [comment]
@editorialbot add @abb58 as reviewer

**Comment by rkurchin** [comment]
Hi reviewers @blakeaw and @abb58, reminder to continue and/or start your reviews!

**Comment by blakeaw** [comment]
Hi @rkurchin, it looks like there have been some updates to the package the review process was paused/restarted. For example, it looks like the authors just recently released version 2.0.0 in the github repo; I was working with version 1.0.5 previously. Should I consider these updates in my review? Also, should we see if the authors want to incorporate any of the updates in the software paper?

**Comment by samiransen23** [comment]
Hi @blakeaw !
Since there has been a rather long delay in the review process, there have been new releases after 1.0.5, but the paper was written and submitted a while ago, with respect to the version released then. So if you were working with version 1.0.5, the authors think you should continue the process with that version.
I hope @rkurchin finds that reasonable.

**Comment by rkurchin** [comment]
This does sound reasonable. My only concern with this approach is whether documentation or other resources have been updated past this version such that it would be hard for our new reviewer @abb58 to restrict review to the same version. We definitely don't want the two reviewers reviewing different versions of the software, so my inclination is to review the latest version instead. But since this is a somewhat unusual circumstance, I'm going to tag in @openjournals/joss-eics and see what the EIC team thinks about this...

**Comment by kyleniemeyer** [comment]
@rkurchin This has definitely happened before with software that is either changing rapidly or a review that takes a while. I believe in the past the JOSS paper focused on the version that had been submitted, or at least the one that was reviewed.

So, in this case, if one reviewer has finished on the original version, then we should probably continue the review of that version, if at all possible. If the documentation has changed, is that version-controlled?

**Comment by samiransen23** [comment]
@kyleniemeyer @rkurchin @blakeaw The documentation ( [HylleraasMD documentation](https://cascella-group-uio.github.io/HyMD/index.html) ) is the same as the one for the version being reviewed. We have not changed it, so there should arise no difficulty in continuing the review process. Hope this answers the doubt.

**Comment by rkurchin** [comment]
Okay, sounds good! Then let's go ahead and do the review for the prior version. Thanks all!

**Comment by rkurchin** [comment]
@blakeaw and @abb58, Checking in on reviews here! 

(@abb58, let me know if you have any questions on how to get started!)

**Comment by blakeaw** [comment]
Hi @rkurchin, my review is almost complete. I opened an issue regarding the Community Guidelines at https://github.com/Cascella-Group-UiO/HyMD/issues/207 and I'm waiting for the authors to address it before completing that final checklist item.

**Comment by abagusetty** [comment]
@editorialbot generate my checklist

**Comment by abagusetty** [comment]
> @blakeaw and @abb58, Checking in on reviews here!
> 
> (@abb58, let me know if you have any questions on how to get started!)

@rkurchin Thanks for the ping. I am almost done with the review process and can complete the necessary checklist soon.

**Comment by abb58** [comment]
@editorialbot generate my checlist

**Comment by abb58** [comment]
@editorialbot generate my checklist

**Comment by blakeaw** [comment]
Hi @rkurchin, the authors have addressed my last comment regarding the Community Guidelines. I have now completed my review checklist!

**Comment by abb58** [comment]
Hi @rkurchin I have completed my review based on v1.0.5. Thanks @blakeaw with the ping on closing the issue.

**Comment by rkurchin** [comment]
@editorialbot create post-review checklist

**Comment by rkurchin** [comment]
@editorialbot check references

**Comment by rkurchin** [comment]
@mortele see post-review checklist above for a few things to do to finalize this!

**Comment by mortele** [comment]
> Some minor editorial remarks:
> 
> * line 15: hyphenate "soft-matter" (it's a compound adjective here)
> * 25: hyphenate "open-source" (same reason)
> * 46: should be "requires" (subject is "elucidating")
> * 65: don't hyphenate "translationally invariant" (translationally is already an adverb)
> * 67: pluralize "calculations"
> * 78-79: feels like there's a missing word at the end of this, maybe add "implementation" or similar?
> * 95: remove extra slash at the beginning of URL
> 
> Also, one reference issue:
> 
> * line 133: capitalization of final name in list


> @mortele see post-review checklist above for a few things to do to finalize this!

Thank you for pointing these errors out. Looking at the post-review checklist items now.

**Comment by mortele** [comment]
@whedon generate pdf

**Comment by mortele** [comment]
Somewhat passive-aggressive, but OK.

@editorialbot generate pdf

**Comment by mortele** [comment]
@editorialbot generate pdf

**Comment by mortele** [comment]
Final version is *1.0.9*, https://github.com/Cascella-Group-UiO/HyMD/releases/tag/v1.0.9. This version is archived in Zenodo, DOI: `10.5281/zenodo.7839898`. Author list and ORCIDs have been double checked and should match those in the JOSS paper. 

> ## Additional Author Tasks After Review is Complete
> * [x]  Double check authors and affiliations (including ORCIDs)
> * [x]  Make a release of the software with the latest changes from the review and post the version number here. This is the version that will be used in the JOSS paper.
> * [x]  Archive the release on Zenodo/figshare/etc and post the DOI here.
> * [x]  Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.
> * [x]  Make sure that the license listed for the archive is the same as the software license.

@rkurchin Apologies for the delay, we had to fix a small issue with the documentation build in the CI before we could release.

**Comment by rkurchin** [comment]
Actually, @openjournals/bcm-eics, how should we handle versioning here? Since the review was done on 1.0.5, should there instead be some sort of "special" version number (1.0.5j or something?) that includes only that version plus the review changes? Or is it fine to do as we have now and continue the patch release increment, even though that means there will be un-reviewed features in the version tied to the JOSS publication?

**Comment by samiransen23** [comment]
Hey @rkurchin !
Just to be clear, version 1.0.9 has no new features compared to 1.0.5 but some bug fixes for the code to run smoothly. It is still 1.0.x, and new features are added only 2.0.0 onwards, which is not tied to this publication.

**Comment by rkurchin** [comment]
@editorialbot set 1.0.9 as version

**Comment by rkurchin** [comment]
@editorialbot set 10.5281/zenodo.7839898 as archive

**Comment by rkurchin** [comment]
@editorialbot recommend-accept

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot set v1.0.9 as version

**Comment by Kevin-Mattheus-Moerman** [comment]
@mortele I am the AEiC for this track and here to help process final steps. I have checked the archive and the paper and have the below minor comments that require your attention: 

On the archive: 
- [ ] Please manually edit the ZENODO archive title to match the JOSS paper title. 

On the paper: 
- [ ] One affiliation says `United States`, this is fine. However, most JOSS papers seem to feature: `United States of America`, so perhaps consider conforming to this too. 
- [ ] Check if `backend` should be written instead as `back-end`

**Comment by mortele** [comment]
> @mortele I am the AEiC for this track and here to help process final steps. I have checked the archive and the paper and have the below minor comments that require your attention:
> 
> On the archive:
> 
> * [x]  Please manually edit the ZENODO archive title to match the JOSS paper title.
> 
> On the paper:
> 
> * [x]  One affiliation says `United States`, this is fine. However, most JOSS papers seem to feature: `United States of America`, so perhaps consider conforming to this too.
> * [ ]  Check if `backend` should be written instead as `back-end`

Hi @Kevin-Mattheus-Moerman, I have changed the Zenodo archive title to match the paper title and added *of America* to Sigbjørn's affiliation in the archive and in the paper. 

As for the last point, I think that *back end* and *backend* are acceptable forms when used as a noun, with *back-end* reserved for usage as a compound adjective. However, I have absolutely no strong feelings about this and would not mind at all changing it if anyone with a stronger background in the English language disagrees.

**Comment by mortele** [comment]
@editorialbot generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot accept

**Comment by Kevin-Mattheus-Moerman** [comment]
@mortele  congratulations on this publication in JOSS! 

@rkurchin thanks for editing! 

And a special thanks to the reviewers: @blakeaw, @yhtang, @abb58
