### ISSUE TITLE
[PRE REVIEW]: micompm - A MATLAB/Octave toolbox for multivariate independent comparison of observations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#415]
**Submitting author:** @fakenmc (<a href="http://orcid.org/0000-0002-8487-5837">Nuno Fachada</a>)
**Repository:** <a href="https://github.com/fakenmc/micompm" target ="_blank">https://github.com/fakenmc/micompm</a>
**Version:** v1.0.0
**Editor:** @cMadan
**Reviewer:** @jordigh

**Author instructions**

Thanks for submitting your paper to JOSS @fakenmc. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@fakenmc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @cMadan - the submitting author suggested you as an editor.

**Comment by cMadan** [comment]
@fakenmc, your submission appears to be in good order--detailed examples, paper.md of appropriate form, and a substantive toolbox. Do you have any suggestions for reviewers?

**Comment by fakenmc** [comment]
Hi @cMadan , looking at JOSS's list of reviewers, I compiled the following list of potential reviewers for our submission:

@Kevin-Mattheus-Moerman 
@fgnievinski
@effigies 
@arokem 
@pboesu 
@ahwillia 
@jordigh 

Thanks in advance,

Nuno

**Comment by jordigh** [comment]
I may like to review Octave integration, but I recognise @fgnievinski's name. He would be a good Octave reviewer too.

**Comment by fakenmc** [comment]
Hi @cMadan, is there anything else I can do at this point?
Thanks,
Nuno

**Comment by cMadan** [comment]
@jordigh, shall I assign you as reviewer?

@fakenmc, nothing yet. First we need someone as the reviewer, then I can start the review process itself.

**Comment by jordigh** [comment]
Oh, alright, I'll do it.

I didn't want to commit until I had finished the other review first.

**Comment by cMadan** [comment]
@jordigh, no worries, thanks for volunteering!

**Comment by cMadan** [comment]
@whedon assign @jordigh as reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/430. Feel free to close this issue now!
