### ISSUE TITLE
[PRE REVIEW]: dNami: a framework for solving systems of balance laws using explicit numerical schemes on structured meshes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4152]
**Submitting author:** @etouber (<a href="http://orcid.org/0000-0002-7553-0351">Emile Touber</a>)
**Repository:** <a href="https://github.com/dNamiLab/dNami" target ="_blank">https://github.com/dNamiLab/dNami</a>
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewers:** @JamieJQuinn, @mancellin
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9/status.svg)](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9"><img src="https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9/status.svg)](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @etouber. **Currently, there isn't an JOSS editor assigned** to your paper.

@etouber if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1584

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1016/j.cpc.2021.107906 is OK
- 10.1103/PhysRevResearch.2.023068 is OK
- 10.1016/j.cpc.2014.07.011 is OK
- 10.1016/j.cpc.2020.107733 is OK
- 10.1016/j.cpc.2021.108063 is OK
- 10.1109/MCSE.2021.3083216 is OK
- 10.31223/X55K8V is OK
- 10.21105/joss.02095 is OK
- 10.21105/joss.02978 is OK
- 10.21105/joss.00301 is OK

MISSING DOIs

- 10.1016/j.jcp.2003.09.003 may be a valid DOI for title: A family of low dispersive and low dissipative explicit schemes for flow and noise computations
- 10.1504/ijcse.2009.029165 may be a valid DOI for title: F2PY: a tool for connecting Fortran and Python programs

INVALID DOIs

- https://doi.org/10.1016/B978-0-12-802118-7.00023-6 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04152/joss.04152/10.21105.joss.04152.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04152/joss.04152/10.21105.joss.04152.pdf) :page_facing_up: :point_left:

**Comment by stephenwinn16** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04152/joss.04152/10.21105.joss.04152.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04152/joss.04152/10.21105.joss.04152.pdf) :page_facing_up: :point_left:

**Comment by stephenwinn16** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jcp.2003.09.003 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1145/2833157.2833162 is OK
- 10.1016/j.cpc.2021.107906 is OK
- 10.1103/PhysRevResearch.2.023068 is OK
- 10.1016/j.cpc.2014.07.011 is OK
- 10.1016/j.cpc.2020.107733 is OK
- 10.1016/j.cpc.2021.108063 is OK
- 10.1504/IJCSE.2009.029165 is OK
- 10.1109/MCSE.2021.3083216 is OK
- 10.1016/B978-0-12-802118-7.00023-6 is OK
- 10.31223/X55K8V is OK
- 10.21105/joss.02095 is OK
- 10.21105/joss.02978 is OK
- 10.21105/joss.00301 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by etouber** [comment]
Hello, we suggest the following list of reviewers:
akaptano
ashwinvis
mikaem
mancellin
jamiejquinn
rabernat
rajeshrinet

**Comment by kthyng** [comment]
@kbarnhart are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @etouber! I'll be the editor for your submission. I'll get back to this in the next few days to find reviewers and get things started.

**Comment by kthyng** [comment]
Hi @mancellin and @jamiejquinn! I am looking for two reviewers for this JOSS submission. I would hope for reviews in 4–6 weeks, though typically starting earlier than that window because the review process tends to be iterative between the author(s) and reviewers. You can read more about the review process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
Any interest?

**Comment by mancellin** [comment]
Yes, I'm in!

**Comment by JamieJQuinn** [comment]
Yep, happy to review!

**Comment by kthyng** [comment]
Excellent @mancellin and @JamieJQuinn!! Let's get the review started.

**Comment by kthyng** [comment]
@whedon assign @mancellin as reviewer

**Comment by whedon** [comment]
OK, @mancellin is now a reviewer

**Comment by kthyng** [comment]
@whedon assign @JamieJQuinn as reviewer

**Comment by whedon** [comment]
OK, @JamieJQuinn is now a reviewer

**Comment by kthyng** [comment]
@whedon add @mancellin as reviewer

**Comment by whedon** [comment]
OK, @mancellin is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4186.
