### ISSUE TITLE
[PRE REVIEW]: PropPy -- Correlated random walk propagation of cosmic rays in magnetic turbulence

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4153]
**Submitting author:** @reichherzerp (<a href="http://orcid.org/0000-0003-4513-8241">Patrick Reichherzer</a>)
**Repository:** https://gitlab.ruhr-uni-bochum.de/reichp2y/proppy
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @christinahedges
**Reviewers:** @carmeloevoli, @amitseta90
**Managing EiC:** Kristen Thyng

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a5634b024a9339613b5a7a6434eb5d7b/status.svg)](https://joss.theoj.org/papers/a5634b024a9339613b5a7a6434eb5d7b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a5634b024a9339613b5a7a6434eb5d7b"><img src="https://joss.theoj.org/papers/a5634b024a9339613b5a7a6434eb5d7b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a5634b024a9339613b5a7a6434eb5d7b/status.svg)](https://joss.theoj.org/papers/a5634b024a9339613b5a7a6434eb5d7b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @reichherzerp. **Currently, there isn't an JOSS editor assigned** to your paper.

@reichherzerp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 2698

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (471.2 files/s, 118322.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          32            915           1164           2907
Jupyter Notebook                 9              0           4781            598
TeX                              1             34              0            424
Markdown                         2            134              0            334
Bourne Shell                     1              0              0              9
-------------------------------------------------------------------------------
SUM:                            45           1083           5945           4272
-------------------------------------------------------------------------------


Statistical information for the repository '3b70e7d03e7bfa8491fd1024' was
gathered on 2022/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Patrick Reichherzer            476          9459           4480          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Patrick Reichherzer        4986           52.7          3.1                9.79
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/806/2/217 is OK
- 10.1088/1674-4527/16/10/162 is OK
- 10.3847/1538-4357/ab643b is OK
- 10.22323/1.395.0468 is OK
- 10.1098/rsif.2008.0014 is OK
- 10.1086/148912 is OK
- 10.1063/1.4928940 is OK
- 10.1063/1.4807033 is OK
- 10.1088/1475-7516/2017/06/046 is OK
- 10.1088/1475-7516/2016/05/038 is OK
- 10.5281/zenodo.5959220 is OK
- 10.5281/zenodo.5959618 is OK
- 10.22323/1.395.0978 is OK
- 10.1093/mnras/staa1650 is OK
- 10.3847/1538-4357/aa603a is OK
- 10.1088/1475-7516/2017/02/015 is OK
- 10.1086/306470 is OK
- 10.1093/mnras/staa2533 is OK
- 10.1103/PhysRevD.65.023002 is OK
- 10.1086/307452 is OK
- 10.1007/s42452-021-04891-z is OK
- 10.1016/j.physrep.2020.05.002 is OK
- 10.3847/1538-4365/ac1517 is OK
- 10.3847/2041-8213/aa6aa6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04153/joss.04153/10.21105.joss.04153.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04153/joss.04153/10.21105.joss.04153.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
For record-keeping, this is a resubmission of #3762.

**Comment by kthyng** [comment]
@christinahedges would this submission be a reasonable fit for you?

**Comment by kthyng** [comment]
@whedon invite @christinahedges as editor

**Comment by whedon** [comment]
@christinahedges has been invited to edit this submission.

**Comment by christinahedges** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @christinahedges

**Comment by christinahedges** [comment]
Thanks @kthyng I'm happy to edit this submission! 

@reichherzerp thank you for your submission to JOSS. I'm going to get to work checking through the submission, and looking for appropriate reviewers. If you know there are people in your field who are not [conflicted with you](https://joss.readthedocs.io/en/latest/review_checklist.html?highlight=conflict#conflict-of-interest) please let me know and I can use that as a starting point to find reviewers.

Looking through your paper submission quickly, I see that there is a lot of detail in the paper about your particular algorithm. You can read more about JOSS standards for papers [here](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). The paper should largely be made up of a Statement of Need, Summary, Acknowledgements, and References sections. Detail about how the package works, (e.g. algorithms, workflows, demonstrations of speed and efficiency of code) should be in the package documentation. In the Statement of Need we do recommend authors include any similar packages (if any), and outline why users may need the new package. I think you have a longer "comparison" section that may need to be in the documentation, but you can highlight that there are other packages (CRPropa) and the top level differences in a few sentences in the SoN. Can you take a look at the JOSS documentation and see if there is anything you'd like to update about the paper submission. Here's an [example paper](https://raw.githubusercontent.com/adrn/gala/f6bb2532afeed3c0b0feea3037bf71a3f42b2a12/paper/paper.md).

I'll start looking for reviewers!

**Comment by reichherzerp** [comment]
Thanks for the patience, I have now updated the paper so that it is ready for review along with the code.

**Comment by christinahedges** [comment]
Hi @reichherzerp, just checking in to let you know I am still searching for reviewers for this submission. If you have any suggestions for people who are experts, but aren't conflicted (which is sometimes quite difficult!) please do let me know, otherwise I will keep up my search.

**Comment by christinahedges** [comment]
@editorialbot add @carmeloevoli as reviewer

**Comment by christinahedges** [comment]
@carmeloevoli Welcome to the review! Please do check the [Conflicts of Interest](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) policy and please double check for me that you aren't conflicted with the submitting authors of PropPy. I'll kick off the review when I have found the second reviewer.

**Comment by reichherzerp** [comment]
Thanks @christinahedges for finding the first reviewer. If you need more ideas, I would suggest Amit Seta and Pedro De La Torre Luque. Both are experienced with propagation codes and experts in the field.

**Comment by christinahedges** [comment]
Hi @reichherzerp, thanks, Pedro De La Torre Luque is unfortunately not able to review but I will ping your other suggestion. Thanks!

**Comment by christinahedges** [comment]
@amitseta90 Welcome to the review! Please do check the [Conflicts of Interest](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) policy and please double check for me that you aren't conflicted with the submitting authors of PropPy. 

We now have two reviewers and we're ready to kick off the review. This will start a new `REVIEW` issue.
