### ISSUE TITLE
[PRE REVIEW]: ausdex: A Python package for using Australian economic indexing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4154]
**Submitting author:** @rbturnbull (<a href="http://orcid.org/0000-0003-1274-6750">Robert Turnbull</a>)
**Repository:** https://github.com/rbturnbull/ausdex
**Branch with paper.md** (empty if default branch): 
**Version:** v0.2.2
**Editor:** @ajstewartlang
**Reviewers:** @konstantinstadler, @potterzot
**Managing EiC:** Kristen Thyng

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/817baa72d2b17b535af8f421a43404b0/status.svg)](https://joss.theoj.org/papers/817baa72d2b17b535af8f421a43404b0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/817baa72d2b17b535af8f421a43404b0"><img src="https://joss.theoj.org/papers/817baa72d2b17b535af8f421a43404b0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/817baa72d2b17b535af8f421a43404b0/status.svg)](https://joss.theoj.org/papers/817baa72d2b17b535af8f421a43404b0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rbturnbull. **Currently, there isn't an JOSS editor assigned** to your paper.

@rbturnbull if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1656

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.92 s (65.5 files/s, 333060.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              2              0             16           4002
Python                          19            890            612           2588
Jupyter Notebook                 5              0         295581            430
Markdown                         5             99              0            243
TeX                              1             29              0            234
JSON                            14              0              0            175
YAML                             5             12              6            121
HTML                             2              0              0             72
TOML                             1              4              0             43
DOS Batch                        1              8              1             26
reStructuredText                 2             21             19             21
Bourne Shell                     2              1              1             10
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            60           1068         296243           7974
-------------------------------------------------------------------------------


Statistical information for the repository 'b7dc7515faeaa677b72a761e' was
gathered on 2022/02/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jonathan Garber                 40          3700            758           58.43
Robert Turnbull                 34          2148           1024           41.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jonathan Garber            2773           74.9          2.7                9.30
Robert Turnbull            1317           61.3          2.8                6.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4154 with the following error: 
```
 [WARNING] Could not convert image '/tmp/tex2pdf.-d30e3455b425bf9d/b03229ba92c131ab2121ab4bc25f78b2858716a9.svg': check that rsvg-convert is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-d30e3455b425bf
9d/b03229ba92c131ab2121ab4bc25f78b2858716a9.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.524 ...29ba92c131ab2121ab4bc25f78b2858716a9.svg}

Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.1111/1467-8462.12152 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.5281/zenodo.3509134 is OK
- 10.1002/cpe.3282 is OK
- 10.14778/3407790.3407807 is OK

MISSING DOIs

- 10.1038/138009d0 may be a valid DOI for title: Official Year Book of the Commonwealth of Australia

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@ajstewartlang would this be a reasonable fit for you?

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #4154 with the following error: 
```
 [WARNING] Could not convert image '/tmp/tex2pdf.-e95646c5a46c854b/b03229ba92c131ab2121ab4bc25f78b2858716a9.svg': check that rsvg-convert is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-e95646c5a46c85
4b/b03229ba92c131ab2121ab4bc25f78b2858716a9.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.524 ...29ba92c131ab2121ab4bc25f78b2858716a9.svg}

Looks like we failed to compile the PDF

```

**Comment by ajstewartlang** [comment]
@danielskatz any idea why the PDF isn't building? Looks like it's something to do with `rsvg-convert`

**Comment by danielskatz** [comment]
From the error message, it looks like an issue with an svg image.  Perhaps the image could be stored in the different format.  If not, the help address to contact is `@openjournals/dev `

**Comment by ajstewartlang** [comment]
@rbturnbull can you try having the image in a different format so we can see if the pdf then builds please?

**Comment by rbturnbull** [comment]
@ajstewartlang - sure thing. I'll try the image as a pdf and see how it goes. I'm a bit surprised that the svg is causing issues because it works in github actions and using the docker image.

**Comment by rbturnbull** [comment]
@ajstewartlang - we just changed the image from an SVG to a PDF and the paper is compiling now on https://whedon.theoj.org. Hopefully it will work for you now.

**Comment by rbturnbull** [comment]
@ajstewartlang  - I'm so sorry, we missed adding the PDF of the actual asset in the update. I'm working on that now and I'll push that change soon and let you know.

**Comment by rbturnbull** [comment]
@ajstewartlang the image is properly in the repository now and it is compiling fine on whedon.theoj.org. Please let me know if there are other issues with anything.

**Comment by ajstewartlang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04154/joss.04154/10.21105.joss.04154.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04154/joss.04154/10.21105.joss.04154.pdf) :page_facing_up: :point_left:

**Comment by ajstewartlang** [comment]
Thanks @rbturnbull - the paper compiles fine now.

Also, if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by rbturnbull** [comment]
Thanks @ajstewartlang. I had a look at the list and I found these three potential reviewers work prefer to work in Python and are comfortable in reviewing topics in geospatial analysis: 
- martinfleis
- alesarrett
- AndrewAnnex

**Comment by ajstewartlang** [comment]
@editorialbot assign @konstantinstadler as reviewer

**Comment by ajstewartlang** [comment]
@editorialbot commands

**Comment by ajstewartlang** [comment]
@editorialbot add @konstantinstadler as reviewer

**Comment by ajstewartlang** [comment]
Many thanks @konstantinstadler and @potterzot for agreeing to review this submission - it's very much appreciated. I'll open the review issue now. Any questions, just ping me.

**Comment by ajstewartlang** [comment]
@editorialbot start review
