### ISSUE TITLE
[PRE REVIEW]: BCEA: An R Package for Cost-Effectiveness Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4155]
**Submitting author:** @n8thangreen (<a href="http://orcid.org/0000-0003-2745-1736">Nathan Green</a>)
**Repository:** https://github.com/n8thangreen/BCEA/
**Branch with paper.md** (empty if default branch): 
**Version:** v2.4.1
**Editor:** @ajstewartlang
**Reviewers:** @rowlandseymour, @volkerschmid
**Managing EiC:** Kristen Thyng

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c98500946568218ac5b70bba60c88c2b/status.svg)](https://joss.theoj.org/papers/c98500946568218ac5b70bba60c88c2b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c98500946568218ac5b70bba60c88c2b"><img src="https://joss.theoj.org/papers/c98500946568218ac5b70bba60c88c2b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c98500946568218ac5b70bba60c88c2b/status.svg)](https://joss.theoj.org/papers/c98500946568218ac5b70bba60c88c2b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @n8thangreen. **Currently, there isn't an JOSS editor assigned** to your paper.

@n8thangreen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4155 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.87 s (389.0 files/s, 96495.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      22           6903           6843          24358
HTML                           149           4866           1077          21276
R                              119           1789           4379           6945
CSS                             10            208            136            940
Markdown                         6            203              0            699
Rmd                             20            534            908            532
XML                              1              0              0            450
TeX                              2             62              8            303
YAML                             5             43             70            169
Sass                             1              4              0             71
SVG                              2              0              1             65
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                           338          14612          13422          55809
-------------------------------------------------------------------------------


Statistical information for the repository 'a36abde8289a9910c56ba6e0' was
gathered on 2022/02/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dr Nathan Green                  5         25670             65           47.86
Gianluca Baio                    1           412              0            0.77
Nathan Green                     3         27628              0           51.38

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dr Nathan Green           53233          207.4          3.1               18.07
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSS-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04155/joss.04155/10.21105.joss.04155.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04155/joss.04155/10.21105.joss.04155.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon invite @jbytecode as editor

**Comment by whedon** [comment]
@jbytecode has been invited to edit this submission.

**Comment by jbytecode** [comment]
@kthyng - I feel comfortable with R but I have nothing with the cost-effectiveness analysis and health economic modeling.

**Comment by danielskatz** [comment]
@jbytecode - are you saying that you would prefer not to edit this?

**Comment by jbytecode** [comment]
@danielskatz yes, it seems it is out of my expertise.

**Comment by danielskatz** [comment]
👋 @ajstewartlang - Would be be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @ajstewartlang as editor

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
Thanks @rowlandseymour for agreeing to review this submission!

**Comment by ajstewartlang** [comment]
@whedon assign @rowlandseymour as reviewer

**Comment by ajstewartlang** [comment]
@whedon add @Volkerschmid as reviewer

**Comment by ajstewartlang** [comment]
@editorialbot add @volkerschmid as reviewer

**Comment by ajstewartlang** [comment]
@editorialbot start review
