### ISSUE TITLE
[PRE REVIEW]: scanstatistics: The R Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#416]
**Submitting author:** @benjak (<a href="http://orcid.org/0000-0002-0927-7183">Benjamin Allévius</a>)
**Repository:** <a href="https://github.com/BenjaK/scanstatistics" target ="_blank">https://github.com/BenjaK/scanstatistics</a>
**Version:** v1.0.0
**Editor:** @leeper
**Reviewer:** @pragyansmita

**Author instructions**

Thanks for submitting your paper to JOSS @benjak. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@benjak if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by BenjaK** [comment]
Suggested reviewers:
- @maelle 
- @robohyun66

**Comment by leeper** [comment]
@robohyun66 Would you be interested in reviewing this for JOSS?

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@jsta Would you be interested in reviewing this?

**Comment by leeper** [comment]
I have thus far been unable to find a reviewer for this. @openjournals/joss-editors - anyone have suggestions or know of willing volunteers?

**Comment by maelle** [comment]
@njtierney ?

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: http://joss.theoj.org/reviewer-signup.html

**Comment by arfon** [comment]
@leeper - did you look through the people in https://bit.ly/joss-reviewers ?

**Comment by pragyansmita** [comment]
I can review this.

**Comment by leeper** [comment]
@pragyansmita Thank you so much! It's yours!!

**Comment by leeper** [comment]
@whedon assign @pragyansmita as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pragyansmita

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/515. Feel free to close this issue now!
