### ISSUE TITLE
[PRE REVIEW]: FEM_2D: A Rust Package for 2D Finite Element Method Computations with Extensive Support for *hp*-refinement

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4160]
**Submitting author:** @jeremiah-corrado (<a href="http://orcid.org/0000-0003-2688-0600">Jeremiah Corrado</a>)
**Repository:** <a href="https://github.com/jeremiah-corrado/fem_2d" target ="_blank">https://github.com/jeremiah-corrado/fem_2d</a>
**Version:** 0.1.0
**Editor:** @jedbrown
**Reviewers:** @jeremylt, @YohannDudouit
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1f6d4416b383d6fe96b4008334ea1bef/status.svg)](https://joss.theoj.org/papers/1f6d4416b383d6fe96b4008334ea1bef)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1f6d4416b383d6fe96b4008334ea1bef"><img src="https://joss.theoj.org/papers/1f6d4416b383d6fe96b4008334ea1bef/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1f6d4416b383d6fe96b4008334ea1bef/status.svg)](https://joss.theoj.org/papers/1f6d4416b383d6fe96b4008334ea1bef)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jeremiah-corrado. **Currently, there isn't an JOSS editor assigned** to your paper.

@jeremiah-corrado if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (288.7 files/s, 101411.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rust                            23            797            731           5675
JSON                             6              3              0           4281
Markdown                         2             73              0            242
TeX                              1              9              0             85
TOML                             1              2              0             23
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            34            885            735          10324
-------------------------------------------------------------------------------


Statistical information for the repository '43594853b016f51e49ed20a1' was
gathered on 2022/02/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeremiah                         2          1664              0           24.67
jeremiah-corrado                10          1708           3372           75.33

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.36227/techrxiv.16695163.v1 is OK
- 10.36227/techrxiv.14807895.v1 is OK
- 10.1515/jnma-2021-0081 is OK

MISSING DOIs

- 10.1007/3-540-36569-9_25 may be a valid DOI for title: SLEPc: Scalable Library for Eigenvalue Problem Computations
- 10.1007/978-1-4612-1986-6_8 may be a valid DOI for title: Efficient Management of Parallelism in Object Oriented Numerical Software Libraries

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04160/joss.04160/10.21105.joss.04160.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04160/joss.04160/10.21105.joss.04160.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @jeremiah-corrado - Can you work on the possibly missing DOIs that whedon suggests, noting that some may be incorrect? Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @jedbrown - I know you are at your paper limit for editing, but thought perhaps you might also be interested in this paper.  A no answer is perfectly fine, if you are not or cannot take on another paper.

**Comment by danielskatz** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by jeremiah-corrado** [comment]
@whedon generate pdf

**Comment by jeremiah-corrado** [comment]
Oh I see. Thank you!

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04160/joss.04160/10.21105.joss.04160.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04160/joss.04160/10.21105.joss.04160.pdf) :page_facing_up: :point_left:

**Comment by jedbrown** [comment]
This looks cool and I'm happy to take it. @jeremiah-corrado I didn't see [community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) in your documentation. Could you add those to your README and/or [standard templates](https://github.com/jeremiah-corrado/fem_2d/community)? I'll line up reviewers.

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jeremiah-corrado** [comment]
@jedbrown Community Guidelines have been added to the README. Thanks!

**Comment by jedbrown** [comment]
@whedon add @jeremylt as reviewer

**Comment by whedon** [comment]
OK, @jeremylt is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @YohannDudouit as reviewer

**Comment by whedon** [comment]
OK, @YohannDudouit is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4172.
