### ISSUE TITLE
[PRE REVIEW]: SPOG+: A Python script to determine Bayesian stellar parameters of stars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4161]
**Submitting author:** @StephanStock (<a href="http://orcid.org/0000-0002-1166-9338">Stephan Stock</a>)
**Repository:** https://github.com/StephanStock/SPOG
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** Pending
**Reviewers:** Pending
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8b11910a53dd598f7b4efa4eb80bb3ad/status.svg)](https://joss.theoj.org/papers/8b11910a53dd598f7b4efa4eb80bb3ad)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8b11910a53dd598f7b4efa4eb80bb3ad"><img src="https://joss.theoj.org/papers/8b11910a53dd598f7b4efa4eb80bb3ad/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8b11910a53dd598f7b4efa4eb80bb3ad/status.svg)](https://joss.theoj.org/papers/8b11910a53dd598f7b4efa4eb80bb3ad)
```

**Author instructions**

Thanks for submitting your paper to JOSS @StephanStock. **Currently, there isn't an JOSS editor assigned** to your paper.

@StephanStock if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 911

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (197.6 files/s, 37900.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            177            251            871
TeX                              1             36              0            395
Markdown                         3            105              0            219
YAML                             1             27              3             26
-------------------------------------------------------------------------------
SUM:                            11            345            254           1511
-------------------------------------------------------------------------------


Statistical information for the repository 'ce6a9996471056f892e2af9f' was
gathered on 2022/02/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
StephanStock                    28          1646            347          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
StephanStock               1299           78.9          2.0                4.93
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04161/joss.04161/10.21105.joss.04161.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04161/joss.04161/10.21105.joss.04161.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @StephanStock - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by StephanStock** [comment]
@danielskatz thank you very much! It would be nice to take into account the adjustments to the prepared evolutionary models that come with the software (explained in the Readme.md) when jugging the scholarly effort. I had anyway intended to possibly integrate the interpolation methodology used for this in the future into SPOG+. This would allow reliable results even with arbitrarily small uncertainties of the measured obervables by using the phase interpolation method to get an even finer grid of stellar models that I provide with the software.  Happy to hear back from you!

**Comment by danielskatz** [comment]
@StephanStock - the editors will review this, taking into account your comments

**Comment by kyleniemeyer** [comment]
Hello @StephanStock, the JOSS editors reviewed your submission, and unfortunately found that it does not meet our requirements to proceed to review in its current state. Although it is on the small side, it looks useful; however, it does not appear extensible, and the documentation, packaging, and testing standards do not meet our expectations.

If you are able to further develop the software package with those aspects in mind, we could reconsider in the future; otherwise/in addition, you might consider a submission to the astronomical literature that focuses on the scholarly aspects.

**Comment by kyleniemeyer** [comment]
@editorialbot reject
