### ISSUE TITLE
[PRE REVIEW]: RedOak: a reference-free and alignment-free structure for indexing a collection of similar genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4167]
**Submitting author:** @cagret (<a href="http://orcid.org/0000-0002-7404-7253">Clement AGRET</a>)
**Repository:** https://gite.lirmm.fr/doccy/RedOak
**Branch with paper.md** (empty if default branch): 
**Version:** 0.1.4
**Editor:** @lpantano
**Reviewers:** @swatimanekar, @samhorsfield96
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1d4506a2b9e02c0d4f2f547673ff25f1/status.svg)](https://joss.theoj.org/papers/1d4506a2b9e02c0d4f2f547673ff25f1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1d4506a2b9e02c0d4f2f547673ff25f1"><img src="https://joss.theoj.org/papers/1d4506a2b9e02c0d4f2f547673ff25f1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1d4506a2b9e02c0d4f2f547673ff25f1/status.svg)](https://joss.theoj.org/papers/1d4506a2b9e02c0d4f2f547673ff25f1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @cagret. **Currently, there isn't an JOSS editor assigned** to your paper.

@cagret if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by danielskatz** [comment]
It seems that the server isn't working well right now, I get 

> 502
> 
> Whoops, GitLab is taking too much time to respond.

I'll try again later.

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.36 s (34.7 files/s, 29876.3 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Bourne Shell                     10           4773           5619          29405
m4                                9           1104            323          10470
C++                              17            506           1409           4437
C/C++ Header                     15            604           4059           1872
TeX                              15            323            210           1807
Markdown                          5            506              0           1147
Bourne Again Shell                3            106            223            607
make                              5             98            433            267
Perl                              1             69            147             66
YAML                              2              1              1             41
--------------------------------------------------------------------------------
SUM:                             82           8090          12424          50119
--------------------------------------------------------------------------------


Statistical information for the repository '6b8c64680a252a5a634a0cd5' was
gathered on 2022/02/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Clement                          2            60             10            0.24
Clement AGRET                   71          8759           2101           36.85
Clément Agret                    1            28             28            0.19
DoccY                          127         12340           6148           62.73

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Clement AGRET              4059           46.3         37.0               46.12
Clement Agret                28          100.0          0.0               85.71
DoccY                      8800           71.3         28.5               40.86
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/1471-2105-6-31 is OK
- 10.1038/nature11346 is OK
- 10.1038/s41588-018-0041-z is OK
- 10.1038/sdata.2018.79 is OK
- 10.1093/bib/bbw089 is OK
- 10.1111/pbi.12499 is OK
- 10.1186/2047-217X-3-8 is OK
- 10.1093/gigascience/giy125 is OK
- 10.1101/090464 is OK
- 10.1089/cmb.2017.0258 is OK
- 10.1186/1471-2105-12-242 is OK
- 10.1093/bioinformatics/btz162 is OK
- 10.1093/bioinformatics/btz162 is OK
- 10.1093/bioinformatics/btr011 is OK
- 10.1093/bioinformatics/btt460 is OK
- 10.1371/journal.pone.0109384 is OK
- 10.1186/s13015-016-0066-8 is OK
- 10.1016/S0020-0255(01)00098-6 is OK
- 10.1007/978-3-642-39053-1_42 is OK
- 10.1109/DCC.2016.17 is OK
- 10.1186/s12864-018-4465-8 is OK
- 10.1101/178129 is OK
- 10.1093/bioinformatics/btu756 is OK
- 10.1093/bioinformatics/btw455 is OK
- 10.1093/bioinformatics/btv603 is OK
- 10.1186/s13015-016-0083-7 is OK
- 10.1093/bioinformatics/btw609 is OK
- 10.1093/bioinformatics/btw609 is OK
- 10.1101/gr.226852.117 is OK
- 10.1007/978-3-319-38851-9_22 is OK
- 10.4230/OASIcs.GCB.2013.35 is OK
- 10.1186/s12864-017-4401-3 is OK
- 10.1186/s13059-016-0997-x is OK
- 10.1137/0222058 is OK
- 10.1186/s12284-018-0224-3 is OK
- 10.1137/070685531 is OK
- 10.1093/bioinformatics/btz299 is OK

MISSING DOIs

- 10.1093/nar/gkp492 may be a valid DOI for title: Using reads to annotate the genome: influence of length, background distribution, and sequence errors on prediction capacity
- 10.1093/bioinformatics/btx304 may be a valid DOI for title: KMC 3: counting and manipulating k-mer statistics
- 10.1007/978-3-319-38851-9_22 may be a valid DOI for title: CHICO: A Compressed Hybrid Index for Repetitive Collections
- 10.1007/978-3-642-03784-9_7 may be a valid DOI for title: Compressed Suffix Arrays for Massive Data
- 10.1007/978-3-642-03784-9_7 may be a valid DOI for title: Compressed Suffix Arrays for Massive Data
- 10.1137/1.9781611975031.96 may be a valid DOI for title: Optimal-Time Text Indexing in BWT-runs Bounded Space
- 10.1007/978-3-319-07959-2_28 may be a valid DOI for title: From Theory to Practice: Plug and Play with Succinct Data Structures
- 10.1007/978-3-540-30218-6_19 may be a valid DOI for title: Open MPI: Goals, Concept, and Design of a Next Generation MPI Implementation
- 10.1101/866756 may be a valid DOI for title: Data structures based on k-mers for querying large collections of sequencing data sets

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@cagret - as you can see, there are a number of problems that need to be resolved.

Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).

Also, please add a Statement of Need section. 

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Also, please make sure that there aren't entries in your bib file that are not referenced.

Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
Specifically in the paper, please remove the blank lines in the header.  And remove the line for an orcid that has no orcid.  Then try regenerating the paper again

**Comment by cagret** [comment]
Hi, you are extremely efficient! I made the major changes but I don't see where the white lines are in the header.

**Comment by cagret** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bib/bbw089 is OK
- 10.1111/pbi.12499 is OK
- 10.1093/gigascience/giy125 is OK
- 10.1186/1471-2105-12-242 is OK
- 10.1093/bioinformatics/btr011 is OK
- 10.1137/070685531 is OK

MISSING DOIs

- 10.1093/nar/gkp492 may be a valid DOI for title: Using reads to annotate the genome: influence of length, background distribution, and sequence errors on prediction capacity

INVALID DOIs

- None
```

**Comment by cagret** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04167/joss.04167/10.21105.joss.04167.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04167/joss.04167/10.21105.joss.04167.pdf) :page_facing_up: :point_left:

**Comment by cagret** [comment]
What are the next steps?

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1055

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bib/bbw089 is OK
- 10.1111/pbi.12499 is OK
- 10.1093/gigascience/giy125 is OK
- 10.1186/1471-2105-12-242 is OK
- 10.1093/bioinformatics/btr011 is OK
- 10.1137/070685531 is OK

MISSING DOIs

- 10.1093/nar/gkp492 may be a valid DOI for title: Using reads to annotate the genome: influence of length, background distribution, and sequence errors on prediction capacity

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@cagret - please add the DOI for the last reference as shown above.

**Comment by lpantano** [comment]
Hi, I can handle this in 1/2 weeks if that works. sorry, a lot of things going on right now.

**Comment by danielskatz** [comment]
That's great, thanks!

**Comment by danielskatz** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@cagret, could you fix the missing DOI please? Thanks!

**Comment by lpantano** [comment]
Hi @druvus, would you like to review this tool or know somebody who would be interested in? Thanks!

**Comment by cagret** [comment]
@whedon check references

**Comment by cagret** [comment]
@editorialbot  check references

**Comment by cagret** [comment]
> @cagret, could you fix the missing DOI please? Thanks!

It's fixed, thank you

**Comment by cagret** [comment]
@editorialbot commands

**Comment by cagret** [comment]
@editorialbot check references

**Comment by lpantano** [comment]
Hi @cagret, 

I took a look at the documentation. Could you expand more how to use it, what is the output looking like, maybe an example of how you use it it would be good as well, not meaning the command lines, but a biological question to answer and showing the example of that, reasoning, conclusion...etc.  It makes easier to understand how to evaluate the package.
 
For installations, we will need to have some docker container or conda package that makes this process easier. 

In the paper it would be good to add some lines comparing with other tools, resources wise and usability wise. After that I can find reviewers, normally people would look for that to see if they can help with this or not.

Thanks!

**Comment by lpantano** [comment]
Hi @cagret, do you have somebody that you could identify as reviewer, I am finding some challenges for this one. If you could get a look at the reviewer list and name a few, it would be great.

**Comment by cagret** [comment]
Hello, i think @luizirber and @diehlpk could fit as reviewers for my paper. Thanks

**Comment by diehlpk** [comment]
Hi, I do not feel comfortable with the topic, it is a little out of scope.

**Comment by lpantano** [comment]
@philippbayer, would you like to review this tool? Thanks!

**Comment by FranzKrah** [comment]
Sorry maybe I missed something … but why am I CC‘d in this? 😅 cheers Franz

**Comment by lpantano** [comment]
sorry @FranzKrah, I got some of your repository related to multiple-alignment and I invited you as reviewer, feel free to ignore if it is very far away from your scope.

**Comment by lpantano** [comment]
@editorialbot add @swatimanekar as reviewer

**Comment by lpantano** [comment]
Hi @samhorsfield96, would you like to review this tool? I got your name from a colleague that you could be interested. Thanks!

**Comment by swatimanekar** [comment]
Yes, I'd like to take a look at the specified tool.

**Comment by samhorsfield96** [comment]
@lpantano yes I'd be happy to review this. I haven't reviewed for JOSS before, would you be able to point me towards the review guidelines/process?

**Comment by lpantano** [comment]
@editorialbot add @samhorsfield96 as reviewer

**Comment by lpantano** [comment]
@editorialbot start review
