### ISSUE TITLE
[REVIEW]: hei: Calculate Healthy Eating Index (HEI) Scores

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#417]
**Submitting author:** @timfolsom (<a href="http://orcid.org/0000-0002-8647-5810">Timothy Folsom</a>)
**Repository:** <a href="https://github.com/timfolsom/hei" target ="_blank">https://github.com/timfolsom/hei</a>
**Version:** v0.1.0
**Editor:** @leeper
**Reviewer:** @maelle
**Archive:** <a href="http://dx.doi.org/10.6084/m9.figshare.5469208" target="_blank">10.6084/m9.figshare.5469208</a>

## Status

[![status](http://joss.theoj.org/papers/e00ec9d9d4bcffce0721ba6d55091f26/status.svg)](http://joss.theoj.org/papers/e00ec9d9d4bcffce0721ba6d55091f26)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e00ec9d9d4bcffce0721ba6d55091f26"><img src="http://joss.theoj.org/papers/e00ec9d9d4bcffce0721ba6d55091f26/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e00ec9d9d4bcffce0721ba6d55091f26/status.svg)](http://joss.theoj.org/papers/e00ec9d9d4bcffce0721ba6d55091f26)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/timfolsom/hei" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@maelle, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/timfolsom/hei">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@timfolsom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @maelle it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by maelle** [comment]
I'm done with the review, nice package! You'll see I've opened many issues but nearly everything in the review list is crossed.

* I think the installation instructions could be made a bit clearer, see [this issue](https://github.com/timfolsom/hei/issues/10)

* I've made some suggestions for the documentation https://github.com/timfolsom/hei/issues/9, https://github.com/timfolsom/hei/issues/11, https://github.com/timfolsom/hei/issues/16, https://github.com/timfolsom/hei/issues/17, https://github.com/timfolsom/hei/issues/20, https://github.com/timfolsom/hei/issues/21.

* I've also made some suggestions regarding the paper. https://github.com/timfolsom/hei/issues/14, https://github.com/timfolsom/hei/issues/19, https://github.com/timfolsom/hei/issues/23.

* I found a (really easy to fix) bug in a vignette https://github.com/timfolsom/hei/issues/18 so this one is an important issue.

* Some other issues are really more suggestions! https://github.com/timfolsom/hei/issues/12, https://github.com/timfolsom/hei/issues/13, https://github.com/timfolsom/hei/issues/15, https://github.com/timfolsom/hei/issues/16, https://github.com/timfolsom/hei/issues/22.

Happy to discuss further is something is unclear.

**Comment by leeper** [comment]
@maelle Thank you so much for your thorough and prompt review!

@timfolsom Can you please address the issues Maëlle has raised and ping me when you're done?

**Comment by maelle** [comment]
I'm happy with the changes that @timfolsom's coauthor @vpnagraj made. Nearly all issues I've opened are closed, now everything in the checklist is checked. ✅

**Comment by timfolsom** [comment]
Thank you for the review and the feedback. @vpnagraj and I have incorporated almost all of your suggestions. If it is all the same to you, we would prefer to leave the pkgdown issue open for now.

**Comment by leeper** [comment]
Thanks, all. This looks good to me. @arfon - over to you.

**Comment by vpnagraj** [comment]
@leeper @maelle thank you both so much for the comprehensive review ... i think this helped make the package a lot better 👍 👍 

let us know if there's anything else you need on our end to wrap up the submission

**Comment by arfon** [comment]
@vpnagraj - please merge this pull request https://github.com/timfolsom/hei/pull/24 
and then could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by vpnagraj** [comment]
@arfon thanks for following up ... i've merged the pull request and published an archive of the package in figshare with the following following DOI:

10.6084/m9.figshare.5469208

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.5469208 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.6084/m9.figshare.5469208" target="_blank">10.6084/m9.figshare.5469208</a> is the archive.

**Comment by arfon** [comment]
@maelle - many thanks for your review and to @leeper for editing this one ✨ 

@timfolsom @vpnagraj - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00417 ⚡️ 🚀 💥
