### ISSUE TITLE
[PRE REVIEW]: easyDifferentialGeneCoexpression, a handy bioinformatics tool to easily perform differential gene coexpression

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4174]
**Submitting author:** @davidechicco (<a href="http://orcid.org/0000-0001-9655-7142">Davide Chicco</a>)
**Repository:** https://github.com/davidechicco/easyDifferentialGeneCoexpression
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0
**Editor:** Pending
**Reviewers:** Pending
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0bc86d3c750800f72767b416a6ca9936/status.svg)](https://joss.theoj.org/papers/0bc86d3c750800f72767b416a6ca9936)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0bc86d3c750800f72767b416a6ca9936"><img src="https://joss.theoj.org/papers/0bc86d3c750800f72767b416a6ca9936/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0bc86d3c750800f72767b416a6ca9936/status.svg)](https://joss.theoj.org/papers/0bc86d3c750800f72767b416a6ca9936)
```

**Author instructions**

Thanks for submitting your paper to JOSS @davidechicco. **Currently, there isn't an JOSS editor assigned** to your paper.

@davidechicco if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1046

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-0716-1839-4_12 is OK
- 10.18129/B9.bioc.annotate is OK
- 10.1093/bioinformatics/btab852 is OK
- 10.1038/nmeth.3252 is OK
- 10.1186/1471-2105-11-183 is OK
- 10.1186/s13059-019-1851-8 is OK
- 10.1186/s12859-015-0582-4 is OK
- 10.1109/TCBB.2019.2893170 is OK
- 10.1186/1471-2105-15-S15-S3 is OK
- 10.1038/s41598-017-05298-w is OK
- 10.1093/bioinformatics/bti722 is OK
- 10.1371/journal.pmed.0020124 is OK
- 10.1371/journal.pbio.1002106 is OK
- 10.1038/s41562-017-0189-z is OK
- 10.1371/journal.pone.0079729 is OK
- 10.18129/B9.bioc.diffcoexp is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1371/journal.pone.0017238 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (407.5 files/s, 44643.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                5            151             84            304
TeX                              1             22              0            180
Markdown                         2             55              0            140
Bourne Shell                     1             11             10             29
-------------------------------------------------------------------------------
SUM:                             9            239             94            653
-------------------------------------------------------------------------------


Statistical information for the repository '9d99d3631e9a761edde14ece' was
gathered on 2022/02/16.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04174/joss.04174/10.21105.joss.04174.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04174/joss.04174/10.21105.joss.04174.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1046

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (581.3 files/s, 63683.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                5            151             84            304
TeX                              1             22              0            180
Markdown                         2             55              0            140
Bourne Shell                     1             11             10             29
-------------------------------------------------------------------------------
SUM:                             9            239             94            653
-------------------------------------------------------------------------------


Statistical information for the repository '61996782d048cf8eaf947385' was
gathered on 2022/02/16.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
@davidechicco - Looking at the comments in the previous version (https://github.com/openjournals/joss-reviews/issues/4165), I see discussion about Perl code, but that code is not apparent in this repository.  Can you explain what software you ask submitting for review?  I'm going to mark this for a scope query by editors, who will take into account your response

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by davidechicco** [comment]
> @davidechicco - Looking at the comments in the previous version (#4165), I see discussion about Perl code, but that code is not apparent in this repository. Can you explain what software you ask submitting for review? I'm going to mark this for a scope query by editors, who will take into account your response

Thanks @danielskatz for considering my submission. 
I ask to review my `easyDifferentialGeneCoexpression` R package, whose GitHub repository can be found [here](https://github.com/davidechicco/easyDifferentialGeneCoexpression) and whose published R library can be found on [CRAN](https://cran.r-project.org/package=easyDifferentialGeneCoexpression). My collaborator @AbbasAlameer developed a Perl/bash wrapper for my R package; the original GitHhb repository of this wrapper can be found [here](https://github.com/AbbasAlameer/easyDifferentialGeneCoexpressionWrapper) and its corresponding published Perl module can be found on [CPAN](https://metacpan.org/dist/App-easyDifferentialGeneCoexpressionWrapper).
 I hope my short paper clarifies everything; please let me know if you need additional information from me.

**Comment by davidechicco** [comment]
> **Author instructions**
> 
> Thanks for submitting your paper to JOSS @davidechicco. **Currently, there isn't an JOSS editor assigned** to your paper.
> 
> @davidechicco if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

I checked the list and I suggest the following ten reviewers, picked from the bottom: chenyenchung, itismeghasyam, chrisamiller, ramiromagno, anthonyofseattle, llrs, allaway, fernandomayer*, franjoim, luciorq*
\*   most suitable two in my opinion

Thanks for handling the review of my short manuscript

**Comment by arfon** [comment]
@davidechicco - thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@editorialbot reject
