### ISSUE TITLE
[PRE REVIEW]: AsFem: A simple to use finite element package for phase-field modeling and multiphysics simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4175]
**Submitting author:** @yangbai90 (<a href="http://orcid.org/0000-0003-1946-4377">yang bai</a>)
**Repository:** https://github.com/M3Group/AsFem
**Branch with paper.md** (empty if default branch): 
**Version:** v0.7
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @vijaysm, @mscroggs, @schruste
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/91ffd7ed4226d840e295c980298a348d/status.svg)](https://joss.theoj.org/papers/91ffd7ed4226d840e295c980298a348d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/91ffd7ed4226d840e295c980298a348d"><img src="https://joss.theoj.org/papers/91ffd7ed4226d840e295c980298a348d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/91ffd7ed4226d840e295c980298a348d/status.svg)](https://joss.theoj.org/papers/91ffd7ed4226d840e295c980298a348d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @yangbai90. **Currently, there isn't an JOSS editor assigned** to your paper.

@yangbai90 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 590

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.ijsolstr.2021.111099 may be a valid DOI for title: A chemo-mechanical damage model at large deformation: numerical and experimental studies on polycrystalline energy materials
- 10.2139/ssrn.3507461 may be a valid DOI for title: A chemo-mechanical grain boundary model and its application to understand the damage of Li-ion battery materials
- 10.1016/j.cma.2010.04.011 may be a valid DOI for title: A phase field model for rate-independent crack propagation: Robust algorithmic implementation based on operator splits
- 10.1016/0167-2789(93)90120-p may be a valid DOI for title: Modeling and numerical simulations of dendritic crystal growth

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04175/joss.04175/10.21105.joss.04175.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04175/joss.04175/10.21105.joss.04175.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=4.44 s (476.6 files/s, 101596.0 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C/C++ Header                    754          31347          44784         170844
C++                            1008          13335          12571          78227
Fortran 77                       51             17          13727          24137
GLSL                             27             80            391          21663
SWIG                             97            958            207          10384
CMake                            92           1617           1858           7905
C                                21            796           2076           3792
CUDA                             14            795            191           3073
Markdown                          5            516              0           1508
Python                           12            166            178            725
YAML                              3             69             33            704
Bourne Shell                     13            150             69            549
CSS                               2             59             18            217
XML                               1             15             10            210
JavaScript                        3             29             15            205
HTML                              4             12              0            119
XSLT                              1              4              0            116
Bourne Again Shell                4             18             21             77
TeX                               1              4              0             51
DTD                               1              1              0             30
--------------------------------------------------------------------------------
SUM:                           2114          49988          76149         324536
--------------------------------------------------------------------------------


Statistical information for the repository '287842b68b21130ecd9b5db9' was
gathered on 2022/02/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
bbsy789                          1            33              5            0.01
walkandthinker                 113         17578          25703            9.13
yang bai                        16          1619            466            0.44
yangbai90                      263        397444          31422           90.43

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
bbsy789                      33          100.0          1.1               18.18
yangbai90                358976           90.3         15.2               26.56
```

**Comment by danielskatz** [comment]
@yangbai90 - I will next try to find an editor for your submission.  While I do this, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
After reviewing the editors, it seems all appropriate editors are busy with other submissions, so I'm going to put this on our waiting list for now, until one becomes available.

**Comment by yangbai90** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.ijsolstr.2021.111099 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.scriptamat.2020.03.027 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cma.2010.04.011 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0167-2789(93)90120-P is INVALID because of 'https://doi.org/' prefix
```

**Comment by yangbai90** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ijsolstr.2021.111099 is OK
- 10.1016/j.scriptamat.2020.03.027 is OK
- 10.1016/j.cma.2010.04.011 is OK
- 10.1016/0167-2789(93)90120-P is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by yangbai90** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04175/joss.04175/10.21105.joss.04175.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04175/joss.04175/10.21105.joss.04175.pdf) :page_facing_up: :point_left:

**Comment by yangbai90** [comment]
The cloc output for pure AsFem code (without external packages) is shown below:

```
github.com/AlDanial/cloc v 1.92  T=0.25 s (2092.0 files/s, 315805.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
GLSL                            27             80            391          21663
C++                            206           2324           5687          21116
SWIG                            97            958            207          10384
C/C++ Header                   176           1649           6366           5887
CMake                            2             66            272            497
Python                           9             81            108            496
YAML                             1              4             10            200
Markdown                         2             42              0            104
TeX                              1              4              0             55
-------------------------------------------------------------------------------
SUM:                           521           5208          13041          60402
-------------------------------------------------------------------------------
```

**Comment by yangbai90** [comment]
I searched your reviewer database for people comfortable reviewing the package and these names came up: trallard, jmbr, nnadeau, iagolemos1, thelfer, smiths, iammix, vsangelidakis, kylebeggs, felipefr, SaumikDana

**Comment by yangbai90** [comment]
Hi @danielskatz,  I mentioned above the suitable reviewers for this article. Thank you!

**Comment by arfon** [comment]
@editorialbot invite @timtroendle as editor

**Comment by arfon** [comment]
👋 @timtroendle – would you be willing to edit this submission for JOSS?

**Comment by timtroendle** [comment]
@arfon, @openjournals/joss-eics I don't feel comfortable editing this submission as its topic is not within my area of expertise.

**Comment by arfon** [comment]
@timtroendle no problem at all. Thanks for letting us know!

**Comment by Kevin-Mattheus-Moerman** [comment]
@likask, @tjhei, @chrisrichardson, @vijaysm, @diehlpk would you be interested in reviewing this work for JOSS?

**Comment by vijaysm** [comment]
Sure, I have some time available for review in March. @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot assign @vijaysm as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot set @vijaysm as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot commands

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot add @vijaysm as reviewer

**Comment by arfon** [comment]
@xuanxu - is @editorialbot responding to deleted comments here? @Kevin-Mattheus-Moerman has been having some weird behaviour issues.

**Comment by xuanxu** [comment]
> is @editorialbot responding to deleted comments here? @Kevin-Mattheus-Moerman has been having some weird behaviour issues.

Maybe, the bot receives the comments immediately after they are posted, so even if the comment is deleted later @editorialbot will respond.

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu here the error message was first posted in response to my mistake. Then I deleted everything and then it repeated the error message. I'll try it again now to see if it is repeatable.

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot assign bla as bla

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu yes it is repeatable see :point_up: i.e. the error comes up again when one deletes the comments causing it and the error message itself (not sure which is responsible).

**Comment by xuanxu** [comment]
@Kevin-Mattheus-Moerman Bug found and fixed!

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu @arfon great thanks. Now I can finally delete all this clutter :smile:

**Comment by fverdugo** [comment]
Hi @Kevin-Mattheus-Moerman thanks for the invitation, but I am unable to engage as reviewer this time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@schruste, @mscroggs, @mikaem, @likask, @tjhei, @diehlpk, would you be interested in reviewing this work featuring a C++ library for finite element analysis and multiphysics for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/)? The [JOSS review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#reviewing-for-joss) focuses on evaluation of [the software](https://github.com/M3Group/AsFem) as well as a [short paper](https://github.com/openjournals/joss-papers/blob/joss.04175/joss.04175/10.21105.joss.04175.pdf).

Note we can be flexible regarding time needed for review.

JOSS reviews are usually smooth and streamlined and take place on GitHub. Here is an example of a completed review: https://github.com/openjournals/joss-reviews/issues/1441

**Comment by mscroggs** [comment]
@Kevin-Mattheus-Moerman I can review this if you're still looking for someone

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot add @mscroggs as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@schruste, @mikaem, @likask, @tjhei, @diehlpk, would you be interested in reviewing this work featuring a C++ library for finite element analysis and multiphysics for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/)? The [JOSS review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#reviewing-for-joss) focuses on evaluation of [the software](https://github.com/M3Group/AsFem) as well as a [short paper](https://github.com/openjournals/joss-papers/blob/joss.04175/joss.04175/10.21105.joss.04175.pdf).

Note we can be flexible regarding time needed for review.

JOSS reviews are usually smooth and streamlined and take place on GitHub. Here is an example of a completed review: https://github.com/openjournals/joss-reviews/issues/1441

**Comment by schruste** [comment]
I'd also be availabel for this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot add @schruste as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot start review
