### ISSUE TITLE
[PRE REVIEW]: PlanktonIndividuals.jl: A GPU supported individual-based phytoplankton life cycle model.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4176]
**Submitting author:** @zhenwu0728 (<a href="http://orcid.org/0000-0001-8474-4274">Zhen Wu</a>)
**Repository:** https://github.com/JuliaOcean/PlanktonIndividuals.jl
**Branch with paper.md** (empty if default branch): 
**Version:** v0.4.9
**Editor:** @elbeejay
**Reviewers:** @navidcy, @Datseris
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/015da73a23acb9d114cb5c5578dd41aa/status.svg)](https://joss.theoj.org/papers/015da73a23acb9d114cb5c5578dd41aa)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/015da73a23acb9d114cb5c5578dd41aa"><img src="https://joss.theoj.org/papers/015da73a23acb9d114cb5c5578dd41aa/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/015da73a23acb9d114cb5c5578dd41aa/status.svg)](https://joss.theoj.org/papers/015da73a23acb9d114cb5c5578dd41aa)
```

**Author instructions**

Thanks for submitting your paper to JOSS @zhenwu0728. **Currently, there isn't an JOSS editor assigned** to your paper.

@zhenwu0728 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 827

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (887.7 files/s, 127722.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           74           2108            653           9578
Markdown                        13            221              0            730
TOML                             5             86              1            357
TeX                              1             11              0            122
YAML                             4              6              0             84
-------------------------------------------------------------------------------
SUM:                            97           2432            654          10871
-------------------------------------------------------------------------------


Statistical information for the repository 'a638f7e480f1d3a61ebfb55d' was
gathered on 2022/02/16.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02813 is OK
- 10.5194/gmd-10-4175-2017 is OK
- 10.3389/fmicb.2020.00086 is OK

MISSING DOIs

- 10.3354/meps148187 may be a valid DOI for title: Dynamic model of phytoplankton growth and acclimation: responses of the balanced growth rate and the chlorophyll a: carbon ratio to light, nutrient-limitation and temperature
- 10.1029/2021gb006941 may be a valid DOI for title: Modeling Photosynthesis and Exudation in Subtropical Oceans
- 10.1177/00375497211068820 may be a valid DOI for title: Agents.jl: A performant and feature-full agent based modelling software of minimal code complexity
- 10.1038/nrmicro.2016.62 may be a valid DOI for title: Advancing microbial sciences by individual-based modelling
- 10.1126/science.1254421 may be a valid DOI for title: Biogeographic patterns in ocean microbes emerge in a neutral agent-based model
- 10.1016/j.ecolmodel.2011.10.001 may be a valid DOI for title: Individual-based modelling of adaptation in marine microbial populations using genetically defined physiological parameters

INVALID DOIs

- https://doi.org/10.1111/j.1529-8817.1973.tb04092.x is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04176/joss.04176/10.21105.joss.04176.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04176/joss.04176/10.21105.joss.04176.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @elbeejay - Would you be willing to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @elbeejay as editor

**Comment by whedon** [comment]
@elbeejay has been invited to edit this submission.

**Comment by danielskatz** [comment]
@zhenwu0728 - while we get the process started, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by zhenwu0728** [comment]
@danielskatz - Thanks! Just added missing DOIs in paper.bib.

**Comment by zhenwu0728** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02813 is OK
- 10.5194/gmd-10-4175-2017 is OK
- 10.1111/j.1529-8817.1973.tb04092.x is OK
- 10.3354/meps148187 is OK
- 10.1029/2021gb006941 is OK
- 10.1177/00375497211068820 is OK
- 10.3389/fmicb.2020.00086 is OK
- 10.1038/nrmicro.2016.62 is OK
- 10.1126/science.1254421 is OK
- 10.1016/j.ecolmodel.2011.10.001 is OK
- 10.1126/science.1138544 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by zhenwu0728** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04176/joss.04176/10.21105.joss.04176.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04176/joss.04176/10.21105.joss.04176.pdf) :page_facing_up: :point_left:

**Comment by zhenwu0728** [comment]
potential reviewers:

vchuravy, an expert of CUDA.jl which PlanktonIndividuals.jl based on;
ali-ramadhan,  an expert of ocean modeling and Julia;
simonbyrne, an expert of climate modeling and Julia.

**Comment by elbeejay** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @elbeejay

**Comment by elbeejay** [comment]
@zhenwu0728 I'll take a closer look at this tomorrow - thanks for fixing the DOIs and suggesting some potential reviewers.

**Comment by elbeejay** [comment]
@zhenwu0728 some minor suggestions for the paper:
- Put parentheses around the figure references (line 13, 24, 62)
- Pluralize "waterbody" on line 36 to be consistent with the plural "grids"
- Switch "taylored" to "tailored" on line 53

Overall the submission package looks good to me, and I'm excited to see this be reviewed and eventually published in JOSS.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04176/joss.04176/10.21105.joss.04176.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04176/joss.04176/10.21105.joss.04176.pdf) :page_facing_up: :point_left:

**Comment by elbeejay** [comment]
:wave: @simonbyrne, @navidcy, @Balinus, @simone-silvestri would you be willing to review this submission to JOSS? All of you have backgrounds working in Julia, as well as on ocean, climate, and hydrodynamic models which I believe would allow you to provide high-quality and insightful reviews. At JOSS we do open checklist-driven reviews; peer-review criteria can be viewed [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

The submission is _"PlanktonIndividuals.jl: A GPU supported individual-based phytoplankton life cycle model"_ . This is a pre-review issue which we use to find peer-reviewers. Once 3 reviewers are found, we will officially start the review in a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks, although this can be extended if needed. If you are not able to review but can recommend someone else, please mention them here (in this case please mention their GitHub handle without the "@" symbol).

If you are interested, please take a look at the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) to ensure you do not have a conflict before agreeing to review this submission.

Thank you, feel free to reach out if you have any questions about the JOSS review process. Please do not feel any pressure to accept this review request if you do not have the time or do not feel comfortable reviewing this software package, we appreciate and respect our peer-reviewers' time.

**Comment by elbeejay** [comment]
> Thanks for considering me. However, the subject matter is outside my expertise. I could suggest Datseris as a potential reviewer. I am not 100% sure though if he has expertise in oceans. I was about to suggest gaelforget but just found out he is the 2nd author smile

Thanks for the input @Balinus - if you are interested you are welcome to review the Julia implementation with the caveat that your expertise is not in ocean sciences, although I leave that up to you. @Datseris, we would welcome your review of this software if you are interested; I believe you are familiar with the JOSS process and very knowledgeable regarding the Julia language, although the subject matter may be a bit out of scope for you as well.

<br>

</br>

@navidcy - Thanks for the reply! Would be very appreciative of your review; with regards to your availability, we can plan to start the review process at the end of February (or the first few days of March at the latest) to try and give you at least 3 weeks before you take leave to perform your review. Does that sound reasonable to you?

**Comment by navidcy** [comment]
@elbeejay if I have 3 weeks before I go on leave it'd be great!

**Comment by elbeejay** [comment]
@whedon invite @navidcy as reviewer

> @elbeejay if I have 3 weeks before I go on leave it'd be great!

Awesome, we can certainly do this. Thanks!

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by elbeejay** [comment]
@whedon add @navidcy as reviewer

**Comment by whedon** [comment]
OK, @navidcy is now a reviewer

**Comment by Datseris** [comment]
Hi, yeap happy to review this!

**Comment by elbeejay** [comment]
@whedon add @Datseris as reviewer

Fantastic, thanks!

**Comment by whedon** [comment]
OK, @Datseris is now a reviewer

**Comment by elbeejay** [comment]
@editorialbot start review
