### ISSUE TITLE
[PRE REVIEW]: ospgrillage: A bridge deck grillage analysis preprocessor for `OpenSeesPy`

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4177]
**Submitting author:** @ccaprani (<a href="http://orcid.org/0000-0001-6166-0895">Colin C. Caprani</a>)
**Repository:** https://github.com/MonashSmartStructures/ospgrillage
**Branch with paper.md** (empty if default branch): 
**Version:** v0.1.1
**Editor:** @prashjha
**Reviewers:** @vsangelidakis, @dbrizard
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d44339b03dc4f1add2678167c1a1b6de/status.svg)](https://joss.theoj.org/papers/d44339b03dc4f1add2678167c1a1b6de)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d44339b03dc4f1add2678167c1a1b6de"><img src="https://joss.theoj.org/papers/d44339b03dc4f1add2678167c1a1b6de/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d44339b03dc4f1add2678167c1a1b6de/status.svg)](https://joss.theoj.org/papers/d44339b03dc4f1add2678167c1a1b6de)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ccaprani. **Currently, there isn't an JOSS editor assigned** to your paper.

@ccaprani if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1245

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.82 s (128.0 files/s, 129079.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              8              8             26          37962
HTML                            17           4207             53          24948
JavaScript                       9           2405           2464           9206
Python                          21           1173           2178           7848
reStructuredText                24           1294           1596           1306
CSS                              3            207             57            834
Jupyter Notebook                 1              0           6592            343
YAML                            11             59             46            311
Markdown                         5            110              0            273
JSON                             2              0              0            197
TeX                              1              7              0             77
DOS Batch                        1              8              1             26
TOML                             1              3              0             14
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           105           9485          13020          83354
-------------------------------------------------------------------------------


Statistical information for the repository '8db2ca26bbd4640bc7a426e9' was
gathered on 2022/02/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Colin Caprani                   12           102             93            0.20
MonashSmartStructure            11          1340            569            1.97
ccaprani                        12           626            196            0.85
jun.ngan@monash.edu            218         47959          26440           76.94
justinngan92                   107         10981           8387           20.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Colin Caprani               280          274.5          5.6               14.64
ccaprani                      4            0.6          3.5                0.00
justinngan92              24990          227.6          8.0               15.74
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2011.66 is OK
- 10.4231/D3PK0727C is OK
- 10.1061/(ASCE)0887-3801(2008)22:4(264) is OK
- 10.15446/dyna.v87n212.80143 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.softx.2017.10.009 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1533/9780857099754.331 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04177/joss.04177/10.21105.joss.04177.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04177/joss.04177/10.21105.joss.04177.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @prashjha - Do you think you would be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @prashjha as editor

**Comment by whedon** [comment]
@prashjha has been invited to edit this submission.

**Comment by danielskatz** [comment]
@ccaprani - While we get this moving, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by ccaprani** [comment]
@danielskatz thank you for your time on this. I've fixed the doi problem.

Suggested reviewer github handles (without @) are: 

**Existing JOSS**:

- iammix
- arunmano121
- vsangelidakis
- Jesusbill

**New to JOSS**: 

- m-clare: OSS-oriented structural engineer
- zhuminjie: developer of OpenSeesPy
- mhscott: maintainer of OpenSees
- hackl: OSS-oriented structural engineer
- robbievanleeuwen: OSS-oriented structural engineer
- connorferster: OSS-oriented structural engineer
- fmckenna: original developer of OpenSees

**Comment by ccaprani** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2011.66 is OK
- 10.1016/j.softx.2017.10.009 is OK
- 10.4231/D3PK0727C is OK
- 10.1061/(ASCE)0887-3801(2008)22:4(264) is OK
- 10.15446/dyna.v87n212.80143 is OK
- 10.1533/9780857099754.331 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ccaprani** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04177/joss.04177/10.21105.joss.04177.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04177/joss.04177/10.21105.joss.04177.pdf) :page_facing_up: :point_left:

**Comment by ccaprani** [comment]
@danielskatz thank you for your time on this. I've fixed the doi problem.

Suggested reviewer github handles (without @) are: 

**Existing JOSS**:

- iammix
- arunmano121
- vsangelidakis
- Jesusbill

**New to JOSS**: 

- m-clare: OSS-oriented structural engineer
- zhuminjie: developer of OpenSeesPy
- mhscott: maintainer of OpenSees
- hackl: OSS-oriented structural engineer
- robbievanleeuwen: OSS-oriented structural engineer
- connorferster: OSS-oriented structural engineer
- fmckenna: original developer of OpenSees

**Comment by prashjha** [comment]
@whedon assign me as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by prashjha** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @prashjha

**Comment by prashjha** [comment]
@danielskatz thanks for the invite. @ccaprani, I will be editing your submission. Thanks for providing a list of reviewers.

**Comment by prashjha** [comment]
Hello @fmckenna, would you be interested in reviewing this submission for publication in JOSS? If you are wondering about the review process in JOSS, please check this [link](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by prashjha** [comment]
Hello @vsangelidakis, any chance you could review this submission for JOSS? Further details about the review process in JOSS are in this [link](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Please let me know!! :)

**Comment by prashjha** [comment]
HI @vsangelidakis, I hope you are settled into a new position. BTW, will you have time now to review this submission? You can work on the review at your own pace. Let me know!

**Comment by prashjha** [comment]
Howdy, @calum-chamberlain! Is there a chance you could review this software article for JOSS? I believe it is in your field. Let me know. Thanks.

**Comment by vsangelidakis** [comment]
> HI @vsangelidakis, I hope you are settled into a new position. BTW, will you have time now to review this submission? You can work on the review at your own pace. Let me know!

Hi @prashjha, all settled now, thank you - I can review this work. I will keep you updated as I progress.

**Comment by prashjha** [comment]
Hi @vsangelidakis, please wait before starting the review as we need one more reviewer. Once the second reviewer is added, you will be directed to the new 'github issue' where you will get your own review checklist. Once you have the checklist, you can start the review.

**Comment by prashjha** [comment]
Hi @dbrizard, would you be interested in reviewing this software article for JOSS? I think this work is in your area of interest. You can learn more about the review process [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). 

Let me know!

**Comment by dbrizard** [comment]
Hi @prashjha, yes it is in my area of interest and I would be interested in reviewing this software...
... but I have been struggling with the installation of the module for more than one hour without success because I am running Python 3.6.8 and the module requires 3.8. So I need to install Python 3.8 (and get familiar with virtual environments for the occasion, which is new to me).
So I need to be sure I am able to import the module and run the code before accepting.

**Comment by dbrizard** [comment]
Done, I can install the module! 
This review is the perfect opportunity to start using venv!
I accept.

**Comment by prashjha** [comment]
@dbrizard awesome...i am adding you as reviewer...we are good to start the review :D

**Comment by prashjha** [comment]
@editorialbot add @dbrizard as reviewer

**Comment by prashjha** [comment]
@ccaprani, we are ready to start the review. Review will be carried out in new github issues. Thanks, @vsangelidakis and @dbrizard for agreeing to review this submission.

**Comment by prashjha** [comment]
@editorialbot start review
