### ISSUE TITLE
[PRE REVIEW]: Archeofrag: an R package for refitting and spatial analysis in archaeology. Presentation and tutorial

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4178]
**Submitting author:** @sebastien-plutniak (<a href="http://orcid.org/0000-0002-6674-3806">Sébastien Plutniak</a>)
**Repository:** https://github.com/sebastien-plutniak/archeofrag
**Branch with paper.md** (empty if default branch): 
**Version:** v0.7.1
**Editor:** @martinfleis
**Reviewers:** @joeroe, @zoometh
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ff2007d87bd4c8460b265c69dc403316/status.svg)](https://joss.theoj.org/papers/ff2007d87bd4c8460b265c69dc403316)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ff2007d87bd4c8460b265c69dc403316"><img src="https://joss.theoj.org/papers/ff2007d87bd4c8460b265c69dc403316/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ff2007d87bd4c8460b265c69dc403316/status.svg)](https://joss.theoj.org/papers/ff2007d87bd4c8460b265c69dc403316)
```

**Author instructions**

Thanks for submitting your paper to JOSS @sebastien-plutniak. **Currently, there isn't an JOSS editor assigned** to your paper.

@sebastien-plutniak if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `archeofrag-paper.md` is 4403

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (376.2 files/s, 51857.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               17            156             98            980
Markdown                         3            352              0            837
Rmd                              2            235            387            155
TeX                              1             26              0            142
YAML                             2              5              4             69
-------------------------------------------------------------------------------
SUM:                            25            774            489           2183
-------------------------------------------------------------------------------


Statistical information for the repository '766797077ae3f7576207b03f' was
gathered on 2022/02/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4720392 is OK
- 10.21105/joss.01821 is OK
- 10.18637/jss.v093.c01 is OK
- 10.18129/B9.bioc.RBGL is OK
- 10.1016/j.quaint.2015.11.080 is OK
- 10.1016/j.jas.2021.105501 is OK
- 10.5281/zenodo.4719577 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @sebastien-plutniak - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
Assuming your submission passes this step, you should then reduce the size of your paper.  It's currently 4403 words, and JOSS suggests papers of around 1000 words.  See https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain and the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

**Comment by arfon** [comment]
@editorialbot invite @kbarnhart as editor

**Comment by arfon** [comment]
@kbarnhart – would you be willing to edit this submission for JOSS (providing you think this submission meets our scope)?

**Comment by kbarnhart** [comment]
@arfon I think this might be too far out of my expertise.

**Comment by sebastien-plutniak** [comment]
what about @leouieda ?

**Comment by kyleniemeyer** [comment]
@martinfleis could you this submission?

**Comment by kyleniemeyer** [comment]
@editorialbot invite @martinfleis as editor

**Comment by martinfleis** [comment]
@editorialbot assign me as editor

**Comment by martinfleis** [comment]
@kyleniemeyer yes, I should be able to edit this submission.

**Comment by martinfleis** [comment]
Hi @sebastien-plutniak!

A few editorial comments before we'll find reviewers for your package. 

1. The repository currently does not contain the `LICENSE` file with the OSI approved license under which your software is distributed. Can you please add it?
2. The paper needs to be shortened as pointed out by @danielskatz above. I suggest removing the `Use case` section and moving it to the documentation of the package.
3. The Readme (is there any other documentation?) is missing community guidelines. There should be clear guidelines for third-parties wishing to:
    - Contribute to the software
    - Report issues or problems with the software
    - Seek support

Also, if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by sebastien-plutniak** [comment]
Hi @martinfleis,
thank you for handling this submission and for this first series of comments.
1. I added a license file
2. I moved the use case to the README and to the vignette of the package
3. the DESCRIPTION file includes a `BugReports` line and my email. Is this not enough?

About potential reviewers, I might suggest: platipodium, benmarwick, steko (from the JOSS reviewers list) and, additionally, Oliver Nakoinz and Alfredo Cortell.

**Comment by martinfleis** [comment]
@editorialbot generate pdf

**Comment by martinfleis** [comment]
@editorialbot check references

**Comment by martinfleis** [comment]
> the DESCRIPTION file includes a BugReports line and my email. Is this not enough?

That does not cover all what I mentioned.

```
Contribute to the software
Report issues or problems with the software
Seek support
```

I would also suggest using an open platform for support, rather than an email. It can be via Github issues as well but you don't want to answer the same questions repeatedly so the support forum should be searchable. You should also explicitly state how others could contribute to the software.

**Comment by sebastien-plutniak** [comment]
Ok, I added a “Community guidelines” section and the required
information in the README.

In addition, two other potential reviewers: Clemens Schmid, Néhémie
Strupler

**Comment by martinfleis** [comment]
@editorialbot add @joeroe as reviewer

**Comment by zoometh** [comment]
@martinfleis it's fine with me if you want to add me as a reviewer

**Comment by martinfleis** [comment]
@editorialbot add @zoometh as reviewer

Thanks @zoometh!

**Comment by martinfleis** [comment]
@editorialbot start review
