### ISSUE TITLE
[REVIEW]: ENASearch: A Python library for interacting with ENA's API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#418]
**Submitting author:** @bebatut (<a href="http://orcid.org/0000-0001-9852-1987">Bérénice Batut</a>)
**Repository:** <a href="https://github.com/bebatut/enasearch" target ="_blank">https://github.com/bebatut/enasearch</a>
**Version:** 0.2.0
**Editor:** @brainstorm
**Reviewer:** @vals
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1034619" target="_blank">10.5281/zenodo.1034619</a>

## Status

[![status](http://joss.theoj.org/papers/8488b6c26819816ec5daa58d4df80488/status.svg)](http://joss.theoj.org/papers/8488b6c26819816ec5daa58d4df80488)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8488b6c26819816ec5daa58d4df80488"><img src="http://joss.theoj.org/papers/8488b6c26819816ec5daa58d4df80488/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8488b6c26819816ec5daa58d4df80488/status.svg)](http://joss.theoj.org/papers/8488b6c26819816ec5daa58d4df80488)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bebatut/enasearch" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@vals, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bebatut/enasearch">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.1)?
- [x] **Authorship:** Has the submitting author (@bebatut) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @vals it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by brainstorm** [comment]
@vals, hope all is clear with the instructions above? Let me know if you run into doubts/issues, happy to help!

**Comment by vals** [comment]
I have now reviewed the repository in accordance to the guidelines.

Due to the following issues, I would not accept it at the moment:

  - No functional claims of the software: bebatut/enasearch#25
  - No statement of need: bebatut/enasearch#26
  - No example usage: bebatut/enasearch#27
  - The functionality documentation is not clear: bebatut/enasearch#28
  - No JOSS paper file: bebatut/enasearch#29

/Valentine

**Comment by brainstorm** [comment]
Thanks @vals for your thorough review 👍 

Let's give a chance to @bebatut to address those issues and give some feedback ;)

**Comment by bebatut** [comment]
Thanks a lot @vals for the review! It helps us to improve a lot the documentation at http://bebatut.fr/enasearch/. So I hope I solved the issues you pointed:
- No functional claims of the software: it should be solved with [PR#33](https://github.com/bebatut/enasearch/pull/33) and [PR#30](https://github.com/bebatut/enasearch/pull/30)
- No statement of need: it should be solved with [PR#30](https://github.com/bebatut/enasearch/pull/30)
- No example usage: it should be solved with [PR#33](https://github.com/bebatut/enasearch/pull/33)
- The functionality documentation is not clear
   - More documentation about the interaction with ENA has been added with [PR#34](https://github.com/bebatut/enasearch/pull/35). It should clarify the different type of data and commands
   - I will add more description about the outputs of the commands during the week
- No JOSS paper file: it is located in [`src/paper/paper.md`](https://github.com/bebatut/enasearch/blob/master/src/paper/paper.md)
     Must it be at the root of the repo?

Please tell me if you think there is more missing or not clear

**Comment by vals** [comment]
Hi @bebatut 

With these changes the software is more clear. It now satisfies the conditions for a JOSS publication.

/Valentine

**Comment by brainstorm** [comment]
Thanks much @vals for your review!

@bebatut At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bebatut** [comment]
@brainstorm I will make an archive on Zenodo. But, because of the changes I made thanks to @vals, I was thinking about increasing the version. Is it possible?

**Comment by brainstorm** [comment]
Yeah, make sure you include the changes proposed by Valentine and bump up the version ;)

**Comment by bebatut** [comment]
The release is: 0.2.0 
Its DOI: 10.5281/zenodo.1034619

**Comment by brainstorm** [comment]
@whedon set 10.5281/zenodo.1034619 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1034619" target="_blank">10.5281/zenodo.1034619</a> is the archive.

**Comment by bebatut** [comment]
@whedon set 0.2.0 as version

**Comment by bebatut** [comment]
(I am trying...)

**Comment by brainstorm** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by brainstorm** [comment]
@arfon I guess that indicating a new version does require a new DOI? I don't know what's the status of that discussion I'm afraid :-S

**Comment by bebatut** [comment]
Which DOI? Because the DOI for the archive is currently for the new version.

**Comment by arfon** [comment]
@vals - many thanks for your review and to @brainstorm for editing this submission ✨ 

@bebatut - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00418 ⚡️ 🚀 💥

**Comment by bebatut** [comment]
Thanks @vals for the reviews, @brainstorm for editing and @arfon globally
