### ISSUE TITLE
[REVIEW]: mxnorm: An R Package to Normalize Multiplexed Imaging Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4180]
**Submitting author:** @ColemanRHarris (<a href="http://orcid.org/0000-0002-6325-0694">Coleman Harris</a>)
**Repository:** https://github.com/ColemanRHarris/mxnorm
**Branch with paper.md** (empty if default branch): joss-paper
**Version:** v1.0.2-joss
**Editor:** @osorensen
**Reviewers:** @askerdb, @tijeco
**Archive:** 10.5281/zenodo.6390746

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07/status.svg)](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07"><img src="https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07/status.svg)](https://joss.theoj.org/papers/c18a1df622016c6ea8ed9e67dda73d07)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ColemanRHarris/mxnorm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@askerdb & @tijeco, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @osorensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @askerdb
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/ColemanRHarris/mxnorm">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ColemanRHarris/mxnorm">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@ColemanRHarris) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @tijeco
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/ColemanRHarris/mxnorm">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ColemanRHarris/mxnorm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ColemanRHarris) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (485.6 files/s, 36050.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               48            347            749           1581
Markdown                         2             65              0            289
TeX                              1             21              0            179
Rmd                              2            190            372            142
-------------------------------------------------------------------------------
SUM:                            53            623           1121           2191
-------------------------------------------------------------------------------


Statistical information for the repository '405ebfc6c496af7d0471122c' was
gathered on 2022/02/18.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #4180 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by osorensen** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04180/joss.04180/10.21105.joss.04180.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04180/joss.04180/10.21105.joss.04180.pdf) :page_facing_up: :point_left:

**Comment by ColemanRHarris** [comment]
Hi @osorensen, any updates on these reviews? Thanks in advance!

**Comment by osorensen** [comment]
@askerdb @tijeco can you please update us on how it's going with your reviews?

**Comment by tijeco** [comment]
@osorensen I'm terribly sorry for the delay. I've had some unexpected events come up that I've been dealing with. I have the review on my calendar for this weekend. I hope that's okay.

**Comment by osorensen** [comment]
Thanks for the quick reply @tijeco. That's absolutely fine

**Comment by tijeco** [comment]
@osorensen @ColemanRHarris I'm going through this now. I've installed the software in a fresh environment and have a few notes / suggestions for the author to include in the documentation. On my end, it wouldn't install unless lme4 and nloptr were also installed. I've raised this as an issue on the mxnorm repo (https://github.com/ColemanRHarris/mxnorm/issues/4)

**Comment by tijeco** [comment]
@osorensen @ColemanRHarris I don't see automated tests. I see the test scripts though! I've raised an issue here (https://github.com/ColemanRHarris/mxnorm/issues/5)

**Comment by tijeco** [comment]
@osorensen @ColemanRHarris I'm not sure if this needs its own separate issue, but I don't see a contributing section.

**Comment by tijeco** [comment]
@osorensen @ColemanRHarris I ran into an interesting issue when going through the examples in the README, I've raised a separate issue (https://github.com/ColemanRHarris/mxnorm/issues/6).

**Comment by osorensen** [comment]
Thanks for all your points, @tijeco!

**Comment by askerdb** [comment]
> @askerdb @tijeco can you please update us on how it's going with your reviews?

Sorry about the delay, I somewhat overestimated how much time I had to do this. I will get to it within this week!

**Comment by osorensen** [comment]
Thanks @askerdb, looking forward to hearing back from you.

**Comment by askerdb** [comment]
@osorensen I can't edit the checklist I suspect I forgot to accept the invite before it expired, is it possible to make a new one?

**Comment by osorensen** [comment]
@askerdb, could you try running `@editorialbot generate my checklist`? It should generate a new checklist which you can use instead.

**Comment by askerdb** [comment]
@editorialbot generate my checklist

**Comment by askerdb** [comment]
I added an issue about references to the underlying software https://github.com/ColemanRHarris/mxnorm/issues/7
and am waiting for clarification on the automated tests and contributors file the other reviewer raised. The software installed (from cran) and ran perfectly for me.

**Comment by ColemanRHarris** [comment]
Hi @askerdb and @tijeco, thank you so much for your feedback here! I'm going to address these issues in the next week and follow up -- much appreciated!

**Comment by ColemanRHarris** [comment]
> @osorensen @ColemanRHarris I'm not sure if this needs its own separate issue, but I don't see a contributing section.

A "Community Guidelines" section has been added to the package README here: https://github.com/ColemanRHarris/mxnorm#community-guidelines

**Comment by ColemanRHarris** [comment]
I believe that I’ve addressed all of the open issues:
- Added information about dependencies and installation instructions in the [Dependencies](https://github.com/ColemanRHarris/mxnorm#dependencies) section of the README.
- Added automated testing via Github Actions.
- Added a [Community Guidelines](https://github.com/ColemanRHarris/mxnorm#community-guidelines) section to the README.
- Added details about methods used in the `mxnorm` package to the Functionality section of the paper text.

Thank you @askerdb and @tijeco for your excellent feedback. What else do you need from me @osorensen?

**Comment by osorensen** [comment]
Thanks @ColemanRHarris. 

@tijeco and @askerdb, when you have time, can you please go through these updates and see if they address you concerns? If so, please also update your checklists.

**Comment by askerdb** [comment]
@whedon generate pdf from branch joss-paper

**Comment by danielskatz** [comment]
@editorialbot generate pdf

(new version of commands for new and improved bot)

**Comment by askerdb** [comment]
I believe my concerns have been adressed, and have updated my checklist accordingly.

I also believe this is a valuable software contribution, congratulations @ColemanRHarris on a job well done.

**Comment by osorensen** [comment]
Dear @tijeco, could you please check whether the last updates address the points raised in your review, and if so, update your checklist? Thanks in advance!

**Comment by tijeco** [comment]
@osorensen It's oh my calendar for the weekend!

**Comment by tijeco** [comment]
@osorensen All looks well to me! I've updated my checklist.

@ColemanRHarris You've done a tremendous job on this project! Congrats on your contribution to software that will serve the community for years to come!

**Comment by osorensen** [comment]
Thanks @tijeco!

**Comment by osorensen** [comment]
@editorialbot generate pdf

**Comment by osorensen** [comment]
@editorialbot check references

**Comment by osorensen** [comment]
@ColemanRHarris, before I can recommend acceptance, please fix the following issues: 

- Add the missing DOIs stated in the post above.
- The term "Figure 1" is duplicated in the caption to Figure 1. Please fix.
- Be consistent, and use full journal names for all references. For example, on line 111, use Journal of Statistical Software rather than J Stat Softw.
- Make sure R is properly capitaliizied in the references, e.g., on line 176. You can enforce this by adding an extra set of curly braces in the `.bib` source file. For this particular example, that would mean writing `booktitle={Bioinformatics and computational biology solutions using {R} and {Bioconductor}}.`

Otherwise, congratulations with a very good and useful R package!

**Comment by ColemanRHarris** [comment]
@editorialbot generate pdf

**Comment by ColemanRHarris** [comment]
@editorialbot check references

**Comment by ColemanRHarris** [comment]
@editorialbot check references

**Comment by ColemanRHarris** [comment]
Hi @osorensen, I've addressed each of the issues above. Please let me know if you need anything else from me!

**Comment by osorensen** [comment]
Thanks @ColemanRHarris!

At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by ColemanRHarris** [comment]
Hi @osorensen! I have completed the above tasks:

- The version tag of the archived version is `v1.0.2-joss`.
- The DOI of the archived version is `10.5281/zenodo.6390746`.

**Comment by osorensen** [comment]
@editorialbot set 10.5281/zenodo.6390746 as archive

**Comment by osorensen** [comment]
@editorialbot set v1.0.2-joss as version

**Comment by osorensen** [comment]
@editorialbot recommend-accept

**Comment by osorensen** [comment]
@openjournals/joss-eic, note that the review checklist for @askerdb appears as a comment in this issue, while the checklist for @tijeco appears at the top. Both checklists are completely filled out.

**Comment by kyleniemeyer** [comment]
Hi @ColemanRHarris, I'm doing some final checks before publishing.

Could you add the appropriate `arXiv:YYMM.NNNNv# [category]` to the McInnes reference, and any other arXiv references I may have missed? You can do this in the `.bib` file with `{\tt arXiv:0706.1234 [math.FA]}` (for example)

**Comment by ColemanRHarris** [comment]
Hi @kyleniemeyer, I have added the arXiv reference as requested. Thank you!

**Comment by kyleniemeyer** [comment]
@editorialbot generate pdf

**Comment by kyleniemeyer** [comment]
@editorialbot accept

**Comment by kyleniemeyer** [comment]
Congratulations @ColemanRHarris on your article's publication in JOSS!

Many thanks to @askerdb and @tijeco for reviewing this, and @osorensen for editing.

**Comment by ColemanRHarris** [comment]
Huge thank you to @tijeco and @askerdb for your reviews, and @osorensen and @kyleniemeyer for your editorial work. Much appreciated! 🎉
