### ISSUE TITLE
[REVIEW]: Synaptus: A Matlab/Octave toolbox for synthetic aperture ultrasound imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4185]
**Submitting author:** @mh-skjelvareid (<a href="http://orcid.org/0000-0003-2103-865X">Martin H. Skjelvareid</a>)
**Repository:** https://github.com/mh-skjelvareid/synaptus
**Branch with paper.md** (empty if default branch): 
**Version:** v1.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @emanuelhuber, @Kevin-Mattheus-Moerman
**Archive:** 10.5281/zenodo.6974195

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/11a4c24fd2f5b2ff9b7d32206453864f/status.svg)](https://joss.theoj.org/papers/11a4c24fd2f5b2ff9b7d32206453864f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/11a4c24fd2f5b2ff9b7d32206453864f"><img src="https://joss.theoj.org/papers/11a4c24fd2f5b2ff9b7d32206453864f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/11a4c24fd2f5b2ff9b7d32206453864f/status.svg)](https://joss.theoj.org/papers/11a4c24fd2f5b2ff9b7d32206453864f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mh-skjelvareid/synaptus" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Kevin-Mattheus-Moerman & @emanuelhuber, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @Kevin-Mattheus-Moerman
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mh-skjelvareid/synaptus">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mh-skjelvareid/synaptus">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mh-skjelvareid) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @emanuelhuber
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mh-skjelvareid/synaptus">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mh-skjelvareid/synaptus">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mh-skjelvareid) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Samuel-Wagner, @emanuelhuber it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1526

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/1.1440826 is OK
- 10.1190/1.1440899 is OK
- 10.1017/9781316756041 is OK
- 10.1109/TUFFC.2010.1718 is OK
- 10.1109/TUFFC.2007.400 is OK
- 10.1109/TUFFC.2011.1904 is OK
- 10.1109/TUFFC.2012.2478 is OK
- 10.1063/1.3703163 is OK
- 10.1016/j.ndteint.2012.10.005 is OK
- 10.1063/1.4928118 is OK
- 10.1109/ULTSYM.2017.8092389 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (617.3 files/s, 75709.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          29            469           1133           1573
Markdown                         5            230              0            778
TeX                              1             18              0            191
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            36            718           1137           2560
-------------------------------------------------------------------------------


Statistical information for the repository '24166a9027d768e496096f49' was
gathered on 2022/02/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04185/joss.04185/10.21105.joss.04185.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04185/joss.04185/10.21105.joss.04185.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@Samuel-Wagner, @emanuelhuber this is where the review takes place. You can now start and you can post comments to the author here or open dedicated issues on their software repository and link to them here. 

Please let me know if you have any questions. Thanks again for your help!!!!

**Comment by Kevin-Mattheus-Moerman** [comment]
@Samuel-Wagner, @emanuelhuber I hope you are doing well. Could you provide an update on how the review is going or if you have started yet? No worries if you haven't started yet, I am just checking in. Thanks again for your help.

**Comment by emanuelhuber** [comment]
@Kevin-Mattheus-Moerman  I started the review, installed Octave . Hope to be finished by the end of the week.
Best,
Emanuel

**Comment by emanuelhuber** [comment]
(@Kevin-Mattheus-Moerman should I leave the check box "Installation instructions" unchecked if the requirement seems to be not completely fulfilled? 

Here are some points I rise

## Documentation

- readme.md file: In the summary the author explains that the toolbox is for a certain type of data but he does not explain what exactly the toolbox do (i.e., focusing these kind of data). I do not know if the toolbox can do more than focusing.
- There is no "clearly-stated list of dependencies": I had to install the 'signal' toolbox which required the 'control' toolbox. A short information about the dependence on signal and how to install and load the 'signal' toolbox would be welcome (why should I load manually the signal package?).
- I could not find any "external" API method documentation but the function are documented in their file and the three main focusing methods are described in the readme file and the examples allow to find the corresponding functions. It requires some extra "dig work" for novices to octave (like me). The simplified algorithms are surely a great ressource for the community.
- examples: 
	- Both file 'array_psm_testFullMatrix_1layer.m' and 'array_psm_testFullMatrix_2layer.m' have exactly the same note ('copper block') but load different files ('steel pins' and 'copper block'). Please check if the notes are correct.
- When running 'cpsm_test2D.m' I got the following error :
   	```
	All image ranges processed
	Total processing time: 1.3711 seconds.
	error: text: Invalid combination of points and text strings
	error: called from
	    text at line 128 column 7
	    polRawDataImage at line 93 column 1
	    cpsm_test2D at line 30 column 1
    	```

## Software paper

- Statement of need: 
	- I suggest the author to repeat that synaptus is a toolbox for focusing...
	- The author writes that Alain Plattner used "the code". This is misleading and it would be better to replace "the code" with the "Stolt fk migration function".
	- I found other open-source toolboxes for SAR data focusing, it would be interesting to know how they differ from synaptus:
		- https://github.com/ThatcherC/RadarPro
		- https://github.com/cryotools/osaris
		- http://step.esa.int/main/toolboxes/snap/snap-faq/
	- Just as a remark: yes, Python is very popular and [Julia](https://julialang.org/) seems even more promising.

## Conclusion

The paper is well written, the code is documented, datasets are available, the examples work well, I could run everything although I am not an octave/matlab user and some effort has been done to explains some of the algorithm. I warmly thank the author for his contribution to the community!

**Comment by mh-skjelvareid** [comment]
@emanuelhuber , thank you for your valuable feedback! I will try to follow up on and correct each point that you have raised. Thanks also for being patient and flexible regarding installation of octave. As indicated in the paper, I'd like to update the toolbox to an open source (and perhaps more modern) programming language, for example Python. I haven'y used Julia but I will definitely look into it. 

@Kevin-Mattheus-Moerman : I guess I should wait for Samuel-Wagner to finish his review before I start changing anything?

**Comment by emanuelhuber** [comment]
@mh-skjelvareid , I startet programming with Matlab 20 years ago, then I switched to R (which is very similar to Matlab). Now I am learning Python for my job and I don't like it. I wrote a R-package (RGPR) and am still playing with the thought to translate it in another language. First I thought that Python would be great because many people in geosciences use it. But now I don't know... maybe write C/C++ functions that can be used in any language? Write a Julia package?

**Comment by Kevin-Mattheus-Moerman** [comment]
@emanuelhuber 
> ... should I leave the check box "Installation instructions" unchecked if the requirement seems to be not completely fulfilled?

Yes, leave anything you are not happy with unchecked until resolved.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid 
>  I guess I should wait for Samuel-Wagner to finish his review before I start changing anything?

No you can start addressing @emanuelhuber 's comments right away if you like.

**Comment by Kevin-Mattheus-Moerman** [comment]
@Samuel-Wagner can you provide an update on how you are getting on with the review? It is okay if you need more time, just let us know, I am only checking in to see how things stand. Thanks again for your help.

**Comment by mh-skjelvareid** [comment]
@whedon generate pdf

**Comment by mh-skjelvareid** [comment]
@editorialbot generate pdf

**Comment by mh-skjelvareid** [comment]
@Kevin-Mattheus-Moerman , I have now tried to address the points raised by @emanuelhuber : 


> **Documentation**
> * readme.md file: In the summary the author explains that the toolbox is for a certain type of data but he does not explain what exactly the toolbox do (i.e., focusing these kind of data). I do not know if the toolbox can do more than focusing.


I have updateed the summary to clarify that the only purpose of the toolbox is to focus pulse-echo data.

> * There is no "clearly-stated list of dependencies": I had to install the 'signal' toolbox which required the 'control' toolbox. A short information about the dependence on signal and how to install and load the 'signal' toolbox would be welcome (why should I load manually the signal package?).


I have added "Requirements" section to the readme.md file which states that the toolbox requires Matlab / Octave and a signal toolbox to run. I've added a few practical details regarding installation of these.

> * I could not find any "external" API method documentation but the function are documented in their file and the three main focusing methods are described in the readme file and the examples allow to find the corresponding functions. It requires some extra "dig work" for novices to octave (like me). The simplified algorithms are surely a great ressource for the community.

I've added a "Documentation" section which states that the main toolbox functions are documented in the standard Matlab/Octave style (description at start of function). The documentation can be viewed on the Matlab/Octave command line by using the `help` command. I've also described how the "test" scripts are intended as a demonstration of how to use the toolbox. 

> * Both file 'array_psm_testFullMatrix_1layer.m' and 'array_psm_testFullMatrix_2layer.m' have exactly the same note ('copper block') but load different files ('steel pins' and 'copper block'). Please check if the notes are correct.

The description in 'array_psm_testFullMatrix_1layer.m' was incorrect and has been updated - thanks!

> * When running 'cpsm_test2D.m' I got the following error :
> All image ranges processed
> Total processing time: 1.3711 seconds.
> error: text: Invalid combination of points and text strings
> error: called from
>     text at line 128 column 7
>     polRawDataImage at line 93 column 1
>     cpsm_test2D at line 30 column 1
> 	```

The `polRawDataImage` and `polFocusedImage` functions have been fixed to avoid this error.

> **Software paper**
> Statement of need:
> * I suggest the author to repeat that synaptus is a toolbox for focusing...

I wasn't entirely sure what Emanuel meant by this comment, but I'm guessing he wanted a similar clarification 
as in the readme.md file (a statement that the toolbox is only used for creating focused images). I have tried to add this in the introduction to the Statement of need.

> * The author writes that Alain Plattner used "the code". This is misleading and it would be better to replace "the code" with the "Stolt fk migration function".

This passage has been updated as recommended.

> * I found other open-source toolboxes for SAR data focusing, it would be interesting to know how they differ from synaptus:
> https://github.com/ThatcherC/RadarPro
> https://github.com/cryotools/osaris
> http://step.esa.int/main/toolboxes/snap/snap-faq/

I have added a paragraph to the paper referencing some of these toolboxes, and explaining that
* They are generally so specialized towards radar data that they are hard to use for ultrasonic data
* They cannot process multi-layer data, which is one of the main features of the `Synaptus` toolbox.

**Comment by emanuelhuber** [comment]
@Kevin-Mattheus-Moerman Thank you very much for adressing all my comments. Everything is fine!

@mh-skjelvareid In my opinion, the paper is ready for publication.

**Comment by emanuelhuber** [comment]
@Kevin-Mattheus-Moerman All check boxes are now checked!

**Comment by Kevin-Mattheus-Moerman** [comment]
@Samuel-Wagner how are you getting on? Are you able to start this review? Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
I have just emailed @Samuel-Wagner a reminder about this review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@Samuel-Wagner can you please update us on review progress?

**Comment by Kevin-Mattheus-Moerman** [comment]
> @Samuel-Wagner can you please update us on review progress?

:point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@Samuel-Wagner Since we have not hear from you I will now assume you cannot review this work and will remove you as a reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot remove @Samuel-Wagner as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon given that it has been challenging to find reviewers for this submission and that one of the reviewers was unable to complete the review I proposed that I will review this work as a second reviewer. Given my MATLAB and image analysis skills I feel I can review this quite well.

**Comment by arfon** [comment]
Sounds good to me @Kevin-Mattheus-Moerman 👍🏻

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot add @Kevin-Mattheus-Moerman as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid I installed and tested the software and it all works really well after I implemented the below minor fix. 

# Main issue

- [ ] Can you merge [this pull request](https://github.com/mh-skjelvareid/synaptus/pull/5), it fixes a bug for Ubuntu Linux. Namely that the path definitions did not work. I went through the various test codes and replaced stuff like: 
```matlab
%% Add path to necessary functions
addpath('../core','../misc')

%% Load test data
load('../datasets/ArraySteelPins.mat','data','MWB')
```

with 
```matlab

%% Add path to necessary functions
toolboxPath=fileparts(fileparts(mfilename('fullpath'))); %Get the toolbox path

%Add core and misc path
addpath(fullfile(toolboxPath,'core'),fullfile(toolboxPath,'misc'));

%% Load test data
load(fullfile(toolboxPath,'datasets','ArraySteelPins.mat'),'data','MWB')
```
This fix should work for all operational systems. 

# Minor comments (not requirements): 
- [ ] Note that you currently use both `caxis([minVal maxVal])` as well as `set(gca,'CLim',[minVal maxVal])`, for clarity you could consider just using one approach. The former (the use of `axis`) is labelled as deprecated for future MATLAB releases in favor of `clim([minVal maxVal])`. However, do check compatibility with Octave too which may still use the `axis` approach. 
- [ ] Note that `clear all` is the same as `clear` since `all` is default. Elsewhere you use `clearvars` which probably does the same thing again. But again, check Octave compatibility too. 
- [ ] You sometime have `disp('Loading data');` and `disp('Processing data');` as messages in the tests, but not always, consider using it for all tests. 
- [ ] You may consider, in future work, implementing automated testing, e.g. by running all tests automatically (see also something like: https://github.com/gibbonCode/GIBBON/blob/master/lib/testGibbon.m). 
- [ ] You may also consider, in future work, making the tests "publishable" in the MATLAB code publishing sense, this way they can turn in to HTML files that you can render as documentation too. Once again GIBBON might be an example. 
- [ ] Similarly you may consider automated script based installation (which could simple be adding the toolbox paths and saving them).

**Comment by mh-skjelvareid** [comment]
@Kevin-Mattheus-Moerman  Thanks a lot for the nice fix for the path definitions, and the other comments regarding consistency and testing. I've addressed the main point and some of the listed suggestions. I've checked the boxes for issues that have been fixed, and have added comments in between.

> @mh-skjelvareid I installed and tested the software and it all works really well after I implemented the below minor fix.
> 
> # Main issue
> * [x ]  Can you merge [this pull request](https://github.com/mh-skjelvareid/synaptus/pull/5), it fixes a bug for Ubuntu Linux. Namely that the path definitions did not work. I went through the various test codes and replaced stuff like:
> 
> ```matlab
> %% Add path to necessary functions
> addpath('../core','../misc')
> 
> %% Load test data
> load('../datasets/ArraySteelPins.mat','data','MWB')
> ```
> 
> with
> 
> ```matlab
> %% Add path to necessary functions
> toolboxPath=fileparts(fileparts(mfilename('fullpath'))); %Get the toolbox path
> 
> %Add core and misc path
> addpath(fullfile(toolboxPath,'core'),fullfile(toolboxPath,'misc'));
> 
> %% Load test data
> load(fullfile(toolboxPath,'datasets','ArraySteelPins.mat'),'data','MWB')
> ```
> 
> This fix should work for all operational systems.

Done!

> 
> # Minor comments (not requirements):
> * [x ]  Note that you currently use both `caxis([minVal maxVal])` as well as `set(gca,'CLim',[minVal maxVal])`, for clarity you could consider just using one approach. The former (the use of `axis`) is labelled as deprecated for future MATLAB releases in favor of `clim([minVal maxVal])`. However, do check compatibility with Octave too which may still use the `axis` approach.

I've gone through the code and changed this to consistent use of caxis([minVal,maxVal]).

> * [x ]  Note that `clear all` is the same as `clear` since `all` is default. Elsewhere you use `clearvars` which probably does the same thing again. But again, check Octave compatibility too.

I've gone through and changed the first lines of each script to "close all; clearvars". "clearvars" only clears variables while "clear" clears everything. It doesn't matter much for the test scripts, I think, but I've found clearvars to work better in some cases, so I've made it a habit. 

> * [x ]  You sometime have `disp('Loading data');` and `disp('Processing data');` as messages in the tests, but not always, consider using it for all tests.

I've added this for all the tests, and I've also standardized the measurement of processing time for each test (using only tic and toc). 

> * [x ]  You may consider, in future work, implementing automated testing, e.g. by running all tests automatically (see also something like: https://github.com/gibbonCode/GIBBON/blob/master/lib/testGibbon.m).

I've added a new script, "tests_runAll.m", which displays a "test suite header" and then runs each test one by one. Inside each of the tests I've also added a bit of code which displays a header. This gives a nice separation between the text output ("Processing layer 1 of 2" etc.) from each test. 

> * [ ]  You may also consider, in future work, making the tests "publishable" in the MATLAB code publishing sense, this way they can turn in to HTML files that you can render as documentation too. Once again GIBBON might be an example.

This seems like a nice solution. I'm not sure if I understand exactly how it works, though. Is all the documentation generated through (Matlab) publishing during installation? If so I guess it won't work for Octave? I get the sense that this could make for some nice documentation, but that it'll be a bit too much work for me to implement at this stage (the toolbox is no longer part of my active research work). 

> * [ ]  Similarly you may consider automated script based installation (which could simple be adding the toolbox paths and saving them).

I agree that this would make the installation a bit smoother. However, I have no experience in making installation scripts, and I'm expecting that it's hard to make something that works in absolutely all cases...(?) I think I'd prefer for the users to add the toolbox to the path of their particular installation of Matlab / Octave themselves.

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid thanks for implementing those changes and for your comments. I tested the changes this time using Octave on Ubuntu, rather than MATLAB, and all tests passed fine and the changes look good.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid I have proofread the paper and here are some last points and recommendations: 

- [ ] Please complete the affiliation with the full name of the institute, the city name, and the country. 
- [ ] Remove the statement: `NOTE: This is a draft version of a paper submitted to the Journal of Open Source Software (JOSS).`
- [ ] Check `more computationally efficient that operating` which should read `more computationally efficient than operating`
- [ ] Check `resouce` -> `resource` 
- [ ] Check `cartesian` -> `Cartesian'
- [ ] Check `procesing` -> `processing`
- [ ] Check `accomodate` -> `accommodate`
- [ ] Can you check for consistency with either American or European (Brittish/Irisih) English? E.g. You use `optimized`, `vectorized`, and `specialized` which favors American English, whereas the use of Aluminium over Aluminum favours Brittish English. Either is fine but it is best to be consistent. 
- [ ] Check `Overview of experiment setup`, this should perhaps be improved to something like `Overview of the experimental setup`
- [ ] Check `Seen from side` -> `Seen from the side`
- [ ] Check `ultrasonic raw data` -> `raw ultrasonic data`

**Comment by mh-skjelvareid** [comment]
@Kevin-Mattheus-Moerman, thanks for finding all these mistakes, I've corrected them all, and have also corrected a couple of other mistakes I found during spellchecking. I went for consistency with American English.

> @mh-skjelvareid I have proofread the paper and here are some last points and recommendations:
> 
> * [x]  Please complete the affiliation with the full name of the institute, the city name, and the country.
> * [x]  Remove the statement: `NOTE: This is a draft version of a paper submitted to the Journal of Open Source Software (JOSS).`
> * [x]  Check `more computationally efficient that operating` which should read `more computationally efficient than operating`
> * [x]  Check `resouce` -> `resource`
> * [x]  Check `cartesian` -> `Cartesian'
> * [x]  Check `procesing` -> `processing`
> * [x]  Check `accomodate` -> `accommodate`
> * [x]  Can you check for consistency with either American or European (Brittish/Irish) English? E.g. You use `optimized`, `vectorized`, and `specialized` which favors American English, whereas the use of Aluminium over Aluminum favours Brittish English. Either is fine but it is best to be consistent.
> * [x]  Check `Overview of experiment setup`, this should perhaps be improved to something like `Overview of the experimental setup`
> * [x]  Check `Seen from side` -> `Seen from the side`
> * [x]  Check `ultrasonic raw data` -> `raw ultrasonic data`

**Comment by mh-skjelvareid** [comment]
@editorialbot generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid it looks good except `Overview of the experiment setup` should still be changed to `Overview of the experimental setup`.

**Comment by mh-skjelvareid** [comment]
@Kevin-Mattheus-Moerman Sorry about that, fixed now.

**Comment by mh-skjelvareid** [comment]
@editorialbot generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid Now that all reviewers are happy with both the software and the paper we can proceed to process this for acceptance in JOSS. Here are some action items for you: 

- [ ] Please archive a copy of the software on ZENODO. You can do this manually if you like but some find [these automated steps](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) useful. 
- [ ] Please check and edit the ZENODO archive so that the title and the authors match those of the paper. Also check that the license is correct. Furthermore we recommend that you add your ORCID information to the ZENODO archive too. 
- [ ] Once you have the archived version created, please report back here with the archive DOI. 
- [ ] The current version tag is `v1.1.0`, is this still accurate or should we update this? Note the automated approach above may cause you to issue an updated version so please inform us what the version tag should be. 

Thanks.

**Comment by mh-skjelvareid** [comment]
@Kevin-Mattheus-Moerman , see replies below:

> @mh-skjelvareid Now that all reviewers are happy with both the software and the paper we can proceed to process this for acceptance in JOSS. Here are some action items for you:
> 
> * [x]  Please archive a copy of the software on ZENODO. You can do this manually if you like but some find [these automated steps](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) useful.
> * [x]  Please check and edit the ZENODO archive so that the title and the authors match those of the paper. Also check that the license is correct. Furthermore we recommend that you add your ORCID information to the ZENODO archive too.
> * [x]  Once you have the archived version created, please report back here with the archive DOI.

All done. The DOI is [10.5281/zenodo.6974194](https://doi.org/10.5281/zenodo.6974194)
I've added the DOI badge at the top of the ´README.md´ file: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.6974195.svg)](https://doi.org/10.5281/zenodo.6974195)

I think I got all the details right, but please check that I did. My chosen license is GNU GPL v3, but this wasn't available in the drop-down menu of possible licenses, so I chose the closest one, "GNU General Public License v2.0 or later" 

> * [x]  The current version tag is `v1.1.0`, is this still accurate or should we update this? Note the automated approach above may cause you to issue an updated version so please inform us what the version tag should be.

I believe that until now, the version has been v1.0 ("Initial release"), but I've created another release in order to get the Zenodo DOI, so the current (latest) version is v1.1. Does it look OK?

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot set 10.5281/zenodo.6974195 as archive

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid Odd that the GPL v3 license does not show up, I just checked and saw the same. Perhaps instead of picking a license which is the "closest one" I recommend you select the option "Other (open)".

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot recommend-accept

**Comment by Kevin-Mattheus-Moerman** [comment]
@editorialbot accept

**Comment by Kevin-Mattheus-Moerman** [comment]
Congratulations on this publication @mh-skjelvareid ! And special thanks to @emanuelhuber for reviewing this as well!! 

:tada:

**Comment by mh-skjelvareid** [comment]
Thanks a lot, @Kevin-Mattheus-Moerman, for stepping in yourself and making the publication happen (and for giving many useful tips along the way) - it really means a lot! :) And thanks again also to @emanuelhuber for generously using your time to review the software. 

I've found the whole process very interesting, and (with the exception of problems finding reviewers) very smooth and more "human" than similar processes I've been through before. Both the idea and the implementation of JOSS are really good! I will be signing up to be a reviewer myself.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mh-skjelvareid you are welcome @mh-skjelvareid. My apologies that the review to much longer than is normal for JOSS. Since COVID finding reviewers has been a challenges (as most people were/are behind on lots of work) as well as getting them to commit to a speedy review process. 

Great that you want to help review for JOSS. 

Congrats again!
