### ISSUE TITLE
[REVIEW]: dNami: a framework for solving systems of balance laws using explicit numerical schemes on structured meshes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4186]
**Submitting author:** @etouber (<a href="http://orcid.org/0000-0002-7553-0351">Emile Touber</a>)
**Repository:** https://github.com/dNamiLab/dNami
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewers:** @JamieJQuinn, @mancellin
**Archive:** Pending

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9/status.svg)](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9"><img src="https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9/status.svg)](https://joss.theoj.org/papers/55bf7f16fdc987f57c157e550bf9a7f9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dNamiLab/dNami" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @JamieJQuinn, @mancellin it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jcp.2003.09.003 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1145/2833157.2833162 is OK
- 10.1016/j.cpc.2021.107906 is OK
- 10.1103/PhysRevResearch.2.023068 is OK
- 10.1016/j.cpc.2014.07.011 is OK
- 10.1016/j.cpc.2020.107733 is OK
- 10.1016/j.cpc.2021.108063 is OK
- 10.1504/IJCSE.2009.029165 is OK
- 10.1109/MCSE.2021.3083216 is OK
- 10.1016/B978-0-12-802118-7.00023-6 is OK
- 10.31223/X55K8V is OK
- 10.21105/joss.02095 is OK
- 10.21105/joss.02978 is OK
- 10.21105/joss.00301 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1584

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.69 s (47.2 files/s, 8909.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          32           2067           1463           7181
Fortran 77                       6            554            148           1026
reStructuredText                18            698            888            349
TeX                              2             20              0            245
Markdown                         2             57              0            120
Fortran 90                      12             72              0             60
YAML                             2             11             14             44
Bourne Shell                     4              2              4             26
C/C++ Header                     1              5              0             22
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            80           3490           2524           9082
-------------------------------------------------------------------------------


Statistical information for the repository '2e3d7ccc9fc8a14f524e132e' was
gathered on 2022/02/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Emile Touber                    14            40             46            0.30
Nicolas Alferez                 32          2373           1654           14.07
Stephen                          2            88             19            0.37
Stephen Winn                    23          3323           2823           21.47
Yussuf                          14           961            207            4.08
Yussuf Ali                      13         11954           3842           55.18
stephenwinn16                    5           943            353            4.53
yali25                           1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Emile Touber                 32           80.0          0.2                0.00
Nicolas Alferez            1004           42.3          7.8               13.65
Stephen                      83           94.3          0.3               12.05
Stephen Winn                 20            0.6          3.2                5.00
Yussuf                     5939          618.0          5.1                6.45
Yussuf Ali                  325            2.7         17.5                4.62
stephenwinn16              3335          353.7          0.5               16.37
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04186/joss.04186/10.21105.joss.04186.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04186/joss.04186/10.21105.joss.04186.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi everyone! @JamieJQuinn, @mancellin, here is where the review will take place. As specific comments/issues come up, please open issues in the [software repo](https://github.com/dNamiLab/dNami) itself and link back to this review issue so we can track related issues/comments. You can track your overall review here with the checklist and ping the author(s) and me as needed, and otherwise let us know when you're finished.

**Comment by kthyng** [comment]
@etouber Forgot in the pre-review issue: please make sure to add a section to your paper called "Statement of Need" — we like to be very upfront about the purpose of the software in the paper.

**Comment by mancellin** [comment]
@kthyng I have a small issue:
I cannot check the item of the checklist, and I cannot find the invitation from whedon (error message from Github: `Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.`)

**Comment by kthyng** [comment]
@mancellin I see your issue and I have a question out to the editorial board about this because we migrated to some new technology under the review system the day after I started this review issue, and I'd like to see if this is related or not. I'll get back to you soon.

**Comment by kthyng** [comment]
@mancellin Ok sounds like we should try the new approach. Can you run this command at the top of a comment?

`@editorialbot generate my checklist`

This should generate your own checklist in line here in the comments that you will have access to. Assuming that works, I will then delete the list at the top of this issue, and then @JamieJQuinn would probably need to do the same thing. This is how the checklists will work moving forward to improve permissions issues, but we are right at the switchover time.

**Comment by JamieJQuinn** [comment]
@editorialbot generate my checklist

**Comment by etouber** [comment]
@whedon generate pdf

**Comment by etouber** [comment]
@editorialbot generate pdf

**Comment by mancellin** [comment]
dNami a very interesting, ambitious and meaningful work.

I was able to consult the documentation, install the code and run some test cases, without any major issue.
I don't have the hardware to really benchmark the HPC performance of the code, but the claims seems reasonable given my small scale tests.
I submitted a few minor issues, that are being addressed.

Overall, the code and the paper meet all the requirements, and **I can recommend the paper for publication**.


Nonetheless, I have some concerns about the long-term maintainability of the code. Code-writing code is hard to debug, and the design of dNami is not always simple and straightforward (e.g. up to 15 levels of indentations in genKer.py). I would suggest that the authors take some time to make sure of the correctness, readability and maintainability of the code. For instance, by adding a more extensive test suite including unit tests. Refactoring dNami into a pip-installable library that write and compile code in a directory that is not the sources of the library itself, could also make it more convenient both for users and for tests. I don't feel like making this kind of large refactoring a condition for the publication of this already good work, and leave this only as a suggestion to the authors.

**Comment by arfon** [comment]
@JamieJQuinn, @mancellin, @kthyng – This review is being paused due to an administrative issue that our editorial team is working through.  Please hold off doing any more work here until you hear back from us, and apologies for any inconvenience caused here!

**Comment by arfon** [comment]
@editorialbot withdraw

@JamieJQuinn, @mancellin, @kthyng – we've been notified by the authors that they would like to withdraw this submission. Thanks for your efforts here, sorry this one didn't work out.
