### ISSUE TITLE
[PRE REVIEW]: chloroExtractor: extraction and assembly of the chloroplast genome from whole genome shotgun data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#420]
**Submitting author:** @greatfireball (<a href="http://orcid.org/0000-0003-4166-5423">Frank Förster</a>)
**Repository:** <a href="https://github.com/chloroExtractorTeam/chloroExtractor" target ="_blank">https://github.com/chloroExtractorTeam/chloroExtractor</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @jdeligt

**Author instructions**

Thanks for submitting your paper to JOSS @greatfireball. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@greatfireball if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @tracykteal it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @tracykteal - the submitting author suggested you as the editor.

**Comment by greatfireball** [comment]
Hey @whedon, @arfon, and @tracykteal - thanks for the introduction. We are looking forward to work on this submission/review together.

**Comment by greatfireball** [comment]
Morning, @tracykteal, @whedon, and @arfon after six weeks without anything happen at this issue, I just wanted to ask if we need to provide something I missed or what we can to provide to speed things up.

Thanks in advance!

**Comment by arfon** [comment]
> Morning, @tracykteal, @whedon, and @arfon after six weeks without anything happen at this issue, I just wanted to ask if we need to provide something I missed or what we can to provide to speed things up.

Yep, looks like we need to find an alternative editor for this submission.

@pjotrp @biorelated @mgymrek - would one of you be willing to edit this submission for JOSS?

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by greatfireball** [comment]
Morning! Thanks for becoming the new editor for our submission @pjotrp Please let us know, if we can provide any assistance from our side

**Comment by jdeligt** [comment]
@whedon assign @jdeligt as reviewer

**Comment by whedon** [comment]
I'm sorry @jdeligt, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by pjotrp** [comment]
@whedon assign @jdeligt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jdeligt

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/464. Feel free to close this issue now!
