### ISSUE TITLE
[PRE REVIEW]: Testing custom branch

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4218]
**Submitting author:** @xuanxu (<a href="http://orcid.org/0000-0001-7699-3983">Juanjo Bazán</a>)
**Repository:** https://github.com/n8thangreen/BCEA/
**Branch with paper.md** (empty if default branch): JOSS-paper
**Version:** v2.4.1
**Editor:** Pending
**Reviewers:** Pending
**Managing EiC:** Juanjo Bazán

## Status

[![status](https://joss.theoj.org/papers/0f9cfa18f9d7d37337d98174be299609/status.svg)](https://joss.theoj.org/papers/0f9cfa18f9d7d37337d98174be299609)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0f9cfa18f9d7d37337d98174be299609"><img src="https://joss.theoj.org/papers/0f9cfa18f9d7d37337d98174be299609/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0f9cfa18f9d7d37337d98174be299609/status.svg)](https://joss.theoj.org/papers/0f9cfa18f9d7d37337d98174be299609)
```

**Author instructions**

Thanks for submitting your paper to JOSS @xuanxu. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @xuanxu.

@xuanxu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @editorialbot is here to help you find and assign reviewers and start the main review. To find out what @editorialbot can do for you type:

```
@editorialbot commands
```

**Comment by xuanxu** [comment]
Wrong repo
