### ISSUE TITLE
[PRE REVIEW]: Multiphonon: Phonon Density of States tools for Inelastic Neutron Scattering Powder Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#422]
**Submitting author:** @Yxqd (<a href="http://orcid.org/0000-0001-9233-0100">Jiao Lin</a>)
**Repository:** <a href="https://github.com/sns-chops/multiphonon" target ="_blank">https://github.com/sns-chops/multiphonon</a>
**Version:** 0.1.1
**Editor:** @lheagy
**Reviewer:** @bjmorgan

**Author instructions**

Thanks for submitting your paper to JOSS @Yxqd. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Yxqd if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as an editor.

**Comment by yxqd** [comment]
@arfon @lheagy May I suggest @tacaswell @nicoguaro or @bjmorgan as potential reviewers? Thanks.

**Comment by nicoguaro** [comment]
I will have to turn this one down.

**Comment by lheagy** [comment]
Happy to take this @arfon and @yxqd! I am travelling at the moment and then will be back into the swing of things on Monday. I will get back to you then. Thanks for your patience

**Comment by lheagy** [comment]
Condensed matter physics isn't really my background, but I am happy to work with this submission. @arfon, is there anyone else one the editorial board that you think might have more background in this that could support? 

@yxqd, I have a couple questions / comments regarding the paper:   
- right now, the summary is brief and quite technical. I would recommend you expand it to make it more accessible for a broader audience. This could include some examples, or further discussion of applications. 
- regarding the [notice of copyright](https://github.com/sns-chops/multiphonon/blob/master/paper/paper.md#notice-of-copyright) in the paper. All JOSS papers are licensed under a Creative Commons Attribution 4.0 License (http://joss.theoj.org/about#content_license). This does not appear to be a conflict, but I wanted to clarify that with you cc @arfon: are there any concerns with such a statement in the paper
- regarding testing, do you have coverage stats that could also be shown alongside the build status in the README? for example https://codecov.io/

**Comment by arfon** [comment]
> - regarding the notice of copyright in the paper. All JOSS papers are licensed under a Creative Commons Attribution 4.0 License (http://joss.theoj.org/about#content_license). This does not appear to be a conflict, but I wanted to clarify that with you cc @arfon: are there any concerns with such a statement in the paper

Thanks for the heads up @lheagy - I don't think this copyright statement causes us any major issues.

**Comment by arfon** [comment]
> Condensed matter physics isn't really my background, but I am happy to work with this submission. @arfon, is there anyone else one the editorial board that you think might have more background in this that could support?

Not really sorry. This is pretty much out of the remit of most of our editors I think.

**Comment by yxqd** [comment]
@lheagy thanks! I admit I don't know enough about the editors backgrounds and did not find an editor specializing on condensed matter physics. You were the closest I could find from the editor list since studies on condensed matter in extreme conditions (high temperature and high pressure, for example) are topics of research in geophysics. Again, thanks @lheagy for picking this up.

@lheagy regarding your comments:

* I agree more explanations should help clarify the applications of the software. I will revise the summary as you suggested
* The [notice of copyright](https://github.com/sns-chops/multiphonon/blob/master/paper/paper.md#notice-of-copyright) was a standard text required by our lab. I don't think it is in conflict with Creative Commons. @arfon please let us know if there are problems
* Tests are run by travis CI right now. I will try to get coverage stats as you suggested.

I am travelling this week so I will only be able to work on these revisions next week. I will keep you posted. @lheagy @arfon please kindly update me on the editing and the copyright text. Thanks!

**Comment by yxqd** [comment]
@lheagy could you please check the expanded summary in [the revised paper](https://github.com/sns-chops/multiphonon/raw/da5a0097012df7679a8fc350f6949c9d095e0a3c/paper/paper.pdf)? The coverage badge were added to [the readme](https://github.com/sns-chops/multiphonon/blob/da5a0097012df7679a8fc350f6949c9d095e0a3c/README.md). Could you please find a reviewer for this paper? Thanks.

**Comment by lheagy** [comment]
Thanks for the updates @yxqd!

**Comment by lheagy** [comment]
👋 Hi @tacaswell and @bjmorgan, would you be willing to review this submission to JOSS?

**Comment by yxqd** [comment]
Thanks @lheagy !

**Comment by lheagy** [comment]
@yxqd: I have sent emails to @tacaswell and @bjmorgan asking if they are willing to review. If we haven't heard back early next week, we can reach out to other reviewers.

**Comment by yxqd** [comment]
May I suggest some other potential reviewers: @khinsen, @betatim, @jochym ?

**Comment by yxqd** [comment]
@lheagy Thanks!

**Comment by bjmorgan** [comment]
@lheagy Happy to review.

**Comment by lheagy** [comment]
Thanks @bjmorgan! 

@tacaswell, @khinsen, @betatim, @jochym: would one of you be willing to be a second reviewer for this submission?

**Comment by yxqd** [comment]
Thank you @bjmorgan @lheagy !

**Comment by yxqd** [comment]
:wave: @lheagy is second reviewer required?

**Comment by lheagy** [comment]
@yxqd, sorry for the delay. It is preferable to have multiple reviewers, and is important here, as I really don't have much background in condensed matter physics. 

I have sent emails to @tacaswell,  @betatim, @jochym (I couldn't find an email for @khinsen). If you know them personally and would also like to send an email, please feel free to point them to this issue. My email is lheagy@eos.ubc.ca if you would like to cc me.

**Comment by jochym** [comment]
@lheagy I'll be willing to review the paper. I do not have much of experience on experimental side but I have a background in phonon calculations - I am a theoretician. This would be my first paper at joss (I already know the http://joss.theoj.org/about#reviewer_guidelines ). What should be the next steps?

**Comment by lheagy** [comment]
Thanks @bjmorgan and @jochym for agreeing to review! I will close this issue and we will start a new issue that includes a checklist for the review. There is only one checklist, so please feel free to communicate back and forth on the issue if there are items to discuss and please don't hesitate to let me know if you have questions

**Comment by lheagy** [comment]
@whedon assign @bjmorgan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bjmorgan

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/440. Feel free to close this issue now!
