### ISSUE TITLE
[PRE REVIEW]: MDEntropy: Information-Theoretic Analyses for Molecular Dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#423]
**Submitting author:** @cxhernandez (<a href="http://orcid.org/0000-0002-8146-5904">Carlos Xavier Hernández</a>)
**Repository:** <a href="https://github.com/msmbuilder/mdentropy/" target ="_blank">https://github.com/msmbuilder/mdentropy/</a>
**Version:** v0.3.0
**Editor:** @arokem
**Reviewer:** @anotherjoshsmith

**Author instructions**

Thanks for submitting your paper to JOSS @cxhernandez. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cxhernandez if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the editor.

**Comment by cxhernandez** [comment]
>@cxhernandez if you have any suggestions for potential reviewers then please mention them here in this thread.

@anotherjoshsmith was very helpful in his review of https://github.com/openjournals/joss-reviews/issues/188

**Comment by anotherjoshsmith** [comment]
@arfon @arokem @cxhernandez I'd be happy to review MDEntropy

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
@whedon assign @anotherjoshsmith as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @anotherjoshsmith

**Comment by arokem** [comment]
Thanks @anotherjoshsmith !

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/427. Feel free to close this issue now!
