### ISSUE TITLE
[REVIEW]: Quail: A Python toolbox for analyzing and plotting free recall data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#424]
**Submitting author:** @andrewheusser (<a href="http://orcid.org/0000-0001-6353-688X">Andrew Heusser</a>)
**Repository:** <a href="https://github.com/ContextLab/quail" target ="_blank">https://github.com/ContextLab/quail</a>
**Version:** v0.1.0
**Editor:** @cMadan
**Reviewer:** @RichardLitt
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1003184" target="_blank">10.5281/zenodo.1003184</a>

## Status

[![status](http://joss.theoj.org/papers/3fb5123eb2538e06f6a25ded0a088b73/status.svg)](http://joss.theoj.org/papers/3fb5123eb2538e06f6a25ded0a088b73)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3fb5123eb2538e06f6a25ded0a088b73"><img src="http://joss.theoj.org/papers/3fb5123eb2538e06f6a25ded0a088b73/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3fb5123eb2538e06f6a25ded0a088b73/status.svg)](http://joss.theoj.org/papers/3fb5123eb2538e06f6a25ded0a088b73)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ContextLab/quail" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@RichardLitt, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ContextLab/quail">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@andrewheusser) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @RichardLitt it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by RichardLitt** [comment]
@arfon You can do a request to https://api.github.com/repos/openjournals/joss-reviews/watchers to see if I am a watcher or not, before posting that message. Might be a good enhancement to @whedon.

**Comment by RichardLitt** [comment]
- [ ] The version does not match. I'm unsure how to suggest a change here - opening an issue in GitHub doesn't make sense. I would suggest, instead, that the given version here by updated to v0.1.3.

**Comment by RichardLitt** [comment]
@cMadan I would consider Quail to be worthy of publication as is within JOSS. All checks passed, all green from my end.

**Comment by RichardLitt** [comment]
Small note: The only thing to change is that the version needs to be updated to v0.1.4. I'm not sure how to do that for JOSS.

**Comment by jeremymanning** [comment]
@RichardLitt we've updated the metadata in the quail repository (and on pip) to reflect the new version (0.1.4).  Let us know if you need us to change anything else on our end, or if this is a JOSS thing.

**Comment by jeremymanning** [comment]
Also, thanks very much for such a thorough review!  An enjoyable experience from our end!

**Comment by RichardLitt** [comment]
Thank you! You've been super responsive. Great work.

**Comment by arfon** [comment]
@andrewheusser - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by andrewheusser** [comment]
Great, thank you!  Here is the DOI I registered with Zenodo

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1003184.svg)](https://doi.org/10.5281/zenodo.1003184)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1003184 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1003184" target="_blank">10.5281/zenodo.1003184</a> is the archive.

**Comment by arfon** [comment]
@RichardLitt - many thanks for your review here and to @cMadan for editing this submission ✨ 

@andrewheusser - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00424 ⚡️ 🚀 💥

**Comment by jeremymanning** [comment]
@arfon Thanks-- we're very excited that our paper has been accepted!  Everything mostly looks great, but I noticed some formatting issues with the references and paper.  I looked through our paper.md and paper.bib files, and I think I see what the problems were:
- In the .bib file, we had separated some of the author names with commas instead of "and."  Also, some of the field names were capitalized instead of lowercase.
- In the .md file, some of the parentheses placements make the formatting strange.

I've corrected these issues in [our repository](https://github.com/ContextLab/quail/tree/master/paper)-- is there any way for us to recompile the PDF to correct the formatting?

**Comment by arfon** [comment]
@jeremymanning - sure thing. I just recompiled the paper. Could you take a look at the new version and see if it's looking better?

**Comment by jeremymanning** [comment]
Hi @arfon -- that fixed some of the issues, but there are still some remaining formatting issues:
- Some misplaced parentheses
- Inconsistently formatted years (e.g. some have parentheses, some don't)
- Inconsistently formatted author names in the reference list, including some missing information

I've attached a marked up PDF with the specific issues.  I'm also happy to attempt to compile the PDF myself and/or generate a properly formatted one if you'd rather.  I could mock something up in LaTeX, or if you point me to the compiler you use, I can attempt to debug this.

[10.21105.joss.00424.pdf](https://github.com/openjournals/joss-reviews/files/1369318/10.21105.joss.00424.pdf)

**Comment by arfon** [comment]
@jeremymanning - [this is the command](https://github.com/openjournals/whedon/blob/d8edf88535db314874199e3ef4cc494e30ccec52/lib/whedon/processor.rb#L155-L164) we use to compile the paper. Can you go from there?

**Comment by jeremymanning** [comment]
Hi @arfon thanks for the pointer!  I've now fixed the remaining formatting issues.  The changes are [on our GitHub repo](https://github.com/ContextLab/quail/tree/master/paper), and I've attached a PDF.

[10.21105.joss.00424.pdf](https://github.com/openjournals/joss-reviews/files/1369829/10.21105.joss.00424.pdf)

**Comment by arfon** [comment]
@jeremymanning - can you take a look at this PDF https://github.com/openjournals/joss-papers/raw/master/joss.00424/10.21105.joss.00424.pdf and see if it looks better?

**Comment by jeremymanning** [comment]
@arfon that looks great-- thanks for your help fixing this!

**Comment by arfon** [comment]
> @arfon that looks great-- thanks for your help fixing this!

NP 😄

**Comment by jeremymanning** [comment]
Ah-- can you re-compile the website too (to match the paper)?  Sorry 😬

**Comment by arfon** [comment]
The site should be updated now...

**Comment by jeremymanning** [comment]
Awesome-- perfect.  Thanks very much 😄
