### ISSUE TITLE
[REVIEW]: BayesianNetwork: Interactive Bayesian Network Modeling and Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#425]
**Submitting author:** @paulgovan (<a href="http://orcid.org/0000-0002-1821-8492">Paul Govan</a>)
**Repository:** <a href="https://github.com/paulgovan/BayesianNetwork" target ="_blank">https://github.com/paulgovan/BayesianNetwork</a>
**Version:** v0.1.3
**Editor:** @katyhuff
**Reviewer:** @rgiordan
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.596010" target="_blank">10.5281/zenodo.596010</a>

## Status

[![status](http://joss.theoj.org/papers/b7f635bc64f1585ea24a0e9ebea2ff21/status.svg)](http://joss.theoj.org/papers/b7f635bc64f1585ea24a0e9ebea2ff21)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b7f635bc64f1585ea24a0e9ebea2ff21"><img src="http://joss.theoj.org/papers/b7f635bc64f1585ea24a0e9ebea2ff21/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b7f635bc64f1585ea24a0e9ebea2ff21/status.svg)](http://joss.theoj.org/papers/b7f635bc64f1585ea24a0e9ebea2ff21)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/paulgovan/BayesianNetwork" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@rgiordan, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/paulgovan/BayesianNetwork">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.3)?
- [x] **Authorship:** Has the submitting author (@paulgovan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @rgiordan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by rgiordan** [comment]
The package is missing automated tests.

https://github.com/paulgovan/BayesianNetwork/issues/6

**Comment by rgiordan** [comment]
@katyhuff 

Sorry, this is the first time I've done this.  Where do I find the software paper?  I don't see it in the repo, nor in any of the issues or emails.

**Comment by katyhuff** [comment]
@rgiordan Thanks for the question. This varies by repository. It looks like the paper for this one is at : https://github.com/paulgovan/BayesianNetwork/blob/master/inst/paper

**Comment by rgiordan** [comment]
https://github.com/paulgovan/BayesianNetwork/issues/7

The author and affiliation are missing from ```paper.md```, and I feel that ```bnlearn``` could be given clearer credit for the underlying learning algorithms.

**Comment by rgiordan** [comment]
https://github.com/paulgovan/BayesianNetwork/issues/8

The paper is missing references.

**Comment by rgiordan** [comment]
I played around with the package, but there are many combinations of options so I didn't evaluate them exhaustively.  As such I'm not 100% sure what the standards are for "Functionality: Have the functional claims of the software been confirmed?"  I'll check it, but maybe @katyhuff can clarity the expectation are?

I would also feel more comfortable if there were unit tests.

**Comment by rgiordan** [comment]
@katyhuff @paulgovan 

This is very nice work!  It's a beautiful and, I imagine, usable interface to a powerful set of learning algorithms.  I think it is well worth publishing.  However, the reviewing standards are quite clear -- it needs automated tests, and if they are in there now, I can't see them.  I'd recommend acceptance as long as good tests can be added.

Is there anything else you need me to fill out or do for the time being?

**Comment by katyhuff** [comment]
Thanks so much, @rgiordan, for your review. Great work! 

The next step is for @paulgovan to look over the comments and issues you've created to make appropriate changes. 

@rgiordan Regarding your question on the confirmation of the functional claims, we expect that the few claims of functionality in paper.md be checked by the reviewer to their satisfaction. This is where domain expertise comes in. For some packages and some reviewers, this means running an example, checking that a plot is as expected, or reviewing the test coverage. Indeed, as you point out @rgiordan, it is usually made much easier with unit tests and examples, so that's why we require unit tests.

**Comment by paulgovan** [comment]
@rgiordan, @katyhuff

Please reference [#6](https://github.com/paulgovan/BayesianNetwork/issues/6), [#7](https://github.com/paulgovan/BayesianNetwork/issues/7), and [#8](https://github.com/paulgovan/BayesianNetwork/issues/8). Working on unit tests, but this could take several days.

Thank you for the thorough review!

**Comment by paulgovan** [comment]
@rgiordan, @katyhuff

Please see my changes referenced in the issues above. Let me know if you have any questions.

**Comment by paulgovan** [comment]
@rgiordan, @katyhuff

Just checking to see if you have had a chance to review my changes. Let me know if you have any additional comments.

**Comment by katyhuff** [comment]
Ah!! Sorry, I was so confused -- the issues are still open! If they have been fixed, it's appropriate to close them (only you can.. we don't own this repository). I'm looking now to ensure that I can run the tests.

**Comment by katyhuff** [comment]
- [ ] The issue with the paper references hasn't been fixed. Much like an ordinary paper, you must actually cite things in the text in order for them to appear in the references.
- [ ] I strongly recommend a caption for the figure in your paper.
- [ ] It's not clear that your unit tests are robustly testing the method itself. 
- [ ] We require either automated tests (e.g. with travis) or instructions on how to run the tests ( in the readme, for future users, not just for us). Your travis instance currently doesn't run your new shiny tests. I recommend adding those commands to your travis.yml file. Once that's done, travis will automatically run your tests. If you'd rather not, then please at least include instructions in the readme on how a user can run your tests.

**Comment by paulgovan** [comment]
@rgiordan, @katyhuff

I believe that issues [#6](https://github.com/paulgovan/BayesianNetwork/issues/6), [#7](https://github.com/paulgovan/BayesianNetwork/issues/7), and [#8](https://github.com/paulgovan/BayesianNetwork/issues/8) have been fixed, and they are now closed.

**Comment by paulgovan** [comment]
@katyhuff, just circling back to this. Any update?

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00425/joss.00425/10.21105.joss.00425.pdf
```

**Comment by katyhuff** [comment]
@paulgovan This looks good to me! I believe it can be accepted! At this point could you make an updated archive of the reviewed version of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by paulgovan** [comment]
Thanks @katyhuff! Here is the new DOI: [![DOI](https://zenodo.org/badge/42831223.svg)](https://zenodo.org/badge/latestdoi/42831223)

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.596010 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.596010" target="_blank">10.5281/zenodo.596010</a> is the archive.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00425/joss.00425/10.21105.joss.00425.pdf
```

**Comment by katyhuff** [comment]
@arfon we're ready to accept this!

**Comment by arfon** [comment]
@rgiordan - many thanks for your review here and to @katyhuff for editing this submission ✨ 

@paulgovan - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00425 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00425/status.svg)](https://doi.org/10.21105/joss.00425)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00425/status.svg)](https://doi.org/10.21105/joss.00425)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
