### ISSUE TITLE
[PRE REVIEW]: PySwarms: a research toolkit for Particle Swarm Optimization in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#428]
**Submitting author:** @ljvmiranda921 (<a href="http://orcid.org/0000-0002-7872-6464">Lester James Miranda</a>)
**Repository:** <a href="https://github.com/ljvmiranda921/pyswarms" target ="_blank">https://github.com/ljvmiranda921/pyswarms</a>
**Version:** v0.1.7
**Editor:** @kyleniemeyer
**Reviewer:** @stsievert

**Author instructions**

Thanks for submitting your paper to JOSS @ljvmiranda921. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ljvmiranda921 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @kyleniemeyer - the submitting author suggested you as an editor.

**Comment by kyleniemeyer** [comment]
@arfon OK, got it. 

@ljvmiranda921 I will work on identifying appropriate reviewer(s); any suggestions you have for people with domain knowledge are also appreciated.

**Comment by ljvmiranda921** [comment]
Hi @kyleniemeyer , thank you for taking the time to oversee the review of this submission. 

I checked the [list of reviewers for JOSS](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv), then looked for keywords such as "optimization" and "python". I think that @stsievert and @oesteban may be suitable to review this if they have the time.

Thank you so much!

**Comment by oesteban** [comment]
@kyleniemeyer @ljvmiranda921 
I'd love reviewing this submission, but I'm pretty swamped right now. I could commit to get the review done in 3/4 weeks from now.

**Comment by stsievert** [comment]
Ditto. Give me another two weeks.

@ljvmiranda921 [hyperopt] and the [accompanying paper] might be of interest for the hyper-parameter optimization. Also, [dask-searchcv] might be of interest.

[hyperopt]:https://github.com/hyperopt/hyperopt
[accompanying paper]:https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf
[dask-searchcv]:https://github.com/dask/dask-searchcv

**Comment by ljvmiranda921** [comment]
Sure, thanks for accepting to review @oesteban , @stsievert . I'd be waiting for your review at the time you've mentioned.

Okay, in the meantime I will check on the hyperparameter optimization libraries stsievert mentioned. It may be useful to add an adapter to one of those libraries in pyswarms.

Thanks a lot!

cc: @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @stsievert and @oesteban, thanks for agreeing to review! (Hopefully that's what you meant with those messages 😄). I'll get the actual review issue started, with @stsievert set as the "main" reviewer since he expects to get to it a bit sooner—but both of you can add comments. (JOSS currently only supports one official reviewer, though we hope to fix that soon.)

@ljvmiranda921 I appreciate your effort finding reviewers, but I will shepherd the review... less appropriate for the submitting author to do so 😆

**Comment by kyleniemeyer** [comment]
@whedon assign @stsievert as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stsievert

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/433. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
@stsievert @oesteban we'll hold the actual review over in #433

**Comment by ljvmiranda921** [comment]
Oops, sorry @kyleniemeyer 😓

**Comment by kyleniemeyer** [comment]
@ljvmiranda921 no worries!

**Comment by stsievert** [comment]
> Hopefully that's what you meant with those messages

Yup, that's what I meant (but can't get to it right away).

> (JOSS currently only supports one official reviewer, though we hope to fix that soon.)

I also ran into this in #382. Hopefully it's fixed soon!
