### ISSUE TITLE
[PRE REVIEW]: Parallel and Adaptive High-Dimensional Numerical Integration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#429]
**Submitting author:** @iljah (<a href="http://orcid.org/0000-0002-9542-5866">Ilja Honkonen</a>)
**Repository:** <a href="https://github.com/iljah/hdintegrator" target ="_blank">https://github.com/iljah/hdintegrator</a>
**Version:** 0.1
**Editor:** @danielskatz
**Reviewer:** @marksantcroos

**Author instructions**

Thanks for submitting your paper to JOSS @iljah. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@iljah if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @danielskatz - the submitting author suggested you as the editor.

**Comment by danielskatz** [comment]
Ok @arfon, will do.

**Comment by danielskatz** [comment]
@iljah - do you have any suggested reviewers?

**Comment by iljah** [comment]
The following usernames seem to have suitable language combinations and areas of expertise in reviewers.csv: jochym, khinsen, betatim, kyleniemeyer, dvalters, arghdos, jochym, marksantcroos.

**Comment by iljah** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by danielskatz** [comment]
@jochym, @khinsen, @betatim, @kyleniemeyer, @dvalters, @arghdos, @jochym, @marksantcroos -- would any of you be willing to review this submission?

**Comment by marksantcroos** [comment]
@danielskatz I was offline for a week. Will do an assessment whether I'm qualified for review today or tomorrow.

**Comment by marksantcroos** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @marksantcroos, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by marksantcroos** [comment]
@danielskatz I can take the review.

**Comment by danielskatz** [comment]
Thanks @marksantcroos

**Comment by danielskatz** [comment]
@whedon assign @marksantcroos as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @marksantcroos

**Comment by danielskatz** [comment]
@whendon start review magic-word=bananas

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/437. Feel free to close this issue now!
