### ISSUE TITLE
[REVIEW]: micompm - A MATLAB/Octave toolbox for multivariate independent comparison of observations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#430]
**Submitting author:** @fakenmc (<a href="http://orcid.org/0000-0002-8487-5837">Nuno Fachada</a>)
**Repository:** <a href="https://github.com/fakenmc/micompm" target ="_blank">https://github.com/fakenmc/micompm</a>
**Version:** v1.0.0
**Editor:** @cMadan
**Reviewer:** @jordigh
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.931838" target="_blank">10.5281/zenodo.931838</a>

## Status

[![status](http://joss.theoj.org/papers/6901c663f02916e5a80dad9a8bbda537/status.svg)](http://joss.theoj.org/papers/6901c663f02916e5a80dad9a8bbda537)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6901c663f02916e5a80dad9a8bbda537"><img src="http://joss.theoj.org/papers/6901c663f02916e5a80dad9a8bbda537/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6901c663f02916e5a80dad9a8bbda537/status.svg)](http://joss.theoj.org/papers/6901c663f02916e5a80dad9a8bbda537)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fakenmc/micompm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@jordigh, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fakenmc/micompm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@fakenmc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jordigh it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@jordigh, let me know if you have any questions regarding the review process!

**Comment by jordigh** [comment]
Coming along, should be finished this week.

**Comment by cMadan** [comment]
@jordigh, how is the review going?

**Comment by cMadan** [comment]
@jordigh, are you still able to review this submission?

**Comment by jordigh** [comment]
Slipped my mind. Will finish this tonight.

**Comment by jordigh** [comment]
Okay, I worked through the tutorial. I think I can tick off all the checkboxes except for the following:

* I don't see a clear indication of how to seek support or report issues. I assume you expect to use github issues, but I don't see this stated anywhere.
* I don't see who the intended audience is. There is more statistics here than I am personally comfortable with. I was running a bit blind here. It looks like a fairly sophisticated statistical audience is intended.

I worked with Octave. I noticed some slightly different outputs for some of the tutorial examples, including some NaNs instead of some very small numbers. I don't know where the rounding errors came from.

I was unable to generate the LaTeX output as shown there. For some reason, none of the tickmarks by tikz would show up, although I could see the axes. It would help to have a complete source code of the intended LaTeX file to compile.

**Comment by fakenmc** [comment]
Thanks, I'll address these issues shortly.

**Comment by fakenmc** [comment]
I've worked through the raised points as follows:

* Added support and issue reporting information to the Contributing guidelines.
* Clarified who's the intended audience in README.md, User Guide and the submitted paper.
* Added a template LaTeX document for quick testing table generation; also added a reference to this template in the tutorial.

Concerning the small differences between MATLAB and Octave results. As described in the User Guide, Octave uses a different way (when compared to MATLAB) of determining the statistics on some of the performed statistical tests. The outputs in the tutorial are from MATLAB, thus the stated differences. I've performed a large number of tests to determine if these MATLAB vs Octave differences are meaningful, but the p-values were consistently similar. I have also validated these conclusions with R. Thus one will get to the same conclusion (on sample similarity or otherwise) using either software.

I believe to have addressed the raised points. If there is anything else I can do please let me know.

**Comment by cMadan** [comment]
@jordigh, can you take a look at the revised repository and see if you think it has been suitably improved? Thanks!

**Comment by cMadan** [comment]
@jordigh, are you able to finish reviewing this project? Thanks!

**Comment by jordigh** [comment]
Looks good now. It's ready.

**Comment by fakenmc** [comment]
Thank you for the review!

**Comment by arfon** [comment]
@cMadan - are we good to accept here?

**Comment by cMadan** [comment]
@jordigh, thank you for reviewing this submission!

@fakenmc and @arfon, I think we're all set! I just need the DOI for an archival version of your code (i.e., upload the current code to Zenodo or figshare).

**Comment by fakenmc** [comment]
@cMadan , the DOI for the latest version of micompm is 10.5281/zenodo.931838 .

Thanks in advance

**Comment by cMadan** [comment]
@whedon set archive as 10.5281/zenodo.931838

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.931838 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.931838" target="_blank">10.5281/zenodo.931838</a> is the archive.

**Comment by arfon** [comment]
@jordigh - many thanks for your review here and to @cMadan for editing this submission ✨ 

@fakenmc - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00430 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00430/status.svg)](https://doi.org/10.21105/joss.00430)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00430/status.svg)](https://doi.org/10.21105/joss.00430)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
