### ISSUE TITLE
[REVIEW]: Simulated Physics and Environment for Autonomous Risk Studies (SPEARS)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#434]
**Submitting author:** @zmimlitz (<a href="http://orcid.org/0000-0001-5431-8362">Zac Mimlitz</a>)
**Repository:** <a href="https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/" target ="_blank">https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/</a>
**Version:** 3.0.5
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @agrignard
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/c2b0579a0582ec24416335d2c9668641/status.svg)](http://joss.theoj.org/papers/c2b0579a0582ec24416335d2c9668641)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c2b0579a0582ec24416335d2c9668641"><img src="http://joss.theoj.org/papers/c2b0579a0582ec24416335d2c9668641/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c2b0579a0582ec24416335d2c9668641/status.svg)](http://joss.theoj.org/papers/c2b0579a0582ec24416335d2c9668641)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@agrignard, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (3.0.5)?
- [ ] **Authorship:** Has the submitting author (@zmimlitz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @agrignard it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @agrignard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @agrignard

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @agrignard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @agrignard

**Comment by Kevin-Mattheus-Moerman** [comment]
Sorry for flooding this issue with editorial stuff. We are having some issues assigning the reviewer as he reported he could not tick the checkboxes at the top of this issue.

**Comment by Kevin-Mattheus-Moerman** [comment]
@agrignard are you able to tick the boxes now?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon can you see what is wrong here? I am able to tick the boxes but the reviewer appears not to.

**Comment by agrignard** [comment]
Ok it's working now

**Comment by Kevin-Mattheus-Moerman** [comment]
Fantabulous! :tada: let the awesome open peer review process begin! Thanks again for agreeing to review. Let us know about your experience as a reviewer too.

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @agrignard how are you getting on? Let me know if you need any help.

**Comment by agrignard** [comment]
Actually yes, I was not able to run the software following the github instruction, i created an issue but I am still waiting for there answer 

https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/issues/35

So I am kind of stuck in the review process, what should I do ?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @agrignard. The ball is in the authors court. 
@zmimlitz can you please respond to the issue raised by the reviewer?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00434/10.21105.joss.00434.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@zmimlitz can you respond to the reviewer's comment?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon can we e-mail the submitting authors of this submission? They have not responded in a very long time.

**Comment by arfon** [comment]
> @arfon can we e-mail the submitting authors of this submission? They have not responded in a very long time.

Done. I copied you @Kevin-Mattheus-Moerman

**Comment by agrignard** [comment]
I am bit lost in this first attempt to do a review... What should I do do we agree that no news has been provide by the author?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @agrignard I've email the authors a second time. Apologies for the delay in this review process. We greatly appreciate your patience.

**Comment by Kevin-Mattheus-Moerman** [comment]
@zmimlitz this is a final reminder to please address the reviewers comments. 

@arfon can you e-mail the authors a final reminder? If this review issue remains stale I suggest we retract this submission.

**Comment by arfon** [comment]
> @arfon can you e-mail the authors a final reminder? If this review issue remains stale I suggest we retract this submission.

Done (and agreed).

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon unfortunately I think we have to retract this submission

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon unfortunately I think we have to retract this submission

**Comment by arfon** [comment]
> @arfon unfortunately I think we have to retract this submission

Agreed.

**Comment by arfon** [comment]
@agrignard & @Kevin-Mattheus-Moerman - thanks for your help here. Sorry it didn't work out :-(

**Comment by douglasvb** [comment]
Just saw these comments a year too late.  For whatever reason, I never was notified.  Is there interest from JOSS to have us fix the error and re-open the review?

**Comment by Kevin-Mattheus-Moerman** [comment]
I believe we should be able to reopen the review process, provided this time you can commit to keeping track of this issue and to responding to reviewers in a timely manor. @arfon can you confirm?

**Comment by douglasvb** [comment]
@Kevin-Mattheus-Moerman I'm checking with @zmimlitz to see about getting the code fixed.  Perhaps it would be appropriate for us to fix the issue first before we have you reopen the review.

I believe the issue was the instructions for compiling the code wasn't working?  Was there anything else that we should address?

**Comment by arfon** [comment]
> I believe the issue was the instructions for compiling the code wasn't working? Was there anything else that we should address?

There could potentially be much more work to do here as @agrignard looks to have only just started their review.

@Kevin-Mattheus-Moerman - we can reopen this issue yes, but I think we should get a 👍 from @agrignard that they are still willing to review this submission. If not, @douglasvb I think you need to resubmit.

**Comment by douglasvb** [comment]
If you're willing to bear with us a little, I think we should be able to respond to issues as they come up in the review process.  I'm working the installation instructions issue now.

Again, apologies that we dropped the ball on the initial review.
