### ISSUE TITLE
[PRE REVIEW]: Masks2Metrics (M2M): A Matlab Toolbox for Gold Standard Morphometrics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#435]
**Submitting author:** @smikhael (<a href="http://orcid.org/0000-0002-2490-9548">Shadia Mikhael</a>)
**Repository:** <a href="https://github.com/Edinburgh-Imaging/Masks2Metrics" target ="_blank">https://github.com/Edinburgh-Imaging/Masks2Metrics</a>
**Version:** v1.0
**Editor:** @cMadan
**Reviewer:** @Kevin-Mattheus-Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @smikhael. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@smikhael if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋🏻 @cMadan. The submitting author suggested you as an editor.

**Comment by cMadan** [comment]
@smikhael, this looks like a great submission! Do you have any suggestions on who would be a suitable reviewer?

**Comment by smikhael** [comment]
Thank you @cMadan! I would suggest either @sealhuang or @arokem as a suitable reviewer. I look forward to everyone's feedback.

**Comment by Kevin-Mattheus-Moerman** [comment]
I can help review this too. :hand:

**Comment by smikhael** [comment]
@Kevin-Mattheus-Moerman , I am happy with that if you are available to assist. Thank you.

**Comment by cMadan** [comment]
Great! Let's go with @Kevin-Mattheus-Moerman then :)

**Comment by cMadan** [comment]
@whedon assign @Kevin-Mattheus-Moerman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Kevin-Mattheus-Moerman

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/436. Feel free to close this issue now!
