### ISSUE TITLE
[PRE REVIEW]: FullSWOF: Full Shallow-Water equations for Overland Flow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#438]
**Submitting author:** @ (<a href="http://orcid.org/0000-0003-1700-4553">Carine Lucas</a>)
**Repository:** <a href="http://www.univ-orleans.fr/mapmo/soft/FullSWOF/" target ="_blank">http://www.univ-orleans.fr/mapmo/soft/FullSWOF/</a>
**Version:** v1.07.00
**Editor:** @kyleniemeyer
**Reviewer:** @wkearn

**Author instructions**

Thanks for submitting your paper to JOSS @. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @kyleniemeyer - the submitting author suggested you as the editor.

**Comment by wkearn** [comment]
@kyleniemeyer I'd be happy to review this submission.

**Comment by kyleniemeyer** [comment]
@wkearn Excellent! Thanks for volunteering

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
@whedon assign @wkearn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wkearn

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/448. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
@wkearn we'll do the actual review over in #448, please take a look at the [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines)
