### ISSUE TITLE
[PRE REVIEW]: mpnum: A matrix product representation library for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#439]
**Submitting author:** @dseuss (<a href="http://orcid.org/0000-0002-6354-457X">Daniel Suess</a>)
**Repository:** <a href="https://github.com/dseuss/mpnum" target ="_blank">https://github.com/dseuss/mpnum</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @SylvainCorlay

**Author instructions**

Thanks for submitting your paper to JOSS @dseuss. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dseuss if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @labarba - the submitting author suggested you as the editor.

**Comment by dseuss** [comment]
Thanks for getting this started. I would suggest @nicoguaro, @khinsen, or @jochym for potentially reviewing this submission.

**Comment by labarba** [comment]
@whedon assign @SylvainCorlay as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @SylvainCorlay

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/465. Feel free to close this issue now!
