### ISSUE TITLE
[PRE REVIEW]: DynamicalBilliards.jl : An easy-to-use, modular and extendable Julia package for Dynamical Billiard systems in two dimensions.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#442]
**Submitting author:** @Datseris (<a href="http://orcid.org/0000-0002-6427-2385">George Datserus</a>)
**Repository:** <a href="https://github.com/JuliaDynamics/DynamicalBilliards.jl" target ="_blank">https://github.com/JuliaDynamics/DynamicalBilliards.jl</a>
**Version:** v1.6.1
**Editor:** @kyleniemeyer
**Reviewer:** @ahwillia

**Author instructions**

Thanks for submitting your paper to JOSS @Datseris. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Datseris if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Datseris** [comment]
@whedon commmands

**Comment by Datseris** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Datseris** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://bit.ly/joss-reviewers

**Comment by Datseris** [comment]
@whedon assign @ChrisRackauckas as reviewer

**Comment by whedon** [comment]
I'm sorry @Datseris, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by Datseris** [comment]
Cool. So now I guess I just wait.

**Comment by kyleniemeyer** [comment]
I will handle this submission.

@whedon assign @kyleniemeyer as editor

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by Datseris** [comment]
Hello, thanks for finally getting into this, I appreciate it.

The following seem to have relation to the Physics area I am interested in: 

mlxd
jarvist
ahwillia


but still the connection is not that big... I hope it will be okay.

P.S.: Could you tell me how I can also apply to become a reviewer? I searched the website but I could not find where the application is. Do I just put my name in the google spreadsheet?

**Comment by Datseris** [comment]
Should I tag these persons? I am not sure how things work here, sorry.

**Comment by kyleniemeyer** [comment]
Hi @Datseris, I can take care of that—aside from the existing JOSS reviewers, is there anyone closer to your domain who you might recommend? (It's ok if not)

As for adding your name to the reviewer list, you can use this link: http://joss.theoj.org/reviewer-signup.html

**Comment by ChrisRackauckas** [comment]
@ahwillia would be a good fit.

**Comment by kyleniemeyer** [comment]
@ChrisRackauckas thanks!

Hello @ahwillia @mlxd @jarvist @ahwillia, would you be willing to review this submission for JOSS? (I prefer to have at least two reviewers, but more are also welcome if you are interested!) Thanks!

**Comment by Datseris** [comment]
@kyleniemeyer unfortunately all the people that I can recommend have discussed with me the code in some way or another, therefore the conflict of interests would not go away...

**Comment by kyleniemeyer** [comment]
@Datseris that's all right, let's see if we can find someone else first. Having a discussion would not be a COI, just actually contributing to the code.

**Comment by ahwillia** [comment]
I'd be happy to review this.

**Comment by kyleniemeyer** [comment]
@ahwillia thanks! I'll wait a bit longer to see if any of the others tagged are also willing to review, for a second opinion.

**Comment by mlxd** [comment]
Also happy to review this.

**Comment by kyleniemeyer** [comment]
Excellent!

**Comment by whedon** [comment]
OK, the reviewer is @ahwillia

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by Datseris** [comment]
hahahahaha

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/458. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
Alright, @Datseris @ahwillia @mlxd we'll move over to #458 for the actual review. 

Currently our infrastructure only "officially" supports one reviewer, so @ahwillia will be able to edit the checkboxes, but @mlxd please comment in the thread if you disagree with anything (along with your regular comments).
