### ISSUE TITLE
[PRE REVIEW]: Missingno: a missing data visualization suite

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#443]
**Submitting author:** @ResidentMario (<a href="http://orcid.org/0000-0002-0066-5825">Aleksey Bilogur</a>)
**Repository:** <a href="https://github.com/ResidentMario/missingno" target ="_blank">https://github.com/ResidentMario/missingno</a>
**Version:** 0.3.7
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @rhiever

**Author instructions**

Thanks for submitting your paper to JOSS @ResidentMario. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ResidentMario if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #443 with the following error: 

 pandoc-citeproc: Could not find paper.bib
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Pandoc.hs:224:39 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Pandoc
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon if there are no references, do we need an empty paper.bib file?

**Comment by Kevin-Mattheus-Moerman** [comment]
@pzwang @rhiever @tacaswell @wesm @jreback @bryevdv is this [JOSS](http://joss.theoj.org/) submission your cup of tea? Would you be willing to review this?

**Comment by arfon** [comment]
> @arfon if there are no references, do we need an empty paper.bib file?

I guess not but in this case the `paper.md` file should not be pointing to a `paper.bib` file that doesn't exist. IMO the current paper is rather too brief and lacking context. I'd encourage the author to flesh this out (and perhaps cite related work/packages?)

**Comment by wesm** [comment]
I don't have the bandwidth to help unfortunately

**Comment by ResidentMario** [comment]
I'm happy to edit the write-up for content, I wasn't too sure how much is enough or too much. In terms of citations, there's an R package that was inspired by this Python package [here](https://www.rdocumentation.org/packages/poppr/versions/2.5.0/topics/missingno), as well as [this blog post](http://www.residentmar.io/2016/06/12/null-and-missing-data-python.html) describing the issue the package tackles more generally. Hopefully that can cover references.

**Comment by rhiever** [comment]
Same as @wesm - bad time of the year for me. If you still need a review in mid-January, please feel free to ping me again.

**Comment by bryevdv** [comment]
Sorry, I am in the middle of a selling a house and moving across the country, I am too swamped. Additionally I don't feel especially qualified to comment on MPL related things.

**Comment by arfon** [comment]
👋 @rhiever - we're still looking for a reviewer for this submission. Any chance we could take you up on [your offer](https://github.com/openjournals/joss-reviews/issues/443#issuecomment-345787713) 😁

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@zkamvar would you be interested in reviewing this submission for JOSS?

**Comment by rhiever** [comment]
What type of review is needed - code review? Functionality review? I don't see a full paper attached to this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@rhiever thanks for your reply. We are currently in a pre-review issue. If you agree to review I'll open a review issue and you'll be able to see the paper as well (the author here still needs to update their paper). 

Here is an example of a [review issue](https://github.com/openjournals/joss-reviews/issues/500#event-1442337848) with 3 reviewers taking part. Essentially reviewers tick boxes at the top of the review issue. From the tickboxes you can see most of the review focuses on the software functionality and documentation.  

Papers are typically very short (e.g. see [the paper](https://github.com/openjournals/joss-papers/blob/joss.00500/joss.00500/10.21105.joss.00500.pdf) submitted to the review issue I linked to). 

You can also read more about our [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines).

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario please expand [your paper](
https://github.com/ResidentMario/missingno/blob/master/paper.md) as per [our guidelines](http://joss.theoj.org/about#author_guidelines). You can also check out [some accepted papers](http://joss.theoj.org/papers/accepted) to get a better picture of the content and level of detail presented in them.

**Comment by rhiever** [comment]
OK, I can act as a reviewer on this paper.

**Comment by ResidentMario** [comment]
@Kevin-Mattheus-Moerman :+1: To review, I've gotten a smattering inquiries on how to cite this library, and this seemed like the perfect venue to achieve that. I made a pretty minimal submission to test the waters. V. happy to flush it out more.

**Comment by zkamvar** [comment]
Hello! Yes, I would be happy to review this. 

Caveats: 

1. I am primarily an R developer and use python on more of a monthly basis.
2. I am the author of the R package that @ResidentMario mentioned in [this comment](https://github.com/openjournals/joss-reviews/issues/443#issuecomment-345762333) (Though I don't see a citation necessary as the name was derived from [a pokemon glitch](https://en.wikipedia.org/wiki/MissingNo.)).

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. Two reviewers is perfect. I'll open the review issue with @rhiever as first reviewer. I'll then also add @zkamvar as second reviewer. Here we go.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @rhiever as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rhiever

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/547. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
Okay review has started over at #547.
