### ISSUE TITLE
[PRE REVIEW]: PolaronMobility.jl: Implementation of the Feynman variational polaron model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#444]
**Submitting author:** @jarvist (<a href="http://orcid.org/0000-0003-1938-4430">Jarvist Moore Frost</a>)
**Repository:** <a href="https://github.com/jarvist/PolaronMobility.jl" target ="_blank">https://github.com/jarvist/PolaronMobility.jl</a>
**Version:** ArXiv-v4
**Editor:** @lheagy
**Reviewer:** @yxqd

**Author instructions**

Thanks for submitting your paper to JOSS @jarvist. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jarvist if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by jarvist** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by jarvist** [comment]
From your list of available reviewers:
@jochym and @khinsen both have more than sufficient electronic structure background to understand where these codes are coming from, but do not list any Julia experience. The codes aren't that complex, or use that specific language features (metaprogramming etc.), but it might be nice to have some expertise & feedback from scientific Julia users, in how to (re)structure the package. 

@bjmorgan also has the scientific background -- but I know him & we're both employees at the University of Bath!

Of the reviewers who indicate Julia familiarity, perhaps @lheagy is the closest in scientific overlap.

**Comment by arfon** [comment]
@lheagy - would you be willing to edit this submission for JOSS?

**Comment by lheagy** [comment]
@arfon, @jarvist: this is outside of my background, but I am happy to help.

**Comment by arfon** [comment]
@lheagy - many thanks. Perhaps we could try and find two reviewers here?

**Comment by arfon** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by lheagy** [comment]
@jarvist: I have looked through the paper and briefly through your software. I have a couple suggestions before we send it out for review.

## Paper
- [ ] the paper is quite technical, do you have a couple examples or applications you could discuss briefly in order to reach a wider audience?
- [ ] you can remove the "Spiel from original website below"
- [ ] citations should be in square brackets (eg. 
```
This package is an implementation in the Julia programming language of solving
the Feynman [@Feynman1955]
``` 

## Software
- [ ] it looks like the testing and code coverage are not currently set up (the badge links at the top of the Readme are all unknown: https://github.com/jarvist/PolaronMobility.jl/blob/master/README.md)

**Comment by jarvist** [comment]
Thanks for the feedback! I'll try and get those edits done today or tomorrow, before it's sent out.

**Comment by lheagy** [comment]
Hi @jarvist: just checking in. Please ping when you are happy with your edits

**Comment by jarvist** [comment]
Thanks for the timely reminder :^)

Had to have a read about before getting CI working. 

I hope I've made the text a little bit more approachable.

**Comment by lheagy** [comment]
Thanks @jarvist: I had a look and the paper and it doesn't look like the most recent changes have made it to your master branch (the last update was October). Is it on a branch somewhere? Thanks! 

![image](https://user-images.githubusercontent.com/6361812/34442023-9cf1336e-ec7c-11e7-865e-0c9066e02f96.png)

**Comment by jarvist** [comment]
My apologies! I had managed to confuse myself + ended up tidying the README instead of the JOOS paper. 
I've applied edits as suggested & tried to write a more lay-person introduction.

https://github.com/jarvist/PolaronMobility.jl/commit/215cc55d63ad233e79f7c8cba79835ff0fad754d

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #444 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     70      0 --:--:-- --:--:-- --:--:--    70
Error reading bibliography ./paper.bib (line 9, column 25):
unexpected "}"
expecting white space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by lheagy** [comment]
Thanks @jarvist, the text looks good. There is an issue with the bibliography when trying to generate the pdf - do you need the citation on line 9 at the moment? It doesn't look like you reference it, so we could potentially remove it for now? 

How are things going with getting the testing up and running?

**Comment by jarvist** [comment]
Ok, I've removed the blank reference.

Travis CI is setup, but the builds sometimes fail due to reasons outside my control - often that Travis fails to get a fresh copy of Julia!

I'll see if I can restrict the architectures it tries on;
https://travis-ci.org/jarvist/PolaronMobility.jl/jobs/325561158

**Comment by lheagy** [comment]
As this submission is outside my domain, I would like to find 2 reviewers.

@tacaswell, @khinsen, @betatim, @jochym - would any of you be willing to review this submission for JOSS? You can read more about the process here http://joss.theoj.org/about#reviewer_guidelines, and feel free to ping with questions!

**Comment by lheagy** [comment]
👋 Hi @tacaswell, @khinsen, @betatim, @jochym - would any of you be willing to review this submission for JOSS?

**Comment by lheagy** [comment]
@jarvist: just a quick update for you, I have sent out emails to potential reviewers and am waiting to hear back. I will keep you posted.

**Comment by lheagy** [comment]
Hi @dean0x7d, @ajgpitch, would you be willing to review this submission on PolaronMobility.jl  for [JOSS](Joss.theoj.org/about)? JOSS is a 'developer friendly' journal. That is, we focus on the software as a scientific contribution. If the submitting authors have followed best practices (have documentation, tests, continuous integration, and a license) then their review should be straight-forward. There are more details on reviewing with JOSS here: http://joss.theoj.org/about#reviewer_guidelines 

With your background in solid state physics, I would greatly appreciate your input!

**Comment by lheagy** [comment]
:wave: Hi, @yxqd, would you be willing to review this submission?

**Comment by yxqd** [comment]
@lheagy Yes I can help

**Comment by lheagy** [comment]
Thanks @yxqd, as this is outside of my domain of expertise, I would like to find one more reviewer. I am still waiting to hear back from @tacaswell, @betatim and @dean0x7d to see if they are willing (I sent emails as well)

**Comment by lheagy** [comment]
ok, well lets get started on the review with @yxqd as lead and we can see if someone else is willing to help out once things are in motion

**Comment by lheagy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by lheagy** [comment]
@whedon assign @yxqd as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @yxqd

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/566. Feel free to close this issue now!
