### ISSUE TITLE
[REVIEW]: CytobankAPIstats: Computes Signaling and Population Statistics for Cytometry Data on Cytobank using 'CytobankAPI'

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#445]
**Submitting author:** @athrom (<a href="http://orcid.org/0000-0001-6689-7904">Allison Throm</a>)
**Repository:** <a href="https://github.com/athrom/CytobankAPIstats" target ="_blank">https://github.com/athrom/CytobankAPIstats</a>
**Version:** v1.0
**Editor:** @pjotrp
**Reviewer:** @nelkibs
**Archive:** <a href="https://doi.org/10.5281/zenodo.2583300" target="_blank">10.5281/zenodo.2583300</a>

## Status

[![status](http://joss.theoj.org/papers/0f9584c0716270ac91c9384d483dc342/status.svg)](http://joss.theoj.org/papers/0f9584c0716270ac91c9384d483dc342)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0f9584c0716270ac91c9384d483dc342"><img src="http://joss.theoj.org/papers/0f9584c0716270ac91c9384d483dc342/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0f9584c0716270ac91c9384d483dc342/status.svg)](http://joss.theoj.org/papers/0f9584c0716270ac91c9384d483dc342)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/athrom/CytobankAPIstats" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@nelkibs, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @biorelated know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/athrom/CytobankAPIstats">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@athrom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @nelkibs it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by biorelated** [comment]
@nelkibs just a quick ping on the status of this review?

**Comment by arfon** [comment]
:wave: @nelkibs are you still able to review this submission for us?

**Comment by arfon** [comment]
@biorelated - I think we might need to find a new reviewer...

**Comment by arfon** [comment]
@biorelated - could you start looking for a new reviewer for this submission please?

**Comment by nelkibs** [comment]
@biorelated and @arfon Sorry for the very slow response. I have been off radar for a while. The checkbox button are inactive on my end? Is there a setting I need to change?

**Comment by arfon** [comment]
@nelkibs - you should have permissions to edit the checklist - GitHub requires a pretty modern browser - which are you using?

**Comment by arfon** [comment]
@nelkibs - how are you getting along here?

**Comment by biorelated** [comment]
@nelkibs raised some issues in regard to this submission.  @athrom as not commented on the issues.
@athrom could kindly comment on these issues?

**Comment by athrom** [comment]
I have addressed the issues raised by adding LICENSE and INSTALLATION INSTRUCTIONS documents to github.

**Comment by arfon** [comment]
:wave: @nelkibs - please take another look at this submission when you get a chance.

**Comment by arfon** [comment]
:wave: @nelkibs - could you please take another look at this submission?

**Comment by arfon** [comment]
@george-githinji - could you please chase @nelkibs? This review is currently stuck.

**Comment by arfon** [comment]
@pjotrp or @mgymrek - would either of you be able to take over as the editor here?

**Comment by pjotrp** [comment]
I am pinging @nelkibs and @george-githinji

**Comment by arfon** [comment]
Thanks @nelkibs. 

> You can however add a little more information on community guidelines (e.g how a user can seek help or extend the package etc).

@athrom - do you think you could do this ☝️

**Comment by athrom** [comment]
Hi @nelkibs @arfon 
I added the followinglines to the README file:

> For help using the package, please see the CRAN repository documentation: https://cran.r-project.org/web/packages/CytobankAPIstats/CytobankAPIstats.pdf.
> 
> If interested in extending the package, please cite the original CRAN package: https://cran.r-project.org/web/packages/CytobankAPIstats/index.html

Please let me know if there is anything else I need to address/add to this declaration.

**Comment by george-githinji** [comment]
Hi @nelkibs please confirm if this is satisfactory.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by pjotrp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #445 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: tags (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by pjotrp** [comment]
@athrom - sorry for the lengthy process. I am here to help now. Your publication is almost ready. Can you fix the PDF (regenerate with above command). Also to finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI (if one exists).

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here with the DOI for the release.

**Comment by pjotrp** [comment]
@athrom you need to do the final steps. It takes 10 minutes. If we hear nothing we'll close without publishing.

**Comment by athrom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #445 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Allison Throm, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by athrom** [comment]
@pjotrp I saw your email and plan to finish submission steps this evening.

**Comment by athrom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00445/joss.00445/10.21105.joss.00445.pdf)

**Comment by athrom** [comment]
@pjotrp 
The above steps have been completed. The Zenodo assigned DOI is: 10.5281/zenodo.2583300

**Comment by pjotrp** [comment]
@whedon set 10.5281/zenodo.2583300 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2583300" target="_blank">10.5281/zenodo.2583300</a> is the archive.

**Comment by pjotrp** [comment]
@whedon accept

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/https://doi.org/10.1002/0471142956.cy1017s53 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pjotrp** [comment]
ping eic @openjournals/joss-eics

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/538

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/538, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @athrom @pjotrp I'm going to send this back to you for some more work, because the paper itself does not quite meet [our expectations](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Right now the article itself is extremely brief and doesn't contain much substance; while we don't expect a full article here, it should be 250–1000 words (currently the main article is <150, which put together is a long paragraph). To me, these items need to be improved:

- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software

Further, I think the article should be improved with more description of how the software works, some examples, and use cases.

Also, the first reference has some issues in the way the DOI is being presented, I think.

**Comment by pjotrp** [comment]
@kyleniemeyer I think the paper is fine. It is not meant for a non-specialist audience and I understand it. The purpose is stated too. It is an impressively short paper - which is usually hard to do. 

Yes, the first DOI may be wrong, but the system did not catch that.

**Comment by arfon** [comment]
> @kyleniemeyer I think the paper is fine. It is not meant for a non-specialist audience and I understand it. The purpose is stated too. It is an impressively short paper - which is usually hard to do.

This is incorrect. Quoting directly from https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

> JOSS welcomes submissions from broadly diverse research areas. For this reason, we request that authors include in the paper some sentences that would explain the software functionality and domain of use to a non-specialist reader. Your submission should probably be somewhere between 250-1000 words.

**Comment by kyleniemeyer** [comment]
@pjotrp Furthermore, the @openjournals/joss-eics have agreed that it's our responsibility to give a final pass over a submission, such that we can give feedback to the author(s), reviewers, and editor (if needed) on the expectations we have agreed on.

If you have issues with that, we can take this offline (... online?) to discuss over email, rather than in the review thread.

> Yes, the first DOI may be wrong, but the system did not catch that.

While whedon's superpowers are very helpful, the system isn't perfect, and it's the job of the editor & @openjournals/joss-eics to give a human review. Clearly in this case a minor fix is needed.

**Comment by athrom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #445 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    190      0 --:--:-- --:--:-- --:--:--   191
Error reading bibliography ./paper.bib (line 49, column 3):
unexpected "v"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by athrom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00445/joss.00445/10.21105.joss.00445.pdf)

**Comment by athrom** [comment]
@kyleniemeyer @pjotrp 
I have updated the PDF to include more details as outlined in paper requirements and updated the doi with the version in Pubmed. Is there anything else I need to do to move the process forward?

**Comment by pjotrp** [comment]
Thanks you @athrom. @kyleniemeyer lgtm.

**Comment by kyleniemeyer** [comment]
Hi @athrom, thanks for making those edits! The text looks great now.

I did notice some minor issues with the references, so I went ahead and fixed them (along with a few things in the paper) and submitted as two pull requests: https://github.com/athrom/CytobankAPIstats/pull/4 and https://github.com/athrom/CytobankAPIstats/pull/5

Could you merge those and let me know when?

**Comment by athrom** [comment]
@kyleniemeyer Thanks for helping with reference formatting. I have merged the pull requests.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00445/joss.00445/10.21105.joss.00445.pdf)

**Comment by kyleniemeyer** [comment]
@athrom thanks, looks all good now!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1126/science.1198704 is OK
- 10.1002/0471142956.cy1017s53 is OK
- 10.1172/jci.insight.121544 is OK
- 10.1172/jci.insight.123236 is OK

MISSING DOIs

- https://doi.org/10.1007/978-1-4302-4726-5_7 may be missing for title: CytobankAPI: Cytobank API Wrapper for R

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/547

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/547, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Looks like that missing DOI is a fluke.

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/550
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00445](https://doi.org/10.21105/joss.00445)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
@athrom your paper is now published in JOSS!

Thanks to @nelkibs for reviewing and @pjotrp for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00445/status.svg)](https://doi.org/10.21105/joss.00445)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00445">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00445/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00445/status.svg
   :target: https://doi.org/10.21105/joss.00445
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00445/status.svg)](https://doi.org/10.21105/joss.00445)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
