### ISSUE TITLE
[PRE REVIEW]: simpleCache: R caching for reproducible, distributed, large-scale projects

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#447]
**Submitting author:** @vpnagraj (<a href="http://orcid.org/0000-0003-0060-566X">VP Nagraj</a>)
**Repository:** <a href="https://github.com/databio/simpleCache" target ="_blank">https://github.com/databio/simpleCache</a>
**Version:** 0.3.1
**Editor:** @leeper
**Reviewer:** @sckott

**Author instructions**

Thanks for submitting your paper to JOSS @vpnagraj. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vpnagraj if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by leeper** [comment]
@HenrikBengtsson would you be interested in reviewing this for JOSS?

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by HenrikBengtsson** [comment]
@leeper, it looks interesting but unfortunately I'm too busy right now.

**Comment by leeper** [comment]
No problem, @HenrikBengtsson. Thanks for getting back to me.

**Comment by leeper** [comment]
@sckott would you be interested in reviewing this for JOSS?

**Comment by sckott** [comment]
@leeper sure thing

**Comment by leeper** [comment]
@whedon set @sckott as reviewer

**Comment by arfon** [comment]
> @whedon set @sckott as reviewer

@leeper - there's a slight inconsistency for Whedon here. You need `@whedon assign @sckott as reviewer`

**Comment by leeper** [comment]
@whedon assign @sckott as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sckott

**Comment by leeper** [comment]
@arfon :*d'oh* reaction emoji:

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/463. Feel free to close this issue now!

**Comment by leeper** [comment]
@sckott Thanks so much! Review is setup over here: https://github.com/openjournals/joss-reviews/issues/463
