### ISSUE TITLE
[REVIEW]: FullSWOF: Full Shallow-Water equations for Overland Flow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#448]
**Submitting author:** @mlep (Frédéric Darboux), on behalf of (<a href="http://orcid.org/0000-0003-1700-4553">Carine Lucas</a>)
**Repository:** <a href="http://www.univ-orleans.fr/mapmo/soft/FullSWOF/" target ="_blank">http://www.univ-orleans.fr/mapmo/soft/FullSWOF/</a>
**Version:** v1.07.00
**Editor:** @kyleniemeyer
**Reviewer:** @wkearn
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1095748" target="_blank">10.5281/zenodo.1095748</a>

## Status

[![status](http://joss.theoj.org/papers/f6c58e6ec6eb4bdb5ff82490b4f5cd9b/status.svg)](http://joss.theoj.org/papers/f6c58e6ec6eb4bdb5ff82490b4f5cd9b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f6c58e6ec6eb4bdb5ff82490b4f5cd9b"><img src="http://joss.theoj.org/papers/f6c58e6ec6eb4bdb5ff82490b4f5cd9b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f6c58e6ec6eb4bdb5ff82490b4f5cd9b/status.svg)](http://joss.theoj.org/papers/f6c58e6ec6eb4bdb5ff82490b4f5cd9b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="http://www.univ-orleans.fr/mapmo/soft/FullSWOF/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@wkearn, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://www.univ-orleans.fr/mapmo/soft/FullSWOF/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.07.00)?
- [x] **Authorship:** Has the submitting author (@) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @wkearn it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by wkearn** [comment]
@kyleniemeyer I can't seem to find a `paper.md` file for this submission.

**Comment by kyleniemeyer** [comment]
Hi Carine, can you point to where the paper is in the repository?

Also, could you clarify which version was submitted? I notice that there are three—is it all of them?

**Comment by kyleniemeyer** [comment]
Hi @wkearn, just FYI—I am currently trying to contact the authors of this submission, since it somehow  made it through without having a GitHub account associated with the submitter.

**Comment by kyleniemeyer** [comment]
Hi @mlep, tagging you in this issue

**Comment by kyleniemeyer** [comment]
@wkearn regarding the paper location, I have this from the authors:
> The paper (paper.md) is located as the guidelines indicated at:
http://www.univ-orleans.fr/mapmo/soft/FullSWOF/paper.md
You will also find the bibliography file:
http://www.univ-orleans.fr/mapmo/soft/FullSWOF/paper.bib
and the metadata file:
http://www.univ-orleans.fr/mapmo/soft/FullSWOF/codemeta.json

**Comment by wkearn** [comment]
Great! I'll finish this up shortly. Thanks!

**Comment by wkearn** [comment]
FullSWOF is an excellent, mature piece of software. Everything works as advertised, and the documentation is comprehensive.

I have one minor concern to be addressed before I can recommend acceptance, and a few suggestions that would be nice to see, but aren't critical.

# Minor concern: community guidelines

There doesn't appear to be explicitly stated information on how someone might go about contributing to the software, what kinds of features the developers are most interested in adding, what kinds of improvements are likely to be accepted to the main code base, etc. This creates a relatively high barrier to entry for someone who wants to get involved with development but who doesn't really know where to start.

I call this a minor concern because the contact information for the developers is available on the website, and the documentation contains information on testing/benchmarking for outside contributors. I'd be satisfied with a statement along the lines of "If you are interested in contributing to FullSWOF, contact the developers at ..." in the "How to contact us?" part of the website or in the Introduction to the documentation, though a comprehensive set of contributor guidelines and a list of desired features would be ideal.

# Suggestions

1. It would be nice to have a real-world example walked through in the documentation. The tests shown are classical shallow water benchmarks, but aren't all that helpful in showing how you might go about modeling a flood event with FullSWOF, for instance. Many examples are available in the various published papers that use FullSWOF, so it might be just a matter of finding a good one, linking to the appropriate data, and walking through the steps required to reproduce the findings in the paper. I would recommend the Thies example.

2. The authors could be a bit more explicit in their statement of need about the target audience of FullSWOF. Is this meant to be used primarily by numerical modelers, surface water hydrologists, or stakeholders interested in flood risks?

**Comment by kyleniemeyer** [comment]
Thanks @wkearn!

Hi @mlep, could you and your coauthors take a look at this feedback?

**Comment by mlep** [comment]
Thank you for your review and constructive comments. Please, find below our replies.

>Minor concern: community guidelines
>
>There doesn't appear to be explicitly stated information on how someone might go about contributing to the software, what kinds of features the developers are most interested in adding, what kinds of improvements are likely to be accepted to the main code base, etc. This creates a relatively high barrier to entry for someone who wants to get involved with development but who doesn't really know where to start.
>
>I call this a minor concern because the contact information for the developers is available on the website, and the documentation contains information on testing/benchmarking for outside contributors. I'd be satisfied with a statement along the lines of "If you are interested in contributing to FullSWOF, contact the developers at ..." in the "How to contact us?" part of the website or in the Introduction to the documentation, though a comprehensive set of contributor guidelines and a list of desired features would be ideal.


Indeed, we have overlooked this issue. In fact, we already have a short to-do list at the beginning of the changelog.txt file (https://sourcesup.renater.fr/scm/viewvc.php/trunk/changelog.txt?view=markup&root=fullswof-2d), but this list is hidden to new comers.  
We have now added a paragraph in the main webpage (http://www.univ-orleans.fr/mapmo/soft/FullSWOF/), in the section "How to contact us?". 
We will think how to improve this, perhaps with a todo.txt file at the root of the repository. 



> Suggestions
> - It would be nice to have a real-world example walked through in the documentation. The tests shown are classical shallow water benchmarks, but aren't all that helpful in showing how you might go about modeling a flood event with FullSWOF, for instance. Many examples are available in the various published papers that use FullSWOF, so it might be just a matter of finding a good one, linking to the appropriate data, and walking through the steps required to reproduce the findings in the paper. I would recommend the Thies example.

Thanks again for your suggestion. We are going to add the Thies case into the directory Examples in the next few days.
Additionally, we are in the process of making data input easier for users: we are developing routines to convert GIS data (AscGrid format) into the FullSWOF format (and vice-versa). We are testing them internally at the moment.


> - The authors could be a bit more explicit in their statement of need about the target audience of FullSWOF. Is this meant to be used primarily by numerical modelers, surface water hydrologists, or stakeholders interested in flood risks?

FullSWOF's primary target are surface water hydrologists. Numerical modelers are the secondary target. We have altered the text (in the file http://www.univ-orleans.fr/mapmo/soft/FullSWOF/paper.md) to state this point explicitly, in the first paragraph : "Several features make FullSWOF particularly suitable for surface water hydrologists:[...]" and "The modular structure of FullSWOF is also useful to numerical modelers willing to test new schemes or boundary conditions."

**Comment by wkearn** [comment]
Looks good! 

I'm happy to recommend acceptance at this point.

**Comment by mlep** [comment]
@wkearn: Thank you for your recommendation (and sorry for the delay).
@kyleniemeyer: What is the next stage? Do we have something to do?

**Comment by kyleniemeyer** [comment]
@mlep I'm going to look over the paper from an editorial perspective, but once that is finalized we will need you to archive the accepted version of the software and provide us the DOI (using, e.g., Zenodo or Figshare).

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #448 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:75:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@kyleniemeyer - @whedon won't know how to compile this automatically as the software isn't in a Git repository.

**Comment by kyleniemeyer** [comment]
@arfon hmm, so what do we do?

**Comment by arfon** [comment]
> @arfon hmm, so what do we do?

I usually process submissions like this myself locally with the `Whedon` gem. @mlep - could you please explain how I can download the source code for this repository (together with the `paper.md` and `paper.bib` files)?

**Comment by mlep** [comment]
Dear @arfon,

The files related to the manuscript are here:
- http://www.univ-orleans.fr/mapmo/soft/FullSWOF/paper.md
- http://www.univ-orleans.fr/mapmo/soft/FullSWOF/paper.bib
- http://www.univ-orleans.fr/mapmo/soft/FullSWOF/codemeta.json

For the source codes of the software, they are here:
- https://sourcesup.renater.fr/scm/viewvc.php?root=fullswof-2d
- https://sourcesup.renater.fr/scm/viewvc.php?root=fullswof-1d
- https://sourcesup.renater.fr/scm/viewvc.php?root=fullswof-ui

Thank you for your time.

**Comment by arfon** [comment]
@kyleniemeyer - here's the compiled PDF: [10.21105.joss.00448.pdf](https://github.com/openjournals/joss-reviews/files/1532473/10.21105.joss.00448.pdf)

**Comment by kyleniemeyer** [comment]
@mlep it looks like the URLs included in the text of the paper were not handled properly; rather than the single quotation marks, could you instead wrap all the links with `< >`?

Also, minor wording fix: `FullSWOF is solving these` -> `FullSWOF solves these`

**Comment by mlep** [comment]
@kyleniemeyer We have modified the syntax for the URLs and fixed the wording. Thank you for your comments!

**Comment by kyleniemeyer** [comment]
@mlep thanks! Could you now archive the software (all elements of it—essentially the entire contents of the repository) and provide us the DOI, using something like Zenodo?

**Comment by kyleniemeyer** [comment]
@arfon could you regenerate the PDF for this one, please?

**Comment by arfon** [comment]
Here you go: [10.21105.joss.00448.pdf](https://github.com/openjournals/joss-reviews/files/1540195/10.21105.joss.00448.pdf)

**Comment by mlep** [comment]
@kyleniemeyer Files are now archived on Zenodo. The doi is 10.5281/zenodo.1095748

**Comment by kyleniemeyer** [comment]
@whedon set archive as 10.5281/zenodo.1095748

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.1095748 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1095748" target="_blank">10.5281/zenodo.1095748</a> is the archive.

**Comment by kyleniemeyer** [comment]
@arfon this paper is accepted and ready to be published.

**Comment by mlep** [comment]
@kyleniemeyer How fast!

**Comment by arfon** [comment]
@wkearn - many thanks for your review here and to @kyleniemeyer for editing this submission ✨ 

@mlep - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00448 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00448/status.svg)](https://doi.org/10.21105/joss.00448)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00448/status.svg)](https://doi.org/10.21105/joss.00448)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by mlep** [comment]
@kyleniemeyer @arfon @wkearn: Thank you for managing JOSS editorial process.

**Comment by mlep** [comment]
@kyleniemeyer @arfon @wkearn: Because of the merging of two laboratories, the URL of the repository has changed from http://www.univ-orleans.fr/mapmo/soft/FullSWOF/ to https://www.idpoisson.fr/fullswof/ .
Could the URL be updated on the page of the article (http://joss.theoj.org/papers/10.21105/joss.00448)?
Cheers.

Note: currently there is an automatic redirection, but we do not know for how long it will last.

**Comment by kyleniemeyer** [comment]
@mlep could you update the address in the Markdown paper? that will make this easier, if possible.

**Comment by mlep** [comment]
@kyleniemeyer The updated md file is here: https://www.univ-orleans.fr/mapmo/membres/lucas/paper.md

**Comment by kyleniemeyer** [comment]
@arfon is it possible to update the paper?

**Comment by arfon** [comment]
> @arfon is it possible to update the paper?

Yep. I've updated the paper with the new address. The PDF might take a few hours to update because of caching.

**Comment by mlep** [comment]
@arfon Thank you for the update.
Just a point of attention: the year, volume and number written at the bottom of the pdf file have changed. It is intended?
Before, it was:
````
Delestre et al., (2017). FullSWOF: Full Shallow-Water equations for Overland Flow. Journal of Open Source Software, 2(20), 448, doi:10.21105/joss.00448
````
Now it is:
````
Delestre et al., (2018). FullSWOF: Full Shallow-Water equations for Overland Flow. Journal of Open Source Software, 3(22), 448. https://doi.org/10.21105/joss.00448
````

**Comment by arfon** [comment]
@mlep - good catch. Thanks for spotting that. (It should now be fixed)
