### ISSUE TITLE
[PRE REVIEW]: The psycho Package: an Efficient and Publishing-Oriented Workflow for Psychological Science

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#449]
**Submitting author:** @DominiqueMakowski (<a href="http://orcid.org/0000-0001-5375-9967">Dominique Makowski</a>)
**Repository:** <a href="https://github.com/neuropsychology/psycho.R" target ="_blank">https://github.com/neuropsychology/psycho.R</a>
**Version:** 0.0.2
**Editor:** @leeper
**Reviewer:** @SachaEpskamp

**Author instructions**

Thanks for submitting your paper to JOSS @DominiqueMakowski. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@DominiqueMakowski if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by leeper** [comment]
@dominiquemakowski do you have any suggestions for whom you would like to review this?

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
I'm working on identifying a reviewer for this and will update again once that person is confirmed.

**Comment by leeper** [comment]
@whedon set @SachaEpskamp as reviewer

**Comment by leeper** [comment]
@whedon assign @SachaEpskamp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @SachaEpskamp

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/470. Feel free to close this issue now!
