### ISSUE TITLE
Submission: ChainConsumer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#45]
**Submitting author:** @samreay (<a href="http://orcid.org/0000-0003-2071-9349">Samuel Hinton</a>)
**Repository:** <a href="https://github.com/samreay/ChainConsumer" target ="_blank">https://github.com/samreay/ChainConsumer</a>
**Version:** 0.10.1
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.61064" target="_blank">10.5281/zenodo.61064</a>

## Status

[![status](http://joss.theoj.org/papers/e8496ffefaece1e7614a24cc86b0535b/status.svg)](http://joss.theoj.org/papers/e8496ffefaece1e7614a24cc86b0535b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e8496ffefaece1e7614a24cc86b0535b"><img src="http://joss.theoj.org/papers/e8496ffefaece1e7614a24cc86b0535b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e8496ffefaece1e7614a24cc86b0535b/status.svg)](http://joss.theoj.org/papers/e8496ffefaece1e7614a24cc86b0535b)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/samreay/ChainConsumer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (0.9.5)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00045.pdf](https://github.com/openjournals/joss-reviews/files/387697/10.21105.joss.00045.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by tacaswell** [comment]
:hand: I will review this.

**Comment by Samreay** [comment]
Excellent, thanks Thomas. I had a request for a another feature, so the current version is 0.9.8 I believe. Hope that isn't an issue.

**Comment by tacaswell** [comment]
Sorry, I have fallen down on getting this done.

**Comment by tacaswell** [comment]
- The current release on github is `0.10.0`, how can the submission be updated?
- I suggest making the installation instruction easier to find (give them a heading).  The setup.py should list `install_requires`.  Did not automatically install `statsmodels`
 - no clear link to contributing guidelines
 - statement of need in the documentation could be expanded (what does `corner` not do that this covers?).  The version in the paper is much better.
 - software archive missing from top of pdf
 - should deps other than mpl get citations?

 - what happens in `add_chain` with dict input + a list of parameters?

I recommend publication on the condition of addressing the above minor issues.

**Comment by arfon** [comment]
> The current release on github is 0.10.0, how can the submission be updated?

I can update this. 

> I recommend publication on the condition of addressing the above minor issues.

Many thanks @tacaswell. @samreay - please let us know on this thread when you've had a chance to review and incorporate @tacaswell's feedback.

**Comment by Samreay** [comment]
Hi guys, am making the requested changes now. In regards to

> The setup.py should list install_requires. Did not automatically install statsmodels

Updated.

> no clear link to contributing guidelines

Have added a contribution heading with explicit details on the main page and the readme.

> statement of need in the documentation could be expanded

Have updated the introduction on the documentation page.

> software archive missing from top of pdf

Neither the example [in the about page](http://joss.theoj.org/about) nor the example [example page](https://github.com/arfon/fidgit/tree/master/paper) have the software archive shown at the top of the page - it is instead linked inline in the example. I also do not know how to generate the pdf itself, so am unsure what syntax to use. The identifier tag in the paper.json which contains the DOI is already filled out with the zenodo link, I thought that was going to be automatically injected.

> should deps other than mpl get citations?

Have added citations for numpy and scipy.

> what happens in add_chain with dict input + a list of parameters?

Have updated the API to be clear on this.

**Comment by arfon** [comment]
> software archive missing from top of pdf

@tacaswell @Samreay - yes this is automatically injected at the end of the review once the submission review process is complete. Sorry for any confusion caused here.

Thanks for the rapid turnaround @Samreay. @tacaswell - would you mind taking another look to see if this is good to accept now?

**Comment by tacaswell** [comment]
Statsmodels is not directly cited, where as the other 3 direct dependencies are.  I defer to @arfon on if that is a blocking issue or not.

otherwise all of my concerns are addressend and looks good to publish :+1: 

the version needs to be bumped to 0.10.1

**Comment by Samreay** [comment]
Yes, I hope to replace statsmodels with scikit-learns kde implementation in
their next release, so because of that, and statsmodels not having a
publicised bibtex citation (would have to @misc ref their github). In
addition, unlike matplotlib, numpy and scipy, which are used in all
instances of the library usage, the kde is only used on specific request
(which should be rare). For those reasons I left statsmodels out of the
citations. Would be happy to add them in, but would then have to update the
paper.md after the review when this changed, which seems also inappropriate.

Cheers

**Comment by arfon** [comment]
> Would be happy to add them in, but would then have to update the
paper.md after the review when this changed, which seems also inappropriate.

Provided this is the only change I think we should add Statsmodels to the current list of citations. @Samreay - could you please do this and then make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by Samreay** [comment]
Have added statsmodels and archived. Final doi is
http://dx.doi.org/10.5281/zenodo.61064

**Comment by arfon** [comment]
OK thanks @Samreay. This is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00045 🚀 🎉 💥 

Thanks for the review @tacaswell

**Comment by Samreay** [comment]
Thanks guys!
