### ISSUE TITLE
[PRE REVIEW]: Retriever: Data Retrieval Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#450]
**Submitting author:** @henrykironde (<a href="http://orcid.org/0000-0001-7105-5808">henry senyondo</a>)
**Repository:** <a href="https://github.com/weecology/retriever" target ="_blank">https://github.com/weecology/retriever</a>
**Version:** v2.1.0
**Editor:** @leeper
**Reviewer:** @amoeba

**Author instructions**

Thanks for submitting your paper to JOSS @henrykironde. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@henrykironde if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋🏻 @leeper - the submitting author suggested you as the editor.

**Comment by leeper** [comment]
@amoeba Would you be interested in reviewing this?

**Comment by amoeba** [comment]
@leeper sure. I'll probably need through this weekend to do the review.

**Comment by leeper** [comment]
@amoeba Excellent. Thank you!

**Comment by leeper** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amoeba

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/451. Feel free to close this issue now!

**Comment by leeper** [comment]
@amoeba @henrykironde Review is setup in #451, please take a look at the [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines) as needed and let me know if you have any questions.
