### ISSUE TITLE
[REVIEW]: Retriever: Data Retrieval Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#451]
**Submitting author:** @henrykironde (<a href="http://orcid.org/0000-0001-7105-5808">henry senyondo</a>)
**Repository:** <a href="https://github.com/weecology/retriever" target ="_blank">https://github.com/weecology/retriever</a>
**Version:** v2.1.0
**Editor:** @leeper
**Reviewer:** @amoeba
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1038272" target="_blank">10.5281/zenodo.1038272</a>

## Status

[![status](http://joss.theoj.org/papers/f76a72ab468973531f33b8a1449943a6/status.svg)](http://joss.theoj.org/papers/f76a72ab468973531f33b8a1449943a6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f76a72ab468973531f33b8a1449943a6"><img src="http://joss.theoj.org/papers/f76a72ab468973531f33b8a1449943a6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f76a72ab468973531f33b8a1449943a6/status.svg)](http://joss.theoj.org/papers/f76a72ab468973531f33b8a1449943a6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/weecology/retriever" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@amoeba, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/weecology/retriever">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.1.0)?
- [x] **Authorship:** Has the submitting author (@henrykironde) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @amoeba it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by amoeba** [comment]
Grade: 2) Minor revisions

I've had a chance to sit down and found this submission meets or exceeds the submission requirements on essentially every item on the reviewer checklist. It's clear to me what the software should do, it was easy for me to get the software installed and make use of it. On top of that, the documentation is abundant and well-written and it's clear a great deal of care has been put into many aspects of the project. I've checked all but one item off the list and am left with two outstanding issues:

1. The `paper.md` does not appear to follow the BibTeX convention for in-text citations using the BibTeX `@` identifiers and instead just hard-codes the reference. If my assessment is correct, I'd like to see a quick fix made for those.
2. I'm not 100% confident this submission qualifies as research software. It's fundamental tooling for research so I would happily consider it research software. A quick 👍 from an editor or JOSS would suffice.

@leeper can you please take a look at my two remaining issues and let me know what you think?

**Comment by henrykironde** [comment]
Updated to BibTeX citations

**Comment by amoeba** [comment]
Great, thanks @henrykironde. Relevant checklist item is now checked. 

Grade: 1) Accept

Last outstanding issue is just a quick 👍 from @leeper on fit. I have no outstanding issues.

**Comment by ethanwhite** [comment]
Regarding fit, this seems very much in line with other software published in JOSS. E.g.,

* http://joss.theoj.org/papers/421837399efdbef2a248d0cf4a6c1d15
* http://joss.theoj.org/papers/0f59fb7eaeb2004ea510d38c00051dd3

My group is a research lab and this software was built for our research and funded as research software by both NSF and the Moore Foundation.

**Comment by amoeba** [comment]
I totally agree, @ethanwhite, and imagine @leeper won't disagree either. Thanks for chiming in with those examples. Perhaps the fact that this submission is in the `review` phase is adequate confirmation of fit.

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1038272 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1038272" target="_blank">10.5281/zenodo.1038272</a> is the archive.

**Comment by leeper** [comment]
@amoeba Excellent. Thank you for your quick review! Very much appreciated.

@henrykironde This looks ready to me. Great submission and thanks for your quick response to the review.

@arfon Over to you.

**Comment by arfon** [comment]
@amoeba - many thanks for your review and to @leeper for your help editing this one ✨ 

@henrykironde - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00451 ⚡️ 🚀 💥

**Comment by henrykironde** [comment]
On behalf of the Team [@Data Retriever](https://github.com/weecology/retriever) we thank you for the time taken to review this paper.

**Comment by henrykironde** [comment]
@arfon, I have just noted that I made a mistake in importing the names of the authors. The main author's name has been corrected. Is there away we could update the paper?

**Comment by Deborah-Digges** [comment]
@arfon I have been affiliated with the University of Florida. Could this affiliation be removed?

**Comment by henrykironde** [comment]
@Deborah-Digges what is your affiliation?

**Comment by Deborah-Digges** [comment]
You could mention "PES Institute of Technology".

Thank you!

**Comment by arfon** [comment]
@henrykironde - please update the affiliations in `paper.md` in https://github.com/weecology/retriever and let me know when you're ready to have the paper re-generated.

**Comment by henrykironde** [comment]
@arfon I have updated the paper.md

**Comment by arfon** [comment]
> @arfon I have updated the paper.md

OK thanks. I've re-generated the paper now too: https://github.com/openjournals/joss-papers/blob/8a8bb9cfd7d0d31ba84475e7708df7b4594413af/joss.00451/10.21105.joss.00451.pdf

**Comment by ethanwhite** [comment]
@arfon - it looks like maybe the regeneration didn't take care of something somewhere because I just noticed that the citation on the website is for the old (incorrect) name.

![screenshot from 2017-12-11 12-40-18](https://user-images.githubusercontent.com/744427/33845154-79688204-de70-11e7-9f56-25f7cb36547f.png)

**Comment by arfon** [comment]
@ethanwhite - good catch. That's fixed now.

**Comment by ethanwhite** [comment]
Thanks @arfon!
