### ISSUE TITLE
[PRE REVIEW]: ros_control: A generic and simple control framework for ROS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#452]
**Submitting author:** @bmagyar (<a href="http://orcid.org/0000-0001-8455-8674">Bence Magyar</a>)
**Repository:** <a href="https://github.com/ros-controls/joss_paper" target ="_blank">https://github.com/ros-controls/joss_paper</a>
**Version:** 0.12.0
**Editor:** @danielskatz
**Reviewer:** @progtologist

**Author instructions**

Thanks for submitting your paper to JOSS @bmagyar. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bmagyar if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @bmagyar. Thanks for your submission to JOSS. A couple of questions/clarifications on this submission:

- Could you confirm what the research application of the `ros-controls` suite of software is?
- I'm concerned about the amount of work any reviewer is going to have to do here to review this submission. We generally expect one repository per submission but this looks to be a collection of separate software repositories. Is there a 'main' repository that it might make more sense to submit?

**Comment by bmagyar** [comment]
Hi @arfon 

`ros_control` is a framework for robot control for robots using the Robot Operating System (ROS). ROS is core to most modern robotics research and it is making it's way to industry as well (e.g.: warehouse robots, home-care research platforms, commercial & research-grade self driving cars). The last section of our paper has a list of some research robots where `ros_control` is used to provide the control architecture & allows for researchers to create their custom controllers using the framework. This project is rather mature, hence the size and number of applications.

I was indeed a bit worried that the review may get a wee bit tricky...

We split the framework among different repositories to ease the binary release process as some packages such as message definitions and core libraries are changed less frequently than our off-the-shelf controllers. I don't think it'd make sense to assess only one part of it.

I can try to help by providing a more detailed guide with pointing out all sources of documentation, how to set things up on one's machine for a quick test and pointers to our continuous integration & test suite with Travis.

**Comment by arfon** [comment]
> We split the framework among different repositories to ease the binary release process as some packages such as message definitions and core libraries are changed less frequently than our off-the-shelf controllers. I don't think it'd make sense to assess only one part of it.

OK thanks @bmagyar. 

> I can try to help by providing a more detailed guide with pointing out all sources of documentation, how to set things up on one's machine for a quick test and pointers to our continuous integration & test suite with Travis.

Yes, I think that might be useful. Also, a forewarning: we might struggle a little to find an editor and reviewers for this submission as it's somewhat outside our 'regular' subject matter.

**Comment by danielskatz** [comment]
I'm a little familiar with ROS, and could act as editor, given good suggestions for reviewers.

**Comment by bmagyar** [comment]
Am I allowed to suggest or does it have to come from the editors?

**Comment by arfon** [comment]
> Am I allowed to suggest or does it have to come from the editors?

We'd welcome some names (and ideally GitHub handles) for some potential reviewers.

**Comment by kyleniemeyer** [comment]
I may be able to help with a reviewer or two—I have some robotics colleagues here at Oregon State who work closely with ROS.

**Comment by danielskatz** [comment]
@bmagyar, please offer some suggestions (that don't have conflicts, of course)

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by bmagyar** [comment]
* Jose Luis Rivero: worked for the Open Source Robotics Foundation (creators & maintainers of ROS) for years | https://github.com/j-rivero

* Aris Synodinos: University of Patras, Robotics Group  | https://github.com/progtologist

* Miguel Prada: works for Tecnalia, Spain. | https://github.com/miguelprada

There are 3 more people on my list, waiting for confirmation of interest.

**Comment by bmagyar** [comment]
* Jorge Nicho (will be away but can either volunteer a colleague or review when back): works at Southwest Research Institute, they are part of the ROS-Industrial consortium  | https://github.com/jrgnicho

**Comment by danielskatz** [comment]
@j-rivero, @progtologist, @miguelprada - would you be willing to review this submission for JOSS?  

Please see http://joss.theoj.org/about#reviewer_guidelines for reviewer guidelines.

Also, please be sure you do not have any conflict of interest.

**Comment by progtologist** [comment]
@danielskatz you can count me in

**Comment by miguelprada** [comment]
@danielskatz count me in too.

**Comment by danielskatz** [comment]
Thanks @@progtologist and @miguelprada 
I'll set up the review and get back to you shortly.

**Comment by danielskatz** [comment]
@whedon assign @progtologist as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @progtologist

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/456. Feel free to close this issue now!

**Comment by j-rivero** [comment]
> @j-rivero, @progtologist, @miguelprada - would you be willing to review this submission for JOSS?

Sorry for not answering before, I'm happy to help if you sill need someone to perform a review.

**Comment by danielskatz** [comment]
that's ok - we have enough reviewers now.
