### ISSUE TITLE
[PRE REVIEW]: A framework for generating interactive reports for cancer genome analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#455]
**Submitting author:** @aokad (<a href="http://orcid.org/0000-0002-9782-5900">Ai Okada</a>)
**Repository:** <a href="https://github.com/Genomon-Project/paplot/" target ="_blank">https://github.com/Genomon-Project/paplot/</a>
**Version:** 0.5.5
**Editor:** @pjotrp
**Reviewer:** @chfi

**Author instructions**

Thanks for submitting your paper to JOSS @aokad. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@aokad if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pjotrp - the submitting author suggested you as the editor.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @chfi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @chfi

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/457. Feel free to close this issue now!
