### ISSUE TITLE
[REVIEW]: A framework for generating interactive reports for cancer genome analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#457]
**Submitting author:** @aokad (<a href="http://orcid.org/0000-0002-9782-5900">Ai Okada</a>)
**Repository:** <a href="https://github.com/Genomon-Project/paplot/" target ="_blank">https://github.com/Genomon-Project/paplot/</a>
**Version:** 0.5.5
**Editor:** @pjotrp
**Reviewer:** @chfi
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1083949" target="_blank">10.5281/zenodo.1083949</a>

## Status

[![status](http://joss.theoj.org/papers/96e840e7edae58a6b6d5eb042870e361/status.svg)](http://joss.theoj.org/papers/96e840e7edae58a6b6d5eb042870e361)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/96e840e7edae58a6b6d5eb042870e361"><img src="http://joss.theoj.org/papers/96e840e7edae58a6b6d5eb042870e361/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/96e840e7edae58a6b6d5eb042870e361/status.svg)](http://joss.theoj.org/papers/96e840e7edae58a6b6d5eb042870e361)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Genomon-Project/paplot/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@chfi, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Genomon-Project/paplot/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.5.5)?
- [x] **Authorship:** Has the submitting author (@aokad) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @chfi it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
Dear @aokad, @chfi will review your interesting submission. To expedite the process please go through above check list and see if we can tick (most) boxes. That would be very helpful. When you confirm you are set Christian will take over. Thanks, Pj.

**Comment by aokad** [comment]
Dear @pjotrp, @chfi, 

I really appreciate the prompt response to our submission. 
As far as I confirmed, I believe our software satisfies most of the check list except: 

1. Automated tests: Our repository currently supports automated test for the build. We will further improve so that several command executions can be checked soon.
2. Community guidelines: We will soon include clearer statement in the document.
3. References: We will improve the reference list so that DOIs are included.

**Comment by pjotrp** [comment]
Excellent. @chfi feel free to start.

**Comment by chfi** [comment]
Dear @aokad, your submission looks very good. Installing and running was a breeze, and everything appears to work just as the excellent documentation says it should. The only things I found missing are the three parts you already identified and are working on :)

**Comment by pjotrp** [comment]
Thanks @chfi! @aokad tell us when you are ready and we can wrap up.

**Comment by aokad** [comment]
Dear @pjotrp, @chfi, 
I have resolved.

1. Automated tests: I added "python setup.py test", which checks the validity of several sub-commands for generating analytical reports.
2. Community guidelines: I have included some description on community guideline to the Contact section in the documentation (http://paplot-doc.readthedocs.io/en/latest/info.html#contact)
3. References: I added DOIs to paper/paper.bib.

Please kindly let me.

**Comment by chfi** [comment]
Looks good! I'm ready to accept this submission.

**Comment by pjotrp** [comment]
Thanks for the fast turn around! @arfon we are ready for the next step.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf
```

**Comment by arfon** [comment]
@aokad - apologies for the late reply to this thread but could you please add a little more detail to your paper. Please see the guidance for authors [here](http://joss.theoj.org/about#paper_structure).

**Comment by pjotrp** [comment]
Yes, main thing is to make it clear to readers what it is about. See it as an advertisement for your work. A figure is usually a good idea. See one of our own [papers](http://joss.theoj.org/papers/84b27b28948be80a47268a5baa2701ad) as an example.

**Comment by aokad** [comment]
@arfon, @pjotrp, thank you very much for the suggestion. 
I have included detailed description on our software. Please let me know if there is any idea for improving the paper.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf
```

**Comment by arfon** [comment]
> @arfon, @pjotrp, thank you very much for the suggestion.
I have included detailed description on our software. Please let me know if there is any idea for improving the paper.

@aokad - many thanks for adding some more detail to your submission. At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by pjotrp** [comment]
@aokad, it looks very nice! Can you check the generated PDF - there are some extraneous dashes (word breaks) and you may want to introduce a page break for the figure. If you have any plans for the future with this tooling I would add a short description of that too.

https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf

**Comment by aokad** [comment]
@pjotrp, thank you for your suggestion. I have updated the layout of the figure.
@arfon, please re-generate pdf.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
> @arfon, please re-generate pdf.

@aokad - you should be able to do this yourself 😁

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf
```

**Comment by pjotrp** [comment]
@aokad if your are happy can you make you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? We can then move forward with accepting the submission.

**Comment by aokad** [comment]
@arfon, @pjotrp, thank you, I have made an archive. DOI is 10.5281/zenodo.1083949.

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by pjotrp** [comment]
@whedon set 10.5281/zenodo.1083949 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1083949" target="_blank">10.5281/zenodo.1083949</a> is the archive.

**Comment by pjotrp** [comment]
@arfon, we are ready to R&R

**Comment by arfon** [comment]
@chfi - many thanks for your review here and to @pjotrp for editing this submission ✨ 

@aokad - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00457 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00457/status.svg)](https://doi.org/10.21105/joss.00457)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00457/status.svg)](https://doi.org/10.21105/joss.00457)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://bit.ly/joss-reviewers

**Comment by aokad** [comment]
@arfon I’m very sorry, but I have realized that there are still many remaining extra dashes in the accepted paper. I’m happy if I  can update the paper. Is it possible? The DOI of the modified version is 10.5281/zenodo.1095371.

Thank you very much in advance.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1095371 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1095371" target="_blank">10.5281/zenodo.1095371</a> is the archive.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf
```

**Comment by arfon** [comment]
@aokad - no problem. Can you confirm this version of the paper looks good? https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf

**Comment by aokad** [comment]
@arfon, thank you, I'll contact you as soon as I finish reviewing.

**Comment by aokad** [comment]
@arfon I'm sorry to bother you again, but as a result of the reconsideration, I changed the arrangement of sentences. 
I'm happy if I can update the paper. The DOI of the modified version is 10.5281/zenodo.1098885.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf
```

**Comment by arfon** [comment]
@aokad - please review the [linked PDF above](https://github.com/openjournals/joss-papers/blob/joss.00457/joss.00457/10.21105.joss.00457.pdf) carefully. I would _really_ like to make this the last round of edits 🙏 😁

**Comment by aokad** [comment]
@arfon, thank you very much.  This is okay.
