### ISSUE TITLE
[PRE REVIEW]: DART: Dynamic Animation and Robotics Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#460]
**Submitting author:** @jslee02 (<a href="http://orcid.org/0000-0002-2146-7502">Jeongseok Lee</a>)
**Repository:** <a href="https://github.com/dartsim/dart" target ="_blank">https://github.com/dartsim/dart</a>
**Version:** 6.3.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @bmagyar

**Author instructions**

Thanks for submitting your paper to JOSS @jslee02. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jslee02 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @labarba - the submitting author suggested you as the editor.

**Comment by jslee02** [comment]
Thank you for initiating this process!

I have a question about ORCID and am asking the question here because I couldn't find an available email address to the editors of JOSS.

Unfortunately, we don't have the ORCID for one of the authors because he is passed away. What could we do in this case? We could make one for him, but I wonder if it would be preferred to just leaving it empty or 0000-0000-0000-0000.

**Comment by arfon** [comment]
@jslee02 - it's ok to omit the ORCID field for the author who has passed away.

**Comment by jslee02** [comment]
@arfon Thanks! I'll omit the ORCID field.

**Comment by jslee02** [comment]
Potential reviewers: @mosteo, @katyhuff, @betatim, @pragyansmita, @kyleniemeyer

**Comment by betatim** [comment]
I'd be happy to look at this.

**Comment by Kevin-Mattheus-Moerman** [comment]
I've also pinged my colleagues at MIT Biomechatronics

**Comment by Kevin-Mattheus-Moerman** [comment]
I can be editor if @labarba can't take this one

**Comment by labarba** [comment]
Feel free to take it, @Kevin-Mattheus-Moerman.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @kevin-mattheus-moerman as editor

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon I'm trying to assign myself as editor. It seems whedon removed lorena but it does not look like it assigned me. Can you see what is going on?

**Comment by kyleniemeyer** [comment]
@Kevin-Mattheus-Moerman you are listed as editor above, no? it looks like @whedon just didn't assign you to the issue.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer @arfon thanks yep it is all good

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00460/10.21105.joss.00460.pdf
```

**Comment by arfon** [comment]
☝️ @Kevin-Mattheus-Moerman - Whedon can now try and compile the PDF for you. Looks like this worked (I'm trying to catch errors with the papers before they even get to the review stage now).

**Comment by jslee02** [comment]
There was a [correction](https://github.com/dartsim/dart/pull/945) of the affiliations. Let me regenerate the PDF.

**Comment by jslee02** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #460 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00460/joss.00460/10.21105.joss.00460.pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00460/joss.00460/10.21105.joss.00460.pdf
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00460/joss.00460/10.21105.joss.00460.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@bmagyar I know @danielskatz just pinged you to review over at https://github.com/openjournals/joss-reviews/issues/477,... but if this submission interests you as well it would be great if you could assist with review here too.

**Comment by jslee02** [comment]
@Kevin-Mattheus-Moerman I'm not trying to involve in the reviewer matching process, but I just wonder if you saw @betatim's [comment](https://github.com/openjournals/joss-reviews/issues/460#issuecomment-345426150) above that he's interested in looking at this submission.

**Comment by bmagyar** [comment]
Hi guys,

Yes,  I'd be pretty interested in reviewing this one actually! The only
downside is that I can only start it over the holidays.

**Comment by Kevin-Mattheus-Moerman** [comment]
Great @bmagyar ! Starting over the holidays is fine.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jslee02  thanks for your inquiry. I was hoping to recruit more than 1 reviewer and also include a robotics specialist. It seems we have exactly that now so we are good to start. Both @bmagyar and @betatim will be reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @bmagyar as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bmagyar

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/500. Feel free to close this issue now!
