### ISSUE TITLE
[REVIEW]: simpleCache: R caching for reproducible, distributed, large-scale projects

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#463]
**Submitting author:** @vpnagraj (<a href="http://orcid.org/0000-0003-0060-566X">VP Nagraj</a>)
**Repository:** <a href="https://github.com/databio/simpleCache" target ="_blank">https://github.com/databio/simpleCache</a>
**Version:** 0.3.1
**Editor:** @leeper
**Reviewer:** @sckott
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1140853" target="_blank">10.5281/zenodo.1140853</a>

## Status

[![status](http://joss.theoj.org/papers/ff76fd08aa8082e1e3e5e52ad2f44a47/status.svg)](http://joss.theoj.org/papers/ff76fd08aa8082e1e3e5e52ad2f44a47)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ff76fd08aa8082e1e3e5e52ad2f44a47"><img src="http://joss.theoj.org/papers/ff76fd08aa8082e1e3e5e52ad2f44a47/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ff76fd08aa8082e1e3e5e52ad2f44a47/status.svg)](http://joss.theoj.org/papers/ff76fd08aa8082e1e3e5e52ad2f44a47)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/databio/simpleCache" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sckott, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/databio/simpleCache">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.3.1)?
- [x] **Authorship:** Has the submitting author (@vpnagraj) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @sckott it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by sckott** [comment]
Nice work @vpnagraj et al. I have a few comments, with linked issues in your GH repo as applicable

- Two of the references in the `paper.md` are missing DOIs (and the papers do have DOIs) - https://github.com/databio/simpleCache/issues/27 
- Community guidelines: could be more on this front -  https://github.com/databio/simpleCache/issues/28
- Tests: tests are present, but could be improved - https://github.com/databio/simpleCache/issues/29 
- I'm not sure if this was intended, but the package level manual text at the top of the `R/simpleCache.R` file is wrapped into the resulting man file `simpleCache.Rd`. is this intended?  Perhaps if you want a separate pkg level manual file, use `@name simpleCache-package` (I'd recommend that to have package level docs as needed)
- Package docs: some thoughts at https://github.com/databio/simpleCache/issues/30
- Pkg makes extensive use of options in functions. Users can set options outside of the functions in the pkg. I didn't see any docs on setting options via `options` outside of fxns. Do you recommend users do that or not do that?  Curious also why you went with options and not env vars (not leaning one way or other, just curious)?

**Comment by leeper** [comment]
Thanks for the great review, @sckott! Much appreciated.

@vpnagraj Please try to respond to Scott's points and the specific issues he's raised.

**Comment by nsheff** [comment]
Thanks for the review, @sckott and @leeper. We will look into it and respond to this issues shortly!

**Comment by leeper** [comment]
@nsheff Just checking in - how are revisions progressing?

**Comment by nsheff** [comment]
Hi @leeper; almost done, we'll have a new release for you shortly.

**Comment by nsheff** [comment]
Hi @leeper and @sckott,

Thanks for the feedback. We've now released [version 0.4](https://github.com/databio/simpleCache/releases), which we think addresses all your comments. Thanks for the review!

To respond to one point here:

>Pkg makes extensive use of options in functions. Users can set options outside of the functions in the pkg. I didn't see any docs on setting options via options outside of fxns. Do you recommend users do that or not do that? Curious also why you went with options and not env vars (not leaning one way or other, just curious)?

We recommend users use the functions to set the options, because these are easier to maintain and change. In a sense, the functions (which are documented) provide a contract with the user; we will honor those functions in the future. The actual option names, and the implementation of how they work, could change at some point, but the functions will remain the same. So, we'd rather just abstract away the actual implementation (whether it uses options, env vars, etc), so that we have room to adjust this as simpleCache advances, without breaking old code. We tried to make this clear with the documentation that explains these setter functions.

**Comment by sckott** [comment]
explanation of options makes sense

**Comment by leeper** [comment]
It looks to me like all issues have been addressed. Is that right, @sckott?

@nsheff Can you produce an archive of the repository using, e.g., Zenodo, and let me know the DOI for it?

**Comment by sckott** [comment]
had another quick look. Yes, looks good.

**Comment by nsheff** [comment]
DOI: 10.5281/zenodo.1140853

See: https://zenodo.org/record/1140853#.WlTOVvZG15w

**Comment by leeper** [comment]
@whedon set archive as 10.5281/zenodo.1140853

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1140853 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1140853" target="_blank">10.5281/zenodo.1140853</a> is the archive.

**Comment by leeper** [comment]
@nsheff This looks great. You're all set! Congratulations!

**Comment by leeper** [comment]
@arfon This one's for you.

**Comment by arfon** [comment]
@sckott - many thanks for your review here and to @leeper for editing this submission ✨ 

@vpnagraj @nsheff - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00463 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00463/status.svg)](https://doi.org/10.21105/joss.00463)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00463/status.svg)](https://doi.org/10.21105/joss.00463)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
