### ISSUE TITLE
[REVIEW]: chloroExtractor: extraction and assembly of the chloroplast genome from whole genome shotgun data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#464]
**Submitting author:** @greatfireball (<a href="http://orcid.org/0000-0003-4166-5423">Frank Förster</a>)
**Repository:** <a href="https://github.com/chloroExtractorTeam/chloroExtractor" target ="_blank">https://github.com/chloroExtractorTeam/chloroExtractor</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @jdeligt
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1148955" target="_blank">10.5281/zenodo.1148955</a>

## Status

[![status](http://joss.theoj.org/papers/eaceb6ac6723a3ea5749f7f50d4a4ad4/status.svg)](http://joss.theoj.org/papers/eaceb6ac6723a3ea5749f7f50d4a4ad4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/eaceb6ac6723a3ea5749f7f50d4a4ad4"><img src="http://joss.theoj.org/papers/eaceb6ac6723a3ea5749f7f50d4a4ad4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/eaceb6ac6723a3ea5749f7f50d4a4ad4/status.svg)](http://joss.theoj.org/papers/eaceb6ac6723a3ea5749f7f50d4a4ad4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/chloroExtractorTeam/chloroExtractor" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jdeligt, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/chloroExtractorTeam/chloroExtractor">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@greatfireball) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jdeligt it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
Thanks @jdeligt for being willing to review this submission! Make sure to accept the invite to the 'openjournals/joss-reviews' repository to be able to tick above boxes and read the reviewer instructions http://joss.theoj.org/about. @greatfireball it is very helpful if you can go through above checklist first and make sure the important points are implemented. Please reply here if you think it all hunky dory!

**Comment by jdeligt** [comment]
I'll wait with further review until @greatfireball has gone through the checklist.
Found one small issue in the paper.md that has been raised on their repo:
https://github.com/chloroExtractorTeam/chloroExtractor/issues/80

**Comment by jdeligt** [comment]
And please check the docker image and example usage, currently it fails:
https://github.com/chloroExtractorTeam/chloroExtractor/issues/81

**Comment by jdeligt** [comment]
As well as the binary download: 
> [17-11-17 15:57:06] [fcg] Unable to open file 'ass/assembly_graph.fastg'
> [17-11-17 15:57:06] [PipeWrap] fcg exited:256
> [17-11-17 15:57:06] [PipeWrap]  at /Users/jdeligt/code/chloroExtractor/bin/../lib/PipeWrap.pm line 153

**Comment by jdeligt** [comment]
Dependencies do not contain version numbers

**Comment by pjotrp** [comment]
Dear @greatfireball please fix/comment before we continue.

**Comment by greatfireball** [comment]
Hey @pjotrp and @jdeligt sorry for the delay. Think we could close those issues above by https://github.com/chloroExtractorTeam/chloroExtractor/issues/83 and https://github.com/chloroExtractorTeam/chloroExtractor/issues/81. @jdeligt mentioned another issue, but we need some more information to reproduce his finding. Nevertheless, the his major concerns should be solved. Please let us know, how we can help you to continue the review process. Thanks again for your time, your help, and your review.

Best,
Frank

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by pjotrp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #464 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/author.rb:32:in `block in build_affiliation_string': Problem with affiliations for Markus J Ankenbrand, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/author.rb:31:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/author.rb:31:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/author.rb:11:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:97:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:97:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:95:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:95:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:76:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by pjotrp** [comment]
@greatfireball while @jdeligt wraps up the review you can generate and check the PDF using above command. It should come out clean.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00464/joss.00464/10.21105.joss.00464.pdf
```

**Comment by greatfireball** [comment]
Thanks for generating the PDF @arfon

**Comment by arfon** [comment]
> Thanks for generating the PDF @arfon

No problem. You raised an interesting bug in our processing system with your paper :-)

**Comment by greatfireball** [comment]
Always a pleasure :)

**Comment by greatfireball** [comment]
Happy new year to both of you @pjotrp and @jdeligt, hope you had a wonderful holiday season. We updated our paper.md and added some more citations. We are still waiting for the more detailed description of the issue @jdeligt found. Please let us know if we can help you finishing the review process.

**Comment by jdeligt** [comment]
Thanks for the reminder and updating the documentation and contribution sections. The latest & greatest binary is running now, if it produces errors I will raise a well documented issue, if not I will tick the last box and the review will be concluded.

**Comment by jdeligt** [comment]
Apart from a minor issue with relative paths https://github.com/chloroExtractorTeam/chloroExtractor/issues/88 no further problems were encountered and this issue can be worked around by the average user. Seen how the previous issues were handled I am confident that this will be resolved and should not impede publication.

As such I'm closing this review and would recommend publication.

**Comment by jdeligt** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by jdeligt** [comment]
@pjotrp Whedon seems disinclined/unable to close the review process, can you work your editorial powers and move the paper along?

**Comment by pjotrp** [comment]
@arfon we are ready to R&R

**Comment by arfon** [comment]
@greatfireball - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by greatfireball** [comment]
Of course I can :) I did a copy of the current status and pushed it to Zenodo. Its DOI is [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1147434.svg)](https://doi.org/10.5281/zenodo.1147434) and the current version number was bumped to v1.0.1

@jdeligt, @pjotrp, and @arfon thanks for your efforts!

**Comment by greatfireball** [comment]
I would like to add the guy who did solve the Mac-issues with our container to the acknowledge section of the paper. Would be nice, if that would be possible. I will then create another version for zenodo. So sry @arfon for the delay. Just give me an hour.

**Comment by greatfireball** [comment]
The new DOI is [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1148955.svg)](https://doi.org/10.5281/zenodo.1148955) and the current version is 1.0.2

Thanks again!

**Comment by arfon** [comment]
> I would like to add the guy who did solve the Mac-issues with our container to the acknowledge section of the paper. Would be nice, if that would be possible. I will then create another version for zenodo. So sry @arfon for the delay. Just give me an hour.

That sounds like a nice idea. Did you add this already @greatfireball?

**Comment by greatfireball** [comment]
Yeah... Version v1.0.2 contains @DanielAmsel in the acknowledgements section

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1148955 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1148955" target="_blank">10.5281/zenodo.1148955</a> is the archive.

**Comment by arfon** [comment]
@jdeligt - many thanks for your review here and to @pjotrp for editing this submission ✨ 

@greatfireball - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00464 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00464/status.svg)](https://doi.org/10.21105/joss.00464)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00464/status.svg)](https://doi.org/10.21105/joss.00464)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
