### ISSUE TITLE
[REVIEW]: mpnum: A matrix product representation library for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#465]
**Submitting author:** @dseuss (<a href="http://orcid.org/0000-0002-6354-457X">Daniel Suess</a>)
**Repository:** <a href="https://github.com/dseuss/mpnum" target ="_blank">https://github.com/dseuss/mpnum</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @SylvainCorlay
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1115574" target="_blank">10.5281/zenodo.1115574</a>

## Status

[![status](http://joss.theoj.org/papers/f5d6dc694fffcffa13f0def4b42bb113/status.svg)](http://joss.theoj.org/papers/f5d6dc694fffcffa13f0def4b42bb113)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f5d6dc694fffcffa13f0def4b42bb113"><img src="http://joss.theoj.org/papers/f5d6dc694fffcffa13f0def4b42bb113/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f5d6dc694fffcffa13f0def4b42bb113/status.svg)](http://joss.theoj.org/papers/f5d6dc694fffcffa13f0def4b42bb113)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dseuss/mpnum" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@SylvainCorlay, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dseuss/mpnum">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@dseuss) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @SylvainCorlay it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by labarba** [comment]
Hi @SylvainCorlay — ping! Gentle reminder here about the review for JOSS. You can start on it, and report any issues you encounter right here (or post issues on the repo of the submitted software). Cheers!

**Comment by dseuss** [comment]
After the submission, we noted a compatibility bug in the `setup.py` that prevents v1.0.0 to be installed with Python2. Could we bump the refereed version to v1.0.1.

**Comment by labarba** [comment]
I don't see a problem with that, @dseuss—thanks for the update.

**Comment by SylvainCorlay** [comment]
> After the submission, we noted a compatibility bug in the setup.py that prevents v1.0.0 to be installed with Python2. Could we bump the refereed version to v1.0.1.

Same here.

**Comment by dseuss** [comment]
> Same here.

Does that mean 1.0.1 doesn't work for you either?

**Comment by SylvainCorlay** [comment]
> Does that mean 1.0.1 doesn't work for you either?

Absolutely! Pardon my brevity.

**Comment by SylvainCorlay** [comment]
Note: I checked the box regarding the matched version. I don't know if it matters that the generated issue specifies 1.0.0

**Comment by SylvainCorlay** [comment]
As I am going through the checklist:

>  References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

I found that there is a DOI for the reference **Enabling High-Dimensional Hierarchical Uncertainty Quantification by ANOVA and Tensor-Train Decomposition*.

**Comment by dseuss** [comment]
@SylvainCorlay Thanks for the feedback.

> I found that there is a DOI for the reference Enabling High-Dimensional Hierarchical Uncertainty Quantification by ANOVA and Tensor-Train Decomposition.
Added DOI and updated arXiv references for another paper  in `a3aaaf5`

> Very minor: on this point, a "contributing" section in the readme could be added (simply linking to the relevant section of the documentation).
Done.

> For some reason, I had to install hdf5 to be able to run the tests. The test_requires specify h5py, which probably requires some installation of hdf5. It seems that the test requirements won't use wheels.
Right, I recalled that we had to manually install test dependencies on travis for that reason. I have added a note to the README as well as to the [documentation](http://mpnum.readthedocs.io/en/latest/devel.html). (The latter should appear once readthedocs renders the new version)

**Comment by SylvainCorlay** [comment]
I could install, run the tests, and the example notebook. The whole process was straightforward. The need for the package is properly justified and prior work appropriately cited. Documentation includes both high-level narrative documentation introducing the package and an API reference generated from the doc strings (although a few items are left as todo).

1) Quick note about the example notebook: I find it extremely useful and detailed. A link to the notebook is provided in the documentation, but the rendered notebook itself could probably be included *as-is* in the documentation. A good tool to achieve this is to use the [nbsphinx](https://nbsphinx.readthedocs.io/en/0.2.18/) sphinx extension.

Minor suggestion: the notebook could include some visual from the narrative documentation about the graphical notation, and how it translate with a simple code example.

3) About the narrative documentation:  *the matrix product state representation of a state* comes without context. The rest of the paragraph is more self-explanatory but I think that this is domain-specific, and is probably not necessary for introducing MPS and MPO.

**Comment by labarba** [comment]
@SylvainCorlay : I see that all boxes are checked. Can you confirm that you recommend acceptance now?

**Comment by dseuss** [comment]
Thanks a lot @SylvainCorlay for the helpful comments. We already implemented remark 1 on the master branch in the repo. We will address the other remarks shortly after fixing some slight mistakes in some images. 

@labarba I would move the `v1.0.1` tag to a different commit in the repo once we incorporate all the fixes. Since all the fixes are in the documentation, this does not affect the version on PyPi. Would that be okay with you?

**Comment by labarba** [comment]
Yay! @dseuss —We'll now need you to deposit the final release on an archival host like figshare or Zenodo, and report here the DOI. Then @arfon will press the buttons to publish!

**Comment by dseuss** [comment]
I have uploaded the final version v1.0.2 with the DOI [10.5281/zenodo.1115574](https://doi.org/10.5281/zenodo.1115574). We have updated the refereed version according to the suggestions of the referee:

- Added some images to the notebook
- Embedded the notebook on readthedocs

We also migrated all the figures from Inkscape to LaTeX/TikZ and fixed some notation errors.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.1115574 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1115574" target="_blank">10.5281/zenodo.1115574</a> is the archive.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00465/joss.00465/10.21105.joss.00465.pdf
```

**Comment by labarba** [comment]
@arfon On to you to push the accept button!

**Comment by dseuss** [comment]
Could we wait for another hour? I just noticed that the bibliography in the PDF is everything but consistent. I'll try to fix this now.

**Comment by dseuss** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00465/joss.00465/10.21105.joss.00465.pdf
```

**Comment by dseuss** [comment]
OK, now I am happy with it as well. Just cleaned up the names in the references, removed unnecessary fields from the bib file, and fixed citations of the Oseledets paper, which gave ??? in the old version.

**Comment by milan-hl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00465/joss.00465/10.21105.joss.00465.pdf
```

**Comment by milan-hl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00465/joss.00465/10.21105.joss.00465.pdf
```

**Comment by milan-hl** [comment]
I slightly adapted the spelling of one of the references. I'm looking forward to the paper being published. Thanks everyone!

**Comment by arfon** [comment]
@SylvainCorlay - many thanks for your review here and to @labarba for editing this submission ✨ 

@dseuss - your submission is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00465 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00465/status.svg)](https://doi.org/10.21105/joss.00465)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00465/status.svg)](https://doi.org/10.21105/joss.00465)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://bit.ly/joss-reviewers
