### ISSUE TITLE
[PRE REVIEW]: An easy-to-use p5.js 3D object picker for visual artists

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#466]
**Submitting author:** @physicsdavid (<a href="http://orcid.org/0000-0002-8321-2062">David Harris</a>)
**Repository:** <a href="https://github.com/physicsdavid/mPicker" target ="_blank">https://github.com/physicsdavid/mPicker</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @Fil

**Author instructions**

Thanks for submitting your paper to JOSS @physicsdavid. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@physicsdavid if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00466/joss.00466/10.21105.joss.00466.pdf
```

**Comment by physicsdavid** [comment]
Of the existing reviewer list, perhaps @fil might be most appropriate but it's unclear given that this submission is outside the scope of most JOSS submissions. In the pre-submission query, @kyleniemeyer was open to a submission of this kind. I believe you also had some discussions with the editorial team so you might have a clearer idea.

**Comment by arfon** [comment]
Thanks @physicsdavid.

@Fil - would you be willing to review this submission for JOSS?

**Comment by Kevin-Mattheus-Moerman** [comment]
@SimonDanish is this submission of interest to you, would you be willing to review it too?

**Comment by Fil** [comment]
Yes! (but next week).

**Comment by arfon** [comment]
> Yes! (but next week).

Great! Thanks @Fil.

**Comment by arfon** [comment]
@whedon assign @Fil as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Fil

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/475. Feel free to close this issue now!

**Comment by arfon** [comment]
@Fil - please head over to #475 to carry out the actual review.
