### ISSUE TITLE
[PRE REVIEW]: PyTransport: A Python package for the calculation of inﬂationary correlation functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#468]
**Submitting author:** @jronayne (<a href="http://orcid.org/0000-0001-6464-6466">John Ronayne</a>)
**Repository:** <a href="https://github.com/jronayne/PyTransport" target ="_blank">https://github.com/jronayne/PyTransport</a>
**Version:** v2.0.0
**Editor:** @arfon
**Reviewer:** @joezuntz

**Author instructions**

Thanks for submitting your paper to JOSS @jronayne. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jronayne if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #468 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #468 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@jronayne - please take another look at the [submission guidelines](http://joss.theoj.org/about#paper_structure) and make sure you have a `paper.md` and `paper.bib` file in your repository.

**Comment by jronayne** [comment]
Hello,

Apologises, I had missed that part of the guideline. I have added the paper.md and paper.bib files into the repository.

It should be good to go.

Regards,
John

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00468/joss.00468/10.21105.joss.00468.pdf
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@joezuntz - would you be willing to review this submission for JOSS? You can read more about what's involved here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by joezuntz** [comment]
@arfon Sure, I'd be happy to referee this.  What timescale do you usually ask for?  I probably couldn't complete this before the holidays.

**Comment by arfon** [comment]
> @arfon Sure, I'd be happy to referee this. What timescale do you usually ask for? I probably couldn't complete this before the holidays.

👍 thanks. Sometime early in the new year would be completely fine.

**Comment by arfon** [comment]
@whedon assign @joezuntz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @joezuntz

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/494. Feel free to close this issue now!

**Comment by arfon** [comment]
@joezuntz - please head over to #494 when you get a chance.
