### ISSUE TITLE
[REVIEW]: Xbim.Essentials: a library for interoperable building information applications

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#473]
**Submitting author:** @CBenghi (<a href="http://orcid.org/0000-0003-3252-5461">Claudio Benghi</a>)
**Repository:** <a href="https://github.com/xBimTeam/XbimEssentials" target ="_blank">https://github.com/xBimTeam/XbimEssentials</a>
**Version:** 4.0
**Editor:** @arfon
**Reviewer:** @Haacked
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1095192" target="_blank">10.5281/zenodo.1095192</a>

## Status

[![status](http://joss.theoj.org/papers/b23bed93a0377b4f4317d0583b4d2c5e/status.svg)](http://joss.theoj.org/papers/b23bed93a0377b4f4317d0583b4d2c5e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b23bed93a0377b4f4317d0583b4d2c5e"><img src="http://joss.theoj.org/papers/b23bed93a0377b4f4317d0583b4d2c5e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b23bed93a0377b4f4317d0583b4d2c5e/status.svg)](http://joss.theoj.org/papers/b23bed93a0377b4f4317d0583b4d2c5e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/xBimTeam/XbimEssentials" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Haacked, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xBimTeam/XbimEssentials">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (4.0)?
- [x] **Authorship:** Has the submitting author (@CBenghi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @Haacked it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00473/joss.00473/10.21105.joss.00473.pdf
```

**Comment by arfon** [comment]
@Haacked - please work through the checklist at the top of this issue. If you have any questions, don't hesitate to ask.

We also have some [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines) which should help you understand the purpose and scope of the review.

**Comment by CBenghi** [comment]
@Haacked,
I've noticed that you have skipped some checkboxes above, so I've improved the submission as follows:

- **Example usage**: I've added an example section in the readme.md to point to the examples available on docs.xbim.net.
- **References**: I've updated the paper.md file to fix two references that were misinterpreted in the previous version.  I've double checked that any entry that does not list a DOI does not have one at all.

Now that I've seen how the paper gets rendered I've also corrected some markdown that worked in my pandoc configuration but has a different behaviour here. While at it I've also changed some text to improve the pagination (a new page happened just before a list) and the diagram of DLL dependencies. I'm not sure how to trigger a recompilation of the PDF.

Have you got any specific guidance for  **Functionality documentation**?

Claudio

**Comment by CBenghi** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by CBenghi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00473/joss.00473/10.21105.joss.00473.pdf
```

**Comment by CBenghi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00473/joss.00473/10.21105.joss.00473.pdf
```

**Comment by Haacked** [comment]
> I've noticed that you have skipped some checkboxes above

@CBenghi, sorry about that. I meant to get to it but I'm at a conference in the Dominican Republic so I've been very busy and didn't get a chance to finish.

I wasn't sure how to check that the DOI references are correct.

> Have you got any specific guidance for Functionality documentation?

I mostly looked at the `///` style code comments for public APIs in the code. I think it could use more of them, but it looks like the important stuff is document. Is there API documentation I'm missing?

**Comment by CBenghi** [comment]
@Haacked, 

my apologies, I had no intention to put pressure on you. There's absolutely no rush, I was only trying to improve the submission so that it would be easier for you to review.

We have no external API docs yet. We have documented the APIs with IntelliSense as you have seen, particularly in the areas where most questions and issues have been received. In our experience this seems Ok for people to start engaging, but I agree that there could be more. I'll check again to see if there are obvious omissions tomorrow.

We have plans to automate the IntelliSense comments on auto-generated classes from the ISO documentation (about 1500 classes and 8000 properties) but it might end up in the next release, and - in a way - it could be considered outside the scope of our contribution, these are only implementations of external schemas.

Regarding the DOI:
It's very easy to test that the DOI that we have specified is correct: click on the DOI part of the reference and it'll take you to the a page where you can control the match.

Conversely, ensuring that a registered DOIs do not exist for the others is much harder and I cannot be certain that I've made no mistakes there, but I've [spent hours searching](https://www.crossref.org/guestquery/) with no luck.

I hope you are enjoying the conference.

Best,
Claudio

**Comment by Haacked** [comment]
Ok, I checked everything off. Is there anything left for me to do?

**Comment by arfon** [comment]
> Ok, I checked everything off. Is there anything left for me to do?

Great. Thanks @Haacked - just your confirmation that you're happy with the software you've reviewed here.

Once I have that I can proceed with accepting the submission.

**Comment by Haacked** [comment]
@arfon I confirm i’m happy with it.

**Comment by arfon** [comment]
@CBenghi - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by CBenghi** [comment]
@arfon,
I've issued a release and recorded it with zenodo with DOI: 10.5281/zenodo.1095192

@Haacked, 
very many thanks for your support with the review process. Hugely appreciated.

The very process of submission have made us think hard about the quality of the software including the aspects of community engagement and documentation. Hopefully this practice will spread and we'll get more from the open source movement than ever before.
I'd be happy to help as a reviewer in the future, if useful.

Thanks, and keep up the good work!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1095192 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1095192" target="_blank">10.5281/zenodo.1095192</a> is the archive.

**Comment by arfon** [comment]
@Haacked - many thanks again for your review here ✨ 

@CBenghi - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00473 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00473/status.svg)](https://doi.org/10.21105/joss.00473)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00473/status.svg)](https://doi.org/10.21105/joss.00473)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
