### ISSUE TITLE
[PRE REVIEW]: The Experiment Factory: Reproducible Experiment Containers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#474]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/expfactory/expfactory" target ="_blank">https://www.github.com/expfactory/expfactory</a>
**Version:** v3.0.0
**Editor:** @leeper
**Reviewer:** @oesteban

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00474/joss.00474/10.21105.joss.00474.pdf
```

**Comment by arfon** [comment]
👋 @leeper - the submitting author suggested you as the handling editor.

**Comment by vsoch** [comment]
:wave: @whedon and @arfon and @leeper, looking forward to the review!

**Comment by vsoch** [comment]
hey @whedon @arfon @leeper anything you need from me?

**Comment by leeper** [comment]
Hi @vsoch, if you have any reviewer suggestions, please let me know.

**Comment by vsoch** [comment]
oh, of course! I think a mix of linux, python, and general experimental knowledge (e.g., psychology, sociology, or economics) would be a logical match, so I'll recommend any of @cMadan @nirum @oesteban  @jsta and @ctb. If we need additional recommendations I could look into others outside of the provided list, please let me know.

**Comment by cMadan** [comment]
This looks like a great project, but unfortunately I don't have time to review it currently.

**Comment by vsoch** [comment]
No worries @cMadan, hang in there it's almost the holiday! :)

**Comment by leeper** [comment]
Hi @nirum would you be interested in reviewing this for JOSS?

**Comment by nirum** [comment]
Hi all, looks interesting, but I don't have the bandwidth right now to give this a proper review :(

**Comment by leeper** [comment]
Hi @oesteban would you be interested in reviewing this for JOSS?

**Comment by oesteban** [comment]
Hi, sorry for the silence. Yes, I can take this. :+1:

**Comment by vsoch** [comment]
woohoo, thanks @oesteban !

**Comment by leeper** [comment]
@whedon assign @oesteban as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @oesteban

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/521. Feel free to close this issue now!

**Comment by leeper** [comment]
@oesteban That's great! Thank you! I've fired up a review ticket here: https://github.com/openjournals/joss-reviews/issues/521, which provides all instructions. Let me know if you have questions.
