### ISSUE TITLE
[REVIEW]: An easy-to-use p5.js 3D object picker for visual artists

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#475]
**Submitting author:** @physicsdavid (<a href="http://orcid.org/0000-0002-8321-2062">David Harris</a>)
**Repository:** <a href="https://github.com/physicsdavid/mPicker" target ="_blank">https://github.com/physicsdavid/mPicker</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @Fil
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1081934" target="_blank">10.5281/zenodo.1081934</a>

## Status

[![status](http://joss.theoj.org/papers/b15a14310643cf6fa2c307e907620d65/status.svg)](http://joss.theoj.org/papers/b15a14310643cf6fa2c307e907620d65)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b15a14310643cf6fa2c307e907620d65"><img src="http://joss.theoj.org/papers/b15a14310643cf6fa2c307e907620d65/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b15a14310643cf6fa2c307e907620d65/status.svg)](http://joss.theoj.org/papers/b15a14310643cf6fa2c307e907620d65)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/physicsdavid/mPicker" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Fil, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/physicsdavid/mPicker">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@physicsdavid) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @Fil it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00475/joss.00475/10.21105.joss.00475.pdf
```

**Comment by Fil** [comment]
Hello David (@physicsdavid)

After a first look at the requirements, a few of them are found insufficient:
- version: needs a corresponding *release*
- statement of need (both in the software and the paper): needs a better explanation of why it's difficult to do this object picking in native p5 (maybe a link to an example of how people do it manually)
- Installation instructions: please write out the dependencies. From the example file we see that you include p5 and two addons, are the addons necessary?
- example usage: the example doesn't work out of the box (I had to fix the path to ../mPicker/mPicker.js); it is far from a real-world example (but that's optional); the kitten is adorable
- functionality documentation: the documentation doesn't seem to hold on its own and needs to be read alongside p5 documentation, please at minimum provide a link to relevant page(s) on p5 regarding the intention and parameters of each function
- automated tests: none
- community guidelines: absent

I might be wrong on some of these issues, please don't hesitate to say it. And I will review again when they are fixed.

Though I'm not a p5 user myself (yet), it looks like the use case is indeed invaluable, and worth working to have this paper published in JOSS.

**Comment by physicsdavid** [comment]
Thanks, Philippe (@Fil). These are very helpful comments. I believe I have addressed your issues with the following notes:
- dependencies/example: Although the two p5 addons are not strictly necessary, the standard p5.js template package includes them as part of the index.html file as they are commonly used in many p5.js applications and their inclusion in index.html appears in most p5.js applications. I have also packaged the example as a .zip as this is the way that many p5.js applications are presented, including those downloaded from the p5.js web editor at http://alpha.editor.p5js.org/
- automated tests: given the nature of the p5.js environment, there does not seem to be an appropriate automated test for this code, but the example code includes an implementation of the core functionality of this code so could be used as a test for future changes.

Feel free to ask for further revisions. Thanks again.

**Comment by Fil** [comment]
Thank you @physicsdavid for all the changes. They do indeed address all the issues!

(The only caveat is I'm not sure I understand why you have made a zip file of the example — it looked more directly accessible and readable as plain files one could look up on github or open in a browser. But it's not an issue for this review.)

@arfon my review is complete and positive for publication.

**Comment by physicsdavid** [comment]
Thanks, @Fil! 

One of the common ways to distribute p5.js applications is via a zip file that contains the set of index.html, sketch.js, plus other assets as required. If you develop a sketch in the online editor (as many of my students do, for example), then if you want to download the sketch, you get a pre-packaged zip with everything in the right folder structure, etc. It's certainly not necessary and I could change it back. One other advantage is that many artists beginning to work with code won't be particularly familiar with github and will likely find it easier to just download one zip file with the example than deal with the files separately. But I'm open to whichever option seems better!

**Comment by Fil** [comment]
Agreed, but in my (limited) understanding that is what the *release* is for.

**Comment by physicsdavid** [comment]
@Fil, I've reconsidered and changed the file structure of the example to make it consistent with the release as the downloadable version with the example files easily readable as separate files within GitHub. I'm still getting used to appropriate use of GitHub!

**Comment by arfon** [comment]
@Fil @physicsdavid - where are we at with this review? Is there still more to be done here?

**Comment by Fil** [comment]
Yes @arfon my review is complete and positive. Thank you @physicsdavid for
the most recent structure changes, makes it even easier to read the example.

**Comment by arfon** [comment]
> Yes @arfon my review is complete and positive. Thank you @physicsdavid for the most recent structure changes, makes it even easier to read the example.

Great! 

@physicsdavid - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by physicsdavid** [comment]
Here is the DOI of the archived version: 10.5281/zenodo.1081934

Thanks!
David

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1081934 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1081934" target="_blank">10.5281/zenodo.1081934</a> is the archive.

**Comment by arfon** [comment]
@Fil - many thanks for your review here ✨ 

@physicsdavid - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00475 ⚡️ 🚀 💥
