### ISSUE TITLE
[PRE REVIEW]: BATMAN: Statistical analysis for expensive computer codes made easy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#476]
**Submitting author:** @tupui (<a href="http://orcid.org/0000-0001-9816-1416">Pamphile ROY</a>)
**Repository:** <a href="https://gitlab.com/cerfacs/batman" target ="_blank">https://gitlab.com/cerfacs/batman</a>
**Version:** v1.7
**Editor:** @katyhuff
**Reviewer:** @mikeckennedy

**Author instructions**

Thanks for submitting your paper to JOSS @tupui. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@tupui if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00476/joss.00476/10.21105.joss.00476.pdf
```

**Comment by tupui** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by tupui** [comment]
For the reviewers, I propose these new names:
@mikeckennedy 
@dbader

And from the list:
@ scollis
@ lheagy
@ katyhuff

**Comment by tupui** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00476/joss.00476/10.21105.joss.00476.pdf
```

**Comment by tupui** [comment]
Hi @arfon, wanted to check on the status of our paper. Still no editor but one reviewer I proposed seems OK to review. So can the review start in the meantime an editor gets assigned?

**Comment by arfon** [comment]
👋 @jakevdp and @karthik - would one of you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
> Hi @arfon, wanted to check on the status of our paper. Still no editor but one reviewer I proposed seems OK to review. So can the review start in the meantime an editor gets assigned?

**Comment by tupui** [comment]
@arfon - OK, will want then.Tthank you for asking other editors.

**Comment by arfon** [comment]
@katyhuff - would you be willing to edit this submission for JOSS?

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@mikeckennedy Are you interested in and able to review this publication? (and can you confirm that you have no conflicts of interest in doing so?)

**Comment by mikeckennedy** [comment]
Hi @katyhuff. Sounds interesting and I'd like to help. What are the responsibilities of a reviewer?

I have no conflicts of interest as far as I know.

Best,
Michael

**Comment by katyhuff** [comment]
Great @mikeckennedy ! This guide is helpful to understand the reviewer process: http://joss.theoj.org/about#reviewer_guidelines  Basically, you're expected to download the code, review it's documentation, try to run the examples, try to evaluate whether it does what it says it does, and a few simple other things on our checklist. Ideally, this should only take a few hours, and should be done quickly but thoroughly. Are you in?

**Comment by scollis** [comment]
Hey team.. I saw my mention here.. I am new :) So this basically means I am on a list of *potential* reviewers? ie I don't need to do anything :)

**Comment by katyhuff** [comment]
@scollis If you're interested in reviewing also, that would be great. Two reviewers is better than one. As I mentioned to @mikeckennedy , this guide is helpful to understand the reviewer process: http://joss.theoj.org/about#reviewer_guidelines Basically, you're expected to download the code, review it's documentation, try to run the examples, try to evaluate whether it does what it says it does, and a few simple other things on our checklist. Ideally, this should only take a few hours, and should be done quickly but thoroughly. Are you in?

**Comment by scollis** [comment]
I had a look at the review guide. Nicely put together. You make it very clear what is expected of reviewers. Typically what is the turn around time?

**Comment by mikeckennedy** [comment]
Thanks @katyhuff  I think I'm probably in. How quickly do you need the review?

**Comment by katyhuff** [comment]
Hi both (@scollis and @mikeckennedy ), thanks for being willing. Ideally, the turn around time should be a week or two. In practice, there is a long tail to the distribution. I recognize we are coming upon the holiday season, but if you could aim to have it done in the next few weeks, that would be great. I'm going to start the review process.

**Comment by katyhuff** [comment]
@whedon assign @mikeckennedy as reviewer.

**Comment by whedon** [comment]
OK, the reviewer is @mikeckennedy

**Comment by katyhuff** [comment]
@whedon assign @scollis as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @scollis

**Comment by katyhuff** [comment]
@whedon assign @mikeckennedy as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mikeckennedy

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/493. Feel free to close this issue now!

**Comment by katyhuff** [comment]
@tupui , the review will happen over in separate issue, #493. @scollis and @mikeckennedy will both review.

**Comment by tupui** [comment]
Thank you @katyhuff, @mikeckennedy and @scollis for accepting to handle our paper. If you have any question, I will be happy to help! We are actively developing the package. So as suggested by JOSS, do not hesitate to create issues in our bug tracker.
