### ISSUE TITLE
[PRE REVIEW]: Gophernotes: the Go kernel for Jupyter and nteract

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#478]
**Submitting author:** @dwhitena (<a href="http://orcid.org/0000-0003-1155-8889">Daniel Whitenack</a>)
**Repository:** <a href="https://github.com/gopherdata/gophernotes" target ="_blank">https://github.com/gopherdata/gophernotes</a>
**Version:** v1.0.0-RC
**Editor:** @arokem
**Reviewer:** @vsivsi

**Author instructions**

Thanks for submitting your paper to JOSS @dwhitena. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dwhitena if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #478 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
Hey Lucas @lgeiger, is this your cup of tea? Are you able to review this submission for JOSS?

**Comment by Kevin-Mattheus-Moerman** [comment]
@dwhitena our system has not detected your paper.md and paper.bib files. Can you please add these to your repository [as per our guidelines](http://joss.theoj.org/about#author_guidelines). Thanks

**Comment by dwhitena** [comment]
@Kevin-Mattheus-Moerman Oh yeah, thanks for the quick feedback. I will get this resolved asap. Sorry for the delay.

**Comment by arfon** [comment]
@arokem - would you be willing to edit this submission for JOSS?

**Comment by arokem** [comment]
Yeah - I will edit this!

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
@dwhitena : do you have any suggestions for reviewers?

**Comment by dwhitena** [comment]
@arokem I would suggest Sebastien Binet (`sbinet`) and/or Brendan Tracey (`btracey`). I'm traveling again today, but hoping to resolve the issue with the included paper today or tomorrow morning at the latest. Thanks again!

**Comment by dwhitena** [comment]
@arokem The issues with the paper and metadata files should be resolved. Let me know if they still aren't detected. Thanks!

**Comment by arokem** [comment]
Let's see what happens if I do this: 

@whedon generate pdf

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #478 with the following error: 

 pandoc-citeproc: "stdin" (line 10, column 2):
unexpected "B"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by arokem** [comment]
Well, that's progress. 

In other news, I have contacted a potential reviewer, and will know tomorrow whether they're a go (I had to!). Otherwise, I will use your suggestions.

**Comment by arokem** [comment]
@whedon assign @vsivsi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vsivsi

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/508. Feel free to close this issue now!
