### ISSUE TITLE
[PRE REVIEW]: GIBBON: The Geometry and Image-Based Bioengineering add-ON

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#479]
**Submitting author:** @Kevin-Mattheus-Moerman (<a href="http://orcid.org/0000-0003-3768-4269">Kevin Moerman</a>)
**Repository:** <a href="https://github.com/gibbonCode/GIBBON" target ="_blank">https://github.com/gibbonCode/GIBBON</a>
**Version:** v2.5.0
**Editor:** @cMadan
**Reviewer:** @siboles

**Author instructions**

Thanks for submitting your paper to JOSS @Kevin-Mattheus-Moerman. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Kevin-Mattheus-Moerman if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00479/joss.00479/10.21105.joss.00479.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan I recommend the following as potential reviewers to this [JOSS](http://joss.theoj.org/about) submission: @gpeyre @siboles

**Comment by cMadan** [comment]
@Kevin-Mattheus-Moerman - it's great to see this project submitted to JOSS! I look forward to overseeing the review process :)

@gpeyre @siboles - are either of you available to review this submission? Thanks!

**Comment by siboles** [comment]
Yes, I am happy to review this. I am a bit under load at the moment, but 
will get to it before the holidays.

Best,

Scott

**Comment by wspr** [comment]
How many reviewers do you like to have? I may also be able to assist.

**Comment by gpeyre** [comment]
Hello,

I am sorry but I will not be able to make the review.

Best

Gabriel

**Comment by cMadan** [comment]
@wspr, one reviewer is usually what we have, but am happy to have feedback from a few people and have a more thorough review process.

**Comment by siboles** [comment]
Hello,
Sorry if this is the wrong place to post, but has the review been started for this. If I recall, a new issue would be opened for the review.
Best,
Scott

**Comment by arfon** [comment]
> Sorry if this is the wrong place to post, but has the review been started for this. If I recall, a new issue would be opened for the review.

@siboles - it doesn't look like @cMadan has started the main review yet.

**Comment by cMadan** [comment]
@siboles, I wasn't sure if someone would be more available to review, but I suppose it has been two weeks now. I'm happy to assign you as the reviewer and get things started.

@wspr, if you're available to contribute to the review, please feel free to also evaluate the submission and make comments!

**Comment by cMadan** [comment]
@whedon assign @siboles as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @siboles

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/506. Feel free to close this issue now!
