### ISSUE TITLE
[REVIEW]: False arrhythmia alarm reduction in the intensive care unit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#481]
**Submitting author:** @liandrea4 (<a href="http://orcid.org/0000-0001-8419-5527">Andrea Li</a>)
**Repository:** <a href="https://github.com/MIT-LCP/false-alarm-reduction" target ="_blank">https://github.com/MIT-LCP/false-alarm-reduction</a>
**Version:** v1.0.1
**Editor:** @arfon
**Reviewer:** @stsievert
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/061fb354807880b63afd1a2e55ffb0ee/status.svg)](https://joss.theoj.org/papers/061fb354807880b63afd1a2e55ffb0ee)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/061fb354807880b63afd1a2e55ffb0ee"><img src="https://joss.theoj.org/papers/061fb354807880b63afd1a2e55ffb0ee/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/061fb354807880b63afd1a2e55ffb0ee/status.svg)](https://joss.theoj.org/papers/061fb354807880b63afd1a2e55ffb0ee)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MIT-LCP/false-alarm-reduction" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@stsievert, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MIT-LCP/false-alarm-reduction">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license? [Yes, MIT]
- [x] **Version:** Does the release version given match the GitHub release (v1.0.1)?
- [x] **Authorship:** Has the submitting author (@liandrea4) made major contributions to the software? Does the full list of paper authors seem appropriate and complete? [Yes, though the commits are listed under Andrew Li]

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation? https://github.com/MIT-LCP/false-alarm-reduction/pull/2 filed
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is? [No. They have a one sentence description of their code's purpose but no intended audience]
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution. [They mention how to install deps]
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems). [None seen]
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)? [I don't see any documentation].
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified? [I don't there are any tests.]
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support [Not that I see]

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is? [Not beyond the title/one sentence description]
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @stsievert it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00481/joss.00481/10.21105.joss.00481.pdf
```

**Comment by stsievert** [comment]
Sorry for the delay on this, but I've finally got around to starting this review. I've written some comments about, but here I've fleshed some of them out:

* Documentation needs improvement
    * At the very least, I should understand what your software does. Typically I can understand what each function does in a piece of software. 
    * I'd have some high-level overview of the software that describes why the software is useful and what features it provides (more than once sentence at the top of the README).
    * Ideally, every functions should have docstrings to describe the inputs/outputs and purpose
    * I'd look at the [readthedocs Getting Started guide][rtd]. Good examples of documentation are with [dask.distributed API] and the [requests API].
* Tests need implementation
    * At minimum, indicate how I can tell if your software performs as expected (likely via a file that uses a couple `assert`ions).
    * Ideally, every function should be tested that it produces the expected outputs. [py.test] is a good tool to help with this.
* Community guidelines
    * I'd have a `CONTRIBUTING` file that lists various tasks you'd like contributors to do. See [GitHub's Contributing Guidelines][gcg].

I'd look at the [JOSS author guidelines] and [JOSS reviewer guidelines].

[requests API]:http://docs.python-requests.org/en/master/
[dask.distributed API]:https://distributed.readthedocs.io/en/latest/
[JOSS author guidelines]:http://joss.theoj.org/about#author_guidelines
[JOSS reviewer guidelines]:http://joss.theoj.org/about#reviewer_guidelines
[gcg]:https://github.com/blog/1184-contributing-guidelines
[rtd]:https://docs.readthedocs.io/en/latest/getting_started.html
[py.test]:https://docs.pytest.org/en/latest/

**Comment by arfon** [comment]
@liandrea4 - please take a look at @stsievert's feedback and let us know when you've had a chance to make the improvements to your submission.

**Comment by arfon** [comment]
Friendly reminder to check in on this soon @liandrea4.

**Comment by alistairewj** [comment]
Thanks - this is a very helpful review and apologies for the delay - we will get on this ASAP.

**Comment by arfon** [comment]
@alistairewj - how are we getting along here?

**Comment by alistairewj** [comment]
Hey @arfon - thanks for patiently following up. We have done a lot - the docs have been rewritten from scratch more or less and are now much more organized - using Sphinx with the plan to host them on readthedocs. Also tidied up a lot of the functions to be more modular and testable - though no tests so far. It's much improved and many thanks to @stsievert for the review.

However, I'm starting to believe we don't really have the time to fully flesh out the package. Essentially, re-reading the journal guidelines, I think our package is too narrow of a contribution (more or less 1-2 algorithms for false alarm reduction), and I don't think we have the time to expand it outside of that (making it more modular and extensible for other users). @liandrea4 is also very busy with getting her masters in an unrelated project. I'm leaning towards deploying the docs this weekend and not pursuing publication - but would be great to hear your thoughts. Thanks again.

**Comment by arfon** [comment]
> However, I'm starting to believe we don't really have the time to fully flesh out the package. Essentially, re-reading the journal guidelines, I think our package is too narrow of a contribution (more or less 1-2 algorithms for false alarm reduction), and I don't think we have the time to expand it outside of that (making it more modular and extensible for other users). @liandrea4 is also very busy with getting her masters in an unrelated project. I'm leaning towards deploying the docs this weekend and not pursuing publication - but would be great to hear your thoughts. Thanks again.

@alistairewj - thanks for getting back to us - I totally understand where you're coming from. If you like we can withdraw this submission on your behalf. If you ever decide to revisit this we'd welcome a re-submission.

**Comment by arfon** [comment]
@stsievert - many thanks for your efforts here. I've gone ahead and withdrawn the submission on behalf of the authors.
