### ISSUE TITLE
[PRE REVIEW]: CheSweet: An application to predict glycan’s chemicals shifts

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#482]
**Submitting author:** @PabloGGaray (<a href="http://orcid.org/0000-0001-6604-0329">Pablo Garay</a>)
**Repository:** <a href="https://github.com/BIOS-IMASL/chesweet" target ="_blank">https://github.com/BIOS-IMASL/chesweet</a>
**Version:** 0.0.1
**Editor:** @arfon
**Reviewer:** @richardjgowers

**Author instructions**

Thanks for submitting your paper to JOSS @PabloGGaray. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@PabloGGaray if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00482/joss.00482/10.21105.joss.00482.pdf
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @richardjgowers - would you be willing to review this submission for JOSS?

**Comment by richardjgowers** [comment]
@arfon Hi, yep looks like a good match

**Comment by arfon** [comment]
> @arfon Hi, yep looks like a good match

Great, thanks! I'll go ahead and assign you and set up the main review issue next..

**Comment by arfon** [comment]
@whedon assign @richardjgowers as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @richardjgowers

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/488. Feel free to close this issue now!

**Comment by arfon** [comment]
@richardjgowers - please head over to #488 to carry out the actual review. I'll be following along there so just shout if anything isn't clear.
