### ISSUE TITLE
[PRE REVIEW]: kima: Exoplanet detection in radial velocities

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#483]
**Submitting author:** @j-faria (<a href="http://orcid.org/0000-0002-6728-244X">João Faria</a>)
**Repository:** <a href="https://github.com/j-faria/kima" target ="_blank">https://github.com/j-faria/kima</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @barentsen

**Author instructions**

Thanks for submitting your paper to JOSS @j-faria. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@j-faria if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00483/joss.00483/10.21105.joss.00483.pdf
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
👋 @barentsen - would you be interested in reviewing this submission for JOSS?

**Comment by barentsen** [comment]
@arfon It would be a privilege to review this package, however I will likely not get to it until next Monday due to travel and commitments.  Would that be acceptable?

**Comment by arfon** [comment]
> @arfon It would be a privilege to review this package, however I will likely not get to it until next Monday due to travel and commitments. Would that be acceptable?

👍 yep, that would be completely acceptable :-)

**Comment by arfon** [comment]
@whedon assign @barentsen as reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/487. Feel free to close this issue now!

**Comment by arfon** [comment]
@barentsen - when you're ready, please head over to #487 to carry out your review.
