### ISSUE TITLE
[PRE REVIEW]: phyphy: A Python package for facilitating the execution and parsing of HyPhy standard analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#484]
**Submitting author:** @sjspielman (<a href="http://orcid.org/0000-0002-9090-4788">Stephanie Spielman</a>)
**Repository:** <a href="https://github.com/sjspielman/phyphy" target ="_blank">https://github.com/sjspielman/phyphy</a>
**Version:** v0.1
**Editor:** @mgymrek
**Reviewer:** @luizirber

**Author instructions**

Thanks for submitting your paper to JOSS @sjspielman. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sjspielman if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #484 with the following error: 

 pandoc-citeproc: Could not find paper.bib
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Pandoc.hs:224:39 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Pandoc
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
👋 @sjspielman - it looks like you're `paper.md` file is referencing a bibtex file named `paper.bib` but there isn't a bibtex file with that name. Could you rename the bibtex file appropriately?

**Comment by sjspielman** [comment]
Yes, my apologies! It was accidentally named `bib.md`. I have now renamed it to `paper.bib` and pushed the change.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00484/joss.00484/10.21105.joss.00484.pdf
```

**Comment by arfon** [comment]
> Yes, my apologies! It was accidentally named bib.md. I have now renamed it to paper.bib and pushed the change.

Great, that's looking much better. This was just a 'pre-flight' check on my part to make sure the paper was compiling OK. Don't expect much activity until one of the JOSS topic editors has volunteered to handle this submission :-)

**Comment by arfon** [comment]
@brainstorm @biorelated @mgymrek @pjotrp - would one of your be willing to edit this submission for JOSS?

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
@krother @Genomematt @luizirber @konrad @cbrueffer Would anyone like to review this submission?

**Comment by luizirber** [comment]
I can review it

**Comment by mgymrek** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by mgymrek** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/514. Feel free to close this issue now!
