### ISSUE TITLE
[PRE REVIEW]: pyodesys: Straightforward numerical integration of ODE systems from Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#485]
**Submitting author:** @bjodah (<a href="http://orcid.org/0000-0003-0596-0222">Björn Dahlgren</a>)
**Repository:** <a href="https://github.com/bjodah/pyodesys" target ="_blank">https://github.com/bjodah/pyodesys</a>
**Version:** v0.11.5
**Editor:** @arfon
**Reviewer:** @arghdos

**Author instructions**

Thanks for submitting your paper to JOSS @bjodah. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bjodah if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #485 with the following error: 

 ! Undefined control sequence.
l.276 Differential Equations in c\(\mathplus

pandoc: Error producing PDF
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
👋 @bjodah - looks like there are some issues with pandoc and your bibtex file, perhaps with the LaTeX syntax on [this line](https://github.com/bjodah/pyodesys/blob/master/joss-paper/paper.bib#L46)? Perhaps these can just be replaced with `+` symbols rather than LaTeX commands?

**Comment by bjodah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00485/joss.00485/10.21105.joss.00485.pdf
```

**Comment by bjodah** [comment]
Looking at the list of possible reviewers, I believe @arghdos might be willing to review?

**Comment by arghdos** [comment]
@bjodah Looks interesting, I'd be happy to review

**Comment by arghdos** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arghdos** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @arghdos, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arghdos** [comment]
@arfon feel free to start the review with me as the reviewer whenever

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arghdos as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arghdos

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/490. Feel free to close this issue now!

**Comment by arfon** [comment]
@arghdos - please head over to #490 to carry out the actual review.
