### ISSUE TITLE
[PRE REVIEW]: Category Encoders: a scikit-learn-contrib package of transformers for encoding categorical data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#486]
**Submitting author:** @wdm0006 (<a href="http://orcid.org/0000-0001-5188-3577">William McGinnis</a>)
**Repository:** <a href="https://github.com/scikit-learn-contrib/categorical-encoding" target ="_blank">https://github.com/scikit-learn-contrib/categorical-encoding</a>
**Version:** v1.2.5
**Editor:** @jakevdp
**Reviewer:** @desilinguist

**Author instructions**

Thanks for submitting your paper to JOSS @wdm0006. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wdm0006 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00486/joss.00486/10.21105.joss.00486.pdf
```

**Comment by arfon** [comment]
👋 @jakevdp - would you be willing to edit this submission for JOSS?

**Comment by jakevdp** [comment]
@desilinguist – would you be willing to review this submission?

**Comment by desilinguist** [comment]
@jakevdp I'd be happy to review this but I am about to go on Christmas break so I can probably start when I'm back in early January?

**Comment by jakevdp** [comment]
@desilinguist – that should be fine. Thanks for being willing to review!

**Comment by jakevdp** [comment]
@whedon assign @desilinguist as reviewer

**Comment by jakevdp** [comment]
@whedon start review magic-word=bananas

**Comment by jakevdp** [comment]
@desilinguist – the review will take place over at #501. Thanks!
