### ISSUE TITLE
[REVIEW]: CheSweet: An application to predict glycan’s chemicals shifts

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#488]
**Submitting author:** @PabloGGaray (<a href="http://orcid.org/0000-0001-6604-0329">Pablo Garay</a>)
**Repository:** <a href="https://github.com/BIOS-IMASL/chesweet" target ="_blank">https://github.com/BIOS-IMASL/chesweet</a>
**Version:** 0.0.1
**Editor:** @arfon
**Reviewer:** @richardjgowers
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1157129" target="_blank">10.5281/zenodo.1157129</a>

## Status

[![status](https://joss.theoj.org/papers/5d4b945f9d9cbb2c0761c1b3a9d2cc66/status.svg)](https://joss.theoj.org/papers/5d4b945f9d9cbb2c0761c1b3a9d2cc66)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5d4b945f9d9cbb2c0761c1b3a9d2cc66"><img src="https://joss.theoj.org/papers/5d4b945f9d9cbb2c0761c1b3a9d2cc66/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5d4b945f9d9cbb2c0761c1b3a9d2cc66/status.svg)](https://joss.theoj.org/papers/5d4b945f9d9cbb2c0761c1b3a9d2cc66)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/BIOS-IMASL/chesweet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@richardjgowers, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BIOS-IMASL/chesweet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0.1)?
- [x] **Authorship:** Has the submitting author (@PabloGGaray) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @richardjgowers it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00488/joss.00488/10.21105.joss.00488.pdf
```

**Comment by PabloGGaray** [comment]
Hello @arfon, excuse me if this is not the place to do this question, but I have to add two line to the paper with the funding of the project, how I do that? I wait for the review or I can add that lines now?.
Thanks in advance and excuse me for the inconveniences.

**Comment by arfon** [comment]
@PabloGGaray - authors do this pretty regularly. I would suggest adding a new section header to the `paper.md` file:

```
# Funding

Anything you want to say about the funding source for the project...
```

**Comment by PabloGGaray** [comment]
I'll do that, thanks @arfon.

**Comment by PabloGGaray** [comment]
I made the change, I suppose you have to compile the `paper.md` again for the review, thanks.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00488/joss.00488/10.21105.joss.00488.pdf
```

**Comment by richardjgowers** [comment]
@arfon I've raised some issues on their repo, overall the paper + software looks good - I'd consider this minor revisions.

I also need to double check the maths of what's happening (functional claims of software, ie are the interpolations all behaving as they claim), but I can do this while they address the issues I've raised.

**Comment by arfon** [comment]
Great, thanks for the update @richardjgowers.

> I also need to double check the maths of what's happening (functional claims of software, ie are the interpolations all behaving as they claim), but I can do this while they address the issues I've raised.

👍 let me know when you're done and satisfied with the submission.

**Comment by arfon** [comment]
@richardjgowers - any update here?

**Comment by arfon** [comment]
@PabloGGaray - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by PabloGGaray** [comment]
Hi @arfon this is the DOI: 10.5281/zenodo.1157129
Just in case that not work correctly this is the [entry in zenodo](https://zenodo.org/record/1157129#.WmYupvZG2V4).
And thanks for your work @richardjgowers.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1157129 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1157129" target="_blank">10.5281/zenodo.1157129</a> is the archive.

**Comment by arfon** [comment]
@richardjgowers - many thanks for your review here ✨ 

@PabloGGaray - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00488 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00488/status.svg)](https://doi.org/10.21105/joss.00488)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00488/status.svg)](https://doi.org/10.21105/joss.00488)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by PabloGGaray** [comment]
Hello @arfon, Its possible make little changes in the paper?
We committed a little mistake in the affiliation information, the name of our institution is "Instituto de Matemática **Aplicada** San Luis", we omitted the "Aplicada" in the name by mistake.
And, if it is possible another change, in one reference the names of the authors don't appear, but we don't know the cause of this last problem.

**Comment by arfonsmith** [comment]
Sure. Please make the edits to the paper.md file and I can regenerate the
PDF.

**Comment by PabloGGaray** [comment]
We made the change @arfon, the paper.md is ready for the regeneration of the PDF.

**Comment by arfon** [comment]
Great. I've updated the paper now. It may take a few hours to show the updated version on the JOSS site as the papers are cached.

**Comment by PabloGGaray** [comment]
Perfect, thanks!
