### ISSUE TITLE
[REVIEW]: CoreRobotics: An object-oriented C++ library with cross-language wrappers for cross-platform robot control

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#489]
**Submitting author:** @CoreRobotics (<a href="http://orcid.org/0000-0003-1160-0426">Parker Owan</a>)
**Repository:** <a href="https://github.com/CoreRobotics/CoreRobotics" target ="_blank">https://github.com/CoreRobotics/CoreRobotics</a>
**Version:** v0.9.1
**Editor:** @danielskatz
**Reviewer:** @bmagyar @amjaeger17
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1166214" target="_blank">10.5281/zenodo.1166214</a>

## Status

[![status](https://joss.theoj.org/papers/627d0100471555a02730d75e626a85ab/status.svg)](https://joss.theoj.org/papers/627d0100471555a02730d75e626a85ab)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/627d0100471555a02730d75e626a85ab"><img src="https://joss.theoj.org/papers/627d0100471555a02730d75e626a85ab/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/627d0100471555a02730d75e626a85ab/status.svg)](https://joss.theoj.org/papers/627d0100471555a02730d75e626a85ab)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/CoreRobotics/CoreRobotics" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer 1 instructions & questions

@bmagyar, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CoreRobotics/CoreRobotics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.9.1)?
- [x] **Authorship:** Has the submitting author (@CoreRobotics) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

## Reviewer 2 instructions & questions

@amjaeger17, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CoreRobotics/CoreRobotics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.9.1)?
- [x] **Authorship:** Has the submitting author (@CoreRobotics) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @bmagyar it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #489 with the following error: 

 pandoc-citeproc: "stdin" (line 25, column 2):
unexpected "b"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by danielskatz** [comment]
@bmagyar & @amjaeger17 - this is ready to go

@amjaeger17 - you will have to accept the invitation to join the JOSS reviewers community: https://github.com/openjournals/joss-reviews/invitations before you will be able to check off items.  Once you do so, I will also assign you to the GitHub issue.

Please use the two checklists above (one for each of you) to carry out your reviews.

An informal guideline is that we would like your review in 2 weeks, but sooner (or later) are also ok.

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Please avoid lengthy details of difficulties in this review thread. Instead, please create a new issue in the target repository and link to those issues (especially acceptance-blockers) in this review thread. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

Any questions/concerns, please let me know.

Thanks!!

**Comment by CoreRobotics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by CoreRobotics** [comment]
Not sure what's going on with the pdf generator.  We have a pdf compiled from latex in the repository root, same content as the paper.md

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #489 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by arfon** [comment]
> Not sure what's going on with the pdf generator. We have a pdf compiled from latex in the repository root, same content as the paper.md

I found a weird edge-case in the code that I just fixed. Looks like the paper is compiling OK now.

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by amjaeger17** [comment]
@danielskatz for  documentation is there an expectation that there is a static/pregenerated api documentation? Or is a Doxygen config file acceptable? - Unclear from JOSS guidlines although most repos seem to have a link to docs.

**Comment by danielskatz** [comment]
Just to take one checkbox as an example:
 >Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

I would expect that if you check this box, there is either hand-written or auto-generated text in the repo or after the software is built that includes such examples.

Does that answer your question?

**Comment by danielskatz** [comment]
@amjaeger17 - How is your review coming along?  Any sticking points where I can help?

@bmagyar - It doesn't look like you've started your review. When do you expect to?

**Comment by bmagyar** [comment]
I remember ticking some boxes, perhaps they didn't get saved or I was a bit of a noob and ticked the boxes belonging to @amjaeger17 . I've actually opened a [bunch of issues](https://github.com/CoreRobotics/CoreRobotics/issues) already

**Comment by danielskatz** [comment]
Thanks - as you open issues, please put a note in this issue saying that you have done so, and ideally linking to those issues as appropriate, so a future reader (or the current editor) can look at this issue and understand the process of the overall review.

**Comment by bmagyar** [comment]
Good point. Here they come:

* https://github.com/CoreRobotics/CoreRobotics/issues/1
* https://github.com/CoreRobotics/CoreRobotics/issues/2
* https://github.com/CoreRobotics/CoreRobotics/issues/3
* https://github.com/CoreRobotics/CoreRobotics/issues/4
* https://github.com/CoreRobotics/CoreRobotics/issues/5
* https://github.com/CoreRobotics/CoreRobotics/issues/6
* https://github.com/CoreRobotics/CoreRobotics/issues/7

**Comment by danielskatz** [comment]
@amjaeger17 - If the checkboxes in your list weren't checked by you, they were accidentally checked by @bmagyar; feel free to uncheck them.

@CoreRobotics - Any news on the issues opened by @bmagyar ?

**Comment by CoreRobotics** [comment]
@danielskatz We are currently working to address some of the issues @bmagyar opened.  I do have a question... a couple of the issues seem to be preferential, e.g.: #7.  It is difficult at this stage for us to rename all the classes since this would require significant rework of existing projects using the library.  Is this a necessary fix?  Thanks for the clarity.

**Comment by CoreRobotics** [comment]
generate pdf

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by danielskatz** [comment]
your response to #7 seems ok to me - let's see what @bmagyar says

**Comment by bmagyar** [comment]
:+1: for bringing it up here as well, the reviewer guidelines are not specific about this.

While #7 is a pedantic issue, the rest I believe directly affect how others can use your library. Since the point of JOSS is to advocate re-using research code I think it is necessary that the code is brought in line with common design principles. 

Of course with open source projects everything is up for discussion.

**Comment by danielskatz** [comment]
Hi - can I get an update from everyone on this review?

@bmagyar, @amjaeger17, @CoreRobotics 

Can you each tell me if you are working on this, or waiting for someone else, and if the latter, who and what are you waiting for?

Thanks!

**Comment by bmagyar** [comment]
From the issues I've raised 3 are still outstanding.

**Comment by CoreRobotics** [comment]
We're almost finished with the most extensive of the issues - we're wrapping our test scripts with google test. There should be a pull request addressing the 3 outstanding issues in the next day or two.

**Comment by danielskatz** [comment]
@amjaeger17 - any news on your side?

**Comment by bmagyar** [comment]
One last issue from me about the DOI entries, everything else has green lights.

**Comment by CoreRobotics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by CoreRobotics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by danielskatz** [comment]
Thanks @bmagyar - it looks like your side of this is almost done, and the path is clear.

**Comment by danielskatz** [comment]
@amjaeger17 - again, any news on your side?

**Comment by CoreRobotics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by CoreRobotics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf
```

**Comment by danielskatz** [comment]
Since @amjaeger17 seems to be missing in action, we may proceed without him.  @amjaeger17 , last chance to speak up...

But I have a few small issues to bring up before we accept this, basically aimed at the fact that repo seems well-written for developers, but not fully for users.  I think the README needs:

- some of the paper content, such as a brief statement of what problems the software is designed to solve and who the target audience is would fit well in the description section
- in the building and compiling section, something that allows the user to know if the build is successful, such as an example that can be run, and what the results should be
- a section called support, that tells users how to report issues or problems with the software, or how else to seek support

**Comment by CoreRobotics** [comment]
Hi @danielskatz I've updated the README.md with commit [https://github.com/CoreRobotics/CoreRobotics/commit/04f3cb04593ba84e41a4515dae653baa4503d366](https://github.com/CoreRobotics/CoreRobotics/commit/04f3cb04593ba84e41a4515dae653baa4503d366)

- Parker

**Comment by danielskatz** [comment]
Thanks @CoreRobotics - this looks good.

And @bmagyar - thanks for your reviewing work.

@arfon, please move ahead with accepting this

**Comment by CoreRobotics** [comment]
@arfon OK thanks.  Is it ok for us to roll to v1.0 prior the Zenodo release DOI?  The version reviewed was 0.9.1 but the changes we've made from this review have prepared for release.

**Comment by arfon** [comment]
> @arfon OK thanks. Is it ok for us to roll to v1.0 prior the Zenodo release DOI? The version reviewed was 0.9.1 but the changes we've made from this review have prepared for release.

Yeah, I think that's fine.

**Comment by CoreRobotics** [comment]
@arfon we have updated v1.0.0 release at Zenodo [https://zenodo.org/record/1166214#.Wnj8IZM-dE4](https://zenodo.org/record/1166214#.Wnj8IZM-dE4)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1166214 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1166214" target="_blank">10.5281/zenodo.1166214</a> is the archive.

**Comment by arfon** [comment]
@bmagyar @amjaeger17 many thanks for your review here and to @danielskatz for editing this submission ✨ 

@CoreRobotics - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00489 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00489/status.svg)](https://doi.org/10.21105/joss.00489)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00489/status.svg)](https://doi.org/10.21105/joss.00489)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider either:

1. Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
2. Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
