### ISSUE TITLE
[REVIEW]: TPIB - Transformation Peak Iterative Baseline

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#49]
**Submitting author:** @drcassar (<a href="http://orcid.org/0000-0001-6472-2780">Daniel Cassar</a>)
**Repository:** <a href="https://github.com/drcassar/TPIB" target ="_blank">https://github.com/drcassar/TPIB</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewer:** @nicoguaro 
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/c33ddde3bc1bedc615cbdc99d656c7e5/status.svg)](http://joss.theoj.org/papers/c33ddde3bc1bedc615cbdc99d656c7e5)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c33ddde3bc1bedc615cbdc99d656c7e5"><img src="http://joss.theoj.org/papers/c33ddde3bc1bedc615cbdc99d656c7e5/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c33ddde3bc1bedc615cbdc99d656c7e5/status.svg)](http://joss.theoj.org/papers/c33ddde3bc1bedc615cbdc99d656c7e5)
```
### Conflict of interest
- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/drcassar/TPIB">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
### Functionality
- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper

Paper PDF: [10.21105.joss.00049.pdf](https://github.com/openjournals/joss-reviews/files/415787/10.21105.joss.00049.pdf)
- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by pjotrp** [comment]
Someone with a physics/chemical background can pick this up

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://gist.github.com/arfon/5317c568cb32c7b917fea3c13958131d

**Comment by kyleniemeyer** [comment]
Hi @nicoguaro & @khinsen: would either of you be able to review this submission?

**Comment by arfon** [comment]
@kyleniemeyer heads up that you don't need to do the `@whedon start review` step on this issue as all of the review metadata is already here at the top of the thread.

**Comment by kyleniemeyer** [comment]
@arfon ah, this one came before the new system, right? I'll just manually change the label once the review starts.

**Comment by arfon** [comment]
> @arfon ah, this one came before the new system, right? I'll just manually change the label once the review starts.

Yep. Still do the `@whedon assign @username as reviewer` though as this gives the reviewer permissions to update the checklist on the issue.

**Comment by arfon** [comment]
👋 @kyleniemeyer any luck finding a reviewer for this one?

**Comment by nicoguaro** [comment]
@kyleniemeyer, I didn't notice that you asked me on this one.

This package consists of a single Python file. I'm not saying it because that's something wrong or right. But the question rises, is there a "minimum"? Or the scientific relevance of the software is what determine it?

It does not have installation instructions, tests, nor contribution guidelines. I think that the folder structure can be improved as well. A better statement of need would be good as well, since I suppose that it can be used in more general contexts than the example provided.

**Comment by drcassar** [comment]
Hello @nicoguaro, thanks for pointing out ways to improve the submission. You see, this is my first time uploading a code to github so I'm still not familiar with all the good practices. I'll look into other accepted  JOSS submissions and check how to improve mine following your suggestions.
The statement of need is focused on differential thermoanalysis measurements. It's one of the most used characterization techniques in the field of materials science. I too suppose it may be useful in other contexts, but I would like to stress that this is not a small field and the reproductibility problem mentioned in the statement (due to the closed nature of various commercial software) is an actual problem.
Please, let me know if it is not OK for me to be posting here within review process.

**Comment by kyleniemeyer** [comment]
Hi @drcassar, this is a perfectly fine place for this discussion. I agree that you should follow @nicoguaro's suggestions about structuring the repo (especially such that it can be installed/distributed as a package); you can look at other Python packages published in JOSS as examples, or use these guidelines: http://docs.python-guide.org/en/latest/writing/structure/

In addition, there are some suggestions about tests, contribution guidelines, and explanation of how to run the examples. I would work towards making these changes—please let us know when it's ready  to take another look. 

@nicoguaro No problem, thanks for looking at it. We don't have a minimum requirement in terms of what is suitable; if the software has a research application and is feature-complete, then it should be acceptable. This package certainly seems focused on one particular technique, but that is fine.

**Comment by nicoguaro** [comment]
@kyleniemeyer, I agree. I just wanted to point it out, some of those points are still grey for me.

@drcassar, can the the software be used for some other measurements and not just differential thermoanalysis measurements? Let's say... some spectral techniques.

**Comment by drcassar** [comment]
Hi @kyleniemeyer, and thanks for the info. I'll read more and update my submission, letting you guys know when I finish the update. Right now I'm studying for a very tough exam, so I'll probably not be able to fix this too quickly. Let me know if this is a problem and I can perhaps remove the submission and try again later.
Good suggestion @nicoguaro, I'll discuss with some experts in this field to see if it could be useful.
Cheers

**Comment by kyleniemeyer** [comment]
@drcassar no problem on a delay, we will keep this review issue open until the next version is ready. Just let us know!

**Comment by kyleniemeyer** [comment]
@whedon assign @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nicoguaro

**Comment by kyleniemeyer** [comment]
Hi @drcassar! It's been a few months, so I just wanted to check in and see if you've been able to work on those changes.

**Comment by drcassar** [comment]
Hi @kyleniemeyer. I'm sorry but I'm afraid I'm able to tackle this one right now. Is is possible for me to close/remove the submission? Thanks and all the best.

**Comment by kyleniemeyer** [comment]
@drcassar there is no time limit on JOSS reviews—we can leave this review thread open until you or a collaborator are able to make the changes.

**Comment by kyleniemeyer** [comment]
Hi @drcassar, just wanted to check in—if you don't think you'll ever be able to make these changes, then we can withdraw this submission, but there is some light on the horizon, then we can keep it open.

**Comment by drcassar** [comment]
Hi @kyleniemeyer. Thank you for your patience. Please, withdraw this submission. I'm thinking about going back to this idea with a different scope in the future (and maybe resubmitting, if possible). All the best.

**Comment by kyleniemeyer** [comment]
@drcassar OK, thanks!

@arfon can you withdraw this submission?

**Comment by arfon** [comment]
> @arfon can you withdraw this submission?

Done.
