### ISSUE TITLE
[REVIEW]: pyodesys: Straightforward numerical integration of ODE systems from Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#490]
**Submitting author:** @bjodah (<a href="http://orcid.org/0000-0003-0596-0222">Björn Dahlgren</a>)
**Repository:** <a href="https://github.com/bjodah/pyodesys" target ="_blank">https://github.com/bjodah/pyodesys</a>
**Version:** v0.11.5
**Editor:** @arfon
**Reviewer:** @arghdos
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1134944" target="_blank">10.5281/zenodo.1134944</a>

## Status

[![status](https://joss.theoj.org/papers/e6e7b06e19f2c671608003b1f1cd3aa6/status.svg)](https://joss.theoj.org/papers/e6e7b06e19f2c671608003b1f1cd3aa6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e6e7b06e19f2c671608003b1f1cd3aa6"><img src="https://joss.theoj.org/papers/e6e7b06e19f2c671608003b1f1cd3aa6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e6e7b06e19f2c671608003b1f1cd3aa6/status.svg)](https://joss.theoj.org/papers/e6e7b06e19f2c671608003b1f1cd3aa6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bjodah/pyodesys" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arghdos, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bjodah/pyodesys">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.11.5)?
- [x] **Authorship:** Has the submitting author (@bjodah) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00490/joss.00490/10.21105.joss.00490.pdf
```

**Comment by bjodah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00490/joss.00490/10.21105.joss.00490.pdf
```

**Comment by arfon** [comment]
@arghdos - how are you getting along here?

**Comment by arghdos** [comment]
@arfon I've been working with @bjodah to clean up the installation instructions in the documentation (I ran into some issues while installing / testing).  Once we have that finalized I expect I'll be finished shortly thereafter

**Comment by arghdos** [comment]
@bjodah looks great! The only remaining issue is a missing contribution guidelines -- in particular, the sympy integration allowing change of variables / reformulation, and automatic analytical Jacobian determination is _very_ cool, great work

**Comment by arghdos** [comment]
@arfon everything looks good on my end

**Comment by arfon** [comment]
> @arfon everything looks good on my end

Excellent!

@bjodah - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bjodah** [comment]
@arfon Thanks,

I've tagged a new patch version (v0.11.6) including the changes suggested by arghdos.
The DOI for the archive of this version is: [10.5281/zenodo.1134944](http://dx.doi.org/10.5281/zenodo.1134944)

**Comment by bjodah** [comment]
...and I just updated the paper meta-data accordingly:
https://github.com/bjodah/pyodesys/commit/92575ddf77ad795247a0f890319be0e94beacc45

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1134944 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1134944" target="_blank">10.5281/zenodo.1134944</a> is the archive.

**Comment by arfon** [comment]
@arghdos - many thanks for your review here ✨ 

@bjodah - your paper is now accepted into JOSS and your paper DOI is https://doi.org/10.21105/joss.00490 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00490/status.svg)](https://doi.org/10.21105/joss.00490)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00490/status.svg)](https://doi.org/10.21105/joss.00490)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
