### ISSUE TITLE
[PRE REVIEW]: Vizualizing DNA sequence co-linearity with xmatchview

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#491]
**Submitting author:** @warrenlr (<a href="http://orcid.org/0000-0002-9890-2293">Rene L. Warren</a>)
**Repository:** <a href="https://github.com/warrenlr/xmatchview" target ="_blank">https://github.com/warrenlr/xmatchview</a>
**Version:** v0.3
**Editor:** @mgymrek
**Reviewer:** @nmmsv

**Author instructions**

Thanks for submitting your paper to JOSS @warrenlr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@warrenlr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/author.rb:32:in `block in build_affiliation_string': Problem with affiliations for Rene L Warren, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/author.rb:31:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/author.rb:31:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/author.rb:11:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:97:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:97:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:95:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:95:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:76:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:75:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@warrenlr - looks like there's a minor issue with your `paper.md` file, I've fixed it up here: https://github.com/warrenlr/xmatchview/pull/1

**Comment by warrenlr** [comment]
thank you @arfon, I merged your fixed version

**Comment by warrenlr** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 pandoc-citeproc: "stdin" (line 73, column 2):
unexpected "a"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 pandoc-citeproc: "stdin" (line 73, column 2):
unexpected "a"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 pandoc-citeproc: "stdin" (line 73, column 2):
unexpected "a"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@warrenlr - there were a couple more issues with your paper and bibtex. I've got the paper to compile cleanly with these changes: https://github.com/warrenlr/xmatchview/pull/2

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 pandoc-citeproc: reference hubbart2002 not found
pandoc-citeproc: reference D not found
[pandoc warning] Unable to convert `/tmp/tex2pdf.394/4e1b05497a8b855e0a52de31d734c86e5d9d8b29.shtml' for use with pdflatex.
[pandoc warning] Unable to convert `/tmp/tex2pdf.394/dda1a7c356977288da99271dc38375c9349fabbf.shtml' for use with pdflatex.
[pandoc warning] Unable to convert `/tmp/tex2pdf.394/4f181ff4b72ee8962b2bcfeee90e1984016e3fbe.shtml' for use with pdflatex.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.394/4e1b05497a8
b855e0a52de31d734c86e5d9d8b29.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.255 ...497a8b855e0a52de31d734c86e5d9d8b29.shtml}

pandoc: Error producing PDF
Looks like we failed to compile the PDF

```

**Comment by warrenlr** [comment]
oh, great, just saw your message.. will merge this back

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00491/joss.00491/10.21105.joss.00491.pdf
```

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by warrenlr** [comment]
hello @arfon, I want to recompile the pdf. It seems stuck.

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
> @whedon generate pdf

@warrenlr - it looks like this is failing as the PDF is large and we can't use the GitHub API in the way I'm currently doing with the Whedon bot.

Here is the compiled PDF:

[10.21105.joss.00491.pdf](https://github.com/openjournals/joss-reviews/files/1543159/10.21105.joss.00491.pdf)

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 pandoc: 10.21105.joss.00491.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

```

**Comment by warrenlr** [comment]
great.. looks good except for possible issue with the Coombe et al citation and reference.  I have re-committed a version with minor edits.

**Comment by warrenlr** [comment]
otherwise, it's good to go for review.

**Comment by warrenlr** [comment]
I will attempt to rebuild one last time  @arfon.

@whedon generate pdf

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@warrenlr - I've compiled this again locally [10.21105.joss.00491.pdf](https://github.com/openjournals/joss-reviews/files/1543202/10.21105.joss.00491.pdf)

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 pandoc: 10.21105.joss.00491.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

```

**Comment by warrenlr** [comment]
thank you @arfon. Still not sure why the Coomb reference is messed up.  The BibTex look ok to me

**Comment by arfon** [comment]
@warrenlr - What's wrong with the way this is formatted?

**Comment by warrenlr** [comment]
it shows:
Coombe, Rene L. AND Jackman, Lauren AND Warren. 2016. “Assembly of the Com- plete Sitka Spruce Chloroplast Genome Using 10x Genomics Gemcode Sequencing Data.” PLOS ONE 11 (9). Public Library of Science: 1–13. doi:10.1371/journal.pone.0163059.

but should be:

Coombe, Lauren AND Warren Rene L. AND Jackman, Shaun AND Yang, Chen AND Vandervalk, Benjamin P. AND Moore, Richard A. AND Pleasance, Stephen AND Coope, Robin J. AND Bohlmann, Joerg AND Holt, Robert A. AND Jones, Steven J. M. AND Birol, Inanc. 2016. “Assembly of the Complete Sitka Spruce Chloroplast Genome Using 10x Genomics Gemcode Sequencing Data.” PLOS ONE 11 (9). Public Library of Science: 1–13. doi:10.1371/journal.pone.0163059.

The text citation also only lists the first author "Coombe 2016" but should be "Coombe et al. 2016".  I have streamlined the bibtex somewhat, maybe a new build will fix it.

**Comment by arfon** [comment]
Does this look better? [10.21105.joss.00491.pdf](https://github.com/openjournals/joss-reviews/files/1543250/10.21105.joss.00491.pdf)

**Comment by warrenlr** [comment]
yes, that works @arfon. ready to proceed to next steps.

**Comment by arfon** [comment]
@warrenlr - this is the fix I made: https://github.com/warrenlr/xmatchview/pull/3

**Comment by warrenlr** [comment]
@arfon, I have made minor edits to the figures.  Could we please rebuild?  Thanks!

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00491/joss.00491/10.21105.joss.00491.pdf
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00491/joss.00491/10.21105.joss.00491.pdf
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00491/joss.00491/10.21105.joss.00491.pdf
```

**Comment by arfon** [comment]
@pjotrp @mgymrek @biorelated - would one of you be willing to edit this submission for JOSS?

**Comment by warrenlr** [comment]
just noticed duplicated text. I have removed it and I'm now rebuilding.

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00491/joss.00491/10.21105.joss.00491.pdf
```

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00491/joss.00491/10.21105.joss.00491.pdf
```

**Comment by warrenlr** [comment]
last version before review.  I made change to fig3 to best show the utility of the tool

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 Killed
Looks like we failed to compile the PDF

```

**Comment by warrenlr** [comment]
this is a big file (fig 3 is now several Mb)

**Comment by warrenlr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #491 with the following error: 

 Killed
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
> this is a big file (fig 3 is now several Mb)

I think you've broken @whedon again :-). If the PDF takes longer to generate than 30 seconds the processing job will be killed by Heroku (where we host our servers). I've generated the PDF locally:
[10.21105.joss.00491.pdf](https://github.com/openjournals/joss-reviews/files/1548851/10.21105.joss.00491.pdf)

**Comment by warrenlr** [comment]
I'm so sorry!  I won't re-generate, this looks good to me.

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
Hi @warrenlr, thanks for the submission. I wanted to ask if you have any reviewers in mind you'd like to suggest?

**Comment by warrenlr** [comment]
I am afraid that I don't have any reviewers in mind. I was looking at the list (https://github.com/openjournals/joss/blob/master/docs/reviewers.csv). Python/bioinformatics + genome experts will do (eg. ctb, Genomematt, rmflight, luizirber). Thank you fo handling the submission, @mgymrek.
Rene

**Comment by mgymrek** [comment]
No worries, thanks for letting me know. I'll get on finding one.

**Comment by mgymrek** [comment]
@whedon assign @nmmsv as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nmmsv

**Comment by mgymrek** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/497. Feel free to close this issue now!
