### ISSUE TITLE
[PRE REVIEW]: nlsLoop - An R package Providing Methods for Finding the Best Estimated Fits for Non-Least Squares Regression over the Level of a Factor

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#492]
**Submitting author:** @padpadpadpad (<a href="http://orcid.org/0000-0001-6799-9670">Daniel Padfield</a>)
**Repository:** <a href="https://github.com/padpadpadpad/nlsLoop" target ="_blank">https://github.com/padpadpadpad/nlsLoop</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @padpadpadpad. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@padpadpadpad if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #492 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #492 with the following error: 

 pandoc-citeproc: Could not find paper.bib
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Pandoc.hs:224:39 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Pandoc
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
> `pandoc-citeproc: Could not find paper.bib`

@padpadpadpad  - Could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by padpadpadpad** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by padpadpadpad** [comment]
Hello @arfon. I am super sorry about this. I had a somewhat eureka moment the night after submitting this package that I could do it a completely different way. This is after doing it the same way for the last 2 years and tidying up the GitHub repository for a submission to JOSS. Could I please withdraw the submission and come back to you in the near future.

Sorry for wasting your time.
Many thanks.
Daniel Padfield

**Comment by arfon** [comment]
@padpadpadpad - sure thing. No problem. I'll withdraw this submission on your behalf :-)

**Comment by padpadpadpad** [comment]
Thank you very much.
