### ISSUE TITLE
[REVIEW]: PyTransport: A Python package for the calculation of inﬂationary correlation functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#494]
**Submitting author:** @jronayne (<a href="http://orcid.org/0000-0001-6464-6466">John Ronayne</a>)
**Repository:** <a href="https://github.com/jronayne/PyTransport" target ="_blank">https://github.com/jronayne/PyTransport</a>
**Version:** v2.0.0
**Editor:** @arfon
**Reviewer:** @joezuntz
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1209239" target="_blank">10.5281/zenodo.1209239</a>

## Status

[![status](https://joss.theoj.org/papers/039d064ca4a3d2103fe06ac497b0645c/status.svg)](https://joss.theoj.org/papers/039d064ca4a3d2103fe06ac497b0645c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/039d064ca4a3d2103fe06ac497b0645c"><img src="https://joss.theoj.org/papers/039d064ca4a3d2103fe06ac497b0645c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/039d064ca4a3d2103fe06ac497b0645c/status.svg)](https://joss.theoj.org/papers/039d064ca4a3d2103fe06ac497b0645c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jronayne/PyTransport" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@joezuntz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jronayne/PyTransport">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.0.0)?
- [x] **Authorship:** Has the submitting author (@jronayne) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @joezuntz it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00494/joss.00494/10.21105.joss.00494.pdf
```

**Comment by joezuntz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
👋 @joezuntz - how are you getting along here?

**Comment by joezuntz** [comment]
I've hit an installation issue that I've listed here: https://github.com/jronayne/PyTransport/issues/3
so I can't yet comment on the functionality.  I'll look at those parts of the docs that I can at this point.

**Comment by joezuntz** [comment]
The code is also missing automated tests: https://github.com/jronayne/PyTransport/issues/4

**Comment by joezuntz** [comment]
I've asked for a contributions statement: https://github.com/jronayne/PyTransport/issues/5

**Comment by joezuntz** [comment]
@arfon Can you clarify about the DOIs requirement - the bibtex file lists them, but do you want them somewhere more obvious than that?  e.g. in the paper PDF itself?

**Comment by arfon** [comment]
> @arfon Can you clarify about the DOIs requirement - the bibtex file lists them, but do you want them somewhere more obvious than that? e.g. in the paper PDF itself?

Basically we just want it present in the bibtex if there is a DOI available. That way we can generate better Crossref metadata when we publish the JOSS paper.

**Comment by arfon** [comment]
@jronayne - please make sure you've addressed @joezuntz's feedback above.

**Comment by jronayne** [comment]
@afron @joezuntz - HI, apologies for the delay in my response. I have hopefully addressed all the feedback above so that you may continue the review.

**Comment by joezuntz** [comment]
@jronayne - many apologies for the long delay before getting back onto this.  

I think this is nearly ready, just a few more issues that I'll open on the main repo.

**Comment by joezuntz** [comment]
Although some of the code methodology (such as its installation process) is non-standard for general software, the differences are within the norm for scientific software designed to support further code development by users.  Everything else is cleanly ticked off, so I'm happy to accept now.

**Comment by arfon** [comment]
👍 thanks @joezuntz.

@jronayne - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by arfon** [comment]
*bump* @jronayne - please go ahead and make an archive of this software so we can proceed with accepting your paper.

**Comment by jronayne** [comment]
@arfon - Archive has been [created](https://zenodo.org/record/1209239#.WrufqrQdLzI) with the reviesed sofware on Zenodo.
DOI:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1209239.svg)](https://doi.org/10.5281/zenodo.1209239)

Sorry for the delay and thanks again.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1209239 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1209239" target="_blank">10.5281/zenodo.1209239</a> is the archive.

**Comment by arfon** [comment]
@joezuntz - many thanks for your review here ✨ 

@jronayne - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00494 ⚡️:rocket: :boom:x

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00494/status.svg)](https://doi.org/10.21105/joss.00494)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00494/status.svg)](https://doi.org/10.21105/joss.00494)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by jronayne** [comment]
@joezuntz @arfon - Thank you both for your patience and reviewing.
