### ISSUE TITLE
[PRE REVIEW]: QPFA: A program for Estimating the Critical Moment and Associated Uncertainty in a Petroleum System

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#495]
**Submitting author:** @AdeBytes (<a href="http://orcid.org/0000-0002-9824-4358">Adewale Amosu</a>)
**Repository:** <a href="https://github.com/AdeBytes/QPFA_Package.git" target ="_blank">https://github.com/AdeBytes/QPFA_Package.git</a>
**Version:** v1.0
**Editor:** @lheagy
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @AdeBytes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@AdeBytes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00495/joss.00495/10.21105.joss.00495.pdf
```

**Comment by lheagy** [comment]
👋 @arfon, I can take this one

**Comment by arfon** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by lheagy** [comment]
Hi @AdeBytes, thanks for your submission. After review the editorial board has determined that your submission does not meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, this submission falls under the 'Minor utility package' category. 

Please don't hesitate to reach out for further clarification on the submission requirements. You can also submit [a pre-submission inquiry](https://github.com/openjournals/joss/issues) to ask questions regarding the submission and if is a fit for JOSS.

**Comment by AdeBytes** [comment]
Hi,
I believe there might be an error.
There are two separate submissions. This submission is a Matlab package for
calculating the critical moment in a petroleum system. The second one is a
python package that may fall under "minor utility clause".

The Matlab package QPFA however is a new software package that calculates
the critical moment in a petroleum system. Although the definition of the
critical moment is defined as the moment in time with the highest
probability for generation, migration and accumulation, it is usually
chosen qualitatively. The program calculate the critical moment
quantitatively. I don't believe this falls under the category of a minor
utility. The critical moment is the moment in which the stratigraphic and
geographical extent (hence the volume) of a petroleum system are drawn.
Hence a wrong estimate of the critical moment will lead to a wrong estimate
of hydrocarbon volume. The wrong volume will lead to wrong exploration
decisions by petroleum exploration companies.

This submission is different from the Python package, however both
submissions seems to have been closed simultaneously as one submission.

Can you kindly look into this.
Best Regards
Adewale

**Comment by lheagy** [comment]
Hi @AdeBytes, 

Thanks for your message. We did intentionally close both submissions. The editorial board has reviewed this submission and determined that it does not meets the [submission requirements](http://joss.theoj.org/about#submission_requirements). 

The GUI and QPFA function appears to be more of a product for a utility function. It is not clear that it satisfies:  
- Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)
- Should be feature complete (no half-baked solutions)
- Minor, 'utility' packages, including 'thin' API clients are not acceptable 

As a result, we've decided that it is not in-scope for JOSS.

**Comment by AdeBytes** [comment]
Hi @lheagy

The QPFA program answers the following research question: How can the
critical moment in a petroleum system be calculated? In addition, it
answers another question: how much uncertainty is associated with the
critical moment.
These are valid research questions that many petroleum geophysicists and
geologists attempt to answer everyday. The critical moment is an important
concept that has to be found in any study of a petroleum system. Like I
mentioned earlier: The critical moment is the moment in which the
stratigraphic and geographical extent (hence the volume) of a petroleum
system are determined. Hence a wrong estimate of the critical moment will
lead to a wrong estimate of hydrocarbon volume. The wrong volume will lead
to wrong exploration decisions by petroleum exploration companies; this is
also why it is important to determine the uncertainty in the determination
of the critical moment. The QPFA program is designed to addresses this
problem and make the determination of the critical moment faster and
easier.
 Examples of papers discussing the importance are listed below:


   1.

   Magoon, L. B., 1992, Petroleum system: Status of research and meth- ods,
   United States Geological Survey Bulletin, v. 20, no. 7, p. 1.
   2.

   Magoon, L. B., and W. G. Dow, 1994, The petroleum system, in L. B.
   Magoon and W. G. Dow, eds., The petroleum system− from source to trap:
   AAPG Memoir 60, p. 3 − 24.
   3.

   Peters, K., Schenck, O. and Wygrala, B., 2009, Exploration paradigm
   shift: the dynamic petroleum system. Swiss Bulletin Angew Geology, v. 14,
   no. 1, p. 65−71.
   4.

   Bird, Kenneth, J., 1994, Bird. Ellesmerian (!) petroleum system, north
   slope of Alaska, USA, in L. B. Magoon, and W. G. Dow, eds., The petroleum
   system− from source to trap: AAPG Memoir 60, p. 339 − 358.


Based on the above,  the program does meet the three requirements you
mentioned.
I do appreciate your time and effort in reviewing.
Sincerely.

**Comment by AdeBytes** [comment]
Hi @lheagy

The QPFA program answers the following research question: How can the
critical moment in a petroleum system be calculated? In addition, it
answers another question: how much uncertainty is associated with the
critical moment.
These are valid research questions that many petroleum geophysicists and
geologists attempt to answer everyday. The critical moment is an important
concept that has to be found in any study of a petroleum system. Like I
mentioned earlier: The critical moment is the moment in which the
stratigraphic and geographical extent (hence the volume) of a petroleum
system are determined. Hence a wrong estimate of the critical moment will
lead to a wrong estimate of hydrocarbon volume. The wrong volume will lead
to wrong exploration decisions by petroleum exploration companies; this is
also why it is important to determine the uncertainty in the determination
of the critical moment. The QPFA program is designed to addresses this
problem and make the determination of the critical moment faster and
easier.
 Examples of papers discussing the importance are listed below:


   1.

   Magoon, L. B., 1992, Petroleum system: Status of research and meth- ods,
   United States Geological Survey Bulletin, v. 20, no. 7, p. 1.
   2.

   Magoon, L. B., and W. G. Dow, 1994, The petroleum system, in L. B.
   Magoon and W. G. Dow, eds., The petroleum system− from source to trap:
   AAPG Memoir 60, p. 3 − 24.
   3.

   Peters, K., Schenck, O. and Wygrala, B., 2009, Exploration paradigm
   shift: the dynamic petroleum system. Swiss Bulletin Angew Geology, v. 14,
   no. 1, p. 65−71.
   4.

   Bird, Kenneth, J., 1994, Bird. Ellesmerian (!) petroleum system, north
   slope of Alaska, USA, in L. B. Magoon, and W. G. Dow, eds., The petroleum
   system− from source to trap: AAPG Memoir 60, p. 339 − 358.


Based on the above,  the program does meet the three requirements you
mentioned.
I do appreciate your time and effort in reviewing.
Sincerely.

**Comment by lheagy** [comment]
Hi @WalBytes,  

Have you considered submitting to the [Leading Edge Tutorials](https://library.seg.org/journal/leedff) (their github repo is: https://github.com/seg/tutorials)? This is another avenue for publishing software along with a short write-up in the geosciences and it might be a better fit for publishing QPFA. 

The editorial board at JOSS has reviewed the software, and the scope of QPFA is not a fit for JOSS.

**Comment by AdeBytes** [comment]
Thank you for your suggestion. Again, the three reasons which you have
given have not been successfully justified.
My previous posting clearly shows that the program does not fall in the
category of minor utility package.
The product of the program is an events chart that contains the critical
moment. This is a publishable vital research product that is required in
the description of any petroleum system.

**Comment by arfon** [comment]
Hi @AdeBytes, the editorial board has made its final decision here. Please seek other venues for publishing this work.
