### ISSUE TITLE
[PRE REVIEW]: PyLogFinder: A Python Program for Graphical Geophysical Log Selection

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#496]
**Submitting author:** @AdeBytes (<a href="http://orcid.org/0000-0002-9824-4358">Adewale Amosu</a>)
**Repository:** <a href="https://github.com/AdeBytes/PyLogFinder_Package.git" target ="_blank">https://github.com/AdeBytes/PyLogFinder_Package.git</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @AdeBytes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@AdeBytes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00496/joss.00496/10.21105.joss.00496.pdf
```

**Comment by lheagy** [comment]
Hi again @AdeBytes, thanks also for this submission. Similar to #495, the editorial board has determined that your submission does not meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). This submission falls under the 'Minor utility package' category. 

Please don't hesitate to reach out for further clarification on the submission requirements. You can also submit [a pre-submission inquiry](https://github.com/openjournals/joss/issues) to ask questions regarding the submission and if is a fit for JOSS.
