### ISSUE TITLE
[PRE REVIEW]: Aronnax: An idealised isopycnal ocean model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#498]
**Submitting author:** @edoddridge (<a href="http://orcid.org/0000-0002-6097-5729">Edward Doddridge</a>)
**Repository:** <a href="https://github.com/edoddridge/aronnax" target ="_blank">https://github.com/edoddridge/aronnax</a>
**Version:** 0.1.0
**Editor:** @kyleniemeyer
**Reviewer:** @dvalters

**Author instructions**

Thanks for submitting your paper to JOSS @edoddridge. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@edoddridge if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #498 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:75:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon do you know what is wrong here?

**Comment by Kevin-Mattheus-Moerman** [comment]
@wkearn do you know if you or one of your colleagues would be interested in reviewing this submission?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00498/joss.00498/10.21105.joss.00498.pdf
```

**Comment by wkearn** [comment]
I could review this submission, but it's not exactly my specialty. I'll try to think of someone more well-versed in these kinds of models and let you know.

**Comment by dvalters** [comment]
I could review this, although I'm not specifically an ocean modeller (more atmospheric/NWP), but happy to review Fortran/Python/numerical modelling in general.

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman - would you be willing to edit this submission?

**Comment by kyleniemeyer** [comment]
@arfon I can take this one.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @dvalters—are you still willing to review this? I will also try to get someone more on the ocean side of things.

**Comment by dvalters** [comment]
Hi @kyleniemeyer - yep I can review

**Comment by edoddridge** [comment]
Hi all, just wondering if there's anything you need me to do for this.

**Comment by kyleniemeyer** [comment]
Hi @edoddridge sorry for the delay, I was planning to get a second reviewer with closer expertise in ocean modeling—will wrap that up shortly.

**Comment by edoddridge** [comment]
No worries. I was just making sure that I wasn't causing the delay. If you haven't found anyone yet, the [stargazers](https://github.com/edoddridge/aronnax/stargazers) might be a useful list.

**Comment by kyleniemeyer** [comment]
Alright so @rabernat has agreed to serve as a secondary reviewer—thanks! (https://twitter.com/rabernat/status/966062926351265792)

I will advance this to the next steps now.

**Comment by kyleniemeyer** [comment]
@whedon assign @dvalters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by kyleniemeyer** [comment]
@dvalters @rabernat you will both serve as reviewers, but our system only supports one "official" reviewer right now.

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/592. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
Moving over to the actual review in #592 now, and closing this.
