### ISSUE TITLE
[PRE REVIEW]: Pymagicc: A Python wrapper for the simple climate model MAGICC

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#502]
**Submitting author:** @rgieseke (<a href="http://orcid.org/0000-0002-1236-5109">Robert Gieseke</a>)
**Repository:** <a href="https://github.com/openclimatedata/pymagicc" target ="_blank">https://github.com/openclimatedata/pymagicc</a>
**Version:** v1.0.1
**Editor:** @arfon
**Reviewer:** @sgrieve

**Author instructions**

Thanks for submitting your paper to JOSS @rgieseke. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rgieseke if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00502/joss.00502/10.21105.joss.00502.pdf
```

**Comment by rgieseke** [comment]
Thanks for opening this pre-review issue!

As reviewers maybe @sgrieve (who reviewed the similar Pyhector submission) or @scollis (having "Climate Science" listed as a domain) would be interested?

From outside the JOSS reviewer pool, maybe @DamienIrving (as a Python and Notebook using climate scientist)?

**Comment by arfon** [comment]
Thanks @rgieseke. As this is somewhat outside of my domain expertise, I'd like to find two reviewers for this submission.

@sgrieve @scollis @DamienIrving - would any of you be willing to review this submission for JOSS? You can read more about the process here http://joss.theoj.org/about#reviewer_guidelines

**Comment by rgieseke** [comment]
@arfon Some minor technical editorial questions:

The Meinshausen2011 reference should have MAGICC6 uppercased. In my local setup (Linux, TeX Live 2016) it looks correct. In the version rendered above it is "Magicc6", even though it is "{MAGICC6}" in the BibTex file. (On my Mac at home I had the same issue, but would need to check what's running there.) 

Where can I find the setup that's used for compiling the JOSS papers to try to debug this?

Post-submission I've a tagged a 1.0.1 release which includes the latest version of the `f90nml` dependency. I had contacted its author and it now also has a Zenodo doi and is cited.

Could you please update the version number?

Many thanks!

**Comment by arfon** [comment]
@rgieseke - this is the Pandoc command we're running: https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb#L101-L122

If you are up for a (small?) challenge, you could install the Whedon gem from GitHub and compile the paper using the gem.

Alternatively (and I'm completely OK with this if you are), feel free to make edits and ask @whedon to recompile the paper here with the command `@whedon generate pdf`.

**Comment by scollis** [comment]
Hey @arfon This is super interesting but the one issue is I am not a windows user and do not have access to a windows system. I also do not use Brew on MacOS. I could probably help in a pinch but I would rather leave it to @sgrieve or @DamienIrving

**Comment by rgieseke** [comment]
@scollis Thanks for the quick reply!

I don't think it's required for reviewers to test all platforms.
The idea of Pymagicc is to make the (Windows-only) MAGICC binary available on Linux, macOS and Linux. It should also work with "port" installed Wine or with manually installing Wine on macOS.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #502 with the following error: 

 --smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
--latex-engine has been removed.  Use --pdf-engine instead.
Try pandoc --help for more information.
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by sgrieve** [comment]
Hi @arfon, I'm happy to review this, it looks interesting! I'm swamped with teaching at the moment, so I wouldn't be able to look at this for at least a week. Will that be ok?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00502/joss.00502/10.21105.joss.00502.pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00502/joss.00502/10.21105.joss.00502.pdf
```

**Comment by arfon** [comment]
> Hi @arfon, I'm happy to review this, it looks interesting! I'm swamped with teaching at the moment, so I wouldn't be able to look at this for at least a week. Will that be ok?

@sgrieve - yeah, that would be great.

> The idea of Pymagicc is to make the (Windows-only) MAGICC binary available on Linux, macOS and Linux. It should also work with "port" installed Wine or with manually installing Wine on macOS.

@scollis - what do you think about @rgieseke's [comment](https://github.com/openjournals/joss-reviews/issues/502#issuecomment-351413826)?

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00502/joss.00502/10.21105.joss.00502.pdf
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00502/joss.00502/10.21105.joss.00502.pdf
```

**Comment by sgrieve** [comment]
Great! I look forward to working on this next week! 🚀

**Comment by arfon** [comment]
@whedon assign @sgrieve as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sgrieve

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/516. Feel free to close this issue now!

**Comment by arfon** [comment]
@sgrieve - please head over the #516 to carry out the actual review.
