### ISSUE TITLE
[PRE REVIEW]: ivporbit:An R package to estimate the instrumental variables probit model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#503]
**Submitting author:** @zedtaha (<a href="http://orcid.org/0000-0002-4488-5774">zaghdoudi Taha</a>)
**Repository:** <a href="https://github.com/zedtaha/ivprobit-1.0" target ="_blank">https://github.com/zedtaha/ivprobit-1.0</a>
**Version:** v1.0
**Editor:** @leeper
**Reviewer:** @justinesarey

**Author instructions**

Thanks for submitting your paper to JOSS @zedtaha. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zedtaha if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #503 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:86:in `check_fields': Paper YAML header is missing expected fields: tags, affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:74:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:75:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
👋 @zedtaha, thanks for your submission to JOSS. Please take a look at the author guidelines and make sure your paper is structured properly please http://joss.theoj.org/about#paper_structure

**Comment by arfon** [comment]
Also, @zedtaha, please make sure you address these points in your paper:

- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software
- A list of key references including a link to the software archive
- Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

Finally, it looks like your project is not open source. Please make sure you add an open source license to your project repository.

**Comment by zedtaha** [comment]
@arfon thanks for your help. I uptated my paper please take a look at. Best

**Comment by zedtaha** [comment]
@whedon i choosed @leeper as a reviewer for this paper if you agree. Thx

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
I am currently recruiting a reviewer for this. I will update when that is determined.

**Comment by zedtaha** [comment]
Ok @leeper. Best

**Comment by leeper** [comment]
@whedon assign @justinesarey as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @justinesarey

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/523. Feel free to close this issue now!
