### ISSUE TITLE
[PRE REVIEW]: humanleague: a C++ microsynthesis package with R and python interfaces

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#504]
**Submitting author:** @virgesmith (<a href="http://orcid.org/0000-0002-9951-6642">Andrew Smith</a>)
**Repository:** <a href="https://github.com/virgesmith/humanleague" target ="_blank">https://github.com/virgesmith/humanleague</a>
**Version:** 2.0.2
**Editor:** @leeper
**Reviewer:** @rdrr1990

**Author instructions**

Thanks for submitting your paper to JOSS @virgesmith. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@virgesmith if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @leeper - would you be willing to edit this submission for JOSS?

**Comment by leeper** [comment]
@jordigh would you be interested in reviewing this (or at least the C++ and Python components) for JOSS?

**Comment by leeper** [comment]
@hausen Would you be interested in reviewing this for JOSS?

**Comment by hausen** [comment]
@leeper I'm sorry, but this submission is completely outside the scope of my knowledge.

**Comment by leeper** [comment]
@wrathematics Would you be interested in reviewing this for JOSS?

**Comment by wrathematics** [comment]
I'm catching up from the holidays + a nasty cold, so I have some other things to attend to right now. If you don't find anyone else, I believe I can review it in a week or two.

**Comment by virgesmith** [comment]
bump

**Comment by leeper** [comment]
@wrathematics Would you still be interested?

**Comment by leeper** [comment]
@hausen Would you be interested in reviewing this for JOSS?

**Comment by hausen** [comment]
@leeper , as I've said before, it's way outside my domain.

**Comment by leeper** [comment]
@hausen oh geez, sorry! Forgot I already asked.

**Comment by virgesmith** [comment]
sadly not. I can't think of anyone with both C++ skills and the domain expertise

**Comment by leeper** [comment]
@virgesmith No problem. I've found someone.

**Comment by leeper** [comment]
@whedon assign @rdrr1990 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rdrr1990

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/629. Feel free to close this issue now!
