### ISSUE TITLE
[REVIEW]: Finch: MinHashing for Sequencing Data with Abundance Calculation and Adaptive Filtering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#505]
**Submitting author:** @bovee (<a href="http://orcid.org/0000-0002-8819-9549">Roderick Boveee</a>)
**Repository:** <a href="https://github.com/onecodex/finch-rs" target ="_blank">https://github.com/onecodex/finch-rs</a>
**Version:** v0.1.4
**Editor:** @biorelated
**Reviewer:** @HadrienG
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1164259" target="_blank">10.5281/zenodo.1164259</a>

## Status

[![status](https://joss.theoj.org/papers/506e8826b77d22fe9a6795717aa794be/status.svg)](https://joss.theoj.org/papers/506e8826b77d22fe9a6795717aa794be)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/506e8826b77d22fe9a6795717aa794be"><img src="https://joss.theoj.org/papers/506e8826b77d22fe9a6795717aa794be/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/506e8826b77d22fe9a6795717aa794be/status.svg)](https://joss.theoj.org/papers/506e8826b77d22fe9a6795717aa794be)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/onecodex/finch-rs" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@HadrienG, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @biorelated know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/onecodex/finch-rs">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.4)?
- [x] **Authorship:** Has the submitting author (@bovee) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @HadrienG it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00505/joss.00505/10.21105.joss.00505.pdf
```

**Comment by HadrienG** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by HadrienG** [comment]
The version in this review doesn't correspond to the latest version of the software. Unsure how to fix that here @biorelated. Can I simply edit the Whedon comment?

I will carry the review with the latest version 0.1.4 in the meantime

**Comment by arfon** [comment]
> I will carry the review with the latest version 0.1.4 in the meantime

I've updated the comment at the top of the issue.

**Comment by arfon** [comment]
@HadrienG - how are you getting along here?

**Comment by HadrienG** [comment]
@arfon It's going pretty well. Vacations have slowed things a little but my last issue is now closed. I'll test the new release and if everything goes fine I fell comfortable recommending for publication

**Comment by HadrienG** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00505/joss.00505/10.21105.joss.00505.pdf
```

**Comment by HadrienG** [comment]
@arfon - all my comments have been addressed! What's the next steps for acceptance?

**Comment by biorelated** [comment]
@arfon Kindly review this for any final checks before onsideration and publication. Many thanks @HadrienG for taking your time to review and @bovee for the submission.

**Comment by arfon** [comment]
> @arfon Kindly review this for any final checks before consideration and publication. 

Mostly this looks fine. I would encourage the authors to consider adding a little more detail to their paper as per our [submission guidelines](http://joss.theoj.org/about#paper_structure):

> - A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
> - A clear statement of need that illustrates the purpose of the software
> - A list of key references including a link to the software archive
> Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

**Comment by biorelated** [comment]
@bovee,  Kindly address the concerns highlighted by @arfon.

**Comment by bovee** [comment]
@arfon Thanks for the suggestions; we've expanded the `paper.md` to address those concerns.

@biorelated Please let me know if there are any remaining concerns or if there's anything else to do. Thanks!

More detailed notes:

> - A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience

The opening paragraph has been expanded to describe what MinHashing is used for and what Finch adds to traditional MinHashing schemes.

> - A clear statement of need that illustrates the purpose of the software

The second paragraph contains an expanded description of how MinHash works that motivates a discussion of the problems that Finch solves in the third paragraph.

> - A list of key references including a link to the software archive

We've added a link to the GitHub software repository.

> - Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

The last paragraph now contains a description of how we are using Finch in our web platform.

**Comment by biorelated** [comment]
@bovee: Thank you for the submission and for addressing all the issues and concerns   
@arfon:  Could we kindly consider this work for publication?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00505/joss.00505/10.21105.joss.00505.pdf
```

**Comment by arfon** [comment]
@bovee - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bovee** [comment]
@arfon - I just submitted the repo to Zenodo and the record's at https://zenodo.org/record/1164259 and the DOI should be `10.5281/zenodo.1164259` (once it's propagated). Thanks!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1164259 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1164259" target="_blank">10.5281/zenodo.1164259</a> is the archive.

**Comment by arfon** [comment]
@HadrienG - many thanks for your review here and to @biorelated for editing this submission ✨ 

@bovee - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00505 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00505/status.svg)](https://doi.org/10.21105/joss.00505)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00505/status.svg)](https://doi.org/10.21105/joss.00505)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
