### ISSUE TITLE
Indicate Matlab Version and OS tested

### ISSUE THREAD

**Issue by siboles** [openjournals/joss-reviews#507]
@Kevin-Mattheus-Moerman #506 
I've installed in R2015a Matlab on Arch Linux. It seems your Linux testing is on an Ubuntu machine, which is probably the best choice for the widest audience. Most things went smoothly, although the help did not integrate for me. I'm not sure if it is my Matlab version, how I installed on Arch, or something else. My Matlab skills are not the greatest.

I would however, indicate somewhere in the paper.md or the README what Matlab Version you've tested on, or if a minimum version is known, and also the Linux OS, and the minimum Windows version.

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #507 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by wspr** [comment]
I'm not 100% sure about this (I haven't reviewed for JOSS before) but I think these comments are intended to go in the [GIBBON issue tracker](https://github.com/gibbonCode/GIBBON/issues).

**Comment by cMadan** [comment]
Yes, @wspr is correct, these comments should go in the project's issue tracker, not the 'general' JOSS review one.
