### ISSUE TITLE
[REVIEW]: Gophernotes: the Go kernel for Jupyter and nteract

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#508]
**Submitting author:** @dwhitena (<a href="http://orcid.org/0000-0003-1155-8889">Daniel Whitenack</a>)
**Repository:** <a href="https://github.com/gopherdata/gophernotes" target ="_blank">https://github.com/gopherdata/gophernotes</a>
**Version:** v1.0.0-RC
**Editor:** @arokem
**Reviewer:** @vsivsi
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/b0034f120957e93c9f645cd04a8c4d1a/status.svg)](https://joss.theoj.org/papers/b0034f120957e93c9f645cd04a8c4d1a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b0034f120957e93c9f645cd04a8c4d1a"><img src="https://joss.theoj.org/papers/b0034f120957e93c9f645cd04a8c4d1a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b0034f120957e93c9f645cd04a8c4d1a/status.svg)](https://joss.theoj.org/papers/b0034f120957e93c9f645cd04a8c4d1a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/gopherdata/gophernotes" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vsivsi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gopherdata/gophernotes">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0-RC)?
- [x] **Authorship:** Has the submitting author (@dwhitena) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @vsivsi it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #508 with the following error: 

 pandoc-citeproc: "stdin" (line 10, column 2):
unexpected "B"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@dwhitena - this should fix the errors compiling your paper: https://github.com/gopherdata/gophernotes/pull/92

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00508/joss.00508/10.21105.joss.00508.pdf
```

**Comment by arokem** [comment]
@vsivsi : have you made any progress on the review of this software?

**Comment by vsivsi** [comment]
I’ve worked my way through some of the checklist.  I actually had an [open issue](https://github.com/gopherdata/gophernotes/issues/17#issuecomment-355446855) on the project repo from over a year ago, and I did an ‘@‘ comment to the author asking about progress on that and haven’t received any response since I sent it several weeks ago.  I’ll ping him again and see if I have any better luck.  @arokem

**Comment by arokem** [comment]
@vsivsi: any progress on this?

**Comment by vsivsi** [comment]
@arokem Working on it now.  Sorry for delay, it slipped into a busy period the past few weeks, but this week is pretty clear, so it will be done by Friday.

**Comment by arokem** [comment]
Hello @dwhitena! Have you had a chance to take a look at the comments that the reviewer made?

**Comment by arfon** [comment]
:wave: @dwhitena - please respond to the reviewer's feedback on your project.

**Comment by arokem** [comment]
Hey @dwhitena: could I ask about the status of this submission? Have you had a chance to address the reviewer's comments?

**Comment by dwhitena** [comment]
@arokem Based on some of the feedback, I was hoping to have some of the plugin issues worked out before publishing. That way it would be more generally relevant. Since then, I haven't been able to devote much time to it, but @sbinet @spencerpark and @cosmos72 have taken the reigns. Maybe they can push this to the finish line?

**Comment by arokem** [comment]
What is the status of this paper? 

It would be great if these new contributors can push this along, but we'd like to know whether you intend to withdraw your paper. Otherwise, you can also consider adding some of these contributors as authors, if you believe that their contributions are crucial to completing the work required to meet the requirements for publication.

**Comment by arokem** [comment]
@arfon Considering the author has indicated that he might not take this paper further to acceptance, should we close this issue for the time being, and reopen when the author(s) is(are) able to carry this work further?

**Comment by arfon** [comment]
> @arfon Considering the author has indicated that he might not take this paper further to acceptance, should we close this issue for the time being, and reopen when the author(s) is(are) able to carry this work further?

Yes, let's close this.
