### ISSUE TITLE
Submission: rdefra: Interact with the UK AIR Pollution Database from DEFRA

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#51]
**Submitting author:** @cvitolo (<a href="http://orcid.org/0000-0002-4252-1176">Claudia Vitolo</a>)
**Repository:** <a href="https://github.com/kehraProject/r_rdefra" target ="_blank">https://github.com/kehraProject/r_rdefra</a>
**Version:** v0.3.0 
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.61033" target="_blank">10.5281/zenodo.61033</a>

## Status

[![status](http://joss.theoj.org/papers/57058f6e8a511f3bb0667ef7687cc87d/status.svg)](http://joss.theoj.org/papers/57058f6e8a511f3bb0667ef7687cc87d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/57058f6e8a511f3bb0667ef7687cc87d"><img src="http://joss.theoj.org/papers/57058f6e8a511f3bb0667ef7687cc87d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/57058f6e8a511f3bb0667ef7687cc87d/status.svg)](http://joss.theoj.org/papers/57058f6e8a511f3bb0667ef7687cc87d)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kehraProject/r_rdefra">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3.0)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00051.pdf](https://github.com/openjournals/joss-reviews/files/420616/10.21105.joss.00051.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by pragyansmita** [comment]
:hand: I am reviewing this 
I will get this reviewed by Friday (8/19) - thanks!

**Comment by pjotrp** [comment]
Web scraping is a notoriously fragile method. 

This software consists of 243 lines of R code. I would like to ask the
author to confirm *here* that he thinks this software is a valuable
contribution to research. I want to point out that once this work has
been published it will be visible for a long time. Adding an example
of having used this tool in research would be a good idea.

**Comment by pragyansmita** [comment]
This is part of the openSci R package and provides access to the Air Information Resource UK-AIR of the Department for Environment, Food and Rural Affairs in the United Kingdom (no public API available today). 

@cvitolo - Can you please confirm the following are included?

-  a plain-text LICENSE file with the contents of an OSI approved software license
- release version number in documentation matching Github

The readme references in usage ukair_catalogue(). However, that method is no longer available. Using catalogue() is available instead. ukair_get_coordinates is also not available. Can the readme and provided examples please be updated to match the current methods? 

If any automated tests can be provided apart from the provided examples, please include the same.

**Comment by cvitolo** [comment]
## rdefra - response to reviewers (step 1)

Many thanks for reviewing my paper/package. Below are my responses to reviewers' comments.

## @pjotrp

* I agree web scraping is a fragile method but without pubblic APIs there are not many alternatives. This is however a temporary solution, when APIs will become available I'll update the package to work with those.

* I wrote this software to carry out my own research and I believe there are many other researchers that could benefit from my work, without the need to re-invent the wheel. In my opinion, this is a valuable contribution to research but it could also be useful for practitioners. I am preparing another journal paper for which I carried out some modelling excercises and used this software to get pollution data. I'll add a link to this second paper as soon as it is published.

## @pragyansmita 

* Regarding the license, I confirm that the license information is included in the DESCRIPTION file where you can read __License: GPL-3__. This should be sufficient, according to the [Writing R Extensions manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing) which says that 'It is very important that you include license information [...] If a package license restricts a base license [...] the additional terms should be placed in file LICENSE'. Therefore, if I understand this well, I only need a file called LICENSE is I want to restrict the LICENSE specified in the DESCRIPTION file. Am I correct?

* I confirm that the latest version is 0.3.0 (see Github repository).

* As requested by ROPENSCI reviewers, all the names of the functions in rdefra  are now in lower case and have a prefix (ukair):

    - `catalogue()` is now called `ukair_catalogue()`
    - `EastingNorthing()` is now called `ukair_get_coordinates()`
    - `get1Hdata()` is now called `ukair_get_hourly_data()`
    - `getSiteID()` is now called `ukair_get_site_id()`

README and vignette have been updated accordingly.

* A number of tests have been provided using the testthat framework.

**Comment by arfon** [comment]
> a plain-text LICENSE file with the contents of an OSI approved software license

@pragyansmita - CRAN has some pretty restrictive policies around where the license can be present. See this thread for background: https://github.com/openjournals/joss-reviews/issues/37#issuecomment-231787026

I believe that @cvitolo has adhered to the CRAN guidelines here which is acceptable to JOSS.

**Comment by pragyansmita** [comment]
@cvitolo Thank you for the information

@arfon Thank you

Recommend for publication. @arfon : Please let me know if anything else is needed. Thanks!

**Comment by arfon** [comment]
> Recommend for publication. @arfon : Please let me know if anything else is needed. Thanks!

Thanks @pragyansmita.

@cvitolo - at this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by cvitolo** [comment]
Many thanks @arfon - I have just made a new release v0.3.2, here is the doi url: http://dx.doi.org/10.5281/zenodo.61033

**Comment by arfon** [comment]
Thanks for the review @pragyansmita :zap:

@cvitolo - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00051 🎉 🚀 💥

**Comment by noamross** [comment]
Adding a note for reference: *rdefra* went through JOSS and rOpenSci review in parallel, having been submitted before our joint-review workflow was in place but approved after.  The rOpenSci review can be found here: https://github.com/ropensci/onboarding/issues/68
