### ISSUE TITLE
[PRE REVIEW]: MixEst: An Estimation Toolbox for Mixture Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#510]
**Submitting author:** @reshadh (<a href="http://orcid.org/0000-0002-3669-760X">Reshad Hosseini</a>)
**Repository:** <a href="https://github.com/utvisionlab/mixest" target ="_blank">https://github.com/utvisionlab/mixest</a>
**Version:** v1.2.0
**Editor:** @arokem
**Reviewer:** @josephhardinee

**Author instructions**

Thanks for submitting your paper to JOSS @reshadh. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@reshadh if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #510 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16  100    16    0     0     62      0 --:--:-- --:--:-- --:--:--    62
Error producing PDF.
! LaTeX Error: File `booktabs.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.152 \usepackage

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
👋 @arokem - the submitting author suggested you as a potential editor.

**Comment by arfon** [comment]
Looks like @whedon doesn't quite know how to compile this paper. I've manually done it here [10.21105.joss.00510.pdf](https://github.com/openjournals/joss-reviews/files/1562585/10.21105.joss.00510.pdf)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #510 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16  100    16    0     0     80      0 --:--:-- --:--:-- --:--:--    80
Error producing PDF.
! LaTeX Error: File `booktabs.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.152 \usepackage

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00510/joss.00510/10.21105.joss.00510.pdf
```

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
Sure - I can edit this! @reshadh - do you have ideas for potential reviewers?

**Comment by arokem** [comment]
👋 @josephhardinee: are you available to review this submission for JOSS?

**Comment by josephhardinee** [comment]
I am. Sorry I was out for holidays. This will be the first one I've reviewed so I'll probably require a little bit of hand holding.

**Comment by arokem** [comment]
@josephhardinee : thanks for getting back to me on this. No problem with this being your first review. I can help along!

I will start by assigning you as an editor and starting the review process. Once that's done, it will create a new issue for the review, with a check list of items that we'd like you to take a look at. The best way to help authors make it through the review is to post issues to the Github of their project, relating them to the review check list.  And the review issue gives you the opportunity to comment on other general aspects of the software that are not covered by the checklist -- you can definitely post issues about these as well.

**Comment by arokem** [comment]
@whedon assign @josephhardinee as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @josephhardinee

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/524. Feel free to close this issue now!

**Comment by arokem** [comment]
@josephhardinee : head on over to #524 for the review. And please ping me whenever you have a question. I might take a few days to answer (as I check in on this only periodically).
