### ISSUE TITLE
[REVIEW]: tidyhydat: Extract and Tidy Canadian Hydrometric Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#511]
**Submitting author:** @boshek (<a href="http://orcid.org/0000-0002-9270-7884">Samuel Albers</a>)
**Repository:** <a href="https://github.com/ropensci/tidyhydat" target ="_blank">https://github.com/ropensci/tidyhydat</a>
**Version:** 0.3.0
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1116459" target="_blank">10.5281/zenodo.1116459</a>

## Status

[![status](https://joss.theoj.org/papers/8fc1d00db51c3015ad49ab35b622423c/status.svg)](https://joss.theoj.org/papers/8fc1d00db51c3015ad49ab35b622423c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8fc1d00db51c3015ad49ab35b622423c"><img src="https://joss.theoj.org/papers/8fc1d00db51c3015ad49ab35b622423c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8fc1d00db51c3015ad49ab35b622423c/status.svg)](https://joss.theoj.org/papers/8fc1d00db51c3015ad49ab35b622423c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/tidyhydat" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arfon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/tidyhydat">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.3.0)?
- [x] **Authorship:** Has the submitting author (@boshek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #511 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16  100    16    0     0     65      0 --:--:-- --:--:-- --:--:--    65
Error producing PDF.
! LaTeX Error: File `fancyvrb.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.153 \newcommand

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
Accepting because of rOpenSci acceptance in https://github.com/ropensci/tidyhydat/pull/69

**Comment by arfon** [comment]
@boshek - one more set of small changes https://github.com/ropensci/tidyhydat/pull/70

**Comment by boshek** [comment]
@arfon Merged

**Comment by arfon** [comment]
@boshek your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00511 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00511/status.svg)](https://doi.org/10.21105/joss.00511)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00511/status.svg)](https://doi.org/10.21105/joss.00511)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://bit.ly/joss-reviewers

**Comment by boshek** [comment]
@arfon Embarrassing ask: Is there any opportunity to correct a few spelling errors in the article?

**Comment by arfonsmith** [comment]
Sure thing. Please make the edits and I can update the paper.

**Comment by boshek** [comment]
Thanks @arfon . Edits made here: https://github.com/ropensci/tidyhydat/blob/master/inst/JOSS/paper.md

**Comment by arfon** [comment]
@boshek - this should be updated now.
