### ISSUE TITLE
[REVIEW]: origami - Cross-validation Framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#512]
**Submitting author:** @jeremyrcoyle (<a href="http://orcid.org/0000-0002-9874-6649">Jeremy Coyle</a>)
**Repository:** <a href="https://github.com/jeremyrcoyle/origami" target ="_blank">https://github.com/jeremyrcoyle/origami</a>
**Version:** v0.8
**Editor:** @karthik
**Reviewer:** @wrathematics
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1155901" target="_blank">10.5281/zenodo.1155901</a>

## Status

[![status](https://joss.theoj.org/papers/01bbb017ad709759be27259a5c80e09a/status.svg)](https://joss.theoj.org/papers/01bbb017ad709759be27259a5c80e09a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/01bbb017ad709759be27259a5c80e09a"><img src="https://joss.theoj.org/papers/01bbb017ad709759be27259a5c80e09a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/01bbb017ad709759be27259a5c80e09a/status.svg)](https://joss.theoj.org/papers/01bbb017ad709759be27259a5c80e09a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jeremyrcoyle/origami" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@wrathematics, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jeremyrcoyle/origami">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8)?
- [x] **Authorship:** Has the submitting author (@jeremyrcoyle) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @wrathematics it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00512/joss.00512/10.21105.joss.00512.pdf
```

**Comment by nhejazi** [comment]
@wrathematics -- Thanks for submitting your review. The issue with the DOI pointing to the incorrect package version has been fixed by minting a new DOI via Zenodo (for the same GitHub release that we originally opened this review for). Here is a link to the new DOI: https://doi.org/10.5281/zenodo.1155901

Please let us know if there are any other corrections that we can make to complete this review process.

**Comment by wrathematics** [comment]
Great, thanks. With the updated DOI, this looks good to me.

This should be good to go as far as JOSS is concerned, but I have a few additional comments that I hope you'll find helpful. The package looks very useful, but the examples don't quite feel right to me. I'd sort of compare it to the idea of something being "pythonic" in python. As you probably know, there are basically two distinct styles in R, base and tidy. This package isn't in the tidy philosophy (which is fine), but it doesn't feel quite right with base either. If we take your linear models example, you could swap out the use of strings for formulas, so the first few lines might look like:

```r
  f <- formula(reg_form)
  mf <- model.frame(f, data=data)
  out_var_ind <- 1

  # split up data into training and validation sets
  train_data <- training(mf)
  valid_data <- validation(mf)
```

This way you could actually automate all of this for the user, and then the `cv_lm()` function would only need to do the fitting. Then in `cross_validate()`, you would pass `reg_form=mpg ~ .`. You could also play the game of attaching the data to the folds object (sort of like how `lm()` itself does) to simplify argument passing. You could even do this with a separate formula interface, and leave the current more general interface as is.

There may be some issues here that I haven't considered and you already have, making this harder than my gut instinct is leading me to believe. But if not, I think it's worth considering touching up the interface to use formulas.

**Comment by nhejazi** [comment]
Perfect, thanks for confirming completion of the JOSS review.

Great to hear that you see the package as useful, and we're glad to hear the critiques/suggestions about the structure of the package, as we'd, of course, like to make sure that potential users feel the code to be natural. I've gone ahead and opened an issue with your comments [here](https://github.com/jeremyrcoyle/origami/issues/26) -- feel free to add to it at any time. I think it definitely makes sense to update the examples (`cv_lm` and the like) to match your suggestions, for example, with passing in a model formula rather than a string. In regard to a few of the other suggestions, I do think some of the ideas might clash with the design philosophy of `origami`, as the goal of the package is not to provide user-friendly functions like `cv_lm` but the rather the tools for interested users to build such functions (that is, users should really only be relying on functions like `training`, `validation`, and `cross_validate` to essentially write a cross-validation wrapper around practically any process). We'll likely have to think carefully about re-structuring aspects of the core functions to ensure that everything works smoothly with these refinements.

**Comment by nhejazi** [comment]
@karthik -- I believe we've now completed the review process, but I'm unsure of what the next steps might be in closing this review and generating the approved paper, etc. @wrathematics -- please feel free to correct me if I'm missing something here. Thank you all for your work in this review process.

**Comment by karthik** [comment]
@nhejazi Great! Can you please update the thread with a DOI (software archive on Zenodo) and I can proceed with the acceptance?

**Comment by nhejazi** [comment]
Excellent -- we've archived v0.8.0 of the `origami` package and generated a DOI via Zenodo: DOI: 10.5281/zenodo.1155901. Please let me know if there's anything more we can do on our end.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1155901 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1155901" target="_blank">10.5281/zenodo.1155901</a> is the archive.

**Comment by arfon** [comment]
@wrathematics many thanks for your review here and to @karthik for editing this submission.

@nhejazi @jeremyrcoyle - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00512 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00512/status.svg)](https://doi.org/10.21105/joss.00512)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00512/status.svg)](https://doi.org/10.21105/joss.00512)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by nhejazi** [comment]
Thank you @wrathematics for the helpful and detailed review, and thank you @karthik for editing the submission for our package. Thanks @arfon for coordinating this process.
