### ISSUE TITLE
[REVIEW]: cleanEHR: The critical care EHR analysis tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#513]
**Submitting author:** @sinanshi (<a href="http://orcid.org/0000-0001-6935-0429">Sinan Shi</a>)
**Repository:** <a href="https://github.com/ropensci/cleanEHR" target ="_blank">https://github.com/ropensci/cleanEHR</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1117244" target="_blank">10.5281/zenodo.1117244</a>

## Status

[![status](https://joss.theoj.org/papers/4cb8b3f995b60521c2019cc8d87fc1c0/status.svg)](https://joss.theoj.org/papers/4cb8b3f995b60521c2019cc8d87fc1c0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4cb8b3f995b60521c2019cc8d87fc1c0"><img src="https://joss.theoj.org/papers/4cb8b3f995b60521c2019cc8d87fc1c0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4cb8b3f995b60521c2019cc8d87fc1c0/status.svg)](https://joss.theoj.org/papers/4cb8b3f995b60521c2019cc8d87fc1c0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/CC-HIC/cleanEHR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arfon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CC-HIC/cleanEHR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@sinanshi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #513 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/513/paper.md): found character that cannot start any token while scanning for the next token at line 4 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-453fa9fb981d/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1117244 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1117244" target="_blank">10.5281/zenodo.1117244</a> is the archive.

**Comment by arfon** [comment]
Accepting because of submission to rOpenSci: https://github.com/ropensci/onboarding/issues/102

**Comment by arfon** [comment]
@sinanshi - I've fixed up some issues with your `paper.md` here https://github.com/ropensci/cleanEHR/pull/151 . 

Also, since you submitted originally, our [submission guidelines](http://joss.theoj.org/about#paper_structure) have been updated a fair bit. Please take a look at the section 'What should my paper contain?' here http://joss.theoj.org/about#paper_structure

Finally, it looks like you're missing a bibliography. Please make sure you cite related work using the standard RMarkdown way: can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by sinanshi** [comment]
Thanks @arfon, could you have a look if it is all OK now.

**Comment by arfon** [comment]
Thanks @sinanshi  - I still think this paper could do with a little more detail. From the text of your paper it's still not very clear to me what this software does! Please consider adding just a little more prose, perhaps with an example use case to address this:

> - A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience

Also, if there are any research projects using this software then please describe them too:

> - Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

**Comment by sinanshi** [comment]
Thank you @arfon for your suggestions. I have updated the paper, adding the high-level functionality description. Regarding other related research project, there is no published research result so far using this package, despite many at the early stage of their research.

**Comment by arfon** [comment]
@sinanshi - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00513 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00513/status.svg)](https://doi.org/10.21105/joss.00513)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00513/status.svg)](https://doi.org/10.21105/joss.00513)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
