### ISSUE TITLE
[REVIEW]: phyphy: A Python package for facilitating the execution and parsing of HyPhy standard analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#514]
**Submitting author:** @sjspielman (<a href="http://orcid.org/0000-0002-9090-4788">Stephanie Spielman</a>)
**Repository:** <a href="https://github.com/sjspielman/phyphy" target ="_blank">https://github.com/sjspielman/phyphy</a>
**Version:** v0.4.1
**Editor:** @mgymrek
**Reviewer:** @luizirber
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1154244" target="_blank">10.5281/zenodo.1154244</a>

## Status

[![status](https://joss.theoj.org/papers/9f65f1bc47bf8f17d773d09928a89b90/status.svg)](https://joss.theoj.org/papers/9f65f1bc47bf8f17d773d09928a89b90)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9f65f1bc47bf8f17d773d09928a89b90"><img src="https://joss.theoj.org/papers/9f65f1bc47bf8f17d773d09928a89b90/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9f65f1bc47bf8f17d773d09928a89b90/status.svg)](https://joss.theoj.org/papers/9f65f1bc47bf8f17d773d09928a89b90)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sjspielman/phyphy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@luizirber, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sjspielman/phyphy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1)?
- [x] **Authorship:** Has the submitting author (@sjspielman) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @luizirber it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00514/joss.00514/10.21105.joss.00514.pdf
```

**Comment by mgymrek** [comment]
Thanks @luizirber for agreeing to review! Please let me know if you have any questions about the review process.

**Comment by mgymrek** [comment]
Hi @luizirber I just wanted to check in on this. Please let me know if you have any questions.

**Comment by sjspielman** [comment]
Hello @mgymrek and @luizirber, 

I have a inquiry regarding this review process. An updated version of one my citations has just been published and I would like to update my `paper.md` with this new citation. Is it possible to update at this stage or should I keep waiting until the review actually begins? It has now been about 4 weeks since the review was assigned so the time frame has not been clear to me.

Thank you, 
Stephanie

**Comment by luizirber** [comment]
Hi Stephanie,

You can update it. I will review it today.

On January 10, 2018 4:12:07 PM UTC, Stephanie <notifications@github.com> wrote:
>Hello @mgymrek and @luizirber, 
>
>I have a inquiry regarding this review process. An updated version of
>one my citations has just been published and I would like to update my
>`paper.md` with this new citation. Is it possible to update at this
>stage or should I keep waiting until the review actually begins? It has
>now been about 4 weeks since the review was assigned so the time frame
>has not been clear to me.
>
>Thank you, 
>Stephanie
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openjournals/joss-reviews/issues/514#issuecomment-356650681

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjspielman** [comment]
Thanks very much! I just updated it. I realize, though, that it's still in press so the full citation with volume/issue/pages is still forthcoming. Either way it's better than before. Thanks again!

**Comment by luizirber** [comment]
Hello @sjspielman! Very nice software, just a couple of comments:

## Blockers
- [ ] DOI missing for datamonkey and HyPhy refs
  - [ ] HyPhy: https://doi.org/10.1093/bioinformatics/bti079
  - [ ] Datamonkey 2: https://doi.org/10.1093/molbev/msx335

## Recommendations

- LICENSE.txt doesn't appear to be recognized by github
  - It seems to be some oddness with detection the FreeBSD-style license, they recommend adding a note to README.md to detect it properly.
  - side note: any special reason to choose this license instead of a 3-clause or 2-clause BSD license?

- tests are a bit odd to run, any reason why they are python2.7 only?

- version listed on this review issue is 0.1, but latest release on github is 0.3 (but this can be fixed once there is a archived DOI)

**Comment by sjspielman** [comment]
HI @luizirber, 

I have gone ahead and pushed the updated refs with the doi. For your other questions:

1) I have no good reason for using FreeBSD over the 2- or 3- clause, and if it helps github to recognize I will happily switch out.
2) The reason the tests are 2.7 compatible only has to do with changes to the unittest module in python, where certain functions that I need to use in testing were deprecated in python3. If you think this will cause a major issue, I can look into a 3rd party testing package, although I am hesitant to add further dependencies.
3) Yes, I did have to update the version with a few patches for some elusive bugs. Is there somewhere specific I should update this version information?

Thanks, 
Stephanie

**Comment by luizirber** [comment]
Hi @sjspielman!

1. it's not a big issue (since the FreeBSD license is OSI approved), and start discussing software license is a neverending bikeshedding problem =P. GitHub uses https://github.com/benbalter/licensee/ to recognize licenses, but it seems to have problems with the FreeBSD one. I tend to use BSD 3-clause when I want a BSD license, but the final decision is up to you.
2. I think that's fine, although `pytest` is the de facto standard for Python testing nowadays.
3. The version is not listed in the paper, but once you mint a DOI for the archival copy (thru zenodo) it is important to have the correct version. @mgymrek is there a @whedon command to bump the version?

Other than that, if @sjspielman doesn't have any other corrections, checklist is completed and review is approved!

**Comment by sjspielman** [comment]
Hi @luizirber, 

Ok, I just went ahead to the BSD-3 clause and github finally recognizes it! I updated the `paper.md` accordingly, too.

In addition, in response to a user-identified bug, I updated the current release to 0.4 this morning, which can be final version for publishing. @mgymrek can hopefully advise on how to proceed with version bumping, as you mentioned.

Other than these, I'm all set on my end!

Thanks!
-Stephanie

**Comment by mgymrek** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by mgymrek** [comment]
Thanks @luizirber and @sjspielman! This looks good to me

I have not dealt with version bumps so will defer to @arfon: 
since the review issue has been created the version of this software has been updated. Is there any @whedon command for that? I didn't see something obvious. Other than that it looks we're ready to accept this submission.

**Comment by arfon** [comment]
> I have not dealt with version bumps so will defer to @arfon: since the review issue has been created the version of this software has been updated. Is there any @whedon command for that? I didn't see something obvious. Other than that it looks we're ready to accept this submission.

This is something I have to do manually (by editing the issue).

**Comment by arfon** [comment]
@sjspielman - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by sjspielman** [comment]
Hi @arfon, 

Got the DOI: [![DOI](https://zenodo.org/badge/97511838.svg)](https://zenodo.org/badge/latestdoi/97511838). I have also placed this badge in my repo's README.

However, it appeared that, in order to accomplish this archiving, I had to make another (sorry...) release of the repo. As such, the release tag associated with this DOI is 0.4.1.

Thanks, 
Stephanie

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1154244 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1154244" target="_blank">10.5281/zenodo.1154244</a> is the archive.

**Comment by arfon** [comment]
@luizirber - many thanks for your review here and to @mgymrek for editing this submission ✨ 

@sjspielman - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00514 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00514/status.svg)](https://doi.org/10.21105/joss.00514)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00514/status.svg)](https://doi.org/10.21105/joss.00514)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
