### ISSUE TITLE
[REVIEW]: scanstatistics: The R Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#515]
**Submitting author:** @benjak (<a href="http://orcid.org/0000-0002-0927-7183">Benjamin Allévius</a>)
**Repository:** <a href="https://github.com/BenjaK/scanstatistics" target ="_blank">https://github.com/BenjaK/scanstatistics</a>
**Version:** v1.0.0
**Editor:** @leeper
**Reviewer:** @tgerke
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1242982" target="_blank">10.5281/zenodo.1242982</a>

## Status

[![status](https://joss.theoj.org/papers/ff2a6f8b6c53b762c85ed7b387bfee4e/status.svg)](https://joss.theoj.org/papers/ff2a6f8b6c53b762c85ed7b387bfee4e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ff2a6f8b6c53b762c85ed7b387bfee4e"><img src="https://joss.theoj.org/papers/ff2a6f8b6c53b762c85ed7b387bfee4e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ff2a6f8b6c53b762c85ed7b387bfee4e/status.svg)](https://joss.theoj.org/papers/ff2a6f8b6c53b762c85ed7b387bfee4e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/BenjaK/scanstatistics" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pragyansmita, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BenjaK/scanstatistics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@benjak) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @pragyansmita it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00515/joss.00515/10.21105.joss.00515.pdf
```

**Comment by leeper** [comment]
Hi @pragyansmita, just a quick reminder about this review! Thanks!

**Comment by leeper** [comment]
Hi again @pragyansmita, any progress on this review?

**Comment by BenjaK** [comment]
Dear @leeper, I cannot see any activity from @pragyansmita, and while waiting for this review, I have released a new (minor) version of the scanstatistics package. Should I withdraw my submission and submitt anew, so that another reviewer can be assigned, or is anyone else willing to review this submission?

**Comment by leeper** [comment]
Hi @BenjaK sorry about this. I've been trying to track down this reviewer for a few weeks and, in the absence of a reply, have started soliciting a replacement reviewer. Please keep the issue open - I hope to have someone in place soon. Huge apologies for the atypically long time getting this package reviewed.

**Comment by leeper** [comment]
@BenjaK very sorry about the delays on this. I've been trying to track down the reviewer to no avail and have already begun trying to find a replacement reviewer. Please keep the review open.

**Comment by BenjaK** [comment]
Thanks, and no worries!

**Comment by pragyansmita** [comment]
My apologies for the delay in completing this. I was not aware this was assigned to me. I have been away sick for the past 10days - thus, missed the reminder. I can get to this by March 15th, if it is ok. Please feel free to reassign if anyone else is available to look into it sooner. My sincere apologies for the inconveniences.

**Comment by leeper** [comment]
@whedon assign @tgerke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tgerke

**Comment by leeper** [comment]
@pragyansmita Thanks for getting back to me! I'd be happy to have your thoughts on the package if you have time but have also appointed @tgerke as a new reviewer.

**Comment by pragyansmita** [comment]
The documentation provided is complete. It includes a good step-by-step example related to New Mexico and occurance of cancer. I will watch out for datasets and problems where this tool can be applied.Very interesting solution and made an engaging read. Thank you.

**Comment by leeper** [comment]
@tgerke Just a quick reminder about this review!

**Comment by tgerke** [comment]
@leeper The reminder is appreciated! Apologies for the delay: had my head buried in sand for a series of grant applications due this week, but will tackle the review within 1 week. Looking forward to it.

**Comment by leeper** [comment]
@tgerke Just another ping on this!

**Comment by tgerke** [comment]
Works as advertised, readme was easy to follow, overall excellent package! Only item in the review checklist I didn't fill was the one regarding the LICENSE file, which I was not able to locate. One minor comment related to the statement of need: the spatial problems the package solves are nicely described, but it could be useful to mention key areas this package extends/complements existing software packages that implement a subset of the same methods (e.g. SaTScan). 

@leeper Do I need to complete extra steps beyond this comment? This is my first review for JOSS, so learning the process (which, by the way, is fantastic thus far; you all really make this easy).

**Comment by leeper** [comment]
@tgerke Thank you! This looks great. Really appreciate the review. Since it sounds like you're mostly happy, that's all we'll need. Excellent job on your first review!

@BenjaK Review is in and all looks good. We're nearly there. Two final things:

 - Consider updating [the paper](https://github.com/BenjaK/scanstatistics/blob/master/JOSS/paper.md) regarding statement of need. @tgerke's suggestion seems useful.
 - Please add DOIs for all cited articles (if they have them) in [your .bib file](https://github.com/BenjaK/scanstatistics/blob/master/JOSS/paper.bib)

**Comment by BenjaK** [comment]
Thank you @tgerke and @leeper. I have now 

1. added a file `LICENCE.md` to clarify which license the package goes under (the licence is also found in the `DESCRIPTION` file), 
2. updated the statement of need with a reference to SaTScan and exemplified what sets my package apart, and 
3. added DOIs for cited articles. Note: One reference has been updated since it is now in press.

**Comment by leeper** [comment]
@BenjaK Great. Thank you. Two final things:

1. I might further suggest that in the paper you situate the references in the actual paper so that it is clear why you are citing the various papers. While JOSS articles are meant to be short, they are still articles that follow a narrative structure.
2. Can you please issue a DOI for an archived version of the software using [zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar service? Please post the DOI for the archive here once you have it.

**Comment by BenjaK** [comment]
@leeper I'm in the process of fixing your point 2. I wonder, would it be possible to update the version number of my package submitted to JOSS? It is currently v1.0.0, but I would like it to be v1.0.1. The latter is the version showed per default on the GitHub page (and likely the one reviewed), and the difference between 1.0.1 and 1.0.0 is minute.

**Comment by BenjaK** [comment]
@leeper The DOI for version 1.0.1 is 10.5281/zenodo.1242982. Points 1 and 2 are thus taken care of.

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1242982 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1242982" target="_blank">10.5281/zenodo.1242982</a> is the archive.

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00515/joss.00515/10.21105.joss.00515.pdf)

**Comment by leeper** [comment]
@BenjaK Great. Thank you. The archived version is 1.0.1 and that is the version we will consider to have been reviewed by JOSS. Happy to say that means your paper is now accepted for JOSS! Apologies for the longer than anticipated review timeline.

@arfon Over to you.

**Comment by BenjaK** [comment]
@leeper Thank you. However, it seems that the article proof is the old version of the article; not the updated version found here: https://github.com/BenjaK/scanstatistics/blob/master/JOSS/paper.md

**Comment by arfon** [comment]
@tgerke - many thanks for your review here and to @leeper for editing this one ✨ 

@BenjaK - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00515 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00515/status.svg)](https://doi.org/10.21105/joss.00515)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00515/status.svg)](https://doi.org/10.21105/joss.00515)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
