### ISSUE TITLE
[REVIEW]: arrgh: a Go interface to the OpenCPU R server system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#517]
**Submitting author:** @kortschak (<a href="http://orcid.org/0000-0001-8295-2301">Robert Daniel Kortschak</a>)
**Repository:** <a href="https://github.com/kortschak/arrgh" target ="_blank">https://github.com/kortschak/arrgh</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @brentp
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1148825" target="_blank">10.5281/zenodo.1148825</a>

## Status

[![status](https://joss.theoj.org/papers/f423363d7adb385ba3234a6ecf3aa68a/status.svg)](https://joss.theoj.org/papers/f423363d7adb385ba3234a6ecf3aa68a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f423363d7adb385ba3234a6ecf3aa68a"><img src="https://joss.theoj.org/papers/f423363d7adb385ba3234a6ecf3aa68a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f423363d7adb385ba3234a6ecf3aa68a/status.svg)](https://joss.theoj.org/papers/f423363d7adb385ba3234a6ecf3aa68a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kortschak/arrgh" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@brentp, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kortschak/arrgh">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (kortschak) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @brentp it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00517/joss.00517/10.21105.joss.00517.pdf
```

**Comment by pjotrp** [comment]
@brentp we review here. @kortschak would you be so kind to validate we can tick the boxes above? Thanks!

**Comment by kortschak** [comment]
I believe so.

**Comment by pjotrp** [comment]
Super. All yours @brentp.

**Comment by brentp** [comment]
@pjotrp now that I read the COI doc, it appears that, by the letter, I would be in conflict. It says:
```
COIs are your present or previous association with any authors of a submission: recent (past four years) collaborators in funded research or work that is published...
```
I am on the [biogo/hts](http://joss.theoj.org/papers/10.21105/joss.00168) paper with @kortschak

**Comment by kortschak** [comment]
Sorry, I did not read that part - I focused on the areas relating to the paper/submission.

**Comment by kortschak** [comment]
May I suggest Jeroen Ooms. He is the author of OpenCPU which is either a good thing or a bad thing; he is the expert on the base system, but whether that constitutes a conflict here, I don't know. I have not worked with him.

**Comment by pjotrp** [comment]
@brentp I don't think being a co-author on an earlier paper is a conflict. @arfon can you advise?

**Comment by danielskatz** [comment]
The CoI policy is defined here: https://github.com/openjournals/joss/blob/master/COI.md and since the paper in question was earlier this year, this is a conflict.

Based on the following text:
> If you have a conflict of interest with a submission, you should disclose the specific reason to the submissions' editor. This may lead to you not being able to review the submission, but some conflicts may be recorded and then waived, and if you think you are able to make an impartial assessment of the work, you should request that the conflict be waived. 

I think there are 2 questions:

@brentp,  do you feel you can make an impartial assessment of the work?

If so, then

@pjotrp, you should decide if you agree, and if so, declare the conflict recorded (here) and waived.

If no to either, then we need a new reviewer.

**Comment by brentp** [comment]
> @brentp, do you feel you can make an impartial assessment of the work?

yes

**Comment by pjotrp** [comment]
waived.

**Comment by pjotrp** [comment]
Thanks @danielskatz for stepping in. I feel confident in waiving this COI. @brentp please continue review.

**Comment by brentp** [comment]
@pjotrp I believe I have completed the review and the software meets the requirements as described with the inclusion of kortschack/arrgh#9

**Comment by pjotrp** [comment]
Excellent. @arfon I believe we are ready.

**Comment by arfon** [comment]
@kortschak - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by kortschak** [comment]
[![10.5281/zenodo.1148825](https://zenodo.org/badge/DOI/10.5281/zenodo.1148825.svg)](https://zenodo.org/record/1148825)

10.5281/zenodo.1148825

Thank you.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1148825 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1148825" target="_blank">10.5281/zenodo.1148825</a> is the archive.

**Comment by arfon** [comment]
@brentp - many thanks for your review here and to @pjotrp for editing this submission.

@kortschak - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00517 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00517/status.svg)](https://doi.org/10.21105/joss.00517)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00517/status.svg)](https://doi.org/10.21105/joss.00517)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
