### ISSUE TITLE
[Question] : Are examples that show code snippets allowed/acceptable?

### ISSUE THREAD

**Issue by Datseris** [openjournals/joss-reviews#518]
Unfortunately I could not find a definite yes or no answer in the [author guidelines](http://joss.theoj.org/about#author_guidelines).

I am going to submit a paper soon and I was wondering if I could include 
a simple code snippet example of 100 lines of code.

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #518 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
> I am going to submit a paper soon and I was wondering if I could include a simple code snippet example of 100 lines of code.

Yes this is fine. Please note this repository is just for reviews, if you have any follow-up questions please post them over in https://github.com/openjournals/joss
