### ISSUE TITLE
[PRE REVIEW]: reper - Genome-wide identification, classification and quantification of repetitive elements without an assembled genome

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#519]
**Submitting author:** @nterhoeven (<a href="http://orcid.org/0000-0002-8669-0000">Niklas Terhoeven</a>)
**Repository:** <a href="https://github.com/nterhoeven/reper" target ="_blank">https://github.com/nterhoeven/reper</a>
**Version:** v1.0.0
**Editor:** @mgymrek
**Reviewer:** @jsgalan

**Author instructions**

Thanks for submitting your paper to JOSS @nterhoeven. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@nterhoeven if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #519 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-4bc3ad988bea/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-4bc3ad988bea/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-4bc3ad988bea/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
👋 @mgymrek - the submitting author suggested you as the editor.

**Comment by arfon** [comment]
@nterhoeven - could you please merge this PR which fixes up some issues with your paper: https://github.com/nterhoeven/reper/pull/4

**Comment by nterhoeven** [comment]
@arfon thanks for the pull request. I jsut merged it

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00519/joss.00519/10.21105.joss.00519.pdf
```

**Comment by mgymrek** [comment]
@jsgalan @afrubin @hdashnow Would any of you be interested in reviewing this submission?

**Comment by jsgalan** [comment]
Hi all, yes, i am interested in reviewing this article.

Let me know the guidelines.

Best

**Comment by nterhoeven** [comment]
@mgymrek @jsgalan Thanks for agreeing to review. Let me know if I can assist you in any way.

**Comment by hdashnow** [comment]
@mgymrek I'm sorry, I can't review this one. I'm on maternity leave at the moment. Let me know if you would like suggestions for another reviewer.

**Comment by jsgalan** [comment]
Hi @nterhoeven and all, i reviewed the article and have minor comments. 

However, when i wanted to install the software through Docker, had some problems. I am working in osx and the installer it seems is made for ubuntu, attached is the error log for the build. Any of you guys know how to get around this?

Let me know if I am doing something wrong.

Best

[reper docker build.txt](https://github.com/openjournals/joss-reviews/files/1610196/reper.docker.build.txt)

**Comment by nterhoeven** [comment]
Hi @jsgalan thanks for reviewing. Would you mind to [open an issue](https://github.com/nterhoeven/reper/issues/new) for your comments. I will then take a look at this.

The Docker error is strange - Docker should be platform independent. Looking at the log, I see the following error:

```
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease  
  Temporary failure resolving archive.ubuntu.com'
```
This seems to be a network issue on your system. maybe related to the DNS server you are using. take a look at [this stackexchange question](https://serverfault.com/questions/386918/apt-get-cannot-connect-failure-resolving-archive-ubuntu-com#386921)


Can you please try to use the automatically built container from dockerhub? This should also be faster than building the container on a local machine.

```
docker pull nterhoeven/reper
```

**Comment by mgymrek** [comment]
Hi @jsgalan thanks for agreeing to review! Sorry for not seeing this earlier. I will now start a review thread where you can paste additional comments and should go through the reviewer checklist.

**Comment by mgymrek** [comment]
@whedon assign @jsgalan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jsgalan

**Comment by mgymrek** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/527. Feel free to close this issue now!

**Comment by mgymrek** [comment]
@jsgalan please see review thread linked above where we can continue discussion. I am closing this issue for now.
