### ISSUE TITLE
[PRE REVIEW]: grapherator: A Modular Multi-Step Graph Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#520]
**Submitting author:** @jakobbossek (<a href="http://orcid.org/0000-0002-4121-4668">Jakob Bossek</a>)
**Repository:** <a href="https://github.com/jakobbossek/grapherator" target ="_blank">https://github.com/jakobbossek/grapherator</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @gvegayon

**Author instructions**

Thanks for submitting your paper to JOSS @jakobbossek. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jakobbossek if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00520/joss.00520/10.21105.joss.00520.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@gvegayon you reviewed related [work by this author](https://github.com/openjournals/joss-reviews/issues/374) in the past. Would you be able and willing to assist with review here too?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@gpeyre Is this submission of interest to you or your colleagues? It is an R-package on multi-criteria optimization problems on graphs, see also the summary in the [paper 📜 ](https://github.com/openjournals/joss-papers/blob/joss.00520/joss.00520/10.21105.joss.00520.pdf).

**Comment by gvegayon** [comment]
Sure @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @gvegayon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gvegayon

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/528. Feel free to close this issue now!
