### ISSUE TITLE
[REVIEW]: The Experiment Factory: Reproducible Experiment Containers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#521]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/expfactory/expfactory" target ="_blank">https://www.github.com/expfactory/expfactory</a>
**Version:** v3.0.0
**Editor:** @leeper
**Reviewer:** @oesteban
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1117203" target="_blank">10.5281/zenodo.1117203</a>

## Status

[![status](http://joss.theoj.org/papers/91829e3895316bb54bf4a3b5e32cdb71/status.svg)](http://joss.theoj.org/papers/91829e3895316bb54bf4a3b5e32cdb71)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/91829e3895316bb54bf4a3b5e32cdb71"><img src="http://joss.theoj.org/papers/91829e3895316bb54bf4a3b5e32cdb71/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/91829e3895316bb54bf4a3b5e32cdb71/status.svg)](http://joss.theoj.org/papers/91829e3895316bb54bf4a3b5e32cdb71)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://www.github.com/expfactory/expfactory" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@oesteban, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://www.github.com/expfactory/expfactory">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v3.0.0)?
- [x] **Authorship:** Has the submitting author (@vsoch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @oesteban it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00521/joss.00521/10.21105.joss.00521.pdf
```

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1117203 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1117203" target="_blank">10.5281/zenodo.1117203</a> is the archive.

**Comment by leeper** [comment]
@oesteban Can you confirm that you are happy with the package in its current form?

**Comment by oesteban** [comment]
Yes, I do.

**Comment by leeper** [comment]
Thank you, @oesteban!

**Comment by leeper** [comment]
@arfon This one's over to you.

**Comment by arfon** [comment]
@oesteban - many thanks for your review here and to @leeper for editing this submission ✨ 

@vsoch - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00521 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00521/status.svg)](https://doi.org/10.21105/joss.00521)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00521/status.svg)](https://doi.org/10.21105/joss.00521)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by vsoch** [comment]
woohooo thanks @whedon @oesteban @arfon and @leeper ! :avocado: :avocado: :avocado:
