### ISSUE TITLE
[PRE REVIEW]: A self-referential HOWTO on release engineering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#522]
**Submitting author:** @markgalassi (<a href="http://orcid.org/0000-0002-3279-2693">Mark Galassi</a>)
**Repository:** <a href="https://bitbucket.org/markgalassi/toy-releng" target ="_blank">https://bitbucket.org/markgalassi/toy-releng</a>
**Version:** v1.1.0
**Editor:** @danielskatz
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @markgalassi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@markgalassi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #522 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-4bc3ad988bea/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-4bc3ad988bea/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-4bc3ad988bea/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
👋 @danielskatz - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@markgalassi - there are a couple of issues with your paper:

- Please change line 12 of your `paper.md` file to `affiliation: 1`
- It looks like you're referencing `figshare_article.png` but there's no file of that name

In addition, the paper is currently far too short. Please address the author guidelines for ['what should my paper contain'](http://joss.theoj.org/about#paper_structure):

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software
- A list of key references including a link to the software archive
- Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

**Comment by danielskatz** [comment]
Happy New Year to you too, @arfon 

Yes, I can possibly edit this, though at this point, I'm uncertain if it meets JOSS requirements: specifically, that it is about research software that is likely to be cited in other research.

I'll wait on changes and comments from @markgalassi to your and my comments.

**Comment by danielskatz** [comment]
I just found and skimmed toy-releng/howto-paper/toy-releng-howto.tex which appears to be a full-length paper about software in general, rather than a brief paper describing specific software.  If the intent of this submission to JOSS is to publish this long paper, JOSS is not the right venue.  Something like [JORS](https://openresearchsoftware.metajnl.com) might be more appropriate:

>JORS also publishes full-length research papers that cover different aspects of creating, maintaining and evaluating open source research software. The aim of the section is to promote the dissemination of best practice and experience related to the development and maintenance of reusable, sustainable research software.

**Comment by markgalassi** [comment]
Daniel, thank you for looking at it.  JORS seems like a good place to go and I will submit there.

Should I withdraw the paper?

**Comment by arfon** [comment]
> Daniel, thank you for looking at it. JORS seems like a good place to go and I will submit there.

I can do this for you @markgalassi.
