### ISSUE TITLE
[REVIEW]: MixEst: An Estimation Toolbox for Mixture Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#524]
**Submitting author:** @reshadh (<a href="http://orcid.org/0000-0002-3669-760X">Reshad Hosseini</a>)
**Repository:** <a href="https://github.com/utvisionlab/mixest" target ="_blank">https://github.com/utvisionlab/mixest</a>
**Version:** v1.2.0
**Editor:** @arokem
**Reviewer:** @josephhardinee
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/bac8c079865ef33491d7ded0bfef0933/status.svg)](http://joss.theoj.org/papers/bac8c079865ef33491d7ded0bfef0933)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/bac8c079865ef33491d7ded0bfef0933"><img src="http://joss.theoj.org/papers/bac8c079865ef33491d7ded0bfef0933/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/bac8c079865ef33491d7ded0bfef0933/status.svg)](http://joss.theoj.org/papers/bac8c079865ef33491d7ded0bfef0933)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/utvisionlab/mixest" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@josephhardinee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/utvisionlab/mixest">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@reshadh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @josephhardinee it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00524/joss.00524/10.21105.joss.00524.pdf
```

**Comment by arokem** [comment]
@josephhardinee : have you had a chance to take a look at mixest?

**Comment by arokem** [comment]
@josephhardinee : just checking in on this. Have you had a chance to take a look at the software at all? Please let me know if you need any more guidance on how to go about this review.

**Comment by josephhardinee** [comment]
@arokem Sorry, I got part way through then got hit with a bunch of work deadlines. I will finish this review tonight.

**Comment by arokem** [comment]
Hi @josephhardinee : I saw that you posted an issue on the software repo. Do you have any more comments here? Several of the check-boxes are currently unchecked -- does that mean that the authors need to fix some of these things? Thanks!

**Comment by arokem** [comment]
Any news here? I see that many of the check marks are marked. Any other comments, so that authors can fill the other requirements?

**Comment by arfon** [comment]
👋@reshadh - I noticed that the paper has been withdrawn on the JOSS site. Did you do this in error or are you wanting to withdraw your paper?

**Comment by reshadh** [comment]
I actually withdrew the paper. Sorry, I thought the reviewers would be informed on this. Otherwise, I would have mentioned this here.
Thanks!

**Comment by arfon** [comment]
> I actually withdrew the paper. Sorry, I thought the reviewers would be informed on this. Otherwise, I would have mentioned this here.

OK thanks for letting us know @reshadh.

@arokem @josephhardinee - I'm sorry that this paper isn't proceeding, especially given all of your work here @josephhardinee.
