### ISSUE TITLE
[PRE REVIEW]: G³M-f a global gradient-based groundwater modelling framwork

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#525]
**Submitting author:** @rreinecke (<a href="http://orcid.org/0000-0001-5699-8584">Robert Reinecke</a>)
**Repository:** <a href="https://github.com/rreinecke/global-gradient-based-groundwater-model" target ="_blank">rreinecke/global-gradient-based-groundwater-model</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @wkearn

**Author instructions**

Thanks for submitting your paper to JOSS @rreinecke. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rreinecke if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #525 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@rreinecke - thanks for your submission to JOSS.

There are a few issues with your submission as it currently stands:

- The source code doesn't seem to be hosted on a platform such as GitHub/Bitbucket/Sourceforge which is going to make it very difficult for your reviewers to open flag issues that arise during review with your project.
- I don't seem to be able to find a `paper.md` file associated with your submission. Please review [our submission guidelines](http://joss.theoj.org/about#paper_structure) on what this needs to contain.
- I don't seem to be able to find an open source license associated with your submission. All submissions to JOSS must have a clear statement on software licensing and use of the [OSI approved](https://opensource.org/licenses/alphabetical) licenses.

Let me know if you have any questions.

**Comment by rreinecke** [comment]
Hi Arfon,

The code is hosted on github:  
https://github.com/rreinecke/global-gradient-based-groundwater-model  
and should contain all the required files and is liked on the submited  
homepage which is also hosted on github.
I'm sorry but the submission form was unclear on that topic and I've  
submitted the official url. Maybe you can add a hint that it is  
automatically processed and that one should use the github url of the  
repository.

Cheers
Robert.


Quoting Arfon Smith <notifications@github.com>:

**Comment by rreinecke** [comment]
@arfon Should I rather resubmit?

**Comment by arfon** [comment]
> @arfon Should I rather resubmit?

No, that's OK. I've updated the URLs here manually.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wkearn are you interested in reviewing this project? Or do you know people that could?

**Comment by Kevin-Mattheus-Moerman** [comment]
@rreinecke are you able to suggest suitable reviewers?

**Comment by wkearn** [comment]
I'd be happy to review this submission!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @wkearn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wkearn

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/548. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
Fantastic. Let the reviewing begin! 🚀
