### ISSUE TITLE
[REVIEW]: reper - Genome-wide identification, classification and quantification of repetitive elements without an assembled genome

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#527]
**Submitting author:** @nterhoeven (<a href="http://orcid.org/0000-0002-8669-0000">Niklas Terhoeven</a>)
**Repository:** <a href="https://github.com/nterhoeven/reper" target ="_blank">https://github.com/nterhoeven/reper</a>
**Version:** v1.0.0
**Editor:** @mgymrek
**Reviewer:** @jsgalan
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1167969" target="_blank">10.5281/zenodo.1167969</a>

## Status

[![status](http://joss.theoj.org/papers/f0d16a43d8b031695f151ea25e0d47b0/status.svg)](http://joss.theoj.org/papers/f0d16a43d8b031695f151ea25e0d47b0)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f0d16a43d8b031695f151ea25e0d47b0"><img src="http://joss.theoj.org/papers/f0d16a43d8b031695f151ea25e0d47b0/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f0d16a43d8b031695f151ea25e0d47b0/status.svg)](http://joss.theoj.org/papers/f0d16a43d8b031695f151ea25e0d47b0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nterhoeven/reper" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jsgalan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nterhoeven/reper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@nterhoeven) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jsgalan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00527/joss.00527/10.21105.joss.00527.pdf
```

**Comment by jsgalan** [comment]
I still have major problems with the docker installation. 

I am blaming mostly the osx High Sierra docker for Mac for the inconvenience.

Any other reviewer using osx High Sierra and Docker could help?

Best

**Comment by nterhoeven** [comment]
Hi @jsgalan that's a pity. 

As it seems, there are other poeple who have problems with Docker after upgrading to High Sierra. For some [reinstalling docker seems to work](https://github.com/docker/for-mac/issues/2091). I am not a Mac expert, but maybe it is worth a try.

If docker is not working for you, you can take a look at [singularity](http://singularity.lbl.gov). This is a similar tool. Take a look at the [reper wiki](https://github.com/nterhoeven/reper/wiki/Installation#singularity) for instructions to run reper with singularity. 

Message me if you have any questions.

**Comment by nterhoeven** [comment]
Hi @jsgalan,

**Comment by jsgalan** [comment]
Hi @nterhoeven i have been trying with Singularity, i got a few than with Docker, still somehow the VM crashed and wasnt able to restart it, I will try it today again.

**Comment by nterhoeven** [comment]
good. Feel free to open issues if you have any problems

**Comment by jsgalan** [comment]
Hi I am done with the review. 

Where should i submit the review?

Best

**Comment by jsgalan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by jsgalan** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @jsgalan, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
> Where should i submit the review?

@jsgalan - sorry for not being clear - this review issue _is the review_. Please leave comments in this thread for @nterhoeven to respond to.

**Comment by nterhoeven** [comment]
Hi @jsgalan, I just wanted to ask, if you have any news regarding uploading your review comments. I would like to read them :-)

**Comment by jsgalan** [comment]
Hi @nterhoeven 

The paper and implementation are excellent. A few corrections are needed:

- (kmer counts based on jelly sh (Marçais and Kingsford 2011)) <-- check parenthesis use here 
-To create exemplar sequences of each repeat in the genome, the assembled repeats ar clustered using cd-hit ((W. Li and Godzik 2006),(Fu et al. 2012)). <-- should read "repeats are clustered"

Hope this finishes the review process

Best

**Comment by mgymrek** [comment]
Thanks @jsgalan! 
@nterhoeven after you make these minor changes update the thread and then we should be ready to go.

**Comment by nterhoeven** [comment]
Hi @jsgalan and @mgymrek, 

thanks for the comments :-) I created an updated version of the paper.md file. 

How are we going to proceed? I believe I have to create a new release and provide you with a DOI for it. Is this correct?

**Comment by mgymrek** [comment]
Thanks @nterhoeven. @arfon we're ready to accept this. @arfon will be able to help with the next steps.

**Comment by arfon** [comment]
@nterhoeven - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by nterhoeven** [comment]
Hi @arfon,
I created a new release (v1.1.0). Here is the new DOI: 10.5281/zenodo.1167969

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1167969 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1167969" target="_blank">10.5281/zenodo.1167969</a> is the archive.

**Comment by arfon** [comment]
@jsgalan - many thanks for your review here and to @mgymrek for editing this submission ✨ 

@nterhoeven - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00527 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00527/status.svg)](https://doi.org/10.21105/joss.00527)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00527/status.svg)](https://doi.org/10.21105/joss.00527)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by nterhoeven** [comment]
Great :smile: Thanks a lot @arfon @mgymrek @jsgalan
