### ISSUE TITLE
[REVIEW]: grapherator: A Modular Multi-Step Graph Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#528]
**Submitting author:** @jakobbossek (<a href="http://orcid.org/0000-0002-4121-4668">Jakob Bossek</a>)
**Repository:** <a href="https://github.com/jakobbossek/grapherator" target ="_blank">https://github.com/jakobbossek/grapherator</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @gvegayon
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1175943" target="_blank">10.5281/zenodo.1175943</a>

## Status

[![status](http://joss.theoj.org/papers/c6c9ef032a807aa223b3975891728e45/status.svg)](http://joss.theoj.org/papers/c6c9ef032a807aa223b3975891728e45)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c6c9ef032a807aa223b3975891728e45"><img src="http://joss.theoj.org/papers/c6c9ef032a807aa223b3975891728e45/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c6c9ef032a807aa223b3975891728e45/status.svg)](http://joss.theoj.org/papers/c6c9ef032a807aa223b3975891728e45)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jakobbossek/grapherator" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gvegayon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jakobbossek/grapherator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@jakobbossek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @gvegayon it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00528/joss.00528/10.21105.joss.00528.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@jakobbossek @gvegayon review has started here. Let me know if I can help.

**Comment by Kevin-Mattheus-Moerman** [comment]
@gvegayon @jakobbossek how are things going? Could you give an update on where things stand?

**Comment by gvegayon** [comment]
Everything OK, just a bit busy these days. Will get back to @jakobbossek soon.

**Comment by gvegayon** [comment]
Looks good in general. Now I'll take a look at the documentation and code.

**Comment by gvegayon** [comment]
Everything looks good to me. I'm OK with the current state of the package.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00528/joss.00528/10.21105.joss.00528.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@jakobbossek it looks like we are nearly there. Can you check your references for DOI's. Not all currently have DOI's, perhaps they are not available for all but please check.

**Comment by jakobbossek** [comment]
@Kevin-Mattheus-Moerman I tried hard to figure out DOI's for all the cited papers. Unfortuenately there are no DOI's available for most of them.

**Comment by Kevin-Mattheus-Moerman** [comment]
Okay thanks for checking. Did you fix the figure caption?

**Comment by jakobbossek** [comment]
Yes. Fixed it.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00528/joss.00528/10.21105.joss.00528.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
Looks good. Okay. You know the drill. At this point please share the DOI for the archived version of the reviewed software. Then @arfon can take it from there.

**Comment by jakobbossek** [comment]
The DOI is 10.5281/zenodo.1175943
Thanks @Kevin-Mattheus-Moerman and @gvegayon 👏

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1175943 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1175943" target="_blank">10.5281/zenodo.1175943</a> is the archive.

**Comment by arfon** [comment]
@gvegayon - many thanks for your review here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@jakobbossek - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00528 ⚡️:rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00528/status.svg)](https://doi.org/10.21105/joss.00528)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00528/status.svg)](https://doi.org/10.21105/joss.00528)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
