### ISSUE TITLE
[PRE REVIEW]: pyneqsys: Solve symbolically defined systems of non-linear equations numerically

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#529]
**Submitting author:** @bjodah (<a href="http://orcid.org/0000-0003-0596-0222">Björn Dahlgren</a>)
**Repository:** <a href="https://github.com/bjodah/pyneqsys" target ="_blank">https://github.com/bjodah/pyneqsys</a>
**Version:** v0.5.1
**Editor:** @arfon
**Reviewer:** @andim

**Author instructions**

Thanks for submitting your paper to JOSS @bjodah. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bjodah if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00529/joss.00529/10.21105.joss.00529.pdf
```

**Comment by bjodah** [comment]
perhaps @arghdos would be willing to review this paper? `pyneqsys` is similar in structure to the earlier submitted pyodesys package.

**Comment by bjodah** [comment]
Or in the interest of spreading the work on reviewers, maybe @oesteban is interested in reviewing?

**Comment by arghdos** [comment]
@bjodah I'm going to be a bit crazy for the next few weeks trying to wrap up a paper, so it might go faster if someone else reviews.  I can do it if you don't find another reviewer though

-- arghdos

**Comment by bjodah** [comment]
@arghdos perfectly understandable‒good luck with the paper! (and thanks for the offer still)

Judging by what I see on Andreas Mayer's profile (@andim) I think it could be possible that he'd be willing to review?

**Comment by andim** [comment]
I can give it a go! It looks like an interesting package. :+1:

**Comment by arfon** [comment]
> @arfon have I understood it correctly that only an editor can set reviwer using whedon?

Yep. I'll go ahead and do that now.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @andim as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andim

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/531. Feel free to close this issue now!

**Comment by arfon** [comment]
@andim @bjodah - please head over to #531 for the actual review.
