### ISSUE TITLE
[REVIEW]: CAZy-parser a way to extract information from the Carbohydrate-Active enZYmes Database

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#53]
**Submitting author:** @rodrigovrgs (<a href="http://orcid.org/0000-0001-5267-3002">Rodrigo Honorato</a>)
**Repository:** <a href="https://github.com/rodrigovrgs/cazy-parser" target ="_blank">https://github.com/rodrigovrgs/cazy-parser</a>
**Version:** v1.0
**Editor:** @pjotrp 
**Reviewer:** @luizirber 
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.200893" target="_blank">10.5281/zenodo.200893</a>

## Status

[![status](http://joss.theoj.org/papers/f709afe5d720fc6eee82fca277942a46/status.svg)](http://joss.theoj.org/papers/f709afe5d720fc6eee82fca277942a46)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f709afe5d720fc6eee82fca277942a46"><img src="http://joss.theoj.org/papers/f709afe5d720fc6eee82fca277942a46/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f709afe5d720fc6eee82fca277942a46/status.svg)](http://joss.theoj.org/papers/f709afe5d720fc6eee82fca277942a46)
```
### Conflict of interest
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rodrigovrgs/cazy-parser">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
### Functionality
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper

Paper PDF: [10.21105.joss.00053.pdf](https://github.com/openjournals/joss-reviews/files/427710/10.21105.joss.00053.pdf)
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by rvargas** [comment]
I'm not @rodrigovrgs

**Comment by arfon** [comment]
> I'm not @rodrigovrgs

Thanks @rvargas. Seems like @rodrigovrgs gave us the wrong GitHub handle :-|

**Comment by kyleniemeyer** [comment]
That's strange—the "*Submitting author*" looks correct

**Comment by arfon** [comment]
> That's strange—the "Submitting author" looks correct

Yeah but the submitting author also just enters their GitHub handle manually which it looks like @rodrigovrgs did incorrectly.

**Comment by rodrigovrgs** [comment]
> That's strange—the "Submitting author" looks correct
>> Yeah but the submitting author also just enters their GitHub handle manually which it looks like @rodrigovrgs did incorrectly.

Sorry for that, I'm the @rodrigovrgs you are looking for. @arfon, is there a way for me to fix handle?

**Comment by arfon** [comment]
@rodrigovrgs - I've updated this thread with the correct GitHub handle. You can just change your GitHub username on JOSS here: http://joss.theoj.org/profile

**Comment by pjotrp** [comment]
I am not in a position to review this paper, but I would like to note this software consists of about 400 lines of code. I would like to ask the author to confirm *here* that he thinks this software is a valuable contribution to research. I want to point out that once this work has been published it will be visible forever. Adding an example of having used this tool in research would be *strongly* recommended.

**Comment by pjotrp** [comment]
Hi @rodrigovrgs - I am looking for a reviewer for your submission. Do you know anyone who may be interested in reviewing and who is independent?

**Comment by ctb** [comment]
I or someone in my group (@luizirber?) could take this on.

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by luizirber** [comment]
I can review this, @pjotrp

**Comment by arfon** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by pjotrp** [comment]
Hi @luizirber, any idea when you can do the review? Thanks.

**Comment by luizirber** [comment]
I'll do it this weekend.

**Comment by pjotrp** [comment]
@luizirber ping

**Comment by luizirber** [comment]
The software is useful and I think it should be accepted, but some points need to be addressed:

- Installation instruction can be clearer: it only talks about dependencies,
but doesn't say that the repository needs to be downloaded or where to get the
released version. Can you add a setup.py and publish the package to
PyPI? `pip` is the standard way of installing Python packages, this also
increases the reach of your software. I see @jkhan already added an issue for this: https://github.com/rodrigovrgs/cazy-parser/issues/2

- Functionality documentation: there is no exposed API besides the two scripts,
for using from a shell. One of them doesn't have options, and the other one uses `argparse` for options.
Even if there are no options `create-cazy-db.py` could have a `--help` option to at least explain what the command does.

- Automated tests: not available.

- Community guidelines: Kind of. There is an email for contact, but no guidelines
on how to collaborate. A CONTRIBUTING.md file in the repo goes a long way on
addressing this.

**Comment by luizirber** [comment]
Sorry for the delay @pjotrp. @rodrigovrgs, I can help with more details on how to address these points if you want, should I open some issues in the `cazy-parser` repo?

**Comment by pjotrp** [comment]
@luizirber thanks for your review! No need to take extra action on your part.

**Comment by rodrigovrgs** [comment]
@pjotrp @luizirber I'll address the issues as soon as I can, thank you very much!

**Comment by rodrigovrgs** [comment]
@luizirber thanks for your review, I've made some changes to the code and the documentation to fit your feedback and make the code compliant to joss.

> Installation instruction can be clearer: it only talks about dependencies,
but doesn't say that the repository needs to be downloaded or where to get the
released version. Can you add a setup.py and publish the package to
PyPI? pip is the standard way of installing Python packages, this also
increases the reach of your software. I see @jkhan already added an issue for this: rodrigovrgs/cazy-parser#2

I've added the functionality and the issue has been closed.

> Functionality documentation: there is no exposed API besides the two scripts,
for using from a shell. One of them doesn't have options, and the other one uses argparse for options.
Even if there are no options create-cazy-db.py could have a --help option to at least explain what the command does.

The recently implement setup.py installation method makes it so that the scripts can be run from the command line. Also, --help arg has been implemented in the code as well as a means to display the user what argument is missing if that is the case.

> Automated tests: not available.

I'm not quite sure how to produce this, could you please give me one example?

> Community guidelines: Kind of. There is an email for contact, but no guidelines
on how to collaborate. A CONTRIBUTING.md file in the repo goes a long way on
addressing this.

I've added a CONTRIBUTING.md stating which features would be a great addiditon to the cazy-parser.

**Comment by pjotrp** [comment]
Great. @luizirber can you take another look?

**Comment by rodrigovrgs** [comment]
@luizirber when could you take another look at this?

**Comment by luizirber** [comment]
Great work @rodrigovrgs!

About the tests: it is one of the journal requirements, but it is not so easy to test your scripts (because it depends on a big DB generated with one of them). You could set up a subset of the DB and execute the `extract_cazy_ids.py` on it, and check the outputs. Another alternative would be refactoring your scripts into functions to make it easier to test, but I think this gets out of the scope of the submission.

@pjotrp, what would be the recommendation in this case?

**Comment by pjotrp** [comment]
Thank you @luizirber .

@arfon I think we can accept this paper. @rodrigovrgs can look into improving the tests - but I think we are good to go.

**Comment by arfon** [comment]
> @arfon I think we can accept this paper. @rodrigovrgs can look into improving the tests - but I think we are good to go.

👍 ok thanks.

@rodrigovrgs - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by arfon** [comment]
> @rodrigovrgs - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

Bump @rodrigovrgs - we're ready to accept this submission but need you to complete this last step before we can proceed.

**Comment by rodrigovrgs** [comment]
Sorry for the delay @arfon I'll look into it asap.

**Comment by rodrigovrgs** [comment]
I've created an archive with the reviewed software [at Zenodo](https://zenodo.org/record/200893), updated the doi and the master's branch *README.md*. 

[![DOI](https://zenodo.org/badge/65995178.svg)](https://zenodo.org/badge/latestdoi/65995178) 

Is that everything?

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.200893 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.200893" target="_blank">10.5281/zenodo.200893</a> is the archive.

**Comment by arfon** [comment]
> Is that everything?

👍 yes. I'm finishing up the submission now.

**Comment by arfon** [comment]
@luizirber many thanks for the review here and @pjotrp many thanks for editing this submission :zap:

@rodrigovrgs - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00053 ⚡️ 🚀 💥
