### ISSUE TITLE
[REVIEW]: PyDMD: Python Dynamic Mode Decomposition

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#530]
**Submitting author:** @mtezzele (<a href="http://orcid.org/0000-0001-9747-6328">Marco Tezzele</a>)
**Repository:** <a href="https://github.com/mathLab/PyDMD" target ="_blank">https://github.com/mathLab/PyDMD</a>
**Version:** v0.1.0
**Editor:** @jakevdp
**Reviewer:** @jkmacc-LANL
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1171787" target="_blank">10.5281/zenodo.1171787</a>

## Status

[![status](http://joss.theoj.org/papers/734e4326edd5062c6e8ee98d03df9e1d/status.svg)](http://joss.theoj.org/papers/734e4326edd5062c6e8ee98d03df9e1d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/734e4326edd5062c6e8ee98d03df9e1d"><img src="http://joss.theoj.org/papers/734e4326edd5062c6e8ee98d03df9e1d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/734e4326edd5062c6e8ee98d03df9e1d/status.svg)](http://joss.theoj.org/papers/734e4326edd5062c6e8ee98d03df9e1d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mathLab/PyDMD" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jkmacc-LANL, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jakevdp know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mathLab/PyDMD">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@mtezzele) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jkmacc-LANL it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00530/joss.00530/10.21105.joss.00530.pdf
```

**Comment by jakevdp** [comment]
Hi @jkmacc-LANL – the review will take place in this issue. Please see the instructions and checklist above, and feel free to let me know if you have any questions!

**Comment by jkmacc-LANL** [comment]
PyDMD is a well-documented, well-tested, easy to install software package.  Congratulations!  It was a pleasure to review this (...and thanks for your patience).  I only had two minor requests (below).  These aren't show-stoppers, so I didn't create issues for them in the project repo.  With these minor tweaks, this contribution is easily ready to be accepted.

## Functionality

I installed and ran the tutorial notebooks on OS X 10.12.6 with Python 3.6.4.  It went very smoothly.

* [ ] Tutorial notebook 2 requires `ffmpeg`.  I recommended that this be explicit at the top of the notebook, or in the cell (7) that uses it.

## Documentation

* [ ] A slightly longer description of the software on the documentation website landing page would be helpful.  Some of the text from the JOSS paper would be appropriate.

## Software Paper

* [ ] Please add DOIs to the references, where possible.

**Comment by mtezzele** [comment]
@jkmacc-LANL thank you very much! I will proceed in implementing your suggestions in the next few days!

**Comment by mtezzele** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00530/joss.00530/10.21105.joss.00530.pdf
```

**Comment by mtezzele** [comment]
@jakevdp I have implemented all the suggestions and regenerated the pdf. What do I have to do now?

**Comment by jkmacc-LANL** [comment]
@mtezzele I see your changes, and they look good.  Regarding the middle point, my suggestion was to add a slightly longer description to https://mathlab.github.io/PyDMD/, not on the README.  I apologize for the confusion.  Everything else is great👍

**Comment by mtezzele** [comment]
Done! I'm sorry I misread, my fault.

**Comment by jakevdp** [comment]
@jkmacc-LANL, has @mtezzele addressed all your comments?

**Comment by jkmacc-LANL** [comment]
Yes, they are addressed.  Thanks!

**Comment by mtezzele** [comment]
@jakevdp what do I have to do now?

**Comment by arfon** [comment]
@mtezzele - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by ndem0** [comment]
@arfon We have upload the package and this is the DOI for all the versions:
 [https://doi.org/10.5281/zenodo.1171787](https://doi.org/10.5281/zenodo.1171787)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1171787 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1171787" target="_blank">10.5281/zenodo.1171787</a> is the archive.

**Comment by arfon** [comment]
@jkmacc-LANL - many thanks for your review here and to @jakevdp for editing this submission ✨ 

@ndem0 @mtezzele - your paper is now accepted in JOSS and your DOI is https://doi.org/10.21105/joss.00530 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00530/status.svg)](https://doi.org/10.21105/joss.00530)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00530/status.svg)](https://doi.org/10.21105/joss.00530)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by mtezzele** [comment]
Thank you very much @jkmacc-LANL, @jakevdp, and @arfon for your time and efforts!
