### ISSUE TITLE
[PRE REVIEW]: IDESolver: a general purpose integro-differential equation solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#532]
**Submitting author:** @JoshKarpel (<a href="http://orcid.org/0000-0001-5968-9373">Josh Karpel</a>)
**Repository:** <a href="https://github.com/JoshKarpel/idesolver" target ="_blank">https://github.com/JoshKarpel/idesolver</a>
**Version:** v1.0.1
**Editor:** @kyleniemeyer
**Reviewer:** @iljah

**Author instructions**

Thanks for submitting your paper to JOSS @JoshKarpel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@JoshKarpel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @kyleniemeyer - the submitting author suggested you as the editor.

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00532/joss.00532/10.21105.joss.00532.pdf
```

**Comment by JoshKarpel** [comment]
Fixed some errors in `paper.bib` that were causing formatting problems in the PDF (commit is on master branch).

**Comment by kyleniemeyer** [comment]
Hi @JoshKarpel, thanks for your submission. Do you have a suggested reviewer or two that we can start from? I usually try to get one suggested and one non-specialist from the JOSS reviewer pool.

**Comment by JoshKarpel** [comment]
Sounds like a good plan @kyleniemeyer. I took a look at the reviewer pool and found several reviewers who might be interested: @nicoguaro, @jarvist, @leios, and @iljah. They're all marked for Python and expressed some interest in numerical methods/computational physics (which is where I'm coming from) in their topic areas.

**Comment by iljah** [comment]
I can take this.

**Comment by kyleniemeyer** [comment]
@arghdos can you serve as a second reviewer?

**Comment by arghdos** [comment]
@kyleniemeyer yes, i'm willing

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by kyleniemeyer** [comment]
@whedon assign @iljah as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @iljah

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/542. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
OK @JoshKarpel @iljah @arghdos we'll continue the review over in #542
