### ISSUE TITLE
[PRE REVIEW]: genieR: An R package for inference of demographic history of phylogenies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#536]
**Submitting author:** @xiangfstats (<a href="http://orcid.org/0000-0003-3644-7114">Fei Xiang</a>)
**Repository:** <a href="https://github.com/xiangfstats/GenieR" target ="_blank">https://github.com/xiangfstats/GenieR</a>
**Version:** v1.0.0
**Editor:** @biorelated
**Reviewer:** @pboesu 

**Author instructions**

Thanks for submitting your paper to JOSS @xiangfstats. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@xiangfstats if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00536/joss.00536/10.21105.joss.00536.pdf
```

**Comment by arfon** [comment]
@biorelated - would you be willing to edit this submission?

**Comment by biorelated** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by biorelated** [comment]
@whedon assign @biorelated as editor

**Comment by whedon** [comment]
OK, the editor is @biorelated

**Comment by biorelated** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by biorelated** [comment]
@pboesu  @Tgerke Would you be happy to kindly review this work?

**Comment by arfon** [comment]
@biorelated - I think we might need to look for some different reviewers?

**Comment by pboesu** [comment]
@biorelated Apologies for the late reply, I've been in the field the past two weeks.

I'm happy to review this contribution.

**Comment by biorelated** [comment]
@whedon assign @pboesu  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pboesu

**Comment by biorelated** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by biorelated** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/634. Feel free to close this issue now!
