### ISSUE TITLE
[REVIEW]: psrqpy: a python interface for querying the ATNF pulsar catalogue

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#538]
**Submitting author:** @mattpitkin (<a href="http://orcid.org/0000-0003-4548-526X">Matthew Pitkin</a>)
**Repository:** <a href="https://github.com/mattpitkin/psrqpy" target ="_blank">https://github.com/mattpitkin/psrqpy</a>
**Version:** v0.4.3
**Editor:** @arfon
**Reviewer:** @ygrange
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1175303" target="_blank">10.5281/zenodo.1175303</a>

## Status

[![status](http://joss.theoj.org/papers/711dc5566159f6e9f8ea5d07dbfaf5d2/status.svg)](http://joss.theoj.org/papers/711dc5566159f6e9f8ea5d07dbfaf5d2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/711dc5566159f6e9f8ea5d07dbfaf5d2"><img src="http://joss.theoj.org/papers/711dc5566159f6e9f8ea5d07dbfaf5d2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/711dc5566159f6e9f8ea5d07dbfaf5d2/status.svg)](http://joss.theoj.org/papers/711dc5566159f6e9f8ea5d07dbfaf5d2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mattpitkin/psrqpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ygrange, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mattpitkin/psrqpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.3)?
- [x] **Authorship:** Has the submitting author (@mattpitkin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @ygrange it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00538/joss.00538/10.21105.joss.00538.pdf
```

**Comment by ygrange** [comment]
Can one of the editors elaborate on the meaning/background of the question: "Version: Does the release version given match the GitHub release (v0.4.3)?"
Seems like the author has released 0.4.4 by now byt 0.4.3 is still an existing release, even though the paper is part of the master repository and will therefore be part of any future release (which I don't think is a bad thing per se by the way).

**Comment by arfon** [comment]
@ygrange - we just want to make sure we're reviewing something _close_ to the current version. I think it's fine to go ahead and look at the `v0.4.4` release for your review. Also, yes, the version number often updates as a result of the review feedback (and the fact that a paper is now present in the repository).

**Comment by mattpitkin** [comment]
@ygrange Sorry, I had meant to say that I'd made a minor update and updated the release number. I added one function that allows you to download the whole ATNF catalogue and return it as an astropy table.

**Comment by ygrange** [comment]
Thanks for the clarification @mattpitkin !  
Another question to the editor. Is it ok from an ethical perspective for me do do a pull request on the repository if I find an issue I can easily fix?

**Comment by ygrange** [comment]
Installation: seems to fail when using python2.7 because of astropy dependency. See ticket:
https://github.com/mattpitkin/psrqpy/issues/12
Issue seems small to fix. Will continue with the quick fix I came up with.

**Comment by ygrange** [comment]
The paper is short and the tool is not very complex. I think this is typically one of those relatively small tools that can turn out to be very useful for people in the community. I have a few comments:

* I couldn't chech the "community guidelines" box yet. Could you read what it states and add such a statement? I guess a single sentence in the README claiming that people wanting to contribute can do a pull request or open a ticket. Also I would add a sentence claiming that all code contributed in this way will adhere to the open source license of the project. 
* The documentation does not explicitly state what the exact target audience is and what problem it tries to solve. To me as a reviewer it is rather obvious from the package description what those two are (target audience: astronomers who want to use data from the ATNF pulsar catalogue in scripts; problem to solve: a web interface to the catalog is not exactly the best way to interact with the catalog from scripts; you want a better interface, with a stable API). It may be sensible for non-astronomer readers of the journal to add a sentence of two on this in both the article and the documentation. 
* You may want to put an example where the input and output are printed in the README. Alternatively it would be nice to have an integration test that essentially queries a well-known object with one or a few properties that aren't changing anytime son and compare the output to a reference (this could then be added to the tests you do in Travis). 
* I can't find an example of the usage of adsref. Could you add one? 
* The readthedocs is complete and the API is quite well-described. What I miss here is a description of the classes (Querying, Pulsars, and utility functions; the Setup constants seems obvious to me). Could you add a few sentences describing in short what each the class is meant to do so?

**Comment by mattpitkin** [comment]
@ygrange - thanks very much for the useful feedback. I'll try and address your points as soon as possible.

**Comment by mattpitkin** [comment]
I've [added](https://github.com/mattpitkin/psrqpy/commit/ec12e6561a5920daca3e50ad5d3691c37f2ef24d) a statement about development and support to both the README and documentation.

**Comment by mattpitkin** [comment]
I've [added](https://github.com/mattpitkin/psrqpy/commit/983a57bae9cd6228da47f995c11748f6d38a76d8) a statement to the article and documentation about the intended users and purpose of the script.

**Comment by mattpitkin** [comment]
I've [added](https://github.com/mattpitkin/psrqpy/commit/3ca04833859d9d7ffc98159e82762fcc1fae7e17) some actual output to the README file and added a test in the travis build that queries the frequency of the Crab pulsars and checks that it rounds down to 29 Hz (this should be good for another 80 years).

**Comment by mattpitkin** [comment]
I've [added](https://github.com/mattpitkin/psrqpy/commit/23cee57d7b2f9e1cd1cadc70c0140e2c55e6ed80) an example to the documentation on getting an ADS reference link for a pulsar parameter. I've also [added](https://github.com/mattpitkin/psrqpy/commit/d50086c3a53910fd79d80f7cce9ca1457d31c4f7) a bit more (although to be honest not much more) documentation for the QueryATNF and Pulsar classes. After adding the additional docs I bumped the version number up to 0.4.6.

**Comment by mattpitkin** [comment]
@ygrange - I hope my above changes address you main issues. Let me know if there's anything else that you'd like to see added.

**Comment by ygrange** [comment]
Very minor comment: In the usage description the word "txet" appears. 

I think for the rest, the paper is good to go as far as I am concerned.

**Comment by mattpitkin** [comment]
> Very minor comment: In the usage description the word "txet" appears.

Thanks, I've fixed to typo now.

**Comment by arfon** [comment]
@ygrange - just confirming we're good to accept here now?

**Comment by ygrange** [comment]
Yes I am! Sorry for the unclarity.

--
Y. Grange

> Op 18 feb. 2018 om 02:04 heeft Arfon Smith <notifications@github.com>
het volgende geschreven:

**Comment by arfon** [comment]
@mattpitkin - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by mattpitkin** [comment]
@arfon - sure, I've created an archive on Zenodo, with the DOI 10.5281/zenodo.1175303. [![DOI](https://zenodo.org/badge/110824647.svg)](https://zenodo.org/badge/latestdoi/110824647)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1175303 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1175303" target="_blank">10.5281/zenodo.1175303</a> is the archive.

**Comment by arfon** [comment]
@ygrange - many thanks for your review here ✨ 

@mattpitkin - your paper is now accepted in JOSS and your DOI is https://doi.org/10.21105/joss.00538 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00538/status.svg)](https://doi.org/10.21105/joss.00538)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00538/status.svg)](https://doi.org/10.21105/joss.00538)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
