### ISSUE TITLE
[PRE REVIEW]: registr: Registration for Exponential Family Functional Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#539]
**Submitting author:** @julia-wrobel (<a href="http://orcid.org/0000-0001-6783-1421">Julia Wrobel</a>)
**Repository:** <a href="https://github.com/julia-wrobel/registr" target ="_blank">https://github.com/julia-wrobel/registr</a>
**Version:** 0.1
**Editor:** @arfon
**Reviewer:** @corybrunson

**Author instructions**

Thanks for submitting your paper to JOSS @julia-wrobel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@julia-wrobel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #539 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:105:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:92:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:76:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
👋 @julia-wrobel - it looks like there are some issues with the YAML header in your `paper.md` file. Could you modify it so it looks like this: https://gist.github.com/arfon/457fb87bdea6285b53bd23480bfe357a ?

**Comment by julia-wrobel** [comment]
@arfon - I modified the YAML header in the paper.md file. Thanks! Let me know if I need additional changes.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #539 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     79      0 --:--:-- --:--:-- --:--:--    79
Error producing PDF.
! Missing \endgroup inserted.
<inserted text> 
                \endgroup 
l.238 \begin{eqnarray*}

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@julia-wrobel - it looks like Pandoc doesn't like the math syntax that you have. Can you try modifying it to look like this:

```
$$
\begin{aligned}
E\left[Y_i\left(h_i^{-1}(t_i^*)\right) | c_i, h_i^{-1} \right] &=& \mu_i(t)
g\left[\mu_i(t)\right]&=& \alpha(t) + \sum_{k = 1}^K c_{ik}\psi_k(t).
\end{aligned}
$$
```

**Comment by julia-wrobel** [comment]
Thanks @arfon! I just changed it - instead of aligning the equations I just separated them into two. Hopefully that should fix the syntax error!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00539/joss.00539/10.21105.joss.00539.pdf
```

**Comment by arfon** [comment]
@corybrunson - would you be willing to review this submission for JOSS?

**Comment by corybrunson** [comment]
@arfon – yes, i'd be glad to! I will need to refresh on functional analysis and familiarize myself with the JOSS process, and i can say later today if i don't feel qualified. Thank you.

**Comment by arfon** [comment]
> Edit: The technique and implementation are accessible enough to me that i believe i can provide a useful review.

Excellent. Thanks! I'll go ahead and start setting up the review now.

**Comment by arfon** [comment]
@whedon assign @corybrunson as reviewer

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon assign @corybrunson as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @corybrunson as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @corybrunson

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/557. Feel free to close this issue now!

**Comment by arfon** [comment]
@corybrunson - please head over to #557 for the main review issue.

**Comment by corybrunson** [comment]
On it!

**Comment by julia-wrobel** [comment]
awesome, thanks Cory!

**Comment by corybrunson** [comment]
Welcome, Julia! Thanks for the opportunity.
