### ISSUE TITLE
[REVIEW]: Bitstream - Binary Data for Humans

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#541]
**Submitting author:** @boisgera (<a href="http://orcid.org/0000-0003-4685-8099">Sébastien Boisgérault</a>)
**Repository:** <a href="https://github.com/boisgera/bitstream" target ="_blank">https://github.com/boisgera/bitstream</a>
**Version:** v2.2.0
**Editor:** @labarba
**Reviewer:** @bmcfee
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1158626" target="_blank">10.5281/zenodo.1158626</a>

## Status

[![status](http://joss.theoj.org/papers/dd351bf2ed414a623557bb51d75b2536/status.svg)](http://joss.theoj.org/papers/dd351bf2ed414a623557bb51d75b2536)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/dd351bf2ed414a623557bb51d75b2536"><img src="http://joss.theoj.org/papers/dd351bf2ed414a623557bb51d75b2536/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/dd351bf2ed414a623557bb51d75b2536/status.svg)](http://joss.theoj.org/papers/dd351bf2ed414a623557bb51d75b2536)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/boisgera/bitstream" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@bmcfee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/boisgera/bitstream">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.2.0)?
- [x] **Authorship:** Has the submitting author (@boisgera) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @bmcfee it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00541/joss.00541/10.21105.joss.00541.pdf
```

**Comment by labarba** [comment]
Thanks for agreeing to review, @bmcfee. This is where the action happens. Go over the review checklist above, add your comments for the author here, and open issues in the software repo as needed (linking to them in your comments here).

**Comment by bmcfee** [comment]
Comments on the install procedure:

The instructions in the [docs](https://boisgera.github.io/bitstream/installation/) don't quite get all the way there.  The usual `python setup.py install` or `pip install -e .` failed for me, but the script gave an error message saying to use `python setup.py --cython install`, which did work.  It would be helpful if the install docs had a section for building from source, as opposed to installing from pip.

**Comment by bmcfee** [comment]
Comments on the documentation:

> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

This part seems incomplete.  The documentations state the functionality of the package, but not it's target applications or audience.  I get that it provides a fairly low-level operation, but it would be helpful to mention why someone might want to encode data as a bit sequence, and how to use the data coming out.

The section `Snapshots`, which is intended to demonstrate the `State` object's functionality, actually provides some nice example applications of reading wave files and gene sequences.  Maybe these could be broken out or linked up in the overview?

>  Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

Having now read through the docs, I noticed that the section I requested above (install from source) exists within the contributing section.  Maybe it should be moved or cross-referenced from the install section?

>  Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

The docstrings provide plenty of simple usage examples, but no real-world analysis problems.

>  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

Mostly:
- The class doc for `BitStream` would be improved (with a bit of redundancy) to list out the constructor parameters.  As is, the reader has to look up `BitStream.write()` to see how to construct a `BitStream`.  Since the call signature is quite small (two params), this amount of redundancy seems acceptable.
- The docstring for `BitStream.read` doesn't specify the `type` of returned values:
```
data: n items of data

The type of data depends on type and n.
```
Is `data` a list of `self.type` entries?  Some other iterable?

- The `State` class documentation is basically empty.

>  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

Yes -- tests run through doctest and run through travis CI.

>  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Yes to 1 and 2, but no explicit mention of support.

**Comment by bmcfee** [comment]
The paper looks pretty good.  On the last point

> References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

Nothing in the bibliography lists a DOI.

**Comment by boisgera** [comment]
Regenerate pdf paper (added DOI for bitstream reference)

@whedon generate pdf

**Comment by bmcfee** [comment]
@labarba The issues I raised above have all been sufficiently addressed by @boisgera -- I think it's in good shape now.

**Comment by labarba** [comment]
Thank you for your review, @bmcfee !!

@arfon — This submission is ready for acceptance.

Yay!

**Comment by arfon** [comment]
@boisgera - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by boisgera** [comment]
@arfon Here we go: <https://doi.org/10.5281/zenodo.1158626>. 

@labarba, @bmcfee, @arfon, everyone involved, thank you for your time and effort in this review.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1158626 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1158626" target="_blank">10.5281/zenodo.1158626</a> is the archive.

**Comment by arfon** [comment]
Hi @boisgera - could you please turn your bibliography into a bibtex file please? Our editorial tools aren't able to handle a JSON format.

**Comment by boisgera** [comment]
Hi @arfon; it's done, let me know if this works for you.

**Comment by arfon** [comment]
@bmcfee - many thanks for your review here and to @labarba for editing this submission ✨ 

@boisgera - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00541 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00541/status.svg)](https://doi.org/10.21105/joss.00541)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00541/status.svg)](https://doi.org/10.21105/joss.00541)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
