### ISSUE TITLE
[REVIEW]: IDESolver: a general purpose integro-differential equation solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#542]
**Submitting author:** @JoshKarpel (<a href="http://orcid.org/0000-0001-5968-9373">Josh Karpel</a>)
**Repository:** <a href="https://github.com/JoshKarpel/idesolver" target ="_blank">https://github.com/JoshKarpel/idesolver</a>
**Version:** v1.0.1
**Editor:** @kyleniemeyer
**Reviewer:** @iljah
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1162964" target="_blank">10.5281/zenodo.1162964</a>

## Status

[![status](http://joss.theoj.org/papers/9d3ba306da6abb37f7cf357cd9aad695/status.svg)](http://joss.theoj.org/papers/9d3ba306da6abb37f7cf357cd9aad695)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9d3ba306da6abb37f7cf357cd9aad695"><img src="http://joss.theoj.org/papers/9d3ba306da6abb37f7cf357cd9aad695/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9d3ba306da6abb37f7cf357cd9aad695/status.svg)](http://joss.theoj.org/papers/9d3ba306da6abb37f7cf357cd9aad695)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JoshKarpel/idesolver" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@iljah, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JoshKarpel/idesolver">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.1)?
- [x] **Authorship:** Has the submitting author (@JoshKarpel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @iljah it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00542/joss.00542/10.21105.joss.00542.pdf
```

**Comment by kyleniemeyer** [comment]
OK @iljah @arghdos please add your review comments here— @iljah you should fill out the checkbox, and @arghdos you should make sure you agree that everything is filled/not filled (JOSS only officially supports one reviewer at the moment).

**Comment by JoshKarpel** [comment]
I've added a code of conduct and contributor guidelines, along with links to them from the readme, on the master branch.

**Comment by iljah** [comment]
The second link in paper pdf is broken, probably because the doi is given as https... in paper.bib to which another https... is prepended.

**Comment by iljah** [comment]
A question about documentation for @kyleniemeyer: reviewer instructions state e.g. "A high-level overview of this documentation should be included in a README file (or equivalent)." but [the readme file](https://github.com/JoshKarpel/idesolver/blob/master/README.rst) mostly refers to documentation elsewhere. The referred documentation is also in html format, is that ok for joss?

@JoshKarpel according to [reviewer instructions](https://joss.theoj.org/about#reviewer_guidelines) the readme should include the following items, could you please add them to readme or to the html docs?

- [ ] A statement of need
- [x] Installation instructions
- [x] Example usage
- [x] API documentation
- [ ] Tests
- [x] Community guidelines

**Comment by iljah** [comment]
Here are the issues in the target repository I've created while trying out the software: https://github.com/JoshKarpel/idesolver/issues/3 https://github.com/JoshKarpel/idesolver/issues/4

**Comment by JoshKarpel** [comment]
I've started a [branch](https://github.com/JoshKarpel/idesolver/tree/joss-review) to address issues raised during the review.

**Comment by iljah** [comment]
About **installation instructions**: pip is an automatic solution but there doesn't seem to be a list of dependencies anywhere, which are scipy and numpy according to pip.

**Comment by JoshKarpel** [comment]
I've fixed the bad DOI link.

Dependencies are listed explicitly in the [requirements.txt](https://github.com/JoshKarpel/idesolver/blob/master/requirements.txt) file in the top directory of the repository, which is standard for Python/pip projects. I've added a line to the readme which lists the dependencies less formally.

I've added some information about running the test suite to the end of the manual, and linked to that in the readme. I also added a bit more information to the readme about the purpose of IDESolver.

I've responded to both issues over in the target repository.

 (All changes are in the joss-review branch, and will not appear on the hosted documentation website until they're pushed to master.)

**Comment by iljah** [comment]
Another issue: https://github.com/JoshKarpel/idesolver/issues/5

**Comment by iljah** [comment]
There might be missing dependencies in the manual regarding testing: https://github.com/JoshKarpel/idesolver/issues/6

**Comment by JoshKarpel** [comment]
Question for @kyleniemeyer - some of the changes need to be pushed to PyPi as a new version, so the post-review version will actually be 1.0.2, not 1.0.1 (hopefully; assuming no breaking changes are needed). Is it possible to change the version number that goes into the final documents?

**Comment by kyleniemeyer** [comment]
@JoshKarpel don't worry about the version number, it's expected that it will change as a result of reviewer-recommended changes.

**Comment by iljah** [comment]
All issues have been resolved so this looks good to go.

**Comment by kyleniemeyer** [comment]
@arghdos have you had a chance to review this yet?

**Comment by arghdos** [comment]
@kyleniemeyer looks good to me

**Comment by JoshKarpel** [comment]
I've merged the responses to the review issues (they were very helpful, thanks @iljah and @arghdos!), and released v1.0.2.

@kyleniemeyer I got a Zenodo: DOI https://doi.org/10.5281/zenodo.1162964

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00542/joss.00542/10.21105.joss.00542.pdf
```

**Comment by kyleniemeyer** [comment]
Hi @JoshKarpel—looks good (including the paper)!

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.1162964 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1162964" target="_blank">10.5281/zenodo.1162964</a> is the archive.

**Comment by kyleniemeyer** [comment]
Hey @arfon this is now accepted!

**Comment by arfon** [comment]
@iljah @arghdos - many thanks for your reviews here and to @kyleniemeyer for editing this submission ✨ 

@JoshKarpel - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00542 ⚡️ 🚀 :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00542/status.svg)](https://doi.org/10.21105/joss.00542)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00542/status.svg)](https://doi.org/10.21105/joss.00542)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
