### ISSUE TITLE
[PRE REVIEW]: Closed-system 230Th-U age calculation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#543]
**Submitting author:** @tonydoss (<a href="http://orcid.org/0000-0002-3575-0106">Anthony Dosseto</a>)
**Repository:** <a href="https://github.com/tonydoss/UTh_dating" target ="_blank">https://github.com/tonydoss/UTh_dating</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @tonydoss. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@tonydoss if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #543 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by tonydoss** [comment]
sorry... I'm new to this...
shouldn't the paper be tonydoss/UTh_dating/paper_UTh_dating.Rmd?

**Comment by tonydoss** [comment]
re: potential reviewer, @benmarwick could be a potential candidate (although he's already edited my script, so there might be a conflict of interest)

**Comment by arfon** [comment]
> shouldn't the paper be tonydoss/UTh_dating/paper_UTh_dating.Rmd?

Please name your paper `paper.md` and then @whedon should pick it up.

**Comment by tonydoss** [comment]
thanks. I did (shortly after my 2nd post) but looks like @whedon didn't keep trying.

**Comment by arfon** [comment]
Hi @tonydoss - many thanks for your submission to JOSS. Unfortunately this submission doesn't meet our [submission requirements](http://joss.theoj.org/about#submission_requirements) as this falls into the 'minor utility' category.
