### ISSUE TITLE
[PRE REVIEW]: The drake R package: a pipeline toolkit for reproducibility and high-performance computing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#546]
**Submitting author:** @wlandau (<a href="http://orcid.org/0000-0003-1878-3253">William Landau</a>)
**Repository:** <a href="https://github.com/ropensci/drake" target ="_blank">https://github.com/ropensci/drake</a>
**Version:** v5.0.0
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @wlandau. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wlandau if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #546 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00546/joss.00546/10.21105.joss.00546.pdf
```

**Comment by arfon** [comment]
Hi @wlandau. Thanks for your submission - I realize this has been through the rOpenSci workflow so this should be quick.

Could you please flesh out your paper a little more please? The current summary is a little short. As a reminder, JOSS papers should contain:

- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software
- A list of key references including a link to the software archive
- Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

**Comment by wlandau** [comment]
Hi @afron. Looking back, I agree that the paper needed expansion. I added more in https://github.com/ropensci/drake/commit/6763e9a11ec22ee85de79d6e227d0cc27a9e672f, elaborating on  reproducibility and high-performance computing, the two central purposes of `drake`.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00546/joss.00546/10.21105.joss.00546.pdf
```

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/550. Feel free to close this issue now!

**Comment by wlandau** [comment]
Thanks, @afron.
