### ISSUE TITLE
[REVIEW]: bit: a git-based tool for the management of code and data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#549]
**Submitting author:** @jorgeboucas (<a href="http://orcid.org/0000-0002-9412-7592">Jorge Boucas</a>)
**Repository:** <a href="https://github.com/mpg-age-bioinformatics/bit" target ="_blank">https://github.com/mpg-age-bioinformatics/bit</a>
**Version:** 0.1.1
**Editor:** @acabunoc
**Reviewer:** @dvalters, @paulklemm
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/3714b0dbb3e3e5acb4277537d7093dee/status.svg)](http://joss.theoj.org/papers/3714b0dbb3e3e5acb4277537d7093dee)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3714b0dbb3e3e5acb4277537d7093dee"><img src="http://joss.theoj.org/papers/3714b0dbb3e3e5acb4277537d7093dee/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3714b0dbb3e3e5acb4277537d7093dee/status.svg)](http://joss.theoj.org/papers/3714b0dbb3e3e5acb4277537d7093dee)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mpg-age-bioinformatics/bit" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer 1 instructions & questions

@dvalters, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @acabunoc know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpg-age-bioinformatics/bit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.1)?
- [x] **Authorship:** Has the submitting author (@jorgeboucas) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

## Reviewer 2 instructions & questions

@paulklemm, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @acabunoc know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpg-age-bioinformatics/bit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.1)?
- [x] **Authorship:** Has the submitting author (@jorgeboucas) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @dvalters it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00549/joss.00549/10.21105.joss.00549.pdf
```

**Comment by acabunoc** [comment]
@dvalters & @paulklemm -- I duplicated the reviewer checklist so you should each have your own list to check off. thanks & let me know if you have any questions!

**Comment by arfon** [comment]
@dvalters & @paulklemm - friendly reminder to get to this review when you get a chance.

**Comment by dvalters** [comment]
Hi @jorgeboucas, I've raised a few issues in the issue tracker in the submission's github repository (see linked issues above). My other comments so far are:

1. Documentation is a bit sparse - there is a 'man page' style usage guide in the README.md file, which I think might meet the minimum requirements for documentation (@acabunoc?) but I could not find any separate documentation linked for the software. (My impression is that JOSS submissions should have separate documentation pages _in addition_ to a high-level overview in the README file, but please correct me if I'm wrong @acabunoc)

2. No tests per se. There are examples of usage in the README.md file, but again, these are fairly limited, and I'm not sure they are sufficient under the JOSS guidelines: 

> Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

3. No community guidelines present.

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by arfon** [comment]
@paulklemm - please carry out your review here when you get a chance?

@jorgeboucas - also, please take a look at @dvalters' comments and provide feedback.

**Comment by arfon** [comment]
:wave: how are we getting along here? @dvalters, @paulklemm - it looks like you're reviews aren't complete yet but also we've not heard back from @jorgeboucas.

**Comment by dvalters** [comment]
@arfon ready to proceed, but https://github.com/mpg-age-bioinformatics/bit/issues/6 question needs resolved before can test software

**Comment by paulklemm** [comment]
Also ready to proceed, require issue https://github.com/mpg-age-bioinformatics/bit/issues/8 to be solved to test the software.

**Comment by arfon** [comment]
@jorgeboucas - how are we getting along here?

**Comment by arfon** [comment]
Hi @jorgeboucas - are you still interested in pursuing this publication in JOSS?

**Comment by arfon** [comment]
@acabunoc, @dvalters, @paulklemm - I'm sorry to say that we're going to have to close this review. I've been unable to get hold of @jorgeboucas over the past few months and so I have to assume he's no longer interested in pursuing this publication.

My apologies for any time wasted here.
