### ISSUE TITLE
[PRE REVIEW]: CheckQC: Quick quality control of Illumina sequencing runs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#551]
**Submitting author:** @johandahlberg (<a href="http://orcid.org/0000-0001-6962-1460">Johan Dahlberg</a>)
**Repository:** <a href="https://github.com/Molmed/checkQC" target ="_blank">https://github.com/Molmed/checkQC</a>
**Version:** v1.2.0
**Editor:** @pjotrp
**Reviewer:** @brainstorm

**Author instructions**

Thanks for submitting your paper to JOSS @johandahlberg. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@johandahlberg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #551 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00551/joss.00551/10.21105.joss.00551.pdf
```

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by brainstorm** [comment]
Happy to review this one there's nobody being pre-assigned at the moment? :)

**Comment by pjotrp** [comment]
Excellent. Thanks @brainstorm.

**Comment by pjotrp** [comment]
@whedon assign @brainstorm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brainstorm

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/556. Feel free to close this issue now!
