### ISSUE TITLE
[PRE REVIEW]: ChemPy: A package useful for chemistry written in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#552]
**Submitting author:** @bjodah (<a href="http://orcid.org/0000-0003-0596-0222">Björn Dahlgren</a>)
**Repository:** <a href="https://github.com/bjodah/chempy" target ="_blank">github.com/bjodah/chempy</a>
**Version:** v0.6.3
**Editor:** @kyleniemeyer
**Reviewer:** @bryanwweber

**Author instructions**

Thanks for submitting your paper to JOSS @bjodah. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bjodah if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #552 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
👋🏻 @kyleniemeyer - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00552/joss.00552/10.21105.joss.00552.pdf
```

**Comment by kyleniemeyer** [comment]
@bryanwweber would you be able to review this submission?

**Comment by bryanwweber** [comment]
@kyleniemeyer Yes, I can review this

**Comment by kyleniemeyer** [comment]
@bryanwweber thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @bryanwweber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bryanwweber

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/565. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
ok @bjodah @bryanwweber we'll hold the actual review in #565
