### ISSUE TITLE
[PRE REVIEW]: PetIBM: toolbox and applications of the immersed-boundary method on distributed-memory architectures

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#553]
**Submitting author:** @labarba (<a href="http://orcid.org/0000-0001-5812-2711">Lorena A. Barba</a>)
**Repository:** <a href="https://github.com/barbagroup/PetIBM" target ="_blank">https://github.com/barbagroup/PetIBM</a>
**Version:** v0.3
**Editor:** @kyleniemeyer
**Reviewer:** @jedbrown

**Author instructions**

Thanks for submitting your paper to JOSS @labarba. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@labarba if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00553/joss.00553/10.21105.joss.00553.pdf
```

**Comment by labarba** [comment]
We suggested @kyleniemeyer as editor, since he edited our previous submission of a related code: 
https://github.com/openjournals/joss-reviews/issues/301

For reviewer, we think @jedbrown would be great, if he's willing. He reviewed 
https://github.com/openjournals/joss-reviews/issues/280
... which is used in PetIBM.

**Comment by kyleniemeyer** [comment]
Sure, I can review this one.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by labarba** [comment]
Suggested you as an editor.

We really don't

**Comment by labarba** [comment]
Oops. Hit the wrong button.

**Comment by labarba** [comment]
Just wanted to cancel my comment to say that I suggested you as editor, rather than reviewer.

We really need more editors for computational mechanics and HPC.

**Comment by kyleniemeyer** [comment]
@labarba probably, but for the time being @katyhuff and I can probably handle all of your submission 😀

**Comment by jedbrown** [comment]
I'm available if needed.

**Comment by kyleniemeyer** [comment]
@jedbrown thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @jedbrown as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jedbrown

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/558. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
ok @labarba @jedbrown we'll proceed with the actual review in #558
