### ISSUE TITLE
[PRE REVIEW]: TSrepr R package: Time Series Representations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#554]
**Submitting author:** @PetoLau (<a href="http://orcid.org/0000-0002-3501-8783">Peter Laurinec</a>)
**Repository:** <a href="https://github.com/PetoLau/TSrepr" target ="_blank">https://github.com/PetoLau/TSrepr</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewer:** @kellieotto

**Author instructions**

Thanks for submitting your paper to JOSS @PetoLau. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@PetoLau if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00554/joss.00554/10.21105.joss.00554.pdf
```

**Comment by arfon** [comment]
👋🏻 @arokem - the submitting author suggested you as the handling editor.

**Comment by arokem** [comment]
Sure. I can edit this. 

Is this one of these cases that should also be reviewed by rOpenSci in parallel?

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
👋 @kellieotto : would you like to review this submission for JOSS?

**Comment by kellieotto** [comment]
Hi @arokem.  Yes I'd be happy to review it.

**Comment by arokem** [comment]
@whedon assign @kellieotto as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kellieotto

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/577. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks @kellieotto : please head over to #577 for the review. I'll close this one.
