### ISSUE TITLE
[REVIEW]: CheckQC: Quick quality control of Illumina sequencing runs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#556]
**Submitting author:** @johandahlberg (<a href="http://orcid.org/0000-0001-6962-1460">Johan Dahlberg</a>)
**Repository:** <a href="https://github.com/Molmed/checkQC" target ="_blank">https://github.com/Molmed/checkQC</a>
**Version:** v1.2.0
**Editor:** @pjotrp
**Reviewer:** @brainstorm
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1166052" target="_blank">10.5281/zenodo.1166052</a>

## Status

[![status](http://joss.theoj.org/papers/e5da9a3f0148719f243685e2647300a9/status.svg)](http://joss.theoj.org/papers/e5da9a3f0148719f243685e2647300a9)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e5da9a3f0148719f243685e2647300a9"><img src="http://joss.theoj.org/papers/e5da9a3f0148719f243685e2647300a9/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e5da9a3f0148719f243685e2647300a9/status.svg)](http://joss.theoj.org/papers/e5da9a3f0148719f243685e2647300a9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Molmed/checkQC" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@brainstorm, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Molmed/checkQC">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@johandahlberg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @brainstorm it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00556/joss.00556/10.21105.joss.00556.pdf
```

**Comment by pjotrp** [comment]
Dear @johandahlberg, thanks for your interesting submission. Do you mind going through above check list and make sure the reviewer can check the boxes ahead of his going through it? Thanks.

**Comment by johandahlberg** [comment]
Hi @pjotrp!

Thank you for taking this under consideration for publication. I see that @brainstorm has been assigned to review this paper. While I believe that Roman is very well qualified to review this submission, I believe that there might be a conflict of interest, since we are currently collaborating on another project.

As for the checkboxes do I understand you correctly that you want me to look at them and make sure that they can be checked by the reviewer? Not that I should actually check them?

**Comment by pjotrp** [comment]
@brainstorm, what is the shared project you are working on? Is it overlapping in any way with this submission? Are you confident you can review independently?

@johandahlberg correct. You can't check them yourself. It is just to prevent some unnecessary work. Just state you are confident they can be checked.

**Comment by johandahlberg** [comment]
@pjotrp I believe we should be able to tick the boxes, with the exception that all the references do not have DOIs. Since some of the software references are websites, since to the best of my knowledge there are no other references for them. Is that alright?

**Comment by pjotrp** [comment]
Should be good. OK, we await @brainstorm

**Comment by brainstorm** [comment]
@pjotrp Arteria/StackStorm (projects I'm collaborating with right now) **could** use CheckQC in some way but they don't by default. Similar analogy: would reviewing a particular tool enter in a conflict of interest if I was using/developing, say, Galaxy core?

At least that's my interpretation, hope I'm not missing the point, this is important to clarify early on.

**Comment by johandahlberg** [comment]
In the interest of full disclosure I think that it should be noted that me and @brainstorm are co-authoring a paper about the Arteria project. Unfortunately I interpret this as grounds for a conflict of interest. 

I would like to point out that I still believe that @brainstorm is very well qualified to review this submission. However, to ensure that there can be no ethical ambiguities I think that it would be better if another reviewer was assigned. I will of course defer to any decision made by the editor(s).

**Comment by pjotrp** [comment]
Lets ask the EIC. Dear @arfon, I think with Roman @brainstorm that he is not having a COI because he happens to be on a different paper with the author. Roman came recommended by another co-worker and sees no conflict of interest himself. I have the intention of giving an all clear. Are you OK with this?

**Comment by arfon** [comment]
> Are you OK with this?

👍 I think this is OK. Thanks for disclosing this @johandahlberg (and for checking @pjotrp).

**Comment by pjotrp** [comment]
OK, @brainstorm, all yours :)

**Comment by brainstorm** [comment]
```

**Comment by brainstorm** [comment]
Thanks @pjotrp, going ahead ;)

@johandahlberg, first bump in the road:

```
$ checkqc 171128_A00119_0035_BH2CTLDSXX
INFO     ------------------------
INFO     Starting checkQC (1.2.0)
INFO     ------------------------
INFO     Runfolder is: 171128_A00119_0035_BH2CTLDSXX/
INFO     No config file specified, using default config from /home/limsadmin/.miniconda3/lib/python3.6/site-packages/checkQC/default_config/config.yaml.
INFO     Run summary
INFO     -----------
INFO     Instrument and reagent version: novaseq_v1
INFO     Read length: 150-150
INFO     Enabled handlers and their config values were:
INFO     	ClusterPFHandler Error=unknown Warning=1400
INFO     	Q30Handler Error=unknown Warning=75
INFO     	ErrorRateHandler Error=unknown Warning=5
INFO     	ReadsPerSampleHandler Error=700 Warning=unknown
INFO     	UndeterminedPercentageHandler Error=10 Warning=unknown
ERROR    Could not identify a Stats.json file at: 171128_A00119_0035_BH2CTLDSXX/Unaligned/Stats/Stats.json. This file is created by bcl2fastq, please ensure that you have run bcl2fastq on this runfolder before running checkqc.
ERROR    Finished with fatal qc errors and will exit with non-zero exit status.

$ find 171128_A00119_0035_BH2CTLDSXX -iname Stats.json
171128_A00119_0035_BH2CTLDSXX/Stats/Stats.json
```

**Comment by brainstorm** [comment]
Also, regarding the statement of need and towards publishing your paper, could you comment/compare with [basecallQC](https://bioconductor.org/packages/release/bioc/vignettes/basecallQC/inst/doc/basecallQC.html)?

**Comment by johandahlberg** [comment]
I have addressed the problems you were having with not finding the `Stats.json` file. The path to the `Stats` directory is configurable now, and the default should match up with the default settings for `bcl2fastq`. So far this has only been merged into master. Before moving on to creating a new release I want to know if that means that I should also update the release version in `codemeta.json`? And if you want me to create a release now for you to test, or if you want to keep on testing straight from the master branch? I'm unsure what your prefered process is with regards to that.

Thanks for bringing basecallQC to my attention. I had not seen it before. From what I understand based on the documentation you referenced, the purpose of the basecallQC library is somewhat different from what we are trying to achive with CheckQC.

The features listed for basecallQC include: 
 - cleaning samplesheets
 - convering samplesheets between bcl2fastq version
 - creating base masks to be used by bcl2fastq
 - creating summary tables and plots based on demultiplexed data

On the first three points, there is no overlap in functionality. On the last point there might be a small amount of overlap in that both programs/libraries read data from the Illumina runfolder, but with the difference that CheckQC is expliclity constructed to be used to automatically check the values gathered against a set of criteria. I therefore see these to as complementary to each other. Would you like me to add a reference and a short section comparing CheckQC with basecallQC to the paper?

**Comment by brainstorm** [comment]
Thanks for the fix Johan!

I think that the editor will link/refer to the latest version and assign a DOI, so yes, in the interest of having a working package "out of the box" as reflected in the README, you should update accordingly.

Regarding basecallQC, I don't think a whole section is worth it, but a small mention as you just did here should suffice.

I'm done here, nice tool overall, when you are done with those latest additions, please at-ping Pjotr so that he can generate the DOI and do the rest ;)

**Comment by johandahlberg** [comment]
@brainstorm I've fixed your suggestions now. And I've created a new release: https://github.com/Molmed/checkQC/releases/tag/v1.3.0 This is now available on PyPI.

@pjotrp If I understand @brainstorm above this is done now. As noted above, there is a new release (v1.3.0), and I've updated the `codemeta.json` to reflect this.

**Comment by pjotrp** [comment]
@arfon ready to RoR

**Comment by arfon** [comment]
@johandahlberg - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by johandahlberg** [comment]
@arfon Thank you! I have created a DOI for the specific version (v1.3.0) here: https://doi.org/10.5281/zenodo.1166052. And the DOI for any version of the software is this one: https://doi.org/10.5281/zenodo.1166051 I'm unsure about which one you need, so now you have both.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1166052 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1166052" target="_blank">10.5281/zenodo.1166052</a> is the archive.

**Comment by arfon** [comment]
@brainstorm - many thanks for your review here and to @pjotrp for editing this submission ✨ 

@johandahlberg - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00556 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00556/status.svg)](https://doi.org/10.21105/joss.00556)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00556/status.svg)](https://doi.org/10.21105/joss.00556)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
