### ISSUE TITLE
[PRE REVIEW]: ChebTools: C++11 (and Python) tools for working with Chebyshev expansions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#559]
**Submitting author:** @ianhbell (<a href="http://orcid.org/0000-0003-1091-9080">Ian Bell</a>)
**Repository:** <a href="https://github.com/usnistgov/ChebTools" target ="_blank">https://github.com/usnistgov/ChebTools</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @drvinceknight

**Author instructions**

Thanks for submitting your paper to JOSS @ianhbell. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ianhbell if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #559 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     40      0 --:--:-- --:--:-- --:--:--    40
Error producing PDF.
! LaTeX Error: File `fancyvrb.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.153 \newcommand

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@ianhbell - thanks for your submission to JOSS. From a quick inspection of the source code on GitHub it looks like this software is released under some kind of public domain notice.

Unfortunately we don't accept submissions that don't have an [OSI-approved open source license](https://opensource.org/licenses). 

I realize this is potentially an issue for government employees and we've discussed this at length already here. Please take a look at this issue for background and let me know if you think you might be able to add a license to this project: https://github.com/openjournals/joss/issues/179

**Comment by ianhbell** [comment]
I just spoke with legal at NIST, and it seems that we can do a dual-license: public domain (whatever that *actually* means) in the USA, and something else (MIT?) elsewhere.  At least that was the most recent ruling I got.  I'll be in touch just as soon as I have some new license verbiage.

**Comment by arfon** [comment]
> I just spoke with legal at NIST, and it seems that we can do a dual-license: public domain (whatever that actually means) in the USA, and something else (MIT?) elsewhere. At least that was the most recent ruling I got. I'll be in touch just as soon as I have some new license verbiage.

:+1: fantastic. Dual-licensing is fine for us.

**Comment by ianhbell** [comment]
Update: License updated to MIT-ish.  

As this is my first (of hopefully many) submissions to JOSS, I didn't fully understand the two-sentence snippet in the submission would be visible to the public on the paper submission record.  Any chance you could remove the P.S. that I added to my submission?  I don't seem to be able to.

**Comment by ianhbell** [comment]
Some recommended reviewers: @drvinceknight @jordigh @JaroslavHron

**Comment by drvinceknight** [comment]
I would be happy to review. To the editor: my knowledge of C++ is not great but I'm familiar with Python and the field.

**Comment by labarba** [comment]
I can edit this one, @arfon -- one question: the "modified MIT" license ... is it really _modified_ from MIT? Because if so, it would not be OSI-approved. I has to be the _actual_ MIT license, no?

**Comment by ianhbell** [comment]
Pinged our legal folks, a clean MIT license plus a note in the README seems sufficient, but I need final confirmation.

**Comment by arfon** [comment]
> Pinged our legal folks, a clean MIT license plus a note in the README seems sufficient, but I need final confirmation.

Excellent. Thanks @ianhbell

**Comment by ianhbell** [comment]
One more try...  Does this work?

**Comment by arfon** [comment]
> One more try... Does this work?

If you could just remove the 'Terms of use' section at the top of the `LICENSE` file I think we'll be set: https://github.com/usnistgov/ChebTools/blob/master/LICENSE#L1-L4

**Comment by ianhbell** [comment]
Done.

**Comment by arfon** [comment]
> I can edit this one, @arfon -- one question: the "modified MIT" license ... is it really modified from MIT? Because if so, it would not be OSI-approved. I has to be the actual MIT license, no?

@labarba - thanks for volunteering to edit this submission. I think we've resolved the licensing concerns here now.

**Comment by ianhbell** [comment]
It's no longer a modified MIT license, though it was before.  Working for the US Government and writing open-source software is at times a frustrating exercise...

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by arfon** [comment]
> It's no longer a modified MIT license, though it was before. Working for the US Government and writing open-source software is at times a frustrating exercise...

Thanks so much for working this through with us @ianhbell.

**Comment by labarba** [comment]
@drvinceknight --Are you still willing to review this submission?

Another potential reviewer, if available and willing, might. be @paulcon ?

**Comment by drvinceknight** [comment]
> @drvinceknight --Are you still willing to review this submission?

Yup. :+1:

**Comment by labarba** [comment]
@whedon assign @drvinceknight as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @drvinceknight

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/569. Feel free to close this issue now!
