### ISSUE TITLE
[PRE REVIEW]: PyMap3D: 3-D coordinate conversions for terrestrial and geospace environments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#560]
**Submitting author:** @scivision (<a href="http://orcid.org/0000-0002-1637-6526">Michael Hirsch</a>)
**Repository:** <a href="https://github.com/scivision/pymap3d" target ="_blank">https://github.com/scivision/pymap3d</a>
**Version:** v1.5.0
**Editor:** @lheagy
**Reviewer:** @hugoledoux

**Author instructions**

Thanks for submitting your paper to JOSS @scivision. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@scivision if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #560 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     64      0 --:--:-- --:--:-- --:--:--    64
Error reading bibliography ./paper.bib (line 10, column 3):
unexpected "m"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
👋 @lheagy - the submitting author suggested you as the handling editor.

**Comment by lheagy** [comment]
Hi, @arfon, this looks identical to #555, did something go awry here?

**Comment by scivision** [comment]
Hi Lindsey, I withdrew and resubmitted as I submitted an old release--I resubmitted with the current pymap3d release.

**Comment by lheagy** [comment]
Ok, Thanks @scivision, so #555 should be closed? and we can look for reviewers here?

**Comment by scivision** [comment]
Yes exactly

**Comment by lheagy** [comment]
:wave: Hi @jsta, @nuest, @fgnievinski, @hugoledoux, @sgrieve, @fil, would any of you be willing to review this submission for JOSS?

**Comment by sgrieve** [comment]
@lheagy I'm pretty busy over the coming weeks so won't have a chance to review this. Hopefully someone else on the list can, if not come back to me and I'll fit it in by the end of the month.

**Comment by Fil** [comment]
@lheagy  though it looks interesting, it's really too far from my field. Sorry!

**Comment by hugoledoux** [comment]
@lheagy I can do a review, but I need ~3-4 weeks, next 2 weeks is very difficult. If okay with you I'm happy to do it.

**Comment by jsta** [comment]
Like Fil, I feel this is outside my area of expertise. Best of luck!

**Comment by lheagy** [comment]
Thanks for getting back so quickly, @hugoledoux, there are a couple other people I can ask, but if you would be willing to do the review in the next 3-4 weeks, that would be great. I will keep you posted

**Comment by lheagy** [comment]
:wave: Hi @leouieda would you be willing and interested to review this submission for JOSS?

**Comment by lheagy** [comment]
@leouieda has offered to provide input on the review as well.

**Comment by lheagy** [comment]
@whedon assign @hugoledoux as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hugoledoux

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/580. Feel free to close this issue now!
