### ISSUE TITLE
[PRE REVIEW]: interpacf: compute autocorrelation functions in light curves with missing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#561]
**Submitting author:** @bmorris3 (<a href="http://orcid.org/0000-0003-2528-3409">Brett Morris</a>)
**Repository:** <a href="https://github.com/bmorris3/interp-acf" target ="_blank">https://github.com/bmorris3/interp-acf</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @bmorris3. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bmorris3 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #561 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by bmorris3** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by bmorris3** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00561/joss.00561/10.21105.joss.00561.pdf
```

**Comment by arfon** [comment]
Hi @bmorris3 - apologies for taking so very long to get to this submission - this looks like a very nice piece of code but unfortunately it's too small to be considered for a JOSS submission. 

JOSS doesn't accept what we consider ['minor utility packages'](http://joss.theoj.org/about#submission_requirements), and single-feature code like this submission falls in that category.

We encourage you to look at some of the accepted submissions to get a better idea of the scale of projects that the community considers research software and potentially expand on this submission to make a more fully-featured software package.

**Comment by danielskatz** [comment]
Hi @arfon - I think we should now close/withdraw this submission
