### ISSUE TITLE
[PRE REVIEW]: EFAshiny: An User-Friendly Shiny Application for Exploratory Factor Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#562]
**Submitting author:** @PsyChiLin (<a href="http://orcid.org/0000-0002-4381-7163">Chi-Lin Yu</a>)
**Repository:** <a href="https://github.com/PsyChiLin/EFAshiny" target ="_blank">https://github.com/PsyChiLin/EFAshiny</a>
**Version:** 1.0.0
**Editor:** @cMadan
**Reviewer:** @DominiqueMakowski

**Author instructions**

Thanks for submitting your paper to JOSS @PsyChiLin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@PsyChiLin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #562 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
👋 @cMadan - the submitting author suggested you as the handling editor

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #562 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:86:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:74:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by cMadan** [comment]
@PsyChiLin, this looks like a solid submission and everything seems to be in order to start the review. Do you have any suggestions for potential reviewers?

**Comment by PsyChiLin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00562/joss.00562/10.21105.joss.00562.pdf
```

**Comment by PsyChiLin** [comment]
@cMadan 
After searching papers in JOSS, I find a few potential reviewers who have submitted or have reviewed psychology-related projects recently.
@DominiqueMakowski @andrewheusser @RichardLitt 
Also look forward to your suggestions !

**Comment by DominiqueMakowski** [comment]
@cMadan @PsyChiLin I will look into that ☺️

**Comment by cMadan** [comment]
@DominiqueMakowski, just to check--are you volunteering to be a reviewer here?

**Comment by RichardLitt** [comment]
I won't have the time for this at the moment; apologies!

**Comment by DominiqueMakowski** [comment]
@cMadan Yes

**Comment by PsyChiLin** [comment]
@cMadan Thanks for your kind assistance.
@DominiqueMakowski  Hope you have a wonderful review process. Look forward to your suggestions 😊

**Comment by cMadan** [comment]
@DominiqueMakowski, great! I'll go ahead and start the review process then :)

**Comment by cMadan** [comment]
@whedon assign @DominiqueMakowski as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @DominiqueMakowski

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/567. Feel free to close this issue now!

**Comment by PsyChiLin** [comment]
@cMadan @DominiqueMakowski, many thanks !
