### ISSUE TITLE
[REVIEW]: ChemPy: A package useful for chemistry written in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#565]
**Submitting author:** @bjodah (<a href="http://orcid.org/0000-0003-0596-0222">Björn Dahlgren</a>)
**Repository:** <a href="https://github.com/bjodah/chempy" target ="_blank">github.com/bjodah/chempy</a>
**Version:** v0.6.3
**Editor:** @kyleniemeyer
**Reviewer:** @bryanwweber
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1212469" target="_blank">10.5281/zenodo.1212469</a>

## Status

[![status](http://joss.theoj.org/papers/68868db6e596dd7e479aed02c0fca1df/status.svg)](http://joss.theoj.org/papers/68868db6e596dd7e479aed02c0fca1df)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/68868db6e596dd7e479aed02c0fca1df"><img src="http://joss.theoj.org/papers/68868db6e596dd7e479aed02c0fca1df/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/68868db6e596dd7e479aed02c0fca1df/status.svg)](http://joss.theoj.org/papers/68868db6e596dd7e479aed02c0fca1df)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="www.github.com/bjodah/chempy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@bryanwweber, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="www.github.com/bjodah/chempy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.3)?
- [x] **Authorship:** Has the submitting author (@bjodah) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @bryanwweber it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #565 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
here is the initial version of the compiled paper: https://github.com/openjournals/joss-papers/blob/joss.00552/joss.00552/10.21105.joss.00552.pdf

**Comment by bryanwweber** [comment]
@bjodah Since this comment is related more to the paper than to the software, I'll put it here. You should specify the target audience for the software - is it undergraduates doing homework problems, research scientists, government agencies, teachers, etc.

**Comment by kyleniemeyer** [comment]
@bryanwweber I noticed a few unchecked boxes above—are those issues related to the bjodah/chempy#80 and bjodah/chempy#81 issues you filed?

**Comment by bjodah** [comment]
Sorry, I haven't addressed those yet. @bryanwweber pointed out that I don't provide conda packages for all platforms (only Linux). So I have been working on trying to support all (optional) dependencies of ChemPy for both OS X and Windows, but since many of them needs to be compiled with quite recent C++ features that endeavor quickly turned into a real rabbit hole.

I think I will just do what @bryanwweber suggested and clearly state that Linux is currently the "officially supported" platform, and then I'll continue to work on adding support for more platforms at a later stage. (I know people have gotten many things to work on OS X and windows using pip so it is doable but I don't have any computers with those systems for testing at the moment).

**Comment by kyleniemeyer** [comment]
@bjodah ok—regarding the platform issue, that seems reasonable as long as you are clear. If you do limit the conda route to Linux, then it would be helpful to explain how the package can be installed/used on other platforms.

**Comment by kyleniemeyer** [comment]
@arfon FYI, the *Repository* link above seems to have some extra junk prepended on it, not sure if that has already been fixed in whedon: `https://github.com/openjournals/joss-reviews/issues/www.github.com/bjodah/chempy` instead of `www.github.com/bjodah/chempy`

**Comment by bryanwweber** [comment]
@kyleniemeyer @bjodah The two about the "Statement of Need" are addressed by my comment on this issue: https://github.com/openjournals/joss-reviews/issues/565#issuecomment-363984324 The installation instructions are covered by the two issues in the ChemPy repository (and I'm satisfied with the response to them generally, which I'll mark on those two issues). The last one is the functionality testing, which is on me, I didn't get a chance to do that yet, will do so ASAP.

**Comment by kyleniemeyer** [comment]
Hi @bryanwweber have you been able to complete your review?

**Comment by bryanwweber** [comment]
@kyleniemeyer @bjodah Sorry! This fell off my radar. I'll try finish ASAP

**Comment by bjodah** [comment]
The second entry in the references in https://github.com/openjournals/joss-papers/blob/joss.00552/joss.00552/10.21105.joss.00552.pdf does not render properly. Any idea what's going wrong there?

**Comment by kyleniemeyer** [comment]
@bjodah the reference style we use avoids repeating the same author name multiple times in a row, so the line is just to indicate the same author as the reference before it

**Comment by bryanwweber** [comment]
I'm satisfied that the package functions as specified, with the exception of an error in one of the demo scripts (linked above, issue on chempy repo). However, the paper appears to have not been updated with the target audience, as suggested in the review criteria, and as I noted in https://github.com/openjournals/joss-reviews/issues/565#issuecomment-363984324 Is there an updated version of the paper I missed?

**Comment by bjodah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #565 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00565/joss.00565/10.21105.joss.00565.pdf)

**Comment by bryanwweber** [comment]
This LGTM now, what do I need to do to approve?

**Comment by bjodah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00565/joss.00565/10.21105.joss.00565.pdf)

**Comment by bjodah** [comment]
(I updated the paper with  2 new references since a PR was merged in between with fixes that added PuLP as a dependency)

**Comment by bjodah** [comment]
I've tagged a new version (v0.6.6) and updated `joss-paper/codemeta.json` with the new version number and the new zenodo doi.

**Comment by kyleniemeyer** [comment]
Hi @bjodah, just a few comments on the paper:

- Could you add the city and country to your affiliation?
- Could you put commas around the "e.g." in the second, third, and last paragraphs?
- Reference `mitchell2011pulp` does not have correct bibliographic information (Citeseer is not a journal); I'm not sure what the correct info should be though... perhaps it is a conference paper, as suggested at https://www.semanticscholar.org/paper/PuLP%3A-A-Linear-Programming-Toolkit-for-Python-Mitchell-Consulting/24c9ad0d66f6a05ad41563a7dade60bff6f59106 ?
- in the last paragraph, I think you need a semicolon in the combined citation `[@mitchell2011pulp,@lougee2003common]`

**Comment by bjodah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #565 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    108      0 --:--:-- --:--:-- --:--:--   109
Error reading bibliography ./paper.bib (line 70, column 3):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by bjodah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00565/joss.00565/10.21105.joss.00565.pdf)

**Comment by bjodah** [comment]
@kyleniemeyer thanks!
I (hopefully) fixed the points you raised. Let me know if you want me to change anything else.

**Comment by kyleniemeyer** [comment]
@bjodah I made a few more in https://github.com/bjodah/chempy/pull/90, please merge that and then archive the repo to get a DOI

**Comment by bjodah** [comment]
@kyleniemeyer thanks again. Merged, tagged & updated codemeta.json with new tag & DOI.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.1212469 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1212469" target="_blank">10.5281/zenodo.1212469</a> is the archive.

**Comment by kyleniemeyer** [comment]
@arfon this paper is now ready to accept.

**Comment by arfon** [comment]
@bryanwweber - many thanks for your review here and to @kyleniemeyer for editing this submission ✨ 

@bjodah - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00565 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00565/status.svg)](https://doi.org/10.21105/joss.00565)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00565/status.svg)](https://doi.org/10.21105/joss.00565)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by bjodah** [comment]
That's great. Thank you all!
