### ISSUE TITLE
[REVIEW]: Gramm: grammar of graphics plotting in Matlab

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#568]
**Submitting author:** @piermorel (<a href="http://orcid.org/0000-0003-0984-7016">Pierre Morel</a>)
**Repository:** <a href="https://github.com/piermorel/gramm" target ="_blank">https://github.com/piermorel/gramm</a>
**Version:** v2.23
**Editor:** @cMadan
**Reviewer:** @trallard
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1188423" target="_blank">10.5281/zenodo.1188423</a>

## Status

[![status](http://joss.theoj.org/papers/530fedebbe416c7e60e7189d92d2925e/status.svg)](http://joss.theoj.org/papers/530fedebbe416c7e60e7189d92d2925e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/530fedebbe416c7e60e7189d92d2925e"><img src="http://joss.theoj.org/papers/530fedebbe416c7e60e7189d92d2925e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/530fedebbe416c7e60e7189d92d2925e/status.svg)](http://joss.theoj.org/papers/530fedebbe416c7e60e7189d92d2925e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/piermorel/gramm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@trallard, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/piermorel/gramm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.23)?
- [x] **Authorship:** Has the submitting author (@piermorel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @trallard it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00568/joss.00568/10.21105.joss.00568.pdf
```

**Comment by trallard** [comment]
Currently doing the review of gramm and have a couple of things to raise:

**Documentation**

> - [ ]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

Even though the instructions allow for correct installation they might be a bit dry? cryptic? to those that have never added 3rd party code to their MATLAB path (issue [here](https://github.com/piermorel/gramm/issues/56)

> - [ ]  **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?

I could not find any tests in the repository so I was wondering if you'd considered adding any
(issue [here](https://github.com/piermorel/gramm/issues/57)

**Comment by trallard** [comment]
### Documentation

> - [ ] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

I think the summary of the [software paper](https://github.com/openjournals/joss-papers/blob/joss.00568/joss.00568/10.21105.joss.00568.pdf) makes an excellent point on why gramm is needed and how it offers a better visualization environment for MATLAB users. This could probably be incorporated to the gramm repository (issue [here](https://github.com/piermorel/gramm/issues/59))

**Comment by piermorel** [comment]
Thank you for these suggestions @trallard. I just adressed all these comments  in commit https://github.com/piermorel/gramm/commit/f74c06deb4944d41509667a102f7cf9b162351eb and closed the corresponding issues. Do not hesitate to reopen them if not satisfactory. The latest commit https://github.com/piermorel/gramm/commit/efaa6f7b4a8b397532b909a581b3641ce05cd196 also adds the doi for "grammar of graphics".

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00568/joss.00568/10.21105.joss.00568.pdf)

**Comment by trallard** [comment]
@cMadan I think we can consider the revision of the package completed for the JOSS submission. @piermorel  has sorted out the issues identified and I am sure this package will continue to evolve since it seems to be already well accepted by the MATLAB community. 

What are the next steps to be followed?

**Comment by cMadan** [comment]
@trallard, great, thank you for your thorough review!

@brian-lau, have you had a chance to test the submission?

**Comment by cMadan** [comment]
@brian-lau, thank you for your interest, but I think I'll go ahead and accept the submission as-is now.

@trallard, thank you again for your review!

@piermorel, can you provide the DOI for an archived version of the project's code? (I.e., archive the current codebase on Zenodo or FigShare). After that we'll be all set to accept!

**Comment by trallard** [comment]
You are very welcome @cMadan it has been an absolute pleasure to review this package

**Comment by piermorel** [comment]
Thank you @cMadan, and thank you @trallard for the useful comments.

Gramm is already on Zenodo since several releases. I think Zenodo provides this DOI that allows to track new releases automatically: https://doi.org/10.5281/zenodo.594625 . If there is the need to provide the specific doi from the reviewed version, the latest release on zenodo corresponds to that.

**Comment by cMadan** [comment]
@whedon set archive as 10.5281/zenodo.1188423

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.1188423 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1188423" target="_blank">10.5281/zenodo.1188423</a> is the archive.

**Comment by cMadan** [comment]
@piermorel, perfect, we're all set then!

@arfon, can you do the honors?

**Comment by arfon** [comment]
@trallard - many thanks for your review here and to @cMadan for editing this submission ✨

@piermorel - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00568 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00568/status.svg)](https://doi.org/10.21105/joss.00568)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00568/status.svg)](https://doi.org/10.21105/joss.00568)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
