### ISSUE TITLE
[PRE REVIEW]: weathercan: Download and format weather data from Environment and Climate Change Canada

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#570]
**Submitting author:** @steffilazerte (<a href="http://orcid.org/0000-0002-7690-8360">Stefanie LaZerte</a>)
**Repository:** <a href="https://github.com/ropensci/weathercan" target ="_blank">https://github.com/ropensci/weathercan</a>
**Version:** v0.2.4
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @steffilazerte. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@steffilazerte if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #570 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #570 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     76      0 --:--:-- --:--:-- --:--:--    76
Error producing PDF.
! LaTeX Error: File `fancyvrb.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.153 \newcommand

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/571. Feel free to close this issue now!
