### ISSUE TITLE
[REVIEW]: weathercan: Download and format weather data from Environment and Climate Change Canada

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#571]
**Submitting author:** @steffilazerte (<a href="http://orcid.org/0000-0002-7690-8360">Stefanie LaZerte</a>)
**Repository:** <a href="https://github.com/ropensci/weathercan" target ="_blank">https://github.com/ropensci/weathercan</a>
**Version:** v0.2.4
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1164301" target="_blank">10.5281/zenodo.1164301</a>

## Status

[![status](http://joss.theoj.org/papers/e33112ace30bb700c5e46baf9230df5c/status.svg)](http://joss.theoj.org/papers/e33112ace30bb700c5e46baf9230df5c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e33112ace30bb700c5e46baf9230df5c"><img src="http://joss.theoj.org/papers/e33112ace30bb700c5e46baf9230df5c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e33112ace30bb700c5e46baf9230df5c/status.svg)](http://joss.theoj.org/papers/e33112ace30bb700c5e46baf9230df5c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/weathercan" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arfon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/weathercan">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.4)?
- [x] **Authorship:** Has the submitting author (@steffilazerte) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #571 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     54      0 --:--:-- --:--:-- --:--:--    54
Error producing PDF.
! LaTeX Error: File `fancyvrb.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.153 \newcommand

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
👋 @steffilazerte - thanks for your submission to JOSS. I realize your submission has already been reviewed by rOpenSci so this should be quick. That said, it looks like your current paper is tailored towards technical documentation which we try to avoid.

Could you please revise your paper to match more closely with our [requested content/structure](http://joss.theoj.org/about#paper_structure)? i.e.:

- A list of the authors of the software and their affiliations
- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software
- A list of key references including a link to the software archive
- Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

 [10.21105.joss.00571.pdf](https://github.com/openjournals/joss-reviews/files/1707417/10.21105.joss.00571.pdf)

**Comment by steffilazerte** [comment]
Hi, so essentially you mean to remove the usage aspect of the paper? And keep it mostly descriptive?

**Comment by arfon** [comment]
> Hi, so essentially you mean to remove the usage aspect of the paper? And keep it mostly descriptive?

Yes please. We believe that the usage content should reside in documentation that is linked to from the paper. Does that make sense?

**Comment by steffilazerte** [comment]
Absolutely, I'll get on this right away!

**Comment by steffilazerte** [comment]
Okay, I've updated the manuscript, let me know if this should be even further simplified.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00571/joss.00571/10.21105.joss.00571.pdf)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1164301 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1164301" target="_blank">10.5281/zenodo.1164301</a> is the archive.

**Comment by arfon** [comment]
@steffilazerte - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00571 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00571/status.svg)](https://doi.org/10.21105/joss.00571)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00571/status.svg)](https://doi.org/10.21105/joss.00571)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by steffilazerte** [comment]
Wow that was fast, thanks!
