### ISSUE TITLE
[PRE REVIEW]: MatchPy: Pattern Matching in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#572]
**Submitting author:** @henrik227 (<a href="http://orcid.org/0000-0001-6744-3605">Henrik Barthels</a>)
**Repository:** <a href="https://github.com/HPAC/matchpy" target ="_blank">https://github.com/HPAC/matchpy</a>
**Version:** v0.4.4
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @llllllllll

**Author instructions**

Thanks for submitting your paper to JOSS @henrik227. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@henrik227 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00572/joss.00572/10.21105.joss.00572.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@asmeurer @mattpap is this your cup of tea :tea: ? Would you be able to help review this [JOSS](http://joss.theoj.org/) submission? Alternatively, could you help suggest reviewers? Thanks! :rocket: 

You can access the paper [here](https://github.com/openjournals/joss-papers/blob/joss.00572/joss.00572/10.21105.joss.00572.pdf). 

The project is housed [here](https://github.com/HPAC/matchpy).

If you choose to accept this invitation we will initiate a review issue where you can tick boxes after reviewing the software (see also: http://joss.theoj.org/about#reviewer_guidelines).

**Comment by Kevin-Mattheus-Moerman** [comment]
@betatim are you interested in this too?

**Comment by Kevin-Mattheus-Moerman** [comment]
@asmeurer @mattpap @betatim pinging you again. Can you please help review this submission?

**Comment by danielskatz** [comment]
@Kevin-Mattheus-Moerman - it looks like you are editing this one - can we assign you as the editor?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
Done. @danielskatz I usually start once I've found suitable reviewers (as others with suitable contacts could jump in and save the day instead of me) but I am fine taking this one.

**Comment by Kevin-Mattheus-Moerman** [comment]
@henrik227 are you able to suggest some suitable reviewers?

**Comment by henrik227** [comment]
@Kevin-Mattheus-Moerman Can this be _anyone_ who is knowledgeable on the topic, or does the person has to be associated to JOSS in any way?

**Comment by Kevin-Mattheus-Moerman** [comment]
@henrik227 absolutely anybody with the required expertise, no affiliation with JOSS required.

**Comment by henrik227** [comment]
Maybe @certik or @Upabjojr ?

**Comment by henrik227** [comment]
@Kevin-Mattheus-Moerman How do we proceed from here? I just checked a few authors of papers that were relevant for our work, but they don't seem to be on GitHub. The only other candidates I can think of right now are other SymPy developers, or somebody from the Mathics project (https://github.com/mathics), but I don't know any of them.

**Comment by Kevin-Mattheus-Moerman** [comment]
@betatim @asmeurer @mattpap @cmry @mrocklin @rlamy @Suor Would you be able to help review this [JOSS](http://joss.theoj.org/) submission about pattern matching for symbolic computation? Alternatively, could you help suggest reviewers? Thanks! :rocket: 

You can access the paper [here](https://github.com/openjournals/joss-papers/blob/joss.00572/joss.00572/10.21105.joss.00572.pdf). 

The project is housed [here](https://github.com/HPAC/matchpy).

If you choose to accept this invitation we will initiate a review issue where you can tick boxes after reviewing the software (see also: http://joss.theoj.org/about#reviewer_guidelines).

**Comment by mrocklin** [comment]
I am no longer active in this field and will have to pass.  I'll recommend
@llllllllll though.

**Comment by betatim** [comment]
Won't have time for this

**Comment by Kevin-Mattheus-Moerman** [comment]
@scopatz Please :rabbit: would you be able to help review this [JOSS](http://joss.theoj.org/) submission about pattern matching for symbolic computation? Alternatively, could you help suggest reviewers? Thanks! :rocket: 

You can access the paper [here](https://github.com/openjournals/joss-papers/blob/joss.00572/joss.00572/10.21105.joss.00572.pdf). 

The project is housed [here](https://github.com/HPAC/matchpy).

If you choose to accept this invitation we will initiate a review issue where you can tick boxes after reviewing the software (see also: http://joss.theoj.org/about#reviewer_guidelines).

**Comment by Kevin-Mattheus-Moerman** [comment]
@llllllllll are you available to help review this submission? Thanks

**Comment by llllllllll** [comment]
I am interested, but I want to make sure I can finish in time. How long do you normally have to submit a review?

**Comment by Kevin-Mattheus-Moerman** [comment]
@llllllllll we do not set a limit to the review time. We ask that reviewers work in a timely manor but we place no strict demands on this. There is quite a bit of variation in the time required to complete the review process. Typically a review process takes a couple of weeks. However I have also seen it completed in several days or several months (especially if significant changes are requested). 
We'll hopefully be able to attract multiple reviewers (let me know if you know more suitable ones) which will start at different time points. So even if you cannot start immediately now you can certainly join in later. How much time do you think you'll need?

**Comment by scopatz** [comment]
@Kevin-Mattheus-Moerman - sorry I am out of [spoons](https://en.wikipedia.org/wiki/Spoon_theory). I'll recommend @asmeurer

**Comment by llllllllll** [comment]
I will be very busy until mid May, I don't think I can commit time until then. If there is still a need at that point I would love to help.

**Comment by Kevin-Mattheus-Moerman** [comment]
@llllllllll if you don't mind I'll add you as the main reviewer so we can start opening the review issue. I will continue to look for additional reviewers and I look forward seeing your comments mid May. Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @llllllllll as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @llllllllll

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/670. Feel free to close this issue now!
