### ISSUE TITLE
[PRE REVIEW]: The MCAPL Framework including the Agent Infrastructure Layer and Agent JavaPathfinder

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#573]
**Submitting author:** @louiseadennis (<a href="http://orcid.org/0000-0003-1426-1896">Louise Dennis</a>)
**Repository:** <a href="https://sourceforge.net/projects/mcapl/" target ="_blank">https://sourceforge.net/projects/mcapl/</a>
**Version:** 2017
**Editor:** @danielskatz
**Reviewer:** @BasTesterink

**Author instructions**

Thanks for submitting your paper to JOSS @louiseadennis. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@louiseadennis if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #573 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #573 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by arfon** [comment]
@whedon is struggling with compiling this paper for some reason. Here's a copy compiled on my computer: [10.21105.joss.00573.pdf](https://github.com/openjournals/joss-reviews/files/1707457/10.21105.joss.00573.pdf)

**Comment by louiseadennis** [comment]
Hmm wrt the compiled paper, it looks like a couple of the citations are borked.  I've fixed these and pushed to sourceforge.  I can try installing whedon, but that looks like it could take a while.

In terms of reviewers no one on the list looks like they are in the areas of agent programming or model-checking that our software is.  Some possibilities would be @rbordini, @jomifred, @koenhindriks, @BasTesterink.

**Comment by danielskatz** [comment]
@louiseadennis  - can you suggest some potential reviewers, who are not conflicted but have experience in software in this area?  Note there is [a list of people](https://bit.ly/joss-reviewers) who have already agreed to review for JOSS, who might be suitable.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
also @louiseadennis where is the code?  the repo link https://git.code.sf.net/p/mcapl/mcapl_code looks like an empty page to me.

**Comment by louiseadennis** [comment]
@danielskatz - No one on the list looks like they are in the areas of agent programming or model-checking that our software is. Some possible alternatives would be @jomifred, @koenhindriks, @BasTesterink.

**Comment by louiseadennis** [comment]
@danielskatz OK weird, the git.code.sf.net URL works for cloning but not, apparently, for viewing online for which you need https://sourceforge.net/p/mcapl/mcapl_code/ci/master/tree/  (which should I list as the repository URL? )

**Comment by danielskatz** [comment]
I think https://sourceforge.net/projects/mcapl/ would be better

**Comment by danielskatz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by danielskatz** [comment]
@whedon set https://sourceforge.net/projects/mcapl/ as repository
(my guess is this won't work, but it should - @arfon, if it doesn't, can you make this change manually?)

**Comment by danielskatz** [comment]
@jomifred, @koenhindriks, @BasTesterink - would one or two of you be willing to review this submission to The Journal of Open Source Software?

Please take a look at our [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines) before you answer.

**Comment by BasTesterink** [comment]
Hi Daniel, 

I just read the reviewer guidelines and would be glad to support JOSS by reviewing this submission. I have scheduled next week Friday to do this.

This will be my first JOSS review. Are previous review examples publicly available? 

With kind regards,


Bas Testerink

**Comment by danielskatz** [comment]
@BasTesterink - thanks!

And, yes, all reviews are public, see [reviews in progress](https://github.com/openjournals/joss-reviews/issues?q=is%3Aissue+is%3Aopen+label%3Areview) and [completed reviews](https://github.com/openjournals/joss-reviews/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+label%3Aaccepted).

Since I don't know this specific area very well, I also hope to get one more reviewer before we start the review.

**Comment by danielskatz** [comment]
@arfon, can you do the equivalent of: @whedon set https://sourceforge.net/projects/mcapl/ as repository ?

**Comment by arfon** [comment]
> @arfon, can you do the equivalent of: @whedon set https://sourceforge.net/projects/mcapl/ as repository ?

Done (I just edited the issue).

**Comment by danielskatz** [comment]
I wasn't sure if it was that simple - thanks :)

**Comment by danielskatz** [comment]
@gannimo - Would you be willing to review this submission for JOSS?

**Comment by gannimo** [comment]
Thanks; the paper is not in my area, so I'll pass.

**Comment by danielskatz** [comment]
@gannimo - Do you have any thoughts on other potential reviewers?

**Comment by louiseadennis** [comment]
@fraimondi might be worth a try, though I know he's pretty busy, but even if he isn't able to do it he might be able to recommend someone in the MCMAS community who would (and anyone familiar with MCMAS would be a good candidate to look at this)

**Comment by danielskatz** [comment]
@fraimondi - following @louiseadennis's suggestion, would you be willing to review this for JOSS?  And if not, can you recommend someone in the MCMAS community who would likely be able to (anyone familiar with MCMAS would be a good candidate to look at this)?

**Comment by fraimondi** [comment]
Hi,
Sorry this ended up in my spam folder. Do you have a deadline for the review? I could do for the 20th of April but not earlier.

**Comment by danielskatz** [comment]
@fraimondi - great, I can live with the 20th of April.  Also, as you may have already figured out, this is not a typical paper review - reviews often involve some interaction between the reviewer and the author(s), and as such, may take some smaller blocks of time rather than one larger one.

In any case, I will now start the review.

**Comment by danielskatz** [comment]
@whedon assign @BasTesterink as reviewer
(I would now like to assign @fraimondi as a reviewer as well, but the system can't do multiple reviewers yet, so I'll do this semi-manually once the review issue is opened.)

**Comment by whedon** [comment]
OK, the reviewer is @BasTesterink

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/617. Feel free to close this issue now!
