### ISSUE TITLE
[PRE REVIEW]: Nostril: A nonsense string evaluator written in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#574]
**Submitting author:** @mhucka (<a href="http://orcid.org/0000-0001-9105-5960">Michael Hucka</a>)
**Repository:** <a href="https://github.com/casics/nostril" target ="_blank">https://github.com/casics/nostril</a>
**Version:** v1.0.0
**Editor:** @jakevdp
**Reviewer:** @desilinguist

**Author instructions**

Thanks for submitting your paper to JOSS @mhucka. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mhucka if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #574 with the following error: 

 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00574/joss.00574/10.21105.joss.00574.pdf
```

**Comment by mhucka** [comment]
Thanks for all that. Regarding reviewers, I don't know these people but based purely on the list of topic areas in that fantastic spreadsheet, the following appear to be most closely related:

* desilinguist
* ahurriyetoglu
* jkahn
* @kellieotto
* linuxscout
* xirdneh

**Comment by jakevdp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by jakevdp** [comment]
@whedon assign @jakevdp as editor

**Comment by whedon** [comment]
OK, the editor is @jakevdp

**Comment by jakevdp** [comment]
Hi @mhucka, thanks for the submission! Looks really interesting... I'm going to work on finding a reviewer or two and start this process along :smile:

**Comment by jakevdp** [comment]
@whedon assign @desilinguist as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @desilinguist

**Comment by jakevdp** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by jakevdp** [comment]
@whedon start review magic-word=bananas
