### ISSUE TITLE
[PRE REVIEW]: Dassie: a database of subject terms and hierarchies in the Library of Congress Subject Headings

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#578]
**Submitting author:** @mhucka (<a href="http://orcid.org/0000-0001-9105-5960">Michael Hucka</a>)
**Repository:** <a href="https://github.com/casics/dassie" target ="_blank">https://github.com/casics/dassie</a>
**Version:** v1.0.2
**Editor:** @jasonclark
**Reviewers:** @soodoku

**Author instructions**

Thanks for submitting your paper to JOSS @mhucka. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mhucka if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jasonclark it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #578 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
👋 @jasonclark - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00578/joss.00578/10.21105.joss.00578.pdf)

**Comment by mhucka** [comment]
I'm not sure where to report this, so I'll try in this issue thread first: the PDF generated automatically by whedon is different from the preview I generated myself (c.f. https://github.com/openjournals/joss/issues/379#issuecomment-362362109) and I cannot figure out why. The difference is in extra whitespace showing up in what whedon produced. I've attached a marked-up PDF that I generated locally, with arrows pointing out where the differences are relative to the PDF produced by whedon. The consequence of these differences on the first page is that in whedon's PDF, the last reference on the 2nd page in the paper spills onto a 3rd page, which is admittedly a small thing, but it's ugly, and avoiding that kind of thing is exactly the reason I was trying to find a way to preview JOSS PDFs in the first place :-).

Is this issue recognizable to anyone here? Is there anything that might be causing the introducing of extra whitespace when whedon runs?  

I suppose a possible cause is using a different Latex or Pandoc environment. Is it possible to see a log of whedon's run when it produce the output? That might help identify differences.

![paper-difference_page_1](https://user-images.githubusercontent.com/1450019/36168472-131281f6-10ae-11e8-8ced-a0281bf6cc7b.png)

**Comment by arfon** [comment]
Interesting. I'm not sure what's going on here exactly @mhucka. The version I produce locally (which ultimately is the version that becomes the final PDF) looks much closer to what you have:
 [10.21105.joss.00578.pdf](https://github.com/openjournals/joss-reviews/files/1722403/10.21105.joss.00578.pdf)

These are the Heroku buildpacks we use to generate the Whedon TeX environment: https://github.com/openjournals/whedon-api/blob/master/app.json#L52-L55 but I'm not sure why we're getting extra whitespace in the Whedon-generated version of the PDF.

**Comment by mhucka** [comment]
Thanks for looking into this @arfon – and sorry it's such a trivial issue. But if you're getting the expected output, and that's what ultimately will be used, then that's good enough for me. It might not be worth pursuing further at this time.

Thanks again!

**Comment by arfon** [comment]
👋 @jasonclark - are you able to edit this submission for JOSS?

**Comment by jasonclark** [comment]
@whedon assign @jasonclark as editor

**Comment by whedon** [comment]
OK, the editor is @jasonclark

**Comment by jasonclark** [comment]
@arfon @mhucka Yes, I'm on it. Asking for possible reviewers and will set up next steps.

**Comment by jasonclark** [comment]
@gabrielspadon Would you have time to review the Dassie software? Thanks for considering.

**Comment by mhucka** [comment]
@arfon I'm not sure how to handle this, so I have to ask here: I neglected to include an NSF agency funding acknowledgment in the paper. How can I add it? Can I go ahead and modify the paper that's in the github repo, or is there a different procedure I should follow?

**Comment by arfon** [comment]
> @arfon I'm not sure how to handle this, so I have to ask here: I neglected to include an NSF agency funding acknowledgment in the paper. How can I add it? Can I go ahead and modify the paper that's in the github repo, or is there a different procedure I should follow?

Please go ahead and add this to the paper. I've seen authors add an `#acknowledgements` section to their `paper.md` file in the past. This should compile OK.

**Comment by mhucka** [comment]
@arfon Thanks – that's exactly what I was going to try to do.

**Comment by mhucka** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00578/joss.00578/10.21105.joss.00578.pdf)

**Comment by arfon** [comment]
@jasonclark - I think we might need to look for alternative reviewers for this submission.

**Comment by mhucka** [comment]
@jasonclark @arfon Not attempting to nag, but I was wondering how things are going, and whether there's anything I should do?

**Comment by arfon** [comment]
@mhucka - things are ok from my end but I realize this is going slooooowly.

@jasonclark - are you still able to edit this submission?

**Comment by kellieotto** [comment]
@jasonclark sorry, I can't review it right now. I am swamped for the next month or so!

**Comment by jasonclark** [comment]
@kellieotto No worries. Thanks for the quick response.

**Comment by jasonclark** [comment]
@soodoku Would you have time to review the Dassie software? Thanks for considering.

**Comment by soodoku** [comment]
sure. first time so may reach out for advice.

**Comment by jasonclark** [comment]
@soodoku Sure, not a problem. Thanks for agreeing. I'll set up next steps and we'll go from there.

**Comment by jasonclark** [comment]
@soodoku The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by jasonclark** [comment]
@whedon assign @soodoku as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @soodoku

**Comment by jasonclark** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/728. Feel free to close this issue now!
