### ISSUE TITLE
[PRE REVIEW]: The vtreat R package: a statistically sound data processor for predictive modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#579]
**Submitting author:** @JohnMount (<a href="http://orcid.org/0000-0002-3696-2012">John Mount</a>)
**Repository:** <a href="https://github.com/WinVector/vtreat/" target ="_blank">https://github.com/WinVector/vtreat/</a>
**Version:** 1.0.2
**Editor:** @karthik
**Reviewer:** @earino

**Author instructions**

Thanks for submitting your paper to JOSS @JohnMount. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@JohnMount if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #579 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
👋 @danielskatz - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #579 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     77      0 --:--:-- --:--:-- --:--:--    77
Error reading bibliography ./paper.bib (line 25, column 2):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by JohnMount** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00579/joss.00579/10.21105.joss.00579.pdf)

**Comment by danielskatz** [comment]
hmmm. I don't have any experience with R, and I'm much more of a computer scientist and computational scientist than a data scientist.  I really don't think I'm the right person to edit this one.

**Comment by JohnMount** [comment]
Perhaps one or more of @milesmcbain @earino @Fusionet24 @nhejazi @trallard could review?  I was just looking through for people with a combination of interests in R, statistics, data science, and data preparation.

**Comment by JohnMount** [comment]
@danielskatz sorry for the trouble.  Should I suggest another editor or is there some other way to go forward?  I just found some R people from the review list.

**Comment by danielskatz** [comment]
If you can suggest another editor, I certainly would appreciate it :)

**Comment by JohnMount** [comment]
Perhaps Thomas J. Leeper (@leeper).  A social scientist (they know their statistics) and CRAN contributor.

**Comment by JohnMount** [comment]
And if that isn't appropriate how about Karthik Ram (@karthik), for data science?

**Comment by JohnMount** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by JohnMount** [comment]
@arfon thank for helping with this.  I assume that I do not assign editors, but have put in some suggestions.  Please let me know if I need to do something.

**Comment by earino** [comment]
Hi am I needed for something?

**Comment by karthik** [comment]
I’m happy to handle as editors. 
Ed: would you like to review?

**Comment by karthik** [comment]
@whedon assign karthik as editor

**Comment by whedon** [comment]
OK, the editor is karthik

**Comment by nhejazi** [comment]
Looks like @earino has already stepped up, but also happy to review should it become necessary.

**Comment by earino** [comment]
LOL hang on, let's make sure I have any idea what I'm doing. I mostly just
asked if I was needed :-) what are the requirements for excellent reviewing?

**Comment by earino** [comment]
But instinctively this sounds like something I would enjoy.

**Comment by JohnMount** [comment]
@whedon set 10.5281/zenodo.1173318 as archive

**Comment by whedon** [comment]
I'm sorry @JohnMount, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by JohnMount** [comment]
Sorry, didn't mean to overstep.

**Comment by arfon** [comment]
> Sorry, didn't mean to overstep.

:-) no problem. There are some things only editors can do and we generally do this towards the end of the review process...

**Comment by karthik** [comment]
@whedon assign @earino as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @earino

**Comment by karthik** [comment]
@earino I’m just about to go offline for a week but once a new review issue is created, you’ll have instructions on what to do. I can also help if you run into problems.

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/584. Feel free to close this issue now!
