### ISSUE TITLE
[REVIEW]: PyMap3D: 3-D coordinate conversions for terrestrial and geospace environments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#580]
**Submitting author:** @scivision (<a href="http://orcid.org/0000-0002-1637-6526">Michael Hirsch</a>)
**Repository:** <a href="https://github.com/scivision/pymap3d" target ="_blank">https://github.com/scivision/pymap3d</a>
**Version:** v1.6.0
**Editor:** @lheagy
**Reviewer:** @hugoledoux
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.213676" target="_blank">10.5281/zenodo.213676</a>

## Status

[![status](http://joss.theoj.org/papers/3a8f7c3bdeaa4ec9ef790d7fad50b8a7/status.svg)](http://joss.theoj.org/papers/3a8f7c3bdeaa4ec9ef790d7fad50b8a7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3a8f7c3bdeaa4ec9ef790d7fad50b8a7"><img src="http://joss.theoj.org/papers/3a8f7c3bdeaa4ec9ef790d7fad50b8a7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3a8f7c3bdeaa4ec9ef790d7fad50b8a7/status.svg)](http://joss.theoj.org/papers/3a8f7c3bdeaa4ec9ef790d7fad50b8a7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/scivision/pymap3d" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions: @hugoledoux

@hugoledoux, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/scivision/pymap3d">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.6.0)?
- [x] **Authorship:** Has the submitting author (@scivision) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

## Reviewer instructions & questions: @leouieda

@hugoledoux, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/scivision/pymap3d">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.5.0)?
- [x] **Authorship:** Has the submitting author (@scivision) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @hugoledoux it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00580/joss.00580/10.21105.joss.00580.pdf)

**Comment by lheagy** [comment]
:wave: Hi @hugoledoux and @leouieda, here is the issue for the review. I have put 2 checklists in the top of the issue, one for each of you. Please let me know if you have any questions!

**Comment by lheagy** [comment]
Hi @leouieda: would you be willing to do a first go on looking through the software? @hugoledoux had a lot on his plate at the moment and mentioned that he would be able to jump in near the end of the month. Please let me know if you have any questions!

**Comment by leouieda** [comment]
Hi @lheagy, I can get started on this tomorrow. I had a look at the guidelines and review questions.

It seems that there has been a new release (1.6.0) since the paper was submitted. Should @scivision update the paper/issue content to match?

**Comment by lheagy** [comment]
Thanks @leouieda, yes, that is a good catch. @arfon: how do we update the version on this issue? manually? or should this be done with whedon?

**Comment by arfon** [comment]
> @arfon: how do we update the version on this issue? manually? or should this be done with whedon?

You can simply edit the comment by @whedon at the top of the issue.

**Comment by scivision** [comment]
Thanks, I updated [paper.md](https://github.com/scivision/pymap3d/commit/c07feead980407e622da9086ce11df2d4174eb96) to mention the Fortran code. The Matlab and Fortran code are completely independent standalone codes for those langauges.

**Comment by hugoledoux** [comment]
@scivision 

I am a GIS person used to work with proj4 (pyproj), and the Python package works as advertised and is surely useful to people in that community. For a GIS person, proj4 is "standard" and everyone uses it.

I only tested the Python version, since I don't have the 1000$ to buy Matlab...

## README
I find the README a bit confusing sometimes to be honest.

## install
You state in INSTALL that there are 3 packages, but you give two installations...

## prereqs
I'd write "prerequisites", but okay fair enough.

What is not clear to me: if I want to use numpy for instance, do I have to do something? It's on my system, is it used automatically? Same thing for AstroPy.

Also a link to AstroPy could help the user.

## version
The version is 1.6.0, I changed the from 1.5.0. I assume this is not a problem.

## pyproj
I believe there are conversions that you perform that are impossible with proj4, no? State a few... For me the argument of not pure python is not very strong, it's trivial to install proj4 on most platform.

## installation
I think it could be written that everything is on PyPI and just doing `pip install pymap3d` works (that's how I installed it under Python 2.7)

## functions
I am not familiar with the terms such as 'aer', 'ned', etc. Are these explained somewhere? That is needed in my opinion, now the docs doesn't really explain them either.

## Software paper
- geospace coordinate systems --> *geographic* coordinate systems is a better term in my opinion

## usage
Not totally clear why there are numbers there `az,el,range = pm.geodetic2aer(lat, lon, alt, 42, -82, 0)`, I mean the 42 and -82. Perhaps just explain?

## community guidelines
I don't see any file there.

**Comment by scivision** [comment]
These issues have been addressed in the latest git commits, thanks

**Comment by lheagy** [comment]
Thanks @scivision, @hugoledoux, @leouieda: could you please take a look and see if your comments have been addressed? Thanks!

**Comment by hugoledoux** [comment]
Everything was done, except I don't see anything for this point "Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

If it's done then all good with me.

**Comment by scivision** [comment]
Thank you this has been added in
https://github.com/scivision/pymap3d/blob/master/docs/CONTRIBUTING.md

**Comment by lheagy** [comment]
Thanks @hugoledoux and @leouieda for the review! @leouieda: there is still one outstanding check-box in the Documentation: the community guidelines. Did this just get missed?

**Comment by leouieda** [comment]
@lheagy sorry, it just got missed. Checked now.

**Comment by lheagy** [comment]
@scivision: Can you confirm that this is the correct DOI for the project: 10.5281/zenodo.213676 ?

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.213676" target="_blank">10.5281/zenodo.213676</a> is the archive.

**Comment by lheagy** [comment]
@arfon: this submission is ready for publication in JOSS. 

Congratulations @scivision! Thanks @hugoledoux and @leouieda for reviewing!

**Comment by arfon** [comment]
@hugoledoux and @leouieda - many thanks for your reviews here and to @lheagy for editing this submission ✨ 

@scivision - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00580 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00580/status.svg)](https://doi.org/10.21105/joss.00580)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00580/status.svg)](https://doi.org/10.21105/joss.00580)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
