### ISSUE TITLE
[PRE REVIEW]: FNFT: A Software Library for Computing Nonlinear Fourier Transforms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#582]
**Submitting author:** @wahls (<a href="http://orcid.org/0000-0001-5159-0918">Sander Wahls</a>)
**Repository:** <a href="https://github.com/FastNFT/FNFT" target ="_blank">https://github.com/FastNFT/FNFT</a>
**Version:** v0.1.0
**Editor:** @kyleniemeyer
**Reviewer:** @hafermann

**Author instructions**

Thanks for submitting your paper to JOSS @wahls. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wahls if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00582/joss.00582/10.21105.joss.00582.pdf)

**Comment by arfon** [comment]
👋 @kyleniemeyer - the submitting author suggested you as the handling editor.

**Comment by wahls** [comment]
@arfon @kyleniemeyer Anything we can do to help at this stage?

**Comment by kyleniemeyer** [comment]
hi @wahls, can you suggest any potential reviewers from your field that we might reach out to?

**Comment by wahls** [comment]
@kyleniemeyer, Hartmut @hafermann would be a good choice if he is available. He also does research in the field and has experience with C++ open source development.

**Comment by hafermann** [comment]
If not too urgent, I would be happy to review the software within, say, three weeks from now. I intended to try it in any case.

**Comment by kyleniemeyer** [comment]
@hafermann ok, that works for us. Thank you!

**Comment by kyleniemeyer** [comment]
@whedon assign @hafermann as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hafermann

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/597. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
Hi @wahls @hafermann the actual review will take place over in #597
