### ISSUE TITLE
[REVIEW]: The vtreat R package: a statistically sound data processor for predictive modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#584]
**Submitting author:** @JohnMount (<a href="http://orcid.org/0000-0002-3696-2012">John Mount</a>)
**Repository:** <a href="https://github.com/WinVector/vtreat/" target ="_blank">https://github.com/WinVector/vtreat/</a>
**Version:** 1.0.2
**Editor:** @karthik
**Reviewer:** @earino
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1196479" target="_blank">10.5281/zenodo.1196479</a>

## Status

[![status](http://joss.theoj.org/papers/0566dff28eab99e15ea90b33f8f1a01d/status.svg)](http://joss.theoj.org/papers/0566dff28eab99e15ea90b33f8f1a01d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0566dff28eab99e15ea90b33f8f1a01d"><img src="http://joss.theoj.org/papers/0566dff28eab99e15ea90b33f8f1a01d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0566dff28eab99e15ea90b33f8f1a01d/status.svg)](http://joss.theoj.org/papers/0566dff28eab99e15ea90b33f8f1a01d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/WinVector/vtreat/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@earino, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/WinVector/vtreat/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.2)?
- [x] **Authorship:** Has the submitting author (@JohnMount) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @earino it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00584/joss.00584/10.21105.joss.00584.pdf)

**Comment by JohnMount** [comment]
Just a note: we have included testthat tests in the package (an R way of automating tests).

**Comment by earino** [comment]
@JohnMount greeting! I was going through the review checklist, and most things are very straightforward. I should add that this is my first review for JOSS, so I please bare with me. I however couldn't verify:

- community guidelines
- all archival references that should have a DOI list one (e.g., papers, datasets, software)?

If you could help me find them, I would appreciate it!

**Comment by JohnMount** [comment]
@earino Thanks for volunteering!  Please don't hesitate to ask me questions.

 * The project has not yet added explicit community guidelines.  We certainly must adhere to the https://help.github.com/articles/github-community-guidelines/ by being on GitHub and subject to their terms of service.  I'll can look into finding some explicit guidelines if that is a requirement (or is it enough to note the project does or does not have some?).
 * DOIs, well part of this submission is to help get a DOI for this work.  But we do have some relevant DOIs: https://zenodo.org/record/1173314#.WpHTaWaZNqc https://zenodo.org/record/1173318#.WpHTZ2aZNqc .

**Comment by JohnMount** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by JohnMount** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by earino** [comment]
@JohnMount I'm happy to. I've spoken about this package in a few talks, so it seems like a good intersection of interest and aptitutde :)
 - I looked a number of other issues, and they all seem to have a CONTRIBUTING.md. Some of them are longer than others, [here](https://github.com/piermorel/gramm/blob/master/CONTRIBUTING.md)'s an example. I think that the expectation is that the expectation is explicit?
- I think you're supposed to include those DOIs in the references section of paper.md? Maybe I'm wrong on this one.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00584/joss.00584/10.21105.joss.00584.pdf)

**Comment by JohnMount** [comment]
I'll run down a CONTRIBUTING.md right now.  I just tried adding DOIs to paper.bib, but the re-render seemed to ignore them. If you know how to get them to render that would help a bit.  I am going to also add the DOIs to the README.md so they will be there in a little bit.

**Comment by earino** [comment]
@JohnMount sadly i don't know how to get them to render. let me know if you figure out the magic? (or maybe @karthik or someone can hop in and help clarify for us.)

**Comment by JohnMount** [comment]
Ah my mistake.  I needed to merge the branch in to get the DOIs in.  I now have DOIs in the paper.bib and the re-generated paper shows them. I'll add the paper one to the README.md (it doesn't make sense for the repository to refer to the code snapshot).  And I'll add a CONTRIBUTING.md .

**Comment by JohnMount** [comment]
Okay, I think I have it all fixed up now. DOIs in the [paper](https://github.com/openjournals/joss-papers/blob/joss.00584/joss.00584/10.21105.joss.00584.pdf) (now visible), and in [README.md](https://github.com/WinVector/vtreat/blob/master/README.md).  Now have a simple [CONTRIBUTING.md](https://github.com/WinVector/vtreat/blob/master/CONTRIBUTING.md) file.

**Comment by earino** [comment]
@JohnMount looks great!
@karthik I've verified the full checklist, what's the next step?

**Comment by karthik** [comment]
@earino Thanks Ed!

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00584/joss.00584/10.21105.joss.00584.pdf)

**Comment by karthik** [comment]
@JohnMount Can you please archive your software on Zenodo and post a DOI here?

**Comment by JohnMount** [comment]
Here you go.

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1196479.svg)](https://doi.org/10.5281/zenodo.1196479)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1196479 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1196479" target="_blank">10.5281/zenodo.1196479</a> is the archive.

**Comment by JohnMount** [comment]
Thanks for accepting the paper.  The article seems to be a dead link even though the check looks good on the thread.  http://joss.theoj.org/papers/10.21105/joss.00584

**Comment by arfon** [comment]
> Thanks for accepting the paper. The article seems to be a dead link even though the check looks good on the thread. http://joss.theoj.org/papers/10.21105/joss.00584

Yup, just working on that now.

**Comment by arfon** [comment]
@earino - many thanks for your review here and thanks to @karthik for editing this submission ✨ 

@JohnMount - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00584 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00584/status.svg)](https://doi.org/10.21105/joss.00584)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00584/status.svg)](https://doi.org/10.21105/joss.00584)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by earino** [comment]
@arfon privilege and an honor! look forward to being of assistance in the future.

**Comment by JohnMount** [comment]
The paper was there for a little while and then disappeared again.

 https://github.com/openjournals/joss-reviews/issues/584 (paper does not show)

https://www.theoj.org/joss-papers/joss.00584/10.21105.joss.00584.pdf (broken link)

**Comment by arfonsmith** [comment]
I think this was a problem with GitHub earlier. This should be fixed again
now.

**Comment by JohnMount** [comment]
Looks like it disappeared again. Does JOSS get the paper from the tar file?  Because it is not there- I used the CRAN distribution to build the marked release of the software (not the raw Github account).

If that is the problem we can up the DOI to have the full GitHub contents:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1196652.svg)](https://doi.org/10.5281/zenodo.1196652)

John

**Comment by arfon** [comment]
Looks like it's back again. I think this is due to the GitHub pages outage earlier.

> Does JOSS get the paper from the tar file? 

No, we pull this straight from GitHub: https://github.com/openjournals/joss-papers/blob/a516dc7ddb45a1cbc0eabe7ecd9446dc2d657256/joss.00584/10.21105.joss.00584.pdf

**Comment by JohnMount** [comment]
Hm, then let's please stick with the version I gave originally.  For me the file is missing again.
