### ISSUE TITLE
[PRE REVIEW]: pynucastro: an interface to nuclear reaction rates and code generator for reaction network equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#585]
**Submitting author:** @dwillcox (<a href="http://orcid.org/0000-0003-2300-5165">Donald Willcox</a>)
**Repository:** <a href="https://github.com/pynucastro/pynucastro" target ="_blank">https://github.com/pynucastro/pynucastro</a>
**Version:** 1.0.0
**Editor:** @katyhuff
**Reviewer:** @kyleniemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @dwillcox. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dwillcox if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00585/joss.00585/10.21105.joss.00585.pdf)

**Comment by dwillcox** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by dwillcox** [comment]
@zingale This is our JOSS pre review issue.

**Comment by dwillcox** [comment]
A reviewer proficient in both Python and Fortran would be best able to assess this submission.

We would like to suggest @kyleniemeyer as a potential reviewer actively working in the closely related field of chemical combustion modeling.

**Comment by dwillcox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00585/joss.00585/10.21105.joss.00585.pdf)

**Comment by dwillcox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00585/joss.00585/10.21105.joss.00585.pdf)

**Comment by dwillcox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00585/joss.00585/10.21105.joss.00585.pdf)

**Comment by kyleniemeyer** [comment]
@katyhuff If you are editing this submission, I can review it

**Comment by kyleniemeyer** [comment]
@katyhuff although someone else in nuclear astrophysics may be good as a second reviewer

**Comment by katyhuff** [comment]
@kyleniemeyer : my pings to other reviewers so far have gone unanswered. It would be great if you'd be willing to review this -- I'll add a second reviewer as soon as an appropriate one arises.

**Comment by katyhuff** [comment]
@whedon set @kyleniemeyer as reviewer

**Comment by katyhuff** [comment]
@whedon assign @kyleniemeyer as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kyleniemeyer

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/588. Feel free to close this issue now!

**Comment by katyhuff** [comment]
@dwillcox @zingale @kyleniemeyer , the review will happen over in #588 .
