### ISSUE TITLE
[PRE REVIEW]: MCMCvis: Tools to Visualize, Manipulate, and Summarize MCMC Output

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#586]
**Submitting author:** @caseyyoungflesh (<a href="http://orcid.org/0000-0001-6343-3311">Casey Youngflesh</a>)
**Repository:** <a href="https://github.com/caseyyoungflesh/MCMCvis" target ="_blank">https://github.com/caseyyoungflesh/MCMCvis</a>
**Version:** v0.9.4
**Editor:** @arfon
**Reviewer:** @jkarreth

**Author instructions**

Thanks for submitting your paper to JOSS @caseyyoungflesh. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@caseyyoungflesh if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00586/joss.00586/10.21105.joss.00586.pdf)

**Comment by caseyyoungflesh** [comment]
Suggested reviewers (based on 'MCMC' or 'Bayes' in Domains and 'R' in Preferred Language):

* pboesu
* mdogucu
* jkarreth
* paulgovan

**Comment by caseyyoungflesh** [comment]
@karthik  Just wanted to check in and see if anything else is needed on my end here.

**Comment by caseyyoungflesh** [comment]
@karthik @arfon Apologies for being such a pest but I just wanted to check in on things to make sure everything was sorted here. Thanks!

**Comment by arfon** [comment]
@jkarreth - would you be willing to review this submission for JOSS?

**Comment by jkarreth** [comment]
Yes, happy to review it!

**Comment by arfon** [comment]
@whedon set arfon as editor

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @jkarreth as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jkarreth

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/640. Feel free to close this issue now!

**Comment by arfon** [comment]
@jkarreth - thanks! See you over in #640 for the actual review.
