### ISSUE TITLE
[PRE REVIEW]: Flux: Seamless machine learning with Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#587]
**Submitting author:** @MikeInnes (<a href="http://orcid.org/0000-0003-0788-0242">Michael Innes</a>)
**Repository:** <a href="https://github.com/FluxML/Flux.jl" target ="_blank">https://github.com/FluxML/Flux.jl</a>
**Version:** v0.4.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @ysimillides

**Author instructions**

Thanks for submitting your paper to JOSS @MikeInnes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MikeInnes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00587/joss.00587/10.21105.joss.00587.pdf)

**Comment by MikeInnes** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by MikeInnes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00587/joss.00587/10.21105.joss.00587.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@betatim is this your cup of tea :tea: or do you know any potential reviewers?

**Comment by MikeInnes** [comment]
I could also suggest @trallard, who I know has been involved with Julia. (Hope it's OK to ping)

**Comment by MikeInnes** [comment]
Alternatively @ysimillides may be able to review.

**Comment by ysimillides** [comment]
I would be happy to perform the review.

**Comment by vchuravy** [comment]
I would also be able to review but I am bit busy currently, so if @ysimillides wants to go ahead. Otherwise I will take a look later this week.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @ysimillides as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ysimillides

**Comment by Kevin-Mattheus-Moerman** [comment]
@vchuravy I've assigned @ysimillides as the first reviewer but I'd like to aim for 3 reviewers so your review is certainly welcome.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/602. Feel free to close this issue now!
