### ISSUE TITLE
[REVIEW]: pynucastro: an interface to nuclear reaction rates and code generator for reaction network equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#588]
**Submitting author:** @dwillcox (<a href="http://orcid.org/0000-0003-2300-5165">Donald Willcox</a>)
**Repository:** <a href="https://github.com/pynucastro/pynucastro" target ="_blank">https://github.com/pynucastro/pynucastro</a>
**Version:** 1.1.1
**Editor:** @katyhuff
**Reviewer:** @jschwab
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1202434" target="_blank">10.5281/zenodo.1202434</a>

## Status

[![status](http://joss.theoj.org/papers/f753b6f21f460ae6a301c21c95dfa001/status.svg)](http://joss.theoj.org/papers/f753b6f21f460ae6a301c21c95dfa001)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f753b6f21f460ae6a301c21c95dfa001"><img src="http://joss.theoj.org/papers/f753b6f21f460ae6a301c21c95dfa001/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f753b6f21f460ae6a301c21c95dfa001/status.svg)](http://joss.theoj.org/papers/f753b6f21f460ae6a301c21c95dfa001)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pynucastro/pynucastro" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kyleniemeyer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pynucastro/pynucastro">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@dwillcox) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00588/joss.00588/10.21105.joss.00588.pdf)

**Comment by katyhuff** [comment]
@whedon assign @jschwab as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jschwab

**Comment by katyhuff** [comment]
@jschwab you are the second reviewer and we are hoping you can contribute your particular expertise in nuclear astrophysics to this review. See below for instructions. (please note that first reviewer @kyleniemeyer has received his own set of instructions, and checklist, above).

## Reviewer instructions & questions

@jschwab, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

  ### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pynucastro/pynucastro">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [ ] **Authorship:** Has the submitting author (@dwillcox) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by jschwab** [comment]
Okay, just started the review.  I made it through the README and opened https://github.com/pynucastro/pynucastro/issues/30, https://github.com/pynucastro/pynucastro/issues/31, https://github.com/pynucastro/pynucastro/issues/32, https://github.com/pynucastro/pynucastro/issues/33.

**Comment by dwillcox** [comment]
Thanks Josiah! I'll make my way through these issues, I appreciate your careful feedback thus far and I look forward to your review.

**Comment by jschwab** [comment]
I made it through the "Software paper" and that part looks good to me (fixed a few typos in https://github.com/pynucastro/pynucastro/pull/37).

There's no DOI for [Zingale et al. 2017](http://adsabs.harvard.edu/abs/2017arXiv171106203Z) but it is on arXiv (and I'm guessing it will get a DOI in the future?).  The BibTeX entry and bib style mean that it doesn't get a hyperlink.  For now, perhaps just change adsurl -> url for that entry in the .bib to give it something clickable?

**Comment by dwillcox** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by dwillcox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00588/joss.00588/10.21105.joss.00588.pdf)

**Comment by dwillcox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00588/joss.00588/10.21105.joss.00588.pdf)

**Comment by dwillcox** [comment]
Thanks @jschwab for the note about the url for the Zingale 2017 paper, which should get a DOI at some point when it is officially published. I've made the link clickable using the `url` bibtex tag as you suggested.

Thank you as well for fixing the typos you've found!

**Comment by jschwab** [comment]
@katyhuff @dwillcox @zingale I'm pleased to recommend that the pynucastro paper be accepted in JOSS.  Thanks to the authors for their rapid and helpful communications during the review process.

I checked off the version checkbox, but given the tweaks that happened during review, there should probably be a new minor version released (e.g. v1.1.0) that will correspond to its accepted state.

**Comment by katyhuff** [comment]
@jschwab , thank you for your prompt and thorough review!
@dwillcox @zingale thank you for promptly responding to review comments!

@kyleniemeyer , do you agree with this assessment?

**Comment by kyleniemeyer** [comment]
@dwillcox @zingale a few minor comments:

- It might be helpful to add some instructions on installing the package—it could be as simple as adding a brief section in the README (even if they are pretty standard instructions)
- There are a few references in the paper with URLs that should be replaced with DOIs: Cyburt et al. 2010: 10.1088/0067-0049/189/1/240, Huang et al. 2017: 10.1088/1674-1137/41/3/030002, Nonaka et al. 2010: 10.1088/0067-0049/188/2/358; Suzuki et al. 2016: 10.3847/0004-637X/817/2/163; Wang et al. 2017: 10.1088/1674-1137/41/3/030003

**Comment by kyleniemeyer** [comment]
Otherwise, this looks good!

**Comment by kyleniemeyer** [comment]
Oh, one other comment: it might be helpful to have a link from the docs page back to the repository; I couldn't find one.

**Comment by zingale** [comment]
I've added a link to the project github on the docs index page.

I also added install instructions (and fixed an issue in the `setup.py`) and confirmed that the example notebook runs with the library installed via `setup.py`

I'll work on the references.

**Comment by zingale** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00588/joss.00588/10.21105.joss.00588.pdf)

**Comment by zingale** [comment]
okay, I think all the DOIs that are available are in place now.

**Comment by jschwab** [comment]
@zingale The install instructions in https://github.com/pynucastro/pynucastro/commit/27bb810131ce4dad60ebb192150f7d01de6569f5 trail off.  "This will put the..."

**Comment by zingale** [comment]
indeed they do!

a little to quick on the push.

**Comment by kyleniemeyer** [comment]
OK, looks good to me!

**Comment by dwillcox** [comment]
Hi @katyhuff @jschwab @kyleniemeyer,

Thank you for all your helpful review suggestions that have significantly improved the usability and accessibility of pynucastro.

Today I pushed a commit adding a brief section to the documentation describing a previously undocumented feature of pynucastro: [Specifying Desired Nuclei to Construct a Network](https://pynucastro.github.io/pynucastro/library-examples-nuclei.html)

I have just tagged two commits as follows on github:

- v1.0.0: the version we submitted to JOSS
- v1.1.0: the current version after incorporating reviewer comments.

We are ready for whatever the next steps are, please let us know.

Thanks again!
Don

**Comment by jschwab** [comment]
> Today I pushed a commit adding a brief section to the documentation describing a previously undocumented feature of pynucastro: Specifying Desired Nuclei to Construct a Network

Just looked that bit over.  That's a nice feature.

**Comment by dwillcox** [comment]
Thanks, I'm glad to hear it!

**Comment by katyhuff** [comment]
Wonderful! Thanks @dwillcox  @zingale @jschwab & @kyleniemeyer !

 @dwillcox  & @zingale : Could you make an archive of the current version of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by dwillcox** [comment]
Hi @katyhuff I have archived the current version on Zenodo, here is the DOI: 10.5281/zenodo.1202434

**Comment by dwillcox** [comment]
Also, I had to make a new release on github in order for Zenodo to archive it, so this is v1.1.1.

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.1202434 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1202434" target="_blank">10.5281/zenodo.1202434</a> is the archive.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by katyhuff** [comment]
@arfon we're ready to accept this!

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00588/joss.00588/10.21105.joss.00588.pdf)

**Comment by arfon** [comment]
@jschwab @kyleniemeyer - many thanks for your reviews here and to @katyhuff for editing this submission ✨ 

@dwillcox - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00588 ⚡️:rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00588/status.svg)](https://doi.org/10.21105/joss.00588)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00588/status.svg)](https://doi.org/10.21105/joss.00588)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by dwillcox** [comment]
Thanks again @katyhuff @jschwab @kyleniemeyer -- it's been a pleasure interacting with you as we prepared pynucastro for publication via JOSS.

This was my first time using JOSS and this has been a very constructive experience!

-Don

**Comment by dwillcox** [comment]
Quick question @katyhuff -- since we retain copyright to the JOSS paper and it's licensed as CC-BY, can we submit the JOSS paper to the arXiv preprint server without modification?

**Comment by katyhuff** [comment]
Whoops --- I only just now saw this. Yes, I think so.
