### ISSUE TITLE
Notification to users when their open review is 'closed' by changes to publisher review display policy

### ISSUE THREAD

**Issue by LauraHarvey** [openjournals/joss-reviews#59]

**Comment by LauraHarvey** [comment]
@andrewtothemax, @arhpreston will be intereste in this, plus probably @pennydown and @drjohnston

**Comment by kyleniemeyer** [comment]
Hi @LauraHarvey—I think you may have submitted this issue to the wrong repository. joss-reviews is only used to track progress of reviews for the Journal of Open Source Software.

Was this intended for the [main JOSS repo](https://github.com/openjournals/joss/issues)?

**Comment by LauraHarvey** [comment]
Argh, sorry about that, will remove...
