### ISSUE TITLE
[PRE REVIEW]: Phylen: automatic phylogenetic reconstruction using the EggNOG database

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#590]
**Submitting author:** @giraola (<a href="http://orcid.org/0000-0002-6516-3404">Gregorio Iraola</a>)
**Repository:** <a href="https://github.com/iferres/phylen" target ="_blank">https://github.com/iferres/phylen</a>
**Version:** v0.1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @juanvillada

**Author instructions**

Thanks for submitting your paper to JOSS @giraola. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@giraola if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #590 with the following error: 

 Can't find any papers to compile :-(

**Comment by giraola** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by giraola** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by giraola** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
I'm sorry @giraola, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by giraola** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #590 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/590/paper.md): mapping values are not allowed in this context at line 17 column 30 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by iferres** [comment]
@whedon compile pdf

**Comment by iferres** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #590 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/590/paper.md): mapping values are not allowed in this context at line 17 column 30 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by iferres** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00590/joss.00590/10.21105.joss.00590.pdf)

**Comment by iferres** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00590/joss.00590/10.21105.joss.00590.pdf)

**Comment by iferres** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00590/joss.00590/10.21105.joss.00590.pdf)

**Comment by iferres** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @iferres, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by iferres** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00590/joss.00590/10.21105.joss.00590.pdf)

**Comment by iferres** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00590/joss.00590/10.21105.joss.00590.pdf)

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00590/joss.00590/10.21105.joss.00590.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @iferres @giraola thanks for your submission. Can you help suggest potential reviewers in your field?

**Comment by giraola** [comment]
Hi @Kevin-Mattheus-Moerman, from the list of reviewers we suggest @kortschak, @serine or @juanvillada from the list of JOSS reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@KlausVigo would you or your co-workers be interested in reviewing this submission for JOSS (the journal of open source software)? 

Review largely focuses on [the software project](https://github.com/iferres/phylen) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.00590/joss.00590/10.21105.joss.00590.pdf). 

Background information: 
- About [JOSS](http://joss.theoj.org/)
- [Reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines)

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @giraola 
@kortschak, @serine or @juanvillada you were suggested as reviewers. Are you interested/available to help with this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by kortschak** [comment]
I can do this, though R is not a preferred language for me so if one of the others want to pick this up that may be better. Having had a brief look through the code though, I don't see any obvious automated testing.

**Comment by juanvillada** [comment]
Hi there! I am available to help, count on me if still required.

**Comment by serine** [comment]
I'm happy for either @juanvillada or @kortschak to take this one, mainly because because I have some work built up and won't be able to commit to this until after a week or so, but can do it later on. 

Thanks,

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @juanvillada as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @juanvillada

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/593. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
Okay @giraola @iferres we've started review at #593 the first reviewer is @juanvillada. @kortschak I'll add you as a second reviewer and any comments you have are welcome. I'll also search for a 3rd reviewer, perhaps @KlausVigo

**Comment by KlausVigo** [comment]
@Kevin-Mattheus-Moerman I could look at it but I have no time this week. Is there any potential conflict of interest as the package uses (and luckily cites) phangorn a lot?

**Comment by Kevin-Mattheus-Moerman** [comment]
@KlausVigo thanks. This review issue will remain open for a bit so we can wait for your to join after this week. Your input would be greatly appreciated! 
Thanks for raising the issue of a conflicts of interest. I do not think them citing/using your work is an issue. In fact it further illustrates that you are a suitable reviewer as this directly applied to your expertise. We also have multiple reviewers for this submission. I'll add you as a reviewer as well and look forward to your comments. Let me know if you have any questions about the review process. It essentially involves ticking boxes at the top of this issue (I'll create a list for you).
