### ISSUE TITLE
[PRE REVIEW]: A reusable tree-based web-visualization to browse EDAM ontology, and contribute to it.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#591]
**Submitting author:** @bryan-brancotte (<a href="http://orcid.org/0000-0001-8669-5525">Bryan Brancotte</a>)
**Repository:** <a href="https://github.com/IFB-ElixirFr/edam-browser" target ="_blank">https://github.com/IFB-ElixirFr/edam-browser</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewers:** @alexgarciac

**Author instructions**

Thanks for submitting your paper to JOSS @bryan-brancotte. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bryan-brancotte if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
Hi 
The labels should be updated, Python should be removed and JavaScript added.
Best,

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00591/joss.00591/10.21105.joss.00591.pdf)

**Comment by bryan-brancotte** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @bryan-brancotte, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
@bryan-brancotte - we'll need to find an editor and a reviewer before we can start this review. This can sometimes find a couple of weeks.

Cheers
Arfon

**Comment by bryan-brancotte** [comment]
Sorry, for the inconvenience @arfon, I though that I had to do an action to initiate the search of editor and reviewer.

Regarding the labels, Python should be removed and JavaScript added.

Cheers
Bryan

**Comment by danielskatz** [comment]
@jasonclark - would you be willing to edit this submission?

**Comment by arfon** [comment]
@bryan-brancotte - many thanks for your submission to JOSS. This looks like an interesting project.

The paper as it stands, is substantially longer than we usually allow for JOSS submissions. In particular, much of this content looks like it might be more appropriate for for the software documentation.

Could you please take a look at the ['What should my paper contain'](http://joss.theoj.org/about#paper_structure) section of the author guidelines and revise the paper?

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by bryan-brancotte** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by bryan-brancotte** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by bryan-brancotte** [comment]
Hi @arfon 
We re submitted a condensed version of the paper (-60%) which is now compliant with 'What should my paper contain'. Note that the compilation never ends.
Best regards

**Comment by arfon** [comment]
Here's the compiled PDF: [10.21105.joss.00591.pdf](https://github.com/openjournals/joss-reviews/files/1807659/10.21105.joss.00591.pdf)

**Comment by hmenager** [comment]
thank you very much for providing the pdf @arfon

**Comment by bryan-brancotte** [comment]
Hi @arfon
Thanks for the pdf, I have done minor updates in the paper since its production, but the result it ok for us.

**Comment by arfon** [comment]
:wave: @mgymrek - would you be willing to edit this submission for JOSS?

**Comment by jasonclark** [comment]
If you don't hear back from @mgymrek, I can help with the editing.

**Comment by pjotrp** [comment]
@whedon assign @jasonclark as reviewer

**Comment by pjotrp** [comment]
@whedon assign @jasonclark as editor

**Comment by whedon** [comment]
OK, the editor is @jasonclark

**Comment by pjotrp** [comment]
@whedon add @pjotrp as editor

**Comment by pjotrp** [comment]
Nice try. @arfon, two editors not allowed. @whedon is silent. @jasonclark I can help find a reviewer, or take over as an editor if you prefer.

**Comment by pjotrp** [comment]
Sorry I added you as an editor without asking - I wanted to add both of us.

**Comment by pjotrp** [comment]
@alexgarciac offers to review the Edam browser.

**Comment by arfon** [comment]
> Nice try. @arfon, two editors not allowed. @whedon is silent. @jasonclark I can help find a reviewer, or take over as an editor if you prefer.

Yes, this is expected. https://github.com/openjournals/whedon-api/pull/25 only added support for multiple _reviewers_.

**Comment by pjotrp** [comment]
@jasonclark ping

**Comment by arfon** [comment]
*bump* - what's the plan with this submission? Looks like we have a willing editor in @pjotrp and a reviewer in @alexgarciac.

@pjotrp - I suggest you move ahead with this.

**Comment by arfon** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by whedon** [comment]
OK, the reviewer is @alexgarciac

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/698. Feel free to close this issue now!
