### ISSUE TITLE
[PRE REVIEW]: DynamicalSystems.jl: A Julia software library for chaos and nonlinear dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#594]
**Submitting author:** @Datseris (<a href="http://orcid.org/0000-0002-6427-2385">George Datserus</a>)
**Repository:** <a href="https://github.com/JuliaDynamics/DynamicalSystems.jl" target ="_blank">https://github.com/JuliaDynamics/DynamicalSystems.jl</a>
**Version:** v0.11.0
**Editor:** @kyleniemeyer
**Reviewer:** @dhhagan

**Author instructions**

Thanks for submitting your paper to JOSS @Datseris. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Datseris if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by Datseris** [comment]
Both packages are part of the same GitHub organization, "JuliaDynamics" and I am the author of both of them.

As far as what they do, they are not related though. One is about 2-dimensional billiards, a quite special class of chaotic systems, while the one submitted here is about studying nonlinear dynamics and chaos.

Both packages certainly fall under the same field of science (Nonlinear Dynamics), but their underlying scope *and* code are very different.

**Comment by Datseris** [comment]
@ahwillia @mlxd have reviewed a previous submission of mine. 

Both the reviewers and myself were pleased with how smoothly the review process went, so I am suggesting them for this submission as well.

**Comment by ahwillia** [comment]
I'm happy to review another submission! I'm busy for the next 2.5 weeks but
I can do a review after that.

If you want a quicker turn around I'd suggest finding someone else...

**Comment by Datseris** [comment]
I am not in any crazy hurry, but I can also suggest @Adrianzo @dhhagan @ygrange from the list of reviewers. Each one has some (maybe distant) connection with what the library offers.

**Comment by kyleniemeyer** [comment]
@ahwillia that timeline is fine, thanks! 

@mlxd are you available to review as well?

**Comment by dhhagan** [comment]
I'm available if you need.

**Comment by Datseris** [comment]
Well, if I can have any say, then of course I'd prefer the faster start on the review :)

**Comment by mlxd** [comment]
I'm unavailable for about 2 more weeks so please go ahead if others are free to review.

**Comment by kyleniemeyer** [comment]
@dhhagan thanks for volunteering! We can get the review started with you, but I would also like to get some feedback from @ahwillia and/or @mlxd for a second set of eyes.

**Comment by kyleniemeyer** [comment]
@whedon assign @dhhagan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dhhagan

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/598. Feel free to close this issue now!
