### ISSUE TITLE
[PRE REVIEW]: LearnSAT: A SAT Solver for Education

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#595]
**Submitting author:** @motib (<a href="http://orcid.org/0000-0002-2091-5107">Mordechai Ben-Ari</a>)
**Repository:** <a href="https://github.com/motib/LearnSAT" target ="_blank">https://github.com/motib/LearnSAT</a>
**Version:** V2.0
**Editor:** @danielskatz
**Reviewer:** @audemard

**Author instructions**

Thanks for submitting your paper to JOSS @motib. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@motib if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by motib** [comment]
Hello,

1. When you say "type @whedon commands", where do I type it??

2. I looked at the list of reviewers. No one is actually in the field of the application of logic to computer science (verification, SAT solving, logic programming, etc.), but krother and hainesr might be appropriate
because of their interest in education.

3. Sorry about the bib file, but the instructions didn't say where to put it.
It is in the directory "docs".
Should I have used "docs/learnsat.bib" as the file name?
Should I have uploaded it to the top level directory with "paper.md".
I am guess that I should have uploaded there, so I have now done so.

I am totally new to Markdown and have limited experience with Git,
so I apologize for any problems and will be grateful for your help.

@motib

**Comment by motib** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by motib** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00595/joss.00595/10.21105.joss.00595.pdf)

**Comment by motib** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00595/joss.00595/10.21105.joss.00595.pdf)

**Comment by danielskatz** [comment]
@motib - do you have any suggested reviewers, even outside the list of JOSS volunteers?

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by motib** [comment]
Matti Järvisalo?
matti.jarvisalo@helsinki.fi
https://www.cs.helsinki.fi/u/mjarvisa/

**Comment by danielskatz** [comment]
@shnarazk, @niklaseen, @alanminko - would you be willing to review this submission to JOSS?

**Comment by motib** [comment]
Hi Daniel, Looking at your suggestions, @shnarazk works in SAT solving, the same area as my submission, and would be the most qualified to review it.

**Comment by danielskatz** [comment]
@whedon assign @audemard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @audemard

**Comment by danielskatz** [comment]
note to all that I am still looking for one more reviewer, after which I will start the review in a new issue - there are no actions needed at this time, unless you are a potential reviewer who wants to volunteer to review this submission.

**Comment by danielskatz** [comment]
@biotomas - would you be willing to review this submission for JOSS?

**Comment by danielskatz** [comment]
@biotomas agreed (via email) to review.

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/639. Feel free to close this issue now!
