### ISSUE TITLE
[PRE REVIEW]: NiaPy: Python microframework for building nature-inspired algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#599]
**Submitting author:** @GregaVrbancic (<a href="http://orcid.org/0000-0003-0723-3889">Grega Vrbančič</a>)
**Repository:** <a href="https://github.com/NiaOrg/NiaPy" target ="_blank">https://github.com/NiaOrg/NiaPy</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewer:** @ljvmiranda921

**Author instructions**

Thanks for submitting your paper to JOSS @GregaVrbancic. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@GregaVrbancic if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00599/joss.00599/10.21105.joss.00599.pdf)

**Comment by GregaVrbancic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00599/joss.00599/10.21105.joss.00599.pdf)

**Comment by GregaVrbancic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00599/joss.00599/10.21105.joss.00599.pdf)

**Comment by GregaVrbancic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00599/joss.00599/10.21105.joss.00599.pdf)

**Comment by GregaVrbancic** [comment]
@arfon our suggestion for potential reviewers: 

@barentsen 
@mattpitkin

**Comment by ljvmiranda921** [comment]
Hi, I was also contacted by one of the authors (Dr. Iztok Fister Jr.) through e-mail  to review this submission. I'm interested to review but:
- I'll only be free by March 19; and
- I'm not part of the official reviewers of JOSS

In addition, I can also recommend @\stsievert , my reviewer during [my submission in PySwarms](https://github.com/openjournals/joss-reviews/issues/433) if that will be a better option.

**Comment by arfon** [comment]
@whedon assign @ljvmiranda921 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ljvmiranda921

**Comment by arfon** [comment]
@ljvmiranda921 - excellent. Thanks! 

> I'm not part of the official reviewers of JOSS

Absolutely, there's no 'requirement' to be an official reviewer for future reviews.

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/613. Feel free to close this issue now!
