### ISSUE TITLE
[REVIEW]: hebbRNN: A Reward-Modulated Hebbian Learning Rule for Recurrent Neural Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#60]
**Submitting author:** JonathanAMichaels (<a href="http://orcid.org/0000-0002-5179-3181">Jonathan A Michaels</a>)
**Repository:** <a href="https://github.com/JonathanAMichaels/hebbRNN" target ="_blank">https://github.com/JonathanAMichaels/hebbRNN</a>
**Version:** v1.2
**Editor:** @arfon 
**Reviewer:** @cMadan 
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.154745" target="_blank">10.5281/zenodo.154745</a>

## Status

[![status](http://joss.theoj.org/papers/03d299789d8d6b633e648342b4454dca/status.svg)](http://joss.theoj.org/papers/03d299789d8d6b633e648342b4454dca)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/03d299789d8d6b633e648342b4454dca"><img src="http://joss.theoj.org/papers/03d299789d8d6b633e648342b4454dca/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/03d299789d8d6b633e648342b4454dca/status.svg)](http://joss.theoj.org/papers/03d299789d8d6b633e648342b4454dca)
```
**Reviewers and authors**: Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue
in the <a href="https://github.com/JonathanAMichaels/hebbRNN" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers)
in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice
versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JonathanAMichaels/hebbRNN">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00060.pdf](https://github.com/openjournals/joss-reviews/files/466546/10.21105.joss.00060.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by cMadan** [comment]
:hand: I am reviewing this

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @cMadan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cMadan

**Comment by cMadan** [comment]
@JonathanAMichaels - sorry for the delay in reviewing your submission.

I looked at the documentation, tried the examples, and checked over everything--your submission impressively follows the JOSS guidelines as-submitted!

I have only two minor suggestions that need to be addressed:
(1) paper.bib, references are missing DOIs.
(2) README.md, typo: "dependecies"

Pending these very minor changes, I am happy to recommend the submission be accepted at JOSS.

**Comment by JonathanAMichaels** [comment]
Thank you for the very positive review!

I have corrected both errors with the exception of one reference that does not have a DOI.

**Comment by cMadan** [comment]
Looks good to me!

@arfon - I am happy to recommend this submission be accepted at JOSS.

**Comment by arfon** [comment]
> @arfon - I am happy to recommend this submission be accepted at JOSS.

@cMadan thanks for turning this around quickly.

@JonathanAMichaels at this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by JonathanAMichaels** [comment]
@arfon Done! Here's the archive: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.154745.svg)](https://doi.org/10.5281/zenodo.154745)

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.154745 as archive

**Comment by whedon** [comment]
OK. <a href='http://dx.doi.org/10.5281/zenodo.154745' target='_blank'>10.5281/zenodo.154745</a> is the archive.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.154745 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.154745" target="_blank">10.5281/zenodo.154745</a> is the archive.

**Comment by arfon** [comment]
Thanks again for the review @cMadan!

@JonathanAMichaels your paper is now accepted into JOSS. Your paper DOI is http://dx.doi.org/10.21105/joss.00060 🎉 🚀 💥
