### ISSUE TITLE
[PRE REVIEW]: 3D ultrasound file reading and coordinate transformations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#600]
**Submitting author:** @plooney (<a href="http://orcid.org/0000-0002-0764-5413">Padraig Looney</a>)
**Repository:** <a href="https://github.com/plooney/kretz" target ="_blank">https://github.com/plooney/kretz</a>
**Version:** 0.01
**Editor:** @cMadan
**Reviewers:** @thewtex

**Author instructions**

Thanks for submitting your paper to JOSS @plooney. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@plooney if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @cMadan - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00600/joss.00600/10.21105.joss.00600.pdf)

**Comment by cMadan** [comment]
Hi @plooney! 

I took a quick look at your project repo, but it seems like the Readme isn't 'minimally complete' yet and the paper.md is still quite brief. While papers at JOSS are brief, they still need to sufficiently describe the project's purpose and the function it fulfills. If you haven't already, you should take a look at some recently accepted papers/projects as examples of the state they are in to be publishable at JOSS.

Let us know if you have any questions about the process!

**Comment by plooney** [comment]
I've added to the readme and the paper. What constitutes 'minimally complete'? I've not described the CMake steps in detail. A necessary requirement to use this is to have ITK installed so familiarity with the CMake build process is fair to assume.

**Comment by cMadan** [comment]
HI @plooney,

If you take a look at any of the review issues (e.g., https://github.com/openjournals/joss-reviews/issues/597), there is a list of what a reviewer will be asked to check for as part of the JOSS review. As your repo is now, many of these are currently missing or incomplete. E.g., no community guidelines, there is a test with an example input but not output, there is only a single sentence to address functionality, statement of need. 

If you look at the repo for this submission, https://github.com/FastNFT/FNFT, you can see that the readme is significantly more detailed (admittedly you may not need OS-dependent installation instructions, but you can see the difference in the level of detail between the two).

**Comment by plooney** [comment]
Hi @cMadab,

I've added to the ReadMe usinf the FNFT as a sample to address these issues. 

I'm not clear on the point you make on the test. There are four tests listed in the CMakeLists with various input and output. "make test" will run all four and produce output and the input is also present. A sample image is downloaded and placed into the test folder that is used in the first three tests.

**Comment by cMadan** [comment]
For the tests, I think the output file should also be provided, so that the user can compare their output file with the pre-made output file to confirm that the code ran successfully.

**Comment by plooney** [comment]
@cMadan I've added those changes to the repository

**Comment by cMadan** [comment]
Great! Do you have any suggestions for potential reviewers?

**Comment by plooney** [comment]
I recommend @thewtex

https://github.com/thewtex

**Comment by plooney** [comment]
@lassoan

**Comment by cMadan** [comment]
Hi @thewetex and @lassoan, would either of you be available to review this submission?

**Comment by thewtex** [comment]
I can help with a review, but it will be a few weeks before I can take it on.

**Comment by cMadan** [comment]
@thewtex, we don't have anyone else right now, so that's fine with me. Let me know when I should nudge you about the review and start the process.

**Comment by cMadan** [comment]
@whedon assign @thewtex as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @thewtex

**Comment by cMadan** [comment]
Hi @thewtex, are you now available to review this submission?

**Comment by thewtex** [comment]
Sorry, @cMadan I have some other reviews I am behind on at the moment, and I will soon be traveling for about a month. To set expectation, it will be a month and a half until I will be able to get to this.

**Comment by cMadan** [comment]
@thewtex, okay, thanks for letting us know.

@plooney, is this okay with you, or do you have any alternate suggestions for potential reviewers?

**Comment by lassoan** [comment]
> This software was not inspired by your KretzFileReader

The two solutions are so similar, it's fascinating that we ended up implementing all this so similarly.

>  I will look to implementing them when time permits

Finding a suitable repository name and making sure the library can be built on all platforms would be important. Let me know what are the items in the mandatory list that you may not have time to implement and I'll try to help.

What is your plan in term of maintenance, support, developments in the future? Do you plan to review and accept pull request with improvements?

**Comment by thewtex** [comment]
Sorry I will not be able to follow up on this more until after I return from a conference the week after next.

Thanks @lassoan for the review and suggestions. Regarding

> File hosting on google drive is fragile. It is already broken (files are not available at the link provided) and even if you fix it, it is likely to break again. I would recommend to use the same test data hosting mechanism as all other ITK remote modules.

We currently host ITK module testing data on [data.kitware.com](https://data.kitware.com). @plooney  if you sign up for an account there, you can host files in your personal folder. Even better, let me know your account name, and I will add upload permissions to the [ITK Remote Module testing data folder](https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/5817681d8d777f10f26ee354). This can be used [as a content link](https://itk.org/ITKExamples/Documentation/Contribute/UploadBinaryData.html) if an [External/Remote ITK module is created](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate)

@stefanklein indicated he could possibly use this contribution to help with his research -- he may also be a good reviewer.

**Comment by cMadan** [comment]
@plooney, can you let me know how/if you want to proceed with the review here?

**Comment by plooney** [comment]
What are the next steps that are required?

**Comment by cMadan** [comment]
@lassoan has provided some detailed comments and suggestions, I would appreciate it if you could respond to each of these. @thewtex has also provided some suggestions for hosting test data, as well as provided the suggestion for a reviewer.

**Comment by arfon** [comment]
:wave: @cMadan - how are we doing here?

**Comment by cMadan** [comment]
@thewtex, that would be great! I'll start the actual review process now since there is enough to go ahead, but, @plooney, please do seriously consider the feedback provided already and see how you can make changes based on the issues already pointed out.

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1063. Feel free to close this issue now!
