### ISSUE TITLE
[PRE REVIEW]: Eixport, an R Package to export emissions to atmospheric models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#601]
**Submitting author:** @ibarraespinosa (<a href="http://orcid.org/0000-0002-3162-1905">Sergio Ibarra</a>)
**Repository:** <a href="https://github.com/atmoschem/eixport" target ="_blank">https://github.com/atmoschem/eixport</a>
**Version:** v0.3.0
**Editor:** @leeper
**Reviewer:** @jhollist

**Author instructions**

Thanks for submitting your paper to JOSS @ibarraespinosa. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ibarraespinosa if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #601 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     28      0 --:--:-- --:--:-- --:--:--    28
Error reading bibliography ./paper.bib (line 66, column 18):
unexpected "."
expecting white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
👋 @leeper - the submitting author suggested you as the handling editor.

**Comment by ibarraespinosa** [comment]
Dear @whedon @arfon @leeper  I have edited the paper.bib file. It now should compile PDF. Thanks

**Comment by leeper** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #601 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     60      0 --:--:-- --:--:-- --:--:--    60
Error reading bibliography ./paper.bib (line 66, column 18):
unexpected "."
expecting white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@ibarraespinosa looks like PDF is still not compiling successfully. Please try to fix.

**Comment by ibarraespinosa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #601 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100    16    0    16    0     0      2      0 --:--:--  0:00:05 --:--:--     3
Error reading bibliography ./paper.bib (line 66, column 18):
unexpected "."
expecting white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ibarraespinosa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00601/joss.00601/10.21105.joss.00601.pdf)

**Comment by ibarraespinosa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00601/joss.00601/10.21105.joss.00601.pdf)

**Comment by leeper** [comment]
@jhollist Would you be interested in reviewing this for JOSS?

**Comment by jhollist** [comment]
Only know a little about emissions and air quality... 

That being said would be happy to review.

**Comment by leeper** [comment]
@jhollist I don't think that's critical in this case given what the package does. But please don't feel obligated to say yes!

**Comment by jhollist** [comment]
No obligation!  Still happy to do it.

**Comment by leeper** [comment]
Great!

**Comment by leeper** [comment]
@whedon assign @jhollist as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jhollist

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/607. Feel free to close this issue now!
