### ISSUE TITLE
[PRE REVIEW]: microPIECE (microRNA pipeline enhanced by CLIP experiments)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#603]
**Submitting author:** @greatfireball (<a href="http://orcid.org/0000-0003-4166-5423">Frank Förster</a>)
**Repository:** <a href="https://github.com/microPIECE-team/microPIECE" target ="_blank">https://github.com/microPIECE-team/microPIECE</a>
**Version:** v1.1.0
**Editor:** @brainstorm
**Reviewer:** @luizirber

**Author instructions**

Thanks for submitting your paper to JOSS @greatfireball. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@greatfireball if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #603 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0     55      0 --:--:-- --:--:-- --:--:--    55
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00603.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by DanielAmsel** [comment]
Sorry to see that the PDF compilation step failed.
We tested this with our docker container and it worked: 
`greatfireball/docker_whedon_translate4joss`

Any ideas how to fix that?

**Comment by DanielAmsel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00603/joss.00603/10.21105.joss.00603.pdf)

**Comment by DanielAmsel** [comment]
Looks good to me.

**Comment by arfon** [comment]
@brainstorm @mgymrek - would either of you be willing to edit this submission for JOSS?

**Comment by brainstorm** [comment]
Sure! Happy to :)

Den 10 mars 2018 8:34 fm skrev "Arfon Smith" <notifications@github.com>:

**Comment by greatfireball** [comment]
Morning @arfon and @brainstorm 

Thanks for agreeing to edit our submission!

In between, we updated to version v1.1.0

**Comment by arfon** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by arfon** [comment]
> Sure! Happy to :)

Great! Next step is to look for a reviewer, probably someone from here: http://bit.ly/joss-reviewers

**Comment by brainstorm** [comment]
Sure, I think @luizirber would do a fantastic job reviewing this if he has the time and stamina? ;)

**Comment by luizirber** [comment]
sure =]

**Comment by brainstorm** [comment]
Awesome, thanks! ;)

@whedon assign @luizirber as reviewer

**Comment by arfon** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/616. Feel free to close this issue now!

**Comment by arfon** [comment]
@luizirber @brainstorm - I've gone ahead and opened the main review issue in #616
