### ISSUE TITLE
[PRE REVIEW]: coalitions: Coalition probabilities in multi-party democracies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#604]
**Submitting author:** @adibender (<a href="http://orcid.org/0000-0001-5628-8611">Andreas Bender</a>)
**Repository:** <a href="https://github.com/adibender/coalitions" target ="_blank">https://github.com/adibender/coalitions</a>
**Version:** v0.6.0
**Editor:** @leeper
**Reviewer:** @fsolt

**Author instructions**

Thanks for submitting your paper to JOSS @adibender. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@adibender if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00604/joss.00604/10.21105.joss.00604.pdf)

**Comment by arfon** [comment]
:wave: @leeper - the submitting author suggested you as the handling editor.

**Comment by leeper** [comment]
@whedon assign @fsolt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @fsolt

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/606. Feel free to close this issue now!
