### ISSUE TITLE
[PRE REVIEW]: Temporalis: an open source software for dynamic LCA

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#605]
**Submitting author:** @cardosan (<a href="http://orcid.org/0000-0003-0442-3580">Giuseppe Cardellini</a>)
**Repository:** <a href="https://bitbucket.org/cardosan/brightway2-temporalis" target ="_blank">https://bitbucket.org/cardosan/brightway2-temporalis</a>
**Version:** 1.0
**Editor:** @arfon
**Reviewer:** @pjamesjoyce

**Author instructions**

Thanks for submitting your paper to JOSS @cardosan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cardosan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #605 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by cardosan** [comment]
HI all,
perhaps @amoeba, who already reviewed Brightway2 #236, might be an option.
Also @pjamesjoyce, which submitted Lcopt #335 and knows about LCA, might be a great candidate for this review.

**Comment by amoeba** [comment]
Hey @cardosan thanks for thinking of me. I'm too swamped to turn this around in a prompt fashion but I'll check back here on March 12 in case you haven't found a reviewer by then.

**Comment by pjamesjoyce** [comment]
Hi @cardosan I'm happy to contribute to the review from a technical LCA standpoint at least. If the editor's happy with me to undertake the full review that's also fine by me.

**Comment by cardosan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @pjamesjoyce as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pjamesjoyce

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/612. Feel free to close this issue now!

**Comment by arfon** [comment]
@pjamesjoyce - many thanks for volunteering here. I've opened up the main review issue over in #612 - see you over there!
