### ISSUE TITLE
[PRE REVIEW]: HSImage: A Python and C++ library to allow interaction with ENVI-BIL hyperspectral images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#608]
**Submitting author:** @DTChuck (<a href="http://orcid.org/0000-0002-3832-775X">Ryan Brown</a>)
**Repository:** <a href="https://github.com/DTChuck/HSImage" target ="_blank">https://github.com/DTChuck/HSImage</a>
**Version:** v1.2.0
**Editor:** @arfon
**Reviewer:** @abhishekbajpayee

**Author instructions**

Thanks for submitting your paper to JOSS @DTChuck. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@DTChuck if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #608 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00608/joss.00608/10.21105.joss.00608.pdf)

**Comment by DTChuck** [comment]
The hyperlinks in the generated PDF are not blue. Is that expected?

**Comment by arfon** [comment]
> The hyperlinks in the generated PDF are not blue. Is that expected?

@DTChuck yes, I think that's normal. 

Would you mind taking a look at the [list of JOSS reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) and seeing if you think there are any that could be good reviewers here?

**Comment by DTChuck** [comment]
I think that the following people are possibly good reviewers:
@abhishekbajpayee
@sgrieve 
@oesteban 
@abuccts
@earino

**Comment by DTChuck** [comment]
Just wanted to check if there was anything else I needed to get to people before the review could start.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @abhishekbajpayee, @oesteban, @abuccts, @earino would one of you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
> Just wanted to check if there was anything else I needed to get to people before the review could start.

Once we have a reviewer assigned we can get going.

**Comment by abhishekbajpayee** [comment]
I would be happy to review.

Abhishek

**Comment by arfon** [comment]
@whedon assign @abhishekbajpayee as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @abhishekbajpayee

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/630. Feel free to close this issue now!

**Comment by arfon** [comment]
@abhishekbajpayee - excellent, thanks! See you over in #630 for the actual review.
