### ISSUE TITLE
[PRE REVIEW]: Open OnDemand: A web-based client portal for HPC centers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#609]
**Submitting author:** @ericfranz (<a href="http://orcid.org/0000-0002-9662-412X">Eric Franz</a>)
**Repository:** <a href="https://github.com/OSC/Open-OnDemand" target ="_blank">https://github.com/OSC/Open-OnDemand</a>
**Version:** v1.2
**Editor:** @danielskatz
**Reviewer:** @marpierc

**Author instructions**

Thanks for submitting your paper to JOSS @ericfranz. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ericfranz if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00609/joss.00609/10.21105.joss.00609.pdf)

**Comment by arfon** [comment]
@danielskatz - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon assign danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is danielskatz

**Comment by danielskatz** [comment]
@marpierc - would you be able to review this for us?

**Comment by danielskatz** [comment]
@smgallo - would you be willing to review this submission to JOSS?

**Comment by marpierc** [comment]
@danielskatz when do you need the review completed?

**Comment by danielskatz** [comment]
Ideally in the next couple of weeks - would that work for you?

**Comment by danielskatz** [comment]
@marpierc - pinging, would the next couple of weeks work as a deadline?

**Comment by marpierc** [comment]
I can submit by April 5th.  Does that date work for you?

 

Marlon

**Comment by danielskatz** [comment]
yes, thanks.  I'll start the review process now.

**Comment by danielskatz** [comment]
@whedon assign @marpierc as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @marpierc

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/622. Feel free to close this issue now!

**Comment by smgallo** [comment]
@danielskatz I can review by the end of March if that is OK with you.

**Comment by danielskatz** [comment]
@smgallo - great - having 2 reviewers is much better than 1.  See https://github.com/openjournals/joss-reviews/issues/622 which I'll finish setting up in 5 or so more minutes.
