### ISSUE TITLE
[PRE REVIEW]: OpenEPSim: An Open Exclusion Process Simulation Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#610]
**Submitting author:** @caley (<a href="http://orcid.org/0000-0001-8593-1987">Caley Finn</a>)
**Repository:** <a href="https://github.com/caley/OpenEPSim" target ="_blank">https://github.com/caley/OpenEPSim</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewers:** @stuartcampbell, @dlagrava

**Author instructions**

Thanks for submitting your paper to JOSS @caley. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@caley if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00610/joss.00610/10.21105.joss.00610.pdf)

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by caley** [comment]
@arfon perhaps stuartcampbell, dlagrava, or krother.  They all have Java listed and mathematics backgrounds.  Also jochym who seems to have a relevent math/physics background, but not Java.

**Comment by arfon** [comment]
:wave: @stuartcampbell, @dlagrava and @jochym - would you be willing to review this submission for JOSS. As this is outside my subject area as an editor I'd like to find two reviewers if possible.

**Comment by stuartcampbell** [comment]
Yes I am willing to have a look...

**Comment by dlagrava** [comment]
@arfon I can also give a look to this.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @stuartcampbell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stuartcampbell

**Comment by arfon** [comment]
@whedon add @dlagrava as reviewer

**Comment by whedon** [comment]
OK, @dlagrava is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/650. Feel free to close this issue now!

**Comment by arfon** [comment]
@stuartcampbell, @dlagrava - please head over to #650 to carry out the actual review.
