### ISSUE TITLE
[PRE REVIEW]: Optim: An optimization package for Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#611]
**Submitting author:** @anriseth (<a href="http://orcid.org/0000-0002-5861-7885">Asbjørn Nilsen Riseth</a>)
**Repository:** <a href="https://github.com/JuliaNLSolvers/Optim.jl" target ="_blank">https://github.com/JuliaNLSolvers/Optim.jl</a>
**Version:** v0.14.0
**Editor:** @labarba
**Reviewer:** @ahwillia 

**Author instructions**

Thanks for submitting your paper to JOSS @anriseth. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@anriseth if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @labarba - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00611/joss.00611/10.21105.joss.00611.pdf)

**Comment by anriseth** [comment]
Of the existing reviewers, may I suggest @vchuravy and  @ahwillia? They both know Julia very well, and machine learning backgrounds may be helpful in terms of optimization.
Another person in the Julia optimization community that has a an appropriate background is @abelsiqueira.

**Comment by anriseth** [comment]
The article proof looks fine. I'll also cc @pkofod

**Comment by ahwillia** [comment]
I'm happy to review.

I've used this package extensively in the past and have had mostly good experiences. I haven't used it in the past year or so.

**Comment by abelsiqueira** [comment]
I can review as well.

**Comment by labarba** [comment]
@whedon assign @ahwillia  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ahwillia

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/615. Feel free to close this issue now!

**Comment by labarba** [comment]
Thank you for agreeing to review, @ahwillia — Please go over to the REVIEW issue now, where you can use comments to communicate with the author and editors as you complete your review.
https://github.com/openjournals/joss-reviews/issues/615

@anriseth — In your paper, I do miss some brief note about existing software providing similar functionality (in the same or other programming language). We don't have a novelty requirement, but we do want to see other software mentioned or cited, as appropriate.
