### ISSUE TITLE
[PRE REVIEW]: EZyRB: Easy Reduced Basis method

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#614]
**Submitting author:** @mtezzele (<a href="http://orcid.org/0000-0001-9747-6328">Marco Tezzele</a>)
**Repository:** <a href="https://github.com/mathLab/EZyRB" target ="_blank">https://github.com/mathLab/EZyRB</a>
**Version:** v0.2.0
**Editor:** @arfon
**Reviewers:** @dlagrava, @ziotom78

**Author instructions**

Thanks for submitting your paper to JOSS @mtezzele. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mtezzele if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00614/joss.00614/10.21105.joss.00614.pdf)

**Comment by arfon** [comment]
:wave: @jakevdp - the submitting author suggested you as the handling editor.

**Comment by mtezzele** [comment]
I've made a small fix to the bib file (missing doi).

@whedon generate pdf

**Comment by mtezzele** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00614/joss.00614/10.21105.joss.00614.pdf)

**Comment by arfon** [comment]
@mtezzele - could you take a look at the list of reviewers and suggest a few people who might be able to review this submission? https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@ziotom78, @JaroslavHron, @dlagrava - would you be willing to review this submission for JOSS?

**Comment by dlagrava** [comment]
@arfon I need to finish another review and I will be short of time during Easter. If the other guys do not take it or are too busy, I will take it.

**Comment by ziotom78** [comment]
@arfon sure, I'll be happy to do it.

**Comment by arfon** [comment]
> @arfon I need to finish another review and I will be short of time during Easter. If the other guys do not take it or are too busy, I will take it.

@dlagrava ideally I'd like to find two reviewers for this submission as it's outside of my subject expertise and it seems like @jakevdp isn't going to be able to handle this one.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @dlagrava as reviewer

**Comment by whedon** [comment]
OK, @dlagrava is now a reviewer

**Comment by arfon** [comment]
@whedon add @ziotom78 as reviewer

**Comment by whedon** [comment]
OK, @ziotom78 is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/661. Feel free to close this issue now!

**Comment by arfon** [comment]
@dlagrava, @ziotom78 - please head over to #661 to carry out the actual JOSS review.
