### ISSUE TITLE
[REVIEW]: microPIECE (microRNA pipeline enhanced by CLIP experiments)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#616]
**Submitting author:** @greatfireball (<a href="http://orcid.org/0000-0003-4166-5423">Frank Förster</a>)
**Repository:** <a href="https://github.com/microPIECE-team/microPIECE" target ="_blank">https://github.com/microPIECE-team/microPIECE</a>
**Version:** v1.5.0
**Editor:** @brainstorm
**Reviewer:** @luizirber
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1215850" target="_blank">10.5281/zenodo.1215850</a>

## Status

[![status](http://joss.theoj.org/papers/f3f099ff59c8874f9d5b7036f15bbb62/status.svg)](http://joss.theoj.org/papers/f3f099ff59c8874f9d5b7036f15bbb62)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f3f099ff59c8874f9d5b7036f15bbb62"><img src="http://joss.theoj.org/papers/f3f099ff59c8874f9d5b7036f15bbb62/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f3f099ff59c8874f9d5b7036f15bbb62/status.svg)](http://joss.theoj.org/papers/f3f099ff59c8874f9d5b7036f15bbb62)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/microPIECE-team/microPIECE" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@luizirber, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/microPIECE-team/microPIECE">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@greatfireball) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @luizirber it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00616/joss.00616/10.21105.joss.00616.pdf)

**Comment by brainstorm** [comment]
@luizirber Feel free to ask any questions if you have any on how to proceed with this review. Check out the checklist above ;)

**Comment by luizirber** [comment]
@brainstorm on it =]

@greatfireball I see there were quite a bunch of new releases since the submission, do you want me to review the latest one (`1.2.3`?)

**Comment by luizirber** [comment]
Some comments and fixes required:

# General checks

- [ ] André Billion and Andreas Vilcinskas are listed in the paper, but not in the repository. (nothing wrong with that, but maybe they should be in the repo too?)

# Installation

- [ ] Use a tagged version instead of master?
`git clone -b v1.2.3 git@github.com:microPIECE-team/microPIECE.git`
`curl -L -o microPIECE.zip https://github.com/microPIECE-team/microPIECE/archive/v1.2.3.zip`

# Functionality

- [ ] I couldn't reproduce the example in the README using v1.2.3, but it worked with v1.0.0
(both using Docker)

# Documentation

## Installation instructions

- [ ] Most of the dependencies are already in bioconda, you might consider packaging microPIECE too. (This is not a requirement for article approval, but would be nice to have).

# Software paper

## References

- [ ]  DOI are missing

**Comment by DanielAmsel** [comment]
Thank you @luizirber for your review. We are going to fix the raised issues as soon as possible.

**Comment by greatfireball** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by greatfireball** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00616/joss.00616/10.21105.joss.00616.pdf)

**Comment by greatfireball** [comment]
Thanks @luizirber for your review. I think we addressed most of your issues, but we need some help with your issue concerning the example (please see below about our detailed answers). In between, we further improved `microPIECE` and pushed our current version to `v1.4.0`. Moreover, we added an explaination why we chose `miraligner` as isomer detection tool into the manuscript.

## General checks

- [X]  André Billion and Andreas Vilcinskas are listed in the paper, but not in the repository. (nothing wrong with that, but maybe they should be in the repo too?)

**Answer**: *Neither André nor Andreas wrote a single line of code, but they have been involved in developing the method. Therefore, they own not a single commit or comment in our repository, but are co-authors of our paper*

## Installation

- [X] Use a tagged version instead of master?
```
git clone -b v1.2.3 git@github.com:microPIECE-team/microPIECE.git
curl -L -o microPIECE.zip https://github.com/microPIECE-team/microPIECE/archive/v1.2.3.zip
```
**Answer**: *We updated the installation instructions and used the current tag. This modification includes the usage of tags for the docker containers.*

## Functionality
- [ ] I couldn't reproduce the example in the README using v1.2.3, but it worked with v1.0.0
    (both using Docker)

**Answer**: *To be honest, we tested the example using different operation systems (Ubuntu/OSX) on different machines and had not a single failure running our example. Can you give a little more details about your setup and what step failed?*

## Documentation
### Installation instructions

- [ ] Most of the dependencies are already in bioconda, you might consider packaging microPIECE too. (This is not a requirement for article approval, but would be nice to have).

**Answer**: *I will check for all dependencies and will create a bioconda recipe in the near future. If finished, we will include an installation via bioconda as alternative into our documentation*

## Software paper
### References
- [X] DOI are missing

**Answer**: *We included the missing DOIs*

**Comment by luizirber** [comment]
Thanks for the comments and updates @greatfireball and @DanielAmsel!

I reran the docker example and it worked now, may have been a glitch on my side (I don't have the error message anymore...)

@brainstorm I checked all the boxes, I think this is good to go! (can you update the version in the initial comment of this PR? to `1.4.0`?)

**Comment by brainstorm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00616/joss.00616/10.21105.joss.00616.pdf)

**Comment by brainstorm** [comment]
Obrigado @luizirber and thanks @greatfireball and @DanielAmsel!

@whedon set 10.5281/zenodo.1188480 as archive

**Comment by brainstorm** [comment]
@whedon set 10.5281/zenodo.1188480 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1188480" target="_blank">10.5281/zenodo.1188480</a> is the archive.

**Comment by greatfireball** [comment]
Good morning! Thanks @luizirber and @brainstorm.

If possible, I would like to release and use the version v1.5.0, due to we further optimized our code. I will generate a new release later this morning, create a new zenodo archive, and post a link and the DOI here.

Thanks!

**Comment by brainstorm** [comment]
Good afternoon from Melbourne!

Thanks @greatfireball, apparently the Zenodo DOI is stable across versions and points to the latest version:

```
Cite all versions? You can cite all versions by using the DOI 10.5281/zenodo.1188480. This DOI represents all versions, and will always resolve to the latest one.
```

As I just read here: http://help.zenodo.org/#versioning

@arfon, does whedon announce the release of the paper upon closing this issue I assume, or is there any additional step to follow?

Thanks everyone again!

**Comment by greatfireball** [comment]
@brainstorm of course you are right... You set the stabil DOI. I thought you would like to use a DOI pointing to the version indicated by the version above. Do you increase the version number to v1.5.0 before closing the issue?

**Comment by greatfireball** [comment]
I just released the version [v1.5.0](https://github.com/microPIECE-team/microPIECE/releases/tag/v1.5.0). The DOI for that version is [10.5281/zenodo.1215850](https://doi.org/10.5281/zenodo.1215850) but if you are fine with the DOI for all versions, we are fine as well. Finally, we will run the pipeline once more and update the numbers within the manuscript. Afterwards, we are ready to go. Thanks!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1215850  as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1215850" target="_blank">10.5281/zenodo.1215850</a> is the archive.

**Comment by arfon** [comment]
> @arfon, does whedon announce the release of the paper upon closing this issue I assume, or is there any additional step to follow?

@brainstorm - I have to do a couple of things in the background. I can take it from here...

**Comment by arfon** [comment]
@luizirber - many thanks for your review here and to @brainstorm for editing this submission ✨ 

@greatfireball - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00616 ⚡️:rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00616/status.svg)](https://doi.org/10.21105/joss.00616)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00616/status.svg)](https://doi.org/10.21105/joss.00616)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by greatfireball** [comment]
Thank you for finalizing the paper and thanks for acception @arfon! Nevertheless, as I stated above, we are currently rerunning the pipeline with version v1.5.0 and might need to change a number inside the manuscript. Is it still possible or to late? Thanks in advance!

**Comment by arfon** [comment]
> Thank you for finalizing the paper and thanks for acception @arfon! Nevertheless, as I stated above, we are currently rerunning the pipeline with version v1.5.0 and might need to change a number inside the manuscript. Is it still possible or to late? Thanks in advance!

Sure thing. I can update the paper whenever you're ready.

**Comment by greatfireball** [comment]
Good morning @arfon,

finally we finished the rerun and updated the numbers. Unfortunately, I forgot to merge an important pull request which dramatically reduced the runtime of a single step. Therefore, I had to create another release [v1.5.2](https://github.com/microPIECE-team/microPIECE/releases/tag/v1.5.2) and a zenodo upload [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1218731.svg)](https://doi.org/10.5281/zenodo.1218731).
If you are able to update the DOI again, I would suggest to set it to the new one: [10.5281/zenodo.1218731](https://doi.org/10.5281/zenodo.1218731) and update the version of the pipeline to v1.5.2. The manuscript is up to date now, and we also included the ORCID for André.

Thanks again to @brainstorm, @luizirber, and @arfon !

Best,
Frank

**Comment by arfon** [comment]
@greatfireball - OK thanks for the update. This should be updated now.
