### ISSUE TITLE
[PRE REVIEW]: mmappickle: A Python 3 library to store memory mappable objects into pickle-compatible files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#618]
**Submitting author:** @lfasnacht (<a href="http://orcid.org/0000-0002-9853-8209">Laurent Fasnacht</a>)
**Repository:** <a href="https://github.com/UniNE-CHYN/mmappickle" target ="_blank">https://github.com/UniNE-CHYN/mmappickle</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @glemaitre, @clemaitre58

**Author instructions**

Thanks for submitting your paper to JOSS @lfasnacht. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lfasnacht if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00618/joss.00618/10.21105.joss.00618.pdf)

**Comment by lfasnacht** [comment]
There seem to be an issue with the bullet list in the article proof, does somebody know how can I fix that?

**Comment by arfon** [comment]
@lfasnacht - this should fix it: https://github.com/UniNE-CHYN/mmappickle/pull/2

The Pandoc converter is a little more fussy than GitHub about markdown structure.

**Comment by lfasnacht** [comment]
Merged, thank you very much!

**Comment by lfasnacht** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00618/joss.00618/10.21105.joss.00618.pdf)

**Comment by arfon** [comment]
@stensy, @clemaitre58, @glemaitre - would you be willing to review this submission for JOSS? I'd like to find a couple of reviewers for this submission.

**Comment by glemaitre** [comment]
I can be one of the reviewer.

**Comment by clemaitre58** [comment]
@arfon I could also one of them

**Comment by arfon** [comment]
@whedon assign @glemaitre as reviewer

**Comment by arfon** [comment]
@whedon add @clemaitre58 as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @glemaitre as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @glemaitre

**Comment by arfon** [comment]
@whedon add @clemaitre58 as reviewer

**Comment by whedon** [comment]
OK, @clemaitre58 is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/651. Feel free to close this issue now!

**Comment by arfon** [comment]
@glemaitre, @clemaitre58 - thanks for agreeing to review this. Please head over to #651 for the actual review.
