### ISSUE TITLE
[PRE REVIEW]: nardl:An R package to estimate the nonlinear cointegrating autoregressive distributed lag model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#619]
**Submitting author:** @zedtaha (<a href="http://orcid.org/0000-0002-4488-5774">zaghdoudi Taha</a>)
**Repository:** <a href="https://github.com/zedtaha/nardl" target ="_blank">https://github.com/zedtaha/nardl</a>
**Version:** 0.1.3
**Editor:** @leeper
**Reviewer:** @JoFAM

**Author instructions**

Thanks for submitting your paper to JOSS @zedtaha. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zedtaha if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00619/joss.00619/10.21105.joss.00619.pdf)

**Comment by zedtaha** [comment]
@leeper as reviewer

**Comment by leeper** [comment]
@whedon list commands

**Comment by leeper** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@zedtaha Would you be interested in reviewing this package for JOSS?

**Comment by zedtaha** [comment]
Hi @leeper do you mean nardl r package ? if yes I'm the developer!

**Comment by leeper** [comment]
@zedtaha Haha! I didn't look at the maintainer - I figured it would be of interest and of course it is because it's your package! Sorry about that.

**Comment by zedtaha** [comment]
@leeper no prob ;) best

**Comment by leeper** [comment]
@whedon assign @JoFAM as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @JoFAM

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/623. Feel free to close this issue now!
