### ISSUE TITLE
[PRE REVIEW]: comorbidity: An R package for computing comorbidity scores

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#620]
**Submitting author:** @ellessenne (<a href="http://orcid.org/0000-0002-8319-7624">Alessandro Gasparini</a>)
**Repository:** <a href="https://github.com/ellessenne/comorbidity" target ="_blank">https://github.com/ellessenne/comorbidity</a>
**Version:** 0.1.0
**Editor:** @leeper
**Reviewers:** @corinne-riddell

**Author instructions**

Thanks for submitting your paper to JOSS @ellessenne. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ellessenne if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00620/joss.00620/10.21105.joss.00620.pdf)

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@ellessenne Thanks for your submission to JOSS! Do you have anyone you'd like to recommend as a possible reviewer of the package?

**Comment by pragyansmita** [comment]
@leeper @ellessenne I am not as familiar with comorbidity codes. I can review w.r.t. the R package.

**Comment by ellessenne** [comment]
Thank you @leeper!
I would be glad if @pragyansmita could review the R package part. 
Also, may I suggest @maelle? If I am correct she has experience with both R packages and epidemiology. @maelle, I would really appreciate it.
Thanks!

**Comment by maelle** [comment]
Thanks for thinking of me! Sorry I have no time in the short term but maybe ask @Paula-Moraga or @brooke-watson?

**Comment by ellessenne** [comment]
Thanks for the feedback and suggestions @maelle! I'd be happy if @Paula-Moraga or @brooke-watson want to get involved!

**Comment by leeper** [comment]
Hi @Paula-Moraga and @brooke-warson, would either of you be interested in reviewing this for JOSS?

**Comment by brooke-watson** [comment]
@maelle , thanks for thinking of me! I've never used Charlson or Elixhauser scores, so I don't think I'm the best fit given the time investment it would require. This looks like it will be a helpful package, though, @ellessenne - all the best!

**Comment by leeper** [comment]
@brooke-watson No problem. Thanks!

**Comment by Paula-Moraga** [comment]
@leeper Same here. I have never used comorbidity scores. Sorry and thanks for thinking of me.

**Comment by leeper** [comment]
@Paula-Moraga Cheers for the reply. No problem!

**Comment by leeper** [comment]
@whedon assign @corinne-riddell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @corinne-riddell

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/648. Feel free to close this issue now!
