### ISSUE TITLE
[PRE REVIEW]: hydroscoper: R interface to the Greek National Data Bank for Hydrological and Meteorological Information

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#621]
**Submitting author:** @kvantas (<a href="http://orcid.org/0000-0001-6387-8791">Konstantinos Vantas</a>)
**Repository:** <a href="https://github.com/ropensci/hydroscoper" target ="_blank">https://github.com/ropensci/hydroscoper</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @kvantas. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kvantas if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00621/joss.00621/10.21105.joss.00621.pdf)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/625. Feel free to close this issue now!
