### ISSUE TITLE
[REVIEW]: nardl:An R package to estimate the nonlinear cointegrating autoregressive distributed lag model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#623]
**Submitting author:** @zedtaha (<a href="http://orcid.org/0000-0002-4488-5774">zaghdoudi Taha</a>)
**Repository:** <a href="https://github.com/zedtaha/nardl" target ="_blank">https://github.com/zedtaha/nardl</a>
**Version:** 0.1.3
**Editor:** @leeper
**Reviewer:** @JoFAM
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/fe9bdfe31cef65860883d6c7f8c0ced6/status.svg)](http://joss.theoj.org/papers/fe9bdfe31cef65860883d6c7f8c0ced6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fe9bdfe31cef65860883d6c7f8c0ced6"><img src="http://joss.theoj.org/papers/fe9bdfe31cef65860883d6c7f8c0ced6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fe9bdfe31cef65860883d6c7f8c0ced6/status.svg)](http://joss.theoj.org/papers/fe9bdfe31cef65860883d6c7f8c0ced6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/zedtaha/nardl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@JoFAM, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zedtaha/nardl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.3)?
- [x] **Authorship:** Has the submitting author (@zedtaha) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @JoFAM it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00623/joss.00623/10.21105.joss.00623.pdf)

**Comment by JoFAM** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by JoFAM** [comment]
The package provides new functionality for R: nonlinear ARDL models currently have to be built manually or calculated using other software. 

## Current issues that warrant "major revision":

- There is no guidelines for bug reports or contributions : https://github.com/zedtaha/nardl/issues/12
- There is no testing done, results are impossible to check: https://github.com/zedtaha/nardl/issues/5
- help files for the few exported functions don't contain return values etc. : https://github.com/zedtaha/nardl/issues/8

## General remarks

In general the code is very ad-hoc and doesn't allow to easily extract test results for the different tests provided. None of the test functions are exported, so they can't be called directly. There's no real API to work with the S3 model object returned by nardl(). There's also no documentation as to what can be found in that object.

In order to be useful in a real world analysis, the API needs to be extended so one can at least work with the returned objects. In order to be maintainable, the code needs serious refactoring so it is more modularized. 

@leeper : this is my assessment of the package nardl at its current state.

**Comment by leeper** [comment]
@JoFAM Thank you very much for your review! This is very useful feedback. Much appreciated.

@zedtaha I think the review does a very good job of identifying weaknesses in the structure of the code that you could address, particularly with regarding to making a fully featured API. Please take a look at the open issues and, especially, address https://github.com/zedtaha/nardl/issues/5. Thanks!

**Comment by JoFAM** [comment]
@zedtaha If you want, I can create a pull request from my fork, so you have already some of the issues (partly) taken care of. Also if you want further assistance with these and other issues, feel free to ping me. I'll be glad to help you clean up your already very valuable work.

**Comment by zedtaha** [comment]
@JoFAM ohh yes its a very good suggestion and I'm already OK and I found your comments very helpful.

**Comment by JoFAM** [comment]
@zedtaha Super. Do I create a pull request directly on your master branch, or do you want to create a devel branch first?

**Comment by zedtaha** [comment]
@JoFAM just make a pull and it will be OK

**Comment by zedtaha** [comment]
Hi @JoFAM i made some changes in the nardl package  and i invite you to take a look

**Comment by zedtaha** [comment]
@JoFAM hope that the changes meet up all the issues ;)

**Comment by leeper** [comment]
Great, thanks @zedtaha!

**Comment by zedtaha** [comment]
Hi @JoFAM any things new?

**Comment by JoFAM** [comment]
@zedtaha sorry, I had a few family issues to take care of and didn't get to this yet. Thank you for reminding me, I am going to go through it again somewhere this week. Prob Thursday or Friday.

**Comment by zedtaha** [comment]
Hi @JoFAM any new!?

**Comment by leeper** [comment]
Hi @JoFAM, just a quick nudge.

**Comment by JoFAM** [comment]
@zedtaha I have another pull request that tackles a number of the issues from the previous review round:

https://github.com/zedtaha/nardl/pull/17

## General remarks:

The package improved in this round, but still doesn't provide basic functionality one would expect. At least one should be able to extract coefficients and other important model statistics from a model object. They might need these to plot, to construct their own tests, to do simulation  studies, ... 

The documentation of the returned objects can be more helpful. Eg, it took me quite a while to realize 'np' is actually the number of lags, what 'sel' and 'fit' are and so forth. 

There is much improvement possible in the unit testing. Currently the code coverage as reported by the `covr` package is about 14%. Even when the plot functions are ignored, there's not a single test for the pssbounds function or the summary.nardl function. 

## Points on which improvement is necessary

For me, the minimal requirements to give this package a pass, are the following : 

- Make sure pssbounds actually outputs something. Now the usefulness of this function is very limited: there's no easy way the results of that function can be captured and used in other code.
- Add a few more unit tests for the important functions of the package. A code coverage of 13% is very low. Especially the pssbounds function with its 1700 lines really needs some testing.
- Solve the failing unit test ( issue https://github.com/zedtaha/nardl/issues/15 ). That is actually a placeholder and example I added in the previous PR to get you started. 
- the output of the function nardl needs describing ( issue https://github.com/zedtaha/nardl/issues/8 )
- You really need to give at least some indication of the source of the data ( issue https://github.com/zedtaha/nardl/issues/3 )

@leeper : This is my assesment of the package nardl at its current state.

**Comment by JoFAM** [comment]
@zedtaha PS: if you need extra explanation or more help with how to remediate my comments, don't hesitate to ask.

**Comment by leeper** [comment]
@JoFAM Thanks! This looks great. Really, really helpful review.

@zedtaha Can you incorporate the PR and try to address the remaining issues? Given the scale of @JoFAM's contribution via the PR, you may also want to list him in DESCRIPTION as a contributor.

**Comment by leeper** [comment]
@zedtaha Just wanted to check in. Are you still planning to make revisions for this?

**Comment by leeper** [comment]
@zedtaha Just another nudge to complete the requested revisions.

**Comment by arfon** [comment]
@zedtaha  - friendly reminder to get to these revisions sometime soon please.

**Comment by zedtaha** [comment]
@leeper I apologize for the delay I was on a working trip. However, there is so many issues to do so I think its correct to withdrew the paper. Best

**Comment by zedtaha** [comment]
@leeper I'm also open to more suggestion.

**Comment by JoFAM** [comment]
@zedtaha Sad to see this disappear after all the work you've put in. If you need help later on when you want to update the package, feel free to tag me again.

Cheers
Joris

**Comment by arfon** [comment]
> @leeper I apologize for the delay I was on a working trip. However, there is so many issues to do so I think its correct to withdrew the paper. Best

Hi @zedtaha. Please feel free to resubmit this sometime again in the future if you're able to make the changes requested here by our reviewers.

@JoFAM @leeper, many thanks for all of your help here.

**Comment by faheemja** [comment]
i have a times series data matrix i want to fit functional autoregessive model of order one and two in R..how i can do do this in R???

**Comment by danielskatz** [comment]
@faheemja - this thread is was a review for a paper for the Journal of Open Source software, and is closed.

The repository for the software that was being reviewed, where you might want to ask your question, is https://github.com/zedtaha/nardl
