### ISSUE TITLE
[PRE REVIEW]: EmissV: An R package to create vehicular and other emissions by Top-down methods to air quality models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#627]
**Submitting author:** @Schuch666 (<a href="http://orcid.org/0000-0001-5977-4519">Daniel Schuch</a>)
**Repository:** <a href="https://github.com/atmoschem/EmissV" target ="_blank">https://github.com/atmoschem/EmissV</a>
**Version:** 0.664.3
**Editor:** @arfon
**Reviewers:** @nuest

**Author instructions**

Thanks for submitting your paper to JOSS @Schuch666. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Schuch666 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00627/joss.00627/10.21105.joss.00627.pdf)

**Comment by Schuch666** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by Schuch666** [comment]
@whedon set 10.5281/zenodo.1208113 as archive

**Comment by whedon** [comment]
I'm sorry @Schuch666, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by Schuch666** [comment]
Hi @arfon , is it possible to suggest you as editor?

**Comment by arfon** [comment]
@Schuch666 - could you take a look at the reviewer list (https://bit.ly/joss-reviewers) and see if you could suggest a few potential reviewers?

**Comment by arfon** [comment]
> Hi @arfon , is it possible to suggest you as editor?

:-) Sure thing. I'd like to find a couple of reviewers first.

**Comment by Schuch666** [comment]
thank you @arfon

**Comment by Schuch666** [comment]
May I suggest @benmarwick and/or @nuest for reviewers? I read their profiles and I believe they have a good background for reviewing. Thanks again.

**Comment by arfon** [comment]
@benmarwick @nuest would you be willing to review this submission for JOSS?

**Comment by nuest** [comment]
Yes.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @nuest as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nuest

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/662. Feel free to close this issue now!

**Comment by arfon** [comment]
@nuest - please head over to #662 to carry out the actual review.

**Comment by benmarwick** [comment]
oops, sorry to be slow, I can review also.

**Comment by arfon** [comment]
> oops, sorry to be slow, I can review also.

Great, thanks @benmarwick - that would be excellent. I'll update the review issue over in #662.
