### ISSUE TITLE
[PRE REVIEW]: Mapelia and friends: create 3D models from maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#628]
**Submitting author:** @jordibc (<a href="http://orcid.org/0000-0002-9198-5380">Jordi Burguet-Castell</a>)
**Repository:** <a href="https://github.com/jordibc/mapelia" target ="_blank">https://github.com/jordibc/mapelia</a>
**Version:** 1.1.1
**Editor:** @arfon
**Reviewers:** @hugoledoux, @ThomasA

**Author instructions**

Thanks for submitting your paper to JOSS @jordibc. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jordibc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00628/joss.00628/10.21105.joss.00628.pdf)

**Comment by arfon** [comment]
:wave: @acabunoc - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
:wave: @jordibc - would you be able to take a look at the JOSS reviewers and suggest a few people who might be able to review this submission? http://bit.ly/joss-reviewers

**Comment by jordibc** [comment]
Hi @arfon , sure, these are my suggestions, in order of what I think may work best:
hugoledoux
pragyansmita
tacaswell
khinsen
ThomasA
sealhuang

**Comment by arfon** [comment]
@hugoledoux @ThomasA @sealhuang - would you be willing to review this submission for JOSS?

**Comment by hugoledoux** [comment]
@arfon sure

**Comment by ThomasA** [comment]
@arfon yes, I can review this.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @hugoledoux as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hugoledoux

**Comment by arfon** [comment]
@whedon add @ThomasA as reviewer

**Comment by whedon** [comment]
OK, @ThomasA is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/660. Feel free to close this issue now!

**Comment by arfon** [comment]
@hugoledoux, @ThomasA - many thanks for agreeing to review this submission. Please head over to #660 to carry out the review.
