### ISSUE TITLE
[REVIEW]: rintrojs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#63]
**Submitting author:** @carlganz (<a href="http://orcid.org/0000-0002-2973-3545">Carl Ganz</a>)
**Repository:** <a href="https://github.com/carlganz/rintrojs" target ="_blank">https://github.com/carlganz/rintrojs</a>
**Version:** v0.1.1
**Editor:** @arfon 
**Reviewer:** @brylie
**Archive:** <a href="https://dx.doi.org/10.5281/zenodo.160211" target ="_blank">https://dx.doi.org/10.5281/zenodo.160211</a>

## Status

[![status](http://joss.theoj.org/papers/45f5dd9b6d519961821eab43762a9c22/status.svg)](http://joss.theoj.org/papers/45f5dd9b6d519961821eab43762a9c22)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/45f5dd9b6d519961821eab43762a9c22"><img src="http://joss.theoj.org/papers/45f5dd9b6d519961821eab43762a9c22/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/45f5dd9b6d519961821eab43762a9c22/status.svg)](http://joss.theoj.org/papers/45f5dd9b6d519961821eab43762a9c22)
```
**Reviewers and authors**: 

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/carlganz/rintrojs" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/carlganz/rintrojs">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00063.pdf](https://github.com/openjournals/joss-reviews/files/477553/10.21105.joss.00063.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by brylie** [comment]
I can review it.

**Comment by brylie** [comment]
Could not locate LICENSE.txt, or equivalent (for wrapper project):

- https://github.com/carlganz/rintrojs/issues/8

**Comment by brylie** [comment]
Could not locate a Github release for 0.1.0, or any release at all:

- https://github.com/carlganz/rintrojs/issues/9
- https://github.com/carlganz/rintrojs/releases

**Comment by brylie** [comment]
Contributing guidelines were a bit 'thin':

- https://github.com/carlganz/rintrojs/issues/10

**Comment by brylie** [comment]
There are no 'performance claims' made by this software, so leaving 'performance' checkbox unchecked.

**Comment by brylie** [comment]
The **Statement of Need** for the project could be improved:

- https://github.com/carlganz/rintrojs/issues/11

In effect, the statement of need is provided in the second paragraph of the published PDF. However, the statement of need is brief, and not clearly distinguished from other content.

**Comment by brylie** [comment]
**DOI References**: the paper contains two citations, neither of which has a DOI number. I am not sure how to determine whether a reference *should* have a DOI number. Assistance needed.

**Comment by danielskatz** [comment]
If there are no performance claims, you can check the performance claims box, since the answer is more or less yes.

For the papers, you should be able to look them up in google or google scholar or other means, go to the place they are published or archived, and see if they do or do not have DOIs.

**Comment by danielskatz** [comment]
FYI, please don't change the labels.  pending-minor-enhancements means the paper has not yet started being reviewed, while review means it has.  It can remain in review for a time while the authors deal with the issues raised by reviewers.

**Comment by brylie** [comment]
> For the papers, you should be able to look them up in google or google scholar or other means, go to the place they are published or archived, and see if they do or do not have DOIs.

The citations were both links to the software websites.

**Comment by danielskatz** [comment]
Then there are no DOIs for those products, and you can check the review box that this is ok.

**Comment by brylie** [comment]
A Github release was just made:

https://github.com/carlganz/rintrojs/releases

**Comment by brylie** [comment]
The project license was updated:

https://github.com/carlganz/rintrojs/commit/ae3137d2168fa8937dae1c2fb708895ce566338e

**Comment by brylie** [comment]
Contribution guidelines and code of conduct were just added:

https://github.com/carlganz/rintrojs/commit/7d6bf2d662a16325618910506ff669281ce10d98

**Comment by brylie** [comment]
Statement of Need was added:

https://github.com/carlganz/rintrojs/commit/d3ef95ad448bac7d63f74899fff6269c93484186

**Comment by carlganz** [comment]
Thanks for the feedback. Let me know if there is anything else you need me to do.

**Comment by arfon** [comment]
@brylie - how are we doing here? Is this submission in a good state to accept now?

**Comment by brylie** [comment]
@arfon I thought I was no longer assigned to the review, since my name was removed from the 'Assignees' field. Also, I can no longer edit the checkboxes in the task description.

What should I do to continue/finish this review?

**Comment by arfon** [comment]
@whedon assign @brylie as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brylie

**Comment by arfon** [comment]
@brylie - my apologies. This review got caught up in some reworking of how reviews work. We'd love for you to finish up this review if you're willing. You should be able to update the checklist again now.

**Comment by brylie** [comment]
@arfon thanks. I will continue today.

**Comment by brylie** [comment]
@arfon the review is complete, and all boxes are checked. I requested that the upstream author make one more release, to include changes from the review process:

https://github.com/carlganz/rintrojs/issues/14

**Comment by arfon** [comment]
> @arfon the review is complete, and all boxes are checked. I requested that the upstream author make one more release, to include changes from the review process:

👍 excellent thanks.

@carlganz. Once you've addressed https://github.com/carlganz/rintrojs/issues/14 could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by carlganz** [comment]
Thanks @brylie and @arfon!

Here is the release that should close carlganz/rintrojs#14: https://github.com/carlganz/rintrojs/releases/tag/0.1.1

And here is the archive on Zenodo: https://zenodo.org/record/160211#.V_1As4QrLcs

**Comment by arfon** [comment]
Thanks for the review @brylie.

@carlganz - your paper is now accepted into JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00063 🚀 🎉 💥
