### ISSUE TITLE
[PRE REVIEW]: MLxtend: Providing machine learning and data science utilities and extensions to Python's scientific computing stack

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#631]
**Submitting author:** @rasbt (<a href="http://orcid.org/0000-0001-6989-4493">Sebastian Raschka</a>)
**Repository:** <a href="https://github.com/rasbt/mlxtend" target ="_blank">https://github.com/rasbt/mlxtend</a>
**Version:** v0.11.0
**Editor:** @arokem
**Reviewer:** @mlgill

**Author instructions**

Thanks for submitting your paper to JOSS @rasbt. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rasbt if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #631 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
👋 @arokem - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #631 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/631/paper.md): did not find expected key while parsing a block mapping at line 5 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:65:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by rasbt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #631 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/631/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:65:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by rasbt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00631/joss.00631/10.21105.joss.00631.pdf)

**Comment by rasbt** [comment]
@arfon It seems to be fixed now. It was due to a stupid mistake: I enclosed the title in single quotes and had an apostrophe (Python's) in the title.

**Comment by rasbt** [comment]
Thanks for volunteering as the editor, @arokem !

> Any particular suggestions for reviewers?

@mlgill , @rhiever , @chrisalbon come to mind, who are data science and python experts as well as big open source contributors (and may have not used the library, yet, to be unbiased when it comes to reviewing it in terms of e.g., the installation and documentation requirements via JOSS)

**Comment by mlgill** [comment]
@rasbt I am potentially interested. Could you let me know what's expected and approximate timeline? I have a hectic next two weeks due to work obligations, but it will improve after that. Thanks!

**Comment by rasbt** [comment]
Thanks @mlgill , and no worries about the time line! I think there's no official time constraint like the 30 days for other academic, reviews, but something in that ballpark would be good. Also, JOSS reviews as involved as reviews for other academic journals, because the papers are basically just a summary of the software package in 250-500 words. Mainly, the reviews is to check whether the submissions adheres to open source practices. If you should accept to review, the editor will post a checklist with instructions, e.g., similar to the one here: https://github.com/openjournals/joss-reviews/issues/634

The complete instructions are available here: https://joss.theoj.org/about#reviewer_guidelines (under the Reviewer Guidelines section).

**Comment by arokem** [comment]
@mlgill : not much left for me to explain: What @rasbt said pretty much sums it up. 

No worries about the time-frame: if you think you might be able to do this in 3-4 weeks, that should be fine. Just let me know if you can take this on, and I will set up the review issue, with the check-list for you to use as a guide. 

Thanks!

**Comment by mlgill** [comment]
@arokem @rasbt I think this is doable -- I might get some time next week to get started, but either way will work on it in April and I think I can complete in 4 weeks. Just let me know when the checklist is ready!

**Comment by rasbt** [comment]
Nice, thanks @mlgill ! And no pressure! :)

**Comment by arokem** [comment]
@whedon set @mlgill as reviewer

**Comment by arokem** [comment]
@whedon assign @mlgill as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mlgill

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/638. Feel free to close this issue now!

**Comment by arokem** [comment]
OK @mlgill : head over to #638 for the review. I am closing this one now.

**Comment by rhiever** [comment]
I can help with this starting next week sometime.
