### ISSUE TITLE
[PRE REVIEW]: `ijtiff`: An R package providing TIFF I/O for _ImageJ_ users

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#632]
**Submitting author:** @rorynolan (<a href="http://orcid.org/0000-0002-5239-4043">Rory Nolan</a>)
**Repository:** <a href="https://github.com/ropensci/ijtiff" target ="_blank">https://github.com/ropensci/ijtiff</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @rorynolan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rorynolan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00632/joss.00632/10.21105.joss.00632.pdf)

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/633. Feel free to close this issue now!
