### ISSUE TITLE
[REVIEW]: genieR: An R package for inference of demographic history of phylogenies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#634]
**Submitting author:** @xiangfstats (<a href="http://orcid.org/0000-0003-3644-7114">Fei Xiang</a>)
**Repository:** <a href="https://github.com/xiangfstats/GenieR" target ="_blank">https://github.com/xiangfstats/GenieR</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @pboesu
**Archive:** <a href="https://doi.org/10.5281/zenodo.2532305" target="_blank">10.5281/zenodo.2532305</a>

## Status

[![status](http://joss.theoj.org/papers/a0b1e6b2abfc2abade8cf11043be7bc6/status.svg)](http://joss.theoj.org/papers/a0b1e6b2abfc2abade8cf11043be7bc6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a0b1e6b2abfc2abade8cf11043be7bc6"><img src="http://joss.theoj.org/papers/a0b1e6b2abfc2abade8cf11043be7bc6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a0b1e6b2abfc2abade8cf11043be7bc6/status.svg)](http://joss.theoj.org/papers/a0b1e6b2abfc2abade8cf11043be7bc6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/xiangfstats/GenieR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pboesu, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @biorelated know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xiangfstats/GenieR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
  ⚠️ **TODO:** No github release exists. DESCRIPTION file lists version as 0.1.0. Please harmonize version numbering and create github release.
- [x] **Authorship:** Has the submitting author (@xiangfstats) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
Installation works as described on the reviewers machine (Windows 10, R 3.4.2, Rtools 3.5)
⚠️ **Suggestion:** It might be worth pointing out (for the benefit of Windows users - not sure what the target audience is likely using) that a C++ compiler / Rtools installation is necessary. See PR.
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
⚠️ **Suggestion:** Automated tests are provided covering input checking. All of these appear to be 'negative tests' i.e. based on `expect_error()`. I'd suggest that the authors also implement tests that check the code provides correct output when provided with correct inputs.
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @pboesu it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00634/joss.00634/10.21105.joss.00634.pdf)

**Comment by biorelated** [comment]
@pboesu how are you getting on with the review process? Kindly let me know if you need some assistance or if you have any concerns. Thank you.

**Comment by pboesu** [comment]
@biorelated Apologies for being dreadfully slow on the review. I have started it finally, and I hope to finish it by next weekend.

**Comment by pboesu** [comment]
Hello @biorelated and @xiangfstats

I have reviewed the package now and provided a number of issues in the target repositories that, in my opinion, warrant responses from the authors.

Critically, the vignette does not compile because of an error in one of the package functions (https://github.com/xiangfstats/GenieR/issues/2), but I would also suggest a number of fairly minor changes to the documentation, API, and testing suite that should greatly improve the re-use potential of the package.

**Comment by biorelated** [comment]
Thank you very much @pboesu  for the review. 
 @xiangfstats kindly respond to the raised issues.

**Comment by xiangfstats** [comment]
Dear @george-githinji 
I have made improvements based on @pboesu 's suggestions and replied separately to those 7 comments.
Thanks very much for the review from @pboesu .
Best
Fei

**Comment by arfon** [comment]
:wave: @pboesu - could you take a look at the feedback from @xiangfstats.

**Comment by george-githinji** [comment]
Dear @pboesu Please review the improvements made by @xiangfstats. Kindly let me know if you need some assistance or if you are not in a position to. Thank you.

**Comment by arfon** [comment]
Hi @george-githinji - what's the status of this submission?

**Comment by george-githinji** [comment]
@arfon I will seek for a new reviewer for this work. @pboesu has not responded to our requests.

**Comment by george-githinji** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by xiangfstats** [comment]
Dear @pjotrp , 
I can confirm that all references have a DOI except two without DOIs. I created a Github release and deposit that release with Zenodo. The DOI is  DOI: 10.5281/zenodo.2532305. Many thanks
Best
Fei

**Comment by pjotrp** [comment]
Oh, it did work. Needed to think about it, I guess ;)

**Comment by pjotrp** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/423

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/423, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by pjotrp** [comment]
@arfon I guess I should leave this step to you!

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/424
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00634](https://doi.org/10.21105/joss.00634)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@pboesu - many thanks for your review and to @pjotrp and @george-githinji for editing this submission ✨ 

@xiangfstats - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00634/status.svg)](https://doi.org/10.21105/joss.00634)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00634">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00634/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00634/status.svg
   :target: https://doi.org/10.21105/joss.00634
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00634/status.svg)](https://doi.org/10.21105/joss.00634)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by xiangfstats** [comment]
Thanks very much to everyone, @arfon, @pboesu, @pjotrp and @george-githinji. Great to know our paper is accepted in JOSS.

**Comment by ajstewartlang** [comment]
:wave: @xiangfstats I am handling a new JOSS submission that seems to overlap nicely with your expertise. Might you have the bandwidth to review it please? It would be very much appreciated. The submission can be found here: https://github.com/marccanby/linguiphyr/
