### ISSUE TITLE
[PRE REVIEW]: Aquatracker: Data Visualization and Analysis for Acoustic Telemetry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#635]
**Submitting author:** @reefpicker (<a href="http://orcid.org/0000-0002-2155-3339">Jose</a>)
**Repository:** <a href="https://github.com/reefpicker/AquaTracker" target ="_blank">https://github.com/reefpicker/AquaTracker</a>
**Version:** 2.41
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @reefpicker. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@reefpicker if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #635 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
👋@reefpicker - please take another look at our [submission requirements](http://joss.theoj.org/about#submission_requirements). This repository appears to be missing:

- A license
- Files named `paper.md` and `paper.bib`
- A README in the repository.

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by karthik** [comment]
@arfon Thanks, on it.

**Comment by karthik** [comment]
@AquaTracker Thanks for the submission. Your software has no README file describing what the software does, how one might use it, or anything other information about installation requirements. There is a `paper.bib.txt` but no paper.   Hidden inside `https://raw.githubusercontent.com/reefpicker/AquaTracker/master/summary.txt` is a note that this is Visual Basic software. I don't use it myself, so can you suggest reviewers who are able to judge your work?

**Comment by reefpicker** [comment]
Karthik,

Sorry, I have been a bit busy with work. Yes, I understand what it is
missing and was planning out on adding the readme.

I believe anyone with C# or .NET skills could review the software source
code. The software itself is available for download as an exe file at the
NOAA website also so if you don't have the VB IDE/compiler, you could in
theory review the materials submitted. It is very likely that folks who
list having .NET and C# knowledge also have VB6 sitting around somewhere.

There is a spreadsheet I got from whedon (I think it was bot generated). I
can pick names from there and submit them to you. How many should I select?

Thanks

**Comment by karthik** [comment]
Hi @reefpicker 
Yes please suggest two to three names from that list and we can go from there.

**Comment by karthik** [comment]
@reefpicker A quick reminder for reviewer names.

**Comment by reefpicker** [comment]
@karthik <https://github.com/karthik>

Reviewers email addresses from that list:

claudio.benghi@northmbria.ac.uk
michael@scivision.co

Thanks!

**Comment by karthik** [comment]
@reefpicker I realize this submission is out of scope for me to serve as an editor. I'm not familiar with evaluating Visual Basic code or finding appropriate editors for it. So I'm going to excuse myself as an editor for this one and hand it back to @arfon

**Comment by arfon** [comment]
@CBenghi @Scivision - would you be willing to review this submission for JOSS?

**Comment by CBenghi** [comment]
Hello @arfon,
I'll have a chat with the author to see what are the technical requirements. 
I don't think I have the tool-set at the moment, but if i can get it, I will happily review.

**Comment by reefpicker** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by reefpicker** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
> I don't think I have the tool-set at the moment, but if i can get it, I will happily review.

@CBenghi - I think we'd like to take you up on this offer if you're still willing?

@reefpicker - are there any other potential reviewers in the list above or people you'd recommend elsewhere on GitHub?

**Comment by CBenghi** [comment]
@arfon there's been a bit of back an forth with @reefpicker on a
There was code missing in repository that prevented me from trying to convert/open in my development environment. This has been addressed a few days ago, but I've not been able to look into the updated version yet.
I should be able to determine in a couple of days.

**Comment by arfon** [comment]
> I should be able to determine in a couple of days.

OK thanks @CBenghi - please let me know here if you think you're able to review this.

**Comment by CBenghi** [comment]
@arfon, 
more files missing from the initial repository. 

I doubt you'll find something else using vb6 in the editor's list. It's a 15 years old technology now discontinued by Microsoft.  My plan is to try and get the code to working in a current development environment before review.

I'll keep working @reefpicker and keep you informed if/when we manage.

**Comment by reefpicker** [comment]
I will like to officially retract this submission.

Thanks!

**Comment by arfon** [comment]
OK thanks for letting us know @reefpicker!
