### ISSUE TITLE
[PRE REVIEW]: Matrix Studio: An OpenCL Integrated Development Environment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#637]
**Submitting author:** @pascal-ballet (<a href="http://orcid.org/0000-0002-2429-9532">Pascal Ballet</a>)
**Repository:** <a href="https://github.com/pascal-ballet/matrixstudio" target ="_blank">https://github.com/pascal-ballet/matrixstudio</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @pascal-ballet. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pascal-ballet if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #637 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
👋 @labarba - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00637/joss.00637/10.21105.joss.00637.pdf)

**Comment by labarba** [comment]
Hi  @pascal-ballet — Thank you for your submission, but we find that it is out of scope for JOSS. 

As we detail in the [Author Guidelines](http://joss.theoj.org/about#author_guidelines):

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

Your software does not seem to fall into any of these descriptions. If there is a research application that we are missing, you would have to clearly expand on this in the paper.

As it is now, the submission was designated as out-of-scope by a trio of editors—which is how we sanction desk rejections.

**Comment by pascal-ballet** [comment]
I thank you for your time and your review. Our software is effectively out of scope.
All the best.
