### ISSUE TITLE
[REVIEW]: MLxtend: Providing machine learning and data science utilities and extensions to Python's scientific computing stack

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#638]
**Submitting author:** @rasbt (<a href="http://orcid.org/0000-0001-6989-4493">Sebastian Raschka</a>)
**Repository:** <a href="https://github.com/rasbt/mlxtend" target ="_blank">https://github.com/rasbt/mlxtend</a>
**Version:** v0.11.0
**Editor:** @arokem
**Reviewer:** @mlgill
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1226560" target="_blank">10.5281/zenodo.1226560</a>

## Status

[![status](http://joss.theoj.org/papers/90bf7d78b7c3c10cbab97da3c56beb97/status.svg)](http://joss.theoj.org/papers/90bf7d78b7c3c10cbab97da3c56beb97)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/90bf7d78b7c3c10cbab97da3c56beb97"><img src="http://joss.theoj.org/papers/90bf7d78b7c3c10cbab97da3c56beb97/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/90bf7d78b7c3c10cbab97da3c56beb97/status.svg)](http://joss.theoj.org/papers/90bf7d78b7c3c10cbab97da3c56beb97)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rasbt/mlxtend" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mlgill, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [X] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rasbt/mlxtend">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.11.0)?
- [x] **Authorship:** Has the submitting author (@rasbt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?  
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @mlgill it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00638/joss.00638/10.21105.joss.00638.pdf)

**Comment by rasbt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00638/joss.00638/10.21105.joss.00638.pdf)

**Comment by rasbt** [comment]
(regarding the changes in the PDF: I just added a list of acknowledgements attributing the contributors)

**Comment by mlgill** [comment]
@rasbt @arokem Am now able to work on this -- thanks for your patience. Have completed general checks and paper checks. Will devote some time to the functionality and documentation sections this week.

**Comment by mlgill** [comment]
@rasbt Requested DOIs links for journal article references in paper. Issue is [here](https://github.com/rasbt/mlxtend/issues/360).

**Comment by rasbt** [comment]
> Requested DOI links for journal article references in paper. Issue is here.

Thx. I added the DOIs to all papers for which they exist. The updated PDF paper is available via whedon's link above

**Comment by mlgill** [comment]
Minor (non-critical) suggestion to link to the very nice user guide from the examples section, see [issue](https://github.com/rasbt/mlxtend/issues/364).

**Comment by mlgill** [comment]
@rasbt  I am completed with the review, other than the request to clean up documentation (which appears to be in-progress) based on the issue. When this is complete, please let me know and I will check it off.

I have also listed one other minor (non-critical suggestion) above. This isn't required.

Please let me know what else is needed other than checking off the last box. Thank you for the opportunity to review -- this was my first JOSS review and I really enjoyed it.

cc @arokem

**Comment by rasbt** [comment]
@mlgill thanks for the time doing such a thorough review, and the issues you pointed out were very helpful -- these were things I never noticed myself and I am glad that they are fixed now! Also, I am glad to hear that you liked the process, which I hope wasn't too tedious :).

**Comment by mlgill** [comment]
@rasbt It wasn't tedious at all--lots of fun. I've marked the last box as complete above. If I need to do anything else to mark this review as complete, please let me know. cc @arokem

**Comment by arokem** [comment]
Thanks @mlgill! Nothing more on your end. 

@rasbt : I believe the paper is ready to be accepted! 

It would be nice to include something to address https://github.com/rasbt/mlxtend/issues/364, but that's not a requirement. Either way, let me know when you have an archive  (e.g., a Zenodo DOI) of the version that includes all the changes following the review.

**Comment by rasbt** [comment]
Sounds great! I will try to address the suggestion in the upcoming days (prob. on the weekend) and make a new release version (and also upload it to Zenodo then), which will also include the other documentation fixes from this review. I will let you know once that's ready!

**Comment by rasbt** [comment]
@arokem I just made the changes as suggested in [rasbt/mlxtend#364](https://github.com/rasbt/mlxtend/issues/364) and also made a new release version (0.12.0). The Zenodo link is https://zenodo.org/record/1226560

Please let me know if there's something else that needs to be done!  I am looking forward to the published version :)

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00638/joss.00638/10.21105.joss.00638.pdf)

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1226560 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1226560" target="_blank">10.5281/zenodo.1226560</a> is the archive.

**Comment by arokem** [comment]
👏 bravo @rasbt : I believe that this is ready to be accepted. 

@arfon : could you please take a look and put the ribbon on this one?

**Comment by arfon** [comment]
@mlgill - many thanks for your review here and to @arokem for editing this submission ✨ 

@rasbt - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00638 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00638/status.svg)](https://doi.org/10.21105/joss.00638)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00638/status.svg)](https://doi.org/10.21105/joss.00638)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by rasbt** [comment]
This is great, thanks @arfon , and thanks @mlgill and @arokem for all your help and volunteering efforts :)
