### ISSUE TITLE
[REVIEW]: LearnSAT: A SAT Solver for Education

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#639]
**Submitting author:** @motib (<a href="http://orcid.org/0000-0002-2091-5107">Mordechai Ben-Ari</a>)
**Repository:** <a href="https://github.com/motib/LearnSAT" target ="_blank">https://github.com/motib/LearnSAT</a>
**Version:** V2.0
**Editor:** @danielskatz
**Reviewer1:** @audemard
**Reviewer2:** @biotomas
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1230536" target="_blank">10.5281/zenodo.1230536</a>

## Status

[![status](http://joss.theoj.org/papers/7bb33dc5b9f0c455eed04642dc710d6b/status.svg)](http://joss.theoj.org/papers/7bb33dc5b9f0c455eed04642dc710d6b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7bb33dc5b9f0c455eed04642dc710d6b"><img src="http://joss.theoj.org/papers/7bb33dc5b9f0c455eed04642dc710d6b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7bb33dc5b9f0c455eed04642dc710d6b/status.svg)](http://joss.theoj.org/papers/7bb33dc5b9f0c455eed04642dc710d6b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/motib/LearnSAT" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer1 instructions & questions

@audemard, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/motib/LearnSAT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (V2.0)?
- [x] **Authorship:** Has the submitting author (@motib) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

## Reviewer2 instructions & questions

@biotomas, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/motib/LearnSAT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (V2.0)?
- [x] **Authorship:** Has the submitting author (@motib) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @audemard it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00639/joss.00639/10.21105.joss.00639.pdf)

**Comment by danielskatz** [comment]
@arfon, please invite @biotomas so that he can do this review

**Comment by danielskatz** [comment]
@audemard & @biotomas - this review is now open.
See instructions above.

Please use this issue to track any questions/concerns you have, even if you actually create new issues on focused details in https://github.com/motib/LearnSAT

Any questions on the review, please ask.

**Comment by motib** [comment]
@audemard , @biotomas,

Thank you for agreeing to review my submission.

I am leaving today for a 12-day vacation (really, I'm not taking a laptop!).
While I will be able to respond to general queries,
addressing detailed questions about the software
will have to wait until the beginning of April.

**Comment by danielskatz** [comment]
@arfon, please invite @biotomas so that he can do this review

**Comment by arfon** [comment]
> @arfon, please invite @biotomas so that he can do this review

Done.

**Comment by danielskatz** [comment]
@audemard @biotomas - I'm hoping that you both can start your reviews soon.

In case it's not clear, your job is basically to go through the checklist items, making sure that all can be checked.  To do this, you will also have to examine the [paper](https://github.com/openjournals/joss-papers/blob/joss.00639/joss.00639/10.21105.joss.00639.pdf) and the contents of the [code repository](https://github.com/motib/LearnSAT).

If you can check off an item, please do.  If you cannot, please either discuss it here if it is brief, or open an issue in the [code repository](https://github.com/motib/LearnSAT) and put a comment here pointing to that issue.

Thanks.

**Comment by biotomas** [comment]
Hi, so I left two checkboxes unchecked because I found no DOIs in references and also no community guidelines.

**Comment by danielskatz** [comment]
@motib - In response to the comments by @biotomas:

1. It looks like the handbook chapters have DOIs (http://ebooks.iospress.nl/volume/handbook-of-satisfiability) so you should be able to add at least that one DOI.  I don't think there are DOIs for the two books, but if they have similar identifiers, such as ISBNs, please add them.

2. While looking at https://github.com/motib/LearnSAT/blob/master/learnsat.bib, I also notice you have quite a few entries in this file that are not actually cited in the paper.md file and thus are not references. I don't know if you want to cite any more of the bib entries.

3. I also see that there is no References header in the paper.md file.   I've created https://github.com/motib/LearnSAT/pull/1 to fix this. 

4. Please also address the lack of community guidelines.

**Comment by motib** [comment]
My thanks to @biotomas for his comments.

1. I have chased down DOIs and ISBNs for all the references and will update the documents.

2. The file "learnsat.bib" contains the bibtex entries for _all_ three of the documents included in the archive as well as those in paper.md. Since latex is smart enough to extract only the references cited for each document, I don't see this as a problem. To the contrary, if I had four separate files, there would be a risk of inconsistency.

3. I am rather new to git. Would it be correct for me simply to click "merge"?

4. I'm sorry for not noticing this. The submission instructions don't specify where this information should be included. In the "readme"? In a separate file? If so, is there a convention for naming it?

@danielskatz: please clarify points 3 and 4 and I'll update the submission.

**Comment by danielskatz** [comment]
@motib -

> 3. I am rather new to git. Would it be correct for me simply to click "merge"?

yes, though of course you should first check the changed file(s) to make sure you want to merge it.

> 4. I'm sorry for not noticing this. The submission instructions don't specify where this information should be included. In the "readme"? In a separate file? If so, is there a convention for naming it?

This is commonly in both the readme and the documentation, but there is no requirement - it should be where you think it will be the most useful to potential contributors.

**Comment by motib** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00639/joss.00639/10.21105.joss.00639.pdf)

**Comment by motib** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00639/joss.00639/10.21105.joss.00639.pdf)

**Comment by motib** [comment]
I have made the modifications, but the isbns/dois do not appear on the generated pdf of the "paper". Possibly, s not including the package \url that I use to format the dois. If so, should I remove \url or is there someway to add this package?

Also: @danielskatz I just noticed that you forked the project, but I made the modifications to the master branch. Is that OK?

**Comment by danielskatz** [comment]
> Also: @danielskatz I just noticed that you forked the project, but I made the modifications to the master branch. Is that OK?

It looks like you made the equivalent change to what was in my branch without merging my branch's PR, which is fine, so I've now deleted the branch and closed the PR.

**Comment by danielskatz** [comment]
> I have made the modifications, but the isbns/dois do not appear on the generated pdf of the "paper". Possibly, it is not including the package \url that I use to format the dois. If so, should I remove \url or is there someway to add this package?

@arfon, can you help with this?  I would have expected the note data to be pulled from the .bib file into the references.  Perhaps you can suggest how this should be done?

**Comment by danielskatz** [comment]
@arfon - ping... re: 2 comments up :)

**Comment by arfon** [comment]
> @arfon, can you help with this? I would have expected the note data to be pulled from the .bib file into the references. Perhaps you can suggest how this should be done?

Sure. I think these should be listed as `doi` fields as well as `url`. So for [this line](https://github.com/motib/LearnSAT/blob/master/learnsat.bib#L22) change it to: 

```
doi={10.1145/3107239},
url={http://dx.doi.org/10.1145/3107239}

```

**Comment by danielskatz** [comment]
And what do you suggest for the ISBNs for the books?  I would have expected the note field to work.

**Comment by motib** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00639/joss.00639/10.21105.joss.00639.pdf)

**Comment by arfon** [comment]
> And what do you suggest for the ISBNs for the books? I would have expected the note field to work.

According to this post the `note` field should work https://tex.stackexchange.com/questions/52040/bibtex-show-isbn-number. I'm not sure what bibliography style we're using for JOSS but it's clearly not including `note` fields by default...

**Comment by motib** [comment]
@arfon: On stackexchange I found a simple way to include DOIs: change the bib style to "plainurl" and include the "hyperref" package. "hyperref" additionally creates internal links in the PDF. Now the documents include "doi" fields with no "http" but the fields are clickable links. On the whedon-generated pdf, the "doi" appears as a link with "http".

There is no simple way include isbn's (without major surgery to the source files that I don't want to do and don't see a need for). The suggestion is to use "note" since books are easy to search for on google or amazon. This works OK for the documents, but not for the whedon-generated pdf. Since that is not under my control, I can't fix it ....

As per @danielskatz's suggestion, I moved the community guidelines to the readme file and referred to it in the User Guide. I took the opportunity to modify the UG by deleting the instruction to download from my personal website; instead, I give links to the JOSS article and to the GitHub repo.

**Comment by arfon** [comment]
> Is this something you think we can fix, or should we just accept that we can't do this for now?

I think it's worth opening an issue to track this bug but I don't think this can be fixed quickly.

**Comment by danielskatz** [comment]
ok, I opened https://github.com/openjournals/joss/issues/392

**Comment by biotomas** [comment]
I checked off all the items

**Comment by danielskatz** [comment]
:wave: @audemard - please continue your review, or let us know what issues are blocking you.

**Comment by audemard** [comment]
Sorry for the delay.
It is done now.

**Comment by danielskatz** [comment]
Great!
:wave: arfon - can we move this to acceptance now?

**Comment by arfon** [comment]
@motib - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by motib** [comment]
@arfon: I have never heard of these before so I have a couple of questions.
I logged into Zenodo (with my GitHub account).

1. It wants me to upload files. Should I update individual files or could I just download a zip of the GitHub repository and upload that? I would prefer the latter since the directories on my computer have additional stuff like my local backups that I don't want to upload.

2. It asks "Did your publisher already assign a DOI to your upload?" Does that mean that I should give them the JOSSS DOI or should I let Zenodo assign one? In the latter case, should I add the JOSS DOI to the "related identifier" field?
Thanks....

**Comment by arfon** [comment]
> It wants me to upload files. Should I update individual files or could I just download a zip of the GitHub repository and upload that? I would prefer the latter since the directories on my computer have additional stuff like my local backups that I don't want to upload.

@motib - I'd suggest following this guide - it should be pretty simple: https://guides.github.com/activities/citable-code/

> It asks "Did your publisher already assign a DOI to your upload?" Does that mean that I should give them the JOSSS DOI or should I let Zenodo assign one? In the latter case, should I add the JOSS DOI to the "related identifier" field?

We don't assign a DOI for your upload. Let Zenodo assign one (and paste it in this thread). 

> In the latter case, should I add the JOSS DOI to the "related identifier" field?

You can do this. Your JOSS DOI will be https://doi.org/10.21105/joss.00639

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00639/status.svg)](https://doi.org/10.21105/joss.00639)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00639/status.svg)](https://doi.org/10.21105/joss.00639)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by motib** [comment]
I think I did everything OK!
The Zenodo DOI is [https://doi.org/10.5281/zenodo.1230536](https://doi.org/10.5281/zenodo.1230536)

**Comment by danielskatz** [comment]
@whedon set https://doi.org/10.5281/zenodo.1230536 as repository

**Comment by arfon** [comment]
@audemard, @biotomas - many thanks for your reviews here and to @danielskatz for editing this submission ✨ 

@motib - your paper is now accepted into JOSS and your DOI Is https://doi.org/10.21105/joss.00639 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00639/status.svg)](https://doi.org/10.21105/joss.00639)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00639/status.svg)](https://doi.org/10.21105/joss.00639)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
