### ISSUE TITLE
[REVIEW]: MCMCvis: Tools to Visualize, Manipulate, and Summarize MCMC Output

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#640]
**Submitting author:** @caseyyoungflesh (<a href="http://orcid.org/0000-0001-6343-3311">Casey Youngflesh</a>)
**Repository:** <a href="https://github.com/caseyyoungflesh/MCMCvis" target ="_blank">https://github.com/caseyyoungflesh/MCMCvis</a>
**Version:** v0.10.0
**Editor:** @arfon
**Reviewer:** @jkarreth
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1216120" target="_blank">10.5281/zenodo.1216120</a>

## Status

[![status](http://joss.theoj.org/papers/9d048f52995899530cd46a2f443f1612/status.svg)](http://joss.theoj.org/papers/9d048f52995899530cd46a2f443f1612)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9d048f52995899530cd46a2f443f1612"><img src="http://joss.theoj.org/papers/9d048f52995899530cd46a2f443f1612/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9d048f52995899530cd46a2f443f1612/status.svg)](http://joss.theoj.org/papers/9d048f52995899530cd46a2f443f1612)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/caseyyoungflesh/MCMCvis" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jkarreth, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/caseyyoungflesh/MCMCvis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.9.4)?
- [x] **Authorship:** Has the submitting author (@caseyyoungflesh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jkarreth it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@jkarreth - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00640/joss.00640/10.21105.joss.00640.pdf)

**Comment by caseyyoungflesh** [comment]
@jkarreth Many thanks. I'll respond here once these issues are addressed.

## Responses to major comments
* Thanks for pointing that bug out. I'll have it fixed shortly.
* 'tidybayes' appears to be an excellent package that I was not aware of until fairly recently. Its strengths lie in its integration of Bayesian model output with ggplot. I think the area where `MCMCvis` excels beyond what `tidybayes` has to offer is summarizing and manipulating Bayesian model output. As you say, the two packages both make analyzing Bayesian model output easier, though the emphasis differs. I can see the additional plotting functionality of `tidybayes` to be extremely useful. Combining these two packages would certainly make for a useful 'one stop shop' for dealing with Bayesian model output. I think there may be an opportunity for merging these packages in the future and I appreciate the suggestion.


## Responses to minor comments
* While all functions have examples, I agree that creating several toy models using different packages to show that the package can handle different output would be helpful for users. I will update the vignette accordingly.
* I think including some tests will make future development easier. I will include these with the other suggested improvements.

**Comment by caseyyoungflesh** [comment]
@jkarreth 

Package version 0.10.0 is now on github.
*  This version fixes the `stanfit` bug identified above. `stanfit` objects are now processed correctly.
*  I have included toy models fit with JAGS and Stan in the vignette to demonstrate how output from different samplers can be input into the MCMCvis functions directly.
* I have also included automated tests to make sure that different input types are properly processed (to avoid the previously noted `stanfit` issue).
* This version also includes several other features, as noted in `NEWS.md`

MCMCvis version 0.10.0 has passed all CRAN checks. A new version will be submitted to CRAN soon. The most recent version github version can be installed with:

`devtools::install_github('caseyyoungflesh/MCMCvis', build_vignettes = TRUE)`

**Comment by caseyyoungflesh** [comment]
Thank you very much @jkarreth! Version 0.10.0 is now on CRAN (though all binaries may not be built yet).

**Comment by jkarreth** [comment]
Looks great to me; all boxes are checked off and my review is complete from my end. Congrats!

**Comment by arfon** [comment]
Excellent. Thanks @jkarreth.

@caseyyoungflesh - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by caseyyoungflesh** [comment]
@arfon thanks!

**DOI for all versions:** 10.5281/zenodo.1216119

**DOI for v0.10.0:** 10.5281/zenodo.1216120

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1216120 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1216120" target="_blank">10.5281/zenodo.1216120</a> is the archive.

**Comment by arfon** [comment]
@jkarreth - many thanks for your review here.

@caseyyoungflesh - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00640 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00640/status.svg)](https://doi.org/10.21105/joss.00640)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00640/status.svg)](https://doi.org/10.21105/joss.00640)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
