### ISSUE TITLE
[PRE REVIEW]: CLIMLAB: a Python toolkit for interactive, process-oriented climate modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#641]
**Submitting author:** @brian-rose (<a href="http://orcid.org/0000-0002-9961-3821">Brian Rose</a>)
**Repository:** <a href="https://github.com/brian-rose/climlab/" target ="_blank">https://github.com/brian-rose/climlab/</a>
**Version:** v0.6.4
**Editor:** @lheagy
**Reviewers:** @Chilipp, @dhhagan

**Author instructions**

Thanks for submitting your paper to JOSS @brian-rose. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@brian-rose if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #641 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
👋@lheagy - the submitting author suggested you as the handling editor.

**Comment by lheagy** [comment]
I would be happy to edit this submission!

**Comment by brian-rose** [comment]
I pushed an update to the climlab repo that fixes the missing affiliation issue. Not sure if I need to take some other action here?

**Comment by lheagy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00641/joss.00641/10.21105.joss.00641.pdf)

**Comment by brian-rose** [comment]
Ok there were some missing refs and formatting issues. Just pushed a new update.

**Comment by brian-rose** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00641/joss.00641/10.21105.joss.00641.pdf)

**Comment by brian-rose** [comment]
Better but not picking up two missing refs that I just added to `paper.bib`

**Comment by lheagy** [comment]
Thanks @brian-rose: when did you add them? we can re-compile again

**Comment by brian-rose** [comment]
In the same commit where I fixed the formatting. I'll try again...

**Comment by brian-rose** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00641/joss.00641/10.21105.joss.00641.pdf)

**Comment by brian-rose** [comment]
Ah, find a typo in my source. Let's try this again...

@whedon generate pdf

**Comment by brian-rose** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00641/joss.00641/10.21105.joss.00641.pdf)

**Comment by brian-rose** [comment]
@lheagy looks good to me now.

**Comment by lheagy** [comment]
Thanks @brian-rose, looks good! I will start sending out messages for reviewers. Do you have any suggestions?

**Comment by brian-rose** [comment]
I don't have any particular reviewer requests. There are a few folks on the reviewer list who list Python and "atmospheric science" or "climate".

**Comment by lheagy** [comment]
👋 Hi @Chilipp, @andreas-h, with your background in climate and atmospheric science as well as experience with python, your input on this JOSS submission would be much appreciated! Would you be willing to review this submission for JOSS?

**Comment by Chilipp** [comment]
Yes @lheagy, it sounds very interesting. :ok_hand:

**Comment by lheagy** [comment]
Thanks @Chilipp! We will wait to hear from @andreas-h before starting the review

**Comment by lheagy** [comment]
Just a quick update: I have sent off an email, so hopefully we will hear back shortly. If possible, it is preferable to have 2 reviewers.

**Comment by dhhagan** [comment]
@lheagy Absolutely. Hopefully within the next week?  A bit busy the next few days, but should be able to start by the weekend/early next week if that's okay.

**Comment by lheagy** [comment]
Thanks @dhhagan, within the next week or early next week would be great!

**Comment by lheagy** [comment]
@whedon assign @Chilipp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Chilipp

**Comment by lheagy** [comment]
@whedon add @dhhagan as reviewer

**Comment by whedon** [comment]
OK, @dhhagan is now a reviewer

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/659. Feel free to close this issue now!
