### ISSUE TITLE
[PRE REVIEW]: Spiral: splitters for identifiers in source code files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#646]
**Submitting author:** @mhucka (<a href="http://orcid.org/0000-0001-9105-5960">Michael Hucka</a>)
**Repository:** <a href="https://github.com/casics/spiral" target ="_blank">https://github.com/casics/spiral</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewers:** @timClicks

**Author instructions**

Thanks for submitting your paper to JOSS @mhucka. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mhucka if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #646 with the following error: 

 Can't find any papers to compile :-(

**Comment by mhucka** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00646/joss.00646/10.21105.joss.00646.pdf)

**Comment by mhucka** [comment]
Looks good.

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by mhucka** [comment]
@arfon Similar to my question related to another paper recently submitted: I neglected to include an NSF agency funding acknowledgment in this paper as well. Can I go ahead and modify the paper that's in the github repo, or is there a different procedure I should follow?

**Comment by mhucka** [comment]
@arfon W.r.t. reviewers, based solely on the domains/topics of expertise listed in the spreadsheet, the following people seem like they might be candidates:
* richardlitt
* timClicks
* ahurriyetoglu

**Comment by arfon** [comment]
@timClicks, @ahurriyetoglu - would you be willing to review this submission for JOSS? As this submission is outside of my research area I would like to find two reviewers for this submission.

**Comment by mhucka** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00646/joss.00646/10.21105.joss.00646.pdf)

**Comment by timClicks** [comment]
@arfon @mhucka Thanks for the invitation both - I will take a detailed look within 48h.

**Comment by timClicks** [comment]
I've taken some time to review the paper and the project. Well done, it's very impressive. Thanks for taking the time to refine so many details.

My decision is to **Accept** the paper, subject to clarification about the first point below.

Here my review notes with reference to the [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines):

- The "JOSS paper" section requires a list of authors and affiliations. This paper doesn't include an explicit list, which I assume is yourself as a single developer. @arfon - could you please provide guidance as to whether the paper's listed author is sufficient?
- license - ✔️ - spiral provides a copy of the [GPL v3 license](https://github.com/casics/spiral) within the root of the distribution  (Acceptable)
- documentation ✔️ 
   - statement of need  ✔️ - ("The need for splitting identifiers arises in a variety of contexts, including natural language processing (NLP) methods applied to source code analysis and program comprehension. ")
   - installation instrutions ✔️ - spiral is installable via `pip`, which is documented in the `README` file ("`sudo pip3 install git+https://github.com/casics/spiral.git`")
    - dependencies ✔️ - described in a machine-readable format by the [`requirements.txt`](https://github.com/casics/spiral/blob/master/requirements.txt) file (Good)
    - example usage: ✔️
    - API documentation: ✔️ All public APIs such as the `spiral.ronin`, `spiral.samurai` and `spiral.simple_splitters` module include extensive, well-written documentation provided as docstrings that includes an overview of the API and the parameters in detail (Good)
- tests: [spiral](https://github.com/casics/spiral/tree/master/tests) includes a thorough test suite and includes instructions on how to run it
- community guidelines: ✔️ are available in the `README` files, with sections for developers and end-users
 
Here is some other feedback from me personally:  

- excellent in-source documentation: the [source files](https://github.com/casics/spiral/blob/master/spiral/ronin.py#L202) contain extensive notes about implementation decisions
- the repository includes extensive details of the differences/limitations between splitting implementations
- cites prior art - spiral includes [references to further material](https://github.com/casics/spiral#-more-information), including alternative implementations

**Comment by mhucka** [comment]
Thanks for your review! About this item:

> The "JOSS paper" section requires a list of authors and affiliations. This paper doesn't include an explicit list, which I assume is yourself as a single developer. 

I am confused about what this refers to. The paper currently includes an explicit list of authors and affiliations in the format defined by JOSS. Also, a quick comparison to other JOSS papers shows that the amount of information about the sole author provided in this paper (about Spiral) is identical to the amount of information provided in other published JOSS papers. Can you please clarify what you mean or are looking at when you say the paper doesn't include an explicit list? I'll be happy to correct the problem if possible.

**Comment by arfon** [comment]
👋@timClicks - thanks for making a head start on this. I should have clarified that I've not actually formally opened the review up yet (I was waiting for a second reviewer).

That said, given you've already started I'll go ahead and make the review issue now with the checklist for you to work through.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @timClicks as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @timClicks

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/653. Feel free to close this issue now!
