### ISSUE TITLE
[PRE REVIEW]: ggstatsplot: R package for 'ggplot2' Based Plots with Statistical Details

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#647]
**Submitting author:** @IndrajeetPatil (<a href="http://orcid.org/0000-0003-1995-6531">Indrajeet Patil</a>)
**Repository:** <a href="https://github.com/IndrajeetPatil/ggstatsplot" target ="_blank">https://github.com/IndrajeetPatil/ggstatsplot</a>
**Version:** 0.0.1
**Editor:** @cMadan
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @IndrajeetPatil. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@IndrajeetPatil if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #647 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
👋@cMadan - the submitting author suggested you as the handling editor.

**Comment by cMadan** [comment]
Hi @IndrajeetPatil! I'm looking forward to overseeing the review of your submission. Before we get started it looks like there are two things to figure out:
(1) You need a paper.md file with your JOSS manuscript in the repo--our automated assistant, @whedon, wasn't able to find it, nor was I.
(2) Do you have any suggestions for suitable reviewers for this package?

That aside, I looked over your readme.md and found it remarkably filed with details and examples, definitely one of the best I have come across!

**Comment by IndrajeetPatil** [comment]
@cMadan Oh no, I am really sorry about this, but I didn't realize that there needs to be an associated paper that needs to be included with the submission. I thought this was just a review of the packages or software and its functioning. I will add the paper to the submission soon.

**Comment by cMadan** [comment]
No worries. Our review process is centered around the software itself, but a brief paper is part of the process, likely only two paragraphs or so (but does have a few references too). I didn't see how well you meet our other requirements, that was just the most obvious missing aspect. Please do take a look at the review issues for a few recent accepted submissions as examples of the requirements for publishing in JOSS and as examples of accepted papers.

Please reply here after you're ready to continue with the pre-review and I'll take another look at your project repo then and see if anything else needs to be sorted before we try and find someone to be a reviewer.

**Comment by arfon** [comment]
I'm going to close this submission at it's been over 6 months since there was any activity. Feel free to resubmit again in the future @IndrajeetPatil.
