### ISSUE TITLE
[REVIEW]: comorbidity: An R package for computing comorbidity scores

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#648]
**Submitting author:** @ellessenne (<a href="http://orcid.org/0000-0002-8319-7624">Alessandro Gasparini</a>)
**Repository:** <a href="https://github.com/ellessenne/comorbidity" target ="_blank">https://github.com/ellessenne/comorbidity</a>
**Version:** 0.1.0
**Editor:** @leeper
**Reviewer:** @corinne-riddell
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1209837" target="_blank">10.5281/zenodo.1209837</a>

## Status

[![status](http://joss.theoj.org/papers/0b42b825bc7d28a427dc2720f6f37790/status.svg)](http://joss.theoj.org/papers/0b42b825bc7d28a427dc2720f6f37790)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0b42b825bc7d28a427dc2720f6f37790"><img src="http://joss.theoj.org/papers/0b42b825bc7d28a427dc2720f6f37790/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0b42b825bc7d28a427dc2720f6f37790/status.svg)](http://joss.theoj.org/papers/0b42b825bc7d28a427dc2720f6f37790)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ellessenne/comorbidity" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@corinne-riddell, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ellessenne/comorbidity">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [x] **Authorship:** Has the submitting author (@ellessenne) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @corinne-riddell it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00648/joss.00648/10.21105.joss.00648.pdf)

**Comment by corinne-riddell** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by corinne-riddell** [comment]
Hi @ellessenne, 

Nice package! I've learned a lot reading your code and it was interesting to read about the comorbidity scores based on ICD codes. 

I've opened three issues  with a few suggestions to improve documentation in the README, and return descriptions for the comorbidity function. I also have an issue regarding testthat, but it may be a misunderstanding on my end.

I have also left unchecked two items above to be addressed:
- please add community guidelines to your documentation
- there is also an item re: clear statement of dependencies. I didn't find any, but not sure of the protocol if your package doesn't have any.

Once these items are addressed we can loop in the editor and keep the ball rolling.

**Comment by leeper** [comment]
Thanks for your review, @corinne-riddell!!

@ellessenne Once you've had a chance to respond to these points and the open issues, please leave me a message here and I will give everything a final check.

**Comment by ellessenne** [comment]
Thank you very much @corinne-riddell for your review!
I merged your pull requests and I am going to work on the issues you raised straight away. Very helpful!
Regarding the two unchecked items left to be addressed:
1- I can add a CONTRIBUTING.md file to the repository;
2- I can add explicit dependencies on the README file, it would be the same packages included in the 
DESCRIPTION file. 
@leeper, would this be ok?
Thanks!

**Comment by leeper** [comment]
No need to list dependencies beyond the DESCRIPTION file. I'll tick that one for you.

**Comment by ellessenne** [comment]
Thanks @leeper; I also just added contributing guidelines and code of conduct to the repository.

@corinne-riddell, I made some changes following your PRs / Issues, could you please give it a check? Thank you!

**Comment by corinne-riddell** [comment]
@ellessenne @leeper looks great, I think we're good to go on accepting this. Good job @ellessenne 👍

**Comment by leeper** [comment]
Excellent. Thanks, @corinne-riddell!!

**Comment by leeper** [comment]
@ellessenne Can you please generate an archive of your repository using, for example, figshare or zenodo and then include the DOI for the archive in a comment here? Once I have that, we can accept your paper in JOSS!

**Comment by ellessenne** [comment]
Thank you very much again @corinne-riddell and @leeper!
I uploaded the current version of `comorbidity` to Zenodo, the corresponding DOI is: [10.5281/zenodo.1209837](https://doi.org/10.5281/zenodo.1209837). I think the link (via [doi.org](https://doi.org)) is not active yet, I am not sure how long it will take but should be ok!

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1209837 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1209837" target="_blank">10.5281/zenodo.1209837</a> is the archive.

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00648/joss.00648/10.21105.joss.00648.pdf)

**Comment by leeper** [comment]
@ellessenne Great. Thank you! We should be all set.

Thank you, again, @corinne-riddell!! Hope you enjoyed your first review for JOSS!

@arfon Over to you.

**Comment by ellessenne** [comment]
Thank you all! This was a great experience overall, and I would like to contribute to the project - @leeper, if you need reviewers for R / epidemiology / biostatistics manuscripts please don't hesitate to contact me!

**Comment by leeper** [comment]
@ellessenne Glad to hear it was a good experience! Please sign-up to be a reviewer here: http://joss.theoj.org/reviewer-signup.html

**Comment by arfon** [comment]
@corinne-riddell - many thanks for your review here and to @leeper for editing this submission ✨ 

@ellessenne - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00648 ⚡️:rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00648/status.svg)](https://doi.org/10.21105/joss.00648)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00648/status.svg)](https://doi.org/10.21105/joss.00648)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
