### ISSUE TITLE
[PRE REVIEW]: Filtering academic literature by Altmetric score and a twitter bot

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#649]
**Submitting author:** @wdecoster (<a href="http://orcid.org/0000-0002-5248-8197">Wouter De Coster</a>)
**Repository:** <a href="https://github.com/wdecoster/PromisingPreprint" target ="_blank">https://github.com/wdecoster/PromisingPreprint</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @wdecoster. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wdecoster if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00649/joss.00649/10.21105.joss.00649.pdf)

**Comment by wdecoster** [comment]
@whedon commands

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00649/joss.00649/10.21105.joss.00649.pdf)

**Comment by wdecoster** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00649/joss.00649/10.21105.joss.00649.pdf)

**Comment by wdecoster** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @wdecoster, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
Hi @wdecoster. Thanks for your submission to JOSS. Unfortunately this submission has been deemed out of scope for JOSS. As noted in our [submission requirements](http://joss.theoj.org/about#submission_requirements):

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

Thanks again for your interest.
