### ISSUE TITLE
[REVIEW]: Spiral: splitters for identifiers in source code files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#653]
**Submitting author:** @mhucka (<a href="http://orcid.org/0000-0001-9105-5960">Michael Hucka</a>)
**Repository:** <a href="https://github.com/casics/spiral" target ="_blank">https://github.com/casics/spiral</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewer:** @timClicks
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1211835" target="_blank">10.5281/zenodo.1211835</a>

## Status

[![status](http://joss.theoj.org/papers/7c70f7eb25abd6d3b4260eb9618a4815/status.svg)](http://joss.theoj.org/papers/7c70f7eb25abd6d3b4260eb9618a4815)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7c70f7eb25abd6d3b4260eb9618a4815"><img src="http://joss.theoj.org/papers/7c70f7eb25abd6d3b4260eb9618a4815/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7c70f7eb25abd6d3b4260eb9618a4815/status.svg)](http://joss.theoj.org/papers/7c70f7eb25abd6d3b4260eb9618a4815)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/casics/spiral" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@timClicks, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/casics/spiral">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@mhucka) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @timClicks it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00653/joss.00653/10.21105.joss.00653.pdf)

**Comment by arfon** [comment]
@timClicks -  please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by arfon** [comment]
@ahurriyetoglu  - we'd still love a review from you for this submission if you're willing/able :grin:

**Comment by timClicks** [comment]
@arfon Thanks for this. Apologies for getting the flow wrong! 

p.s. I hadn't actually realized that my request to become a reviewer had been accepted. Happy to help 😄

**Comment by timClicks** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by timClicks** [comment]
@arfon I've reviewed the paper & code and could only find this technicality preventing an Accept: 

- **References**: My understanding is that WordNet should be given a formal citation in the paper https://wordnet.princeton.edu/citing-wordnet. The DOI for the Miller article is [10.1145/219717.219748](http://dx.doi.org/10.1145/219717.219748)

Some more general notes:

- Has the Ronin algorithm been described in its own right? It looks like a very interesting contribution to the state of the art.
- The repo is _large_ as it contains data files and installation takes a long time to download the ~70MB of assets. `pip` doesn't report progress made by `git` during the clone stage and initially believed that the process had hung when I ran `pip install git+https://github.com/casics/spiral.git` myself.

**Comment by mhucka** [comment]
@timClicks Thank you for your review and comments. 

With respect to citing WordNet, although I interpret their instructions to only require citing where WordNet is discussed (note the paper doesn't mention it), I think I should modify the paper to mention WordNet and then cite the recommended sources. In any case, the website doesn't properly acknowledge the papers (though it referenced WordNet and its license). I'll update that too.

With respect to the other questions:
* Ronin has not been described elsewhere. I hope to have time to write a separate paper about the algorithm.
* Turns out the problem is not so much Spiral itself (which totals 23Mb) but rather the git history. I will try to prune it using BFG – maybe we reduce the size.

**Comment by mhucka** [comment]
The new version of the paper has the new citations.

**Comment by mhucka** [comment]
Regarding the size: I've now spent an hour trying various git pruning methods, and while they definitely did remove some old cruft in the git history, the cloned repo size has not changed – it's still 70M.  I'm very annoyed, but I'm also at the limit of what I know how to do with git in reducing sizes. My best guess here is that the repeated updates of the data files are in git's history, and that's what's blowing up the size of the repo.

How much of a problem is the size issue? At this point, I think the only option to avoid it is to create a pypi distribution and avoid the git clone approach, which is something I wanted to do eventually anyway, but preferably not right now due to time constraints ...

**Comment by arfon** [comment]
> How much of a problem is the size issue? At this point, I think the only option to avoid it is to create a pypi distribution and avoid the git clone approach, which is something I wanted to do eventually anyway, but preferably not right now due to time constraints ...

@mhucka - I think this is OK and shouldn't be a blocker for accepting this submission.

At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by mhucka** [comment]
Thanks! This is now done. The DOI at Zenodo is [10.5281/zenodo.1211835](https://zenodo.org/record/1211835)

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1211835" target="_blank">10.5281/zenodo.1211835</a> is the archive.

**Comment by arfon** [comment]
@timClicks - many thanks for your review here ✨ 

@mhucka - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00653 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00653/status.svg)](https://doi.org/10.21105/joss.00653)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00653/status.svg)](https://doi.org/10.21105/joss.00653)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
