### ISSUE TITLE
[PRE REVIEW]: Fast, Consistent Tokenization of Natural Language Text

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#654]
**Submitting author:** @lmullen (<a href="http://orcid.org/0000-0001-5103-6917">Lincoln Mullen</a>)
**Repository:** <a href="https://github.com/ropensci/tokenizers" target ="_blank">https://github.com/ropensci/tokenizers</a>
**Version:** v0.2.0
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @lmullen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lmullen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/655. Feel free to close this issue now!

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00654/joss.00654/10.21105.joss.00654.pdf)
