### ISSUE TITLE
[REVIEW]: Fast, Consistent Tokenization of Natural Language Text

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#655]
**Submitting author:** @lmullen (<a href="http://orcid.org/0000-0001-5103-6917">Lincoln Mullen</a>)
**Repository:** <a href="https://github.com/ropensci/tokenizers" target ="_blank">https://github.com/ropensci/tokenizers</a>
**Version:** v0.2.0
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1205017" target="_blank">10.5281/zenodo.1205017</a>

## Status

[![status](http://joss.theoj.org/papers/ad45003e0530e32579534b57322dd2f1/status.svg)](http://joss.theoj.org/papers/ad45003e0530e32579534b57322dd2f1)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ad45003e0530e32579534b57322dd2f1"><img src="http://joss.theoj.org/papers/ad45003e0530e32579534b57322dd2f1/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ad45003e0530e32579534b57322dd2f1/status.svg)](http://joss.theoj.org/papers/ad45003e0530e32579534b57322dd2f1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/tokenizers" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arfon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/tokenizers">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@lmullen) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00655/joss.00655/10.21105.joss.00655.pdf)

**Comment by arfon** [comment]
Accepting because of https://github.com/ropensci/onboarding/issues/33

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1205017 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1205017" target="_blank">10.5281/zenodo.1205017</a> is the archive.

**Comment by arfon** [comment]
@lmullen - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00655 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00655/status.svg)](https://doi.org/10.21105/joss.00655)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00655/status.svg)](https://doi.org/10.21105/joss.00655)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by lmullen** [comment]
@arfon Wow. That was fast. 

I noticed just a few minor formatting things with the BibTex. If I just update `paper.md` and `paper.bib`, can I regenerate the published version?

**Comment by arfon** [comment]
> I noticed just a few minor formatting things with the BibTex. If I just update paper.md and paper.bib, can I regenerate the published version?

Sure thing. Please just update the files in `master` on https://github.com/ropensci/tokenizers and I can update.

**Comment by lmullen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00655/joss.00655/10.21105.joss.00655.pdf)

**Comment by lmullen** [comment]
@arfon I've corrected some typos and the BibTeX for this paper as well. Could you please regenerate the final version? I didn't realize we could generate a PDF proof with the bot, or I would have done this earlier.

**Comment by arfon** [comment]
Sure thing. I've updated the PDF now. BTW, the online version you see is cached so it might take a few hours to show as updated online.

**Comment by lmullen** [comment]
@arfon Sorry to be a pest. But I noticed that the published PDF did not update after you regenerated it. I.e. the proof a few lines above is corrected but the published version isnt. Would you mind updating it if possible?

**Comment by arfon** [comment]
> @arfon Sorry to be a pest. But I noticed that the published PDF did not update after you regenerated it. I.e. the proof a few lines above is corrected but the published version isnt. Would you mind updating it if possible?

@lmullen - could you tell me what difference I should be looking for and can you confirm that this paper is _not_ correct: https://github.com/openjournals/joss-papers/blob/5716811674dbd048372cd310e8598708e82a235b/joss.00655/10.21105.joss.00655.pdf ?

**Comment by lmullen** [comment]
@arfon Yes, the [link above](https://github.com/openjournals/joss-papers/blob/5716811674dbd048372cd310e8598708e82a235b/joss.00655/10.21105.joss.00655.pdf) is not correct. If you compare that to [this proof](https://github.com/openjournals/joss-papers/blob/joss.00655/joss.00655/10.21105.joss.00655.pdf) you can check that the link to tokenizers in the second paragraph should *not* be bold and that in the bibliography my name should only appear once as `Mullen, Lincoln A. ` rather than two different entries, among other minor corrections.

**Comment by arfon** [comment]
OK, could you take a look now?

**Comment by lmullen** [comment]
Yes, that looks great. Thanks!
