### ISSUE TITLE
[REVIEW]: Quantitative Imaging Tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#656]
**Submitting author:** @spinicist (<a href="http://orcid.org/0000-0001-7640-5520">Tobias Wood</a>)
**Repository:** <a href="https://github.com/spinicist/QUIT" target ="_blank">https://github.com/spinicist/QUIT</a>
**Version:** v2.0.0
**Editor:** @cMadan
**Reviewer:** @oesteban
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1292086" target="_blank">10.5281/zenodo.1292086</a>

## Status

[![status](http://joss.theoj.org/papers/ddc35ff312425b42d5bfd77f2d9a56cf/status.svg)](http://joss.theoj.org/papers/ddc35ff312425b42d5bfd77f2d9a56cf)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ddc35ff312425b42d5bfd77f2d9a56cf"><img src="http://joss.theoj.org/papers/ddc35ff312425b42d5bfd77f2d9a56cf/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ddc35ff312425b42d5bfd77f2d9a56cf/status.svg)](http://joss.theoj.org/papers/ddc35ff312425b42d5bfd77f2d9a56cf)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/spinicist/QUIT" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@oesteban, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/spinicist/QUIT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.0.0)?
- [x] **Authorship:** Has the submitting author (@spinicist) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @oesteban it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00656/joss.00656/10.21105.joss.00656.pdf)

**Comment by spinicist** [comment]
Hello, I've been away but am now back. Is there anything I need to do for this except wait? The article proof looks okay to me. Thanks.

**Comment by oesteban** [comment]
I made a first pass over the conformity checks. I hope I'll go through installation and the rest along this week.

I guess all is on my plate right now

**Comment by spinicist** [comment]
Great, much appreciated.

**Comment by cMadan** [comment]
@oesteban, how is this review coming?

**Comment by oesteban** [comment]
Oh, sorry, my deepest apologies to @spinicist since I completely forgot about it. I'll finish up tomorrow: I don't expect to request anything else, so I'm 99% positive it will be the final thumbs up.

Sorry again.

**Comment by oesteban** [comment]
Okay, I managed to finish. Thumbs up from my side. My apologies for the delay.

**Comment by spinicist** [comment]
Thank you very much for your time.

I will keep pursuing the NeuroDebian packages, but there is a steep learning curve there. Hopefully will have some time when I get back from ISMRM.

@cMadan do you need anything more from me?

**Comment by cMadan** [comment]
@oesteban, no problem, thank you for the thorough review!

@spinicist, you're almost done! I just need the DOI for an archived version of the current code (i.e., deposit it on Zenodo or FigShare).

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.1292086 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1292086" target="_blank">10.5281/zenodo.1292086</a> is the archive.

**Comment by cMadan** [comment]
@spinicist, perfect, thank you!

@arfon, I think we're all set to accept here! :)

**Comment by arfon** [comment]
@oesteban - many thanks for your review here and to @cMadan for editing this submission ✨ 

@spinicist - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00656 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00656/status.svg)](https://doi.org/10.21105/joss.00656)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00656/status.svg)](https://doi.org/10.21105/joss.00656)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by spinicist** [comment]
@cMadan - Hi, I'm slightly concerned the meta-data for my paper is incorrect. If you look on the "Cite As:" section, it says "Wood, (2018) ...", i.e. my initials are missing. Similarly, I downloaded the paper and dragged it into Zotero and there it comes up with the author as "C Wood, Tobias", instead of "Wood, Tobias C". Could you take a quick look please?

Also does JOSS link to ORCID?

**Comment by cMadan** [comment]
Hi @spinicist, sorry I didn't see your reply here earlier!

The footer and website do just show the last name, without any initials. I'm not sure about how Zotero parses the meta data. I'm also not sure how integrated JOSS is with ORCiD (@arfon, maybe you can comment on this when you have a chance?). As far as I can tell, things are in order in the paper.md and resulting PDF.

**Comment by arfon** [comment]
It is possible that the Crossref metadata is incorrect. That's possibly/probably what's going on.

> Also does JOSS link to ORCID?

I don't know quite what you mean - we use ORCID logins but we don't have any other integrations. I believe Crossref has the ability to auto-update\ ORCID profiles: https://www.crossref.org/blog/crossref-to-auto-update-orcid-records/

**Comment by spinicist** [comment]
Thanks both. I was particularly concerned because my Google Scholar profile had not picked up the paper, but now it has.

I don't think I added my ORCID to the paper meta-data? Is it possible to do that?

**Comment by arfon** [comment]
Your ORCID was associated with this submission when we made the DOI with Crossref: https://github.com/openjournals/joss-papers/blob/master/joss.00656/10.21105.joss.00656.crossref.xml#L37

Is that the correct ORCID?

**Comment by spinicist** [comment]
Yes, that is the correct ORCID.

Of course, if I log into ORCID itself, the paper is listed there. Sorry I didn't think to do that first and taking up your time instead.

I think everything is in order now, thanks again.
