### ISSUE TITLE
[REVIEW]: CLIMLAB: a Python toolkit for interactive, process-oriented climate modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#659]
**Submitting author:** @brian-rose (<a href="http://orcid.org/0000-0002-9961-3821">Brian Rose</a>)
**Repository:** <a href="https://github.com/brian-rose/climlab/" target ="_blank">https://github.com/brian-rose/climlab/</a>
**Version:** v0.6.4
**Editor:** @lheagy
**Reviewer:** @Chilipp, @dhhagan
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1226360" target="_blank">10.5281/zenodo.1226360</a>

## Status

[![status](http://joss.theoj.org/papers/6831d26a8ae32c11b8991bb848d0d4e2/status.svg)](http://joss.theoj.org/papers/6831d26a8ae32c11b8991bb848d0d4e2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6831d26a8ae32c11b8991bb848d0d4e2"><img src="http://joss.theoj.org/papers/6831d26a8ae32c11b8991bb848d0d4e2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6831d26a8ae32c11b8991bb848d0d4e2/status.svg)](http://joss.theoj.org/papers/6831d26a8ae32c11b8991bb848d0d4e2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/brian-rose/climlab/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Chilipp & @dhhagan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/brian-rose/climlab/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.4)?
- [x] **Authorship:** Has the submitting author (@brian-rose) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/brian-rose/climlab/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.4)?
- [x] **Authorship:** Has the submitting author (@brian-rose) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @Chilipp, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00659/joss.00659/10.21105.joss.00659.pdf)

**Comment by lheagy** [comment]
Thanks @Chilipp and @dhhagan for being willing to review. The review issue is here, and there is a checklist above for each of you as you review the software. Please don't hesitate to reach out with questions!

**Comment by lheagy** [comment]
👋 Thanks @Chilipp and @dhhagan for being willing to review. There is a checklist above for each of you as you go through the review process. It works through general checks, installation, functionality and the quality of the paper. Please let me know if you have any questions or if I can be of assistance in the review process!

**Comment by Chilipp** [comment]
@lheagy  and @brian-rose: I apologize for the delay that is caused by the EGU. I expect to have it done at latest by Tuesday evening.

**Comment by brian-rose** [comment]
Thanks @Chilipp for the help with the references and the Python 3 update. I merged the PR.

Will add some community guidelines next.

**Comment by lheagy** [comment]
Thanks @Chilipp and @brian-rose!

**Comment by brian-rose** [comment]
The documentation now includes a new page (http://climlab.readthedocs.io/en/latest/contributing.html) with explicit guidelines for 
- reporting bugs and issues
- seeking help and support
- contributing bug fixes, new features, and documentation

There is also a [new open github issue](https://github.com/brian-rose/climlab/issues/68) where I'm inviting people to self-report their usage of CLIMLAB. I hope to collect references and links and make these available as additional resources for new users.

**Comment by Chilipp** [comment]
Thanks @brian-rose! That is fine with me. However, apparently you wrote the CONTRIBUTING in markdown, which doesn't render well in your docs. I'd recommend to fix this.

**Comment by brian-rose** [comment]
@Chilipp thanks for finding that. I fixed up the formatting of the new page and got rid of the errant bit of markdown.

**Comment by dhhagan** [comment]
Hey @brian-rose I suggested adding more clear instructions on running the tests, otherwise this paper is good to go!

**Comment by lheagy** [comment]
Thanks @dhhagan and @Chilipp for a speedy and thorough review! @brian-rose: please keep us updated on your progress on brian-rose/climlab#69 - we can proceed with publishing once addressed

**Comment by brian-rose** [comment]
As noted in https://github.com/brian-rose/climlab/issues/69, there is now a new section in the docs on [Building and Testing CLIMLAB](http://climlab.readthedocs.io/en/latest/contributing.html#building-and-testing-climlab) with explicit instructions.

**Comment by lheagy** [comment]
Thanks @brian-rose, @dhhagan, would you mind taking one last look and closing brian-rose/climlab#69 if it has been addressed?

**Comment by lheagy** [comment]
@arfon, this submission is ready to be published. Congratulations @brian-rose!  

Many thanks @Chilipp and @dhhagan for your work on this review!

**Comment by brian-rose** [comment]
Thanks all.

**Comment by arfon** [comment]
@brian-rose - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by brian-rose** [comment]
I just released climlab v0.6.5 including the updated documentation. It is archived on Zenodo under doi:10.5281/zenodo.1226360 ([direct link](https://zenodo.org/record/1226360#.Wto4sS_MxUM))

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1226360 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1226360" target="_blank">10.5281/zenodo.1226360</a> is the archive.

**Comment by arfon** [comment]
@Chilipp, @dhhagan - many thanks for your reviews here and to @lheagy for editing this submission ✨ 

@brian-rose - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00659 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00659/status.svg)](https://doi.org/10.21105/joss.00659)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00659/status.svg)](https://doi.org/10.21105/joss.00659)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by brian-rose** [comment]
Great news, thanks @arfon.
