### ISSUE TITLE
[PRE REVIEW]: MicroBenthos: a modeling framework for microbial benthic ecology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#665]
**Submitting author:** @achennu (<a href="http://orcid.org/0000-0002-0389-5589">Arjun Chennu</a>)
**Repository:** <a href="https://github.com/achennu/microbenthos" target ="_blank">https://github.com/achennu/microbenthos</a>
**Version:** v0.8.2
**Editor:** @lheagy
**Reviewers:** @leouieda

**Author instructions**

Thanks for submitting your paper to JOSS @achennu. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@achennu if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00665/joss.00665/10.21105.joss.00665.pdf)

**Comment by arfon** [comment]
👋 @lheagy - the submitting author suggested you as the handling editor.

**Comment by achennu** [comment]
@arfon Thanks for initiating the review. I just checked the proof. Noticed an error: There is a blank line in the bullet list of features.

@lheagy The software I submitted is useful in biogeochemistry. Based on your topical expertise and that simpeg relates to finite volume estimation, I figured you may be able to easily review my submission.

**Comment by lheagy** [comment]
@arfon, @achennu, I would be happy to edit this submission!

**Comment by achennu** [comment]
@lheagy Thanks for taking this on. I don't have other (specific) reviewers to suggest, but I suspect it would be directly within your reach. There is nothing critically specific to chemistry or biology to review. The software essentially is an interface for the user to create partial differential equations. Then these equations are solved, visualized in real time and saved. The benefit for a biogeochem user is that they can work at the abstractions of biomass, microbial group, etc.

There are tutorials in the source tree under `docs/tutorials`, each of which are runnable. While running with `--show-eqns`, the actual constructed PDE is shown. The `--plot` option visualizes the model domain as it happens. From a user perspective, one could try to edit the parameters in the definition file and confirm that these show up in the simulations.

If you could give this a try and let me know if you need more info, then I'd be happy to oblige.

**Comment by lheagy** [comment]
@leouieda has indicated that he is willing to help out with this submission. @leouieda: does it work with you if I put you down as the lead reviewer on this? I can jump in and help out as well.
