### ISSUE TITLE
[PRE REVIEW]: SuchTree : A Python library for fast, thread-safe computations on phylogenetic trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#666]
**Submitting author:** @ryneches (<a href="http://orcid.org/0000-0002-2055-8381">Russell Y. Neches</a>)
**Repository:** <a href="https://github.com/ryneches/SuchTree" target ="_blank">https://github.com/ryneches/SuchTree</a>
**Version:** 0.6
**Editor:** @karthik
**Reviewers:** @giraola

**Author instructions**

Thanks for submitting your paper to JOSS @ryneches. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ryneches if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00666/joss.00666/10.21105.joss.00666.pdf)

**Comment by arfon** [comment]
👋 @karthik - the submitting author suggested you as the handling editor.

**Comment by karthik** [comment]
@arfon thanks! Will make a quick determination if I'm able to handle this one and update the thread soon.

**Comment by ryneches** [comment]
Hey @karthik! Here are some suggested reviewers :
* @giraola (from the JOSS list of reviewers)
* @arvestad (or perhaps someone in his lab?)
* @trayc7 (or someone in her lab?)
* @snacktavish (or someone in her lab?)

**Comment by arvestad** [comment]
Never been included in reviewer discussions like this before. :-)

	L

**Comment by ryneches** [comment]
Hope you don't mind that I suggested you! I'm pretty sure our respective social and co-authorship graphs don't share any direct links.

**Comment by arvestad** [comment]
I don't mind at all. I am new to JOSS and am curious about its extreme openness.

**Comment by giraola** [comment]
Hi @karthik, I have some time to handle this if needed.

**Comment by karthik** [comment]
@giraola Thanks! I'll take you up on the offer.

**Comment by karthik** [comment]
@whedon assign @giraola as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @giraola

**Comment by karthik** [comment]
@whedon start review magic-word=bananas
