### ISSUE TITLE
[REVIEW]: ACTIN: A tool to calculate stellar activity indices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#667]
**Submitting author:** @gomesdasilva (<a href="http://orcid.org/0000-0001-8056-9202">João Gomes da Silva</a>)
**Repository:** <a href="https://github.com/gomesdasilva/ACTIN" target ="_blank">https://github.com/gomesdasilva/ACTIN</a>
**Version:** v1.2.2
**Editor:** @arfon
**Reviewer:** @RuthAngus
**Archive:** <a href="https://doi.org/10.5281/zenodo.1478610" target="_blank">10.5281/zenodo.1478610</a>

## Status

[![status](http://joss.theoj.org/papers/7557310eac6f40bb3fa22cdd13ab7cf7/status.svg)](http://joss.theoj.org/papers/7557310eac6f40bb3fa22cdd13ab7cf7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7557310eac6f40bb3fa22cdd13ab7cf7"><img src="http://joss.theoj.org/papers/7557310eac6f40bb3fa22cdd13ab7cf7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7557310eac6f40bb3fa22cdd13ab7cf7/status.svg)](http://joss.theoj.org/papers/7557310eac6f40bb3fa22cdd13ab7cf7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/gomesdasilva/ACTIN." target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@RuthAngus, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gomesdasilva/ACTIN.">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@gomesdasilva) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @RuthAngus it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #667 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:52:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00667/joss.00667/10.21105.joss.00667.pdf)

**Comment by arfon** [comment]
👋@RuthAngus - I just wanted to check in and see how you are getting on here?

**Comment by RuthAngus** [comment]
@arfon eeshk, sorry! I got slammed immediately after accepting this review. I'll try to get to this tomorrow.

**Comment by RuthAngus** [comment]
@arfon I submitted some issues for ACTIN almost a week ago but I am not sure whether the author has seen these. Should I try to get in touch with the author another way?

**Comment by RuthAngus** [comment]
Hi @gomezdasilva did you see the issues I raised on the ACTIN github page?

**Comment by RuthAngus** [comment]
Oops, sorry about that, @gomesdasilva!

**Comment by arfon** [comment]
How are we getting along here @gomesdasilva and @RuthAngus?

**Comment by gomesdasilva** [comment]
sorry @arfon and @RuthAngus, I am very busy at this time but will get back to this in the next couple of weeks

**Comment by arfon** [comment]
@gomesdasilva - any chance we can try and wrap this up in the next couple of weeks?

**Comment by RuthAngus** [comment]
Sorry -- I've been traveling solidly for the last month. Getting to it now!

**Comment by arfon** [comment]
Hi @gomesdasilva - when do you think you will be able to revisit this?

**Comment by gomesdasilva** [comment]
Hi Arfon,

I will update it next week for sure.

Regards,
João

**Comment by arfon** [comment]
Excellent, thanks @gomesdasilva

**Comment by arfon** [comment]
Friendly reminder to get to this soon @gomesdasilva.

**Comment by arfon** [comment]
> Letting you know, @arfon is currently OOO until Monday, October 29th 2018. ❤️

It's a lie. I'm here :-)

> Hi @arfon and @gomesdasilva I think this code has met all the criteria and is ready to be accepted! How should I proceed?

Great, thanks @RuthAngus!

@gomesdasilva - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by arfon** [comment]
> @gomesdasilva - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

Friendly reminder to make an archive of the software sometime soon @gomesdasilva. You can read how to do that here: https://guides.github.com/activities/citable-code/

**Comment by gomesdasilva** [comment]
Hi Arfon,

I uploaded the software to Zenodo, DOI: 10.5281/zenodo.1478610.

Regards,
João

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1478610 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1478610" target="_blank">10.5281/zenodo.1478610</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/54

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/54, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/55

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/55, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/56
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00667](https://doi.org/10.21105/joss.00667)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@RuthAngus - many thanks for your review here ✨ 

@gomesdasilva - your paper is now accepted into JOSS :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00667/status.svg)](https://doi.org/10.21105/joss.00667)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00667">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00667/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00667/status.svg
   :target: https://doi.org/10.21105/joss.00667
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00667/status.svg)](https://doi.org/10.21105/joss.00667)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by gomesdasilva** [comment]
Thank you Arfon and Ruth!

Just one last thing, is it possible to change the name from “Da Silva et al.” to "Gomes da Silva et al.”?
The last one is the one I use in my publications.

Cheers,
João

**Comment by arfon** [comment]
> Just one last thing, is it possible to change the name from “Da Silva et al.” to "Gomes da Silva et al.”?
The last one is the one I use in my publications.

Sure thing. I've updated this now. The online PDF might take a few hours to update.

**Comment by gomesdasilva** [comment]
Thank you very much

Cheers,
João
