### ISSUE TITLE
[REVIEW]: MatchPy: Pattern Matching in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#670]
**Submitting author:** @henrik227 (<a href="http://orcid.org/0000-0001-6744-3605">Henrik Barthels</a>)
**Repository:** <a href="https://github.com/HPAC/matchpy" target ="_blank">https://github.com/HPAC/matchpy</a>
**Version:** v0.4.5
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @llllllllll
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1294930" target="_blank">10.5281/zenodo.1294930</a>

## Status

[![status](http://joss.theoj.org/papers/e456bc05880b533652980aee6550a3cb/status.svg)](http://joss.theoj.org/papers/e456bc05880b533652980aee6550a3cb)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e456bc05880b533652980aee6550a3cb"><img src="http://joss.theoj.org/papers/e456bc05880b533652980aee6550a3cb/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e456bc05880b533652980aee6550a3cb/status.svg)](http://joss.theoj.org/papers/e456bc05880b533652980aee6550a3cb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/HPAC/matchpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@llllllllll, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HPAC/matchpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.4)?
- [x] **Authorship:** Has the submitting author (@henrik227) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @llllllllll it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00670/joss.00670/10.21105.joss.00670.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@henrik227 @llllllllll this is where the review will take place. Let me know if you have any questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@llllllllll thanks again for being a reviewer for this submission. I believe that over at https://github.com/openjournals/joss-reviews/issues/572 you indicated you could start the review mid-May. Do you think you are ready to pick this up? Let me know how you are getting on. Thanks! :rocket:

**Comment by Kevin-Mattheus-Moerman** [comment]
@llllllllll are you still able to help with the review process? Thanks

**Comment by llllllllll** [comment]
Sorry about that, thanks for the remindrs though. I can begin reviewing this week.

**Comment by llllllllll** [comment]
The statement of need in the documentation could be more clear: https://github.com/HPAC/matchpy/issues/32. This should be a very small documentation change.

I only see a DOI for the sympy paper reference, I am not sure how these get assigned so this may be the only citation that has one. I am leaving this unchecked for now because of this.

After these two things are addressed this meets all of the criteria.

**Comment by Kevin-Mattheus-Moerman** [comment]
@henrik227 can you respond to @llllllllll 's comments? @llllllllll thanks for your review work so far! :rocket:

**Comment by henrik227** [comment]
I was about to look into this. Thanks for the comments, @llllllllll !

**Comment by henrik227** [comment]
I improved the statement of need and added DOIs for all references that have one (at least to my knowledge).

**Comment by llllllllll** [comment]
Awesome, those changes look good.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00670/joss.00670/10.21105.joss.00670.pdf)

**Comment by henrik227** [comment]
What happens next, now that the checklist is complete?

**Comment by Kevin-Mattheus-Moerman** [comment]
@llllllllll can you confirm we are all good to accept this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@henrik227, once @llllllllll confirms, could you create a DOI for an archived version of the reviewed software, and list it here? You can use a service like [Zenodo](http://zenodo.org/) to do this (see also [here](https://guides.github.com/activities/citable-code/)).

**Comment by llllllllll** [comment]
I confirm that this meets all of criteria for a submission.

I would also like to say that this is a very interesting and useful project. I'm glad I was able to learn more about this while reviewing.

**Comment by henrik227** [comment]
Is it ok to create a new MatchPy release (0.4.5), so I can make use of Zenodo automatically archiving releases? And if yes, do I also change that in the metadata of the paper?

**Comment by Kevin-Mattheus-Moerman** [comment]
Yes you can, so go ahead and create the new release and list the DOI for it here. @arfon can then help update the version number listed here and the metadata for the paper.

**Comment by henrik227** [comment]
The DOI of Version v0.4.5 is "10.5281/zenodo.1294930"

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon can you set the version to 0.4.5, assign [10.5281/zenodo.1294930](https://zenodo.org/record/1294930) as the DOI, and proceed to accept this submission? Thanks :rocket: :rabbit: :camel: :tulip:

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1294930 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1294930" target="_blank">10.5281/zenodo.1294930</a> is the archive.

**Comment by arfon** [comment]
@llllllllll - many thanks for your review here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@henrik227 - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00670 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00670/status.svg)](https://doi.org/10.21105/joss.00670)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00670/status.svg)](https://doi.org/10.21105/joss.00670)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
