### ISSUE TITLE
[PRE REVIEW]: OPEM (Open Source PEM Fuel Cell Simulation Tool)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#672]
**Submitting author:** @sepandhaghighi (<a href="http://orcid.org/0000-0001-9450-2375">Sepand Haghighi</a>)
**Repository:** <a href="https://github.com/ECSIM/opem" target ="_blank">https://github.com/ECSIM/opem</a>
**Version:** v0.8
**Editor:** @katyhuff
**Reviewers:** @nnadeau

**Author instructions**

Thanks for submitting your paper to JOSS @sepandhaghighi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sepandhaghighi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00672/joss.00672/10.21105.joss.00672.pdf)

**Comment by arfon** [comment]
👋@danielskatz - the submitting author suggested you as the handling editor.

**Comment by danielskatz** [comment]
sure - I have a lot of spare time now :)
But more seriously, while I can do this, is there another editor more in engineering who would be interested?

**Comment by danielskatz** [comment]
@arfon  - If I had not been suggested, who would you have asked to edit this?

**Comment by arfon** [comment]
@kyleniemeyer is probably a better choice.

**Comment by danielskatz** [comment]
👋 @kyleniemeyer  - can you take this one?

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00672/joss.00672/10.21105.joss.00672.pdf)

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00672/joss.00672/10.21105.joss.00672.pdf)

**Comment by danielskatz** [comment]
👋 @kyleniemeyer - still hoping I can transfer this to you...

**Comment by kyleniemeyer** [comment]
@danielskatz Practically I don't think I'd be able to handle this within the next week. @katyhuff are you available right now?

**Comment by katyhuff** [comment]
I'm swamped this week, too, but this does look like a strong submission and hopefully will be fairly straightforward. I can take it.

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@nnadeau - It seems to me you would be an excellent reviewer for this submission. Are you willing to be assigned this submission?

**Comment by kyleniemeyer** [comment]
Thank you @katyhuff!

**Comment by danielskatz** [comment]
Thanks from me too!

**Comment by nnadeau** [comment]
@katyhuff Yes, I'm good to review :)

**Comment by katyhuff** [comment]
Great news! Thanks @nnadeau .

**Comment by katyhuff** [comment]
@whedon assign @nnadeau as reviewer.

**Comment by whedon** [comment]
OK, the reviewer is @nnadeau

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/676. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Thanks folks. @nnadeau and @sepandhaghighi , please let's head over to #676 for the review itself.
