### ISSUE TITLE
[PRE REVIEW]: OctApps: a library of Octave functions for continuous gravitational-wave data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#673]
**Submitting author:** @kwwette (<a href="http://orcid.org/0000-0002-4394-7179">Karl Wette</a>)
**Repository:** <a href="https://github.com/octapps/octapps" target ="_blank">https://github.com/octapps/octapps</a>
**Version:** v0.1
**Editor:** @danielskatz
**Reviewers:** @stevenrbrandt

**Author instructions**

Thanks for submitting your paper to JOSS @kwwette. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kwwette if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00673/joss.00673/10.21105.joss.00673.pdf)

**Comment by arfon** [comment]
:wave: @kwwette, many thanks for your submission to JOSS. Do you have any suggestions for potential reviewers for your submission?

**Comment by kwwette** [comment]
@arfon Thanks!

Re. potential reviewers: from the list I'd suggest perhaps @fgnievinski, @Scivision, or @jordigh for their Octave expertise. Unfortunately I don't have any off-list reviewers to suggest: in the field of gravitational wave astronomy/astrophysics we are all part of large collaborations and publish papers with 1000+ authors, so I'm a co-author with pretty much everyone who might have scientific expertise in the field.

**Comment by kwwette** [comment]
Also re. the article proof: looks good, there are a few minor issues with the formatting of citations and references, should I be trying to correct those now? I'm also not sure whether there should be a **References** header between the acknowledgements and the bibliography.

**Comment by kwwette** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by kwwette** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00673/joss.00673/10.21105.joss.00673.pdf)

**Comment by kwwette** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00673/joss.00673/10.21105.joss.00673.pdf)

**Comment by kwwette** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00673/joss.00673/10.21105.joss.00673.pdf)

**Comment by kwwette** [comment]
FYI I've fixed up the citations and references formatting and added a **References** header.

**Comment by arfon** [comment]
:wave: @mzevin1 would you be willing to review this submission for JOSS?

**Comment by mzevin1** [comment]
Hi @arfon, I'm a member of LIGO as well (and not too versed in continuous waves science), so I may not be best suited for review.

**Comment by arfon** [comment]
> Unfortunately I don't have any off-list reviewers to suggest: in the field of gravitational wave astronomy/astrophysics we are all part of large collaborations and publish papers with 1000+ authors, so I'm a co-author with pretty much everyone who might have scientific expertise in the field.

Thanks @kwwette. I'm curious how other journals manage to review gravitational wave related papers...? 

@fgnievinski, @scivision, @jordigh - would you be willing to review this submission for JOSS? We'd only be asking you to review the software aspects of this (and not the gravitational wave physics!)

**Comment by arfon** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @stevenrbrandt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stevenrbrandt

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/707. Feel free to close this issue now!
