### ISSUE TITLE
[REVIEW]: MicroBenthos: a modeling framework for microbial benthic ecology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#674]
**Submitting author:** @achennu (<a href="http://orcid.org/0000-0002-0389-5589">Arjun Chennu</a>)
**Repository:** <a href="https://github.com/achennu/microbenthos" target ="_blank">https://github.com/achennu/microbenthos</a>
**Version:** v0.9
**Editor:** @lheagy
**Reviewer:** @leouieda
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1240940" target="_blank">10.5281/zenodo.1240940</a>

## Status

[![status](http://joss.theoj.org/papers/5daae2e14258034d77cb694370cbae23/status.svg)](http://joss.theoj.org/papers/5daae2e14258034d77cb694370cbae23)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5daae2e14258034d77cb694370cbae23"><img src="http://joss.theoj.org/papers/5daae2e14258034d77cb694370cbae23/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5daae2e14258034d77cb694370cbae23/status.svg)](http://joss.theoj.org/papers/5daae2e14258034d77cb694370cbae23)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/achennu/microbenthos" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@leouieda, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/achennu/microbenthos">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8.2)?
- [x] **Authorship:** Has the submitting author (@achennu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00674/joss.00674/10.21105.joss.00674.pdf)

**Comment by lheagy** [comment]
👋 Hi @leouieda, here is the review issue. I will jump in on this one and add comments as well, but I will leave the check-list up to you. Please let me know if you have any questions!

**Comment by leouieda** [comment]
@lheagy OK, will do :+1:

**Comment by achennu** [comment]
Thanks @leouieda 

I have been rerunning the software on some previous model definition files. Found some bugs in the user's CLI interface due to a refactor. I've starting adding commits to the `develop` branch with these minor fixes.

@lheagy Can you clarify about this checkbox?
 Version: Does the release version given match the GitHub release (v0.8.2)?

That version is no longer actual (0.9). I intend that the final version after the review should somehow be referenced?

**Comment by achennu** [comment]
Just realized the version number may be a non-issue, since a designated version needs to be put on an archival site after review.

**Comment by lheagy** [comment]
@achennu, I can update the version referenced in the github issue. And correct, it will also be included on the archival site

**Comment by achennu** [comment]
@lheagy @leouieda 
Thanks for your inputs on the repo. I've made the changes you've indicated thus far. Travis builds are passing. Once you indicate that the JOSS review is through, I'll bump version, release and create an archive on zenodo.

**Comment by leouieda** [comment]
@achennu @lheagy I'll get to this week. Sorry for the delay @achennu.

**Comment by achennu** [comment]
@leouieda Thanks for the update. Do let me know if you need any info.

**Comment by lheagy** [comment]
Thanks @leouieda! In your opinion, should these issues be addressed before the paper is published?

**Comment by leouieda** [comment]
@lheagy maybe just achennu/microbenthos#6 but that's just a single word

**Comment by achennu** [comment]
Thanks @leouieda ! I'm glad you enjoyed it.

The ``export model`` command is used to validate an input file by the user. That command writes out the validated YAML string to stdout, which can of course be piped to a file for further use.

HDF5 is a widely used standard format for storing scientific data. It contains many useful features: it is self-documenting, supports structured metadata, can be resized, etc. The specifications for it are codified by the HDF group. I use the vanilla h5py library to read and write to this format, but there are other libraries that build on it like pytables. There are of course readers in matlab, R, C++, etc. In fact, there is the java based GUI called ``hdfview`` to inspect it, though I'm partial to `vitables` written in python. With these, one can double click the file, inspects the hierarchy, the nodes, the metadata attached, etc. For microbenthos, the HDF5 format serves as a good archival output target. It is not tied down to the microbenthos software, or even python for that matter. The produced data can be consumed in whatever way serves the user's needs best: export to video, export to frames, open as interactive visualization, or read and analyze in their tool of choice.

I hope this satisfies all your concerns. Thanks for taking the time and giving useful feedback.

**Comment by leouieda** [comment]
@achennu OK, thanks for the clarification! 

@lheagy I don't have any more comments. I think this is good to go :rocket:

**Comment by lheagy** [comment]
Thanks @leouieda for your review! 

@achennu, could you please archive your software (eg. on [zenodo](https://zenodo.org/) or similar) and post the doi here?

**Comment by achennu** [comment]
Thank you @leouieda !

@lheagy I have created an archive on zenodo: http://doi.org/10.5281/zenodo.1240940

**Comment by arfon** [comment]
@leouieda - many thanks for your review here and to @lheagy for editing this submission ✨ 

@achennu - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00674 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00674/status.svg)](https://doi.org/10.21105/joss.00674)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00674/status.svg)](https://doi.org/10.21105/joss.00674)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
