### ISSUE TITLE
[PRE REVIEW]: chronovise: Measurement-Based Probabilistic Timing Analysis framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#675]
**Submitting author:** @federeghe (<a href="http://orcid.org/0000-0002-1888-9579">FEDERICO REGHENZANI</a>)
**Repository:** <a href="https://github.com/federeghe/chronovise" target ="_blank">https://github.com/federeghe/chronovise</a>
**Version:** v1.0
**Editor:** @danielskatz
**Reviewers:** @lkosmid

**Author instructions**

Thanks for submitting your paper to JOSS @federeghe. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@federeghe if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00675/joss.00675/10.21105.joss.00675.pdf)

**Comment by danielskatz** [comment]
I can take this one

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@federeghe - please suggest potential reviewers. [This list of people](https://bit.ly/joss-reviewers) who have already agreed to review for JOSS may be candidates.

**Comment by federeghe** [comment]
Thank you, maybe @fritzo or @jordigh? According to the list, they are experts in C++ and statistics, not on real-time systems but it may be sufficient for the review.

**Comment by danielskatz** [comment]
@fritzo and @jordigh - would either or both of you be willing to review this submission?

**Comment by fritzo** [comment]
@danielskatz sorry I can't handle any additional reviews at the moment

**Comment by danielskatz** [comment]
FYI, I'm currently trying to find reviewers by email

**Comment by danielskatz** [comment]
@whedon assign @lkosmid as editor

**Comment by whedon** [comment]
OK, the editor is @lkosmid

**Comment by danielskatz** [comment]
@whedon assign @lkosmid as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lkosmid

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/711. Feel free to close this issue now!
