### ISSUE TITLE
[PRE REVIEW]: KLRfome - Kernel Logistic Regression on Focal Mean Embeddings

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#677]
**Submitting author:** @mrecos (<a href="http://orcid.org/0000-0002-4627-7692">Matthew Harris</a>)
**Repository:** <a href="https://github.com/mrecos/klrfome" target ="_blank">https://github.com/mrecos/klrfome</a>
**Version:** v2.1.0
**Editor:** @leeper
**Reviewers:** @benmarwick

**Author instructions**

Thanks for submitting your paper to JOSS @mrecos. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mrecos if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #677 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00677/joss.00677/10.21105.joss.00677.pdf)

**Comment by mrecos** [comment]
Hello. Thanks for the Pre-review! From the reviewer list I would suggest: @benmarwick , @jsta , and @nuest  or others with experience in archaeology, machine learning, or R and spatial analysis.
PS - I can certainly add more details to the paper.md if desired.
Thank you all for your efforts.

**Comment by arfon** [comment]
> PS - I can certainly add more details to the paper.md if desired.

Thanks @mrecos - yes, please try and flesh the paper out in a little more detail following the guidelines from the main JOSS site:

> - A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
> - A clear statement of need that illustrates the purpose of the software
> - A list of key references including a link to the software archive
> - Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it

**Comment by arfon** [comment]
@benmarwick - would you be willing to review this submission for JOSS?

**Comment by mrecos** [comment]
Thank you @arfon. I added a bit more detail to the paper. Please let me know if you have other suggested edits prior to review.

**Comment by benmarwick** [comment]
Yes, no worries, happy to review.

**Comment by leeper** [comment]
@arfon would you like me to handle as editor?

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by leeper** [comment]
@whdon assign @leeper as editor

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon assign @benmarwick as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @benmarwick

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/722. Feel free to close this issue now!

**Comment by leeper** [comment]
@benmarwick Thanks for agreeing to review!! The review issue is now open at #722.
