### ISSUE TITLE
[REVIEW]: SuchTree : A Python library for fast, thread-safe computations on phylogenetic trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#678]
**Submitting author:** @ryneches (<a href="http://orcid.org/0000-0002-2055-8381">Russell Y. Neches</a>)
**Repository:** <a href="https://github.com/ryneches/SuchTree" target ="_blank">https://github.com/ryneches/SuchTree</a>
**Version:** 0.6
**Editor:** @karthik
**Reviewer:** @giraola
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1294297" target="_blank">10.5281/zenodo.1294297</a>

## Status

[![status](http://joss.theoj.org/papers/23bac1ae69cfaf201203dd52d7dd5610/status.svg)](http://joss.theoj.org/papers/23bac1ae69cfaf201203dd52d7dd5610)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/23bac1ae69cfaf201203dd52d7dd5610"><img src="http://joss.theoj.org/papers/23bac1ae69cfaf201203dd52d7dd5610/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/23bac1ae69cfaf201203dd52d7dd5610/status.svg)](http://joss.theoj.org/papers/23bac1ae69cfaf201203dd52d7dd5610)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ryneches/SuchTree" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@giraola, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ryneches/SuchTree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.6)?
- [x] **Authorship:** Has the submitting author (@ryneches) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00678/joss.00678/10.21105.joss.00678.pdf)

**Comment by ryneches** [comment]
Article proof looks good to me.

**Comment by giraola** [comment]
@ryneches please add DOIs to all references listed in the manuscript.

**Comment by ryneches** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00678/joss.00678/10.21105.joss.00678.pdf)

**Comment by ryneches** [comment]
Hmm. I'm not happy with the way the references are getting formatted. Multiple references look weird, and BibTeX is doing that thing where it turns repeated author lists into a long dash. :-/

Is there a formatting guide? I'm not so familiar with the MarkDown to LaTeX way of doing things.

**Comment by arfon** [comment]
> Hmm. I'm not happy with the way the references are getting formatted. Multiple references look weird, and BibTeX is doing that thing where it turns repeated author lists into a long dash. :-/

This is the standard style for our bibliography - it's because the author list of the second paper is the same as the one above it.

**Comment by ryneches** [comment]
Ah, OK. I've always thought looks weird.

**Comment by ryneches** [comment]
What's next?

**Comment by arfon** [comment]
> What's next?

I think we're waiting for @giraola to finish their review?

**Comment by giraola** [comment]
Hi @arfon @ryneches, sorry for the delay, I will complete it within the following two of days...

**Comment by giraola** [comment]
@ryneches please add installation guidelines and list SuchTree dependencies in the readme file.

**Comment by ryneches** [comment]
Added. 5d6ad02df29ebe4fa2c6a0652335f87b0c311e7b 4a639b16f7b9fd63809320e3e5dfc09e63cbde55

**Comment by ryneches** [comment]
Anything else?

**Comment by giraola** [comment]
@ryneches I just completed the revision. Sorry for this delay.

**Comment by arfon** [comment]
@karthik - I think this paper is good to accept?

**Comment by karthik** [comment]
@arfon Yes, definitely. I communicated with Russel before I left for my trip and am just returning to editorial duties. Will finish this up asap.

**Comment by karthik** [comment]
@ryneches So sorry for the delay. This is good to go and thanks for your patience! 
🙏

Now, can you deposit the software on Zenodo and post a DOI here so we can complete the final steps towards acceptance?

**Comment by ryneches** [comment]
All right! After a little tidying up, here's the Zenodo DOI :

https://doi.org/10.5281/zenodo.1294297

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.1294297 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1294297" target="_blank">10.5281/zenodo.1294297</a> is the archive.

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00678/joss.00678/10.21105.joss.00678.pdf)

**Comment by karthik** [comment]
@ryneches Congrats on your paper being accepted! 🎉
@arfon will do a couple more steps to finalize your paper.

**Comment by arfon** [comment]
@ryneches - I made a small fix to one of your bibtex entries which wasn't working in https://github.com/ryneches/SuchTree/pull/14

@giraola - many thanks for your review here and to @karthik for editing this submission ✨ 

@ryneches - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00678 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00678/status.svg)](https://doi.org/10.21105/joss.00678)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00678/status.svg)](https://doi.org/10.21105/joss.00678)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
