### ISSUE TITLE
[PRE REVIEW]: malan: MAle Lineage ANlysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#679]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/mikldk/malan" target ="_blank">https://github.com/mikldk/malan</a>
**Version:** v0.0.3
**Editor:** @brainstorm
**Reviewers:** @afrubin

**Author instructions**

Thanks for submitting your paper to JOSS @mikldk. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mikldk if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by mikldk** [comment]
Based on reviewer list: Maybe @ajank, @afrubin or @conradstack?

**Comment by mikldk** [comment]
I see that the footer in the pdf article proof contains the Markdown markup (the stars for making some letters boldface). I am not sure how to fix this -- is there an option to provide a clear text title without markup?

**Comment by arfon** [comment]
> I see that the footer in the pdf article proof contains the Markdown markup (the stars for making some letters boldface). I am not sure how to fix this -- is there an option to provide a clear text title without markup?

Yeah, sorry about this. We only have limited support for custom typesetting. The only suggestion I have for this is to remove the custom formatting from the title (I realize this isn't ideal).

**Comment by mikldk** [comment]
@arfon, I guess it would make sense to look into making this possible?

By the look of it, it would require changes to:

[openjournals/whedon/lib/whedon/processor.rb#L101](https://github.com/openjournals/whedon/blob/6d7d3729232081e24ef1f1d03b9203f12ce8771f/lib/whedon/processor.rb#L101)
and
[openjournals/whedon/resources/latex.template#L64](https://github.com/openjournals/whedon/blob/6d7d3729232081e24ef1f1d03b9203f12ce8771f/resources/latex.template#L64)

One way is to add an additional `title_footer` YAML field, but I guess that would have impact many places. The easy fix is to "just" strip the title for Markdown synxtax related to italic/bold. Maybe simply with regex with pairs of `**`/`*`/`__`/`_` like (not tested)

```ruby
gsub(/\*\*(.+?)\*\*/,'\1')
gsub(/\*(.+?)\*/,'\1')
gsub(/__(.+?)__/,'\1')
gsub(/_(.+?)_/,'\1')
```
Or maybe using a proper function like <http://www.rubydoc.info/github/vmg/redcarpet/Redcarpet/Render/StripDown>. 
And then in the footer in the LaTeX template have a, `$paper_title_footer$`, say.

Or: If I'm the only one making troubles, I change my title :-).

**Comment by afrubin** [comment]
@mikldk @brainstorm I'm happy to review this paper.

**Comment by arfon** [comment]
> @arfon, I guess it would make sense to look into making this possible?

Thanks for digging into this @mikldk - I agree this is how it _could_ work, I'm just not sure this is a direction we want to go in. JOSS is deliberately lightweight in terms of tooling and that extends to how sophisticated we can be with our typesetting.

I suggest you leave your `paper.md` _as is_ and if you remind me when we're accepting the publication I can manually fix this for you when I'm processing the paper.

**Comment by brainstorm** [comment]
@whedon assign @afrubin as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @afrubin

**Comment by brainstorm** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/684. Feel free to close this issue now!

**Comment by ajank** [comment]
@brainstorm, if you needed another opinion, I'm happy to review this paper as well.

@arfon, it might be a good general practice to have each paper reviewed by at least two reviewers if possible. This would allow for more scrutiny, without delaying the process too much.

**Comment by arfon** [comment]
> @arfon, it might be a good general practice to have each paper reviewed by at least two reviewers if possible. This would allow for more scrutiny, without delaying the process too much.

Yes, we do this regularly but leave this up to the discretion of the editor (@brainstorm in this case).

**Comment by brainstorm** [comment]
Yes please, be my guest! ;)

>

**Comment by arfon** [comment]
> Yes please, be my guest! ;)

@ajank - I've added you to the review in #684
