### ISSUE TITLE
[PRE REVIEW]: ParticleScattering: Solving and optimizing multiple-scattering problems in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#680]
**Submitting author:** @bblankrot (<a href="http://orcid.org/0000-0003-3364-9298">Boaz Blankrot</a>)
**Repository:** <a href="https://github.com/bblankrot/ParticleScattering.jl" target ="_blank">https://github.com/bblankrot/ParticleScattering.jl</a>
**Version:** v0.0.2
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @ziotom78, @ysimillides

**Author instructions**

Thanks for submitting your paper to JOSS @bblankrot. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bblankrot if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by bblankrot** [comment]
Thanks, proof looks good overall.

From the list of reviewers, I suggest any of the following:
- ChrisRackauckas
- ysimillides
- ziotom78
- lheagy

**Comment by ziotom78** [comment]
Hi, I would be happy to review it!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @ziotom78 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ziotom78

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @ysimillides as reviewer

**Comment by whedon** [comment]
OK, @ysimillides is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/691. Feel free to close this issue now!
