### ISSUE TITLE
[PRE REVIEW]: BeeNestABM: An open-source agent-based model of spatiotemporal distribution of bumblebees in nests

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#681]
**Submitting author:** @ashleefv (<a href="http://orcid.org/0000-0001-9059-5703">Ashlee N. Ford Versypt</a>)
**Repository:** <a href="https://github.com/ashleefv/BeeNestABM" target ="_blank">https://github.com/ashleefv/BeeNestABM</a>
**Version:** 1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @sdelandtsheer

**Author instructions**

Thanks for submitting your paper to JOSS @ashleefv. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ashleefv if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00681/joss.00681/10.21105.joss.00681.pdf)

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00681/joss.00681/10.21105.joss.00681.pdf)

**Comment by ashleefv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00681/joss.00681/10.21105.joss.00681.pdf)

**Comment by sdelandtsheer** [comment]
@ashleefv I agree to review this article

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @ashleefv as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ashleefv

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @sdelandtsheer as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sdelandtsheer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @ashleefv as reviewer

**Comment by whedon** [comment]
OK, @ashleefv is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@pboesu @giskid are you able to review this submission for [JOSS](http://joss.theoj.org/about)? 

[--> Software repository :floppy_disk: : <--](https://github.com/ashleefv/BeeNestABM)   

[--> Article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00681/joss.00681/10.21105.joss.00681.pdf)

**Comment by GISKid** [comment]
I cannot, although looks interesting!

**Comment by Kevin-Mattheus-Moerman** [comment]
We'll start the review process to avoid delays.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/718. Feel free to close this issue now!
