### ISSUE TITLE
[PRE REVIEW]: sumo: Command-line tools for plotting and analysis of ab initio calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#682]
**Submitting author:** @utf (<a href="http://orcid.org/0000-0002-4486-3321">Alex Ganose</a>)
**Repository:** <a href="https://github.com/SMTG-UCL/sumo" target ="_blank">https://github.com/SMTG-UCL/sumo</a>
**Version:** v1.0.4
**Editor:** @kyleniemeyer
**Reviewers:** @jarvist, @cfgoldsmith

**Author instructions**

Thanks for submitting your paper to JOSS @utf. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@utf if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by utf** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by utf** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00682/joss.00682/10.21105.joss.00682.pdf)

**Comment by utf** [comment]
As for potential reviewers, the following people are well respected in the field and are familiar with the requirements of modern open-source projects:

@jarvist
@aronwalsh 
@bjmorgan 
@keeto
@rgraucrespo
@hautierg

**Comment by arfon** [comment]
@kyleniemeyer - would you be willing to edit this submission for JOSS?

**Comment by utf** [comment]
Hi @arfon,

As @kyleniemeyer doesn't seem to be available, I wonder if @katyhuff might also be appropriate as a reviewer.

**Comment by kyleniemeyer** [comment]
@arfon sure, I can take this one

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by jarvist** [comment]
I'm happy to help! Though in the interest of full disclosure I know the two primary authors.

**Comment by kyleniemeyer** [comment]
@jarvist great! I was actually about to email you, so thanks for volunteering. Knowing the authors is fine, as long as you don't have a formal conflict of interest based on our policy: https://github.com/openjournals/joss/blob/master/COI.md

**Comment by kyleniemeyer** [comment]
@whedon add @jarvist as reviewer

**Comment by whedon** [comment]
OK, @jarvist is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @cfgoldsmith as reviewer

**Comment by whedon** [comment]
OK, @cfgoldsmith is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/717. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
ok @utf @jarvist @cfgoldsmith we will hold the actual review over in #717
