### ISSUE TITLE
[PRE REVIEW]: Sentiment Analysis of Twitter Data (SAoTD)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#683]
**Submitting author:** @evan-l-munson (<a href="http://orcid.org/0000-0002-9958-6800">Evan Munson</a>)
**Repository:** <a href="https://github.com/evan-l-munson/SAoTD" target ="_blank">https://github.com/evan-l-munson/SAoTD</a>
**Version:** 0.1.0
**Editor:** @leeper
**Reviewers:** @kbenoit

**Author instructions**

Thanks for submitting your paper to JOSS @evan-l-munson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@evan-l-munson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
Hi @evan-l-munson - please review our [submission guidelines](https://joss.theoj.org/about#author_guidelines) and prepare a paper to accompany this submission.

Any questions, don't hesitate to ask.

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00683/joss.00683/10.21105.joss.00683.pdf)

**Comment by leeper** [comment]
@kbenoit Would you be willing to review this submission for JOSS?

**Comment by kbenoit** [comment]
Sure

**Comment by leeper** [comment]
@whedon add @kbenoit as reviewer

**Comment by whedon** [comment]
OK, @kbenoit is now a reviewer

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/764. Feel free to close this issue now!

**Comment by leeper** [comment]
@kbenoit Excellent. Thanks! The review ticket is open:  #764
