### ISSUE TITLE
[PRE REVIEW]: Apple Health Data Extractor

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#685]
**Submitting author:** @drjmm84 (<a href="http://orcid.org/0000-0002-8098-0170">Joseph M. Mahoney</a>)
**Repository:** <a href="https://github.com/drjmm84/applehealthdata" target ="_blank">https://github.com/drjmm84/applehealthdata</a>
**Version:** 1.0.3
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @drjmm84. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@drjmm84 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00685/joss.00685/10.21105.joss.00685.pdf)

**Comment by hooman650** [comment]
@hooman650 , I can review this paper.

**Comment by trallard** [comment]
Ah @hooman650 bet me to it 🙂 of you need a second pair of eyes I'd be happy to do it

**Comment by hooman650** [comment]
@trallard that would be great to have another reviewer, thank you. I guess, we need to wait till an editor is assigned for this submission...

**Comment by drjmm84** [comment]
Thank you for both volunteering. I have not seen reviewers (including myself) respond as quickly and positively to reviewing before.

I think that I recommended either @Kevin-Mattheus-Moerman or @mgymrek as the editor for this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @drjmm84 thanks for your submission. After review the editorial board has determined that your submission does not meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, this submission falls under the 'Minor utility package' category. 

Apologies that you did not receive a reply to your [pre-submission inquiry](https://github.com/openjournals/joss/issues/396). Although your submission does look useful, and reviewers appeared interested, it does not meet our requirements. 

Please don't hesitate to reach out for further clarification on the submission requirements. 

I hope you consider our platform in the future for publishing more extensive research software.
