### ISSUE TITLE
[PRE REVIEW]: dustmaps: A Python interface for maps of interstellar dust

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#687]
**Submitting author:** @gregreen (<a href="http://orcid.org/0000-0001-5417-2260">Gregory Green</a>)
**Repository:** <a href="https://github.com/gregreen/dustmaps" target ="_blank">https://github.com/gregreen/dustmaps</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewers:** @jegpeek

**Author instructions**

Thanks for submitting your paper to JOSS @gregreen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gregreen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #687 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@gregreen - please merge this PR to fix your paper metadata https://github.com/gregreen/dustmaps/pull/10

**Comment by arfon** [comment]
:wave: @jegpeek - would you be willing to review this submission for JOSS?

**Comment by jegpeek** [comment]
I'm sorry @arfon I've though about this long and hard and I've decided I only review for Elsevier journals.

Just kidding, bring it on.

**Comment by arfon** [comment]
> I'm sorry @arfon I've though about this long and hard and I've decided I only review for Elsevier journals.

🤣very nice @jegpeek.

**Comment by whedon** [comment]
OK, the reviewer is @jegpeek

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/695. Feel free to close this issue now!

**Comment by arfon** [comment]
@jegpeek - please head over to #695 to carry out the actual review.
