### ISSUE TITLE
[PRE REVIEW]: qualtRics: retrieve survey data using the Qualtrics API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#688]
**Submitting author:** @JasperHG90 (<a href="http://orcid.org/0000-0002-5019-2923">Jasper Ginn</a>)
**Repository:** <a href="https://github.com/ropensci/qualtRics" target ="_blank">https://github.com/ropensci/qualtRics</a>
**Version:** v3.0
**Editor:** @karthik
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @JasperHG90. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@JasperHG90 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @karthik - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00688/joss.00688/10.21105.joss.00688.pdf)

**Comment by karthik** [comment]
@arfon This has already been reviewed and accepted at rOpenSci.

Review thread: https://github.com/ropensci/onboarding/issues/192

**Comment by arfon** [comment]
> @arfon This has already been reviewed and accepted at rOpenSci.

Got it. Thanks!

**Comment by arfon** [comment]
@whedon set @arfon as reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/690. Feel free to close this issue now!
