### ISSUE TITLE
[PRE REVIEW]: GeoStats.jl - High-performance geostatistics in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#689]
**Submitting author:** @juliohm (<a href="http://orcid.org/0000-0003-2789-297X">Júlio Hoffimann</a>)
**Repository:** <a href="https://github.com/juliohm/GeoStats.jl" target ="_blank">https://github.com/juliohm/GeoStats.jl</a>
**Version:** v0.6.0
**Editor:** @lheagy
**Reviewers:** @wkearn, @ziotom78

**Author instructions**

Thanks for submitting your paper to JOSS @juliohm. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@juliohm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00689/joss.00689/10.21105.joss.00689.pdf)

**Comment by arfon** [comment]
:wave: @lheagy, the submitting author suggested you as the handling editor.

**Comment by juliohm** [comment]
Thank you @arfon for the follow up. I noticed that the figure in the compiled PDF is placed differently than in my local version. Is there a template that I can use to reproduce exactly the document compiled by the bot?

**Comment by juliohm** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00689/joss.00689/10.21105.joss.00689.pdf)

**Comment by juliohm** [comment]
I've fixed the figure placement issue, and other small English issue. Looking forward to start the review process.

Best,

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00689/joss.00689/10.21105.joss.00689.pdf)

**Comment by lheagy** [comment]
Thanks @arfon, I am happy to take this. @juliohm: do you have any suggestions for reviewers?

**Comment by lheagy** [comment]
👋 Hi @nuest, would you be willing to review this submission for JOSS?

**Comment by juliohm** [comment]
Hi @lheagy, thank you for the prompt reply and for pinging @nuest. Is there a list of reviewers from which to select similar to the list of editors on the JOSS website?

**Comment by lheagy** [comment]
@juliohm, the list is here: https://bit.ly/joss-reviewers. Ideally, we find 2 reviewers

**Comment by juliohm** [comment]
:wave: @dhhagan @ziotom78 @wkearn @rowanc1 would any of you be available to review the submission? I've checked your GitHub profiles and websites, and concluded that you all have experience with spatial data, geosciences & statistics. Looking forward to your feedback.

**Comment by wkearn** [comment]
I'd be happy to review!

**Comment by ziotom78** [comment]
Ok for me.

**Comment by lheagy** [comment]
Thanks @wkearn and @ziotom78!

**Comment by lheagy** [comment]
@whedon assign @wkearn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wkearn

**Comment by lheagy** [comment]
@whedon add @ziotom78 as reviewer

**Comment by whedon** [comment]
OK, @ziotom78 is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/692. Feel free to close this issue now!
