### ISSUE TITLE
[REVIEW]: GeoStats.jl - High-performance geostatistics in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#692]
**Submitting author:** @juliohm (<a href="http://orcid.org/0000-0003-2789-297X">Júlio Hoffimann</a>)
**Repository:** <a href="https://github.com/juliohm/GeoStats.jl" target ="_blank">https://github.com/juliohm/GeoStats.jl</a>
**Version:** v0.6.0
**Editor:** @lheagy
**Reviewer:** @wkearn, @ziotom78
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1228609" target="_blank">10.5281/zenodo.1228609</a>

## Status

[![status](http://joss.theoj.org/papers/63d603dc7b9e9bd51a841864f4c8f4ff/status.svg)](http://joss.theoj.org/papers/63d603dc7b9e9bd51a841864f4c8f4ff)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/63d603dc7b9e9bd51a841864f4c8f4ff"><img src="http://joss.theoj.org/papers/63d603dc7b9e9bd51a841864f4c8f4ff/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/63d603dc7b9e9bd51a841864f4c8f4ff/status.svg)](http://joss.theoj.org/papers/63d603dc7b9e9bd51a841864f4c8f4ff)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/juliohm/GeoStats.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@wkearn & @ziotom78, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/juliohm/GeoStats.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.0)?
- [x] **Authorship:** Has the submitting author (@juliohm) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/juliohm/GeoStats.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.0)?
- [x] **Authorship:** Has the submitting author (@juliohm) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @wkearn, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00692/joss.00692/10.21105.joss.00692.pdf)

**Comment by lheagy** [comment]
Thanks @wkearn, @ziotom78 for being willing to review! In the issue description, there is a checklist for each of you to help guide the review. Please let me know if you have any questions or if I can provide any support.

**Comment by juliohm** [comment]
Thank you @wkearn and @ziotom78 for making time to review the submission. Thank you @lheagy for leading the process. :+1:

**Comment by ziotom78** [comment]
Really a good and interesting package! I am going through the documentation and the examples, at the moment I have opened two tickets ([#20](https://github.com/juliohm/GeoStats.jl/issues/20) and [#21](https://github.com/juliohm/GeoStats.jl/issues/21)).

In the README, you might consider putting a link to your `CONTRIBUTING.md` file, as it contains valuable information that might be missed.

**Comment by juliohm** [comment]
Thank you @ziotom78 for your time and for going through the documentation, very helpful. I will add a link to the CONTRIBUTING.md file in the README.md

**Comment by juliohm** [comment]
Fixed the example everywhere, the documentation, the README.md and the paper.md. I've also added the link to CONTRIBUTING.md as suggested to the README.md

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00692/joss.00692/10.21105.joss.00692.pdf)

**Comment by ziotom78** [comment]
Great, @juliohm! The only last thing I think might be improved is the section "Comparison methods" in the paper. It looks a bit sketchy, and the reader might not understand that the library actually implements both comparison methods. You might simply quote the relevant functions and types (`compare`, `VisualComparison`, `CrossValidation`) in the text.

**Comment by juliohm** [comment]
Thank you @ziotom78 , I've added a sentence with the `compare` command to clarify the section. It was indeed really sketchy, thank you for your feedback.

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00692/joss.00692/10.21105.joss.00692.pdf)

**Comment by ziotom78** [comment]
Excellent! From my point of view the paper as it is now is fine, but let's wait for @wkearn's review.

**Comment by juliohm** [comment]
Thank you @wkearn! I am glad the documentation and examples are clear. This was a place where I did put a lot of effort. One of my goals is to really demystify geostatistics to the scientific community in general.

I will expand the comparison section of the paper a little more with a figure, and then let you know. We could then wrap up the review process. :+1:

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #692 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    150      0 --:--:-- --:--:-- --:--:--   151
Error producing PDF.
! Unable to load picture or PDF file 'SolverComparison.png'.
<to be read again> 
                   }
l.399 ...width=.8\textwidth]{SolverComparison.png}

Looks like we failed to compile the PDF

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00692/joss.00692/10.21105.joss.00692.pdf)

**Comment by juliohm** [comment]
@ziotom78 @wkearn could you please give your final word on the latest version of the paper above? Please let me know if anything is out of place.

**Comment by lheagy** [comment]
Thanks @wkearn and @ziotom78 for a speedy and thorough review! 

@juliohm: we can proceed to accept the paper - congratulations! Could you please archive your software on [Zenodo](https://zenodo.org/) or similar and post the doi here?

**Comment by juliohm** [comment]
Thank you all for your feedback, it is been an amazing experience to work with you on this review process.

@lheagy I will archive the software and post the DOI here as soon as possible.

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00692/joss.00692/10.21105.joss.00692.pdf)

**Comment by juliohm** [comment]
@lheagy the Zenodo DOI is here: https://doi.org/10.5281/zenodo.1228609

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1228609 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1228609" target="_blank">10.5281/zenodo.1228609</a> is the archive.

**Comment by arfon** [comment]
@juliohm - I had to fiddle around a little with the YAML header of your paper to get it to compile properly for production. In particular, I had to edit the email you had listed and turn it into a 'corresponding author' footnote:

```
---
title: 'GeoStats.jl -- High-performance geostatistics in Julia'
tags:
  - Geostatistics
  - Inverse problems
  - Random processes
  - Spatial statistics
  - Variography
  - Kriging
  - Estimation
  - Simulation
  - Julia
authors:
  - name: "Júlio Hoffimann^[Corresponding author: juliohm@stanford.edu]"
    orcid: 0000-0003-2789-297X
    affiliation: 1
affiliations:
  - name: Stanford University
    index: 1
date: 20 April 2018
bibliography: paper.bib
---

```

**Comment by arfon** [comment]
@wkearn, @ziotom78 - many thanks for your review here and to @lheagy for editing this submission ✨ 

@juliohm - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00692 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00692/status.svg)](https://doi.org/10.21105/joss.00692)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00692/status.svg)](https://doi.org/10.21105/joss.00692)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by juliohm** [comment]
Thank you all for the incredible process! Please let me know how I can become a reviewer for Julia software.

**Comment by arfon** [comment]
> Thank you all for the incredible process! Please let me know how I can become a reviewer for Julia software.

Great! Please fill in your details/interests here: http://joss.theoj.org/reviewer-signup.html

**Comment by arfon** [comment]
> The author name is listed incorrectly, and the cross references are not assigned to my profile. Is there any way to maintain the email but remove this side effect produced by LaTeX syntax?

There is not sorry. I think this is a limitation of our current template and document processing. The short-term fix here is to simply remove the footnote/your email from the submission.

**Comment by juliohm** [comment]
Thank you @arfon I will consider the change for future releases of the project.

**Comment by juliohm** [comment]
The software archive link is broken in the JOSS page. How can I fix it?

**Comment by juliohm** [comment]
The link I am referring to is named "software archive" in the screenshot below:

![screenshot from 2018-04-25 17-43-40](https://user-images.githubusercontent.com/3345261/39279823-4b72bbc6-48b0-11e8-9e88-6e6ceda8902e.png)

**Comment by arfon** [comment]
@juliohm - this link issue should be fixed now.

**Comment by juliohm** [comment]
Thank you @arfon :+1:
