### ISSUE TITLE
[REVIEW]: dustmaps: A Python interface for maps of interstellar dust

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#695]
**Submitting author:** @gregreen (<a href="http://orcid.org/0000-0001-5417-2260">Gregory Green</a>)
**Repository:** <a href="https://github.com/gregreen/dustmaps" target ="_blank">https://github.com/gregreen/dustmaps</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @jegpeek
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1299368" target="_blank">10.5281/zenodo.1299368</a>

## Status

[![status](http://joss.theoj.org/papers/40e2dafaa31accc83de303718ba9ac1d/status.svg)](http://joss.theoj.org/papers/40e2dafaa31accc83de303718ba9ac1d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/40e2dafaa31accc83de303718ba9ac1d"><img src="http://joss.theoj.org/papers/40e2dafaa31accc83de303718ba9ac1d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/40e2dafaa31accc83de303718ba9ac1d/status.svg)](http://joss.theoj.org/papers/40e2dafaa31accc83de303718ba9ac1d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/gregreen/dustmaps" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jegpeek, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gregreen/dustmaps">repository url</a>?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@gregreen) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jegpeek it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00695/joss.00695/10.21105.joss.00695.pdf)

**Comment by arfon** [comment]
@jegpeek - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by gregreen** [comment]
@arfon Is there an equivalent to `\citet{}` in mardown? Some of the citations should not be in parentheses.

**Comment by gregreen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00695/joss.00695/10.21105.joss.00695.pdf)

**Comment by gregreen** [comment]
@arfon Yes, that covered it. Thanks!

**Comment by arfon** [comment]
👋@jegpeek - friendly reminder to take a look at this review when you get a chance.

**Comment by gregreen** [comment]
@jegpeek Any progress on the review?

**Comment by jegpeek** [comment]
Yep — been traveling with crappy wifi so hard to kick all the tires. Will do!

**Comment by jegpeek** [comment]
I know this is classic referee garbage but... what do you think of adding Peek & Graves 2010?

**Comment by gregreen** [comment]
I would be happy to do so. I can't access http://peekandgraves2010.com/ though. Is there a newer link to the data? Better yet, is the data stored in some semi-permanent archive (like the Harvard Dataverse)? I write a `fetch()` function for each dust map, so having a stable URL is best.

**Comment by jegpeek** [comment]
Thanks for the nudge! https://doi.org/10.7910/DVN/VBSI4A

**Comment by gregreen** [comment]
I've added an issue, which I'll work on, but don't let that get in the way of looking over the code as it already is!

**Comment by gregreen** [comment]
@jegpeek Have you had time to test the functionality of the package, or to look at the documentation?

**Comment by jegpeek** [comment]
@gregreen making progress! Right now I am having this issue: I was following along in the directions [here](http://dustmaps.readthedocs.io/en/latest/examples.html#querying-reddening-at-an-array-of-coordinates):

```
import dustmaps.planck
dustmaps.planck.fetch()
```
and then got 

```
Downloading http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_CompMap_ThermalDustModel_2048_R1.20.fits ...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-3c6fb0816ca2> in <module>()
      1 import dustmaps.planck
----> 2 dustmaps.planck.fetch()

/Users/jegpeek/anaconda3/lib/python3.5/site-packages/dustmaps/planck.py in fetch()
    130         'planck',
    131         'HFI_CompMap_ThermalDustModel_2048_R1.20.fits')
--> 132     fetch_utils.download_and_verify(url, md5, fname=fname)
    133 
    134 

/Users/jegpeek/anaconda3/lib/python3.5/site-packages/dustmaps/fetch_utils.py in download_and_verify(url, md5sum, fname, chunk_size, clobber, verbose)
    234 
    235             with open(fname, 'wb') as f:
--> 236                 content_length = int(r.headers['content-length'])
    237                 bar = FileTransferProgressBar(content_length)
    238 

/Users/jegpeek/anaconda3/lib/python3.5/site-packages/requests/structures.py in __getitem__(self, key)
     52 
     53     def __getitem__(self, key):
---> 54         return self._store[key.lower()][1]
     55 
     56     def __delitem__(self, key):

KeyError: 'content-length'
```

any ideas?

**Comment by gregreen** [comment]
It looks like the website isn't returning "content-length" in the headers. I'll fix the case where "content-length" is missing.

**Comment by jegpeek** [comment]
<KHAAAN.gif, but instead, PLAAAANCK>
also
<and_I_helped.gif>

**Comment by gregreen** [comment]
@jegpeek Can you verify that latest commit in the develop branch (gregreen/dustmaps@4c48e989c893a76f8107bf28d3e2620fd704b6ae) fixes the "content-length" issue?

**Comment by jegpeek** [comment]
Yup, works!

**Comment by jegpeek** [comment]
Hey @gregreen I'm a little worried about the scaling issue, especially for bayestar. It's kinda confusing to report things "in SFD units" by default. There are two corrections discussed in GSF, I think (?) and I have trouble understanding which are which, and which are applied. This
```
sfd = SFDQuery()
Av_sfd = 2.742 * sfd(coords)

planck = PlanckQuery()
Av_planck = 3.1 * planck(coords)

bayestar = BayestarQuery(max_samples=1)
Av_bayestar = 2.742 * bayestar(coords)
```
makes me think bayestar is reported in "SFD units". I haven't met anyone outside the three of you who finds this natural (not that I have taken a poll...) . I get that the map is reported in these units, and thus that ship has in some sense sailed. Could there be either clearer documentation on this, or a correction=False flag, or something? I'll bet a ton of people are applying this naively.

**Comment by jegpeek** [comment]
@gregreen (sorry, just found the ebv comments) are there automated tests?

**Comment by jegpeek** [comment]
@gregreen I know you guys have thought about this a lot, but it might be worth reconsidering the default behavior for these functions regarding "EBV_SFD". I don't think it's my role here as JOSS reviewer to get into it, so I'm not going to hold up the process or anything, but I think if you are going to all the trouble to package all of this so elegantly, asking folks to think in unrescaled SFD units and then multiplying is pretty weird. Maybe the package

**Comment by gregreen** [comment]
@jegpeek There are tests [here](https://github.com/gregreen/dustmaps/tree/master/dustmaps/tests). You can go to the dustmaps/ directory in the repository and run

    nosetests -v

Be careful though - some of the tests use a lot of memory! If you want to reduce the memory usage of the Bayestar map test, you can change [this line](https://github.com/gregreen/dustmaps/blob/master/dustmaps/tests/test_bayestar.py#L106) to `max_samples = 1`.

**Comment by jegpeek** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by jegpeek** [comment]
OK @arfon I checked off all the things. Awesome piece of work @gregreen. Sorry it took so long.

**Comment by gregreen** [comment]
@jegpeek No problem. Thanks for looking through my code/docs/paper!

**Comment by gregreen** [comment]
@arfon The DOI is now: [10.5281/zenodo.1299368](https://doi.org/10.5281/zenodo.1299368).

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1299368 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1299368" target="_blank">10.5281/zenodo.1299368</a> is the archive.

**Comment by arfon** [comment]
@jegpeek - many thanks for your review here ✨ 

@gregreen - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00695 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00695/status.svg)](https://doi.org/10.21105/joss.00695)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00695/status.svg)](https://doi.org/10.21105/joss.00695)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
