### ISSUE TITLE
[PRE REVIEW]: Galore: Broadening and weighting for simulation of photoelectron spectroscopy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#696]
**Submitting author:** @ajjackson (<a href="http://orcid.org/0000-0001-5272-6530">Adam J. Jackson</a>)
**Repository:** <a href="https://github.com/SMTG-UCL/galore" target ="_blank">https://github.com/SMTG-UCL/galore</a>
**Version:** 0.5.0
**Editor:** @arfon
**Reviewers:** @shyamd

**Author instructions**

Thanks for submitting your paper to JOSS @ajjackson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ajjackson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by ajjackson** [comment]
I have pushed an update to master which should fix the whedon error. Is there a way to trigger a rebuild?

From the former reviewer list, @tacaswell @jochym @mikapfl have listed relevant topics but I do not know if they have access/familiarity with the electronic structure codes that this is intended to post-process (VASP and GPAW). Test data is provided with the package.

@bjmorgan (former reviewer) is well qualified to look at this but I should disclose that he is my mentor in the Software Sustainability Institute [Fellowship Programme](https://www.software.ac.uk/index.php/fellowship-programme)

@jameskermode and @askhl are both VASP users with a good knowledge of open-source development; @askhl is also a GPAW developer.

**Comment by ajjackson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00696/joss.00696/10.21105.joss.00696.pdf)

**Comment by ajjackson** [comment]
(Added to affiliations and acknowledgements, changed citation style to one that isn't broken.)
@whedon generate pdf

**Comment by ajjackson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00696/joss.00696/10.21105.joss.00696.pdf)

**Comment by ajjackson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00696/joss.00696/10.21105.joss.00696.pdf)

**Comment by ajjackson** [comment]
(Fixed the chemical symbols in some cited paper titles)

**Comment by katyhuff** [comment]
@tacaswell @jochym @mikapfl @jameskermode or @askhl : Are any of you available to conduct a review for this paper? @ajjackson has submitted it to JOSS and I am the current editor.

The paper is here: https://github.com/openjournals/joss-papers/blob/joss.00696/joss.00696/10.21105.joss.00696.pdf

From the README: 

> Galore is a package which applies Gaussian and Lorentzian broadening to data from ab initio calculations. The two main intended applications are
>
> Gaussian and Lorentzian broadening of electronic density-of-states, with orbital weighting to simulate UPS/XPS/HAXPES measurements.
Application of Lorentzian instrumental broadening to simulated Raman spectra from DFPT calculations.

**Comment by jochym** [comment]
Sorry. A bit outside of my field and I am swamped with work right now. Maybe next time.

**Comment by ajjackson** [comment]
Ah, apologies @askhl I had noticed you being active on ASE/Vasp issues! Not very much of the codebase is Vasp-specific, just some import functions which rely on Pymatgen. I would be happy to send extra sample data if needed; Vasp import just needs the files, while GPAW input needs a working GPAW setup.

**Comment by ajjackson** [comment]
Perhaps @shyamd would be interested? He has provided some very useful feedback on another Vasp-related package of ours.

@askhl when reviewers are set there is another Issue page with checklists for reviewers to use. The reviewer guidelines are located [here](https://joss.theoj.org/about#reviewer_guidelines) (< 1000 words).

@mikapfl the package does come with some sample data, but of course it would be great if reviewers could test with their own. @katyhuff what is your view on this?

**Comment by shyamd** [comment]
@ajjackson  I would interested , but depending on the desired timeline might not be able to. My next 3 weeks are 120% booked.

**Comment by ajjackson** [comment]
@arfon @katyhuff Is there anything more I can do to get this review moving? The process seems to have stalled.

**Comment by arfon** [comment]
@ajjackson - sorry for the delay here. I'll take this one.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@shyamd @askhl - sorry for the delay but are you both still willing to review this submission?

**Comment by arfon** [comment]
@whedon assign @shyamd as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @shyamd

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/773. Feel free to close this issue now!

**Comment by arfon** [comment]
@shyamd @ajjackson - please head over to #773 for the actual review issue.
