### ISSUE TITLE
[PRE REVIEW]: RcmdrPlugin.OptimClassifier: Extending the R Commander Interface to create the best train for classification models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#697]
**Submitting author:** @economistgame (<a href="http://orcid.org/0000-0001-5658-4795">Agustín Pérez-Torregrosa</a>)
**Repository:** <a href="https://github.com/economistgame/RcmdrPlugin.OptimClassifier" target ="_blank">https://github.com/economistgame/RcmdrPlugin.OptimClassifier</a>
**Version:** v0.1.2
**Editor:** @karthik
**Reviewers:** @@andrewheiss

**Author instructions**

Thanks for submitting your paper to JOSS @economistgame. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@economistgame if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by economistgame** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00697/joss.00697/10.21105.joss.00697.pdf)

**Comment by economistgame** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00697/joss.00697/10.21105.joss.00697.pdf)

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by economistgame** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00697/joss.00697/10.21105.joss.00697.pdf)

**Comment by economistgame** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by economistgame** [comment]
I suggest @wrathematics and @masalmon to review the paper

**Comment by arfon** [comment]
:wave: @karthik - would you be willing to edit this submission for JOSS?

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@wrathematics are you able to review this one?

**Comment by economistgame** [comment]
@karthik  as we did not receive a reply to our request for @wrathematics, I assume him must be very busy or on extended travel. For this sake, we suggest new potential reviewers such as @andrewheiss or maybe @briatte

**Comment by karthik** [comment]
@economistgame Thanks for the suggestions. 

@andrewheiss and/or @briatte, would either of you be able to review?

**Comment by andrewheiss** [comment]
Sure! Are there official guidelines for reviewing that I should be aware of?

**Comment by karthik** [comment]
Thanks @andrewheiss! Once I start the review you'll be tagged in another issue with a checklist and link to guidelines (http://joss.theoj.org/about#reviewer_guidelines). I'd be happy to answer any questions you may have about the process (email in profile).

**Comment by karthik** [comment]
@whedon assign @@andrewheiss as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @@andrewheiss

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/727. Feel free to close this issue now!

**Comment by briatte** [comment]
@whedon – May I use this conversation to ask whether the [Google Sheets](https://bit.ly/joss-reviewers) you posted is the same as the one produced by filling in [this form](https://ropensci.org/onboarding/)? Can't remember what I filled in.

Happy to help on future reviews.

**Comment by karthik** [comment]
@briatte No. Both forms look similar but they post to two different reviewer collections.

**Comment by briatte** [comment]
@karthik Alright, thanks.
