### ISSUE TITLE
[PRE REVIEW]: EndoMineR for the extraction of endoscopic and associated pathology data from medical reports

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#700]
**Submitting author:** @sebastiz (<a href="http://orcid.org/0000-0003-1673-2663">Sebastian Zeki</a>)
**Repository:** <a href="https://github.com/ropensci/EndoMineR" target ="_blank">https://github.com/ropensci/EndoMineR</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @sebastiz. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sebastiz if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #700 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #700 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0     89      0 --:--:-- --:--:-- --:--:--    89
Error reading bibliography ./paper.bib (line 2, column 10):
unexpected "="
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/701. Feel free to close this issue now!

**Comment by karthik** [comment]
@sebastiz No additional review required at JOSS. But please check the issues that @arfon has poined out in https://github.com/openjournals/joss-reviews/issues/701
