### ISSUE TITLE
[PRE REVIEW]: fib-tf: A TensorFlow-based Cardiac Electrophysiology Simulator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#702]
**Submitting author:** @siravan (<a href="http://orcid.org/0000-0003-2132-1543">Shahriar Iravanian</a>)
**Repository:** <a href="https://github.com/siravan/fib_tf" target ="_blank">https://github.com/siravan/fib_tf</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @mgalloy, @leios

**Author instructions**

Thanks for submitting your paper to JOSS @siravan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@siravan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00702/joss.00702/10.21105.joss.00702.pdf)

**Comment by siravan** [comment]
Regarding possible reviewers from the list, the following reviewers have skills that fit this project:
#50 arghdos
#133 leios
#296 mgalloy

**Comment by arfon** [comment]
👋 @mgalloy @leios - would you be willing to review this submission for JOSS?

**Comment by leios** [comment]
@arfon I can review this, if you like.

**Comment by mgalloy** [comment]
@arfon I can also review this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @mgalloy as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mgalloy

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @leios as reviewer

**Comment by whedon** [comment]
OK, @leios is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/719. Feel free to close this issue now!
