### ISSUE TITLE
[PRE REVIEW]: mlpack 3: a fast, flexible machine learning library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#703]
**Submitting author:** @rcurtin (<a href="http://orcid.org/0000-0002-9903-8214">Ryan Curtin</a>)
**Repository:** <a href="https://github.com/mlpack/mlpack" target ="_blank">https://github.com/mlpack/mlpack</a>
**Version:** v3.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @rasbt, @MikeInnes, @mlgill

**Author instructions**

Thanks for submitting your paper to JOSS @rcurtin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rcurtin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00703/joss.00703/10.21105.joss.00703.pdf)

**Comment by arfon** [comment]
@rcurtin - many thanks for your submission. Is there anything stopping you from moving the paper into the https://github.com/mlpack/mlpack repository? This is our preferred way of handling submissions.

The `paper.md` file can exist basically anywhere in the https://github.com/mlpack/mlpack/ repo (e.g. nested somewhere under the docs folder)

**Comment by rcurtin** [comment]
@arfon thanks for the quick reply.  If it's necessary, we can move the paper into the repository, but to me it seems that the paper itself is a separate artifact from the code.  (As time goes on, the paper itself may become out of date, for example.)  I think that the Armadillo submission, which I was also involved with, had the paper in a separate place also.  Let me know what you think.

I see that there are some minor issues with the paper; I will handle those.  But I do have a question: some of our authors chose to have no affiliation for this paper, but it looks like the paper has compiled such that their affiliation has default-chosen the first affiliation.  Is there a way to specify no affiliation?  I don't see anything in the documentation.

**Comment by rcurtin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00703/joss.00703/10.21105.joss.00703.pdf)

**Comment by arfon** [comment]
> @arfon thanks for the quick reply. If it's necessary, we can move the paper into the repository, but to me it seems that the paper itself is a separate artifact from the code. (As time goes on, the paper itself may become out of date, for example.) I think that the Armadillo submission, which I was also involved with, had the paper in a separate place also. Let me know what you think.

This is a hard requirement for us these days. Our editorial system is heavily automated and so the current layout (paper not being with the software) means manual work for our editorial team.

**Comment by rcurtin** [comment]
Ok, if it is a hard requirement, we have gone ahead and merged the paper.md into the mlpack/mlpack repository.  The repository is now:

https://github.com/mlpack/mlpack

and the paper is located at:

https://github.com/mlpack/mlpack/tree/master/doc/joss_paper

Please let me know if that works, and if I didn't do it right just let me know and I can fix it.  Thanks!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00703/joss.00703/10.21105.joss.00703.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@rcurtin thanks for this submission. I'm going to start looking for reviewers. Are you able to suggest any reviewers at this point?

**Comment by Kevin-Mattheus-Moerman** [comment]
@rcurtin minor point on the paper, can you please add DOI's to all references that have them. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
Review invitation. @MikeInnes @betatim @rasbt @cxhernandez @mlgill @rhiever would you be interested in reviewing this submission? 

[-->project repo :floppy_disk:  <--](https://github.com/mlpack/mlpack)
[--> Paper  :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00703/joss.00703/10.21105.joss.00703.pdf)

**Comment by rasbt** [comment]
i would be happy to do that. Timeline-wise, I think I will be able to get started on that later this week or next weekend.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @rasbt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rasbt

**Comment by MikeInnes** [comment]
I'll review (my time for it might be a bit scattered over the next couple of weeks though).

**Comment by mlgill** [comment]
I can do it next week if a third is needed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @MikeInnes as reviewer

**Comment by whedon** [comment]
OK, @MikeInnes is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @mlgill as reviewer

**Comment by whedon** [comment]
OK, @mlgill is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/726. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
Okay @rcurtin @mlgill @rasbt MikeInnes I've started the review issue over at #726
