### ISSUE TITLE
[PRE REVIEW]: approxposterior: A Python Implementation of “Bayesian Active Learning For Posterior Estimation”

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#704]
**Submitting author:** @dflemin3 (<a href="http://orcid.org/0000-0001-9293-4043">David Fleming</a>)
**Repository:** <a href="https://github.com/dflemin3/approxposterior" target ="_blank">https://github.com/dflemin3/approxposterior</a>
**Version:** v0.1
**Editor:** @jedbrown
**Reviewers:** @dmdu

**Author instructions**

Thanks for submitting your paper to JOSS @dflemin3. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dflemin3 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #704 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #704 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #704 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #704 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@dflemin3 - it looks like the YAML header of this paper is incorrectly structured. Could you take a look at the example here and fix your paper please? http://joss.theoj.org/about#author_guidelines

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00704/joss.00704/10.21105.joss.00704.pdf)

**Comment by arfon** [comment]
:wave: @kyleniemeyer - would you be willing to edit this submission for JOSS? I realize this is a little outside your domain but perhaps you could solicit an extra reviewer or two? :grin:

**Comment by jedbrown** [comment]
@arfon I can take this one.

**Comment by arfon** [comment]
> @arfon I can take this one.

Great, thanks!

Feel free to assign yourself with `@whedon assign @jedbrown as editor`

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@whedon assign @dmdu as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dmdu

**Comment by arfon** [comment]
@jedbrown are you planning on adding a second reviewer? If not, then you can move this forward by typing:

```
@whedon start review magic-word=bananas
```

which will make the actual review issue.

**Comment by jedbrown** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/781. Feel free to close this issue now!

**Comment by jedbrown** [comment]
The second reviewer I had in mind just had a baby and @dmdu is entirely capable so one is enough.
