### ISSUE TITLE
[PRE REVIEW]: egtplot: A Python Package for Three-Strategy Evolutionary Games

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#705]
**Submitting author:** @drew-williamson (<a href="http://orcid.org/0000-0003-1745-8846">Drew Williamson</a>)
**Repository:** <a href="https://github.com/mirzaevinom/egtplot" target ="_blank">https://github.com/mirzaevinom/egtplot</a>
**Version:** v0.3
**Editor:** @arfon
**Reviewers:** @fil, @jmbr

**Author instructions**

Thanks for submitting your paper to JOSS @drew-williamson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@drew-williamson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
I've updated `paper.md` in the repo so that the figures should now (fingers crossed) display correctly.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by arfon** [comment]
@drew-williamson can you check? 👆

**Comment by drew-williamson** [comment]
Forgot to add figure 2 to the repo. Once more?

**Comment by arfon** [comment]
> Forgot to add figure 2 to the repo. Once more? Thanks!

You can ask Whedon to do this for you :-)

**Comment by drew-williamson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00705/joss.00705/10.21105.joss.00705.pdf)

**Comment by drew-williamson** [comment]
@arfon After much ado with the figures, it's finally ready to go. Thank goodness for whedon.

**Comment by arfon** [comment]
> @arfon After much ado with the figures, it's finally ready to go. Thank goodness for whedon.

Indeed!

**Comment by arfon** [comment]
:wave: @labarba - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@drew-williamson - could you take a look at the list of reviewers above and suggest a few potential candidates? ☝️

**Comment by drew-williamson** [comment]
Not sure if I should @ them directly, but perhaps fil, jmbr, nagoue, or krother?

**Comment by arfon** [comment]
@nagoue @jmbr - would you be willing to review this submission for JOSS?

**Comment by jmbr** [comment]
I’m willing.

**Comment by arfon** [comment]
@fil - would you be willing to review this submission for JOSS? Ideally I'd like to have two reviewers for this submission (@jmbr has already kindly volunteered)

**Comment by Fil** [comment]
yes — will remind me of my research 25 yrs ago that was on this topic :)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @fil as reviewer

**Comment by whedon** [comment]
OK, @fil is now a reviewer

**Comment by arfon** [comment]
@whedon add @jmbr as reviewer

**Comment by whedon** [comment]
OK, @jmbr is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/735. Feel free to close this issue now!

**Comment by arfon** [comment]
@Fil, @jmbr, @drew-williamson - see you over in #735 for the actual review.
