### ISSUE TITLE
[PRE REVIEW]: dit: a Python package for discrete information theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#709]
**Submitting author:** @Autoplectic (<a href="http://orcid.org/0000-0003-2149-9085">Ryan G. James</a>)
**Repository:** <a href="https://github.com/dit/dit" target ="_blank">https://github.com/dit/dit</a>
**Version:** v1.2.0
**Editor:** @arfon
**Reviewers:** @kczimm, @stsievert

**Author instructions**

Thanks for submitting your paper to JOSS @Autoplectic. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Autoplectic if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00709/joss.00709/10.21105.joss.00709.pdf)

**Comment by arfon** [comment]
:wave: @jakevdp - the submitting author suggested you as the handling editor.

**Comment by Autoplectic** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@Autoplectic - could you take a look at the list of reviewers above and suggest a few potential good candidates for reviewing this submission?

**Comment by Autoplectic** [comment]
@arfon khinsen, rougier, jmbr, kczimm, stsievert, vsoch would all probably be fine reviewers.

**Comment by arfon** [comment]
@kczimm, @stsievert - would you be willing to review this submission for JOSS?

**Comment by stsievert** [comment]
I'd be happy to! I've got a deadline on Friday, but I should be free after.

**Comment by stsievert** [comment]
Here's a good list of some reviewer guidelines: http://joss.theoj.org/about#reviewer_guidelines

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @kczimm as reviewer

**Comment by whedon** [comment]
OK, @kczimm is now a reviewer

**Comment by arfon** [comment]
@whedon add @stsievert as reviewer

**Comment by whedon** [comment]
OK, @stsievert is now a reviewer

**Comment by arfon** [comment]
@kczimm, @stsievert - many thanks for agreeing to review this. I'll go ahead and set up the main review issue next.

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/738. Feel free to close this issue now!

**Comment by arfon** [comment]
@kczimm, @stsievert, @Autoplectic - please head over to #738 for the actual review.
