### ISSUE TITLE
[REVIEW]: MCycle: A Python package for 1D sizing and analysis of thermodynamic power cycles

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#710]
**Submitting author:** @momargoh (<a href="http://orcid.org/0000-0002-6928-2187">Momar Hughes</a>)
**Repository:** <a href="https://github.com/momargoh/MCycle" target ="_blank">https://github.com/momargoh/MCycle</a>
**Version:** v0.1.2
**Editor:** @katyhuff
**Reviewers:** @Tabeel, @puncan
**Archive:** <a href="https://doi.org/10.5281/zenodo.1324221" target="_blank">10.5281/zenodo.1324221</a>

## Status

[![status](http://joss.theoj.org/papers/4363ce4be11df7bc38bd47246fbd34ce/status.svg)](http://joss.theoj.org/papers/4363ce4be11df7bc38bd47246fbd34ce)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4363ce4be11df7bc38bd47246fbd34ce"><img src="http://joss.theoj.org/papers/4363ce4be11df7bc38bd47246fbd34ce/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4363ce4be11df7bc38bd47246fbd34ce/status.svg)](http://joss.theoj.org/papers/4363ce4be11df7bc38bd47246fbd34ce)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/momargoh/MCycle" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@puncan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/momargoh/MCycle">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.2)?
- [x] **Authorship:** Has the submitting author (@momargoh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/momargoh/MCycle">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.2)?
- [x] **Authorship:** Has the submitting author (@momargoh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @puncan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by katyhuff** [comment]
@whedon assign @Tabeel as reviewer

**Comment by katyhuff** [comment]
@whedon add @puncan as reviewer

**Comment by whedon** [comment]
OK, @puncan is now a reviewer

**Comment by katyhuff** [comment]
Ok, both @puncan and @Tabeel will be reviewers for this submission. Each of you has a review checklist above. Please use the one with your name on it.

**Comment by Tabeel** [comment]
Hi @katyhuff, I am unable to make changes to the review checklist. Am I am missing something?

**Comment by katyhuff** [comment]
@Tabeel there's a little note about this up at the top of the issue, but it's easy to miss. 

It says:

 If you cannot edit the checklist please:

1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

**Comment by Tabeel** [comment]
Thank you

**Comment by arfon** [comment]
@puncan - it looks like you're only part way through your review here. Any chance you could complete this in the next week or so?

**Comment by puncan** [comment]
Yes, my apologies. It got away from me. Certainly within a week.

-Paul

**Comment by puncan** [comment]
There were a couple I checked off after creating new issues. Am I doing this right?

**Comment by momargoh** [comment]
Thanks @puncan I'll fix up the issues you've raised now.

**Comment by momargoh** [comment]
Also, there is a newer version of MCycle that uses Cython; it has a different build and different directory structure. At the moment it's just in the cython fork, I haven't pulled it to master yet. Could I update my joss submission to consider this version?

**Comment by puncan** [comment]
I don’t see why not.

**Comment by katyhuff** [comment]
Yes, go right ahead and update to the new version. Sorry for the delay in responding. It looks like all of the issues raised by the reviewers have now been handled. Is that correct @puncan @Tabeel @momargoh ? 


If so, then @momargoh  at this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by puncan** [comment]
Sounds good to me.

**Comment by momargoh** [comment]
No, I haven't handled all the issues raised by @puncan yet, doing so now. I'm having trouble committing the new Cython-based version to pip due to problems creating a cross-platform dist wheel. The package can be built from the source using `python3 setup.py install` and similarly the docs will not be hosted properly until the package is on pip, so at the moment they can just be built from the source using Sphinx3 `make html`.
Is this OK: the package needing to be built from source instead of available from pip?

**Comment by momargoh** [comment]
No, I haven't handled all the issues raised by @puncan yet, doing so now. I'm having trouble committing the new Cython-based version to pip due to problems creating a cross-platform dist wheel. The package can be built from the source using `python3 setup.py install` and similarly the docs will not be hosted properly until the package is on pip, so at the moment they can just be built from the source using Sphinx3 `make html`.
Is this OK: the package needing to be built from source instead of available from pip?

**Comment by momargoh** [comment]
OK, the docs are building OK https://mcycle.readthedocs.io/index.html. For now the source has to be installed from source as opposed to from pip. I have updated my JOSS submission to v1.0.0: the latest version of the source code.

**Comment by katyhuff** [comment]
It looks to me like @puncan approved this a few comments ago. (https://github.com/openjournals/joss-reviews/issues/710#issuecomment-407145425)

It seems you can go ahead and make the DOI whenever you're ready.

**Comment by momargoh** [comment]
doi:10.5281/zenodo.1324221
https://zenodo.org/record/1324222#.W2BdfxiuY5k

**Comment by katyhuff** [comment]
Excellent!

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.1324221 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1324221" target="_blank">10.5281/zenodo.1324221</a> is the archive.

**Comment by katyhuff** [comment]
@arfon This submission is ready for acceptance! 
Congratulations @momargoh , and thank you for your reviews @Tabeel and @puncan !

**Comment by arfon** [comment]
@Tabeel, @puncan - many thanks for your reviews here and to @katyhuff for editing this submission ✨ 

@momargoh - your paper is now accepted and your DOI is https://doi.org/10.21105/joss.00710 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00710/status.svg)](https://doi.org/10.21105/joss.00710)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00710">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00710/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00710/status.svg)](https://doi.org/10.21105/joss.00710)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by momargoh** [comment]
@katyhuff @arfon

Thanks so much, however my paper incorrectly says the software has the old CC-BY licence, which was updated to Apache-2.0. I had updated the github license.txt file as well as paper.json to reflect this. Is it possible to rectify this?
