### ISSUE TITLE
[REVIEW]: chronovise: Measurement-Based Probabilistic Timing Analysis framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#711]
**Submitting author:** @federeghe (<a href="http://orcid.org/0000-0002-1888-9579">FEDERICO REGHENZANI</a>)
**Repository:** <a href="https://github.com/federeghe/chronovise" target ="_blank">https://github.com/federeghe/chronovise</a>
**Version:** v1.0
**Editor:** @danielskatz
**Reviewer:** @lkosmid
**Archive:** <a href="https://doi.org/10.5281/zenodo.1404670" target="_blank">10.5281/zenodo.1404670</a>

## Status

[![status](http://joss.theoj.org/papers/dbfdcb46ef47edbd3124ba2a8309e0c3/status.svg)](http://joss.theoj.org/papers/dbfdcb46ef47edbd3124ba2a8309e0c3)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/dbfdcb46ef47edbd3124ba2a8309e0c3"><img src="http://joss.theoj.org/papers/dbfdcb46ef47edbd3124ba2a8309e0c3/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/dbfdcb46ef47edbd3124ba2a8309e0c3/status.svg)](http://joss.theoj.org/papers/dbfdcb46ef47edbd3124ba2a8309e0c3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/federeghe/chronovise" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lkosmid, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/federeghe/chronovise">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@federeghe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @lkosmid it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00711/joss.00711/10.21105.joss.00711.pdf)

**Comment by danielskatz** [comment]
@lkosmid - thanks for agreeing to do this review.  You should start with the information at the top of the issue.  Please let me know if you have questions.

**Comment by danielskatz** [comment]
@lkosmid - just a ping to see if everything is ok.  I think you were out last week, but perhaps you will be able to start on this review this week?

**Comment by lkosmid** [comment]
@danielskatz - yes, indeed,  everything is ok. I think I will be able to start reviewing at the end of this week.

**Comment by danielskatz** [comment]
@lkosmid - just a ping to see how the review is going

**Comment by lkosmid** [comment]
@danielskatz - review it's under way, prepared a clean environment to test the software

**Comment by danielskatz** [comment]
👋 @lkosmid - it looks like the issues you brought up have been addressed

Please confirm, and please continue your review

**Comment by lkosmid** [comment]
@danielskatz - Indeed, thanks @federeghe 
I continue with the review

**Comment by lkosmid** [comment]
In general the short paper seems adequate. It motivates the need for Measurement Based Probabilistic Timing Analysis and in particular the need for an open source tool to compute pWCETs. However, I think that some important references are missing as well as the implementation of some of hte a state-of-the-art MBPTA features.

You can find more details comments here: https://github.com/federeghe/chronovise/issues/11

**Comment by federeghe** [comment]
@lkosmid Thank you for the detailed review. We'll work on that.

**Comment by federeghe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00711/joss.00711/10.21105.joss.00711.pdf)

**Comment by federeghe** [comment]
@lkosmid We updated the article and the code.

We replied inline to the issue federeghe/chronovise#11

Thank you again for the detailed review.

**Comment by lkosmid** [comment]
@federeghe Thank you for the updates in both the code and article. 
I will continue with my review and let you know.

**Comment by lkosmid** [comment]
@federeghe Thank you for the updates in both the code and article. 
I will continue with my review and let you know.

**Comment by lkosmid** [comment]
@federeghe I updated my comments on the short paper.
Some more minor changes are required.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00711/joss.00711/10.21105.joss.00711.pdf)

**Comment by lkosmid** [comment]
@federeghe thank you very much for your updates in the code and the manuscript.
We are almost there, some typos only need to be fixed, see my comments.
Regarding the code review, I have some imminent deadlines and back-to-back trips which might reduce my responsiveness and delay a bit the review, but I will try my best to finish it soon.

**Comment by federeghe** [comment]
@lkosmid Ok, thank you.

**Comment by federeghe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00711/joss.00711/10.21105.joss.00711.pdf)

**Comment by federeghe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00711/joss.00711/10.21105.joss.00711.pdf)

**Comment by danielskatz** [comment]
@lkosmid - can we get an update from you on where things are from your point of view?

**Comment by lkosmid** [comment]
@danielskatz the short paper has been thoroughly reviewed and after several iterations with @federeghe is ready.
From my side it is pending to review the software, its functionality, test environment and documentation (in fact the missing check boxes).
I have already installed the software and gave it a spin a while ago and it seems functional and according to the short paper, but I need to deeply review the code and compare its results with other software packages with similar functionality that I requested e.g. MBPTA-CV
However, as I mentioned I'm between back-to-back business trips and vacations will follow, so I'm afraid that I won't be able to complete those tasks before mid July. I apologise for the long review cycle...

**Comment by danielskatz** [comment]
👋 @lkosmid - Just checking to see if you are back...

**Comment by danielskatz** [comment]
👋 @lkosmid - Just checking again to see if you are back...

**Comment by lkosmid** [comment]
Hi @danielskatz I'm back trying to catch up. I will provide an update during the week.

**Comment by danielskatz** [comment]
Hi @lkosmid - Can I get an update about this review?

I see a bunch of stuff in https://github.com/federeghe/chronovise/issues/11 from a while ago, but it looks like they have all been addressed.  Should that issue now be closed?

Are there other issues that have been raised?

**Comment by lkosmid** [comment]
Hi @danielskatz , all the issues regarding the content of the short paper paper have been addressed. I had forgotten to close the issue (although I had updated the corresponding checkboxes in the review page) soon after @federeghe updated it. 

The only remaining (but time consuming) part from my side is to review the chronovise source code and documentation/examples to verify the claims of the short paper and be able to check the last remaining checkboxes to close the review. I want to make a comparison of some pWCET estimations computed with chronovise with at least MBPTA-CV, which is the reference open source tool in measurement based probabilistic timing analysis. This is necessary in order to make sure that the last claim of the paper, and one of the fundamental contributions of the paper (that the tool can be used by end users like engineers to obtain pWCET estimations with different EVT approaches and compare them) is correct. The problem is that my bandwidth is very limited at the moment, but I have it in high priority. Thank you both for bearing with me and I apologise for the long delay that this causes in  the review process, but I think this extra step will ensure a high-quality review and increase the credibility and impact of the publication.

**Comment by danielskatz** [comment]
Thanks @lkosmid - I think there are likely some checkboxes in the review that could also be checked at this time (e.g., Authorship), and if you have a chance to do this so it's clear from the list what still needs to be done, that would be great, but is not strictly required - it can wait until you have time to do the code check.

**Comment by federeghe** [comment]
Dear @lkosmid,

To simplify your review and reduce your effort, I pushed a small example over 10000 samples generated from a normal distribution for MBPTA-CV together with a small bugfix. The example is called `simple_hello_world_cv_2.cpp` and in the samples folder you can find the original dataset (both in txt for R and in .h for chronovise).
I hope that this can be useful.

The result of the original MBPTA-CV R software is:
```
CV-Value = 0.981919
pWCET(10-6) = 42
pWCET(10-9) = 46
```
The result of chronovise is:
```
CV-Value = 0.986187
pWCET(10-6) = 42.8073
pWCET(10-9) = 46.9047
```

**Comment by danielskatz** [comment]
👋 @lkosmid - please let us know where you are

**Comment by lkosmid** [comment]
Hi @danielskatz and @federeghe , I was out of the office last week.
@federeghe thank you for the example you added, it definitely simplifies a lot  my review.
I will be able to provide an update this week.

**Comment by lkosmid** [comment]
I think that the documentation is in a very good state. I only have a minor suggestion for improving the documentation ([#16](https://github.com/federeghe/chronovise/issues/16)) and one small feature to be implemented ([#15](https://github.com/federeghe/chronovise/issues/15)).

**Comment by federeghe** [comment]
@lkosmid Thank you for the suggestions and the detailed comments, issues federeghe/chronovise#15 and federeghe/chronovise#16 have been fixed.

**Comment by lkosmid** [comment]
@federeghe Thank you for applying the suggestions! I only have a very minor comment for [#16](https://github.com/federeghe/chronovise/issues/16)

**Comment by lkosmid** [comment]
@federeghe Thank you for addressing all the comments. I don't have anything else, the review is complete. I have checked the last remaining item in the above checklist.
@danielskatz What are the next steps?

**Comment by danielskatz** [comment]
Thanks very much @lkosmid 

@federeghe , please archive the current version of the repository in zenodo or similar, and let me know the DOI.

**Comment by federeghe** [comment]
Zenodo DOI: 10.5281/zenodo.1404670

Thank you

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.1404670 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1404670" target="_blank">10.5281/zenodo.1404670</a> is the archive.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00711/joss.00711/10.21105.joss.00711.pdf)

**Comment by danielskatz** [comment]
👋  @arfon, over to you to finish the acceptance

**Comment by arfon** [comment]
@lkosmid - many thanks for your review here and to @danielskatz for editing this submission ✨ 

@federeghe - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00711 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00711/status.svg)](https://doi.org/10.21105/joss.00711)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00711">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00711/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00711/status.svg)](https://doi.org/10.21105/joss.00711)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
