### ISSUE TITLE
[PRE REVIEW]: Calliope: a multi-scale energy systems modelling framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#712]
**Submitting author:** @sjpfenninger (<a href="http://orcid.org/0000-0002-8420-9498">Stefan Pfenninger</a>)
**Repository:** <a href="https://github.com/calliope-project/calliope" target ="_blank">https://github.com/calliope-project/calliope</a>
**Version:** v0.6.0
**Editor:** @jedbrown
**Reviewers:** @mdoucet, @gonsie, @ecotillasanchez

**Author instructions**

Thanks for submitting your paper to JOSS @sjpfenninger. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sjpfenninger if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #712 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
:wave: @katyhuff - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00712/joss.00712/10.21105.joss.00712.pdf)

**Comment by sjpfenninger** [comment]
Noticed a broken bibtex ref in the article proof and [pushed an update to fix it](https://github.com/calliope-project/calliope/commit/159664ba3623ea0134ed473836f296b4485547c8)

**Comment by katyhuff** [comment]
Hi @mdoucet and @gonsie -- - It seems to me you would be excellent reviewers for this submission. Are you willing to be assigned to review this software paper submission? We'll need at least two volunteers, but the more the merrier. Information about being a reviewer can be found here : http://joss.theoj.org/about#reviewer_guidelines .

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00712/joss.00712/10.21105.joss.00712.pdf)

**Comment by mdoucet** [comment]
I'll be happy to help review this submission.

**Comment by gonsie** [comment]
I am happy to help review this submission.

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@whedon add @mdoucet as reviewer
@whedon add @gonsie as reviewer
@whedon add @ecotillasanchez as reviewer

**Comment by whedon** [comment]
OK, @mdoucet is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @gonsie as reviewer

**Comment by whedon** [comment]
OK, @gonsie is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @ecotillasanchez as reviewer

**Comment by whedon** [comment]
OK, @ecotillasanchez is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/825. Feel free to close this issue now!
