### ISSUE TITLE
[PRE REVIEW]: HelpMe Command Line Helper Utility

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#713]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/vsoch/helpme" target ="_blank">https://www.github.com/vsoch/helpme</a>
**Version:** 0.0.2
**Editor:** @arfon
**Reviewers:** @iljah, @rougier

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @karthik - the submitting author suggested you as the handling editor

**Comment by vsoch** [comment]
Thanks @whedon and :wave: @arfon ! The article proof looks good!

**Comment by karthik** [comment]
Thanks @vsoch I'll update this thread with more information once I've done some initial checks. Stay tuned.

**Comment by vsoch** [comment]
Awesome thank you @karthik ! Please take the time that you need, and I look forward to our discussion.

**Comment by karthik** [comment]
@arfon @vsoch I did an initial review and it looks like this would be better suited for someone like @katyhuff or @jakevdp if they have the bandwidth.

**Comment by vsoch** [comment]
hey @arfon @katyhuff @jakevdp this is almost a month old... ping!

**Comment by katyhuff** [comment]
Hi all, I'm sorry to say I don't have the bandwidth this month.

**Comment by arfon** [comment]
Hi @vsoch - sorry this is taking a while. While we're waiting for an editor to pick this up could you take a look at the reviewer list and suggest a few folks? https://bit.ly/joss-reviewers

**Comment by vsoch** [comment]
Sure! I'll choose Python / HPC / and or API expertise for now, since the tool is so general. Ping @rougier and @krother and @ctb @iljah and @diegoenry @adamhsparks @jhollist @noamross

**Comment by vsoch** [comment]
No worries @katyhuff ! Thanks for your response, and hang in there :)

**Comment by rougier** [comment]
I'm available for review.

**Comment by noamross** [comment]
I am not available to review, and in any case Python is not one of my programming languages.

**Comment by iljah** [comment]
I can also review.

**Comment by adamhsparks** [comment]
Looks nice, but I'm a one trick pony for programming languages and Python isn't one of them.

**Comment by vsoch** [comment]
@arfon would @iljah or @rougier be suitable to start the review?

**Comment by diegoenry** [comment]
I’m up to reviewing, just let me know the deadlines.

Envoyé de mon iPhone

Le 12 juin 2018 à 21:50, Vanessa Sochat <notifications@github.com<mailto:notifications@github.com>> a écrit :


@arfon<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farfon&data=02%7C01%7C%7Caf977cc10c0044b46db208d5d09db5ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636644298126072060&sdata=3cmyItaGgejbsYxsdZpAcvstZ5ELxT1wygNK5yqJx2Y%3D&reserved=0> would @iljah<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Filjah&data=02%7C01%7C%7Caf977cc10c0044b46db208d5d09db5ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636644298126072060&sdata=QdbZlGvW%2BwWB%2FSzXysOMaOWQns9jOUFpqUrBIokXEJQ%3D&reserved=0> or @rougier<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frougier&data=02%7C01%7C%7Caf977cc10c0044b46db208d5d09db5ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636644298126072060&sdata=1TKjuOfgvfLWJNtmR7%2BitQijV0odj3WAtc5A7bBfloI%3D&reserved=0> be suitable to start the review?

**Comment by vsoch** [comment]
@arfon that's three!! :D @diegoenry I would bet the deadlines are pretty flexible, it's already been a month and we are still at timepoint zero, haha :) I am so grateful for your offering to do the review, and although it's not my decision, I would advocate for giving the time that is needed.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @iljah as reviewer

**Comment by whedon** [comment]
OK, @iljah is now a reviewer

**Comment by arfon** [comment]
@whedon add @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/775. Feel free to close this issue now!

**Comment by arfon** [comment]
@vsoch, @iljah, @rougier - please head over to #775 for the actual review issue. @diegoenry - thanks for volunteering - I think we should be OK with just two reviewers.
