### ISSUE TITLE
[PRE REVIEW]: quhomology: Calculation of Homology of Quandles, Racks, Biquandles and Biracks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#714]
**Submitting author:** @ansgarwenzel (<a href="http://orcid.org/0000-0001-7154-1590">Ansgar Wenzel</a>)
**Repository:** <a href="https://github.com/ansgarwenzel/quhomology" target ="_blank">https://github.com/ansgarwenzel/quhomology</a>
**Version:** 1.1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @ansgarwenzel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ansgarwenzel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @karthik - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
👋 @karthik - any chance we can assign some reviewers to get this moving along?

**Comment by karthik** [comment]
@arfon Several declines, have approached more folks.

**Comment by karthik** [comment]
@arfon Im not able to find anyone to review this. @ansgarwenzel do you have any suggestions?

**Comment by ansgarwenzel** [comment]
@karthik 
I will think about it and ask around. It*s not the easiest, being at the intersection of package and algebraic knot theory

**Comment by karthik** [comment]
@ansgarwenzel It's been very hard at my end as well. I'll keep looking but if you have any potential users in mind (without any conflicts of interest) please suggest names/github handles.

**Comment by akhmerov** [comment]
@labarba thanks for the invitation, but unfortunately this is too far
outside of my domain that I don't feel knowledgeable enough to review even
the basic domain-specific aspects.

**Comment by labarba** [comment]
Thanks, Anton! I believe I read "homology" and thought "topology" 😬

**Comment by labarba** [comment]
👋 @ansgarwenzel Since you already published a **Software Metapaper** in JORS, would this submission (if accepted) amount to a duplicate publication of the same work?
https://openresearchsoftware.metajnl.com/articles/10.5334/jors.53/

**Comment by labarba** [comment]
We haven't heard from you in a while, @ansgarwenzel — If you still want us to go ahead with assigning an editor and looking for reviewers, I would ask that you justify how this submission is set apart from the JORS paper, and confirm that we're not looking at duplicate publication of the same work. Thanks!

**Comment by poulson** [comment]
@karthik I could review this given a bit of time. I've spent some time thinking about de Rham cohomology and it seems that the core of the project is an adaptation of Gaussian elimination (which I have definitely spent some time thinking about!).

**Comment by poulson** [comment]
Hi @karthik. I can review this if you would like.

**Comment by labarba** [comment]
Before we start the review, I would like a response from the authors on my question from 22 days ago:

> justify how this submission is set apart from the JORS paper, and confirm that we're not looking at duplicate publication of the same work

**Comment by labarba** [comment]
Since the authors have not responded to my query, I will mark this as "paused" for now — ping `@openjournals/joss-eics` to continue in consideration.

**Comment by labarba** [comment]
Hello, @ansgarwenzel — We had a discussion in the editorial board about your submission, and decided that publication in JOSS here would indeed constitute a duplicate publication, and the submission should be withdrawn.
