### ISSUE TITLE
[PRE REVIEW]: suppdata: loading SUPPlementary DATA into R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#715]
**Submitting author:** @willpearse (<a href="http://orcid.org/0000-0002-6241-3164">William D Pearse</a>)
**Repository:** <a href="https://github.com/ropensci/suppdata" target ="_blank">https://github.com/ropensci/suppdata</a>
**Version:** v1.0-0
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @willpearse. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@willpearse if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #715 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @willpearse - please take a look at http://joss.theoj.org/about#paper_structure for the required YAML fields for `paper.md` - it looks like you're missing a `bibliography` field.

You can ask @whedon to recompile your paper with `@whedon generate pdf`

**Comment by willpearse** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00715/joss.00715/10.21105.joss.00715.pdf)

**Comment by willpearse** [comment]
@arfon Thanks for spotting that, and I'm sorry to have made such a silly mistake.

In case it's gotten lost in the system, `suppdata` has been reviewed as an ROpenSci package (https://github.com/ropensci/onboarding/issues/195).

Thanks again for your time.

**Comment by arfon** [comment]
Thanks @willpearse - could you take a look a reformatting the code examples in the paper so they wrap properly?

**Comment by willpearse** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00715/joss.00715/10.21105.joss.00715.pdf)

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1238947" target="_blank">10.5281/zenodo.1238947</a> is the archive.

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/721. Feel free to close this issue now!

**Comment by willpearse** [comment]
Fantastic. Thank you very much for your help!
