### ISSUE TITLE
[PRE REVIEW]: Cylc: a Workflow Engine for Automating Cycling Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#716]
**Submitting author:** @hjoliver (<a href="http://orcid.org/0000-0002-5715-5279">Hilary Oliver</a>)
**Repository:** <a href="https://github.com/cylc/cylc" target ="_blank">https://github.com/cylc/cylc</a>
**Version:** cylc-7.6.1
**Editor:** @arfon
**Reviewers:** @sarats, @Chilipp

**Author instructions**

Thanks for submitting your paper to JOSS @hjoliver. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@hjoliver if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #716 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0     72      0 --:--:-- --:--:-- --:--:--    72
Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by hjoliver** [comment]
From the list of potential reviewers @ygrange looks good (scientific workflow management, Python).

**Comment by hjoliver** [comment]
Otherwise reviewers listing "atmospheric science" or possibly "HPC" could work (these are Cylc's core application areas thus far).

**Comment by ygrange** [comment]
I'm not too familiar with the background application field (maybe I'm wrong and we could actually apply it to Astronomy; haven't really thought very deeply about it tbh) so I may mostly comment on the more technical details. Wouldn't mind having an in-depth look at it though. I will however be unavailable untill the end of next week.

**Comment by hjoliver** [comment]
@arfon - the error says "could not find paper.bib", but that file is in the same location as paper.md in the repostory (which is "doc/joss-paper"). The pandoc command given in whedon docs works when I run it manually in that directory.  The instruction for authors does not say a specific location is required, or have I missed something?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00716/joss.00716/10.21105.joss.00716.pdf)

**Comment by ygrange** [comment]
So in principle I'd happily do it but I will be looking at it from the direction of a different field (so I will judge the documentation on how clear it is for me as an outsider for example). I leave it to you to judge if that's an angle you want to have covered (not sure of joss allows multiple reviewers to cover different angles). 

Going offline for a week now and I'll see what's expected from me next week :)

**Comment by hjoliver** [comment]
Thanks @ygrange.  Regarding documentation, I don't think you'll find it too weather-specialized, except perhaps for the introductory section of the User Guide which dates back to the inception of the project. I'm not sure if this is good news or bad for reviewers, but Cylc is a reasonably large, mature application, so the User Guide is quite big.  I suggest you run through one of the presentations here https://cylc.github.io/cylc/documentation.html first as a quick overview.

**Comment by arfon** [comment]
> From the list of potential reviewers `@ygrange` looks good (scientific workflow management, Python).

@hjoliver - I'd like to get an extra reviewer for this submission. Could you take a look at this list and suggest some others? https://bit.ly/joss-reviewers

Also, if you know the GitHub handles of any other potential good reviewers feel free to mention them here.

**Comment by hjoliver** [comment]
@arfon - from the list I could suggest @sarats and @Chilipp, who seem to be involved in Earth System Modeling, one of Cylc's primary use cases currently.

If they don't work out I can try to find others, but unfortunately most of my immediate contacts in the subject area are already Cylc users or developers (which is presumably not OK?)

**Comment by Chilipp** [comment]
@arfon and @hjoliver - Looks interesting, I would be willing to review it

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @sarats as reviewer

**Comment by whedon** [comment]
OK, @sarats is now a reviewer

**Comment by arfon** [comment]
@whedon add @Chilipp as reviewer

**Comment by whedon** [comment]
OK, @Chilipp is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/737. Feel free to close this issue now!

**Comment by arfon** [comment]
@sarats, @Chilipp - many thanks for agreeing to help out! Please head over to #737 to carry out the review.

**Comment by hjoliver** [comment]
@sarats, @Chilipp - many thanks from me too.
