### ISSUE TITLE
[REVIEW]: sumo: Command-line tools for plotting and analysis of ab initio calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#717]
**Submitting author:** @utf (<a href="http://orcid.org/0000-0002-4486-3321">Alex Ganose</a>)
**Repository:** <a href="https://github.com/SMTG-UCL/sumo" target ="_blank">https://github.com/SMTG-UCL/sumo</a>
**Version:** v1.0.4
**Editor:** @kyleniemeyer
**Reviewer:** @jarvist, @cfgoldsmith
**Archive:** <a href="https://doi.org/10.5281/zenodo.1338124" target="_blank">10.5281/zenodo.1338124</a>

## Status

[![status](http://joss.theoj.org/papers/d12ca1f4198dffa2642a30b2ab01e16d/status.svg)](http://joss.theoj.org/papers/d12ca1f4198dffa2642a30b2ab01e16d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d12ca1f4198dffa2642a30b2ab01e16d"><img src="http://joss.theoj.org/papers/d12ca1f4198dffa2642a30b2ab01e16d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d12ca1f4198dffa2642a30b2ab01e16d/status.svg)](http://joss.theoj.org/papers/d12ca1f4198dffa2642a30b2ab01e16d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SMTG-UCL/sumo" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jarvist & @cfgoldsmith, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SMTG-UCL/sumo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.4)?
- [x] **Authorship:** Has the submitting author (@utf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SMTG-UCL/sumo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.4)?
- [x] **Authorship:** Has the submitting author (@utf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jarvist, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00717/joss.00717/10.21105.joss.00717.pdf)

**Comment by kyleniemeyer** [comment]
👋 @utf @jarvist @cfgoldsmith

For @jarvist & @cfgoldsmith, note that you each have a separate reviewer checklist above. Thanks for agreeing to review!

**Comment by utf** [comment]
@kyleniemeyer: I've just had a look through the conflict of interest page you linked in the previous issue. Jarvist and David Scanlon (@scanlond), the last author on this paper, were on a paper together back in 2016: https://aip.scitation.org/doi/abs/10.1063/1.4943973

**Comment by utf** [comment]
Actually, sorry for the confusion here, I was mistaken, @jarvist and @scanlond haven't actually worked on a paper together.

**Comment by kyleniemeyer** [comment]
@utf thanks for checking!

**Comment by jarvist** [comment]
I have however co-authored a few times with @ajjackson back when were were in the same group. If @kyleniemeyer is happy, I'm happy! I certainly do know these people, but I don't think that's any problem in terms of writing a fair and open review of these codes.

**Comment by kyleniemeyer** [comment]
@jarvist I can see the partial overlap—thanks for being upfront about it. I agree that these connections should not be an issue.

**Comment by kyleniemeyer** [comment]
Hey @jarvist @cfgoldsmith, just wanted to check in on the status of your reviews.

**Comment by cfgoldsmith** [comment]
Thanks, Kyle. As we discussed earlier, I am not going to install the software, but will provide feedback on their objectives within the broader computational chemistry community. I don't see where to put that info. Also, since I'm not installing the software, would you prefer that I check the Funtionality boxes or leave them unchecked?

**Comment by jarvist** [comment]
Successfully installed & am slowly working my way through its functionality. It's quite a broad package with multiple features, which really requires some 'live' electronic structure calculations to throw it against.

**Comment by kyleniemeyer** [comment]
@cfgoldsmith yes, that's fine. Aside from checking off items, you can give your feedback to @utf here directly. As for the functionality items, you can just check off if there is evidence of them.

**Comment by kyleniemeyer** [comment]
@jarvist thanks for the update!

**Comment by utf** [comment]
Hi guys. Just checking if there is any update on the status of the reviews?

Please get in touch if you have any comments for me.

**Comment by cfgoldsmith** [comment]
Hi. Here is my review:
“sumo currently only supports VASP” this strikes me as rather curious, since VASP is one of the more expensive packages — even for academics. In the spirit of this journal, they should consider expanding their approach to include many of the open-source packages, such as GPAW, Orca, etc.
The authors fail to mention Molden, which blurs the line between command-line and gui, but is old and free and has much of the same functionality (though certainly not all).

The approach and examples is very specifically geared to solid state physics, even if they don’t explicitly say it. They should at least mention it. It would be helpful to elaborate on what future aspects they would consider, especially for the non solid-state community (e.g. what about electron density, molecular orbitals, charge distribution, etc).

Beyond that, the pack seems well developed, the graphics are appropriate and polished, and I think people will find it useful.

**Comment by jarvist** [comment]
Sumo does many different things - I haven't had time to try them all out yet! Here's a partial review, with some feedback. 

1) It wasn't immediately obvious what the code was for + what it did. 'Ab-initio' is a very general term. Making it clear that these tools are for reciprocal-space band structures / computational solid-state physics would help. 
Having used a few of the components, I think perhaps explicitly describing it as a convenience interface to the many dependent python packages / post-processing tools for VASP calculations is most descriptive. Sign-posting which of the many packages are being used 'under the hood' would also be useful,
i.e. something like
`An extensive framework for generating high-symmetry k-point paths,` by interfacing SeeK-path and SPGlib.  
I also think the tutorials in the online documentation should be signposted more clearly in the README, as the /tests /examples folder don't offer much by themselves.
I noticed several spelling errors / typos in the STDOUT of the tools.

2) The disk space requirements are very heavy. It became apparent upon installing where the name 'sumo' came from, but it might be an idea to alert the user in the README.md.
I required the following additional packages to be able to install under pip3 on Debian:-
` sudo apt-get install python3-pip python3-numpy `
The lack of python3-numpy was a little cryptic, pip3 just failed at some point. Perhaps it can be added as a check?
The Debian additions required Required 72 MB (this was on top of the Python3 runtime).
Installed by pip3, I ended up with 361 MB in .local/lib/python3.5/site-packages/

3) Tests: I'm not really sure what to do with the tests directory. 
Could you provide a 'runtests.py' in the root? Ideally you would add continuous integration. Reading the source of the tests, it's not obvious that they are tests, but more that they are examples where you can check by eye that some sensible results are produced. 
As Sumo does little computation by itself, maybe this is acceptable, but it should be documented and explained. But you could e.g. have a computational pipeline + at least automatically validate that an output file is produced.

Suggested (partial review) actions:-
- [ ] Improve `README.md`
- [ ] Spell check sources, particularly the output to the user (for examples, try grep'ing for 'eleemtns' 'possibily' 'indicies:')
- [ ] Clean up / document / implement tests

**Comment by utf** [comment]
@cfgoldsmith 

Thank you for your review.

We appreciate that VASP is a little exclusive which is unfortunate, however, it is very widely used in the field (there have been 25,000 papers published using the code in the last 10 years). Crucially VASP comes with a minimal toolchain, which motivated the development of this package.
We have intentionally designed Sumo to separate VASP-specific details from other elements in order to facilitate interfaces for open-source codes. Our team does not have much hands-on experience with the other codes that would most benefit from this, but contributions would be welcome from e.g. Abinit users to add these interfaces. We will add a section to the README which expressly invites this kind of assistance.

From what I can tell, Molden cannot directly load VASP output files and instead requires additional codes to convert the VASP output into a different format. Accordingly, I think Sumo and Molden occupy different niches. In particular, Molden is primarily focused on 3D visualisation which is not something we plan to support.

We agree that Sumo is currently geared towards the solid-state chemistry and physics communities (although the tools will work equally well for any molecular calculations performed in VASP). Sumo will likely remain focussed on the solid-state for the near future so we can make the mention of "solid-state" more prominent in the package descriptions if desired.

We appreciate that you found the package well developed and think others will find it useful. On this basis, are you able to complete the Review Checklist at the top of this page?

**Comment by utf** [comment]
@jarvist 

Thank you for looking at Sumo.

In response to your numbered points:

1. We agree that ab initio is a general term. As noted in our response to @cfgoldsmith, we will update the documentation to make it clear that this package is geared for solid state analysis.
  - We already mention all the packages used under the hood in the README but perhaps we could be more specific where each of these is implemented.
  - Do you have a specific suggestion as to how we should signpost the tutorials more clearly? The README contains quite a few links to the documentation already.
  - Thanks for noticing the typos, we will go make sure to fix those.

2. For the disk space requirements, unfortunately there isn’t much we can do about that as most of this comes from the package dependencies. We will instead add a warning to the “Requirements” section of the readme to highlight this.

3. Regarding tests: we already have a section in the documentation detailing how to run the tests (see https://github.com/SMTG-UCL/sumo#tests). To be clear, these are definitely testing the code base and are not provided as examples of how to run the code.  Furthermore, we already have continuous integration enabled using Travis CI (this is indicated by the “build: passing” button at the top of the README). It isn't really expected that general users will poke around the test and example directories, as they are encouraged to install the package from PyPI.

Thank you again for reviewing Sumo.

**Comment by cfgoldsmith** [comment]
Yes, happily. Well done.

**Comment by jarvist** [comment]
To be clear - I'm certainly not requesting any extra development in response to my review, just more + clearer signposting in the documentation.

Apologies for missing the CI - would it be possible to add a code-coverage badge? I will investigate the unit tests next week. A two line README.md in the tests directory would not go amiss, repeating the info in the main README.md.

**Comment by kyleniemeyer** [comment]
@jarvist @cfgoldsmith thanks for your reviews!

@utf please let us know when you've made changes in response to their comments, and specifically what changes you made. (If you open up issues or PRs on your own repository in response, you can link to them here to make it even easier.)

**Comment by ajjackson** [comment]
I have pushed an update to master that should address these review points. @utf has already assaulted the collection of typos.
Summary of changes pasted here from the commit message:
```
- Emphasise solid-state scope
- Emphasise use of other Python packages
- Add Contributing guidelines
- Raise links to Tutorial and Gallery
- Rework installation/requirements notes
- Add README to test directory
```
And "ab initio calculations" in the setup.py (i.e. for PyPI description) is replaced with "ab initio solid-state calculations".

**Comment by jarvist** [comment]
With these edits, `README.rst` is much more clear, and I think you have covered all of my partial review points. 

Running your unit tests as your documented 
`python3 -m unittest discover tests` 
in the pip-installed `~/.local/lib/python3.5/site-packages/sumo/` (maybe point users in this direction in the README?), resulted in:
``` 
Ran 97 tests in 3.198s

FAILED (failures=4, errors=14)
```
(Full STDOUT here: https://gist.github.com/jarvist/ae461f6dd22e1f989a0625bbf4b63f3f ) 

Most of the errors looked like it trying to find data sets (bz2 / gz) files, which might be hard-coded / not present in the repository?

**Comment by ajjackson** [comment]
Running from inside `~/.local/lib` is rather unorthodox, does it work from a cloned source directory?

**Comment by ajjackson** [comment]
@jarvist are the tests working for you when they are run from the source folder? In the README we say "the unittests can be run (from the root directory of the project) ..."

The Travis logs show the process followed there, which simply clones the repo https://travis-ci.org/SMTG-UCL/sumo/jobs/402148229

**Comment by jarvist** [comment]
I'm travelling this week, so haven't had the opportunity to re-install a 'developer' version + try the tests from there.
 
It seems a bit strange that the tests ran partially. They seemed to be failing either because the datasets were not downloading(?) (permissions in the pip folder?), or that a python dependency on BZip2/Gzip was not present (assumed present but not specified in the package?).

**Comment by ajjackson** [comment]
Looking at the traceback more carefully, I don't think the tests you found are anything to do with Sumo. Sumo does not install tests to lib, and most of the messages refer to something called "monty"?

**Comment by ajjackson** [comment]
I believe we have now responded to all reviewer points, except for the suggestion to include a code-coverage badge. This is something we have considered, but it is going to be difficult to achieve _meaningful_ high coverage in a package that a) mostly consists of command line tools and b) mostly outputs graphics. At present the tests are focused on the internal data manipulation. It's achievable with some thought and effort, but not a priority for us at this point.

**Comment by kyleniemeyer** [comment]
Hi @jarvist I noticed a few of your checklist items unfilled above—are you satisfied with the changes they have made?

**Comment by ajjackson** [comment]
@jarvist did you have any more issues or can we wrap this up?

**Comment by jarvist** [comment]
If @ajjackson could add some instructions in the README / etc. for how a standard user (following the supplied installation instructions) can run the tests, then I'll consider it closed. 

I'm generally happy with the package; I'll now go and review the `paper.md`.

**Comment by utf** [comment]
Hi @jarvist, standard users are not expected to run the tests. If you install from pip directly using the `pip3 install --user sumo` command the test data will not be installed (as is standard for all pip installations).

Developers are expected to run the tests through the instructions in the README.

To make this clear will we state that the developer installation should occur from a clone of the repository, and that tests can only be run from a developer installation.

**Comment by jarvist** [comment]
Mainly a question for the editor @kyleniemeyer, currently `paper.md` lists David Scanlon (the PI) as final + corresponding author. This would be standard for a scientific publication, but (from the commit history) they do not appear to have directly contributed to the code. 
The current JOSS guidelines call for "A list of the authors of the software" (https://joss.readthedocs.io/en/latest/review_criteria.html#the-joss-paper), does this include non directly code-writing authors who may have contributed to the design of the package etc. ?

Generally I thought `paper.md` was useful + well written, but I think it could do with an extra sentence or two of introduction, similar to how `README.md` now reads. It just needs a bit more of an introduction explaining that these tools are for solid-state / band-structure calculations, making the 'statement of need' more clear.

**Comment by jarvist** [comment]
Re: tests
I'd recommend merging 'Developer installation' with 'Tests', and making it clear that a developer installation is a pre-requisite:
 https://github.com/SMTG-UCL/sumo/tree/6de16a00e2a488180bfafc34439d969737bd1854#developer-installation

The text around there could be improved - from inspecting the pip command, you are assuming that the reader would first clone the GitHub repository, and then run the pip command from that location as pwd.
Similar with the preceding sentence on building the documentation.

**Comment by ajjackson** [comment]
Good point! Have reworked the README: *Tests* and *Documentation* are now subsections of *Developer installation* and are explicit that you need to have the files.

**Comment by kyleniemeyer** [comment]
@jarvist regarding the authorship question, non-code intellectual contributions make someone eligible for authorship, as long as all authors agree on the author list.

**Comment by utf** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00717/joss.00717/10.21105.joss.00717.pdf)

**Comment by utf** [comment]
@jarvist we've updated the paper to clarify in several places, including the paper title, that the the code is specifically for solid-state materials analysis.

Does that look ok now?

**Comment by jarvist** [comment]
Adding an explicit:
```
git clone https://github.com/SMTG-UCL/sumo.git
cd sumo
```
To the quoted shell commands for the developer installation would make it even clearer.

But I'm happy to sign off on this JOSS review as done!

**Comment by kyleniemeyer** [comment]
@utf only one comment on the paper before we accept: the reference for Togo 2013 is missing some info, like a DOI or URL. Once you've added that and confirmed the paper looks all good, then please archive your entire repo and provide the associated DOI here.

**Comment by ajjackson** [comment]
Done! Have also added a note to Dev installation that *"Regular users can skip this section!"* and added explanation of `--user` flag.

**Comment by ajjackson** [comment]
Re: Spglib there doesn't seem to be a permanent identifier, but I have added the website https://atztogo.github.io/spglib/. It's available in the waybackmachine, at least!

**Comment by ajjackson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00717/joss.00717/10.21105.joss.00717.pdf)

**Comment by utf** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by utf** [comment]
@kyleniemeyer We've made the changes you asked for. The repository DOI is 10.5281/zenodo.1338124 (https://doi.org/10.5281/zenodo.1338124).

**Comment by kyleniemeyer** [comment]
OK @arfon this paper is now accepted

**Comment by arfon** [comment]
@jarvist, @cfgoldsmith - many thanks for your reviews here and to @kyleniemeyer for editing this submission ✨ 

@utf - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00717 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00717/status.svg)](https://doi.org/10.21105/joss.00717)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00717">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00717/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00717/status.svg)](https://doi.org/10.21105/joss.00717)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
