### ISSUE TITLE
[PRE REVIEW]: TrajectoryMergeAssist

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#723]
**Submitting author:** @avimanyu786 (<a href="http://orcid.org/0000-0003-4806-2238">Avimanyu Bandyopadhyay</a>)
**Repository:** <a href="https://github.com/avimanyu786/TrajectoryMergeAssist/" target ="_blank">https://github.com/avimanyu786/TrajectoryMergeAssist/</a>
**Version:** v1.1.03
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @avimanyu786. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@avimanyu786 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #723 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by avimanyu786** [comment]
I have been trying to edit the paper.bib file. I have tried different structures but I can't get it compiled. I also tried using a single reference. Please help.

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #723 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:45:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #723 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #723 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0    162      0 --:--:-- --:--:-- --:--:--   164
Error reading bibliography ./paper.bib (line 10, column 5):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00723/joss.00723/10.21105.joss.00723.pdf)

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00723/joss.00723/10.21105.joss.00723.pdf)

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00723/joss.00723/10.21105.joss.00723.pdf)

**Comment by avimanyu786** [comment]
I've been able to narrow down the issues and was finally been able to generate a pdf. But the references section is still showing as empty. I'm also unable to get my second affiliation to the next line. Awaiting your kind assistance. I'm really sorry about so many comments on this thread.

The references I'm trying to include are:

1. [MDTraj: A Modern Open Library for the Analysis of Molecular Dynamics Trajectories](https://www.cell.com/biophysj/fulltext/S0006-3495(15)00826-7)

2. [Scalable Algorithms for Molecular Dynamics Simulations on Commodity Clusters](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.98.2121)
   
3. [D. E. Shaw Research | Desmond](https://www.deshawresearch.com/resources_desmond.html)

4. [Schrödinger | Maestro](https://www.schrodinger.com/maestro)
  
I would like @HadrienG to please review my paper submission. Thank you.

@whedon assign @HadrienG as reviewer

**Comment by avimanyu786** [comment]
@whedon assign @HadrienG as reviewer

**Comment by whedon** [comment]
I'm sorry @avimanyu786, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by avimanyu786** [comment]
Sorry I wasn't aware of that. Requesting the editors to please help me. Thank you.

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00723/joss.00723/10.21105.joss.00723.pdf)

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00723/joss.00723/10.21105.joss.00723.pdf)

**Comment by avimanyu786** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00723/joss.00723/10.21105.joss.00723.pdf)

**Comment by arfon** [comment]
Hi @avimanyu786 - thanks for your submission to JOSS. Unfortunately this package doesn't meet our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, on this criteria:

> - Minor, 'utility' packages, including 'thin' API clients are not acceptable

The editorial team have decided that this submission falls under the 'minor utility' criteria and is therefore not acceptable to JOSS.
