### ISSUE TITLE
[PRE REVIEW]: mbir: Magnitude-Based Inferences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#725]
**Submitting author:** @kdpeterson51 (<a href="http://orcid.org/0000-0003-0128-5282">Kyle Peterson</a>)
**Repository:** <a href="https://github.com/kdpeterson51/mbir" target ="_blank">https://github.com/kdpeterson51/mbir</a>
**Version:** 1.3
**Editor:** @leeper
**Reviewers:** @kellieotto

**Author instructions**

Thanks for submitting your paper to JOSS @kdpeterson51. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kdpeterson51 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #725 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: tags (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@kdpeterson51 - please take a look at the guidelines for the paper structure http://joss.theoj.org/about#paper_structure and update yours accordingly.

In addition, this package doesn't look like it has a README, license etc. You might want to take a look at the [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines) to see what your package will be evaluated on.

**Comment by kdpeterson51** [comment]
Sincere apologies, Afron. 

Tags have been added  to YAML header, README and LICENSE files are now up-to-date.

**Comment by kdpeterson51** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by kdpeterson51** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00725/joss.00725/10.21105.joss.00725.pdf)

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
Hi, @kdpeterson51. Thanks for your submission. A couple of preliminary things here before we get started:

1. Can you clarify the license for the functions mentioned in [COPYRIGHT](https://github.com/kdpeterson51/mbir/blob/master/mbir/inst/COPYRIGHT)? Do you have permission to redistribute this code from the original author? If so, under what license?

2. It looks like you are generating your R [NAMESPACE file](https://github.com/kdpeterson51/mbir/blob/master/mbir/NAMESPACE) by hand rather than through roxygen. Can you delete and reinitialize using `devtools::document()`?

3. Should [the vignette](http://www.mbir-project.us/mbir.pdf) be included in a typical `/vignettes` directory in the package itself?

4. Do you have any suggested reviewers for the package?

**Comment by kdpeterson51** [comment]
Hi @leeper. Thank you very much for your assistance.

1. The copyright was obtained by written permission to use those cited MS Excel spreadsheets.

2. Original NAMESPACE file has been deleted and replaced with `devtools` version.

3. Vignette folder is now up-to-date within `/mbir` folder.

4. We do not have any suggested reviewers at this time.

**Comment by kdpeterson51** [comment]
Your suggestions are appreciated, @leeper. The [COPYRIGHT](https://github.com/kdpeterson51/mbir/blob/master/mbir/inst/COPYRIGHT) file has been updated to improve the language.

**Comment by leeper** [comment]
@kellieotto Would you be interested in reviewing this software for JOSS?

**Comment by kellieotto** [comment]
@leeper Yes, happy to review this.

**Comment by leeper** [comment]
@whedon assign @kellieotto as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kellieotto

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/746. Feel free to close this issue now!
