### ISSUE TITLE
[REVIEW]: mlpack 3: a fast, flexible machine learning library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#726]
**Submitting author:** @rcurtin (<a href="http://orcid.org/0000-0002-9903-8214">Ryan Curtin</a>)
**Repository:** <a href="https://github.com/mlpack/mlpack" target ="_blank">https://github.com/mlpack/mlpack</a>
**Version:** v3.0.2
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @rasbt, @MikeInnes, @mlgill
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1292120" target="_blank">10.5281/zenodo.1292120</a>

## Status

[![status](http://joss.theoj.org/papers/f9fb80cf56e79edd4d87e5cf7c5f1759/status.svg)](http://joss.theoj.org/papers/f9fb80cf56e79edd4d87e5cf7c5f1759)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f9fb80cf56e79edd4d87e5cf7c5f1759"><img src="http://joss.theoj.org/papers/f9fb80cf56e79edd4d87e5cf7c5f1759/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f9fb80cf56e79edd4d87e5cf7c5f1759/status.svg)](http://joss.theoj.org/papers/f9fb80cf56e79edd4d87e5cf7c5f1759)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mlpack/mlpack" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rasbt & @MikeInnes & @mlgill, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mlpack/mlpack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v3.0.0)?
- [x] **Authorship:** Has the submitting author (@rcurtin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mlpack/mlpack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v3.0.0)?
- [x] **Authorship:** Has the submitting author (@rcurtin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mlpack/mlpack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v3.0.0)?  
- [x] **Authorship:** Has the submitting author (@rcurtin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed? 
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.) 

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution. 
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @rasbt, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00726/joss.00726/10.21105.joss.00726.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@rcurtin this is where the review process takes place. @mlgill @rasbt @MikeInnes you have tickboxes at the top here to guide the review process. You can leave comments here and for larger issues we encourage you to open issues on the project repository and link to them here. Let me know if you have any questions.

**Comment by rcurtin** [comment]
Sounds good---do let me know if there is anything required from me during the reviews.

In openjournals/joss#406, I opened an issue about this paper.  Authors 4 and 5 (Sumedh and Yannis) should have no affiliation, but I could not figure out a way to get this behavior.

**Comment by rasbt** [comment]
Sounds good!

@rcurtin I will try to go through the checklist chronologically throughout this and next week. If I have comments/suggestions, I will open those as issues in the mlpack GitHub repo as suggested by Joss.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @rstolyarov as reviewer

**Comment by whedon** [comment]
OK, @rstolyarov is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon yep I know, told me the other day :) I have updated the checklists manually already.

**Comment by rcurtin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00726/joss.00726/10.21105.joss.00726.pdf)

**Comment by rcurtin** [comment]
I've redone the paper PDF to have an explicit "None" affiliation for unaffiliated authors, but if openjournals/whedon#23 is merged I will update the paper.

**Comment by mlgill** [comment]
Have requested dependency and installation information be added to main website, issue is [here](https://github.com/mlpack/mlpack/issues/1404).

**Comment by mlgill** [comment]
@arfon @rcurtin I noticed the version on GitHub has been bumped to 3.0.1 (our checklist says 3.0.0). Is there somewhere else that I should verify that the update has been made?

**Comment by Kevin-Mattheus-Moerman** [comment]
@mlgill thanks for pointing that out. We'll request to get that fixed before acceptance. By the way please address editorial comments in this issue to me directly.

**Comment by rasbt** [comment]
@rcurtin have begun the review and bumped into an issue with the installation instructions (https://github.com/mlpack/mlpack/issues/1406), would be nice if you could take a look at it some time. Other than that, I found a very minor issue with the copyright info in the copyright & license files being out of sync (https://github.com/mlpack/mlpack/issues/1405).

**Comment by rcurtin** [comment]
Hi there @mlgill and @rasbt, thanks for your comments.  I've addressed each of the issues you opened (mlpack/mlpack#1403, mlpack/mlpack#1404, mlpack/mlpack#1405, mlpack/mlpack#1406)---let me know if everything is handled to your satisfaction.

You are right that we have released 3.0.1 (it's a pretty incremental release).  We can update the version in the paper, but maybe it is good to wait until the review process is done---we may release 3.0.2 (another bugfix release) between now and then.  Personally given the lack of serious changes between 3.0.1 and 3.0.0, I think it would be nicer to release the paper as 3.0.0, since that's a nicer "round" number.  But I don't know the JOSS policy on such things, so let me know what you'd like me to do or if anything is needed from my end. :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@rcurtin our policy is that the version number should reflect the state of the reviewed software. So if you implement fixes in 3.0.2 relevant to the review then that should be the version number for the paper.

**Comment by rcurtin** [comment]
Your call, either way is fine with me. :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@mlgill @rasbt thanks for your comments so far. I understand @rcurtin has been addressing some of your comments. Can you give an update as to where we stand? Thanks :rocket:

**Comment by Kevin-Mattheus-Moerman** [comment]
@MikeInnes @rstolyarov can we expect feedback from your end shortly too? Thanks :robot:

**Comment by MikeInnes** [comment]
I've checked off what I can verify, and things look generally good, but I haven't tried to run things locally yet. Are there build instructions оr binaries for OS X, or is this a Linux-only project?

**Comment by rcurtin** [comment]
Builds fine on OS X.  An old version of mlpack (2.2.5) is available via Homebrew, but it's not too hard to build---should be just `cmake ../ && make && make install` basically; see http://mlpack.org/docs/mlpack-3.0.1/doxygen/build.html.  The Linux build instructions should also work fine for OS X.

**Comment by rasbt** [comment]
@Kevin-Mattheus-Moerman 

> Can you give an update as to where we stand?

I am still in the process of running the software on examples (testing the functionality) but I should be able to wrap this review up on/shortly after the weekend

**Comment by rasbt** [comment]
To provide a more concrete heads-up (and a reference for me to stay on track): The installation eventually went smoothly and the software works as expected. 

I was able to check off most of the things. The remaining items are

- Version number: I assume we should wait until the other reviewers finished the technical review in case there will be additional changes requested
-  Installation: just two tiny changes that are currently being addressed https://github.com/mlpack/mlpack/issues/1406 and https://github.com/mlpack/mlpack/issues/1416
- Functionality documentation: also here, only two minor documentation fixes remaining, https://github.com/mlpack/mlpack/issues/1419 and https://github.com/mlpack/mlpack/issues/1418

**Comment by mlgill** [comment]
@Kevin-Mattheus-Moerman 

I am still in the process of getting the Python bindings installed. From some of @rasbt's comments on the repo issues, it seems I am not the only one. I will have to work on it later this week.

@rcurtin Thanks for updating the DOIs. Can you rebuild the PDF so I can look at that directly? Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00726/joss.00726/10.21105.joss.00726.pdf)

**Comment by rcurtin** [comment]
Thanks reviewers for your attention to detail.  We've done our best to make the build and installation process as easy as possible, but there is always some level of trickiness at the border of C++ and Python (and I'm sure it will get worse as we add other languages...).

We'll merge mlpack#1421 soon and this should fix the rest of the open issues.

**Comment by rasbt** [comment]
@Kevin-Mattheus-Moerman 

happy to let you know that all my issues were addressed in the recent merge of PR [mlpack/mlpack#1421](https://github.com/mlpack/mlpack/pull/1421). Aside from bumping the version to 3.0.2 in the paper and linking to the 3.0.2 archive (I think Joss uses Zenodo?; I think this should probably be done after the other reviewers finished the review, though), I am happy to approve this submission :)

**Comment by MikeInnes** [comment]
Looks good to me too!

**Comment by mlgill** [comment]
@Kevin-Mattheus-Moerman It looks like someone may have marked the installation issues under my name by mistake, but I can confirm that those items are complete. As @rasbt mentioned, the version bump is the only thing remaining. Thanks!

**Comment by rcurtin** [comment]
Hello reviewers, thank you so much for your comments.  We've released mlpack 3.0.2 last week that addresses all the issues.  Is there anything else needed from our end?

Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. It looks like we are all set! @mlgill @MikeInnes @rasbt thanks for reviewing :tada: 

@rcurtin please can you provide the DOI to an archived version of the reviewed software? You can use a service like [Zenodo](https://zenodo.org/), let me know if you have questions (see also https://guides.github.com/activities/citable-code/).

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon can you increment the version here to 3.0.2 and also proceed to accept once @rcurtin provides the DOI for the archived version? Thanks.

**Comment by rcurtin** [comment]
I've posted the library to Zenodo: https://zenodo.org/record/1292120.  Let me know if anything is needed from the mlpack end.  Thank you so much!

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon we are good to accept here

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1292120 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1292120" target="_blank">10.5281/zenodo.1292120</a> is the archive.

**Comment by arfon** [comment]
@rasbt, @MikeInnes, @mlgill - many thanks for your reviews here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@rcurtin - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00726 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00726/status.svg)](https://doi.org/10.21105/joss.00726)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00726/status.svg)](https://doi.org/10.21105/joss.00726)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
