### ISSUE TITLE
[REVIEW]: Dassie: a database of subject terms and hierarchies in the Library of Congress Subject Headings

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#728]
**Submitting author:** @mhucka (<a href="http://orcid.org/0000-0001-9105-5960">Michael Hucka</a>)
**Repository:** <a href="https://github.com/casics/dassie" target ="_blank">https://github.com/casics/dassie</a>
**Version:** v1.0.2
**Editor:** @jasonclark
**Reviewer:** @soodoku
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/68ed4e5e3e05718344da32f688ac841e/status.svg)](http://joss.theoj.org/papers/68ed4e5e3e05718344da32f688ac841e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/68ed4e5e3e05718344da32f688ac841e"><img src="http://joss.theoj.org/papers/68ed4e5e3e05718344da32f688ac841e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/68ed4e5e3e05718344da32f688ac841e/status.svg)](http://joss.theoj.org/papers/68ed4e5e3e05718344da32f688ac841e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/casics/dassie" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@soodoku, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jasonclark know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/casics/dassie">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.2)?
- [x] **Authorship:** Has the submitting author (@mhucka) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @soodoku it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00728/joss.00728/10.21105.joss.00728.pdf)

**Comment by arfon** [comment]
:wave: @soodoku - please complete your review when you get a chance.

**Comment by soodoku** [comment]
@arfon: working on it right now.

**Comment by soodoku** [comment]
Please fix: 

1. https://github.com/casics/dassie/issues/5
2. https://github.com/casics/dassie/issues/4
3. https://github.com/casics/dassie/issues/1

**Comment by arfon** [comment]
How are you getting along here @mhucka?

**Comment by mhucka** [comment]
Unfortunately I won't have time to do anything on this until later at least in the year. I don't know what the requirements are for the paper submission in terms of timing; if it's necessary to withdraw, then that's okay since I really don't have an alternative at this time.

**Comment by arfon** [comment]
@mhucka - that's ok. We'll just mark this as paused. I'll ping you again in a month or so?

**Comment by mhucka** [comment]
@arfon yes, thanks!

**Comment by arfon** [comment]
:wave: @mhucka - any chance you can pick this up again sometime soon?

**Comment by mhucka** [comment]
Hi there! I am hoping to have time at the end of this month.

**Comment by labarba** [comment]
👋  @mhucka — We haven't heard from you in a while. What's your status? Are you able to work on this revision soon?

**Comment by mhucka** [comment]
My apologies for the long radio silence, and thank you for your considerable patience.

Although editing the manuscript for the content & clarification issues would be easy, solving the Windows portability issues are likely to take an unpredictable amount of time. I really wish I could do it; I don't actually have a strong dislike of Windows, so that's not the problem – the problem is simply lack of time. I am forced to admit even to myself that it's just not going to happen anytime soon. I am in time bankruptcy.

What is the procedure in a situation like this? Withdraw the paper? Or something else?

**Comment by danielskatz** [comment]
We can just halt the review and withdraw the paper from the system.  I'll go ahead and do this.
