### ISSUE TITLE
[REVIEW]: PyCM: Multi class confusion matrix library in python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#729]
**Submitting author:** @sepandhaghighi (<a href="http://orcid.org/0000-0001-9450-2375">Sepand Haghighi</a>)
**Repository:** <a href="https://github.com/sepandhaghighi/pycm" target ="_blank">https://github.com/sepandhaghighi/pycm</a>
**Version:** v0.8.1
**Editor:** @arokem
**Reviewer:** @NickleDave
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1250175" target="_blank">10.5281/zenodo.1250175</a>

## Status

[![status](http://joss.theoj.org/papers/8268642abd7b142426722c0c39123ff4/status.svg)](http://joss.theoj.org/papers/8268642abd7b142426722c0c39123ff4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8268642abd7b142426722c0c39123ff4"><img src="http://joss.theoj.org/papers/8268642abd7b142426722c0c39123ff4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8268642abd7b142426722c0c39123ff4/status.svg)](http://joss.theoj.org/papers/8268642abd7b142426722c0c39123ff4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sepandhaghighi/pycm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@NickleDave, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sepandhaghighi/pycm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8.1)?
- [x] **Authorship:** Has the submitting author (@sepandhaghighi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by NickleDave** [comment]
review in progress, would say "accept with minor revisions".
added issue about documenting API.
https://github.com/sepandhaghighi/pycm/issues/16

**Comment by NickleDave** [comment]
added one other minor revision, asking for more specific example usages:
https://github.com/sepandhaghighi/pycm/issues/17

**Comment by arokem** [comment]
Thanks @NickleDave ! 

@sepandhaghighi : please let me know here when you've had a chance to address these comments!

**Comment by sepandhaghighi** [comment]
Hi

@NickleDave Thanks again for review ;-)

@arokem I fixed first issue and working on second

**Comment by NickleDave** [comment]
added two other issues, after those are closed, this should be ready to accept
https://github.com/sepandhaghighi/pycm/issues/19
https://github.com/sepandhaghighi/pycm/issues/18

**Comment by sepandhaghighi** [comment]
@NickleDave @arokem 
Thank you for your time
The issues have been fixed. ;-)

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00729/joss.00729/10.21105.joss.00729.pdf)

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00729/joss.00729/10.21105.joss.00729.pdf)

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00729/joss.00729/10.21105.joss.00729.pdf)

**Comment by NickleDave** [comment]
added two other issues, after those are closed, this should be ready to accept
https://github.com/sepandhaghighi/pycm/issues/19
https://github.com/sepandhaghighi/pycm/issues/18

**Comment by NickleDave** [comment]
@sepandhaghighi thank you!
@arokem LGTM

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00729/joss.00729/10.21105.joss.00729.pdf)

**Comment by arokem** [comment]
@sepandhaghighi : Great! I believe your paper is ready to be accepted.

At this point, please create a new release of the software and create an archive for it (e.g., using https://zenodo.org/). Once you have that, please reply here with the DOI, so we can set that as the archive to be included in the paper.

**Comment by sepandhaghighi** [comment]
@arokem 
Done ! 
10.5281/zenodo.1250175

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #729 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/729/paper/paper.md): could not find expected ':' while scanning a simple key at line 12 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:65:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00729/joss.00729/10.21105.joss.00729.pdf)

**Comment by arokem** [comment]
@whedon set  10.5281/zenodo.1250175 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1250175" target="_blank">10.5281/zenodo.1250175</a> is the archive.

**Comment by arokem** [comment]
@arfon : I think this paper is ready to go!

**Comment by arfon** [comment]
@NickleDave - many thanks for your review here and to @arokem for editing this one ✨ 

@sepandhaghighi - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00729 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00729/status.svg)](https://doi.org/10.21105/joss.00729)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00729/status.svg)](https://doi.org/10.21105/joss.00729)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by NickleDave** [comment]
Nice work @sepandhaghighi 
Have you thought about sharing PyCM on the scikit-learn mailing list (scikit-learn@python.org )? I bet a lot of people there would be interested
