### ISSUE TITLE
[PRE REVIEW]: PyNomaly

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#730]
**Submitting author:** @vc1492a (<a href="http://orcid.org/0000-0002-5279-4143">Valentino Constantinou</a>)
**Repository:** <a href="https://www.github.com/vc1492a/PyNomaly" target ="_blank">https://www.github.com/vc1492a/PyNomaly</a>
**Version:** v0.2.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @yzhao062

**Author instructions**

Thanks for submitting your paper to JOSS @vc1492a. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vc1492a if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00730/joss.00730/10.21105.joss.00730.pdf)

**Comment by arfon** [comment]
👋@vc1492a - it looks like you're missing references in this paper. Is there nothing you wish to cite?

**Comment by vc1492a** [comment]
@arfon I was under the impression that references should be included in ```paper.bib```. The examples [linked from the JOSS website](https://github.com/arfon/fidgit/tree/master/paper) show references in ```paper.bib``` and not in ```paper.md```. Should I also add my references to ```paper.md```?

**Comment by arfon** [comment]
@vc1492a - I think the issue is that you're not citing them directly (so they're not showing up in the compiled PDF). You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by vc1492a** [comment]
@afron thanks for the helpful link. I've updated my citations in ```paper.md```, let me know if it looks good to you.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00730/joss.00730/10.21105.joss.00730.pdf)

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@vc1492a - could you take a look at the list of potential reviewers above and suggest a few that might be appropriate for your submission? ☝️

**Comment by vc1492a** [comment]
@arfon I took a look at the list of potential reviewers. Here are my suggestions:

- jkahn
- desilinguist
- krother

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00730/joss.00730/10.21105.joss.00730.pdf)

**Comment by arfon** [comment]
@mlgill @sssomani - would you be willing to review this submission for JOSS?

**Comment by mlgill** [comment]
@arfon sorry, I don’t have much experience with this topic.

**Comment by arfon** [comment]
@nhejazi @fritzo - would you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
@jkahn - would you be willing to review this submission for JOSS?

**Comment by Kevin-Mattheus-Moerman** [comment]
@yzhao062 @betatim @aqibsaeed @rhiever would you be willing to review this submission for [JOSS](https://joss.theoj.org/about)? The [review process](https://joss.theoj.org/about#reviewer_guidelines) focuses largely on the software and a short paper. 

[--> The paper :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00730/joss.00730/10.21105.joss.00730.pdf)

[--> The project repo :floppy_disk: : <--](https://github.com/vc1492a/PyNomaly)

**Comment by yzhao062** [comment]
@Kevin-Mattheus-Moerman I am happy to review PyNomaly since I used it in one of my previous research. Just need to get familiar with the [review process](https://joss.theoj.org/about#reviewer_guidelines) :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @yzhao062 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @yzhao062

**Comment by Kevin-Mattheus-Moerman** [comment]
@yzhao062 great thanks. I've added you as reviewer and will attempt to recruit a few more. Let me know if you have questions about the review process. This issue here is a so called pre-review issue. Once we have sufficient reviewers we'll move on to a review issue where the actual review takes place. I'll ping you there when we are ready.  
The review process is guided by a set of tickboxes for each reviewer. Here is a nice example of a finished review process: https://github.com/openjournals/joss-reviews/issues/726
As you can see the reviewers comment in the review issue to provide feedback but also create PR's or issues on the project repository as well.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/845. Feel free to close this issue now!
