### ISSUE TITLE
[PRE REVIEW]: rsimsum: Summarise results from Monte Carlo simulation studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#732]
**Submitting author:** @ellessenne (<a href="http://orcid.org/0000-0002-8319-7624">Alessandro Gasparini</a>)
**Repository:** <a href="https://github.com/ellessenne/rsimsum/" target ="_blank">https://github.com/ellessenne/rsimsum/</a>
**Version:** 0.3.1
**Editor:** @leeper
**Reviewers:** @lebebr01

**Author instructions**

Thanks for submitting your paper to JOSS @ellessenne. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ellessenne if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #732 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0     66      0 --:--:-- --:--:-- --:--:--    67
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00732.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @karthik - would you be willing to edit this submission for JOSS?

**Comment by leeper** [comment]
@whedon assign @leeper as @editor

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@lebebr01 Would you be interested in reviewing this for JOSS?

**Comment by lebebr01** [comment]
@leeper I'm happy to help.

**Comment by leeper** [comment]
@whedon assign @lebebr01 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lebebr01

**Comment by leeper** [comment]
@lebebr01 Great. Thank you! The review issue and instructions are open at: https://github.com/openjournals/joss-reviews/issues/739 Please follow the checklist and let me know (on that thread) if you have any questions.
