### ISSUE TITLE
[REVIEW]: dit: a Python package for discrete information theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#738]
**Submitting author:** @Autoplectic (<a href="http://orcid.org/0000-0003-2149-9085">Ryan G. James</a>)
**Repository:** <a href="https://github.com/dit/dit" target ="_blank">https://github.com/dit/dit</a>
**Version:** v1.2.0
**Editor:** @arfon
**Reviewer:** @kczimm, @stsievert
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1255350" target="_blank">10.5281/zenodo.1255350</a>

## Status

[![status](http://joss.theoj.org/papers/ba78ef2d389a4954aab904b5fb53f18d/status.svg)](http://joss.theoj.org/papers/ba78ef2d389a4954aab904b5fb53f18d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ba78ef2d389a4954aab904b5fb53f18d"><img src="http://joss.theoj.org/papers/ba78ef2d389a4954aab904b5fb53f18d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ba78ef2d389a4954aab904b5fb53f18d/status.svg)](http://joss.theoj.org/papers/ba78ef2d389a4954aab904b5fb53f18d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dit/dit" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kczimm & @stsievert, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dit/dit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@Autoplectic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dit/dit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license? (well, a LICENSE.txt file)
- [x] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@Autoplectic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kczimm, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00738/joss.00738/10.21105.joss.00738.pdf)

**Comment by kczimm** [comment]
@afron I am still testing the functionality of this software package. In the meantime, I've a few questions. I'm not familiar with DOI or how to answer the following question: "Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?" I didn't see anything in the reviewer guidelines that could help my understanding of this question. Also, my minor feedback for the authors at this time is to increase the statement of need and intended audience in their documentation. Is this minor feedback worth creating an issue in their repository? Thanks in advance for the help.

**Comment by stsievert** [comment]
@Autoplectic I'm guessing @chebee7i is Christopher J. Ellison and James P. Crutchfield is your advisor. Is that correct?

**Comment by stsievert** [comment]
I've gone through this repo, and have a couple comments. This software looks good and almost ready for acceptance, but I have a couple comments.

* I didn't see a clear statement of need in the paper or in the docs. This should clearly list the problems your software solves (not just the functions it provides) and the target audience. https://github.com/dit/dit/issues/141
* I didn't see any DOIs linked in `paper.bib` though the references were complete (and I would consider suitable for another academic journal). @afron is this acceptable?
* I didn't see any guidelines for users to contribute to your software. I think this is most often in CONTRIBUTING.md, which GitHub has support for.
* The dependency list confused me, especially the optional dependencies. There weren't any reasons why some dependencies were optional, and some of them were out of date. I've filed https://github.com/dit/dit/issues/144 for this.
* I didn't find steps to test the software, thought I figured it out and filed https://github.com/dit/dit/pull/146

I've put in some other issues and PRs too, but these are the most important issues right now.

**Comment by arfon** [comment]
> I didn't see any DOIs linked in paper.bib though the references were complete (and I would consider suitable for another academic journal). @afron is this acceptable?

@stsievert - references without DOIs are acceptable provided they _don't actually have one_, i.e. a journal publications such as [this one](https://github.com/dit/dit/blob/master/joss_paper/paper.bib#L93) is missing this DOI: https://doi.org/10.1016/j.physleta.2011.10.066

@Autoplectic - please go through your `paper.bib` and add a DOI for each entry where you can find a DOI.

**Comment by Autoplectic** [comment]
> @Autoplectic I'm guessing @chebee7i is Christopher J. Ellison and James P. Crutchfield is your advisor. Is that correct?

Largely. CJE & I were both graduate students under JPC. CJE is now in industry, and I am back with JPC as a postdoc.

**Comment by Autoplectic** [comment]
I have added DOIs where possible.

**Comment by Autoplectic** [comment]
I believe I have addressed all the reviewers concerns at this point.

**Comment by Autoplectic** [comment]
scratch that --- working on an issue with the docs. the custom mathjax works fine under docs.dit.io, but fails under dit.readthedocs.io

**Comment by Autoplectic** [comment]
OK, the docs work fine at http://dit.readthedocs.io and at http://docs.dit.io, which is the official link. I'm not sure why it doesn't work at https://dit.readthedocs.io. Since it works at the official link, which is the only one in the readme and such, things should be ok.

**Comment by stsievert** [comment]
Thanks @Autoplectic, both for the quick response and handling these issues well.

Maybe I'm missing it, but have you addressed contributing issue mentioned in https://github.com/openjournals/joss-reviews/issues/738#issuecomment-390523494?

**Comment by Autoplectic** [comment]
@stsievert The information about contributing is at the bottom of the readme. I've also added a CONTRIBUTING.md as you have suggested.

Thank you @stsievert, @kczimm, and @arfon for your help shepherding this submission through!

**Comment by kczimm** [comment]
I had many of the same comments as @stsievert. I don't have any other comments or suggestions at this time.

**Comment by stsievert** [comment]
> I've also added a CONTRIBUTING.md as you have suggested.

Could you add a line for people seeking support? This could be a link to a Gitter channel, a tip to stackoverflow with some tag or file an issue.

 Here's the GitHub support for CONTRIBUTING.md: https://blog.github.com/2012-09-17-contributing-guidelines/

It's easy to check off boxes when everything (or most things) are done right.

**Comment by Autoplectic** [comment]
@stsievert i've added to the contributing.md file!

**Comment by arfon** [comment]
OK, I think we're good to go here. If I could just get a final :+1: from @kczimm, @stsievert that we're good to accept I'll move forward with this submission.

**Comment by Autoplectic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00738/joss.00738/10.21105.joss.00738.pdf)

**Comment by Autoplectic** [comment]
Looks like we've got the thumbs!

**Comment by arfon** [comment]
@Autoplectic - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by Autoplectic** [comment]
doi: 10.5281/zenodo.1255350

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1255350 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1255350" target="_blank">10.5281/zenodo.1255350</a> is the archive.

**Comment by arfon** [comment]
@Autoplectic - I get the following error when compiling the doc:

```
pandoc-citeproc: reference Allen2014 not found
```
Can you check this reference? Is it missing in the bibtex or just cited incorrectly in the `paper.md`

**Comment by Autoplectic** [comment]
Fixed. I updated the bib file to reference the published version of that paper, but didn't fix the ref in the paper.

**Comment by arfon** [comment]
@kczimm, @stsievert - many thanks for your reviews here ✨ 

@Autoplectic - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00738 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00738/status.svg)](https://doi.org/10.21105/joss.00738)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00738/status.svg)](https://doi.org/10.21105/joss.00738)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
