### ISSUE TITLE
[REVIEW]: rsimsum: Summarise results from Monte Carlo simulation studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#739]
**Submitting author:** @ellessenne (<a href="http://orcid.org/0000-0002-8319-7624">Alessandro Gasparini</a>)
**Repository:** <a href="https://github.com/ellessenne/rsimsum/" target ="_blank">https://github.com/ellessenne/rsimsum/</a>
**Version:** 0.3.1
**Editor:** @leeper
**Reviewer:** @lebebr01
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1293527" target="_blank">10.5281/zenodo.1293527</a>

## Status

[![status](http://joss.theoj.org/papers/4b0df561e6cf7f1ef2b839645f612a4a/status.svg)](http://joss.theoj.org/papers/4b0df561e6cf7f1ef2b839645f612a4a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4b0df561e6cf7f1ef2b839645f612a4a"><img src="http://joss.theoj.org/papers/4b0df561e6cf7f1ef2b839645f612a4a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4b0df561e6cf7f1ef2b839645f612a4a/status.svg)](http://joss.theoj.org/papers/4b0df561e6cf7f1ef2b839645f612a4a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ellessenne/rsimsum/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lebebr01, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ellessenne/rsimsum/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.3.1)?
- [x] **Authorship:** Has the submitting author (@ellessenne) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00739/joss.00739/10.21105.joss.00739.pdf)

**Comment by leeper** [comment]
@lebebr01 Just a quick reminder about this review.

**Comment by lebebr01** [comment]
@leeper I have completed my review and have posted a few issues for @ellessenne to consider. Many of the issues are related to clarification of arguments, output, or documentation of the functions. I'm happy to look over the package again after @ellessenne has a chance to consider the issues.

**Comment by ellessenne** [comment]
Thanks a lot @lebebr01 (and @leeper) - I will go through the issues as quickly as possible!

**Comment by ellessenne** [comment]
Hello @lebebr01 and @leeper,
I just finished making some changes following @lebebr01 comments (for which I am very grateful - thank you very much!). Do you think there are other things I could improve on?

**Comment by leeper** [comment]
Great. @lebebr01, can you take another look and see if there are remaining issues to be addressed?

**Comment by lebebr01** [comment]
@leeper I took a look again and LGTM. 

@ellessenne thank you for the comments and further clarification of the documentation.

**Comment by leeper** [comment]
Thank you, @lebebr01!

@ellessenne Please create a release of the package and issue a DOI for it using, for example, figshare or zenodo, and let me know the DOI once you have it.

**Comment by ellessenne** [comment]
Thank you @lebebr01 for the review!

@leeper I just archived the current version of `rsimsum` using Zenodo and the corresponding DOI is: [10.5281/zenodo.1293527](http://doi.org/10.5281/zenodo.1293527)!

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1293527 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1293527" target="_blank">10.5281/zenodo.1293527</a> is the archive.

**Comment by leeper** [comment]
@arfon Over to you.

**Comment by arfon** [comment]
@lebebr01 - many thanks for your review and to @leeper for editing this submission ✨ 

@ellessenne - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00739 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00739/status.svg)](https://doi.org/10.21105/joss.00739)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00739/status.svg)](https://doi.org/10.21105/joss.00739)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
