### ISSUE TITLE
[PRE REVIEW]: ezknitr: Avoid the typical working directory pain when using 'knitr'

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#74]
**Submitting author:** @daattali (<a href="http://orcid.org/0000-0002-5645-3493">Dean Attali</a>)
**Repository:** <a href="https://github.com/ropenscilabs/ezknitr" target ="_blank">https://github.com/ropenscilabs/ezknitr</a>
**Version:** v0.5
**Editor:** @acabunoc
**Reviewer:** @acabunoc

**What this issue is for**

Thanks for submitting your paper to JOSS @daattali. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik, it looks like you're currently assigned as the editor for this paper :tada: 

For a list of things I can do to help you, just type: 

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Open the review issue
@whedon start review
```
:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue afterrunning a @whedon command (you might also need to refresh the page to seethe issue update).

**Comment by karthik** [comment]
@arfon Since I was one of the reviewers for this particular paper on the rOpenSci side, it would be a COI to be the handling editor on this side for this paper as well. So I am going to assign a new editor.

**Comment by karthik** [comment]
@whedon assign @masalmon as editor

**Comment by whedon** [comment]
OK @masalmon is now the editor

**Comment by karthik** [comment]
Sorry for the confusion. But I wanted to assign @acabunoc as editor and if she wants a reviewer suggestion, then suggest @masalmon 
So I will fix this shortly.

**Comment by karthik** [comment]
@whedon assign @acabunoc as editor

**Comment by whedon** [comment]
OK @acabunoc is now the editor

**Comment by karthik** [comment]
@acabunoc For context, this paper has already been through a stringent review at rOpenSci (https://github.com/ropensci/onboarding/issues/56). If this submission looks ok to you, just hit accept. No need to send out for review unless you feel something is off with the process that it has already been through.

**More detailed explanation:** We recently introduced a mechanism where someone can 'onboard' a package at rOpenSci and also check a couple more boxes to have this as a paper at JOSS. We check then check JOSS requirements as part of the process so when it comes here, everything is already in place. A human editor just needs to take a quick look and hit accept.

In this _particular_ case, I was also the reviewer there so I cannot hit accept. That's why I've assigned you. So no need for this to go out to review unless you feel that it is not up to JOSS standards.

cc @arfon

**Comment by acabunoc** [comment]
Thanks! I'll take a look ✨

**Comment by arfon** [comment]
> Thanks! I'll take a look ✨

@acabunoc great thanks. Take a look at https://github.com/ropensci/onboarding/issues/56 and see what you think. We should probably make the formal review issue anyway (even for tracking). Also I want to try out @whedon's new super-powers :grin:.

In practice this means:

1. Assigning a reviewer (`@whedon assign @username as reviewer`)
2. Starting the review (`@whedon start review`)

@whedon should then update this issue with the actual review issue which is where we should probably document the decision around what kind of review we need.

**Comment by acabunoc** [comment]
Just read through https://github.com/ropensci/onboarding/issues/56 -- looks great and thorough and complies with our own review process. I'll make a formal issue with myself as a reviewer and I'll document the decision there. Let me know if I should go about this differently!

Do I have to use a new comment to to use @whedon's super powers? I'm going to try here:

@whedon assign @acabunoc as reviewer

**Comment by acabunoc** [comment]
@whedon assign @acabunoc as reviewer

**Comment by whedon** [comment]
OK I'm assigning @acabunoc as the reviewer

**Comment by acabunoc** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:
```
@whedon start review magic-word=bananas
```

**Comment by acabunoc** [comment]
bananas are gross, @whedon 🍌

**Comment by acabunoc** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
Creating the review issue #75. @acabunoc feel free to close this issue now.
