### ISSUE TITLE
[PRE REVIEW]: PyUnfold: A Python Package for Iterative Unfolding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#740]
**Submitting author:** @zhampel (<a href="http://orcid.org/0000-0003-0253-9117">Zigfried Hampel-arias</a>)
**Repository:** <a href="https://github.com/jrbourbeau/pyunfold" target ="_blank">https://github.com/jrbourbeau/pyunfold</a>
**Version:** v0.3
**Editor:** @lheagy
**Reviewers:** @juliohm, @benjaminrose

**Author instructions**

Thanks for submitting your paper to JOSS @zhampel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zhampel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00740/joss.00740/10.21105.joss.00740.pdf)

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor.

**Comment by lheagy** [comment]
Thanks @arfon, I am happy to take this

**Comment by arfon** [comment]
> Thanks @arfon, I am happy to take this

Thanks!

**Comment by lheagy** [comment]
Hi @zhampel, thanks for your submission! Do you have any recommendations for reviewers? Ideally, we find 2.

**Comment by jrbourbeau** [comment]
Perhaps @rowanc1 is interested in being a reviewer?

**Comment by rowanc1** [comment]
Thanks for the suggestion, cursory glance through things looks cool. :) Unfortunately, I won't be able to realistically look at this until late July. You might be able to find someone else, or I can aim for that time frame. Let me know!

**Comment by zhampel** [comment]
Perhaps @juliohm or @benjaminrose are interested/available as reviewers?

**Comment by jrbourbeau** [comment]
@betatim also seems like a good potential reviewer. Are you interested/available to review?

**Comment by zhampel** [comment]
@juliohm Yeah I think that time frame seems OK. @jrbourbeau that's good for you as well yes? @lheagy, should we still search for another reviewer or is this good to get started?

**Comment by jrbourbeau** [comment]
The time frame laid out by @juliohm is totally fine with me. Thank you @lheagy and @juliohm for agreeing to be reviewers!

**Comment by benjaminrose** [comment]
Thank you @zhampel for considering me. I am also able to review this submission. I too am busy this through early next week, but I can review it on a similar time scale as @juliohm.

**Comment by lheagy** [comment]
Thanks @juliohm and @benjaminrose for agreeing to review!

**Comment by lheagy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by lheagy** [comment]
@whedon assign @juliohm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @juliohm

**Comment by lheagy** [comment]
@whedon add @benjaminrose as reviewer

**Comment by whedon** [comment]
OK, @benjaminrose is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas
