### ISSUE TITLE
[REVIEW]: PyUnfold: A Python Package for Iterative Unfolding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#741]
**Submitting author:** @zhampel (<a href="http://orcid.org/0000-0003-0253-9117">Zigfried Hampel-arias</a>)
**Repository:** <a href="https://github.com/jrbourbeau/pyunfold" target ="_blank">https://github.com/jrbourbeau/pyunfold</a>
**Version:** v0.4
**Editor:** @lheagy
**Reviewer:** @juliohm, @benjaminrose
**Archive:** <a href="https://doi.org/10.5281/zenodo.1258211">10.5281/zenodo.1258211</a>

## Status

[![status](http://joss.theoj.org/papers/7ce84a37ff74be06ef28f8ea9b8831e6/status.svg)](http://joss.theoj.org/papers/7ce84a37ff74be06ef28f8ea9b8831e6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7ce84a37ff74be06ef28f8ea9b8831e6"><img src="http://joss.theoj.org/papers/7ce84a37ff74be06ef28f8ea9b8831e6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7ce84a37ff74be06ef28f8ea9b8831e6/status.svg)](http://joss.theoj.org/papers/7ce84a37ff74be06ef28f8ea9b8831e6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jrbourbeau/pyunfold" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@juliohm & @benjaminrose, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jrbourbeau/pyunfold">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3)?
- [x] **Authorship:** Has the submitting author (@zhampel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jrbourbeau/pyunfold">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3)?
- [x] **Authorship:** Has the submitting author (@zhampel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @juliohm, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00741/joss.00741/10.21105.joss.00741.pdf)

**Comment by lheagy** [comment]
Many thanks @juliohm and @benjaminrose for being willing to review! In the main issue thread, there is a checklist for each of you as you go through the review. Please let me know if you have any questions or if there is anything I can assist with!

**Comment by juliohm** [comment]
Very good documentation @zhampel, I was able to reproduce all the examples, and follow the mathematical derivations.

A few comments to improve the project further:

### Conceptual
- It would be nice to compare `pyunfold` with other related packages for inverse problems in Python, or clarify in the documentation the unique features of the project.
- Additionally, it would be interesting to see examples where the observed distribution is very different than the true distribution. Or alternatively, you could list the distributional assumptions under which the method is successful. For example, can the method be applied to update a bimodal observation into an unimodal truth?

### Implementation
- Priors (or distributions) in the project are represented with a vector of numbers (densities). In the section "custom priors" you could clarify that any vector of numbers (integrating to one) can be used as a prior and that priors `uniform` and `jeffreys` are not specialized classes.
- The binder option to run the examples online is missing the `pyunfold` module as reported in https://github.com/jrbourbeau/pyunfold/issues/67
- Since you are using Travis CI for the tests, you could also consider activating the build on Mac OS. You can do it by adding the section below:

```
os:
  - linux
  - osx
```

**Comment by jrbourbeau** [comment]
> The binder option to run the examples online is missing the pyunfold module

Thanks @juliohm for pointing this out and submitting a corresponding issue! I've updated the environment that is built to run the example notebooks on binder. `pyunfold` is now installed and the notebooks all work as expected. 

ref: jrbourbeau/pyunfold#68

**Comment by jrbourbeau** [comment]
> Since you are using Travis CI for the tests, you could also consider activating the build on Mac OS. 

That's a good point. I added Mac OS tests for Python 3.6 in jrbourbeau/pyunfold#69. 

I didn't want to double the number of jobs that are run on Travis by running both `linux` and `osx` tests for several different versions of Python. So instead I'm keeping the original jobs that run Python 2.7, 3.4, 3.5, and 3.6 on `linux` and have added a job for Python 3.6 on `osx`. This should catch if there is a Python-specific problem or a Mac OS-specific problem.

**Comment by juliohm** [comment]
Thank you @jrbourbeau for incorporating the changes. Is there a good reason to test on all 3.x versions of Python? Are they very different?

I will convert my previous comment into a set of tasks, and will mark the tasks you've already implemented as done. :heavy_check_mark:

**Comment by jrbourbeau** [comment]
> Is there a good reason to test on all 3.x versions of Python? Are they very different?

All of the existing code in PyUnfold should work just fine on all Python 3.x versions. Running the automated tests on different 3.x versions is more a preventative measure to make sure new contributions don't unexpectedly add something that isn't fully backwards compatible (e.g. Python 3.6 added a new [f-string formatting syntax](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) which are really nice, but won't work on Python 3.4 or 3.5).

**Comment by jrbourbeau** [comment]
> you could clarify that any vector of numbers (integrating to one) can be used as a prior and that priors uniform and jeffreys are not specialized classes

@juliohm I've updated the [Custom Priors section](https://jrbourbeau.github.io/pyunfold/notebooks/user_prior.html#Custom-Priors) in the documentation in jrbourbeau/pyunfold#70 to address the points you brought up. Hopefully it is more clear now that any given `prior` array can be used, not just the built-in `uniform_prior` or `jeffreys_prior`. Please let me know if you think it needs any further clarification.

Thank you for the thorough read through and feedback!

**Comment by jrbourbeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00741/joss.00741/10.21105.joss.00741.pdf)

**Comment by jrbourbeau** [comment]
> clarify in the documentation the unique features of the project

@juliohm we've added a ["Why PyUnfold?" ](https://jrbourbeau.github.io/pyunfold/why) page to the documentation that outlines the unique features of the project. 

ref: jrbourbeau/pyunfold#71

**Comment by jrbourbeau** [comment]
> Additionally, it would be interesting to see examples where the observed distribution is very different than the true distribution...For example, can the method be applied to update a bimodal observation into an unimodal truth?

@juliohm Indeed a bimodal observed distribution can be unfolded into a unimodal truth distribution. For example, in a similar fashion to the "Tutorial" notebook, one can have true, observed, and unfolded distributions as shown below. 

![image](https://user-images.githubusercontent.com/11656932/40750330-8af0e36c-642c-11e8-81e3-43fa1326b81b.png)

I can add this as an additional example notebook to the documentation. My only concern is that it wouldn't really walk through any new functionality in PyUnfold, just simply using a different example dataset.

**Comment by juliohm** [comment]
That is a very nice example, I think it tells a lot more about the generality of the method than the current example in the documentation, but it is up to you to decide what example is more telling for the audience you are targeting. =)

From a user's perspective, or maybe putting myself in the mind of someone that is probing different packages for inverse problems, I'd say that just knowing that the method doesn't assume gaussianity or bell shapes is a big plus. :+1: 

I am marking all the items as solved. Congratulations again on the package, good stuff!

@benjaminrose do you have further corrections or improvements that you would like to share?

**Comment by jrbourbeau** [comment]
> just knowing that the method doesn't assume gaussianity or bell shapes is a big plus 

That's a really good point. I'll discuss with @zhampel as to which example dataset would be more illuminating for the unfolding community.

**Comment by jrbourbeau** [comment]
@juliohm Thanks so much for your detailed review of PyUnfold and useful review comments! I definitely think they helped improve the project

**Comment by zhampel** [comment]
@juliohm so we've used the method on power law spectra in publications, so @jrbourbeau and I can cook up an example from simulation for example that demonstrates a non-gaussian data set. We just have to decide how to make our fake data without violating our collaborations's respective public release agreements ;)

**Comment by zhampel** [comment]
@juliohm we've used the method successfully on power law spectra unfoldings for publications, so @jrbourbeau and I can cook up such an example in addition to our canonical examples. We just have to make sure we don't violate any public release agreements from our respective collaborations ;)

**Comment by zhampel** [comment]
Testing: @whedon Who's your favorite Buffy character?

**Comment by benjaminrose** [comment]
This is a great project. @juliohm's thank you for your great comments. A have a few of my own to add.

# Docs - Tutorial

- [ ] Binder is a great tool for this! Thanks for using it. Also, maybe add a line about needing to install `matplotlib`  if you want to follow this tutorial on your own.
- [ ] Can you point out the cause for "We can see how the structure of the 2-d response histogram differs from the normalized response matrix."
- [ ] In the tutorial, can you either add a short explanation of the `ts` parameter is or just use the default values for input 20. 

# Docs - API
- [ ] Can you define the `ts` stats in the API docs, only their acronyms are used.
    - The paper does define them, but not the API docs
- [ ] Can you explain/link to a definition of Jeffrey's priors in the API docs? Maybe as a References header?

# Docs - Contributing page
- [ ] The how to contribute guide is great. Like you liked to Github's article on forks, maybe in step 11 add a link to Github's recommendation to writing a pull request, https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/.
* Thanks for explaining `git fetch upstream`. This is very useful for first-time contributors.

# Paper

- [ ] The statement of need is better in the docs than in the paper. I really like [this section](https://jrbourbeau.github.io/pyunfold/overview.html#what-is-unfolding).

# General

* What is your plan to get to v1.0?
* Walking through one simple but complete example is enough. I support the idea of at least pointing out more complicated solutions are solve-able, like the bimodal observed distribution coming from a unimodal truth. Putting it with the other advanced techniques makes sense to me.

**Comment by jrbourbeau** [comment]
Thanks for your review @benjaminrose! I'll get started on addressing your comments and link back to this review in the relevant PRs.

**Comment by jrbourbeau** [comment]
@benjaminrose At this point I think I've addressed your comments related to the tutorial notebook, API documentation, and contributing guide. Please let me know if further clarification / changes are needed to these sections of the documentation. 

Also, thanks for the link to the "How to write the perfect pull request" article! There's a bunch of really good stuff in there.

**Comment by jrbourbeau** [comment]
> The statement of need is better in the docs than in the paper

@benjaminrose Just to clarify, are you recommending we include the content from the "What is unfolding?" documentation in the paper?

**Comment by jrbourbeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00741/joss.00741/10.21105.joss.00741.pdf)

**Comment by benjaminrose** [comment]
@jrbourbeau, I think the "What is unfolding?" is your strongest statement of need. The paper is fine, but I feel like you have a better argument somewhere else. Having the best argument in the docs is helpful since most people will read that and not the paper. If you see a simple way to add it, and you want to, I think it would make the paper better.

**Comment by benjaminrose** [comment]
The other changes look great @jrbourbeau. But I missed the API docs for the `teststat` class.   The abbreviations that are the not fully that I was talking about were in describing the `ts` parameter for `iterative_unfold()`. I would just add a "more info" link to https://jrbourbeau.github.io/pyunfold/api.html#test-statistics at the end of that parameter's description.

**Comment by jrbourbeau** [comment]
> I was talking about were in describing the ts parameter for iterative_unfold()

Gotcha, I misunderstood your comment. Thanks for noticing that! I'll update the `iterative_unfold` docstring accordingly

**Comment by jrbourbeau** [comment]
@benjaminrose I updated the `ts` parameter description with a link to the test statistics section in the API docs

**Comment by jrbourbeau** [comment]
@juliohm just as an FYI the "Performance" checkbox under the "Functionality" section for your review checklist is unchecked. If there's anything else that needs to be done on my end, just let me know. Thanks!

**Comment by juliohm** [comment]
@jrbourbeau I don't recall reading in the docs statements about performance? Please let me know if they exist somewhere. The checkbox should only be marked in case the software claims states explicitly that it is "high-performance" or faster than alternatives.

**Comment by benjaminrose** [comment]
@lheagy, I think  @zhampel  and @jrbourbeau have a great project here and I fully endorse their paper for publication in JOSS.

**Comment by jrbourbeau** [comment]
>  I think the "What is unfolding?" is your strongest statement of need...If you see a simple way to add it, and you want to, I think it would make the paper better.

@benjaminrose I agree, that's a really good point. I've added the content from the "What is unfolding?" docs to the beginning of the paper. I think it helps clarify the problem we're addressing with PyUnfold without messes with the overall flow of the paper. Thanks for the feedback! 

ref: jrbourbeau/pyunfold#83

**Comment by jrbourbeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00741/joss.00741/10.21105.joss.00741.pdf)

**Comment by jrbourbeau** [comment]
> The checkbox should only be marked in case the software claims states explicitly that it is "high-performance" or faster than alternatives.

@juliohm You're correct, we don't make any statements about the performance in the docs. However, I interpreted the "If there are no claims, please check off this item" sentence to mean that since we make no performance claims, then the performance checkbox should be marked as done. I could definitely be misinterpreting that though.

**Comment by juliohm** [comment]
Oh maybe it is a language issue, I am not a native speaker. When I read "Check off" I interpret it as "Do not mark the box", it is probably the opposite?

**Comment by jrbourbeau** [comment]
I took "check off" to mean "mark the box". Perhaps @lheagy can clarify this point for us.

**Comment by lheagy** [comment]
Hi @juliohm and @jrbourbeau: sorry for the confusion (and I appreciate knowing that this is a potential point of confusion for non-native speakers). By "check off", we do mean that you can "mark the box" if there are no claims made.

**Comment by juliohm** [comment]
Thank you @lheagy, checking it off :ok_hand:

**Comment by jrbourbeau** [comment]
Thanks for such a quick reply @juliohm!

**Comment by jrbourbeau** [comment]
@lheagy at this point both the reviewers have approved the paper / project for publication in JOSS. Are there any additional steps I need to take in order to move forward with publication? Thanks!

**Comment by lheagy** [comment]
Excellent! Thank you @juliohm and @benjaminrose for your review!! 

@zhampel and @jrbourbeau at this point, could you please archive your software on [zenodo](https://zenodo.org/) or similar and post the doi here?

**Comment by zhampel** [comment]
@lheagy: @jrbourbeau has archived on zenodo with [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1258211.svg)](https://doi.org/10.5281/zenodo.1258211)

**Comment by lheagy** [comment]
Thanks @zhampel: quick question for you - it looks like the version you archived is v0.4. This is the version we should list with the publication?

**Comment by zhampel** [comment]
Yes, I think so, is that correct @jrbourbeau ? I know originally when we submitted we listed as v0.3

**Comment by lheagy** [comment]
👋 Hi @arfon: This submission is ready to be published!

**Comment by arfon** [comment]
@juliohm, @benjaminrose - many thanks for your reviews here and to @lheagy for editing this submission ✨ 

@zhampel - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00741 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00741/status.svg)](https://doi.org/10.21105/joss.00741)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00741/status.svg)](https://doi.org/10.21105/joss.00741)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by zhampel** [comment]
Thank you so much @lheagy @juliohm @benjaminrose for your thorough and speedy review! 🎉 We look forward to further contributions to JOSS.
