### ISSUE TITLE
[PRE REVIEW]: skijumpdesign: A Ski Jump Design Tool for Specified Equivalent Fall Height

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#742]
**Submitting author:** @moorepants (<a href="http://orcid.org/0000-0002-8698-6143">Jason K. Moore</a>)
**Repository:** <a href="https://gitlab.com/moorepants/skijumpdesign" target ="_blank">https://gitlab.com/moorepants/skijumpdesign</a>
**Version:** v1.2.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @trallard

**Author instructions**

Thanks for submitting your paper to JOSS @moorepants. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@moorepants if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #742 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0    139      0 --:--:-- --:--:-- --:--:--   141
Error reading bibliography ./paper.bib (line 142, column 9):
unexpected "("
expecting letter, white space or "{"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@moorepants - could you take a look at the errors from the paper compilation above?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon I can take this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants I think you just need to replace a ( by a { on line 142. I created a merge request on your repo. Just say `@whedon generate pdf` here when you are ready to test

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants any reviewers you can recommend for this work?

**Comment by moorepants** [comment]
@monthubbard the review will be happening here. FYI.

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00742/joss.00742/10.21105.joss.00742.pdf)

**Comment by moorepants** [comment]
@monthubbard Do you have any recommendations for reviewers? They'll need to be willing to review via the Github interface here.

**Comment by moorepants** [comment]
There are a couple reviewers on the list that have biomechanics listed: trallard and CELavecchia

**Comment by moorepants** [comment]
pandoc converts `\(mg\)` to latex mathematics locally for me but it doesn't seem to work via whedon, see:

![image](https://user-images.githubusercontent.com/276007/40291603-c505f358-5c7a-11e8-9398-49f983fb9ed3.png)

I have an issue open for this: https://github.com/openjournals/joss/issues/409

**Comment by moorepants** [comment]
Ok, the paper seems to be compiling correctly and I've fixed some minor issues wrt to that.

**Comment by monthubbard** [comment]
Prof Chris Brown, Worcester Poly, brown@wpi.edu
Dr Martin Mossner, University of Innsbruck, email unknown

I have no idea whether they are willing to use Github

**Comment by devinberg** [comment]
@Kevin-Mattheus-Moerman Looks interesting but I worry I'm not software savvy enough to review this. (i.e.  I've been able to install this package but not successfully run it so far.)

**Comment by moorepants** [comment]
@devinberg If you can report the issue you have, I can try to improve the installation documentation. Thanks!

**Comment by moorepants** [comment]
Here is Dr. Martin Mossner's email: martin.moessner@uibk.ac.at

**Comment by moorepants** [comment]
Note that Devin and I fixed the Windows install issues and that should all work as expected now.

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00742/joss.00742/10.21105.joss.00742.pdf)

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by moorepants** [comment]
This is compiling fine now and ready for review. Thanks.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00742/joss.00742/10.21105.joss.00742.pdf)

**Comment by moorepants** [comment]
Are there any status updates on finding reviewers? Here are our consolidated suggestions:

- Prof Chris Brown, Worcester Poly, brown@wpi.edu
- Dr. Martin Mossner, University of Innsbruck, martin.moessner@uibk.ac.at
- trallard t.allard@sheffield.ac.uk (from JOSS list with biomechanics keyword)
- CELavecchia lavecchia.carolina@gmail.com (from JOSS list with biomechanics keyword)

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @moorepants I've invited Brown and Moessner via email. I'll let you know if I hear back from them.

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard @CELavecchia would you be interested in reviewing this JOSS submission? Thanks

**Comment by trallard** [comment]
Hi! Apologies for the late reply. I would be happy to do this review, however, I am about to go on very much needed annual leave. If this can wait until the 8th of July I would be happy to pick it up then

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @trallard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @trallard

**Comment by Kevin-Mattheus-Moerman** [comment]
Great @trallard. We'll start sooner if other reviewers join sooner but I'll ping you around the 8th of July. Enjoy your annual leave! :beach_umbrella:

**Comment by trallard** [comment]
Great! I will keep an eye here then

**Comment by Kevin-Mattheus-Moerman** [comment]
I have not had luck finding other reviewers. I have e-mailed @moorepants 's suggested reviewers but have not heard back from them yet.

**Comment by moorepants** [comment]
I just found this paper, maybe one of these authors would be interested:

https://www.researchgate.net/publication/323152326_Robust_Trajectory_Optimization_of_a_Ski_Jumper_for_Uncertainty_Influence_and_Safety_Quantification

- Patrick Piprek patrick.piprek@tum.de
- Florian Holzapfel florian.holzapfel@tum.de

**Comment by trallard** [comment]
@Kevin-Mattheus-Moerman do you still need reviewers for this? I am slowly easing back into work after my leave so I could pick this up if needed be

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard thanks. I think we can get started. If I manage to find more reviewers they can join later.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/818. Feel free to close this issue now!
