### ISSUE TITLE
[PRE REVIEW]: sjmisc - Data and Variable Transformation Functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#743]
**Submitting author:** @strengejacke (<a href="http://orcid.org/0000-0002-8895-3206">Daniel Lüdecke</a>)
**Repository:** <a href="https://github.com/strengejacke/sjmisc" target ="_blank">https://github.com/strengejacke/sjmisc</a>
**Version:** 2.7.2
**Editor:** @leeper
**Reviewers:** @jrosen48, @methodds

**Author instructions**

Thanks for submitting your paper to JOSS @strengejacke. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@strengejacke if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #743 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/743/paper.md): did not find expected '-' indicator while parsing a block collection at line 9 column 3 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:65:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@strengejacke - this PR should fix your paper metadata https://github.com/strengejacke/sjmisc/pull/85

**Comment by strengejacke** [comment]
Thanks, I just merged the PR.

**Comment by strengejacke** [comment]
I would suggest @noamross or @jrosen48 as reviewers, and have also asked someone not from this list. I will give feedback as soon as I get a response.

**Comment by jrosen48** [comment]
I'd be pleased to review **sjmisc**.

**Comment by leeper** [comment]
@whedon set @leeper as editor

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #743 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0    139      0 --:--:-- --:--:-- --:--:--   141
Error reading bibliography ./paper.bib (line 16, column 3):
unexpected "p"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon add @jrosen48 as reviewer

**Comment by whedon** [comment]
OK, @jrosen48 is now a reviewer

**Comment by leeper** [comment]
@methodds Can you confirm you're interested in reviewing this for JOSS?

**Comment by leeper** [comment]
@strengejacke Can you merge [this PR](https://github.com/strengejacke/sjmisc/pull/87) to fix your bibliography?

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00743/joss.00743/10.21105.joss.00743.pdf)

**Comment by strengejacke** [comment]
Just got a msg that @methodds is on holiday break and gets back by the end of this week.

**Comment by methodds** [comment]
If you still need a reviewer, I'd be happy to do it :)

**Comment by leeper** [comment]
@whedon add methodds as reviewer

**Comment by whedon** [comment]
OK, methodds is now a reviewer

**Comment by leeper** [comment]
@whedon remove methodds as reviewer

**Comment by whedon** [comment]
OK, methodds is no longer a reviewer

**Comment by leeper** [comment]
@whedon add @methodds as reviewer

**Comment by whedon** [comment]
OK, @methodds is now a reviewer

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/754. Feel free to close this issue now!

**Comment by leeper** [comment]
@jrosen48 and @methodds thanks for agreeing to review! You each have a review checklist to complete over at https://github.com/openjournals/joss-reviews/issues/754

Let me know if you have any questions.
