### ISSUE TITLE
[REVIEW]: The Vascular Modeling Toolkit: A Python Library for the Analysis of Tubular Structures in Medical Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#745]
**Submitting author:** @rlizzo (<a href="http://orcid.org/0000-0002-0811-6513">Richard Izzo</a>)
**Repository:** <a href="https://github.com/vmtk/vmtk" target ="_blank">https://github.com/vmtk/vmtk</a>
**Version:** v1.4.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @wouterpotters, @brainstorm
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1253598" target="_blank">10.5281/zenodo.1253598</a>

## Status

[![status](http://joss.theoj.org/papers/238cc3a9c1c4105b616cc3a0f2414ecb/status.svg)](http://joss.theoj.org/papers/238cc3a9c1c4105b616cc3a0f2414ecb)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/238cc3a9c1c4105b616cc3a0f2414ecb"><img src="http://joss.theoj.org/papers/238cc3a9c1c4105b616cc3a0f2414ecb/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/238cc3a9c1c4105b616cc3a0f2414ecb/status.svg)](http://joss.theoj.org/papers/238cc3a9c1c4105b616cc3a0f2414ecb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/vmtk/vmtk" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@wouterpotters & @brainstorm, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vmtk/vmtk">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.4.0)?
- [x] **Authorship:** Has the submitting author (@rlizzo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vmtk/vmtk">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.4.0)?
- [x] **Authorship:** Has the submitting author (@rlizzo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by Kevin-Mattheus-Moerman** [comment]
@rlizzo, @wouterpotters, @brainstorm this is where the review process takes place. There are sets of tickboxes for both reviewers at the top of this issue (let me know if you are unable to tick them). If you have questions please let me know. You may also want to check out the [JOSS reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines).

**Comment by Kevin-Mattheus-Moerman** [comment]
@osmsc @sshadden @jmerkow @alexkaiser @updega2 @gmaher @fkong7 this is a [JOSS](http://joss.theoj.org/about) review issue for [ _The Vascular Modeling Toolkit_ ](https://github.com/vmtk/vmtk). Please let me know if you are interested in reviewing this submission.  
 
The review process is focused largely on the software and a short paper, see the [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines). 

[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00736/joss.00736/10.21105.joss.00736.pdf)

[--> Check software repository :floppy_disk: <--](https://github.com/vmtk/vmtk)

**Comment by wouterpotters** [comment]
minor issue: license in LICENSE file https://github.com/vmtk/vmtk/issues/283

**Comment by wouterpotters** [comment]
There are no automated tests for the vmtk Python scripts and C++ classes.
However:

- A large part of the software is based on ITK routines, which do have automated testing for all their routines. 
- There are options for visual user feedback (i.e. ITK visualisations) every step of the way using vmktimageviewer, vmtksurfaceviewer, vmtkrenderer 
- There are options for checking the results in other software packages (e.g. by using vmtksurfacewriter and vmtkimagewriter). 
- the website does have several extensive tutorials and example data using the visual feedback. 

I would consider the added value for automated vmtk tests limited. I would advise to look into this, but I do not consider it a requirement for publication. What do you think @brainstorm?

**Comment by wouterpotters** [comment]
Extensive testing; all explained in the CONTRIBUTING.md file, test folder and on https://github.com/vmtk/vmtk-test-data.

**Comment by wouterpotters** [comment]
already fixed; new user instructions: https://github.com/vmtk/vmtk/issues/286

**Comment by wouterpotters** [comment]
Despite the fact that there already is a lot of useful documentation for both users and developers: issue with (incomplete) documentation: http://github.com/vmtk/vmtk/issues/288

Improving this point would improve the open source aspect of vmtk

**Comment by wouterpotters** [comment]
Some small issues with the submitted manuscript: https://github.com/vmtk/vmtk/issues/289

**Comment by wouterpotters** [comment]
Overall opinion on the submitted paper:
The VMTK software package is a scientifically relevant open source software package that is relevant specifically to the field of vascular imaging and simulation. 

The package is useful for users at different levels. Clinicians and non-technical users can use their precompiled version, more advanced developers can use either the python or the C++ libraries. 

As the package is largely based on the common VTK and ITK packages, the software is easily used within other VTK / ITK based packages and the other way around. VTK / ITK features are easily implemented in vmtk. 

Key features besides VTK / ITK are the pypes pipeline, which enables users to manually or automatically process all types of files into custom pipelines with custom output files.
Another key feature is the unique and robust way to detect and process the centrelines of tubular structures. Together with several surface processing and mesh generating functions, this software package can quantify basic vascular/tubular properties and perform the required preparations for (open source) CFD simulations. 
The extensive manuals and (almost complete) documentation pages guide new user through these features. 

The previous release of this software (2008) has been cited and used a lot by many users. In the past years the software package went through some significant and important changes (test system, user interface improvements, new features).

Overall I would advise to accept the publication of this excellent open source software package, provided that the authors improve the C++ classes documentation and the paper.md.

**Comment by rlizzo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00745/joss.00745/10.21105.joss.00745.pdf)

**Comment by rlizzo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00745/joss.00745/10.21105.joss.00745.pdf)

**Comment by wouterpotters** [comment]
Already looking good now with the latest additions. As soon as the C++ docs are (more) complete, I vote to accept the package. What do you think @brainstorm?

**Comment by brainstorm** [comment]
Yeah, likewise @wouterpotters, the functional docs are the only area where a bit more text/work would be great to have to pass this review, imho.

**Comment by rlizzo** [comment]
@brainstorm and @wouterpotters: Just letting you know that we have merged the improvements to the C++ class level documentation you requested. You can review the the changes in the Merged PR https://github.com/vmtk/vmtk/pull/295, or view the additions online: http://www.vmtk.org/doc/html/annotated.html. The majority of effort went into documenting the code which has to do with data structures or processing methods which are more specialized to the field of computational vascular analysis. For your reference, the centerline analysis scripts primarily exist within the [vtkVmtk/ComputationalGeometry](https://github.com/vmtk/vmtk/tree/master/vtkVmtk/ComputationalGeometry) subdirectory of the repository. 

I hope this addresses your concern on the low level library documentation.Please let me know your thoughts. Thank you!

**Comment by brainstorm** [comment]
There seems to be a few function description gaps still left to fill on the http://www.vmtk.org/doc/html/annotated.html link, but overall looks good, what do you think @wouterpotters?

**Comment by wouterpotters** [comment]
@brainstorm Looks like a great addition to the docs. I vote to accept this manuscript & code for publication.

**Comment by wouterpotters** [comment]
@kevinmoerman unfortunately I can’t due to technical limitations. I don’t have acces to a physical computer in the next few days and both my iPhone and my Android phone are not allowed (by github) to check that box. Maybe @brainstorm or you could check it?

**Comment by rlizzo** [comment]
@Kevin-Mattheus-Moerman thank you, I will have some time in a few hours to update the last few functions @brainstorm mentioned. I appreciate the feedback!

**Comment by Kevin-Mattheus-Moerman** [comment]
@wouterpotters I ticked it for you now thanks again for your help with this review! :tada:

**Comment by rlizzo** [comment]
@brainstorm and @Kevin-Mattheus-Moerman, I have updated the documentation at your request. See changes in http://www.vmtk.org/doc/html/annotated.html.

**Comment by brainstorm** [comment]
Fantastic, thanks! All thumbs up from my side, I just ticked the last box, thanks everyone.

**Comment by rlizzo** [comment]
Thanks everyone! Archived the version with all the boxes checked on zendoo:

[![DOI](https://zenodo.org/badge/842163.svg)](https://zenodo.org/badge/latestdoi/842163)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1253598 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1253598" target="_blank">10.5281/zenodo.1253598</a> is the archive.

**Comment by arfon** [comment]
@wouterpotters, @brainstorm - many thanks for your reviews here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@rlizzo - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00745 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00745/status.svg)](https://doi.org/10.21105/joss.00745)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00745/status.svg)](https://doi.org/10.21105/joss.00745)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
