### ISSUE TITLE
[REVIEW]: mbir: Magnitude-Based Inferences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#746]
**Submitting author:** @kdpeterson51 (<a href="http://orcid.org/0000-0003-0128-5282">Kyle Peterson</a>)
**Repository:** <a href="https://github.com/kdpeterson51/mbir" target ="_blank">https://github.com/kdpeterson51/mbir</a>
**Version:** 1.3
**Editor:** @arfon
**Reviewer:** @kellieotto
**Archive:** <a href="https://doi.org/10.5281/zenodo.2546910" target="_blank">10.5281/zenodo.2546910</a>

## Status

[![status](http://joss.theoj.org/papers/ff46731883f6f27042a27fc970f3b150/status.svg)](http://joss.theoj.org/papers/ff46731883f6f27042a27fc970f3b150)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ff46731883f6f27042a27fc970f3b150"><img src="http://joss.theoj.org/papers/ff46731883f6f27042a27fc970f3b150/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ff46731883f6f27042a27fc970f3b150/status.svg)](http://joss.theoj.org/papers/ff46731883f6f27042a27fc970f3b150)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kdpeterson51/mbir" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kellieotto, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kdpeterson51/mbir">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.3)?
- [x] **Authorship:** Has the submitting author (@kdpeterson51) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kellieotto it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00746/joss.00746/10.21105.joss.00746.pdf)

**Comment by kellieotto** [comment]
I've done a first review. The version and automated tests need attention. I'm leaving detailed feedback in the repository issues.

**Comment by leeper** [comment]
Excellent. Thank you, @kellieotto!

**Comment by leeper** [comment]
@kdpeterson51 Please address the issues raised in the review and then let me know once your updates are ready. I'll then take a look and decide if further review is needed.

**Comment by kdpeterson51** [comment]
Thank you for your patience, @leeper. One of the two issues raised by @kellieotto has been [addressed](https://github.com/kdpeterson51/mbir/issues/3). 

To address the second, I am currently in progress of pairing up Travis CI and will update you immediately  upon successful integration.

**Comment by kdpeterson51** [comment]
@leeper Both issues raised by @kellieotto have now been addressed. 

Please inform me if there is anything else you may need form me. Thank you very much.

**Comment by kellieotto** [comment]
The version issue has been addressed. The package still needs unit tests.

**Comment by leeper** [comment]
Yes, please add unit tests as suggested here: https://github.com/kdpeterson51/mbir/issues/2

**Comment by leeper** [comment]
@kdpeterson51 I see you've started adding tests. Let me know when you feel the package is ready for me to take another, more thorough look. Thanks!

**Comment by kdpeterson51** [comment]
@leeper @kellieotto we have added more comprehensive unit tests and would like your feedback on the matter. Thank you for all that you do.

**Comment by leeper** [comment]
Thanks, @kdpeterson51. @kellieotto can you take a final look?

**Comment by kellieotto** [comment]
I'm very sorry for such a long delay. This got buried in my inbox. The tests are a good start, but I'd still like to see more comprehensive ones. [See my comment.](https://github.com/kdpeterson51/mbir/issues/2)

Might be useful to have a look at [this resource or other tutorials on unit testing.](https://katyhuff.github.io/python-testing/) This tutorial is Python specific, but there are some good conceptual things in there that apply to R packages too.

**Comment by arfon** [comment]
@kdpeterson51 - how are you getting along here?

**Comment by kdpeterson51** [comment]
All but 1 function is left for required [tests](https://github.com/kdpeterson51/mbir/issues/2#issuecomment-410449582). I apologize for how long this process has been and appreciate your patience.

**Comment by arfon** [comment]
👋 @kdpeterson51 - how are you getting along here?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by labarba** [comment]
👋 @kdpeterson51 — We haven't heard from you in a while... it looks like there remained only some work to do with the tests. Will you be able to finish this up soon?

**Comment by kdpeterson51** [comment]
@arfon @labarba All tests are finished. Thank you for all your help.

**Comment by arfon** [comment]
:wave: @kellieotto - would you be able to take another look at this submission now that @kdpeterson51 has made their updates?

**Comment by kellieotto** [comment]
@arfon @kdpeterson51 Looks like the functions with missing unit tests have them now. I've closed the issue on it. Great! I recommend to accept.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00746/joss.00746/10.21105.joss.00746.pdf)

**Comment by arfon** [comment]
@kdpeterson51 - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by kdpeterson51** [comment]
@arfon Zenodo [archive](https://zenodo.org/record/2546910#.XEdp0VxKiiM) has been made.

**Comment by arfon** [comment]
@kellieotto - many thanks for your review here and to @leeper for editing this submission :sparkles:

@kdpeterson51 - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00746/status.svg)](https://doi.org/10.21105/joss.00746)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00746">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00746/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00746/status.svg
   :target: https://doi.org/10.21105/joss.00746
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00746/status.svg)](https://doi.org/10.21105/joss.00746)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
