### ISSUE TITLE
[REVIEW]: NN-SVG: Publication-Ready Neural Network Architecture Schematics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#747]
**Submitting author:** @zfrenchee (<a href="http://orcid.org/0000-0001-8173-2315">Alexander LeNail</a>)
**Repository:** <a href="https://github.com/zfrenchee/NN-SVG" target ="_blank">https://github.com/zfrenchee/NN-SVG</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewer:** @nilesh-patil, @terrytangyuan
**Archive:** <a href="https://doi.org/10.5281/zenodo.2541121" target="_blank">10.5281/zenodo.2541121</a>

## Status

[![status](http://joss.theoj.org/papers/52b511ab107595a805107aa4ad70161d/status.svg)](http://joss.theoj.org/papers/52b511ab107595a805107aa4ad70161d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/52b511ab107595a805107aa4ad70161d"><img src="http://joss.theoj.org/papers/52b511ab107595a805107aa4ad70161d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/52b511ab107595a805107aa4ad70161d/status.svg)](http://joss.theoj.org/papers/52b511ab107595a805107aa4ad70161d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/zfrenchee/NN-SVG" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nilesh-patil & @terrytangyuan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zfrenchee/NN-SVG">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [ ] **Authorship:** Has the submitting author (@zfrenchee) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zfrenchee/NN-SVG">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@zfrenchee) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @nilesh-patil, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00747/joss.00747/10.21105.joss.00747.pdf)

**Comment by arfon** [comment]
@nilesh-patil, @terrytangyuan - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by zfrenchee** [comment]
Hi @nilesh-patil, @terrytangyuan, 
Thanks for agreeing to review this! I'm going to make a first round of edits right now to conform to the checklists I see above -- I can tell already there are a few things missing. You should be all clear to review in about an hour or so.

**Comment by zfrenchee** [comment]
Oh, and one important note about this project, @arfon, @nilesh-patil, @terrytangyuan,
NN-SVG is principally a web-tool, not a package. Although this project was built with extensibility in mind ([and I've already been contacted about using it elsewhere](https://github.com/zfrenchee/NN-SVG/issues/4)) the main purpose of this code is to be the basis for [the site](http://alexlenail.me/NN-SVG/). For that reason, there are no installation instructions / API methods / etc... 

So I would put a N/A by those checkmarks.

**Comment by arfon** [comment]
> For that reason, there are no installation instructions / API methods / etc...

Just pushing back on this a little @zfrenchee. While I understand that this might not be wrapped up in a library/module with a clean API, I think it's reasonable to expect that installation instructions for this software (i.e. how to run this site myself) would be provided.

**Comment by zfrenchee** [comment]
@arfon that's an interesting idea. Then again, they're just HTML pages, so there isn't too much I can think of to explain. But I'll keep thinking about it..

**Comment by zfrenchee** [comment]
@terrytangyuan @arfon 
Thanks for the feedback, and sorry for the delayed reply. After some mulling over, I've come to see that you're quite right, and this tool would be more broadly applicable if I make it into a piece of independent code that can be used more broadly. Unfortunately, that's going to require a fair bit of refactoring and re-architecting, which I probably won't have time to get to in the immediate future. If it's alright with you, I'll just leave this open, and hopefully get to it in the next 1-3 weeks. Sound good?

**Comment by arfon** [comment]
> Thanks for the feedback, and sorry for the delayed reply. After some mulling over, I've come to see that you're quite right, and this tool would be more broadly applicable if I make it into a piece of independent code that can be used more broadly. Unfortunately, that's going to require a fair bit of refactoring and re-architecting, which I probably won't have time to get to in the immediate future. If it's alright with you, I'll just leave this open, and hopefully get to it in the next 1-3 weeks. Sound good?

Yes, this is completely fine. I'll mark this as `paused` for now - please let me know on this thread when you're ready to pick this up again.

**Comment by zfrenchee** [comment]
@arfon @terrytangyuan 
I've done the refactoring. I believe it will now be possible to use this tool on other sites. 
I probably still should add docs about how to do that. Besides that, what else needs doing? What is the way forwards? Should I add the docs and then we do another round of review?

**Comment by zfrenchee** [comment]
@arfon @terrytangyuan 
I've written some docs: https://github.com/zfrenchee/NN-SVG/wiki/NN-SVG-API
I believe it makes sense to update the paper slightly, but I also think I'm ready for the next round of review, unless I'm forgetting something?

**Comment by zfrenchee** [comment]
@arfon could you remove the "paused" label please?

**Comment by arfon** [comment]
@nilesh-patil @terrytangyuan - please come and take another look at this.

**Comment by arfon** [comment]
@nilesh-patil - do you think you might be able to carry out your review sometime soonish? 🙏

**Comment by zfrenchee** [comment]
Would still love to see this reviewed @arfon

**Comment by terrytangyuan** [comment]
Cool. Also, could you address my comments regarding community guidelines?

**Comment by zfrenchee** [comment]
- @terrytangyuan Could you share an example of what you mean by community guidelines? I'm not seeing anything that obviously seems like community guidelines in [BioPandas](https://github.com/rasbt/biopandas). 
- @terrytangyuan I'm not sure it makes sense for a visual tool to provide automated tests? 
- @terrytangyuan the wiki documents all the API methods for each architecture. Each architecture only has 2-3 methods, which might have confused you?

**Comment by terrytangyuan** [comment]
There is no descriptions for each parameters in the public methods. 

You can find example here: http://rasbt.github.io/biopandas/contributing/#how-to-contribute
It's located in the README.md: https://github.com/rasbt/biopandas#links
You can also provide a CONTRIBUTING.md file in the repo.

Regarding automated tests for visual tool, @arfon any suggestions?

**Comment by arfon** [comment]
> Regarding automated tests for visual tool, @arfon any suggestions?

Are the visualizations in HTML? If so, something like Selenium might be a good fit?

**Comment by zfrenchee** [comment]
@arfon that's a good point, but I think that would be overkill for this project. From the little frontend testing I have written, I can tell this would require 2-3x the code I've already written to write robust UI tests. That doesn't seem called for by this application. What do you think?

**Comment by arfon** [comment]
@zfrenchee - yeah, I hear you. Automated tests aren't a firm requirement for JOSS but if they're not present then something similar (documented test procedures with example data etc.) needs to be provided instead. Basically the reviewers need to be able to verify the functionality of the software.

**Comment by zfrenchee** [comment]
@arfon that makes a lot of sense. Let me see what I can rustle up in the way of something like tests.

**Comment by arfon** [comment]
> @arfon that makes a lot of sense. Let me see what I can rustle up in the way of something like tests.

How are you getting along @zfrenchee?

**Comment by arfon** [comment]
Just sent a reminder to @zfrenchee via email.

**Comment by zfrenchee** [comment]
I created a set of minimal examples which demonstrate how to get up and running with this project: 

https://github.com/zfrenchee/NN-SVG/wiki/Tests---Minimal-Examples

With those examples, you should be able to draw an NN, and configure it with any of the display parameters listed in the API docs: 

https://github.com/zfrenchee/NN-SVG/wiki/NN-SVG-API#iii-style-the-network

I think a reasonable test case is to clone thee repo, copy paste a minimal example, verify that you see an NN diagram, and then configure or style it in various ways using the API.

**Comment by arfon** [comment]
Thanks @zfrenchee. 

@terrytangyuan - could you take a look at the examples @zfrenchee has added here and see if:

> - Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g. a sample input file to assert behaviour)

**Comment by terrytangyuan** [comment]
Thanks @zfrenchee for addressing those and thanks @arfon for the ping. That looks fine. Could you address the following comments that I posted earlier?
* There's no community guidelines for how to contribute from other people (how to extend to new NN structure beyond just LeNet, AlexNet, FCNN, etc given how fast this field is evolving).
* Missing installation instructions (this is too trivial @arfon do we need this?)

**Comment by arfon** [comment]
> - Missing installation instructions (this is too trivial @arfon do we need this?)

I guess since most (all?) of the dependencies here are JavaScript libraries that a pulled from CDNs on the web, perhaps we don't need installation instructions?

That said, it might be good to make clear in the README (or wiki) what the end-user needs to generate these figures.

**Comment by zfrenchee** [comment]
Hi @arfon, @terrytangyuan 

1. "Installation Instructions": The wiki describes the necessary javascripts to include via CDN, implicitly in the [Minimal examples](https://github.com/zfrenchee/NN-SVG/wiki/Tests---Minimal-Examples) and explicitly in the [API docs](https://github.com/zfrenchee/NN-SVG/wiki/NN-SVG-API#i-initialize-the-object)

2. [Contributing Guidelines added to the wiki](https://github.com/zfrenchee/NN-SVG/wiki/Contributing), and linked to in the README.

**Comment by terrytangyuan** [comment]
Thanks. I've marked all the items in checklist. @arfon Handing over to you now.

**Comment by zfrenchee** [comment]
@arfon sorry to be a bother -- could you point me towards a little more information about this step in the process? I don't see anything on the [JOSS submission instructions page](https://joss.theoj.org/about#author_guidelines), and I'm slightly unsure about what's being asked of me. Am I hearing correctly that I should archive the current code on zenodo? Just downloading a zip of the repo from github and uploading to zenodo would fulfill this?

**Comment by arfon** [comment]
> Am I hearing correctly that I should archive the current code on zenodo? Just downloading a zip of the repo from github and uploading to zenodo would fulfill this?

Yes, that's correct. If you have made substantial changes to the codebase/docs during review then we also encourage you to make a new release on GitHub. You can learn how to do this by following this guide: https://guides.github.com/activities/citable-code/

**Comment by zfrenchee** [comment]
Thanks @arfon 

See https://zenodo.org/record/2541121#.XD49sM9KjmE and the [releases page of NN-SVG](https://github.com/zfrenchee/NN-SVG/releases)

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/436
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00747](https://doi.org/10.21105/joss.00747)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@terrytangyuan - many thanks for your review here ✨ 

@zfrenchee - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by zfrenchee** [comment]
> Party like you just published a paper! 🎉🌈🦄💃👻🤘

Thanks for the review, @terrytangyuan and for the kind support, @arfon . Looking forward to contributing back to this community =)
