### ISSUE TITLE
[REVIEW]: SpeechPy - Speech Processing and Recognition

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#749]
**Submitting author:** @astorfi (<a href="http://orcid.org/0000-0003-2282-4361">Amirsina Torfi</a>)
**Repository:** <a href="https://github.com/astorfi/speechpy" target ="_blank">https://github.com/astorfi/speechpy</a>
**Version:** 2.3
**Editor:** @arfon
**Reviewer:** @ThomasA, @kczimm 
**Archive:** <a href="https://doi.org/10.5281/zenodo.810391" target="_blank">10.5281/zenodo.810391</a>

## Status

[![status](http://joss.theoj.org/papers/63b4f3c7170b7dc431d6870abba0a9cd/status.svg)](http://joss.theoj.org/papers/63b4f3c7170b7dc431d6870abba0a9cd)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/63b4f3c7170b7dc431d6870abba0a9cd"><img src="http://joss.theoj.org/papers/63b4f3c7170b7dc431d6870abba0a9cd/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/63b4f3c7170b7dc431d6870abba0a9cd/status.svg)](http://joss.theoj.org/papers/63b4f3c7170b7dc431d6870abba0a9cd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/astorfi/speechpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ThomasA & @jjatria, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/astorfi/speechpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.3)?
- [x] **Authorship:** Has the submitting author (@astorfi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/astorfi/speechpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.3)?
- [x] **Authorship:** Has the submitting author (@astorfi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @ThomasA, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by arfon** [comment]
@ThomasA, @jjatria - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by ThomasA** [comment]
I checked the article proof. Comparing to the GitHub-formatted Markdown [here](https://github.com/astorfi/speechpy/blob/master/paper/paper.md), the PDF seems to be typeset wrong: the bullet list specified with "+"-es does not get typeset properly.

**Comment by ThomasA** [comment]
If you don't mind, I am just going to comment bit by bit here as I go through the review...

- Version: Links to the repository do not point to any specific version, but there is a release tagged 2.3 in the repository. I suppose this is OK?

**Comment by ThomasA** [comment]
- Authorship: In addition to @astorfi, @MatthewScholefield has made a small contribution to the project and @cclauss a very tiny one. Given that @astorfi has contributed the vast majority of the package, I guess it is OK that he is the sole author of this publication?

**Comment by ThomasA** [comment]
- Installation: This works as documented in the repository's README, but: I explicitly checked out the '2.3' release for installation whereas the install script output refers to version 2.2:

    $ python setup.py develop
    running develop
    running egg_info
    creating speechpy.egg-info
    writing speechpy.egg-info/PKG-INFO
    writing dependency_links to speechpy.egg-info/dependency_links.txt
    writing requirements to speechpy.egg-info/requires.txt
    writing top-level names to speechpy.egg-info/top_level.txt
    writing manifest file 'speechpy.egg-info/SOURCES.txt'
    reading manifest file 'speechpy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'speechpy.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/tha/.conda/envs/joss-review-tmp/lib/python3.6/site-packages/speechpy.egg-link (link to .)
    Adding speechpy 2.2 to easy-install.pth file
    
    Installed /home/tha/other-repo/speechpy
    Processing dependencies for speechpy==2.2
    Searching for numpy==1.14.3
    Best match: numpy 1.14.3
    Adding numpy 1.14.3 to easy-install.pth file
    
    Using /home/tha/.conda/envs/joss-review-tmp/lib/python3.6/site-packages
    Searching for scipy==1.1.0
    Best match: scipy 1.1.0
    Adding scipy 1.1.0 to easy-install.pth file
    
    Using /home/tha/.conda/envs/joss-review-tmp/lib/python3.6/site-packages
    Finished processing dependencies for speechpy==2.2

I suspect this is just some configuration text string that was not properly updated for the 2.3 release, but I think @astorfi should check and possibly correct this so we are sure that it indeed installs the 2.3 release.

**Comment by ThomasA** [comment]
- Example usage: Glancing through the documentation, I did not find any usage examples, but the test scripts can be considered not-too-well-documented examples. A few usage examples that were easier to find and documented with a bit of explanatory text would be nice to have.

**Comment by ThomasA** [comment]
- Functionality documentation: The package's functions are documented with docstrings and nicely formatted in the package HTML documentation. The modules of the package, however, do not have any docstrings. This could be a slight improvement, also when quickly looking up documentation from IPython, for example: `speechpy.processing?`

      Type:        module
      String form: <module 'speechpy.processing' from '/home/tha/other-repo/speechpy/speechpy/processing.py'>
      File:        ~/other-repo/speechpy/speechpy/processing.py
      Docstring:   <no docstring>

**Comment by ThomasA** [comment]
- Automated tests: There are tests available in the 'tests' folder. These are in my opinion more like usage examples and not proper tests in the sense that they do not check anything. They run some example commands and display the output. In my opinion, proper automated tests should check the output and determine whether it is correct, resulting in clearly 'passed' or 'failed' test cases.

**Comment by ThomasA** [comment]
- Community guidelines: The package documentation has very clear guidelines on [how to contribute](http://speechpy.readthedocs.io/en/latest/epilogue/finalnote.html#contributing) to the project. It is however a bit unclear on the reporting issues and seeking support aspects. The latter two aspects could be improved for example by mentioning the that issues should be reported in the repository's issue tracker or similar.

  In addition, it would be helpful to mention these things in the repository's README as well, where potential users and contributors can more easily find it at a quick glance.

**Comment by ThomasA** [comment]
- References: The software paper does not list any references and as such does not need DOIs for these.

**Comment by ThomasA** [comment]
I am done with the first pass of my review, but before I recommend publication I would like to hear what @astorfi thinks of my comments.

**Comment by astorfi** [comment]
@ThomasA Thank you for your review. I will investigate them and will comment here.

**Comment by astorfi** [comment]
@ThomasA About the docstring for modules you are absolutely correct. I am modifying the repo as you suggested and will investigate the rest afterwards.

**Comment by astorfi** [comment]
@ThomasA Just added docstrings for modules. Please kindly send me your feedback.

**Comment by astorfi** [comment]
@ThomasA @arfon About the "+" es, I just check it and you are correct. I changed them to "*" es with some space. However, I do not know how to render PDF to see if it resolved the issue.

**Comment by astorfi** [comment]
@ThomasA As you kindly suggested, I added a contributing section in the README as well as how to declare and follow issues. However, about ``seeking support aspects`` that you mentioned, I need a little bit more clarification if possible.

**Comment by astorfi** [comment]
@ThomasA  About creating test cases, I am working on it and will get back with the updated information.

**Comment by jjatria** [comment]
I have been trying to find time to take a look at this, and I just don't think I'll be able to.
Apologies for the trouble.

**Comment by ThomasA** [comment]
@arfon more general question; how is it handled when a review leads to some revisions - like here? The tagged version 2.3 of the repository will be out-dated by the revisions discussed here. Should the collected revisions be released as 2.3.1 and the paper here updated to refer to that version?

**Comment by ThomasA** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by ThomasA** [comment]
Hmm, I dunno - let's try:
@whedon generate pdf

**Comment by ThomasA** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by ThomasA** [comment]
Yay, it works! @astorfi the bullet list comes out right now.

**Comment by ThomasA** [comment]
I need to be careful not to get too picky here, but I can perhaps recommend you run `pycodestyle` on your modules to get [PEP8](https://www.python.org/dev/peps/pep-0008/) code style recommendations? Over-long lines of text in docstrings are a bit annoying to read in terminals...

**Comment by cclauss** [comment]
https://github.com/astorfi/speechpy/pull/19 runs http://flake8.pycqa.org testing which is a superset of PyCodeStyle (fka PEP8) + PyFlakes + McCabe complexity + syntax checking.

**Comment by ThomasA** [comment]
@cclauss sounds like a good idea. Fixing for example over-long lines would be nice.

**Comment by arfon** [comment]
> @arfon more general question; how is it handled when a review leads to some revisions - like here? The tagged version 2.3 of the repository will be out-dated by the revisions discussed here. Should the collected revisions be released as 2.3.1 and the paper here updated to refer to that version?

Yes, we'll just update the revision at the end of the review (when the archive of the code is made).

**Comment by ThomasA** [comment]
> Just added docstrings for modules. Please kindly send me your feedback.

I have proposed some minor revisions of your docstrings in https://github.com/astorfi/speechpy/pull/21.

**Comment by ThomasA** [comment]
> However, about seeking support aspects that you mentioned, I need a little bit more clarification if possible.

I think you have got this covered by "technical and conceptual questions".

**Comment by astorfi** [comment]
@cclauss  Thank you!

**Comment by astorfi** [comment]
@ThomasA  Thank you for all the suggestions. I will investigate them and will get back with the possible changes.

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by astorfi** [comment]
@ThomasA The modules and functions related to SpeechPy, have been modified to be ai aligned with [PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/#fn-hi).

**Comment by astorfi** [comment]
@ThomasA  Tests has been added as well. Although there is room for improvement as well. However, I added the tests for different parts for continuous integration as well. Example usage has been separated.

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by ThomasA** [comment]
> Example usage: Glancing through the documentation, I did not find any usage examples, but the test scripts can be considered not-too-well-documented examples. A few usage examples that were easier to find and documented with a bit of explanatory text would be nice to have.

The former test scripts are now used as usage examples and likewise shown in the README. I think this is fine now.

**Comment by ThomasA** [comment]
> Automated tests: There are tests available in the 'tests' folder. These are in my opinion more like usage examples and not proper tests in the sense that they do not check anything. They run some example commands and display the output. In my opinion, proper automated tests should check the output and determine whether it is correct, resulting in clearly 'passed' or 'failed' test cases.

There are now automated tests using `pytest` in the 'tests' folder. They are not overly thorough (the coverage seems a bit low and the tests mostly check details like correct shape of outputs), but some testing is better than none and now it has a testing framework set up that more tests can easily be added to.

**Comment by ThomasA** [comment]
As far as I am concerned, I am done with the review and can **recommend publication**.
If you like, @astorfi , I can nitpick and style-comb the repository a bit more, but I am trying not to get too intrusive :-)

**Comment by arfon** [comment]
Thanks @ThomasA! @jjatria - when you do you think you might be able to complete your review by?

**Comment by astorfi** [comment]
@ThomasA  Thank you so much for your suggestions, modifications, and review. You are always welcome to propose changes in the repo.

**Comment by astorfi** [comment]
Hey @arfon. As @jjatria  Mentioned here, he might not be able to do it.
If possible, please propose a new reviewer.

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by arfon** [comment]
@kczimm - would you be available to provide a second review of this package?

**Comment by astorfi** [comment]
@arfon  I guess @kczimm  is not available as well

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by astorfi** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by astorfi** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by kczimm** [comment]
I'm sorry I'm just seeing this. I don't know the required timeline but I can finish a review of this package over the weekend.

**Comment by arfon** [comment]
@kczimm - great, thanks! Please go ahead and carry out the review in this thread. The timeline you propose would be perfect.

**Comment by astorfi** [comment]
Dear @arfon  and @kczimm ,
Thank you both very much.

**Comment by kczimm** [comment]
I see the automated tests in the tests directory, however the coverage is minimal, as was previously mentioned. Although I wouldn't say more is required for recommendation, I strongly urge increasing the test coverage.

**Comment by astorfi** [comment]
@kczimm  Thank you for your suggestions.

About the first one:
[test_package.py](https://github.com/astorfi/speechpy/blob/master/example/test_package.py) is designed to exactly perform the job of [test_local.py](https://github.com/astorfi/speechpy/blob/master/example/test_local.py). [test_package.py](https://github.com/astorfi/speechpy/blob/master/example/test_package.py) file also requires **a pip install**. Both are available in the [example](https://github.com/astorfi/speechpy/tree/master/example) folder.

**Comment by astorfi** [comment]
@kczimm  About the tests, you are absolutely correct. However, as the package is currently a feature extractor, it is not trivial to add tests for accuracy tests. I tried to add tests as I make sure the package can be tested for minimal run requirements. It also tests the outputs to be in the correct format.

**Comment by kczimm** [comment]
@astorfi Thanks for the explanations. Based on these and the explanations you've already provided to @ThomasA, I've completed my review and can recommend publication. Good work.

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by astorfi** [comment]
Thank you @kczimm .
@arfon  Should I take any further action?

**Comment by astorfi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00749/joss.00749/10.21105.joss.00749.pdf)

**Comment by arfon** [comment]
Thanks for your reviews @ThomasA, @kczimm!

@astorfi - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by astorfi** [comment]
@arfon  I updated the version in Zenodo as well as the PyPi.
Please check to see if it is suitable.
Thanks

**Comment by arfon** [comment]
Looks like the Zenodo DOI (https://doi.org/110.5281/zenodo.810391) isn't resolving yet... Perhaps it takes a few hours to register?

**Comment by astorfi** [comment]
@arfon Yes it may take a while

**Comment by astorfi** [comment]
@arfon  Please check. I think it is resolved now.

**Comment by astorfi** [comment]
@arfon I realized that I made a mistake and I put the DOI as [https://doi.org/110.5281/zenodo.810391](https://doi.org/110.5281/zenodo.810391) instead of [https://doi.org/10.5281/zenodo.810391](https://doi.org/10.5281/zenodo.810391). I think it is solved now.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.810391 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.810391" target="_blank">10.5281/zenodo.810391</a> is the archive.

**Comment by arfon** [comment]
@astorfi - It looks like the citations aren't being compiled into the paper as you're not citing them directly. You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html).

**Comment by astorfi** [comment]
@arfon I see the citations in the article proof. I am not quite sure if I got your point.

**Comment by arfon** [comment]
> @arfon I see the citations in the article proof. I am not quite sure if I got your point.

Sorry for any confusion. I was working with an earlier clone of your repo.

BTW, I did need to make a small change to your `paper.md` to get the images working: https://github.com/astorfi/speechpy/pull/25

**Comment by arfon** [comment]
@ThomasA & @kczimm - many thanks for your reviews here! ✨ 

@astorfi - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00749 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00749/status.svg)](https://doi.org/10.21105/joss.00749)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00749">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00749/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00749/status.svg)](https://doi.org/10.21105/joss.00749)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
