### ISSUE TITLE
[REVIEW]: ezknitr: Avoid the typical working directory pain when using 'knitr'

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#75]
**Submitting author:** @daattali (<a href="http://orcid.org/0000-0002-5645-3493">Dean Attali</a>)
**Repository:** <a href="https://github.com/ropenscilabs/ezknitr" target ="_blank">https://github.com/ropenscilabs/ezknitr</a>
**Version:** v0.5
**Editor:** @acabunoc
**Reviewer:** @acabunoc
**Archive:** <a href="http://dx.doi.org/10.6084/m9.figshare.3545363" target="_blank">10.6084/m9.figshare.3545363</a>

## Status

[![status](http://joss.theoj.org/papers/b89568b89a7b8fd7d0792fcd836ba120/status.svg)](http://joss.theoj.org/papers/b89568b89a7b8fd7d0792fcd836ba120)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b89568b89a7b8fd7d0792fcd836ba120"><img src="http://joss.theoj.org/papers/b89568b89a7b8fd7d0792fcd836ba120/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b89568b89a7b8fd7d0792fcd836ba120/status.svg)](http://joss.theoj.org/papers/b89568b89a7b8fd7d0792fcd836ba120)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropenscilabs/ezknitr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropenscilabs/ezknitr">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.5)?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by acabunoc** [comment]
I hope it's okay that I'm both editor and reviewer!

Based on the review completed for ropensci: https://github.com/ropensci/onboarding/issues/56, I think we should accept this to JOSS

**Comment by arfon** [comment]
> I hope it's okay that I'm both editor and reviewer!

👍 sounds good to me! Lemme just compile the paper to check things look good there. (@whedon can't do this just yet)

**Comment by arfon** [comment]
@acabunoc - there was a small update required here: https://github.com/ropenscilabs/ezknitr/pull/9

@daattali - @acabunoc has recommended acceptance here. At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by daattali** [comment]
rOpenSci already required us to submit to figshare: 10.6084/m9.figshare.3545363

**Comment by arfon** [comment]
Thanks for handling this @acabunoc.

@daattali - your paper is now accepted into JOSS. Your DOI is http://joss.theoj.org/papers/10.21105/joss.00075 🎉 🚀 💥
