### ISSUE TITLE
[PRE REVIEW]: PyBox: An automated box-model generator for atmospheric chemistry and aerosol simulations.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#750]
**Submitting author:** @loftytopping (<a href="http://orcid.org/0000-0001-8247-9649">David Topping</a>)
**Repository:** <a href="https://github.com/loftytopping/PyBox" target ="_blank">https://github.com/loftytopping/PyBox</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewers:** @dvalters, @highendcompute

**Author instructions**

Thanks for submitting your paper to JOSS @loftytopping. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@loftytopping if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00750/joss.00750/10.21105.joss.00750.pdf)

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor.

**Comment by loftytopping** [comment]
Hi guys.

Great any thanks for progressing. Ive had a look at the existing reviewers and would suggest dvalters is ideal given he covers everything PyBox is designed for.  Another reviewer who is not on the list but I would suggest is Dr Michael Bane [mkb@highendcompute.co.uk] as he would offer a robust critique/testing of the automated Python-to-Fortran component.

Thanks!
Dave

**Comment by lheagy** [comment]
Thanks @loftytopping! I will send an email to Dr. Michael Bane and see if he is willing to review. Do you have any other reviewer suggestions? Ideally, we get 2.

**Comment by loftytopping** [comment]
Hi! Great. Ok cool, can you get in touch with 'dvalters' from the current JOSS reviewers list too? This covers Python, OpenMP and the domain of interest so its perfect for PyBox if they can review :).

**Comment by lheagy** [comment]
👋 Hi @dvalters, would you be willing to review this submission for JOSS?

**Comment by dvalters** [comment]
Hi @lheagy - sure I can review

**Comment by lheagy** [comment]
Thanks @dvalters! Michael has also agreed to review - I am just waiting to get his github handle and we can get started.

**Comment by lheagy** [comment]
@whedon assign @dvalters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by lheagy** [comment]
@whedon add @highendcompute as reviewer

**Comment by lheagy** [comment]
@whedon add @highendcompute as reviewer

**Comment by whedon** [comment]
OK, @highendcompute is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/755. Feel free to close this issue now!
