### ISSUE TITLE
[PRE REVIEW]: Neutron Imaging Normalization Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#751]
**Submitting author:** @jeanbilheux (<a href="http://orcid.org/0000-0003-2172-6487">Jean Bilheux</a>)
**Repository:** <a href="https://github.com/scikit-beam/NeuNorm" target ="_blank">https://github.com/scikit-beam/NeuNorm</a>
**Version:** 1.4.0
**Editor:** @arfon
**Reviewers:** @stuartcampbell

**Author instructions**

Thanks for submitting your paper to JOSS @jeanbilheux. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jeanbilheux if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00751/joss.00751/10.21105.joss.00751.pdf)

**Comment by arfon** [comment]
@JeanBilheux - could you take a look at this list of reviewers and suggest a few that might be good candidates to review this package? https://bit.ly/joss-reviewers

**Comment by JeanBilheux** [comment]
I know Stuart Campbell background and I think he is the perfect candidate to review this package. 
scampbell@bnl.gov

**Comment by arfon** [comment]
> I know Stuart Campbell background and I think he is the perfect candidate to review this package.
scampbell@bnl.gov

OK thanks @JeanBilheux - I've just sent him an email.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @stuartcampbell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stuartcampbell

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/815. Feel free to close this issue now!

**Comment by arfon** [comment]
Thanks for agreeing to review this @stuartcampbell!
