### ISSUE TITLE
[PRE REVIEW]: Philentropy: Information Theory and Distance Quantification with R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#752]
**Submitting author:** @HajkD (<a href="http://orcid.org/0000-0002-1567-306X">Hajk-Georg Drost</a>)
**Repository:** <a href="https://github.com/HajkD/philentropy" target ="_blank">https://github.com/HajkD/philentropy</a>
**Version:** v0.2.0
**Editor:** @leeper
**Reviewers:** @kellieotto

**Author instructions**

Thanks for submitting your paper to JOSS @HajkD. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@HajkD if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by HajkD** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00752/joss.00752/10.21105.joss.00752.pdf)

**Comment by HajkD** [comment]
@whedon add @kellieotto as reviewer

**Comment by whedon** [comment]
I'm sorry @HajkD, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by HajkD** [comment]
Hi,

Many thanks for the managing the review process.

After going through the list of potential reviewers I would like to suggest @kellieotto and @sctyner as reviewers.

Kind regards,
Hajk

**Comment by kellieotto** [comment]
I'd be glad to review. Looks like we're still waiting for an editor to be assigned.

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by leeper** [comment]
@whedon commands

**Comment by leeper** [comment]
@arfon it appears @whedon has become unresponsive.

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by leeper** [comment]
@whendon assign @kellieotto as reviewer

**Comment by leeper** [comment]
@whedon assign @kellieotto as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kellieotto

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/765. Feel free to close this issue now!

**Comment by leeper** [comment]
@kellieotto Thanks for agreeing to review for JOSS. The review ticket is open here: https://github.com/openjournals/joss-reviews/issues/765

**Comment by arfon** [comment]
> @arfon it appears @whedon has become unresponsive.

Looks like he was a little sleepy there for a while...
