### ISSUE TITLE
[REVIEW]: sjmisc - Data and Variable Transformation Functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#754]
**Submitting author:** @strengejacke (<a href="http://orcid.org/0000-0002-8895-3206">Daniel Lüdecke</a>)
**Repository:** <a href="https://github.com/strengejacke/sjmisc" target ="_blank">https://github.com/strengejacke/sjmisc</a>
**Version:** 2.7.2
**Editor:** @leeper
**Reviewer:** @jrosen48, @methodds
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1293370" target="_blank">10.5281/zenodo.1293370</a>

## Status

[![status](http://joss.theoj.org/papers/81c535ee0b1991849e310b87e13209de/status.svg)](http://joss.theoj.org/papers/81c535ee0b1991849e310b87e13209de)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/81c535ee0b1991849e310b87e13209de"><img src="http://joss.theoj.org/papers/81c535ee0b1991849e310b87e13209de/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/81c535ee0b1991849e310b87e13209de/status.svg)](http://joss.theoj.org/papers/81c535ee0b1991849e310b87e13209de)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/strengejacke/sjmisc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jrosen48 & @methodds, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/strengejacke/sjmisc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.7.2)?
- [x] **Authorship:** Has the submitting author (@strengejacke) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/strengejacke/sjmisc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.7.2)?
- [x] **Authorship:** Has the submitting author (@strengejacke) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jrosen48, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00754/joss.00754/10.21105.joss.00754.pdf)

**Comment by jrosen48** [comment]
@leeper if I have comments about, just for example because it's the first item I came upon that I think I may have a note for, the following item:

`Repository: Is the source code for this software available at the repository url?

Do you suggest I add them a) in a comment here below the checklist, b) as a note beside the checklist item, c) as an issue in the repository, d) a differeny way? 

Thanks!

**Comment by leeper** [comment]
@jrosen48 You can do either (a) open an issue on the source repo with a link back to this page, asking for changes, or (b) create a cumulative review that raises all issues not addressed in the checklist and leave it as a comment here, or a mix of both.

**Comment by strengejacke** [comment]
May I kindly ask how the review process continues? Will the reviewers let me or you know when they finished their review, or will I be contacted via notification? Just wondering, because from the checklist you can't completely decide if there are parts left to review, or if these are issues I have to address. :-)

**Comment by leeper** [comment]
@strengejacke  I've had a look at the reviews so far and opened several issues for you to address in line with the unchecked items above. Please address these and I will then ask the reviewers to take another look.

**Comment by strengejacke** [comment]
Thanks for your comments, I have addressed the above mentioned issues.

1) I added a paragraph with statement of need to the README file, so it's immediately obvious to visitors of the GitHub Repo. Furthermore, the README now also links to a CONTRIBUTION file.

2) I added a detailed CONTRIBUTION file, which guides users how they may contribute to my package.

3) I added a lot of tests (using testthat) to the `/tests`-folder. Tests not just check if arguments are working (which is also done in the examples), but check if certain inputs result in the expected outputs.

**Comment by leeper** [comment]
Thanks. @jrosen48 can you take another look and see if anything else should be addressed?

**Comment by jrosen48** [comment]
Hi @leeper, I think @strengejacke did a great job of addressing the issues you raised. 

1. I think the paragraph with a statement of need added to the README is strong (particularly this: "Packages for data preparation have been released recently as part of the tidyverse, focussing on the transformation of data sets. Packages with special focus on transformation of variables, which fit into the workflow and design-philosophy of the tidyverse, are missing."). 

2. The contribution page is excellent, with a description of *multiple* ways users can contribute, including filing issues and making pull requests (with specific and helpful instructions in both cases).

3. The tests use built-in and small, constructed data sets, to test many (most?) to test multiple sets of arguments and types of inputs to, as @strengejacke mentioned, test their output.

**Comment by strengejacke** [comment]
At this point I'd really like to thank the editors and reviewers for their work so far. The process of paper submission and review raised awareness of the fact that a GitHub-repo is not just only a "cloud-backup", but also a place where users inform themselves about software and its intention and need. I think changing the perspective from the repo-owner to a "visitor" - and that's what's necessary to do when preparing a paper for JOSS - is really helpful to make the software and documentation more accessable!

**Comment by leeper** [comment]
@jrosen48 Thank you! It sounds like we're both satisfied then.

@strengejacke Please issue a release of the package and obtain a DOI for the release from, for example, figshare or zenodo and post that DOI here when you have it.

**Comment by strengejacke** [comment]
The current version (2.7.2) is already registered at zenodo: http://doi.org/10.5281/zenodo.1249192
The doi referring to the latest version on zenodo is 10.5281/zenodo.1249191.

**Comment by leeper** [comment]
You should be able to get a DOI for a new release. We want the one for the final version as accepted by JOSS.

**Comment by strengejacke** [comment]
Ok, here it is: 10.5281/zenodo.1293370

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1293370 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1293370" target="_blank">10.5281/zenodo.1293370</a> is the archive.

**Comment by leeper** [comment]
@arfon over to you

**Comment by arfon** [comment]
@jrosen48, @methodds - many thanks for your reviews here and to @leeper for editing this submission ✨ 

@strengejacke - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00754 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00754/status.svg)](https://doi.org/10.21105/joss.00754)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00754/status.svg)](https://doi.org/10.21105/joss.00754)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by strengejacke** [comment]
Thanks a lot to all! btw, I signed up as potential reviewer already some time ago, I really like the idea of this journal. Especially thanks to @leeper - my impression is, that he's the only editor for social sciences and R and has to edit quite some submissions here. Great work!

**Comment by jrosen48** [comment]
Congrats @strengejacke--please keep up the exemplary work grealt benefits the R community. Thanks  @leeper and @methodds & @arfon for being part of a great process (for reviewers!).
