### ISSUE TITLE
[PRE REVIEW]: stacomiR : a common tool for monitoring fish migration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#756]
**Submitting author:** @MarionLegrandLogrami (<a href="http://orcid.org/0000-0002-4688-8303">Marion Legrand</a>)
**Repository:** <a href="https://github.com/MarionLegrandLogrami/stacomiR" target ="_blank">https://github.com/MarionLegrandLogrami/stacomiR</a>
**Version:** 0.5.3.1
**Editor:** @arfon
**Reviewers:** @steffilazerte

**Author instructions**

Thanks for submitting your paper to JOSS @MarionLegrandLogrami. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MarionLegrandLogrami if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #756 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:78:in `check_fields': Paper YAML header is missing expected fields: tags (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon.rb:66:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/lib/whedon/processor.rb:29:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-a31a5c2a9125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by MarionLegrandLogrami** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #756 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0     65      0 --:--:-- --:--:-- --:--:--    66
pandoc-citeproc: Cannot decode byte '\x75': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by MarionLegrandLogrami** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00756/joss.00756/10.21105.joss.00756.pdf)

**Comment by MarionLegrandLogrami** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00756/joss.00756/10.21105.joss.00756.pdf)

**Comment by MarionLegrandLogrami** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by MarionLegrandLogrami** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @MarionLegrandLogrami, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
👋@MarionLegrandLogrami - could you take a look at this list of potential reviewers and suggeste a few names? https://bit.ly/joss-reviewers

**Comment by MarionLegrandLogrami** [comment]
Thanks for the list of potential reviewers. I suggest : amoeba, pboesu, jhollist, steffilazerte and ben-williams.
Thanks a lot

**Comment by arfon** [comment]
:wave: @steffilazerte @ben-williams - would you be willing to review this submission for JOSS?

**Comment by steffilazerte** [comment]
Sure!

**Comment by arfon** [comment]
@whedon assign @steffilazerte as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/791. Feel free to close this issue now!

**Comment by arfon** [comment]
@MarionLegrandLogrami @steffilazerte - please head over to #791 for the actual review.
