### ISSUE TITLE
[PRE REVIEW]: Salabim: discrete event simulation and animation in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#759]
**Submitting author:** @salabim (<a href="http://orcid.org/0000-0001-7696-8059">Ruud van der Ham</a>)
**Repository:** <a href="https://github.com/salabim/salabim" target ="_blank">https://github.com/salabim/salabim</a>
**Version:** 2.2.23
**Editor:** @danielskatz
**Reviewers:** @gonsie, pspringer, @pspringer

**Author instructions**

Thanks for submitting your paper to JOSS @salabim. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@salabim if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00759/joss.00759/10.21105.joss.00759.pdf)

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@salabim - do you have any suggestions for reviewers?  Perhaps from [this list of people](https://bit.ly/joss-reviewers) who have already agreed to review for JOSS and may be suitable for this submission?

**Comment by salabim** [comment]
gonsie ( gonsiorowski1@llnl.gov) has indicated to have discrete event
simulation as his domain/topic for review.




Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by danielskatz** [comment]
@gonsie - would you be willing to be a reviewer for this submission?

**Comment by gonsie** [comment]
Yes, I will review this submission.

**Comment by danielskatz** [comment]
thanks!

I'm also contacting one more person by email, and I would ideally like to get 2 reviewers, since I don't know this area well.  I'll let you know when the review is ready to start

**Comment by danielskatz** [comment]
@whedon assign @gonsie as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gonsie

**Comment by danielskatz** [comment]
@whedon add pspringer as reviewer

**Comment by whedon** [comment]
OK, pspringer is now a reviewer

**Comment by danielskatz** [comment]
@whedon add @pspringer as reviewer

**Comment by whedon** [comment]
OK, @pspringer is now a reviewer

**Comment by danielskatz** [comment]
@whendon remove pspringer as reviewer

**Comment by danielskatz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by danielskatz** [comment]
@wendon remove pspringer as reviewer

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/767. Feel free to close this issue now!
