### ISSUE TITLE
[PRE REVIEW]: Python Active-subspaces Utility Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#76]
**Submitting author:** @paulcon (<a href="http://orcid.org/0000-0003-3726-6307">Paul Constantine</a>)
**Repository:** <a href="https://github.com/paulcon/active_subspaces" target ="_blank">https://github.com/paulcon/active_subspaces</a>
**Version:** v 0.1
**Editor:** @kyleniemeyer
**Reviewer:** @nicoguaro

**What this issue is for**

Thanks for submitting your paper to JOSS @paulcon. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer, it looks like you're currently assigned as the editor for this paper :tada: 

For a list of things I can do to help you, just type: 

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by paulcon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://gist.github.com/arfon/5317c568cb32c7b917fea3c13958131d

**Comment by kyleniemeyer** [comment]
Hi @jordigh & alex-konovalov: would either of you be able to review this submission? I've also requested a review from an external subject-area expert, so just one of you would be great.

**Comment by kyleniemeyer** [comment]
@whedon assign @mtezzele as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mtezzele

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK starting the review

**Comment by kyleniemeyer** [comment]
@whedon assign @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nicoguaro
