### ISSUE TITLE
[PRE REVIEW]: quanteda: An R package for the quantitative analysis of textual data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#760]
**Submitting author:** @kbenoit (<a href="http://orcid.org/0000-0002-0797-564X">Kenneth Benoit</a>)
**Repository:** <a href="https://github.com/quanteda/quanteda" target ="_blank">https://github.com/quanteda/quanteda</a>
**Version:** v1.3
**Editor:** @arfon
**Reviewers:** @lmullen, @borishejblum, @alexgarciac

**Author instructions**

Thanks for submitting your paper to JOSS @kbenoit. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kbenoit if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by leeper** [comment]
@arfon Given @kenbenoit and I are at the same institution, I believe I can't edit this according to our rules. Perhaps @karthik can manage?

**Comment by karthik** [comment]
I believe I  also have a COI with Ken.

**Comment by arfon** [comment]
OK, I'll take this one.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @kenbenoit - can you take a look the list of JOSS reviewers https://bit.ly/joss-reviewers and suggest a few potential reviewers?

**Comment by kbenoit** [comment]
Will do very shortly - but I failed to see the notifications because my GitHub name is listed wrongly - it's actually @kbenoit.

**Comment by kbenoit** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by kbenoit** [comment]
@whedon assign @juliasilge as reviewer
@whedon assign @bstewart as reviewer

**Comment by whedon** [comment]
I'm sorry @kbenoit, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by kbenoit** [comment]
OK @whedon then please accept those as my referee recommendations. Another possibility would be @matthewjdenny.

**Comment by kbenoit** [comment]
From the list, I suggest @lmullen or @zfurnas. I can provide other suggestions but they are not from the list.

**Comment by lmullen** [comment]
I can review this but may need a little flexibility with the due date.

**Comment by arfon** [comment]
@borishejblum - would you be willing to review this submission for JOSS?

**Comment by borishejblum** [comment]
I can review this submission, what is the due date ?

**Comment by alexgarciac** [comment]
I could also review this one. What is the die date?

**Comment by arfon** [comment]
> I could also review this one. What is the die date?

Next couple of weeks would be ideal.

**Comment by arfon** [comment]
@whedon add @lmullen as reviewer

**Comment by whedon** [comment]
OK, @lmullen is now a reviewer

**Comment by arfon** [comment]
@whedon add @borishejblum as reviewer

**Comment by whedon** [comment]
OK, @borishejblum is now a reviewer

**Comment by arfon** [comment]
@whedon add @alexgarciac as reviewer

**Comment by whedon** [comment]
OK, @alexgarciac is now a reviewer

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/774. Feel free to close this issue now!

**Comment by arfon** [comment]
@lmullen, @borishejblum, @alexgarciac - many thanks for agreeing to review this submission. Please head over to #774 to carry out the actual review.
