### ISSUE TITLE
[PRE REVIEW]: Nashpy: A Python library for the computation of Nash equilibria

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#761]
**Submitting author:** @drvinceknight (<a href="http://orcid.org/0000-0002-4245-0638">Vincent Knight</a>)
**Repository:** <a href="https://github.com/drvinceknight/Nashpy" target ="_blank">https://github.com/drvinceknight/Nashpy</a>
**Version:** v0.0.14
**Editor:** @labarba
**Reviewers:** @Fil, @alex-konovalov

**Author instructions**

Thanks for submitting your paper to JOSS @drvinceknight. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@drvinceknight if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by labarba** [comment]
@drvinceknight In several places (repo, docs), you have a note like "to do sophisticated equilibria computation you should use gambit" — could you explain how this software, which you say computes equilibria in 2-player games only, would be useful in a research scenario?

**Comment by drvinceknight** [comment]
> After inspecting the software repository and the documentation, I get the clear impression that this package has more of a pedagogical value than a research application. You recently reviewed one of our first submissions to JOSE (thanks!) ... that software originally came to JOSS—have a look at the pre-review discussion: #212
> Do you think your submission here is in a similar situation? (That would be my impression.)

I actually was hesitating in my choice for this one: I'll happily resubmit this over to JOSE :)

**Comment by labarba** [comment]
👍  I do think you should include a couple of worked-out examples, in that case. For JOSE, one thing we want is to make it easier for someone else to adopt the software/materials, or for someone to use them for self-learning. Worked examples are important for that.

**Comment by drvinceknight** [comment]
> I do think you should include a couple of worked-out examples, in that case. For JOSE, one thing we want is to make it easier for someone else to adopt the software/materials, or for someone to use them for self-learning. Worked examples are important for that.

Yup of course, I'm at a conference at the moment but will reshape the paper for JOSE. In terms of worked examples, do you mean in `paper.md`? The library [documentation](http://nashpy.readthedocs.io/en/stable/) has quite an extensive set of examples.

A thought: I've actually used Nashpy for a game theory course which uses software in a lot of other ways as well that I was thinking as writing up as a paper for JOSE also. (Use of gh-pages as content delivery, heavy reliability on jupyter notebooks with a testing framework, bespoke static site generator, as well as sphinx backed documentation of "how to lead the course".) My intent is that the paper on Nashpy and the course would not be the same.

**Comment by drvinceknight** [comment]
I have submitted this to JOSE so am closing this. Thanks :+1:

**Comment by drvinceknight** [comment]
Dear editors,

I would like to un-"withdraw" this paper, please let me know if it's simpler if I were to resubmit it perhaps?

This follows a discussion at JOSE https://github.com/openjournals/jose-reviews/issues/18 were I believe it has become clear that a paper about this software library is not within the scope of JOSE.

I apologise for the confusion/mistake.

@labarba regarding your queries prior to withdrawal:

> @drvinceknight In several places (repo, docs), you have a note like "to do sophisticated equilibria computation you should use gambit" — could you explain how this software, which you say computes equilibria in 2-player games only, would be useful in a research scenario?

I have modified the paper to hopefully make this clearer, the following is now included:

```
# Statement of need

Access to these algorithms is non trival, an example of this includes the
modelling of healthcare decisions [@knight2017measuring] where a bespoke
theoretic result was used to design a specific algorithm for the computation of
equilibria. Easily accessibly software would make that research more
straightforward as no new algorithm would need to be implemented.

The most mature piece of software available for the computation of equilibria
is **Gambit** [@mckelvey2006gambit]. Gambit includes a python wrapper to its
core C functionality however is not currently portable for example
Windows is not supported. There does exist a web interface with a Gambit back
end: [Game theory
explorer](http://gte.csc.liv.ac.uk/index/index.html#document-documentation)
however this is not practical for reproducible research.

``Nashpy`` is a Python library with all dependencies being part of the standard
scientific Python stack (numpy and scipy [@scipy]) thus it is portable. For
example Windows support is regularly tested through a Windows continuous
integration service (Appveyor).
```

I don't believe that there being another piece of software that has the same functionality precludes from publication in JOSS  but I might be mistaken.

Apologies again for the confusion and extra work that has resulted.

**Comment by arfon** [comment]
> I would like to un-"withdraw" this paper, please let me know if it's simpler if I were to resubmit it perhaps?

OK, thanks for the heads up @drvinceknight. We should be able to work with this original submission.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00761/joss.00761/10.21105.joss.00761.pdf)

**Comment by arfon** [comment]
@drvinceknight - looks like some of the LaTeX formatting is a little wonky in the compiled PDF ☝️. Could you try and fix that? If you make a change to your `paper.md` you can ask @whedon to recompile the paper with `@whedon generate pdf`

**Comment by drvinceknight** [comment]
Sorry for the late reply @arfon, I've had a week's leave. Thanks for taking a look at this :) Regenerating now :+1:

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00761/joss.00761/10.21105.joss.00761.pdf)

**Comment by drvinceknight** [comment]
That's looking good to me, let me know if there's anything else I should/could do at this stage.

**Comment by drvinceknight** [comment]
@arfon @labarba I realise everyone is busy so no problem at all (and apologies for the pings), just checking if I there's anything I can do and/or should be doing to start the ball rolling on the review process? (In case perhaps this has been forgotten).

**Comment by arfon** [comment]
Hi @drvinceknight - things are pretty busy at JOSS right now (close to 100 submissions on the go!) so we're a little slow getting to things.

Can you look at [this list of potential reviewers](https://bit.ly/joss-reviewers) and suggest a few people that might be suitable to review your package?

**Comment by drvinceknight** [comment]
No problem at all, I completely understand: zero pressure/impatience on my side.

Looking through the list I'd suggest https://github.com/fil looks like a good fit, otherwise https://github.com/jordigh or https://github.com/nicoguaro perhaps.

Thank you again to all the editors for your efforts/work on this journal.

**Comment by Fil** [comment]
I'm in @labarba

**Comment by labarba** [comment]
@whedon assign @Fil as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Fil

**Comment by labarba** [comment]
Thanks, @Fil — I'm waiting for a reply from a possible second reviewer, then I'll start the review!

**Comment by labarba** [comment]
Hmm ... @arfon, our loyal bot `@whedon` is not obeying my command to start the review. What's going on?

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/904. Feel free to close this issue now!

**Comment by arfon** [comment]
> OK, I've started the review over in #904. Feel free to close this issue now!

@labarba - I found a weird bug with this paper. I've fixed it now.
