### ISSUE TITLE
[PRE REVIEW]: ShinySSD: Species Sensitivity Distributions for Ecotoxicological Risk Assessment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#762]
**Submitting author:** @flor14 (<a href="http://orcid.org/0000-0002-0041-097X">María Florencia D&#39;Andrea</a>)
**Repository:** <a href="https://github.com/flor14/paper" target ="_blank">https://github.com/flor14/paper</a>
**Version:** v1.0.0
**Editor:** @karthik
**Reviewers:** @kylehamilton

**Author instructions**

Thanks for submitting your paper to JOSS @flor14. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@flor14 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by flor14** [comment]
Hello.
About the reviewers:
aj2duncan could be a possible reviewer as he mentions experience with rmarkdown and shiny.
Also jhollist interests are related to my field of work.

**Comment by flor14** [comment]
adamhsparks, pboesu, maelle could be another options

**Comment by flor14** [comment]
I had select different names for the files, I have corrected them now. There is a paper.bib and a paper.md

**Comment by karthik** [comment]
Thanks @flor14 I appreciate your patience and please expect a reviewer shortly.

**Comment by karthik** [comment]
@kylehamilton Tagging you here following my email request. Would you be able to review this Shiny app?

**Comment by kylehamilton** [comment]
@karthik Yes, I am available and can review this Shiny app.

**Comment by karthik** [comment]
@whedon assign @kylehamilton as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kylehamilton

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/785. Feel free to close this issue now!
