### ISSUE TITLE
[PRE REVIEW]: General binary file parser.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#763]
**Submitting author:** @jfjlaros (<a href="http://orcid.org/0000-0002-8715-7371">J.F.J. Laros</a>)
**Repository:** <a href="https://github.com/jfjlaros/bin-parser" target ="_blank">https://github.com/jfjlaros/bin-parser</a>
**Version:** 0.0.20
**Editor:** @danielskatz
**Reviewers:** @hainesr, @Smattr

**Author instructions**

Thanks for submitting your paper to JOSS @jfjlaros. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jfjlaros if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
Hi @jfjlaros

1 - There's an error compiling your paper.md file which seems to be that there is no bibliography file included.  You need to add a bibliography to the directory that contains paper.md (docs in this case.)

2 - Can you suggest some potential reviewers, perhaps from [this list of people](https://bit.ly/joss-reviewers) who have already agreed to review for JOSS and may be suitable for this submission?

**Comment by jfjlaros** [comment]
Dear @danielskatz

Thank you for pointing this out. I have added a bibliography for the essential dependencies.

As for reviewers, I think hainesr (standards / protocols), smattr (compilers) and Funnelfiasco (CLI tools) may be interested.

**Comment by danielskatz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00763/joss.00763/10.21105.joss.00763.pdf)

**Comment by danielskatz** [comment]
@jfjlaros - Please merge https://github.com/jfjlaros/bin-parser/pull/7 to fix the remaining bib issues

**Comment by danielskatz** [comment]
@hainesr , @smattr, @Funnelfiasco - would one of you be willing to review this JOSS submission?

**Comment by jfjlaros** [comment]
@danielskatz - Your fixes were merged and I fixed one additional capitalisation issue. Thank you.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00763/joss.00763/10.21105.joss.00763.pdf)

**Comment by danielskatz** [comment]
ok, looks good - now we just need to find a reviewer...

**Comment by hainesr** [comment]
Hi @danielskatz, I'm happy to have a look at this.

**Comment by Smattr** [comment]
I'm OK to review as well. I don't have a strong JS background, but I'm solid on Python and reverse engineering. Were you planning to pick just one or did you want multiple reviewers?

**Comment by danielskatz** [comment]
I would be pleased if we could have two reviews - I'm generally trying to do this for JOSS papers, unless I'm really an expert in the software myself, which is not the case here.

**Comment by danielskatz** [comment]
@whedon assign @hainesr as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hainesr

**Comment by danielskatz** [comment]
@whedon add @Smattr as reviewer

**Comment by whedon** [comment]
OK, @Smattr is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/766. Feel free to close this issue now!
