### ISSUE TITLE
[REVIEW]: Salabim: discrete event simulation and animation in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#767]
**Submitting author:** @salabim (<a href="http://orcid.org/0000-0001-7696-8059">Ruud van der Ham</a>)
**Repository:** <a href="https://github.com/salabim/salabim" target ="_blank">https://github.com/salabim/salabim</a>
**Version:** 2.2.23
**Editor:** @danielskatz
**Reviewer:** @gonsie, @pspringer
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.6791129" target="_blank">10.6084/m9.figshare.6791129</a>

## Status

[![status](http://joss.theoj.org/papers/225837fff5f6f153660cd05044cd4267/status.svg)](http://joss.theoj.org/papers/225837fff5f6f153660cd05044cd4267)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/225837fff5f6f153660cd05044cd4267"><img src="http://joss.theoj.org/papers/225837fff5f6f153660cd05044cd4267/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/225837fff5f6f153660cd05044cd4267/status.svg)](http://joss.theoj.org/papers/225837fff5f6f153660cd05044cd4267)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/salabim/salabim" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gonsie & @pspringer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/salabim/salabim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.2.23)?
- [x] **Authorship:** Has the submitting author (@salabim) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/salabim/salabim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.2.23)?
- [x] **Authorship:** Has the submitting author (@salabim) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @gonsie, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by danielskatz** [comment]
👋  @arfon - I screwed up and added @pspringer twice as a reviewer.  I'm going to manually edit the first comment in the issue to fix this, but if there's something in the @whedon database that also needs to be fixed, please do so.

**Comment by danielskatz** [comment]
👋 @gonsie, @pspringer - thanks for volunteering to review.  Instructions and the review checklists are in the first comment in this issue.  Please go ahead and start your reviews when you are ready.

If you have any questions, please feel free to ask me.

**Comment by pspringer** [comment]
Hi Dan, this is Paul.  I've not done this sort of collaboration before, so I am completely lost.  I don't even know if you will get this if I don't put that @ sign in front of your name.  I'm not even sure what button to click at the bottom to send this.  At any rate, if you could point me to a guide for how to do this, it would help.  Thanks

**Comment by danielskatz** [comment]
@pspringer - We're using GitHub's notification feature within issues, so if you put @danielskatz, I will be notified.

And these are typical GitHub issues - fully public for anyone who cares to look, and continually added to as more comments are added (by the green comment button under the empty box at the end of a current list of comments on an issue)

It might be useful for us to talk offline on some of the details of how this reviewing process works within GitHub, and not bother others who may be following this issue.  I'll followup by email.

**Comment by pspringer** [comment]
@salabim, the documentation section on **Reading items from a file** is pretty slim.  I would recommend either adding some detail to it, or inserting a note that the Reference section has more detail.

**Comment by salabim** [comment]
@pspringer I have updated the section on reading files and the requirement section (re Pillow).

@pspringer I would like to say something about the unique features of salabim, but where?

**Comment by pspringer** [comment]
@salabim I would recommend mentioning the unique features in the README file, but let's see if @danielskatz concurs.

**Comment by danielskatz** [comment]
one or both of the following would be appropriate:
the readme, the documentation
in addition to in the paper.

**Comment by salabim** [comment]
I have added the requested information to paper.md and READ.me.


Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by danielskatz** [comment]
@salabim - Just looking at the paper, I think it's still too short, and also it doesn't have any references.  See http://joss.theoj.org/about#author_guidelines, and perhaps take a look at some of the accepted submissions in http://joss.theoj.org

For example, I'm not sure the paper clearly state what problems the software is designed to solve and who the target audience is?  Also, the paper could briefly explain what DES is.

**Comment by salabim** [comment]
Updated.


Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by danielskatz** [comment]
@salabim - References should be specific articles or web sites.
Otherwise, I will leave it to @pspringer and @gonsie to provide more feedback on the content.

**Comment by gonsie** [comment]
@salabim - Please respond to the issues in the salabim/salabim repo ([here](https://github.com/salabim/salabim/issues))

**Comment by danielskatz** [comment]
@pspringer and @gonsie - I don't see any open issues in the salabim repo currently, so I think this review is back to you both.  Can you please update us on anything you are waiting for, or how this stands to you otherwise?

**Comment by danielskatz** [comment]
Also @salabim - the paper still needs to have specific references added, and cited in the body of the paper.

**Comment by salabim** [comment]
What kind of references are we talking about. I know that there some users
who are going to publish an article, but nothing concrete yet.
Is that a problem?
Otherwise, can I just cite some sample projects?



Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by danielskatz** [comment]
RIght now, the references says "Several wikipedia articles on DES and simulation languages."

What are these articles?  You need to list them.
Are there academic papers about DES and the simulations languages?  If so, you should list them as well.

To pick a recent example, see https://github.com/openjournals/joss-papers/blob/joss.00773/joss.00773/10.21105.joss.00773.pdf  which has a lot of reference (likely more than you need).  The [paper](https://github.com/SMTG-UCL/galore/blob/master/paper.md) includes citations to the references, which are listed in the [bibliography file](https://github.com/SMTG-UCL/galore/blob/master/paper.bib)

This is what I'm looking for

**Comment by pspringer** [comment]
@danielskatz and @salabim I'm going through the six functional blocks I've identified to make sure all are as documented.  I should be able to finish that this week.

**Comment by salabim** [comment]
I have updated the paper.bib file to contain a couple of relevant references. Does this meets the requirements. now?


On Thu, Jun 21, 2018 at 6:34pm, Daniel S. Katz < notifications@github.com [notifications@github.com] > wrote:RIght now, the references says "Several wikipedia articles on DES and simulation languages."

What are these articles? You need to list them.
Are there academic papers about DES and the simulations languages? If so, you should list them as well.

To pick a recent example, see https://github.com/openjournals/joss-papers/blob/joss.00773/joss.00773/10.21105.joss.00773.pdf [https://github.com/openjournals/joss-papers/blob/joss.00773/joss.00773/10.21105.joss.00773.pdf] which has a lot of reference (likely more than you need). The paper [https://github.com/SMTG-UCL/galore/blob/master/paper.md] includes citations to the references, which are listed in the bibliography file [https://github.com/SMTG-UCL/galore/blob/master/paper.bib]

This is what I'm looking for

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by danielskatz** [comment]
Add the papers to .bib file is good, but now you have to update the .md file to cite them.  Only references that are cited are built into the pdf.

**Comment by salabim** [comment]
I have updated the paper.md and paper.bib files.
Sorry for my stupid questions ...

On Tue, Jun 26, 2018 at 20:35, Daniel S. Katz <notifications@github.com> wrote:
Add the papers to .bib file is good, but now you have to update the .md file to cite them. Only references that are cited are built into the pdf.

**Comment by danielskatz** [comment]
Thanks - you can also regenerate the PDF to check it (this is not just something I can do).

Though I will do it again this time.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by danielskatz** [comment]
Those bibtex entries didn't quite work right...

**Comment by danielskatz** [comment]
I've created 2 pull requests for the bib and the md of the paper - let's see if these fix the problems

**Comment by salabim** [comment]
Daniel,

I have updated the paper.bib document and double checked it manually.
I still don't know how to check or generate the pdf myself. Could you be so
kind as to do that for me?

Ruud van der Ham

*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by danielskatz** [comment]
@whedon generate pdf

@salabim - I think you should also be able to give this command as a comment in this GitHub issue

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #767 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0    134      0 --:--:-- --:--:-- --:--:--   135
Error reading bibliography ./paper.bib (line 12, column 32):
unexpected "{"
expecting space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
I'm a little confused why you didn't merge my pull requests: https://github.com/salabim/salabim/pull/10 and https://github.com/salabim/salabim/pull/11

**Comment by danielskatz** [comment]
These pull requests should fix the problems.

**Comment by salabim** [comment]
Sorry, but I am very confused and far from an expert in GitHub.

I have now merged the pull requests (no idea what that means) and uploaded a corrected vetsion of paper.bib.

And now?


Ruud, just a simple open source software developer ...

________________________________

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by danielskatz** [comment]
@salabim - you might want to read through some of the [GitHub Guides](https://guides.github.com), in particular the [one on Git](https://guides.github.com/introduction/git-handbook/)

**Comment by danielskatz** [comment]
The merge of my pull request for the bib file did not work - I think you merged into the patch, rather than into the master.  Here's what I think the file should contain:

@book{Matloff:2013,
  	author = {Matloff, Norm},
  	title = {Introduction to Discrete-Event Simulation and the SimPy Language},
  	year = 2013,
  	note = {Available from \url{http://heather.cs.ucdavis.edu/~matloff/156/PLN/DESimIntro.pdf}, Accessed 2018-07-04}
  	}
@book{Robinson:2004,
  	author = {Robinson, Stewart},
  	title = {Simulation – The practice of model development and use},
 	publisher={Wiley},
  	year = 2013
  	}
@book{Page:2005,
  	author = {Bernd Page and Wolfgang Kreutzer},
  	title = {Simulating Discrete Event Systems},
 	publisher={Shaker Verlag},
  	year = 2005
  	}
@book{Lutz:2014,
  	author = {Mark Lutz},
  	title = {Python Pocket Reference}, 
 	publisher = {O'Reilly},
  	year = 2014
  	}

**Comment by salabim** [comment]
I have now put a new paper.bib, with your contents on the master branch.

Does it work now?


________________________________

**Comment by danielskatz** [comment]
close

let's try changing the first entry to

```
@book{Matloff:2013,
  	author = {Matloff, Norm},
  	title = {Introduction to Discrete-Event Simulation and the Sim{P}y Language},
  	year = 2013,
  	url = {http://heather.cs.ucdavis.edu/~matloff/156/PLN/DESimIntro.pdf}
  	}
```

Then you should be able to go to the GitHub Issue where the review is taking place (this one, https://github.com/openjournals/joss-reviews/issues/767), and type "@whedon generate pdf" a new comment to generate a new PDF.

**Comment by salabim** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by salabim** [comment]
Got it!


________________________________

**Comment by pspringer** [comment]
@salabim, @danielskatz, the References section in paper.md is blank.  Also, where is the link to the pdf version of the paper, other than whedon's "Check article proof"?

**Comment by danielskatz** [comment]
@pspringer - don't worry about the lack of references in the .md file, they are built automatically in the PDF from the .bib file.  And the latest "Check article proof" is the most recent version of the pdf version.

**Comment by pspringer** [comment]
@danielskatz, @salabim, I've checked everything off on the list, it looks good.

**Comment by gonsie** [comment]
@salabim do any of the paper references have DOIs?

**Comment by salabim** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by salabim** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #767 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0    259      0 --:--:-- --:--:-- --:--:--   261
Error reading bibliography ./paper.bib (line 18, column 1):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by salabim** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00767/joss.00767/10.21105.joss.00767.pdf)

**Comment by salabim** [comment]
@gonsie 
I have found one DOI and added it to the references (paper.bib).

**Comment by danielskatz** [comment]
@gonsie - Can you go ahead and check off the last box?  The references are books which generally don't have DOIs.

**Comment by gonsie** [comment]
@danielskatz done.

**Comment by danielskatz** [comment]
👋 @arfon - can you take over the last steps?

@pspringer and @gonsie - thanks for your work on your reviews!

**Comment by salabim** [comment]
@arfon 
The DOI of the figshare repository is
10.6084/m9.figshare.6791129

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.6791129 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.6791129" target="_blank">10.6084/m9.figshare.6791129</a> is the archive.

**Comment by arfon** [comment]
@gonsie, @pspringer - many thanks for your reviews and to @danielskatz for editing this submission ✨ 

@salabim - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00767 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00767/status.svg)](https://doi.org/10.21105/joss.00767)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00767">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00767/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00767/status.svg)](https://doi.org/10.21105/joss.00767)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
