### ISSUE TITLE
[PRE REVIEW]: unyt: Handle, manipulate, and convert data with units in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#770]
**Submitting author:** @ngoldbaum (<a href="http://orcid.org/0000-0001-5557-267X">Nathan Goldbaum</a>)
**Repository:** <a href="https://github.com/yt-project/unyt" target ="_blank">https://github.com/yt-project/unyt</a>
**Version:** v1.0.3
**Editor:** @kyleniemeyer
**Reviewers:** @Cadair, @tbekolay, @ygrange

**Author instructions**

Thanks for submitting your paper to JOSS @ngoldbaum. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ngoldbaum if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #770 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    462      0 --:--:-- --:--:-- --:--:--   480
[WARNING] Could not fetch resource 'apply.png': replacing image with description
[WARNING] Could not fetch resource 'unary.png': replacing image with description
[WARNING] Could not fetch resource 'binary_different_units.png': replacing image with description
[WARNING] Could not fetch resource 'binary_same_units.png': replacing image with description
[WARNING] Could not fetch resource 'ufunc.png': replacing image with description
[WARNING] Could not fetch resource 'ufuncout.png': replacing image with description
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00770.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @kyleniemeyer - the submitting author suggested you as the handling editor.

**Comment by ngoldbaum** [comment]
Not sure why it couldn’t find the images, they’re in the paper directory: https://github.com/yt-project/unyt/tree/master/paper

**Comment by kyleniemeyer** [comment]
@arfon ok, I'll take this

**Comment by ngoldbaum** [comment]
@kyleniemeyer ping? What are the next steps here?

**Comment by kyleniemeyer** [comment]
@ngoldbaum hey, sorry for the delay—just busy-ness on my end. Can you recommend one or two people to review, that would bring some domain expertise? I will also select one from a more broad background.

**Comment by ngoldbaum** [comment]
How about Stuart Mumford (has experience with yt.units and astropy.units, is on the reviewer list for JOSS), Marten van Kerkwijk (astropy and numpy developer, helps maintain astropy's Quantity class) or Trevor Bekolay (reviewed unit packages in Python at SciPy 2013).

**Comment by kyleniemeyer** [comment]
@whedon add @Cadair as reviewer

**Comment by whedon** [comment]
OK, @Cadair is now a reviewer

**Comment by mhvk** [comment]
@kyleniemeyer - with @Cadair already reviewing, I feel adding me would not add much and perhaps make the review too "astropy biased".

**Comment by kyleniemeyer** [comment]
@mhvk ok, fair enough—thanks for the input.

**Comment by kyleniemeyer** [comment]
Hi @kellieotto @ygrange @bocklund would any of you be willing to serve as a second reviewer for this submission? It would be great to have a second set of eyes, particularly from a slightly different field.

**Comment by tbekolay** [comment]
Apologies for the slow response; I'm happy to serve as second reviewer.

**Comment by ygrange** [comment]
Whoops. Same here (both the sorry and the happy to be parts).

**Comment by kyleniemeyer** [comment]
@tbekolay no worries, and thanks!

@ygrange thanks! I think we can handle three reviewers, so I'll add you both

**Comment by kyleniemeyer** [comment]
@whedon add @tbekolay as reviewer

**Comment by whedon** [comment]
OK, @tbekolay is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @ygrange as reviewer

**Comment by whedon** [comment]
OK, @ygrange is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/809. Feel free to close this issue now!
