### ISSUE TITLE
[REVIEW]: HelpMe Command Line Helper Utility

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#775]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/vsoch/helpme" target ="_blank">https://www.github.com/vsoch/helpme</a>
**Version:** 0.0.35
**Editor:** @arfon
**Reviewer:** @iljah, @rougier
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1293062" target="_blank">10.5281/zenodo.1293062</a>

## Status

[![status](http://joss.theoj.org/papers/18dcee0f359b9fbcc76bbdd8ac88fda4/status.svg)](http://joss.theoj.org/papers/18dcee0f359b9fbcc76bbdd8ac88fda4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/18dcee0f359b9fbcc76bbdd8ac88fda4"><img src="http://joss.theoj.org/papers/18dcee0f359b9fbcc76bbdd8ac88fda4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/18dcee0f359b9fbcc76bbdd8ac88fda4/status.svg)](http://joss.theoj.org/papers/18dcee0f359b9fbcc76bbdd8ac88fda4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://www.github.com/vsoch/helpme" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@iljah & @rougier, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://www.github.com/vsoch/helpme">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0.2)?
- [x] **Authorship:** Has the submitting author (@vsoch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://www.github.com/vsoch/helpme">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0.2)?
- [x] **Authorship:** Has the submitting author (@vsoch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @iljah, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00775/joss.00775/10.21105.joss.00775.pdf)

**Comment by vsoch** [comment]
Thank you @whedon robot friend! Fantastic to get this underway!

**Comment by iljah** [comment]
Paper.md has statement of need but it's missing from readme.md (Do the authors clearly state what problems the software is designed to solve and who the target audience is?).

**Comment by iljah** [comment]
Readme.md is missing community guidelines (Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support)

**Comment by vsoch** [comment]
hey @iljah ! I just merged some changes to address your points above:
 - I added a "year" field to references, where appropriate
 - The version of the software coincides with the pypi release. I can definitely create a tag/official release if you think this is necessary, but generally I rely on pypi to provide these files (so there isn't confusion/ doubling of it)
 - I added the statement of need to the README.md.
 - I added community guidelines to the README.md

**Comment by rougier** [comment]
I think you need to work on the `paper.bib` since some references does not make much sense. For example, the github reference is not really a reference. It would be better to just add a link in the paper rather than having it as a reference.

Also, you can reformat some references, e.g.:

```
@MISC{helpme,
  title        = "{HelpMe}",
  booktitle    = "{HelpMe}",
  author       = "{vsoch}",
  abstract     = "HelpMe - a command line tool for helping you out.",
  publisher    = "vsoch",
  year        = {2018},
  howpublished = "\url{https://vsoch.github.io/helpme/helpme/}",
  note         = "Accessed: 2018-4-30"
}

could be rewritten as:

@MISC{helpme,
  title =  "{HelpMe}",
  author = "Sochat, Vanessa",
  year =  {2018},
  url = "https://vsoch.github.io/helpme/helpme/",
}
```

**Comment by rougier** [comment]
For the README, why don't you advertise the pip install method instead of the docker one ?

**Comment by vsoch** [comment]
Okay, I made some changes to the bib, please take a look!

I also added the install with pip to the readme. It wasn't there mostly because I want users to rely on the documentation base, but I agree that some won't want to go that many clicks (and the README is a good place to have it).

**Comment by iljah** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by iljah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #775 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    140      0 --:--:-- --:--:-- --:--:--   141
Error reading bibliography ./paper.bib (line 12, column 3):
unexpected "u"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by vsoch** [comment]
oups sorry @whedon , I'm a terrible robot owner! Let's try again...

@whedon generate pdf

**Comment by vsoch** [comment]
I don't think @whedon listens to me :scream:

**Comment by vsoch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00775/joss.00775/10.21105.joss.00775.pdf)

**Comment by iljah** [comment]
Pdf looks pretty good except github reference still has n.d., maybe adding a year would make that go away?

**Comment by vsoch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00775/joss.00775/10.21105.joss.00775.pdf)

**Comment by vsoch** [comment]
okay, added a date!

**Comment by vsoch** [comment]
How do I change the latter?

**Comment by iljah** [comment]
Hmm don't know, @arfon is it possible to change program version in this issue, or in final paper or something?..

**Comment by arfon** [comment]
@iljah - I can update the version here. What is the correct version @vsoch ?

**Comment by vsoch** [comment]
Hey @arfon ! Given no further changes, the version that is current is 0.0.35.

**Comment by rougier** [comment]
@vsoch Don't you need to make a GitHub release?

**Comment by rougier** [comment]
For the README, I think all the information is present but the structure is a bit weird. You have the overview and usage near the end, the contributing and license are at the subsection level (instead of section) and it is not clear that local and docker refers to the installation. I guess you can leave it as it is if your prefer but a restructuration might be an option worth to consider.

**Comment by vsoch** [comment]
Oh thanks @rougier I didn't remember that I needed to do this. I'll fix up the README, create a release, and post here when that is done.

**Comment by vsoch** [comment]
hey @whedon @arfon what are next steps? Please let me know what I can do to help.

**Comment by arfon** [comment]
@vsoch - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by vsoch** [comment]
All set! Here is the DOI: https://zenodo.org/account/settings/github/repository/vsoch/helpme#

I had created the tagged release 2 days ago, but in the wrong order so it didn't trigger anything on Zenodo (this I had completely forgotten about!) I re-created the release and now the two are synced up. Thanks for the heads up @arfon !

**Comment by arfon** [comment]
Hi @vsoch - this URL looks to link to your account page. Could you share the DOI?

**Comment by vsoch** [comment]
Third time is the charm! https://doi.org/10.5281/zenodo.1293062

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1293062 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1293062" target="_blank">10.5281/zenodo.1293062</a> is the archive.

**Comment by arfon** [comment]
@iljah, @rougier - many thanks for your reviews here ✨ 

@vsoch - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00775 ⚡️:rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00775/status.svg)](https://doi.org/10.21105/joss.00775)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00775/status.svg)](https://doi.org/10.21105/joss.00775)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by vsoch** [comment]
Woohoo, robot party! Thanks @whedon @arfon @iljah and @rougier !
