### ISSUE TITLE
[PRE REVIEW]: quimb: a python library for quantum information and many-body calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#777]
**Submitting author:** @jcmgray (<a href="http://orcid.org/0000-0001-9461-3024">Johnnie Gray</a>)
**Repository:** <a href="https://github.com/jcmgray/quimb" target ="_blank">https://github.com/jcmgray/quimb</a>
**Version:** 0.4.2
**Editor:** @jedbrown
**Reviewers:** @dalcinl, @sunqm

**Author instructions**

Thanks for submitting your paper to JOSS @jcmgray. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jcmgray if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jedbrown it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00777/joss.00777/10.21105.joss.00777.pdf)

**Comment by arfon** [comment]
👋@jedbrown - the submitting author suggested you as the handling editor.

**Comment by jedbrown** [comment]
@mlxd :wave: would you be available to review?

**Comment by mlxd** [comment]
@jedbrown I'd be happy to review, but will not be available to start until the end of July. If you require a more prompt review, feel free to choose somebody else.

**Comment by jcmgray** [comment]
:wave: hi all. From my perspective earlier than late July would of course be nice, however I'm also very grateful for any review so no problem if this isn't possible!

**Comment by jedbrown** [comment]
@whedon assign @dalcinl as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dalcinl

**Comment by jedbrown** [comment]
@whedon add @sunqm as reviewer

**Comment by whedon** [comment]
OK, @sunqm is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/819. Feel free to close this issue now!
