### ISSUE TITLE
[PRE REVIEW]: GMSimViz

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#778]
**Submitting author:** @viktor76525 (<a href="http://orcid.org/0000-0001-5442-2960">Viktor</a>)
**Repository:** <a href="https://github.com/ucgmsim/GMSimViz" target ="_blank">https://github.com/ucgmsim/GMSimViz</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewers:** @leouieda, @hugoledoux

**Author instructions**

Thanks for submitting your paper to JOSS @viktor76525. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@viktor76525 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #778 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/778/paper/paper.md): mapping values are not allowed in this context at line 9 column 9 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/lib/whedon.rb:67:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@viktor76525 - it looks like the whitespace isn't quite right in your `paper.md` - could you make sure all of the YAML keys are lined up correctly?

**Comment by viktor76525** [comment]
@arfon I'm not sure what you mean, I thought the format of `paper.md` was GitHub markdown. I think the issue may have been with the table of contents and I have removed it as it was unnecessary anyway. Please let me know if there are further changes required.

**Comment by arfon** [comment]
I've fixed this for you here. YAML is whitespace sensitive and your fields for authors and affiliations had inconsistent indentations: https://github.com/ucgmsim/GMSimViz/pull/1

**Comment by viktor76525** [comment]
Thank you. Sorry, I mixed up `paper.md` with `readme.md`.

**Comment by lheagy** [comment]
👋 Hi @arfon and @viktor76525: I would be happy to be the editor on this submission

**Comment by lheagy** [comment]
👋 Hi @viktor76525, do you have any suggestions for reviewers?

@leouieda: This might be of interest? I know you have done a number of reviews recently though, so no worries if your plate is full. If you have any suggestions of other GMT  / python users who might be intrigued by this submission - I would appreciate your input!

**Comment by leouieda** [comment]
@lheagy I was actually taking a look at this and would like to review it. I might take a while, though, with Scipy coming up next week. Would that be OK?

I think @seisman and @joa-quim might be interested in reviewing this as well.

**Comment by leouieda** [comment]
@viktor76525 the youtube movie looks amazing!

**Comment by viktor76525** [comment]
@lheagy looking at the list I can see @hugoledoux, @sgrieve might also be a good match. Not too worried about time here.

**Comment by lheagy** [comment]
Thanks @leouieda and @viktor76525! @leouieda, getting the review in after SciPy is fine - enjoy the conference

**Comment by lheagy** [comment]
@whedon assign @leouieda as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @leouieda

**Comment by lheagy** [comment]
👋 Hi @seisman, @joa-quim, @hugoledoux, and @sgrieve: would any of you be willing and interested to assist with this review?

**Comment by joa-quim** [comment]
Well, I wouldn't mind help the review but the condition of "Linux only" is not for me. I'm a Windows guy. And also, Python is not a language that I practice. So, I don't think I would be very helpful.

**Comment by hugoledoux** [comment]
Is it Linux only? I don't know all these packages but I see no reason why it wouldn't work on macOS (Windows too I guess).

I can review this, and see if that works on macOS

**Comment by lheagy** [comment]
Thanks @joa-quim for getting back to me, and @hugoledoux for being willing to review!

**Comment by lheagy** [comment]
@whedon add @hugoledoux as reviewer

**Comment by whedon** [comment]
OK, @hugoledoux is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/808. Feel free to close this issue now!
