### ISSUE TITLE
[PRE REVIEW]: GFF3toEMBL: Preparing annotated assemblies for submission to EMBL

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#78]
**Submitting author:** @andrewjpage (<a href="http://orcid.org/0000-0001-6919-6062">Andrew Page</a>)
**Repository:** <a href="https://github.com/sanger-pathogens/gff3toembl.git" target ="_blank">https://github.com/sanger-pathogens/gff3toembl.git</a>
**Version:** v1.1.0
**Editor:** @arfon
**Reviewer:** @andersgs

**What this issue is for**

Thanks for submitting your paper to JOSS @andrewjpage. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
Hey @mgymrek - would you be able to edit this paper for us?

**Comment by andrewjpage** [comment]
Hey I was wondering if I could suggest @peterjc as a reviewer?

**Comment by peterjc** [comment]
Potential conflict of interest: I have contributed to the tool with feedback and some small pull requests, https://github.com/sanger-pathogens/gff3toembl/issues?q=author%3Apeterjc https://github.com/sanger-pathogens/gff3toembl/graphs/contributors - does this exclude me as a potential reviewer?

**Comment by arfon** [comment]
> Hey I was wondering if I could suggest @peterjc as a reviewer?

Thanks @andrewjpage & @peterjc - I'd rather try and find an alternative reviewer for now given that Peter has contributed to this project (albeit small contributions). Do either of you have alternative reviewers in mind?

**Comment by peterjc** [comment]
Maybe @tseemann could review https://github.com/sanger-pathogens/gff3toembl for JOSS? He is very familiar with American sister sequence archive run by the NCBI though his work on Prokka https://github.com/tseemann/prokka - even if he does not submit to the European sequence archive himself?

**Comment by andrewjpage** [comment]
@andersgs has volunteered to review it if thats acceptable.

**Comment by arfon** [comment]
> @andersgs has volunteered to review it if thats acceptable.

That sounds good to me.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @andersgs as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andersgs

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
OK the review is open in https://github.com/openjournals/joss-reviews/issues/80 now. @andersgs @andrewjpage let's head over there.
