### ISSUE TITLE
[REVIEW]: Async Modules Supporting ES5 & ES6 with Control Flow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#780]
**Submitting author:** @IbrahimTanyalcin (<a href="http://orcid.org/0000-0003-0327-5096">Ibrahim  Tanyalcin</a>)
**Repository:** <a href="https://github.com/IbrahimTanyalcin/taskq" target ="_blank">https://github.com/IbrahimTanyalcin/taskq</a>
**Version:** v2.1.4
**Editor:** @arfon
**Reviewer:** @xirdneh
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/864b66eb13ca2c0dc83f22400ae7ce25/status.svg)](http://joss.theoj.org/papers/864b66eb13ca2c0dc83f22400ae7ce25)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/864b66eb13ca2c0dc83f22400ae7ce25"><img src="http://joss.theoj.org/papers/864b66eb13ca2c0dc83f22400ae7ce25/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/864b66eb13ca2c0dc83f22400ae7ce25/status.svg)](http://joss.theoj.org/papers/864b66eb13ca2c0dc83f22400ae7ce25)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/IbrahimTanyalcin/taskq" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@xirdneh, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/IbrahimTanyalcin/taskq">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v2.1.4)?
- [ ] **Authorship:** Has the submitting author (@IbrahimTanyalcin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @xirdneh it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #780 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    178      0 --:--:-- --:--:-- --:--:--   179
Error producing PDF.
! Misplaced alignment tab character &.
\f@nch@olf ...018). Async Modules Supporting ES5 &
                                                   ES6 with Control Flow. \t...
l.242 \end{document}

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
> Is it because of the white spaces/- in the paper.md ?

Looks like this is because of the `&` in the title. I can't seem to figure out how to get Pandoc to escape it properly. A quick fix would be to change `&` to `and`.

**Comment by IbrahimTanyalcin** [comment]
I guess &amp; would work. Let's give it a try, I'll push paper.md again

**Comment by IbrahimTanyalcin** [comment]
Updated.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #780 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    351      0 --:--:-- --:--:-- --:--:--   355
Error producing PDF.
! Misplaced alignment tab character &.
\f@nch@olf ...018). Async Modules Supporting ES5 &
                                                  amp; ES6 with Control Flow...
l.242 \end{document}

Looks like we failed to compile the PDF

**Comment by IbrahimTanyalcin** [comment]
Oww, I yield, :man_facepalming:  I will replace with  and.

**Comment by IbrahimTanyalcin** [comment]
Done!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00780/joss.00780/10.21105.joss.00780.pdf)

**Comment by IbrahimTanyalcin** [comment]
Is there anything I should do?

**Comment by arfon** [comment]
Hi @xirdneh - when do you think you might be able to complete your review by?

**Comment by arfon** [comment]
I just contacted @xirdneh by email.

**Comment by arfon** [comment]
Over the past 8 weeks I've contacted @IbrahimTanyalcin multiple times over email. Unfortunately both our reviewer and author are unreachable. 

Given the major challenges we had finding a reviewer for this submission, I'm going to withdraw this submission on behalf of the submitting author.
