### ISSUE TITLE
[PRE REVIEW]: ukpopulation: UK Demographic Projections

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#783]
**Submitting author:** @virgesmith (<a href="http://orcid.org/0000-0002-9951-6642">Andrew Smith</a>)
**Repository:** <a href="https://github.com/nismod/ukpopulation" target ="_blank">https://github.com/nismod/ukpopulation</a>
**Version:** 1.0.1
**Editor:** @leeper
**Reviewers:** @soodoku

**Author instructions**

Thanks for submitting your paper to JOSS @virgesmith. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@virgesmith if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #783 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    208      0 --:--:-- --:--:-- --:--:--   210
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00783.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by virgesmith** [comment]
Proof looks fine to me thanks

**Comment by leeper** [comment]
@soodoku Would you be interested in reviewing this for JOSS?

**Comment by soodoku** [comment]
sure.

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon assign @soodoku as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @soodoku

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/803. Feel free to close this issue now!
