### ISSUE TITLE
[PRE REVIEW]: iml: An R package for Interpretable Machine Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#784]
**Submitting author:** @christophM (<a href="http://orcid.org/0000-0003-2331-868X">Christoph Molnar</a>)
**Repository:** <a href="https://github.com/christophM/iml" target ="_blank">https://github.com/christophM/iml</a>
**Version:** v0.5.2
**Editor:** @leeper
**Reviewers:** @nhejazi

**Author instructions**

Thanks for submitting your paper to JOSS @christophM. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@christophM if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @leeper, the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00784/joss.00784/10.21105.joss.00784.pdf)

**Comment by leeper** [comment]
@thomasp85 would you be willing to review this for JOSS?

**Comment by thomasp85** [comment]
Yes - but I have to be honest about my calendar and say that it will happen earliest in august... If that doesn't work then you'll have to ping someone else 🙂

**Comment by leeper** [comment]
@thomasp85 Okay, I'll see if I can find someone before then. If not, I may come back to you. Thanks!

**Comment by leeper** [comment]
@nhejazi Are you willing to review this for JOSS?

**Comment by nhejazi** [comment]
@leeper --- sure thing; I would be happy to review this submission for JOSS.

**Comment by leeper** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/786. Feel free to close this issue now!

**Comment by leeper** [comment]
@nhejazi Thanks! That's great. The review issue is open for you here: https://github.com/openjournals/joss-reviews/issues/786

Please let me know (over there) if you have any questions.
