### ISSUE TITLE
[REVIEW]: iml: An R package for Interpretable Machine Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#786]
**Submitting author:** @christophM (<a href="http://orcid.org/0000-0003-2331-868X">Christoph Molnar</a>)
**Repository:** <a href="https://github.com/christophM/iml" target ="_blank">https://github.com/christophM/iml</a>
**Version:** v0.5.2
**Editor:** @leeper
**Reviewer:** @nhejazi
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1299059" target="_blank">10.5281/zenodo.1299059</a>

## Status

[![status](http://joss.theoj.org/papers/9e8466400de93f5aabfb999f23db5072/status.svg)](http://joss.theoj.org/papers/9e8466400de93f5aabfb999f23db5072)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9e8466400de93f5aabfb999f23db5072"><img src="http://joss.theoj.org/papers/9e8466400de93f5aabfb999f23db5072/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9e8466400de93f5aabfb999f23db5072/status.svg)](http://joss.theoj.org/papers/9e8466400de93f5aabfb999f23db5072)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/christophM/iml" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nhejazi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/christophM/iml">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.2)?
- [x] **Authorship:** Has the submitting author (@christophM) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @nhejazi it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00786/joss.00786/10.21105.joss.00786.pdf)

**Comment by nhejazi** [comment]
I've now completed a preliminary review of the `iml` R package --- @christophM, this looks really great! There are just a few outstanding items that require your attention before I can check off the remaining items required for the JOSS review. Please take a look at the two issues ([on examples](https://github.com/christophM/iml/issues/23) and [on licensing/contributions](https://github.com/christophM/iml/issues/24)) that provide specific details on what needs to be addressed. Feel free to let me know if I can provide any further information that might be helpful in completing this review.

**Comment by leeper** [comment]
@nhejazi Thank you for the very fast review!

@christophM Please address these issues when you get a chance and let me know when they're complete.

**Comment by christophM** [comment]
@nhejazi  thank you for the review! 

@leeper, @nhejazi I adressed and closed the issues (was not sure if to leave them open or close them. feel free to re-open if something is missing).

**Comment by leeper** [comment]
Great. @nhejazi Can you take another look and let me know about any new or continuing concerns?

**Comment by nhejazi** [comment]
Everything looks good to me! I've checked off the remaining review items.

**Comment by leeper** [comment]
Thanks, @nhejazi!

**Comment by leeper** [comment]
@christophM The review process is now complete. To finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI (if one exists). It looks like a few of those papers should have DOIs.

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here with the DOI for the release.

**Comment by christophM** [comment]
I went through the references and updated the DOIs, wherever I found one.

**Comment by christophM** [comment]
@whedon help

**Comment by christophM** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by christophM** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00786/joss.00786/10.21105.joss.00786.pdf)

**Comment by christophM** [comment]
Here is the DOI: 

https://doi.org/10.5281/zenodo.1299059

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1299059 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1299059" target="_blank">10.5281/zenodo.1299059</a> is the archive.

**Comment by leeper** [comment]
@arfon over to you

**Comment by arfon** [comment]
@nhejazi - many thanks for your review here and to @leeper for editing this submission ✨ 

@christophM - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00786 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00786/status.svg)](https://doi.org/10.21105/joss.00786)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00786/status.svg)](https://doi.org/10.21105/joss.00786)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by christophM** [comment]
@arfon @nhejazi @leeper 
Thanks for the smooth and pleasant process!

**Comment by christophM** [comment]
Hi @arfon, I just talked to @leeper about the possibilty to add an author to the paper after publishing. 
When I wrote the paper, I (falsely) assumed that only code contributors can be authors. 

It would be really great if I could update the paper with authors that also contributed conceptually. 

@leeper mentioned that it might be possible. 
@arfon is it possible to update the list of authors?

Thanks for your efforts!

**Comment by arfon** [comment]
> @arfon is it possible to update the list of authors?

Yes, please update the `paper.md` in your `master` branch of the repository and give me a shout when you've done so.

**Comment by christophM** [comment]
Thanks @arfon. 
I updated the `paper.md` in the `master`. Let me know if there are any more actions I have to take.

**Comment by arfon** [comment]
> I updated the paper.md in the master. Let me know if there are any more actions I have to take.

👍 this should be updated on the JOSS site now. It can take a few hours to update due to caching.

**Comment by christophM** [comment]
Great, thanks a lot!
