### ISSUE TITLE
[REVIEW]: rowan: A Python package for working with quaternions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#787]
**Submitting author:** @vyasr (<a href="http://orcid.org/0000-0001-5181-9532">Vyas Ramasubramani</a>)
**Repository:** <a href="https://bitbucket.org/glotzer/rowan" target ="_blank">https://bitbucket.org/glotzer/rowan</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @pdebuyl, @CorySimon
**Archive:** <a href="https://doi.org/10.5281/zenodo.1323676" target="_blank">10.5281/zenodo.1323676</a>

## Status

[![status](http://joss.theoj.org/papers/9c781f6fd89b36396abbabd26d6d9ef6/status.svg)](http://joss.theoj.org/papers/9c781f6fd89b36396abbabd26d6d9ef6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9c781f6fd89b36396abbabd26d6d9ef6"><img src="http://joss.theoj.org/papers/9c781f6fd89b36396abbabd26d6d9ef6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9c781f6fd89b36396abbabd26d6d9ef6/status.svg)](http://joss.theoj.org/papers/9c781f6fd89b36396abbabd26d6d9ef6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/glotzer/rowan" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pdebuyl & @CorySimon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/glotzer/rowan">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@vyasr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/glotzer/rowan">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@vyasr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @pdebuyl, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by labarba** [comment]
@pdebuyl, @CorySimon -- here is where the magic happens. Let me know if you have any questions.

**Comment by pdebuyl** [comment]
Hi,

The rowan project gives a very good impression! The source code is well structured, the
design of the API is direct to understand and fully documented.

I did tick most of the checklist already. I have a few improvements to request:

- In the documentation file `doc/index.rst`, there should be a blank line below the
  `code-block` directives else sphinx complains (ref:
  http://www.sphinx-doc.org/en/stable/rest.html#directives)

- The "issues" page on Bitbucket is not accessible. It is however recommended to use it in the
  documentation.

- The license has Python highligthing. Add ` :language: none` as a directive option to
  literalinclude.

- The definitions of the derivative and integral in rowan.calculus are not given. Please
  mention the definitions in the docstrings.

- In comparison to the README, the sphinx documentation misses the installation and
  quickstart instructions. If you add them, the sphinx documentation will be complete.

- The installation instruction for the documentation should also install
  'sphinx_rtd_theme'. This theme is no longer installed by default.

- The package claims to be efficient. The design makes it very probable but you should
  quantify this and mention whether all the algorithms operate at the broadcasting level or
  if some are left aside.

- As per the JOSS reviewer guidelines, it is important to cite prior
  software. http://matthew-brett.github.io/transforms3d/ should also be cited then.

**Comment by vyasr** [comment]
Thanks for the comments. I'll keep a running checklist here as I address them.

Regarding the efficiency, how would you recommend I do this? For example, are you interested in O(N) scaling? I can also include explicit benchmarks against the other code bases, I've done something like this before so I could formalize that script and include it in the repository as well, or just discuss it in the paper.

- [ ] Fix spacing for code-blocks
- [ ] Make issues page publicly accessible
- [ ] Add language directive to License
- [ ] Add definitions of derivative and integral to `rowan.calculus`
- [ ] Add installation and quickstart instructions to the sphinx documentation `doc/index.rst`
- [ ] Add sphinx_rtd_theme to installation instructions in docs and README
- [ ] Provide some form of benchmarks
- [ ] Cite transforms3d as well

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by labarba** [comment]
Regarding performance claims, or comparison with other software, you can include this in the documentation, with a brief summary of results on the paper.

**Comment by pdebuyl** [comment]
Hi @vyasr thank you for the update. The solution you propose to time the other packages is fine. You can keep the mention in the paper brief of course.

All that will be missing then is the archived version of the software, for which you will probably wait for the other review. If you need assistance for archiving software on Zenodo, you can request it in this review page.

**Comment by vyasr** [comment]
I've updated the paper with a couple of sentences about performance, and I've added a benchmarks folder with a Jupyter notebook that compares to a pair of alternative solutions. I've noted the existence of these benchmarks in the documentation as well.

Regarding the archived version, I was under the impression that the Zenodo archiving happened once the paper was published. Correct me if I'm wrong though.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by pdebuyl** [comment]
@vyasr Yes, archiving on completion of the review is fine. Thank you for all the updates in response to the review :-)

@labarba The submission is 100% ok for me.

**Comment by vyasr** [comment]
Great thanks for the review @pdebuyl !

**Comment by vyasr** [comment]
@labarba at this point I don't need to do anything else until the other reviewer begins his review, correct? Just want to make sure I'm not holding up the process.

**Comment by labarba** [comment]
Yes, @vyasr, hang tight. The second reviewer will start soon: I know he had commitments running up to this weekend.

**Comment by vyasr** [comment]
No problem, as long as I'm not expected to do anything to alert him that it's ready. Whenever the review commences is fine with me.

**Comment by CorySimon** [comment]
hi @vyasr,

Very nice, professional, and well-documented Python package!

Coincidentally, I recently implemented a rotation Monte Carlo move for molecules in my code and was looking into quaternions, but went with the method in "Fast Random Rotation Matrices" [here](https://pdfs.semanticscholar.org/04f3/beeee1ce89b9adf17a6fabde1221a328dbad.pdf). I'm curious about the ad-/dis-advantages of using quaternions over this.

My suggestions/comments, some more trivial than others, are listed below.

1. Upon `python -m unittest discover tests`, I get the following warning; is it significant?
```
............................./usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
..................................
----------------------------------------------------------------------
Ran 63 tests in 0.630s

OK
```

2. Mention in the docs where to run the tests, i.e. "`cd` into the test directory of the repository"

3. "Quaternions form a number system with various interesting properties, and they have a number of uses." seems a bit vacuous, maybe be more concrete and mention in the documentation the areas where quaternions are most widely used.

4. In the "random" section of the docs, instead of "Generate random rotations uniformly", I would spell out "uniformly distributed random rotations on a unit sphere" to be more precise.

5. When I run this example from the docs,
```
import rowan
import numpy as np

rands = np.random.rand(100, 3)
alpha, beta, gamma = rands.T
ql = rowan.from_euler(alpha, beta, gamma)
alpha_return, beta_return, gamma_return = rowan.to_euler(ql)
assert(np.all(alpha_return == alpha))
assert(np.all(beta_return == beta))
assert(np.all(gamma_return == gamma))
```
I get an error `ValueError: too many values to unpack (expected 3)`

6. Some of the examples in the documentation are intended to be self-contained, in that I can open up Python for the first time and copy-and-paste the examples in to run them because they contain the necessary `import`'s (e.g. `rotate` and `reflect`, except you still need to `from rowan import reflect`). Some are not, e.g. by not including `import rowan` or `from rowan import *` or `from rowan.calculus import integrate`. Would that be better to put the necessary imports in the example so they are self-contained, or no? At least, I would be consistent.

7. Could you provide examples for the functions in `rowan.random` in the docs?

8. Arguably, the most complicated functions are under `mapping`. Copying the scikit-learn model, I think it would be helpful if you could provide a toy example of their use: two sets of points in 2D that need aligned, for example. You can generate the toy data set with a known shift and transformation matrix, then show that your functions recover the result and show the plots before and after alignment. It would be powerful and also serve as a nice displayed test that the more complicated functions are working. I do see you have something like this in `rowan/tests/test_mapping.py`, I'm suggesting you use the example to document the `mapping` module.

9. I suggest putting the performance bar plot (you can condense it by putting three bars next to each other per algorithm) in the documentation. This will show users in what cases they should choose your package over others, and also let other contributors know where to focus their efforts. Please put an xlabel on the performance plot as well.

**Comment by vyasr** [comment]
Thanks for the comments! I'm currently at SciPy, so I don't have too much bandwidth this week, but I will respond as soon as possible.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by labarba** [comment]
@CorySimon --- Do let me know if you are satisfied with the author's mods, and if you are ready to recommend acceptance of this submission. Thanks for  your contribution to JOSS!

**Comment by CorySimon** [comment]
Yes, thank you @vyasr for taking my suggestions into account. Rowan is a nice piece of software, and I'm sure many will find it useful!

I apologize for taking 13 days to see this; I don't recall seeing an email notification from the above post, and this Github account is linked to my personal email.

As an intriguing side note, I also like [the story of how quaternions were discovered/invented](https://en.wikipedia.org/wiki/History_of_quaternions). Perhaps a visit to the Brougham Bridge is in order for celebration of v1.0 of rowan!

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by labarba** [comment]
Good effort! Were you able at any point to get the figures of a smaller size, so a short text snippet would fit under them in page 2?

**Comment by vyasr** [comment]
That's what I'd like to do! I'm having a bit of trouble with it though (sorry for the deluge of recompilations). Can I control the figure size directly in any way? It's currently a bit larger than I'd like, so not only does no text fit under it, but also the labels on the left are getting cut off a little.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by labarba** [comment]
I agree that they are a bit large. I'm not sure if we can have embedded HTML, in which case you could use the `width` property:

`img src="dir/file.png" width="200">`

**Comment by labarba** [comment]
How about just moving the figures to the end? Not ideal, but might work better in this case.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
I gave the HTML solution a shot, let's see how it looks. If it doesn't work, then I'll do as you suggest and move the figure to the end.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
If I split the paragraph up I can get some of the text onto the first page, but the figure insists on taking up the full page and being a bit too wide to properly fit the existing margins.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by labarba** [comment]
Yikes. They don't appear if you place them in the end???

(I always tell my students: prepare your figures and output the image in the size you will use in the document :-)

@arfon Help! We're having problem with float placement!

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
Ooops no that was a different problem, a different way I tried to fix the size. Clearly did not work too well!

Yes, perhaps it will work better if I take the programatically generated png, import it into a properly sized Illustrator artboard, and then export that as PDF. Currently no matter what size I output the png as, it's getting resized to the full width of the page.

**Comment by labarba** [comment]
Then you could add white side margins _to the figure_, leaving the vertical image size the same.

**Comment by labarba** [comment]
It's currently not so bad (and fits in 3 pages), but the figure caption clashes with the footer rule.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
OK the width issue appears to be fixed now. The primary outstanding problem is the figure height. Additional padding to the figure just leaves additional white space between the figure content and the caption, but the caption position still overlaps the footer rule.

**Comment by arfon** [comment]
@vyasr - you can limit the figure height like this:

```
![Performance Comparison](Performance.pdf){ height=750px }
```

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00787/joss.00787/10.21105.joss.00787.pdf)

**Comment by vyasr** [comment]
Thanks @arfon, that worked!

@labarba I think it's fine now. I tried playing with it a bit to see if I could get some text onto the same page as the figure, but the figure needs to be quite small before that happens so I did just enough to fix the issues with the footer. Let me know if you would like me to try reflowing text around the figure somehow though.

**Comment by labarba** [comment]
Looks good now, phew!

@arfon — this submission is ready to process for publication.

@pdebuyl, @CorySimon — Thank you for your contribution to this adventure in new scholarly publishing!

**Comment by pdebuyl** [comment]
@labarba and all, my pleasure :-)

BTW, if you wish to fix the author naming issue in the reference (that was mentioned in the pre-review), you will need to wait for https://github.com/openjournals/joss/issues/400 to be fixed.

**Comment by arfon** [comment]
@vyasr - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by vyasr** [comment]
@arfon Here's the doi: 10.5281/zenodo.1323676.

[Zenodo link](https://zenodo.org/record/1323676)

**Comment by labarba** [comment]
@pdebuyl You didn't tick the version item on the checklist ... I assume this is fine?

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1323676 as archive

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1323676" target="_blank">10.5281/zenodo.1323676</a> is the archive.

**Comment by arfon** [comment]
@pdebuyl, @CorySimon - many thanks for your reviews here and to @labarba for editing this submission ✨ 

@vyasr - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00787 :zap: :rocket: :boom:

**Comment by vyasr** [comment]
Thanks @pdebuyl @CorySimon for your reviews!

And thank you @labarba @arfon for managing the process.

@CorySimon unrelated, I just realized that in your original review you asked a question about quaternions vs. rotation matrices. In general, the main advantage of quaternions is that the actual rotation operation is much faster (quaternion multiplication requires fewer operations than matrix multiplication). There are good algorithms for both for generating random rotations, but it's the actual rotation operations that are costly. Also, for certain applications (such as on-board computers) where memory is a factor, quaternions use substantially less memory (4 numbers instead of 9). This is also why Euler angles still get used despite their flaws (only 3 numbers).

**Comment by labarba** [comment]
All share!
https://twitter.com/JOSS_TheOJ/status/1024063365482725376
