### ISSUE TITLE
[PRE REVIEW]: phylogram: an R package for phylogenetic analysis with nested lists

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#789]
**Submitting author:** @shaunpwilkinson (<a href="http://orcid.org/0000-0002-7332-7931">Shaun Wilkinson</a>)
**Repository:** <a href="https://github.com/ropensci/phylogram" target ="_blank">https://github.com/ropensci/phylogram</a>
**Version:** v2.1.0
**Editor:** @karthik
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @shaunpwilkinson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@shaunpwilkinson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00789/joss.00789/10.21105.joss.00789.pdf)

**Comment by shaunpwilkinson** [comment]
Hi @karthik and others, thanks for considering this paper for JOSS. As for suggested reviewers, @wcornwell and @BenJWard have already reviewed the source code for ropensci and are familiar with the workings of the package, so may be a good place to start. Otherwise on the list of JOSS reviewers @juanvillada and @giraola have interests in phylogenetic analysis with R.

**Comment by arfon** [comment]
@karthik - it looks like this package has been through the rOpenSci on-boarding in https://github.com/ropensci/onboarding/issues/212 so I think we're good to fast-tracking this?

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/790. Feel free to close this issue now!
