### ISSUE TITLE
[PRE REVIEW]: effmass: An effective mass package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#793]
**Submitting author:** @lucydot (<a href="http://orcid.org/0000-0002-2992-9871">Lucy Whalley</a>)
**Repository:** <a href="https://github.com/lucydot/effmass" target ="_blank">https://github.com/lucydot/effmass</a>
**Version:** v1.0.b1
**Editor:** @katyhuff
**Reviewers:** @ajjackson, @mkhorton, @bocklund

**Author instructions**

Thanks for submitting your paper to JOSS @lucydot. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lucydot if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #793 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @katyhuff - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #793 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    145      0 --:--:-- --:--:-- --:--:--   146
Error producing PDF.
! Package xcolor Error: Undefined color `TealBlue'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.218 }

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@lucydot - it looks like @whedon can't handle your colour selections 😸. Could you please remove this line from your `paper.md`?

```
 urlcolor: "TealBlue"
```

**Comment by lucydot** [comment]
Hello @arfon and @katyhuff - 

I have removed the offending line - 

Perhaps @ajjackson might like to review the code. We worked in the same research group 2 years ago, but he has had no input on this project.

Looking at the reviewer database, the following people may also like to review:
@mdoucet
@bocklund
@mkhorton
@yxqd

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #793 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    368      0 --:--:-- --:--:-- --:--:--   375
Error producing PDF.
! Package xcolor Error: Undefined color `Blue'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.218 }

Looks like we failed to compile the PDF

**Comment by katyhuff** [comment]
@lucydot can you look through to deal with all colors that cause these errors? You can debug until it works with `@whedon generate pdf` here in the comments. Thanks!

**Comment by katyhuff** [comment]
Hi @ajjackson, @mdoucet, @bocklund, and @mkhorton - It seems to me you would be an excellent reviewer for this submission. As soon as it builds, are you willing to be assigned to review this software paper submission? We'll need at least two volunteers, but the more the merrier. Information about being a reviewer can be found here : http://joss.theoj.org/about#reviewer_guidelines .

**Comment by bocklund** [comment]
@katyhuff @lucydot I would be happy to review this.

**Comment by mkhorton** [comment]
@katyhuff @lucydot  I'd be happy to review too

**Comment by ajjackson** [comment]
I'm happy to review this

**Comment by lucydot** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00793/joss.00793/10.21105.joss.00793.pdf)

**Comment by katyhuff** [comment]
@whedon set @bocklund as reviewer

**Comment by katyhuff** [comment]
@whedon assign @bocklund as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bocklund

**Comment by katyhuff** [comment]
@whedon assign @mkhorton as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mkhorton

**Comment by katyhuff** [comment]
@whedon assign @ajjackson as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ajjackson

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
@katyhuff - if you want to add a second reviewer you need to do:

```
@whedon add @reviewername as reviewer
```

`assign` clobbers the existing assignments.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/797. Feel free to close this issue now!

**Comment by katyhuff** [comment]
@arfon Thanks -- ok. I'll delete #797 and fix this.

**Comment by katyhuff** [comment]
@whedon add @mkhorton as reviewer

**Comment by whedon** [comment]
OK, @mkhorton is now a reviewer

**Comment by katyhuff** [comment]
@whedon add @bocklund as reviewer

**Comment by whedon** [comment]
OK, @bocklund is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by katyhuff** [comment]
@arfon ... do you think I broke it?

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by katyhuff** [comment]
Ok team, I messed up the command for adding reviewers and may need to do a little fixing. Thanks for your patience.

**Comment by katyhuff** [comment]
Hi @bocklund @mkhorton @ajjackson @lucydot , we'll be conducting the review over in  #797 . Let's move over there. I've now fixed it manually so it should have one review checklist for each reviewer. Thanks!

**Comment by arfon** [comment]
Looks like you've fixed it up @katyhuff 🤘

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/e9a40b87-8129-485c-a15d-60146ac75920-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
