### ISSUE TITLE
[PRE REVIEW]: WEdiff: A Python and C++ package for automatic differentiation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#794]
**Submitting author:** @ctdegroot (<a href="http://orcid.org/0000-0002-2069-8253">Christopher DeGroot</a>)
**Repository:** <a href="https://bitbucket.org/cdegroot/wediff" target ="_blank">https://bitbucket.org/cdegroot/wediff</a>
**Version:** N/A
**Editor:** @arfon
**Reviewers:** @highlando, @kyleniemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @ctdegroot. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ctdegroot if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @labarba - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00794/joss.00794/10.21105.joss.00794.pdf)

**Comment by ctdegroot** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by ctdegroot** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00794/joss.00794/10.21105.joss.00794.pdf)

**Comment by ctdegroot** [comment]
Some suggested reviewers are @clemaitre5 @highlando @kyleniemeyer @dlagrava

**Comment by highlando** [comment]
Looks interesting and in my field of expertise. What do I have to do?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
> Looks interesting and in my field of expertise. What do I have to do?

@highlando - thanks! You can get an idea of the review process here:

- https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Basically the review happens in a GitHub issue and has a bunch of checkboxes for you to work through. If you're able to help us that would be great!

**Comment by labarba** [comment]
@arfon --- thanks for taking over; I've been overloaded, and off to SciPy tomorrow, so unable to attend to new things short-fuse.

**Comment by kyleniemeyer** [comment]
I would also look at this but can't really for two weeks... @arghdos might be interested though.

**Comment by arfon** [comment]
@kyleniemeyer - would you be willing to be a second reviewer.

**Comment by arfon** [comment]
@whedon assign @highlando as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @highlando

**Comment by kyleniemeyer** [comment]
@arfon I can't really for at least another week (CAREER proposal due...)

**Comment by arfon** [comment]
> @arfon I can't really for at least another week (CAREER proposal due...)

NP. I'm happy to wait for a couple of weeks :-)

**Comment by arfon** [comment]
Yep, was hoping to hear back from Kyle that he was OK with this but let's assume he is and I'm sure he'll let us know if not 😬

**Comment by arfon** [comment]
@whedon add @kyleniemeyer as reviewer

**Comment by whedon** [comment]
OK, @kyleniemeyer is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/820. Feel free to close this issue now!

**Comment by arfon** [comment]
@ctdegroot @highlando @kyleniemeyer - see you all over in #820 for the actual review.
