### ISSUE TITLE
[PRE REVIEW]: sigmajs: An R htmlwidget interface to the sigma.js visualization library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#795]
**Submitting author:** @JohnCoene (<a href="http://orcid.org/0000-0002-6637-4107">Jean-Philippe Coene</a>)
**Repository:** <a href="https://github.com/JohnCoene/sigmajs" target ="_blank">https://github.com/JohnCoene/sigmajs</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewers:** @strengejacke, @jankatins

**Author instructions**

Thanks for submitting your paper to JOSS @JohnCoene. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@JohnCoene if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00795/joss.00795/10.21105.joss.00795.pdf)

**Comment by JohnCoene** [comment]
Below are 5 reviewers I would suggest, based on "Preferred Programming Language" (`r`) and "Domains/topic areas you are comfortable reviewing" (`visualisation` or `networks`):

* @cdcrabtree 
* @aj2duncan
* @jakobbossek
* @strengejacke
* @aj2duncan

*List from from [joss reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822)*

**Comment by strengejacke** [comment]
I had a quick look at the paper, I think the topic might be suitable for me, so I'd be happy to review the submission.

**Comment by JohnCoene** [comment]
Thank you @strengejacke !

**Comment by arfon** [comment]
> I had a quick look at the paper, I think the topic might be suitable for me, so I'd be happy to review the submission.

Thanks @strengejacke. I'd like to find a second reviewer for this submission if possible so if you're happy to wait for a while before we get started I'd be much obliged :-)

@janschulz - would you be willing to review this submission for JOSS?

**Comment by jankatins** [comment]
I can do it but I'm not familiar what the role of a second reviewer is.

**Comment by arfon** [comment]
> I can do it but I'm not familiar what the role of a second reviewer is.

Fantastic - thanks! The second reviewer basically just does the same review.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @strengejacke as reviewer

**Comment by whedon** [comment]
OK, @strengejacke is now a reviewer

**Comment by arfon** [comment]
@whedon add @jankatins as reviewer

**Comment by whedon** [comment]
OK, @jankatins is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/814. Feel free to close this issue now!

**Comment by arfon** [comment]
@strengejacke, @jankatins - please head over to #814 where we will carry out the actual review of this submission.
