### ISSUE TITLE
[PRE REVIEW]: The hhi Package: Streamlined Calculation and Visualization of Herfindahl-Hirschman Index Scores

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#796]
**Submitting author:** @pdwaggoner (<a href="http://orcid.org/0000-0002-7825-7573">Philip D. Waggoner</a>)
**Repository:** <a href="https://github.com/pdwaggoner/hhi" target ="_blank">https://github.com/pdwaggoner/hhi</a>
**Version:** v1.1.0
**Editor:** @leeper
**Reviewers:** @cskovron

**Author instructions**

Thanks for submitting your paper to JOSS @pdwaggoner. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pdwaggoner if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #796 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/lib/whedon.rb:80:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-195e6d124d0f/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by pdwaggoner** [comment]
Thanks for getting this going!  Are you waiting for something from me?

**Comment by arfon** [comment]
👋 @pdwaggoner. We'll need an editor to volunteer to handle this submission before we can get going. In the meantime could you take a look at addressing the compilation error? It looks like the YAML header for your paper is malformed.

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@pdwaggoner Thanks for your submission. In order to review it, we'll need the repository to be in standard R package form (as in the form you build using `R CMD build` containing `/R`, `/man`, `/tests` directories) not isolated R code files.

**Comment by pdwaggoner** [comment]
@arfon Thanks for this. I have updated the YAML header. Should be good to go now. Thanks for catching this. Also, @leeper thanks so much for serving as editor and for the guidance. I have included the standard R package form in my hhi repository. I think everything should be in there and good to go. Let me know if you need anything or else, or if you find another oversight. Many thanks.

**Comment by leeper** [comment]
@pdwaggoner To clarify, the repo should contain all the code such that it is visible and navigable in the GitHub interface and can be installed and built by the reviewer, in standard package format. We don't need the .tar.gz file.

As an example, see the structure of the repository for this recent JOSS publication: https://github.com/strengejacke/ggeffects

**Comment by pdwaggoner** [comment]
@leeper Apologies for the delay; we are in the process of moving. Also, apologies for the incorrect format. The example you sent was helpful. I think it should be in proper format now. I may have missed something. Hope this works, but if not, let me know. I will make corrections as needed. Thanks again!

**Comment by leeper** [comment]
@strengejacke Would you be willing to review this for JOSS?

**Comment by strengejacke** [comment]
I'm on holiday until July 29th, if it's ok when I start the review after my return I'd be willing to review the submission.

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #796 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    225      0 --:--:-- --:--:-- --:--:--   230
Error reading bibliography ./paper.bib (line 37, column 1):
unexpected end of input
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by pdwaggoner** [comment]
@leeper I merged pull request. All should be good. Please excuse the .bib oversight

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #796 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    157      0 --:--:-- --:--:-- --:--:--   157
Error producing PDF.
! Undefined control sequence.
l.362 Herfindahl-Hirschman Index Over Time\nUnited

Looks like we failed to compile the PDF

**Comment by pdwaggoner** [comment]
@leeper fixed title

**Comment by pdwaggoner** [comment]
@leeper Not sure if you are looking for a response from me re: this proof, but this looks good to me. Let me know whatever else you need, if anything. Thanks!

**Comment by leeper** [comment]
@pdwaggoner Nope, no need to do anything. Thanks!

**Comment by leeper** [comment]
@whedon assign @cskovron as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cskovron

**Comment by leeper** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/828. Feel free to close this issue now!
