### ISSUE TITLE
[PRE REVIEW]: proEQUIB - IDL Library for Plasma Diagnostics and Abundance Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#798]
**Submitting author:** @danehkar (<a href="http://orcid.org/0000-0003-4552-5997">Ashkbiz Danehkar</a>)
**Repository:** <a href="https://github.com/equib/proEQUIB" target ="_blank">https://github.com/equib/proEQUIB</a>
**Version:** v0.0.6
**Editor:** @arfon
**Reviewers:** @mdpiper, @mgalloy

**Author instructions**

Thanks for submitting your paper to JOSS @danehkar. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@danehkar if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00798/joss.00798/10.21105.joss.00798.pdf)

**Comment by danehkar** [comment]
Based on your list of joss reviewers, I think that @mgalloy @Scivision @Mankoff would be great reviewers for IDL programs.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@mgalloy @scivision @mankoff - would one or more of you be willing to review this submission for JOSS?

**Comment by mgalloy** [comment]
I can review this.

**Comment by danehkar** [comment]
Your list of joss reviewers also shows that @manodeep @mattpitkin @zingale @ziotom78 @benjaminrose @Cadair @nespinoza are comfortable with reviewing topic areas of astronomy and astrophysics.

**Comment by danehkar** [comment]
@arfon I corrected minor typo mistakes. Please regenerate the article PDF after assigning 2 reviewers.

**Comment by danehkar** [comment]
For this IDL library, @wlandsman if you are able to review and test this IDL library, please let @arfon know as soon as possible since he is looking for 2 reviewers this submission for JOSS. Currently, he found one reviewer.

**Comment by mgalloy** [comment]
@mdpiper would be a good IDL reviewer. I believe he has started the process to be a reviewer.

**Comment by arfon** [comment]
@whedon add @mdpiper as reviewer

**Comment by whedon** [comment]
OK, @mdpiper is now a reviewer

**Comment by arfon** [comment]
@whedon add @mgalloy as reviewer

**Comment by whedon** [comment]
OK, @mgalloy is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/899. Feel free to close this issue now!

**Comment by arfon** [comment]
@mdpiper, @mgalloy - see you over in #899 for the actual review. Thanks again!

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00798/joss.00798/10.21105.joss.00798.pdf)
