### ISSUE TITLE
[PRE REVIEW]: AtomNeb: Atomic Data for Ionized Nebulae

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#799]
**Submitting author:** @danehkar (<a href="http://orcid.org/0000-0003-4552-5997">Ashkbiz Danehkar</a>)
**Repository:** <a href="https://github.com/atomneb/AtomNeb-idl" target ="_blank">https://github.com/atomneb/AtomNeb-idl</a>
**Version:** v0.0.1
**Editor:** @arfon
**Reviewers:** @mgalloy, @mdpiper

**Author instructions**

Thanks for submitting your paper to JOSS @danehkar. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@danehkar if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00799/joss.00799/10.21105.joss.00799.pdf)

**Comment by danehkar** [comment]
Based on your list of joss reviewers, I think that @mgalloy @Scivision @Mankoff would be great reviewers for IDL programs.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@mgalloy @scivision @mankoff - would one or more of you be willing to review this submission for JOSS?

**Comment by mgalloy** [comment]
I can review this.

**Comment by arfon** [comment]
> I can review this.

Great, thanks @mgalloy! I'd like to find two reviewers for this submission if possible so if you could just sit tight for another few days that would be great. Once we have a second reviewer, I'll open up the main review issue.

**Comment by danehkar** [comment]
Your list of joss reviewers also shows that @manodeep @mattpitkin @zingale @ziotom78 @benjaminrose @Cadair @nespinoza are comfortable with reviewing topic areas of astronomy and astrophysics.

**Comment by danehkar** [comment]
@arfon I corrected minor typo mistakes. Please regenerate the article PDF after assigning 2 reviewers.

**Comment by zingale** [comment]
I'm not really an IDL person anymore, and don't have IDL to test it, so I don't think I can review

**Comment by ziotom78** [comment]
Same for me, it has been years since I used IDL and no longer have a license.

In data 9 agosto 2018 9:57:12 PM Michael Zingale <notifications@github.com> 
ha scritto:

**Comment by manodeep** [comment]
Same situation for me - have not written/used IDL in 3+ years

**Comment by nespinoza** [comment]
Same here! Dropped IDL at least 7+ years ago. Sorry!

**Comment by arfon** [comment]
@danehkar as with your other submission, I think it might be tough to find IDL reviewers these days. Please feel free to suggest potential reviewers from places _other_ than the list I shared earlier.

**Comment by danehkar** [comment]
It might work on [GNU Data Language (GDL)](https://github.com/gnudatalanguage/gdl). As my library depends on [IDL Astronomy User's library](https://idlastro.gsfc.nasa.gov/homepage.html), I cannot fix any GDL-incompatibility bugs related to IDL Astronomy User's library. I am also preparing a Python version of these package (AtomNeb + proEQUIB). However, I will release them next year. Most people who work at US research institutes have IDL license on their computers. For example, @wlandsman who works on IDL Astronomy User's library,  [IDLAstro](https://github.com/wlandsman/IDLAstro), might be able to test my IDL libraries (AtomNeb and proEQUIB), or @flamingbear who works on [Coyote IDL Library](https://github.com/idl-coyote/coyote).

**Comment by wlandsman** [comment]
FYI, the team leading the development of GDL (the free IDL clone) have
worked to make it compatible with IDL Astronomy User's library, and have
verified this for the case of the FITS I/O routines.   I took a  quick look
at  AtomNeb and it seems very likely to work under GDL since it does not
use widget or very recent IDL additions.

**Comment by danehkar** [comment]
@wlandsman if you are able to review and test this IDL library, please let @arfon know as soon as possible since he is looking for 2 reviewers this submission for JOSS. Currently, he found one reviewer.

**Comment by mgalloy** [comment]
@mdpiper would be a good IDL reviewer. I believe he has started the process to be a reviewer.

**Comment by arfon** [comment]
Hi @mgalloy & @wlandsman, firstly, many thanks for your help/interest in these packages thus far.

We've recently had two submissions from @danehkar: this one, and the [proEQUIB](https://github.com/openjournals/joss-reviews/issues/798) IDL library.

I'm wondering if you'd be both willing to review _both_ of these packages? I ask as we're really struggling to find suitable reviewers for these packages.

If this is something that you'd be open to then I would go ahead and start the reviews for both but there would be no expectation on our part that you complete these both simultaneously! 

What do you both think?

**Comment by mgalloy** [comment]
I can review both of the packages.

**Comment by mdpiper** [comment]
Hi Arfon,

I’m happy to help; just let me know!

mp

On Aug 16, 2018, at 4:13 AM, Arfon Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @mgalloy<https://github.com/mgalloy> & @wlandsman<https://github.com/wlandsman>, firstly, many thanks for your help/interest in these packages thus far.

We've recently had two submissions from @danehkar<https://github.com/danehkar>: this one, and the proEQUIB<https://github.com/openjournals/joss-reviews/issues/798> IDL library.

I'm wondering if you'd be both willing to review both of these packages? I ask as we're really struggling to find suitable reviewers for these packages.

If this is something that you'd be open to then I would go ahead and start the reviews for both but there would be no expectation on our part that you complete these both simultaneously!

What do you both think?

**Comment by arfon** [comment]
@whedon add @mgalloy as reviewer

**Comment by whedon** [comment]
OK, @mgalloy is now a reviewer

**Comment by arfon** [comment]
@whedon add @mdpiper as reviewer

**Comment by whedon** [comment]
OK, @mdpiper is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/898. Feel free to close this issue now!

**Comment by arfon** [comment]
@mgalloy, @mdpiper - thanks so much for agreeing to review these packages! I've gone ahead and started the review for this submission and will do the same for #798.

@danehkar - given you have the same reviewers for both of these packages - do you have a preference for which package @mgalloy & @mdpiper review first?

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00799/joss.00799/10.21105.joss.00799.pdf)

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00799/joss.00799/10.21105.joss.00799.pdf)

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00799/joss.00799/10.21105.joss.00799.pdf)
