### ISSUE TITLE
[REVIEW]: GFF3toEMBL: Preparing annotated assemblies for submission to EMBL

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#80]
**Submitting author:** @andrewjpage (<a href="http://orcid.org/0000-0001-6919-6062">Andrew Page</a>)
**Repository:** <a href="https://github.com/sanger-pathogens/gff3toembl.git" target ="_blank">https://github.com/sanger-pathogens/gff3toembl.git</a>
**Version:** v1.1.0
**Editor:** @arfon
**Reviewer:** @andersgs
**Archive:** <a href="https://dx.doi.org/10.6084/m9.figshare.3988815.v1" target ="_blank">https://dx.doi.org/10.6084/m9.figshare.3988815.v1</a>

## Status

[![status](http://joss.theoj.org/papers/9253390f38f4ce6b71674f433fa72afe/status.svg)](http://joss.theoj.org/papers/9253390f38f4ce6b71674f433fa72afe)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9253390f38f4ce6b71674f433fa72afe"><img src="http://joss.theoj.org/papers/9253390f38f4ce6b71674f433fa72afe/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9253390f38f4ce6b71674f433fa72afe/status.svg)](http://joss.theoj.org/papers/9253390f38f4ce6b71674f433fa72afe)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sanger-pathogens/gff3toembl.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sanger-pathogens/gff3toembl.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.0)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00080.pdf](https://github.com/openjournals/joss-reviews/files/487654/10.21105.joss.00080.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by andersgs** [comment]
Terrific work. Nice that you provide a `Docker`. It would be nicer if it were smaller, but I understand the reasons for using the base image. I just had difficulty with the brew install on the mac (sanger-pathogens/gff3toembl#63), and noticed that the brew recipe is one version behind (sanger-pathogens/gff3toembl#62).

Anders.

**Comment by andersgs** [comment]
I am satisfied everything works as described in the `README`.

**Comment by arfon** [comment]
Thanks for the review @andersgs! @andrewjpage at this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by andrewjpage** [comment]
Thanks for all the work on this.  I've deposited the code in Figshare https://dx.doi.org/10.6084/m9.figshare.3988815.v1

**Comment by arfon** [comment]
Thanks for the review @andersgs.

@andrewjpage your paper is now accepted into JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00080 🎉 🚀 💥
