### ISSUE TITLE
[PRE REVIEW]: DeGAUSS: Decentralized Geomarker Assessment for Multi-Site Studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#800]
**Submitting author:** @cole-brokamp (<a href="http://orcid.org/0000-0002-0289-3151">Cole Brokamp</a>)
**Repository:** <a href="https://github.com/cole-brokamp/DeGAUSS" target ="_blank">https://github.com/cole-brokamp/DeGAUSS</a>
**Version:** v0.2
**Editor:** @pjotrp
**Reviewers:** @vsoch, @george-githinji

**Author instructions**

Thanks for submitting your paper to JOSS @cole-brokamp. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cole-brokamp if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @pjotrp - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00800/joss.00800/10.21105.joss.00800.pdf)

**Comment by cole-brokamp** [comment]
Hi @whedon , I've updated the paper in the DeGAUSS repository based on the article proof above.  Please recompile.

**Comment by cole-brokamp** [comment]
Based on the list of existing JOSS reviewers, I feel that @nuest @jhollist @vsoch @sgrieve would all make great reviewers.

**Comment by sgrieve** [comment]
This looks like really interesting work! Unfortunately I'm not familiar enough with R to review this adequately.

**Comment by vsoch** [comment]
I am doing a trip followed by a cross country move starting next week, so I can't review imminently, but I'd be available at the end of July or early August!  

I don't think R as a predominant language is totally necessary because the actual executable to review would be a container. For everyone in this thread, here is a direct link to the repo to help decide if you would be a suitable reviewer --> https://github.com/cole-brokamp/DeGAUSS. If you look at the README, interaction with the application is via docker commands. 

@arfon is there a tag for container / Docker? I think many more that are familiar with containers (and perhaps not having the primary language as the executables inside) would still be able to provide some level of review. As long as one of the reviewers has more familiarity, I think it might be ok :L)

**Comment by cole-brokamp** [comment]
@vsoch makes a good point. In fact, this software is designed for users that don’t use R at all. Most of the end users hardly have any experience with command line programming at all.

**Comment by arfon** [comment]
> @arfon is there a tag for container / Docker? I think many more that are familiar with containers (and perhaps not having the primary language as the executables inside) would still be able to provide some level of review. As long as one of the reviewers has more familiarity, I think it might be ok :L)

We don't label submissions as such yet but I can definitely see the argument for doing so...

**Comment by cole-brokamp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00800/joss.00800/10.21105.joss.00800.pdf)

**Comment by pjotrp** [comment]
This is an interesting method for sure. I can be an editor if @vsoch is happy to review. There is no hurry.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@george-githinji are you Ok to review?

**Comment by george-githinji** [comment]
I have some immediate deadlines and I will only have a proper look from mid next week. If you get a second reviewer that will be great. Thanks.

**Comment by pjotrp** [comment]
@whedon assign @george-githinji as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @george-githinji

**Comment by pjotrp** [comment]
@whedon assign @vsoch as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vsoch

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by pjotrp** [comment]
@whedon add @george-githinji as reviewer

**Comment by whedon** [comment]
OK, @george-githinji is now a reviewer

**Comment by pjotrp** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by pjotrp** [comment]
@whedon add @pjotrp as editor

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@arfon hmm. So I would like @vsoch and @george-githinji as reviewers. Is that the case now?

**Comment by arfon** [comment]
> @arfon hmm. So I would like @vsoch and @george-githinji as reviewers. Is that the case now?

Yep, looks to be. You can always refresh the page and look at the top of the issue thread:

<img width="717" alt="screen shot 2018-07-06 at 8 18 16 am" src="https://user-images.githubusercontent.com/4483/42378395-2c1c5fb6-80f5-11e8-8887-bf6de31fe065.png">

**Comment by pjotrp** [comment]
@arfon  Got it. I was looking at the github assignees...

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/812. Feel free to close this issue now!
