### ISSUE TITLE
[PRE REVIEW]: DynaML: Scala Library/REPL for Machine Learning Research 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#802]
**Submitting author:** @mandar2812 (<a href="http://orcid.org/0000-0001-6025-7113">Mandar Chandorkar</a>)
**Repository:** <a href="https://github.com/transcendent-ai-labs/DynaML" target ="_blank">https://github.com/transcendent-ai-labs/DynaML</a>
**Version:** v1.5.3-beta.2
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @tovbinm

**Author instructions**

Thanks for submitting your paper to JOSS @mandar2812. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mandar2812 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #802 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00802/joss.00802/10.21105.joss.00802.pdf)

**Comment by mandar2812** [comment]
@arfon Thanks for helping with the pdf compilation! cc @whedon 

From the list of joss reviewers I see that 

@rougier @nilesh-patil @xirdneh and @abuccts are interested in reviewing machine learning related submissions, although this is not an exhaustive list, I guess its a start.

**Comment by mandar2812** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by mandar2812** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@acabunoc
@arfon
@arokem
@brainstorm
@cMadan
@danielskatz
@george-githinji
@jakevdp
@jasonclark
@jedbrown
@karthik
@katyhuff
@kyleniemeyer
@labarba
@leeper
@lheagy
@mgymrek
@pjotrp
@tracykteal
```

**Comment by mandar2812** [comment]
@acabunoc: It would be super awesome if you want to be the editor for my manuscript on DynaML. I'm new to the JOSS process so don't really know how things work. But if you are interested, I can ask @whedon to assign you as the editor.

**Comment by arfon** [comment]
:wave: @acabunoc - would you be able to edit this?

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@mlgill @MikeInnes @rcurtin @rasbt @ysimillides @thomasabeel @tovbinm would you be able to review this submission for the [ _Journal of Open Source Software_ (JOSS)](http://joss.theoj.org/). 
Review is focused on the [software :floppy_disk:](http://joss.theoj.org/) on a [short paper :page_facing_up: ](https://github.com/openjournals/joss-papers/blob/joss.00802/joss.00802/10.21105.joss.00802.pdf). 

For more information see our [review criteria :information_source: ](https://joss.readthedocs.io/en/latest/review_criteria.html#review-criteria). Let me know if you have questions.

**Comment by rcurtin** [comment]
@Kevin-Mattheus-Moerman I'd be happy to help JOSS but I don't speak Scala (and don't have the time right now to bring myself up to speed enough in it).  Perhaps I can be more helpful for a C++ submission in the future?

**Comment by rasbt** [comment]
@Kevin-Mattheus-Moerman Unfortunately, I have to pass, too. My Scala skills are practically non-existent.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mandar2812 if you have any suggestions for reviewers please let me know.

**Comment by mandar2812** [comment]
@Kevin-Mattheus-Moerman : Amongst the reviewers you proposed @tovbinm works with Scala (from his GitHub profile). 

As a start, I propose @eaplatanios @sbrunk @lucataglia @aishfenton @maxpumperla @mbhushan 
I can look for more members in the Scala ML community, if needed.

**Comment by tovbinm** [comment]
I would be glad to help, not sure how though ;) Which aspect of the project should be reviewed? What are the criteria?

**Comment by thomasabeel** [comment]
I can review. This is my first experience with a review process through git, so some instructions would be welcome.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @thomasabeel as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @thomasabeel

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your reply @tovbinm @thomasabeel. This is a pre-review issue. Once I gather enough reviewers I will initiate a review issue where the actual review will take place. At the top of a review issue each reviewer will have a simple list of checkboxes which will guide you through the review process. 

* Here is an example of a completed review process: https://github.com/openjournals/joss-reviews/issues/670

* You can also check out our review guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#the-joss-review-process

Let me know if you have any other questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tovbinm the review focuses on these items: https://joss.readthedocs.io/en/latest/review_criteria.html#review-items which form the basis of the checkboxes as well. Let me know if you can help. Thanks.

**Comment by hclent** [comment]
@Kevin-Mattheus-Moerman I am happy to help review! I do have a background with Scala as well as machine learning, so its a good fit :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @hclent as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hclent

**Comment by Kevin-Mattheus-Moerman** [comment]
@tovbinm did you see my comments? Let me know if you can help. Thanks.

**Comment by tovbinm** [comment]
I can help. NP. (Actually I will consider submitting my own freshly open sourced project https://transmogrif.ai/)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @tovbinm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tovbinm

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @tovbinm. Looking forward to it.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/922. Feel free to close this issue now!
