### ISSUE TITLE
[REVIEW]: ukpopulation: UK Demographic Projections

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#803]
**Submitting author:** @virgesmith (<a href="http://orcid.org/0000-0002-9951-6642">Andrew Smith</a>)
**Repository:** <a href="https://github.com/nismod/ukpopulation" target ="_blank">https://github.com/nismod/ukpopulation</a>
**Version:** 1.0.1
**Editor:** @leeper
**Reviewer:** @soodoku
**Archive:** <a href="https://doi.org/10.5281/zenodo.1328267" target="_blank">10.5281/zenodo.1328267</a>

## Status

[![status](http://joss.theoj.org/papers/269be2c1044e902e2cf7716bc9f0f7c0/status.svg)](http://joss.theoj.org/papers/269be2c1044e902e2cf7716bc9f0f7c0)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/269be2c1044e902e2cf7716bc9f0f7c0"><img src="http://joss.theoj.org/papers/269be2c1044e902e2cf7716bc9f0f7c0/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/269be2c1044e902e2cf7716bc9f0f7c0/status.svg)](http://joss.theoj.org/papers/269be2c1044e902e2cf7716bc9f0f7c0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nismod/ukpopulation" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@soodoku, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nismod/ukpopulation">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.1)?
- [x] **Authorship:** Has the submitting author (@virgesmith) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00803/joss.00803/10.21105.joss.00803.pdf)

**Comment by leeper** [comment]
@soodoku Review checklist is here. Please open an issue on the source repo for anything that is missing, or any other changes you would like to see in the software. Let me know if you have questions. And thanks for volunteering to review!

**Comment by leeper** [comment]
@soodoku Just a nudge on this review.

**Comment by soodoku** [comment]
@leeper: i opened a few issues around JOSS at the repo. a few weeks ago. All of them have been addressed. There are still some things I need to investigate.

For now, one q.: the version number is bumped up to 1.03 as a consequence of some of the changes i proposed. I am assuming it is ok if i check 1.01 on the checklist.

**Comment by leeper** [comment]
Yep, that's fine. Just let me know if anything else needs to be addressed. Thanks!

**Comment by soodoku** [comment]
Except for the pending 'community guidelines', everything else is all set. I offered another round of copy-edits but they are optional.

**Comment by leeper** [comment]
Excellent. Thanks!

**Comment by soodoku** [comment]
dear @leeper: this is good to go.

**Comment by leeper** [comment]
@soodoku Great! Thank you!

**Comment by leeper** [comment]
@virgesmith Looks like the package version is now 1.0.3. Can you create a new release for the current version and update your Zenodo archive? Once that's done, please let me know the updated DOI.

**Comment by virgesmith** [comment]
Updated as requested: https://zenodo.org/badge/latestdoi/131988266

DOi: 10.5281/zenodo.1328267

Thanks @soodoku @leeper!

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1328267 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1328267" target="_blank">10.5281/zenodo.1328267</a> is the archive.

**Comment by leeper** [comment]
@arfon Over to you

**Comment by arfon** [comment]
@virgesmith @leeper - the compiled paper doesn't appear to have any references - is that correct? The bibtex file appears to have an entry.

You can read how to cite records in markdown [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by virgesmith** [comment]
@arfon Thanks for spotting the oversight, now fixed

**Comment by leeper** [comment]
Oops, sorry about that. <jetlagged brain>

**Comment by arfon** [comment]
@soodoku - many thanks for your review here and to @leeper for editing this submission ✨ 

@virgesmith - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00803 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00803/status.svg)](https://doi.org/10.21105/joss.00803)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00803">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00803/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00803/status.svg)](https://doi.org/10.21105/joss.00803)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
