### ISSUE TITLE
[PRE REVIEW]: mzEasy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#804]
**Submitting author:** @chasemc (<a href="http://orcid.org/0000-0001-6439-9397">Chase M Clark</a>)
**Repository:** <a href="https://github.com/chasemc/mzEasy" target ="_blank">https://github.com/chasemc/mzEasy</a>
**Version:** 0.1.0
**Editor:** @arfon
**Reviewers:** @biswapriyamisra, @mwang87

**Author instructions**

Thanks for submitting your paper to JOSS @chasemc. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@chasemc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by chasemc** [comment]
I did some searching but am currently unsure the reason the PDF isn't compiling. 

@biswapriyamisra may be suited for this review

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00804/joss.00804/10.21105.joss.00804.pdf)

**Comment by biswapriyamisra** [comment]
I am willing to do a peer-review as an invited reviewer.

Thanks,
Biswa

**Comment by biswapriyamisra** [comment]
1. Fairly quick and easy installation when MSConvert and R 3.5 or so are in place!
2. Useful too for the conversions. 
3. More comments and suggestions in the annotated PDF. 
4. Useful tutorial and walk through images. 

[mzEasy_JOSS_Reviewer_Comments.pdf](https://github.com/openjournals/joss-reviews/files/2172385/mzEasy_JOSS_Reviewer_Comments.pdf)

Thanks for the opportunity to review and all the best. Shall keep adding requests to more functionalities or issues when faced.

Thanks,
Biswa

**Comment by bovee** [comment]
Sorry, I'm currently on vacation without a computer (it'd be at least a
week before I'm able to) and I don't have access to a Windows box (skimming
over, it looks like installation requires Windows). If it can be used on
Mac/Linux and the delay's not a problem, I'd be happy to review though.

On Jul 7, 2018 1:24 PM, "Arfon Smith" <notifications@github.com> wrote:

@bovee <https://github.com/bovee> - would you be willing to review this
submission for JOSS?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/804#issuecomment-403234463>,
or mute the thread

**Comment by arfon** [comment]
OK thanks @bovee.

> If it can be used on Mac/Linux and the delay's not a problem, I'd be happy to review though.

@chasemc - can this software be used on Mac/Linux?

**Comment by chasemc** [comment]
Unfortunately not, I was waiting to address this as it was also a comment here (https://github.com/openjournals/joss-reviews/issues/804#issuecomment-403182850). 

The reliance on MSConvert to convert spectra is necessary, and MSConvert itself relies on vendor dll files that require a Windows operating system.  There are workarounds for Linux and Mac, but they remain buggy and incomplete (https://sourceforge.net/p/proteowizard/mailman/message/35780564).

**Comment by arfon** [comment]
@chasemc - could you take a look at this list of viewers and see if you can identify any other potential candidates? https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
Also, feel free to nominate anyone you are aware of professionally that might be able to review that isn't in this list.

**Comment by chasemc** [comment]
@mwang87 would you still be able to review?  I know you said Windows machines are hard to come by.

**Comment by chasemc** [comment]
If not- maybe @lgatto could or would know someone.

**Comment by mwang87** [comment]
@chasemc Would be happy to review. I have my personal windows machine at home that I can install it on. 

--Ming

**Comment by lgatto** [comment]
@chasemc - I don't have any windows computer at hand for the moment, and won't before a couple of months. 
What about @jotsetung? Or @vladpetyuk? Do you have access to a windows.

**Comment by chasemc** [comment]
@arfon How many reviewers does JOSS usually have? I can see if I can suggest others if needed.

**Comment by arfon** [comment]
@chasemc - ideally two or more.

**Comment by jotsetung** [comment]
I do have a Windows (7) virtual machine for testing purposes, but I'm still in post-vacation stress and quite busy the next weeks.

**Comment by chasemc** [comment]
I think mass spec is especially well covered.  I went through the google doc again and think the following people (in no specific order) would also be qualified for review.
@juanvillada 
@road2stat  
@skummerf 
@mschubert 
@semacu

**Comment by arfon** [comment]
:wave: @jotsetung - would you be able to commit to reviewing this package by mid-September?

**Comment by arfon** [comment]
@juanvillada, @road2stat, @skummerf, @mschubert, @semacu - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by mschubert** [comment]
I don't have a Windows box. - Judging from the comments, this seems to be a requirement.

**Comment by semacu** [comment]
I am unable to grade the submission as I am not an expert on this area and I do not have access to a Windows machine to try / test mzEasy in detail. Here are some points though:
- It would be useful if the paper could mention any ongoing research projects ot recent publications using mzEasy specifically
- Contains MIT LICENSE file
- Statement of need: it would be useful if the author could spell out both in the paper and the documentation the meaning of the acronym GNPS
- Installation instructions: Good, some dependencies (RInno / DesktopDeplyR) seem to be automatically installed after running the exe installer. However others (Proteowizard) require separate installation. Can all the different dependencies be installed at once?
- No example usage presented in the README. Please include a step-by-step example of how to use  mzEasy in a real dataset.
- Contains guidelines in CONTRIBUTING.md
- I could not try / test mzEasy as I don't have access to Windows (In a separate note, it'd be good to include an extra column in the joss_reviewers excel sheet to add a list of accessible OS by each potential reviewer)

**Comment by chasemc** [comment]
Thank you for your time @semacu.  I've informally outlined some responses below.

- It would be useful if the paper could mention any ongoing research projects ot recent publications using mzEasy specifically
  - I don't personally have any current projects using it, but certainly will within the next 6 months and it would have been useful for past work.  It has been downloaded > 70 times in 10 countries and I personally know a few people using it, but no publication.
- Statement of need: it would be useful if the author could spell out both in the paper and the documentation the meaning of the acronym GNPS 
  - Will do!
- Installation instructions: Good, some dependencies (RInno / DesktopDeplyR) seem to be automatically installed after running the exe installer. However others (Proteowizard) require separate installation. Can all the different dependencies be installed at once?
  - Unfortunately not for Proteowizard for the same reason the program requires Windows (https://github.com/openjournals/joss-reviews/issues/804#issuecomment-403336901)- the vendor-supplied dlls in Proteowizard are windows based and the vendor-licenses are not all open for secondary distribution. 
- No example usage presented in the README. Please include a step-by-step example of how to use mzEasy in a real dataset.
  - Will do!

Thanks again for the extra effort.
-Chase

**Comment by juanvillada** [comment]
Thanks for the invitation @arfon. I am sorry, I could have access to a Windows machine on the weekend, but I am not experienced enough to judge a submission in this area.

**Comment by arfon** [comment]
@whedon add @mwang87 as reviewer

**Comment by whedon** [comment]
OK, @mwang87 is now a reviewer

**Comment by arfon** [comment]
Reading back up this thread, I'd forgotten that @biswapriyamisra had kindly carried out a pre-review of this submission already. I'm hoping he's willing to help us with the main review too 😄

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/928. Feel free to close this issue now!

**Comment by arfon** [comment]
@biswapriyamisra, @mwang87 - I've gone ahead and set up the main review issue over in #928. Any questions/comments/feedback should be in that issue please.
