### ISSUE TITLE
[PRE REVIEW]: pyPhenology: A python framework for plant phenology modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#805]
**Submitting author:** @sdtaylor (<a href="http://orcid.org/0000-0002-6178-6903">Shawn Taylor</a>)
**Repository:** <a href="https://github.com/sdtaylor/pyPhenology" target ="_blank">https://github.com/sdtaylor/pyPhenology</a>
**Version:** v0.5.0
**Editor:** @pjotrp
**Reviewers:** @harmn, @Chilipp

**Author instructions**

Thanks for submitting your paper to JOSS @sdtaylor. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sdtaylor if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #805 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/805/paper/paper.md): mapping values are not allowed in this context at line 2 column 19 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@sdtaylor - https://github.com/sdtaylor/pyPhenology/pull/87 should fix your paper.

**Comment by sdtaylor** [comment]
thanks!

**Comment by sdtaylor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00805/joss.00805/10.21105.joss.00805.pdf)

**Comment by sdtaylor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00805/joss.00805/10.21105.joss.00805.pdf)

**Comment by sdtaylor** [comment]
From the list I think @Chilipp, @jsta, and @molgor might be suitable reviewers.

**Comment by molgor** [comment]
Hi @sdtaylor I´d be interested but I'm new to this. Do you have any guideline?

**Comment by sdtaylor** [comment]
Reviewer guidelines are here http://joss.theoj.org/about#reviewer_guidelines, hopefully an editor will chime in with more details.

**Comment by Chilipp** [comment]
Hi @sdtaylor and @arfon : I am not an expert on phenology, to be honest, so I cannot judge the usefulness, comprehensiveness and correct implementation of the software. Here, @jsta would be a better reviewer, probably.
But if that is no problem for you (and for @arfon), I am happy to contribute here by reviewing and testing the technical aspects of pyPhenology and work myself through the docs.

**Comment by arfon** [comment]
> But if that is no problem for you (and for @arfon), I am happy to contribute here by reviewing and testing the technical aspects of pyPhenology and working myself through the docs.

Hi @molgor - as @sdtaylor mentioned above, we post our review guidelines here: http://joss.theoj.org/about#reviewer_guidelines

I'm also working on an updated set of docs over in https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

Basically, the review happens in a GitHub issue, is checklist-driven, and is generally more of a conversation with the author (and other reviewer sometime). If this sounds like something you might be able to help with I'll go ahead and start setting up the review thread.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@assign @Chilipp as reviewer

**Comment by pjotrp** [comment]
Thanks @Chilipp - I am looking for a second reviewer to help you out. Part of the fun of doing this work is to learn about new topics!

**Comment by pjotrp** [comment]
@whedon add @harmn as reviewer

**Comment by whedon** [comment]
OK, @harmn is now a reviewer

**Comment by pjotrp** [comment]
@whedon add @Chilipp as reviewer

**Comment by whedon** [comment]
OK, @Chilipp is now a reviewer

**Comment by pjotrp** [comment]
We should have one editor and two reviewers now :)

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/827. Feel free to close this issue now!
