### ISSUE TITLE
[PRE REVIEW]: CusToM: a Matlab toolbox for musculoskeletal simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#806]
**Submitting author:** @anmuller (<a href="http://orcid.org/0000-0003-2606-1429">Antoine Muller</a>)
**Repository:** <a href="https://github.com/anmuller/CusToM.git" target ="_blank">https://github.com/anmuller/CusToM.git</a>
**Version:** v1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @modenaxe, @demotu

**Author instructions**

Thanks for submitting your paper to JOSS @anmuller. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@anmuller if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @Kevin-Mattheus-Moerman the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00806/joss.00806/10.21105.joss.00806.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard @moorepants @cybanical @tshu @CELavecchia would you be interested in reviewing this [JOSS](http://joss.theoj.org/about) submission? The review process (once initiated) will take place on GitHub and focuses on [a short paper](https://github.com/openjournals/joss-papers/blob/joss.00806/joss.00806/10.21105.joss.00806.pdf) and the [software](https://github.com/anmuller/CusToM).

**Comment by moorepants** [comment]
I could review this except that I do not have access to Matlab. Does it run in Octave? If so, I will review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mnawrot are you interested in reviewing this work?

**Comment by CELavecchia** [comment]
I am very interested in the topic, however I am not able to do it in the next weeks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@CELavecchia are you able to take on the review at this point? :rabbit: :rocket: :robot:

**Comment by Kevin-Mattheus-Moerman** [comment]
@mnawrot are you able to review this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard are you interested in reviewing this work?

**Comment by trallard** [comment]
hey @Kevin-Mattheus-Moerman I am not sure if I still have access to MATLAB, but I can check later today/early tomorrow and take up on it if so

**Comment by Kevin-Mattheus-Moerman** [comment]
@anmuller can you comment on whether your submission is compatible with Octave?

**Comment by trallard** [comment]
hi, I am afraid I no longer have a working license for MATLAB so will have to miss this

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard okay. No worries

**Comment by Kevin-Mattheus-Moerman** [comment]
@stavness would you be interested in reviewing this work?

**Comment by Kevin-Mattheus-Moerman** [comment]
@chrisdembia @sohapouya @modenaxe @demotu would you be interested in reviewing this for the [Journal of Open Source Software](http://joss.theoj.org/)? [The review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#the-joss-review-process) focuses on [the software :floppy_disk:](https://github.com/anmuller/CusToM) as well as a very [short paper :page_facing_up:](https://github.com/openjournals/joss-papers/blob/joss.00806/joss.00806/10.21105.joss.00806.pdf).  Let me know if you are interested or if you have questions.

**Comment by stavness** [comment]
Hi Kevin,

Thanks for the invitation, but I'm on sabbatical until next July, so I am
trying to limit my admin work.

Ian

**Comment by demotu** [comment]
I am on vacation; i would be able to review by October.

**Comment by Kevin-Mattheus-Moerman** [comment]
Great @modenaxe, thanks! I'll add you as reviewer shortly. This is a pre-review issue. The actual review will take place in a new review issue which I'll open once there are enough reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @modenaxe as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @modenaxe

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @demotu as reviewer

**Comment by whedon** [comment]
OK, @demotu is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/927. Feel free to close this issue now!
