### ISSUE TITLE
[PRE REVIEW]: MaDaTS: Managing Data on Tiered Storage for Scientific Workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#807]
**Submitting author:** @dghoshal-lbl (<a href="http://orcid.org/0000-0002-6819-6949">Devarshi Ghoshal</a>)
**Repository:** <a href="https://github.com/dghoshal-lbl/madats" target ="_blank">https://github.com/dghoshal-lbl/madats</a>
**Version:** v1.1.2
**Editor:** @danielskatz
**Reviewers:** @ian-taylor, @gflofst

**Author instructions**

Thanks for submitting your paper to JOSS dghoshal-lbl. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

dghoshal-lbl if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #807 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by dghoshal-lbl** [comment]
Hi @arfon - I have fixed the header and pushed in the changes.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00807/joss.00807/10.21105.joss.00807.pdf)

**Comment by arfon** [comment]
@danielskatz - is this something you might be interested in editing?

**Comment by danielskatz** [comment]
If the authors are ok with me editing, I'm happy to.  (There's a small possibility of an informal conflict, though not a formal one according to the JOSS guidelines.)

@dghoshal-lbl - what do you think?

**Comment by dghoshal-lbl** [comment]
@danielskatz I am fine with you being the editor. However, I am not sure if there is a possibility of a conflict.

**Comment by danielskatz** [comment]
It's not a formal conflict, so let's not worry about it as long as you are ok with me doing this, which you are.

@dghoshal-lbl - can you suggest potential reviewers?   In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by dghoshal-lbl** [comment]
@danielskatz I am not sure if I have a good idea of who can be the potential reviewers. Since the code is in Python, I think anyone who has a working knowledge of Python can review this. Last time, I submitted a Python software to JOSS, I think @krother was the reviewer.

**Comment by danielskatz** [comment]
The potential reviewers don't have to be from the list of reviewers - you can give me suggestions of others as well.  For example, if you were submitting a paper on this to a conference, who would you want to review it?

**Comment by dghoshal-lbl** [comment]
@danielskatz If there are no potential reviewers assigned to this, one suggestion is: Jay Lofstead (http://www.lofstead.org/)

**Comment by danielskatz** [comment]
Thanks @dghoshal-lbl - I'll check with Jay.  I've also been trying to find a number of other people through email, but without success so far.

**Comment by whedon** [comment]
OK, the reviewer is @ian-taylor

**Comment by danielskatz** [comment]
I'm still looking for one more reviewer before I start the review.  In addition, @ian-taylor is not available until the 2nd week of August, so this isn't delaying the review.

**Comment by danielskatz** [comment]
@whedon add @gflofst as reviewer

**Comment by whedon** [comment]
OK, @gflofst is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/830. Feel free to close this issue now!

**Comment by danielskatz** [comment]
yeah, no bananas any more!!! 🎆

**Comment by arfon** [comment]
> yeah, no bananas any more!!! 🎆
😁
