### ISSUE TITLE
[PRE REVIEW]: Correlation Trait Loci (CTL) mapping: phenotype network inference subject to genotype

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#81]
**Submitting author:** @DannyArends (<a href="http://orcid.org/0000-0001-8738-0162">Danny Arends</a>)
**Repository:** <a href="https://github.com/DannyArends/CTLmapping" target ="_blank">https://github.com/DannyArends/CTLmapping</a>
**Version:** v1.0.0-joss-1
**Editor:** @biorelated
**Reviewer:** @byandell

**What this issue is for**

Thanks for submitting your paper to JOSS @DannyArends. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @biorelated it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@biorelated would you be able to play the role of editor on this submission?

**Comment by pjotrp** [comment]
@whedon help

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @biorelated as editor

**Comment by whedon** [comment]
OK, the editor is @biorelated

**Comment by pjotrp** [comment]
@biorelated we need to find a reviewer. Best approach is to look in our network. You can also put a call up on twitter and MLs. @byandell would you be interested to review this work? Take a look at the other reviews to see what it entails.

**Comment by arfon** [comment]
@pjotrp let's leave this issue open until we have a reviewer too.

**Comment by pjotrp** [comment]
It was an accident - I am challenged with the mouse and non-text UIs ;). Also note that @whedon does not respond to box updates.

**Comment by arfon** [comment]
> It was an accident - I am challenged with the mouse and non-text UIs ;)

😆 no problem.

> Also note that @whedon does not respond to box updates.

Not sure what you mean by _'box updates'_?

**Comment by biorelated** [comment]
+1 👍

**Comment by pjotrp** [comment]
@whedon assign @byandell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @byandell

**Comment by pjotrp** [comment]
@byandell will review the CTL paper in the coming weeks

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/87. Feel free to close this issue now!
