### ISSUE TITLE
[PRE REVIEW]: Samewords: Word disambiguation in critical text editions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#810]
**Submitting author:** @Stenskjaer (<a href="http://orcid.org/0000-0002-8190-679X">Michael Stenskjær Christensen</a>)
**Repository:** <a href="https://github.com/stenskjaer/samewords" target ="_blank">https://github.com/stenskjaer/samewords</a>
**Version:** 0.5.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @maieul, @MarjorieBurghart, @Padlina

**Author instructions**

Thanks for submitting your paper to JOSS @Stenskjaer. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Stenskjaer if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #810 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00810/joss.00810/10.21105.joss.00810.pdf)

**Comment by stenskjaer** [comment]
I'm a little bit uncertain whether I am expected to react to this, or I just wait until reviewers are assigned?

I could maybe make some minor changes to the text, now that I have seen the PDF proof. But I'm not sure this is the time and place.

**Comment by arfon** [comment]
> I'm a little bit uncertain whether I am expected to react to this, or I just wait until reviewers are assigned?

Hi @stenskjaer - we're currently waiting for an editor to pick up this submission. We currently have close to 100 submissions in progress and so are a little behind. Thanks for your patience.

In the meantime, if you want to edit your paper, please do so and then as @whedon to recompile it with:

```
@whedon generate pdf
```

**Comment by stenskjaer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00810/joss.00810/10.21105.joss.00810.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@stenskjaer thanks for your submission. From reading your paper it seems your work is a useful package to automate the disambiguation of identical words e.g. when writing critical notes. It is unclear to me however how this work is relevant to research (I am not an expert in this field). The [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) state: 

> The software should have an **obvious** research application

Could you please have a read through the submission requirements and ensure that your paper clearly discusses research applications, and how the software influences research outcomes?

**Comment by stenskjaer** [comment]
@Kevin-Mattheus-Moerman thank you for your response.

I think it is important to stress that the creation of critical text editions and textual criticism is the most foundational research you can find when it comes to any text interpretative discipline. The purpose of the activity is to provide texts that will be the basis for any subsequent work, be it analysis by a researcher, translation for further sedimentation, or leisurely reading. This activity thus provides the raw material for any kind of research within a given discipline. 

Establishing such texts, be it in English, German, French or the classical languages such as Greek and Latin in my own case, is a highly specialized activity presupposing research skills in all the relevant subject areas of a text, such as the linguistic disciplines, the study of the content, but also the whole discipline of stemmatics, codicology, palaeography (it very often involves reading medieval or early modern material in manuscript form), and text history. For some descriptions of these different branches of the discipline, see [the wikipedia article](https://en.wikipedia.org/wiki/Textual_criticism).

The [review and vetting sheet for the Modern Language Association](https://www.mla.org/Resources/Research/Surveys-Reports-and-Other-Documents/Publishing-and-Scholarship/Reports-from-the-MLA-Committee-on-Scholarly-Editions/Guidelines-for-Editors-of-Scholarly-Editions) for critical text editions will give you an impression of some of the requirements of a critical text edition.

To get an impression of what the results of such textual work looks like, I can point you to one of my own publications: https://cimagl.saxo.ku.dk/download/86/86christensen79-131.pdf.
But you can also have a look at this picture of a page from the standard critical edition of the New Testament in Greek.
![c5euc84lap8jf1dnr](https://user-images.githubusercontent.com/4047523/45203924-fa03a880-b27d-11e8-9f88-b639df273582.jpg)

It is all the cryptical scriblings at the bottom of the page, the so-called critical apparatus, that is the focus of this package. That apparatus of critical notes shows how a range of witnesses to a text (in my own case just two manuscripts which of course is much simpler than the hundreds of manuscripts and papyrus fragments in the Greek bible) differ and are related. All that information is very densely represented, as you can see, but it also serves as a direct tool for any domain expert to glean important information about the history of a text, relation between its witnesses and alternative readings of any passages. 
As you can see, this is not just everyday pedestrial footnotes. 

My package is written to make that process of establishing that critical apparatus more accurate and less error-prone. In my view it therefore contributes directly to the improvement of research, as it is used to produce research results in their own right, but those results are also the direct basis for any further research within a text discipline.

If you would like me to, I should be very happy to make these connections clear in the paper. It may be made more clear what is mean by a *critical* edition in the article. It is kept out for the sake of brevity, as (and I mean absolutely no offence by saying this) I believe that the research application is immediately obvious to to any researcher who uses the software to improve his critical textual editions.

I would also be happy to provide you with any further information about the field, if you have the stamina to evaluate the research literature.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@olivierverdier @JelteF @gpoore @alvinwan @maieul @adunning @kfeuerherm @pharos-alexandria @awtrindade would you be interested in reviewing this submission (_Samewords: Word disambiguation in critical text editions_) for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/about)? [The review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#the-joss-review-process) focuses on [the software :floppy_disk:](https://github.com/stenskjaer/samewords) and [this short paper :scroll:](http://joss.theoj.org/about).
This submission features python (for critical text editing) with LaTeX, even if the actual application is not your field of expertise we would still appreciate review contributions in relation to the software itself. We aim to recruit multiple reviewers, some of whom are ideally working in a field related to this submission, however some may not work in this field but their software skills overlap such that they may judge the quality of the software.

**Comment by maieul** [comment]
Dear @Kevin-Mattheus-Moerman I could, but as the author of the software on which Michael software is based, I am not sur to be the best man....

**Comment by Kevin-Mattheus-Moerman** [comment]
@maieul thanks for your reply. You are probably hinting at a potential conflict of interest since you developed the "reledmac" package. Thanks for bringing this to our attention. Since we'll recruit multiple reviewers, and since you are not an author of the work presented here, I do not consider this to be a serious conflict of interest issue. If you are still interested I'd welcome you as a reviewer given your expertise in this field.

**Comment by maieul** [comment]
dear @Kevin-Mattheus-Moerman it could be ok for myself.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @maieul as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @maieul

**Comment by maieul** [comment]
@Kevin-Mattheus-Moerman my opinion : I don't see any problem in the article, except that is may be elliptic on two points:
- what is a critical edition
- in which way editor must mark the text manually with reledmac, and what the software does could be a good point

I don't know the FOSS, but I think the article should be more explicit for not philologist reader.

**Comment by Kevin-Mattheus-Moerman** [comment]
@maieul thanks for your comments. @stenskjaer can start working on these comments. BTW as a side not this is currently a _pre-review issue_. You are welcome to start reviewing already but once I have some additional reviewers lined up I'll open the actual _review issue_. A review issue looks like [this](https://github.com/openjournals/joss-reviews/issues/845) and contains a checklist which guides reviewers through the review process. Thanks again for your help!

**Comment by stenskjaer** [comment]
@Kevin-Mattheus-Moerman This is great! Should I start revising the article based on @maieul's comments or wait until we are furhter in the review process (comments from other reviewer and you as the editor?).

**Comment by stenskjaer** [comment]
Another possible reviever could be @MarjorieBurghart who first raised the problem within the context of the reledmac LaTeX package (https://github.com/maieul/ledmac/issues/467).

**Comment by stenskjaer** [comment]
Yet another good possible reviewer could be @Padlina.

**Comment by Kevin-Mattheus-Moerman** [comment]
@Padlina @MarjorieBurghart would you be interested in reviewing this submission (_Samewords: Word disambiguation in critical text editions_) for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/about)? [The review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#the-joss-review-process) focuses on [the software :floppy_disk:](https://github.com/stenskjaer/samewords) and [this short paper :scroll:](http://joss.theoj.org/about).

**Comment by Kevin-Mattheus-Moerman** [comment]
@stenskjaer you can start working on the comments now if you like. We'll reiterate what has been done as part of the review in the actual review issue as well.

**Comment by Kevin-Mattheus-Moerman** [comment]
@MarjorieBurghart @Padlina Excellent thanks! We generally aim for 2 weeks but there is not real set deadline. Some reviews take days others months but we of course prefer a speedy process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @MarjorieBurghart as reviewer

**Comment by whedon** [comment]
OK, @MarjorieBurghart is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @Padlina as reviewer

**Comment by whedon** [comment]
OK, @Padlina is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@MarjorieBurghart are [this](https://www.digitalmanuscripts.eu/people/co-ordinators/marjorie-burghart/) and [this](http://ciham.ish-lyon.cnrs.fr/membres/marjorie-burghart) accurate professional links for you?  @Padlina could you share your full name and preferably a link to a professional profile? Apologies I could not tell much from your GitHub profiles.

**Comment by MarjorieBurghart** [comment]
@Kevin-Mattheus-Moerman the first link is an accurate bio but not an institutional link (it's a project website), the second is the "official" page on my research centre's website

**Comment by gpoore** [comment]
@Kevin-Mattheus-Moerman I don't have any expertise in this area, just experience with Python and LaTeX. Unfortunately, I'm currently not able to take on any additional projects until at least December, so I would recommend finding others who can review this sooner.

**Comment by Padlina** [comment]
@Kevin-Mattheus-Moerman My full name is Roberta Padlina. I don't really have a professional profile online, except for LinkedIn ([here](https://www.linkedin.com/in/roberta-padlina-6589591)) which isn't really updated. I'm a PhD student in Medieval Philosophy at the University of Fribourg, but I also work in the DH field: I worked a long time for e-codices ([my old page](https://lettres.unifr.ch/fr/hist/histoire/sciences-auxiliaires-de-lhistoire/collaborateurs/padlina.html)) and I'm working now since a year for the NIE-INE project at the University of Basel ([here](http://www.fee.unibas.ch/nie_ine.html)). Is this info enough?

**Comment by Kevin-Mattheus-Moerman** [comment]
@Padlina yes, thanks for sharing that information.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/941. Feel free to close this issue now!
