### ISSUE TITLE
[PRE REVIEW]: powermh: Power analysis for studies with multiple hypotheses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#813]
**Submitting author:** @dbrookswr (<a href="http://orcid.org/0000-0002-4619-1848">Daniel Wright</a>)
**Repository:** <a href="https://github.com/dbrookswr/powermh" target ="_blank">https://github.com/dbrookswr/powermh</a>
**Version:** v0.1.0
**Editor:** @cMadan
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @dbrookswr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dbrookswr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #813 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @cMadan - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@dbrookswr - looks like you've got a typo in your `paper.md` file: `bilbliography`

**Comment by dbrookswr** [comment]
Thank you!  The spelling of bibliography has been fixed. Dan

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #813 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Marianna E. Carlucci (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by cMadan** [comment]
@dbrookswr, can you correct the ORCiD for your coauthor?

**Comment by dbrookswr** [comment]
Sorry about the delay. Summer holidays away from email.  I put her ORCID in
now.

Dan

On Wed, Jul 25, 2018 at 4:54 AM, Christopher Madan <notifications@github.com

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00813/joss.00813/10.21105.joss.00813.pdf)

**Comment by cMadan** [comment]
@dbrookswr, it looks like there are some issues in your paper.md. Can you fix this? You can also ask @whedon to recompile (as I did above), to confirm that it's all sorted afterwards.

The main issue seems to be with extra line breaks, compare https://raw.githubusercontent.com/dbrookswr/powermh/master/paper.md and https://joss.readthedocs.io/en/latest/submitting.html.

**Comment by dbrookswr** [comment]
Sorry about that. I did have too many spaces in that part of the document.

Dan

On Tue, Jul 31, 2018 at 3:06 PM, Christopher Madan <notifications@github.com

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00813/joss.00813/10.21105.joss.00813.pdf)

**Comment by cMadan** [comment]
@dbrookswr, great the paper.md seems to be in order now and the repo passes the general checks (e.g., having a license).

Do you have any suggestions for reviewers? Feel free to consult the list of volunteers linked in the first post in this issue thread.

**Comment by dbrookswr** [comment]
Sorry for the delay. I have jury duty.  Three reviewers from the list that
look good are:

benmarwick
bradweiner
lebebr01

Much thanks,

Dan

**Comment by cMadan** [comment]
@benmarwick @bradwiner @lebebr01, are you available and interested in reviewing this submission? Thanks for your consideration!

**Comment by benmarwick** [comment]
Thanks for considering me. I'm afraid I must decline as I'm already late for reviewing another JOSS submission. I'd like to recommend that the authors use the rOpenSci packaging guide to prepare their submission for JOSS: https://ropensci.github.io/dev_guide/building.html Most R package reviewers will be expecting this.

**Comment by cMadan** [comment]
@dbrookswr, do you have any other suggestions for reviewers, or plans on using the packaging guide (or leaving it as-is) ?

**Comment by dbrookswr** [comment]
We are happy with it.  Dan

**Comment by lebebr01** [comment]
I apologize for the delayed response, I was on vacation during the original ping. I would be happy to review, however, in my quick 3 minute look at the repo there is no indication about how to install the software. In addition, as Ben noted, the package does not follow common or required R package guidelines. 

Therefore, in it's current form I would decline to review and also second Ben's comment about following common R package guidelines as these will likely be issues during the review phase.

**Comment by cMadan** [comment]
Thanks for taking a quick look, @lebebr01, I appreciate your input on this!

**Comment by cMadan** [comment]
@dbrookswr, do you still intend to move ahead with this submission?

**Comment by dbrookswr** [comment]
Sorry I have been slow. I do. I will make these changes soon.
Unfortunately I have had some family issues that are slowing my research
down.

Dan

**Comment by cMadan** [comment]
@dbrookswr, no problem, thanks for the update.

**Comment by cMadan** [comment]
@dbrookswr, how are things going?

**Comment by dbrookswr** [comment]
Hi Christopher,

Thanks for asking.

It is probably best to un-submit this this piece. It will be several months
before things get back to normal.

Dan

**Comment by cMadan** [comment]
@dbrookswr, okay, I will mark this submission as withdrawn.
