### ISSUE TITLE
[PRE REVIEW]: YAD: A Learning-based Inductive Logic Programming Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#816]
**Submitting author:** @hamedmx (<a href="http://orcid.org/0000-0002-9132-593X">Hamed Karimi</a>)
**Repository:** <a href="https://github.com/hamedmx/YAD-ILP-Tool" target ="_blank">https://github.com/hamedmx/YAD-ILP-Tool</a>
**Version:** v1.0
**Editor:** @jasonclark
**Reviewers:** @dredamonsta1

**Author instructions**

Thanks for submitting your paper to JOSS @hamedmx. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@hamedmx if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jasonclark it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #816 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Ali Kamandi (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @jasonclark - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@hamedmx - please see the error above. Authors don't have to include and ORCID but the one you've given here is invalid.

**Comment by hamedmx** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #816 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:91:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:91:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #816 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    227      0 --:--:-- --:--:-- --:--:--   226
100    12    0    12    0     0    226      0 --:--:-- --:--:-- --:--:--   226
[WARNING] Could not convert image '/tmp/tex2pdf.88/6e81298938ff130e201773573b4fd1fd6d389e60.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
[WARNING] Could not convert image '/tmp/tex2pdf.88/39a2c668737d80b4ecd6961a94a3fc054fddc997.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
[WARNING] Could not convert image '/tmp/tex2pdf.88/e12243540d71df5c2d6ace4fdf0cecbef9862f81.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.88/6e81298938ff
130e201773573b4fd1fd6d389e60.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.281 ...8938ff130e201773573b4fd1fd6d389e60.shtml}

Looks like we failed to compile the PDF

**Comment by hamedmx** [comment]
Hello @arfon and @jasonclark , first of all thank you for your guidance. well, it seems to have some problems to compile my paper.md file i guess and i could not find them to resolve. please help me in compile process.

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by arfon** [comment]
> Thank you so much @arfon . Now, i have some problems; firstly, in writing mathematical statements and their symbols and secondly, in going to a new line, using bullets, and writing captions for the figures. So, is there any links to the related guidelines ?

We're just using standard Pandoc/Markdown here: https://pandoc.org/README.pdf

Looks like the document is compiling now :-)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon  generate pdf

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00816/joss.00816/10.21105.joss.00816.pdf)

**Comment by hamedmx** [comment]
I would like to mention @xirdneh as my suggestion to review this submission.

**Comment by hamedmx** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@hamedmx - first we need to hear back from @jasonclark as to whether he is willing to edit this submission, then we need to identify reviewers, then we can start the actual review.

**Comment by hamedmx** [comment]
Thank you very much @arfon . I look forward to your response...

**Comment by jasonclark** [comment]
@arfon @hamedmx I am willing to edit this submission.

**Comment by jasonclark** [comment]
@whedon assign @jasonclark as editor

**Comment by whedon** [comment]
OK, the editor is @jasonclark

**Comment by jasonclark** [comment]
@hamedmx Can you create a README file for the repository? All JOSS entries require a general description of the software (what is it?, why would I use it?, etc.) along with basic install instructions. You might even use some of the narrative from your article at https://github.com/hamedmx/YAD-ILP-Tool/blob/master/YAD-JOSS.pdf.

**Comment by hamedmx** [comment]
@jasonclark Yes, sure. Of course all the desired descriptions about the tool exist in the article, i.e. paper.md file in the repository.

**Comment by hamedmx** [comment]
@jasonclark The required README file is ready in the repository with adequate descriptions about the tool and its usage and also a new additional sample test file has been uploaded there.

**Comment by arfon** [comment]
> @arfon , @jasonclark has declared his willing to edit this submission since about 16 days ago and according to his revision on our repository, we have already prepared the desired README file for the repository. So, when should we identify the reviewers for our submission and start the actual review ?

Yes, time to identify reviewers. @hamedmx - could you take a look a this list of potential reviewers and suggest a few people you think might be suitable? https://bit.ly/joss-reviewers

**Comment by hamedmx** [comment]
Thank you @arfon . Okay, sure. Here are my suggestions for reviewers: @xirdneh , @Fusionet24 , @martinmodrak , and @Dredamonsta1 .

**Comment by martinmodrak** [comment]
I've so far never reviewed for JOSS, so I am not sure if I am expected to react to @hamedmx 's suggestion or if I should wait for @jasonclark . Anyway, I feel the software is on the border of my knowledge (honestly, probably some distance on the wrong side of the border). Also I will be out of office for most of August and early September and so will be able to have a first look no sooner than ~ September 7th. Just thought this might be factors in reviewer selection.

**Comment by arfon** [comment]
> @martinmodrak Thank you very much for your notification. @arfon So, what is the next step to begin the actual review section ? I've already suggested some other reviewers for our submission about 5 days ago.

Hi @hamedmx, we just need a little more time here I think. @martinmodrak isn't able to look at this submission until early September and none of the other suggested reviewers have responded yet so I think we're still in the pre-review phase.

@xirdneh  @fusionet24 @dredamonsta1 - would one of you be willing to review this submission for JOSS?

**Comment by dredamonsta1** [comment]
Sorry I’m late to reply my mailbox was full I can start reviewing later today I am also new and not sure but I want to help out as best as I can

**Comment by hamedmx** [comment]
Thank you so much @dredamonsta1 . @arfon , @dredamonsta1 is willing to review this submission for us.

**Comment by jasonclark** [comment]
@whedon assign @dredamonsta1 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dredamonsta1

**Comment by jasonclark** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/892. Feel free to close this issue now!

**Comment by jasonclark** [comment]
Closing out of pre-review and setting review at https://github.com/openjournals/joss-reviews/issues/892
