### ISSUE TITLE
[PRE REVIEW]: GEM: A Python package for graph embedding methods

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#817]
**Submitting author:** @palash1992 (<a href="http://orcid.org/0000-0003-2455-2160">Palash Goyal</a>)
**Repository:** <a href="https://github.com/palash1992/GEM" target ="_blank">https://github.com/palash1992/GEM</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @jsgalan, @rougier

**Author instructions**

Thanks for submitting your paper to JOSS @palash1992. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@palash1992 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @danielskatz - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00817/joss.00817/10.21105.joss.00817.pdf)

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@palash1992
1. Can you clean up the references in your paper?  A bunch need DOIs, and have case problems, eg ACM as Acm.
1. Can you suggest any reviewers?  [This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission, or you may have other suggestions for people from the field of your work.

**Comment by palash1992** [comment]
@danielskatz

   1. I have cleaned up the references and modified the paper.bib file in
   Github. I added the missing DOIs (except 1 for which I could not find it).
   The problem about case you mentioned "Acm" is not in the bib but in the
   compiled PDF. I am not sure why that is the case. We can see if the problem
   persists and modify accordingly.
   2. Here are the reviewers who would be suitable for review:


   - jankatins
   - gabrielspadon
   - adebytes
   - paulgovan

Thanks! Let me know if there are any other concerns.

On Tue, Jul 10, 2018 at 1:41 AM, Daniel S. Katz <notifications@github.com>
wrote:

> @palash1992
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palash1992&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=UagMmUqlcX0Vv7jM-_Mpl8A2teKfEdMYXVkBXcz-EY0&s=V8xSto08YZtP9qSzjM94vEPr-UV5M5VcDdpHP-nirqY&e=>
>
>    1. Can you clean up the references in your paper? A bunch need DOIs,
>    and have case problems, eg ACM as Acm.
>    2. Can you suggest any reviewers? This list of people
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__bit.ly_joss-2Dreviewers&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=UagMmUqlcX0Vv7jM-_Mpl8A2teKfEdMYXVkBXcz-EY0&s=ZXVEmSP98HmAs45AH_kF6wf0MBhSibN5XxXAkOiaUW8&e=>
>    have already agreed to review for JOSS and may be suitable for this
>    submission, or you may have other suggestions for people from the field of
>    your work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_openjournals_joss-2Dreviews_issues_817-23issuecomment-2D403706733&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=UagMmUqlcX0Vv7jM-_Mpl8A2teKfEdMYXVkBXcz-EY0&s=CTSSpAQYDoO_cfM6xx8Z65lx2J2mItTi9mahEKUhNrw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABH2RYWExcHkr6OjXzLym6iYxIFG16rcks5uFD6cgaJpZM4VIdID&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=UagMmUqlcX0Vv7jM-_Mpl8A2teKfEdMYXVkBXcz-EY0&s=We4HWChTzUPcMk597FXcXsQ2o9Mrb0eBc99O5D4WJNA&e=>
> .
>



-- 
Regards,
Palash Goyal
Research Assistant
Department of Computer Science
University of Southern California

**Comment by danielskatz** [comment]
@palash1992 The Bib issues can be fixed by putting {}s around letters/words that should be kept in the case that they are.  Otherwise, the paper generation process may change them to what it thinks it correct.

**Comment by danielskatz** [comment]
👋  @jankatins, @gabrielspadon, @adebytes, @paulgovan 
I'm looking for 2 reviewers for this submission - would you be interested/willing to be one of them?

**Comment by palash1992** [comment]
@danielskatz I have made the modification. Hopefully it should be fine now.

**Comment by palash1992** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00817/joss.00817/10.21105.joss.00817.pdf)

**Comment by palash1992** [comment]
@danielskatz : Some other suitable reviewers are @galenstocking, @corybrunson , @vchuravy and @hausen.

**Comment by palash1992** [comment]
@danielskatz : In that case, here are some other reviewers proficient in Python with focus machine learning: @rougier , @sealhuang, @ahurriyetoglu, @betatim and @jsgalan

**Comment by danielskatz** [comment]
👋  @rougier, @sealhuang, @ahurriyetoglu, @betatim, or @jsgalan - would any of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
Thanks @jsgalan - I want to get one more reviewer before we start the review, so please stand by :)

**Comment by danielskatz** [comment]
@whedon assign @jsgalan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jsgalan

**Comment by danielskatz** [comment]
👋  @corybrunson - can I ask you to do this as a second reviewer?

**Comment by corybrunson** [comment]
Yes, though i'll need a few weeks. I just agreed to review another paper closer to my areas of expertise/experience.

**Comment by rougier** [comment]
@danielskatz Sorry for the late answer, I was on vacation. If it's still time, I can also review.

**Comment by corybrunson** [comment]
@danielskatz i can review this coming week, but if @rougier is willing then i would defer to them (Python being their preferred language).

**Comment by danielskatz** [comment]
@rougier - thanks (and sorry for the delay in responding, I was teaching in a week-long summer school)
I'll add you and start the review with you and @jsgalan
@corybrunson  - thanks for volunteering as well, but 2 reviews is good for this one.

**Comment by danielskatz** [comment]
@whedon add @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/876. Feel free to close this issue now!
