### ISSUE TITLE
[REVIEW]: quimb: a python library for quantum information and many-body calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#819]
**Submitting author:** @jcmgray (<a href="http://orcid.org/0000-0001-9461-3024">Johnnie Gray</a>)
**Repository:** <a href="https://github.com/jcmgray/quimb" target ="_blank">https://github.com/jcmgray/quimb</a>
**Version:** 0.4.2
**Editor:** @jedbrown
**Reviewer:** @dalcinl, @sunqm
**Archive:** <a href="https://doi.org/10.5281/zenodo.1408690" target="_blank">10.5281/zenodo.1408690</a>

## Status

[![status](http://joss.theoj.org/papers/92db2a3c1469e004af79e730fa7ae870/status.svg)](http://joss.theoj.org/papers/92db2a3c1469e004af79e730fa7ae870)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/92db2a3c1469e004af79e730fa7ae870"><img src="http://joss.theoj.org/papers/92db2a3c1469e004af79e730fa7ae870/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/92db2a3c1469e004af79e730fa7ae870/status.svg)](http://joss.theoj.org/papers/92db2a3c1469e004af79e730fa7ae870)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jcmgray/quimb" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dalcinl & @sunqm, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jedbrown know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jcmgray/quimb">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.4.2)?
- [x] **Authorship:** Has the submitting author (@jcmgray) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jcmgray/quimb">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.4.2)?
- [x] **Authorship:** Has the submitting author (@jcmgray) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @dalcinl, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00819/joss.00819/10.21105.joss.00819.pdf)

**Comment by sunqm** [comment]
@jcmgray 

Please add the doi for the references.  Most of them should be available This is one item in the JOSS checklist.

**Comment by jcmgray** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00819/joss.00819/10.21105.joss.00819.pdf)

**Comment by jcmgray** [comment]
I've now added a DOI for as many of the references as I can (https://github.com/jcmgray/quimb/commit/0597ecadf5730f8f87fcbba07f0c0827db722a89).

**Comment by sunqm** [comment]
@jcmgray Sorry for the long delay for reviewing. Thanks for updating the reference doi. I noticed that the function documents were generated in the _autosummary folder. Although not required by the review checklist, if possible, I think it may be better to have an entry in the main page or in the developer's notes that points to the _autosummary page.

@jedbrown This is a well written program. I have gone through the checklist and everything looks good to me now. Please let me know what I should do next.

**Comment by jedbrown** [comment]
Great! Thanks, @sunqm and @jcmgray.

@dalcinl Can you weigh in on the remainder of your checklist from your perspective as slepc4py and mpi4py developer?

**Comment by jcmgray** [comment]
> @jcmgray Sorry for the long delay for reviewing. Thanks for updating the reference doi. I noticed that the function documents were generated in the _autosummary folder. Although not required by the review checklist, if possible, I think it may be better to have an entry in the main page or in the developer's notes that points to the _autosummary page.

Not at all, thanks very much for the review! Yes the ``_autosummary`` is used to generate the sections [here (index/module index)](https://quimb.readthedocs.io/en/latest/#indices-and-tables) as well as cross references within the docs. I think you are right that it might be nice to explicitly point this out on the main page / dev pages, so might add that soon.

**Comment by jcmgray** [comment]
Just to note that I have added a brief sentence highlighting those sections.

**Comment by dalcinl** [comment]
@jcmgray Sorry for the long delay. I'm quite happy you are taking advantage of the `mpi4py.futures` framework!. There is just one minor issue with the references in the paper. The citation for `slepc4py` is wrong. There is no published paper about `slepc4py`, the suggested citation would be just the Bitbucket repo https://bitbucket.org/slepc/slepc4py, or maybe this paper https://doi.org/10.1016/j.advwatres.2011.04.013 (though it is about `mpi4py` and `petsc4py`, not `slepc4py`). And maybe you should cite core SLEPc: https://doi.org/10.1145/1089014.1089019 (I think this is the paper you have in the current bib file, although the title and authors are wrong).

**Comment by jcmgray** [comment]
@dalcinl thanks very much for getting round to it - ``mpi4py.futures`` has been very useful! Yes wasn't sure about the ``slepc4py`` reference but have now [updated it](https://github.com/jcmgray/quimb/commit/35535551400a62e5c3c8cb8bda969259ee872e51) with those papers you suggest.

**Comment by jcmgray** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00819/joss.00819/10.21105.joss.00819.pdf)

**Comment by dalcinl** [comment]
@jedbrown The couple issues I found are fixed. Everything looks good to me now.

**Comment by jedbrown** [comment]
@dalcinl Thanks!

@jcmgray I notice one minor grammatical issue in the first paragraph: "requires much care is taken" could be "requires that much care is taken" or "requires great care to be taken". Can you adjust that wording and archive your repository on Zenodo or similar?

**Comment by jcmgray** [comment]
@jedbrown thanks for picking that up - I've adjusted that wording [here](https://github.com/jcmgray/quimb/commit/bae8312a1320da0721a63aa537f50aa5f4652e70). And I've uploaded the package to zenodo [here](https://zenodo.org/record/1408690).

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00819/joss.00819/10.21105.joss.00819.pdf)

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.1408690 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1408690" target="_blank">10.5281/zenodo.1408690</a> is the archive.

**Comment by jedbrown** [comment]
@arfon Over to you.

**Comment by arfon** [comment]
@dalcinl, @sunqm - many thanks for your reviews here and to @jedbrown for edit this submission ✨ 

@jcmgray - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00819 :zap: 🚀:boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00819/status.svg)](https://doi.org/10.21105/joss.00819)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00819">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00819/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00819/status.svg
   :target: https://doi.org/10.21105/joss.00819
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00819/status.svg)](https://doi.org/10.21105/joss.00819)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by jcmgray** [comment]
Fantastic, thanks very much again @jedbrown, @sunqm and @dalcinl!
