### ISSUE TITLE
[REVIEW]: heatwaveR: A central algorithm for the detection of heatwaves and cold-spells

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#821]
**Submitting author:** @robwschlegel (<a href="http://orcid.org/0000-0002-0705-1287">Robert Schlegel</a>)
**Repository:** <a href="https://github.com/robwschlegel/heatwaveR" target ="_blank">https://github.com/robwschlegel/heatwaveR</a>
**Version:** 0.2.7
**Editor:** @leeper
**Reviewer:** @khaors
**Archive:** <a href="https://doi.org/10.5281/zenodo.1324309" target="_blank">10.5281/zenodo.1324309</a>

## Status

[![status](http://joss.theoj.org/papers/9353247bebdfcc0f7357a759381416bb/status.svg)](http://joss.theoj.org/papers/9353247bebdfcc0f7357a759381416bb)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9353247bebdfcc0f7357a759381416bb"><img src="http://joss.theoj.org/papers/9353247bebdfcc0f7357a759381416bb/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9353247bebdfcc0f7357a759381416bb/status.svg)](http://joss.theoj.org/papers/9353247bebdfcc0f7357a759381416bb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/robwschlegel/heatwaveR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@khaors, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/robwschlegel/heatwaveR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (0.2.7)?
- [x] **Authorship:** Has the submitting author (@robwschlegel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @khaors it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00821/joss.00821/10.21105.joss.00821.pdf)

**Comment by leeper** [comment]
@khaors The review checklist is available here. Let me know if you have questions.

**Comment by khaors** [comment]
@leeper In the Installation Instructions, the list of dependencies should be clearly stated. Is this referring  to the README file in addition to the DESCRIPTION file?

**Comment by leeper** [comment]
@khaors DESCRIPTION file is fine, unless there are non-CRAN, non-R, or otherwise atypical dependencies.

**Comment by khaors** [comment]
@leeper I have finished the review. Sorry for the delay. Checking the vignettes took a while but the results are ok. I opened an issue in the heatwaveR repository with the my comments ( you can check this under the tag JOSS review).

**Comment by leeper** [comment]
@khaors Excellent. Thanks for your careful review!

@robwschlegel Please address the issues raised at: https://github.com/robwschlegel/heatwaveR/issues/7 and let me know when you're ready for me to take another look.

**Comment by robwschlegel** [comment]
Hello,
Thank you very much for reviewing the package.
I've read over the comments and am happy to make the changes. I'm
particularly glad that it was recommended to cut down the length of the
README and move that information to separate vignettes.
I've just returned now from a conference and have some work to catch up on
but will make the corrections as soon as I can. Hopefully within a week.
All the best,
-Robert

**Comment by robwschlegel** [comment]
I've addressed the issues at robwschlegel/heatwaveR#7

**Comment by leeper** [comment]
Great, thank you @robwschlegel. @khaors Can you take a look and see if there's anything else that should be addressed?

**Comment by robwschlegel** [comment]
I've addressed the issues at robwschlegel/heatwaveR#7

**Comment by khaors** [comment]
@leeper I checked and the suggestions have been addressed and the heatwaveR package has been modified in accordance.

**Comment by leeper** [comment]
Great. Thanks!

**Comment by leeper** [comment]
@robwschlegel The review process is now complete. To finalize your submission and accept your paper in JOSS, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here to @leeper with the DOI for the release.

Let me know if you have any questions about the process.

**Comment by robwschlegel** [comment]
@leeper 
Here is the web link if that helps:
https://zenodo.org/record/1324309#.W2B7DRgS08o

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1324309 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1324309" target="_blank">10.5281/zenodo.1324309</a> is the archive.

**Comment by leeper** [comment]
@arfon over to you

**Comment by arfon** [comment]
@khaors - many thanks for your review here and to @leeper for editing this submission :sparkles:

@robwschlegel - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00821 :Zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00821/status.svg)](https://doi.org/10.21105/joss.00821)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00821">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00821/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00821/status.svg)](https://doi.org/10.21105/joss.00821)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by robwschlegel** [comment]
Woohoo!
