### ISSUE TITLE
[PRE REVIEW]: pfla: A Python Package for Dental Facial Analysis using Computer Vision and Statistical Shape Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#822]
**Submitting author:** @maxrousseau (<a href="http://orcid.org/0000-0002-1417-2511">Maxime Rousseau</a>)
**Repository:** <a href="https://github.com/maxrousseau/pfla" target ="_blank">https://github.com/maxrousseau/pfla</a>
**Version:** v0.1.4
**Editor:** @arokem
**Reviewers:** @glemaitre, @mnarayan

**Author instructions**

Thanks for submitting your paper to JOSS @maxrousseau. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@maxrousseau if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #822 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by maxrousseau** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by maxrousseau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00822/joss.00822/10.21105.joss.00822.pdf)

**Comment by maxrousseau** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@acabunoc
@arfon
@arokem
@brainstorm
@cMadan
@danielskatz
@george-githinji
@jakevdp
@jasonclark
@jedbrown
@karthik
@katyhuff
@kyleniemeyer
@labarba
@leeper
@lheagy
@mgymrek
@pjotrp
@tracykteal
```

**Comment by maxrousseau** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by pjotrp** [comment]
This is more of an AI thing - which editor do we have specialized in this direction?

**Comment by maxrousseau** [comment]
Indeed, maybe I should suggest Ariel Rokem @arokem as an editor.

**Comment by maxrousseau** [comment]
@arfon - Do you know of any editor that would be available for this type of paper?

Thank you,

Maxime Rousseau

**Comment by arokem** [comment]
I can take this one!

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
👋 @mnarayan: would you be willing to review this article for JOSS?

**Comment by maxrousseau** [comment]
Thank you very much @arokem!

**Comment by maxrousseau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arokem** [comment]
Hey @glemaitre! Would you be willing to review this article for [The Journal of Open Source Software](http://joss.theoj.org/)? It seems to be within your area of expertise. To read more about what the review process entails, please see [this page](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by mnarayan** [comment]
Sure, @arokem Happy to review

**Comment by maxrousseau** [comment]
Thank you @mnarayan!

**Comment by glemaitre** [comment]
I will be able to review it as well

Sent from my phone - sorry to be brief and potential misspell.

**Comment by maxrousseau** [comment]
Thank you @glemaitre!

**Comment by arokem** [comment]
Great. I believe I can assign you both to review this.

**Comment by arokem** [comment]
@whedon add @glemaitre as reviewer

**Comment by whedon** [comment]
OK, @glemaitre is now a reviewer

**Comment by arokem** [comment]
@whedon add @mnarayan as reviewer

**Comment by whedon** [comment]
OK, @mnarayan is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/855. Feel free to close this issue now!

**Comment by arokem** [comment]
Alright! @glemaitre and @mnarayan : please head over to #855 for the review, where you will find a checklist for each one of you at the top. I'll go ahead and close this one.
