### ISSUE TITLE
[PRE REVIEW]: sdmbench: An R Package for Benchmarking Species Distribution Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#823]
**Submitting author:** @boyanangelov (<a href="http://orcid.org/0000-0001-5068-4234">Boyan Angelov</a>)
**Repository:** <a href="https://github.com/boyanangelov/sdmbench" target ="_blank">https://github.com/boyanangelov/sdmbench</a>
**Version:** v0.1.2
**Editor:** @karthik
**Reviewers:** @sckott, @goldingn

**Author instructions**

Thanks for submitting your paper to JOSS @boyanangelov. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@boyanangelov if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00823/joss.00823/10.21105.joss.00823.pdf)

**Comment by arfon** [comment]
👋 @karthik - the submitting author suggested you as the handling editor.

**Comment by karthik** [comment]
Yes happy to review.

**Comment by karthik** [comment]
Have reached out to two reviewers on 07/25

**Comment by karthik** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by karthik** [comment]
@whedon add @sckott as reviewer

**Comment by whedon** [comment]
OK, @sckott is now a reviewer

**Comment by karthik** [comment]
@sckott Hang on till I assign the second reviewer and then I'll start the review thread which will contain the checklist and more instructions. 🙏

**Comment by karthik** [comment]
@whedon add @goldingn as reviewer

**Comment by whedon** [comment]
OK, @goldingn is now a reviewer

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/847. Feel free to close this issue now!
