### ISSUE TITLE
[REVIEW]: Calliope: a multi-scale energy systems modelling framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#825]
**Submitting author:** @sjpfenninger (<a href="http://orcid.org/0000-0002-8420-9498">Stefan Pfenninger</a>)
**Repository:** <a href="https://github.com/calliope-project/calliope" target ="_blank">https://github.com/calliope-project/calliope</a>
**Version:** v0.6.2
**Editor:** @jedbrown
**Reviewer:** @mdoucet, @gonsie, @ecotillasanchez
**Archive:** <a href="https://doi.org/10.5281/zenodo.1262406" target="_blank">10.5281/zenodo.1262406</a>

## Status

[![status](http://joss.theoj.org/papers/5db25929acbe2dd51e7e59078c000346/status.svg)](http://joss.theoj.org/papers/5db25929acbe2dd51e7e59078c000346)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5db25929acbe2dd51e7e59078c000346"><img src="http://joss.theoj.org/papers/5db25929acbe2dd51e7e59078c000346/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5db25929acbe2dd51e7e59078c000346/status.svg)](http://joss.theoj.org/papers/5db25929acbe2dd51e7e59078c000346)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/calliope-project/calliope" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mdoucet & @gonsie & @ecotillasanchez, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/calliope-project/calliope">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.2)?
- [x] **Authorship:** Has the submitting author (@sjpfenninger) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/calliope-project/calliope">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.2)?
- [x] **Authorship:** Has the submitting author (@sjpfenninger) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/calliope-project/calliope">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.2)?
- [x] **Authorship:** Has the submitting author (@sjpfenninger) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @mdoucet, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00825/joss.00825/10.21105.joss.00825.pdf)

**Comment by mdoucet** [comment]
I've completed my review. While I'm not a subject matter expert of energy systems modeling, I found the documentation quite clear. I was able to go through examples without any issue. The code itself is well organized, with great use of continuous integration and automated testing.

**Comment by ecotillasanchez** [comment]
It was a pleasure to review this work by Pfenninger and Pickering. Excellent software and documentation. Please find below some suggestions:

* It is clear from the paper and the examples that the analysis scales well from urban to national networks. For a power systems user, however, it would be good to clarify that building a transmission model with Calliope is different than a traditional power flow analysis (Ybus, generation, demand -> dc or ac power flow equations -> voltage magnitude and angles). 

* Similarly, perhaps note that the focus is power system planning (as opposed to operations). 

* The tutorials cover a great amount of content, options, and optimization constraints. For a given network size, I would suggest a performance comparison between some of the external solvers, or simply some pointers to help users decide before finding possible roadblocks.

**Comment by gonsie** [comment]
Should the version number be updated to the latest release (v0.6.2)?

**Comment by sjpfenninger** [comment]
@gonsie Yes that would make sense. @jedbrown, should we modify the submission now or wait for all reviews to be completed?

**Comment by sjpfenninger** [comment]
I guess the paper also still says 0.6.0 - should I modify `paper.md` or do that at the very end of the review process?

**Comment by jedbrown** [comment]
We can do it at the end.

**Comment by gonsie** [comment]
I am unable the test the functionality of this due to issues with my work firewall (I am unable to install conda / dependencies). I may be able to review this on personal time (maybe another week or so), or I'm happy to defer to the other reviewers.

**Comment by jedbrown** [comment]
I notice the requirement `ruamel.yaml<=0.15` which would allow 0.15.0, but not 0.15.1. Is that really intentional? I also notice that ruamel.yaml 0.15.0 is not compatible with Python-3.7 and that Calliope is not compatible with current ruamel.yaml (at least because it now returns a type that implements the dict interface, but is not an instance of `dict`).

I think the reviews above are sufficient, but wanted to give an opportunity to address version compatibility issues because it would ease non-conda installation and coupling of Calliope with other software.

**Comment by sjpfenninger** [comment]
Thanks @jedbrown for raising the `ruamel.yaml` requirement issue. The version pinning is based on the [ruamel.yaml README](https://pypi.org/project/ruamel.yaml/):

> Starting with version 0.15.0 the way YAML files are loaded and dumped is changing. See the API doc for details. Currently existing functionality will throw a warning before being changed/removed. For production systems you should pin the version being used with ``ruamel.yaml<=0.15``.

Not providing Python 3.7 compatibility is certainly issue. We will investigate this. I don't think there's a quick fix, as we'll have to make some changes to our internals.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00825/joss.00825/10.21105.joss.00825.pdf)

**Comment by jedbrown** [comment]
I installed the software and followed one of the tutorials -- looks great.

@sjpfenninger Can you fix capitalization in the bib file? I think this is a result of a new JOSS style file, but proper names should be protected: "europe", "great britain", "ecos", "san diego, ca", "south africa", "python". When that is fixed, we'll be ready to archive. Thanks for your patience.

**Comment by sjpfenninger** [comment]
@jedbrown That should be fixed. I also bumped `codemeta.json` to v0.6.2 (the current version and the version that was online when the review started).

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00825/joss.00825/10.21105.joss.00825.pdf)

**Comment by jedbrown** [comment]
@sjpfenninger Looks good. Please archive your repository using Zenodo or similar and report the DOI here.

**Comment by sjpfenninger** [comment]
The generic Zenodo DOI is 10.5281/zenodo.593292 and the DOI for version 0.6.2 is 10.5281/zenodo.1262406 -- or do you need the specific commit that contains the accepted version of the JOSS paper to be archived?

**Comment by arfon** [comment]
> @arfon Do we need a fresh archive or is the v0.6.2 DOI sufficient?

Should be sufficient as long as it represents the code associated with this submission (including any changes from the review).

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.1262406 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1262406" target="_blank">10.5281/zenodo.1262406</a> is the archive.

**Comment by jedbrown** [comment]
@arfon Over to you.
Thanks to @ecotillasanchez, @mdoucet, and @gonsie for your reviews.

**Comment by arfon** [comment]
@ecotillasanchez, @mdoucet, @gonsie many thanks for your reviews here and to @jedbrown for editing this submission ✨ 

@sjpfenninger - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00825 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00825/status.svg)](https://doi.org/10.21105/joss.00825)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00825">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00825/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00825/status.svg
   :target: https://doi.org/10.21105/joss.00825
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00825/status.svg)](https://doi.org/10.21105/joss.00825)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by sjpfenninger** [comment]
Thanks @jedbrown, @ecotillasanchez, @mdoucet, @gonsie for your reviews/comments/editing!
