### ISSUE TITLE
[REVIEW]: pyPhenology: A python framework for plant phenology modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#827]
**Submitting author:** @sdtaylor (<a href="http://orcid.org/0000-0002-6178-6903">Shawn Taylor</a>)
**Repository:** <a href="https://github.com/sdtaylor/pyPhenology" target ="_blank">https://github.com/sdtaylor/pyPhenology</a>
**Version:** v0.5.0
**Editor:** @pjotrp
**Reviewer:** @harmn, @Chilipp
**Archive:** <a href="https://doi.org/10.5281/zenodo.1345528" target="_blank">10.5281/zenodo.1345528</a>

## Status

[![status](http://joss.theoj.org/papers/55a690757520d6ba7437db21e8426db2/status.svg)](http://joss.theoj.org/papers/55a690757520d6ba7437db21e8426db2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/55a690757520d6ba7437db21e8426db2"><img src="http://joss.theoj.org/papers/55a690757520d6ba7437db21e8426db2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/55a690757520d6ba7437db21e8426db2/status.svg)](http://joss.theoj.org/papers/55a690757520d6ba7437db21e8426db2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sdtaylor/pyPhenology" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@harmn & @Chilipp, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sdtaylor/pyPhenology">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.0)?
- [x] **Authorship:** Has the submitting author (@sdtaylor) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sdtaylor/pyPhenology">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.0)?
- [x] **Authorship:** Has the submitting author (@sdtaylor) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @harmn, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00827/joss.00827/10.21105.joss.00827.pdf)

**Comment by pjotrp** [comment]
@Chilipp and @harmn we are starting review on this issue tracker. 

@sdtaylor to expedite the review process do you mind going through above list of check boxes and make sure they can be ticked (you can't tick them). Also check the PDF output carefully. Ping us here when you are done.

**Comment by pjotrp** [comment]
Excellent. @Chilipp you can start review! Note @harmn is on holiday, but he is there to help out when he is back.

**Comment by Chilipp** [comment]
Great, I am looking forward to it! I will do it within the next week.

**Comment by Chilipp** [comment]
Hey! I really apologize for the late response, sorry.

I had a closer look at your software and enjoyed it a lot, thanks for your work here! To me it looks like a rather small package (only about ~1000 statements) but the editor knew this, when he accepted your software for review. So there are some minor points that need to be corrected from my point of view:

## General checks

- [ ] **Version**
> Does the release version given match the GitHub release (v0.5.0)?

Only a minor thing here: in https://github.com/sdtaylor/pyPhenology/releases there are two versions available: https://github.com/sdtaylor/pyPhenology/releases/tag/v0.5.0 and  https://github.com/sdtaylor/pyPhenology/releases/tag/0.5.0.
I assume, that v0.5.0 is the official release, so what about tag 0.5.0?

## Documentation

- [ ] **Installation instructions**
> Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

What about the different OS? To me, it looks like it runs on all platforms (Linux, MaxOSX and Windows) but it would be better to have written in the docs. This could be solved by merging https://github.com/sdtaylor/pyPhenology/pull/96

- [ ] **Example usage**
> Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

You have a quickstart example in your docs (http://pyphenology.readthedocs.io/en/master/quickstart.html) but this is very short. Just be a bit more verbose in order to be more transparent, as well.
For example, add some statistics and/or plots on how the prediction compares against the observations (also in order to show the user, how he can compare the two.)

- [ ] **Functionality documentation**
> Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

I like your documentation and your classes are well documented. Only the [Model.score](http://pyphenology.readthedocs.io/en/master/generated/pyPhenology.models.Model.score.html#pyPhenology.models.Model.score) method needs a better docstring but I have the impression that this method is not really maintained (and tested) anyway, since your are not using it nor testing it.

- [ ] **Automated tests**
> Are there automated tests or manual steps described so that the function of the software can be verified?

Your tests are fine and complete, however I strongly recommend to use a coverage service as well since this is super easy for a pure python package and adds more transparency to your open source project. Just use [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/) on your CI and [codecov](https://codecov.io/) or [coveralls](https://coveralls.io/)

- [ ] **Community guidelines**
> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I could not find them, neither in the repository, nor in the docs. Please add the necessary file (e.g. a [CONTRIBUTING](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file in the main repository)

## Software paper

- [ ] **References**
> Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

1. Some DOI and names were wrong (see https://github.com/sdtaylor/pyPhenology/pull/97)
2. Is there any reference that you should provide for [the test data you use in your docs](file:///Users/psommer/Documents/reviews/pyPhenology/pyPhenology/docs/_build/html/utils.html#test-data)? Where is this data coming from?

**Comment by pjotrp** [comment]
@sdtaylor can you address these points?

**Comment by sdtaylor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00827/joss.00827/10.21105.joss.00827.pdf)

**Comment by sdtaylor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00827/joss.00827/10.21105.joss.00827.pdf)

**Comment by sdtaylor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00827/joss.00827/10.21105.joss.00827.pdf)

**Comment by sdtaylor** [comment]
@pjotrp here is my reply for @Chilipp's review

Thanks for reviewing my package and your comments, I appreciate the your thoroughness. Though it is a relatively small package, the process of programming phenology models is a major bottleneck for most researchers, so I hope it will help them out in that regard. As detailed below I've implemented all of your suggestions.

## General Checks

#### Version
The 0.5.0 tag was created mistakenly. I've deleted it and now there is only v0.5.0

## Documentation

#### Installation instructions
pyPhenology does run on all operating systems. Thank you for PR in helping clarifying this, I've merged it.

#### Example usage
I've expanded the quickstart to better describe some of the common usage, such as parameter
adjustment and saving models. I also included a link at the end to point users
towards the examples which represent a more realistic analysis using this package.
You can see the changes [here](https://github.com/sdtaylor/pyPhenology/pull/99/files#diff-9d8a6f5b32d4a70a56734fd0eb50dd5b)

#### Functionality Documentation
Thanks for pointing this out. I would like the score method to be more prominent. I've
updated the docstring to be more clear and added some tests specifically for this here https://github.com/sdtaylor/pyPhenology/pull/98.

#### Automated tests
I have setup codecov for the repository and added the badge to the GitHub readme.

#### Community guidelines
I've added a [CONTRIBUTER.md](https://github.com/sdtaylor/pyPhenology/blob/master/CONTRIBUTING.md) file outlining the basics of contributing, as well
as a [CODE_OF_CONDCUCT.md](https://github.com/sdtaylor/pyPhenology/blob/master/CODE_OF_CONDUCT.md) file.

## Software Paper

#### References

1. I've merged this PR, thanks for fixing this DOI.
2. I've included citations for the 3 datasets used as well as a short description of them in the paper.

**Comment by pjotrp** [comment]
@Chilipp can you check and tick the relevant boxes? If you are happy we can wrap up. @harmn I assume you are happy about this submission?

**Comment by harmn** [comment]
@pjotr, only two very minor issues: 
-the minimal required version for pandas (0.18.0) seems to be incorrect,Series does not have an isna method until 0.21 (used in pyPhenology/models/utils/misc.py on line 53)
-the Basler reference in the text has additional parentheses around the year

**Comment by sdtaylor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00827/joss.00827/10.21105.joss.00827.pdf)

**Comment by sdtaylor** [comment]
Thank you @harmn for reviewing my package. I tested it with pandas 0.18.0 and you are correct that it doesn't work due to this incomparability. I've changed the pandas requirement to 0.21.0. 

For the reference issue, I tried changing the ordering from `[@tang2016, @basler2016]` to `[@basler2016, @tang2016]` and now there is parenthesis around the year of the Tang reference. I'm not sure whats causing that, @pjotrp do you have any ideas?

**Comment by Chilipp** [comment]
@pjotrp  and @sdtaylor: 

> @Chilipp can you check and tick the relevant boxes? If you are happy we can wrap up. @harmn I assume you are happy about this submission?

Done! It's all fine from my point of view. So if The two points by @harmn are fixed, this paper should be accepted.

**Comment by pjotrp** [comment]
@arfon we are ready to accept this submission. Note there is a small issue with generating the PDF (two boxes up on this page). Great work everyone!

**Comment by pjotrp** [comment]
@sdtaylor the review process is now complete. To finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI (if one exists) - I think you have

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here with the DOI for the release.

**Comment by sdtaylor** [comment]
Thanks @pjotrp, The DOI's all look good to me. The current release is no v0.6.0, and I've deposited at zenodo at https://doi.org/10.5281/zenodo.1345528

**Comment by pjotrp** [comment]
@whedon set 10.5281/zenodo.1345528 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1345528" target="_blank">10.5281/zenodo.1345528</a> is the archive.

**Comment by pjotrp** [comment]
@arfon note above comment on parenthesis in the PDF.

**Comment by arfon** [comment]
Looks like the citations need to be separated by semicolons in the `paper.md`: http://pandoc.org/MANUAL.html#citations : 

> Citations go inside square brackets and are separated by semicolons.

I've made this change locally to the `paper.md`.

**Comment by arfon** [comment]
@harmn, @Chilipp - many thanks for your reviews here and to @pjotrp for editing this submission ✨ 

@sdtaylor - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00827 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00827/status.svg)](https://doi.org/10.21105/joss.00827)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00827">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00827/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00827/status.svg)](https://doi.org/10.21105/joss.00827)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
