### ISSUE TITLE
[REVIEW]: The hhi Package: Streamlined Calculation and Visualization of Herfindahl-Hirschman Index Scores

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#828]
**Submitting author:** @pdwaggoner (<a href="http://orcid.org/0000-0002-7825-7573">Philip D. Waggoner</a>)
**Repository:** <a href="https://github.com/pdwaggoner/hhi" target ="_blank">https://github.com/pdwaggoner/hhi</a>
**Version:** v1.1.0
**Editor:** @leeper
**Reviewer:** @cskovron
**Archive:** <a href="https://doi.org/10.5281/zenodo.1336788" target="_blank">10.5281/zenodo.1336788</a>

## Status

[![status](http://joss.theoj.org/papers/0a08e0a488c9291a8412242f49bcbe2c/status.svg)](http://joss.theoj.org/papers/0a08e0a488c9291a8412242f49bcbe2c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0a08e0a488c9291a8412242f49bcbe2c"><img src="http://joss.theoj.org/papers/0a08e0a488c9291a8412242f49bcbe2c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0a08e0a488c9291a8412242f49bcbe2c/status.svg)](http://joss.theoj.org/papers/0a08e0a488c9291a8412242f49bcbe2c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pdwaggoner/hhi" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cskovron, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pdwaggoner/hhi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.0)?
- [x] **Authorship:** Has the submitting author (@pdwaggoner) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @cskovron it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00828/joss.00828/10.21105.joss.00828.pdf)

**Comment by leeper** [comment]
@cskovron The review issue is here. Just work through the checklist (above), [open an issue here](https://github.com/pdwaggoner/hhi/issues) for anything missing or any other changes you'd like to see, and then ping me here when you've completed your review. Let me know if you have any questions.

**Comment by leeper** [comment]
@cskovron Just a nudge on this review.

**Comment by cskovron** [comment]
Everything looks great here. Nice, simple package. Good work @pdwaggoner!

**Comment by pdwaggoner** [comment]
@cskovron Many thanks for the review and words. Appreciate it. @leeper

**Comment by leeper** [comment]
Thanks, @cskovron! Appreciate the quick review!

@pdwaggoner I have a few additional points I'd like to see addressed:

- [ ] You'll need to change the LICENSE file to be LICENSE.md or LICENSE.txt and add it to an .Rbuildignore file.
- [ ] For LICENSE, just have your name and copyright dates (like this: https://github.com/tidyverse/dplyr/blob/master/LICENSE), as this is what CRAN expects for an MIT-licensed package
- [ ] Add the following files to .Rbuildignore:
  - LICENSE.md/LICENSE.txt (as above)
  - hhi_manual.pdf
  - microwaves.csv
  - paper.bib
  - paper.md
  - plot1.png
  - plot2.png
- [ ] Please add a `/tests` directory that contains an automated test (e.g., using testthat) that verifies the calculated index is correct for either a simulated or example dataset. More information on testing can be found in: http://r-pkgs.had.co.nz/tests.html. An example of what I'm looking for can be found here: https://github.com/leeper/GK2011/blob/master/tests/testthat/tests.R.
- [ ] I believe you can simplify these lines: https://github.com/pdwaggoner/hhi/blob/master/R/hhi.R#L31-L37 to just be the following vectorized alternative, which will be faster:

```R
if (any(d < 0)) {
    stop('vector "s" must contain only positive values')
}
hhi <- sum(d^2)
```

- [ ] Optional: consider setting up a continuous integration service. For details: http://r-pkgs.had.co.nz/check.html

Once that's done, please deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here to @leeper with the DOI for the release.

Let me know if you have any questions about the process.

**Comment by pdwaggoner** [comment]
@leeper This sounds great. I will get on these things in a day or so. Thanks. To be extra clear, did you want me to resubmit my package to CRAN after adding these things, or did you want me to make the changes only in GitHub (e.g., in the current release on CRAN, the LICENSE file is currently a .txt in the exact form you suggested; its only more verbose on GitHub)? Just want to get it right the first time. Thanks!

**Comment by leeper** [comment]
For JOSS, I'm only concerned about GitHub. CRAN release is up to you.

**Comment by pdwaggoner** [comment]
@leeper Alright - I think everything is good to go. I followed all steps, and think the tests should be structure properly as well. I created the release and also generated the DOI with Zenodo. Here is the target URL they provided: https://doi.org/10.5281/zenodo.1336788 . Let me know what next steps are. I would like to quickly update the sample code structure in my paper prior to finalizing it with JOSS and also update my thanks section, if at all possible. Thanks again!

**Comment by leeper** [comment]
@pdwagonner Great. Please update your paper accordingly and we'll regenerate the PDF.

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1336788 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1336788" target="_blank">10.5281/zenodo.1336788</a> is the archive.

**Comment by leeper** [comment]
@pdwaggoner Great. Please update your paper accordingly and we'll regenerate the PDF.

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00828/joss.00828/10.21105.joss.00828.pdf)

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00828/joss.00828/10.21105.joss.00828.pdf)

**Comment by leeper** [comment]
@pdwaggoner Great. I also just sent you a PR: https://github.com/pdwaggoner/hhi/pull/3, which will hopefully get the code chunks rendering correctly in the PDF.

**Comment by pdwaggoner** [comment]
@leeper Perfect; its merged. I was wondering why it did that, but I suppose it was just an old format for inserting code into md. Many thanks for the find and fix!

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00828/joss.00828/10.21105.joss.00828.pdf)

**Comment by leeper** [comment]
@pdwaggoner Thanks. Take a look at the PDF and make sure everything looks ok. Seems like you might want to tweak the paper.md to wrap some of the longer code and comment lines. That's a purely aesthetic change, though.

**Comment by pdwaggoner** [comment]
Thanks @leeper . I updated the code a bit and it looks fine in my repo. Would you mind generating one more time to make sure it looks alright when compiling the PDF?

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00828/joss.00828/10.21105.joss.00828.pdf)

**Comment by leeper** [comment]
Looks good to me. Thanks, @pdwaggoner!

**Comment by leeper** [comment]
@arfon Over to you.

**Comment by arfon** [comment]
@cskovron - many thanks for your review and to @leeper for editing this submission ✨ 

@pdwaggoner - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00828 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00828/status.svg)](https://doi.org/10.21105/joss.00828)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00828">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00828/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00828/status.svg)](https://doi.org/10.21105/joss.00828)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by pdwaggoner** [comment]
@arfon Many thanks!
