### ISSUE TITLE
[REVIEW]: pysrim: Automation, Analysis, and Plotting of SRIM Calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#829]
**Submitting author:** @costrouc (<a href="http://orcid.org/0000-0002-8734-4564">Christopher Ostrouchov</a>)
**Repository:** <a href="https://gitlab.com/costrouc/pysrim" target ="_blank">https://gitlab.com/costrouc/pysrim</a>
**Version:** v0.5.3
**Editor:** @katyhuff
**Reviewer:** @ledius
**Archive:** <a href="https://doi.org/10.5281/zenodo.1326538" target="_blank">10.5281/zenodo.1326538</a>

## Status

[![status](http://joss.theoj.org/papers/d5ff2e218ff209390eb4882822e7b382/status.svg)](http://joss.theoj.org/papers/d5ff2e218ff209390eb4882822e7b382)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d5ff2e218ff209390eb4882822e7b382"><img src="http://joss.theoj.org/papers/d5ff2e218ff209390eb4882822e7b382/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d5ff2e218ff209390eb4882822e7b382/status.svg)](http://joss.theoj.org/papers/d5ff2e218ff209390eb4882822e7b382)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/costrouc/pysrim" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ledius, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/costrouc/pysrim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.3)?
- [x] **Authorship:** Has the submitting author (@costrouc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by katyhuff** [comment]
@ledius Thanks for starting your review! It looks like you've checked the straightforward parts and functionality checks are remaining. I hope you won't hesitate to communicate with @costrouc and I here in this issue if you run into anything that is missing in this submission.

**Comment by ledius** [comment]
@costrouc I have a question about SRIM. You have included srim in your docker container. Is it allowed by the licence of it or have you asked about it from the developers?

**Comment by ledius** [comment]
@costrouc There seems to be missing actual test functionalities. There seems to be some test scripts in the tests directory, but currently they do not do anything. One can use the jupyter notebook to verify the programs does work, but it isn't the same.

**Comment by costrouc** [comment]
@ledius regarding several of the items above. 

>  Does the release version given match the GitHub release (v0.5.3)?

Gitlab's interface is a bit different than Github's. `releases` are called `tags` they are [here](https://gitlab.com/costrouc/pysrim/tags)

> If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

The [documentation](pysrim.readthedocs.io) contains [benchmarks](https://pysrim.readthedocs.io/en/latest/benchmarks.html).

**Comment by ledius** [comment]
@costrouc Only thing missing is the fix the sentence in the paper about the performance. The sentence about 50% performance increase give too optimistic picture about the situation. In many cases the performance with wine and docker quite close. You should change the sentence about the performance.

**Comment by costrouc** [comment]
@ledius [commit to fix issue](https://gitlab.com/costrouc/pysrim/commit/a2a92d191fb7a9a5743ac865a37d3750b918a41a).

> These tests indicate that the docker container may have
better performance due to rending in a virtual X frame buffer.

**Comment by costrouc** [comment]
[commit](https://gitlab.com/costrouc/pysrim/commit/303be92dd3c2e97261ebc8d01fd7ef0be633a800) to fix paper performance statement

> Along with cross platform support, a Docker container image using `pysrim` has been constructed that allows SRIM to run on a linux server without a display. [Benchmarks](https://pysrim.readthedocs.io/en/latest/benchmarks.html) show that the docker container may have better performance.

**Comment by costrouc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00829/joss.00829/10.21105.joss.00829.pdf)

**Comment by katyhuff** [comment]
To be clear (regarding the question about the SRIM license) ... it seems to me that the SRIM is merely a dependency, downloaded by docker on install, and the SRIM distribution isn't actually included in this repository. Correct? If so, there's no concern at all regarding the license. If you do include the SRIM.*.e binary file somewhere, I've missed it. 

Can you clarify @costrouc ?

**Comment by costrouc** [comment]
> To be clear (regarding the question about the SRIM license) ... it seems to me that the SRIM is merely a dependency, downloaded by docker on install, and the SRIM distribution isn't actually included in this repository. Correct?

The SRIM executable is included in one of the docker files when built `Dockerfile.srim`. See these lines. This was due to the fact that the SRIM installer (SRIM.*.e) extracts the files into a directory and requires a manual `click` of the extract button. I haven't found out how to automate a click in the GUI through xvfb. `https://gitlab.com/costrouc/pysrim/raw/master/assets/srim.2013.zip` is a zip file of what `SRIM.*.e` extracts into a folder.

```
RUN mkdir -p $SRIM_DIR && \
    cd $SRIM_DIR && \
    wget -q https://gitlab.com/costrouc/pysrim/raw/master/assets/srim.2013.zip && \
    unzip srim.2013.zip && \
    cd "$SRIM_DIR/srim" && \
    echo "1" > $SRIM_DIR/srim/TRIMAUTO
```

I have [Dockerfile.srim](https://gitlab.com/costrouc/pysrim/blob/master/Dockerfile.srim)  as a dependency of [Dockerfile.pysrim](https://gitlab.com/costrouc/pysrim/blob/master/Dockerfile.pysrim).

I am looking at how to automate the `click` or keypresses using [xdotool](https://www.semicomplete.com/projects/xdotool/) thus the SRIM executable could be just downloaded from the website.

**Comment by katyhuff** [comment]
Ok. So, you currently distribute the srim zip in your repository. Since you're distributing the file as part of your repository, you have to obey the requests of the SRIM license. I am not a lawyer, but I believe that this is easy enough to do, according to the SRIM license, as long as you distribute the copyright and permission notice along with it. 

> Permission to use, copy, modify and distribute this software for any non-commercial purpose 
> and without fee is hereby granted, provided that this copyright and permission notice appear 
> on all copies of the software.

Are the permission notice and copyright inside the zip? If so, I think you're following the rules just fine. That said, I do think a slightly better strategy would be to `wget` the actual SRIM executable *from its native location online rather than from your github repository* during docker install. This would avoid the issue entirely because you wouldn't be distributing the software. 

In any case, I think options 1,2, and 3 are all fine as long as the permission notice and copyright are distributed alongside SRIM wherever you distribute SRIM.

**Comment by costrouc** [comment]
@katyhuff I have looked at the zip file and found an obscure license is packaged at `srim/Data/LEGAL.rtf`. I have added a `srim/LICENSE` to the zip file `srim.2013.zip` to make it much clearer.  With the included text. [commit](https://gitlab.com/costrouc/pysrim/commit/61d3eaf92877150850cf8283daf630ceebb4e2d6) 

> SRIM.EXE, (C) 1984-2013, James F. Ziegler
> 
> Permission to use, copy, modify and distribute this software for any non-commercial purpose and without fee is hereby granted, provided that this copyright and permission notice appear on all copies of the software. The name of the author may not be used in any advertising or publicity pertaining to the use of the software. The author makes no warranty or representations about the suitability of the software for any purpose. It is provided "AS IS" without any express or implied warranty, including the implied warranties of merchantability, fitness for a particular purpose and non-infringement. The author shall not be liable for any direct, indirect, special or consequential damages resulting from the loss of use, data or projects, whether in an action of contract or tort, arising out of or in connection with the use or performance of this software. Downloading any software from this site is implicit acceptance of these conditions. The term "SRIM" as used to refer to topics concerning the  Stopping and Range of Ions in Matter is copyright registered in the United States Copyright Office and may not be used for commercial purposes without permission. For commercial applications, licenses may be obtained for incorporating SRIM into applications by writing to SRIM.org.

**Comment by katyhuff** [comment]
Again, I'm not a lawyer, but I think that makes you compliant.
@ledius : it seems you have checked all the review boxes. Do you have a recommendation about accepting this submission?

**Comment by ledius** [comment]
@katyhuff @costrouc    Yes, I can recommend article for publication.  The program is cleanly written and does what is promises.

**Comment by katyhuff** [comment]
Thank you for your review @ledius, I agree! 
We're ready to accept your paper @costrouc !

 At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by costrouc** [comment]
Great! Thank you @ledius and @katyhuff for the review. This has been a very pleasant experience. Here is the zenodo doi: 10.5281/zenodo.1326538

[![DOI](https://zenodo.org/badge/135215837.svg)](https://zenodo.org/badge/latestdoi/135215837)

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.1326538 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1326538" target="_blank">10.5281/zenodo.1326538</a> is the archive.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00829/joss.00829/10.21105.joss.00829.pdf)

**Comment by katyhuff** [comment]
@arfon We're ready to accept this submission, so it's over to you! The archive is  10.5281/zenodo.1326538 .

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1326538 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1326538" target="_blank">10.5281/zenodo.1326538</a> is the archive.

**Comment by arfon** [comment]
@ledius - many thanks for your review here and to @katyhuff for editing this submission ✨ 

@costrouc - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00829 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00829/status.svg)](https://doi.org/10.21105/joss.00829)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00829">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00829/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00829/status.svg)](https://doi.org/10.21105/joss.00829)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
