### ISSUE TITLE
[PRE REVIEW]: VCFPy: a Python 3 library with good support for both reading and writing VCF

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#83]
**Submitting author:** @holtgrewe (<a href="http://orcid.org/0000-0002-3051-1763">Manuel Holtgrewe</a>)
**Repository:** <a href="https://github.com/bihealth/vcfpy" target ="_blank">https://github.com/bihealth/vcfpy</a>
**Version:** v0.7.0
**Editor:** @pjotrp
**Reviewer:** @chapmanb

**What this issue is for**

Thanks for submitting your paper to JOSS @holtgrewe. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@pjotrp - would you be able to handle this submission?

**Comment by pjotrp** [comment]
@arfon sure

**Comment by gymreklab** [comment]
Might I suggest @lh3 as a potential reviewer?

**Comment by pjotrp** [comment]
I was thinking of asking the biopython members @peterjc, what do yo think? Heng we should reserve for something more performance related - that is unless @lh3 wants to have a go at JOSS?

**Comment by peterjc** [comment]
I've not used VCF so I think that might rule me out. Perhaps @chapmanb would be a better match?

**Comment by chapmanb** [comment]
Thanks for the ping, happy to help with this.

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @chapmanb as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @chapmanb

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/85. Feel free to close this issue now!
