### ISSUE TITLE
[PRE REVIEW]: 'tidynamics: A tiny package to compute the dynamics of stochastic and molecular simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#831]
**Submitting author:** @pdebuyl (<a href="http://orcid.org/0000-0002-6640-6463">Pierre de Buyl</a>)
**Repository:** <a href="https://github.com/pdebuyl-lab/tidynamics" target ="_blank">https://github.com/pdebuyl-lab/tidynamics</a>
**Version:** 0.1.2
**Editor:** @kyleniemeyer
**Reviewers:** @richardjgowers, @malramsay64

**Author instructions**

Thanks for submitting your paper to JOSS @pdebuyl. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pdebuyl if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #831 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00831/joss.00831/10.21105.joss.00831.pdf)

**Comment by pdebuyl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00831/joss.00831/10.21105.joss.00831.pdf)

**Comment by pdebuyl** [comment]
From the list of reviewers, I can suggest:
- @tacaswell 
- @richardjgowers 
- @ha0ye
- @malramsay64

If this is not asking too much, can we ask whedon to pick another citation style? See issue https://github.com/openjournals/whedon/issues/2

**Comment by pdebuyl** [comment]
@arfon Is there anything else needed from my part for the review to start?

**Comment by richardjgowers** [comment]
I’m happy to review this, or is it for the editor to pick?

**Comment by arfon** [comment]
> @arfon Is there anything else needed from my part for the review to start?

@pdebuyl - we're waiting for an editor to pick up this submission first. Sorry for the delay, there have been a bunch of submissions recently and we're a little backed up.

**Comment by pdebuyl** [comment]
@arfon thank you for the update. No worry with the delay, I understand editorial loads and the increase for JOSS just means more work from volunteers.

**Comment by kyleniemeyer** [comment]
@arfon ok, can do.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon add @richardjgowers as reviewer

**Comment by whedon** [comment]
OK, @richardjgowers is now a reviewer

**Comment by kyleniemeyer** [comment]
@fdroessler @malramsay64 @keipertk would any one of you be willing to provide a second review?

**Comment by malramsay64** [comment]
I would be happy to provide a second review.

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/877. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
OK @pdebuyl @richardjgowers @malramsay64 we will have the actual review over in issue #877
