### ISSUE TITLE
[PRE REVIEW]: diwanalr: An R data analysis package for diffusing-wave spectroscopy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#833]
**Submitting author:** @peterjwatkins (<a href="http://orcid.org/0000-0002-1290-3843">Peter Watkins</a>)
**Repository:** <a href="https://github.com/peterjwatkins/diwanalr" target ="_blank">https://github.com/peterjwatkins/diwanalr</a>
**Version:** v0.1
**Editor:** @arfon
**Reviewers:** @alexpghayes

**Author instructions**

Thanks for submitting your paper to JOSS @peterjwatkins. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@peterjwatkins if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #833 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #833 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@peterjwatkins - please make sure the YAML header in your paper matches the formatting of this example: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by peterjwatkins** [comment]
The YAML header has been reviewed and the problem rectified - incorrect indent on affiliations

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00833/joss.00833/10.21105.joss.00833.pdf)

**Comment by peterjwatkins** [comment]
The article PDF is satisfactory

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@peterjwatkins - could you take a look at this list of reviewers https://bit.ly/joss-reviewers and suggest a few potential candidates?

**Comment by peterjwatkins** [comment]
Hi Arfon,

I reviewed the list and identified the following people as potential reviewers.
Terrytangyuan, chlalanne, alexpghayes, https://github.com/semacu

Cheers Peter

**Comment by arfon** [comment]
@chlalanne @alexpghayes @semacu - would you be willing to review this submission for JOSS?

**Comment by alexpghayes** [comment]
I'd be happy to. Just FYI: this will be my first review. I'll also be away from the internet intermittently for the next two weeks.

**Comment by semacu** [comment]
Thanks for letting me know, I am afraid I am not familiar enough with diffusing-wave spectroscopy to be able to do a good job at reviewing this work.

**Comment by arfon** [comment]
> 👋 @biswapriyamisra - would you be willing to review this submission for JOSS?

Apologies @biswapriyamisra - I see you already have a pending review for us on another submission.

**Comment by alexpghayes** [comment]
Are there steps I should be taking in terms of my review at the moment? Or are we in a waiting phase?

**Comment by arfon** [comment]
> Are there steps I should be taking in terms of my review at the moment? Or are we in a waiting phase?

Let's get going on this review (given we're struggling to find a second reviewer here).

**Comment by arfon** [comment]
@whedon assign @alexpghayes as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @alexpghayes

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/947. Feel free to close this issue now!

**Comment by arfon** [comment]
@alexpghayes - please head over to #947 where the actual review will take place.
