### ISSUE TITLE
[PRE REVIEW]: UMAP: Uniform Manifold Approximation and Projection

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#835]
**Submitting author:** @lmcinnes (<a href="http://orcid.org/0000-0003-2143-6834">Leland McInnes</a>)
**Repository:** <a href="https://github.com/lmcinnes/umap" target ="_blank">https://github.com/lmcinnes/umap</a>
**Version:** v0.3.0
**Editor:** @arokem
**Reviewers:** @terrytangyuan

**Author instructions**

Thanks for submitting your paper to JOSS @lmcinnes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lmcinnes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00835/joss.00835/10.21105.joss.00835.pdf)

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the handling editor.

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
Happy to do it! I saw the scipy talk on youtube and enjoyed that. Happy to see this paper submitted for review in JOSS.

@lmcinnes: do you have suggestions for reviewers? You can see a list of potential reviewers [here](https://bit.ly/joss-reviewers).

**Comment by lmcinnes** [comment]
Glad you enjoyed the talk! That is an impressively long list of reviewers. Some potential suggestions based on that list are: glemaitre; stsievert; jsgalan; rabst; terrytangyuan, although there are a number of other clearly qualified individuals on that list, so I would also be happy with many others. I would also note that corybrunson has ideal expertise (topological data analysis in particular), but only lists R. If they were willing they would also make a great reviewer.

**Comment by arokem** [comment]
👋 @terrytangyuan : would you be willing to review this paper for JOSS?

**Comment by terrytangyuan** [comment]
Yes

**Comment by arokem** [comment]
Wonderful! Thanks a lot.

**Comment by arokem** [comment]
@whedon assign @terrytangyuan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @terrytangyuan

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/861. Feel free to close this issue now!

**Comment by arokem** [comment]
OK @terrytangyuan : head on over to #861 for the review. I'm closing this one.
