### ISSUE TITLE
[PRE REVIEW]: MPDS platform Python API client

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#837]
**Submitting author:** @blokhin (<a href="http://orcid.org/0000-0002-5333-3947">Evgeny Blokhin</a>)
**Repository:** <a href="https://github.com/mpds-io/python-api-client" target ="_blank">https://github.com/mpds-io/python-api-client</a>
**Version:** v0.0.17
**Editor:** @arfon
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @blokhin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@blokhin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00837/joss.00837/10.21105.joss.00837.pdf)

**Comment by blokhin** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by blokhin** [comment]
Please let me invite @mohammadidinani and @kxyyang as reviewers. The review should take 10-15 minutes of their time.

**Comment by arfon** [comment]
:wave: @mohammadidinani and @kxyyang - would you be willing to review this submission for JOSS.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
Hi @blokhin. I'm sorry it's taken so long to get to this submission - we've got a major backlog of submissions right now.

Unfortunately this submission isn't allowable under our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) as it falls into the 'thin API client' category.

Thanks for your interest in publishing in JOSS.
