### ISSUE TITLE
[PRE REVIEW]: countrycode: An R package to convert country names and country codes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#838]
**Submitting author:** @vincentarelbundock (<a href="http://orcid.org/0000-0003-2042-7063">Vincent Arel-Bundock</a>)
**Repository:** <a href="https://github.com/vincentarelbundock/countrycode" target ="_blank">https://github.com/vincentarelbundock/countrycode</a>
**Version:** 1.00.0
**Editor:** @leeper
**Reviewers:** @andybega

**Author instructions**

Thanks for submitting your paper to JOSS @vincentarelbundock. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vincentarelbundock if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #838 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by vincentarelbundock** [comment]
Thanks a lot for working on this. I really appreciate the time an efforts you invest in JOSS!

I added a `LICENSE.txt` file to the repo.

Also, I suspect that the PDF compilation failed because I had added this to the markdown header `CJKmainfont: STSong` (chinese characters didn't render locally on my computer without that line). I have now removed that line. Hopefully this fixes the failed to compile

**Comment by vincentarelbundock** [comment]
thanks! not sure how I could have missed this. The header in the new version mimics the example you linked to.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00838/joss.00838/10.21105.joss.00838.pdf)

**Comment by NilsEnevoldsen** [comment]
@vincentarelbundock Looks like you need to add back `CJKmainfont` if it doesn't break anything.

**Comment by vincentarelbundock** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by vincentarelbundock** [comment]
I just tried, but the chinese characters don't show up, even with `CJKmainfont`. If there's no way to render these characters, we can find another usage example to replace that one.

**Comment by leeper** [comment]
@whedon assign @andybega as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andybega

**Comment by leeper** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/848. Feel free to close this issue now!
