### ISSUE TITLE
[PRE REVIEW]: bor: An R Package for Transforming Behavioral Observation Records into Data Matrices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#839]
**Submitting author:** @davidnsousa (<a href="http://orcid.org/0000-0001-7277-6447">David Sousa</a>)
**Repository:** <a href="https://github.com/davidnsousa/bor" target ="_blank">https://github.com/davidnsousa/bor</a>
**Version:** v0.1.0
**Editor:** @karthik
**Reviewers:** @ViniciusBRodrigues

**Author instructions**

Thanks for submitting your paper to JOSS @davidnsousa. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@davidnsousa if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00839/joss.00839/10.21105.joss.00839.pdf)

**Comment by leeper** [comment]
@davidnsousa Okay, thanks for those details. The term "social behavior" is unfortunately a bit ambiguous for a multidisciplinary audience as it could also imply sociology, anthropology, etc. Can you update the paper and README to reflect your meaning, perhaps with an example? 

And yes, please add a LICENSE/LICENSE.txt/LICENSE.md file (and add it to `.Rbuildignore`).

**Comment by davidnsousa** [comment]
@leeper thank you. Added example to README and paper. Is it more clear now? Also added LICENSE (and added LICENSE to `.Rbuildignore`)

**Comment by davidnsousa** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by leeper** [comment]
Yes, that's helpful. Thanks.

**Comment by davidnsousa** [comment]
@leeper what is the next step? Thanks!

**Comment by leeper** [comment]
An editor will pick up your submission shortly. It will likely not be me as this is outside of my area.

**Comment by arfon** [comment]
:wave: @karthik - would you be willing to edit this submission for JOSS?

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by davidnsousa** [comment]
@karthik should I suggest reviewers? Thank you!

**Comment by karthik** [comment]
@davidnsousa I'm waiting on a couple of people to respond but yes more names would be welcome.

**Comment by karthik** [comment]
@whedon add @ViniciusBRodrigues as reviewer

**Comment by whedon** [comment]
OK, @ViniciusBRodrigues is now a reviewer

**Comment by ViniciusBRodrigues** [comment]
Hi,
I made an initial review and the submission looks great. It's everything good with the review criteria. One think that they need to do is complete the **Community guidelines:**

> There should be clear guidelines for third-parties wishing to:
> 
> - Contribute to the software
> - Report issues or problems with the software
> - Seek support

The minor suggestion is break the follow line in the paper:
 `## specify the set of behaviors recorded and that will be used in bset argument`

**Comment by davidnsousa** [comment]
@ViniciusBRodrigues should I do this changes now? Where do I complete the community guidelines? In the README file in github or in the paper itself? Thank you

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/909. Feel free to close this issue now!

**Comment by karthik** [comment]
@ViniciusBRodrigues Please proceed with your full review in #909. I will close this review assignment issue. 🙏

**Comment by ViniciusBRodrigues** [comment]
@davidnsousa we [will proceed here](https://github.com/openjournals/joss-reviews/issues/909)
