### ISSUE TITLE
[PRE REVIEW]: TraitDB: Web application database of phenotypic trait data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#840]
**Submitting author:** @dleehr (<a href="http://orcid.org/0000-0003-3221-9579">Dan Leehr</a>)
**Repository:** <a href="https://github.com/NESCent/TraitDB" target ="_blank">https://github.com/NESCent/TraitDB</a>
**Version:** v0.9.1
**Editor:** @pjotrp
**Reviewers:** @amoeba

**Author instructions**

Thanks for submitting your paper to JOSS @dleehr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dleehr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00840/joss.00840/10.21105.joss.00840.pdf)

**Comment by arfon** [comment]
👋@dleehr - could you take a look at this list of reviewers and identify a few potential candidates? https://bit.ly/joss-reviewers

**Comment by dleehr** [comment]
Sure - I don't see a lot of overlap between the technologies (Ruby on Rails) and the domain (evolution/trait data) in the reviewers. Considering those and the focus on dataset homogenization, I'd suggest @HadrienG, @dredamonsta1, @amoeba, @krother. Thanks!

**Comment by arfon** [comment]
> Sure - I don't see a lot of overlap between the technologies (Ruby on Rails) and the domain (evolution/trait data) in the reviewers. Considering those and the focus on dataset homogenization, I'd suggest @HadrienG, @dredamonsta1, @amoeba, @krother. Thanks!

Yes, this might be tough :smile:. I know a fair amount about Ruby on Rails and so might be able to help with some of the review aspects there (we may want to assign a different editor in that case).

@HadrienG, @dredamonsta1, @amoeba, @krother - would you be willing to review this submission for JOSS?

**Comment by krother** [comment]
I won't be available in the near future, sorry.

**Comment by dleehr** [comment]
Hey @pjotrp, would you be able to review or suggest someone that could?

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
Hi @dleehr, even better I can be the editor ;). Before I look for reviewers I would like you to work a little on the paper. It is too short now. If you check other JOSS papers you can see we like short, but it would be good to add more context, prior art, and future work. Look at one of mine, for example, http://joss.theoj.org/papers/10.21105/joss.00025.

The idea is to put your project in the best possible light so people start using it. Right? People like figures, so a screen shot will help.

**Comment by dleehr** [comment]
Thanks @pjotrp. I'll let you know after I make those changes.

**Comment by pjotrp** [comment]
How are we doing?

**Comment by pjotrp** [comment]
ping!

**Comment by dleehr** [comment]
Thanks for the reminder, @pjotrp. I haven't had the chance to revisit this yet, perhaps in the next week or so.

**Comment by pjotrp** [comment]
Ping!

**Comment by pjotrp** [comment]
@dleehr it should not be too hard. Just make clear who uses the project today and what scientific context it has. Alternatively pull the submission. It has to be worth the effort, right? Also for the reader (take pity on the reader!)

**Comment by labarba** [comment]
👋  @dleehr — We haven't heard from you in a while. Are you planning on making the improvements requested by @pjotrp soon? Give us a quick status update. Thanks!

**Comment by dleehr** [comment]
Yes I’ll get it done this week. Apologies for the delay!

**Comment by dleehr** [comment]
@pjotrp I think the submission is ready for another look. Thank you for your patience and look forward to any feedback you may have.

**Comment by pjotrp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00840/joss.00840/10.21105.joss.00840.pdf)

**Comment by pjotrp** [comment]
@amoeba would you be able to review in the coming weeks?

**Comment by amoeba** [comment]
Yes @pjotrp I can have a review in by Feb 7. Would that work?

**Comment by pjotrp** [comment]
For sure, thanks!

**Comment by pjotrp** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amoeba

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1201. Feel free to close this issue now!
