### ISSUE TITLE
[PRE REVIEW]: RISE: An R package for RISE analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#841]
**Submitting author:** @kalendar (<a href="http://orcid.org/0000-0001-6722-4744">David Wiley</a>)
**Repository:** <a href="https://github.com/lumenlearning/rise" target ="_blank">https://github.com/lumenlearning/rise</a>
**Version:** v1.0
**Editor:** @leeper
**Reviewers:** @seankross

**Author instructions**

Thanks for submitting your paper to JOSS @kalendar. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kalendar if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #841 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    539      0 --:--:-- --:--:-- --:--:--   545
Error reading bibliography ./paper.bib (line 13, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by kalendar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00841/joss.00841/10.21105.joss.00841.pdf)

**Comment by leeper** [comment]
@whedon add @seankross as reviewer

**Comment by whedon** [comment]
OK, @seankross is now a reviewer

**Comment by leeper** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/846. Feel free to close this issue now!
