### ISSUE TITLE
[PRE REVIEW]: powerbox: A Python package for creating structured fields with isotropic power spectra

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#842]
**Submitting author:** @steven-murray (<a href="http://orcid.org/0000-0003-3059-3823">Steven Murray</a>)
**Repository:** <a href="https://github.com/steven-murray/powerbox" target ="_blank">https://github.com/steven-murray/powerbox</a>
**Version:** v0.5.5
**Editor:** @arfon
**Reviewers:** @dfm

**Author instructions**

Thanks for submitting your paper to JOSS @steven-murray. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@steven-murray if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #842 with the following error: 

 Can't find any papers to compile :-(

**Comment by steven-murray** [comment]
Ahh, I forgot to hit "push", sorry. It is there now.

**Comment by steven-murray** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00842/joss.00842/10.21105.joss.00842.pdf)

**Comment by steven-murray** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00842/joss.00842/10.21105.joss.00842.pdf)

**Comment by steven-murray** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00842/joss.00842/10.21105.joss.00842.pdf)

**Comment by dfm** [comment]
@arfon: sure!

**Comment by arfon** [comment]
@whedon set @dfm as reviewer

**Comment by arfon** [comment]
@whedon add @dfm as reviewer

**Comment by whedon** [comment]
OK, @dfm is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/850. Feel free to close this issue now!

**Comment by arfon** [comment]
> @arfon: sure!

Thanks @dfm for agreeing to review this submission. You know how this goes :-) see you over in #850 for the actual review.
