### ISSUE TITLE
[PRE REVIEW]: The Glasgow Fortran Source-to-Source Compiler

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#843]
**Submitting author:** @wimvanderbauwhede (<a href="http://orcid.org/0000-0001-6768-0037">Wim Vanderbauwhede</a>)
**Repository:** <a href="https://github.com/wimvanderbauwhede/RefactorF4Acc" target ="_blank">https://github.com/wimvanderbauwhede/RefactorF4Acc</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @rouson, @rasmussn

**Author instructions**

Thanks for submitting your paper to JOSS @wimvanderbauwhede. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wimvanderbauwhede if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #843 with the following error: 

 Can't find any papers to compile :-(

**Comment by wimvanderbauwhede** [comment]
Sorry, the paper was in my devel branch, I've now added it to the master branch.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00843/joss.00843/10.21105.joss.00843.pdf)

**Comment by labarba** [comment]
@whedon assign @rouson as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rouson

**Comment by labarba** [comment]
@whedon add @rasmussn as reviewer

**Comment by whedon** [comment]
OK, @rasmussn is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/865. Feel free to close this issue now!
