### ISSUE TITLE
[PRE REVIEW]: Overlapping: a R package for Estimating Overlapping in Empirical Distributions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#844]
**Submitting author:** @masspastore (<a href="http://orcid.org/0000-0002-7922-6365">MASSIMILIANO PASTORE</a>)
**Repository:** <a href="https://github.com/masspastore/overlapping" target ="_blank">https://github.com/masspastore/overlapping</a>
**Version:** v1.5.0
**Editor:** @leeper
**Reviewers:** @soodoku, @russellpierce

**Author instructions**

Thanks for submitting your paper to JOSS @https://github.com/masspastore. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@https://github.com/masspastore if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00844/joss.00844/10.21105.joss.00844.pdf)

**Comment by masspastore** [comment]
Dear Colleagues,

Thanks for the prompt feedback. From the list that you sent me I have
identified as possible reviewers the following based on their area of
expertise

- lebebr01; lebebr01@gmail.com

- russellpierce; russell.s.pierce@gmail.com

- jkarreth; jkarreth@ursinus.edu

Best wishes,
Massimiliano Pastore

________________________________________________________
Massimiliano Pastore
Department of Developmental and Social Psychology
Room 03-019 - Phone +39.049.827.7481
Via Venezia 8 - 35131 Padova - ITALY
http://147.162.146.188/~pastore/

**Comment by masspastore** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by masspastore** [comment]
@whedon says "Failed to discover a valid open source license." Should I add a License file to overlapping repository?

**Comment by masspastore** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00844/joss.00844/10.21105.joss.00844.pdf)

**Comment by leeper** [comment]
Hi @masspastore, can you clarify: is this a method you have developed in addition to the software implementation thereof? If so, how is it related to (or distinct from) [equivalence testing](https://en.wikipedia.org/wiki/Equivalence_test)? Further, if it is a new method, you may want to expand the paper to state this explicitly as well as define some of the properties of your method in greater depth.

**Comment by masspastore** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00844/joss.00844/10.21105.joss.00844.pdf)

**Comment by masspastore** [comment]
Hi @leeper, thanks for your questions.

Actually the overlapping package presented in this paper is not a new method, but a package for easily computing an index already used in behavioral research, i.e. the overlapping index. 

For making this more evident, I added a brief description and some references in the summary of the paper. In my opinion the overlapping index is not directly related to equivalence test, but like this latter it is related in some way to effect sizes measures (e.g. Cohen's d or McGraw and Wong’s CL measure).

If you think that could be interesting, I could add a brief section with a formal description of the overlapping index.

**Comment by leeper** [comment]
Thanks, that's very helpful. I've sent you a quick PR to cleanup some of the paper metadata: https://github.com/masspastore/overlapping/pull/1

I'll regenerate the PDF once that's accepted.

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00844/joss.00844/10.21105.joss.00844.pdf)

**Comment by leeper** [comment]
@rmhogervorst Would you be interested in reviewing this for JOSS?

**Comment by masspastore** [comment]
Hi @leeper,  given that we did not receive any feedback from @RMHogervorst, would it be possible to look for another reviewer?

**Comment by arfon** [comment]
@masspastore - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by masspastore** [comment]
Thanks @arfon, I would suggest reviewers with R as their primary language, and with topic areas in statistics and social sciences. Some suggestions:

- lebebr01; lebebr01@gmail.com
- russellpierce; russell.s.pierce@gmail.com
- jkarreth; jkarreth@ursinus.edu
- briatte; francois.briatte@sciencespo.fr
- soodoku; gsood07@gmail.com

**Comment by russellpierce** [comment]
@arfon I'd be glad to help out.  Will there be a follow-up with some more tooling/guidance around submitting the review?

**Comment by arfon** [comment]
@russellpierce - definitely! The review is a checklist-based process (not visible yet here). See this for example: https://github.com/openjournals/joss-reviews/issues/974

**Comment by arfon** [comment]
Just to clarify, I won't start the review until we've got a second reviewer.

**Comment by masspastore** [comment]
Hi @arfon,  thanks for sending out the paper for review. It looks we didn't get any feedback from @jkarreth since the 25 september. Would it be possible to try with another reviewer?

**Comment by arfon** [comment]
@briatte @soodoku - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by arfon** [comment]
👍 great. Thanks @soodoku!

**Comment by arfon** [comment]
@whedon add @soodoku as reviewer

**Comment by whedon** [comment]
OK, @soodoku is now a reviewer

**Comment by arfon** [comment]
@whedon add @russellpierce as reviewer

**Comment by whedon** [comment]
OK, @russellpierce is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1023. Feel free to close this issue now!

**Comment by arfon** [comment]
@soodoku, @russellpierce - please head over to #1023 for the actual review of this package.

**Comment by briatte** [comment]
Dear all ~

The entire review process went too quick for me to accept the offer, but I would have accepted it gladly.

Please feel free to send social science-y packages my way in the future. The email address listed earlier on is correct.

All the best, ~ François
