### ISSUE TITLE
[REVIEW]: sdmbench: An R Package for Benchmarking Species Distribution Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#847]
**Submitting author:** @boyanangelov (<a href="http://orcid.org/0000-0001-5068-4234">Boyan Angelov</a>)
**Repository:** <a href="https://github.com/boyanangelov/sdmbench" target ="_blank">https://github.com/boyanangelov/sdmbench</a>
**Version:** v0.1.2
**Editor:** @karthik
**Reviewer:** @sckott, @goldingn
**Archive:** <a href="https://doi.org/10.5281/zenodo.1436376" target="_blank">10.5281/zenodo.1436376</a>

## Status

[![status](http://joss.theoj.org/papers/b0166a4b4c9cfa39761ec2a2fa71ff1c/status.svg)](http://joss.theoj.org/papers/b0166a4b4c9cfa39761ec2a2fa71ff1c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b0166a4b4c9cfa39761ec2a2fa71ff1c"><img src="http://joss.theoj.org/papers/b0166a4b4c9cfa39761ec2a2fa71ff1c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b0166a4b4c9cfa39761ec2a2fa71ff1c/status.svg)](http://joss.theoj.org/papers/b0166a4b4c9cfa39761ec2a2fa71ff1c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/boyanangelov/sdmbench" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sckott & @goldingn, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/boyanangelov/sdmbench">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.2)?
- [x] **Authorship:** Has the submitting author (@boyanangelov) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/boyanangelov/sdmbench">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.2)?
- [x] **Authorship:** Has the submitting author (@boyanangelov) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @sckott, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00847/joss.00847/10.21105.joss.00847.pdf)

**Comment by karthik** [comment]
🙏  very much @sckott, @goldingn. Please let me know if you have any questions about the review process.

**Comment by goldingn** [comment]
## Software paper review

Hi @boyanangelov, here's a short review of the software paper:

I think it reads really well. The statements of the problem that SDM solves, and the issue of benchmarking SDMs that sdmbench solves, are nice and succinct. The rest of the document does a nice job of explaining what the package provides that others don't. Great work!

### Affiliation
You don't have an affiliation listed. Was that deliberate?

### Citations

One of the citations has as the author: "Datasets, Healthcare Mimic", which looks like a bibtex malformation of the author. You should be able to change the author to: "Healthcare MIMIC Datasets" (which I'm guessing you were after) by editing the bibtex entry to have `{}`s around the author, like [this](http://timmurphy.org/2011/02/15/using-an-organisation-name-as-an-author-in-bibtex/). Though there's also [this version of the paper](https://arxiv.org/abs/1710.08531), with a human name for the author, so maybe that's worth using instead.

The citation for Wu et al. doesn't have a date. Maybe it would be worth citing [this dated arxiv paper](https://arxiv.org/abs/1703.00564) instead.

The ENMeval citation has smallcaps html tags for Maxent, that didn't render properly in the bibliography. It's probably possible to get them working in the file (e.g. [here](https://tex.stackexchange.com/questions/191401/bold-or-smallcaps-typesetting-in-bibliography)?), or you could just omit the small caps, as in the [Google Scholar bibtex version](https://scholar.googleusercontent.com/scholar.bib?q=info:gIvEknnKvx4J:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAW2ETw1iIMFXKPWMo9zgDRU1bn9ZJqFTI&scisf=4&ct=citation&cd=-1&hl=en).

**Comment by boyanangelov** [comment]
Hi @goldingn,

Thank you for the positive opinion on the paper. About the affiliation - yes, at the moment I am not formally academically affiliated. I work as a machine learning researcher in the industry but in a different field.

I pushed the citation changes to Github, I hope they are fixed now. Thanks again for taking the time to review this package!

**Comment by karthik** [comment]
@boyanangelov Can you use a former institution if any part of this work was begun while employed there? If not, you should just use your current employer as the affiliation.

**Comment by boyanangelov** [comment]
@karthik Thank you for the suggestions, I just added my current employer as the affiliation.

**Comment by sckott** [comment]
### software

- had an issue with the vignette building locally for me, and examples seemed to be not in sync with ([issue 4](https://github.com/boyanangelov/sdmbench/issues/4)) - it's not quite clear to me if the rendered vignette online is behind the v0.1.2 tagged version or ahead?
- some notes on GBIF data ([issue 5](https://github.com/boyanangelov/sdmbench/issues/5))
- For __Statement of Need__, i'd say that's partially fulfilled. the problem is clearly stated but i don't see a clear statment of who the software is targeted at
- For __Installation Instructions__, i think the github repo (Readme, vignette) could use more instructions given that it depends on Python and Java and Maxent (a separate standalone piece of software), like what to do if users are having trouble with a python dependency or virtualenv or python version, etc.
- For __Functionality documentation__, as someone not super familiar with SDM's and macine learning, i'd love more documentation in each fxns man page about what possible values are for each parameter (if there's a finite set), etc. 
- i'd pull the Code of Conduct out of the contributing file into a separate file `CODE_OF_CONDUCT.md`

### paper

- Wu et al. has a DOI: https://doi.org/10.1039/C7SC02664A
- affilitation not present for author, already pointed out by other reviewer
- author does a nice job introducing the problem and defining how this effort is different from previous art
- "The data processing pipeline relies on external functions" maybe is more accurate as "software" or "packages" cause in theory a function doesn't need to be in a package :)

**Comment by sckott** [comment]
thanks, will have a look

**Comment by goldingn** [comment]
@boyanangelov sorry for being so slow with the code review. I've been away for a few weeks, but have tomorrow afternoon blocked out to get my comments to you!

**Comment by boyanangelov** [comment]
@goldingn no worries. Take your time :)

**Comment by goldingn** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by goldingn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00847/joss.00847/10.21105.joss.00847.pdf)

**Comment by goldingn** [comment]
Wow, thanks @whedon! I for one welcome ... etc.

**Comment by boyanangelov** [comment]
Thanks @goldingn. Just pushed the fixes for the undocumented functions.

**Comment by goldingn** [comment]
Great! All ticks from me now. Good job!

**Comment by karthik** [comment]
@sckott Are you ok with signing off on this?

**Comment by sckott** [comment]
Happy with it now. I did open an issue https://github.com/boyanangelov/sdmbench/issues/9 when trying to run examples, but I imagine it's just an outdated readme issue or so

**Comment by boyanangelov** [comment]
@sckott You are right, some code that was necessary as a previous step was missing from the `README`. I just pushed the changes.

**Comment by karthik** [comment]
Thanks @boyanangelov! Can you please archive your software on Zenodo and post a DOI so we proceed with next steps? 🙏

**Comment by boyanangelov** [comment]
@karthik Great! I just made a release with all the JOSS fixes and improvements (v.0.1.3), archived in Zenodo (http://doi.org/10.5281/zenodo.1436376) and changed the DOI and version number in the paper.

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.1436376 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1436376" target="_blank">10.5281/zenodo.1436376</a> is the archive.

**Comment by karthik** [comment]
@arfon This is ready to accept (A few checklist items remain open but both reviewers have signed off).  Thanks very much @sckott and @goldingn for the review! 🙏

**Comment by goldingn** [comment]
🎉🎊🍾
Thanks for inviting me to review, and great work @boyanangelov!

**Comment by arfon** [comment]
@sckott, @goldingn - many thanks for your reviews here and to @karthik for editing this submission. 

@boyanangelov - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00847 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00847/status.svg)](https://doi.org/10.21105/joss.00847)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00847">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00847/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00847/status.svg
   :target: https://doi.org/10.21105/joss.00847
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00847/status.svg)](https://doi.org/10.21105/joss.00847)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by boyanangelov** [comment]
@sckott @goldingn Thank you for reviewing! The package improved greatly from your feedback. @karthik thank you for organizing everything, and @arfon thank you and everyone else at JOSS for this journal - I will be gladly recommending it to my colleagues!
