### ISSUE TITLE
[REVIEW]: VCFPy: a Python 3 library with good support for both reading and writing VCF

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#85]
**Submitting author:** @holtgrewe (<a href="http://orcid.org/0000-0002-3051-1763">Manuel Holtgrewe</a>)
**Repository:** <a href="https://github.com/bihealth/vcfpy" target ="_blank">https://github.com/bihealth/vcfpy</a>
**Version:** v0.7.0
**Editor:** @pjotrp
**Reviewer:** @chapmanb
**Archive:** <a href="https://dx.doi.org/10.6084/m9.figshare.3863583.v2" target="_blank">https://dx.doi.org/10.6084/m9.figshare.3863583.v2</a>

## Status

[![status](http://joss.theoj.org/papers/edae85d90ea8a49843dbaaa109e47cba/status.svg)](http://joss.theoj.org/papers/edae85d90ea8a49843dbaaa109e47cba)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/edae85d90ea8a49843dbaaa109e47cba"><img src="http://joss.theoj.org/papers/edae85d90ea8a49843dbaaa109e47cba/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/edae85d90ea8a49843dbaaa109e47cba/status.svg)](http://joss.theoj.org/papers/edae85d90ea8a49843dbaaa109e47cba)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bihealth/vcfpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bihealth/vcfpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.7.0)?
- [x] **Authorship:** Has the submitting author (@holtgrewe) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00085.pdf](https://github.com/openjournals/joss-reviews/files/508804/10.21105.joss.00085.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @chapmanb as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @chapmanb

**Comment by pjotrp** [comment]
@holtgrewe please remind us if nothing happens. @chapmanb when do have time to review?

**Comment by chapmanb** [comment]
Thank you for the work on VCFPy. This software is open source, well documented, tested and generally pleasurable to use and contribute to. It easily passes all of the JOSS requirements listed above.

After testing, I don't have any major feature suggestions as it does work nicely for reading/writing VCFs. This is a welcome contributions, as changing VCFs is tricky with the current set of Python VCF tools (PyVCF, cyvcf2, pysam.VariantFile) and only a subset of changes are possible.

I do have concerns centered around development and support. My biggest worry is that this further splinters the Python VCF parsing community, making it more difficult to support and improve the parsers. While it provides another option filling a missing set of functionality, I would have much rather seen this added to an existing Python project. The biggest issue for most people with Python-only parses like PyVCF and now VCFPy is their speed. You mention issues building off of PyVCF, but would it have been possible to contribute some of this work to a htslib-based parser like pysam's.

Thanks again for this contribution and hope this feedback is useful.

**Comment by pjotrp** [comment]
Thank you @chapmanb! Note to the author that I wrote a fast parser in Ruby by processing multi-core, see https://github.com/pjotrp/bioruby-vcf. Perhaps worth looking into.

@arfon I think we can accept the paper. Is there a @whedon command for that?

**Comment by arfon** [comment]
> @arfon I think we can accept the paper. Is there a @whedon command for that?

Not yet. I'll move it forward from here.

@holtgrewe at this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by holtgrewe** [comment]
@arfon Here it is https://dx.doi.org/10.6084/m9.figshare.3863583.v2

@chapmanb I agree that improving another library would have been better but I found working with the PyVCF and pysamtools code to be harder than implementing everything from scratch and not having to be backwards compatible.

**Comment by pjotrp** [comment]
@holtgrewe are you on to this?

**Comment by holtgrewe** [comment]
@pjotrp What do you mean? I created a DOI when submitting and this is the version that Brad reviewed. I did not get any issue from him to address during the review.

**Comment by pjotrp** [comment]
I was referring to @arfon 's 11-day old request. Glad we are moving forward.

**Comment by arfon** [comment]
@chapmanb many thanks for the review here!

@holtgrewe your paper is now accepted into JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00085 🎉 🚀 💥
