### ISSUE TITLE
[REVIEW]: powerbox: A Python package for creating structured fields with isotropic power spectra

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#850]
**Submitting author:** @steven-murray (<a href="http://orcid.org/0000-0003-3059-3823">Steven Murray</a>)
**Repository:** <a href="https://github.com/steven-murray/powerbox" target ="_blank">https://github.com/steven-murray/powerbox</a>
**Version:** v0.5.5
**Editor:** @arfon
**Reviewer:** @dfm
**Archive:** <a href="https://doi.org/10.5281/zenodo.1400822" target="_blank">10.5281/zenodo.1400822</a>

## Status

[![status](http://joss.theoj.org/papers/a62f027419958d6122f187dc4230a6e0/status.svg)](http://joss.theoj.org/papers/a62f027419958d6122f187dc4230a6e0)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a62f027419958d6122f187dc4230a6e0"><img src="http://joss.theoj.org/papers/a62f027419958d6122f187dc4230a6e0/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a62f027419958d6122f187dc4230a6e0/status.svg)](http://joss.theoj.org/papers/a62f027419958d6122f187dc4230a6e0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/steven-murray/powerbox" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dfm, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/steven-murray/powerbox">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.5)?
- [x] **Authorship:** Has the submitting author (@steven-murray) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @dfm it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00850/joss.00850/10.21105.joss.00850.pdf)

**Comment by steven-murray** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00850/joss.00850/10.21105.joss.00850.pdf)

**Comment by dfm** [comment]
I'm starting to go through this and here are a few comments as I go:

- The travis build is currently failing with some sort of coverage bug.
- I think that the quickstart tutorial could have a few more words about the details of what is meant by "power spectrum" (e.g. units, normalization, etc.) and what the properties are required by the function provided to the PowerBox class.
- The powerbox version in the [quickstart tutorial](http://powerbox.readthedocs.io/en/latest/demos/getting_started.html) is not the same as the one that it is documenting (v0.5.4 vs 0.5.5).
- The arguments to `create_discrete_sample` are not all documented. (I was not clear on what `min_at_zero` meant until I looked at the source)
- I think that it would also be useful to have a discussion of the specific numerical method (perhaps in the context of the relevant literature) somewhere in the docs. For example, how does this method compare to a Gaussian Process method that wouldn't require discretization for sampling. This might also lead to a useful discussion of how to choose N for specific use cases.
- The docs need a discussion of the dependencies and how to contribute.

**Comment by dfm** [comment]
Also:

- a few of the references in the paper are missing DOIs

**Comment by steven-murray** [comment]
> The travis build is currently failing with some sort of coverage bug.

This is fixed by https://github.com/steven-murray/powerbox/commit/59980d84365099fab31e56238dfeb4ec7d3c2cfc

**Comment by steven-murray** [comment]
> The powerbox version in the quickstart tutorial is not the same as the one that it is documenting (v0.5.4 vs 0.5.5).

Fixed in https://github.com/steven-murray/powerbox/commit/50efcded235e8d046c4ef28447e41019b017b307

**Comment by steven-murray** [comment]
> The arguments to create_discrete_sample are not all documented. (I was not clear on what min_at_zero meant until I looked at the source)

Fixed in https://github.com/steven-murray/powerbox/commit/4e7cdcb7bb36b9be4149adf9bcd4bda0a1ea4751

**Comment by steven-murray** [comment]
> The docs need a discussion of the dependencies and how to contribute.

Added some of these in https://github.com/steven-murray/powerbox/commit/e49a26037b69c9c29f4d1006be68fe06d8a36c3f. Please let me know if they are not adequate.

**Comment by steven-murray** [comment]
> I think that the quickstart tutorial could have a few more words about the details of what is meant by "power spectrum" (e.g. units, normalization, etc.) and what the properties are required by the function provided to the PowerBox class.

I've had a go of this in https://github.com/steven-murray/powerbox/commit/04e6a6de0f0c969e933affe1402b9a9ec45a833c.

The discussion is in the quickstart tutorial introduction. Please let me know if this is not quite what you were thinking and can be improved.

**Comment by steven-murray** [comment]
> a few of the references in the paper are missing DOIs

I have added DOIs to Coles 1991 and Peacock 1999 (cf https://github.com/steven-murray/powerbox/commit/086cb71443cdcfbb0ce6f08a6ac08df72898c49a). The book "Statistical Fluid Mechanics" by Monin and Yaglom does not seem to have a DOI. The article by Wolz2018 does not yet have a DOI as it is not yet accepted.

**Comment by steven-murray** [comment]
> I think that it would also be useful to have a discussion of the specific numerical method (perhaps in the context of the relevant literature) somewhere in the docs. For example, how does this method compare to a Gaussian Process method that wouldn't require discretization for sampling. This might also lead to a useful discussion of how to choose N for specific use cases.

In https://github.com/steven-murray/powerbox/commit/6078a428012ac6e8e496d8c77dae5baf680464f9 I have added a new example notebook discussing the algorithm in a little more depth. I am not quite sure how to relate this method to Gaussian Processes, so I have left this out for now. I have commented that no information on the power is available for scales less than L/N, and given a rule-of-thumb for choosing N.

Thank you for all your comments so far. I hope I have addressed them reasonably!

**Comment by dfm** [comment]
Good stuff! I'm happy with these changes and everything looks good to me now.
@arfon: I'm happy to recommend this for acceptance.
@steven-murray: congrats on the excellent software and documentation!

**Comment by arfon** [comment]
> @arfon: I'm happy to recommend this for acceptance.

:zap: thanks @dfm.

@steven-murray - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by steven-murray** [comment]
@dfm : Thanks for the smooth and thorough review process!
@arfon : Thanks, the DOI is 10.5281/zenodo.1400822 . 

I will definitely be publishing with JOSS again!

**Comment by arfon** [comment]
@dfm - many thanks for your review here ✨ 

@steven-murray - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00850 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00850/status.svg)](https://doi.org/10.21105/joss.00850)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00850">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00850/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00850/status.svg)](https://doi.org/10.21105/joss.00850)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
