### ISSUE TITLE
[PRE REVIEW]: logKDE: log-transformed kernel density estimation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#851]
**Submitting author:** @hiendn (<a href="http://orcid.org/0000-0002-9958-432X">Hien Nguyen</a>)
**Repository:** <a href="https://github.com/andrewthomasjones/logKDE" target ="_blank">https://github.com/andrewthomasjones/logKDE</a>
**Version:** v0.3.1
**Editor:** @arfon
**Reviewers:** @strengejacke

**Author instructions**

Thanks for submitting your paper to JOSS @hiendn. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@hiendn if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00851/joss.00851/10.21105.joss.00851.pdf)

**Comment by hiendn** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by hiendn** [comment]
Upon perusal of the list of reviewers, I have identified the following people to be suitable:

@amoeba
@sctyner
@AlexAxthelm
@corybrunson
@strengejacke
@kdirek

Please let me know if further suggestions are needed!

**Comment by hiendn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00851/joss.00851/10.21105.joss.00851.pdf)

**Comment by arfon** [comment]
:wave: @sctyner, @AlexAxthelm, @corybrunson - would you be willing to review this submission for JOSS?

**Comment by corybrunson** [comment]
I should not volunteer before emptying my current queue; i will make a note to check back once i have.

(By the way, i don't recall getting a notification 9 days ago from the comment by @hiendn . Should i have?)

**Comment by arfon** [comment]
> (By the way, i don't recall getting a notification 9 days ago from the comment by @hiendn . Should i have?)

I *think* so, not sure why you didn't...

**Comment by corybrunson** [comment]
@arfon then i may have overlooked it; if so, i apologize, and i'll make a point to pay closer attention. Thanks!

**Comment by arfon** [comment]
> @arfon then i may have overlooked it; if so, i apologize, and i'll make a point to pay closer attention. Thanks!

Don't worry about it at all! GitHub notifications can be hard to deal with :grin:

**Comment by strengejacke** [comment]
I'm back from vacation, if you are still looking for reviewers, I could review this submission.

**Comment by arfon** [comment]
@whedon assign @strengejacke as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
> I'm back from vacation, if you are still looking for reviewers, I could review this submission.

That would be great. Thanks @strengejacke!

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/870. Feel free to close this issue now!

**Comment by arfon** [comment]
@strengejacke @hiendn - see you both over in #870 for the actual review.
