### ISSUE TITLE
[PRE REVIEW]: Estimating statistics from multi-state models using simulation with multistateutil

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#852]
**Submitting author:** @stulacy (<a href="http://orcid.org/0000-0002-8570-7528">Stuart Lacy</a>)
**Repository:** <a href="https://github.com/stulacy/multistateutils" target ="_blank">https://github.com/stulacy/multistateutils</a>
**Version:** v1.2.0
**Editor:** @arfon
**Reviewers:** @tgerke, @jenniferthompson, @rrrlw

**Author instructions**

Thanks for submitting your paper to JOSS @stulacy. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@stulacy if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00852/joss.00852/10.21105.joss.00852.pdf)

**Comment by arfon** [comment]
:wave: @stulacy - could you take a look at the JOSS reviewers https://bit.ly/joss-reviewers and suggest a few potential candidates?

**Comment by stulacy** [comment]
Here's a few potential reviewers: @tgerke @nhejazi @acolum @borishejblum @jenniferthompson @rrrlw

**Comment by rrrlw** [comment]
I am not familiar with multi-state modeling, so I will not be able to effectively review `multistateutils` myself. However, if there is a content expert who is willing to review, I would be happy to be a second reviewer and focus on the mechanics (installation issues, code documentation, etc.). @stulacy let me know if that would be useful to you; @arfon let me know if you would prefer people familiar with multi-state modeling to review.

**Comment by stulacy** [comment]
Yes that would be fine with me. I selected a sample of reviewers who are experienced in biostatistics in the hope that at least one would be familiar with multi-state modelling.

**Comment by rrrlw** [comment]
Sounds good. If paired with a context expert, I would be happy to review the multistateutils package.

**Comment by tgerke** [comment]
I'm happy to help with the review as well. Like @jenniferthompson, I'm not an every day user of multistate models, but our joint efforts could likely fill the contextual review need (in addition to extra sets of eyes on the package itself, of course).

**Comment by arfon** [comment]
OK thanks folks. Between you all I think it should be possible to give this package a good review.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @tgerke as reviewer

**Comment by whedon** [comment]
OK, @tgerke is now a reviewer

**Comment by arfon** [comment]
@whedon add @jenniferthompson as reviewer

**Comment by whedon** [comment]
OK, @jenniferthompson is now a reviewer

**Comment by arfon** [comment]
@whedon add @rrrlw as reviewer

**Comment by whedon** [comment]
OK, @rrrlw is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/893. Feel free to close this issue now!

**Comment by arfon** [comment]
@tgerke, @jenniferthompson, @rrrlw - see you over in #893 for the actual review.
