### ISSUE TITLE
[REVIEW]: pfla: A Python Package for Dental Facial Analysis using Computer Vision and Statistical Shape Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#855]
**Submitting author:** @maxrousseau (<a href="http://orcid.org/0000-0002-1417-2511">Maxime Rousseau</a>)
**Repository:** <a href="https://github.com/maxrousseau/pfla" target ="_blank">https://github.com/maxrousseau/pfla</a>
**Version:** v0.1.4
**Editor:** @arokem
**Reviewer:** @glemaitre, @mnarayan
**Archive:** <a href="https://doi.org/10.5281/zenodo.1761769" target="_blank">10.5281/zenodo.1761769</a>

## Status

[![status](http://joss.theoj.org/papers/d86beb0eb37afd606630b2535e88c4a2/status.svg)](http://joss.theoj.org/papers/d86beb0eb37afd606630b2535e88c4a2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d86beb0eb37afd606630b2535e88c4a2"><img src="http://joss.theoj.org/papers/d86beb0eb37afd606630b2535e88c4a2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d86beb0eb37afd606630b2535e88c4a2/status.svg)](http://joss.theoj.org/papers/d86beb0eb37afd606630b2535e88c4a2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/maxrousseau/pfla" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@glemaitre & @mnarayan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/maxrousseau/pfla">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.4)?
- [x] **Authorship:** Has the submitting author (@maxrousseau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/maxrousseau/pfla">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.4)?
- [x] **Authorship:** Has the submitting author (@maxrousseau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @glemaitre, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by maxrousseau** [comment]
Is there an issue with my paper.md? The file still has not been compiled to a pdf.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00855/joss.00855/10.21105.joss.00855.pdf)

**Comment by maxrousseau** [comment]
Thank you @arfon!

**Comment by arokem** [comment]
@glemaitre : have you been able to resolve the installation issue mentioned in https://github.com/maxrousseau/pfla/issues/4? 

@mnarayan : have you had a chance to take a look at this?

**Comment by glemaitre** [comment]
I did not have time last week. I should be able to finish up the review this week. 

Sent from my phone - sorry to be brief and potential misspell.

**Comment by mnarayan** [comment]
I have looked at the repository and it still needs some work. Will finish submitting all the issues around documentation this weekend

**Comment by maxrousseau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00855/joss.00855/10.21105.joss.00855.pdf)

**Comment by glemaitre** [comment]
I open 2 issues which need to be addressed (for unit testing and file fetching).
I need to open another one but if those could be addressed first, it could be great.

**Comment by maxrousseau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by maxrousseau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00855/joss.00855/10.21105.joss.00855.pdf)

**Comment by maxrousseau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by maxrousseau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00855/joss.00855/10.21105.joss.00855.pdf)

**Comment by maxrousseau** [comment]
Hello @arokem!
Any updates on the review process?
Thank you

**Comment by arokem** [comment]
@mnarayan : I see that all your issues on the software repo are closed. Does that mean that the software now meets all the criteria in your estimation?

@glemaitre : have you had a chance to take a look whether the issues you raised were properly addressed?

**Comment by arokem** [comment]
@glemaitre, @mnarayan: any word about this review?

**Comment by maxrousseau** [comment]
Hello @arokem, @glemaitre and @mnarayan! 
Is it possible to confirm that this is still under active review?
Thank you

**Comment by mnarayan** [comment]
I am satisfied with all the corrections and have no more issues to raise.

**Comment by maxrousseau** [comment]
@mnarayan Perfect! I think you still need to finish checking the boxes of your review section (above) for the paper to be published.

**Comment by arokem** [comment]
@glemaitre : could you please confirm that you are still reviewing this? 

Is there anything left to do from your perspective?

**Comment by glemaitre** [comment]
I will have a final look in this week.

**Comment by maxrousseau** [comment]
@glemaitre: Any final thoughts?

**Comment by glemaitre** [comment]
Sorry for the delay regarding this review. Let me book some time in
the week to finalize it.
Since that you have the +1 of @mnarayan, I assume that it should be ok.

**Comment by arokem** [comment]
@whedon render pdf

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00855/joss.00855/10.21105.joss.00855.pdf)

**Comment by arokem** [comment]
OK. Since this review has gone on for a while, one reviewer has already provided a +1, and since the author has addressed the issues raised by the remaining reviewer, I'm going to call it. 

@mnarayan, @glemaitre : thanks for your reviews! 

@maxrousseau : your article is ready to be accepted by JOSS. 

To proceed, please create an archive of the accepted version of the software (e.g., using [zenodo](https://zenodo.org)) and post the DOI here for archiving.

**Comment by maxrousseau** [comment]
![image](https://user-images.githubusercontent.com/16603191/49250690-745f4700-f3ed-11e8-9d72-7581d401999e.png)

**Comment by maxrousseau** [comment]
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1710578.svg)](https://doi.org/10.5281/zenodo.1710578)

**Comment by glemaitre** [comment]
I just made a PR to correct the last glitch. Nothing important regarding the paper.

**Comment by arokem** [comment]
@maxrousseau : would you like to include @glemaitre's additional suggestion in the version that will go along with the paper? If so, please create another archived version.

**Comment by maxrousseau** [comment]
perfect just pushed the fixed docs and will accept the pull request as soon as it passes the CI

**Comment by maxrousseau** [comment]
@arokem: since the PR failed the CI I would prefer to stick with the current version for publication. I will look into @glemaitre PR as per maintenance of the package independently later on.

**Comment by maxrousseau** [comment]
@arokem: I have just merge @glemaitre 's PR, I will be creating a new archive soon.

**Comment by glemaitre** [comment]
@maxrousseau you could also make a PyPi release at the same time.

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1761769 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1761769" target="_blank">10.5281/zenodo.1761769</a> is the archive.

**Comment by arokem** [comment]
@arfon : I believe this article is ready to go!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/94

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/94, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/95
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00855](https://doi.org/10.21105/joss.00855)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by maxrousseau** [comment]
All looks good! Thank you all!

**Comment by arfon** [comment]
@glemaitre, @mnarayan - many thanks for your reviews here and to @arokem for editing this submission ✨ 

@maxrousseau - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00855/status.svg)](https://doi.org/10.21105/joss.00855)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00855">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00855/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00855/status.svg
   :target: https://doi.org/10.21105/joss.00855
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00855/status.svg)](https://doi.org/10.21105/joss.00855)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
