### ISSUE TITLE
[PRE REVIEW]: Pymer4: Connecting R and Python for Linear Mixed Modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#857]
**Submitting author:** @ejolly (<a href="http://orcid.org/0000-0002-6144-5789">Eshin Jolly</a>)
**Repository:** <a href="https://github.com/ejolly/pymer4" target ="_blank">https://github.com/ejolly/pymer4</a>
**Version:** 0.5.0
**Editor:** @cMadan
**Reviewers:** @RMHogervorst, @janfreyberg, @tomfaulkenberry

**Author instructions**

Thanks for submitting your paper to JOSS @ejolly. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ejolly if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @cMadan -the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00857/joss.00857/10.21105.joss.00857.pdf)

**Comment by ejolly** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by RMHogervorst** [comment]
I'm willing to review this paper / software package.  :+1:

**Comment by janfreyberg** [comment]
Me too!

**Comment by cMadan** [comment]
@ejolly, everything looks in order to me--I'll go ahead and start the review

@RMHogervorst, @janfreyberg, @tomfaulkenberry, great that you're all able and interested to review this submission! I'll add you all as reviewers! :)

**Comment by cMadan** [comment]
@whedon add @RMHogervorst as reviewer

**Comment by whedon** [comment]
OK, @RMHogervorst is now a reviewer

**Comment by cMadan** [comment]
@whedon add @janfreyberg as reviewer

**Comment by whedon** [comment]
OK, @janfreyberg is now a reviewer

**Comment by cMadan** [comment]
@whedon add @tomfaulkenberry as reviewer

**Comment by whedon** [comment]
OK, @tomfaulkenberry is now a reviewer

**Comment by cMadan** [comment]
@whedon start review
