### ISSUE TITLE
[PRE REVIEW]: Mordecai: Full Text Geoparsing and Event Geocoding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#86]
**Submitting author:** @ahalterman (<a href="http://orcid.org/0000-0001-9716-9555">Andrew Lee Halterman</a>)
**Repository:** <a href="https://github.com/openeventdata/mordecai" target ="_blank">https://github.com/openeventdata/mordecai</a>
**Version:** v1.1.0
**Editor:** @acabunoc
**Reviewer:** @riordan

**What this issue is for**

Thanks for submitting your paper to JOSS @ahalterman. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
@acabunoc would you be able to edit this submission for us 😁?

**Comment by acabunoc** [comment]
Can do 👍  -- I'll take a look later this week

**Comment by acabunoc** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by acabunoc** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://gist.github.com/arfon/5317c568cb32c7b917fea3c13958131d

**Comment by acabunoc** [comment]
Hey @jsta any interest in reviewing this?

Also flagging @joeyklee, @auremoser, @riordan in case any of you are interested in becoming a reviewer for JOSS (it's fun!)

**Comment by riordan** [comment]
Totally! I've been watching the mordecai project from afar from some time. I'd be down to be a reviewer.

I stumbled across this like a year ago when they were they first folks to start combining Word2Vec with Elasticsearch.

**Comment by acabunoc** [comment]
Yay thanks @riordan 🎉 !

@arfon can let you know how to get on the official reviewers list. In the meantime, you can read the [JOSS reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines) and I'll set you as reviewer here!

**Comment by acabunoc** [comment]
@whedon assign @riordan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @riordan

**Comment by acabunoc** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by acabunoc** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/91. Feel free to close this issue now!

**Comment by acabunoc** [comment]
*sigh* bananas are still gross @whedon 🍌

**Comment by auremoser** [comment]
happy to help for round 2 @acabunoc
