### ISSUE TITLE
[REVIEW]: TDAstats: R pipeline for computing persistent homology in topological data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#860]
**Submitting author:** @rrrlw (<a href="http://orcid.org/0000-0003-0503-9580">Raoul R. Wadhwa</a>)
**Repository:** <a href="https://github.com/rrrlw/TDAstats" target ="_blank">https://github.com/rrrlw/TDAstats</a>
**Version:** v0.2.0
**Editor:** @leeper
**Reviewer:** @corybrunson
**Archive:** <a href="https://doi.org/10.5281/zenodo.1341719" target="_blank">10.5281/zenodo.1341719</a>

## Status

[![status](http://joss.theoj.org/papers/0ac4998ce691c718c4518201b86ef87d/status.svg)](http://joss.theoj.org/papers/0ac4998ce691c718c4518201b86ef87d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0ac4998ce691c718c4518201b86ef87d"><img src="http://joss.theoj.org/papers/0ac4998ce691c718c4518201b86ef87d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0ac4998ce691c718c4518201b86ef87d/status.svg)](http://joss.theoj.org/papers/0ac4998ce691c718c4518201b86ef87d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rrrlw/TDAstats" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@corybrunson, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rrrlw/TDAstats">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@rrrlw) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @corybrunson it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00860/joss.00860/10.21105.joss.00860.pdf)

**Comment by leeper** [comment]
@corybrunson Review issue is here. Please follow the checklist and let me know if you have any questions.

**Comment by rrrlw** [comment]
Hi @corybrunson, thanks again for agreeing to review! Just wanted to check-in and see if there are any updates.

**Comment by corybrunson** [comment]
@rrrlw yes indeed. I'm sorry for the delay, as i had some deadlines to meet when i returned to work this week, but i intend to conduct my review today. Hopefully i won't have to leave anything for tomorrow. Thanks for checking!

**Comment by rrrlw** [comment]
All good, thank you again for reviewing!

A couple of quick notes: (1) the file at https://github.com/rrrlw/TDAstats/blob/master/JOSS-paper/reviewer-checklist.md might save you some time (adapted reviewer checklist from JOSS website); (2) `install.packages("TDAstats")` won't download the latest version of TDAstats so `devtools::install_github("rrrlw/TDAstats")` is required. Let me know if I can help in any way.

**Comment by corybrunson** [comment]
@rrrlw since you're the only author to have committed changes to the repo, could you comment on the contributions of your coauthors? I don't question the significance of their contributions; i just would like to have a point of reference for the last item under "General checks" above.

**Comment by corybrunson** [comment]
@rrrlw i've raised all of the issues that have come up for me, so, as soon as they're resolved (some are just questions), my review will be done. The package is a great help—i only recently was pointed to Ripser and made do with some ad hoc functions to interface with it through R, which i'm glad to no longer have to do. : ) Thank you for the contribution!

**Comment by rrrlw** [comment]
I added a separate line in README.md with `build_vignettes = TRUE`, and have replied to the 3 issues brought up in the TDAstats repo.

In terms of author contributions:
* Drew F.K. Williamson: software design, software testing, writing paper
* Andrew Dhawan: software design, software testing, writing paper
* Jacob G. Scott: software design, software testing, writing paper

Here, software design refers to selection of user-available functions, designing and selecting algorithms for implementation, providing expert opinion on the theoretical aspects of topological data analysis, and the aesthetic aspects of the visualizations. Software testing refers to manual testing of software features as they were implemented, for accuracy and efficiency (TDAstats and its previous iteration, ripserr). Writing the paper refers to preparation of the markdown file for submission to JOSS.

Thank you for the feedback! Did I miss responding to anything?

**Comment by rrrlw** [comment]
Question for @leeper: is it appropriate to add a short "Acknowledgments" section?

**Comment by rrrlw** [comment]
P.S. - I am really glad that you like TDAstats! I hope it saves you (and others) time/effort with TDA projects.

**Comment by corybrunson** [comment]
@rrrlw i'm satisfied! In particular, the most recent commit has resolved the diagonal line issue for me. Thanks for your thorough responses.

@leeper i have concluded my review and recommend acceptance of the current development version.

**Comment by rrrlw** [comment]
Fantastic, thank you @corybrunson!

**Comment by leeper** [comment]
Thanks, @corybrunson! Much appreciated.

**Comment by leeper** [comment]
@rrrlw The review process is now complete. To finalize your submission and accept your paper in JOSS, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. First, please merge this PR: https://github.com/rrrlw/TDAstats/pull/4
 2. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 3. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 4. Post a comment here to @leeper with the DOI for the release.

Let me know if you have any questions about the process.

**Comment by rrrlw** [comment]
Will do, @leeper. The PR has been merged, I would just like to proofread paper.md once more. I will update you in this issue once that and steps 2-4 have been completed. Thank you!

**Comment by leeper** [comment]
@rrrlw Sounds great.

**Comment by rrrlw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00860/joss.00860/10.21105.joss.00860.pdf)

**Comment by rrrlw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00860/joss.00860/10.21105.joss.00860.pdf)

**Comment by rrrlw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00860/joss.00860/10.21105.joss.00860.pdf)

**Comment by rrrlw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00860/joss.00860/10.21105.joss.00860.pdf)

**Comment by rrrlw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00860/joss.00860/10.21105.joss.00860.pdf)

**Comment by rrrlw** [comment]
@leeper, the current version of the PDF looks good, and TDAstats v0.3.2 has been archived on Zenodo with DOI: 10.5281/zenodo.1341719. Please let me know if there is anything else I need to do. Thank you!

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1341719 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1341719" target="_blank">10.5281/zenodo.1341719</a> is the archive.

**Comment by leeper** [comment]
@arfon over to you

**Comment by arfon** [comment]
@corybrunson - many thanks for your review here and to @leeper for editing this submission ✨ 

@rrrlw - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00860 ⚡️:rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00860/status.svg)](https://doi.org/10.21105/joss.00860)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00860">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00860/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00860/status.svg)](https://doi.org/10.21105/joss.00860)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by rrrlw** [comment]
Thank you so much, @corybrunson @leeper @arfon!
