### ISSUE TITLE
[REVIEW]: UMAP: Uniform Manifold Approximation and Projection

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#861]
**Submitting author:** @lmcinnes (<a href="http://orcid.org/0000-0003-2143-6834">Leland McInnes</a>)
**Repository:** <a href="https://github.com/lmcinnes/umap" target ="_blank">https://github.com/lmcinnes/umap</a>
**Version:** v0.3.0
**Editor:** @arokem
**Reviewer:** @terrytangyuan
**Archive:** <a href="https://doi.org/10.5281/zenodo.1407268" target="_blank">10.5281/zenodo.1407268</a>

## Status

[![status](http://joss.theoj.org/papers/2dd7bee9c9ae58ada787bde947592605/status.svg)](http://joss.theoj.org/papers/2dd7bee9c9ae58ada787bde947592605)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2dd7bee9c9ae58ada787bde947592605"><img src="http://joss.theoj.org/papers/2dd7bee9c9ae58ada787bde947592605/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2dd7bee9c9ae58ada787bde947592605/status.svg)](http://joss.theoj.org/papers/2dd7bee9c9ae58ada787bde947592605)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lmcinnes/umap" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@terrytangyuan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lmcinnes/umap">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3.0)?
- [x] **Authorship:** Has the submitting author (@lmcinnes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @terrytangyuan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00861/joss.00861/10.21105.joss.00861.pdf)

**Comment by lmcinnes** [comment]
Fixed a typo in paper.md. Otherwise all looks good.

**Comment by lmcinnes** [comment]
Hi @terrytangyuan , this is a friendly ping for any status updates on this -- thanks.

**Comment by terrytangyuan** [comment]
Hi @lmcinnes, thanks for your ping! It is a well-written package and has already earned 1.5k stars. 

Two things that are missing:

* References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)? You need at list one reference with DOI. 
* Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Besides, a couple suggestions:

* It might be worthwhile showing examples to use UMAP together with sklearn's pipelines, e.g. after UNMAP transformation, apply an sklearn estimator to show the differences in performance. 
* Considering providing utility functions to plot the result of UNMAP, e.g. example [here](https://github.com/lmcinnes/umap/blob/97d33f57459de796774ab2d7fcf73c639835676d/examples/plot_algorithm_comparison.py) might be too verbose and hard-to-understand for beginners.

**Comment by lmcinnes** [comment]
Hi @terrytangyuan ! Thanks for the feedback. I have added a CONTRIBUTING.md to provide some guidelines of contributions which goes into more detail than the small "Contributing" section in the README.rst. The project already has a CODE_OF_CONDUCT.md that should cover community behaviour when contributing.

The references issue is more difficult. Currently UMAP is still a pre-print, and arXiv does not provide DOIs. As that pre-print is currently the only reference this makes things difficult. Is there any wiggle room on the requirement for a DOI for a reference? I can certainly ensure the code, when it gets archived for inclusion, gets a DOI, but that isn't a reference. I would welcome any thoughts on the right approach to this.

Finally, thanks for the suggestions! Both are excellent, and I'll try to get something sorted out soon -- they will take a little more work.

**Comment by terrytangyuan** [comment]
@arokem Any suggestions regarding DOI reference? 

@lmcinnes Thanks for your quick action. I don't think you have to do it for this review but I am glad that you are keeping track of them through issues.

**Comment by arokem** [comment]
Sorry for slowness here. 

I think that the arXiv reference is sufficient. 

Looks like that was the last item here? Is anything else required before this paper can be accepted?

**Comment by terrytangyuan** [comment]
Yep just checked all the boxes. We can move forward with this paper.

**Comment by arokem** [comment]
Wonderful! Congratulations @lmcinnes! 🎉 

@lmcinnes : could you please create an archive for the accepted version (e.g., using https://zenodo.org/)? Once you have that send over the DOI as a comment on this issue, we will move ahead with the acceptance and paper.

**Comment by arokem** [comment]
@terrytangyuan : thank you for the review! 👏

**Comment by lmcinnes** [comment]
Thanks @terrytangyuan for the review, and thanks @arokem for all the help.

The DOI is: 10.5281/zenodo.1407268

It's been great working with both of you.

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1407268 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1407268" target="_blank">10.5281/zenodo.1407268</a> is the archive.

**Comment by arokem** [comment]
@arfon : I believe this paper is ready to be published. 

Nice work everyone! 🚀

**Comment by arfon** [comment]
@terrytangyuan - many thanks for your review here and to @arokem for editing this submission ✨ 

@lmcinnes - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00861 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00861/status.svg)](https://doi.org/10.21105/joss.00861)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00861">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00861/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00861/status.svg)](https://doi.org/10.21105/joss.00861)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
