### ISSUE TITLE
[PRE REVIEW]: Yellowbrick: Visualizing the Scikit-Learn Model Selection Process

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#864]
**Submitting author:** @bbengfort (<a href="http://orcid.org/0000-0003-0660-7682">Benjamin Bengfort</a>)
**Repository:** <a href="https://github.com/DistrictDataLabs/yellowbrick" target ="_blank">https://github.com/DistrictDataLabs/yellowbrick</a>
**Version:** v0.8
**Editor:** @arfon
**Reviewers:** @mnarayan

**Author instructions**

Thanks for submitting your paper to JOSS @bbengfort. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bbengfort if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #864 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0     76      0 --:--:-- --:--:-- --:--:--    76
Error reading bibliography ./paper.bib (line 79, column 3):
unexpected "n"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@jakevdp - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@bbengfort - looks like there's some issues with your `paper.bib` file. Can you take a look at fixing it up?

You can test your changes with:

```
@whedon generate pdf
```

**Comment by bbengfort** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00864/joss.00864/10.21105.joss.00864.pdf)

**Comment by bbengfort** [comment]
The proof looks good, there are a couple changes that I think might tighten this up:

1. Change title to "Yellowbrick: Visualizing the Model Selection Process" to get the title on one line. 
2. Instead of 5 separate figures, I can generate one big figure, unless there is a way to control placement in a Markdown file like in a TeX file. 

Looking forward to your review!

**Comment by rebeccabilbro** [comment]
Yes, @jakevdp - looking forward to your feedback!

**Comment by arfon** [comment]
@bbengfort - could you take a look at this list of potential reviewers and identify a few suitable people? https://bit.ly/joss-reviewers

**Comment by bbengfort** [comment]
@arfon after a quick Python script that scored reviewers based on topics, here's what I've come up with:

1. tacaswell
2. mlgill
3. jkahn
4. jochym
5. jankatins
6. arokem
7. desilinguist

**Comment by arfon** [comment]
@mlgill @jankatins - would you be willing to review this submission for JOSS?

**Comment by jankatins** [comment]
This looks very interesting! Unfortunately, I'm currently out due to private commitments, sorry!

**Comment by mlgill** [comment]
@arfon Unfortunately I'm not able to to devote the necessary time to this right now. 

Could you let me know how to remove my name from the volunteer list? My work demands have unfortunately shifted dramatically at the moment.

**Comment by arfon** [comment]
> Could you let me know how to remove my name from the volunteer list? My work demands have unfortunately shifted dramatically at the moment.

Sure thing. I've removed you from the list.

**Comment by arfon** [comment]
@mnarayan @tianxzhu @ionlights would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by mnarayan** [comment]
I am happy to review this.

**Comment by arfon** [comment]
> I am happy to review this.

Wonderful, thanks @mnarayan. I'll go ahead and set up the review now.

**Comment by arfon** [comment]
@whedon add @mnarayan as reviewer

**Comment by whedon** [comment]
OK, @mnarayan is now a reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1075. Feel free to close this issue now!
