### ISSUE TITLE
[REVIEW]: The Glasgow Fortran Source-to-Source Compiler

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#865]
**Submitting author:** @wimvanderbauwhede (<a href="http://orcid.org/0000-0001-6768-0037">Wim Vanderbauwhede</a>)
**Repository:** <a href="https://github.com/wimvanderbauwhede/RefactorF4Acc" target ="_blank">https://github.com/wimvanderbauwhede/RefactorF4Acc</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @rouson, @rasmussn
**Archive:** <a href="https://doi.org/10.5281/zenodo.2222337" target="_blank">10.5281/zenodo.2222337</a>

## Status

[![status](http://joss.theoj.org/papers/5ced707dc2be213ad7ee02291e2c6e3c/status.svg)](http://joss.theoj.org/papers/5ced707dc2be213ad7ee02291e2c6e3c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5ced707dc2be213ad7ee02291e2c6e3c"><img src="http://joss.theoj.org/papers/5ced707dc2be213ad7ee02291e2c6e3c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5ced707dc2be213ad7ee02291e2c6e3c/status.svg)](http://joss.theoj.org/papers/5ced707dc2be213ad7ee02291e2c6e3c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/wimvanderbauwhede/RefactorF4Acc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rouson & @rasmussn, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wimvanderbauwhede/RefactorF4Acc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@wimvanderbauwhede) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wimvanderbauwhede/RefactorF4Acc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@wimvanderbauwhede) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @rouson, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00865/joss.00865/10.21105.joss.00865.pdf)

**Comment by wimvanderbauwhede** [comment]
OK, I have checked the proof and it looks fine to me. 

Wim

**Comment by labarba** [comment]
👋 @rouson, @rasmussn — Thank you for agreeing to review this JOSS submission. You can find a description of the [Review Criteria](https://joss.readthedocs.io/en/latest/review_criteria.html), and more, in our documentation pages. Feel free to ask any questions here. For specific change requests, you can open issues on the submission's repository, and mention in this thread, for a link-back.

**Comment by arfon** [comment]
@rouson, @rasmussn - please remember to get to these reviews sometime soon. Many thanks!

**Comment by rouson** [comment]
[issue #2](https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/2)

**Comment by rouson** [comment]
[issue3 ](https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/3)

**Comment by rouson** [comment]
[issue #4](https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/4)

**Comment by wimvanderbauwhede** [comment]
I closed issue #3, I will close the others after I've actually added the CONTRIBUTE file and the version option, in the coming days.

**Comment by rouson** [comment]
I've added [issue 5] to better explain what I think was required for issue 2, which I don't think I have the ability to reopen.

[issue 5]: https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/5

**Comment by rouson** [comment]
I have now run the NIST test suite using the [directions] in the README.md.  I would feel more confident my verification of this software's functionality if the repository contained a much shorter example (say 50-100 lines) that demonstrates the results of the transformations this software provides.  I have created [issue 6] to request this.

[directions]: https://github.com/wimvanderbauwhede/RefactorF4Acc#to-run-the-nist-test-suite
[issue 6]: https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/6

**Comment by rouson** [comment]
I have submitted [issue 6] got request that a DOI be added to one article reference.  Once issues 5, 6, and 7 have been addressed, I expect to be able to recommend acceptance.

**Comment by labarba** [comment]
I just pinged @rasmussn by email to ask if he can move forward with this review soon. 

@wimvanderbauwhede : Let us know here when you address the issues raised by @rouson.

**Comment by wimvanderbauwhede** [comment]
I have addressed all issues but  I am waiting for a reply from @rouson on
[issue 6](https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/6).

**Comment by rouson** [comment]
I just added a comment on [issue 6](
https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/6).

**Comment by rouson** [comment]
I've also added [issue 8] that probably needs to be addressed before acceptance.  For new users, I think the documentation should contain a working version of an extremely simple example similar to one of the "Hello, world!" examples in [issue 8].

 [issue 8]: https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/8

**Comment by rouson** [comment]
I have closed [issue 6].  I expect to recommend acceptance after [issue 8] has been addressed.

[issue 6]: 
https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/6

[issue 8]: 
https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/8

**Comment by rouson** [comment]
[Pull request 10] has been submitted with severals suggested documentation improvements.   As soon as the parser fix has been pushed, I'll work on a second pull request to resolve [issue 8], which is the last issue related to this review.  The second pull request will include the GETTING_STARTED.md.

[Pull request 10]: https://github.com/wimvanderbauwhede/RefactorF4Acc/pull/10
[issue 8]: 
https://github.com/wimvanderbauwhede/RefactorF4Acc/issues/8

**Comment by wimvanderbauwhede** [comment]
I think I have now closed all remaining issues. Thank you very much for all your comments and inputs.

**Comment by labarba** [comment]
@rouson -- Do recommend acceptance, at this point?

I have contacted @rasmussn by email to ask about his review, as he's been rather quiet here. Stay tuned.

**Comment by labarba** [comment]
@whedon generated pdf

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00865/joss.00865/10.21105.joss.00865.pdf)

**Comment by wimvanderbauwhede** [comment]
I'm sorry, I don't understand what you mean by "not resolving properly". I assume this is about the DOI in [paper.bib](https://github.com/wimvanderbauwhede/RefactorF4Acc/blob/master/paper.bib)? 

The DOI is [https://doi.org/10.1016/j.compfluid.2018.06.005](https://doi.org/10.1016/j.compfluid.2018.06.005) and it resolves to [https://www.sciencedirect.com/science/article/pii/S0045793018302950?via%3Dihub](https://www.sciencedirect.com/science/article/pii/S0045793018302950?via%3Dihub) and I get the full paper.  I've tried this from home as well as from the University network. What happens when you try this?

**Comment by labarba** [comment]
The *link is broken* in the PDF.

**Comment by rouson** [comment]
@labarba I just finished checking all boxes on my reviewer checklist.  All issues that I submitted as part of this review have been resolved and closed.  I enthusiastically recommend acceptance.  Thanks for the invitation to review.  

@wimvanderbauwhede Thanks for the great contribution.  There's a reasonable chance this software will positively impact one of my current projects and I'll definitely use it in teaching, including in a [course] I'm teaching next week.

[course]: http://writing-fortran-2018-today.eventbrite.com

**Comment by wimvanderbauwhede** [comment]
OK, I changed the DOI in paper.bib, I hope it works now.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00865/joss.00865/10.21105.joss.00865.pdf)

**Comment by labarba** [comment]
The DOI link works now!

I've pinged @rasmussn by email again. I hope we can get this finished in the next few days.

**Comment by labarba** [comment]
I've emailed @rasmussn one last time. If he is unresponsive or unable to complete his review in the next week, I will make an executive decision and accept on the basis of @rouson's recommendation.

**Comment by labarba** [comment]
Hi everyone — Given that I have not received a reply from @rasmussn on several emails requesting his update on this review, I am hereby making an executive decision to accept this submission on the basis of the thorough and helpful review by @rouson.

**Comment by labarba** [comment]
@wimvanderbauwhede Please now make a deposit of your submission in an archival-quality service (e.g., Zenodo), and report here the archive DOI. Thanks!

**Comment by wimvanderbauwhede** [comment]
Thanks a lot! I've released the latest tagged version (V1.1.1) and archived it on Zenodo. The DOI is 

10.5281/zenodo.2222337

**Comment by labarba** [comment]
You will need to manually fix the author list in the Zenodo archive.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2222337 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2222337" target="_blank">10.5281/zenodo.2222337</a> is the archive.

**Comment by labarba** [comment]
In addition to the authors, the title might need manual editing, too. Zenodo just grabs its metadata from the repo.

**Comment by wimvanderbauwhede** [comment]
Thanks, I didn't realise that. Title and author is now as in the JOSS paper.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/117

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/117, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/118
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00865](https://doi.org/10.21105/joss.00865)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by wimvanderbauwhede** [comment]
OK, I did 0., 1. and 2. 
DOI resolves, have downloaded and checked the PDF. On to 3. !
Thank you very much for your patience and assistance!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00865/status.svg)](https://doi.org/10.21105/joss.00865)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00865">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00865/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00865/status.svg
   :target: https://doi.org/10.21105/joss.00865
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00865/status.svg)](https://doi.org/10.21105/joss.00865)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
