### ISSUE TITLE
[PRE REVIEW]: Comet Time Series (CometTS) Visualizer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#866]
**Submitting author:** @jshermeyer (<a href="http://orcid.org/0000-0002-8143-2790">Jacob Shermeyer</a>)
**Repository:** <a href="https://github.com/CosmiQ/CometTS" target ="_blank">https://github.com/CosmiQ/CometTS</a>
**Version:** v1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @rhiever, @zhampel

**Author instructions**

Thanks for submitting your paper to JOSS @jshermeyer. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jshermeyer if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #866 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    138      0 --:--:-- --:--:-- --:--:--   139
pandoc-citeproc: reference Holden:2015 not found
pandoc: /ExamplePlots/Workflow.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #866 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    217      0 --:--:-- --:--:-- --:--:--   218
pandoc-citeproc: reference Holden:2015 not found
pandoc: /ExamplePlots/Workflow.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by Kevin-Mattheus-Moerman** [comment]
@jshermeyer before we proceed, can you help address the issue with you paper. It seems it cannot find the references to `Holden:2015`. Can you check this?

**Comment by Kevin-Mattheus-Moerman** [comment]
:point_up: @jshermeyer can you check that paper reference to help compile your paper?

**Comment by jshermeyer** [comment]
Apologies, have been traveling. Will address this next week. Thanks for the reminder!

-Jake

**Comment by jshermeyer** [comment]
@whedon @Kevin-Mattheus-Moerman Appears I had the wrong year cited in the text, changed from 2015 to 2017 as I have it in the references.  Let me know if this fixes the problem.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #866 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0     54      0 --:--:-- --:--:-- --:--:--    54
pandoc: /ExamplePlots/Workflow.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by Kevin-Mattheus-Moerman** [comment]
@jshermeyer you can also do '@whedon generate pdf'

**Comment by jshermeyer** [comment]
@arfon Thanks, did just that, will try again

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00866/joss.00866/10.21105.joss.00866.pdf)

**Comment by jshermeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00866/joss.00866/10.21105.joss.00866.pdf)

**Comment by jshermeyer** [comment]
@arfon @Kevin-Mattheus-Moerman Thanks both, proof looks good to me.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @rhiever as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rhiever

**Comment by Kevin-Mattheus-Moerman** [comment]
@almarklein is this submission of interest to you?

**Comment by Kevin-Mattheus-Moerman** [comment]
@jshermeyer are you able to help suggest more reviewers?

**Comment by jshermeyer** [comment]
@Kevin-Mattheus-Moerman Is there a listing of persons that you would recommend? Or is this just anyone from an academic/research community?

**Comment by Kevin-Mattheus-Moerman** [comment]
@jshermeyer we can invite anybody from the academic research community.

**Comment by Kevin-Mattheus-Moerman** [comment]
@campagnola would you be interested in reviewing this submission for [JOSS](http://joss.theoj.org/)?

**Comment by danielskatz** [comment]
👋 @chrismattman - would you be interested, or possibly able to provide @Kevin-Mattheus-Moerman with suggestions for reviewers in NASA?

**Comment by danielskatz** [comment]
👋 @chrismattmann - would you be interested, or possibly able to provide @Kevin-Mattheus-Moerman with suggestions for reviewers in NASA?

**Comment by Kevin-Mattheus-Moerman** [comment]
@zhampel @jgrss @slandersson @mmann1123 @avanetten would you be interested in reviewing this submission for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/review_criteria.html) (which takes place on GitHub) focuses largely on [the software](https://github.com/CosmiQ/CometTS) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.00866/joss.00866/10.21105.joss.00866.pdf). 
Let me know if you have questions.

**Comment by zhampel** [comment]
@Kevin-Mattheus-Moerman Yes, I'd be happy to review the CometTS submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @zhampel as reviewer

**Comment by whedon** [comment]
OK, @zhampel is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
To avoid further delay in processing this submission I'll now start review. I do welcome additional reviewers if any are found, I'll add them on the review issue itself. Thanks all. Let's get started.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1047. Feel free to close this issue now!

**Comment by dmittman** [comment]
Fascinating.

@whedon add @dmittman as a  reviewer

**Comment by dmittman** [comment]
@whedon add @dmittman as reviewer

**Comment by whedon** [comment]
I'm sorry @dmittman, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by dmittman** [comment]
Fascinating. We need a @whedon at JPL.

**Comment by danielskatz** [comment]
Hi @dmittman - fancy meeting you here...

In any event, this was the pre-review issue to find reviewers, @Kevin-Mattheus-Moerman is the editor, and he should add you to the actual review issue: #1047

**Comment by arfon** [comment]
> In any event, this was the pre-review issue to find reviewers, @Kevin-Mattheus-Moerman is the editor, and he should add you to the actual review issue: #1047

Closing this as the review is moving forward in #1047
