### ISSUE TITLE
[PRE REVIEW]: js-emass: A flexible JavaScript implementation of the emass algorithm

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#867]
**Submitting author:** @emptyport (<a href="http://orcid.org/0000-0002-1148-6603">Michael Porter</a>)
**Repository:** <a href="https://github.com/emptyport/js-emass" target ="_blank">https://github.com/emptyport/js-emass</a>
**Version:** 1.2.4
**Editor:** @arfon
**Reviewers:** @bovee

**Author instructions**

Thanks for submitting your paper to JOSS @emptyport. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@emptyport if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00867/joss.00867/10.21105.joss.00867.pdf)

**Comment by emptyport** [comment]
I looked through the list and @bovee seems like a good reviewer for this paper

**Comment by emptyport** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by bovee** [comment]
Looks interesting. I'd be happy to review.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by whedon** [comment]
OK, the reviewer is @bovee

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/869. Feel free to close this issue now!

**Comment by arfon** [comment]
Thanks for agreeing to review this submission @bovee - see you over in #869 for the actual review.
