### ISSUE TITLE
[REVIEW]: Correlation Trait Loci (CTL) mapping: phenotype network inference subject to genotype

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#87]
**Submitting author:** @DannyArends (<a href="http://orcid.org/0000-0001-8738-0162">Danny Arends</a>)
**Repository:** <a href="https://github.com/DannyArends/CTLmapping" target ="_blank">https://github.com/DannyArends/CTLmapping</a>
**Version:** v1.0.0-joss-2
**Editor:** @biorelated
**Reviewer:** @byandell
**Archive:** <a href="https://dx.doi.org/10.5281/zenodo.163510" target="_blank">https://dx.doi.org/10.5281/zenodo.163510</a>

## Status

[![status](http://joss.theoj.org/papers/440382846e5184c5ad875f8a53cf266d/status.svg)](http://joss.theoj.org/papers/440382846e5184c5ad875f8a53cf266d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/440382846e5184c5ad875f8a53cf266d"><img src="http://joss.theoj.org/papers/440382846e5184c5ad875f8a53cf266d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/440382846e5184c5ad875f8a53cf266d/status.svg)](http://joss.theoj.org/papers/440382846e5184c5ad875f8a53cf266d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/DannyArends/CTLmapping" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DannyArends/CTLmapping">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0-joss-1)?
- [x] **Authorship:** Has the submitting author (@DannyArends) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00087.pdf](https://github.com/openjournals/joss-reviews/files/517691/10.21105.joss.00087.pdf)
 
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@byandell this is where you should report back on your review. Please update the checklist on this issue as you proceed.

**Comment by pjotrp** [comment]
The paper URL is not complete. You can find it at https://github.com/DannyArends/CTLmapping/blob/master/doc/joss/2016/paper.md

**Comment by arfon** [comment]
> The paper URL is not complete. You can find it at https://github.com/DannyArends/CTLmapping/blob/master/doc/joss/2016/paper.md

Thanks for the reminder @pjotrp. @byandell - I've compiled the paper for your review: [10.21105.joss.00087.pdf](https://github.com/openjournals/joss-reviews/files/517691/10.21105.joss.00087.pdf)

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @byandell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @byandell

**Comment by byandell** [comment]
I updated the comment by arfon, which said I should put my review there. I took this literally and edited that entry to include my review. I attache below as well.
Brian


Review of Danny Arends


Would be very helpful to plot St7 against Il18r1 using plot symbols for genotype at strongest CTL signal on chr 2 at ~15Mbp. Similarly do this for Mtvr2 against C1qtnf5 on chr 19 proximal end with CTL genotype. If first case, expect to see a change in direction of association.


What is basis for "rule of thumb"? Does this involve some genome-wide correction or threshold calculation?


Here is some related work that probably should be cited.


Relate CTL to ANCOVA which is the underlying tool to determine change in correlation. Usual use of ANCOVA in QTL is to adjust for covariates in searching for QTL (see Broman and Sen 2009 book).


CTL differs fundamentally from mediation (Chick et al. Gygi 2016 doi:10.1038/nature18270) where the goal is to use covariates tied to genomic position (e.g. mRNA expression) to look at change in strength of QTL signal.


For MAGIC, please cite de Koning and McIntyre LM (2014) doi:10.1534/g3.114.013680

**Comment by pjotrp** [comment]
Thanks @byandell! We'll amend the paper to include your suggestions.

**Comment by pjotrp** [comment]
@byandell we modified the paper following your suggestions: https://github.com/DannyArends/CTLmapping/blob/master/doc/joss/2016/paper.md. @arfon as the software ticks all the boxes I believe we can accept the paper and go live.

**Comment by arfon** [comment]
@DannyArends - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by DannyArends** [comment]
@arfon I created a new release (v1.0.0-joss-2) with Zenodo, the DOI of the release is: 10.5281/zenodo.163510

@whedon set 10.5281/zenodo.163510 as archive

**Comment by byandell** [comment]
I am ok with paper as is. I would have liked to see scatterplot of variables with QTL alleles as plot symbols, but not necessary. I submitted very minor typo as issue just now. Brian

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Oct 27, 2016 at 7:07 AM -0500, "Arfon Smith" <notifications@github.com<mailto:notifications@github.com>> wrote:


@DannyArends<https://github.com/DannyArends> - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

-

**Comment by arfon** [comment]
@byandell many thanks for your review!

@DannyArends your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00087 🚀 🎉 💥
