### ISSUE TITLE
[PRE REVIEW]: Spatially-Correlated Multilevel Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#871]
**Submitting author:** @ljwolf (<a href="http://orcid.org/0000-0003-0274-599X">Levi Wolf</a>)
**Repository:** <a href="https://github.com/pysal/spvcm" target ="_blank">https://github.com/pysal/spvcm</a>
**Version:** 0.0.8
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @ljwolf. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ljwolf if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #871 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@ljwolf - please review the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) and let me know when you've prepared a paper (`paper.md`, `paper.bib`) file.

**Comment by Kevin-Mattheus-Moerman** [comment]
Still no paper files. Should this issue be closed / the submission be removed?

**Comment by ljwolf** [comment]
Sure, I'll fix and resubmit if I have time later. No problem if you want to clear stale issues.
