### ISSUE TITLE
[PRE REVIEW]: medical image visualization library in python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#872]
**Submitting author:** @raamana (<a href="http://orcid.org/0000-0003-4662-0558">Pradeep Reddy Raamana</a>)
**Repository:** <a href="https://github.com/raamana/mrivis" target ="_blank">https://github.com/raamana/mrivis</a>
**Version:** 0.3
**Editor:** @arokem
**Reviewers:** @miykael

**Author instructions**

Thanks for submitting your paper to JOSS @raamana. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@raamana if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #872 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    200      0 --:--:-- --:--:-- --:--:--   202
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00872.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00872/joss.00872/10.21105.joss.00872.pdf)

**Comment by arokem** [comment]
I have a question regarding the title of the article: the software is called `mrivis` and the title on the repo refers only to neuroimaging. It also seems that the file formats supported by the software are neuroimaging-specific. I wonder whether the title of the article could be made more specific to reflect this?

**Comment by raamana** [comment]
Thanks Ariel for agreeing to edit and starting the review. Appreciate it.

Yes, the docs need to improved, and I plan to fix it shortly. 

Just to clarify, yes It’s mostly tested for neuroimaging data so far, but there is absolutely nothing that’s not generic to other medical image data i.e. any type of 3D/4D data that can be read by nibabel or similar library.

**Comment by raamana** [comment]
Also, I've just updated the paper.md, is it possible to regenerate the PDF for review? cc @arfon

**Comment by arfon** [comment]
@raamana - yep, you can ask @whedon to do this for you 👇

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00872/joss.00872/10.21105.joss.00872.pdf)

**Comment by raamana** [comment]
thanks! didn't think I'd have permission. let me again with some changes:

@whedon generate pdf

**Comment by raamana** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00872/joss.00872/10.21105.joss.00872.pdf)

**Comment by miykael** [comment]
@arokem - sorry for my late reply. Yes, I'm very happy to review this!

**Comment by raamana** [comment]
Great, thanks Michael. give me a day or two to finalize some documentation.

**Comment by arokem** [comment]
@whedon assign @miykael as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @miykael

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/897. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks @miykael! Please head over to #897 for your reviewer checklist. I am closing this now.
