### ISSUE TITLE
[PRE REVIEW]: pvlib python: a python package for modeling solar energy systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#873]
**Submitting author:** @wholmgren (<a href="http://orcid.org/0000-0001-6218-9767">William F. Holmgren</a>)
**Repository:** <a href="https://github.com/pvlib/pvlib-python" target ="_blank">https://github.com/pvlib/pvlib-python</a>
**Version:** v0.5.2
**Editor:** @katyhuff
**Reviewers:** @sjpfenninger, @ecotillasanchez

**Author instructions**

Thanks for submitting your paper to JOSS @wholmgren. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wholmgren if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @katyhuff - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #873 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    349      0 --:--:-- --:--:-- --:--:--   358
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00873.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00873/joss.00873/10.21105.joss.00873.pdf)

**Comment by wholmgren** [comment]
Re reviewers... perhaps the reviewers/authors in #825 (Calliope) would be appropriate.

cc @cwhanse @mikofski

**Comment by katyhuff** [comment]
Happy to edit this one -- it looks very interesting! Thanks for your submission @wholmgren . I agree with your assessment of appropriate reviewers.

@ecotillasanchez  @mdoucet  @sjpfenninger Would you be interested in reviewing [this JOSS paper](https://github.com/openjournals/joss-papers/blob/joss.00873/joss.00873/10.21105.joss.00873.pdf)?

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by sjpfenninger** [comment]
@katyhuff I'll be happy to help review this.

**Comment by katyhuff** [comment]
@whedon assign @sjpfenninger as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sjpfenninger

**Comment by katyhuff** [comment]
@ecotillasanchez @mdoucet Would either of you be interested in reviewing [this JOSS paper](https://github.com/openjournals/joss-papers/blob/joss.00873/joss.00873/10.21105.joss.00873.pdf) ? It seems to be well within your area of expertise.  "pvlib python: a python package for modeling solar energy systems"

**Comment by ecotillasanchez** [comment]
@katyhuff I’ll be happy to review this work. I’ll get to it after the IEEE PES GM in Portland wraps up.

**Comment by katyhuff** [comment]
@whedon add @ecotillasanchez as reviewer

**Comment by whedon** [comment]
OK, @ecotillasanchez is now a reviewer

**Comment by katyhuff** [comment]
Ok -- @arokem you're off the hook!

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/884. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok! @sjpfenninger @ecotillasanchez @wholmgren, let's head over to #884 for the review.
