### ISSUE TITLE
[PRE REVIEW]: nestcheck: error analysis, diagnostic tests and plots for nested sampling calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#874]
**Submitting author:** @ejhigson (<a href="http://orcid.org/0000-0001-8383-4614">Edward Higson</a>)
**Repository:** <a href="https://github.com/ejhigson/nestcheck" target ="_blank">https://github.com/ejhigson/nestcheck</a>
**Version:** v0.1.5
**Editor:** @arfon
**Reviewers:** @ziotom78, @mattpitkin

**Author instructions**

Thanks for submitting your paper to JOSS @ejhigson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ejhigson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #874 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00874/joss.00874/10.21105.joss.00874.pdf)

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00874/joss.00874/10.21105.joss.00874.pdf)

**Comment by ejhigson** [comment]
Hi @arfon - would it be helpful if I suggested some possible reviewers? Sorry I should have done this earlier! Thanks

**Comment by arfon** [comment]
> Hi @arfon - would it be helpful if I suggested some possible reviewers? Sorry I should have done this earlier! Thanks

Yes please!

**Comment by ejhigson** [comment]
Perhaps @mattpitkin or @ziotom78 would be suitable reviewers?

**Comment by mattpitkin** [comment]
I'd be happy to do this.

**Comment by ejhigson** [comment]
Great, thanks very much!

**Comment by ziotom78** [comment]
Hi @ejhigson, I am on vacation till September 5th and have not brought my laptop with me, so I would not be able to review it before this date. If this is too late, feel free to search for another reviewer!

**Comment by ejhigson** [comment]
No problem @ziotom78 - I hope you have a nice holiday!

@arfon how many reviewers do you need? I can suggest some alternatives who may be able too look at this sooner

**Comment by arfon** [comment]
> @arfon how many reviewers do you need? I can suggest some alternatives who may be able too look at this sooner

Ideally two.

**Comment by ejhigson** [comment]
Ok cool - perhaps @nespinoza or @benjaminrose would also be suitable reviewers? Thanks very much

**Comment by nespinoza** [comment]
Hi @ejhigson; would love to but this week I'm in a conference, and next on vacation. I'll be available from September 3rd and on --- if this works for you, I could make my report for that week.

Best,

Néstor

**Comment by ejhigson** [comment]
Hi @arfon - maybe mattpitkin and one of ziotom78 and nespinoza would be a good pair of reviewers? I'm happy to wait until the latter gets back from vacation. Thanks very much!

**Comment by benjaminrose** [comment]
Sorry for the delayed response. But I am in the middle of relocating for a new job so I just don't have the time. I hope you can get this review done as quickly and smoothly as possible.

**Comment by arfon** [comment]
:wave: @ziotom78 & @mattpitkin - thanks for agreeing to review this submission! @nespinoza - thanks for volunteering too but I think we have sufficient help with this review now ✨

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @ziotom78 as reviewer

**Comment by whedon** [comment]
OK, @ziotom78 is now a reviewer

**Comment by arfon** [comment]
@whedon add @mattpitkin as review

**Comment by arfon** [comment]
@whedon add @mattpitkin as reviewer

**Comment by whedon** [comment]
OK, @mattpitkin is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/916. Feel free to close this issue now!

**Comment by arfon** [comment]
@ziotom78, @mattpitkin - thanks again for agreeing to review this submission. See you over in #916 for the actual review.
