### ISSUE TITLE
[PRE REVIEW]: Containershare: Open Source Registry to build, test, deploy with CircleCI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#875]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://github.com/vsoch/containershare" target ="_blank">https://github.com/vsoch/containershare</a>
**Version:** v.0.0.1
**Editor:** @arfon
**Reviewers:** @brainstorm

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @acabunoc - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00875/joss.00875/10.21105.joss.00875.pdf)

**Comment by brainstorm** [comment]
Happy to review this one, @arfon ;)

**Comment by arfon** [comment]
@whedon add @brainstorm as reviewer

**Comment by arfon** [comment]
@whedon set @arfon as editor

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon add @brainstorm as reviewer

**Comment by arfon** [comment]
@whedon set @arfon as editor

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/878. Feel free to close this issue now!

**Comment by arfon** [comment]
@brainstorm - many thanks for agreeing to review this submission. See you over in #878 !
