### ISSUE TITLE
[REVIEW]: 'tidynamics: A tiny package to compute the dynamics of stochastic and molecular simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#877]
**Submitting author:** @pdebuyl (<a href="http://orcid.org/0000-0002-6640-6463">Pierre de Buyl</a>)
**Repository:** <a href="https://github.com/pdebuyl-lab/tidynamics" target ="_blank">https://github.com/pdebuyl-lab/tidynamics</a>
**Version:** 1.0.0
**Editor:** @kyleniemeyer
**Reviewer:** @richardjgowers, @malramsay64
**Archive:** <a href="https://doi.org/10.5281/zenodo.1404296" target="_blank">10.5281/zenodo.1404296</a>

## Status

[![status](http://joss.theoj.org/papers/c4784e48e7514c207d95f440c2a07874/status.svg)](http://joss.theoj.org/papers/c4784e48e7514c207d95f440c2a07874)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c4784e48e7514c207d95f440c2a07874"><img src="http://joss.theoj.org/papers/c4784e48e7514c207d95f440c2a07874/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c4784e48e7514c207d95f440c2a07874/status.svg)](http://joss.theoj.org/papers/c4784e48e7514c207d95f440c2a07874)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pdebuyl-lab/tidynamics" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@richardjgowers & @malramsay64, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pdebuyl-lab/tidynamics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.2)?
- [x] **Authorship:** Has the submitting author (@pdebuyl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pdebuyl-lab/tidynamics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.2)?
- [x] **Authorship:** Has the submitting author (@pdebuyl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @richardjgowers, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00877/joss.00877/10.21105.joss.00877.pdf)

**Comment by kyleniemeyer** [comment]
@pdebuyl @richardjgowers @malramsay64 👋

**Comment by malramsay64** [comment]
@kyleniemeyer I can see that @pdebuyl is preparing for release 0.1.2, which I assume will be in concert with the completion of the review, yet the version is not technically 0.1.2 being a pre-release version (0.1.2.dev5). Is a 0.1.2 release required for review? Also does there have to be a GitHub release (tagged commit) for the version being reviewed?

**Comment by kyleniemeyer** [comment]
@malramsay64 we don't have a requirement on this—I think it's fine to hold the 0.1.2 release pending for any changes that come about due to the JOSS review. I will expect that version to be released and archived when the submission in accepted, though

**Comment by malramsay64** [comment]
@pdebuyl I have mostly finished my review, with mostly the assessment of functionality remaining. I have raised a number of issues in the repository, with issues marked [review] specifically not meeting review criteria. These are 
- pdebuyl-lab/tidynamics#8
- pdebuyl-lab/tidynamics#9
- pdebuyl-lab/tidynamics#10

The remaining issues I have raised are more suggestions. 

Some general notes. 
- I like the concept of the library and would like to use it for my research, however I don't find the documentation particularly helpful for understanding how to use the software.
- There appears to be a lack of consistency throughout the package.
- With a stated goal of being a reference implementation I would expect more comprehensive documentation.

I'm happy to discuss/help with anything I have raised.

**Comment by richardjgowers** [comment]
@pdebuyl : @malramsay64 has made good points about docs.  I think the tests should also be a bit more comprehensive, ideally some realistic data but at least some seeded random walks to act as regression tests.

**Comment by pdebuyl** [comment]
Thanks all for the feedback. I have started to work on the issues.

**Comment by pdebuyl** [comment]
Hi all,

While waiting for the end of the review, and after improving the documentation, I thought of providing an example notebook that one can launch on mybinder.

See https://github.com/pdebuyl-lab/tidynamics/tree/binder_notebook

It is in a separate branch for now, but as it is a coming addition to the software I wanted to notify the review page.

Also, for a first release "0.1.2" is not a nice number and I plan to release 0.2.0 when the review is over and I have to archive the code to zenodo.

Regards,

Pierre

**Comment by richardjgowers** [comment]
@kyleniemeyer ok I'm happy to accept this.  @pdebuyl if you're happy that the API won't change you can just call it 1.0.0 according to [semantic versioning](https://semver.org)

**Comment by pdebuyl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00877/joss.00877/10.21105.joss.00877.pdf)

**Comment by pdebuyl** [comment]
@kyleniemeyer I believe I addressed all reviewers' feedback.

**Comment by malramsay64** [comment]
I am also happy to accept this. @pdebuyl I also agree with @richardjgowers on version 1.0.0.

**Comment by pdebuyl** [comment]
Ok, I'll release as 1.0.0 on zenodo.

@arfon may I include the DOI badge and the corresponding citation already in 1.0.0 (so that the released version is "self-contained")? I plan to add a `CITATION` file and the corresponding information in the README, `doc/index.rst` and `tidynamics/__init__.py` file.

From my understanding the doi is reserved already and visible in the pdf builds from whedon, is that the good one?

**Comment by arfon** [comment]
> From my understanding the doi is reserved already and visible in the pdf builds from whedon, is that the good one?

@pdebuyl yet that's fine.  The DOI for the paper will be https://doi.org/10.21105/joss.00877

**Comment by pdebuyl** [comment]
tidynamics 1.0.0 is archived on zenodo as

https://doi.org/10.5281/zenodo.1401185

**Comment by kyleniemeyer** [comment]
Hi @pdebuyl @arfon, I just need to copy-edit the paper first, then we will be ready to accept.

**Comment by kyleniemeyer** [comment]
A few comments on the paper:

- The second sentence is a little confusing due to the comma use: "The autocorrelation, the correlation between two time-series, the mean-square displacement, and the cross-displacement (for off-diagonal realisations of Brownian motion), allow...". Perhaps something like this would be more clear? "The autocorrelation (the correlation between two time-series), the mean-square displacement, and the cross-displacement (for off-diagonal realisations of Brownian motion) allow the quantitative measure of relaxation and transport coefficients from numerical trajectories."
- Third paragraph: "Python 2.7, 3.5 and 3.6" -> "Python 2.7, 3.5, and 3.6"
- Fourth paragraph: is the sentence "We show the actual CPU time and compare it favourably to the expected scaling in the example Scaling behaviour." meant to refer to Figure 3?
- Sixth paragraph: "The Fast Correlation Algorithm as applied to mean-square displacements was proposed in (G. R. Kneller et al. 1995)" -> "The Fast Correlation Algorithm as applied to mean-square displacements was proposed by Kneller et al. (1995)". You should be able to do this by replacing `[@nmoldyn_1995]` with just `@nmoldyn_1995`.
- Seventh paragraph: "The benefits of using tidynamics originate in the implementation of the suitable definitions for the study of dynamical systems, in a good performance, and in its ease of installation." -> "The benefits of using tidynamics originate in the implementation of the suitable definitions for the study of dynamical systems, good performance, and its ease of installation."
- In "Examples", please capitalize "figures". Also, the legends in Figures 1 and 3 overlap with the content of the plots. Could you regenerate with them a bit bigger to avoid this?
- Throughout, some of the inline references have authors initials in them—I'm not sure how this happened, but it should just be their last name. Also, https://doi.org/10.1109/MCSE.2007.58 might be a better reference for NumPy

Please let me know when you are finished making these changes.

**Comment by pdebuyl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00877/joss.00877/10.21105.joss.00877.pdf)

**Comment by kyleniemeyer** [comment]
@pdebuyl looks good, thanks! Please now archive this latest version with the updated paper (1.0.1, maybe?) and provide the DOI, and we'll be done.

**Comment by pdebuyl** [comment]
Hi @kyleniemeyer , thanks for the editing. The doi for 1.0.1 is https://doi.org/10.5281/zenodo.1404296

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.1404296 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1404296" target="_blank">10.5281/zenodo.1404296</a> is the archive.

**Comment by pdebuyl** [comment]
Thanks @kyleniemeyer @malramsay64 @richardjgowers @arfon for editing and reviewing!

**Comment by arfon** [comment]
@richardjgowers, @malramsay64 - many thanks for your reviews here and to @kyleniemeyer for editing this submission ✨ 

@pdebuyl - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00877 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00877/status.svg)](https://doi.org/10.21105/joss.00877)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00877">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00877/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00877/status.svg)](https://doi.org/10.21105/joss.00877)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
