### ISSUE TITLE
[PRE REVIEW]: Pyessence - Generalised Coupled Quintessence Linear Perturbation Python Code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#88]
**Submitting author:** @leithes (<a href="http://orcid.org/0000-0001-9593-6757">Alexander Leithes</a>)
**Repository:** <a href="https://bitbucket.org/pyessence/pyessence" target ="_blank">https://bitbucket.org/pyessence/pyessence</a>
**Version:** v2.0.1
**Editor:** @jakevdp
**Reviewer:** @joergdietrich

**What this issue is for**

Thanks for submitting your paper to JOSS @leithes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@kyleniemeyer - this looks like it's up your street. Do you think you could edit this submission for JOSS?

**Comment by kyleniemeyer** [comment]
Sure @arfon I will cover this one.

**Comment by kyleniemeyer** [comment]
Hey @arfon after a bit more research it looks like this may be more up @jakevdp's alley, since the application seems to be in astronomy/astrophysical research. I can handle if needed, but he might have more insight...

**Comment by arfon** [comment]
@jakevdp - can you take this one? 😁 🙏

**Comment by jakevdp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by jakevdp** [comment]
@whedon assign @jakevdp as editor

**Comment by whedon** [comment]
OK, the editor is @jakevdp

**Comment by jakevdp** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by jakevdp** [comment]
@whedon assign @joergdietrich as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @joergdietrich

**Comment by jakevdp** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by jakevdp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/108. Feel free to close this issue now!
