### ISSUE TITLE
[REVIEW]: pvlib python: a python package for modeling solar energy systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#884]
**Submitting author:** @wholmgren (<a href="http://orcid.org/0000-0001-6218-9767">William F. Holmgren</a>)
**Repository:** <a href="https://github.com/pvlib/pvlib-python" target ="_blank">https://github.com/pvlib/pvlib-python</a>
**Version:** v0.5.2
**Editor:** @katyhuff
**Reviewer:** @sjpfenninger, @ecotillasanchez
**Archive:** <a href="https://doi.org/10.5281/zenodo.1411511" target="_blank">10.5281/zenodo.1411511</a>

## Status

[![status](http://joss.theoj.org/papers/41187535cad22dd4b076c89b72f874b1/status.svg)](http://joss.theoj.org/papers/41187535cad22dd4b076c89b72f874b1)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/41187535cad22dd4b076c89b72f874b1"><img src="http://joss.theoj.org/papers/41187535cad22dd4b076c89b72f874b1/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/41187535cad22dd4b076c89b72f874b1/status.svg)](http://joss.theoj.org/papers/41187535cad22dd4b076c89b72f874b1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pvlib/pvlib-python" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sjpfenninger & @ecotillasanchez, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pvlib/pvlib-python">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.2)?
- [x] **Authorship:** Has the submitting author (@wholmgren) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pvlib/pvlib-python">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.2)?
- [x] **Authorship:** Has the submitting author (@wholmgren) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @sjpfenninger, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00884/joss.00884/10.21105.joss.00884.pdf)

**Comment by sjpfenninger** [comment]
It was a pleasure to review this submission. The software is well structured and the documentation is  extensive and easy to follow. Just one (minor) item not checked on the checklist: references `Holmgren2017` and `Holmgren2018` don't have a DOI - can that be remedied, or could they be linked to a PDF instead (@wholmgren)?

Some other minor comments:

* You could set the repository's website at the very top of the GitHub page to the documentation, making it quicker to get there from the repository
* Installation docs could explicitly list requirements (right now, they do so only  implicitly in the `conda create` command under "Install as an editable library", as far as I can see)
* `tracking.LocalizedSingleAxisTracker` has a somewhat mysterious docstring
* A conda-forge package would be highly appreciated :smile:

**Comment by arfon** [comment]
@ecotillasanchez - please remember to get to this review sometime soon. Thanks!

**Comment by ecotillasanchez** [comment]
Excellent work in this contribution, a pleasure to review and test. One can easily see the comprehensive functionality and the seamless support for a variety of external sources of data. This is very valuable for benchmarking. Besides the comments raised above, I will only add one other suggestion. In the documentation, the main functionality could be structured around a tutorial or use cases, so that the user has a clear flow of what to read first and what to read next. For example, _ModelChain_ shows up nearly on top on the left panel, and then it becomes a submenu within _API reference_.

**Comment by wholmgren** [comment]
Thanks @sjpfenninger and @ecotillasanchez for your reviews!

> You could set the repository's website at the very top of the GitHub page to the documentation, making it quicker to get there from the repository

Good idea. Done.

> Installation docs could explicitly list requirements (right now, they do so only implicitly in the conda create command under "Install as an editable library", as far as I can see)

We expanded the [Compatibility](https://pvlib-python.readthedocs.io/en/latest/installation.html#compatibility) section to address this. It looks likely that we'll add a requirements.txt file to the package in the near future, so I'd like to defer a larger Installation docs reorganization until then. https://github.com/pvlib/pvlib-python/pull/533

> tracking.LocalizedSingleAxisTracker has a somewhat mysterious docstring

Fixed in https://github.com/pvlib/pvlib-python/pull/534

> A conda-forge package would be highly appreciated 😄

We've actually had one for the last ~2 years or so, but I neglected to add it to the installation documentation until now. [See here](https://pvlib-python.readthedocs.io/en/latest/installation.html#install-standard-release). https://github.com/pvlib/pvlib-python/pull/533

> the main functionality could be structured around a tutorial or use cases

@ecotillasanchez would moving [Modeling paradigms](https://pvlib-python.readthedocs.io/en/latest/package_overview.html#modeling-paradigms) out of Package Overview and into its own top-level documentation address this concern? Perhaps we could rename it something like "Intro examples" to make it more clear.

> For example, ModelChain shows up nearly on top on the left panel, and then it becomes a submenu within API reference.

In this case, the [left panel ModelChain documentation](https://pvlib-python.readthedocs.io/en/latest/modelchain.html) provides a comprehensive discussion of the feature, while the [submenu within API reference](https://pvlib-python.readthedocs.io/en/latest/api.html#modelchain) provides, well, API reference. The same situation applies to "Clear sky" and "Forecasting". 

To do:

- [ ] "references Holmgren2017 and Holmgren2018 don't have a DOI - can that be remedied, or could they be linked to a PDF instead"

cc @mikofski @cwhanse

**Comment by wholmgren** [comment]
@sjpfenninger @ecotillasanchez I believe we've addressed all of your helpful comments. Let us know if we're missing anything. Thanks!

**Comment by katyhuff** [comment]
Thanks for quickly handling all of the reviewer comments @wholmgren ! It looks to me like the comments from @sjpfenninger and @ecotillasanchez have been handled. @sjpfenninger and @ecotillasanchez can you confirm that you approve these changes? Once you confrim, we'll be ready to move forward with acceptance.

**Comment by ecotillasanchez** [comment]
Confirmed. Thanks!

**Comment by sjpfenninger** [comment]
I also confirm!

**Comment by wholmgren** [comment]
@katyhuff is there anything I need to do to move this forward?

**Comment by katyhuff** [comment]
Ah -- I'm so sorry wholmgren  -- I missed the last notification. 

Indeed, it's time for the next step! 

Could you please make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission! (You may want to be sure to double check the paper, all minor details, etc. before creating the archive).

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00884/joss.00884/10.21105.joss.00884.pdf)

**Comment by wholmgren** [comment]
Thanks. Looks like we have some issues with reference formatting. I'll try to fix those. Is it possible to run the pdf compilation locally without too much trouble?

We are very close to a new release so maybe best to wait a few days for that DOI.

**Comment by katyhuff** [comment]
Hi @wholmgren the references look ok to me. Perhaps I'm not sufficiently discerning. Can you give an example of what the problem is in the reference formatting?

Regarding the DOI, technically we'd like the DOI to be representative of the reviewed version of the code. However, if it's really just a few days to release, I think waiting for the updated doi is fine as long as new changes in your upcoming release don't alter the functionality we reviewed, do contain their own appropriate test coverage, and don't challenge any of the other elements necessary for successful JOSS review (docs, etc). I think with the development workflow you have demonstrated, this shouldn't be a problem for this project.

**Comment by wholmgren** [comment]
Thanks @katyhuff. I believe that the reviewers ultimately approved commit [845a75](https://github.com/pvlib/pvlib-python/tree/845a75ac736c00901c5077f2e57902d505e18d71). I could describe this as v0.6.0-alpha and follow the normal GitHub Release --> Zenodo archive process. Alternatively, I could download the repo at that commit and upload it as a separate Zenodo archive. Is one approach preferable to the other?

Re references, I was expecting all citations in the text to be rendered as e.g. Lastname (Year), Lastname and Lastname (Year), or Lastname et al (Year). I was confused about the presence of initials and especially full first names. Maybe it's because many of our citations are proceedings. In any case, it's fine with me if it's fine with you. The References section looks ok.

**Comment by katyhuff** [comment]
- Both DOI generation approaches are equivalent, from the perspective of JOSS.
- Regarding the references -- I see. Indeed, I think that's happening at the level of the bibstyle, so it's right according to JOSS.

Thanks!

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.1411511 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1411511" target="_blank">10.5281/zenodo.1411511</a> is the archive.

**Comment by katyhuff** [comment]
@whedon set https://doi.org/10.5281/zenodo.1411511 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1411511" target="_blank">10.5281/zenodo.1411511</a> is the archive.

**Comment by katyhuff** [comment]
@sjpfenninger @ecotillasanchez : Thank you for your prompt and helpful reviews. 
@wholmgren Thank you for your submission, and congratulations.

@arfon We're ready to accept this submission!

**Comment by arfon** [comment]
@sjpfenninger, @ecotillasanchez - many thanks for your reviews here and to @katyhuff for editing this submission ✨ 

@wholmgren - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00884 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00884/status.svg)](https://doi.org/10.21105/joss.00884)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00884">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00884/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00884/status.svg
   :target: https://doi.org/10.21105/joss.00884
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00884/status.svg)](https://doi.org/10.21105/joss.00884)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by wholmgren** [comment]
Thank you @katyhuff @sjpfenninger @ecotillasanchez @arfon! I would be happy to review a future submission.
