### ISSUE TITLE
[PRE REVIEW]: cottoncandy: scientific python package for easy cloud storage

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#888]
**Submitting author:** @anwarnunez (<a href="http://orcid.org/0000-0003-1346-670X">Anwar Nunez-Elizalde</a>)
**Repository:** <a href="https://github.com/gallantlab/cottoncandy" target ="_blank">https://github.com/gallantlab/cottoncandy</a>
**Version:** v.0.0.2
**Editor:** @leeper
**Reviewers:** @vsoch

**Author instructions**

Thanks for submitting your paper to JOSS @anwarnunez. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@anwarnunez if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00888/joss.00888/10.21105.joss.00888.pdf)

**Comment by anwarnunez** [comment]
potential reviewers:

Wilfred Tyler Gee: wtgee (wilfred.gee@students.mq.edu.au)
Vanessa Sochat: vsoch (vsochat@stanford.edu)
Ariel Rokem: arokem (arokem@gmail.com)

**Comment by anwarnunez** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by vsoch** [comment]
A module named cottoncandy? Please let me review this! :candy: :chocolate_bar: :gift:

**Comment by anwarnunez** [comment]
=)

**Comment by leeper** [comment]
@whedon assign @leeper as editor

**Comment by whedon** [comment]
OK, the editor is @leeper

**Comment by leeper** [comment]
@whedon assign @vsoch as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vsoch

**Comment by leeper** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/890. Feel free to close this issue now!
