### ISSUE TITLE
[PRE REVIEW]: MCSD: A MATLAB Tool for Monte-Carlo Simulations of Diffusion in biological Tissues

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#889]
**Submitting author:** @davidnsousa (<a href="http://orcid.org/0000-0001-7277-6447">David Sousa</a>)
**Repository:** <a href="https://github.com/davidnsousa/mcsd" target ="_blank">https://github.com/davidnsousa/mcsd</a>
**Version:** v0.1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @nnadeau, @mwacaan

**Author instructions**

Thanks for submitting your paper to JOSS @davidnsousa. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@davidnsousa if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00889/joss.00889/10.21105.joss.00889.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@davidnsousa I'll act as editor for this submission. I'll start looking for reviewers. In the mean time it would also be useful if you could suggest reviewers. Thanks.

**Comment by nnadeau** [comment]
@Kevin-Mattheus-Moerman I'd be happy to review :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @nnadeau as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nnadeau

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @nnadeau, I've added you here. I'll leave this pre-review issue open a bit longer to attract additional reviewers before we kick off the official review. You are welcome to start reviewing already if you are familiar with the process. Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@markus-nilsson @mfroeling @JianCheng would you be interested in reviewing this submission for the [Journal of Open Source Software](http://joss.theoj.org/)? [The review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#the-joss-review-process) focuses on [the software :floppy_disk:](https://github.com/davidnsousa/mcsd) as well as a very [short paper :page_facing_up:](https://github.com/openjournals/joss-papers/blob/joss.00889/joss.00889/10.21105.joss.00889.pdf). Let me know if you are interested or if you have questions. 
This is a pre-review issue. Once you accept this invitation I'll add you as a reviewer and we can initiate the actual review issue.

**Comment by nirum** [comment]
I don’t have time right now, unfortunately

**Comment by fernandoandreotti** [comment]
Sorry, I also do not have time at the moment.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @mwacaan as reviewer

**Comment by whedon** [comment]
OK, @mwacaan is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
I invited [Dr. Matthan Caan](http://www.lebic-amc.nl/matthan) to review via e-mail.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/966. Feel free to close this issue now!
