### ISSUE TITLE
[PRE REVIEW]: q2-sample-classifier: machine-learning tools for microbiome classification and regression

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#891]
**Submitting author:** @nbokulich (<a href="http://orcid.org/0000-0002-1784-8935">Nicholas Bokulich</a>)
**Repository:** <a href="https://github.com/caporaso-lab/sample-classifier-ms" target ="_blank">https://github.com/caporaso-lab/sample-classifier-ms</a>
**Version:** 2018.6
**Editor:** @yochannah
**Reviewers:** @rasbt, @luizirber

**Author instructions**

Thanks for submitting your paper to JOSS @nbokulich. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@nbokulich if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #891 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/author.rb:36:in `block in build_affiliation_string': Problem with affiliations for J Gregory Caporaso, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/author.rb:35:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/author.rb:35:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/author.rb:11:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:108:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:108:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by nbokulich** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00891/joss.00891/10.21105.joss.00891.pdf)

**Comment by yochannah** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by yochannah** [comment]
@nbokulich I think this is ready to be reviewed - do you have any suggestions for reviewers?

**Comment by gregcaporaso** [comment]
Sebastian Raschka, Dan Knights (though @nbokulich and I have published with Dan, so that might be a conflict of interest) and Holly Bik could be good reviewers for this manuscript.

**Comment by yochannah** [comment]
@gregcaporaso I'll contact them - thanks for the tips!

**Comment by rasbt** [comment]
I could review the pkg

**Comment by yochannah** [comment]
@rasbt fantastic! I'm still looking for a second reviewer so I won't kick the review process off quite yet.

**Comment by yochannah** [comment]
👋  @luizirber is this something you might be interested in reviewing?

**Comment by luizirber** [comment]
@yochannah sure!

**Comment by yochannah** [comment]
Excellent!

**Comment by yochannah** [comment]
@whedon assign @rasbt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rasbt

**Comment by yochannah** [comment]
@whedon add @luizirber as reviewer

**Comment by whedon** [comment]
OK, @luizirber is now a reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/934. Feel free to close this issue now!
