### ISSUE TITLE
[REVIEW]: YAD: A Learning-based Inductive Logic Programming Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#892]
**Submitting author:** @hamedmx (<a href="http://orcid.org/0000-0002-9132-593X">Hamed Karimi</a>)
**Repository:** <a href="https://github.com/hamedmx/YAD-ILP-Tool" target ="_blank">https://github.com/hamedmx/YAD-ILP-Tool</a>
**Version:** v1.0
**Editor:** @jasonclark
**Reviewers:** @dredamonsta1, @cmccomb
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.7189043" target="_blank">10.6084/m9.figshare.7189043</a>

## Status

[![status](http://joss.theoj.org/papers/ed6680f793c8c40e7dbdeacac6b595dd/status.svg)](http://joss.theoj.org/papers/ed6680f793c8c40e7dbdeacac6b595dd)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ed6680f793c8c40e7dbdeacac6b595dd"><img src="http://joss.theoj.org/papers/ed6680f793c8c40e7dbdeacac6b595dd/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ed6680f793c8c40e7dbdeacac6b595dd/status.svg)](http://joss.theoj.org/papers/ed6680f793c8c40e7dbdeacac6b595dd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/hamedmx/YAD-ILP-Tool" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dredamonsta1, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jasonclark know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/hamedmx/YAD-ILP-Tool">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@hamedmx) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/hamedmx/YAD-ILP-Tool">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@hamedmx) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dredamonsta1 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00892/joss.00892/10.21105.joss.00892.pdf)

**Comment by jasonclark** [comment]
@dredamonsta1 the YAD software is ready for your review. 
cc @arfon @hamedmx

**Comment by jasonclark** [comment]
@dredamonsta1 the review checklist is above, but let me know if you have questions.

**Comment by dredamonsta1** [comment]
everything is in tact as ive seen

**Comment by hamedmx** [comment]
@dredamonsta1 Thank you. @arfon Is this issue completed by our reviewer's response ? What is the next step ?

**Comment by hamedmx** [comment]
@arfon Thank you for reopening this review issue. As a concern, Is this issue in the actual review process by @dredamonsta1 for JOSS now or it is stopped ?

**Comment by jasonclark** [comment]
Hi, @cmccom, would you have the chance to look at this software and do second review in the next couple of weeks?

**Comment by cmccomb** [comment]
@jasonclark I have a lot of upcoming travel. I could spend some time on this after 9/24, but I won't be able to turn around a good review before then. Please advise!

**Comment by jasonclark** [comment]
@cmccomb I can look for another reviewer. If I don't find one before 9/24, can I reach back out? Thanks for getting back to me.

**Comment by cmccomb** [comment]
@jasonclark Yes please do!

**Comment by hamedmx** [comment]
@jasonclark Hello, Is there any chances to find an additional reviewer sooner except @cmccomb that we know he will be available after 9/24 ?

**Comment by hamedmx** [comment]
@jasonclark Hello; Since it is 9/26, is there any chances for my submission to be reviewed by @cmccomb ?
Thank you and I am looking forward to your reply.

**Comment by cmccomb** [comment]
@jasonclark, please advise!

**Comment by jasonclark** [comment]
@cmccomb Hey, Chris. Would you be able to review? It would be a great favor to get us closer to final production. Thanks for considering.

**Comment by cmccomb** [comment]
@jasonclark @hamedmx I'll try to knock out the review this week.

**Comment by jasonclark** [comment]
@cmccomb Thanks, Chris! @arfon You mentioned that we might need to reopen. It looks like that has happened. Can I just reassign Chris as editor suing whedon? cc @hamedmx

**Comment by arfon** [comment]
> @cmccomb Thanks, Chris! @arfon You mentioned that we might need to reopen. It looks like that has happened. Can I just reassign Chris as editor using whedon? cc @hamedmx

Kind of. I'll need to handle this semi-manually.

**Comment by arfon** [comment]
@whedon add @cmccomb as reviewer

**Comment by whedon** [comment]
OK, @cmccomb is now a reviewer

**Comment by arfon** [comment]
@cmccomb - you should be all set.

**Comment by jasonclark** [comment]
Perfect. Thanks, @arfon! 
cc @cmccomb @hamedmx

**Comment by jasonclark** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
Can't start a review when the review has already started

**Comment by jasonclark** [comment]
@cmccomb In case you miss it (as I did), there is a second review checklist for you above. Cheers and thanks for all of your work.

**Comment by cmccomb** [comment]
@jasonclark Thanks for bringing that to my attention!

**Comment by cmccomb** [comment]
@hamedmx I think there's only one thing that needs to be fixed: adding some guidelines for potential contributors, bug-reporting, etc. (see Documentation > Community Guidelines in the reviewer checklist above). With that, I think that my review will be complete.
https://github.com/hamedmx/YAD-ILP-Tool/issues/1

**Comment by hamedmx** [comment]
@cmccomb Thank you very much.
So, can I add those community guidelines to the README.md file or, I should add it to the original paper.md file?

**Comment by cmccomb** [comment]
@hamedmx I would recommend just adding it to the README.md

**Comment by hamedmx** [comment]
@cmccomb I provided the desired community guidelines in README.md file

**Comment by cmccomb** [comment]
@hamedmx Thanks for making those changes!
@jasonclark This completes my review!

**Comment by hamedmx** [comment]
@arfon I think the review of our submission is complete now

**Comment by hamedmx** [comment]
@arfon As I can see the information for authors in author guidelines of JOSS, I created an account in figshare to upload the updated submission and got a DOI for this submission. What should I do now?

**Comment by arfon** [comment]
@jasonclark - I think this is good to accept now. Can you confirm?

**Comment by hamedmx** [comment]
@arfon I think @jasonclark is not available these days.

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.7189043 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.7189043" target="_blank">10.6084/m9.figshare.7189043</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/15

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/15, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00892/status.svg)](https://doi.org/10.21105/joss.00892)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00892">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00892/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00892/status.svg
   :target: https://doi.org/10.21105/joss.00892
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00892/status.svg)](https://doi.org/10.21105/joss.00892)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/16
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00892](https://doi.org/10.21105/joss.00892)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@dredamonsta1, @cmccomb - many thanks for your reviews here and to @jasonclark for editing this submission ✨ 

@hamedmx - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00892 :zap: :rocket: :boom:
