### ISSUE TITLE
[PRE REVIEW]: compboost: Modular Framework for Component-Wise Boosting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#894]
**Submitting author:** @schalkdaniel (<a href="http://orcid.org/0000-0003-0950-1947">Daniel Schalk</a>)
**Repository:** <a href="https://github.com/schalkdaniel/compboost" target ="_blank">https://github.com/schalkdaniel/compboost</a>
**Version:** v0.1.0
**Editor:** @brainstorm
**Reviewers:** @moonso

**Author instructions**

Thanks for submitting your paper to JOSS @schalkdaniel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@schalkdaniel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by schalkdaniel** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by schalkdaniel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00894/joss.00894/10.21105.joss.00894.pdf)

**Comment by schalkdaniel** [comment]
Hi, the editor assignment is now pending for 2 weeks. Is there anything I can do to speed up the process?

**Comment by arfon** [comment]
> Hi, the editor assignment is now pending for 2 weeks. Is there anything I can do to speed up the process?

Apologies. We're very busy right now. I'll see if I can encourage some of our editors to get this moving.

**Comment by schalkdaniel** [comment]
Thanks, sorry for rushing you. :)

**Comment by arfon** [comment]
:wave: @jakevdp - would you be able to edit this submission for JOSS?

**Comment by arfon** [comment]
:wave: @brainstorm - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
Hi @schalkdaniel - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by brainstorm** [comment]
@arfon Happy to edit this one too.

I would like to summon @moonso if no other reviewer steps in ;)

**Comment by moonso** [comment]
Hi @brainstorm ! Sounds interesting, what do I need do do/read?

**Comment by brainstorm** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by brainstorm** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/967. Feel free to close this issue now!
