### ISSUE TITLE
[PRE REVIEW]: hoggorm: a python library for explorative multivariate statistics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#896]
**Submitting author:** @olivertomic (<a href="http://orcid.org/0000-0003-1595-9962">Oliver Tomic</a>)
**Repository:** <a href="https://github.com/olivertomic/hoggorm" target ="_blank">https://github.com/olivertomic/hoggorm</a>
**Version:** 0.12.0
**Editor:** @arfon
**Reviewers:** @jsgalan

**Author instructions**

Thanks for submitting your paper to JOSS @olivertomic. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@olivertomic if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #896 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @jakevdp the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #896 with the following error: 

 ORCID looks malformed
/app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (none) for Thomas Graff (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
Hi @olivertomic, please remove the `orcid` YAML key for authors who don't have one (e.g. Thomas Graff)

**Comment by olivertomic** [comment]
Hi @arfon, thank you very much for initialising the process and the feedback regarding the orcid YAML keys. I removed them for two of the authors that were not registered with orcid.

**Comment by olivertomic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00896/joss.00896/10.21105.joss.00896.pdf)

**Comment by arfon** [comment]
@olivertomic - could you take a look at this [list of potential reviewers](https://bit.ly/joss-reviewers) and suggest some people who might be good candidates?

**Comment by olivertomic** [comment]
@arfon, thank you for getting in touch.  A very good candidate would be candidate on row 338 on your list, since this person is the only one who has named chemometrics as their domain. Another great candidate would be candidate on row 275. Other possible candidates would be 108, 123, 173.

**Comment by arfon** [comment]
@expectopatronum @GalenStocking @tupi @jsgalan would any of you be willing to review this submission for JOSS? You can learn more about what that process looks like here: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by jsgalan** [comment]
Hi all, Sorry for the late reply, has the reviewers been assigned?

If not, i will gladly review the submission.

Please let me know,

Best

**Comment by arfon** [comment]
@jsgalan thanks! I'll got ahead and set up the review issue now.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @jsgalan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jsgalan

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/980. Feel free to close this issue now!

**Comment by arfon** [comment]
@jsgalan @olivertomic - please head over to #980 for the actual review
