### ISSUE TITLE
[REVIEW]: medical image visualization library in python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#897]
**Submitting author:** @raamana (<a href="http://orcid.org/0000-0003-4662-0558">Pradeep Reddy Raamana</a>)
**Repository:** <a href="https://github.com/raamana/mrivis" target ="_blank">https://github.com/raamana/mrivis</a>
**Version:** 0.3
**Editor:** @arokem
**Reviewer:** @miykael
**Archive:** <a href="https://doi.org/10.5281/zenodo.1450944" target="_blank">10.5281/zenodo.1450944</a>

## Status

[![status](http://joss.theoj.org/papers/06f56034fa3b4c012f96dcba17167b69/status.svg)](http://joss.theoj.org/papers/06f56034fa3b4c012f96dcba17167b69)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/06f56034fa3b4c012f96dcba17167b69"><img src="http://joss.theoj.org/papers/06f56034fa3b4c012f96dcba17167b69/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/06f56034fa3b4c012f96dcba17167b69/status.svg)](http://joss.theoj.org/papers/06f56034fa3b4c012f96dcba17167b69)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/raamana/mrivis" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@miykael, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/raamana/mrivis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.3)?
- [x] **Authorship:** Has the submitting author (@raamana) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @miykael it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00897/joss.00897/10.21105.joss.00897.pdf)

**Comment by raamana** [comment]
Hi @miykael, the docs website for you to get a sense of what it is. I am finalizing the implementation for one another class Carpet, but what it is now should give you a very good sense of what's happening.

**Comment by raamana** [comment]
It should be ready now, I believe.

**Comment by miykael** [comment]
Perfect! I have a conference and workshop coming up in the next 10 days but will start reviewing in the time between and finalize the review shortly after.

**Comment by arokem** [comment]
@raamana : is this ready for a review? It seems like you are still working on some things?

**Comment by raamana** [comment]
Yes it is. Sorry I should have made that explicit.

**Comment by arokem** [comment]
@miykael: have you had a chance to take a look?

**Comment by miykael** [comment]
@arokem and @raamana I apologize for my late reply, I had an unforeseen hectic two weeks. But the review has now my full attention!

The software looks very good and useful and I will write my full review in the issue tracker of https://github.com/raamana/mrivis. But I think the repo is missing a `paper.md` file (as mentioned 
in the [author guidlines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), or is this optional?

**Comment by raamana** [comment]
thanks - looking fwd to learn your comments.

its in the docs folder, as required : https://github.com/raamana/mrivis/blob/master/docs/paper.md

**Comment by miykael** [comment]
@raamana and @arokem - my review can be found under https://github.com/raamana/mrivis/issues/11. @raamana, don't hesitate to ask for clarification!

**Comment by raamana** [comment]
Thanks Michael for a thorough and a helpful review, appreciate it.

Ariel, this is the final DOI for this version: 10.5281/zenodo.1443427

**Comment by raamana** [comment]
Just pushed the latest code to pypi also! :)

**Comment by arokem** [comment]
Thanks @miykael for the excellent review! 👏 Your work is done here...

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1443427 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1443427" target="_blank">10.5281/zenodo.1443427</a> is the archive.

**Comment by arokem** [comment]
@raamana : sorry - a couple of things I noticed about your article just now: 

- The title is not capitalized. I don't think that you want every word in the title to be capitalized, but the very first word probably should be. Also, the title currently doesn't include the name of the software library. I would recommend adding that. 

- The references do not have DOIs. Please add these.

**Comment by raamana** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00897/joss.00897/10.21105.joss.00897.pdf)

**Comment by raamana** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00897/joss.00897/10.21105.joss.00897.pdf)

**Comment by raamana** [comment]
Good catch - fixed them now.

**Comment by arokem** [comment]
Thanks for doing that. Would you mind creating a new Zenodo DOI?

**Comment by raamana** [comment]
Sure - it is 10.5281/zenodo.1450944

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1450944 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1450944" target="_blank">10.5281/zenodo.1450944</a> is the archive.

**Comment by arokem** [comment]
@arfon : I believe that this paper is ready to be accepted!

**Comment by arfon** [comment]
@miykael - many thanks for your review here and to @arokem for editing this submission ✨ 

@raamana - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00897 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00897/status.svg)](https://doi.org/10.21105/joss.00897)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00897">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00897/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00897/status.svg
   :target: https://doi.org/10.21105/joss.00897
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00897/status.svg)](https://doi.org/10.21105/joss.00897)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
