### ISSUE TITLE
[REVIEW]: proEQUIB - IDL Library for Plasma Diagnostics and Abundance Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#899]
**Submitting author:** @danehkar (<a href="http://orcid.org/0000-0003-4552-5997">Ashkbiz Danehkar</a>)
**Repository:** <a href="https://github.com/equib/proEQUIB" target ="_blank">https://github.com/equib/proEQUIB</a>
**Version:** v0.0.6
**Editor:** @arfon
**Reviewer:** @mdpiper, @mgalloy
**Archive:** <a href="https://doi.org/10.5281/zenodo.1890337" target="_blank">10.5281/zenodo.1890337</a>

## Status

[![status](http://joss.theoj.org/papers/181c4203efb0928e7f1e17e5b51be09d/status.svg)](http://joss.theoj.org/papers/181c4203efb0928e7f1e17e5b51be09d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/181c4203efb0928e7f1e17e5b51be09d"><img src="http://joss.theoj.org/papers/181c4203efb0928e7f1e17e5b51be09d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/181c4203efb0928e7f1e17e5b51be09d/status.svg)](http://joss.theoj.org/papers/181c4203efb0928e7f1e17e5b51be09d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/equib/proEQUIB" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mdpiper & @mgalloy, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/equib/proEQUIB">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.6)?
- [x] **Authorship:** Has the submitting author (@danehkar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/equib/proEQUIB">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.6)?
- [x] **Authorship:** Has the submitting author (@danehkar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mdpiper, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00899/joss.00899/10.21105.joss.00899.pdf)

**Comment by mdpiper** [comment]
I created https://github.com/equib/proEQUIB/pull/1 to add a short note on installing the proEQUIB library. This addresses item 2 in the Documentation checklist.

**Comment by mdpiper** [comment]
My review of **proEQUIB** is complete. The library and its associated paper are appropriate for publication in JOSS, pending @danehkar's responses to the issues I've opened in the repository. Further:

1. https://github.com/equib/proEQUIB/issues/3 is especially important. There's a fair amount of code in the library (including a common block), and no tests. A set of tests that cover the library will increase my confidence that the library is working as it should.
1. The paper reads well, but it could use one more editing pass. There are a couple awkward phrasings that could be smoothed; for example, "...allow to..." in the first and second bullets.

@arfon I'll complete the open items in the review checklist once the issues above have been addressed.

**Comment by arfon** [comment]
> @arfon I'll complete the open items in the review checklist once the issues above have been addressed.

Excellent news, thanks @mdpiper! @danehkar - please let us know here when you've had a chance to incorporate this feedback.

**Comment by mgalloy** [comment]
I have checked off as many items on the Review Checklist as I can right now. Remaining items need to be addressed by @danehkar before I can check them off.

**Comment by arfon** [comment]
Friendly reminder to get to this review sometime soon please @mgalloy

**Comment by mgalloy** [comment]
As mentioned above, I have reviewed everything on the Review Checklist I can right now. The issues opened by @mdpiper need to be addressed by @danehkar to continue.

**Comment by arfon** [comment]
> Friendly reminder to get to this review sometime soon please @mgalloy

Sorry, tagged the wrong person. Please let us know when you've had a chance to incorporate the feedback here @danehkar

**Comment by arfon** [comment]
@danehkar has confirmed by email that he is going to try and make updates by the end of November.

**Comment by danehkar** [comment]
> @mdpiper The `equib_*` routines in the `pro` directory don't appear to be written by the author. To separate them from the author's work, I suggest that they be moved to a new directory under `externals`. I've raised this as [equib/proEQUIB#5](https://github.com/equib/proEQUIB/issues/5).

I moved them to to a `misc` under `externals`, and I renamed  `equib_*` to `_*`.  These routines (interp2d.pro, meshgrid.pro, sign.pro, str2int.pro, strnumber.pro) were chosen from other IDL packages to replace some FORTRAN functions of [EQUIB](https://github.com/equib/EQUIB) during my conversion from FORTRAN to IDL. I added `equib_*` to them to separate from other IDL functions with similar names in other IDL packages in my machine.  Now I closed the issue [equib/proEQUIB#5](https://github.com/equib/proEQUIB/issues/5).

**Comment by danehkar** [comment]
> @mdpiper I added three issues:
> 
> * [equib/proEQUIB#2](https://github.com/equib/proEQUIB/issues/2)
> * [equib/proEQUIB#4](https://github.com/equib/proEQUIB/issues/4)
> 
> to the author's repo to address the last three items in the Documentation checklist.

- I added [CONTRIBUTING.md](https://github.com/equib/proEQUIB/blob/master/CONTRIBUTING.md) to the [proEQUIB repository](https://github.com/equib/proEQUIB) on GitHub, which contains some guidelines for contributors. I closed the issue [equib/proEQUIB#2](https://github.com/equib/proEQUIB/issues/2).

- I created API documentation with [IDLdoc](https://github.com/mgalloy/idldoc) and copied them into [docs](https://github.com/equib/proEQUIB/tree/master/docs). You can check it. If there is no problem, I will close the issue [equib/proEQUIB#4](https://github.com/equib/proEQUIB/issues/4).

**Comment by mdpiper** [comment]
@danehkar Looks good! You can close https://github.com/equib/proEQUIB/issues/4. It would be best to host the documentation at another location, such as rtfd.io or your own site.

**Comment by danehkar** [comment]
> @mdpiper It would be best to host the documentation at another location, such as rtfd.io or your own site.

The documentation is now hosted at https://equib.github.io/proEQUIB/doc/

**Comment by sundmanbo** [comment]
Please remove me from this and other JOSS reviewing threads, I have tried
but not managed to do that myself

Bo Sundman


Den lör 1 dec. 2018 kl 08:46 skrev Ashkbiz Danehkar <
notifications@github.com>:

**Comment by danehkar** [comment]
I noticed that `triangulate` and `trigrid` in GDL have some bugs, and not work correctly in [interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro). I replaced [interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro) with [interp_2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp_2d.pro). Now proEQUIB functions also work in GDL as seen in [Travis CI](https://travis-ci.org/equib/proEQUIB) and [Appveyor](https://ci.appveyor.com/project/danehkar/proequib). To check, you need to install GDL (`sudo dnf install gdl` in Fedora, `sudo apt-get install gnudatalanguage` in Ubuntu, `brew install gnudatalanguage` in OS X).

**Comment by mgalloy** [comment]
@sundmanbo Unwatch this repo. Go to any page on for the JOSS reviews repo (such as the page for this thread), go to the top of the page, click "Unwatch".

**Comment by arfon** [comment]
@sundmanbo - yes, please do this:

![](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

**Comment by mgalloy** [comment]
I have marked all items on the checklist. My review is complete, good luck @danehkar!

**Comment by danehkar** [comment]
> I added three issues:
> 
> * [equib/proEQUIB#2](https://github.com/equib/proEQUIB/issues/2)
> * [equib/proEQUIB#3](https://github.com/equib/proEQUIB/issues/3)
> * [equib/proEQUIB#4](https://github.com/equib/proEQUIB/issues/4)
> 
> to the author's repo to address the last three items in the Documentation checklist.

@mdpiper I included  [mgunit](https://github.com/mgalloy/mgunit) in the folder  [test_mgunit](https://github.com/equib/proEQUIB/tree/master/test_mgunit) for automated tests. You need to have atomic data in ``externals/atomneb/atomic-data`` and ``externals/atomneb/atomic-data-rc`` in do this test. To have all dependencies, you can clone the whole project with dependent libraries:

    git clone --recursive https://github.com/equib/proEQUIB.git

Then, you can run the test for mgunit:

    idl test_all.pro

There should not be any failure in ``test-results.log`` and ``test-results.html`` files. 

I closed the issues [equib/proEQUIB#2](https://github.com/equib/proEQUIB/issues/2) and [equib/proEQUIB#4](https://github.com/equib/proEQUIB/issues/4). If there is no problem in the above test, I will close the issue [equib/proEQUIB#3](https://github.com/equib/proEQUIB/issues/3).

**Comment by danehkar** [comment]
> I have marked all items on the checklist. My review is complete, good luck @danehkar!

@mgalloy Thank you for your test. I much appreciate your review. I am now checking the paper if there is any typos there.

**Comment by danehkar** [comment]
@arfon I uploaded the updated paper into the folder [`paper`](https://github.com/equib/proEQUIB/tree/master/paper). Previously, there were some issues in ``paper.bib`` and the paper pdf file did not show the journal names.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00899/joss.00899/10.21105.joss.00899.pdf)

**Comment by arfon** [comment]
How is this looking @danehkar ☝️

**Comment by danehkar** [comment]
@arfon The paper looks fine, but there is an issue in the citation order and style:

- For `[see e.g. @Danehkar:2013; @Danehkar:2014; @Danehkar:2016; @Danehkar:2018]`:

  > (Danehkar, 2018a; see e.g. Danehkar, Parker, & Ercolano, 2013; Danehkar, Parker, & Steffen, 2016; Danehkar, Todt, Ercolano, & Kniazev, 2014)

  should be:

  > (see e.g. Danehkar, Parker, and Ercolano 2013; Danehkar et al. 2014; Danehkar, Parker, and Steffen 2016; Danehkar 2018a)

- For `[@Ercolano:2003; @Ercolano:2005]`:

  > (Ercolano, Barlow, & Storey, 2005; Ercolano, Barlow, Storey, & Liu, 2003)

  should be 

  > (Ercolano et al. 2003; Ercolano, Barlow, and Storey 2005)

- For `[@Danehkar:2016; @Danehkar:2018]`:

  > (Danehkar, 2018a; Danehkar et al., 2016)

  should be

  > (Danehkar, Parker, and Steffen 2016; Danehkar 2018a)

- For `[see e.g. @Danehkar:2013; @Danehkar:2014; @Danehkar:2014b]`:

  > (Danehkar, 2014; see e.g. Danehkar et al., 2013, 2014)

  should be

  > (see e.g. Danehkar, Parker, and Ercolano 2013; Danehkar et al. 2014; Danehkar 2014)

- I do not think it is necessary to show more than 3 authors in text:

  > (Arabas, Schellens, Coulais, Gales, & Messmer, 2010; Coulais et al., 2010)

  should be

  > (Arabas, et al., 2010; Coulais et al., 2010)

The citation style in the previous PDF file did not have any problems.

**Comment by danehkar** [comment]
@arfon I now switched to the APA citation style. I checked it here [#798](https://github.com/openjournals/joss-reviews/issues/798). You can reproduce the article proof. Thanks.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00899/joss.00899/10.21105.joss.00899.pdf)

**Comment by mdpiper** [comment]
@danehkar Thanks for addressing all the issues I raised. I've checked off the last item on my review checklist, so my review is complete!

**Comment by danehkar** [comment]
@mdpiper @mgalloy Thank you for reviewing this software.

@arfon Thank you for handling and editing this submission. I made an archived of the reviewed software in Zenodo: doi:[10.5281/zenodo.1890337](https://doi.org/10.5281/zenodo.1890337)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1890337 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1890337" target="_blank">10.5281/zenodo.1890337</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/98

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/98, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/99
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00899](https://doi.org/10.21105/joss.00899)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@mdpiper, @mgalloy - many thanks for your reviews here ✨ 

@danehkar - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00899/status.svg)](https://doi.org/10.21105/joss.00899)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00899">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00899/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00899/status.svg
   :target: https://doi.org/10.21105/joss.00899
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00899/status.svg)](https://doi.org/10.21105/joss.00899)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
