### ISSUE TITLE
Consider making a new release, since there are some recent changes

### ISSUE THREAD

**Issue by brylie** [openjournals/joss-reviews#90]
Now that we are nearly done with the review process, it would be good to make a release incorporating all recent changes. Please make one more release, so that we may finish the review.

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by brylie** [comment]
Oops. Sorry, wrong repository.
