### ISSUE TITLE
[PRE REVIEW]: Plot Flow Charts According to the PRISMA Statement

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#902]
**Submitting author:** @jackwasey (<a href="http://orcid.org/0000-0003-3738-4637">Jack Wasey</a>)
**Repository:** <a href="https://github.com/jackwasey/PRISMAstatement" target ="_blank">https://github.com/jackwasey/PRISMAstatement</a>
**Version:** 1.0.4
**Editor:** @pjotrp
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @jackwasey. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jackwasey if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00902/joss.00902/10.21105.joss.00902.pdf)

**Comment by arfon** [comment]
:wave: @pjotrp - the submitting author suggested you as the handling editor.

**Comment by jackwasey** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by jackwasey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00902/joss.00902/10.21105.joss.00902.pdf)

**Comment by pjotrp** [comment]
Dear @jackwasey 

We discussed this submission among the editorial board and decided that it is of 'minor utility' as per our
[submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

I am sorry to say that we can not accept it for review. 

Please to not feel discouraged to try again - and, next time, feel freeto check with me in advance.

**Comment by jackwasey** [comment]
Thanks for considering.
