### ISSUE TITLE
[PRE REVIEW]: Parareal Algorithm Implementation and Simulation in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#903]
**Submitting author:** @sperugin (<a href="http://orcid.org/0000-0002-1736-4009">Saverio Perugini</a>)
**Repository:** <a href="https://github.com/sperugin/Parareal-Implementation-and-Simulation-in-Julia" target ="_blank">https://github.com/sperugin/Parareal-Implementation-and-Simulation-in-Julia</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @sperugin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sperugin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00903/joss.00903/10.21105.joss.00903.pdf)

**Comment by arfon** [comment]
Hi @sperugin, thanks for your submission to JOSS. Unfortunately this software is not suitable for JOSS as it falls into our 'minor' category: https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements
