### ISSUE TITLE
[REVIEW]: Nashpy: A Python library for the computation of Nash equilibria

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#904]
**Submitting author:** @drvinceknight (<a href="http://orcid.org/0000-0002-4245-0638">Vincent Knight</a>)
**Repository:** <a href="https://github.com/drvinceknight/Nashpy" target ="_blank">https://github.com/drvinceknight/Nashpy</a>
**Version:** v0.0.18
**Editor:** @labarba
**Reviewer:** @Fil, @alex-konovalov
**Archive:** <a href="https://doi.org/10.5281/zenodo.1453761" target="_blank">10.5281/zenodo.1453761</a>

## Status

[![status](http://joss.theoj.org/papers/3ada2a699914888658b7ac9c12d20e03/status.svg)](http://joss.theoj.org/papers/3ada2a699914888658b7ac9c12d20e03)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3ada2a699914888658b7ac9c12d20e03"><img src="http://joss.theoj.org/papers/3ada2a699914888658b7ac9c12d20e03/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3ada2a699914888658b7ac9c12d20e03/status.svg)](http://joss.theoj.org/papers/3ada2a699914888658b7ac9c12d20e03)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/drvinceknight/Nashpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Fil & @alex-konovalov, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/drvinceknight/Nashpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.18)?
- [x] **Authorship:** Has the submitting author (@drvinceknight) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/drvinceknight/Nashpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.18)?
- [x] **Authorship:** Has the submitting author (@drvinceknight) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Fil, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00904/joss.00904/10.21105.joss.00904.pdf)

**Comment by labarba** [comment]
👋 @Fil, @alex-konovalov — This is where the action happens. Feel free to ask any questions.

**Comment by Fil** [comment]
Apart from the version issue, it's all good for me. Thank you @drvinceknight for submitting to JOSS.

**Comment by labarba** [comment]
I've updated the version number in the review issue.

**Comment by labarba** [comment]
👋 @alex-konovalov — will you be able to submit your review soon? Let me know!

**Comment by alex-konovalov** [comment]
@labarba sorry for delay - should be there by Monday!

**Comment by alex-konovalov** [comment]
@labarba review completed. Fixed two typos in https://github.com/drvinceknight/Nashpy/pull/50 and pointed out a couple of issues with DOIs at https://github.com/drvinceknight/Nashpy/issues/51. Otherwise, straightforward installation, proper testing and detailed documentation - @drvinceknight, thank you for submitting to JOSS!

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00904/joss.00904/10.21105.joss.00904.pdf)

**Comment by labarba** [comment]
Small editorial fixes:

1. paragraph 3: "beats Rock (the first action." ... close parenthesis.
2. paragraph 5: "computing this equilibria" ... these equilibria? or this equilibrium? Same sentence: check commas; something isn't quite right.
3. page 2: "easily accessibly" ... accessible
4. p. 2, par. 2: capitalize "python" ... also, check verb: "includes ... to its core C functionality" (adds?) ... and commas.
5. par. 3: numpy > NumPy; scipy> SciPy; also, maybe use em-dashes to avoid the double parenthesis due to the citation.
6. For example Windows > add comma
7. par. 4: 2 player games > 2-player games (add hyphen)
8. par. 5: avoid syntactic expletive in "There are potential limitations ... , these are due to" > "Potential limitations of Nashpy are due to the complexity..."
9. "potential pairs of strategy" > a strategy?
10. "For n x n sized square matrices" > delete "sized"
11. "it has complexity of the order of O(2^n^2)" > it has O(.) complexity" (the big-O already means "order of")
12. numpy > NumPy
13. "are generators which ensures" ... comma before "which"
14. "For example, below an 11 by 11 game" > "For example, below, an 11-by-11 game" (comma and hyphens)
15. "and timings computed are shown" > "and timings are shown"
16. "Using the ... (ref) an equilibrium..." > comma after (ref)
17. "it is already currently" > delete "already"?
18. "final year course" > "final-year course" (hyphen)
19. "read and understand implementation of the algorithms" > the implementation
20. awkward: "with the linked DOI: (ref)" ... maybe just remove "with the linked DOI" and simply put the ref.

**Comment by labarba** [comment]
Also, DOI links in the reference list are broken. Please clean up the bib file so the links resolve.

**Comment by drvinceknight** [comment]
Thanks @labarba I'll make those changes over next couple of days.

**Comment by labarba** [comment]
OK. Ping when done!

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00904/joss.00904/10.21105.joss.00904.pdf)

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00904/joss.00904/10.21105.joss.00904.pdf)

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00904/joss.00904/10.21105.joss.00904.pdf)

**Comment by drvinceknight** [comment]
@labarba thank you very much for taking the time to point all those out. I've made all the changes (https://github.com/drvinceknight/Nashpy/commit/67a27f3300c804fa44ee393e7ff447c2bce126a0) and checked the proof. I believe it's all done now :)

**Comment by labarba** [comment]
I bring you more editorial fixes!

Page 1, par. 2: comma before “which”
par. 3 “For example A_21” …add comma. “Using Nashpy the equilibrium” …add comma.
Statement of Need: “an example of this includes” >> “an example is”
Page 2.
Ref to Jones, Oliphant et al. appears with years marked as 2001–2001– … can you fix this?
On the same line, remove spaces before and after the em-dashes (that’s the norm).
par. 5: “Nashpy” here is formatted differently than elsewhere—pick one: code or non-code font?
Jones et al. again appears with that strange year range. Can you fix?

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00904/joss.00904/10.21105.joss.00904.pdf)

**Comment by drvinceknight** [comment]
Thanks again @labarba, I believe https://github.com/drvinceknight/Nashpy/commit/af30119a129995a66f2c7ef1ee9bf3d1ef1e4ce8 gets all these. If there's anything else let me know.

I appreciate you taking the time. :)

**Comment by labarba** [comment]
OK! Go ahead and make a deposit on Zenodo now (or your favorite archival repository) and do post the DOI here.

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00904/joss.00904/10.21105.joss.00904.pdf)

**Comment by drvinceknight** [comment]
Thank you @labarba, here is the zenodo archive: https://zenodo.org/record/1453761

DOI: [10.5281/zenodo.1453761](https://doi.org/10.5281/zenodo.1453761)

Let me know if I need to do anything further (and thanks again for all your time).

**Comment by labarba** [comment]
The author list on the Zenodo entry does not match the author list on the paper. You may need to manually edit the author list on Zenodo (which grabs that automatically from commit history, I think.)

**Comment by drvinceknight** [comment]
That's been updated now.

**Comment by labarba** [comment]
👋 @arfon — this paper is accepted and ready to be published.

Many thanks to @Fil and @alex-konovalov for reviewing for JOSS. Without your efforts, this adventure in new-wave publishing would not be possible!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1453761 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1453761" target="_blank">10.5281/zenodo.1453761</a> is the archive.

**Comment by arfon** [comment]
@drvinceknight - can you confirm that this maths looks OK? @whedon is giving me a warning when compiling the paper [10.21105.joss.00904.pdf](https://github.com/openjournals/joss-reviews/files/2465225/10.21105.joss.00904.pdf)

```
[WARNING] Could not convert TeX math '
  A=
  \begin{pmatrix}
  0  & -1 & 1  \\
  1  & 0  & -1 \\
  -1 & 1  & 0  \\
  \end{pmatrix}
  ', rendering as TeX```

**Comment by drvinceknight** [comment]
> @drvinceknight - can you confirm that this maths looks OK?

@arfon I confirm that that looks right. (I'd suggest that it looks like the compiler is just raising a warning before falling "up" to use a superset compiler with the amsmath library.)

**Comment by arfon** [comment]
@Fil, @alex-konovalov - many thanks for your reviews here and to @labarba for editing this submission ✨ 

@drvinceknight - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00904 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00904/status.svg)](https://doi.org/10.21105/joss.00904)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00904">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00904/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00904/status.svg
   :target: https://doi.org/10.21105/joss.00904
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00904/status.svg)](https://doi.org/10.21105/joss.00904)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by drvinceknight** [comment]
Thank you all once again for your time and effort. Having reviewed a few times it's been a pleasure to be on the other side. @arfon @labarba et al. well done for what you're doing here, this "new-wave publishing" is really enthusing.
