### ISSUE TITLE
[REVIEW]: Python Implementation of Codon Adaptation Index

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#905]
**Submitting author:** @benjamin-lee (<a href="http://orcid.org/0000-0002-7133-8397">Benjamin Lee</a>)
**Repository:** <a href="https://github.com/Benjamin-Lee/CodonAdaptationIndex" target ="_blank">https://github.com/Benjamin-Lee/CodonAdaptationIndex</a>
**Version:** v1.0.0
**Editor:** @george-githinji
**Reviewer:** @ctb
**Archive:** <a href="https://doi.org/10.5281/zenodo.1439494" target="_blank">10.5281/zenodo.1439494</a>

## Status

[![status](http://joss.theoj.org/papers/8adf6bd9fd6391d5343d15ea0b6b6525/status.svg)](http://joss.theoj.org/papers/8adf6bd9fd6391d5343d15ea0b6b6525)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8adf6bd9fd6391d5343d15ea0b6b6525"><img src="http://joss.theoj.org/papers/8adf6bd9fd6391d5343d15ea0b6b6525/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8adf6bd9fd6391d5343d15ea0b6b6525/status.svg)](http://joss.theoj.org/papers/8adf6bd9fd6391d5343d15ea0b6b6525)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Benjamin-Lee/CodonAdaptationIndex" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ctb, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @george-githinji know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Benjamin-Lee/CodonAdaptationIndex">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@benjamin-lee) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by Benjamin-Lee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00905/joss.00905/10.21105.joss.00905.pdf)

**Comment by george-githinji** [comment]
Hello @ctb, Kindly let me know how you are getting along with the review process and if you need any assistance.

**Comment by ctb** [comment]
Finished the easy bit of the review and filed some suggestions in issues --

- [ ] track down some example input files https://github.com/Benjamin-Lee/CodonAdaptationIndex/issues/2
- [ ] add a bit more documentation about contributing and filing issues https://github.com/Benjamin-Lee/CodonAdaptationIndex/issues/3

**Comment by Benjamin-Lee** [comment]
On the changes now – give me ~30 mins to get those fixed

**Comment by Benjamin-Lee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00905/joss.00905/10.21105.joss.00905.pdf)

**Comment by Benjamin-Lee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00905/joss.00905/10.21105.joss.00905.pdf)

**Comment by Benjamin-Lee** [comment]
Changes are live!

**Comment by ctb** [comment]
Hello! Thank you for this! I think this is perfectly acceptable for publication.

The only _suggestion_ I have is that a complete real-world set of sequences be made available (along with test instructions) either as part of the repo or for download.  Specifically, under https://cai.readthedocs.io/en/latest/usage.html#basic-usage, it would be great to have a command to run that actually worked with files that were readily available. This helps users identify format issues and otherwise engage quickly with the software. But it is not essential for acceptance.

Nice work!

**Comment by Benjamin-Lee** [comment]
I just updated the https://cai.readthedocs.io/en/latest/usage.html#basic-usage section to point out specifically that the referenced files are a part of the repository. In addition, the [example_seqs](https://github.com/Benjamin-Lee/CodonAdaptationIndex/blob/master/example_seqs/) directory on the GitHub contains six reference sets of highly expressed genes and six example CDSs.

**Comment by ctb** [comment]
Excellent! Sorry I missed it in my review - I did some find commands but clearly not good ones :)

--
Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu>

On Sep 30, 2018, at 4:12 PM, Benjamin Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


I just updated the https://cai.readthedocs.io/en/latest/usage.html#basic-usage section to point out specifically that the referenced files are a part of the repository. In addition, the example_seqs<https://github.com/Benjamin-Lee/CodonAdaptationIndex/blob/master/example_seqs/> directory on the GitHub contains six reference sets of highly expressed genes and six example CDSs.

**Comment by Benjamin-Lee** [comment]
Great! Anything else I need to get the check box for examples?

**Comment by george-githinji** [comment]
@ctb Thank you for the review and thank you @Benjamin-Lee for the timely feedback. @arfon please can we move to get this published?

**Comment by arfon** [comment]
@Benjamin-Lee - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by Benjamin-Lee** [comment]
`10.5281/zenodo.1439494` is the archived version of v1.0.2

**Comment by Benjamin-Lee** [comment]
@arfon Quick question: is there supposed to be a space between the ")" and "P" in "E. Mocarski, Ed.)PLOS Pathogens" in the citations?

**Comment by arfon** [comment]
> @arfon Quick question: is there supposed to be a space between the ")" and "P" in "E. Mocarski, Ed.)PLOS Pathogens" in the citations?

That looks like a bug in the citation style formatting. Perhaps just remove this line from your bibtex?:

https://github.com/Benjamin-Lee/CodonAdaptationIndex/blob/master/paper/paper.bib#L52

**Comment by Benjamin-Lee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00905/joss.00905/10.21105.joss.00905.pdf)

**Comment by Benjamin-Lee** [comment]
@arfon That did the trick! I looked into [whedon/resources/apa.csl](https://github.com/openjournals/whedon/blob/master/resources/apa.csl) but didn't make much progress on identifying the problem to prevent it from happening to other authors. Am I looking in the right place?

That being said, the proof looks like its good to go. Thanks!

**Comment by arfon** [comment]
> @arfon That did the trick! I looked into whedon/resources/apa.csl but didn't make much progress on identifying the problem to prevent it from happening to other authors. Am I looking in the right place?

Yeah, that's probably where. Thanks for looking!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1439494 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1439494" target="_blank">10.5281/zenodo.1439494</a> is the archive.

**Comment by arfon** [comment]
Many thanks for your review here @ctb and to @george-githinji for editing this submission ✨ 

@Benjamin-Lee - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00905 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00905/status.svg)](https://doi.org/10.21105/joss.00905)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00905">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00905/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00905/status.svg
   :target: https://doi.org/10.21105/joss.00905
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00905/status.svg)](https://doi.org/10.21105/joss.00905)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
