### ISSUE TITLE
[PRE REVIEW]: `datastructures`: An R package for organisation and storage of data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#907]
**Submitting author:** @dirmeier (<a href="http://orcid.org/0000-0001-9795-3550">Simon Dirmeier</a>)
**Repository:** <a href="https://github.com/dirmeier/datastructures" target ="_blank">https://github.com/dirmeier/datastructures</a>
**Version:** v0.2.7
**Editor:** @karthik
**Reviewers:** @fabian-s

**Author instructions**

Thanks for submitting your paper to JOSS @dirmeier. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dirmeier if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @karthik - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00907/joss.00907/10.21105.joss.00907.pdf)

**Comment by dirmeier** [comment]
Hey, I believe @fabian-s could be a good reviewer for this if he is interested.

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by dirmeier** [comment]
@karthik Hello, there are no conflicts of interest. I've found him through the JOSS reviewer list and thought his experience with R/C++ suits this project well.

**Comment by karthik** [comment]
@fabian-s Would you be able to review this submission for us?

**Comment by fabian-s** [comment]
Will do.

**Comment by karthik** [comment]
@whedon assign @fabian-s as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @fabian-s

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/910. Feel free to close this issue now!

**Comment by karthik** [comment]
@fabian-s Thank you! Please continue the review in #910 I'll close this issue. If you have any questions about the review process, feel free to reach out to me anytime. 🙏
