### ISSUE TITLE
[PRE REVIEW]: eights: BS 8888:2011 first angle projection drawings from FreeCAD 3D model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#908]
**Submitting author:** @danielhatton (<a href="http://orcid.org/0000-0002-4585-3336">Daniel Hatton</a>)
**Repository:** <a href="https://github.com/danielhatton/eights/" target ="_blank">https://github.com/danielhatton/eights/</a>
**Version:** 0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @devinberg

**Author instructions**

Thanks for submitting your paper to JOSS @danielhatton. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@danielhatton if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00908/joss.00908/10.21105.joss.00908.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielhatton thanks for your submission. 
One of the JOSS [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) is: 

> The software should have an obvious research application

It is clear to me that this work offers a useful means to automate the creation of 2D drawings for FreeCAD 3D models (which are BS 8888:2011 compliant). However can you elaborate on the use of the software in research, and how it may influence research outcomes.

**Comment by danielhatton** [comment]
On 27 August 2018 08:35:52 BST, Kevin Mattheus Moerman <notifications@github.com> wrote:
>@danielhatton thanks for your submission.
>One of the JOSS [submission
>requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)
>is:
>> The software should have an obvious research application
>It is clear to me that this work offers a useful means to automate the
>creation of 2D drawings for FreeCAD 3D models (which are BS 8888:2011
>compliant). However can you elaborate on the use of the software in
>research, and how it may influence research outcomes.




Good idea.  I'll dig out some relevant supporting literature and add an appropriate paragraph to the paper.  It might take me a couple of weeks, due to near-term undergraduate teaching commitments.


________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by danielhatton** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #908 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    122      0 --:--:-- --:--:-- --:--:--   122
Error reading bibliography ./paper.bib (line 117, column 12):
unexpected "U"
expecting white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielhatton** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00908/joss.00908/10.21105.joss.00908.pdf)

**Comment by danielhatton** [comment]
Dear Dr. Moerman,

I've added a paragraph to the statement of need in this paper, suggesting the applicability of the tool in research contexts.  Does it help?

**Comment by Kevin-Mattheus-Moerman** [comment]
@devinberg are you interested in reviewing this work?

**Comment by devinberg** [comment]
@Kevin-Mattheus-Moerman Sure, I can do this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @devinberg as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @devinberg

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/974. Feel free to close this issue now!
