### ISSUE TITLE
[REVIEW]: bor: An R Package for Transforming Behavioral Observation Records into Data Matrices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#909]
**Submitting author:** @davidnsousa (<a href="http://orcid.org/0000-0001-7277-6447">David Sousa</a>)
**Repository:** <a href="https://github.com/davidnsousa/bor" target ="_blank">https://github.com/davidnsousa/bor</a>
**Version:** v0.1.0
**Editor:** @karthik
**Reviewer:** @ViniciusBRodrigues
**Archive:** <a href="https://doi.org/10.5281/zenodo.1405098" target="_blank">10.5281/zenodo.1405098</a>

## Status

[![status](http://joss.theoj.org/papers/03ad4d832eb94173552f31d8a25dceb4/status.svg)](http://joss.theoj.org/papers/03ad4d832eb94173552f31d8a25dceb4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/03ad4d832eb94173552f31d8a25dceb4"><img src="http://joss.theoj.org/papers/03ad4d832eb94173552f31d8a25dceb4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/03ad4d832eb94173552f31d8a25dceb4/status.svg)](http://joss.theoj.org/papers/03ad4d832eb94173552f31d8a25dceb4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/davidnsousa/bor" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ViniciusBRodrigues, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/davidnsousa/bor">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@davidnsousa) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ViniciusBRodrigues it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00909/joss.00909/10.21105.joss.00909.pdf)

**Comment by ViniciusBRodrigues** [comment]
Hi @davidsousa, almost done!

There are few small stuffs to add in your repository to complete:
  * Automated test
  * Community guidelines (how people can contribute and report issues)

In pratical words: you need to create a folder with a R script for tests, like [here](https://github.com/williamsbenjamin/blendR). Also you can see how do it better [here](https://www.r-bloggers.com/unit-testing-with-r); Please, add the contact and how to contribute with the package in the README.md (that is, how the users can get help? email? Github? How to contribute?).

Best,

**Comment by ViniciusBRodrigues** [comment]
Hi @karthik,

It's everything fine right now. Review is complete. Many thanks!

**Comment by karthik** [comment]
Thanks @ViniciusBRodrigues!

**Comment by karthik** [comment]
@davidnsousa Can you please archive your software on [Zenodo](https://zenodo.org/) with the appropriate metadata and post the DOI here? 🙏

**Comment by davidnsousa** [comment]
hello @karthik! The software is already archived in zenodo. Here is the DOI ![image](https://user-images.githubusercontent.com/5941390/44738244-3734a180-aaec-11e8-9adf-40e2de6e5b6d.png)

Thank you

**Comment by karthik** [comment]
@davidnsousa did you archive before or after the review?

**Comment by davidnsousa** [comment]
@karthik before the review

**Comment by karthik** [comment]
@davidnsousa In that case you'll need to create a new Zenodo release and post that DOI here.

**Comment by davidnsousa** [comment]
@karthik here it is 
![image](https://user-images.githubusercontent.com/5941390/44740510-8f6ea200-aaf2-11e8-8756-228d4586ef54.png)

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.1405098 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1405098" target="_blank">10.5281/zenodo.1405098</a> is the archive.

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00909/joss.00909/10.21105.joss.00909.pdf)

**Comment by karthik** [comment]
Congrats @davidnsousa, your paper has been accepted. And thank you @ViniciusBRodrigues for the fast and timely review!  🎉

@arfon over to you for final processing.

**Comment by davidnsousa** [comment]
Thank you guys!! :D

**Comment by arfon** [comment]
@ViniciusBRodrigues - many thanks for your review here and to @karthik for editing this submission ✨ 

@davidnsousa - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00909 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00909/status.svg)](https://doi.org/10.21105/joss.00909)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00909">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00909/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00909/status.svg)](https://doi.org/10.21105/joss.00909)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by davidnsousa** [comment]
@arfon thank you! There are just two things that I have just notice. 1) the first reference in the text (Sousa & Daniel, 2018) should point to the DOI of the package in References but the DOI does not appear. Can I still remove this reference maybe it is not necessary. 2) The group of references in the first paragraph 1974, 1998 and 1993 does not appear to be in the right format in the text. Sorry that I only noticed this now. Is it still possible to correct these issues? Thank you very much for your help.

Best,

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00909/joss.00909/10.21105.joss.00909.pdf)

**Comment by arfon** [comment]
@davidnsousa - I suspect this is just the APA style for `@manual` etc. based on your entries in the bibtex: https://github.com/davidnsousa/bor/blob/master/paper.bib

Feel free to experiment with modifications to your bibtex here (in `master` on your repository) and use @whedon to rebuild the paper with `@whedon generate pdf`

**Comment by davidnsousa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00909/joss.00909/10.21105.joss.00909.pdf)

**Comment by davidnsousa** [comment]
@arfon thank you! These issues are now corrected!
