### ISSUE TITLE
[REVIEW]: qsort R package: A New Tool for Scoring Q-sort Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#911]
**Submitting author:** @davidnsousa (<a href="http://orcid.org/0000-0001-7277-6447">David Sousa</a>)
**Repository:** <a href="https://github.com/joaordaniel/qsort" target ="_blank">https://github.com/joaordaniel/qsort</a>
**Version:** v0.2.0
**Editor:** @leeper
**Reviewer:** @maxheld83
**Archive:** <a href="https://doi.org/10.5281/zenodo.1844717" target="_blank">10.5281/zenodo.1844717</a>

## Status

[![status](http://joss.theoj.org/papers/d691db3ee91ae5c10e26464ddda1bd2e/status.svg)](http://joss.theoj.org/papers/d691db3ee91ae5c10e26464ddda1bd2e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d691db3ee91ae5c10e26464ddda1bd2e"><img src="http://joss.theoj.org/papers/d691db3ee91ae5c10e26464ddda1bd2e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d691db3ee91ae5c10e26464ddda1bd2e/status.svg)](http://joss.theoj.org/papers/d691db3ee91ae5c10e26464ddda1bd2e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/joaordaniel/qsort" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@maxheld83, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/joaordaniel/qsort">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@davidnsousa) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @maxheld83 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00911/joss.00911/10.21105.joss.00911.pdf)

**Comment by leeper** [comment]
@maxheld83 Here's the review issue. Above you will find a checklist of issues we would like you to complete related to the submitted software and article. If there's anything missing or if there are changes to the software you would like to see, please open Github issues on the source repository.

Let me know if you have any questions about the process. Thanks, again, for volunteering to review!

**Comment by maxheld83** [comment]
re: **conflict of interest**, just to keep this on the record:
As I mentioned previously to @leeper I've been a (minor) contributor to the [qmethod](https://github.com/aiorazabala/qmethod) package, and am the author of the yet-in-dev [pensieve](https://github.com/maxheld83/pensieve/) package. 
Both are R packages for analysing Q methodological data, and might thus be conceived as "competitors" to the package under review here.
On closer inspection, the overlap in functionality is pretty small / nonexistent.

**Comment by leeper** [comment]
Thanks for the disclosure, @maxheld83. In my judgment this does not a conflict of interest as defined in [our policy](https://github.com/openjournals/joss/blob/master/COI.md).

**Comment by maxheld83** [comment]
re: **authorship**

it appears that most of the substantive commits are made by @joaordaniel, with @davidnsousa doing the paper and JOSS stuff. 
Both are listed as paper authors, so that makes sense.

**Comment by maxheld83** [comment]
re: **automated tests**

as far as I can see, there are currently no unit or otherwise automated tests, no cross-validation against published results or input validation.

**Comment by maxheld83** [comment]
I've raised a bunch of separate issues in the source repo, and am done with my review for now.

Here's a bit of overall feedback cc @leeper @joaordaniel @davidnsousa:

My suggestion would be to do **major revisions** before accepting the package (with an important caveat, see below).

These kinds of specialized packages can do a great service to a community of researchers, by making their every day *very* domain specific tasks a lot easier. It's a tremendous and laudable effort to build this kind of package for a community.

That being said, in my opinion, a package also shouldn't be *too* specific in its focus, monolithic in its design or arcane in the way it stores and handles data, because this can cause frustration with users, degrade the overall R experience, guide users away from better, more standard uses of R (ie. around tidy data), and, in the worst case, make a package vulnerable to bugs and reproducibility issues.

This is my chief concern with the package: it seems *very* specialised (on only 4 datasets!). This is also reflected in a **statement of need** which I suspect many users and newcomers can't quite follow, and the example usage and API documentation, both of which are pretty sparse and idiosyncratic at the same time. (See separate issues for detailed suggestions).

As the package stands now, I'm not 100% sure that users wouldn't be better off doing the (relatively simple) calculations "by hand", using more standard tools.

I would think that the community would benefit much more from a more granular package, with small, lean separate functions.
I'd hope that this would also be a way for the work of the submitters to see a greater impact.

----

Now, here's the **caveat** *with regard to my own review*:

I'm pretty familiar and experienced with Q methodology, but have (because of my own ignorance) never heard of this *particular* use/adaptation/extension to Q.
It is entirely possible that the community around these extensions is *so* focused on these 4 datasets (or something else) that the (otherwise excessive) specialisation of this package might be justified.

I am unable to speak to that. So, if the authors @joaordaniel @davidnsousa feel that I'm grossly misunderstanding the use case in this niche of a niche community (Q), which *is entirely possible* (science is weird like that), it might be a good idea to add a second reviewer @leeper.

Hope this is helpful.

**Comment by leeper** [comment]
Thanks, @maxheld83, for the very thorough review.

What I would suggest at this point is @joaordaniel and @davidnsousa take a look through the issues you've opened and the main points raised in your review here and see what they think they can respond to and address at this point. Please try to address as much of this as you can and ping me on this thread when you have an update ready to for further review. Then I'll have a look through and see how we should proceed, including consulting again with @maxheld83 and/or another reviewer.

**Comment by davidnsousa** [comment]
@leeper @maxheld83 thank you. All the issues have been answered,

best,

**Comment by joaordaniel** [comment]
We would like to thank @maxheld83 for his extensive review of the package. We have made some edits to the package to accommodate reviewer's concerns, but chose to maintain some of the code as it was. We present our motives to do so in the replies to specific issues.

We agree with the reviewer that this is a very specific package. It is mostly directed to researchers coming from developmental psychology- we have stressed this in the new version of the paper. For now the package only includes descriptions and scoring options for 4 qsets. These were chosen because there are the most commonly used in developmental psychology studies.

Although its focus is not very broad the package streamlines the data analysis required for researchers in this field. Calculations are quite simple, but when you have a lot of individual data, coming from different classrooms, observers etc., this process can became cumbersome. The functions we share here have made our life a lot easier, and we think researchers using qsets as we do will find this tool helpful as well.

Hope to hear your feedback on this revised version of the package.

**Comment by arfon** [comment]
@joaordaniel thanks for following up here. Could you be a little more specific about the edits/updates that you _have_ made based on @maxheld83's feedback?

**Comment by arfon** [comment]
Also :wave: folks. I'll be talking over as editor for this submission since @leeper has unfortunately had to resign his role with JOSS because of his new job.

**Comment by davidnsousa** [comment]
Dear Arfon @arfon ,

Thank your for getting back to us on our submission.

Reviewer Maximilian Held (@maxheld83) suggested some helpful changes to the github repository and the qsort package. Namely, adding community guidelines, automated units tests, and a vignnete to make the usage of the package more clear for users. We have revised our package accordingly and integrated proposed changes.

Also, Maximilian Held suggested we should change the way that the datasets, required to run our core function (qsort function), were organized. As suggested these datasets were tidied and stored as separate objects-the former list 'qsets' was broken down to 4 different objects (qset_ccq; qset_aqs; qset_mbqs; qset_pq). qsort functions’ code was edited to accommodate these changes.

Maximilian Held also suggested with edited the paper to better explain readers how this package could help them analyse Qsort data. We tried to give a more precise focus on the goals of this package- analyse Qsort data as is commonly done in Developmental Psychology studies. Consequently, we fell the manuscript is now more clear and better shows its potential merits.

Despite these helpful suggestions by Maximilian Held, we believe that changing our code to accommodate two other suggestions, rose in issues 7 and 11, to be a little counter-intuitive to the package's objectives- a fast, little-code required procedure for scoring Qsort data as commonly collected by developmental psychologists. As such we have not broken the qsort function into a number of “smaller” functions, nor the way the input data is specified. Considering the type of instrument used, and how data is stored by researchers using it we do not feel requested changes to be helpful for the users this package may appeal. Our only requirement for input data is that qset item’s columns/variables (scores of these columns are used to computed a set of new variables) to be in order from 1 to max number of qset items.

We hope the changes we made have made our manuscript and package reach the standards of JOSS.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00911/joss.00911/10.21105.joss.00911.pdf)

**Comment by arfon** [comment]
Hi @davidnsousa, thanks for this detailed summary of your changes. Firstly, one change I need you to make to the paper to fix your references formatting: https://github.com/joaordaniel/qsort/pull/13

I think @maxheld83's suggestions in https://github.com/joaordaniel/qsort/issues/11 and https://github.com/joaordaniel/qsort/issues/7 are good ones in fact, we've recently updated our submission requirements to better fit with feedback such as given in this issue: https://github.com/joaordaniel/qsort/issues/9

> - The software should be feature complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications).

This paper was submitting before these guidelines were updated so I don't think it's reasonable to hold this submission to exactly these requirements.

The primary goal of JOSS is to enable academic credit for authors of (open source) research software, a secondary (but very important) goal is to improve the quality of the software being produced by the research community.

This means that sometimes when reviewers and authors disagree on how a package should be constructed, we defer to the author. On balance, I think this is probably one of those times.

@maxheld83 - thanks for all of your efforts thus far. Could you take a look at the un-checked items on your reviewer checklist and see if you're able to verify some of these now?

**Comment by maxheld83** [comment]
@arfon thanks.

I've checked the remaining items off of my reviewer checklist above, though I still have reservations concerning the usability, maintainability and focus of the package, as I mentioned above. Among other things, I still think the package is too monolithic and idiosyncratic in its design, and does not follow (enough) software dev best practices, including defensive programming or reasonably extensive unit tests.

But I might be mistaken about the acceptance guidelines of JOSS, and @arfon's decision seems very reasonable to me.

In any event, I wouldn't want to spring such (contentious) demands on @davidnsousa  and @joaordaniel's generous work without it being a transparent JOSS  acceptance criteria.

I added a separate [issue over at joss](https://github.com/openjournals/joss/issues/469) to discuss the criteria.

**Comment by davidnsousa** [comment]
@arfon thank you for your fix. Merged!

@arfon @maxheld83 thank you both for your comments.

**Comment by arfon** [comment]
@davidnsousa - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by davidnsousa** [comment]
@arfon here is the updated DOI for the zenode archive [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1844717.svg)](https://doi.org/10.5281/zenodo.1844717)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1844717 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1844717" target="_blank">10.5281/zenodo.1844717</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/92

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/92, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/93
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00911](https://doi.org/10.21105/joss.00911)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@davidnsousa - I wonder if there's a way to truncate the output of your examples so they don't overflow the margins? We'll accept now and can tweak the appearance later if you want to.

**Comment by arfon** [comment]
@maxheld83 - many thanks for your review here ✨ 

@davidnsousa @joaordaniel - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00911/status.svg)](https://doi.org/10.21105/joss.00911)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00911">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00911/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00911/status.svg
   :target: https://doi.org/10.21105/joss.00911
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00911/status.svg)](https://doi.org/10.21105/joss.00911)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by davidnsousa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by davidnsousa** [comment]
@arfon @maxheld83 thank you both!

I fixed the margins issue. I attempted to generate a new pdf... I hope it s fixed.
