### ISSUE TITLE
[PRE REVIEW]: PTVResearch: Robust particle tracking for all types of research applications

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#913]
**Submitting author:** @jonnyhigham (<a href="http://orcid.org/0000-0001-7577-0913">Jonathan Higham</a>)
**Repository:** <a href="https://github.com/jonnyhigham/PTVResearch" target ="_blank">https://github.com/jonnyhigham/PTVResearch</a>
**Version:** v.1.0.1
**Editor:** @lheagy
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @jonnyhigham. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jonnyhigham if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor.

**Comment by jonnyhigham** [comment]
Many apologies. The license is now added.
Jonny

**Comment by Kevin-Mattheus-Moerman** [comment]
@jonnyhigham your submission currently only contains various "matlab project" and matlab app and app installation files. These are not deemed source code. If these files are one of the ways for users to install this work that is fine but for your work to be considered in JOSS you need to also provide the full source code for this submission. For instance add a folder containing all source .m files.

**Comment by jonnyhigham** [comment]
@Kevin-Mattheus-Moerman <http://biomech.media.mit.edu/kevin-m-moerman/> I
have now uploaded a .m file. However, the app itself is written in Matlab's
new AppDesigner (a drastic update to GUIDE). All of the code is actually in
the .mlapp file, this can be edited by typing  " appdesigner
PTVResearch.mlapp "  into Matlab. I decided to go this route as it seems
MathWorks are supporting more the development of this rather than GUIDE.

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@acabunoc
@arfon
@arokem
@brainstorm
@cMadan
@danielskatz
@george-githinji
@jakevdp
@jasonclark
@jedbrown
@karthik
@katyhuff
@kyleniemeyer
@labarba
@leeper
@lheagy
@mgymrek
@pjotrp
@tracykteal
@yochannah
```
