### ISSUE TITLE
[PRE REVIEW]: DataDepsGenerators.jl: making reusing data easy by automatically generating DataDeps.jl registration code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#914]
**Submitting author:** @oxinabox (<a href="http://orcid.org/0000-0003-1386-1646">Lyndon White</a>)
**Repository:** <a href="https://github.com/oxinabox/DataDepsGenerators.jl/" target ="_blank">https://github.com/oxinabox/DataDepsGenerators.jl/</a>
**Version:** v0.4.0
**Editor:** @arfon
**Reviewers:** @ninjin

**Author instructions**

Thanks for submitting your paper to JOSS @oxinabox. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@oxinabox if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #914 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by oxinabox** [comment]
@whedon commands

What can't you find, robo-buddy?

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by oxinabox** [comment]
@whedon generate pdf

Try again buddy

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00914/joss.00914/10.21105.joss.00914.pdf)

**Comment by oxinabox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00914/joss.00914/10.21105.joss.00914.pdf)

**Comment by juliohm** [comment]
I'd be happy to review @oxinabox after my PhD defense tomorrow :)

Thanks for pinging.

Cheers,

**Comment by juliohm** [comment]
@oxinabox I passed my defense! \o/ Everything is super busy around here though as I am relocating, moving out from California, and submitting the final draft of the dissertation to the university. I thought I would have time to review your paper, but I am super busy wrapping up. Will join a vacation trip in the next weeks, which will literally put me offline for some time.

I appreciate if other Julians from your list of suggested reviewers can help: @vchuravy @ahwillia @ChrisRackauckas @ninjin

**Comment by ninjin** [comment]
Yes, I would be happy to review this.

**Comment by oxinabox** [comment]
Thanks @ninjin 

@juliohm enjoy your break :-D.

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00914/joss.00914/10.21105.joss.00914.pdf)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @ninjin as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ninjin

**Comment by arfon** [comment]
Thanks for agreeing to review this submission @ninjin. I'll go ahead and set up the main review issue now...

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/921. Feel free to close this issue now!

**Comment by arfon** [comment]
@oxinabox @ninjin - please head over to #921 where the actual review will take place.
