### ISSUE TITLE
[PRE REVIEW]: graynet: single-subject morphometric networks for neuroscience connectivity applications

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#915]
**Submitting author:** @raamana (<a href="http://orcid.org/0000-0003-4662-0558">Pradeep Reddy Raamana</a>)
**Repository:** <a href="https://github.com/raamana/graynet" target ="_blank">https://github.com/raamana/graynet</a>
**Version:** v0.3.9
**Editor:** @arokem
**Reviewers:** rougier

**Author instructions**

Thanks for submitting your paper to JOSS @raamana. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@raamana if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #915 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the handling editor

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #915 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    166      0 --:--:-- --:--:-- --:--:--   168
pandoc-citeproc: reference brett2016nibabel not found
pandoc-citeproc: reference hunter2007matplotlib not found
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00915.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by raamana** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00915/joss.00915/10.21105.joss.00915.pdf)

**Comment by raamana** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00915/joss.00915/10.21105.joss.00915.pdf)

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
@raamana : do you have any suggestions for reviewers?

**Comment by raamana** [comment]
Thanks Ariel for agreeing to handle this. Let me think about potential reviewers and get back to you!

**Comment by raamana** [comment]
How about https://github.com/rougier or https://github.com/nirum?

**Comment by raamana** [comment]
Michael would be good too, but he is already helping us with mrivis. So another candidate  https://github.com/kristianeschenburg ?

**Comment by rougier** [comment]
@arokem Sure.

**Comment by rougier** [comment]
By the way, @GaelVaroquaux can be also a potential reviewer.

**Comment by arokem** [comment]
@whedon assign rougier as reviewer

**Comment by whedon** [comment]
OK, the reviewer is rougier

**Comment by arokem** [comment]
Thanks @rougier! I'll start the review after we resolve the existence and identity of a second reviewer.

**Comment by arokem** [comment]
👋 @GaelVaroquaux: would you be available to review this JOSS paper?

**Comment by GaelVaroquaux** [comment]
> 👋 @GaelVaroquaux: would you be available to review this JOSS paper?

Sorry, I am way behind everything (including reviews). I've been
traveling for a month straight. It's exhausting!

**Comment by arokem** [comment]
OK. Let's go with one reviewer for this. Thanks!

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/924. Feel free to close this issue now!

**Comment by arokem** [comment]
@rougier : please head over to #924 for the reviewer check-list. I'm closing this one.
