### ISSUE TITLE
[REVIEW]: nestcheck: error analysis, diagnostic tests and plots for nested sampling calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#916]
**Submitting author:** @ejhigson (<a href="http://orcid.org/0000-0001-8383-4614">Edward Higson</a>)
**Repository:** <a href="https://github.com/ejhigson/nestcheck" target ="_blank">https://github.com/ejhigson/nestcheck</a>
**Version:** v0.1.5
**Editor:** @arfon
**Reviewer:** @ziotom78, @mattpitkin
**Archive:** <a href="https://doi.org/10.5281/zenodo.1418657" target="_blank">10.5281/zenodo.1418657</a>

## Status

[![status](http://joss.theoj.org/papers/5abb55cf6e8685e3dd61082fe7999c1a/status.svg)](http://joss.theoj.org/papers/5abb55cf6e8685e3dd61082fe7999c1a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5abb55cf6e8685e3dd61082fe7999c1a"><img src="http://joss.theoj.org/papers/5abb55cf6e8685e3dd61082fe7999c1a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5abb55cf6e8685e3dd61082fe7999c1a/status.svg)](http://joss.theoj.org/papers/5abb55cf6e8685e3dd61082fe7999c1a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ejhigson/nestcheck" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ziotom78 & @mattpitkin, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ejhigson/nestcheck">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.5)?
- [x] **Authorship:** Has the submitting author (@ejhigson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ejhigson/nestcheck">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.5)?
- [x] **Authorship:** Has the submitting author (@ejhigson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ziotom78, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00916/joss.00916/10.21105.joss.00916.pdf)

**Comment by mattpitkin** [comment]
@ejhigson Sorry for the delay in starting the review, but I'm getting started now.

First, some easy fixes. In the references could you:

* add the DOI for the Matplotlib paper https://doi.org/10.1109/MCSE.2007.55
* add the arXiv URL for the "Importance Nested Sampling..." paper https://arxiv.org/abs/1306.2144

**Comment by mattpitkin** [comment]
Just a small request and query for the "Quickstart demo".

In the "**Calculating errors due to implementation-specific effects**" [section](https://nestcheck.readthedocs.io/en/latest/demos/quickstart_demo.html#Calculating-errors-due-to-implementation-specific-effects) could you state explicitly that this requires you to have multiple run (I know this is kind of covered in the next section, but it would be useful to have it).

In the "**Tests for implementation specific effects using only 2 nested sampling runs**" [section](https://nestcheck.readthedocs.io/en/latest/demos/quickstart_demo.html#Tests-for-implementation-specific-effects-using-only-2-nested-sampling-runs) should the line:

> As expected, the p-values are not particularly low nor are the KS distances particularly high - indicating there are significant implementation-specific effects for the simple 2-dimensional Gaussian

actually say

> As expected, the p-values are not particularly low nor are the KS distances particularly high - indicating there are **no** significant implementation-specific effects for the simple 2-dimensional Gaussian

**Comment by mattpitkin** [comment]
Would you be able to add some more information to the documentation about how to go about allowing samples from different nested sampling codes to be read in to `nestcheck`? I.e., what should a code output to allow you to use it with `nestcheck` through a custom `process_XXXX_runs` function? I see from the [`process_dynesty_runs`](https://github.com/ejhigson/nestcheck/blob/master/nestcheck/data_processing.py#L254) source that it seems to need values of the log likelihood, the actual sample values, the number of live points, and the sample ID - is the sample ID the order with which that sample was used for the nested sample integral (i.e., when that point "died")? What is a "thread" in this context?

**Comment by ziotom78** [comment]
@arfon, I'll have a look at it in the next days, I've come back from holidays just last week and am still trying to catch up things…

**Comment by ziotom78** [comment]
@arfon, I have downloaded the two papers cited by the package's authors and have discovered that they used it for work related to the Planck project, to whom I have belonged for a long time. I do not think there is a clear conflict of interest, as I have never interacted with any of the authors about the topics covered here. However, the JOSS Code of Conduct states clearly that I need to report this.

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00916/joss.00916/10.21105.joss.00916.pdf)

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00916/joss.00916/10.21105.joss.00916.pdf)

**Comment by mattpitkin** [comment]
@ejhigson would you be able to add a `__version__` parameter to the package, so that:

```python
print(nestcheck.__version__)
```

gives the current version information.

**Comment by ejhigson** [comment]
@mattpitkin thank you very much for your comments! I think I have addressed them - please let me know if there is anything else I should add or change.

> * add the DOI for the Matplotlib paper https://doi.org/10.1109/MCSE.2007.55
> * add the arXiv URL for the "Importance Nested Sampling..." paper https://arxiv.org/abs/1306.2144

Added.

> In the "**Calculating errors due to implementation-specific effects**" [section](https://nestcheck.readthedocs.io/en/latest/demos/quickstart_demo.html#Calculating-errors-due-to-implementation-specific-effects) could you state explicitly that this requires you to have multiple run (I know this is kind of covered in the next section, but it would be useful to have it).

Added.

> In the "**Tests for implementation specific effects using only 2 nested sampling runs**" [section](https://nestcheck.readthedocs.io/en/latest/demos/quickstart_demo.html#Tests-for-implementation-specific-effects-using-only-2-nested-sampling-runs) should the line:
> 
> > As expected, the p-values are not particularly low nor are the KS distances particularly high - indicating there are significant implementation-specific effects for the simple 2-dimensional Gaussian
> 
> actually say
> 
> > As expected, the p-values are not particularly low nor are the KS distances particularly high - indicating there are **no** significant implementation-specific effects for the simple 2-dimensional Gaussian

You are correct - this is a (not insignificant) typo. Thank you for pointing it out! I have fix it.

> Would you be able to add some more information to the documentation about how to go about allowing samples from different nested sampling codes to be read in to `nestcheck`? I.e., what should a code output to allow you to use it with `nestcheck` through a custom `process_XXXX_runs` function? I see from the [`process_dynesty_runs`](https://github.com/ejhigson/nestcheck/blob/master/nestcheck/data_processing.py#L254) source that it seems to need values of the log likelihood, the actual sample values, the number of live points, and the sample ID - is the sample ID the order with which that sample was used for the nested sample integral (i.e., when that point "died")? What is a "thread" in this context?

I have added a guide to this in the module docstring of data_processing - let me know if this is ok/if it can be improved.

> @ejhigson would you be able to add a `__version__` parameter to the package, so that:
> 
> ```python
> print(nestcheck.__version__)
> ```
> 
> gives the current version information.

Added

**Comment by mattpitkin** [comment]
@ejhigson thanks, it all looks good to me.

**Comment by ziotom78** [comment]
Hi @ejhigson , I have started testing your package, I found an issue and reported it here: [#1](https://github.com/ejhigson/nestcheck/issues/1).

**Comment by ziotom78** [comment]
@ejhigson thanks for having fixed that problem so quickly! I have used the program and read the paper, for me everything looks ok.

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00916/joss.00916/10.21105.joss.00916.pdf)

**Comment by ejhigson** [comment]
@arfon I think the reviews are now complete. I have archived an up to date version on zenodo at 10.5281/zenodo.1418657

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1418657 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1418657" target="_blank">10.5281/zenodo.1418657</a> is the archive.

**Comment by arfon** [comment]
@ziotom78, @mattpitkin - many thanks for your reviews here ✨ 

@ejhigson - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00916 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00916/status.svg)](https://doi.org/10.21105/joss.00916)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00916">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00916/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00916/status.svg
   :target: https://doi.org/10.21105/joss.00916
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00916/status.svg)](https://doi.org/10.21105/joss.00916)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
