### ISSUE TITLE
[PRE REVIEW]: hIPPYlib: An Extensible Software Framework for Large-Scale Inverse Problems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#917]
**Submitting author:** @uvilla (<a href="http://orcid.org/0000-0002-5142-2559">Umberto Villa</a>)
**Repository:** <a href="https://github.com/hippylib/hippylib" target ="_blank">https://github.com/hippylib/hippylib</a>
**Version:** 2.1.0
**Editor:** @lheagy
**Reviewers:** @IgorBaratta, @boehmc

**Author instructions**

Thanks for submitting your paper to JOSS @uvilla. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@uvilla if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00917/joss.00917/10.21105.joss.00917.pdf)

**Comment by uvilla** [comment]
@whedon commands

**Comment by uvilla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00917/joss.00917/10.21105.joss.00917.pdf)

**Comment by uvilla** [comment]
Suggested reviewers

- @IgorBaratta: `hIPPYlib` relies on `FEniCS` for the discretization of the PDE, and for generating weak forms for the adjoint and incrementals problem. Since @IgorBaratta is a `FEniCS` developer he might be interested in reviewing `hIPPYlib`.

- @lheagy: She is working on inverse problem with geophysical applications

**Comment by arfon** [comment]
:wave: @lheagy - would you be willing to edit this submission for JOSS?

**Comment by uvilla** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by lheagy** [comment]
Hi @arfon, I am happy to edit this submission!

**Comment by arfon** [comment]
> Hi @arfon, I am happy to edit this submission!

Great, thanks @lheagy!

**Comment by lheagy** [comment]
:wave: Hi @IgorBaratta, would you be willing to review this submission for JOSS?

**Comment by lheagy** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by IgorBaratta** [comment]
> Hi @IgorBaratta, would you be willing to review this submission for JOSS?

Hi @lheagy , I'd be glad to review this submission.

**Comment by lheagy** [comment]
Excellent, thanks @IgorBaratta! I have sent out a few messages to other potential reviewers (hopefully we get 2).

**Comment by lheagy** [comment]
@whedon assign @IgorBaratta as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @IgorBaratta

**Comment by uvilla** [comment]
Thank you to @lheagy for serving as editor and @IgorBaratta for serving as reviewer!

**Comment by lheagy** [comment]
Hi @uvilla and @IgorBaratta, just a quick update - I have found another reviewer and am just waiting to get his github information. We can get the review started from there. Thanks for your patience!

**Comment by uvilla** [comment]
Thank you @lheagy

**Comment by lheagy** [comment]
@whedon add @boehmc as reviewer

**Comment by whedon** [comment]
OK, @boehmc is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/940. Feel free to close this issue now!
