### ISSUE TITLE
[PRE REVIEW]: nb:  Naive Bayes Model in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#918]
**Submitting author:** @renatorrsilva (<a href="http://orcid.org/0000-0002-1934-8141">Renato</a>)
**Repository:** <a href="https://github.com/renatorrsilva/nb" target ="_blank">https://github.com/renatorrsilva/nb</a>
**Version:** v0.1.0
**Editor:** @pjotrp
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @renatorrsilva. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@renatorrsilva if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #918 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:90:in `block in check_orcids': undefined method `has_key?' for ["name", "Renato Rodrigues Silva"]:Array (NoMethodError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by renatorrsilva** [comment]
Dear,

The line command

@whedon commands


Does not work.

2018-08-28 8:41 GMT-03:00 whedon <notifications@github.com>:

**Comment by renatorrsilva** [comment]
Recently, I 've submitted a paper to the journal called the journal open
source software and I received
an instruction from @whedom.

However ,


the line commands

@whedon commands

does not work and I received a error message by email.

I am completely lost. Can I help me with this?

Thank you.



2018-08-28 8:41 GMT-03:00 whedon <notifications@github.com>:

**Comment by arokem** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arokem** [comment]
@renatorrsilva : the way to use the whedon bot is to go to the GitHub web interface and enter exactly just one line into the comment box, containing `@whedon` followed by the command you want executed. For example:

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #918 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:90:in `block in check_orcids': undefined method `has_key?' for ["name", "Renato Rodrigues Silva"]:Array (NoMethodError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@renatorrsilva - please reformat your paper header to match the syntax shown here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

Specifically, your header:

```
---
title: 'nb:  Naive Bayes Model in R'
tags:
  - classification
  - machine learning
authors:
  name: Renato Rodrigues Silva
  orcid: 0000-0002-1934-8141
  affiliation: "1"
affiliations:
  - name: Federal University of Goias
    index: 1
date: 27 August 2018
bibliography: refs.bib
---
```

needs changing to:

```
---
title: 'nb:  Naive Bayes Model in R'
tags:
  - classification
  - machine learning
authors:
  - name: Renato Rodrigues Silva
    orcid: 0000-0002-1934-8141
    affiliation: "1"
affiliations:
  - name: Federal University of Goias
    index: 1
date: 27 August 2018
bibliography: refs.bib
---
```

**Comment by arfon** [comment]
@renatorrsilva - this PR should fix the paper compilation issues: https://github.com/renatorrsilva/nb/pull/1

**Comment by renatorrsilva** [comment]
I am sorry i did not understand what you are saying

Em ter, 4 de set de 2018 às 07:36, Arfon Smith <notifications@github.com>
escreveu:

**Comment by arfon** [comment]
@renatorrsilva - if you merge this pull request https://github.com/renatorrsilva/nb/pull/1 then the issues @whedon is having building the PDF (e.g. https://github.com/openjournals/joss-reviews/issues/918#issuecomment-417318265) should be fixed.

**Comment by renatorrsilva** [comment]
Hi I did



2018-09-04 11:02 GMT-03:00 Arfon Smith <notifications@github.com>:

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #918 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    161      0 --:--:-- --:--:-- --:--:--   162
Could not find bibliography file: refs.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@renatorrsilva - this change is also needed: https://github.com/renatorrsilva/nb/pull/2

**Comment by renatorrsilva** [comment]
I don't know why, the reference did not work.

2018-09-07 19:25 GMT-03:00 whedon <notifications@github.com>:

**Comment by arfon** [comment]
@renatorrsilva - please fix your references in `paper.bib`. The current ones you have are from the example paper, not the ones you are citing in your `paper.md` (i.e. none of these are in your `paper.bib ` file:  `@Russel:2003`, `@Koller:2009`, `@ElKourdi:2004`)

**Comment by arfon** [comment]
This is the current contents of `paper.bib`:

```
@online{GitHub,
  author = {GitHub},
  title = {GitHub.com},
  year = 2008,
  url = {https://github.com},
  urldate = {2016-02-14}
}

@online{figshare,
  author = {figshare},
  title = {figshare - credit for all your research},
  year = 2016,
  url = {https://figshare.com},
  urldate = {2016-02-14}
}

@online{Fidgit,
  author = {Arfon M Smith},
  title = {Fidgit: An ungodly union of GitHub and figshare},
  year = 2013,
  url = {https://github.com/arfon/fidgit},
  urldate = {2016-02-14}
}

@misc{figshare_archive,
  author = {{figshare Archive}},
  title = {Fidgit: An ungodly union of GitHub and figshare},
  doi = {10.6084/m9.figshare.828487},
  howpublished = {\url{https://doi.org/10.6084/m9.figshare.828487}}
}
```

**Comment by renatorrsilva** [comment]
Thank you Arfon,

I've just replaced the references of paper.bib.

2018-09-07 19:28 GMT-03:00 Arfon Smith <notifications@github.com>:

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00918/joss.00918/10.21105.joss.00918.pdf)

**Comment by arfon** [comment]
@renatorrsilva - this is looking much better. This PR (https://github.com/renatorrsilva/nb/pull/4 for the mult) will fix a small reference formatting issue for these multiple references:
```
Old: (Koller & Friedman, 2009, Al-Aidaroos, Bakar, & Othman (2010))

to

After fix: (Al-Aidaroos, Bakar, & Othman, 2010; Koller & Friedman, 2009)
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00918/joss.00918/10.21105.joss.00918.pdf)

**Comment by arfon** [comment]
@arokem - are you willing to edit this submission for JOSS?

**Comment by renatorrsilva** [comment]
Well, for me looks good, but  if you think is necessary to modify more
things, I can do.




2018-09-07 19:51 GMT-03:00 Arfon Smith <notifications@github.com>:

**Comment by arfon** [comment]
> Well, for me looks good, but  if you think is necessary to modify more things, I can do.

Yes, this looks good now. Next we need to find a JOSS editor to handle this submission through the review process.

**Comment by pjotrp** [comment]
I am happy to edit and look for a reviewer

**Comment by arfon** [comment]
> I am happy to edit and look for a reviewer

:zap: thanks @pjotrp

**Comment by pjotrp** [comment]
@renatorrsilva sorry for being quiet. I got some feedback on your method. A fellow editor wrote:

The naïve bayes algorithm is not novel. It is a well described algorithm and there are variants of the same in R (caret package) and in other languages. The code he has written could be novel in that that is his implementation if the algorithm. I am not sure what is new in this implementation, does it run faster? Does it use less memory compared to the implementation in caret? Would be nice to see such figures.

It would be nice to see some performance metrics relative to other packages that implement the same algorithm in R. Maybe do a quick table of feature comparison with other R packages?  In addition, I find interesting that they use the caret package for cross-validation and they don’t mention that caret has its own implementation of naïve Bayes.  There are also a couple of typos in the text that would need to be addressed to make the text more legible.

Before we look for a reviewer it would be good to address these comments. How do we go about that?

**Comment by renatorrsilva** [comment]
First of all, Many thanks for email.

I will try answer the questions

. "I am not sure what is new in this implementation, does it run faster?
Does it use less memory compared to the implementation in caret? Would be
nice to see such figures."
Answer: The reason that I wrote this package because I did not find a R
package that run naive Bayes model in a dataset which contains continuous
and discrete variables at the same time. But I can test the speed and
memory usage. Also, I will verify if R caret does what I am proposing

"In addition, I find interesting that they use the caret package for
cross-validation and they don’t mention that caret has its own
implementation of naïve Bayes."
Answer:  Sorry I did not see that function called train of the R caret
package has naive bayes implemented.

"There are also a couple of typos in the text that would need to be
addressed to make the text more legible."
I will check.

Do you have a deadline?

Thank you!

Em qua, 3 de out de 2018 às 18:27, Pjotr Prins <notifications@github.com>
escreveu:

**Comment by pjotrp** [comment]
There is no deadline. Main thing is to get a publication we can all be proud of :). If you can address these points we should be able to find a reviewer.

**Comment by labarba** [comment]
@renatorrsilva :wave Are you working on, or do you have plans to work on this submission to get to a reviewable stage? It's been nearly two months, and my assessment at this point is that the submission does not qualify as research software, but rather it appears to be a learning exercise by the author. 

My recommendation is to withdraw this submission.

**Comment by renatorrsilva** [comment]
Ok you can withdraw the submission.

Thank you.

Em qui, 22 de nov de 2018 às 11:09, Lorena A. Barba <
notifications@github.com> escreveu:
