### ISSUE TITLE
[PRE REVIEW]: imager: an R package for image processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#919]
**Submitting author:** @dahtah (<a href="http://orcid.org/0000-0003-0174-5058">Simon BARTHELME</a>)
**Repository:** <a href="https://github.com/dahtah/imager" target ="_blank">https://github.com/dahtah/imager</a>
**Version:** 0.41.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @jeroen, @NikEfth

**Author instructions**

Thanks for submitting your paper to JOSS @dahtah. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dahtah if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #919 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00919/joss.00919/10.21105.joss.00919.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@karthik @leeper I don't mind editing this submission but would you be able to help suggest reviewers? Thanks :rabbit:

**Comment by karthik** [comment]
I have a great reviewer in mind if he's available: @jeroen

**Comment by Kevin-Mattheus-Moerman** [comment]
@jeroen is this work of interest to you? Would you be able to help with review? Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth is this submission something you could review? Thanks

**Comment by jeroen** [comment]
Yes I can do the review

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @jeroen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jeroen

**Comment by Kevin-Mattheus-Moerman** [comment]
@jeroen the reviewer guidelines are here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

This is a pre-review issue and I aim to attract some more reviewers. Once I do I'll start the actual review issue and review process. Here is an [example of a review process](https://github.com/openjournals/joss-reviews/issues/890). As you can see the review process is guided by a set of tick boxes that will appear for you at the top of the review issue. 
Let me know if you have more questions.

**Comment by NikEfth** [comment]
I do not have tons of experience with R but I could check the image processing aspects.

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth thanks. Yes that would be great.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @NikEfth as reviewer

**Comment by whedon** [comment]
OK, @NikEfth is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah please let me know if you know any other potential reviewers

**Comment by dahtah** [comment]
@Kevin-Mattheus-Moerman, I'm sorry, the people I know at the intersection of R and image processing are all imager users or contributors, I'm not sure they'd be appropriate as reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah contributors would have a potential conflict of interest. Users of the software however may not so they could be potential reviewers. I'll start the review process now but we can add new reviewers at a later stage as well.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1012. Feel free to close this issue now!
