### ISSUE TITLE
[REVIEW]: edarf: Exploratory Data Analysis using Random Forests

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#92]
**Submitting author:** @zmjones (<a href="http://orcid.org/0000-0002-7523-0471">Zachary Jones</a>)
**Repository:** <a href="http://github.com/zmjones/edarf/" target ="_blank">http://github.com/zmjones/edarf/</a>
**Version:** 1.0.0
**Editor:** @cMadan
**Reviewer:** @PhilippPro
**Archive:** <a href="https://dx.doi.org/10.5281/zenodo.162238" target="_blank">https://dx.doi.org/10.5281/zenodo.162238</a>

## Status

[![status](http://joss.theoj.org/papers/d29df349c8450ef958c0fde5bf164371/status.svg)](http://joss.theoj.org/papers/d29df349c8450ef958c0fde5bf164371)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d29df349c8450ef958c0fde5bf164371"><img src="http://joss.theoj.org/papers/d29df349c8450ef958c0fde5bf164371/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d29df349c8450ef958c0fde5bf164371/status.svg)](http://joss.theoj.org/papers/d29df349c8450ef958c0fde5bf164371)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="http://github.com/zmjones/edarf/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://github.com/zmjones/edarf/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@zmjones) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00092.pdf](https://github.com/openjournals/joss-reviews/files/525302/10.21105.joss.00092.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by PhilippPro** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by cMadan** [comment]
@PhilippPro - The reviewer guidelines are here: http://joss.theoj.org/about#reviewer_guidelines

For the most part you need to see if the statements above in the first post are true and check things off accordingly (as you've already started). If something isn't the case, or you otherwise have a suggestion, just post a comment to @zmjones here (or ask me) and we'll sort things out until the submission meets all of JOSS' guidelines.

**Comment by PhilippPro** [comment]
I have posted in his issue tracker: https://github.com/zmjones/edarf/issues


I do not understand the last point, which also is not a complete sentence:

> References: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by cMadan** [comment]
@PhilippPro - perfect, thank you!

As for the references, I think there's a comma missing, but it otherwise reads fine to me. For each of the references in the compiled paper (https://github.com/openjournals/joss-reviews/files/525302/10.21105.joss.00092.pdf), is there a DOI. Here there are two references, neither of which have a DOI, but I expect both of them should have DOIs, so @zmjones will need to fix that in the bib file. (E.g., older papers may simply not have a DOI to list.)

**Comment by PhilippPro** [comment]
Ah ok, sorry I am not a native speaker and did not see "list" as verb. Thx!

**Comment by cMadan** [comment]
No problem! :)

**Comment by zmjones** [comment]
I added a doi for one article but couldn't find one for the Friedman 2001 article. I do have a jstor stable url that I could include though.

I also added two other papers which use this software, however they are unpublished. Is that ok? I see that it is necessary to talk about applications of the software to solve research problems.

**Comment by cMadan** [comment]
It looks like the doi for Friedman (2001) is 10.1214/aos/1013203451 (see http://projecteuclid.org/euclid.aos/1013203451#info). The publisher is also incorrect in being listed as JSTOR.

I think it's fine to cite 'jones2015exploratory' as a conference paper, though I think the booktitle start with "Proceedings of" rather than "Prepared for". If you think there is a stable url, I would appreciate you including it here, but I'll leave that to your discretion.

For 'jones2016there', some additional details should be included, or it should be listed as @unpublished (rather than @article).

**Comment by zmjones** [comment]
Thanks. Made all of those changes.

**Comment by cMadan** [comment]
@PhilippPro - have you had a chance to take to try out the package since @zmjones has made the recent changes? Thanks again!

**Comment by PhilippPro** [comment]
I will finish the review by the end of the week as mentioned in the other issue. ;)

**Comment by cMadan** [comment]
@PhilippPro - great, thanks! I must've missed that comment.

**Comment by PhilippPro** [comment]
Ok, I think I am done and hope that I have checked everything relevant.

**Comment by cMadan** [comment]
@PhilippPro - awesome, thank you!

@zmjones - everything looks good to me! I think the only thing left then is to archive the repository in a service such as Zenodo or figshare and let us know the associated doi.

@arfon - just pinging you to let you know that we're almost all set here!

**Comment by zmjones** [comment]
done. i added a link to the zenodo doi in the readme too

 DOI: 10.5281/zenodo.162238

**Comment by arfon** [comment]
@zmjones - it looks like there aren't any ORCID fields present in the `paper.md` metadata. We like authors to always have these if they have an academic affiliation - can you add these please?

**Comment by zmjones** [comment]
yep sure. just name the field orcid?

**Comment by arfon** [comment]
:zap: thanks. Just like this:

```  authors:
   - name: Arfon M Smith
     orcid: 0000-0002-3957-2474
     affiliation: 1
   - name: Mickey Mouse
     orcid: 0000-0000-0000-1234
     affiliation: 2
```

**Comment by zmjones** [comment]
ok cool, that is what we did. we are all set then!

**Comment by arfon** [comment]
@zmjones - your paper is now accepted into JOSS and the DOI is http://dx.doi.org/10.21105/joss.00092

@PhilippPro many thanks for reviewing this one!
