### ISSUE TITLE
[PRE REVIEW]: bem: Modeling for Neutron Bragg-Edge Imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#920]
**Submitting author:** @Yxqd (<a href="http://orcid.org/0000-0001-9233-0100">Jiao Lin</a>)
**Repository:** <a href="https://github.com/ornlneutronimaging/braggedgemodeling" target ="_blank">https://github.com/ornlneutronimaging/braggedgemodeling</a>
**Version:** v0.1.1
**Editor:** @katyhuff
**Reviewers:** @stuartcampbell, @mikapfl, @katyhuff

**Author instructions**

Thanks for submitting your paper to JOSS @Yxqd. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Yxqd if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00920/joss.00920/10.21105.joss.00920.pdf)

**Comment by arfon** [comment]
:wave: @lheagy - would you be able to edit this submission for JOSS?

**Comment by lheagy** [comment]
Hi @arfon, this is a ways outside of my background, I can help if need be, but this might be closer to @katyhuff's background??

**Comment by arfon** [comment]
> Hi @arfon, this is a ways outside of my background, I can help if need be, but this might be closer to @katyhuff's background??

OK, no worries. @katyhuff - is this something you could take on?

**Comment by katyhuff** [comment]
Yes, this is definitely something I can be the editor for.

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
This looks like a very interesting submission @yxqd . I'm now beginning the process of selecting reviewers. If you have recommendations for reviewers, I'm open to hearing them. That said, they'll need to be free of any conflict of interest with the work. Thanks!

**Comment by katyhuff** [comment]
@jwuttke @mdoucet @stuartcampbell @mikapfl @marcocamma : All of you seem to be eminently qualified to review this JOSS submission ["bem: Modeling for Neutron Bragg-Edge Imaging"](https://github.com/openjournals/joss-papers/blob/joss.00920/joss.00920/10.21105.joss.00920.pdf). 

Would any of you be interested in reviewing it and available to do so soon?

**Comment by stuartcampbell** [comment]
@katyhuff I would probably have time to do it next week if that's ok.

**Comment by katyhuff** [comment]
@whedon assign @stuartcampbell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stuartcampbell

**Comment by katyhuff** [comment]
Thanks @stuartcampbell for your prompt response! Hopefully one or two of the others will also be available in the next few weeks to look this over. ( @jwuttke @mdoucet @mikapfl @marcocamma )

**Comment by mdoucet** [comment]
@katyhuff I'd normally be happy to help, but I work with the author so I should pass on this one.

**Comment by katyhuff** [comment]
Thanks for letting me know @mdoucet !

**Comment by stuartcampbell** [comment]
@katyhuff Just for complete transparency, I was in the same group as @yxqd until January 2017.  But I wasn't involved in this work.

**Comment by katyhuff** [comment]
@stuartcampbell Sorry I missed that -- Consider where you think you land in the COI policy. I think this might be a borderline case, but the assessment of COI is up to you https://github.com/openjournals/joss/blob/master/COI.md

**Comment by yxqd** [comment]
Thanks, guys. I have not yet collaborated with either @stuartcampbell or @mdoucet on any published works. But yes @mdoucet and I are in the same group, and @stuartcampbell and I overlapped for a bit more than a year at ORNL.

**Comment by stuartcampbell** [comment]
@katyhuff I think I am ok, I recently reviewed something with a similar COI and @arfon agreed I wasn't conflicted!

**Comment by katyhuff** [comment]
@yxqd I would like one more reviewer with no conflict of interest or appearance of a conflict of interest. @jwuttke @mikapfl @marcocamma : would any of you be willing to review this JOSS paper?

**Comment by mikapfl** [comment]
Hi,

I could do a review of the documentation and code, but I can't really say anything about the physics since I haven't worked with Neutrons yet.

Cheers,

Mika

**Comment by katyhuff** [comment]
@mikapfl This would be great, I'll also do a review to bolster the neutron part.

**Comment by katyhuff** [comment]
@whedon add @mikapfl as reviewer

**Comment by whedon** [comment]
OK, @mikapfl is now a reviewer

**Comment by katyhuff** [comment]
@whedon add @katyhuff as reviewer

**Comment by whedon** [comment]
OK, @katyhuff is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/973. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Sorry for the delay on my part @yxqd .  @stuartcampbell @mikapfl , let's start the review over in #973. I'll close this pre-review issue now.
