### ISSUE TITLE
[REVIEW]: DynaML: Scala Library/REPL for Machine Learning Research 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#922]
**Submitting author:** @mandar2812 (<a href="http://orcid.org/0000-0001-6025-7113">Mandar Chandorkar</a>)
**Repository:** <a href="https://github.com/transcendent-ai-labs/DynaML" target ="_blank">https://github.com/transcendent-ai-labs/DynaML</a>
**Version:** v1.5.3-beta.2
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @tovbinm, @hclent, @thomasabeel
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/a561bdd3e960c5b0718c67c3f73c6f3b/status.svg)](http://joss.theoj.org/papers/a561bdd3e960c5b0718c67c3f73c6f3b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a561bdd3e960c5b0718c67c3f73c6f3b"><img src="http://joss.theoj.org/papers/a561bdd3e960c5b0718c67c3f73c6f3b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a561bdd3e960c5b0718c67c3f73c6f3b/status.svg)](http://joss.theoj.org/papers/a561bdd3e960c5b0718c67c3f73c6f3b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/transcendent-ai-labs/DynaML" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tovbinm, @hclent, @thomasabeel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/transcendent-ai-labs/DynaML">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.5.3-beta.2)?
- [x] **Authorship:** Has the submitting author (@mandar2812) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
---

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/transcendent-ai-labs/DynaML">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.5.3-beta.2)?
- [x] **Authorship:** Has the submitting author (@mandar2812) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

---

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/transcendent-ai-labs/DynaML">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.5.3-beta.2)?
- [x] **Authorship:** Has the submitting author (@mandar2812) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tovbinm it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00922/joss.00922/10.21105.joss.00922.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @hclent as reviewer

**Comment by whedon** [comment]
OK, @hclent is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @thomasabeel as reviewer

**Comment by whedon** [comment]
OK, @thomasabeel is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@tovbinm, @hclent, @thomasabeel this is where the review takes place. There are sets of check boxes at the top of this issue for each of you. Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tovbinm, @hclent, @thomasabeel sorry for adding you in the preview issue and again here. I accidentally replaced rather than add the review twice. Anyway we should be all set now. :rocket: :robot:

**Comment by tovbinm** [comment]
The [List of Contributors](https://transcendent-ai-labs.github.io/DynaML/about/#contributors) is missing the `sisirkoppaka` and `gitter-badger`.

**Comment by tovbinm** [comment]
**RE: Example usage**: Most examples of usage do not contain the actual data points, but rather only specify the type `val data: Stream[(DenseVector[Double], Double)] = _`. It could be useful to introduce a convenient object to allow retrieving some sample data from, e.g
```scala
val data: Stream[(DenseVector[Double], Double)] = Samples.Streams.stockPrices
```

**Comment by tovbinm** [comment]
**RE: Automated Tests:** - I looked into TravisCI builds and I could not find any tests being executed there, since the command is `sbt clean stage`, which clearly only runs the build without tests. I also noticed that nothing is reported into Codecov (https://codecov.io/gh/transcendent-ai-labs/DynaML), which I think should be fixed.

**Comment by tovbinm** [comment]
Minor: Contributing and Code of Conduct are not linked from https://transcendent-ai-labs.github.io/DynaML, but only from the README.

**Comment by tovbinm** [comment]
@Kevin-Mattheus-Moerman I am done with my review. Please let me know if any more actions are required.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @tovbinm for that speedy review! :rocket: I'll ping you once @mandar2812 has worked on the issues you've raised.

**Comment by hclent** [comment]
@Kevin-Mattheus-Moerman I have gone through all of the bullet points, and checked off as many as I could. There are a few places where I do not believe the criteria has been fully met, or at least it needs a bit more work before publication, which I will describe below:

### Comments

* General checks and functionality were all fine
* Documentation needs improvement
    * Motivation, installation, and the examples were all good.
    * I checked off `functionality documentation` because there is decent documentation in `docs` **BUT** I think that the actual source code needs link back to these. For example, [GeneralizedLinearModel.scala](https://github.com/transcendent-ai-labs/DynaML/blob/8a565e1da39e2c28294a976becf837d40ef2c7d1/dynaml-core/src/main/scala-2.11/io/github/mandar2812/dynaml/models/lm/GeneralizedLinearModel.scala) should have a link back to [the documentation](https://transcendent-ai-labs.github.io/DynaML/core/core_glm/), and the documentation should have a link back to the class. The code and the docs are oddly disconnected, which means that an unnecessary amount of digging around has to be done by the users to get back to the source code, in my opinion. 
    * So I can see that the [TRAVIS build](https://travis-ci.org/transcendent-ai-labs/DynaML) is passing, but looking at the tests, I think there needs to be more documentation. I could not find any documentation about _which_ tests in `dynaml-core/src/test` that a potential contributor needs to update if they are going to contribute or about how the testing process plays into contribution at all.
    * Some tests seem incomplete, for example [WaveletSpec.scala](https://github.com/transcendent-ai-labs/DynaML/blob/master/dynaml-core/src/test/scala-2.11/io/github/mandar2812/dynaml/wavelets/WaveletSpec.scala)
* Per the statement of need in the software paper, the author(s) describe what `dynaml` gives (e.g. its end-to-end), but I don't think the need for anything is explained _explicitly_, and it should be! A good way to do this could be by citing other ML softwares that work on the JVM, and what `dynaml` has that they don't. 

All in all, this is a really cool project and I think that a few additional updates to documentation and the paper will make it suitable for publication :)

**Comment by hclent** [comment]
@Kevin-Mattheus-Moerman Now that all of the initial reviews are in (sorry, everyone, that mine was so late!!), is there anything that should be done on the part of the reviewers?

**Comment by Kevin-Mattheus-Moerman** [comment]
@hclent thanks for your comments. At this point the author needs to address the issues raised. I'll ping you here if we require your feedback, thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@mandar2812 how are you getting on? Can you formulate a reply to the issues raised by the reviewers? Thanks.

**Comment by mandar2812** [comment]
Hi @Kevin-Mattheus-Moerman, sorry for the delayed response. I am currently in the final year of my PhD, although I really appreciate the feedback from the referees. This will require significant investment of time from me. 

If it is possible to give me a few months to make progress on this, it would be great. If that is not possible, I accept whatever decision that you want to make regarding this submission.

Thank you all for your time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mandar2812 In order to ensure we do not loose track of the reviewers I do recommend that you work on this as soon as possible, however we can pause this submission for now and await your work in a couple of months.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon how do we assign a "pause" label here?

**Comment by arfon** [comment]
> @arfon how do we assign a "pause" label here?

Just use the label picker on the top right of the issue ☝️

**Comment by Kevin-Mattheus-Moerman** [comment]
@mandar2812 hope you are doing well on your PhD. Any thoughts on when to resume the review of this submission?

**Comment by labarba** [comment]
@mandar2812 last [commented on Nov 20, 2018](https://github.com/openjournals/joss-reviews/issues/922#issuecomment-440215126) that time was scarce to work on the improvements requested during review. It has now been nearly 6 months, and we should either have a commitment from the author that they will work on this revision, or withdraw the submission.

**Comment by mandar2812** [comment]
Yes, I would like to withdraw this submission.

**Comment by labarba** [comment]
OK, @mandar2812, we will withdraw it. You can make a new submission later on, when you have time to work on the project. Please link to this closed issue when you do so.
