### ISSUE TITLE
[PRE REVIEW]: Embeddings.jl: easy access to pretrained word embeddings from julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#923]
**Submitting author:** @oxinabox (<a href="http://orcid.org/0000-0003-1386-1646">Lyndon White</a>)
**Repository:** <a href="https://github.com/JuliaText/Embeddings.jl/" target ="_blank">https://github.com/JuliaText/Embeddings.jl/</a>
**Version:** v0.3.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @aviks

**Author instructions**

Thanks for submitting your paper to JOSS @oxinabox. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@oxinabox if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00923/joss.00923/10.21105.joss.00923.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@weijianzhang is this submission of interest to you? Would you be able to help review it for [JOSS](http://joss.theoj.org/)? Thanks.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00923/joss.00923/10.21105.joss.00923.pdf)

**Comment by AsafManela** [comment]
I cannot, too busy these days. Sorry,

- Asaf

**Comment by Kevin-Mattheus-Moerman** [comment]
@weijianzhang @aviks @hshindo @johnmyleswhite @abelsiqueira @dpo @vchuravy is this submission of interest to you? Would you be able to help review it for  [the Journal of Open Source Software (JOSS)](http://joss.theoj.org/)? 

The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#the-joss-review-process) focuses on [the software :floppy_disk:](https://github.com/JuliaText/Embeddings.jl/), and a [short paper :scroll:](https://github.com/openjournals/joss-papers/blob/joss.00923/joss.00923/10.21105.joss.00923.pdf). 

Let me know if you have questions. Thanks.

**Comment by oxinabox** [comment]
Prods @aviks since this package came up in your JuliaCon tutorial, I know you've already used it.

**Comment by abelsiqueira** [comment]
Sorry, I have no expertise on the subject. Our NLP stands for Nonlinear Programming.

**Comment by Kevin-Mattheus-Moerman** [comment]
@abelsiqueira thanks for your reply, my sincere apologies for this mix up.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @aviks as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @aviks

**Comment by oxinabox** [comment]
@Kevin-Mattheus-Moerman  is this now able to move from Pre-Review to Review?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ssfrr would you be able to help review this submission?

**Comment by xuedong** [comment]
@Kevin-Mattheus-Moerman Hi, I only have a limited experience on NLP, I don't know if I'm well qualified for this review.

**Comment by ssfrr** [comment]
@Kevin-Mattheus-Moerman similarly I have machine learning experience but not NLP specifically. I'm happy to review for software/documentation quality I can't really speak to whether the included embeddings are the best choices for NLP.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1013. Feel free to close this issue now!
