### ISSUE TITLE
[REVIEW]: graynet: single-subject morphometric networks for neuroscience connectivity applications

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#924]
**Submitting author:** @raamana (<a href="http://orcid.org/0000-0003-4662-0558">Pradeep Reddy Raamana</a>)
**Repository:** <a href="https://github.com/raamana/graynet" target ="_blank">https://github.com/raamana/graynet</a>
**Version:** v0.3.9
**Editor:** @arokem
**Reviewer:** @rougier
**Archive:** <a href="https://doi.org/10.5281/zenodo.1442846" target="_blank">10.5281/zenodo.1442846</a>

## Status

[![status](http://joss.theoj.org/papers/abddd873e5bd22e4bf0124d2778878f4/status.svg)](http://joss.theoj.org/papers/abddd873e5bd22e4bf0124d2778878f4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/abddd873e5bd22e4bf0124d2778878f4"><img src="http://joss.theoj.org/papers/abddd873e5bd22e4bf0124d2778878f4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/abddd873e5bd22e4bf0124d2778878f4/status.svg)](http://joss.theoj.org/papers/abddd873e5bd22e4bf0124d2778878f4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="github.com/raamana/graynet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rougier, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="github.com/raamana/graynet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3.9)?
- [x] **Authorship:** Has the submitting author (@raamana) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rougier it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #924 with the following error: 

 Can't find any papers to compile :-(

**Comment by raamana** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00924/joss.00924/10.21105.joss.00924.pdf)

**Comment by rougier** [comment]
@raamana I've started the review and I've a few questions:

* I'm checking the docs but it seems there is a problem (I can read it at https://raamana.github.io/graynet/ but it's like the css style is broken. I'm using OSX/firefox to read it.
* Can you add all the missing DOI in the paper?
* In the test script, some tests are commented, is that on purpose?
* How do I check I get the right result from those tests?

**Comment by raamana** [comment]
Thanks for getting started.

1. docs seem to look fine on my laptop, but are somehow broken on the website. This is a bit beyond my expertise, will followup with Sphinx etc to try why it isn't working. Are you able to follow the text without the neat layout? And confirm necessary info is there? For the time being, you could perhaps open the `index.html` at the top-level in `gh-pages` branch of the repo. Sorry for the inconvenience, but I'll figure out whats going on.
2. paper.md does have DOI for this tool noted: 10.5281/zenodo.1403304 - do you mean DOIs for references?
3. They are meant to help me with executing a specific test in the debugging mode. On the CI server, all tests get executed.
4. to check if the code is passing all the tests, do this:

```python
cd <<path to cloned graynet>>
cd graynet/tests
pytest
```

that will run all tests in `test_graynet.py` and it should report no errors (like `12 passed` below):

```bash
$ 08:38:39 SQuark-3 tests >>  pwd
/Users/Reddy/dev/graynet/graynet/tests
$ 08:38:48 SQuark-3 tests >>  pytest
===================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.6.2, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /Users/Reddy/dev/graynet, inifile:
plugins: hypothesis-3.30.1
collected 12 items

test_graynet.py ............                                                                                                                                                             [100%]

======================================================================================= warnings summary =======================================================================================
graynet/tests/test_graynet.py::test_run_roi_stats_via_API
  /Users/Reddy/anaconda/envs/py36/lib/python3.6/site-packages/scipy/stats/stats.py:2831: FutureWarning:

  Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


-- Docs: http://doc.pytest.org/en/latest/warnings.html
=========================================================================== 12 passed, 1 warnings in 106.92 seconds ============================================================================



```

**Comment by rougier** [comment]
1. I'll look a the local version but you might want to fix the online version (such that people want to use your soft)
2. Yes, I was talking about references
3. ok
4. I'll try then.

**Comment by rougier** [comment]
I cannot build the doc because of: 
```
 $ make html
Running Sphinx v1.7.9

Extension error:
Could not import extension sphinxarg.ext (exception: No module named 'sphinxarg')
```
Where does this extension comes from?

**Comment by raamana** [comment]
you don't need to build them - they are already committed to `gh-pages` branch

can you try (cd-ing to top-level graynet dir):
```
git checkout gh-pages
firefox index.html
```

thanks.

**Comment by rougier** [comment]
Works thanks (and documentation is much better)!

Test have passed by the way. You might want to add a subsection in the documentation under installation to tell people how to test.

**Comment by raamana** [comment]
Users are not expected to run the tests themselves - the badge on the repo

[![Build Status](https://travis-ci.org/raamana/graynet.svg?branch=master)](https://travis-ci.org/raamana/graynet)

should give them confidence that its passing all the tests, and releases are not made if the tests fail.

Developers/contributors typically know what to do ;)

This document provides details:
https://github.com/raamana/graynet/blob/master/CONTRIBUTING.md

**Comment by rougier** [comment]
Do you think it could be possible to add a small toy example alongside the soft ?
With the missing DOI this is the last thing to do I think.

**Comment by rougier** [comment]
You're right, but some users might want to test on their own machine to know if their installation is ok.

**Comment by raamana** [comment]
I am not following you on 

"Do you think it could be possible to add a small toy example alongside the soft ?

With the missing DOI this is the last thing to do I think."

could you elaborate please? thanks.

**Comment by rougier** [comment]
Sorry. Things to do:

1. Add missing DOI from the references in your paper.md (and regenerate it)
2. ~add a small toy example~ Forget about it, I totally missed the script repo...

**Comment by raamana** [comment]
Thanks - so the doc website seems to have fixed itself with a new theme: https://raamana.github.io/graynet/index.html

Per your suggestion, I've added the developer guidelines: https://github.com/raamana/graynet/blob/gh-pages/docs/contributing.rst

This will show up on the docs in a few minutes or so

I will add the DOIs now.

**Comment by raamana** [comment]
The article is filled with DOIs now, except for `networkx` package which I couldn't find DOI for (seems like this old paper never got indexed). Let me know what else needs to be done.

**Comment by rougier** [comment]
Thanks @raamana. I think your paper is ready for publication (I recommend publication).
@arokem Do we need another review?

**Comment by rougier** [comment]
Last question @raamana: did you find what is wrong with the online documentation? Did you managed to fix it? I can open an issue on the repo (as a reminder).

**Comment by raamana** [comment]
Thank you for the speedy review, much appreciate your efforts!

Not sure why it didn’t work before, but the doc website seems to have fixed itself with a new theme: 

https://raamana.github.io/graynet/index.html

Take a look

**Comment by raamana** [comment]
I have also added more info on how to test graynet locally, as well as many links to how to test python packages. It should appear at the end of developer guidelines shortly (depending on github's CDN responsiveness :)..)

**Comment by raamana** [comment]
I added additional info on how to test python packages, if that might be of any help. Let me know what else needs to be done.

**Comment by arokem** [comment]
@rougier : is there anything more to do here? I see that the one item remaining on your list is the examples. Was that resolved to your satisfaction?

**Comment by rougier** [comment]
@arokem Just forgot to tick the box.

**Comment by raamana** [comment]
Thanks @rougier for the review, and recommending it for publication.

**Comment by arokem** [comment]
@rougier: thank you so much for the review! 

@raamana: I believe this paper is ready to be accepted! Could you please create another release of the software and an archive (e.g., on zenodo) and then post the DOI here?

**Comment by raamana** [comment]
Hi Ariel, there is some issue with Zenodo - its failing to create a release
https://zenodo.org/account/settings/github/repository/raamana/graynet

Don't want to make a distinct new upload, outside the typical mechanism for Zenodo, that might separate this DOI from the previous releases.. How do you handle this? 

I can try again in few days.

**Comment by arokem** [comment]
I am not sure what that's all about. Have you had a chance to try again?

**Comment by raamana** [comment]
I tired it again, just now. Luckily it worked. Final DOI is: 10.5281/zenodo.1442846

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1442846 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1442846" target="_blank">10.5281/zenodo.1442846</a> is the archive.

**Comment by arfon** [comment]
@rougier - many thanks for your review here and to @arokem for editing this submission ✨ 

@raamana - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00924 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00924/status.svg)](https://doi.org/10.21105/joss.00924)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00924">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00924/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00924/status.svg
   :target: https://doi.org/10.21105/joss.00924
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00924/status.svg)](https://doi.org/10.21105/joss.00924)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by raamana** [comment]
Yay! Thanks so much everyone ;)
