### ISSUE TITLE
[REVIEW]: mzEasy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#928]
**Submitting author:** @chasemc (<a href="http://orcid.org/0000-0001-6439-9397">Chase M Clark</a>)
**Repository:** <a href="https://github.com/chasemc/mzEasy" target ="_blank">https://github.com/chasemc/mzEasy</a>
**Version:** 0.1.0
**Editor:** @arfon
**Reviewer:** @biswapriyamisra, @mwang87
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/fcf70d0d1f8efc7f2d76617d4000eb6f/status.svg)](http://joss.theoj.org/papers/fcf70d0d1f8efc7f2d76617d4000eb6f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fcf70d0d1f8efc7f2d76617d4000eb6f"><img src="http://joss.theoj.org/papers/fcf70d0d1f8efc7f2d76617d4000eb6f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fcf70d0d1f8efc7f2d76617d4000eb6f/status.svg)](http://joss.theoj.org/papers/fcf70d0d1f8efc7f2d76617d4000eb6f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/chasemc/mzEasy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@biswapriyamisra & @mwang87, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/chasemc/mzEasy">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [ ] **Authorship:** Has the submitting author (@chasemc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/chasemc/mzEasy">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [ ] **Authorship:** Has the submitting author (@chasemc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @biswapriyamisra, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00928/joss.00928/10.21105.joss.00928.pdf)

**Comment by chasemc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00928/joss.00928/10.21105.joss.00928.pdf)

**Comment by chasemc** [comment]
Images were out of place, needed to play with markdown
@whedon generate pdf

**Comment by chasemc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00928/joss.00928/10.21105.joss.00928.pdf)

**Comment by chasemc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00928/joss.00928/10.21105.joss.00928.pdf)

**Comment by arfon** [comment]
@biswapriyamisra, @mwang87 - please complete your reviews of this package when you get a chance. Do you think you might be able to complete them in the next two weeks?

**Comment by biswapriyamisra** [comment]
Hello,

This is all going bit out of hand. The situation is funny and precarious
(with so many Emails, and so many invitees from  the List of Reviewers
declining for what ever reasons!), and then am being asked for the comments
again and again. I sympathize with the author- for this is all sounding
painful for a small software with 1-2 pages of content for the manuscript.
I hope in the future you would take care of these incomprehensible
situations, Emails, declining reviewers etc.

I did provide the 1st comments and an annotated PDF for the article in July
6th here https://github.com/openjournals/joss-reviews/issues/804 . These
are as follows and I have also attached the annotated PDF yet again for the
author.


   1. *Fairly quick and easy installation when MSConvert and R 3.5 or so
   are in place!*
   2. *Useful too for the conversions.*
   3. *More comments and suggestions in the annotated PDF.*
   4. *Useful tutorial and walk through images.*

*mzEasy_JOSS_Reviewer_Comments.pdf
<https://github.com/openjournals/joss-reviews/files/2172385/mzEasy_JOSS_Reviewer_Comments.pdf>*

*Thanks for the opportunity to review and all the best. Shall keep adding
requests to more functionalities or issues when faced.*


*Thanks, Biswa*

Thanks again for the opportunity to review it!

Best wishes,
Biswa

**Comment by arfon** [comment]
> I did provide the 1st comments and an annotated PDF for the article in July 6th here #804 . These are as follows and I have also attached the annotated PDF yet again for the author.

Hi @biswapriyamisra - sorry for causing frustration here but it's not clear from your comments on this PDF that you have actually carried out a review of this software. JOSS reviews are primarily *not* of the paper, rather the software instead. 

As you can see at the top of this issue, there is a checklist for you to work through which _is the JOSS review_. The comments you have left in your annotated PDF are helpful but not sufficient for the level of review we ask of our reviewers.

If you are still willing, I'd ask that you familiarize yourself with the [reviewer guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html) and work through the checklist above, leaving comments either here or on the review repository (https://github.com/chasemc/mzEasy).

Thanks again. Arfon.

**Comment by arfon** [comment]
I've just emailed @mwang87 to ask him to complete his review soon.

**Comment by arfon** [comment]
On closer inspection of this submission I've deemed it not suitable for JOSS due to the minor utility nature of this package.

Apologies for not catching this sooner @chasemc.
