### ISSUE TITLE
[PRE REVIEW]: survxai: an R package for model agnostic explanations of survival models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#929]
**Submitting author:** @AleksandraDabrowska (<a href="http://orcid.org/0000-0002-5963-6260">Aleksandra Grudziąż</a>)
**Repository:** <a href="https://github.com/MI2DataLab/survxai" target ="_blank">https://github.com/MI2DataLab/survxai</a>
**Version:** 0.2.0
**Editor:** @yochannah
**Reviewers:** @hiendn, @dirmeier

**Author instructions**

Thanks for submitting your paper to JOSS @AleksandraDabrowska. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@AleksandraDabrowska if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by AleksandraDabrowska** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by AleksandraDabrowska** [comment]
@whedon  generate pdf

**Comment by AleksandraDabrowska** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by yochannah** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by yochannah** [comment]
👋  Hi @hiendn and @dirmeier - can I interest either or both of you in reviewing this?

**Comment by hiendn** [comment]
Hi @yochannah, I can conduct the review. Just let me know what to do! :)

**Comment by yochannah** [comment]
@hiendn You are awesome! I'm still hunting for a second reviewer before I kick off the official review process, but in the meantime you can check out [the reviewer guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html) and/or start looking at the software package.

**Comment by yochannah** [comment]
Okay, @dirmeier has agreed to be the second reviewer when he's back in the office in a few days. I'll kick off the review process now.

**Comment by yochannah** [comment]
@whedon assign @hiendn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hiendn

**Comment by yochannah** [comment]
@whedon add @dirmeier as reviewer

**Comment by whedon** [comment]
OK, @dirmeier is now a reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/961. Feel free to close this issue now!
