### ISSUE TITLE
[PRE REVIEW]: qtools: A Python toolset for the Q molecular simulation package.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#930]
**Submitting author:** @mpurg (<a href="http://orcid.org/0000-0003-4647-6103">Miha Purg</a>)
**Repository:** <a href="https://github.com/mpurg/qtools" target ="_blank">https://github.com/mpurg/qtools</a>
**Version:** v0.6.1
**Editor:** @kyleniemeyer
**Reviewers:** @malramsay64, @esguerra, @fdroessler

**Author instructions**

Thanks for submitting your paper to JOSS @mpurg. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mpurg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00930/joss.00930/10.21105.joss.00930.pdf)

**Comment by mpurg** [comment]
Hi @kyleniemeyer,

Based on declared topics of research, I can suggest the following users
from the list of joss reviewers:
@richardjgowers
@fdroessler
@malramsay64

Additionally, I can suggest an expert in the topic specific to the
manuscript:
@esguerra

Best regards,
Miha


V V čet., 6. sep. 2018 ob 18:19 je oseba Arfon Smith <
notifications@github.com> napisala:

**Comment by fdroessler** [comment]
Hi, I would be happy to have a go at it. As this is my first review it would be great to have someone to be able to get in touch if I have questions.

**Comment by esguerra** [comment]
Hi @kyleniemeyer and @mpurg. I would be glad to help or help the reviewers in whichever way @kyleniemeyer  seems fit. For full disclosure I know the author of the paper and we work in the same institution, but in different groups and departments.

**Comment by malramsay64** [comment]
I am happy to review if I am required. @fdroessler I have done one review before, and I am happy for you to direct any questions at me.

**Comment by kyleniemeyer** [comment]
@whedon add @malramsay64 as reviewer

**Comment by whedon** [comment]
OK, @malramsay64 is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @esguerra as reviewr

**Comment by kyleniemeyer** [comment]
@whedon add @esguerra as reviewer

**Comment by whedon** [comment]
OK, @esguerra is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @fdroessler as reviewr

**Comment by whedon** [comment]
OK, @fdroessler is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/935. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
@malramsay64 @esguerra @fdroessler the review will be in #935
