### ISSUE TITLE
Author last name is wrong

### ISSUE THREAD

**Issue by offray** [openjournals/joss-reviews#931]
Hi,
I was linking this paper and I noticed that the last name appearing [here][joss] is still Cárdenas, but it should be Luna.

[joss]: http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #931 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
This is now fixed.
