### ISSUE TITLE
[PRE REVIEW]: alv: a console-based viewer for molecular sequence alignments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#932]
**Submitting author:** @arvestad (<a href="http://orcid.org/0000-0001-5341-1733">Lars Arvestad</a>)
**Repository:** <a href="https://github.com/arvestad/alv" target ="_blank">https://github.com/arvestad/alv</a>
**Version:** v1.2.0
**Editor:** @yochannah
**Reviewers:** @karinlag, @juanvillada

**Author instructions**

Thanks for submitting your paper to JOSS @arvestad. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@arvestad if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #932 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
Hi @arvestad - please review the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) and prepare a paper. The review cannot proceed until you have done this.

**Comment by arvestad** [comment]
I am on it. I had forgotten to commit/push the prepared paper to the repo. :-(

	Thanks,
	L

**Comment by arvestad** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00932/joss.00932/10.21105.joss.00932.pdf)

**Comment by arvestad** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00932/joss.00932/10.21105.joss.00932.pdf)

**Comment by arvestad** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00932/joss.00932/10.21105.joss.00932.pdf)

**Comment by arvestad** [comment]
@whedon add @karinlag as reviewer

**Comment by whedon** [comment]
I'm sorry @arvestad, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arvestad** [comment]
My suggestions for reviewers:

* Karin Lagesen, @karinlag. Involved in Software Carpentry and advocate for quality in Bioinformatics software. 

I picked three names with an interest in evolution from the list of potential referees:

* @giraola
* @shaunpwilkinson
* @juanvillada

Bioinformatics is a broad subject these days, but people working in evolution are more likely to be interested in using this software.

**Comment by karinlag** [comment]
I accept being a reviewer for this paper.

**Comment by juanvillada** [comment]
I'll be glad to review it. Count me in 👍🏼👍🏼

**Comment by yochannah** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by yochannah** [comment]
@whedon assign @karinlag as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @karinlag

**Comment by yochannah** [comment]
@whedon add @juanvillada as reviewer

**Comment by whedon** [comment]
OK, @juanvillada is now a reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/955. Feel free to close this issue now!

**Comment by yochannah** [comment]
@karinlag @juanvillada thanks for agreeing to review! Please hop over to #955 to start the review there.
