### ISSUE TITLE
[PRE REVIEW]: ipc: An R Package for Inter-process Communication

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#933]
**Submitting author:** @ifellows (<a href="http://orcid.org/0000-0003-1261-0925">Ian Fellows</a>)
**Repository:** <a href="https://github.com/fellstat/ipc" target ="_blank">https://github.com/fellstat/ipc</a>
**Version:** 0.1.0
**Editor:** @yochannah
**Reviewers:** @mschubert , @JohnCoene

**Author instructions**

Thanks for submitting your paper to JOSS @ifellows. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ifellows if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @yochannah it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
:wave: @yochannah - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00933/joss.00933/10.21105.joss.00933.pdf)

**Comment by ifellows** [comment]
note: license specified in package as per https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing

**Comment by ifellows** [comment]
Quickly looking over potential reviewers it looks like JohnCoene and wrathematics might be good fits.

**Comment by yochannah** [comment]
@ifellows thanks for your suggestions for potential reviewers, that's really handy! 

One of the requirements for JOSS papers is that they should have an obvious research application. Could you elaborate a little bit how this package is used for research?

Re: licencing - it would probably be best if you could include a LICENSE file in your repo as well, and add it to your `.Rbuildignore` if you wish. 

Thanks!

**Comment by ifellows** [comment]
Thanks. 

Sorry if it wasn't immediately apparent from the paper. Like the recent `datastructures` paper, this package is supporting infrastructure for researchers. It comes out of a CDC initiative to build UIs for complex statistical methods for use by researchers in the field. 

Often research requires computationally intensive activity. This package supports HPC by making it easy for the researcher to monitor their distributed processing by having child threads report back partial results and progress. Additionally, shiny is very popular among researchers for building user interfaces to their methods. Currently shiny becomes unresponsive with computationally intensive tasks (see for example http://blog.fellstat.com/?p=407 ). This package fixes this allowing for responsive, scalable applications. Three such applications are included in the package as examples.

**Comment by yochannah** [comment]
@ifellows Thanks, that does make sense - HPC is definitely an important part of research, and as you say, Shiny is well-loved amongst researchers too - I can see why one might want to make it more able to handle computationally intensive tasks. 

Please go ahead and add a LICENSE file to your repo as well. 👍

**Comment by yochannah** [comment]
👋  @wrathematics and @JohnCoene - hey there! Can we interest either or both of you in reviewing this package? Thanks!

**Comment by ifellows** [comment]
@yochannah : License file added. Actually made it MIT while I was at it.

**Comment by JohnCoene** [comment]
@ifellows @yochannah I had a brief look at the paper, I'm happy to review it but I'm away for the next 2 weeks and can't do anything before 1st October. Feel free to assign someone else if that is too long.

**Comment by ifellows** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00933/joss.00933/10.21105.joss.00933.pdf)

**Comment by yochannah** [comment]
@JohnCoene thanks for letting us know! I'll look for someone in the meantime and loop back if we're still looking in two weeks!

**Comment by yochannah** [comment]
@mschubert Hey there! 👋 Is this something you'd be interested in reviewing?

**Comment by mschubert** [comment]
As the author of the `txtq` package (which this package builds on), @wlandau might have some good input?

**Comment by wlandau** [comment]
Thanks for the endorsement. However, since [`ipc`](https://github.com/fellstat/ipc) builds on [`txtq`](https://github.com/wlandau/txtq), I am not sure a review from me would be sufficiently free of bias. (And like @JohnCoene, I will be away from Sept 15 through Oct 1). I think @clarkfitzg would be an excellent second reviewer, should he accept.

**Comment by yochannah** [comment]
Hey @clarkfitzg, would you be interested in reviewing?

**Comment by ifellows** [comment]
@yochannah , since it is now the 25th, I'd like to suggest we move forward with @mschubert and @JohnCoene . What do you think?

**Comment by yochannah** [comment]
@ifellows sounds like a good plan!

@JohnCoene: Are you good to go ahead reviewing?

**Comment by JohnCoene** [comment]
@yochannah Just got back; yes, I can help review this paper.

**Comment by yochannah** [comment]
@whedon assign @mschubert  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mschubert

**Comment by yochannah** [comment]
@whedon add @JohnCoene as reviewer

**Comment by whedon** [comment]
OK, @JohnCoene is now a reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/988. Feel free to close this issue now!

**Comment by yochannah** [comment]
Thanks everyone! @ifellows, @mschubert @JohnCoene: let's hope over to #988 to get the review started :)
