### ISSUE TITLE
[REVIEW]: qtools: A Python toolset for the Q molecular simulation package.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#935]
**Submitting author:** @mpurg (<a href="http://orcid.org/0000-0003-4647-6103">Miha Purg</a>)
**Repository:** <a href="https://github.com/mpurg/qtools" target ="_blank">https://github.com/mpurg/qtools</a>
**Version:** v0.6.1
**Editor:** @kyleniemeyer
**Reviewers:** @malramsay64, @fdroessler
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/6dc33648ae23a49031b9c305cbd8300f/status.svg)](http://joss.theoj.org/papers/6dc33648ae23a49031b9c305cbd8300f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6dc33648ae23a49031b9c305cbd8300f"><img src="http://joss.theoj.org/papers/6dc33648ae23a49031b9c305cbd8300f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6dc33648ae23a49031b9c305cbd8300f/status.svg)](http://joss.theoj.org/papers/6dc33648ae23a49031b9c305cbd8300f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mpurg/qtools" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@malramsay64 & @esguerra & @fdroessler, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpurg/qtools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.1)?
- [x] **Authorship:** Has the submitting author (@mpurg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpurg/qtools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.6.1)?
- [x] **Authorship:** Has the submitting author (@mpurg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @malramsay64, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00935/joss.00935/10.21105.joss.00935.pdf)

**Comment by kyleniemeyer** [comment]
@mpurg @malramsay64 @esguerra @fdroessler 👋  you each have individual checklists above. Detailed review criteria are at https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by malramsay64** [comment]
@mpurg I have taken an initial look and raised a number of issues. To be clear, only the issues with '[review]' in the title are the ones which require action based on the review criteria. The others are more suggestions which I think would make the software better. I am happy to help fix or discuss any issues.

**Comment by esguerra** [comment]
@mpurg @malramsay64  @fdroessle @kyleniemeyer 
Sorry  this reply has taken so long.
Only until now do I have time to read the COI policy in detail.
The author of this software and I are coauthors in a paper published less than four years ago, so,  I cannot act as a reviewer, sadly.

Thanks for the invitation and what a great idea this is,

Mauricio

**Comment by kyleniemeyer** [comment]
@esguerra OK, thanks for letting me know!

**Comment by kyleniemeyer** [comment]
@whedon remove @esguerra as reviewer

**Comment by whedon** [comment]
OK, @esguerra is no longer a reviewer

**Comment by kyleniemeyer** [comment]
@fdroessler @malramsay64 Have your reviews progressed? I noticed that many/most of the checkboxes in the review list above are not filled.

**Comment by fdroessler** [comment]
@kyleniemeyer I should be able to get to it beginninof next week. I am currently traveling in Africa but have looked at the paper and can start the full review process shortly.

**Comment by malramsay64** [comment]
@kyleniemeyer I have some time this week set aside to continue my review. I had somewhat put it on the side expecting some response from @mpurg to the issues I have raised.

**Comment by fdroessler** [comment]
Sorry I wanted to check if the following item: ` Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?` refers to the references in the paper or the reference of the software itself.

**Comment by fdroessler** [comment]
@kyleniemeyer @mpurg I have been through my checklist now and will wait till some of the issues that @malramsay64 and myself have raised are addressed.

**Comment by malramsay64** [comment]
@mpurg The updates you have been making to the code are all great. There is still the documentation which needs more explanation aimed at a new user. Feel free to get in contact if you want some ideas or feedback as you make changes.

**Comment by mpurg** [comment]
Hi @malramsay64, @kyleniemeyer, @fdroessler 
I've already addressed some of the issues as well as ported the whole codebase to Py3+, but as @malramsay64 points out, the documentation needs quite some work. Unfortunately, I'm juggling this revision with studying for a final exam and preparing for my PhD defense, making the whole process at this moment painfully slow and inefficient. Considering the extent of the revisions, would it be possible to postpone the revision process until the 3rd of Nov?

**Comment by kyleniemeyer** [comment]
Hi @mpurg, just wanted to check on the status of your revisions—hope your PhD defense went well!

**Comment by mpurg** [comment]
It went well, thanks.
I'll go over the revisions in the following days, I should be done in a
week or so.

**Comment by labarba** [comment]
👋 @mpurg — We haven't heard from you in a while. What's your status? Are you able to work on the revisions soon?

**Comment by labarba** [comment]
@kyleniemeyer — I manually removed the checklist for the unassigned reviewer, to avoid confusion and left-over un-ticked marks.

**Comment by labarba** [comment]
Thanks, @mpurg. We'll add this label here ☝️ and pause the review. Ping us back when you feel the review can restart.

**Comment by danielskatz** [comment]
👋 @mpurg @kyleniemeyer - Given the long delay at this point, I suggest that withdrawing the submission might be a good option, with the idea that it can be submitted again later.

Your thoughts?

**Comment by kyleniemeyer** [comment]
I agree, if @mpurg feels the same.

**Comment by labarba** [comment]
If this submission is withdrawn (and given the long delay, I agree that it should), we would ask the authors to please provide a link to this issue when they submit again (via a comment in the Pre-Review issue). This way, we can recall the history and possibly ask the same reviewers if they are still willing to contribute a review.

**Comment by mpurg** [comment]
Hi all, I agree that the submission be withdrawn and apologize for any
inconvenience.
Thank you reviewers for your valuable feedback.

**Comment by danielskatz** [comment]
Thanks - I will go ahead and withdraw this.
If/when do you resubmit, please add a comment that this was already partially reviewed, so as @labarba suggests, we can reference this issue and potentially get the same review back
