### ISSUE TITLE
[PRE REVIEW]: ungroup: An R package for efficient estimation of smooth distributions from coarsely binned data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#936]
**Submitting author:** @mpascariu (<a href="http://orcid.org/0000-0002-2568-6489">Marius Dan Pascariu</a>)
**Repository:** <a href="https://github.com/mpascariu/ungroup" target ="_blank">https://github.com/mpascariu/ungroup</a>
**Version:** v1.0.3
**Editor:** @karthik
**Reviewers:** @rlbarter

**Author instructions**

Thanks for submitting your paper to JOSS @mpascariu. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mpascariu if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #936 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: authors (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @karthik - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@mpascariu - please update your YAML paper header to exactly match this structure (looks like the `authors` field is missing) https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by mpascariu** [comment]
Done.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #936 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    158      0 --:--:-- --:--:-- --:--:--   160
[WARNING] Could not convert image '/tmp/tex2pdf.122/8e64be10ea50258a1f138548639970944c791d2a.tiff': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : II*XC
  HDR Invalid radiance file signature
  Tiff Can't find row per strip
  TGA Invalid bit depth (232)
[WARNING] Could not convert image '/tmp/tex2pdf.122/945a437d31637d82adc6959db27bb5f2090e4045.tiff': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : II*<_
  HDR Invalid radiance file signature
  Tiff Unknown compression scheme 8
  TGA Invalid bit depth (222)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.122/8e64be10ea5
0258a1f138548639970944c791d2a.tiff (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.257 ...e10ea50258a1f138548639970944c791d2a.tiff}

Looks like we failed to compile the PDF

**Comment by mpascariu** [comment]
Seems to be an issue with the `tiff` files. Should I try saving the figures as `pdf` files?

**Comment by mpascariu** [comment]
I have generated figures in pdf format. Hope it will work now.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00936/joss.00936/10.21105.joss.00936.pdf)

**Comment by arfon** [comment]
@mpascariu - layout is tricky with Markdown/Pandoc. I suggest we wait until the review is complete before tweaking layout.

**Comment by mpascariu** [comment]
@arfon I agree.

**Comment by karthik** [comment]
@mpascariu I'm looking for reviewers now so stay tuned. Here are some pre-review suggestions for you to fix ahead of time:

```
  ✖ omit "Date" in DESCRIPTION. It is not required and it gets invalid quite often. A build date will be added to the
    package when you perform `R CMD build` on it.
  ✖ use '<-' for assignment instead of '='. '<-' is the standard, and R users and developers are used it and it is
    easier to read your code for them if you use '<-'.

    R/pclm_1D.R:117:20
    R/pclm_1D.R:141:16
    R/pclm_1D.R:141:33
    R/pclm_1D.R:141:50
    R/pclm_2D.R:69:20
    ... and 23 more lines

  ✖ avoid long code lines, it is bad for readability. Also, many people prefer editor windows that are about 80
    characters wide. Try make your lines shorter than 80 characters

    R/pclm_fit.R:14:1
    R/pclm_fit.R:16:1
    R/pclm_graphics.R:41:1
    R/pclm_graphics.R:48:1
    R/pclm_graphics.R:72:1
    ... and 7 more lines

  ✖ avoid 1:length(...), 1:nrow(...), 1:ncol(...), 1:NROW(...) and 1:NCOL(...) expressions. They are error prone and
    result 1:0 if the expression on the right hand side is zero. Use seq_len() or seq_along() instead.

    R/pclm_2D.R:137:9
    R/pclm_graphics.R:120:11
    R/pclm_graphics.R:132:11
    R/pclm_graphics.R:133:11

  ✖ fix this R CMD check NOTE: Namespace in Imports field not imported from: ‘Rdpack’ All declared Imports should be
    used.
  ✖ avoid 'T' and 'F', as they are just variables which are set to the logicals 'TRUE' and 'FALSE' by default, but
    are not reserved words and hence can be overwritten by the user.  Hence, one should always use 'TRUE' and 'FALSE' for the
    logicals.

    R/pclm_1D.R:NA:NA
    R/pclm_1D.R:NA:NA
    R/pclm_2D.R:NA:NA
    R/pclm_2D.R:NA:NA
    R/pclm_fit.R:NA:NA
    ... and 20 more lines
```

**Comment by karthik** [comment]
@whedon assign @rlbarter as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rlbarter

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/937. Feel free to close this issue now!

**Comment by karthik** [comment]
Thanks @rlbarter for agreeing to review! Please see issue #937 for the review and reach out if you have any questions. I'll close up this issue.
