### ISSUE TITLE
[REVIEW]: ungroup: An R package for efficient estimation of smooth distributions from coarsely binned data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#937]
**Submitting author:** @mpascariu (<a href="http://orcid.org/0000-0002-2568-6489">Marius Dan Pascariu</a>)
**Repository:** <a href="https://github.com/mpascariu/ungroup" target ="_blank">https://github.com/mpascariu/ungroup</a>
**Version:** v1.0.3
**Editor:** @karthik
**Reviewer:** @rlbarter
**Archive:** <a href="https://doi.org/10.5281/zenodo.1421648" target="_blank">10.5281/zenodo.1421648</a>

## Status

[![status](http://joss.theoj.org/papers/f9b26bcbe25f3d2149d52fd7f8d8e484/status.svg)](http://joss.theoj.org/papers/f9b26bcbe25f3d2149d52fd7f8d8e484)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f9b26bcbe25f3d2149d52fd7f8d8e484"><img src="http://joss.theoj.org/papers/f9b26bcbe25f3d2149d52fd7f8d8e484/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f9b26bcbe25f3d2149d52fd7f8d8e484/status.svg)](http://joss.theoj.org/papers/f9b26bcbe25f3d2149d52fd7f8d8e484)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mpascariu/ungroup" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rlbarter, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpascariu/ungroup">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.3)?
- [x] **Authorship:** Has the submitting author (@mpascariu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rlbarter it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00937/joss.00937/10.21105.joss.00937.pdf)

**Comment by karthik** [comment]
@rlbarter Good to check the latest version. The bump from `1.0.3` to `1.0.4` appears to be in response to my suggestions (most were cosmetic) which should not change any of your review comments. You can view those changes here: https://github.com/mpascariu/ungroup/commit/964b126b145ef4a390f3a0019f6717f30715265c

**Comment by mpascariu** [comment]
@rlbarter Thanks for your comments. See below my response.

1) In the `README.md` it is specified the version no. of the stable software available on CRAN. The development version will change more frequently and has no real importance to the common user.

2) In GitHub we provide all the source file. The `.rmd` file can be found in `ungroup/vignettes/` folder. The already compiled vignette can be found in `ungroup/inst/doc/Intro.pdf`. We will add a link in `README.md` is this solves the situation.

3) The guidelines for contributing can be found in `CONTRIBUTING.md` file.

The last point I will address in the next comment.

**Comment by mpascariu** [comment]
@rlbarter Your suggestions have been addressed in `v1.0.5` not on GitHub. Thanks.

**Comment by rlbarter** [comment]
@mpascariu Great. This all looks good to me! Up to you whether you want to add a URL link to the vignette in the README (I personally find this helpful in general when I go to R packages on GitHub).

**Comment by mpascariu** [comment]
@rlbarter Excellent. Thank you very much.
I added the link too.

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00937/joss.00937/10.21105.joss.00937.pdf)

**Comment by karthik** [comment]
@mpascariu As @arfon noted earlier, it is very challenging to typeset accurately when using markdown + pandoc.  Given that you also have such a short paper the accurate placement you seek would be very challenging (without inserting a lot of empty space and page breaks).  You might have to mess with figure sizes to make it fit the way you seek. 

I'll let @arfon weigh in but I think the paper looks fine the way it is.

**Comment by mpascariu** [comment]
@karthik I understand.

I made some minor changes in the `.md` file. I think the paper should look better now. 
Can we generate the PDF again? Thank you.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00937/joss.00937/10.21105.joss.00937.pdf)

**Comment by arfon** [comment]
@mpascariu - you can ask @whedon to recompile the paper for you with `@whedon generate pdf`

Also, it looks like the `#Summary` needs changing to `# Summary` at the top of the paper.

**Comment by mpascariu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00937/joss.00937/10.21105.joss.00937.pdf)

**Comment by mpascariu** [comment]
@arfon I think the article looks fine now. Thank you very much.

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.1421648 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1421648" target="_blank">10.5281/zenodo.1421648</a> is the archive.

**Comment by karthik** [comment]
@mpascariu Thank you for the submission! And thanks @rlbarter for the review! This is ready to accept @arfon :tada:

**Comment by mpascariu** [comment]
Thank you everyone for your work! It is much appreciated.

**Comment by arfon** [comment]
@rlbarter - many thanks for your review here and to @karthik for editing this submission ✨ 

@mpascariu - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00937 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00937/status.svg)](https://doi.org/10.21105/joss.00937)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00937">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00937/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00937/status.svg
   :target: https://doi.org/10.21105/joss.00937
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00937/status.svg)](https://doi.org/10.21105/joss.00937)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
