### ISSUE TITLE
[PRE REVIEW]: Eniric: Extended NIR Information Content

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#938]
**Submitting author:** @jason-neal (<a href="http://orcid.org/0000-0003-0390-9896">Neal, Jason J.</a>)
**Repository:** <a href="https://github.com/jason-neal/eniric" target ="_blank">https://github.com/jason-neal/eniric</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @crawfordsm

**Author instructions**

Thanks for submitting your paper to JOSS @jason-neal. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jason-neal if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #938 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #938 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #938 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
I think this repository is too big for Whedon to clone in a reasonable timeframe... 😢

**Comment by arfon** [comment]
Here's the paper I compiled locally [10.21105.joss.00938.pdf](https://github.com/openjournals/joss-reviews/files/2374711/10.21105.joss.00938.pdf)

**Comment by jason-neal** [comment]
Oh, right. I am getting prepared to use BFG-repo-cleaner to clean out old large data files from the repo, that might help Whedon

**Comment by jason-neal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by jason-neal** [comment]
@whedon generate pdf from branch develop

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch develop. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #938 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
> @whedon generate pdf from branch develop

@jason-neal - did you manage to strip down the size of this repository?

**Comment by jason-neal** [comment]
Yea I think I cleaned out ~1.3GB from the repo. Its now just under 300M...

**Comment by arfon** [comment]
@whedon generate pdf from branch develop

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch develop. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #938 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@jason-neal we only recently added the functionality to optionally build from a branch and it doesn't look like it's working properly. Could you try either merging your `develop` branch into `master` or putting the `paper.md` and other paper-related resources into the `master` branch please?

**Comment by jason-neal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00938/joss.00938/10.21105.joss.00938.pdf)

**Comment by jason-neal** [comment]
Proof looks ok to me. (the figure should probably shrunk to keep it to 3 pages but I from looking at other reviews that can wait until after review/acceptance.)

**Comment by arfon** [comment]
@jason-neal - could you take a look at the [list of potential reviewers](https://bit.ly/joss-reviewers) and identify some people who could review this submission? Also, feel free to tag anyone you might recommend here with their GitHub handle.

**Comment by jason-neal** [comment]
From the list possibly @nespinoza.
 
@mzechmeister

I also use/cite pieces from of @sczesla, @iancze but I don't know weather that causes any conflicts.

**Comment by jason-neal** [comment]
Is there something  I need to do to progress this review?

**Comment by arfon** [comment]
> Is there something I need to do to progress this review?

@jason-neal - nothing at this point. We're currently waiting on some reviewers, once we have those we can proceed.

**Comment by arfon** [comment]
@whedon assign @crawfordsm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @crawfordsm

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1053. Feel free to close this issue now!

**Comment by arfon** [comment]
@jason-neal - apologies for taking so long to get this moving. @crawfordsm has kindly volunteered to review this submission for us.
