### ISSUE TITLE
[PRE REVIEW]: Diff_classifier: Parallelization of multi-particle tracking video analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#939]
**Submitting author:** @ccurtis7 (<a href="http://orcid.org/0000-0001-6312-392X">Chad Curtis</a>)
**Repository:** <a href="https://github.com/ccurtis7/diff_classifier" target ="_blank">https://github.com/ccurtis7/diff_classifier</a>
**Version:** v0.1-alpha
**Editor:** @cMadan
**Reviewers:** @stsievert

**Author instructions**

Thanks for submitting your paper to JOSS @ccurtis7. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ccurtis7 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @cMadan - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    144      0 --:--:-- --:--:-- --:--:--   145
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.274 

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by ccurtis7** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    112      0 --:--:-- --:--:-- --:--:--   112
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.274 

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
It seems that the test PDF is failing to generate. I looked at a few [examples](https://github.com/openjournals/joss-reviews/issues/485) from other JOSS pre-reviews to see if I could track down a solution. I think it has to do with a stray character or figure that is being interpreted incorrectly. I'm not sure exactly what it is, but I suspect it is somewhere in my paper.bib file. I tried removing the abstracts from the paper.bib file to see if I could resolve the error in a new branch [joss_review](https://github.com/ccurtis7/diff_classifier/tree/joss_review).

@whedon generate pdf from branch joss_review

**Comment by arfon** [comment]
@whedon generate pdf from branch joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    111      0 --:--:-- --:--:-- --:--:--   111
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.276 

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf from branch joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    143      0 --:--:-- --:--:-- --:--:--   144
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.276 

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf from branch joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    134      0 --:--:-- --:--:-- --:--:--   136
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.276 

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf from branch joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    166      0 --:--:-- --:--:-- --:--:--   165
100    17    0    17    0     0    165      0 --:--:-- --:--:-- --:--:--   165
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.277 

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@ccurtis7 - I'm trying to debug this myself. The issue seems to be with the YAML header. I'm wondering if there are some hidden characters in there or something...

**Comment by ccurtis7** [comment]
Thanks @arfon, I couldn't narrow down where the error was.

**Comment by arfon** [comment]
@ccurtis7 - the issue is with the underscore in the title. Please change:

```
title: 'diff_classifier: Parallelization of multi-particle tracking videos'

to 

title: 'diff\_classifier: Parallelization of multi-particle tracking videos'
```

**Comment by arfon** [comment]
Also, I should try and sanitize this kind of input as it's passed to Pandoc. This isn't the first time it's caught us out...

**Comment by ccurtis7** [comment]
@whedon generate pdf from branch joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0     27      0 --:--:-- --:--:-- --:--:--    27
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.276 

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf from branch joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    101      0 --:--:-- --:--:-- --:--:--   101
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.276 

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
I'm not sure why it's still not working after I changed the YAML file. I'm unfamiliar with Latek, but I tried checking a [complete list](https://www.sharelatex.com/learn/Errors/Missing_$_inserted) of symbols that need to be written as math. Is the colon throwing it as well?

**Comment by arfon** [comment]
@ccurtis7 - I'm wondering if the new command `@whedon generate pdf from branch...` is being weird. I can compile your changes on the `joss_paper` branch locally OK.

Perhaps merge what you have in the `joss_paper` branch into `master` and just try `@whedon generate pdf`?

Sorry for the both here. I've only recently added the ability for Whedon to compile papers from a different branch and it's quite possibly a little buggy...

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

A few minor edits from @arokem

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by cMadan** [comment]
Hi @ccurtis7! Do you have any suggestions for potential reviewers?

**Comment by cMadan** [comment]
@sealhuang @oesteban, would you be available and interested to review this submission?

**Comment by oesteban** [comment]
I'm on vacation now, and I expect to be pretty swamped for a while when I'm
back. Sorry I have to let this one go.

**Comment by ccurtis7** [comment]
Others I think that might be good fits, @stsievert and @vsoch

**Comment by cMadan** [comment]
@stsievert, that would be great, thank you!

I'll go ahead and start the review process now.

**Comment by cMadan** [comment]
@whedon assign @stsievert as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stsievert

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/989. Feel free to close this issue now!

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    388      0 --:--:-- --:--:-- --:--:--   395
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.356 T

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    251      0 --:--:-- --:--:-- --:--:--   253
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.354 T

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    164      0 --:--:-- --:--:-- --:--:--   166
pandoc-citeproc: reference Pulford:2005 not found
pandoc-citeproc: reference Chenouard:2014 not found
pandoc-citeproc: reference Tineves:2017 not found
pandoc-citeproc: reference Wang:2015 not found
pandoc-citeproc: reference cloudknot not found
pandoc-citeproc: reference zenodo not found
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.356 T

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    349      0 --:--:-- --:--:-- --:--:--   354
Error producing PDF.
! Missing { inserted.
<to be read again> 
                   $
l.357 T

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    179      0 --:--:-- --:--:-- --:--:--   180
Error producing PDF.
! Missing { inserted.
<to be read again> 
                   $
l.356 T

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #939 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    299      0 --:--:-- --:--:-- --:--:--   303
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.356 T

Looks like we failed to compile the PDF

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)

**Comment by ccurtis7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00939/joss.00939/10.21105.joss.00939.pdf)
