### ISSUE TITLE
[PRE REVIEW]: Confidence Intervals for Random Forests in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#94]
**Submitting author:** @kpolimis (<a href="http://orcid.org/0000-0002-3498-0479">Kivan Polimis</a>)
**Repository:** <a href="https://github.com/scikit-learn-contrib/forest-confidence-interval" target ="_blank">https://github.com/scikit-learn-contrib/forest-confidence-interval</a>
**Version:** .1
**Editor:** @jakevdp
**Reviewer:** @DannyArends

**What this issue is for**

Thanks for submitting your paper to JOSS @kpolimis. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @jakevdp - do you think you could edit this submission?

**Comment by arfon** [comment]
@whedon assignments

**Comment by arfon** [comment]
@whedon assignments

**Comment by arfon** [comment]
@whedon assignments

**Comment by whedon** [comment]
**EDITORIAL ASSIGNMENTS**

| Editor | Assignments |
| ----- | ----- |
| `@acabunoc` | 2 |
| `@arfon` | 8 |
| `@cMadan` | 1 |
| `@danielskatz` | 2 |
| `@jakevdp` | 2 |
| `@karthik` | 1 |
| `@katyhuff` | 0 |
| `@Kevin-Mattheus-Moerman` | 2 |
| `@kyleniemeyer` | 2 |
| `@labarba` | 0 |
| `@mgymrek` | 1 |
| `@pjotrp` | 1 |
| `@tracykteal` | 1 |

**Comment by arfon** [comment]
:wave: @labarba - any chance you could edit this for us?

**Comment by danielskatz** [comment]
The message I take from this is that I should make sure the papers I'm assigned are reviewed slowly so I don't get assigned more. Not sure this is quite right...

On Nov 12, 2016, at 17:37, whedon <notifications@github.com<mailto:notifications@github.com>> wrote:


EDITORIAL ASSIGNMENTS

Editor  Assignments
@acabunoc       2
@arfon  8
@cMadan 1
@danielskatz    2
@jakevdp        2
@karthik        1
@katyhuff       0
@Kevin-Mattheus-Moerman 2
@kyleniemeyer   2
@labarba        0
@mgymrek        1
@pjotrp 1
@tracykteal     1

**Comment by labarba** [comment]
Topic-wise, not in my area of expertise. I could activate some contacts to see if a reviewer can be located, but would not be able to moderate if author and reviewer disagree.

**Comment by labarba** [comment]
We're looking for volunteers to review this submission to JOSS. It is a **sci-kit-learn** compatible project. Any chance that we could get a review from @amueller, @GaelVaroquaux or maybe @NelleV?

**Comment by arfon** [comment]
> The message I take from this is that I should make sure the papers I'm assigned are reviewed slowly so I don't get assigned more. Not sure this is quite right...

@danielskatz - `¯\_(ツ)_/¯` I guess so? Currently there's little/no visibility into who is reviewing what....and we've got 8 submissions currently without an editor. Just trying out some tooling to help make sure we have a relatively even load on each editor.

Any suggestions for improvements would be very welcome :-)

> Topic-wise, not in my area of expertise. I could activate some contacts to see if a reviewer can be located, but would not be able to moderate if author and reviewer disagree.

Understood. Would you be willing to start editing this and if there's a disagreement then perhaps we can bring in a domain expert?

**Comment by danielskatz** [comment]
Maybe we should also look at how many papers we have edited in the last 3 and 12 months (yes, I know 12 months won't say different, *yet*)

**Comment by arfon** [comment]
> Maybe we should also look at how many papers we have edited in the last 3 and 12 months (yes, I know 12 months won't say different, yet)

Yeah. That's a good point. I'll look at adding that.

**Comment by GaelVaroquaux** [comment]
> It is a sci-kit-learn compatible project. Any chance that we could get
> a review from @amueller, @GaelVaroquaux or maybe @NelleV?

I really don't have the time to do everything that I should be
doing. And, to be honest, if I find time, I'd rather review PRs in
scikit-learn, where we have a terrible backlog.

Sorry :$

**Comment by danielskatz** [comment]
Thinking about the general editor balance issue a bit more...

I don't think our goal should be to balance work across editors.  We should be assigning reviews to editors based on topics.  If an editor is getting too many submission in a given topic, we should add another editor in that topic.

I think the PeerJ CS model is what we should be following here, add editors as needed, and when there are papers where the assignment to an editor is not clear, ask the editors for volunteers.

**Comment by amueller** [comment]
On 11/13/2016 05:21 AM, Gael Varoquaux wrote:
> > It is a sci-kit-learn compatible project. Any chance that we could get
> > a review from @amueller, @GaelVaroquaux or maybe @NelleV?
>
> I really don't have the time to do everything that I should be
> doing. And, to be honest, if I find time, I'd rather review PRs in
> scikit-learn, where we have a terrible backlog.
>
> Sorry :$
Same here. Gilles Louppe might be a good candidate for this paper, 
though I'm sure he's also busy.

**Comment by pjotrp** [comment]
@DannyArends would you care to review?

**Comment by DannyArends** [comment]
Hey all,

Sure I'll be the reviewer for this submission.

Gr,
Danny

**Comment by whedon** [comment]
OK, the reviewer is @DannyArends

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/124. Feel free to close this issue now!

**Comment by arfon** [comment]
Closing as the review is now happening over in #124
