### ISSUE TITLE
[PRE REVIEW]: hillR: taxonomic, functional, and phylogenetic diversity and similarity through Hill Numbers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#942]
**Submitting author:** @daijiang (<a href="http://orcid.org/0000-0002-0925-3421">Daijiang Li</a>)
**Repository:** <a href="https://github.com/daijiang/hillR" target ="_blank">https://github.com/daijiang/hillR</a>
**Version:** v0.3.0
**Editor:** @karthik
**Reviewers:** @sydnerecord

**Author instructions**

Thanks for submitting your paper to JOSS @daijiang. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@daijiang if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00942/joss.00942/10.21105.joss.00942.pdf)

**Comment by arfon** [comment]
👋 @karthik - the submitting author suggested you as the handling editor.

**Comment by daijiang** [comment]
Hi @whedon @karthik @arfon thanks for your help. I think @aurielfournier or @ethanwhite can be good reviewers.

**Comment by aurielfournier** [comment]
Hi @daijiang I don't do phylogenetic work, so I don't think I would be a very good reviewer for this package.. Thanks for thinking of me though

**Comment by daijiang** [comment]
Hi @aurielfournier , the methods have been proposed by others. This package implements it and it is actually straightforward. I think it is more about the R code than the methods. This is why I think you should be a good reviewer candidate.

**Comment by daijiang** [comment]
@arfon @karthik any progress with the review process? Thanks.

**Comment by karthik** [comment]
@daijiang We are waiting for reviewers to respond. Stay tuned until we get someone to commit.

**Comment by daijiang** [comment]
@karthik thanks!

**Comment by daijiang** [comment]
@karthik any news about reviewers hunting? Thanks!

**Comment by karthik** [comment]
Thanks @daijiang! I've reached out to Sydne and will update when I hear back.

**Comment by karthik** [comment]
@whedon assign @sydnerecord as reviewer

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, the reviewer is @sydnerecord

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1041. Feel free to close this issue now!

**Comment by daijiang** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```
