### ISSUE TITLE
[PRE REVIEW]: VIVO: a system for research discovery

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#943]
**Submitting author:** @mconlon17 (<a href="http://orcid.org/0000-0002-1304-8447">Michael Conlon</a>)
**Repository:** <a href="https://github.com/vivo-project/VIVO" target ="_blank">https://github.com/vivo-project/VIVO</a>
**Version:** v1.10.0
**Editor:** @jasonclark
**Reviewers:** @sonal-raj

**Author instructions**

Thanks for submitting your paper to JOSS @mconlon17. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mconlon17 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jasonclark it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #943 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/943/paper/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @jasonclark - the submitting authors suggested you as the handling editor.

**Comment by jasonclark** [comment]
@arfon Yes, I can edit this submission. 
@mconlon17 Thanks for the submission. The software has a general description, a BSD 3-Clause "New" or "Revised" License, you are a recognized contributor on the project, and it is scoped correctly as research software (E.g., software for a research application). These are a few of my pre-review checks. Our next step is to find a reviewer.

**Comment by jaynanavati** [comment]
I am so sorry. I am busy with other pre-planned things. So, I am not
available.

**Comment by jasonclark** [comment]
@jaynanavati No worries. Thanks for the note.

**Comment by jasonclark** [comment]
@corybrunson Would you be available to review the VIVO software? We would be looking for a review in the next few weeks. Thanks for considering. cc @mconlon17

**Comment by corybrunson** [comment]
@jasonclark i'm sorry, i don't think i'll be able to right now.

**Comment by jasonclark** [comment]
@semacu Would you be available to review the VIVO software? We would be looking for a review in the next few weeks. Thanks for considering. cc @mconlon17 @arfon

**Comment by jasonclark** [comment]
@sonal-raj We could really use a reviewer on this software. Thought your experience with Graphs and Graph Databases would be super useful here. Would you be available to review the VIVO software? We would be looking for a review in the next few weeks. Thanks for considering. cc @mconlon17 @arfon

**Comment by semacu** [comment]
Thanks for letting me know, I am afraid I won't have time to review this in detail now as the few weeks leading to Christmas are always hectic.

**Comment by sonal-raj** [comment]
> @sonal-raj We could really use a reviewer on this software. Thought your experience with Graphs and Graph Databases would be super useful here. Would you be available to review the VIVO software? We would be looking for a review in the next few weeks. Thanks for considering. cc @mconlon17 @arfon

@jasonclark Thanks for the request. I like the idea of this software and would love to help review it. Only constraint is my schedule is packed till 18th of Dec, but I am available post that. Depending on the urgency, if the time looks fine to you, I can definitely help review VIVO. Do let me know.

**Comment by jasonclark** [comment]
@sonal-raj That timeline still works for us. Thanks for offering your expertise. I'll set up the review process and you can pick it up after December 18. cc @mconlon17 @arfon

**Comment by sonal-raj** [comment]
@jasonclark Sounds Good!

**Comment by arfon** [comment]
@jasonclark - are we good to set up the main review at this stage or are you looking for a second reviewer?

**Comment by jasonclark** [comment]
Was hoping to keep @sonal-raj on this review after the holidays. I'm going to set up review now. @sonal-raj if you have questions or limited availability. Please let me know.

**Comment by jasonclark** [comment]
@sonal-raj That is fine. I'm happy to have you as a reviewer and start the process. Later this month works. Apologies for missing the assignment over the holiday. Going to assign you as a reviewer and open it for editing. You can pick up when you are able. If you have questions, just reach out.

**Comment by jasonclark** [comment]
@whedon assign @sonal-raj as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sonal-raj

**Comment by jasonclark** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1182. Feel free to close this issue now!
