### ISSUE TITLE
[PRE REVIEW]: Verde: Processing and gridding spatial data using Green's functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#944]
**Submitting author:** @leouieda (<a href="http://orcid.org/0000-0001-6123-9515">Uieda, L</a>)
**Repository:** <a href="https://github.com/fatiando/verde" target ="_blank">https://github.com/fatiando/verde</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewers:** @fourndo, @Fil

**Author instructions**

Thanks for submitting your paper to JOSS @leouieda. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@leouieda if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #944 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    204      0 --:--:-- --:--:-- --:--:--   204
pandoc: functions       -V footnote_paper_title=Verde:: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@leouieda - this PR https://github.com/fatiando/verde/pull/135 will fix the paper compilation issue.

**Comment by arfon** [comment]
@lheagy - the submitting author suggested you as the handling editor 😺

**Comment by lheagy** [comment]
Hi @arfon: I am happy to be the editor on this!

**Comment by leouieda** [comment]
@arfon thanks for the fix! It's merged now.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00944/joss.00944/10.21105.joss.00944.pdf)

**Comment by lheagy** [comment]
:wave: Hi @sgrieve, @fil, @Chilipp, @WalBytes, would one of you be willing to review this submission for JOSS?

**Comment by lheagy** [comment]
@whedon assign @fourndo as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @fourndo

**Comment by Fil** [comment]
> 👋 would one of you be willing to review this submission for JOSS?

yes, thanks!

**Comment by Chilipp** [comment]
Me, too, if you need third one

**Comment by lheagy** [comment]
Excellent, Thanks for your enthusiasm @Fil and @Chilipp! We only need two reviewers, here, so @Chilipp, I will ping you for the next one :)

**Comment by lheagy** [comment]
@whedon add @Fil as reviewer

**Comment by whedon** [comment]
OK, @Fil is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/957. Feel free to close this issue now!
