### ISSUE TITLE
[PRE REVIEW]: `rr2`: An R package to calculate R2s for regression models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#945]
**Submitting author:** @arives (<a href="http://orcid.org/0000-0001-9375-9523">Anthony Ives</a>)
**Repository:** <a href="https://github.com/arives/rr2" target ="_blank">https://github.com/arives/rr2</a>
**Version:** v1.0.0
**Editor:** @karthik
**Reviewers:** @sastoudt

**Author instructions**

Thanks for submitting your paper to JOSS @arives. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@arives if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #945 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    166      0 --:--:-- --:--:-- --:--:--   166
100    17    0    17    0     0    164      0 --:--:-- --:--:-- --:--:--   165
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.280 \end{document}

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @karthik - the submitting author suggested you as the handling editor.

**Comment by daijiang** [comment]
@whedon @arfon we are not sure why the PDF complication failed. We have changed `R^2^` to `$R^2$` and see whether this works.

**Comment by arives** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00945/joss.00945/10.21105.joss.00945.pdf)

**Comment by arives** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by daijiang** [comment]
@karthik any news about reviewers hunting? Thanks!

**Comment by karthik** [comment]
@daijiang Still working through declines and also on a bit of travel at the moment. I'll have this squared away soon.

**Comment by whedon** [comment]
OK, the reviewer is @sastoudt

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1028. Feel free to close this issue now!
