### ISSUE TITLE
[REVIEW]: PyTeNet: A concise Python implementation of quantum tensor network algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#948]
**Submitting author:** @cmendl (<a href="http://orcid.org/0000-0002-6386-0230">Christian B. Mendl</a>)
**Repository:** <a href="https://github.com/cmendl/pytenet" target ="_blank">https://github.com/cmendl/pytenet</a>
**Version:** v1.0
**Editor:** @jedbrown
**Reviewer:** @mlxd, @jcmgray
**Archive:** <a href="https://doi.org/10.5281/zenodo.1464149" target="_blank">10.5281/zenodo.1464149</a>

## Status

[![status](http://joss.theoj.org/papers/b466d20151ffc50519dbacd8c3f599da/status.svg)](http://joss.theoj.org/papers/b466d20151ffc50519dbacd8c3f599da)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b466d20151ffc50519dbacd8c3f599da"><img src="http://joss.theoj.org/papers/b466d20151ffc50519dbacd8c3f599da/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b466d20151ffc50519dbacd8c3f599da/status.svg)](http://joss.theoj.org/papers/b466d20151ffc50519dbacd8c3f599da)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cmendl/pytenet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mlxd & @jcmgray, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cmendl/pytenet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@cmendl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cmendl/pytenet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@cmendl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mlxd it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00948/joss.00948/10.21105.joss.00948.pdf)

**Comment by mlxd** [comment]
Hi  @cmendl 
Really nice package. I have no problem recommending this for publicatoin, but I do have a few suggestions first based on the above checklist items:

**Version: Does the release version given match the GitHub release (v1.0)?**         
    
No version is given for this software. Consider tagging the code with a release version for this     publication (eg `git tag v1.0`).

**Functionality
Installation: Does installation proceed as outlined in the documentation?**     
    
No installation documentation provided for this package. As stated by @jmcgray above, it may be worth-while explaining how to install/run the software, using a package manager (conda/pip), or simply just cloning and running instructions.

**Functionality: Have the functional claims of the software been confirmed?**
The available physics of the software has been mentioned in the Readme.md file. However, giving a specific examples of each of the available functionalities may be worthwhile to anybody wishing to use the software. This could take the place of some Markdown file with example code sections, and some discussions of what is happening.
    
**Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.**     

No installation instructions given. Please consider providing some installation instructions, either in the Readme.md, or elsewhere in documentation. See above comments for Functionality::Installation
    
**Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).**     

Source examples provided in `pytenet/experiments` for several use-cases. Additionally, `pytenet/tests` directory has documented test-cases for many  routines. Consider adding a Readme.md to each respective directory to describe the listed files/classes/methods discussing each example usage.

**Functionality  documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?**     

Source code has comments in key-locations to describe usage functionality. However, an API documentation framework may be beneficial (eg sphinx, doxygen, etc), to allow ease-of-use for developers and users. Alternatively, a Readme.md describing each source file/class/method in each respective directory would be beneficial.

**Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support**

No community guidelines given for development. Adding some options for options 1), 2), and 3) would be welcome.


Feel free to @ me for any further information if the above comments are insufficient.

**Comment by cmendl** [comment]
OK thanks for the suggestions! I'll try to incorporate them in the next few days..

**Comment by jcmgray** [comment]
I haven't yet had time to install and test the package (which looks like it has a lot of nice stuff!) but very much agree with all the documentation points @mlxd raised.

To just add a few thoughts, it would be very nice to have some 'getting started' style examples at a simpler level than the ``experiments`` but with more introduction and explanation than the tests. For example, a simple ground-state calculation, pure-state evolution and maybe a custom MPO hamiltonian construction might be good, minimal jumping off points.

I'm sure you know about jupyter notebooks, but just thought I'd mention that they can be a good choice for this kind of example (with possibly maths+code+graphs...) as github can render them ([here](https://github.com/jcmgray/quimb/blob/develop/docs/examples/ex_TEBD_evo.ipynb) is an example of mine) and they can even be incorporated into proper sphinx docs using [nbsphinx](https://nbsphinx.readthedocs.io).

**Comment by cmendl** [comment]
The raised issues should now be addressed: the package is now actually remodeled into a Python package for easy installation, I've included a short example code section for the TDVP time evolution directly in the ReadMe file, created two tutorials as Jupyter notebooks, and hosted them together with Sphinx API documentation at https://pytenet.readthedocs.io (@jcmgray quimb was really helpful as guide how to set this up...)

@mlxd : Before actually attaching the missing GitHub release (v1.0) tag, I'm planning to commit a slightly extended version of the manuscript. Should I preserve the original date or update it to the present date in paper.md? Thanks!

**Comment by mlxd** [comment]
> @mlxd : Before actually attaching the missing GitHub release (v1.0) tag, I'm planning to commit a slightly extended version of the manuscript. Should I preserve the original date or update it to the present date in paper.md? Thanks!

If you are regenerating the paper with a longer version then I think an updated date should be fine (though Git always provides a paper trail of changes, so it probably shouldn't matter much). Otherwise, great work on the documentation and other changes.

**Comment by cmendl** [comment]
Just updated the paper and added the tag...

**Comment by mlxd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00948/joss.00948/10.21105.joss.00948.pdf)

**Comment by mlxd** [comment]
> ...so from my side, I've completed the current round of revision

No problem. I'll regenerate the PDF and we can go from there.

**Comment by mlxd** [comment]
Guidelines issue created: https://github.com/cmendl/pytenet/issues/3

**Comment by mlxd** [comment]
I'm happy with the current version. Once @jcmgray is too I think we can end the review.

**Comment by jcmgray** [comment]
Yes I've had a look through and very happy with all the changes - so good to go on my part!

**Comment by cmendl** [comment]
DOI: 10.5281/zenodo.1464149

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.1464149 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1464149" target="_blank">10.5281/zenodo.1464149</a> is the archive.

**Comment by jedbrown** [comment]
@arfon Over to you.

**Comment by arfon** [comment]
> @arfon Over to you.

:+1: thanks. I'm going to try some new Whedon functionality here so apologies in advance if things go a little awry...

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/9

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/9, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@mlxd, @jcmgray - many thanks for your reviews here and to @jedbrown for editing this submission ✨ 

@cmendl - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00948 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00948/status.svg)](https://doi.org/10.21105/joss.00948)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00948">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00948/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00948/status.svg
   :target: https://doi.org/10.21105/joss.00948
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00948/status.svg)](https://doi.org/10.21105/joss.00948)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
