### ISSUE TITLE
[PRE REVIEW]: SALib: An open-source Python library for Sensitivity Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#95]
**Submitting author:** jdherman (<a href="http://orcid.org/0000-0002-4081-3175">Jonathan Herman</a>)
**Repository:** <a href="https://github.com/SALib/SALib" target ="_blank">https://github.com/SALib/SALib</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewer:** @stijnvanhoey

**What this issue is for**

Thanks for submitting your paper to JOSS jdherman. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @kyleniemeyer thanks for agreeing to edit this one 💖

**Comment by kyleniemeyer** [comment]
Hi @bryanwweber any interest in reviewing this?

Also, @jdherman if you have any potential reviewers you could suggest (i.e., closer to the domain), that would be great. I usually like to have two reviewers.

**Comment by jdherman** [comment]
Thanks @kyleniemeyer. For reviewers, you might try asking @quaquel or @stijnvanhoey if they are available.

**Comment by kyleniemeyer** [comment]
Ah great, thank you. @quaquel or @stijnvanhoey, would either of you be interested in reviewing this for JOSS? I will also be getting an existing JOSS reviewer that is not necessarily close to the relevant domain.

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by kyleniemeyer** [comment]
Hi @khinsen @nirum @amoeba @jordigh would any of you be willing to review this? If so, you can respond with a 👋 (otherwise ignore). Thanks!

**Comment by stijnvanhoey** [comment]
Hi @kyleniemeyer, I'm willing to review the SALIB contribution.

**Comment by kyleniemeyer** [comment]
Great @stijnvanhoey thanks! 

@whedon assign @stijnvanhoey as reviewer

**Comment by quaquel** [comment]
'll be happy to help as well

**Comment by kyleniemeyer** [comment]
@whedon assign @stijnvanhoey as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stijnvanhoey

**Comment by kyleniemeyer** [comment]
Hi @quaquel thanks, your additional review would be great. As soon as @whedon kicks into gear, a new issue for the review itself will be created.

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/97. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
Alright, thanks @stijnvanhoey and @quaquel for agreeing to review! (Any of the others I pinged: you are welcome to contribute as well if you have the bandwidth.)

The review itself will take place in #97; if you haven't reviewed for JOSS before, please check out the reviewer guidelines: http://joss.theoj.org/about#reviewer_guidelines

Thanks again!
