### ISSUE TITLE
[PRE REVIEW]: An Extensible Framework for Compairing Equity Portfolio Creation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#952]
**Submitting author:** @Alasdair-Macindoe (<a href="http://orcid.org/0000-0002-8712-2582">Alasdair Macindoe</a>)
**Repository:** <a href="https://github.com/Alasdair-Macindoe/financeframework" target ="_blank">https://github.com/Alasdair-Macindoe/financeframework</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @Alasdair-Macindoe. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Alasdair-Macindoe if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #952 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    365      0 --:--:-- --:--:-- --:--:--   369
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00952.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by brainstorm** [comment]
@Alasdair-Macindoe a quick look at your code reveals that you have no automated tests (required for a successful JOSS submission), although I see you had plans to implement them?: https://github.com/Alasdair-Macindoe/financeframework/issues/36

@arfon Something went wrong with whedon fetching that pdf?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00952/joss.00952/10.21105.joss.00952.pdf)

**Comment by jedbrown** [comment]
Note that "compairing" in the title is misspelled. While JOSS papers are typically short, this paper.md is unusually short. Please see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain.

**Comment by arfon** [comment]
Closing this due to lack of responses from the submitting author.
