### ISSUE TITLE
[PRE REVIEW]: eSCAPE: parallel global-scale landscape evolution model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#953]
**Submitting author:** @tristan-salles (<a href="http://orcid.org/0000-0001-6095-7689">Tristan Salles</a>)
**Repository:** <a href="https://github.com/Geodels/eSCAPE" target ="_blank">https://github.com/Geodels/eSCAPE</a>
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewers:** @sgrieve, @kbarnhart

**Author instructions**

Thanks for submitting your paper to JOSS @tristan-salles. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@tristan-salles if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #953 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #953 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@tristan-salles, please make this change to your `paper.md` file:

```
Change this line:

![Example of **eSCAPE** output showing Earth evolution in the future after 100,000 years of constant sea-level and uniform precipitation.](https://github.com/Geodels/eSCAPE/blob/master/images/FA.png)

to this:

![Example of **eSCAPE** output showing Earth evolution in the future after 100,000 years of constant sea-level and uniform precipitation.](https://raw.githubusercontent.com/Geodels/eSCAPE/master/images/FA.png)
```

**Comment by arfon** [comment]
@kthyng - this also looks like it might be a good fit for your background?

**Comment by tristan-salles** [comment]
Done!

Tristan Salles | Lecturer
The University of Sydney
Faculty of Science, School of Geosciences
Rm 454, Madsen Building F09 | The University of Sydney | NSW | 2006
+61 2 8627 4123<tel://8627%204123>  | +61 451 462 502<tel://+61%20451%20462%20502>
tristan.salles@sydney.edu.au<mailto:firstname.surname@sydney.edu.au>  | sydney.edu.au<http://sydney.edu.au/>
[ web-profile<https://tristansalles.github.io/>   |   badlands<http://github.com/badlands-model> ]
CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this email if necessary.


On 16 September 2018 at 9:58:41 pm, Arfon Smith (notifications@github.com<mailto:notifications@github.com>) wrote:

@tristan-salles<https://protect-au.mimecast.com/s/7ixyCxnMRvtOrNJpiwwxQF?domain=github.com>, please make this change to your paper.md file:

Change this line:

![Example of **eSCAPE** output showing Earth evolution in the future after 100,000 years of constant sea-level and uniform precipitation.](https://github.com/Geodels/eSCAPE/blob/master/images/FA.png<https://protect-au.mimecast.com/s/dD44Cr8DLRt9LJAyU7LBHs?domain=github.com>)

to this:

![Example of **eSCAPE** output showing Earth evolution in the future after 100,000 years of constant sea-level and uniform precipitation.](https://raw.githubusercontent.com/Geodels/eSCAPE/master/images/FA.png<https://protect-au.mimecast.com/s/EGIxCvl0PoCXMVWJhXCBCm?domain=raw.githubusercontent.com>)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00953/joss.00953/10.21105.joss.00953.pdf)

**Comment by tristan-salles** [comment]
Checked.

Tristan Salles | Lecturer
The University of Sydney
Faculty of Science, School of Geosciences
Rm 454, Madsen Building F09 | The University of Sydney | NSW | 2006
+61 2 8627 4123<tel://8627%204123>  | +61 451 462 502<tel://+61%20451%20462%20502>
tristan.salles@sydney.edu.au<mailto:firstname.surname@sydney.edu.au>  | sydney.edu.au<http://sydney.edu.au/>
[ web-profile<https://tristansalles.github.io/>   |   badlands<http://github.com/badlands-model> ]
CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this email if necessary.

On 16 September 2018 at 22:27:16, whedon (notifications@github.com<mailto:notifications@github.com>) wrote:

👉 Check article proof 📄 👈<https://protect-au.mimecast.com/s/52NBCoVzGQi4xWjRS14cgU?domain=github.com>

**Comment by lheagy** [comment]
My plate is pretty full at the moment. I can take this if need be, but if @kthyng, would be willing to - I would be grateful! Let me know what works

**Comment by kthyng** [comment]
Yes, I will do this!

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@tristan-salles One high level comment: as per the [Review Criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#the-joss-paper), you don't want any instructions on how to use the code in your paper, so I think your "Dependencies and Examples" section should just be in your code documentation.

Do you have any reviewer suggestions? There is a [list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) available, or perhaps you have someone else in mind.

**Comment by tristan-salles** [comment]
Hi @kthyng<https://protect-au.mimecast.com/s/hOpgC0YZWVF88r12f2uMyu?domain=github.com>,

Do you want me to remove this section now? In terms of potential reviewers sgrieve, kbarnhart, rmsare and mdpiper are a good fit for this.

Thanks

Tristan

Tristan Salles | Lecturer
The University of Sydney
Faculty of Science, School of Geosciences
Rm 454, Madsen Building F09 | The University of Sydney | NSW | 2006
+61 2 8627 4123<tel://8627%204123>  | +61 451 462 502<tel://+61%20451%20462%20502>
tristan.salles@sydney.edu.au<mailto:firstname.surname@sydney.edu.au>  | sydney.edu.au<http://sydney.edu.au/>
[ web-profile<https://tristansalles.github.io/>   |   badlands<http://github.com/badlands-model> ]
CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this email if necessary.


On 18 September 2018 at 5:37:14 am, Kristen Thyng (notifications@github.com<mailto:notifications@github.com>) wrote:

@tristan-salles<https://protect-au.mimecast.com/s/U6gfCzvOWKiLL4E4SKtNij?domain=github.com> One high level comment: as per the Review Criteria<https://protect-au.mimecast.com/s/GWLLCwVLQmippykyFV_kVu?domain=joss.readthedocs.io>, you don't want any instructions on how to use the code in your paper, so I think your "Dependencies and Examples" section should just be in your code documentation.

Do you have any reviewer suggestions? There is a list<https://protect-au.mimecast.com/s/zCFyCxnMRvtOOxDxTvxmQB?domain=docs.google.com> available, or perhaps you have someone else in mind.

**Comment by kthyng** [comment]
@tristan-salles Yes, please go ahead and update your paper accordingly, since otherwise I think the reviewers will request that.

Hi @sgrieve and @kbarnhart! Are you willing to refer this submission for JOSS? You can read about the review process [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by sgrieve** [comment]
I'd be delighted to review this! I saw some tweets about this and was planning to play with it, and this will make sure I follow through!

It's the start of teaching for me this week, so I won't have a chance till next week, if that's ok.

**Comment by kthyng** [comment]
@sgrieve That sounds great! Thanks!

In the meantime, I'll start up the Review issue, which is where you should do your review (not in this issue). I'll keep this issue open while I search for a 2nd reviewer.

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/964. Feel free to close this issue now!

**Comment by kbarnhart** [comment]
@kthyng I'd also be happy to review this.

**Comment by kthyng** [comment]
Awesome! I'll add you as a review and close this issue.

**Comment by kthyng** [comment]
@whedon add @kbarnhart as reviewer

**Comment by whedon** [comment]
OK, @kbarnhart is now a reviewer
