### ISSUE TITLE
[PRE REVIEW]: Local clustering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#954]
**Submitting author:** @volfpeter (<a href="http://orcid.org/0000-0002-6226-4277">Péter Volf</a>)
**Repository:** <a href="https://github.com/volfpeter/localclustering" target ="_blank">https://github.com/volfpeter/localclustering</a>
**Version:** v0.10
**Editor:** @pjotrp
**Reviewers:** @DannyArends

**Author instructions**

Thanks for submitting your paper to JOSS @volfpeter. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@volfpeter if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #954 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/954/paper.md): did not find expected comment or line break while scanning a block scalar at line 3 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by volfpeter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #954 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@volfpeter - please format your `paper.md` YAML header _exactly_ as shown in this [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

**Comment by volfpeter** [comment]
Hi!
Thanks. I have one question. What affiliation should i set if i'm not part of any organization (i'm self-employed)?

**Comment by pjotrp** [comment]
Just put in 'Independent' or your company name. I am very supportive of the independents :). We can also start looking for a reviewer. @volfpeter it would be good to put an example/application/figure in your paper to advertise the work. Do you have something that visualizes the algorithm? It is not totally necessary, but I think it will improve the paper. Also you may want to add a paragraph on future plans, if any, and/or how one could expand/modify the library.

**Comment by pjotrp** [comment]
Oh yes, it would also be good to give it a bit more context with references to prior art/state-of-the-art.

**Comment by volfpeter** [comment]
@pjotrp Thanks, i'll use independent then :)

I wanted to make the paper as compact as possible. The details (detailed description, evaluation, ideas for future development) are hidden in the documents that i've referenced in the References section and the readme of the project.

The iPython [notebook](https://github.com/volfpeter/localclustering/blob/master/documents/Algorithm%20Analysis%20with%20the%20Spotify%20Related%20Artists%20Graph.ipynb) referenced in the Resources section contains plenty of plots, charts, and tables. I can take one of them and place it somewhere in the paper.

I'll try to compile a list of papers that are related to this topic. Unfortunately i've originally created this a few years ago (recently i only finalised it and published it on github), so my theoretical knowledge is not quite up-to-date.

**Comment by volfpeter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #954 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    397      0 --:--:-- --:--:-- --:--:--   404
[WARNING] Could not convert image '/tmp/tex2pdf.671/27c95526f725d0a9040932e3bbf71ed2fd90b78e.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.671/27c95526f72
5d0a9040932e3bbf71ed2fd90b78e.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.281 ...26f725d0a9040932e3bbf71ed2fd90b78e.shtml}

Looks like we failed to compile the PDF

**Comment by volfpeter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #954 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    325      0 --:--:-- --:--:-- --:--:--   326
[WARNING] Could not convert image '/tmp/tex2pdf.707/15e88c41169be731ed9e02a4ed7374b7d18063b3.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.707/15e88c41169
be731ed9e02a4ed7374b7d18063b3.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.281 ...41169be731ed9e02a4ed7374b7d18063b3.shtml}

Looks like we failed to compile the PDF

**Comment by volfpeter** [comment]
I've added an example result to the paper.
Now i'm trying to install whedon on my mac, so i can compile the paper locally and not spam the issue with compile errors.

**Comment by pjotrp** [comment]
Hmm. That sounds heroic to me. @arfon do you have any suggestions about this?

**Comment by arfon** [comment]
@volfpeter - this PR should fix your paper compilation issues: https://github.com/volfpeter/localclustering/pull/1

Also, you don't appear to be citing any prior work/related materials in your paper yet.

**Comment by volfpeter** [comment]
@arfon Thanks and yes, the citation list in progress.

**Comment by volfpeter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00954/joss.00954/10.21105.joss.00954.pdf)

**Comment by pjotrp** [comment]
@whedon assing @DannyArends as reviewer

**Comment by pjotrp** [comment]
@whedon assign @DannyArends as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @DannyArends

**Comment by pjotrp** [comment]
We have a great reviewer. @volfpeter when you are done tell us.

**Comment by volfpeter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00954/joss.00954/10.21105.joss.00954.pdf)

**Comment by volfpeter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00954/joss.00954/10.21105.joss.00954.pdf)

**Comment by volfpeter** [comment]
Dear @pjotrp and @DannyArends,
I've added the citations to the paper and a short Ideas for future work section. I think (hope) it is ready for review.

**Comment by pjotrp** [comment]
Thanks. Nice improvement!

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/960. Feel free to close this issue now!

**Comment by volfpeter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00954/joss.00954/10.21105.joss.00954.pdf)

**Comment by volfpeter** [comment]
Thanks, the reason for regenerating it here is that i didn't want to spam that issue with these messages and i wasn't sure the PDF generation would be successful because i changed file references to relative ones.
