### ISSUE TITLE
[REVIEW]: alv: a console-based viewer for molecular sequence alignments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#955]
**Submitting author:** @arvestad (<a href="http://orcid.org/0000-0001-5341-1733">Lars Arvestad</a>)
**Repository:** <a href="https://github.com/arvestad/alv" target ="_blank">https://github.com/arvestad/alv</a>
**Version:** v1.2.0
**Editor:** @yochannah
**Reviewer:** @karinlag, @juanvillada
**Archive:** <a href="https://doi.org/10.5281/zenodo.1477794" target="_blank">10.5281/zenodo.1477794</a>

## Status

[![status](http://joss.theoj.org/papers/b40f61b5ed41e23d4d31b75a5f1129a8/status.svg)](http://joss.theoj.org/papers/b40f61b5ed41e23d4d31b75a5f1129a8)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b40f61b5ed41e23d4d31b75a5f1129a8"><img src="http://joss.theoj.org/papers/b40f61b5ed41e23d4d31b75a5f1129a8/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b40f61b5ed41e23d4d31b75a5f1129a8/status.svg)](http://joss.theoj.org/papers/b40f61b5ed41e23d4d31b75a5f1129a8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/arvestad/alv" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@karinlag & @juanvillada, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @yochannah know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/arvestad/alv">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@arvestad) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/arvestad/alv">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@arvestad) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karinlag, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00955/joss.00955/10.21105.joss.00955.pdf)

**Comment by juanvillada** [comment]
Hi @arvestad, this is a very nice and useful tool!

Some minor suggestions:

1. Installation proceeded smoothly. I just specified a `pip` update to make sure it is updated before installing `alv`:

```sh
pip install --upgrade pip
pip install alv
```
I would suggest you to consider moving the [installation](https://github.com/arvestad/alv#install) section to the top, before the [examples](https://github.com/arvestad/alv#examples).

2. The examples seem enough to show the functions of `alv`. However, in the [examples](https://github.com/arvestad/alv#examples) section appears:

```sh
alf msa.fa
```
Where I suppose it should be:

```sh
alv msa.fa
```

Same for:

```sh
alf -so a,b,c msa.fa
```

3. You may consider moving one of the [screenshots](https://github.com/arvestad/alv#screenshot) to the [introduction section](https://github.com/arvestad/alv#alv-a-command-line-alignment-viewer) in order to call the attention of users.

I already tested `alv` on macOS and will test it on centOS later this week. I will come back with some other comments after that.

Best wishes!

**Comment by arvestad** [comment]
Thanks for the nice comments @juanvillada ! I have adapted your suggestions.

**Comment by yochannah** [comment]
👋 Hey there @karinlag, have you had a chance to look at this yet?

**Comment by karinlag** [comment]
I have now finished my review.

First, @arvestad what a nice little tool!

Install instructions are nice and easy to follow, and it is easy to use and understand. The paper also clearly demonstrates the need, and it seems like this software fills that need. 

I'd like to see a CONTRIBUTING.md file, detailing how to contribute, otherwise this looks good to go for me.

**Comment by juanvillada** [comment]
Hi @arvestad 

Some minor typos to correct in README.md:

1. In the [Introduction](https://github.com/arvestad/alv#alv-a-command-line-alignment-viewer) section, it reads:
>View you**r** DNA or protein.

2. In the next line, it reads:
>but this ha~~ve~~**s** not been tested

`alv` really works nice, I am now using it constantly for visual inspection of codon variants. Thanks @arvestad for taking the time to contribute open source software to the world!

@yochannah, I think I am ready to suggest `alv` for publication once @arvestad follows @karinlag comments.

**Comment by arvestad** [comment]
Thanks @juanvillada and @karinlag for your nice comments!

I have now created CONTRIBUTING.md file, that nicely complements a file THANKS.md that I started just two days ago, and addressed Juan's minor issues. So I think that I have taken care of the points that have been raised. Karin has created a couple of small bug/functionality issues in the alv repo, which I have started to take care of.

Thanks for your careful and constructive reviewing!

**Comment by arvestad** [comment]
I guess I should ping @yochannah too, since I think that I have addressed all the reviewer's points.

**Comment by karinlag** [comment]
Checked off a few more, comfortable to move forward.

**Comment by arvestad** [comment]
Thanks @karinlag ! 
I'd just like to point out that the remaining non-checked item is about community guidelines and based on Karin's feedback I have added a file CONTRIBUTING.md (see https://github.com/arvestad/alv/blob/master/CONTRIBUTING.md) that I believe meets the requested needs.

**Comment by karinlag** [comment]
Hadn't caught that, good to proceed!

**Comment by arvestad** [comment]
Hey @yochannah , no stress, pinging in case you missed that Karin gave her go-ahead.
Cheers,
L

**Comment by yochannah** [comment]
Whoops, thanks for the ping!

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00955/joss.00955/10.21105.joss.00955.pdf)

**Comment by yochannah** [comment]
Okay, all looks good! 💯 

@arvestad - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive?

**Comment by arvestad** [comment]
Thanks a lot @yochannah . I have now put it on Zenodo and the DOI is 10.5281/zenodo.1477804.

Just to avoid confusion: I made a first erroneous Zenodo submission based on a development branch, so the DOI you see here is the second attempt. :-)

**Comment by yochannah** [comment]
@arvestad thanks! One small thing: in the Zenodo archive, there are two authors listed, but in the paper only one. You might need to edit the Zenodo metadata to remove any automatically added authors (I'm told this is a thing; I've never tried it myself so let me know how you get on!)

**Comment by yochannah** [comment]
@whedon set 10.0.20.161/zenodo.1477804 as archive

**Comment by whedon** [comment]
10.0.20.161/zenodo.1477804 doesn't look like an archive DOI.

**Comment by yochannah** [comment]
@whedon set 10.5281/zenodo.1477794 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1477794" target="_blank">10.5281/zenodo.1477794</a> is the archive.

**Comment by yochannah** [comment]
@arfon I think we're ready to accept!! 💯

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/59

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/59, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/60
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00955](https://doi.org/10.21105/joss.00955)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@karinlag, @juanvillada - many thanks for your reviews here and to @yochannah for editing this submission ✨ 

@arvestad - your paper is now accepted into JOSS :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/.00955/status.svg)](https://doi.org/10.21105/.00955)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/.00955">
  <img src="http://joss.theoj.org/papers/10.21105/.00955/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/.00955/status.svg
   :target: https://doi.org/10.21105/.00955
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/.00955/status.svg)](https://doi.org/10.21105/.00955)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by arvestad** [comment]
@arfon Hi, just a small note: the Markdown badge does not contain the right DOI. Should I file this as an issue somewhere? I edited it by hand, of course, so no big deal, but some users may not notice the error.

**Comment by arfon** [comment]
> @arfon Hi, just a small note: the Markdown badge does not contain the right DOI. Should I file this as an issue somewhere? I edited it by hand, of course, so no big deal, but some users may not notice the error.

@arvestad - this was a bug earlier. This _should_ be fixed now.
