### ISSUE TITLE
[PRE REVIEW]: Opycleid: A Python package for transformational music theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#956]
**Submitting author:** @AlexPof (<a href="http://orcid.org/0000-0002-3767-0361">Alexandre Popoff</a>)
**Repository:** <a href="https://github.com/AlexPof/opycleid" target ="_blank">https://github.com/AlexPof/opycleid</a>
**Version:** 0.2.5
**Editor:** @danielskatz
**Reviewers:** @drvinceknight, @adammichaelwood

**Author instructions**

Thanks for submitting your paper to JOSS @AlexPof. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@AlexPof if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #956 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:116:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:103:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @danielskatz - the submitting author suggested you as the handling editor.

**Comment by AlexPof** [comment]
I'm fixing some bugs in the paper.md and paper.bib files.

@whedon generate pdf

**Comment by AlexPof** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00956/joss.00956/10.21105.joss.00956.pdf)

**Comment by danielskatz** [comment]
I'm glad to have my musical abilities and affinities recognized, and I will attempt to handle this as the editor.

**Comment by AlexPof** [comment]
@danielskatz - Thank you for accepting to be the editor for this submission. I'm afraid I'm not familiar enough with the reviewers which are mentionned in the list to make a proper choice. May I perhaps suggest drvinceknight who seems to be familiar with sagemath and Python, and who might be interested by the algebraic and computational aspects ?

**Comment by danielskatz** [comment]
@drvinceknight - would you be willing to be one of the reviewers for this submission?

**Comment by drvinceknight** [comment]
Yup no problem at all :+1:

(We're expecting an increment to our little family over next couple of days/weeks so my review could be slightly delayed.)

**Comment by danielskatz** [comment]
Thanks @drvinceknight  - I'm also working on finding another review by email, so this likely won't start immediately.

**Comment by danielskatz** [comment]
@whedon assign @drvinceknight as reviewer

**Comment by AlexPof** [comment]
@danielskatz To anticipate the review process, I have two questions:
- I am not affiliated to any university / lab / etc. I work for a private company, and this package is completely unrelated. Can this be a problem for the submission process ?
- This package is hosted on PyPi and can be installed via pip, with version number 0.2.5. If the review process highlights some changes to be made, does this mean that the version number will have to be changed and the package updated on PyPi ?
Thank you in advance for your help.

**Comment by danielskatz** [comment]
> I am not affiliated to any university / lab / etc. I work for a private company, and this package is completely unrelated. Can this be a problem for the submission process ?

no, this is fine.

> This package is hosted on PyPi and can be installed via pip, with version number 0.2.5. If the review process highlights some changes to be made, does this mean that the version number will have to be changed and the package updated on PyPi ?

yes, that's likely.

**Comment by danielskatz** [comment]
@willingc - would you be interested in reviewing this? (mostly putting this here as a recording mechanism, since we will talk in person tomorrow)

**Comment by adammichaelwood** [comment]
I am happy to be a reviewer on this as well.  I have a music degree and am a python developer and tech writer.

**Comment by adammichaelwood** [comment]
I am happy to be a reviewer on this as well.  I have a music degree and am a python developer and tech writer.

**Comment by danielskatz** [comment]
@adammichaelwood - thanks for agreeing to do this

**Comment by danielskatz** [comment]
@whedon add @adammichaelwood as reviewer

**Comment by whedon** [comment]
OK, @adammichaelwood is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/981. Feel free to close this issue now!

**Comment by willingc** [comment]
> 👋 @willingc - you mentioned a couple of other people on Monday - Can we ping them here and see if they would be able and willing to review this?

It looks like there are now enough reviewers. In the future, would @mscuthbert or @jefftrevino be willing to consider being a reviewer for music submissions for the Journal of Open Source Software (JOSS)?

**Comment by danielskatz** [comment]
👋  @mscuthbert or @jefftrevino - if you are interested in reviewing, please volunteer via http://joss.theoj.org/reviewer-signup.html

**Comment by jefftrevino** [comment]
@willingc Thanks for thinking of me, but I don't know anything about transformational music theory. I use Python to compose by aggregating instances of notational element classes (as in the Abjad API for Formalized Score Control), but I don't model these kinds of relationships abstractly in my work, except implicitly through generative processes. (Although perhaps I should....)

**Comment by mscuthbert** [comment]
@jefftrevino I think that @willingc is asking if we’d be willing to review open source projects in music in general and not this particular one. To which I say, “of course!”
