### ISSUE TITLE
[REVIEW]: Verde: Processing and gridding spatial data using Green's functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#957]
**Submitting author:** @leouieda (<a href="http://orcid.org/0000-0001-6123-9515">Uieda, L</a>)
**Repository:** <a href="https://github.com/fatiando/verde" target ="_blank">https://github.com/fatiando/verde</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewer:** @fourndo, @Fil
**Archive:** <a href="https://doi.org/10.5281/zenodo.1421979" target="_blank">10.5281/zenodo.1421979</a>

## Status

[![status](http://joss.theoj.org/papers/610a04bf43ba7913a1ad3b504aa02577/status.svg)](http://joss.theoj.org/papers/610a04bf43ba7913a1ad3b504aa02577)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/610a04bf43ba7913a1ad3b504aa02577"><img src="http://joss.theoj.org/papers/610a04bf43ba7913a1ad3b504aa02577/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/610a04bf43ba7913a1ad3b504aa02577/status.svg)](http://joss.theoj.org/papers/610a04bf43ba7913a1ad3b504aa02577)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fatiando/verde" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fourndo & @Fil, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fatiando/verde">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@leouieda) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fatiando/verde">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@leouieda) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fourndo, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00957/joss.00957/10.21105.joss.00957.pdf)

**Comment by lheagy** [comment]
Many thanks @fourndo, @Fil for being willing to review 🎉. Above, there is a checklist for each of you to work through to guide the review. Please let me know if you have any questions or if I can provide any clarification!

**Comment by leouieda** [comment]
Hi @fourndo and @Fil, thanks for taking the time to review! Just to let you know that conda installation isn't working right now because of conda-forge/staged-recipes#6659. I'll let you know once that is resolved and we have a working conda package.

**Comment by leouieda** [comment]
The error is resolved and packages are now build and available through conda-forge.

**Comment by Fil** [comment]
I have installed and tested it — no problem! I just would have preferred to start a jupyter notebook rather than tutorials/*py, but that's a personal preference.

**Comment by leouieda** [comment]
The tutorials are converted to notebooks by sphinx-gallery. There's a
button to download them at the bottom of each page, like
https://www.fatiando.org/verde/latest/tutorials/overview.html#sphx-glr-download-tutorials-overview-py

Notebooks are so hard to maintain in version control. I really like this
option of editing a .py but being able to get notebooks in the end :)

**Comment by Fil** [comment]
ha, excellent. I had only tested in my local clone :)

**Comment by lheagy** [comment]
Thanks @Fil for your speedy review! @fourndo: just checking in, when do you think you will have time to get to the review?

**Comment by fourndo** [comment]
Thanks for the reminder. I ll do it this am

**Comment by fourndo** [comment]
@lheagy Where is the ```paper.md``` supposed to be?

**Comment by fourndo** [comment]
Look good on my end. Well done @leouieda

**Comment by lheagy** [comment]
hi @fourndo, the [paper.md](https://github.com/fatiando/verde/blob/master/paper/paper.md) is in the repo, but it is nicer to look at the [pdf version](https://github.com/openjournals/joss-papers/blob/joss.00957/joss.00957/10.21105.joss.00957.pdf) that will be used

**Comment by fourndo** [comment]
@lheagy Yea thanks, I asked too quickly... found it.

**Comment by lheagy** [comment]
Many thanks @fourndo and @Fil for your speedy reviews 🎉 

@leouieda: congrats on a nice piece of work 😄 Can you please archive the package on [Zenodo](https://zenodo.org) or similar and post the doi here?

**Comment by leouieda** [comment]
Thanks @lheagy @fourndo and @Fil! That was very fast. I'm away on a trip without my laptop. I'll create the doi when i get back next week.

**Comment by leouieda** [comment]
@lheagy I already had a Zenodo archive for v1.0.0. Since there weren't changes requested, can we use this one? https://doi.org/10.5281/zenodo.1415280  The only new thing in the repo is the paper.

**Comment by lheagy** [comment]
Thanks @leouieda, yes, that works. Would you mind doing a new release with the final JOSS paper to capture the current state of the repo?

**Comment by leouieda** [comment]
@lheagy OK, I have made all the updates I needed. If the citation in the preview PDF going to be the final one? If so, I'd like to include it in the CITATION file before making the release (this way I don't need a new version just for updating that).

**Comment by leouieda** [comment]
I had a look at other papers and they all used the same DOI and citation as the preview so I went ahead and made a new release (v1.0.1).

This is the Zenodo archive of it: https://doi.org/10.5281/zenodo.1421979

@lheagy we're good to go on my part. Thanks for editing! :1st_place_medal:

**Comment by lheagy** [comment]
@whedon set 10.5281/zenodo.1421979 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1421979" target="_blank">10.5281/zenodo.1421979</a> is the archive.

**Comment by lheagy** [comment]
Many thanks @fourndo and @Fil for your speedy reviews! And congratulations @leouieda on your submission 🎉 🎉 

@arfon: this submission is ready to be published

**Comment by arfon** [comment]
@fourndo, @Fil - many thanks for your reviews here and to @lheagy for editing this submission ✨ 

@leouieda - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00957  :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00957/status.svg)](https://doi.org/10.21105/joss.00957)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00957">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00957/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00957/status.svg
   :target: https://doi.org/10.21105/joss.00957
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00957/status.svg)](https://doi.org/10.21105/joss.00957)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by leouieda** [comment]
@arfon @lheagy thanks!
