### ISSUE TITLE
[PRE REVIEW]: Easily Carry Out Latent Profile Analysis (LPA) Using Open-Source or Commercial Software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#958]
**Submitting author:** @jrosen48 (<a href="http://orcid.org/0000-0003-2170-0447">Joshua Rosenberg</a>)
**Repository:** <a href="https://github.com/jrosen48/tidyLPA" target ="_blank">https://github.com/jrosen48/tidyLPA</a>
**Version:** 0.2.1 (development version; most recent CRAN version is 0.2.0)
**Editor:** @arfon
**Reviewers:** @jnese, @strengejacke

**Author instructions**

Thanks for submitting your paper to JOSS @jrosen48. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jrosen48 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #958 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/958/paper.md): mapping values are not allowed in this context at line 5 column 8 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @leeper - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@jrosen48 - please take a look at these example `paper.md` and `paper.bib` files and format your paper in exactly the same way please: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by jrosen48** [comment]
I'm sorry about that-I've updated these files to be formatted as the example files.

**Comment by arfon** [comment]
Please modify your `paper.md` file to have an `affiliations` section as per the example here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by jrosen48** [comment]
I've updated the `paper.md` file to have the `affiliations` section in the right format. I'm sorry again about that; thank you for walking me through this step that I should have had correct when I submitted.

**Comment by jrosen48** [comment]
I'd like to suggest the following as potential reviewers (if they are available and willing):

- @strengejacke 
- @jnese (if I understand correctly through a colleague, he uses [the commercial software] MPlus and can test functions the subset of functions in the package that require MPlus)

**Comment by strengejacke** [comment]
Yes, I'm available and would like to review the submission.

**Comment by jnese** [comment]
I am also available to to review the submission.

**Comment by strengejacke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00958/joss.00958/10.21105.joss.00958.pdf)

**Comment by jrosen48** [comment]
Hi, this looks good

**Comment by jrosen48** [comment]
Hi @leeper - if it's alright, hoping to check-in regarding the next steps. Thank you very much.

**Comment by arfon** [comment]
@whedon add @jnese as reviewer

**Comment by whedon** [comment]
OK, @jnese is now a reviewer

**Comment by arfon** [comment]
@whedon add @strengejacke as reviewer

**Comment by whedon** [comment]
OK, @strengejacke is now a reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@jnese, @strengejacke, @jrosen48 - @leeper has asked me to cover this review for him. I'll go ahead and set up the main review issue now.

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/978. Feel free to close this issue now!

**Comment by arfon** [comment]
@jnese, @strengejacke, @jrosen48 - please head over to #978 for the actual review issue.
