### ISSUE TITLE
[PRE REVIEW]: MTSS: A CUDA software for the analysis of Multivariate Time Series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#959]
**Submitting author:** @DavideNardone (<a href="http://orcid.org/0000-0003-0486-1791">Davide Nardone</a>)
**Repository:** <a href="https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare" target ="_blank">https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare</a>
**Version:** v1.0.0
**Editor:** @jedbrown
**Reviewers:** @krischer, @karlrupp

**Author instructions**

Thanks for submitting your paper to JOSS @DavideNardone. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@DavideNardone if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @kyleniemeyer - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00959/joss.00959/10.21105.joss.00959.pdf)

**Comment by DavideNardone** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by DavideNardone** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00959/joss.00959/10.21105.joss.00959.pdf)

**Comment by DavideNardone** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00959/joss.00959/10.21105.joss.00959.pdf)

**Comment by DavideNardone** [comment]
@danielskatz Is eventually possibile change the handling editor? The review might take more than what it's written in the `Author Guidelines`.
Thanks.

Regards,
DN

**Comment by danielskatz** [comment]
Who do you suggest?

**Comment by DavideNardone** [comment]
@jedbrown

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@krischer @suyashkumar @scivision Would any of you be available to review this submission?

**Comment by krischer** [comment]
Yes - but due to existing commitments I could only get this done around November 9th. If that is okay sign me up.

**Comment by jedbrown** [comment]
@krischer That's reasonable. Thanks!

**Comment by jedbrown** [comment]
@whedon add @krischer as reviewer

**Comment by whedon** [comment]
OK, @krischer is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @karlrupp as reviewer

**Comment by whedon** [comment]
OK, @karlrupp is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1049. Feel free to close this issue now!
