### ISSUE TITLE
[PRE REVIEW]: popeye: a population receptive field estimation tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#96]
**Submitting author:** @kdesimone (<a href="http://orcid.org/0000-0003-4254-9408">Kevin DeSimone</a>)
**Repository:** <a href="https://github.com/kdesimone/popeye" target ="_blank">https://github.com/kdesimone/popeye</a>
**Version:** v.1.0.0
**Editor:** @cMadan
**Reviewer:** @tknapen

**What this issue is for**

Thanks for submitting your paper to JOSS @kdesimone. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 thanks @cMadan.

**Comment by cMadan** [comment]
@kdesimone - I've been trying to find a reviewer but haven't been able to yet. Would you like to suggest one?

**Comment by arokem** [comment]
Maybe someone  from the psychopy community would be willing and able to do this?

cc @psychopy/psychopy

**Comment by arokem** [comment]
Another direction are members of the Nilearn team (@bthirion and his team, for example)

**Comment by kdesimone** [comment]
I was going to suggest nipy contributors ...

https://github.com/orgs/nipy/people

**Comment by cMadan** [comment]
@mih, @alexis-roche, @satra, @chrisfilo - would any of you be interested in reviewing this submission? (If not, any suggestions on who else we could ask?) Thanks!

**Comment by tknapen** [comment]
I'd like to volunteer for this, I and a few of my lab members would love to run through the Popeye code.

**Comment by cMadan** [comment]
@tknapen - awesome, thank you! Please see the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines

@whedon assign @tknapen as reviewer

**Comment by cMadan** [comment]
@whedon assign @tknapen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tknapen

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/103. Feel free to close this issue now!
