### ISSUE TITLE
[PRE REVIEW]: FixedPointFinder: A Tensorflow toolbox for identifying and characterizing fixed points in recurrent neural networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#962]
**Submitting author:** @mattgolub (<a href="http://orcid.org/0000-0003-4508-0537">Matthew Golub</a>)
**Repository:** <a href="https://github.com/mattgolub/fixed-point-finder" target ="_blank">https://github.com/mattgolub/fixed-point-finder</a>
**Version:** v1.0
**Editor:** @arokem
**Reviewers:** @malmaud

**Author instructions**

Thanks for submitting your paper to JOSS @mattgolub. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mattgolub if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00962/joss.00962/10.21105.joss.00962.pdf)

**Comment by mattgolub** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00962/joss.00962/10.21105.joss.00962.pdf)

**Comment by mattgolub** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00962/joss.00962/10.21105.joss.00962.pdf)

**Comment by mattgolub** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00962/joss.00962/10.21105.joss.00962.pdf)

**Comment by mattgolub** [comment]
@arokem I'm having trouble getting both of the figures to display in the acticle proof pdf. Are you able to help with this? Both figures appear on the Github preview of the paper.md file.

**Comment by arfon** [comment]
@mattgolub - I've fixed the paper in https://github.com/mattgolub/fixed-point-finder/pull/1 . The `---` lines seemed to be suppressing the figure captions.

**Comment by arokem** [comment]
@whedon set arokem as editor

**Comment by arokem** [comment]
@mattgolub : happy to edit this submission. Looks interesting! 

While I look around the submissions, do you have any suggestions for reviewers?

**Comment by arokem** [comment]
@mattgolub: Could you please clarify the relationship between this software and "recurrent whisperer"? Is it really an independent software library?

**Comment by mattgolub** [comment]
@arokem RecurrentWhisperer is another repository with code we have developed for training recurrent neural networks (RNNs) using Tensorflow. It is used to train the RNN used in the example that we provide, but it is not required (in general) to use FixedPointFinder.

FixedPointFinder is a tool meant for studying an RNN. The RNN to be studied will be different for each user--some may study RNNs they have trained, and others may study untrained (randomized) networks. FixedPointFinder is appropriate for all of these cases. In the example, we study of a network that we train using RecurrentWhisperer.

From a software engineering, it makes sense to keep RecurrentWhisperer as a separate repository, as it is used for other projects. However, if necessary for this submission, we can consider adding a copy of it into FixedPointFinder.

**Comment by mattgolub** [comment]
@arokem Are you still in need of reviewer suggestions? What are the criteria of a good reviewer candidate? Would it be the same as for a reviewer in our field-specific journals (computational neuroscience)?

**Comment by arokem** [comment]
Hi @mattgolub : thanks for the clarification. That makes sense. 

As for reviewer: yes, if you have any suggestions for reviewers, that would be helpful. Maybe the author of similar software that you use yourself? It has to be someone who understands the development process and is able to weigh in on the organization of the software for use by others. Domain expertise is also good, but I would say that it's secondary. I'll look for someone as well.

**Comment by arokem** [comment]
👋 Hey @hiendn! Would you be willing to review this article for JOSS?

**Comment by hiendn** [comment]
> 👋 Hey @hiendn! Would you be willing to review this article for JOSS?

Hi @arokem. Unfortunately I am a bit overloaded at the moment. I will have to pass on this one :(

**Comment by mattgolub** [comment]
Hi @arokem. We can suggest Eric Jang (ejang@google.com) as a reviewer. He is an engineer at Google Brain with neuroscience interests.

Is one reviewer sufficient here? We can continue racking our brains for others if necessary.

**Comment by arokem** [comment]
Thanks for the suggestion. I would rather try to find someone who doesn't share an affiliation with one of the authors, if possible.

@malmaud: would you be willing to review this article for JOSS?

**Comment by malmaud** [comment]
Ya sure.

**Comment by arokem** [comment]
@whedon assign @malmaud as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @malmaud

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1003. Feel free to close this issue now!

**Comment by arokem** [comment]
@malmaud : thanks for agreeing to review this! Please head over to #1003 for your reviewer check list. I'll close this one.
