### ISSUE TITLE
[PRE REVIEW]: Mobile Gaze Mapping: A Python package for mapping mobile gaze data to a fixed target stimulus

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#963]
**Submitting author:** @jeffmacinnes (<a href="http://orcid.org/0000-0003-2388-0699">Jeffrey MacInnes</a>)
**Repository:** <a href="https://github.com/jeffmacinnes/mobileGazeMapping" target ="_blank">https://github.com/jeffmacinnes/mobileGazeMapping</a>
**Version:** v1.0.0
**Editor:** @cMadan
**Reviewers:** @nnadeau

**Author instructions**

Thanks for submitting your paper to JOSS @jeffmacinnes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jeffmacinnes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #963 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:36:in `block in build_affiliation_string': Problem with affiliations for Elizabeth N. Johnson, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:35:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:35:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:11:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:108:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:108:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
:wave: @cMadan - the submitting author suggested you as the handling editor.

**Comment by cMadan** [comment]
Hi @jeffmacinnes! Do you have any suggestions for reviewers for this submission?

It would also be great if you can try and resolve the paper compiling errors above. After you've attempted to correct it, post a comment with just the text `@whedon generate pdf` to try and re-run the compile command

**Comment by jeffmacinnes** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by jeffmacinnes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #963 with the following error: 

 /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:36:in `block in build_affiliation_string': Problem with affiliations for Elizabeth N. Johnson, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:35:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:35:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/author.rb:11:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:108:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:108:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-2caaf5cba519/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by jeffmacinnes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00963/joss.00963/10.21105.joss.00963.pdf)

**Comment by jeffmacinnes** [comment]
Hi @cMadan! I fixed the PDF issue, and you can find the proof above. From looking through the list of reviewers, I think @shivam11, @nnadeau, and @ionlights would all be well-qualified reviewers with the expertise to assess our methods and the contribution of our package. Please let me know if there's anything else I can do to help. Cheers!

**Comment by nnadeau** [comment]
@cMadan @jeffmacinnes I'm good to review :)

**Comment by cMadan** [comment]
@jeffmacinnes, thanks for sorting that out! It looks like your license is a BSD-3 clause license, but has information about a related patent at the top. I'm not sure if that still fits JOSS' requirements re: using an OSI-approved license, so I'm going to consult with the other JOSS editors and get back to you.

@nnadeau, assuming the license issue get sorted, it would be great to have you as a reviewer!

@shivam11 @ionlights, please let me know if you're also able to review this submission.

**Comment by cMadan** [comment]
@whedon assign @nnadeau as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nnadeau

**Comment by jeffmacinnes** [comment]
@cMadan Preference would be for the MIT license, but our package makes use of the SIFT algorithm (as part of the [OpenCV](https://docs.opencv.org/3.4.3/da/df5/tutorial_py_sift_intro.html) library), which is patented for any commercial use. I included the current license file to address that, but welcome any other suggestions!

**Comment by cMadan** [comment]
@jeffmacinnes, I discussed this wither other JOSS editors and we decided that the license needs to be an OSI-approved license without modification (https://opensource.org/licenses/alphabetical), and that an OSI+Patents license is not acceptable. 

I understand that SIFT is a standard CV method, so I'm not quite sure what to do here. I'll ask and see if any of the other editors can comment here and give you more specific advice.

**Comment by jeffmacinnes** [comment]
@cMadan, gotcha, that's a reasonable policy. I noticed that OpenCV, as well as the [opencv_contrib](https://github.com/opencv/opencv_contrib) extra modules, where SIFT methods are found, are distributed with unmodified 3-clause BSD licenses:

[opencv license](https://github.com/opencv/opencv/blob/master/LICENSE)
[opencv_contrib license](https://github.com/opencv/opencv_contrib/blob/master/LICENSE) 

Would a similar strategy work for our package? Thanks for your help in sorting this out.

**Comment by cMadan** [comment]
Yes, I think that should be fine here. How about you update your license file and I'll then run by the other editors to confirm, though I think that's the best you can do.

**Comment by jeffmacinnes** [comment]
Great, thanks @cMadan -- just updated the repo with the new license

**Comment by cMadan** [comment]
@jeffmacinnes, that looks good to me! I think we can go ahead and start the review now!

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/984. Feel free to close this issue now!
