### ISSUE TITLE
[REVIEW]: dyPolyChord: dynamic nested sampling with PolyChord

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#965]
**Submitting author:** @ejhigson (<a href="http://orcid.org/0000-0001-8383-4614">Edward Higson</a>)
**Repository:** <a href="https://github.com/ejhigson/dyPolyChord" target ="_blank">https://github.com/ejhigson/dyPolyChord</a>
**Version:** v0.0.4
**Editor:** @arfon
**Reviewer:** @andrewfowlie, @zhampel
**Archive:** <a href="https://doi.org/10.5281/zenodo.1439193" target="_blank">10.5281/zenodo.1439193</a>

## Status

[![status](http://joss.theoj.org/papers/d5e465b4d6cecf0de7083c6d7c72951b/status.svg)](http://joss.theoj.org/papers/d5e465b4d6cecf0de7083c6d7c72951b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d5e465b4d6cecf0de7083c6d7c72951b"><img src="http://joss.theoj.org/papers/d5e465b4d6cecf0de7083c6d7c72951b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d5e465b4d6cecf0de7083c6d7c72951b/status.svg)](http://joss.theoj.org/papers/d5e465b4d6cecf0de7083c6d7c72951b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ejhigson/dyPolyChord" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@andrewfowlie & @zhampel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ejhigson/dyPolyChord">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.4)?
- [x] **Authorship:** Has the submitting author (@ejhigson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ejhigson/dyPolyChord">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.4)?
- [x] **Authorship:** Has the submitting author (@ejhigson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by ejhigson** [comment]
(minor addition to paper.md giving more details about performance)

@whedon generate pdf

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00965/joss.00965/10.21105.joss.00965.pdf)

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00965/joss.00965/10.21105.joss.00965.pdf)

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00965/joss.00965/10.21105.joss.00965.pdf)

**Comment by andrewfowlie** [comment]
I have completed the checklist of tasks. The program, documentation and software paper were well-written and I think the program could be very useful for the scientific community.

**Comment by ejhigson** [comment]
@zhampel thank you very much for taking the time to review this software - I really appreciate it! Do you know how long it will take you to finish your review?

I am actually going to submit my PhD thesis on Monday and it would be ideal if this is all done by then and I can cite the paper in it, but this is no big deal so no worries at all if that is not convenient!

**Comment by zhampel** [comment]
@ejhigson I will be done by the weekend for sure, no worries.

**Comment by ejhigson** [comment]
Amazing - thank you very much!!

**Comment by zhampel** [comment]
@ejhigson Yes, I have been checking things for the last few days. I wanted to make a few notes about Installation, Performance and Tests. I will not require these for publication, but I will require you make a few notes in the documentation regarding a few comments I have, and I **strongly** suggest you address after your thesis ;)

**Comment by zhampel** [comment]
Installation
========

Python
-------
I had no troubles installing and subsequently running with Python 3. Your setup.py script works seamlessly there. 

However, I did have issues with Python 2.7. The steps required to get running in Python 2.7 were the following:
1. `virtualenv -p /usr/bin/python2 dyPolyChord_review`
2. `source dyPolyChord_review/bin/activate`
3. `python setup.py install`
4. `pip install futures pytz python-dateutil`
If I didn't perform step 4, then I would get the following main error messages (including a bunch of other import garbage) when running `nosetests`:
- nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
EE
======================================================================
ERROR: Failure: ImportError (No module named concurrent.futures)
- ImportError: No module named concurrent.futures
- ImportError: Missing required dependencies ['pytz', 'dateutil']

After doing so, then the `nosetests` worked fine.

I suggest you simply make a note in the docs that in Python 2.7 you need to run step 4 OR you take time to address this in your setup script reqs. But again, given your thesis, I think the docs method is  sufficient. Of course, if you haven't had these issues before, then please explicitly provide some cmd line steps that work for you.


Finally, with Python 2.7 on my Mac, I had to run additionally run the following to get the `python setup.py install` step to work:
- `pip install pytest-runner nestcheck`


Installation & Performance
===================
PyPolyChord
-------------
In order to get the PyPolyChord functionality to work, I had to run `sudo apt-get install libblacs-mpi-dev` to get mpif90 installed. There is not streamlined PolyChord installation documentation that I could see in the package, unless I completely missed something. In addition, I see that *CCPForge is closing*, so there another repo must be made available for its use in the near future. This is of course beyond the scope of this review, but I wanted to make note of it.

I know that you've discussed and addressed this with @andrewfowlie, so I understand that the package is designed to work without PyPolyChord, but I think that could be clearer in the docs in one of two ways:
- Make the fact that the tests can run without PyPolyChord uber clear, and perhaps provide some examples in the Performance section instead of just pointing the user to your dns package (perhaps you have some figures from writing your thesis... ;) )
- Provide a streamlined installation procedure for all parts, so that the Performance can be verified in a straightforward manner.

If you can show a few examples that would be best, but I leave that up to you.

**Comment by zhampel** [comment]
@ejhigson I think you should make a few notes in your documentation addressing my comments. I have however, checked off all the boxes because the dyPolyChord project is well written, does work as advertised, and is well documented. Good luck with your thesis!

For the purposes of this submission, @arfon I have completed my review.

**Comment by ejhigson** [comment]
> @ejhigson Yes, I have been checking things for the last few days. I wanted to make a few notes about Installation and Performance. I will not require these for publication, but I will require you make a few notes in the documentation regarding a few comments I have, and I **strongly** suggest you address after your thesis ;)

Thank you so much for being so accommodating!!

> However, I did have issues with Python 2.7. The steps required to get running in Python 2.7 were the following:
> 
> 1. `virtualenv -p /usr/bin/python2 dyPolyChord_review`
> 2. `source dyPolyChord_review/bin/activate`
> 3. `python setup.py install`
> 4. `pip install futures pytz python-dateutil`
>    If I didn't perform step 4, then I would get the following main error messages (including a bunch of other import garbage) when running `nosetests`:
> 
> * nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
>   EE
>   ======================================================================
>   ERROR: Failure: ImportError (No module named concurrent.futures)
> * ImportError: No module named concurrent.futures
> * ImportError: Missing required dependencies ['pytz', 'dateutil']
> 
> After doing so, then the `nosetests` worked fine.
> 
> I suggest you simply make a note in the docs that in Python 2.7 you need to run step 4 OR you take time to address this in your setup script reqs. But again, given your thesis, I think the docs method is sufficient. Of course, if you haven't had these issues before, then please explicitly provide some cmd line steps that work for you.

Thank you for pointing this out! I like your testing with a fresh virtualenv - I will use this in future. I managed to replicate this issue and fix it in 05642826781b73868a04f6ba629ce5d7fb271188 by adding
`
':python_version == "2.7"': ['futures', 'pytz',  'python-dateutil']`

to setup.py.

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00965/joss.00965/10.21105.joss.00965.pdf)

**Comment by ejhigson** [comment]
> ## PyPolyChord
> In order to get the PyPolyChord functionality to work, I had to run `sudo apt-get install libblacs-mpi-dev` to get mpif90 installed. There is not streamlined PolyChord installation documentation that I could see in the package, unless I completely missed something. In addition, I see that _CCPForge is closing_, so there another repo must be made available for its use in the near future. This is of course beyond the scope of this review, but I wanted to make note of it.
> 
> I know that you've discussed and addressed this with @andrewfowlie, so I understand that the package is designed to work without PyPolyChord, but I think that could be clearer in the docs in one of two ways:
> 
> * Make the fact that the tests can run without PyPolyChord uber clear, and perhaps provide some examples in the Performance section instead of just pointing the user to your dns package (perhaps you have some figures from writing your thesis... ;) )
> * Provide a streamlined installation procedure for all parts, so that the Performance can be verified in a straightforward manner.
> 
> If you can show a few examples that would be best, but I leave that up to you.

Thank you for pointing this out! Unfortunately I don't have any control over PolyChord and its docs, install method etc. but I know the PolyChord authors are working on improved versions and are aware of the CCPForge closure.

I have updated the dyPolyChord install docs to make it (hopefully) much clearer that the tests run without PolyChord and why they do this. I also do indeed have more tests/plots of dyPolyChord performance which will be released after my PhD :) Unfortunately rigorous performance verification is rather computationally expensive since, the gains are biggest in high dimensional problems and the calculations need to be repeated many times. Nevertheless I intend to make my tests reproducible as much as possible given practical limitations.

**Comment by ejhigson** [comment]
@andrewfowlie and @zhampel thank you very much for taking the time to review this submission! Your feedback has been extremely helpful!

@arfon I think the reviews are now complete. I have archived an up to date version on zenodo at 10.5281/zenodo.1439193

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1439193 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1439193" target="_blank">10.5281/zenodo.1439193</a> is the archive.

**Comment by arfon** [comment]
> @andrewfowlie and @zhampel thank you very much for taking the time to review this submission! Your feedback has been extremely helpful!

Yes, thanks @andrewfowlie and @zhampel for your excellent reviews here. 

@ejhigson - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00965 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00965/status.svg)](https://doi.org/10.21105/joss.00965)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00965">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00965/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00965/status.svg
   :target: https://doi.org/10.21105/joss.00965
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00965/status.svg)](https://doi.org/10.21105/joss.00965)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
