### ISSUE TITLE
[REVIEW]: MCSD: A MATLAB Tool for Monte-Carlo Simulations of Diffusion in biological Tissues

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#966]
**Submitting author:** @davidnsousa (<a href="http://orcid.org/0000-0001-7277-6447">David Sousa</a>)
**Repository:** <a href="https://github.com/davidnsousa/mcsd" target ="_blank">https://github.com/davidnsousa/mcsd</a>
**Version:** v0.1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @nnadeau, @mwacaan
**Archive:** <a href="https://doi.org/10.5281/zenodo.1471546" target="_blank">10.5281/zenodo.1471546</a>

## Status

[![status](http://joss.theoj.org/papers/887b1b7792d59ea6582a4700f8ff98ad/status.svg)](http://joss.theoj.org/papers/887b1b7792d59ea6582a4700f8ff98ad)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/887b1b7792d59ea6582a4700f8ff98ad"><img src="http://joss.theoj.org/papers/887b1b7792d59ea6582a4700f8ff98ad/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/887b1b7792d59ea6582a4700f8ff98ad/status.svg)](http://joss.theoj.org/papers/887b1b7792d59ea6582a4700f8ff98ad)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/davidnsousa/mcsd" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nnadeau & @mwacaan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/davidnsousa/mcsd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@davidnsousa) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/davidnsousa/mcsd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@davidnsousa) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nnadeau, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00966/joss.00966/10.21105.joss.00966.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@nnadeau, @mwacaan this is where the review happens. Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mfroeling want to help review this package?

**Comment by nnadeau** [comment]
@davidnsousa how did `Hugo A. Ferreira` contribute? They are not listed in any commit history.

**Comment by davidnsousa** [comment]
@nnadeau Hugo A. Ferreira contributed to the program, tutorial, replication script and paper, but he did not contribute directly through the GitHub platform to the package maintenance. I took full responsibility on the repository.

**Comment by nnadeau** [comment]
@davidnsousa everything looks good to me! :)

Just fix the following:
- https://github.com/davidnsousa/mcsd/issues/13
- https://github.com/davidnsousa/mcsd/issues/14
- https://github.com/davidnsousa/mcsd/pull/12
- https://github.com/davidnsousa/mcsd/issues/11
- https://github.com/davidnsousa/mcsd/issues/10
- https://github.com/davidnsousa/mcsd/issues/15

**Comment by davidnsousa** [comment]
@nnadeau thank you :) these issues are all fixed!

**Comment by nnadeau** [comment]
@davidnsousa I’m at a conference in Madrid right now, but I’ll finalize everything when I’m back!

**Comment by Kevin-Mattheus-Moerman** [comment]
@mwacaan can you remind us when you are able to work on this review? Thanks! :robot:

**Comment by mwacaan** [comment]
@davidnsousa: in the paper you say: 'no simple and free open-source tools were designed and made available for researchers in this field to test their basic predictions.'
I know of at least the Camino package for Monte Carlo diffusion simulations, but there may/must be more. Can you cite available packages in the pdf?

**Comment by Kevin-Mattheus-Moerman** [comment]
@mwacaan Thanks for your review comments. If you want to open any issues for this submission please do so here: https://github.com/davidnsousa/mcsd/issues. Thanks :rocket:

**Comment by nnadeau** [comment]
@Kevin-Mattheus-Moerman @davidnsousa everything looks good to me :)

@davidnsousa great job fixing the previous issues (especially adding testing)

**Comment by Kevin-Mattheus-Moerman** [comment]
@davidnsousa, reviewer @mwacaan posted these issues (albeit not in the correct repository), have you been able to work on these too? 
https://github.com/openjournals/joss-reviews/issues/1019
https://github.com/openjournals/joss-reviews/issues/1020

**Comment by Kevin-Mattheus-Moerman** [comment]
@nnadeau are you able to tick the boxes at the top of this issue?

**Comment by davidnsousa** [comment]
@nnadeau thank you! :) 

@Kevin-Mattheus-Moerman I am working on these issues.

@mwacaan thank you for your notes. 
- I updated the paper. 
- I fixed the name of the replication script. 
- I do not see how do you get these errors. Everything runs fine locally and I have just updated the repository and the build passes. Are you running the most recent version of the .m files? Did you changed them? Could it be your MATLAB version? Thank you!

**Comment by davidnsousa** [comment]
@mwacaan is there anything I can do to help make the usage of the toolbox clear? Or is there anything more you can tell me about these errors? Thank you.

**Comment by Kevin-Mattheus-Moerman** [comment]
Reviewer @mwacaan has ticked all the boxes above and has e-mail myself and @davidnsousa the following (his first comment is about this issue: https://github.com/davidnsousa/mcsd/issues/16):

> hi David and Kevin,
> 
> the joy of backwards compatibility in matlab. thanks for adding a comment David.
>
> I ticked all boxes assuming that this automatically finalizes my review.
> good luck, best,
> 
> Matthan Caan,

Thanks @mwacaan for your review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00966/joss.00966/10.21105.joss.00966.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@davidnsousa below are some minor issue with the paper. Please work on these and regenerate the paper here by calling `@whedon generate pdf`. 

- [ ] Typo in: `....and any measures the user may want to defined, as well as....`, here `defined` should be `define`. 
- [ ] Please add DOI's or hyperlinks where possible for all references.

**Comment by davidnsousa** [comment]
I was trying to tick the check boxes. The issues are fixed! Thank you!

**Comment by davidnsousa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00966/joss.00966/10.21105.joss.00966.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @davidnsousa can you provide the DOI link for the updated archived version on Zenodo? Has the version/release number been changed or is it still v0.1.0?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon once the author presents the updated version number and DOI or the archived version I recommend we accept this work in JOSS. Thanks @mwacaan and @nnadeau for your review efforts!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1471546 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1471546" target="_blank">10.5281/zenodo.1471546</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/34

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/34, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@nnadeau, @mwacaan - many thanks for your reviews here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@davidnsousa - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00966 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00966/status.svg)](https://doi.org/10.21105/joss.00966)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00966">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00966/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00966/status.svg
   :target: https://doi.org/10.21105/joss.00966
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00966/status.svg)](https://doi.org/10.21105/joss.00966)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by davidnsousa** [comment]
@Kevin-Mattheus-Moerman @nnadeau @mwacaan Thank you! :)

best,

**Comment by nnadeau** [comment]
Congrats :+1:

**Comment by nnadeau** [comment]
@arfon could you please submit this review to Publons? https://publons.com/a/1545968/

**Comment by arfon** [comment]
> @arfon could you please submit this review to Publons? https://publons.com/a/1545968/

I'm not sure I know how to do this sorry :-\ . Any guidance/docs you might be able to point me towards here would be very welcome.

**Comment by nnadeau** [comment]
@arfon, @katyhuff introduced me to `publons`, maybe they have a guideline link?

**Comment by katyhuff** [comment]
I have been adding them myself as editor (so if @nnadeau does a good job reviewing, I got to publons and note this). Since we don't send the "Thank you for your review" email that publons needs (they call it a "review receipt) I think the confirmation that a review happened comes from the editor of the submission. However, the reviewer has github notifications sent to their email, then the final thank you usually works.
