### ISSUE TITLE
[REVIEW]: compboost: Modular Framework for Component-Wise Boosting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#967]
**Submitting author:** @schalkdaniel (<a href="http://orcid.org/0000-0003-0950-1947">Daniel Schalk</a>)
**Repository:** <a href="https://github.com/schalkdaniel/compboost" target ="_blank">https://github.com/schalkdaniel/compboost</a>
**Version:** v0.1.0
**Editor:** @brainstorm
**Reviewer:** @moonso
**Archive:** <a href="https://doi.org/10.5281/zenodo.1460435" target="_blank">10.5281/zenodo.1460435</a>

## Status

[![status](http://joss.theoj.org/papers/94cfdbbfdfc8796c5bdb1a74ee59fcda/status.svg)](http://joss.theoj.org/papers/94cfdbbfdfc8796c5bdb1a74ee59fcda)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/94cfdbbfdfc8796c5bdb1a74ee59fcda"><img src="http://joss.theoj.org/papers/94cfdbbfdfc8796c5bdb1a74ee59fcda/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/94cfdbbfdfc8796c5bdb1a74ee59fcda/status.svg)](http://joss.theoj.org/papers/94cfdbbfdfc8796c5bdb1a74ee59fcda)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/schalkdaniel/compboost" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@moonso, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/schalkdaniel/compboost">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@schalkdaniel) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @moonso it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00967/joss.00967/10.21105.joss.00967.pdf)

**Comment by brainstorm** [comment]
@moonso, please read the instructions on this issue, you are now the reviewer for this JOSS paper, let me know if anything is unclear about how to proceed with it :)

**Comment by moonso** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by moonso** [comment]
Hi @brainstorm ! Thanks for asking me to review, I will do my best here. To start with I have a few questions:

1. The theory and real world use of this project are a bit over my expertise. When I read the [reviewer guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html) it is mostly about testing the functionality of the package so I guess this is my focus?

1. When I post issues in the package should I use some special words to indicate that I am a reviewer? In this case the [LICENCE](https://github.com/schalkdaniel/compboost/blob/master/LICENSE) does not follow any of the approved ones as far as I can tell. Not sure how to communicate that in the issue.

Thx!

**Comment by brainstorm** [comment]
1. Yes, that's right @moonso, your overall task (TL;DR'd) here is to validate the operation/usefulness/completeness of this package.

2. I already assigned you as a reviewer, so whedon, our friendly bot knows you already, no worries ;)

@schalkdaniel, as @moonso points out, you should use a valid, [OSI approved LICENSE](https://opensource.org/licenses/alphabetical).

@moonso You can move on into reviewing the other points while the author addresses things. Thanks a lot for helping out JOSS! ;)

**Comment by schalkdaniel** [comment]
Hi @moonso @brainstorm, I have added another file `LICENSE.md` containing the plain text of the MIT license. The file `LICENSE` is required by CRAN and should just include the year and copyright holder (if I understood that correctly).

**Comment by brainstorm** [comment]
Weird, are you sure @schalkdaniel?:

https://cran.r-project.org/web/licenses/

According to:

https://cran.r-project.org/doc/contrib/Leisch-CreatingPackages.pdf

The format you mention seems to belong to `DESCRIPTION`?

**Comment by schalkdaniel** [comment]
But isn't that what I have done @brainstorm? Maybe I miss something, but my `DESCRIPTION` file contains
```
License: MIT + file LICENSE
```
and refers to the `LICENSE` file as specified in your link and also [here](http://r-pkgs.had.co.nz/description.html). Some other repositories follow the same guidelines, e.g. [iml](https://github.com/christophm/iml), [pdfsearch](https://github.com/lebebr01/pdfsearch), or [checkr](https://github.com/poissonconsulting/checkr).

**Comment by schalkdaniel** [comment]
Ah, yes I see. Originally there were one `LICENSE` and the plain text of the MIT license was included in the `Readme`. The intention to include another `LICENSE.md` file came after looking at repositories from the [tidyverse](https://github.com/tidyverse) (e.g. [dplyr](https://github.com/tidyverse/dplyr)) where they do it like this. :)

**Comment by moonso** [comment]
Hi @schalkdaniel @brainstorm . I'm done with the review now, nice job @schalkdaniel 😸 . The documentation is clear and comprehensive, examples could be followed.
I went through a little installation hell, nice to see that it exists in R to 😛 , it had nothing to do with this package though. It was to install 'devtools' on my Mac OS. 

My only remark is the contribution of the co-authors. Thomas Janek has contributed a fairly small part of the code compare to the main author. Also it is unclear how Bernd Bischl have contributed, I guess he is the PI but I think it should be stated somewhere how this person have contributed.

Again good job!

Best

/Måns

**Comment by moonso** [comment]
I understand. It's a question for @brainstorm

**Comment by brainstorm** [comment]
@arfon Do we have any established policies for contributions that are not reflected/seen on github?

Other than that, this is a thumbs up submission, thanks everyone! 👍

**Comment by arfon** [comment]
> @arfon Do we have any established policies for contributions that are not reflected/seen on github?

Ultimately, authorship is left up to the authors but we have some guidelines here: https://joss.readthedocs.io/en/latest/review_criteria.html#authorship

**Comment by brainstorm** [comment]
Alright, nothing seems off as far as I can see regarding authorship then and the author stated publicly who contributed where.

**Comment by schalkdaniel** [comment]
@brainstorm I have added a file `CONTRIBUTORS.md` and linked on this file from the Readme.

**Comment by schalkdaniel** [comment]
@brainstorm Sure, the link is https://zenodo.org/record/1451302#.W7sPNXUzan8

**Comment by brainstorm** [comment]
@whedon set 10.2402/compboost.0.1.0 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.2402/compboost.0.1.0" target="_blank">10.2402/compboost.0.1.0</a> is the archive.

**Comment by brainstorm** [comment]
@whedon set https://doi.org/10.2402/compboost.0.1.0 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.2402/compboost.0.1.0" target="_blank">10.2402/compboost.0.1.0</a> is the archive.

**Comment by arfon** [comment]
@schalkdaniel  - it doesn't look like `https://doi.org/10.2402/compboost.0.1.0` resolves yet?

**Comment by schalkdaniel** [comment]
@arfon - I have uploaded a new version. The archive is: https://doi.org/10.5281/zenodo.1460435

The problem was that zenodo does not register custom dois. Sorry for that.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1460435 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1460435" target="_blank">10.5281/zenodo.1460435</a> is the archive.

**Comment by arfon** [comment]
@moonso - many thanks for your review here and to @brainstorm for editing this submission ✨ 

@schalkdaniel - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00967 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00967/status.svg)](https://doi.org/10.21105/joss.00967)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00967">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00967/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00967/status.svg
   :target: https://doi.org/10.21105/joss.00967
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00967/status.svg)](https://doi.org/10.21105/joss.00967)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by schalkdaniel** [comment]
Hi @arfon, is it possible to make a small change to the paper? I (stupidly) used a wrong latex symbol and didn't recognize it during the review process. Instead of `\geq` it should be `\gg`.  

It would be really great if I could update the paper with the correct symbol.

Thanks for your efforts!

**Comment by arfon** [comment]
> It would be really great if I could update the paper with the correct symbol.

Sure thing. Please go ahead and push the fix to the `master` branch of your repository and we can recompile the paper.

**Comment by schalkdaniel** [comment]
Thanks! @arfon I have pushed the fix to the master. :-)

**Comment by arfon** [comment]
> Thanks! @arfon I have pushed the fix to the master. :-)

OK, I've updated the paper. This sometimes take a few hours to update on the live site because of caching.
