### ISSUE TITLE
[PRE REVIEW]: TaylorSeries.jl: Taylor expansions in one and many variables in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#968]
**Submitting author:** @lbenet (<a href="http://orcid.org/0000-0002-8470-9054">Luis Benet</a>)
**Repository:** <a href="https://github.com/JuliaDiff/TaylorSeries.jl" target ="_blank">https://github.com/JuliaDiff/TaylorSeries.jl</a>
**Version:** v0.8.0
**Editor:** @jedbrown
**Reviewers:** @sriharikrishna, @tobydriscoll

**Author instructions**

Thanks for submitting your paper to JOSS @lbenet. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lbenet if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jedbrown it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @jedbrown - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #968 with the following error: 

 Can't find any papers to compile :-(

**Comment by lbenet** [comment]
@arfon I didn't know that the paper has to be in master. The paper can be found at https://github.com/JuliaDiff/TaylorSeries.jl/pull/181; shall I merge it to master?

Cc: @dpsanders, coauthor of the package and paper.

**Comment by jedbrown** [comment]
@lbenet Whedon takes the paper from 'master' (unless run manually). If it isn't overly disruptive to you, merging will make the automation do its job. The paper should be part of the repository that is eventually tagged (after acceptance) anyway.

**Comment by lbenet** [comment]
Thanks @jedbrown! I just merged https://github.com/JuliaDiff/TaylorSeries.jl/pull/181, so the paper is now in master. Sorry for the confusion.

Regarding the referees, @ChrisRackauckas, @vchuravy and/or @datseris are certainly good options.

**Comment by ChrisRackauckas** [comment]
I'm a bit busy these next few months but if you need me I can do it.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00968/joss.00968/10.21105.joss.00968.pdf)

**Comment by jedbrown** [comment]
@lbenet It looks like you missed `.jl` in some bib keys. I'll expand my reviewer search.

**Comment by lbenet** [comment]
@jedbrown Thanks a lot! Shall I correct that now or wait for the review?

**Comment by jedbrown** [comment]
We usually work incrementally with reviewers.  You can fix it in a branch if you want to avoid noise on 'master'.

**Comment by lbenet** [comment]
Thanks again; I just pushed the corrections to branch lbenet/corrections_paper; I also created a new PR, though I do not know if it should be merged now, or wait for the review.

**Comment by jedbrown** [comment]
@whedon add @sriharikrishna as reviewer

**Comment by whedon** [comment]
OK, @sriharikrishna is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @tobydriscoll as reviewer

**Comment by jedbrown** [comment]
@arfon Is whedon asleep?

**Comment by whedon** [comment]
OK, @tobydriscoll is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1043. Feel free to close this issue now!

**Comment by lbenet** [comment]
Thanks @jedbrown!

A small note: today the last version of the paper (with the corrected links of the references, https://github.com/JuliaDiff/TaylorSeries.jl/pull/185) was merged into master.
