### ISSUE TITLE
[PRE REVIEW]: perfectns: perfect dynamic and standard nested sampling for spherically symmetric likelihoods and priors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#969]
**Submitting author:** @ejhigson (<a href="http://orcid.org/0000-0001-8383-4614">Edward Higson</a>)
**Repository:** <a href="https://github.com/ejhigson/perfectns" target ="_blank">https://github.com/ejhigson/perfectns</a>
**Version:** v2.1.0
**Editor:** @arfon
**Reviewers:** @ziotom78

**Author instructions**

Thanks for submitting your paper to JOSS @ejhigson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ejhigson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00969/joss.00969/10.21105.joss.00969.pdf)

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00969/joss.00969/10.21105.joss.00969.pdf)

**Comment by ejhigson** [comment]
Perhaps @mattpitkin @ziotom78 @nespinoza @adam-m-jcbs would be willing to review this? Thanks very much!

**Comment by ziotom78** [comment]
Sure, I'll be appy to review this.

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00969/joss.00969/10.21105.joss.00969.pdf)

**Comment by ejhigson** [comment]
@mattpitkin @nespinoza @adam-m-jcbs would you be willing to review this submission? No worries if not, I can suggest alternative reviewers.

Thank you very much for your help with this - it is much appreciated! I am keen to get the review started as I am about to leave my current position and want to wrap up my projects.

**Comment by mattpitkin** [comment]
@ejhigson sorry, I won't be able to do this on a short timescale

**Comment by ejhigson** [comment]
No problem @mattpitkin and thank you anyway! Alternatively, perhaps @andrewfowlie would be willing to review this submission?

**Comment by andrewfowlie** [comment]
Sorry, I’d like to be able to help but we’re moving to China and I’m very busy!

**Comment by ejhigson** [comment]
> Sorry, I’d like to be able to help but we’re moving to China and I’m very busy!
@andrewfowlie no problem thank you anyway and good luck with your move!

**Comment by ejhigson** [comment]
@arfon would you consider allowing this submission to go to review with only one reviewer? Thank you very much for your help!

**Comment by adam-m-jcbs** [comment]
> @mattpitkin @nespinoza @adam-m-jcbs would you be willing to review this submission? No worries if not, I can suggest alternative reviewers.
> 
> Thank you very much for your help with this - it is much appreciated! I am keen to get the review started as I am about to leave my current position and want to wrap up my projects.

Thank you for considering me.  A good-faith review over a short timescale is currently not feasible for me, especially as the statistical theory underlying this project is not something I actively use in my current research and thus would require me to read up on the fundamental literature you cite.  In addition, it would be my first JOSS review and doing something for the first time usually takes me a while.  

I hope next time I'll be in a better position to carry out a timely review.

**Comment by arfon** [comment]
> @arfon would you consider allowing this submission to go to review with only one reviewer? Thank you very much for your help!

Yep, let's get moving.

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/985. Feel free to close this issue now!

**Comment by arfon** [comment]
@ziotom78, @ejhigson - see you over in #985 for the actual review.
