### ISSUE TITLE
[REVIEW]: SALib: An open-source Python library for Sensitivity Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#97]
**Submitting author:** jdherman (<a href="http://orcid.org/0000-0002-4081-3175">Jonathan Herman</a>)
**Repository:** <a href="https://github.com/SALib/SALib" target ="_blank">https://github.com/SALib/SALib</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewer:** @stijnvanhoey
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.233103" target="_blank">10.5281/zenodo.233103</a>

## Status

[![status](http://joss.theoj.org/papers/431262803744581c1d4b6a95892d3343/status.svg)](http://joss.theoj.org/papers/431262803744581c1d4b6a95892d3343)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/431262803744581c1d4b6a95892d3343"><img src="http://joss.theoj.org/papers/431262803744581c1d4b6a95892d3343/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/431262803744581c1d4b6a95892d3343/status.svg)](http://joss.theoj.org/papers/431262803744581c1d4b6a95892d3343)
```

**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SALib/SALib" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)
### Conflict of interest
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SALib/SALib">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (jdherman) made major contributions to the software?
### Functionality
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
Hi @quaquel I can't seem to assign you, but here's the review issue.

**Comment by stijnvanhoey** [comment]
Installation checked for both python 2.7 and 3.5. Able to run the minimal example in both cases.

**Comment by quaquel** [comment]
on what OS did you check it? I have acces macOS, windows 7, windows 10, and if necessary windows server 2012.

**Comment by stijnvanhoey** [comment]
Installed on Ubuntu 16.04 within conda environments.

**Comment by kyleniemeyer** [comment]
Hi @stijnvanhoey @quaquel, any updates on your reviews? Thanks!

**Comment by quaquel** [comment]
I have successfully installed it on both mac and windows, under both python 2.7 and python 3.5.

**Comment by quaquel** [comment]
I have used the various sampling techniques successfully. The claimed functionality is thus working.

**Comment by kyleniemeyer** [comment]
Thanks @quaquel! Could you check off the remaining reviewer questions at the top? Please note that in addition to the functionality, there are questions about the documentation and paper (which @arfon shared a link to a few comments ago). 

@stijnvanhoey your comments are still also welcome!

**Comment by stijnvanhoey** [comment]
In general, I would like to congratulate the authors on the current work. This library is nicely structured, well documented and easy to setup. The issues raised require minor adaptations. 

Some comments:
* As no statement is made about **performance**, this is already checked as such. Still, the current contributing guidelines information is giving an advice about potential benefits by vectorizing functions, I suggest to make an issue from this, cfr. my issue https://github.com/SALib/SALib/issues/116
* With regard to the **community guidelines** and current setup of the paper, I'm wondering if the descriptions and package could not be adapted in order to formalize and simplify the potential extension with new methods (what is the workflow, what kind of tests,..). Also, the current paper is focusing on the 6 currently implemented methods, but when this would increase, this kind of information will be outdated (as well as the paper). How does this work? Should the paper be updated at that moment?

**Comment by kyleniemeyer** [comment]
Thanks @stijnvanhoey—both to you and @quaquel, what about the "Example usage" question above?

@jdherman: it looks like some issues/concerns have been raised regarding the testing, documentation, and community guidelines. Could you resolve/respond to these?

**Comment by jdherman** [comment]
Thanks @stijnvanhoey and @kyleniemeyer. I'm at a conference right now but I will resolve the issues as soon as possible (hopefully next week).

**Comment by kyleniemeyer** [comment]
Hi @jdherman, just wanted to ping you on these changes (happy new year!). (That said there's no deadline or anything—the paper will remain "under review" indefinitely until you make the changes.)

**Comment by jdherman** [comment]
Hi @kyleniemeyer and @stijnvanhoey -- we have updated the contributing guidelines, docs, and testing. Thanks for the suggestions, and please see what you think when you have time. Here is the pull request (now merged):
https://github.com/SALib/SALib/pull/120

**Comment by kyleniemeyer** [comment]
Thanks @jdherman! 

@stijnvanhoey could you take a look at the changes, and let me know if they satisfy your outstanding issues?

**Comment by stijnvanhoey** [comment]
Thanks @jdherman and @willu47 for the work and revisions of the guidelines and documentation. I do like the scope and structure of the package. Tests and examples are available for the user as well. All issues are closed and checked, so I'm perfectly fine with publication. 

Just some minor remark, the link to the advanced readme on the [github page](http://salib.github.io/SALib/) does not work: http://salib.github.io/SALib/README-advanced.md

**Comment by willu47** [comment]
Thank you @stijnvanhoey for the comments. It has been a productive (and enjoyable!) process to go through.

Regarding the broken links, I also spotted these yesterday and have made a new issue to prompt a fix. I'll get around to tidying up the page asap.

Thanks again. 👍

**Comment by kyleniemeyer** [comment]
@stijnvanhoey 🚀 

@willu47 sounds great! It seems this is the only outstanding issue, so when you've made that change please let us know. Also create an archive for the software, and report it here—then we'll be done!

**Comment by jdherman** [comment]
Thanks again @kyleniemeyer and @stijnvanhoey , this has helped a lot. 

I fixed the broken links on the landing page (see [here](http://salib.github.io/SALib)) as well as a few other bugs. 

This is all wrapped up in a new version number, [v1.0.2](https://github.com/SALib/SALib/releases), which is also updated on PyPI.

**Comment by kyleniemeyer** [comment]
@jdherman ⚡️ Can you give a new DOI associated with this version? That's the last bit we need.

**Comment by jdherman** [comment]
It's still in the process of being activated, but according to Zenodo it looks like it will be: 10.5281/zenodo.233103

**Comment by kyleniemeyer** [comment]
Thanks @jdherman, I'll hold off closing this until the DOI is available via https://doi.org/10.5281/zenodo.233103 (it still isn't resolving for me)

**Comment by jdherman** [comment]
Ok thanks. I'm not sure how long it should take. @willu47 can you check if I did something wrong? It looks like the new DOI was created for the release:
https://zenodo.org/account/settings/github/repository/SALib/SALib

but still doesn't resolve after 4 hours. How long does it usually take?

**Comment by kyleniemeyer** [comment]
Yeah, that's a bit strange- when I upload something to Zenodo and it gives me a DOI, it generally resolves pretty much immediately, I think.

That second link is not publicly viewable, although something that has been published/released on Zenodo *will* have a URL there in addition to the DOI (what the DOI resolves to). Perhaps the release hasn't actually been published, and is just a draft?

**Comment by jdherman** [comment]
Hm still not resolving. This is a screenshot of the zenodo page, looks like it's published
![image](https://cloud.githubusercontent.com/assets/1936620/21751837/a4d9e790-d582-11e6-90dd-f45f4aeee361.png)

Maybe it just takes more time. Sorry about this!

**Comment by arfon** [comment]
> Hm still not resolving. This is a screenshot of the zenodo page, looks like it's published

My guess is that this is an issue with Zenodo. @jdherman - might be worth emailing the Zenodo folks if this isn't fixed tomorrow.

**Comment by willu47** [comment]
That's frustrating.  I have sent Zenodo support an e-mail to check up on the DOI.  It should point to [this Zenodo entry](https://zenodo.org/record/233103) but there seems to be something wrong with Zenodo as @arfon suggested.  Fingers crossed it will get fixed asap.  I have checked and rechecked @jdherman & everything seems fine.

**Comment by willu47** [comment]
Okay, DOI LIVE! 🚀 🎸

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.233103 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.233103" target="_blank">10.5281/zenodo.233103</a> is the archive.

**Comment by kyleniemeyer** [comment]
Alright @arfon good to go! Great job @willu47 and @jdherman, thanks for figuring that out.

**Comment by jdherman** [comment]
Great, thanks Will!!

**Comment by arfon** [comment]
Thanks for your review @stijnvanhoey and for editing this one @kyleniemeyer ✨ 

@jdherman - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00097 ⚡️ 🚀 💥
