### ISSUE TITLE
[PRE REVIEW]: piggyback: Managing Larger Data on a GitHub Repository

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#970]
**Submitting author:** @cboettig (<a href="http://orcid.org/0000-0002-1642-628X">Carl Boettiger</a>)
**Repository:** <a href="https://github.com/ropensci/piggyback" target ="_blank">https://github.com/ropensci/piggyback</a>
**Version:** v0.0.6
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @cboettig. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cboettig if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/971. Feel free to close this issue now!
