### ISSUE TITLE
[PRE REVIEW]: Lithology: A Landlab submodule for spatially variable rock properties

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#972]
**Submitting author:** @kbarnhart (<a href="http://orcid.org/0000-0001-5682-455X">Katherine Barnhart</a>)
**Repository:** <a href="https://github.com/landlab/landlab" target ="_blank">https://github.com/landlab/landlab</a>
**Version:** 1.5.4
**Editor:** @kthyng
**Reviewers:** @speleophysics, @tristan-salles

**Author instructions**

Thanks for submitting your paper to JOSS @kbarnhart. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kbarnhart if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
> - I wrote version 1.5.4 because this is the number of the first release version of Landlab that I anticipate this submission being a part of (our next release is in December, we are currently at v1.5.3, and this submission is on the master branch). I haven't tagged a commit because that triggers automatic building of packages.
> - This submission only pertains to the Lithology submodule of Landlab (located at landlab/landlab/components/lithology), not Landlab as a whole. The paper.md is located at landlab/landlab/components/lithology/joss/paper.md. I discussed the appropriate way to handle this submission at Issue #433 and in the interim of implementing a more formal method for specifying the submodule of interest, @arfon recommended that I just make a note here.

Notes from the submitting author ☝️

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00972/joss.00972/10.21105.joss.00972.pdf)

**Comment by arfon** [comment]
:wave: @kthyng - the submitting author suggested you as the handling editor.

**Comment by kbarnhart** [comment]
A couple of questions

1. I've noticed that there is an error in the proofs associated with my not understanding how to the citations correctly. 

How do I cite multiple people at the same time, or add e.g. to the beginning of the citation? 

I had wrote: 
`` (e.g. [@Forte2016Complexites], [@Perne2017Steady])``

Should I have done?
``[e.g., @Forte2016Complexites], [@Perne2017Steady])``

or something else?

2. Should I set up a reserve Zenodo DOI at this point, or is OK to wait to do this until later in the review process?

3. To fix these things do I just make changes on the the Landlab `master` branch and ask `whedon` to recompile the pdf?

thanks!

**Comment by kthyng** [comment]
Hi @kbarnhart! 

> Should I set up a reserve Zenodo DOI at this point, or is OK to wait to do this until later in the review process?

You can do this at the end of the review process.

> To fix these things do I just make changes on the the Landlab master branch and ask whedon to recompile the pdf?

Yes I think so to the master branch part. You can make your changes now and then when your Review issue is opened, `whedon` will try to compile your paper at that time again. I'm not sure you have the authority to ask `whedon` to recompile, but I can do it anyway (or at least I can try!). 

Do you have any suggestions for reviewers? 2 to 4 would be great, so we can get 2 committed reviewers. There is a [list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) of potential reviewers available you can choose from if you don't have anyone in mind.

**Comment by kbarnhart** [comment]
@kthyng some potential reviewers might be:

@speleophysics
@fclubb
@benbovy
@sgrieve 
@tristan-salles

**Comment by sgrieve** [comment]
I'm afraid I wont have time to review this one, since I'm supposed to be working on another JOSS review at the moment. Another potential reviewer might be @dvalters

**Comment by kthyng** [comment]
Hi @speleophysics and @tristan-salles! Are you willing and able to review this submission to JOSS? You can read about the review process [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by speleophysics** [comment]
I can review it, though I do have two other reviews on my plate at the
moment. What is the suggested timeline?
-------------------------
Matt Covington
Associate Professor
Department of Geosciences
340 N. Campus Dr.
216 Gearhart Hall
University of Arkansas
Fayetteville, AR 72701

webpage - http://www.speleophysics.com/
-------------------------

**Comment by speleophysics** [comment]
Should be able to handle that.

**Comment by tristan-salles** [comment]
sounds good will do my best to provide review in the coming 2 weeks!

**Comment by kthyng** [comment]
Awesome! Ok here we go!

**Comment by kthyng** [comment]
@whedon assign @speleophysics as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @speleophysics

**Comment by kthyng** [comment]
@whedon add @tristan-salles as reviewer

**Comment by whedon** [comment]
OK, @tristan-salles is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/979. Feel free to close this issue now!
