### ISSUE TITLE
[REVIEW]: eights: BS 8888:2011 first angle projection drawings from FreeCAD 3D model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#974]
**Submitting author:** @danielhatton (<a href="http://orcid.org/0000-0002-4585-3336">Daniel Hatton</a>)
**Repository:** <a href="https://github.com/danielhatton/eights/" target ="_blank">https://github.com/danielhatton/eights/</a>
**Version:** 0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @devinberg
**Archive:** <a href="https://doi.org/10.5281/zenodo.2531603" target="_blank">10.5281/zenodo.2531603</a>

## Status

[![status](http://joss.theoj.org/papers/c84cff5cc862d37325cc4a525d9ed6fa/status.svg)](http://joss.theoj.org/papers/c84cff5cc862d37325cc4a525d9ed6fa)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c84cff5cc862d37325cc4a525d9ed6fa"><img src="http://joss.theoj.org/papers/c84cff5cc862d37325cc4a525d9ed6fa/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c84cff5cc862d37325cc4a525d9ed6fa/status.svg)](http://joss.theoj.org/papers/c84cff5cc862d37325cc4a525d9ed6fa)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/danielhatton/eights/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@devinberg, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/danielhatton/eights/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0)?
- [x] **Authorship:** Has the submitting author (@danielhatton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @devinberg it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00974/joss.00974/10.21105.joss.00974.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielhatton @devinberg can you provide an update on the review process so far?

**Comment by devinberg** [comment]
@Kevin-Mattheus-Moerman still in progress. A few issues have been cleared up and a few are still pending here: https://github.com/danielhatton/eights/issues

**Comment by danielhatton** [comment]
On Wed, 24 Oct 2018, Kevin Mattheus Moerman wrote:

> @danielhatton @devinberg can you provide an update on the review
> process so far?

@devinberg has proposed several improvements to the software and
(especially) its documentation.  All of @devinberg's propsals are
excellent ideas; so far I have acted on about a third of them.

--

Kind regards,

Dan Hatton

 Dr. Daniel C. Hatton
 Lecturer

 Mechanical and Marine Engineering Subject Group
 Autonomous Marine Systems Research Group

E-mail:<daniel.hatton@plymouth.ac.uk>

Address:School of Engineering,
 University of Plymouth,
 Drake Circus,
 Plymouth,
 UK.
 PL4 8AA

SIP:<daniel.hatton@sip.linphone.org>
Telephone:+44 (0)1752 586191

Fax:+44 (0)1752 586101
________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielhatton how are you getting on? Can you provide an update on progress? Thanks

**Comment by danielhatton** [comment]
On 20 November 2018 08:43:34 GMT, Kevin Mattheus Moerman <notifications@github.com> wrote:
>@danielhatton how are you getting on? Can you provide an update on
>progress? Thanks


I've done nothing further on this since my last message.  Did you have a particular deadline in mind for me to complete @devinberg's suggested improvements?  (It will be quite helpful if the answer is "yes": my task scheduling at the moment is pretty much strictly in chronological order of deadline, so anything for which no specific deadline has been given goes continually to the back of the queue.)




________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the update @danielhatton, I would say that you should aim to have the improvements finished within a month to avoid loosing track of our reviewer.

**Comment by danielhatton** [comment]
On 26 November 2018 10:45:46 GMT, Kevin Mattheus Moerman <notifications@github.com> wrote:
>Thanks for the update @danielhatton, I would say that you should aim to
>have the improvements finished within a month to avoid loosing track of
>our reviewer.


OK.  I'll set myself a deadline four weeks from your message, i.e. 24th December.

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by danielhatton** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielhatton can I help? You can use `@whedon generate pdf` if you like

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00974/joss.00974/10.21105.joss.00974.pdf)

**Comment by devinberg** [comment]
@Kevin-Mattheus-Moerman @danielhatton With the most recent edits and latest release, I feel that the Review Checklist is now satisfied.

**Comment by danielhatton** [comment]
On Wed, 26 Dec 2018, Kevin Mattheus Moerman wrote:

> @danielhatton can I help? You can use `@whedon generate pdf` if you like

I was trying to find out what sequence of shell commands @whedon uses
to process Markdown documents containing JoSS-style \@bibtexlabel
citations, because I was considering using the same method for
citations in a Markdown document within the `eights` project tree.  In
the end, though, I decided I needed a method that would work in
GitHub-flavoured Markdown without any client-side shell commands, so I
found another way.

--

Kind regards,

Dan Hatton

 Dr. Daniel C. Hatton
 Lecturer

 Mechanical and Marine Engineering Subject Group
 Autonomous Marine Systems Research Group

E-mail:<daniel.hatton@plymouth.ac.uk>

Address:School of Engineering,
 University of Plymouth,
 Drake Circus,
 Plymouth,
 UK.
 PL4 8AA

SIP:<daniel.hatton@sip.linphone.org>
Telephone:+44 (0)1752 586191

Fax:+44 (0)1752 586101
________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @devinberg for your review work!

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielhatton congrats I will now recommend that this work is accepted in JOSS for publication. To proceed please do the following:

1. Archive a release of reviewed software using a service like Zenodo (or FigShare or similar, see also https://guides.github.com/activities/citable-code/)
Once you have a DOI of the archived version please list it here. 
2. Please inform us of the version tag for the release that was archived. Should it be v0.1 by now? 

Thanks.

**Comment by danielhatton** [comment]
@Kevin-Mattheus-Moerman 

> congrats I will now recommend that this work is accepted in JOSS for publication.

Brilliant, thank you very much.

> To proceed please do the following:
>     1. Archive a release of reviewed software using a service like Zenodo (or FigShare or similar, see > also https://guides.github.com/activities/citable-code/)
>        Once you have a DOI of the archived version please list it here.
>     2. Please inform us of the version tag for the release that was archived.

Will do.

> Should it be v0.1 by now?

The release of which @devinberg said 'the Review Checklist is now satisfied' was 0.1; but there is now a release 0.2, in which there's been a further clarification to one sentence in the "installation" section of `README.md`.  I think I'll archive and get the DOI for release 0.2.

**Comment by devinberg** [comment]
v0.2 is fine with me

**Comment by danielhatton** [comment]
Excellent.  Release 0.2 of `eights` now has DOI `10.5281/zenodo.2531603`.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @labarba @kyleniemeyer @danielskatz we are good to accept this paper. @devinberg Thanks for your review work!

**Comment by danielhatton** [comment]
On Fri, 11 Jan 2019, Lorena A. Barba wrote:

> @danielhatton Please edit the title of the Zenodo deposit to match
> the title of the JOSS paper. Thanks!


Thanks.  Does the edit I've just made to the Zenodo record do the
trick?

--

Kind regards,

Dan Hatton

 Dr. Daniel C. Hatton
 Lecturer

 Mechanical and Marine Engineering Subject Group
 Autonomous Marine Systems Research Group

E-mail:<daniel.hatton@plymouth.ac.uk>

Address:School of Engineering,
 University of Plymouth,
 Drake Circus,
 Plymouth,
 UK.
 PL4 8AA

SIP:<daniel.hatton@sip.linphone.org>
Telephone:+44 (0)1752 586191

Fax:+44 (0)1752 586101
________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/444
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00974](https://doi.org/10.21105/joss.00974)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @danielhatton, your paper is published!

Heartfelt thanks to the handling editor, @Kevin-Mattheus-Moerman, and the reviewer, @devinberg 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00974/status.svg)](https://doi.org/10.21105/joss.00974)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00974">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00974/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00974/status.svg
   :target: https://doi.org/10.21105/joss.00974
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00974/status.svg)](https://doi.org/10.21105/joss.00974)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by danielhatton** [comment]
On Sun, 20 Jan 2019, Lorena A. Barba wrote:

> Heartfelt thanks to the handling editor, @Kevin-Mattheus-Moerman,
> and the reviewer, @devinberg ?

Seconded.

--

Kind regards,

Dan Hatton

 Dr. Daniel C. Hatton
 Lecturer

 Mechanical and Marine Engineering Subject Group
 Autonomous Marine Systems Research Group

E-mail:<daniel.hatton@plymouth.ac.uk>

Address:School of Engineering,
 University of Plymouth,
 Drake Circus,
 Plymouth,
 UK.
 PL4 8AA

SIP:<daniel.hatton@sip.linphone.org>
Telephone:+44 (0)1752 586191

Fax:+44 (0)1752 586101
________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by danielhatton** [comment]
On Sun, 20 Jan 2019, Lorena A. Barba wrote:

> Heartfelt thanks to the handling editor, @Kevin-Mattheus-Moerman,
> and the reviewer, @devinberg ?

... and to you too.

--

Kind regards,

Dan Hatton

 Dr. Daniel C. Hatton
 Lecturer

 Mechanical and Marine Engineering Subject Group
 Autonomous Marine Systems Research Group

E-mail:<daniel.hatton@plymouth.ac.uk>

Address:School of Engineering,
 University of Plymouth,
 Drake Circus,
 Plymouth,
 UK.
 PL4 8AA

SIP:<daniel.hatton@sip.linphone.org>
Telephone:+44 (0)1752 586191

Fax:+44 (0)1752 586101
________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.
