### ISSUE TITLE
[PRE REVIEW]: GFAKluge: A C++ library and command line utilities for the Graphical Fragment Assembly formats

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#975]
**Submitting author:** @edawson (<a href="http://orcid.org/0000-0001-5448-1653">Eric Dawson</a>)
**Repository:** <a href="https://github.com/edawson/gfakluge" target ="_blank">https://github.com/edawson/gfakluge</a>
**Version:** v1.0.0
**Editor:** @mgymrek
**Reviewers:** @sjackman

**Author instructions**

Thanks for submitting your paper to JOSS @edawson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@edawson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #975 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    145      0 --:--:-- --:--:-- --:--:--   146
Error reading bibliography ./paper.bib (line 8, column 5):
unexpected "a"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @mgymrek - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@edawson - I think you're missing a comma on this line: https://github.com/edawson/gfakluge/blob/master/paper/paper.bib#L7

**Comment by edawson** [comment]
Thanks @arfon ! I've fixed the missing comma on the master branch - do I need to do anything else?

**Comment by edawson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00975/joss.00975/10.21105.joss.00975.pdf)

**Comment by arfon** [comment]
> (Aside - this is a very pleasant way to deal with proofing.)

😬

**Comment by edawson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00975/joss.00975/10.21105.joss.00975.pdf)

**Comment by edawson** [comment]
These proofs look good. Is there more I need to do to bump this towards review?

We'd like to suggest @ctb , @luizirber , @afrubin , @betteridiot  as possible reviewers based on the list of people who have volunteered previously.  @sjackman and @richarddurbin might also have good ideas about possible reviewers (maybe @jts ?). Thanks!

**Comment by sjackman** [comment]
Giorgio Gonnella @ggonnella, author of https://github.com/ggonnella/gfapy and https://github.com/ggonnella/rgfa, is a possible reviewer.

**Comment by mgymrek** [comment]
@ctb @afrubin @betteridiot would either of you be able to review this submission?

**Comment by betteridiot** [comment]
As interesting as this is, I am a reviewer for another JoSS paper right now.

**Comment by mgymrek** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

```

**Comment by mgymrek** [comment]
@whedon assign @sjackman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sjackman

**Comment by mgymrek** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1083. Feel free to close this issue now!
