### ISSUE TITLE
[PRE REVIEW]: Reasons: A digital argument mapping library for modern browsers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#976]
**Submitting author:** @davekinkead (<a href="http://orcid.org/0000-0001-5396-8099">David Kinkead</a>)
**Repository:** <a href="https://github.com/davekinkead/reasons" target ="_blank">https://github.com/davekinkead/reasons</a>
**Version:** v1.0.0
**Editor:** @yochannah
**Reviewers:** @mbod, @andytwoods

**Author instructions**

Thanks for submitting your paper to JOSS @davekinkead. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@davekinkead if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00976/joss.00976/10.21105.joss.00976.pdf)

**Comment by RichardLitt** [comment]
I don't think I would have the requisite experience to judge this adequately from a digital humanities perspective, at the moment.

**Comment by yochannah** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by yochannah** [comment]
Quick update - I sent some mails out to look for reviewers but haven't had any responses yet.

**Comment by yochannah** [comment]
Still trying to chase down some reviewers for this. Thanks for your patience @davekinkead! 

@BasTesterink - I note on the JOSS reviewer list that one of your domain areas is formal logic. Would you be interested in reviewing this package?

**Comment by davekinkead** [comment]
Thanks for keeping us in the loop.

**Comment by mbod** [comment]
I'm happy to take a look at this - I don't have formal logic expertise but
have linguistics, digital humanities and JS knowledge

**Comment by yochannah** [comment]
Excellent! @andytwoods has also agreed to review - I'll kick the review process off now.

**Comment by yochannah** [comment]
@whedon assign @mbod as reviewer

**Comment by yochannah** [comment]
@whedon add @andytwoods as reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, the reviewer is @mbod

**Comment by whedon** [comment]
OK, @andytwoods is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1044. Feel free to close this issue now!

**Comment by yochannah** [comment]
Yay, Whedon is feeling better.

@davekinkead, @andytwoods, and @mbod - let's head over to #1044 to start the review process!
