### ISSUE TITLE
[PRE REVIEW]: TensorFlow.jl: An Idiomatic Julia Front End for TensorFlow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#977]
**Submitting author:** @malmaud (<a href="http://orcid.org/0000-0002-5352-2086">Jonathan Matthew Malmaud</a>)
**Repository:** <a href="https://github.com/malmaud/TensorFlow.jl" target ="_blank">https://github.com/malmaud/TensorFlow.jl</a>
**Version:** v0.10.1
**Editor:** @arokem
**Reviewers:** @jekbradbury

**Author instructions**

Thanks for submitting your paper to JOSS @malmaud. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@malmaud if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the handling editor

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00977/joss.00977/10.21105.joss.00977.pdf)

**Comment by oxinabox** [comment]
I suggest @jekbradbury  might be a good reviewer; though he's not reviewed for JOSS before.
He is familiar with julia, and is on the Google TensorFlow team.
But has never contributed to TensorFlow.jl.

**Comment by jekbradbury** [comment]
Sure, I'd be happy to.

**Comment by arokem** [comment]
@whedon assign @jekbradbury as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jekbradbury

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1002. Feel free to close this issue now!

**Comment by arokem** [comment]
@jekbradbury : thanks for agreeing to review this contribution. Please head over to #1002, where you will find your reviewer check-list. I will close this one.
