### ISSUE TITLE
[REVIEW]: Easily Carry Out Latent Profile Analysis (LPA) Using Open-Source or Commercial Software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#978]
**Submitting author:** @jrosen48 (<a href="http://orcid.org/0000-0003-2170-0447">Joshua Rosenberg</a>)
**Repository:** <a href="https://github.com/jrosen48/tidyLPA" target ="_blank">https://github.com/jrosen48/tidyLPA</a>
**Version:** 0.2.1 (development version; most recent CRAN version is 0.2.0)
**Editor:** @arfon
**Reviewer:** @jnese, @strengejacke
**Archive:** <a href="https://doi.org/10.5281/zenodo.1455773" target="_blank">10.5281/zenodo.1455773</a>

## Status

[![status](http://joss.theoj.org/papers/ccb887b4991abca9517847b016cdb33d/status.svg)](http://joss.theoj.org/papers/ccb887b4991abca9517847b016cdb33d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ccb887b4991abca9517847b016cdb33d"><img src="http://joss.theoj.org/papers/ccb887b4991abca9517847b016cdb33d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ccb887b4991abca9517847b016cdb33d/status.svg)](http://joss.theoj.org/papers/ccb887b4991abca9517847b016cdb33d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jrosen48/tidyLPA" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jnese & @strengejacke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jrosen48/tidyLPA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.2.1 (development version; most recent CRAN version is 0.2.0))?
- [x] **Authorship:** Has the submitting author (@jrosen48) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jrosen48/tidyLPA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.2.1 (development version; most recent CRAN version is 0.2.0))?
- [x] **Authorship:** Has the submitting author (@jrosen48) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jnese, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00978/joss.00978/10.21105.joss.00978.pdf)

**Comment by strengejacke** [comment]
Ok, from my side all issues have been addressed adequately, so I have no further requests to the author(s).

**Comment by arfon** [comment]
@jnese - how are you getting along with your review?

**Comment by jnese** [comment]
It is coming along. Do you have a date by which you would like it completed?

**Comment by arfon** [comment]
> It is coming along. Do you have a date by which you would like it completed?

Ideally in the next couple of weeks?

**Comment by jnese** [comment]
Absolutely. I hope to have it completed in less time than that.

**Comment by jnese** [comment]
Ok, my review is complete.

**Comment by jnese** [comment]
I am happy to accept at this time. Thank you.

**Comment by strengejacke** [comment]
Yes, accept from my point of view.

**Comment by arfon** [comment]
@jrosen48 - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by jrosen48** [comment]
Thank you @strengejacke and @jnese for lending your time and expertise - the package is better and I appreciate the feedback you provided in terms of revisions to make after the paper is accepted, too! Thank you @arfon for your work on this, too - this was a helpful and illuminating peer-review experience and I appreciate your time and expertise as well.

**Comment by jrosen48** [comment]
@arfon thank you again! The archive (on Zenodo) is here: [https://zenodo.org/record/1455773#.W745vFIpAW8](https://zenodo.org/record/1455773#.W745vFIpAW8) and the doi is 10.5281/zenodo.1455773

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1455773 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1455773" target="_blank">10.5281/zenodo.1455773</a> is the archive.

**Comment by arfon** [comment]
@jnese, @strengejacke - many thanks for your reviews here ✨ 

@jrosen48 - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00978 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00978/status.svg)](https://doi.org/10.21105/joss.00978)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00978">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00978/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00978/status.svg
   :target: https://doi.org/10.21105/joss.00978
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00978/status.svg)](https://doi.org/10.21105/joss.00978)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by jrosen48** [comment]
Thanks so much @arfon
