### ISSUE TITLE
[PRE REVIEW]: acronym: An Automatic Reduction Pipeline for Astronomical Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#98]
**Submitting author:** @kweis (<a href="http://orcid.org/0000-0002-4639-1436">Kolby Weisenburger</a>)
**Repository:** <a href="https://github.com/kweis/acronym" target ="_blank">https://github.com/kweis/acronym</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @xuanxu

**What this issue is for**

Thanks for submitting your paper to JOSS @kweis. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
👋  @xuanxu would you be interested in reviewing this submission for us?

**Comment by xuanxu** [comment]
Yes, I can review this, feel free to assign it to me.
(probably I won't have time for it before november 1st, in case someone wants to start reviewing right away)

**Comment by arfon** [comment]
@whedon assign @xuanxu as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @xuanxu

**Comment by arfon** [comment]
@whedon start review magic_word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/102. Feel free to close this issue now!
