### ISSUE TITLE
[REVIEW]: Opycleid: A Python package for transformational music theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#981]
**Submitting author:** @AlexPof (<a href="http://orcid.org/0000-0002-3767-0361">Alexandre Popoff</a>)
**Repository:** <a href="https://github.com/AlexPof/opycleid" target ="_blank">https://github.com/AlexPof/opycleid</a>
**Version:** 0.2.5
**Editor:** @danielskatz
**Reviewer:** @drvinceknight, @danielskatz 
**Archive:** <a href="https://doi.org/10.5281/zenodo.1857913" target="_blank">10.5281/zenodo.1857913</a>

## Status

[![status](http://joss.theoj.org/papers/9cce385bc676b84853e8026ac452eb33/status.svg)](http://joss.theoj.org/papers/9cce385bc676b84853e8026ac452eb33)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9cce385bc676b84853e8026ac452eb33"><img src="http://joss.theoj.org/papers/9cce385bc676b84853e8026ac452eb33/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9cce385bc676b84853e8026ac452eb33/status.svg)](http://joss.theoj.org/papers/9cce385bc676b84853e8026ac452eb33)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/AlexPof/opycleid" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@drvinceknight & @adammichaelwood, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AlexPof/opycleid">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.2.5)?
- [x] **Authorship:** Has the submitting author (@AlexPof) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AlexPof/opycleid">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.2.5)?
- [x] **Authorship:** Has the submitting author (@AlexPof) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @drvinceknight, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00981/joss.00981/10.21105.joss.00981.pdf)

**Comment by danielskatz** [comment]
@drvinceknight and @adammichaelwood - thanks for agreeing to be reviewers.

Please see the instructions above in the start of this issue, and let me know if you have any problems.

**Comment by drvinceknight** [comment]
Just back from paternity leave so will be looking at this next week.

**Comment by danielskatz** [comment]
👋 @adammichaelwood - please let us know how you are getting along on this

**Comment by adammichaelwood** [comment]
I've reviewed the literature and browsed the code. I have not had the
space to do the complete install and use it. I should be able to do that
 in the next week.

**Comment by drvinceknight** [comment]
@AlexPof I have opened https://github.com/AlexPof/opycleid/issues/1 with some initial queries/suggestions. :) :+1:

**Comment by AlexPof** [comment]
@drvinceknight I have made the requested modifications in the repository. I also added some missing DOIs to the `paper.md`.

**Comment by AlexPof** [comment]
@whedon compile

**Comment by AlexPof** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00981/joss.00981/10.21105.joss.00981.pdf)

**Comment by danielskatz** [comment]
👋 @adammichaelwood  - any update from your side?

**Comment by danielskatz** [comment]
👋 @adammichaelwood - We're still waiting to hear from you

**Comment by danielskatz** [comment]
👋 @drvinceknight - note that a number of changes have been made since your initial remarks - perhaps you can check on the response?  And continue your review?

**Comment by drvinceknight** [comment]
Thanks for the changes @AlexPof, everything looks good to me now. I've left one very minor/small suggestion on https://github.com/AlexPof/opycleid/issues/1 but it's in no way a blocker.

**Comment by AlexPof** [comment]
This is ok, I've corrected it in the repository, and closed the issue.

**Comment by AlexPof** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00981/joss.00981/10.21105.joss.00981.pdf)

**Comment by danielskatz** [comment]
I've pinged @adammichaelwood here and in email (5 days ago) will no answer back...

👋  @arfon what do you suggest?

**Comment by adammichaelwood** [comment]
Sorry I've been unresponsive. I will try to work on this today, and leave a note about whether I have gotten through it or what my status is.

**Comment by danielskatz** [comment]
@adammichaelwood - What's happened in the last 9 days?

**Comment by danielskatz** [comment]
@adammichaelwood - What's happened in the last 14 days?

**Comment by danielskatz** [comment]
@adammichaelwood - What's happened in the last 22 days?

**Comment by danielskatz** [comment]
👋  @adammichaelwood - What's happened in the last 28 days?

**Comment by AlexPof** [comment]
@danielskatz I was hoping to be able to cite this in a manuscript submission which is due mid-January, do you think it will possible by then ?

**Comment by danielskatz** [comment]
@AlexPof - sorry for the delay on this.  I've started looking at it myself from the point of view of a reviewer, and once I'm ok with it, we'll go ahead, which hopefully will be quick.

**Comment by danielskatz** [comment]
@adammichaelwood - I'm going to take you off this and do the second review.

**Comment by AlexPof** [comment]
Thank you for your answer. I have responded to the issue you opened on the repository. Please do not hesitate to contact me if you have additional remarks.

**Comment by danielskatz** [comment]
@AlexPof - please add non PyPi build instructions to the README and docs as well.

**Comment by danielskatz** [comment]
You can also upload this version to PyPi.

After that, you should upload the repo to zenodo or similar, and let me know the DOI of the archived version.

**Comment by AlexPof** [comment]
I have added the necessary instructions, uploaded the new version on PyPi, and also uploaded the repo to zenodo. The DOI of the zenodo archived version is 10.5281/zenodo.1857913

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.1857913 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1857913" target="_blank">10.5281/zenodo.1857913</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/96

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/96, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/97
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00981](https://doi.org/10.21105/joss.00981)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
@AlexPof - your paper is now accepted into JOSS ⚡️🚀💥

**Comment by danielskatz** [comment]
@drvinceknight - thanks for your review!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00981/status.svg)](https://doi.org/10.21105/joss.00981)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00981">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00981/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00981/status.svg
   :target: https://doi.org/10.21105/joss.00981
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00981/status.svg)](https://doi.org/10.21105/joss.00981)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
