### ISSUE TITLE
[PRE REVIEW]: treemaker

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#982]
**Submitting author:** @SimonGreenhill (<a href="http://orcid.org/0000-0001-7832-6156">Simon Greenhill</a>)
**Repository:** <a href="https://github.com/simonGreenhill/Treemaker" target ="_blank">https://github.com/simonGreenhill/Treemaker</a>
**Version:** v1.03
**Editor:** @trallard 
**Reviewers:** @RichardLitt, @deniederhut

**Author instructions**

Thanks for submitting your paper to JOSS @SimonGreenhill. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@SimonGreenhill if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00982/joss.00982/10.21105.joss.00982.pdf)

**Comment by SimonGreenhill** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by arfon** [comment]
@trallard - would you be able to edit this submission for JOSS?

**Comment by trallard** [comment]
Sure @arfon 

👋 @SimonGreenhill I will be handling editor for your submission. Have you thought about any reviewers for the package?
If you have not gotten anyone in mind you can check the  current reviewers registered using the following command `@whedon list reviewers`

**Comment by trallard** [comment]
@whedon assign @trallard  as editor

**Comment by SimonGreenhill** [comment]
Thanks @trallard, any of the python people should be ok. It's a very simple package* so should be quite easy to review, I hope

(* in fact, I worry it's _too_ simple, but it does fill a small and annoying gap in the toolkit).

**Comment by arfon** [comment]
> @whedon assign @trallard as editor

Looks like @whedon is sleepy... Let me check in on this...

**Comment by SimonGreenhill** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@acabunoc
@arfon
@arokem
@brainstorm
@cMadan
@danielskatz
@george-githinji
@jakevdp
@jasonclark
@jedbrown
@karthik
@katyhuff
@kthyng
@kyleniemeyer
@labarba
@leeper
@lheagy
@mgymrek
@pjotrp
@tracykteal
@trallard
@yochannah
```

**Comment by SimonGreenhill** [comment]
Perhaps (not `@`'ing them out of politeness): richardlitt, deniederhut, krother, Genomematt (trying to find linguistics/bioinformatics/phylogenetics/anthropology matches)

**Comment by trallard** [comment]
Hi @RichardLitt @deniederhut @krother  @genomematt would any of you be interested in and have availability to review this JOSS submission?
We'd ideally be looking at getting two reviewers

**Comment by trallard** [comment]
hey @RichardLitt  thanks for agreeing to review this submission. I will wait and see if any of the other proposed reviewers would be happy to join before jumping into the formal review process/issue

**Comment by trallard** [comment]
@whedon assign @RichardLitt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @RichardLitt

**Comment by deniederhut** [comment]
@trallard I'm in!

**Comment by trallard** [comment]
@whedon assign @deniederhut as a reviewer

**Comment by trallard** [comment]
@whedon add @deniederhut as reviewer

**Comment by trallard** [comment]
@whedon add @deniederhut as reviewer

**Comment by trallard** [comment]
@whedon add @deniederhut as reviewer

**Comment by whedon** [comment]
OK, @deniederhut is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by trallard** [comment]
Closing this issue now. @deniederhut  and @RichardLitt let's proceed with the review at #1040  🌟
