### ISSUE TITLE
[PRE REVIEW]: Pyoints: A Python package for point cloud, voxel and raster processing.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#983]
**Submitting author:** @laempy (<a href="http://orcid.org/0000-0002-8963-2762">Sebastian Lamprecht</a>)
**Repository:** <a href="https://github.com/laempy/pyoints" target ="_blank">https://github.com/laempy/pyoints</a>
**Version:** v0.2.0a2
**Editor:** @lheagy
**Reviewers:** @kbevers, @scivision

**Author instructions**

Thanks for submitting your paper to JOSS @laempy. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@laempy if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00983/joss.00983/10.21105.joss.00983.pdf)

**Comment by lheagy** [comment]
Hi @arfon, happy to take this!

**Comment by lheagy** [comment]
:wave: Hi @Chilipp, @kbevers, would you be willing to review this submission for JOSS?

**Comment by kbevers** [comment]
@lheagy Yes, I'm happy to review this submission

**Comment by Chilipp** [comment]
@lheagy: unfortunately I won't have enough time within the next two or three weeks, sorry

**Comment by lheagy** [comment]
Excellent, thanks @kbevers for being willing to review and thanks @Chilipp for getting back to me! 

I will try to find one more reviewer before we get the review process started

**Comment by lheagy** [comment]
@whedon assign @kbevers as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kbevers

**Comment by lheagy** [comment]
👋 Hi @Scivision would you be willing to review this submission for JOSS?

**Comment by scivision** [comment]
@lheagy yes thanks

**Comment by lheagy** [comment]
Excellent, thanks @scivision!

**Comment by lheagy** [comment]
@whedon add @scivision as reviewer

**Comment by whedon** [comment]
OK, @scivision is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/990. Feel free to close this issue now!
