### ISSUE TITLE
[REVIEW]: Mobile Gaze Mapping: A Python package for mapping mobile gaze data to a fixed target stimulus

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#984]
**Submitting author:** @jeffmacinnes (<a href="http://orcid.org/0000-0003-2388-0699">Jeffrey MacInnes</a>)
**Repository:** <a href="https://github.com/jeffmacinnes/mobileGazeMapping" target ="_blank">https://github.com/jeffmacinnes/mobileGazeMapping</a>
**Version:** v1.0.0
**Editor:** @cMadan
**Reviewer:** @nnadeau
**Archive:** <a href="https://doi.org/10.5281/zenodo.1494278" target="_blank">10.5281/zenodo.1494278</a>

## Status

[![status](http://joss.theoj.org/papers/241ef433b23ae3839aa762bbe4d9f4f2/status.svg)](http://joss.theoj.org/papers/241ef433b23ae3839aa762bbe4d9f4f2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/241ef433b23ae3839aa762bbe4d9f4f2"><img src="http://joss.theoj.org/papers/241ef433b23ae3839aa762bbe4d9f4f2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/241ef433b23ae3839aa762bbe4d9f4f2/status.svg)](http://joss.theoj.org/papers/241ef433b23ae3839aa762bbe4d9f4f2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jeffmacinnes/mobileGazeMapping" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nnadeau, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jeffmacinnes/mobileGazeMapping">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@jeffmacinnes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nnadeau it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00984/joss.00984/10.21105.joss.00984.pdf)

**Comment by cMadan** [comment]
@nnadeau, thank you for agreeing to review this submission! Let me know if you have any questions :)

**Comment by nnadeau** [comment]
@cMadan I’m at a conference in Madrid right now, but I’ll finalize everything when I’m back!

**Comment by cMadan** [comment]
@nnadeau, no problem, thanks for letting me know!

**Comment by cMadan** [comment]
@nnadeau, during the pre-review (https://github.com/openjournals/joss-reviews/issues/963) I noticed some typos in the README, so I fixed them (https://github.com/jeffmacinnes/mobileGazeMapping/pull/1).

**Comment by zablab** [comment]
> @jeffmacinnes how are your co-authors involved in the repo? They have no commits.

I am one of the co-authors. Trying to streamline correspondence, so letting @jeffmacinnes take the lead--just FYI he's been out of the country for the past week.

**Comment by jeffmacinnes** [comment]
@nnadeau This package is the culmination of a project that my co-authors and I developed and tested over the course of a year. However, it was only recently that we made the decision to modify the tools so that we may release publicly via github and JOSS. The repository only reflects those recent changes.

**Comment by jeffmacinnes** [comment]
Hi @nnadeau, I noticed two pull requests that I had overlooked earlier this week, so went ahead and merged -- thanks for those fixes! I think that we've addressed the other concerns, but please let me know if there's anything else that I'm missing.

**Comment by nnadeau** [comment]
@jeffmacinnes last two issues:
- https://github.com/jeffmacinnes/mobileGazeMapping/issues/14
- https://github.com/jeffmacinnes/mobileGazeMapping/issues/13

Then I believe it's all good to go! Kudos!

**Comment by jeffmacinnes** [comment]
Thanks @nnadeau! I just fixed those last two issues. I really appreciate your help reviewing this repo and helping us get the package prepped for release. @cMadan -- just let us know what's next!

**Comment by cMadan** [comment]
@nnadeau, can you check and see if you're satisfied with those issues? If so, please update the reviewer checklist at the top.

@jeffmacinnes, after @nnadeau confirms everything is all set, I'll look over things one last time and see if there are any minor issues remaining. If not, I'll ask you to archive the code in Zenodo or figshare and you'll be all set! So, just sit tight for now, but we're almost done.

**Comment by nnadeau** [comment]
@cMadan all good :+1: 

Congrats @jeffmacinnes

**Comment by cMadan** [comment]
Thank you for the thorough review, @nnadeau!

@jeffmacinnes, everything looks good to me! Now all I need is the doi for an archived version of the code (i.e., on Zenodo or figshare).

**Comment by jeffmacinnes** [comment]
@cMadan, here you go: 10.5281/zenodo.1494278

Thanks!

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.1494278 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1494278" target="_blank">10.5281/zenodo.1494278</a> is the archive.

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/76

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/76, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by cMadan** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @cMadan, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by cMadan** [comment]
@arfon, can you do the honours?

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/77
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00984](https://doi.org/10.21105/joss.00984)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@nnadeau - many thanks for your review here and to @cMadan for editing this submission ✨ 

@jeffmacinnes - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00984/status.svg)](https://doi.org/10.21105/joss.00984)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00984">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00984/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00984/status.svg
   :target: https://doi.org/10.21105/joss.00984
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00984/status.svg)](https://doi.org/10.21105/joss.00984)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
