### ISSUE TITLE
[REVIEW]: perfectns: perfect dynamic and standard nested sampling for spherically symmetric likelihoods and priors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#985]
**Submitting author:** @ejhigson (<a href="http://orcid.org/0000-0001-8383-4614">Edward Higson</a>)
**Repository:** <a href="https://github.com/ejhigson/perfectns" target ="_blank">https://github.com/ejhigson/perfectns</a>
**Version:** v2.1.0
**Editor:** @arfon
**Reviewer:** @ziotom78
**Archive:** <a href="https://doi.org/10.5281/zenodo.1443509" target="_blank">10.5281/zenodo.1443509</a>

## Status

[![status](http://joss.theoj.org/papers/364e6137dc43aeee3c244a3a8fde16ef/status.svg)](http://joss.theoj.org/papers/364e6137dc43aeee3c244a3a8fde16ef)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/364e6137dc43aeee3c244a3a8fde16ef"><img src="http://joss.theoj.org/papers/364e6137dc43aeee3c244a3a8fde16ef/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/364e6137dc43aeee3c244a3a8fde16ef/status.svg)](http://joss.theoj.org/papers/364e6137dc43aeee3c244a3a8fde16ef)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ejhigson/perfectns" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ziotom78, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ejhigson/perfectns">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.1.0)?
- [x] **Authorship:** Has the submitting author (@ejhigson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ziotom78 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00985/joss.00985/10.21105.joss.00985.pdf)

**Comment by arfon** [comment]
@ziotom78 - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by ejhigson** [comment]
@ziotom78 thank you very much for taking the time to review my submission, I really appreciate it!

Unfortunately for personal reasons it looks like it will be very difficult for me to make changes from (next) Sunday 7th October onwards. I would therefore be extraordinarily grateful if you could do your review this coming week? I am aware the process is normally 2 weeks so please don't worry if this is inconvenient for you! And thank you again very much for your help

**Comment by ziotom78** [comment]
Hi @ejhigson, don't worry, I should be able to complete the review in a few days.

**Comment by ziotom78** [comment]
I've read the paper; it looks ok, there are only one spelling error and one unclear sentence:

- Third paragraph: "such problems provides" should be "such problems provide"
- Same sentence: I do not fully understand the meaning of the clause "…and for use statistical research into nested sampling."

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00985/joss.00985/10.21105.joss.00985.pdf)

**Comment by ejhigson** [comment]
> Hi @ejhigson, don't worry, I should be able to complete the review in a few days.

Thank you so much for this! It is much appreciated.


> I've read the paper; it looks ok, there are only one spelling error and one unclear sentence:
> 
> * Third paragraph: "such problems provides" should be "such problems provide"
> * Same sentence: I do not fully understand the meaning of the clause "…and for use statistical research into nested sampling."

Thank you for pointing these out! They are both typos. The sentence now reads "Furthermore, such problems provide a rich source of test cases for assessing the capacity of other software implementations to perform the nested sampling algorithm accurately, and for use in statistical research into nested sampling."

**Comment by ziotom78** [comment]
@ejhigson , I noticed that some docstrings are not correct:

- The docstring for [`priors.Uniform`](https://github.com/ejhigson/perfectns/blob/master/perfectns/priors.py#L32) and [`priors.Gaussian`](https://github.com/ejhigson/perfectns/blob/master/perfectns/priors.py#L69) are identical

- In the docstrings of these two classes, it might be worth expliciting what is the meaning of the parameter `prior_scale` passed to `__init__` (e.g., in the Gaussian prior it's just the sigma).

**Comment by ejhigson** [comment]
> @ejhigson , I noticed that some docstrings are not correct:
> 
> * The docstring for [`priors.Uniform`](https://github.com/ejhigson/perfectns/blob/master/perfectns/priors.py#L32) and [`priors.Gaussian`](https://github.com/ejhigson/perfectns/blob/master/perfectns/priors.py#L69) are identical
> * In the docstrings of these two classes, it might be worth expliciting what is the meaning of the parameter `prior_scale` passed to `__init__` (e.g., in the Gaussian prior it's just the sigma).
Well spotted! I have fixed this added more information about `prior_scale` as suggested in 2a68a7cea55f330733d028f3563b196915e1f14d

**Comment by arfon** [comment]
@ejhigson - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00985/joss.00985/10.21105.joss.00985.pdf)

**Comment by ejhigson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00985/joss.00985/10.21105.joss.00985.pdf)

**Comment by ejhigson** [comment]
@ziotom78 thank you so much for your very prompt review - it is much appreciated!

**Comment by ejhigson** [comment]
@arfon thank you very much for your help with this! I have archived the latest version at:

10.5281/zenodo.1443509

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1443509 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1443509" target="_blank">10.5281/zenodo.1443509</a> is the archive.

**Comment by arfon** [comment]
@ziotom78 - many thanks for your review here ✨ 

@ejhigson - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00985 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00985/status.svg)](https://doi.org/10.21105/joss.00985)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00985">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00985/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00985/status.svg
   :target: https://doi.org/10.21105/joss.00985
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00985/status.svg)](https://doi.org/10.21105/joss.00985)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
