### ISSUE TITLE
[PRE REVIEW]: fibergen: An introductory tool for FFT-based material homogenization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#986]
**Submitting author:** @fospald (<a href="http://orcid.org/0000-0001-8372-9179">Felix Ospald</a>)
**Repository:** <a href="https://github.com/fospald/fibergen" target ="_blank">https://github.com/fospald/fibergen</a>
**Version:** 2018.1
**Editor:** @jedbrown
**Reviewers:** @tisaac, @ctdegroot

**Author instructions**

Thanks for submitting your paper to JOSS @fospald. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@fospald if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by fospald** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00986/joss.00986/10.21105.joss.00986.pdf)

**Comment by fospald** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00986/joss.00986/10.21105.joss.00986.pdf)

**Comment by fospald** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00986/joss.00986/10.21105.joss.00986.pdf)

**Comment by fospald** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00986/joss.00986/10.21105.joss.00986.pdf)

**Comment by fospald** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00986/joss.00986/10.21105.joss.00986.pdf)

**Comment by fospald** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00986/joss.00986/10.21105.joss.00986.pdf)

**Comment by fospald** [comment]
@arfon now I have the paper and license added

**Comment by fospald** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by jedbrown** [comment]
Thanks for adding the paper @fospald and working with Whedon to get it built. I'm currently reaching out to potential reviewers. Additional suggestions would be welcome. Once we have reviewers, the conversation will move to a new REVIEW issue where they will be able to provide feedback and recommendations.

**Comment by jedbrown** [comment]
@whedon add @tisaac as reviewer

**Comment by whedon** [comment]
OK, @tisaac is now a reviewer

**Comment by fospald** [comment]
@jedbrown thank you for adding the reviewer!
@tisaac thank you for reviewing!

**Comment by jedbrown** [comment]
@nnadeau @ctdegroot Would you be available to review this submission?

**Comment by nnadeau** [comment]
@jedbrown unfortunately, I'll have to pass on this review.

**Comment by ctdegroot** [comment]
@jedbrown Yes, I can review it.

**Comment by jedbrown** [comment]
@whedon add @ctdegroot as reviewer

**Comment by whedon** [comment]
OK, @ctdegroot is now a reviewer

**Comment by jedbrown** [comment]
Thanks, @ctdegroot and @nnadeau for the quick replies.

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1027. Feel free to close this issue now!
