### ISSUE TITLE
[PRE REVIEW]: PyGeoPressure: Geopressure Prediction in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#987]
**Submitting author:** @whimian (<a href="http://orcid.org/0000-0002-4109-6358">Hao Yu</a>)
**Repository:** <a href="https://github.com/whimian/pyGeoPressure" target ="_blank">https://github.com/whimian/pyGeoPressure</a>
**Version:** v0.1.8
**Editor:** @kthyng
**Reviewers:** @WalBytes, @JesperDramsch

**Author instructions**

Thanks for submitting your paper to JOSS @whimian. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@whimian if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by kthyng** [comment]
I can take this on!

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @whimian! Do you have any suggestions for reviewers? [Here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) is a list of people who have volunteered to be potential reviewers you can select from, or you may know others who would be a good fit.

**Comment by whimian** [comment]
Hey @kthyng ! 💭Maybe @WalBytes from the reviewer list. It seems that he's interested in Geophysics and Petroleum Exploration.

**Comment by WalBytes** [comment]
Yes I can review this.

**Comment by whimian** [comment]
@WalBytes Thank you for accepting to review it.

**Comment by whimian** [comment]
@kthyng Could you please assign @WalBytes as the reviewer?

**Comment by kthyng** [comment]
Ok that's great. I would like to have two reviewers.

@JesperDramsch are you interested in reviewing this?

**Comment by JesperDramsch** [comment]
That'd be lovely @kthyng. Thank you for considering me and ping-ing me. I'll gladly accept.

**Comment by kthyng** [comment]
Great, thanks all! I will add you two as reviewers, and close this issue. The official review will take place in a newly-opened issue.

**Comment by kthyng** [comment]
@whedon assign @WalBytes as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @WalBytes

**Comment by kthyng** [comment]
@whedon add @JesperDramsch as reviewer

**Comment by whedon** [comment]
OK, @JesperDramsch is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/992. Feel free to close this issue now!
