### ISSUE TITLE
[REVIEW]: ipc: An R Package for Inter-process Communication

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#988]
**Submitting author:** @ifellows (<a href="http://orcid.org/0000-0003-1261-0925">Ian Fellows</a>)
**Repository:** <a href="https://github.com/fellstat/ipc" target ="_blank">https://github.com/fellstat/ipc</a>
**Version:** 0.1.0
**Editor:** @yochannah
**Reviewer:** @mschubert , @JohnCoene
**Archive:** <a href="https://doi.org/10.5281/zenodo.1478139" target="_blank">10.5281/zenodo.1478139</a>

## Status

[![status](http://joss.theoj.org/papers/d422d276dd8f38e922b151e4ff248230/status.svg)](http://joss.theoj.org/papers/d422d276dd8f38e922b151e4ff248230)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d422d276dd8f38e922b151e4ff248230"><img src="http://joss.theoj.org/papers/d422d276dd8f38e922b151e4ff248230/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d422d276dd8f38e922b151e4ff248230/status.svg)](http://joss.theoj.org/papers/d422d276dd8f38e922b151e4ff248230)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fellstat/ipc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mschubert  & @JohnCoene, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @yochannah know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fellstat/ipc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [x] **Authorship:** Has the submitting author (@ifellows) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fellstat/ipc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [x] **Authorship:** Has the submitting author (@ifellows) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mschubert it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00988/joss.00988/10.21105.joss.00988.pdf)

**Comment by JohnCoene** [comment]
@yochannah Unit tests are present in the package's source code but not coverage is reported due to lack of continuous integration (codecov/coveralls), is it necessary to require adding that?

**Comment by yochannah** [comment]
@ifellows I see no reason to wait until the end - feel free to fix them in real time!

**Comment by yochannah** [comment]
@JohnCoene I think CI goes under the "optional but strongly recommended" category - https://joss.readthedocs.io/en/latest/review_criteria.html#tests - adding CI would be awesome but given we have automated tests that is probably sufficient.

**Comment by ifellows** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00988/joss.00988/10.21105.joss.00988.pdf)

**Comment by ifellows** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00988/joss.00988/10.21105.joss.00988.pdf)

**Comment by yochannah** [comment]
Quick status check - it looks like there are issues in the main repo mentioned directly above that are being worked on, so all is progressing nicely - ping me if there are any more questions or if we're ready to move forward 👍

**Comment by ifellows** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00988/joss.00988/10.21105.joss.00988.pdf)

**Comment by ifellows** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00988/joss.00988/10.21105.joss.00988.pdf)

**Comment by ifellows** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00988/joss.00988/10.21105.joss.00988.pdf)

**Comment by ifellows** [comment]
@mschubert , @JohnCoene: I believe that comments have been addressed. Does everything look good to you both in terms of moving the paper forward?

**Comment by mschubert** [comment]
All my points have been addressed and I'm happy to move this forward @yochannah

Good work @ifellows!

**Comment by ifellows** [comment]
@JohnCoene: Does everything look good in terms of moving the paper forward?

**Comment by JohnCoene** [comment]
@ifellows sorry for the late reply @yochannah, all good on my side too. A great package!

**Comment by yochannah** [comment]
@ifellows - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive?

**Comment by ifellows** [comment]
10.5281/zenodo.1478139


fyi: revised package on it's way to CRAN

**Comment by yochannah** [comment]
@whedon set 10.5281/zenodo.1478139 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1478139" target="_blank">10.5281/zenodo.1478139</a> is the archive.

**Comment by yochannah** [comment]
@arfon Ready to accept! 💯

**Comment by ifellows** [comment]
A hearty thank you to @JohnCoene and @mschubert for reviewing and to @yochannah for shepherding the process. The package has benefited significantly from all of your attention.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/52

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/52, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/53
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00988](https://doi.org/10.21105/joss.00988)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@mschubert , @JohnCoene - many thanks for your reviews here and to @yochannah for editing this submission ✨ 

@ifellows - your paper is now accepted into JOSS :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00988/status.svg)](https://doi.org/10.21105/joss.00988)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00988">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00988/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00988/status.svg
   :target: https://doi.org/10.21105/joss.00988
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00988/status.svg)](https://doi.org/10.21105/joss.00988)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
