### ISSUE TITLE
[PRE REVIEW]: rucrdtw: Fast time series subsequence search in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#99]
**Submitting author:** @pboesu (<a href="http://orcid.org/0000-0001-6723-6833">Philipp Boersch-Supan</a>)
**Repository:** <a href="https://github.com/pboesu/rucrdtw" target ="_blank">https://github.com/pboesu/rucrdtw</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewer:** @masalmon

**What this issue is for**

Thanks for submitting your paper to JOSS @pboesu. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
👋  @masalmon - would you be willing to review this submission for JOSS?

**Comment by masalmon** [comment]
Ok I will! :-)

**Comment by arfon** [comment]
> Ok I will! :-)

Wonderful, thanks!

**Comment by arfon** [comment]
@whedon assign @masalmon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @masalmon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/100. Feel free to close this issue now!

**Comment by arfon** [comment]
@masalmon - let's continue the review over in #100

**Comment by noamross** [comment]
May I volunteer as a second reviewer for this? I watch the submissions feed for rOpenSci pass-throughs and this one interests me.

**Comment by pboesu** [comment]
Thanks for you interest @noamross (And of course thanks for agreeing to review @masalmon)

I briefly considered rOpenSci for this, but felt it was in the "standalone statistical tools" category. I'd be more than happy to have a shot in making this compliant with the onboarding criteria, though, if you both think this would fit into the rOpenSci ecosystem!

**Comment by noamross** [comment]
Hi @pboesu.  I was just telling @arfon that I'm watching this repo to track packages going from RO to JOSS through our joint submittal approach.  You are correct, rucrdtw wouldn't fit in the rOpenSci scope.  I just have done some time series stuff and thought I'd take the chance to explore DTW more deeply by reviewing your package.

**Comment by arfon** [comment]
> May I volunteer as a second reviewer for this? I watch the submissions feed for rOpenSci pass-throughs and this one interests me.

Absolutely. Please feel free to also contribute your review over in #100 @noamross
