### ISSUE TITLE
[REVIEW]: Pyoints: A Python package for point cloud, voxel and raster processing.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#990]
**Submitting author:** @laempy (<a href="http://orcid.org/0000-0002-8963-2762">Sebastian Lamprecht</a>)
**Repository:** <a href="https://github.com/laempy/pyoints" target ="_blank">https://github.com/laempy/pyoints</a>
**Version:** v0.2.0rc3
**Editor:** @lheagy
**Reviewer:** @kbevers, @scivision
**Archive:** <a href="https://doi.org/10.5281/zenodo.2619945" target="_blank">10.5281/zenodo.2619945</a>

## Status

[![status](http://joss.theoj.org/papers/74503e9ec493adc91fc43e47b82a2e8e/status.svg)](http://joss.theoj.org/papers/74503e9ec493adc91fc43e47b82a2e8e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/74503e9ec493adc91fc43e47b82a2e8e"><img src="http://joss.theoj.org/papers/74503e9ec493adc91fc43e47b82a2e8e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/74503e9ec493adc91fc43e47b82a2e8e/status.svg)](http://joss.theoj.org/papers/74503e9ec493adc91fc43e47b82a2e8e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/laempy/pyoints" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kbevers & @scivision, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/laempy/pyoints">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0a2)?
- [x] **Authorship:** Has the submitting author (@laempy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/laempy/pyoints">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.2.0a2)?
- [x] **Authorship:** Has the submitting author (@laempy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kbevers, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00990/joss.00990/10.21105.joss.00990.pdf)

**Comment by lheagy** [comment]
Many thanks @kbevers and @scivision for being willing to review! In the main comment thread above, there is a checklist to help guide your reviews. If possible, I would greatly appreciate if you can do your review within the next 2 weeks. Please let me know if you have any questions or if I can provide any clarification.

**Comment by lheagy** [comment]
Just checking in. Thanks @kbevers, @scivision for creating the issues. @laempy, please keep us posted on your progress addressing these

**Comment by laempy** [comment]
Thank you very much for reviewing my package. I have addressed issues 3 to 4 have. I am currently try to solve issue 2. I will push my changes altogether as soon as possible.

**Comment by scivision** [comment]
@lheagy FYI I am quite tied up on other projects till approx. Nov 15th. If this is an issue someone else can review in the meantime. Sorry about that, this is an interesting project.

**Comment by lheagy** [comment]
Hi @scivision: thanks for the heads-up! I don't think this should be a problem. 
@laempy: please keep us updated on your progress and let us know when to do another pass. Thanks!

**Comment by laempy** [comment]
Hello @Iheagy, I have addressed the issues and published a new version 0.2.0a3 to re-review. I have added some comments on each issue.
Next to some minor revisions I have enabled conda installation as suggested by @kbevers. Unfortunately this took much more time than expected. Currently win-64 and linux-64 packages are provided. The installation instructions have been adapted accordingly. In addition a CONTRIBUTING.md file has been added.

**Comment by kbevers** [comment]
The changes looks good to me and I have ticked some more boxes above. I most likely won't have time to do a proper test of the code within the next week or two. It does seem to be significantly easier to get started now, good job on that!

**Comment by lheagy** [comment]
:wave: Hi @scivision: would you have time to take another look through the software? Thanks!

**Comment by lheagy** [comment]
👋 Hi @scivision: Would you be willing to take a look through the software? If so, when do you think you will have time to do the review? Thank you!

**Comment by lheagy** [comment]
👋 Hi @kbevers, would you have time in the next week or so to jump back in and take a look at the unchecked functionality boxes?

**Comment by lheagy** [comment]
Many thanks @kbevers!

**Comment by kbevers** [comment]
I have now succesfully installed the software, ran the test-suite and confirmed that the package indeed does what it says on the tin. A minor issue in the test suite was found and reporting in https://github.com/laempy/pyoints/issues/7. This is not a blocker for publication but would be nice see fixed in a future release.

As I am working no an unsupported platform (OS X) I did have some trouble installing the package but in the end I managed to make it work.  I have not tested on a supported platform but I have no reason to believe it doesn't work there.

**Comment by laempy** [comment]
Thanks a lot @kbevers. I have fixed issue laempy/pyoints#7. Since this was just a minor issue, I will push a new version after the review of @scivision.

**Comment by lheagy** [comment]
@laempy: I have not heard anything from @scivision, so I will jump in and complete his review later this week

**Comment by lheagy** [comment]
Hi @laempy: overall, this is looking good! I just have a few comments with respect to the installation and including easy pointers to an example (preferably with a plot) in the README and / or documentation. I have outlined these in issues 8, 9, and 10. Please ping when you have addressed these and I can take another look.

**Comment by laempy** [comment]
@lheagy thank you very much for these suggestions. I will take a look at the details as soon as possible. Regarding the installation issue: In the README is a typo. `conda install -c laempy pyoints` should work.

**Comment by lheagy** [comment]
Hi @laempy, just checking in to see how things are going. Please comment here when you have addressed the issues I outlined and I can take another look then.

**Comment by laempy** [comment]
Hi @lheagy. I have addressed the open issues and created a new version v0.2.0b1. Could you please take a second look? Unfortunately I wasn't able to create a new conda package yet, but I will do that as soon as I find enough time. In consequence, currently the package needs to be installed from source according to the README.

**Comment by lheagy** [comment]
@whedon make pdf

**Comment by lheagy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00990/joss.00990/10.21105.joss.00990.pdf)

**Comment by lheagy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1109/ICRA.2011.5980567 is OK
- http://doi.org/10.3390/rs9050505 is OK
- http://doi.org/10.3390/rs70809975 is OK

MISSING DOIs

- https://doi.org/10.1109/mra.2009.933612 may be missing for title: The OpenCV Library
- https://doi.org/10.1109/cvpr.2018.00409 may be missing for title: Open3D: A Modern Library for 3D Data Processing

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
👋 Hi @laempy, thanks for your changes - I really like the tutorials you added. Just one outstanding item from my perspective, that is the doi's mentioned above (laempy/pyoints#8). Would you mind taking a look and see if those are appropriate to add to the paper? 

@kbevers, @scivision, thanks for your efforts on the review. Would you like to take a look at the revisions and add any final comments?

**Comment by kbevers** [comment]
@lheagy It looks good to me.

**Comment by lheagy** [comment]
👋 @laempy: could you please make a new release, archive the software on [zenodo](http://zenodo.org) or similar and post the doi here?

**Comment by laempy** [comment]
@lheagy and @kbevers thanks a lot! I am going to take a look at the DOIs and I will create a new release as soon as possible.

**Comment by laempy** [comment]
@lheagy: I have taken a look at the DOIs (see laempy/pyoints#8) and created a new release **0.2.0rc2** with DOI 10.5281/zenodo.2582977 (or 10.5281/zenodo.2557574 for citing all versions). I have noticed, that the PDF file created by whedon is based on an old version of the package. So, it needs to be regenerated for proof reading.
After several problems with the conda recipe I had to drop Windows support. So I have created conda packages for linux only. But, the manual conda installation should still work (tested with win7, 64-bit).

**Comment by laempy** [comment]
Hi @lheagy and @kbevers, I have found some remaining issues. So, I created the release **0.2.0rc3** with DOI 10.5281/zenodo.2585430. Could you please take another look? Thanks a lot.

**Comment by lheagy** [comment]
@whedon set 10.5281/zenodo.2585430 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2585430" target="_blank">10.5281/zenodo.2585430</a> is the archive.

**Comment by lheagy** [comment]
Thanks @laempy, can you please update the zenodo record so that the title and author list are the same as they are on your paper?

**Comment by lheagy** [comment]
👋 Hi @laempy, just checking in - would you mind updating the zenodo archive record so that the title and author list are the same as on the paper?

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00990/joss.00990/10.21105.joss.00990.pdf)

**Comment by laempy** [comment]
Hi @whedon, I have updated the zenodo record accordingly.

**Comment by lheagy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2557574 is OK
- 10.1109/ICRA.2011.5980567 is OK
- 10.3390/rs9050505 is OK
- 10.3390/rs70809975 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
:wave: @openjournals/joss-eics: This submission is ready to be accepted!  

Congratulations @laempy  🎉

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by danielskatz** [comment]
(there will now be a few hour pause in the processing...)

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/591

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/591, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2557574 is OK
- 10.1109/ICRA.2011.5980567 is OK
- 10.3390/rs9050505 is OK
- 10.3390/rs70809975 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @laempy - I've suggested a bunch of changes in the paper text in https://github.com/laempy/pyoints/pull/12 - please make whichever of them you think are useful.  Most are to make the English more idiomatic, some are spelling and grammar fixes as well.

**Comment by laempy** [comment]
Thank you @lheagy for accepting my paper. @danielskatz - Thank you for the suggestions in laempy/pyoints#12. I am going to add your modifications and create the final release. I will post the corresponding zenodo DOI here as soon as possible.

**Comment by laempy** [comment]
The new zenodo DOI is 10.5281/zenodo.2619945

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.2619945 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2619945" target="_blank">10.5281/zenodo.2619945</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #990 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    168      0 --:--:-- --:--:-- --:--:--   170
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00990.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2557574 is OK
- 10.1109/ICRA.2011.5980567 is OK
- 10.3390/rs9050505 is OK
- 10.3390/rs70809975 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00990/joss.00990/10.21105.joss.00990.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #990 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
👋 @arfon - something's wrong here - can you help?

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2557574 is OK
- 10.1109/ICRA.2011.5980567 is OK
- 10.3390/rs9050505 is OK
- 10.3390/rs70809975 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @arfon - ping - help needed...

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2557574 is OK
- 10.1109/ICRA.2011.5980567 is OK
- 10.3390/rs9050505 is OK
- 10.3390/rs70809975 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/601

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/601, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/602
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00990](https://doi.org/10.21105/joss.00990)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
@laempy sorry for the delays - Our bot @whedon was acting up, but seems to be ok again...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00990/status.svg)](https://doi.org/10.21105/joss.00990)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00990">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00990/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00990/status.svg
   :target: https://doi.org/10.21105/joss.00990
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00990/status.svg)](https://doi.org/10.21105/joss.00990)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by laempy** [comment]
Great! Thanks a lot!
