### ISSUE TITLE
[PRE REVIEW]: SWEpy: A Python Library for Quick and Easy Access and Manipulation of MEaSUREs CETB files for SWE analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#993]
**Submitting author:** @wino6687 (<a href="http://orcid.org/0000-0002-6772-9600">will norris</a>)
**Repository:** <a href="https://github.com/wino6687/SWEpy" target ="_blank">https://github.com/wino6687/SWEpy</a>
**Version:** v1.1.5
**Editor:** @arfon
**Reviewers:** @usethedata

**Author instructions**

Thanks for submitting your paper to JOSS @wino6687. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wino6687 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #993 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    235      0 --:--:-- --:--:-- --:--:--   238
Error reading bibliography ./paper.bib (line 8, column 1):
unexpected end of input
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by wino6687** [comment]
I had an extra '{ ' in my bib file. I have pushed a fix to the repo. Is there a way to trigger @whedon to compile it again? Thanks!

**Comment by wino6687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00993/joss.00993/10.21105.joss.00993.pdf)

**Comment by wino6687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00993/joss.00993/10.21105.joss.00993.pdf)

**Comment by wino6687** [comment]
@Chilipp would you be willing to do this review? I noticed you have experience working with climate data, and possibly remotely sensed stuff. Maybe this would be a good fit? Thanks!

**Comment by wino6687** [comment]
Hi @krischer, @usethedata, your backgrounds seems well suited for reviewing this library/paper. Do either of you have time to do this review? Thanks!

**Comment by arfon** [comment]
@lheagy - would you be able to edit this submission for JOSS?

**Comment by usethedata** [comment]
@wino6687 Sorry I missed the notification 3 days ago.  Yes, I'll take a crack at this.  It will be the first one I've done, so some instructions on the mechanics will be useful.

**Comment by wino6687** [comment]
Hi @usethedata, thanks for agreeing to do this review. I believe once an editor is assigned there will be a check list here in the issue, but this is my first submission so I am not 100% on that. I do see that other recent submissions that have assigned editors and reviewers have the check list locally in the issue.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by usethedata** [comment]
I'm going off https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and https://joss.readthedocs.io/en/latest/review_criteria.html.  That will at least be a start, I'm sure folks will let me know if I miss anything.

**Comment by arfon** [comment]
@whedon assign @usethedata as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @usethedata

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1018. Feel free to close this issue now!

**Comment by arfon** [comment]
@usethedata - many thanks for agreeing to review this submission! Please head over to #1018 to carry out the review - the checklist is there for you :-)

**Comment by lheagy** [comment]
Hey @arfon, sorry for my late reply! I am happy to take this if your plate is full - please let me know what works.
