### ISSUE TITLE
[PRE REVIEW]: rIP: An R package for tracing IP addresses and detecting likely responses from server farms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#995]
**Submitting author:** @pdwaggoner (<a href="http://orcid.org/0000-0002-7825-7573">Philip D. Waggoner</a>)
**Repository:** <a href="https://github.com/MAHDLab/rIP" target ="_blank">https://github.com/MAHDLab/rIP</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @pdwaggoner. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pdwaggoner if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00995/joss.00995/10.21105.joss.00995.pdf)

**Comment by pdwaggoner** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00995/joss.00995/10.21105.joss.00995.pdf)

**Comment by pdwaggoner** [comment]
@leeper , we suggest any of the following people as potential reviewers for our paper: @mariacuellar @cimentadaj or @benmarwick . However, we certainly defer to whatever you think is best. Thanks!

**Comment by arfon** [comment]
Hi @pdwaggoner. Thanks for your submission to JOSS. Unfortunately this submission isn't allowed in JOSS as it falls into our ['minor utility'](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) category.
