### ISSUE TITLE
[PRE REVIEW]: Pingouin: statistics in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#999]
**Submitting author:** @raphaelvallat (<a href="http://orcid.org/0000-0003-1779-7653">Raphael Vallat</a>)
**Repository:** <a href="https://github.com/raphaelvallat/pingouin" target ="_blank">https://github.com/raphaelvallat/pingouin</a>
**Version:** v0.1.10
**Editor:** @cMadan
**Reviewers:** @snastase

**Author instructions**

Thanks for submitting your paper to JOSS @raphaelvallat. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@raphaelvallat if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00999/joss.00999/10.21105.joss.00999.pdf)

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
Hi @raphaelvallat! I'm happy to be editor for this submission. It looks like your submission is generally in order, though you can remove the `Citations to entries in paper.bib should be in rMarkdown format.` from the paper.

Do you have any suggestions for reviewers for this submission?

**Comment by raphaelvallat** [comment]
Hi @cMadan! Thank you for accepting to be the editor! 

I just re-generated the PDF without the "Citation" part. I think that these reviewers would be a great fit:
- snastase
- nhejazi
- kellieotto

**Comment by raphaelvallat** [comment]
Hi @cMadan! 
Just released version 0.1.10 of Pingouin, is it possible to update the review to this version?
Thank you - Raphael

**Comment by cMadan** [comment]
@raphaelvallat, that's not a problem. I've updated the version number in the initial comment.

@snastase @nhejazi @kellieotto, would you be available and interested to review this submission? Thanks for considering!

**Comment by snastase** [comment]
@cMadan I should be able to help out. A bit overloaded right now, but should be able to get to it soon (< 1 week).

**Comment by cMadan** [comment]
@snastase, great, thank you! I will wait to see if anyone else is interested in also reviewing, and will start the review process early next week.

**Comment by kellieotto** [comment]
I'm in the thick of another review right now. I will pass on this one.

**Comment by nhejazi** [comment]
I'm also quite busy with reviews at the present. Happy to provide a review at a later date if necessary.

**Comment by cMadan** [comment]
@kellieotto, no problem, thank you for considering!

@nhejazi, sounds good. I'll go ahead and start the review, but feel free to take a look at the submission if you have time. (Or, I may ask again if it looks like an additional perspective seems necessary.)

**Comment by cMadan** [comment]
@whedon add @snastase as reviewer

**Comment by whedon** [comment]
OK, @snastase is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1026. Feel free to close this issue now!
